### ISSUE TITLE
Properly version the Python SDK

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#1000]
Currently the Python SDK always has version 0.1.
The user does not know which version do they have installed. Package manager can be confused by same versions.

We need to add proper version to `setup.py` when building the SDK.

We could make CLoudBuild write the release version to the `VERSION` file in the package and make setup.py read the version from that file.

**Comment by vicaire** [comment]
Could you please provide more details on what needs to be done?

**Comment by Ark-kun** [comment]
> Could you please provide more details on what needs to be done?

Done.

**Comment by vicaire** [comment]
Thank you. Increasing the priority since that seems quite important.

**Comment by vicaire** [comment]
@Ark-kun, can we close this one?

**Comment by Ark-kun** [comment]
Currently the version is updated manually, but at least it's being updated.
