### ISSUE TITLE
[feature] Set Simplify Graph as the default behaviour in the kubeflow UI

### ISSUE THREAD

**Issue by kavita1205** [kubeflow/pipelines#10045]
### Feature Area -Kubeflow UI

 Kubeflow UI

### What feature would you like to see?
Hi Team,
We want to see Simply graph as the default behaviour in the kubeflow UI. 
Please let us know if it is possible to set the above requirement.
Thanks,
Kavita

### Is there a workaround currently?

---

Love this idea? Give it a 👍.

**Comment by kavita1205** [comment]
@zijianjoy Do we have any update over it?

**Comment by zijianjoy** [comment]
Hello @kavita1205 , we currently don't see this feature request attract many attention. Nor do we think that simplied Workflow Graph by default is going to be beneficial for user understanding the workflow. I keep this issue open to wait for community attention.
