### ISSUE TITLE
[feature] Support Kustomize 5

### ISSUE THREAD

**Issue by midhun1998** [kubeflow/pipelines#10053]
### Feature Area

/area manifests 

### What feature would you like to see?
Currently, The manifest produce the following deprecated warnings when using the Kustomize version 5+. 
```
# Warning: 'vars' is deprecated. Please use 'replacements' instead. [EXPERIMENTAL] Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'bases' is deprecated. Please use 'resources' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'patchesJson6902' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
```
This is part of the effort mentioned in the issue https://github.com/kubeflow/manifests/issues/2388 

---

Love this idea? Give it a 👍.

**Comment by juliusvonkohout** [comment]
@midhun1998 https://github.com/kubeflow/pipelines/pull/10087 is a WIP

**Comment by juliusvonkohout** [comment]
no stalebot, it is still very relevant.
