### ISSUE TITLE
Default S3 compatible provider in metadata writer

### ISSUE THREAD

**Issue by nagar-ajay** [kubeflow/pipelines#10085]
Hi Team,

For the provider part, in the [artifact storage URI](https://github.com/kubeflow/pipelines/blob/master/backend/metadata_writer/src/metadata_writer.py#L106-L113) function of metadata writer module, we're checking if the endpoint is Amazon S3 compatible by [matching the endpoint](https://github.com/kubeflow/pipelines/blob/master/backend/metadata_writer/src/metadata_writer.py#L98) with `'^.*s3.*amazonaws.com.*$'`. If it matches we return the provider as S3 else the default is minio.

I think the default should be S3 not minio as there are many S3-compatible object store providers whose endpoint might not match with `'^.*s3.*amazonaws.com.*$'` regex.

cc @johnugeorge

**Comment by nagar-ajay** [comment]
Hi @zijianjoy, let me know how can I help you with more information.

**Comment by chensun** [comment]
> I think the default should be S3 not minio as there are many S3-compatible object store providers whose endpoint might not match with '^.*s3.*amazonaws.com.*$' regex.

I'm not sure how many users are using these S3-compatible object store, and how is the current logic affects them. 
I don't feel like there's enough justification for the making the behavior change which could affect existing users.
