### ISSUE TITLE
[feature]  Make `set_env_variable` compatible with the channels [KFP V2]

### ISSUE THREAD

**Issue by alexdashkov** [kubeflow/pipelines#10111]
### Feature Area

/area sdk

### What feature would you like to see?

I want to be able to use values from the parameters and/or outputs to set environment variables in KFP v2

### What is the use case or pain point?

I'm trying to pass a variable in the parameters of the job execution and then set it as a variable. 
Example: 
```python

@dsl.pipeline(name="useful-pipeline")
def training_pipeline(
    env: str = "dev",
):
    great_operator_op = great_operator().set_env_variable("env", env)
```

However current code raises an exception:
```python
TypeError: Cannot set ml_pipelines.PipelineDeploymentConfig.PipelineContainerSpec.EnvVar.value to {{channel:task=;name=env;type=String;}}: {{channel:task=;name=env;type=String;}} has type <class 'kfp.dsl.pipeline_channel.PipelineParameterChannel'>, but expected one of: (<class 'bytes'>, <class 'str'>) for field EnvVar.value
```

I've tried to pass trough the intermediate task to cast a type (it helped me with the similar situation to cast parameters types ) but it doesn't work neither. 

```python
@dsl.component()
def convert_env_to_string(environment: str) -> str:
    return environment

@dsl.pipeline(name="useful-pipeline")
def training_pipeline(
    env: str = "dev",
):
    convert_env_to_string_op = convert_env_to_string(environment=env)
    great_operator_op = great_operator().set_env_variable("env", convert_env_to_string_op.output)
```
```python
TypeError: Cannot set ml_pipelines.PipelineDeploymentConfig.PipelineContainerSpec.EnvVar.value to {{channel:task=convert-env-to-string;name=Output;type=String;}}: {{channel:task=convert-env-to-string;name=Output;type=String;}} has type <class 'kfp.dsl.pipeline_channel.PipelineParameterChannel'>, but expected one of: (<class 'bytes'>, <class 'str'>) for field EnvVar.value

```
### Is there a workaround currently?
It's possible to don't use an environment at all, but it's not really a workaround. 

---

Love this idea? Give it a 👍.

**Comment by Davidnet** [comment]
As an alternative, would you consider to pass as a parameter to `great_operator` instead?

**Comment by alexdashkov** [comment]
Hi @Davidnet, yes. I should have been more clear. That's exactly what I meant by `don't use an environment at all`.  This solution works and I'll use it. But still I have to move out from the environment variables. I can imagine even deeper solution by passing this value as a param and then, inject it using for example `environ` but it looks really hackish. 

```python
@dsl.component()
def convert_env_to_string(env: str) -> str:
    import os
    os.environ["env"] = env
    # rest of the code

@dsl.pipeline(name="useful-pipeline")
def training_pipeline(
    env: str = "dev",
):
    great_operator_op = great_operator(env=env)
```

**Comment by ViktorWelbers** [comment]
Hi, 
I am also struggling with this. 

I am using the env variables to set the image to a dynamic version inside of the components like so:

```python

@dsl.component(
    base_image=os.environ.get("BASE_IMAGE"),
)
def some_op(foo: str):
...


@dsl.pipeline(name="useful-pipeline")
def training_pipeline(
    base_image: str = "IMAGE_ID"
):
  op = (
       some_op(
            foo=bar.outputs["scaling_factor"],
        )
        .set_env_variable(name="BASE_IMAGE", value=base_image)
    )
```

Is there any alternatives? Otherwise I would like to work maybe help out on implementing this feature.

**Comment by alexdashkov** [comment]
@ViktorWelbers , are you sure that you're looking for the same feature? If you want it to fill `base_image` for your component only, you should provide this variable during pipeline compilation, not in runtime.

Something like that: 

```python
import os
BASE_IMAGE = =os.environ.get("BASE_IMAGE")

@dsl.component(
    base_image=BASE_IMAGE
)
def some_op(foo: str):
    ...


@dsl.pipeline(name="useful-pipeline")
def training_pipeline(
    base_image: str = "IMAGE_ID"
):
  op = (
       some_op(
            foo="bar",
        )
    )
```

From my understanding, `base_image` from the `dsl.component` won't be accessible at runtime even if you would have a possibility to set env variable from the parameters. 
So if you really want to change an image from parameters I guess you should go trough the container component. 
Something like that: 
```python
from kfp import dsl

@dsl.container_component
def some_op(foo:str, base_image: str):
    return dsl.ContainerSpec(image=base_image, command=['echo'], args=[foo])
    
@dsl.pipeline(name="useful-pipeline")
def training_pipeline(
    base_image: str = "IMAGE_ID"
):
  op = (
       some_op(
            foo="bar",
            base_image=base_image
        )
    )
```

**Comment by ViktorWelbers** [comment]
@alexdashkov 

You are totally correct. I think the second option you posted is what I was looking for.
Thank you.

**Comment by fw8** [comment]
Same problem with
```
kubernetes.use_secret_as_env(task, secret_name=secret_name_from_pipeline_args,...)
```

**Comment by alexdashkov** [comment]
A comment to remove `stale` label.

**Comment by beoygnas** [comment]
Hi, I struggled with this problem, but I think I found a way.

You can use `value` field of  params (or outputs).

Something like that : 
``` python
@dsl.pipeline(name="useful-pipeline")
def training_pipeline(
    env: str = "dev",
):
    great_operator_op = great_operator().set_env_variable("env", env.value)
```

`set_env_variable()` needs string value, but dsl parameters and outputs are `kfp.dsl.pipeline_channel.PipelineParameterChannel`. And `kfp.dsl.pipeline_channel.PipelineParameterChannel` provides its  actual string value of the pipline channel by `value` attributes.

**Comment by alexdashkov** [comment]
@beoygnas Where do you run your pipeline? Do you have an on-premise kubeflow instance? 
I'm using GCP's vertex ai pipelines and it does not pass there. I can compile a pipeline, but then an executor fails. 
```
com.google.cloud.ai.platform.common.errors.AiPlatformException: code=INVALID_ARGUMENT, message=List of found errors: 1.Field: job_spec.worker_pool_specs[0].container_spec.env[0].value; Message: Required field is not set. , cause=null; Failed to create custom job for the task. 
```
