### ISSUE TITLE
[sdk] With SDK > 2.0.1, python containerized components don't work on Vertex Pipelines

### ISSUE THREAD

**Issue by juansebashr** [kubeflow/pipelines#10122]
### Environment

*  KFP version: NA
*  KFP SDK version: Greater than 2.0.1

### Steps to reproduce

I try to upgrade the version of KFP on some projects due to the latest cool changes, but when I compiled a big pipeline and ran it in vertex, I noticed that all the Python containerized components broke, and all of them due to the same problem
`/usr/local/bin/python3: No module named kfp.dsl.executor_main`
![image](https://github.com/kubeflow/pipelines/assets/26184787/a88eb73a-77f9-4f72-98a4-5f43aa6fc7df)

I've tried with kfp==2.3.0, 2.2.0 and 2.1.3, apparently in PyPi the 2.1.2 and 2.1.1 are yanked, finally works with the version 2.0.1

I did not change a single comma on the code; I recompiled the components with the specific kfp version that I was testing, and still nothing
### Expected result

The Python containerized components should work fine on Vertex Pipelines

Impacted by this bug? Give it a 👍.

**Comment by juansebashr** [comment]
Ohh I found the reason why they broke, apparently on the older version when compiling the component kfp was automatically installed without specifically putting it on the component packages_to_install, this changes on the newer versions. But this is the wanted behavior?

**Comment by chensun** [comment]
@juansebashr KFP SDK 2.3.0 should work. Can you please share your component code, especially what you have in the component decorator?

**Comment by juansebashr** [comment]
@chensun This is one example of the components that was failing

```python

import os
from pathlib import Path
from typing import NamedTuple

from kfp.dsl import component


def get_requirements():
    """
    Get a list of requirements from requirements.txt

    Returns:
        requirements (list): List of requirements
    """
    # Get the requirements file and read it line by line, save this into a list
    req_path = os.path.join(Path(__file__).parent, "requirements.txt")
    with open(req_path, "r") as file:
        content = file.read()

    lines = content.splitlines()
    requirements = [line for line in lines if line and not line.startswith("#")]

    return requirements


@component(
    base_image="python:3.10",
    target_image="gcr.io/autonomy-286821/kfp-server-client:latest",
    packages_to_install=get_requirements(),
)
def model_ingestion(
    model_type: str,
    model_version: str,
    url_server: str,
    env: str,
) -> NamedTuple("outputs", torch_url=str, model_info=dict, label_map=dict):
    """
    Get the appropriate model from the deployment server and returns the URI of the model
    in GCS

    Args:
        model_type (str): Type of the model to download, if not empty, will download
        the last version of the model type
        model_version (str): Version of the model to download
        url_server (str): URL of the deployment server
        env (str): Environment of the model

    Returns:
        outputs (NamedTuple): NamedTuple with 3 fields:
            torch_url (str): URI of the model in GCS
            model_info (dict): Dictionary with the model information
            label_map (dict): Dictionary with the label map of the model
    """
    # Imports
    from utils import request_model_info
   # Rest of the code, is a simple HTTP request
```

And this was the requirements.txt file
```
requests==2.28.2
requests-oauthlib==1.3.1
requests-toolbelt==0.10.1
google-api-core==2.11.0
google-api-python-client==2.82.0
google-auth==2.16.2
google-cloud-core==2.3.2
```

After add the kfp==2.3.0 on the requirements, it works

**Comment by droctothorpe** [comment]
Does a pipeline deployed with kfp v2 require kfp v2 to be deployed on its components? I'm running into `No module named kfp.dsl.executor_main` when using v2 to create a run that includes a component that has kfp v1 on it.

**Comment by juansebashr** [comment]
@droctothorpe yes it does, the kfp version of the compilation should be the same of the component
