### ISSUE TITLE
Users should be able to add metadata to component.yaml

### ISSUE THREAD

**Issue by animeshsingh** [kubeflow/pipelines#1013]
currently it appears components are checked for exact match on the schema, but this can be made extensible by giving an option to pass addition attributes etc which a user may define, which is not exactly used by pipeline subsystem, but can be information which an entity can use to display things  e.g. link to logo etc...

**Comment by Ark-kun** [comment]
I think that having a strict schema is important and the general structure needs to be fixed, so th the components are portable and we can maintain backwards compatibility.

But.

I think that the cases you've mentioned can be covered by adding the `metadata` section to the component.yaml

In keeping it similar to kubernetes and Argo, we can have `annotations` and `labels` inside.

Would that fit your needs?

**Comment by Ark-kun** [comment]
Check the https://github.com/kubeflow/pipelines/pull/1023 PR and /lgtm if it fulfills your need.
