### ISSUE TITLE
[bug] pip install kfp==1.8.20 fails

### ISSUE THREAD

**Issue by philop1309** [kubeflow/pipelines#10172]
### Environment

python3.10

*  How do you deploy Kubeflow Pipelines (KFP)?

*  KFP version:

*  KFP SDK version:

### Steps to reproduce

Run `pip install kfp==1.8.20`

Getting pyyaml install error 

`> [2/2] RUN pip install kfp==1.8.20:                                                                                                           
#5 0.479 WARNING: The directory '/home/ray/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.                  
#5 0.992 Collecting kfp==1.8.20
#5 1.107   Downloading kfp-1.8.20.tar.gz (304 kB)
#5 1.174      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 304.8/304.8 kB 4.8 MB/s eta 0:00:00
#5 1.230   Preparing metadata (setup.py): started
#5 1.502   Preparing metadata (setup.py): finished with status 'done'
#5 1.523 Requirement already satisfied: absl-py<2,>=0.9 in ./anaconda3/lib/python3.10/site-packages (from kfp==1.8.20) (1.4.0)
#5 1.628 Collecting PyYAML<6,>=5.3 (from kfp==1.8.20)
#5 1.653   Downloading PyYAML-5.4.1.tar.gz (175 kB)
#5 1.663      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 kB 25.3 MB/s eta 0:00:00
#5 1.811   Installing build dependencies: started
#5 8.080   Installing build dependencies: finished with status 'done'
#5 8.081   Getting requirements to build wheel: started
#5 8.287   Getting requirements to build wheel: finished with status 'error'
#5 8.294   error: subprocess-exited-with-error
#5 8.294   
#5 8.294   × Getting requirements to build wheel did not run successfully.
#5 8.294   │ exit code: 1
#5 8.294   ╰─> [62 lines of output]
#5 8.294       /tmp/pip-build-env-l0d9ycv_/overlay/lib/python3.10/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
#5 8.294       !!
#5 8.294       
#5 8.294               ********************************************************************************
#5 8.294               The license_file parameter is deprecated, use license_files instead.
#5 8.294       
#5 8.294               By 2023-Oct-30, you need to update your project and remove deprecated calls
#5 8.294               or your builds will no longer be supported.
#5 8.294       
#5 8.294               See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
#5 8.294               ********************************************************************************
#5 8.294       
#5 8.294       !!
#5 8.294         parsed = self.parsers.get(option_name, lambda x: x)(value)
#5 8.294       running egg_info
#5 8.294       writing lib3/PyYAML.egg-info/PKG-INFO
#5 8.294       writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
#5 8.294       writing top-level names to lib3/PyYAML.egg-info/top_level.txt
#5 8.294       Traceback (most recent call last):
#5 8.294         File "/home/ray/anaconda3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
#5 8.294           main()
#5 8.294         File "/home/ray/anaconda3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
#5 8.294           json_out['return_val'] = hook(**hook_input['kwargs'])
#5 8.294         File "/home/ray/anaconda3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
#5 8.294           return hook(config_settings)
#5 8.294         File "/tmp/pip-build-env-l0d9ycv_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
#5 8.294           return self._get_build_requires(config_settings, requirements=['wheel'])
#5 8.294         File "/tmp/pip-build-env-l0d9ycv_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
#5 8.294           self.run_setup()
#5 8.294         File "/tmp/pip-build-env-l0d9ycv_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in run_setup
#5 8.294           exec(code, locals())
#5 8.294         File "<string>", line 271, in <module>
#5 8.294         File "/tmp/pip-build-env-l0d9ycv_/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
#5 8.294           return distutils.core.setup(**attrs)
#5 8.294         File "/tmp/pip-build-env-l0d9ycv_/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
#5 8.294           return run_commands(dist)
#5 8.294         File "/tmp/pip-build-env-l0d9ycv_/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
#5 8.294           dist.run_commands()
#5 8.294         File "/tmp/pip-build-env-l0d9ycv_/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
#5 8.294           self.run_command(cmd)
#5 8.294         File "/tmp/pip-build-env-l0d9ycv_/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
#5 8.294           super().run_command(command)
#5 8.294         File "/tmp/pip-build-env-l0d9ycv_/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
#5 8.294           cmd_obj.run()
#5 8.294         File "/tmp/pip-build-env-l0d9ycv_/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 318, in run
#5 8.294           self.find_sources()
#5 8.294         File "/tmp/pip-build-env-l0d9ycv_/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 326, in find_sources
#5 8.294           mm.run()
#5 8.294         File "/tmp/pip-build-env-l0d9ycv_/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 548, in run
#5 8.294           self.add_defaults()
#5 8.294         File "/tmp/pip-build-env-l0d9ycv_/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 586, in add_defaults
#5 8.294           sdist.add_defaults(self)
#5 8.294         File "/tmp/pip-build-env-l0d9ycv_/overlay/lib/python3.10/site-packages/setuptools/command/sdist.py", line 113, in add_defaults
#5 8.294           super().add_defaults()
#5 8.294         File "/tmp/pip-build-env-l0d9ycv_/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
#5 8.294           self._add_defaults_ext()
#5 8.294         File "/tmp/pip-build-env-l0d9ycv_/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
#5 8.294           self.filelist.extend(build_ext.get_source_files())
#5 8.294         File "<string>", line 201, in get_source_files
#5 8.294         File "/tmp/pip-build-env-l0d9ycv_/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
#5 8.294           raise AttributeError(attr)
#5 8.294       AttributeError: cython_sources
#5 8.294       [end of output]
#5 8.294   
#5 8.294   note: This error originates from a subprocess, and is likely not a problem with pip.
#5 8.296 error: subprocess-exited-with-error
#5 8.296 
#5 8.296 × Getting requirements to build wheel did not run successfully.
#5 8.296 │ exit code: 1
#5 8.296 ╰─> See above for output.
#5 8.296 
#5 8.296 note: This error originates from a subprocess, and is likely not a problem with pip.`

### Labels

---

Impacted by this bug? Give it a 👍.

**Comment by zijianjoy** [comment]
Would you like to upgrade to latest 1.8 version? https://pypi.org/project/kfp/1.8.22/.  There might be issues with older version. cc @connor-mccarthy
