### ISSUE TITLE
[frontend] DAG status shows running even all sub-DAG are completed 

### ISSUE THREAD

**Issue by chensun** [kubeflow/pipelines#10175]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
KFP standalone/Kubeflow
*  KFP version: 
KFP 2.0.0-2.0.3

### Steps to reproduce
Run any pipeline with a DAG (parallelFor, condition, or pipeline as component, etc.)
![image](https://github.com/kubeflow/pipelines/assets/2043310/68ade5ce-4de8-4c62-902f-396db54eb4a3)

### Expected result

Expect DAG to show finished status when its children all finish.

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

**Comment by nikmodha** [comment]
/reopen 

We are facing this bug in our systems still

**Comment by nikmodha** [comment]
@chensun Hi, could you reopen this ticket? We are still seeing this in our production systems
