### ISSUE TITLE
Pass env vars to create_custom_training_job_from_component

### ISSUE THREAD

**Issue by jmmanso** [kubeflow/pipelines#10174]
### Feature Area

/area components

### What feature would you like to see?

I would like to add an `env_var` argument to the custom_job.utils.create_custom_training_job_from_component function, so that I can pass environment variables to my application container. 

### What is the use case or pain point?

When building pipeline components with this function, there is no way to pass environment variables to my container. It is weird that this function supports all other parts of the container spec, except "env". I wonder if this was just an oversight. 

### Is there a workaround currently?

I had to vendor and modify the code of create_custom_training_job_from_component. It's a super simple change, just add `env_vars` as argument and add this inside the function:

```python
 if env_vars:
        worker_pool_spec["container_spec"]["env"] = env_vars
```

---

Love this idea? Give it a 👍.

**Comment by pthieu** [comment]
@jmmanso did you find a workaround for this?

**Comment by jmmanso** [comment]
@pthieu  it actually got fixed at the source, thanks for following up
