### ISSUE TITLE
[backend] kubernetes properties not taken into account for caching

### ISSUE THREAD

**Issue by TobiasGoerke** [kubeflow/pipelines#10189]
### Environment

*  KFP version:
`2.0.3` (manifests v1.8 release)
*  KFP SDK version:
```
kfp                      2.4.0
kfp-kubernetes           1.0.0
kfp-pipeline-spec        0.2.2
kfp-server-api           2.0.3
```

### Steps to reproduce

In v1, volume mounts were taken into account for the cache key computation. 

In v2, this doesn't seem to happen, leading to inconsistent behavior.

Example: execute the following pipeline twice to create caches:

```python
from kfp import dsl
from kfp import kubernetes


@dsl.component
def test_step():
    print("Hello world")


@dsl.pipeline
def test_pipeline():
    create_pvc = kubernetes.CreatePVC(
        access_modes=["ReadWriteOnce"],
        size="10Mi",
    )
    task = test_step()
    kubernetes.mount_pvc(task, pvc_name=create_pvc.outputs["name"], mount_path="/test")


client.create_run_from_pipeline_func(test_pipeline, arguments={})
```

The second run will look like this: 
![image](https://github.com/kubeflow/pipelines/assets/13769461/5e8042ae-fabe-4034-afb4-c9d877a6eda8)

So, even though a new volume has been created and mounted by the succeeding step, the cache hasn't been invalidated. 

### Expected result

Compared to v1, we'd expect the cache to get evicted. 

Not sure if this is intended behavior for v2. If so, we'd need to work around this and pass the volume's name to the step, which wouldn't get used. 

---

Impacted by this bug? Give it a 👍.

**Comment by zijianjoy** [comment]
Would you like to share the KFP runtime version here? I think we have fixed it in the latest release.

/assign @chensun

**Comment by TobiasGoerke** [comment]
> Would you like to share the KFP runtime version here? I think we have fixed it in the latest release.
> 
> /assign @chensun

Edited the issue description. I'm on SDK 2.4.0 and backend 2.0.3
