### ISSUE TITLE
[feature] Kubeflow Pipeline V2 GPU node pool (with autoscale)

### ISSUE THREAD

**Issue by yonggunpeak** [kubeflow/pipelines#10191]
### Feature Area

import kfp
from kfp import dsl
from kfp.dsl import InputPath, OutputPath, component
import os

base_image = 'gcr.io/something/'

@component(base_image=base_image)
def all_in_one(bucket_name: str, download_folder_path: str, destination_folder_path: str, metrics_path: OutputPath('Metrics'), graph_path: OutputPath('PNG')):
    # ---- download_dataset ----
    import subprocess
    import os

    # ---- train_resnet50 ----
    import torch
    import torchvision
    import torchvision.transforms as transforms
    import torch.optim as optim
    import torch.nn as nn
    import torchvision.models as models
    import matplotlib.pyplot as plt
    
    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
   < my codes>
    model = models.resnet50(pretrained=True).to(device)

@dsl.pipeline(name='All-in-one Pipeline')
def pipeline( <my inputs>
): 
   
    all_in_one_op = all_in_one(bucket_name=bucket_name, download_folder_path=download_folder_path, destination_folder_path=destination_folder_path)

     # This is the part for KFv1 pipeline, but I don't see for V2. I need for V2
    all_in_one_op.add_node_selector_constraint('cloud.google.com/gke-accelerator', 'nvidia-tesla-t4')

if __name__ == '__main__':
    kfp.compiler.Compiler().compile(pipeline, 'V2_ML_allinone_GPU_1.yaml')

### What feature would you like to see?

For the Kubeflow pipeline V1, I see there is simple line that I can call my node.
I currently added node pool for V2 with autoscale min:0 ~ max:3. 
I wonder how to call the node to run on it for KFv2 pipeline. 
I think for KFv1 pipeline, it is like "task.set_accelerator_type('NVIDIA_TESLA_T4')"
curious how should I do for v2 for autoscaled nodes.

### What is the use case or pain point?

After I added additional node pools for current cluster with auto scale NVIDIA T4, I don't know how to run my component on that node with my docker image and codes.

### Is there a workaround currently?

I don't know. I don't want to deploy my kubeflow on GPU base machine on GCP. I wish to deploy on CPU base and just use autoscale with GPU node pools to save money. I need some solution.

Additional question, is there some quick guide that I can just run some tensorflow or pytorch code (like with cifar10) with all visualization and metrics with pipeline? I can't find any.
---

Love this idea? Give it a 👍.

**Comment by zijianjoy** [comment]
You can use node selector from kubernetes platform flags: [node selector](https://github.com/kubeflow/pipelines/blob/master/kubernetes_platform/proto/kubernetes_executor_config.proto#L112-L116).

The way to use kubernetes platform flags is documented in https://www.kubeflow.org/docs/components/pipelines/v2/platform-specific-features/.

Example of using node selector: https://github.com/kubeflow/pipelines/blob/d9c3b86adc4dc03beb623dc6ec8230347051200c/kubernetes_platform/python/test/snapshot/data/node_selector.py#L27


cc @chensun

**Comment by rimolive** [comment]
@yonggunpeak Did it work after following @zijianjoy suggestion?

**Comment by yonggunpeak** [comment]
Oh basically, I moved to vertex ai and figured differently. Thank you for
replyings

**Comment by rimolive** [comment]
No worries! I'm closing the issue, but free to reopen if the issue persists.

/close
