### ISSUE TITLE
[sdk] Metrics Visualization v2 test is broken

### ISSUE THREAD

**Issue by rimolive** [kubeflow/pipelines#10208]
Running `samples/test/metrics_visualization_v2.py` pipeline test in my KFP environment, I got an error in the step `wine-classification`. The error is shown below:

```
I1106 16:26:46.396816      14 launcher_v2.go:692] ExecutorOutput: {"artifacts": {"metrics": {"artifacts": [{"name": "", "uri": "minio://mlpipeline/v2/artifacts/metrics-visualization-pipeline/c7e50972-ae4c-42ea-9327-9f55c6679f3c/wine-classification/metrics", "metadata": {"confidenceMetrics": [{"confidenceThreshold": Infinity, "recall": 0.0, "falsePositiveRate": 0.0}, {"confidenceThreshold": 1.0, "recall": 0.33962264150943394, "falsePositiveRate": 0.0}, {"confidenceThreshold": 0.9, "recall": 0.6037735849056604, "falsePositiveRate": 0.0}, {"confidenceThreshold": 0.8, "recall": 0.8490566037735849, "falsePositiveRate": 0.0}, {"confidenceThreshold": 0.6, "recall": 0.8867924528301887, "falsePositiveRate": 0.0}, {"confidenceThreshold": 0.5, "recall": 0.9245283018867925, "falsePositiveRate": 0.0125}, {"confidenceThreshold": 0.4, "recall": 0.9622641509433962, "falsePositiveRate": 0.075}, {"confidenceThreshold": 0.3, "recall": 1.0, "falsePositiveRate": 0.0875}, {"confidenceThreshold": 0.2, "recall": 1.0, "falsePositiveRate": 0.2375}, {"confidenceThreshold": 0.1, "recall": 1.0, "falsePositiveRate": 0.475}, {"confidenceThreshold": 0.0, "recall": 1.0, "falsePositiveRate": 1.0}]}}]}}}
I1106 16:26:46.418131      14 launcher_v2.go:151] publish success.
F1106 16:26:46.418156      14 main.go:49] failed to execute component: failed to unmarshall ExecutorOutput in file "/tmp/kfp_outputs/output_metadata.json": proto: syntax error (line 1:252): invalid value Infinity
```

It turns out that one of the points to produce the ROC Curve visualization is set to `Infinity`. Since it uses `scikit-learn` library, it is suppose to produce that value. From [scikit-learn docs](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.roc_curve.html):

```
An arbitrary threshold is added for the case tpr=0 and fpr=0 to ensure that the curve starts at (0, 0). This threshold corresponds to the np.inf.
```
According to the [protobuf 3 documentation](https://protobuf.dev/programming-guides/proto3/#json), this value is accepted in case of a float type but it seems the issue is because `Infinity` is written to the JSON file without double quotes. The same case applies to `NaN` values.

### Environment

*  KFP version:
2.0.1
*  KFP SDK version: 
2.0.1
*  All dependencies version:
kfp                      2.4.0
kfp-pipeline-spec        0.2.2
kfp-server-api           2.0.3

### Steps to reproduce
* Build the IR yaml from `samples/test/metrics_visualization_v2.py` file
* Import to KFP and create a pipeline run

### Expected result
All pipeline steps run successfully with all artifacts available to visualize

### Materials and Reference
[scikit-learn docs](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.roc_curve.html)

Impacted by this bug? Give it a 👍.

**Comment by chensun** [comment]
We discussed this issue in the KFP community meeting this week. I think we lean to rely on user code to preprocess the data.
Keep the issue open for now for feedback.

**Comment by LorenzoColombi** [comment]
Has anyone found any possible workaround?

**Comment by rimolive** [comment]
@LorenzoColombi Thank you for the workaround. The issue not only affects `Infinity` values but `NaN` as well, so for this particular case you workaround looks good, but there are others we need to tackle.
