### ISSUE TITLE
[sdk] Update pydantic in kfp v1.8

### ISSUE THREAD

**Issue by caroline-paul99** [kubeflow/pipelines#10210]
### Feature Area

/area sdk

### What feature would you like to see?

Hello! I am from Capital One and we are using KFP version 1.8.22 in one of our main repos. With using that version, [it requires ](https://github.com/kubeflow/pipelines/blob/1.8.22/sdk/python/requirements.in#L39)`pydantic` verison <2. With some work that we are doing we need to use pydantic version >2. Therefore this version dependency is causing issues. When looking at the [pydantic documentation](https://docs.pydantic.dev/2.0/migration/#continue-using-pydantic-v1-features), users can install pydantic version 2 but still use all the features from version 1 by importing `from pydantic.v1 ...`. Thus we would like request this feature changes by:

1. Installing `pydantic 2.*` on KFP version 1.8.*
2. Change the import calls to `from pydantic.v1 ...` so that the code is still using v1 but us as users don't have the dependency

### What is the use case or pain point?

The use case for this feature would be to be able to use pydantic v2 with KFP 1.8.22 but not having any breaking changes to the code. 

### Is there a workaround currently?

The workaround currently is to use pydantic v1, however it does not have all the same capabilities of v2.

---

Love this idea? Give it a 👍.

**Comment by revolutionisme** [comment]
Is there an update on this, if not, I can give it a shot to update and contribute!

**Comment by rimolive** [comment]
pydantic dependency was removed in kubeflow pipelines 2.0.0-alpha.3

https://github.com/kubeflow/pipelines/blob/master/sdk/RELEASE.md?plain=1#L568

**Comment by revolutionisme** [comment]
@rimolive Unfortunately we are still using KFP V1 with KFP SDK 1.8.22 because of blockers we are facing with KFP V2 (With SDK V2) that's why it probably would make sense to update the pydantic version.

**Comment by rimolive** [comment]
Contributors are now working with v2 feature parity with v1 and adding new features, so v1 is not the focus.

It's recommended that you point out your blockers in a separate issue so we can prioritize accordingly and close this issue.

**Comment by revolutionisme** [comment]
I have pointed out some blockers in the past in respective issues and also raised some issues in the KFP community calls. At this point, they are either being worked on right now or are not a priority for now. Nevertheless, I thought I could contribute to this, but all good! ^_^

**Comment by rimolive** [comment]
I am responsible for Kubeflow 1.9 release. If you list the blocker issues, I can track and prioritize to have it available when 1.9 is out.

Other than that, I don't think it will be possible to fix old KFP SDK versions.

**Comment by rimolive** [comment]
Is there anything would you like to discuss?

**Comment by rimolive** [comment]
Closing this issue as there is no more activity. You can reopen it if the issue persists in latest release.

/close

**Comment by caroline-paul99** [comment]
Hi @rimolive is it possible to open this back up? Sorry for the late response here. The blockers for us is that:

- We are using an internal SDK that pins KFP version 1.8 and we can't change the version of KFP that is being used. That is why I opened this PR to KFP 1.8
- We need to be able to use pydantic 2.x

**Comment by rimolive** [comment]
/cc @connor-mccarthy @chensun 

There's another issue opened for that feature request https://github.com/kubeflow/pipelines/issues/10690. I'd advise you to add your comments in the new issue. Let's focus on a single issue and this one was created 2 weeks ago.

**Comment by caroline-paul99** [comment]
> /cc @connor-mccarthy @chensun
> 
> There's another issue opened for that feature request #10690. I'd advise you to add your comments in the new issue. Let's focus on a single issue and this one was created 2 weeks ago.

I @rimolive [I confirmed](https://github.com/kubeflow/pipelines/issues/10690#issuecomment-2081425957) with the creater of that feature request that my intention of the original request (bumping pydnatic version in kfp 1.8) would not be covered in the issue that you linked. Thus, can we open this issue back up please?

**Comment by rimolive** [comment]
I think this worths a broader discussion with the community. I'm pretty new to the community so I'm unaware of any backport changes policy and what is the decision flow to say if a feature/bug fix should or not be backported.

@caroline-paul99 Can you join the next [Pipelines WG meeting](https://www.kubeflow.org/docs/about/community/#kubeflow-community-calendars) to discuss that specific issue?
