### ISSUE TITLE
[feature] Parametrize launcher image in KFPV2

### ISSUE THREAD

**Issue by rimolive** [kubeflow/pipelines#10229]
### Feature Area

/area backend

### What feature would you like to see?
Launcher image could be parametrized in a way that users can make use of the following tasks:
* Work on a custom launcher image for additional checks before running a pipeline step
* Run Kubeflow Pipelines in a disconnected environment

### What is the use case or pain point?
Launcher image is hard-coded, and this is bad practice IMHO. We should be able to let users parameterize any image used by KFP, and launcher image is that example.

### Is there a workaround currently?
There is no possible workarounds

---

Love this idea? Give it a 👍.

**Comment by nirajkl** [comment]
Hi @rimolive ,

please suggest on timelines when the changes will be implemented.

thanks.

**Comment by and-1** [comment]
It would be great If you parametrize driver image also

**Comment by rimolive** [comment]
@nirajkl @and-1 Please check latest status. We have an ongoing PR to introduce launcher and driver image parametrization.

**Comment by thesuperzapper** [comment]
I want to highlight that `V2_LAUNCHER_IMAGE` will NOT affect [`V2_COMPATIBLE`](https://github.com/kubeflow/pipelines/blob/sdk-2.7.0/sdk/python/kfp/deprecated/dsl/_pipeline.py#L34-L36) mode runs.

These runs will still use the `_DEFAULT_LAUNCHER_IMAGE` which was hard-coded in the version of the `kfp` SDK you are using which is usually `gcr.io/ml-pipeline/kfp-launcher:1.8.7`:

- It is defined [here in `kfp==2.7.0`](https://github.com/kubeflow/pipelines/blob/sdk-2.7.0/sdk/python/kfp/deprecated/compiler/v2_compat.py#L24)
- It is defined [here in `kfp==1.8.7`](https://github.com/kubeflow/pipelines/blob/1.8.22/sdk/python/kfp/compiler/v2_compat.py#L25)

**Comment by rimolive** [comment]
v2-compatible mode is no longer supported, and the ideal path is upgrade kfp to the latest release. We're currently in 2.1.0  but we're planning to release 2.2.0 for Kubeflow 1.9.
