### ISSUE TITLE
[Execution strategy for backlog of queued runs] 

### ISSUE THREAD

**Issue by viktorsobol** [kubeflow/pipelines#10237]
### Feature Area

Hi dear Kubeflow community!

 /area backend

/area components 

### What feature would you like to see?

While running kubeflow in production we've seen a cases when run which is part of recurring run is taking more time then the schedule period and thus accumulates runs in ScheduledWorkflowController queue. 

Oozie scheduler has a feature called  `Execution strategy`
https://oozie.apache.org/docs/3.1.3-incubating/CoordinatorFunctionalSpec.html#a6.1.6._Coordinator_Action_Execution_Policies. 

Which allows to:

> Execution strategy: A coordinator job can specify the execution strategy of its coordinator actions when there is backlog of coordinator actions in the coordinator engine. The different execution strategies are 'oldest first', 'newest first' and 'last one only'. A backlog normally happens because of delayed input data, concurrency control or because manual re-runs of coordinator jobs.

The value last one only is especially useful; 

Are there any plans/thoughts regarding support of such feature? 

### Is there a workaround currently?

---

Love this idea? Give it a 👍.

**Comment by viktorsobol** [comment]
Hi @zijianjoy, 
I see that issue was moved to "Awaits Contributor"

I'm keen to work on this issue, and according to [this process ](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#step-4-design-review) the next step will be preparation of the document with the design. 
Let me know if this is correct next step.

**Comment by zijianjoy** [comment]
Hello @viktorsobol , that is correct. You may design the API and behavior of the execution strategy, and then present in one of the KFP community meetings.
