### ISSUE TITLE
[question] how to add `tolerations` using sdk `v2`.

### ISSUE THREAD

**Issue by akshatdalton** [kubeflow/pipelines#10252]
### Environment

*  KFP version: `2.0.1`

*  KFP SDK version: `2.0.1`

How can I add `tolerations` in kubeflow pipelines/components in kfp `v2`? In `v1`, I can see that there is a method: `add_toleration` but supported in `v1`.

Impacted by this bug? Give it a 👍.

**Comment by zijianjoy** [comment]
Duplicate of https://github.com/kubeflow/pipelines/issues/9682

**Comment by rimolive** [comment]
Closing this issue as @zijianjoy already marked as duplicated.

/close
