### ISSUE TITLE
feature request: consider component versioning

### ISSUE THREAD

**Issue by amygdala** [kubeflow/pipelines#1025]
I noticed that this change: https://github.com/kubeflow/pipelines/commit/5ccbbb9a0ca7c23aa8103568ec9f12ddc7c2bf54#diff-acbc4ac54289700274e3e3fefa0d3cbc
broke a pipeline that was using that component (because I had written the pipeline to accommodate the way that the export path worked with the original version of the component).

You are probably considering this already, but it might be useful to be able to pin a pipeline to use a component _version_, in order to avoid unexpected breaking changes.
(Of course then there is the problem of how to deprecate versions...)

**Comment by Ark-kun** [comment]
I have an extensive story on component versioning.
We'll be realizing it as the components start to arrive.
All the SDK pieces are already in place. (https://github.com/kubeflow/pipelines/pull/519) I need to add the `update_component.sh` script to the components though.

As a quick workaround, you should always pin the version of you container images in your pipeline.
You should either specify tag (based on GIT commit ID):
```gcr.io/ml-pipeline/components/keras/train_classifier:256:a123...456b```
(For more security you can use image digest: ```gcr.io/ml-pipeline/components/keras/train_classifier@sha256:a123...456b```)

Here is how the components are supposed to be versioned:
Component author updates component code in `./src/`.
Component author builds the `Dockerfile` by running `build_image.sh` which should also output the strict image name with digest: `gcr.io/ml-pipeline/components/keras/train_classifier@sha256:a123...456b`.
Component author runs the `update_component.sh` script (is not checked in yet) which takes `./component.yaml` file and replaces the `image:` there with the newly-built image's strict name. It then hashes the modified `component.yaml` file and writes it into a versioned file where the file name is the immutable file hash `./versions/sha256/fa51...cb61`.
Now the pipeline author can load the component by using the direct URL of the specific version:
`train_op = kfp.components.load_component('https://raw.githubusercontent.com/kubeflow/pipelines/master/components/samples/keras/train_classifier/versions/sha256/fa51...cb61')`

**Comment by Ark-kun** [comment]
As a quick fix for your pipeline: Try adding the following tag to all you container images in the pipeline:
`a60355abac5f7a835d2ca685c6a28ac34d3079fe`
The names should look like:
```gcr.io/ml-pipeline/components/keras/train_classifier:a60355abac5f7a835d2ca685c6a28ac34d3079fe```

**Comment by hongye-sun** [comment]
Sorry for breaking your pipeline, Amy. 

I have a PR (https://github.com/kubeflow/pipelines/pull/1019) to pin  the version in component yaml. After it's in, the next step for me is to update all the samples to pin the last commit id of the component.yaml files. Later after AIHub is live, I will update the samples to use the AIHub storage links.

For now, you can wait for the PR to be in and use the commit ID of the PR to reference the yaml file from github.

**Comment by hongye-sun** [comment]
Just noticed that Yang have already released the component by https://github.com/kubeflow/pipelines/pull/1021.

Amy, you can use https://raw.githubusercontent.com/kubeflow/pipelines/e9a65c223f34aa1181d437f07c7c37516336885e/components/gcp/ml_engine/train/component.yaml to load the component. This version will no longer be changed until you manually upgrade it.

**Comment by amygdala** [comment]
Thanks!
Hongye, I updated the pipeline logic to be compatible with the new version of that component, so no worries.  (I'll change my component URL to  point to that newer commit tag now).

The plan for versioning going forward makes sense. Since it's in the works I'll close this. Thanks for all the quick replies.

**Comment by Ark-kun** [comment]
Reopening to track the versioning issue until it's solved.

**Comment by Ark-kun** [comment]
Our samples have been using strictly versioned components fro a while. We store most components on GitHub and use commit-based perma-links to the component files.
The release script properly handles the updates.

There might be some improvements to this process in future (e.g. storing component versions in GCS bucket or only rebuilding components when the code changes), but generally the versioning is working.
