### ISSUE TITLE
[bug] kubeflow pipeines sdk v2 specify image_pull_secrets

### ISSUE THREAD

**Issue by ran-haim** [kubeflow/pipelines#10262]
There seems to be no way to specify image_pull_secrets for a step or pipeline in sdk v2.
This is a must have in order for the images to be able to get pulled for the pods.

**Comment by shishirkr-git** [comment]
is there any update on this issue? It is a blocker for V1 to V2 migration.



kfp.deprecated  has the V1  methods to set image pull secret but importing kfp.deprecated is giving error. 

    __def get_kfp_healthz(self) -> kfp_server_api.ApiGetHealthzResponse:
AttributeError: module 'kfp_server_api' has no attribute 'ApiGetHealthzResponse'. Did you mean: 'V2beta1GetHealthzResponse'?__

I see there is another open issue for this kfp.deprecated import error 
https://github.com/kubeflow/pipelines/issues/9330

**Comment by rimolive** [comment]
It looks like this was already implemented. I'm closing this issue but feel free to reopen it if it's not yet included in latest SDK.

/close
