### ISSUE TITLE
Need a user interface and/or documentation for the Viewer CRD

### ISSUE THREAD

**Issue by vicaire** [kubeflow/pipelines#1026]
We need a user interface and/or documentation for the Viewer CRD:

- So that users can keep track of their instances of Tensorboard or other viewers. 
- So that users do not forget to delete them once they do not need them. 

Ideally, the viewer CRD should automatically terminate processes if they have not been used for a while (though this is harder to do).

**Comment by rileyjbauer** [comment]
Is there design work here?
@ajayalfred

**Comment by vicaire** [comment]
Yes, there should be design work needed.

**Comment by ajayalfred** [comment]
I'll setup a meeting to discuss scope of the design work.

**Comment by rileyjbauer** [comment]
@jingzhang36 do you think you can take this on?

**Comment by neuromage** [comment]
I think we can close this as a duplicate of https://github.com/kubeflow/kubeflow/issues/3578 which @kimwnasptd has volunteered to tackle.
