### ISSUE TITLE
[sdk] KFP V2 upgrade issue with concatenating strings

### ISSUE THREAD

**Issue by karimhenry** [kubeflow/pipelines#10261]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
I am using kubeflow in gcp vertex ai pipelines. I am migrating from SDK v1-v2 namespace to v2
 

*  KFP version: 
2.4.0

### Steps to reproduce

I am having this pipeline whereby I am passing parameters and I would like to concat strings when being passed to a component but due to pythonic upgrade being done, this fails to parse correctly.

Code Snippet:
```
@component(base_image=PYTHON310, 
           packages_to_install=None,)
def add_component(
    d:str,
    e:dict=None
) -> int:
    print(d)
    print(e)
    return c

@kfp.dsl.pipeline(
    name = 'kfp-test',
    pipeline_root = URI+'/'+str(TIMESTAMP)+'/kfp/'
)
def pipeline(
    g: str = "name",
):
    k=f"Hello {g}"
    output2 = add_component(
        a = a1,
        b = b1,
        d=k,
        e={"key":k}
    ).set_display_name("test")
```

### Expected result

The string got printed as expected "Hello name" but dict fails to parse correctly {'key': 'Hello {{channel:task=;name=g;type=String;}}'} This used to work fine in kfp v1. This is happening since you are parsing dict as normal python function so it fails to parse correctly inside dictionary but work well within string

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

**Comment by SamAgarwal0** [comment]
I am facing a similar issue: 

KFP version:
2.4.0

```python
from kfp import compiler, dsl

@dsl.pipeline(name="xgboost-train-pipeline")
def xgboost_pipeline(
    pipeline_files_gcs_path: str = os.environ.get("PIPELINE_FILES_GCS_PATH"),
    ):
    print(pipeline_files_gcs_path)
    print(os.environ.get("PIPELINE_FILES_GCS_PATH"))

```

first prints  {{channel:task=;name=pipeline_files_gcs_path;type=String;}}
second prints `gs://bucket` (the correct path)

**Comment by dominique-lambert-OBS** [comment]
Hello,
I am facing a similar issue:

KFP version:
2.7.0

def pipeline(my_gcs_source: str = USE_CASE_DATA_CSV_GCS):
    print(my_gcs_source)

=> {{channel:task=;name=my_gcs_source;type=String;}}
