### ISSUE TITLE
[bug] Pythonic artifact dataset output not working, raise KeyError: 'name'

### ISSUE THREAD

**Issue by ibnummuhammad** [kubeflow/pipelines#10264]
### Environment

*  How do you deploy Kubeflow Pipelines (KFP)?

Deployed in AWS EKS using manifest as instructed in https://docs.aws.amazon.com/sagemaker/latest/dg/kubernetes-sagemaker-components-install.html

*  KFP version:

KFP Version = 2.0.3

*  KFP SDK version:

KFP SDK Version = v2.4.0

### Steps to reproduce

as documented in https://www.kubeflow.org/docs/components/pipelines/v2/data-types/artifacts/#new-pythonic-artifact-syntax
I tried to build a component with `Pythonic artifact syntax` with `multiple output artifacts` for `Dataset`.
I run the pipeline, get error log below, it raise `KeyError: 'name'`.
is this expected, since in the document stated that `The Pythonic artifact authoring syntax is not yet supported by the KFP orchestration backend `? or do I make any mistake in building the component while using the pythonic artifact style?

<img width="1797" alt="Screenshot 2023-11-24 at 15 26 05" src="https://github.com/kubeflow/pipelines/assets/25792451/2339be63-3907-4181-8778-1e64d4947bb9">

    time="2023-11-24T08:25:11.369Z" level=info msg="capturing logs" argo=true
    time="2023-11-24T08:25:11.481Z" level=info msg="capturing logs" argo=true
    I1124 08:25:11.554870      27 launcher_v2.go:90] input ComponentSpec:{
    "outputDefinitions": {
        "artifacts": {
        "dataset1": {
            "artifactType": {
            "schemaTitle": "system.Dataset",
            "schemaVersion": "0.0.1"
            }
        },
        "x_train_artifact": {
            "artifactType": {
            "schemaTitle": "system.Dataset",
            "schemaVersion": "0.0.1"
            }
        }
        }
    },
    "executorLabel": "exec-load-dataset"
    }
    I1124 08:25:11.560478      27 cache.go:116] Connecting to cache endpoint 10.100.11.243:8887
    WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: 
    https://pip.pypa.io/warnings/venv
    [KFP Executor 2023-11-24 08:25:14,896 INFO]: Looking for component `load_dataset` in --component_module_path `/tmp/tmp.OV1G8lNCND/ephemeral_component.py`
    [KFP Executor 2023-11-24 08:25:14,897 INFO]: Loading KFP component "load_dataset" from /tmp/tmp.OV1G8lNCND/ephemeral_component.py (directory "/tmp/tmp.OV1G8lNCND" and module name "ephemeral_component")
    [KFP Executor 2023-11-24 08:25:14,897 INFO]: Got executor_input:
    {
        "inputs": {},
        "outputs": {
            "artifacts": {
                "dataset1": {
                    "artifacts": [
                        {
                            "type": {
                                "schemaTitle": "system.Dataset",
                                "schemaVersion": "0.0.1"
                            },
                            "uri": "minio://mlpipeline/v2/artifacts/pipeline-flow/3acaf0e0-5aa2-4a22-9689-5d30394d18c8/load-dataset/dataset1"
                        }
                    ]
                },
                "x_train_artifact": {
                    "artifacts": [
                        {
                            "type": {
                                "schemaTitle": "system.Dataset",
                                "schemaVersion": "0.0.1"
                            },
                            "uri": "minio://mlpipeline/v2/artifacts/pipeline-flow/3acaf0e0-5aa2-4a22-9689-5d30394d18c8/load-dataset/x_train_artifact"
                        }
                    ]
                }
            },
            "outputFile": "/tmp/kfp_outputs/output_metadata.json"
        }
    }
    2023-11-24 08:25:15.380062: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
    To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
    Downloading data from 
    https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
        8192/11490434 [..............................] - ETA: 0s
    49152/11490434 [..............................] - ETA: 44s
    81920/11490434 [..............................] - ETA: 51s
    131072/11490434 [..............................] - ETA: 37s
    180224/11490434 [..............................] - ETA: 30s
    229376/11490434 [..............................] - ETA: 27s
    278528/11490434 [..............................] - ETA: 24s
    344064/11490434 [..............................] - ETA: 21s
    442368/11490434 [>.............................] - ETA: 18s
    557056/11490434 [>.............................] - ETA: 15s
    688128/11490434 [>.............................] - ETA: 13s
    835584/11490434 [=>............................] - ETA: 11s
    1048576/11490434 [=>............................] - ETA: 9s 
    1310720/11490434 [==>...........................] - ETA: 7s
    1654784/11490434 [===>..........................] - ETA: 6s
    2064384/11490434 [====>.........................] - ETA: 4s
    2596864/11490434 [=====>........................] - ETA: 3s
    3284992/11490434 [=======>......................] - ETA: 2s
    4096000/11490434 [=========>....................] - ETA: 2s
    5062656/11490434 [============>.................] - ETA: 1s
    6438912/11490434 [===============>..............] - ETA: 1s
    7618560/11490434 [==================>...........] - ETA: 0s
    9330688/11490434 [=======================>......] - ETA: 0s
    10862592/11490434 [===========================>..] - ETA: 0s
    11460608/11490434 [============================>.] - ETA: 0s
    11490434/11490434 [==============================] - 2s 0us/step
    Traceback (most recent call last):
    File "<frozen runpy>", line 198, in _run_module_as_main
    File "<frozen runpy>", line 88, in _run_code
    File "/usr/local/lib/python3.11/dist-packages/kfp/dsl/executor_main.py", line 109, in <module>
        executor_main()
    File "/usr/local/lib/python3.11/dist-packages/kfp/dsl/executor_main.py", line 101, in executor_main
        output_file = executor.execute()
                    ^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/dist-packages/kfp/dsl/executor.py", line 362, in execute
        return self.write_executor_output(result)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/dist-packages/kfp/dsl/executor.py", line 265, in write_executor_output
        self.handle_single_return_value(field, field_type,
    File "/usr/local/lib/python3.11/dist-packages/kfp/dsl/executor.py", line 208, in handle_single_return_value
        artifact_name = self.executor_input['outputs']['artifacts'][
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    KeyError: 'name'
    I1124 08:25:20.484936      27 launcher_v2.go:151] publish success.
    F1124 08:25:20.484961      27 main.go:49] failed to execute component: exit status 1
    time="2023-11-24T08:25:20.514Z" level=info msg="sub-process exited" argo=true error="<nil>"
    Error: exit status 1
    time="2023-11-24T08:25:21.402Z" level=info msg="sub-process exited" argo=true error="<nil>"
    Error: exit status 1

### Expected result

Expecting to get the artifact output just like `Traditional artifact syntax`.

### Materials and reference

Example code to reproduce

    @dsl.component(base_image="tensorflow/tensorflow")
    def load_dataset(
        x_train_artifact: Output[Dataset],
    ) -> NamedTuple("outputs", dataset1=Dataset):
        import numpy as np
        from tensorflow import keras
        import os
    
        (x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()
    
        np.save("/tmp/x_train.npy", x_train)
        os.rename("/tmp/x_train.npy", x_train_artifact.path)
    
        outputs = NamedTuple("outputs", dataset1=Dataset)
    
        return outputs(dataset1=x_train_artifact)
    
    
    @dsl.pipeline()
    def pipeline_flow():
        load_dataset()

and compiled yaml as below

    >>> compiler.Compiler().compile(pipeline_flow, "kubeflow_pipeline.yml")

    ---

    # PIPELINE DEFINITION
    # Name: pipeline-flow
    components:
    comp-load-dataset:
        executorLabel: exec-load-dataset
        outputDefinitions:
        artifacts:
            dataset1:
            artifactType:
                schemaTitle: system.Dataset
                schemaVersion: 0.0.1
            x_train_artifact:
            artifactType:
                schemaTitle: system.Dataset
                schemaVersion: 0.0.1
    deploymentSpec:
    executors:
        exec-load-dataset:
        container:
            args:
            - --executor_input
            - '{{$}}'
            - --function_to_execute
            - load_dataset
            command:
            - sh
            - -c
            - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
            \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
            \ python3 -m pip install --quiet --no-warn-script-location 'kfp==2.4.0'\
            \ '--no-deps' 'typing-extensions>=3.7.4,<5; python_version<\"3.9\"' && \"\
            $0\" \"$@\"\n"
            - sh
            - -ec
            - 'program_path=$(mktemp -d)

            printf "%s" "$0" > "$program_path/ephemeral_component.py"

            _KFP_RUNTIME=true python3 -m kfp.dsl.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

            '
            - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
            \ *\n\ndef load_dataset(\n    x_train_artifact: Output[Dataset],\n) -> NamedTuple(\"\
            outputs\", dataset1=Dataset):\n    import numpy as np\n    from tensorflow\
            \ import keras\n    import os\n\n    (x_train, y_train), (x_test, y_test)\
            \ = keras.datasets.mnist.load_data()\n\n    np.save(\"/tmp/x_train.npy\"\
            , x_train)\n    os.rename(\"/tmp/x_train.npy\", x_train_artifact.path)\n\
            \n    outputs = NamedTuple(\"outputs\", dataset1=Dataset)\n\n    return\
            \ outputs(dataset1=x_train_artifact)\n\n"
            image: tensorflow/tensorflow
    pipelineInfo:
    name: pipeline-flow
    root:
    dag:
        tasks:
        load-dataset:
            cachingOptions:
            enableCache: true
            componentRef:
            name: comp-load-dataset
            taskInfo:
            name: load-dataset
    schemaVersion: 2.1.0
    sdkVersion: kfp-2.4.0

### Labels

/area backend

---

Impacted by this bug? Give it a 👍.

**Comment by connor-mccarthy** [comment]
Hi, @ibnummuhammad. With the Pythonic artifact authoring style, you don't need to use the input parameter `x_train_artifact: Output[Dataset]`. You can simply return the Dataset as you would a typical Python object in a typical Python function:

```python
@dsl.component(base_image="tensorflow/tensorflow")
def load_dataset() -> NamedTuple("outputs", dataset1=Dataset):
    import numpy as np
    from tensorflow import keras

    (x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()
    x_train_artifact = Dataset(uri=dsl.get_uri('dataset1'))
    np.save(x_train_artifact.path, x_train)

    outputs = NamedTuple("outputs", dataset1=Dataset)
    return outputs(dataset1=x_train_artifact)
```

For one output, you can reduce this even further:

```python
@dsl.component(base_image="tensorflow/tensorflow")
def load_dataset() -> Dataset:
    import numpy as np
    from tensorflow import keras

    (x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()
    x_train_artifact = Dataset(uri=dsl.get_uri('dataset1'))
    np.save(x_train_artifact.path, x_train)
    return x_train_artifact
```

The above runs successfully on Vertex Pipelines. Note that you will still have issues with the Pythonic artifact authoring approach on the KFP OSS backend, as this backend does not yet support it.

![image](https://github.com/kubeflow/pipelines/assets/55268212/7f689157-7347-410d-9043-ebd09c56fb29)
