### ISSUE TITLE
[feature] Setting a task group name

### ISSUE THREAD

**Issue by yas0nia** [kubeflow/pipelines#10274]
### Feature Area

/area backend

### What feature would you like to see?

Able to set a custom name for a task group:
https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/dsl/tasks_group.py#L78

### What is the use case or pain point?

when using dsl.If and dsl.Else, they get grouped in a task group with an automatically generated name, which makes the pipeline less readable
![Screenshot 2023-11-29 at 13 21 10](https://github.com/kubeflow/pipelines/assets/39127823/782cef30-69ea-450b-a111-4d4fee1f91c2)

### Is there a workaround currently?

Custom "head" if component (instead of deprecated dsl.Condition) to mimic a task group, I guess

Love this idea? Give it a 👍.

**Comment by chensun** [comment]
You can customize the group name via the `name` parameter: https://kubeflow-pipelines.readthedocs.io/en/latest/source/dsl.html#kfp.dsl.Condition.__init__.name
