### ISSUE TITLE
Enhance samples documentation

### ISSUE THREAD

**Issue by hbelmiro** [kubeflow/pipelines#10275]
I am facing challenges running the [condition](https://github.com/kubeflow/pipelines/tree/master/samples/core/condition) sample. I used the [sdk/python/requirements.txt](https://github.com/kubeflow/pipelines/blob/master/sdk/python/requirements.txt) file to install the dependencies (which I'm not sure is the right one). It does not include `kfp` and installing `kfp==1.8` separately results in the following error:

```bash
python condition.py
Traceback (most recent call last):
  File "/home/hbelmiro/dev/tests/kubeflow/pipelines/condition/condition.py", line 15, in <module>
    from kfp.deprecated import components
ModuleNotFoundError: No module named 'kfp.deprecated'
```

Are the requirements to run the samples defined in [sdk/python/requirements.txt](https://github.com/kubeflow/pipelines/blob/master/sdk/python/requirements.txt) or somewhere else?

## Proposal
If the requirements are not defined anywhere, we could add a `requirements.txt` file for each sample (or one for all samples) to clarify and specify the necessary dependencies. This enhancement will facilitate a smoother user experience.

I can send a PR once the requirements are clarified.

**Comment by chensun** [comment]
[sdk/python/requirements.txt](https://github.com/kubeflow/pipelines/blob/master/sdk/python/requirements.txt) is not meant for users but for SDK developers. 
For SDK users, they would install `kfp` simply using `pip install` command with or without a specified version, and the dependencies would be installed automatically. 

samples/core/condition/condition.py is a legacy v1 sample, please try out samples/core/condition/condition_v2.py instead which requires `kfp` SDK 2.*
