### ISSUE TITLE
Remove link to JupyterHub from pipelines UI

### ISSUE THREAD

**Issue by jlewi** [kubeflow/pipelines#1029]
In 0.5 we are removing JupyterHub from Kubeflow and replacing it with a new UI for managing notebooks.

We should remove the link in the pipelines UI that is redirecting to JupyterHub.

![jupyterhub](https://user-images.githubusercontent.com/777219/54874584-89505380-4dab-11e9-8169-8ad109d7e519.png)

I think we can remove the link and not just update it because with 0.5 we have a central navigation bar that will include a link to notebooks.

Here's how it looks

![pipelines](https://user-images.githubusercontent.com/777219/54874596-c61c4a80-4dab-11e9-8476-d0b781b702dd.png)

If user clicks the hamburger icon they see the navigation bar which has a link to notebooks.

![dashboard](https://user-images.githubusercontent.com/777219/54874601-e1875580-4dab-11e9-92d6-f79721cf687b.png)

**Comment by kunmingg** [comment]
Can we close this?

**Comment by avdaredevil** [comment]
@rileyjbauer Feel free to open if there are any lingering changes.
/close
