### ISSUE TITLE
Return the total number of resources in list APIs

### ISSUE THREAD

**Issue by yebrahim** [kubeflow/pipelines#103]
This is needed by the UI to show the total number of resources when paging through them. It's also needed when showing the total number of recurring runs in an experiment.

**Comment by neuromage** [comment]
@IronPan I can try to take a stab at this if you haven't already started work on it. Seems like a good way to get into the inner workings of the API server. Let me know what you think.

**Comment by IronPan** [comment]
@neuromage Thanks it looks like @yebrahim has a PR about it https://github.com/kubeflow/pipelines/pull/595
