### ISSUE TITLE
Create a separate sample to illustrate component build

### ISSUE THREAD

**Issue by gaoning777** [kubeflow/pipelines#1033]

**Comment by vicaire** [comment]
@gaoning777, I am assigning the DSL sample issues to illustrate features to you. Please reassign to the most appropriate person as needed.

**Comment by SinaChavoshi** [comment]
Submitted PR #1681
TODO: Add automated test for the sample.

**Comment by gaoning777** [comment]
All sample tests are tracked: https://github.com/kubeflow/pipelines/issues/1813
