### ISSUE TITLE
DSL samples to illustrate the full set of features

### ISSUE THREAD

**Issue by gaoning777** [kubeflow/pipelines#1034]
Create more samples to fully cover the DSL features:
Volume mount: https://github.com/kubeflow/pipelines/issues/566
Python2 component build: https://github.com/kubeflow/pipelines/issues/1033
Secret Mount: https://github.com/kubeflow/pipelines/issues/993
Local Storage: https://github.com/kubeflow/pipelines/issues/721
Imagepullsecrets: https://github.com/kubeflow/pipelines/issues/1036
Execution order: #665 
GPU/TPU: #980 
Multiple output: https://github.com/kubeflow/pipelines/issues/1517

**Comment by vicaire** [comment]
@gaoning777, I am assigning the DSL sample issues to illustrate features to you. Please reassign to the most appropriate person as needed.

**Comment by gaoning777** [comment]
Execution order: #665

**Comment by jessiezcc** [comment]
@gaoning777 will drive the sample effort

**Comment by gaoning777** [comment]
Acked.

**Comment by gaoning777** [comment]
All samples listed are added. Test coverage is tracked in https://github.com/kubeflow/pipelines/issues/1813
