### ISSUE TITLE
[sdk] <command not found: kfp after pip3 install on mac m1>

### ISSUE THREAD

**Issue by wang-mask** [kubeflow/pipelines#10349]
### Environment

*  KFP version:

*  KFP SDK version: 

*  All dependencies version:

### Steps to reproduce

pip3 install kfp (Mac M1pro)

kfp --version

command not found: kfp

### Expected result
kfp cli works

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

**Comment by chensun** [comment]
This isn't a KFP issue per se. Usually it's due to your Python environment setup, and the solution could be add the pip component path into `$PATH` environment variable.
