### ISSUE TITLE
[sdk] enable_caching=False does not work using run_pipeline() command

### ISSUE THREAD

**Issue by ibnummuhammad** [kubeflow/pipelines#10352]
### Environment

*  KFP version:
2.4.0
*  KFP SDK version: 
2.0.5
*  All dependencies version:
kfp==2.4.0
kfp-pipeline-spec==0.2.2
kfp-server-api==2.0.5

### Steps to reproduce

```
client.run_pipeline(
    ...
    enable_caching=False,
    ...
)
```

but pipeline is still running with cache

![Screenshot from 2024-01-02 20-34-54](https://github.com/kubeflow/pipelines/assets/25792451/501ad963-5b95-44fb-909d-25f57fa9b20a)

### Expected result

expecting pipeline will run without cache.

is this expected? using run_pipeline() with enable_caching False not affecting the component run task?

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

**Comment by gomrinal** [comment]
Encountered similar issue with `.enable_caching()`
