### ISSUE TITLE
[feature] Apply Pod Labels and Pod Annotations for Kubeflow Pipeline Tasks

### ISSUE THREAD

**Issue by revolutionisme** [kubeflow/pipelines#10363]
### Feature Area

/area backend
/area sdk

### What feature would you like to see?

In KFP SDK V1, we had existing methods to easily [add pod labels](https://kubeflow-pipelines.readthedocs.io/en/1.8.22/source/kfp.dsl.html?highlight=add_pod#kfp.dsl.ContainerOp.add_pod_label) and [add pod annotations](https://kubeflow-pipelines.readthedocs.io/en/1.8.22/source/kfp.dsl.html?highlight=add_pod#kfp.dsl.ContainerOp.add_pod_annotation)

However when we are working with KFP V2 SDK, these methods are all missing and there's no way (not even a workaround?) to add these pod labels and annotations. I checked the open issues and there seems to be issues pertaining to adding podaffinity and tolerations which are unfortunately still open. 

Is there a way to add aforementioned labels and annotations? If not I would like to see this feature parity with KFP V1. 

### What is the use case or pain point?

We are used to using selectors to match the labels and find relevant set of pods together, which is unfortunately not possible anymore. Also, we want to apply PodDefaults based on the labels on the component pods.

### Is there a workaround currently?

Nothing I could find out so far. 

---

Love this idea? Give it a 👍.

**Comment by zijianjoy** [comment]
Currently it is being worked on in https://github.com/kubeflow/pipelines/issues/9682. Closing this for now to avoid duplication.

**Comment by OutSorcerer** [comment]
It is possible in v2 at the moment using "Kubernetes Platform-specific Features" package, [kfp-kubernetes](https://pypi.org/project/kfp-kubernetes/). 

```
from kfp import dsl
from kfp import kubernetes


@dsl.component
def comp():
    pass


@dsl.pipeline
def my_pipeline():
    task = comp()
    kubernetes.add_pod_label(
        task,
        label_key='kubeflow.com/kfp',
        label_value='pipeline-node',
    )
    kubernetes.add_pod_annotation(
        task,
        annotation_key='run_id',
        annotation_value='123456',
    )
```
