### ISSUE TITLE
Differentiate between Failed and Terminated runs on list pages

### ISSUE THREAD

**Issue by rileyjbauer** [kubeflow/pipelines#1040]
The way termination is done and handled by Argo is a bit touchy, and they don't provide a `Terminated` status. Instead, the run has the status `Failed` and includes the exact error message `'terminated'`. This is how we distinguish between the two on the frontend. However, this information is not currently available through the list APIs, which is why on the list pages, terminated runs will have the `Failed` icon and will not indicate that they are terminated.
It is also quite brittle, but there isn't a great solution to it until we either have an intermediary layer between the API server and the frontend, or Argo changes the way they handle terminated runs.

Incidentally, according to @IronPan, it seems as though Argo intentionally chose not to disambiguate between `Failed` and `Terminated`, so it's possible we could convince them to change that.

**Comment by rileyjbauer** [comment]
Is this really a p0? It's not ideal, but it's not really critical.

I filed an issue on the Argo repo to potentially address it on that end:
https://github.com/argoproj/argo/issues/1289

**Comment by Bobgy** [comment]
I don't feel this is really critical either.

/close
Please reopen if this is important to you.
