### ISSUE TITLE
[feature] Run name should be unique

### ISSUE THREAD

**Issue by HumairAK** [kubeflow/pipelines#10446]
### Feature Area
/area frontend
/area backend

### What feature would you like to see?

Make run names unique, and prevent the user from creating a run when a run with the same name already exists

### What is the use case or pain point?
Currently multiple runs can share a name: 

![image](https://github.com/kubeflow/pipelines/assets/10904967/93a82c36-c601-4045-8bf5-08779f183d2e)

If a user wants to delete Test1 — they don’t understand which Test1 is what — it’s ambiguous — the user does it to themselves yes, but it’s strange for the API to let it go through. Much like pipeline version names, there should be no need to allow duplicate run names.

### Is there a workaround currently?

No

---

Love this idea? Give it a 👍.

**Comment by zijianjoy** [comment]
Thank you for the feature request @HumairAK, from the current implementation point-of-view, it is using Run ID to differentiate each run entry. Run name is not restricted to be unique. 

Do you think showing pipeline ID on the UI can be helpful?

**Comment by xianli123** [comment]
Hi @zijianjoy Is the Run ID generated in the backend and not editable? Thanks!

**Comment by zijianjoy** [comment]
> Hi @zijianjoy Is the Run ID generated in the backend and not editable? Thanks!

That is correct, Run ID is UUID generated by kfp API server and it is immutable.
