### ISSUE TITLE
[feature] Add file_system_poll_wait_seconds parameter in CRD controller

### ISSUE THREAD

**Issue by chmielas** [kubeflow/pipelines#10448]
### Feature Area

 /area backend

### What feature would you like to see?

I would like to propose the addition of a --file_system_poll_wait_seconds parameter to the CRD controller in Kubeflow Pipelines to help mitigate high costs associated with frequent S3 bucket access, as described in https://github.com/tensorflow/serving/issues/1291 or https://github.com/tensorflow/serving/issues/1916

### What is the use case or pain point?

The default value of this parameter is set to one second, which as a result incurs a high cost.
By allowing the adjustment of the polling interval through  `--file_system_poll_wait_seconds` parameter and pass it to the Kubernetes deployment, users can reduce the number `ListBucket` operations to S3, thus lowering operational costs.

### Is there a workaround currently?

ChatGPT
As of now, I had to disable the CRD controller to avoid additional costs.

---

Love this idea? Give it a 👍.

**Comment by chensun** [comment]
Kubeflow Pipelines relies on [Argo workflow](https://github.com/argoproj/argo-workflows) CRD controller. You may need to file a feature request to Argo.
