### ISSUE TITLE
[backend] Unable to render pipelines UI after upgrade

### ISSUE THREAD

**Issue by pythonking6** [kubeflow/pipelines#10457]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
deployed using documentation setting pipeline version and using 2 more commands .

*  KFP version: 
PIPELINE_VERSION = 2.0.5
*  KFP SDK version: 
KFP VERSION 2.5.0

### Steps to reproduce

Upgrade kfp pipelines backend to 2.0.5

Get api error as follows:

{
    "error": "Failed to list runs: Failed to list runs due to authorization error. Check if you have permission to access namespace : Invalid input error: A run cannot have an empty namespace in multi-user mode",
    "code": 3,
    "message": "Failed to list runs: Failed to list runs due to authorization error. Check if you have permission to access namespace : Invalid input error: A run cannot have an empty namespace in multi-user mode",
    "details": [
        {
            "@type": "type.googleapis.com/google.rpc.Status",
            "code": 3,
            "message": "A run cannot have an empty namespace in multi-user mode"
        }
    ]
}

### Expected result

Should display runs

### Materials and Reference

https://www.kubeflow.org/docs/components/pipelines/v1/installation/standalone-deployment/

---

Impacted by this bug? Give it a 👍.

**Comment by chensun** [comment]
@pythonking6 The screenshot you have shows it's a full-Kubeflow deployment, rather than "kfp standalone development".
How did you deploy the Kubeflow, and on which platform?

**Comment by pythonking6** [comment]
I solved this by updating using manifests instead!

**Comment by rimolive** [comment]
Can you be more specific? what manifests you used?
