### ISSUE TITLE
[backend] Pipeline v2 Advanced Example Not completing

### ISSUE THREAD

**Issue by Boes-man** [kubeflow/pipelines#10458]
I dont have permssions to [move the issue here](https://github.com/kubeflow/manifests/issues/2615)

**Comment by Boes-man** [comment]
Hello, I am trying to run this [kf example pipeline](https://www.kubeflow.org/docs/components/pipelines/v2/installation/quickstart/) (Build a more advanced ML pipeline). I modified it: removed endpoint and added compiler. I can now upload the pipeline and run it, but it is not completing. I have found some error message related to RBAC and "files not found" but I am not sure if its related or how to fix them. Thanks

**Comment by Boes-man** [comment]
@juliusvonkohout

**Comment by rimolive** [comment]
What is the KFP version you deployed?

**Comment by Boes-man** [comment]
Hi @rimolive, thanks for checking in. I am not sure, its a followon question i have :) I just git cloned the main branch and then used the manifest example install process. In the UI it show "dev local" (dont have a cluster up now, but its something like that).
I did dump out `List of images` as per the last part of my original post. Hope that helps.
Thanks

**Comment by rimolive** [comment]
I recommend you to follow the installation documentation in https://www.kubeflow.org/docs/components/pipelines/v2/installation/quickstart/. Applying manifests from main branch is just for dev purposes and not recommended for production/testing.

**Comment by rimolive** [comment]
Is there anything else you need about this issue?

**Comment by Boes-man** [comment]
Hi rimolive. think we can close for now. I have not been able to look at this further. Thanks

**Comment by rimolive** [comment]
Sure, no worries!

/close
