### ISSUE TITLE
[feature] Upgrade to latest Argo 3.4.x

### ISSUE THREAD

**Issue by HumairAK** [kubeflow/pipelines#10469]
/area backend

### What feature would you like to see?
Upgrade to latest Argo 3.4.x

### What is the use case or pain point?
3.3 is no longer being patched with security fixes, and has not been for over a year now, lots of CVE's have accumulated since then, and KFP needs to catch up in this regard.

### Is there a workaround currently?
A user can try to manually deploy Argo 3.4, but this has resulted in various issues: 
* https://github.com/kubeflow/pipelines/issues/8942
* https://github.com/kubeflow/pipelines/issues/8935

Related: 
https://github.com/kubeflow/pipelines/pull/9301

---

Love this idea? Give it a 👍.

**Comment by chensun** [comment]
Previous upgrade attempt: https://github.com/kubeflow/pipelines/pull/9301, in case anyone want to pick up and finish the work.

**Comment by HumairAK** [comment]
This was resolved in https://github.com/kubeflow/pipelines/pull/10568
