### ISSUE TITLE
[feature] Add the ability to disable annotations to reduce the compiled manifest size

### ISSUE THREAD

**Issue by droctothorpe** [kubeflow/pipelines#10529]
### Feature Area

/area sdk

### What feature would you like to see?
Given the long-standing issue, https://github.com/kubeflow/pipelines/issues/4170, and the hacky workaround documented [here](https://github.com/kubeflow/pipelines/issues/4170#issuecomment-655764762), it would be great if `compile` included parameters that at a bare minimum stripped annotations and potentially other parameters that stripped docstrings or comments out to get the compiled manifest size down under 1.5MB. 

### What is the use case or pain point?
We have many massive pipelines that run into the 1.5MB manifest limit. 

### Is there a workaround currently?
The recommended workaround, at present, is to deconstruct the pipeline into multiple smaller pipelines.

**We'd be happy to implement this if the feature makes sense.**

---

Love this idea? Give it a 👍.

**Comment by rimolive** [comment]
All examples posted are from kubeflow pipelines v1. Since in v2 we introduced the IR yaml feature, what is the new size?

This needs some research to understand what is the difference between v1 and v2 and evaluate if that feature makes sense.

**Comment by droctothorpe** [comment]
Haven't had a chance to compare the size discrepancy between V1 and V2 manifests. Will reply when I have a chance to. Thanks!

**Comment by droctothorpe** [comment]
This should no longer be necessary in V2 once https://github.com/kubeflow/pipelines/pull/10979 is merged.
