### ISSUE TITLE
[frontend] Unable to pass input artifact to pipeline on Central Dashboard

### ISSUE THREAD

**Issue by milind-u** [kubeflow/pipelines#10526]
We are unsure how to specify an input artifact to a kubeflow v2 pipeline being run from the dashboard. Here, as we do Create Run there is no way to specify this `dsl.Model` artifact named model:

![image](https://github.com/kubeflow/pipelines/assets/79386439/ddf4d485-cdc0-4680-aba5-3b7c5a84bde9)
![image](https://github.com/kubeflow/pipelines/assets/79386439/f87e134b-803d-4f74-9b62-1e57c311e36b)

**Comment by adil-ahorger** [comment]
Were you able to resolve this issue? I'm likewise unsure how to pass input artifacts to the pipeline. It's also unclear in [the docs](https://www.kubeflow.org/docs/components/pipelines/v2/run-a-pipeline/#2-run-from-the-kfp-sdk-client) if the `arguments` parameter should also be used for input artifacts when using the KFP SDK.

**Comment by milind-u** [comment]
We were not able to resolve this, we instead wrote outputs/inputs of pipelines to MinIO storage and then could read them in from other pipelines.

**Comment by adil-ahorger** [comment]
> We were not able to resolve this, we instead wrote outputs/inputs of pipelines to MinIO storage and then could read them in from other pipelines.

I see. Hopefully there will be some additional clarity for pipeline input artifacts in the near future, but in the meantime I think your solution is the best workaround.
