### ISSUE TITLE
How to support continuous online learning?

### ISSUE THREAD

**Issue by yingfeng** [kubeflow/pipelines#1053]
The existing samples demostrate how to deploy a pipeline where given data is sent to feature engineering component, followed by a training as well as prediction. However, in many cases, online learning or continuous learning is required which means data comes as a stream, as a result, orchestrating a streaming based pipeline is required, what's more, the prediction server should be 7*24 available to provide online prediction service.  Could Kubeflow Pipelines support such kinds of production pipeline? Thanks~

**Comment by Ark-kun** [comment]
I'd say that currently KF Pipelines are more focused on batch processing and all the guarantees and value it can provide.
Would your problem be solved by running periodic (daily/hourly) jobs incorporating new data and deploying the improved models?

**Comment by yingfeng** [comment]
It's not that elegant ...
For online learning, the freshness of model is a key factor to reflect the user behaviours as quickly as possible.  The logging comes continuously from a data streaming source such as Kafka.

**Comment by hongye-sun** [comment]
Yingfeng, this use case can actually be achieved by combining cloud
function with KFP today on GCP. Within the cloud function, you can call KFP
SDK to submit a KFP workflow. At the end of the workflow, you can push the
model to a prediction service on cloud or in cluster.

If you are not on GCP, you can create a long lived pod in your cluster
which watches changes in Target data source and use KFP SDK to submit a new
workflow.

It is not ideal. We are planning to support a more k8s  native way like CRD
to support data triggering. Though, we don't have an ETA for that yet.

**Comment by vicaire** [comment]
Resolving in favor of https://github.com/kubeflow/pipelines/issues/651. Support for triggering workflow should enable the continuous online learning use case.
