### ISSUE TITLE
JSON Decode error while using google_cloud_components.v1.dataproc in Kubeflow Pipeline

### ISSUE THREAD

**Issue by jegadesh-google** [kubeflow/pipelines#10559]
### Environment

*  How do you deploy Kubeflow Pipelines (KFP)?
 Kubeflow Pipelines available in Google Cloud Marketplace
*  KFP version:
2.0.0
To find the version number, See version number shows on bottom of KFP UI left sidenav. -->
*  KFP SDK version:
2.7.0

### Steps to reproduce

Run a simple pipeline using component google_cloud_pipeline_components.v1.dataproc.DataprocPySparkBatchOp in Kubeflow . Was able to run the same yaml compiled in Vertex AI Pipeline , but the same yaml is failing with kubeflow pipeline

Stack Trace : Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/google_cloud_pipeline_components/container/v1/dataproc/utils/dataproc_util.py", line 342, in create_batch
    json.loads(insert_system_labels_into_payload(payload), strict=False)
  File "/usr/local/lib/python3.8/dist-packages/google_cloud_pipeline_components/container/v1/dataproc/utils/dataproc_util.py", line 49, in insert_system_labels_into_payload
    job_spec = json.loads(payload)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 855 (char 854)

### Expected result

Pipeline should be submitted scucessfully

### Labels

---

Impacted by this bug? Give it a 👍.

**Comment by rimolive** [comment]
Did you try running that pipeline in KFP 2.0.5?

**Comment by jegadesh-google** [comment]
Not yet. Is there a change in KFP 2.0.5 that fixes this bug ?

**Comment by jegadesh-google** [comment]
tried in Kubeflow 2.0.5 as well. same error.

**Comment by rimolive** [comment]
cc @chensun @connor-mccarthy

**Comment by jegadesh-google** [comment]
The issue is due to lack of support for `dsl.ConcatPlaceholder` in Kubeflow OSS  which is referenced in 
https://github.com/kubeflow/pipelines/blob/master/components/google-cloud/google_cloud_pipeline_components/v1/dataproc/create_pyspark_batch/component.py#L78-L157

As a workaround , modified the Dataproc component definition by using f-strings instead of the `dsl.ConcatPlaceholder`

` payload = f"""{{
  "labels": {labels},
  "runtime_config": {{
    "version": "{runtime_config_version}",
    "container_image": "{container_image}",
    "properties": {runtime_config_properties}
  }},
  "environment_config": {{
    "execution_config": {{
      "service_account": "{service_account}",
      "network_tags": {network_tags},
      "kms_key": "{kms_key}",
      "network_uri": "{network_uri}",
      "subnetwork_uri": "{subnetwork_uri}"
    }},
    "peripherals_config": {{
      "metastore_service": "{metastore_service}",
      "spark_history_server_config": {{
        "dataproc_cluster": "{spark_history_dataproc_cluster}"
      }}
    }}
  }},
  "pyspark_batch": {{
    "main_python_file_uri": "{main_python_file_uri}",
    "python_file_uris": {python_file_uris},
    "jar_file_uris": {jar_file_uris},
    "file_uris": {file_uris},
    "archive_uris": {archive_uris},
    "args": {args}
  }}
}}"""
    return ContainerSpec(
      image=GCPC_IMAGE_NAME,
      command=[
          'python3',
          '-u',
          '-m',
          'google_cloud_pipeline_components.container.v1.dataproc.create_pyspark_batch.launcher',
      ],
      args=[
          '--type',
          'DataprocPySparkBatch',
          '--payload',
          payload,
          '--project',
          project,
          '--location',
          location,
          '--batch_id',
          batch_id,
          '--gcp_resources',
          gcp_resources,
      ],
  )`

**Comment by chensun** [comment]
> The issue seems to be due to lack of support for dsl.ConcatPlaceholder in Kubeflow OSS which is referenced in

That's right. ConcatPlaceholder is not supported yet, it's tracked by https://github.com/kubeflow/pipelines/issues/9486 with no ETA at this moment.
