### ISSUE TITLE
[backend] Failed to build backend/Dockerfile due to the installation of default-jdk

### ISSUE THREAD

**Issue by champon1020** [kubeflow/pipelines#10553]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
Local machine using kind.

*  KFP version: 
2.7.0

*  KFP SDK version: 
2.7.0

### Steps to reproduce
Following the instruction of building api server image locally ([ref](https://github.com/kubeflow/pipelines/blob/master/backend/README.md)).
```
cd /path/to/pipelines
docker build -f backend/Dockerfile -t api_server . 
```

### Expected result
I got following error message.
```
53.68 Setting up ca-certificates-java (20190405) ...
53.70 head: cannot open '/etc/ssl/certs/java/cacerts' for reading: No such file or directory
53.80 Exception in thread "main" java.lang.InternalError: Error loading java.security file
53.80 	at java.base/java.security.Security.initialize(Security.java:94)
53.80 	at java.base/java.security.Security$1.run(Security.java:79)
53.80 	at java.base/java.security.Security$1.run(Security.java:77)
53.80 	at java.base/java.security.AccessController.doPrivileged(Native Method)
53.80 	at java.base/java.security.Security.<clinit>(Security.java:77)
53.80 	at java.base/sun.security.jca.ProviderList.<init>(ProviderList.java:176)
53.80 	at java.base/sun.security.jca.ProviderList$2.run(ProviderList.java:94)
53.80 	at java.base/sun.security.jca.ProviderList$2.run(ProviderList.java:92)
53.80 	at java.base/java.security.AccessController.doPrivileged(Native Method)
53.80 	at java.base/sun.security.jca.ProviderList.fromSecurityProperties(ProviderList.java:91)
53.80 	at java.base/sun.security.jca.Providers.<clinit>(Providers.java:54)
53.80 	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:156)
53.80 	at java.base/java.security.cert.CertificateFactory.getInstance(CertificateFactory.java:193)
53.80 	at org.debian.security.KeyStoreHandler.<init>(KeyStoreHandler.java:50)
53.80 	at org.debian.security.UpdateCertificates.<init>(UpdateCertificates.java:65)
53.80 	at org.debian.security.UpdateCertificates.main(UpdateCertificates.java:51)
53.81 dpkg: error processing package ca-certificates-java (--configure):
53.81  installed ca-certificates-java package post-installation script subprocess returned error exit status 1
```

### Materials and Reference
According to my investigation, it seems to be resolved by replacing the following line default-jdk to default-jdk-headless.
https://github.com/kubeflow/pipelines/blob/ea56a40212116bc0f8675a10c1ec47a1b17386c6/backend/Dockerfile#L31

However, since I'm not familiar with Java, I don't know why this is happened and resolved by this modification.
Does anyone know why this happens and is this the better solution?

---

Impacted by this bug? Give it a 👍.

**Comment by rimolive** [comment]
Just curious: Are you building this image on a Mac?

**Comment by champon1020** [comment]
My environment is as follows:
```
OS: Ubuntu 22.04.4 LTS (x86_64) 
Docker: version 25.0.4
```

**Comment by champon1020** [comment]
This is my gist
https://gist.github.com/champon1020/98f8ec5e2b335ff079e63e384051a0fe

**Comment by rimolive** [comment]
Thank you and sorry for the late response. I could not reproduce the image build on my end, but all I can tell you is that jdk packages with `-headless` suffix is a minimalistic version of the jdk, so probably you won't get the troubleshooting tools (jstack, jmap, etc.) available if you install that package. This won't impact the kfp API Server component build, so you can make the change locally and build it.

Let me know if you have any additional questions, otherwise feel free to close the issue.

**Comment by champon1020** [comment]
@rimolive Thank you for investigating!
I understand installing headless pkg would not affect my local environment, and close this issue as resolved :)
