### ISSUE TITLE
[feature] upgrade metadata envoy

### ISSUE THREAD

**Issue by freefood89** [kubeflow/pipelines#10578]
### What feature would you like to see?

upgrade envoy (and config version) to a supported version

### What is the use case or pain point?

envoy 1.12 is no longer supported or patched

### Is there a workaround currently?

I've created my own image for now using 1.27. I can make a PR but I don't know enough about kfp to know how to validate that I didn't break anything

---

Love this idea? Give it a 👍.

**Comment by rimolive** [comment]
@freefood89 I made my own configuration for envoy v3 api. This is the current configuration: https://gist.github.com/rimolive/41ecf263aebef5b6ec6df7c0682e90ac

It worked, if you want to test just check if Executions and Artifacts pages aren't broken, and if artifact lineage page is still working.

If you want to contribute, just create a PR and I'll help you review.

**Comment by freefood89** [comment]
@rimolive I've created a PR! (#10589) I navigated to Executions, Artifacts, and then Lineage in Artifacts as you suggested and I see no errors in the console or network tab of chrome dev tools. The run I used was "[Tutorial] DSL - Control structures"
