### ISSUE TITLE
[Discussion] Looking for way to use azure container registry images in kubeflow pipeline 

### ISSUE THREAD

**Issue by Ragavendran-Venkataraman** [kubeflow/pipelines#10593]
Link of kubeflow pipeline docs of using container component 
https://www.kubeflow.org/docs/components/pipelines/v2/components/container-components/

is there a way to pass image pull secrets for using custom docker images that are present in azure container registry.

**Comment by rimolive** [comment]
Hello! as an effort to better triage the issues from the questions and troubleshooting, we added a [discussions](https://github.com/kubeflow/pipelines/discussions) tab in the repo. Please move your topic to the new place.

/close
