### ISSUE TITLE
Bigquery component should support only export to table

### ISSUE THREAD

**Issue by hongye-sun** [kubeflow/pipelines#1060]
It requires to output to GCS path today. We need to allow only output to a table.

**Comment by Ark-kun** [comment]
Is there a component that can "download" the data from BigQuery?

**Comment by hongye-sun** [comment]
Download from bigquery is not scalable if the data is bigger than 10M. https://cloud.google.com/bigquery/docs/writing-results#downloading_and_saving_query_results

It's recommended to export data to table or GCS. It's low priority to me to support download to local disk unless we have new inputs from user.

**Comment by Ark-kun** [comment]
> It's recommended to export data to table or GCS.

I'd consider that "downloading".

OK. So, I've looked at the doc and here are the important parts:

> Downloading query results to a local file is not supported by the command-line tool or the API. Download query results as a CSV or newline-delimited JSON file by using the web UI...
> Saving query results to Google Sheets is not supported by the command-line tool or the API. Save query results to Google Sheets by using the web UI...
> Saving query results to Google Drive is not supported by the command-line tool, the API, or the classic BigQuery web UI. Save query results to Google Drive by using the GCP Console...
> 
> You cannot export table data to a local file, to Google Sheets, or to Google Drive. The only supported export location is Cloud Storage. For information on saving query results, see Downloading and saving query results.
> You can export up to 1 GB of table data to a single file. If you are exporting more than 1 GB of data, use a wildcard to export the data into multiple files. When you export data to multiple files, the size of the files will vary.

**Comment by vicaire** [comment]
Hi Hongye, I don't understand the issue very well. Could you please provide more details?
