### ISSUE TITLE
[bug] Please stop using gcr.io/google-containers, k8s.gcr.io

### ISSUE THREAD

**Issue by BenTheElder** [kubeflow/pipelines#10615]
### Environment

https://github.com/kubeflow/pipelines/blob/c3869137d0e55f69f447d5d684a4a85bc7078166/backend/src/cache/server/mutation.go#L170

https://github.com/kubeflow/pipelines/blob/c3869137d0e55f69f447d5d684a4a85bc7078166/samples/core/resource_ops/resource_ops.py#L39

### Steps to reproduce

Search repo for gcr.io/google-containers, k8s.gcr.io, both of which are deprecated and not supported by the Kubernetes project (and note that GCR is deprecated by AR and shutting down next year).

Kubernetes provides https://registry.k8s.io (with lots of Google work / funding 👋) as the currently supported, fully community controlled host. Please switch.

### Labels

---

Impacted by this bug? Give it a 👍.

**Comment by rimolive** [comment]
Hello! as an effort to better triage the issues from the questions/discussions and troubleshooting, we added a [discussions](https://github.com/kubeflow/pipelines/discussions) tab in the repo. Please move your topic to the new place.

/close

**Comment by BenTheElder** [comment]
> Hello! as an effort to better triage the issues from the questions/discussions and troubleshooting, we added a [discussions](https://github.com/kubeflow/pipelines/discussions) tab in the repo. Please move your topic to the new place.

Hi @rimolive, this is a bug report, not a question or troublshooting ...?

**Comment by HumairAK** [comment]
definitely agree, this should stay open

/reopen

**Comment by AndersBennedsgaard** [comment]
Still relevant

**Comment by BenTheElder** [comment]
note: you can directly replace the host with registry.k8s.io, we have carried forward all images to date.

gcr.io/google-containers -> registry.k8s.io
k8s.gcr.io -> registry.k8s.io
