### ISSUE TITLE
[bug] Step in UI was completed, but didn't run at all

### ISSUE THREAD

**Issue by asaff1** [kubeflow/pipelines#10623]
### Environment
AWS EKS
kubeflow 1.0.4

### Steps to reproduce
Sometimes in the pipeline kubeflow will show that the step was run, while in fact it did not run. Retry won't work in that case.
See here:
![image](https://github.com/kubeflow/pipelines/assets/18662769/ce6d4ce0-c6e3-4da8-8a4c-520d953fc031)
The step that did not run is above the failed "reports" step.  (this is why the reports step was failed, it relies on the outputs of the train step).
It is also quite weird that for this failed "train" step kubeflow doesn't show "results were taken from cache" - unlike other steps that did run successfully.
The other steps that did run, show that "results taken for cache" - no idea why, these steps were fully run. What cache what used here? Can you explain how can I debug this? I don't want any cache for my runs. 
This is happening randomly. Don't know exactly why this happens. I can clone the entire run and then it will succeed.  (kind of random..). Where can I check why the step didn't run?

### Expected result
The step should not shown as like it was run.

### Labels

---

Impacted by this bug? Give it a 👍.

**Comment by rimolive** [comment]
Hello! as an effort to better triage the issues from the questions and troubleshooting, we added a [discussions](https://github.com/kubeflow/pipelines/discussions) tab in the repo. Please move your topic to the new place.

/close

**Comment by asaff1** [comment]
@rimolive The discussions tab is empty... no one is active there.
Can someone here can provide help for such issues? 
I am really stuck with these pipelines not running, and I don't know which component in kubeflow I need to look at.

**Comment by rimolive** [comment]
@asaff1 I'll just post here but we should keep interactions through the Discussions tab. The Discussions tab is recently enabled as per https://github.com/kubeflow/pipelines/pull/10557.

As you posted a question during the weekend, then people will probably answer your questions during their working hours, as the contributors are doing volunteering work or they work for their companies to maintain Kubeflow. 

At last, let's keep the discussion in the Discussions tab.
