### ISSUE TITLE
[bug] Integration test failed after the 2.1.0 release commit

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/pipelines#10629]
### Environment

*  How do you deploy Kubeflow Pipelines (KFP)?
Running unit tests on 2.1.0 branch
*  KFP version:
2.1.0
*  KFP SDK version:
2.7.0

### Steps to reproduce
After the 2.1.0 release, all the API integration tests are failing which causes all the current backend PRs to fail too.
e.g. `FAIL github.com/kubeflow/pipelines/backend/src/common/client/api_server/v1`

Before the [2.1.0 release commit](https://github.com/kubeflow/pipelines/commit/f328f0b588c35cdf1e5b31638fbe3596b2f38413), the backend API didn't change and the integration test works fine.

### Labels

---

Impacted by this bug? Give it a 👍.

**Comment by Tomcli** [comment]
Hi @chensun, the 2.1.0 release commit updated the backend API package, but the integration test is not updated to test again the new changes. So right now all the backend PRs are failing at the integration tests.
https://github.com/kubeflow/pipelines/commit/f328f0b588c35cdf1e5b31638fbe3596b2f38413

**Comment by chensun** [comment]
I commented on https://github.com/kubeflow/pipelines/pull/10631#issuecomment-2024333086
