### ISSUE TITLE
Unable to use DockerRunner()

### ISSUE THREAD

**Issue by juansebastiani2cat** [kubeflow/pipelines#10624]
### Environment

*  How do you deploy Kubeflow Pipelines (KFP)?
I have deployed Kubeflow Pipelines using a K3S environment and only installing KFP. 
*  KFP version:

When using "`$kfp version`" I get the following: 

The 'kfp-server-api<2.1.0,>=2.0.0' distribution was not found and is required by kfp

*  KFP SDK version:

However, when I run `$pip list | grep kfp` I get the following:

```
kfp                      2.7.0      
kfp-pipeline-spec        0.3.0      
kfp-server-api           2.1.0   
```
### Steps to reproduce
```
from kfp import local
from kfp import dsl

local.init(runner=local.DockerRunner(),
            pipeline_root='/home/pipelines_code')

@dsl.component
def add(a: int, b: int) -> int:
    return a + b

# run a single component
task = add(a=1, b=2)
assert task.output == 3

# or run it in a pipeline
@dsl.pipeline
def math_pipeline(x: int, y: int, z: int) -> int:
    t1 = add(a=x, b=y)
    t2 = add(a=t1.output, b=z)
    return t2.output

pipeline_task = math_pipeline(x=1, y=2, z=3)
assert pipeline_task.output == 6
```

I ran the code and I get the following error: 

> docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))

### Expected result

The pipeline should be ran locally, create a docker container and run the code inside, save the output files in the pipeline_root and confirm it with the exception. 

### Materials and reference

I followed this tutorial: 

https://www.kubeflow.org/docs/components/pipelines/v2/local-execution/

### Labels

---

Impacted by this bug? Give it a 👍.

**Comment by connor-mccarthy** [comment]
This looks like a Docker configuration issue.

@juansebastiani2cat, can you confirm you have Docker installed and that you can connect to it outside of KFP (e.g., `docker run alpine echo 'Hello World'`)? If so, can you also confirm that you're able to use the Docker Python SDK to do the same?

```python
import docker

client = docker.from_env()
output = client.containers.run("alpine", ["echo", "Hello World"])
print(output.decode("utf-8"))
```

**Comment by juansebastiani2cat** [comment]
Hello,

```
$ docker run alpine echo 'Hello World'
Hello World

```
I've saved the Python code in a file named `docker_testing.py`

When I run (inside a virtual environment): `$ python3 docker_testing.py `

I get: 
`docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
`
However, when I run it as sudo: `$ sudo python3 -m docker_testing.py ` I get: 

```
$ sudo python3 -m docker_testing.py 
Hello World

/usr/bin/python3: Error while finding module specification for 'docker_testing.py' (ModuleNotFoundError: __path__ attribute not found on 'docker_testing' while trying to find 'docker_testing.py')
```
Don't quite understand the last line about the error finding the module specification, but it seems to be working when running it as sudo right ?

**Comment by rimolive** [comment]
So running your pipeline code with `sudo` should work as well. I can't find any limitations about python virtualenv and docker, but it seems the best solution so far.
