### ISSUE TITLE
[backend] API updates for v2.1.0 release causing CI/Unit Test failures

### ISSUE THREAD

**Issue by gmfrasca** [kubeflow/pipelines#10630]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)? N/A
*  KFP version: 2.1.0
*  KFP SDK version: 2.7.0

### Steps to reproduce
For one, `go test -v ./backend/...` produces many compile errors

### Expected result
Unit tests should not fail due to compilation errors

Impacted by this bug? Give it a 👍.

**Comment by Tomcli** [comment]
Duplicate of #10629, but I guess we created at the same time.

**Comment by chensun** [comment]
Let's dedupe to the oldest bug.
