### ISSUE TITLE
[feature]  Mounting emptyDir option on kfp v2 workflow-task using kfp-kubernetes

### ISSUE THREAD

**Issue by harshad16** [kubeflow/pipelines#10656]
### Feature Area

/area sdk 

### What feature would you like to see?

In `kfp-kubernetes` SDK can we include `add_volume` function.
as in the kfp dsl, we had the option in kfp v1 https://github.com/kubeflow/pipelines/blob/f80bfd4e07565f0a95ccebcf5abd8e9a7ae2627f/sdk/python/kfp/deprecated/dsl/_container_op.py#L934
Use case is to have an option to volumes to the workflow tasks.

### What is the use case or pain point?

In (kfp v2) kfp-kubernetes only provides the `add_pvc` and `mount_pvc` options.
As currently , there is no option to mount ,  `emptyDir`
secretes and configmaps can be mounted separately. 

https://github.com/kubeflow/pipelines/blob/master/kubernetes_platform/python/kfp/kubernetes/volume.py

### Is there a workaround currently?

No. 
use older deprecated version.

---

Love this idea? Give it a 👍.

**Comment by gregsheremeta** [comment]
not stale ... i'm working on it

**Comment by thesuperzapper** [comment]
It looks like there is a PR to add this important feature in https://github.com/kubeflow/pipelines/pull/10913, but I am not sure about its status.

Can one of @gregsheremeta @hbelmiro @droctothorpe @rimolive confirm what we need to do to get that merged?

**Comment by gregsheremeta** [comment]
> confirm what we need to do to get that merged?

We need one of the Google maintainers to review it. Chen is out until July 22. It doesn't appear that Connor works on this project anymore.

**Comment by haiminh2001** [comment]
Hi all, can I ask when will these feature be released ? And I expect that this feature only requires me to update my python KFP SDK, is that true?

**Comment by gregsheremeta** [comment]
The change requires both a backend update and an SDK update. The project doesn't currently have a fixed release schedule, but I'll ask about the next release at this week's KFP community meeting (tomorrow, Wednesday August 28 at 1PM US Eastern Time, [agenda](http://bit.ly/kfp-meeting-notes))

**Comment by haiminh2001** [comment]
@gregsheremeta great! Thank you.

**Comment by gregsheremeta** [comment]
Update from the meeting: @chensun is ready to to both backend and SDK releases. There's currently a failing test blocking him, but as soon as that's fixed, they should be out. I don't have an ETA but shouldn't be too long.

**Comment by gregsheremeta** [comment]
> I don't have an ETA but shouldn't be too long.

https://github.com/kubeflow/pipelines/issues/11148

**Comment by haiminh2001** [comment]
@gregsheremeta thank you for your update.
