### ISSUE TITLE
[bug] Kfp-kubernetes SDK missing modules in package

### ISSUE THREAD

**Issue by harshad16** [kubeflow/pipelines#10653]
### Environment

The kfp-kubernetes sdk package available on pypi , is missing the module function:
```
from kfp.kubernetes.pod_metadata import add_pod_label
from kfp.kubernetes.pod_metadata import add_pod_annotation
from kfp.kubernetes.image import set_image_pull_secrets
```
which is described in here:
https://github.com/kubeflow/pipelines/blob/sdk-2.7.0/kubernetes_platform/python/kfp/kubernetes/__init__.py

*  KFP SDK version: `2.7.0` 
* KFP-Kubernetes SDK version: `1.1.0`

### Steps to reproduce

1. Install kfp-kubernetes package from pypi, either pip install or download the tar 
https://pypi.org/project/kfp-kubernetes/#files
2. Inspect the tar: kfp>kubernetes > __init.py
3. see that the above modules are missing:

```
from kfp.kubernetes.pod_metadata import add_pod_label
from kfp.kubernetes.pod_metadata import add_pod_annotation
from kfp.kubernetes.image import set_image_pull_secrets
```

### Expected result

Package has all modules specified here: https://github.com/kubeflow/pipelines/blob/sdk-2.7.0/kubernetes_platform/python/kfp/kubernetes/__init__.py

### Materials and reference

https://pypi.org/project/kfp-kubernetes/#files
https://github.com/kubeflow/pipelines/blob/sdk-2.7.0/kubernetes_platform/python/kfp/kubernetes/__init__.py

### Labels

 /area SDK 

Seems like either there has not been a new release or some how it goes missed in past release. 

Impacted by this bug? Give it a 👍.

**Comment by rimolive** [comment]
/close

As per #10685, kfp-kubernetes 1.2.0 was just released and it includes all these functions.
