### ISSUE TITLE
[Docs] Update documents from using kubectl apply -k to kustomize 5.0.4

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/pipelines#10664]
> > Can users still use kubectl apply -k .?
> 
> @rawc0der I want to confirm users can still use kubectl apply -k after this PR. This is not a blocker for this PR. I just want to make sure we are going to address the documentations after this PR is merged.

The latest `kubectl` release comes with kustomize 5.0.4, so probably the best is change it to use `kustomize build` instead of `kubectl apply -k`. cc @juliusvonkohout

_Originally posted by @rimolive in https://github.com/kubeflow/pipelines/issues/10087#issuecomment-2037526021_

**Comment by rimolive** [comment]
Closing this issue as #10864 is merged.

/close
