### ISSUE TITLE
vertex ai component doesn't support kfp 2.x

### ISSUE THREAD

**Issue by raihan1khan** [kubeflow/pipelines#10674]
# Vertex Pipelines
import google.cloud.aiplatform as aiplatform
from typing import NamedTuple
import kfp
from kfp import dsl
from kfp.dsl import (
    Artifact,
    Dataset,
    Input,
    InputPath,
    Model,
    Output,
    OutputPath,
    Metrics,
    ClassificationMetrics,
    Condition,
    component,
)

from kfp import compiler

from google.cloud import aiplatform as vertex_ai
from google_cloud_pipeline_components import aiplatform as vertex_ai_components
from kfp.google.client import AIPlatformClient as VertexAIClient

Error
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[18], line 29
     26 from kfp import compiler
     28 from google.cloud import aiplatform as vertex_ai
---> 29 from google_cloud_pipeline_components import aiplatform as vertex_ai_components
     30 from kfp.google.client import AIPlatformClient as VertexAIClient

File /opt/conda/lib/python3.10/site-packages/google_cloud_pipeline_components/aiplatform/__init__.py:18
     16 import os
     17 from google.cloud import aiplatform as aiplatform_sdk
---> 18 from google_cloud_pipeline_components.aiplatform import utils
     19 try:
     20   from kfp.v2.components import load_component_from_file

File /opt/conda/lib/python3.10/site-packages/google_cloud_pipeline_components/aiplatform/utils.py:27
     25 import kfp
     26 from kfp import components
---> 27 from kfp.components import structures
     29 # prefix for keyword arguments to separate constructor and method args
     30 INIT_KEY = 'init'

ImportError: cannot import name 'structures' from 'kfp.components' (/opt/conda/lib/python3.10/site-packages/kfp/components/__init__.py)

**Comment by connor-mccarthy** [comment]
The v2 `google-cloud-pipeline-components` SDK and v2 `kfp` SDK are compatible with one another.

**Comment by raihan1khan** [comment]
@connor-mccarthy - Original issue occur from this components, what replaces `aiplatform.CustomContainerTrainingJobRunOp` in `google-cloud-pipeline-components` V2

Example - https://github.com/GoogleCloudPlatform/fraudfinder/blob/main/vertex_ai/06_formalization.ipynb
  # custom training job component - script
    train_model_op = vertex_ai_components.CustomContainerTrainingJobRunOp(
        display_name=JOB_NAME,
        model_display_name=MODEL_NAME,
        container_uri=IMAGE_URI,
        staging_bucket=bucket_name,
        dataset=dataset_create_op.outputs["dataset"],
        base_output_dir=bucket_name,
        args=ARGS,
        replica_count=replica_count,
        machine_type=machine_type,
        training_fraction_split=train_split,
        validation_fraction_split=val_split,
        test_fraction_split=test_split,
        model_serving_container_image_uri=MODEL_SERVING_IMAGE_URI,
        project=project_id,
        location=region,
    ).after(dataset_create_op)
