### ISSUE TITLE
[feature] Create 1.2.0 release for the kfp-kubernetes SDK

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/pipelines#10685]
### Feature Area
There are many features added into the kfp-kubernetes SDK since the last release. We would like to have a 1.2.0 kfp-kubernetes SDK release to unblock many of the community users.

### Is there a workaround currently?

---

Love this idea? Give it a 👍.

**Comment by Tomcli** [comment]
/assign @connor-mccarthy 
@connor-mccarthy Can you create the 1.2.0 kfp-kubernetes SDK release? Thank you.
fyi @rimolive

**Comment by Tomcli** [comment]
fix #10673

**Comment by rimolive** [comment]
Fix #10653

**Comment by rimolive** [comment]
/close

`kfp-kubernetes==1.2.0` has just released.
Pypi website: https://pypi.org/project/kfp-kubernetes/1.2.0/
Documentation: https://kfp-kubernetes.readthedocs.io/en/kfp-kubernetes-1.2.0/source/kubernetes.html

How to upgrade?
```
$ pip install --upgrade kfp[kubernetes]
```
