### ISSUE TITLE
[sdk] Custom `base_image` and `dsl.component` breaks imports

### ISSUE THREAD

**Issue by aliaksei-shlemiankou-unity** [kubeflow/pipelines#10686]
### Environment

*  KFP version: v2
*  KFP SDK version: 2.7.0
*  All dependencies version:
```
cachetools==5.3.3
certifi==2024.2.2
charset-normalizer==3.3.2
click==8.1.7
Deprecated==1.2.14
docker==6.1.3
docstring_parser==0.16
google-api-core==2.18.0
google-auth==2.27.0
google-cloud-appengine-logging==1.4.3
google-cloud-audit-log==0.2.5
google-cloud-bigquery==3.20.1
google-cloud-core==2.4.1
google-cloud-dataproc==5.9.3
google-cloud-firestore==2.16.0
google-cloud-logging==2.7.1
google-cloud-secret-manager==2.19.0
google-cloud-storage==2.16.0
google-crc32c==1.5.0
google-resumable-media==2.7.0
googleapis-common-protos==1.63.0
grpc-google-iam-v1==0.12.7
grpcio==1.62.1
grpcio-status==1.62.1
idna==3.6
kfp==2.7.0
kfp-kubernetes==1.1.0
kfp-pipeline-spec==0.3.0
kfp-server-api==2.0.5
kubernetes==26.1.0
oauthlib==3.2.2
packaging==24.0
proto-plus==1.23.0
protobuf==4.24.4
pyasn1==0.6.0
pyasn1_modules==0.4.0
python-dateutil==2.9.0.post0
python-dotenv==0.21.1
PyYAML==6.0.1
requests==2.31.0
requests-oauthlib==2.0.0
requests-toolbelt==0.10.1
rsa==4.9
six==1.16.0
smart-open==5.2.1
tabulate==0.9.0
urllib3==1.26.18
websocket-client==1.7.0
wrapt==1.16.0
```

### Steps to reproduce
Create a base docker image with the following dependencies (see pip freeze). 

```

@kfp.dsl.component(
    base_image="my_custom_docker_image:latest",
    install_kfp_package=False,
)
def foo():
    import kfp
    print(kfp.Client)
```

```
deploymentSpec:
    executors:
      exec-trigger-op:
        container:
          args:
            - '--executor_input'
            - '{{$}}'
            - '--function_to_execute'
            - trigger_op
          command:
            - sh
            - '-ec'
            - >
              program_path=$(mktemp -d)


              printf "%s" "$0" > "$program_path/ephemeral_component.py"

              _KFP_RUNTIME=true python3 -m
              kfp.dsl.executor_main                        
              --component_module_path                        
              "$program_path/ephemeral_component.py"                        
              "$@"
            - |+
 ```

### Expected result

Success. 

### Received
Import errors since the env_variable `_KFP_RUNTIME` is set to true even though the base_image has everything installed.
Current error is `AttributeError: module 'kfp' has no attribute 'Client'`, but this does happen with lots of other attributes. 
I suppose it's connected with [that](https://github.com/kubeflow/pipelines/commit/cf0e0cf87c7a33f906e2bc31da8c5356ed75a831) feature release.

### Expected:
Usable component with pre-built base image or least being able to set the `_KFP_RUNTIME` env variable by myself (when needed) and not have it hardcoded [here]
(https://github.com/kubeflow/pipelines/blob/ac399315e66d6ed2666dc9dbaecbce4938f87356/sdk/python/kfp/dsl/component_factory.py#L481) when using my own base_image with installed KFP and other dependencies. 

### Materials and Reference
See the expected part. 

### Mitigation scenario
Note that the reload is called first to dsl, only after to kfp since otherwise circular imports are encountered. 

```
@kfp.dsl.component(
    base_image="my_custom_docker_image:latest",
    install_kfp_package=False,
)
def foo():
    import importlib
    import os

    import kfp
    from kfp import dsl

    os.environ['_KFP_RUNTIME'] = 'false'
    importlib.reload(dsl)
    importlib.reload(kfp)
```

Impacted by this bug? Give it a 👍.

**Comment by droctothorpe** [comment]
Running into the same exact issue.

**Comment by cbartram** [comment]
Also hitting this exact issue

**Comment by moorthy156** [comment]
Same, hitting the same issue
