### ISSUE TITLE
what replaces `aiplatform.CustomContainerTrainingJobRunOp` in `google-cloud-pipeline-components` V2?

### ISSUE THREAD

**Issue by raihan1khan** [kubeflow/pipelines#10681]
### Environment
Original issue occur from this components, what replaces `aiplatform.CustomContainerTrainingJobRunOp` in `google-cloud-pipeline-components` V2

Example - https://github.com/GoogleCloudPlatform/fraudfinder/blob/main/vertex_ai/06_formalization.ipynb
  # custom training job component - script
    train_model_op = vertex_ai_components.CustomContainerTrainingJobRunOp(
        display_name=JOB_NAME,
        model_display_name=MODEL_NAME,
        container_uri=IMAGE_URI,
        staging_bucket=bucket_name,
        dataset=dataset_create_op.outputs["dataset"],
        base_output_dir=bucket_name,
        args=ARGS,
        replica_count=replica_count,
        machine_type=machine_type,
        training_fraction_split=train_split,
        validation_fraction_split=val_split,
        test_fraction_split=test_split,
        model_serving_container_image_uri=MODEL_SERVING_IMAGE_URI,
        project=project_id,
        location=region,
    ).after(dataset_create_op)
*  KFP version:

*  KFP SDK version: 

*  All dependencies version:

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

**Comment by rimolive** [comment]
Please open a [Discussion thread](https://github.com/kubeflow/pipelines/discussions) for asking questions. Issues are for bug fixes and feature requests.

/close

**Comment by raihan1khan** [comment]
@rimolive - i did opened a discussion question can you please take a look
