### ISSUE TITLE
[bug] Kfp-kubernetes SDK missing options for kubernetes_executor_config

### ISSUE THREAD

**Issue by rkpattnaik780** [kubeflow/pipelines#10687]
### Environment

The kfp-kubernetes sdk when installed via pypi doesn't contain the following options:
1. "image_pull_policy" field.
2. Registration of the `Toleration` message type.

These options are defined in: https://github.com/kubeflow/pipelines/blob/master/kubernetes_platform/proto/kubernetes_executor_config.proto#L31-L36

* KFP SDK version: 2.7.0
* KFP-Kubernetes SDK version: 1.1.0

### Steps to reproduce

1. Install kfp-kubernetes from pypi.
2. Inspect the file `kfp/kubernetes/kubernetes_executor_config_pb2.py`.
3. You should be able to see that `image_pull_policy` property and `Toleration` type are not mentioned.

### Expected result

Installed package should have all options as mentioned in: https://github.com/kubeflow/pipelines/blob/master/kubernetes_platform/proto/kubernetes_executor_config.proto#L31-L36

### Materials and Reference
* https://pypi.org/project/kfp-kubernetes/#files
* https://github.com/kubeflow/pipelines/blob/master/kubernetes_platform/proto/kubernetes_executor_config.proto#L31-L36

Impacted by this bug? Give it a 👍.

**Comment by rimolive** [comment]
/close

As per #10685, kfp-kubernetes 1.2.0 was just released and it includes image pull policy.
