### ISSUE TITLE
[bug] AttributeError: 'PythonComponent' object has no attribute 'platform_config'

### ISSUE THREAD

**Issue by nutmilk10** [kubeflow/pipelines#10697]
I am running this code in a local and kubeflow notebook server, with python versions Python 3.10.9, Python 3.11.5 respectively. Here are the libraries.
kfp==2.7.0
kfp-kubernetes==1.1.0
kfp-pipeline-spec==0.3.0
kfp-server-api==2.0.5
kubernetes==25.3.0

When I run my code, I get this error: 
```
File ~/miniconda3/lib/python3.11/site-packages/kfp/kubernetes/common.py:21, in get_existing_kubernetes_config_as_message(task)
     19 def get_existing_kubernetes_config_as_message(
     20         task: 'PipelineTask') -> pb.KubernetesExecutorConfig:
---> 21     cur_k8_config_dict = task.platform_config.get('kubernetes', {})
     22     k8_config_msg = pb.KubernetesExecutorConfig()
     23     return json_format.ParseDict(cur_k8_config_dict, k8_config_msg)

AttributeError: 'PythonComponent' object has no attribute 'platform_config'
```

```
from kfp import dsl
from kfp import compiler
from kfp import kubernetes

@dsl.component
def read_data():
    import pandas as pd
    df = pd.read_csv('sample.csv')
    return df


@dsl.pipeline
def my_pipeline():
    """My ML pipeline."""
    kubernetes.mount_pvc(read_data, pvc_name="data-rw", mount_path="/data-rw")
    return read_data().output

compiler.Compiler().compile(my_pipeline, package_path='pipeline.yaml')
```

Impacted by this bug? Give it a 👍.

**Comment by rimolive** [comment]
/close

This code is not correct in terms of kfp DSL. Please take a look at the [Kubeflow quickstart](https://www.kubeflow.org/docs/components/pipelines/v2/installation/quickstart/) to understand the concepts. To use PVCs, take a look at the [pipeline_with_volume sample](https://github.com/kubeflow/pipelines/blob/master/samples/v2/pipeline_with_volume.py)
