### ISSUE TITLE
Not writing to a file in a notebook server after running kubeflow pipeline

### ISSUE THREAD

**Issue by nutmilk10** [kubeflow/pipelines#10691]
I created a kubeflow pipeline where I try to connect to a notebook server volume that contains a file called "file.txt". My pipeline should be writig "Hello World" to that file, but when I check the file on the notebook server its empty, though the pipeline runs without any issues.
*  KFP version: KFP v1

`
from kfp import components, dsl, compiler

@components.create_component_from_func
def write_to_volume():
    with open("/mnt/file.txt", "w") as file:
       file.write("Hello world")

@dsl.pipeline(
    name="volumeop-basic",
    description="A Basic Example on VolumeOp Usage."
)
def volumeop_basic(size: str="1Gi"):
    vop = dsl.VolumeOp(
        name="data-rw",
        resource_name="data-rw",
        modes=dsl.VOLUME_MODE_RWO,
        size=size,
        generate_unique_name  = False,
        action='apply',
    )

    write_to_volume().add_pvolumes({"/home/jovyan/data-rw": vop.volume})

kfp.compiler.Compiler().compile(volumeop_basic, 'my_pipeline.yaml')
`

Impacted by this bug? Give it a 👍.

**Comment by rimolive** [comment]
Can you test with KFP v2?

**Comment by nutmilk10** [comment]
> Can you test with KFP v2?

Unfortunately, havent been able to get KFP v2 to work, only v1. Keep getting invalid spec: templates.pipeline must have at least one task.

KFP v1 yaml
`
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: volumeop-basic-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.22, pipelines.kubeflow.org/pipeline_compilation_time: '2024-04-11T10:44:50.280847',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "A Basic Example on VolumeOp
      Usage.", "inputs": [{"default": "1Gi", "name": "size", "optional": true, "type":
      "String"}], "name": "volumeop-basic"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.22}
spec:
  entrypoint: volumeop-basic
  templates:
  - name: data-rw
    resource:
      action: apply
      manifest: |
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: volumeop-basic-bkb2f-resource-name-test0505-1
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: '{{inputs.parameters.size}}'
    inputs:
      parameters:
      - {name: size}
    outputs:
      parameters:
      - name: data-rw-manifest
        valueFrom: {jsonPath: '{}'}
      - name: data-rw-name
        valueFrom: {jsonPath: '{.metadata.name}'}
      - name: data-rw-size
        valueFrom: {jsonPath: '{.status.capacity.storage}'}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: volumeop-basic
    inputs:
      parameters:
      - {name: size}
    dag:
      tasks:
      - name: data-rw
        template: data-rw
        arguments:
          parameters:
          - {name: size, value: '{{inputs.parameters.size}}'}
      - name: write-to-volume
        template: write-to-volume
        dependencies: [data-rw]
        arguments:
          parameters:
          - {name: data-rw-name, value: '{{tasks.data-rw.outputs.parameters.data-rw-name}}'}
  - name: write-to-volume
    container:
      args: []
      command:
      - sh
      - -ec
      - |
        program_path=$(mktemp)
        printf "%s" "$0" > "$program_path"
        python3 -u "$program_path" "$@"
      - |
        def write_to_volume():
            with open("/mnt/file.txt", "w") as file:
               file.write("Hello world")

        import argparse
        _parser = argparse.ArgumentParser(prog='Write to volume', description='')
        _parsed_args = vars(_parser.parse_args())

        _outputs = write_to_volume(**_parsed_args)
      image: python:3.7
      volumeMounts:
      - {mountPath: /home/jovyan/data-rw, name: data-rw}
    inputs:
      parameters:
      - {name: data-rw-name}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/component_spec: '{"implementation": {"container":
          {"args": [], "command": ["sh", "-ec", "program_path=$(mktemp)\nprintf \"%s\"
          \"$0\" > \"$program_path\"\npython3 -u \"$program_path\" \"$@\"\n", "def
          write_to_volume():\n    with open(\"/mnt/file.txt\", \"w\") as file:\n       file.write(\"Hello
          world\")\n\nimport argparse\n_parser = argparse.ArgumentParser(prog=''Write
          to volume'', description='''')\n_parsed_args = vars(_parser.parse_args())\n\n_outputs
          = write_to_volume(**_parsed_args)\n"], "image": "python:3.7"}}, "name":
          "Write to volume"}', pipelines.kubeflow.org/component_ref: '{}'}
    volumes:
    - name: data-rw
      persistentVolumeClaim: {claimName: '{{inputs.parameters.data-rw-name}}'}
  arguments:
    parameters:
    - {name: size, value: 1Gi}
  serviceAccountName: pipeline-runner
`

kfp2 yaml
`
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.22, pipelines.kubeflow.org/pipeline_compilation_time: '2024-04-11T14:37:42.788593',
    pipelines.kubeflow.org/pipeline_spec: '{"inputs": [{"name": "func", "type": "typing.Callable"}],
      "name": "Pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.22}
spec:
  entrypoint: pipeline
  templates:
  - name: pipeline
    dag:
      tasks: []
  arguments:
    parameters:
    - {name: func}
  serviceAccountName: pipeline-runner

`
