### ISSUE TITLE
[sdk] remove `kfp.deprecated` namespace

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/pipelines#10715]
### Overview

The `kfp.deprecated` Python namespace in the KFP v2 SDK versions does not work.

If you attempt to use it after running `pip install kfp==2.7.0` on a clean python install, it will not have the dependencies required to actually run the `kfp.deprecated` code, you will get import errors like `ModuleNotFoundError: No module named 'uritemplate'`.

If you actually install all the dependencies, you will still run into an error which means you can never submit a run, `AttributeError: module 'kfp_server_api' has no attribute 'V2beta1PipelineVersionReference'` (see https://github.com/kubeflow/pipelines/issues/9803).

It's confusing to include a broken namespace, can we either fix it, or remove it entirely?

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

**Comment by therc** [comment]
I have some fixes in https://github.com/kubeflow/pipelines/pull/11109

Please don't remove it (yet).

**Comment by gregsheremeta** [comment]
fixed in #11366 (thanks @chensun )

/close
