### ISSUE TITLE
usage reporting link broken 

### ISSUE THREAD

**Issue by IronPan** [kubeflow/pipelines#1073]
![image](https://user-images.githubusercontent.com/2348602/55310115-8b9e5780-5414-11e9-86eb-5cf55c79d253.png)

link to https://www.kubeflow.org/docs/guides/usage-reporting/ which is not available anymore

**Comment by rileyjbauer** [comment]
Talked with @ajayalfred and @avdaredevil and decided it makes sense to just remove this link entirely for now since KFP itself no longer runs spartakus.

This is addressed in #1074
