### ISSUE TITLE
[sdk] Relax `python_requires` in `setup.py`

### ISSUE THREAD

**Issue by AndersBennedsgaard** [kubeflow/pipelines#10738]
### Environment

*  KFP version: 2.1.0 (not relevant)
*  KFP SDK version: 2.7.0
*  All dependencies version:
   ```text
   kfp                      2.7.0
   kfp-pipeline-spec        0.3.0
   kfp-server-api           2.0.5
   ```

### Steps to reproduce

I tried to install `kfp` using Poetry, where I've set the allowed Python versions to `python = "^3.11.0"`. However, this results in an `version solving failed` error since 3.13.0 is allowed in that range, but isn't allowed by `kfp`:

https://github.com/kubeflow/pipelines/blob/c967d9f7df0bec5827cdf45ea02d3463d8b17aff/sdk/python/setup.py#L102

As new minor versions of Python should be backwards compatible, there is no real reason for setting an upper limit to the Python version to `<3.13.0`.

### Expected result

`poetry add kfp` doesn't return an error, since `python_requires='>=3.7.0' is used`

As a workaround I can set `kfp = { version = "^2.7.0", python = ">=3.7,<3.13.0" }` to force Poetry to figure out the highest allowed Python version, but we shouldn't have to do this.

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

**Comment by AndersBennedsgaard** [comment]
Still relevant

**Comment by zeinalii** [comment]
any updates on this?
