### ISSUE TITLE
Replacement of components with "@graph_component" decorator in V2

### ISSUE THREAD

**Issue by rimolive** [kubeflow/pipelines#10748]
/area sdk
/kind feature

### Discussed in https://github.com/kubeflow/pipelines/discussions/10717

<div type='discussions-op-text'>

<sup>Originally posted by **cs-gennadiy** April 21, 2024</sup>
Please advise or correct me in following Use Case:

With kfp V1:

1. _**componentA**_: submits spark application by container with `kubectl apply -f spark_app_manifest.yml` to spark operator
2. _**componentB**_ (task inner to **_componentC_**): gets application state by `kubectl get SparkApplication myApp ...`
3. **_componentC_** (with "@graph_component" decorator): creates and runs task from _**componentB**_. Checks application state - if it isn't equal to "COMPLETED", then runs itself recursively.

With kfp V2:

the "@graph_component" decorator doesn't  exist, so there is no way to run a task recursively. A workaround would be to implement "get and check state" loop, like "while" loop, inside of the same component function or command (E.g. using of "dsl.If" wouldn't be possible then).

Is my assumption for V2 correct?

 </div>

**Comment by J1635** [comment]
Do we have any update on whether the graph_component will be available in v2?
