### ISSUE TITLE
Migrate presubmit tests to GH Actions

### ISSUE THREAD

**Issue by rimolive** [kubeflow/pipelines#10746]
## Description

As part of the [main tracker issue](https://github.com/kubeflow/pipelines/issues/10744), we need to migrate [presubmit tests](https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml) to GH Actions.

### Acceptance Criteria
* Need to be able to run locally (preferrable using KinD)
* Need to implement artifact generation ([workflow example](https://github.com/kubeflow/pipelines/blob/master/.github/workflows/backend.yml#L76), and [script example](https://github.com/kubeflow/pipelines/blob/master/scripts/deploy/github/helper-functions.sh#L252)

Impacted by this bug? Give it a 👍.

**Comment by pratikkumar-mohite** [comment]
I would like to work on this, if no one is working, please assign

**Comment by liavweiss** [comment]
Hey, regarding the presubmit tests, does the "tests" mean all the presubmit tests that are still not on Git Hub action?
- presubmit-tests-tfx.sh 
- presubmit-tests-sdk.sh
- presubmit-tests-with-pipeline-deployment.sh
- presubmit-yapf-sdk.sh
 ?

**Comment by liavweiss** [comment]
I'm interested in working on this issue, I am waiting for an answer to the question above.
/assign

**Comment by liavweiss** [comment]
ok thanks for the answer, /unassign

**Comment by sky0walker99** [comment]
I’d like to contribute to this issue and work on the remaining test migration. I will refer to #11048 as suggested. Please let me know if there are any additional details or steps I should follow before getting started.
/assign

**Comment by hbelmiro** [comment]
@sky0walker99 thank you for trying to contribute. But this was already done.

/close
