### ISSUE TITLE
TensorBoard artifact should be visible before the step is completed

### ISSUE THREAD

**Issue by dhodun** [kubeflow/pipelines#1075]
Potentially related to #959 
https://github.com/kubeflow/pipelines/issues/959

My container has output the Tensorboard artifact info to the local filesystem before training starts. I have a long training job (8 hours) and would like to see Tensorboard link displayed before the training completes. I already know the GCS source directory, so tensorboard can be opened immediately after training begins.

**Comment by Ark-kun** [comment]
@hongye-sun 
This could be fixed if we add "Tensorboard logs" output to the components that support TB. (We'll also need artifact passing support.)

This way, the UX can see that the running task has an output of type "Tensorboard logs" and can see where the logs are being placed to show the artifact.
Same with all other artifacts, actually.

**Comment by martin-laurent** [comment]
Any update on this? It's been a year!

**Comment by Ark-kun** [comment]
What a coincidence
I've just created a workaround component for this. https://github.com/kubeflow/pipelines/pull/3760

```
tensorboard_op = load-component_from_url('https://raw.githubusercontent.com/kubeflow/pipelines/0f4037231fd8a5a163a568d3876d1be0c5da30a6/components/tensorflow/tensorboard/prepare_tensorboard/component.yaml')

def my_pipeline():
    tensorboard_task = tensorboard_op(log_dir_uri=...)
    train_op(log_dir_uri=tensorboard_task.outputs['log_dir_uri'],...)
```

This way you can see the tensorboard even before the training starts.

**Comment by dhodun** [comment]
Cool! Still curious if we can solve the underling issue so user doesn't have to create a separate step.

**Comment by dcyoung** [comment]
@Ark-kun thanks for the component. Is it possible to use this strategy with volumes created in the pipeline? If so, could you provide a snippet that demonstrates how to use this with volumes? Something along the lines of...

```python
    model_vol_op = dsl.VolumeOp(
        name="modelpvc",
        resource_name="modelpvc",
        size="100Mi",
        modes=dsl.VOLUME_MODE_RWO,
    )

    tensorboard_task = tensorboard_op(log_dir_uri=???)
    train_op(
      log_dir_uri=? #tensorboard_task.outputs['log_dir_uri'],
      ...
    ).add_pvolumes({"/mnt": model_vol_op.volume})

```

**Comment by Ashwin-Ramesh2607** [comment]
@Ark-kun That's a neat script to use tensorboard with a training pipeline. I would like to know whether I can use GCS bucket path for the `log_dir_uri` field?

**Comment by HelmiGH** [comment]
@Ark-kun is the component you created supports a PVC  in the log_dir_uri field ?
