### ISSUE TITLE
[frontend] incompatible error while building frontend image

### ISSUE THREAD

**Issue by YuriJin-Unity** [kubeflow/pipelines#10770]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?

N/A
*  KFP version: 

N/A

### Steps to reproduce

Git clone this repo with the master branch (the last commit e9d687690bea2d88263ca331d049cb6c68495f02)
Build the frontend image
`docker build -t frontend:latest -f frontend/Dockerfile .  `

Error:

> #14 451.5 [2/4] Fetching packages...
> #14 469.3 error @aws-sdk/credential-providers@3.567.0: The engine "node" is incompatible with this module. Expected version ">=16.0.0". Got "14.21.3"
> #14 469.3 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> #14 469.3 error Found incompatible module.

### Expected result

Build the docker image successfully

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

**Comment by YuriJin-Unity** [comment]
There was a similar issue in the past, but it was resolved in v2.0.0
https://github.com/kubeflow/pipelines/issues/9804

**Comment by YuriJin-Unity** [comment]
After upgrading some components below, the image was built successfully. If there are no issues with this version, why not upgrade?
- node 14.21.3 -> 18.0.0
- craco/craco 6.2.0 -> 7.0.0

**Comment by orfeas-k** [comment]
@YuriJin-Unity Is this getting backported to 2.2.0?
