### ISSUE TITLE
[frontend] Pipeline status unknown, cannot fetch

### ISSUE THREAD

**Issue by tomaszstachera** [kubeflow/pipelines#10789]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
* https://awslabs.github.io/kubeflow-manifests/release-v1.7.0-aws-b1.0.3/docs/deployment/vanilla/guide/
*  KFP version: 
* build version dev_local (https://awslabs.github.io/kubeflow-manifests/release-v1.7.0-aws-b1.0.3/docs/deployment/vanilla/guide/)

### Steps to reproduce

Run a lot of pipelines (few thousands for few months), also I did a mysql db migration from one PVC to another due to full disk.

### Expected result

Proper pipeline status and graphs shown.

### Materials and Reference

Screenshots:

<img width="2546" alt="ppln_status_unknown1" src="https://github.com/kubeflow/pipelines/assets/61825692/513c56a7-1e43-4108-aeca-0bedd94080c9">

<img width="2549" alt="ppln_status_unknown2" src="https://github.com/kubeflow/pipelines/assets/61825692/9c910cb7-3376-4c6c-976a-cdcddcbff429">

Other pipelines started from recurring run show proper status. Few started manually show unknown status.

Impacted by this bug? Give it a 👍.

**Comment by HumairAK** [comment]
@tomaszstachera thanks, can you peak at the logs from the server/ui/persistent-agent pods when the failures occur, do you notice any errors?

**Comment by tomaszstachera** [comment]
Issue disappeared without any changes. This can be closed.
