### ISSUE TITLE
Connect local notebook to remote Pipeline cluster

### ISSUE THREAD

**Issue by IronPan** [kubeflow/pipelines#1079]
Currently if a Jupyter notebook runs locally, the DSL doesn't know the host name of the pipeline cluster. It assumes the pipeline is accessible through a port-forwarded local port, and it uses localhost:8080/pipeline/* to connect to the Pipeline server. 

This doesn't work in case of the cluster is accessible only through IAP or basic auth. 

Instead, the notebook should direct the traffic to the right hostname, following by the steps below

1. Run kubectl -n kubeflow port-forward service/ml-pipeline 8888:8888   
   (as opposed to kubectl port-forward svc/ambassador -n ${NAMESPACE} 8080:80)
2. Modify Client() if you aren't running in cluster run the following kubectl command to get the ingress end point  
    * e.g. shell out to 
      kubectl -n kubeflow get ingress -o jsonpath='{.items[0].spec.rules[0].host}')

The ingress endpoint will look like https://kf-vmaster-n01.endpoints.kubeflow-ci-deployment.cloud.goog/pipeline/#/runs/details/247f400d-5660-11e9-81a3-42010a8e00c8

**Comment by kevinbache** [comment]
related: #780, #590

**Comment by vicaire** [comment]
Resolving in favor of https://github.com/kubeflow/pipelines/issues/780 (support to run notebooks locally)
