### ISSUE TITLE
Avoid depending on port-forwarded ambassador service

### ISSUE THREAD

**Issue by IronPan** [kubeflow/pipelines#1080]
Kubeflow is moving away from ambassador, in favor of istio, and proxy the cluster using cloud endpoint with IAP or simple auth. In both cases, we should use the ingress endpoint instead of depending on port-forwarding to access the cluster.

**Comment by kevinbache** [comment]
somewhat related: #1104, #780

**Comment by jlewi** [comment]
@IronPan @vicaire How's this coming? Are you on track to have this ready for 0.6?

**Comment by IronPan** [comment]
@jingzhang36 I remember you are working on istio integration. How is it going?
@jlewi Just to double check. I think we agreed that despite istio integration, we always leave user an option to not install istio, and can do port-forwarding. Is that something that still align with your thinking?

**Comment by IronPan** [comment]
Instruction to depend on the IAP endpoint
https://github.com/amygdala/examples/blob/cookbook/cookbook/pipelines/notebooks/kfp_remote_deploy.ipynb

**Comment by jlewi** [comment]
@IronPan I think we discussed this offline. ISTIO or a service mesh is a requirement. If users want to customize the ISTIO gateway config to disable auth to allow port-forwarding they can do that. This would require editing various config files to disable AuthZ at the ISTIO gateway.

**Comment by jlewi** [comment]
@IronPan Is this done?

**Comment by IronPan** [comment]
@jingzhang36 Do you have any update on this?
@hongye-sun I think we should do an evaluation on the kfp.client() when the 0.6 candidate is out. WDYT?
Let's not close this before both items above are done.

**Comment by jlewi** [comment]
@IronPan @hongye-sun I would suggest trying out master as soon as possible to see if its working.

**Comment by jlewi** [comment]
IAP should be working on master; basic auth seems to be having problems on master #3562

**Comment by jingzhang36** [comment]
Regarding istio, I feel tensorboard /data hack is no longer blocking istio since https://github.com/kubeflow/pipelines/pull/1237 is recently merged (and Gabriel's PR https://github.com/kubeflow/kubeflow/pull/3036 is already in master). Are there any other things that need to be done to complete istio integration? E.g., remove old routing rules?

**Comment by jlewi** [comment]
@IronPan Have you or someone else verified that the pipelines SDK works with IAP? I believe that was the original genesis of this issue. In particular the goal of this issue was to ensure the  could connect via the secure public endpoint of KF to pipelines from outside the cluster.

/cc @jessiezcc

**Comment by IronPan** [comment]
Verified the KFP client works well with a v0.6 KF cluster with IAP. 
Here is a code snippet that can successfully create/list experiment
```
import kfp
client=kfp.Client(namespace="kubeflow")
exp=client.create_experiment(name="commandline")
client.list_experiments()
```
