### ISSUE TITLE
Fix inconsistent Python versions between kfp and tfx

### ISSUE THREAD

**Issue by ianhellstrom** [kubeflow/pipelines#1081]
The [TFX example pipelines](https://github.com/tensorflow/tfx/tree/master/examples/chicago_taxi_pipeline) all rely on Python 2.7, whereas the [Kubeflow example](https://github.com/kubeflow/pipelines/tree/master/samples/tfx-oss) based on that pipeline uses 3.5. This is most likely due to [kfp](https://pypi.org/project/kfp/) requiring >=3.5.3. However, when compiling the example from the TFX repo, there is a `UserWarning: Running the Apache Beam SDK on Python 3 is not yet fully supported. You may encounter buggy behavior or missing features.  'Running the Apache Beam SDK on Python 3 is not yet fully supported. '`.

However, [TFX](https://pypi.org/project/tfx/) is as of now restricted to version prior to Python 3. Users who wish to use `virtualenv` (with PyPI) instead of `conda` (and direct downloads of wheels) to manage virtual environments will therefore run into version issues, which adds to the friction in adoption. A workaround I've been using is to create a KFP+TFX Docker image for the packaging, but, as I said, that makes it only more annoying for newcomers to start using immediately.

**Comment by Ark-kun** [comment]
Python2 is going out of support in 8 months (January 1, 2020). We will create an issue in the TFX repo to ask for a Python3 package release.

**Comment by IreneGi** [comment]
Python 3 tfx support here https://www.tensorflow.org/tfx/tutorials/tfx/workshop 0.13 supports python 3.5
