### ISSUE TITLE
[feature] Support S3 virtual hosted style

### ISSUE THREAD

**Issue by sanchesoon** [kubeflow/pipelines#10814]
### Feature Area

/area backend

### What feature would you like to see?
To be able use Virtual Host Style S3 protocol we should provide configuration option. Because "by default, the S3 client will use virtual hosted bucket addressing when possible."  According aws-sdk-go documentation.

### What is the use case or pain point?

Ability to switch between Virtual Host and Path Style

### Is there a workaround currently?

There is no work round for this. Because this is hardcoded https://github.com/kubeflow/pipelines/blob/master/backend/src/v2/objectstore/object_store.go#L260

---

Love this idea? Give it a 👍.

**Comment by thesuperzapper** [comment]
@sanchesoon what additional benefit would this give us?

I am pretty sure it would take a lot of work, which would be better spent on other problems which actually affect the user experience.

**Comment by sanchesoon** [comment]
@thesuperzapper It give us ability to use Virtual Host style. Not sure if here a lot work, should be just additional parameter to pass launcher (but I never did PR here) 
BTW this was fixed in argo workflow https://github.com/argoproj/pkg/pull/368/files
