### ISSUE TITLE
Retrieve the experiment during list run

### ISSUE THREAD

**Issue by IronPan** [kubeflow/pipelines#1084]
In list run page for a given experiment, it looks like the UI is sending more requests at once than needed. For a page that have 20 runs, it send 
- 1 list call to list all runs
- 20 get call to get all runs
- 20 get calls to get the same experiments

This can be a single batch request instead. 
![Screen Shot 2019-04-04 at 6 09 46 PM](https://user-images.githubusercontent.com/2348602/55597976-3361a100-5705-11e9-87a4-43da8fb40074.png)

**Comment by Ark-kun** [comment]
The logic should really be moved away from browser to the UX-backend (frontend). (Which should probably be getting all the model data in a single API call)

**Comment by vicaire** [comment]
Resolving in favor of https://github.com/kubeflow/pipelines/issues/149. Feel free to add the results of your investigation to https://github.com/kubeflow/pipelines/issues/149.
