### ISSUE TITLE
[feature] Add ability to mount self-signed certs to kfp

### ISSUE THREAD

**Issue by DharmitD** [kubeflow/pipelines#10848]
### Feature Area

/area backend

### What feature would you like to see?

Add ability to mount self-signed certificates to kfp.
### Is there a workaround currently?

---

Love this idea? Give it a 👍.

**Comment by HumairAK** [comment]
to clarify, this is about allowing CA bundles to be mounted to the launcher/executor pods since those make external connections to object store, which can be behind self signed certs
