### ISSUE TITLE
[test] periodic functional tests fail due to absence of GCP credentials

### ISSUE THREAD

**Issue by tmvfb** [kubeflow/pipelines#10851]
Not a backend but rather a testing issue, I'm not able to select any suitable labels.

Periodic functional tests currently fail as connection to GCP test cluster is not possible (https://github.com/kubeflow/pipelines/actions/runs/9247286137/job/25435904107).

I already started fixing the tests, but now I need some community input. Issues to be addressed:

1. GCP test cluster access from GitHub actions. Is there a secret in this repository that provides GCP credentials for the test cluster  that can be used with GitHub actions (possibly [GOOGLE_APPLICATION_CREDENTIALS](https://github.com/prokube-ai/pipelines/tree/master/test/kfp-functional-test))? GitHub CI is trying to access test cluster that is configured here: https://github.com/kubeflow/testing/tree/master/test-infra/kfp.
2. Prow tests [failing](https://testgrid.k8s.io/googleoss-kubeflow-pipelines#kubeflow-pipelines-periodic-functional-test). Python3.7-slim image used to run prow test ([defined here](https://github.com/prokube-ai/pipelines/blob/master/test/kfp-functional-test/kfp-functional-test.sh)) is debian-based and doesn't have `sudo`. GitHub actions need `sudo` as they run on ubuntu. Should be easily fixable by changing test code to something like this:
```bash
if command -v sudo >/dev/null 2>&1; then
    sudo apt-get update -y
    sudo apt --no-install-recommends -y -q install curl
else
    apt-get update -y
    apt --no-install-recommends -y -q install curl
fi
```

---

Impacted by this bug? Give it a 👍.

**Comment by rimolive** [comment]
The periodic funcional tests running in GitHub actions should be using the KinD cluster created by the workflow. GCP is not an option here because this is specific environment and we want to run these tests in a vendor-neutral environment.

That said, ensure that your fixes target the KinD cluster created in the workflow.

**Comment by tmvfb** [comment]
@rimolive thank you, now that makes sense to me! 

From my understanding, running the functional tests against bare kind cluster is not of any use, since we need to actually install kfp on this cluster. I tried to address this in a new PR, tested on a fork, seems to work now.
