### ISSUE TITLE
[backend] <Image `gcr.io/ml-pipeline/workflow-controller:v3.3.8-license-compliance`  is not supported for linux/arm64 paltform>

### ISSUE THREAD

**Issue by Monokaix** [kubeflow/pipelines#10856]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?

`while ! kustomize build example | kubectl apply -f -; do echo "Retrying to apply resources"; sleep 10; done`

*  KFP version: 

v1.8.0
*  KFP SDK version: 

### Steps to reproduce

1、execute `while ! kustomize build example | kubectl apply -f -; do echo "Retrying to apply resources"; sleep 10; done`
2、 failed to run image `gcr.io/ml-pipeline/workflow-controller:v3.3.8-license-compliance` , it show exec format error
### Expected result
`gcr.io/ml-pipeline/workflow-controller:v3.3.8-license-compliance`  run successfully

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

**Comment by Monokaix** [comment]
Is there any plan to build this image on linux/arm platform?

**Comment by chensun** [comment]
workflow-controller is based on Argo's image and we only add licenses info to it: https://github.com/kubeflow/pipelines/blob/609c637811e46eab2d5c9a915913a1520c979a88/third_party/argo/Dockerfile.workflow-controller#L16

You'll need to raise the ARM support request to https://github.com/argoproj/argo-workflows
