### ISSUE TITLE
[feature] Allow the ability to sort Experiments by "last run creation" 

### ISSUE THREAD

**Issue by HumairAK** [kubeflow/pipelines#10884]
### Feature Area

/area frontend
/area backend

### What feature would you like to see?

When experiments list get's rather long, would be very useful to be able to sort the experiments by "last run creation date": 

In the UI this would result in the user being able to click the "Last 5 runs" column header, and sort by this. Thus also getting rid of the "Cannot sort by this column" mouseover message. 

![image](https://github.com/kubeflow/pipelines/assets/10904967/4d24154a-1728-4bcb-b70b-e64b28828c87)

Note that this field does not currently exist in the backend api, and would need to be added. This would result in a new column on the Experiments table for which we could sort this field by. This field would need to be updated everytime a run is created, this means when: 

* a single run is manually created
* when a scheduled run is triggered

### What is the use case or pain point?

It is hard to find experiments that have had a recent run because we cannot sort by this field.

### Is there a workaround currently?

No

---

Love this idea? Give it a 👍.

**Comment by HumairAK** [comment]
@ElayAharoni we have implemented this in our downstream here: https://github.com/opendatahub-io/data-science-pipelines/commit/bf77909897738751fc58b8b5b1dd928bf264bf49 

Would you be open to rebasing over this commit for upstream?

**Comment by ElayAharoni** [comment]
@HumairAK there was a mistake, the pr that fixes this issue is #11163

**Comment by HumairAK** [comment]
whoops, I commented on the wrong issue heh
/re-open
