### ISSUE TITLE
[bug] Kubeflow Pipelines may stop working after `March 18, 2025` 

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/pipelines#10891]
We currently use a number of `gcr.io` container image repos, and if we dont take action __they may stop existing__ on `March 18, 2025`. You can see a notice [on the top of all `gcr.io` repos](https://console.cloud.google.com/gcr/images/ml-pipeline/GLOBAL/frontend), and Google has published this [migration guide](https://cloud.google.com/artifact-registry/docs/transition/prepare-gcr-shutdown) which implies that if we don't explicitly migrate to Artifact Registry before `May 22, 2025` the images will be deleted.

We need to confirm that all `gcr.io` accounts which we depend on are going to continue existing (have migrated all images to Artifact Registry), or create a migration and communication plan for users BEFORE next year.

The `gcr.io` repos we currently use are:

- [`gcr.io/ml-pipeline/*`](https://console.cloud.google.com/gcr/images/ml-pipeline/GLOBAL/)
    - This one has almost all KFP images in it.
- [`gcr.io/tfx-oss-public/ml_metadata_store_server`](https://console.cloud.google.com/gcr/images/tfx-oss-public/GLOBAL)
    - This one is the official home of the [`google/ml-metadata`](https://github.com/google/ml-metadata) images.
- [`gcr.io/google-containers/busybox`](https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/busybox)
     - __NOTE:__ this one is probably the most likely to disappear unless we can get confirmation from a Google employee about the status of `gcr.io/google-containers`.
     - This one disappearing would stop pipelines from running cached steps, because we use this image to run a simple `echo` command for cached outputs (see https://github.com/kubeflow/pipelines/pull/5184)

---

Impacted by this bug? Give it a 👍.

**Comment by KevinGrantLee** [comment]
cc @chensun

**Comment by thesuperzapper** [comment]
Bumping because this issue is still not fixed, and even once we do fix it for new versions, old KFP versions will break after that date.

**Comment by chensun** [comment]
> [gcr.io/ml-pipeline/*](https://console.cloud.google.com/gcr/images/ml-pipeline/GLOBAL/)

This was migrated to Artifact Registry, thanks to @PaulinaPacyna' help.

> [gcr.io/tfx-oss-public/ml_metadata_store_server](https://console.cloud.google.com/gcr/images/tfx-oss-public/GLOBAL)

This I have followed up with internal TFX team and they verified this is also migrated.

> [gcr.io/google-containers/busybox](https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/busybox)

I'm not sure about this status for this one. But this is no longer a dependency for KFP v2. 

> Bumping because this issue is still not fixed, and even once we do fix it for new versions, old KFP versions will break after that date.

While the images are hosted in Artifact registry, the old `gcr.io` URL will redirect and continue working. There won't be any breakage.
