### ISSUE TITLE
RBAC: clusterrole.rbac.authorization.k8s.io "pipeline-runner" not found

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#1092]
I see some sample tests ?randomly? failing with the following error
```secrets \"mlpipeline-minio-artifact\" is forbidden: User \"system:serviceaccount:kubeflow:pipeline-runner\" cannot get secrets in the namespace \"kubeflow\": RBAC: clusterrole.rbac.authorization.k8s.io \"pipeline-runner\" not found```

Failure:
https://pantheon.corp.google.com/logs/viewer?interval=NO_LIMIT&project=ml-pipeline-test&minLogLevel=0&expandAll=false&timestamp=2019-04-05T22:08:42.928000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22ml-pipeline-test%22%0Aresource.labels.location%3D%22us-east1-b%22%0Aresource.labels.cluster_name%3D%22sample-1b33946-6227%22%0Aresource.labels.namespace_name%3D%22kubeflow%22%0Aresource.labels.pod_name%3D%22tfx-taxi-cab-classification-pipeline-example-c4r4g-708414357%22%0Aresource.labels.container_name%3D%22wait%22&scrollTimestamp=2019-04-04T20:35:30.546574100Z commit: https://github.com/kubeflow/pipelines/commit/1b3394641eb9a0870f5ef6f19626ed9a365a2838

Failure:
https://pantheon.corp.google.com/logs/viewer?interval=NO_LIMIT&project=ml-pipeline-test&minLogLevel=0&expandAll=false&timestamp=2019-04-05T22:13:57.201000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22ml-pipeline-test%22%0Aresource.labels.location%3D%22us-east1-b%22%0Aresource.labels.cluster_name%3D%22sample-1b33946-6227%22%0Aresource.labels.namespace_name%3D%22kubeflow%22%0Aresource.labels.pod_name%3D%22tfx-taxi-cab-classification-pipeline-example-59nhx-2455571170%22%0Aresource.labels.container_name%3D%22wait%22&scrollTimestamp=2019-04-04T20:34:41.775475457Z

Success:
https://pantheon.corp.google.com/logs/viewer?interval=NO_LIMIT&project=ml-pipeline-test&minLogLevel=0&expandAll=false&timestamp=2019-04-05T22:13:59.758000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22ml-pipeline-test%22%0Aresource.labels.location%3D%22us-east1-b%22%0Aresource.labels.cluster_name%3D%22sample-1b33946-6227%22%0Aresource.labels.namespace_name%3D%22kubeflow%22%0Aresource.labels.pod_name%3D%22tfx-taxi-cab-classification-pipeline-example-c4r4g-1573144304%22%0Aresource.labels.container_name%3D%22wait%22&scrollTimestamp=2019-04-04T20:34:09.000000000Z

**Comment by gaoning777** [comment]
Does this error still persist?

**Comment by gaoning777** [comment]
I cannot reproduce the error. Are you still having the issue?

**Comment by gaoning777** [comment]
Feel free to reopen
