### ISSUE TITLE
[CI] Fail the e2e tests if the image builds fail

### ISSUE THREAD

**Issue by HumairAK** [kubeflow/pipelines#10929]
If the image builds fail, the e2e tests will proceed as usual, but fail to deploy with "imagePullBackOff" states for the associated deployments. 

Relevant gh workflows: 
* https://github.com/kubeflow/pipelines/actions/runs/9599914551/workflow?pr=10787
* https://github.com/kubeflow/pipelines/actions/runs/9599914548/job/26474847944?pr=10787

**Comment by HumairAK** [comment]
Example: https://github.com/kubeflow/pipelines/actions/runs/9599914548/job/26474847944?pr=10787 

We could have notified a lot earlier for this failure

**Comment by ElayAharoni** [comment]
i think this issue is fixed by this pr https://github.com/kubeflow/pipelines/pull/11115
 i  created and was merged yesterday
