### ISSUE TITLE
[sdk] Not possible to conditionally trigger cache

### ISSUE THREAD

**Issue by AndersBennedsgaard** [kubeflow/pipelines#10959]
### Environment

*  KFP version: 2.2.0

*  KFP SDK version: 2.4.0 and 2.8.0

*  All dependencies version:

### Steps to reproduce

I was trying to trigger caching using the `.set_caching_options` field of the returned components, as explained here: https://www.kubeflow.org/docs/components/pipelines/user-guides/core-functions/caching/
However, I want to have control when it is disabled/enabled, so I tried to use something like the following:

```python
from kfp import compiler
from kfp import dsl

@dsl.component(base_image="python:3.8")
def say_hello(name: str) -> str:
    hello_text = f'Hello, {name}!'
    print(hello_text)
    return hello_text

@dsl.pipeline
def pipeline(enable_caching: bool):
    hello_task = say_hello(name="World")
    hello_task.set_caching_options(enable_caching)

compiler.Compiler().compile(pipeline, "pipeline.yaml")
```

On KFP SDK v2.8.0 this returns a TypeError: `'PipelineParameterChannel' object cannot be interpreted as an integer`
A similarly sounding error is returned on lower versions

### Expected result

It should be able to optionally trigger caching

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

**Comment by gregsheremeta** [comment]
@DharmitD looks just like 10914. Maybe we can apply a similar fix here.

**Comment by petrpechman** [comment]
I have the same bug. I want to use gpu_type and gpu_number as pipeline parameters.  
```python
@dsl.pipeline
def build_engine(
    gpu_number: int,
    gpu_type: str
):
    main_task = setup_main_task()
    main_task.set_accelerator_limit(gpu_number)
    main_task.set_accelerator_type(gpu_type)
```
Error: `TypeError: 'PipelineParameterChannel' object cannot be interpreted as an integer`

**Comment by senyuyouren** [comment]
ValueError: Pipeline parameter modelname does not match any known pipeline input.

**Comment by fountaindive** [comment]
I have this issue, is there a workaround to this?

It would be really helpful to be able to configure turning on/off caching by passing an input parameter.

**Comment by asteroth** [comment]
has there been any update on this one? It would make sense to have a parameter for the pipeline itself (not it's components). To my understanding, you can't nest components, only pipelines which means a very common usecase won't work
#### a quick pseudocode:
```python
@dsl.component
def train(model_in, model_out):
    # train a model

@dsl.component
def eval(model_in,):
    # evaluate model

@dsl.pipeline
def do_train(epochs: int):
    t1 = load_model() # task to load a model

#FAIL -  TypeError: 'PipelineParameterChannel' object cannot be interpreted as an integer
    for e in range(epochs):
        t2 = train(model_in = t1.output).after(t1)
        t1 = eval(model_in = t2.output).after(t2)
        
```
Trying to hardcode epochs inside the pipeline body does work, but the input type is channel
