### ISSUE TITLE
[sdk] unable to pip install kfp 1.8.x with recent kubernetes (>=26) python client

### ISSUE THREAD

**Issue by MichaelSkralivetsky** [kubeflow/pipelines#10967]
### Environment

*  KFP version:
1.8.22

*  KFP SDK version: 
1.8.22

*  All dependencies version:
 kubernetes==26.1.0

### Steps to reproduce

pip install kubernetes==26.1.0 kfp==1.8.22
ERROR: Cannot install kfp==1.8.22 and kubernetes==26.1.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested kubernetes==26.1.0
    kfp 1.8.22 depends on kubernetes<26 and >=8.0.0

### Expected result

expecting latest kfp 1.8 to support more recent kubernetes client

Impacted by this bug? Give it a 👍.

**Comment by rimolive** [comment]
kfp 1.8 is a very old release and it won't support latest kubernetes client.

You should upgrade to the latest releases of kfp.
