### ISSUE TITLE
[bug] Cannot reuse the same components in different nested pipelines

### ISSUE THREAD

**Issue by roytman** [kubeflow/pipelines#10969]
### Environment

*  How do you deploy Kubeflow Pipelines (KFP)?
OpenShift AI
*  KFP version:
rhods-operator.2.10.0, 

*  KFP SDK version:
kfp                       2.7.0
kfp-kubernetes            1.2.0
kfp-pipeline-spec         0.3.0
kfp-server-api            2.0.5

### Steps to reproduce
Create a pipeline with 2 nested pipelines that reuse the same components. When the pipeline is deployed, only one nested pipeline shows the inner components, the second one is empty, see the picture. 

### Expected result

These nested pipelines should show all their inner components and be independent. 

### Materials and reference

```python
import kfp.compiler as compiler
import kfp.dsl as dsl

@dsl.component(base_image='python:3.10')
def square(x: float) -> float:
    return x ** 2

@dsl.component(base_image='python:3.10')
def add(x: float, y: float) -> float:
    return x + y

@dsl.component(base_image='python:3.10')
def square_root(x: float) -> float:
    return x ** .5

@dsl.pipeline
def square_and_sum(a: float, b: float) -> float:
    a_sq_task = square(x=a)
    b_sq_task = square(x=b)
    return add(x=a_sq_task.output, y=b_sq_task.output).output

@dsl.pipeline
def another_square_and_sum(a: float, b: float) -> float:
    a_sq_task = square(x=a)
    b_sq_task = square(x=b)
    return add(x=a_sq_task.output, y=b_sq_task.output).output

@dsl.pipeline
def pythagorean(a: float = 1.2, b: float = 1.2) -> float:
    sq_and_sum_task = square_and_sum(a=a, b=b)
    sq_and_sum_task2 = another_square_and_sum(a=a, b=b)
    if sq_and_sum_task.output == sq_and_sum_task2.output:
        return square_root(x=sq_and_sum_task.output).output
    else:
        return -1.0

if __name__ == "__main__":
    # Compiling the pipeline
    compiler.Compiler().compile(pythagorean, __file__.replace(".py", ".yaml"))
```

<img width="595" alt="image" src="https://github.com/kubeflow/pipelines/assets/1816654/9e7d2ffa-cc79-4905-9fd0-ce7bd6797a62">

### Labels

---

Impacted by this bug? Give it a 👍.

**Comment by zazulam** [comment]
May be related: https://github.com/kubeflow/pipelines/issues/10039

**Comment by roytman** [comment]
Hi, I don't think the issues are related, we just used the same sample. 
I changed the code so it doesn't depend on outputs, and now it looks like a UI issue. I do see the execution of the components and pipelines, but the UI shows it wrong.

The updated code:
```python
import kfp.compiler as compiler
import kfp.dsl as dsl

@dsl.component(base_image='python:3.10')
def square(x: float) -> float:
    return x ** 2

@dsl.pipeline
def check_square(a: float):
    square(x=a)

@dsl.pipeline
def another_check_square(a: float):
    square(x=a)

@dsl.pipeline
def dummy_pipeline(a: float = 1.1):
    pipeline1 = check_square(a=a)
    another_check_square(a=3.0).after(pipeline1)

if __name__ == "__main__":
    compiler.Compiler().compile(dummy_pipeline, __file__.replace(".py", ".yaml"))
```

This is the UI view 
<img width="298" alt="image" src="https://github.com/kubeflow/pipelines/assets/1816654/06910039-0c3d-4b49-aeac-b30e2eef8333">

In addition, the UI behavior is wrong, when I try to enter into the nested pipelines.

**Comment by roytman** [comment]
I retried the code with the opensource kubeflow and it works as expected, so I assume it is an OpenShiftAI issue. Closing it here. 
CC: @HumairAK
