### ISSUE TITLE
Samples should load explicit versions of component definitions.

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#1098]
Currently, samples load components from master.

**Comment by jessiezcc** [comment]
@Ark-kun, can you explain why this is P0?
/cc @gaoning777

**Comment by Ark-kun** [comment]
This was P0, because the issue was bound to cause forward compatibility issues (old pipeline version using latest component versions). Fortunately, this issue has been fixed long time ago and sample pipelines pin component versions.
