### ISSUE TITLE
Fix /data routing hack for TensorBoard

### ISSUE THREAD

**Issue by jlewi** [kubeflow/pipelines#1100]
The pipelines UI currently has an Ambassador route which maps all traffic to "/data" back to the pipelines UI so that it can be routed to TensorBoard.
https://github.com/kubeflow/kubeflow/blob/35c725e7e969099473c693d4f8098a996f6e6c91/kubeflow/pipeline/pipeline-ui.libsonnet#L67

This was a hack to make pipelines work when it was initially installed as part of Kubeflow back in November.

Summary of meeting from @yebrahim 

>
- Current state of affairs is we have an Ambassador route mapping hack to make absolute requests to /data from Tensorboard be handled by the Pipelines service, which knows how to proxy them back to the right TB pod. This is a hack, but it works for now.
- There is a jsonnet config here that seems to be working properly even though it's behind a /tensorboard base URL. Jeremy has that deployed in a cluster too. I'll look into why this works and the Pipeline UI setup doesn't.
- It would be great to have a Tensorboard management service (with UI?), so that users can start instances given only the logdir(s) by calling its APIs. The Pipelines UI does this currently, but it would be nice to isolate that from Pipelines, and have a Kubeflow component manage that.
- Central storage isn't needed for such management service, all it needs to do is encode the provided logdir(s) in the Tensorboard pod/deployment annotations, then it can use those to query/manage new pods/deployments. (This is what the Pipelines UI does btw, except that it encodes the logdir(s) in the pod args.)

Does it suffice to extract the logic in k8s-helper into a standalone service? We can modify it to use the working Tensorboard config mentioned above.

In 0.6 we will be moving to ISTIO so we will need to fix this is part of moving from Ambassador to ISTIO.

**Comment by neuromage** [comment]
Can we close this in favour of #1026? @ajayalfred and @rileyjbauer are working on a UI for employing the Tensorboard viewer for this. 

The move to ISTIO (replacing Ambassador) is still a valid point, and we will have to migrate Viewer CRD as well when that happens.

**Comment by jingzhang36** [comment]
Do we have a rough road map on how to migrate to ISTIO? If resolving /data hack is part of this migration, I am wondering what are the rest and trying to see if there is anything I can help with.

**Comment by gabrielwen** [comment]
@jingzhang36  [this is](bit.ly/kf-istio-integration) is the ISTIO migration plan.  We are roughly at half way and currently migrating ambassador annotations to ISTIO traffic management.

@lluunn

**Comment by gabrielwen** [comment]
@jingzhang36 @IronPan any updates on this?

Also note that kubeflow/kubeflow#3036 is ready for review.  That routing rule should follow what you've decided.

**Comment by jingzhang36** [comment]
Thank you @gabrielwen

**Comment by jlewi** [comment]
@jingzhang36 Any update on this?

**Comment by jingzhang36** [comment]
@jlewi I have a PR under review for this https://github.com/kubeflow/pipelines/pull/1237.  I am doing a test of this PR by using my local built image on ml-pipeline-ui pod. The problem I ran into during the test is that calling methods  on the custom object client tends to hang forever. I am still trying to figure out the reason of it.

**Comment by vicaire** [comment]
@jingzhang36, can we close this issue?

**Comment by jlewi** [comment]
@jingzhang36 Is there any more work to do here or can we close this?

Kubeflow master should be working with ISTIO and kustomize so you could try deploying from master and verifying that everything is working. With ISTIO I don't believe we ported over the "/data" hack we were using with Ambassador.

**Comment by jlewi** [comment]
According to @jingzhang36 this is fixed. Pipelines is now using their TensorBoard CRD.
https://github.com/kubeflow/pipelines/pull/1237
