### ISSUE TITLE
[backend] module 'kfp' has no attribute 'auth'

### ISSUE THREAD

**Issue by jaffe-fly** [kubeflow/pipelines#11003]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
use manifests 
*  KFP version: 
2.2.0
*  KFP SDK version: 
2.7.0

### Steps to reproduce
```
import kfp

# the namespace in which you deployed Kubeflow Pipelines
namespace = "kubeflow"

# the KF_PIPELINES_SA_TOKEN_PATH environment variable is used when no `path` is set
# the default KF_PIPELINES_SA_TOKEN_PATH is /var/run/secrets/kubeflow/pipelines/token
credentials = kfp.auth.ServiceAccountTokenVolumeCredentials(path=None)

client = kfp.Client(host=f"http://ml-pipeline-ui.{namespace}", credentials=credentials)

print(client.list_experiments())
```

https://www.kubeflow.org/docs/components/pipelines/user-guides/core-functions/connect-api/#full-kubeflow-subfrom-inside-clustersub

**Comment by Yael-F** [comment]
Hey @jaffe-fly 
The ServiceAccountTokenVolumeCredentials class is located in the kfp.client.set_volume_credentials module.
Here’s how you can modify your code to use the correct import path:

`from kfp.client.set_volume_credentials import ServiceAccountTokenVolumeCredentials
credentials = ServiceAccountTokenVolumeCredentials(path=None)`
