### ISSUE TITLE
Pipelines switch to kustomize

### ISSUE THREAD

**Issue by jlewi** [kubeflow/pipelines#1101]
In 0.6 Kubeflow will be replacing ksonnet since its been deprecated. 

We are currently evaluating kustomize and adding kustomize support to kfctl.

kustomize manifests are being added here:
https://github.com/kubeflow/manifests

pipelines should ideally migrate off ksonnet in 0.6. This means migrating the package configs to the config manager chosen to replace ksonnet (we are currently evaluating kustomize).

In addition, pipelines will need to figure out how to migrate its current upgrade story to work with the new config manager.

/cc @IronPan

**Comment by gabrielwen** [comment]
After kubeflow/manifests#106 pipeline YAMLs should look exactly the same as YAMLs from KSONNET.

**Comment by jlewi** [comment]
@IronPan @vicaire Is anyone working on this?

**Comment by jlewi** [comment]
@IronPan @vicaire ping? Have you taken a look at the manifest in
https://github.com/kubeflow/manifests/tree/master/pipeline

Is there more work to be done there?

**Comment by jlewi** [comment]
We probably need to pin the images to whatever version we want to release in 0.6.

**Comment by IronPan** [comment]
I think we can ping version 0.1.23 and do a test. 
/assign @rileyjbauer doing release for .23

**Comment by elikatsis** [comment]
Please take a look at #1570 before cutting the release.

**Comment by elikatsis** [comment]
And also kubeflow/manifests#186.
I'm quite confused regarding what will be used for the deployment of 0.6.

**Comment by jlewi** [comment]
@elikatsis What is your confusion?

**Comment by jlewi** [comment]
kubeflow/manifests#184 updates pipelines to the latest images.

**Comment by elikatsis** [comment]
@jlewi, Thank you for answer Jeremy.

I'm not quite sure what's the purpose of `manifests/` in this repo, since `kubeflow/manifests` exist. Is it used at all or it is to be deprecated?

**Comment by jlewi** [comment]
@elikatsis [kubeflow/pipelines/manifests](https://github.com/kubeflow/pipelines/tree/master/manifests) is a separate kustomize package the pipelines team is maintaining to address additional use cases.

kubeflow/manifests/pipelines is the primary kustomize package used by Kubeflow to deploy pipelines.

Closing this since the manifests have been updated and merged.
