### ISSUE TITLE
[sdk] Environment variables of pipeline ignored in local execution

### ISSUE THREAD

**Issue by vanHavel** [kubeflow/pipelines#11030]
### Environment

*  KFP version: 2.2.0
*  KFP SDK version: 2.8.0
*  All dependencies version:
```
kfp                                2.8.0
kfp-kubernetes                     1.2.0
kfp-pipeline-spec                  0.3.0
kfp-server-api                     2.0.5
```

### Steps to reproduce

Minimal example: 
```
from kfp import dsl, local
from kfp.dsl import PipelineTask


@dsl.component
def return_env() -> str:
    import os
    return os.environ["FOO"]

@dsl.pipeline(
    name="pipeline",
    description="A pipeline that returns the environment variable FOO",
)
def pipeline() -> str:
    task: PipelineTask = return_env()
    task.set_env_variable("FOO", "bar")
    return task.output

if __name__ == "__main__":
    local.init(runner=local.DockerRunner())
    result = pipeline()
    print(result.output)
```

### Expected result

Environment variables defined in the pipeline are set using local execution.

### Workarounds

For `SubprocessRunner`, there is a workaround by adapting `os.environ` with the same variables that are set in the pipeline.
For `DockerRunner`, no workaround is known.

Impacted by this bug? Give it a 👍.

**Comment by stacymiller** [comment]
I have the same situation with
```
kfp==2.9.0
docker==7.1.0
```

Given this, I don't how to test new tasks locally, especially if they're running in custom built containers.
