### ISSUE TITLE
Move kubeflow-pipelines-manifests to GitHub Actions

### ISSUE THREAD

**Issue by hbelmiro** [kubeflow/pipelines#11051]
As part of the https://github.com/kubeflow/pipelines/issues/10744, we need to migrate [kubeflow-pipelines-manifests](https://issues.redhat.com/browse/RHOAIENG-10367#L70]) to GH Actions.

The output of this issue is:

- The new GitHub workflow created and passing
- The existing Prow configuration removed from https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

You can use the following PRs as a reference:

- https://github.com/kubeflow/pipelines/pull/10926
- https://github.com/GoogleCloudPlatform/oss-test-infra/pull/2298

/area testing

---

Impacted by this bug? Give it a 👍.

**Comment by rimolive** [comment]
@hbelmiro Looks like this is done?

**Comment by hbelmiro** [comment]
Resolved by https://github.com/kubeflow/pipelines/pull/11066.
