### ISSUE TITLE
[bug] Cannot run sql commands from pyspark

### ISSUE THREAD

**Issue by gioargyr** [kubeflow/pipelines#11099]
My team wants to use py-spark in Kubeflow pipeline nodes.

This py-spark pipeline node is communicating with a completely independent MinIO instance and runs ANSI SQL commands to it.
When we create a table it succeeds, but with all the other SQL commands it fails.

The exact same container, when it is deployed independently, it has no issues communicating to the independent MinIO instance.
The errors in the logs do not help at all.
e.g.: `Py4JJavaError: An error occurred while calling o37.sql.`

I find several things online about Kubeflow pipeline nodes that cannot connect to postrgresql or issues with Spark and Kubeflow, but nothing like my case.

Can you help me, so at least I can approach this issue in a better way?

**Comment by amelendezunilu** [comment]
Hi, just adding a comment on the bug
The problem is when we try to use the library 
`from pyspark.sql import SparkSession`
the context is created with no problems, but that error shows up after trying to make a simple query of a table
