### ISSUE TITLE
[Release] KFP 2.3.0 & KFP SDK 2.9.0 release tracker

### ISSUE THREAD

**Issue by chensun** [kubeflow/pipelines#11148]
Release owner: @chensun 
Release instructions: https://github.com/kubeflow/pipelines/blob/master/RELEASE.md

Tentative release timeline: early to mid September

**Comment by chensun** [comment]
Current release blockers:

- Post-submit tests failures:
![image](https://github.com/user-attachments/assets/05770e68-5adf-4792-930e-7356df9a64c1)

**Comment by HumairAK** [comment]
I would like to propose we also get this merged in: https://github.com/kubeflow/pipelines/issues/11058 
cc @zijianjoy before we cut a release, it's a very apparent bug that users will immediately hit

**Comment by hbelmiro** [comment]
@chensun it seems like these tests are not expected to run on pushes. See, for example, https://github.com/kubeflow/pipelines/blob/71a52ab4a9cfce59bd5bc64467dce35e06eb2453/.github/workflows/kfp-sdk-runtime-tests.yml#L30 and https://github.com/kubeflow/pipelines/blob/2009dfb2f1e5b601b35165f1d13bbc432698179e/test/kfp-kubernetes-execution-tests/sdk_execution_tests.py#L113
```
AssertionError: 1 != 0 :   WARNING: Did not find branch or tag 'refs/pull//merge', assuming revision or ref.
```

I created a test PR and all tests are passing: https://github.com/kubeflow/pipelines/pull/11150

I'll take a closer look to fix them.

**Comment by hbelmiro** [comment]
@chensun it seems like we also have some flaky tests.

As a workaround, can we ignore the failing tests in the `master` branch and use [my test PR](https://github.com/kubeflow/pipelines/pull/11150) instead? Just while we fix the failing tests.
We can rebase and/or rerun the tests (with `rerun-all`) as much as needed before releasing.

If the failing tests block some automation, we can disable them from running on pushes. (Also, just while we fix them)

Please let me know if that works for you and if I need to disable them from running on pushes.

I created [this issue](https://github.com/kubeflow/pipelines/issues/11153) to track this work.

**Comment by HumairAK** [comment]
I'm not sure if this is included as part of the instructions, but please also [rebuild driver/launcher images](https://github.com/kubeflow/pipelines/blob/0e37fd66a4f15bb7ce31ecceec7421ba1bd65fd6/backend/src/v2/compiler/argocompiler/container.go#L33-L36), as these have also undergone changes.

**Comment by chensun** [comment]
> @chensun it seems like these tests are not expected to run on pushes. See, for example,
> 
> https://github.com/kubeflow/pipelines/blob/71a52ab4a9cfce59bd5bc64467dce35e06eb2453/.github/workflows/kfp-sdk-runtime-tests.yml#L30
> 
> and
> https://github.com/kubeflow/pipelines/blob/2009dfb2f1e5b601b35165f1d13bbc432698179e/test/kfp-kubernetes-execution-tests/sdk_execution_tests.py#L113
> 
> ```
> AssertionError: 1 != 0 :   WARNING: Did not find branch or tag 'refs/pull//merge', assuming revision or ref.
> ```
> 
> I created a test PR and all tests are passing: #11150
> 
> I'll take a closer look to fix them.

Thank you for the investigation. It sounds good to me to ignore the failure and unblock the release. I can probably do the release tomorrow.

**Comment by chensun** [comment]
Release notes:
https://github.com/kubeflow/pipelines/releases/tag/2.3.0
https://github.com/kubeflow/pipelines/releases/tag/sdk-2.9.0
