### ISSUE TITLE
[bug] Move test-run-all-gcpc-modules to GitHub Actions

### ISSUE THREAD

**Issue by hbelmiro** [kubeflow/pipelines#11154]
`test-run-all-gcpc-modules` [is timing out on Prow](https://github.com/kubeflow/pipelines/pull/11079#issuecomment-2313223678). It seems to be an infra issue.
It's preventing PRs from being merged.

- https://github.com/kubeflow/pipelines/pull/11147
- https://github.com/kubeflow/pipelines/pull/11079
- https://github.com/kubeflow/pipelines/pull/11142

By migrating it to GitHub Actions we fix it.

The output of this issue is:

- The new GitHub workflow created and passing
- The existing Prow configuration removed from https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

You can use the following PRs as a reference:

- https://github.com/kubeflow/pipelines/pull/10926
- https://github.com/GoogleCloudPlatform/oss-test-infra/pull/2298

These instructions for running the tests locally may be helpful: https://github.com/kubeflow/pipelines/pull/11147#issuecomment-2321327616

### Labels

/area testing

---

Impacted by this bug? Give it a 👍.

**Comment by hbelmiro** [comment]
@TheKevJames @egeucak I don't have the bandwidth to work on this right now.
Would any of you guys like to contribute with a PR?

**Comment by TheKevJames** [comment]
Currently I am also swamped, sorry. If no one gets to fixing your CI in a couple weeks, I might be able to take some time then!

**Comment by aman23bedi** [comment]
Hi all, 
Can I work on this?

**Comment by hbelmiro** [comment]
> Hi all, Can I work on this?

Sure @aman23bedi. Feel free to let me know if you need any help.
