### ISSUE TITLE
[sdk] KFP SDK prints "Built and pushed" despite push errors

### ISSUE THREAD

**Issue by OutSorcerer** [kubeflow/pipelines#11164]
### Environment

*  KFP version:
not relevant (bug only is SDK)
*  KFP SDK version: 
2.8.0
*  All dependencies version:
```
kfp                      2.8.0
kfp-pipeline-spec        0.3.0
kfp-server-api           2.0.5
docker                   7.1.0
```

```
docker --version
Docker version 26.1.2, build 211e74b
```

### Steps to reproduce

1. Try to build and push an image to a private Docker registry  without setting up registry authentication. Example command:
   ```
   kfp component build --push-image --component-filepattern component.py .
   ``` 
   (see `component.py` below)
  
2. KFP prints a message that an image was pushed successfully despite in fact pushing failed due to auth errror. Example output:

   ```
   Building component using KFP package path: kfp==2.8.0
   ...
   Built and pushed component container busybox:latest
   ```

### Expected result

`kfp` reports a error and returns a non-zero exit code.

### Materials and Reference

`component.py`:

```
from kfp import dsl

@dsl.component(
    base_image=f"busybox:latest",
    packages_to_install=["numpy"],
    target_image=f"busybox:latest",
)
def test_component():
    pass
```

---

Impacted by this bug? Give it a 👍.

**Comment by Yael-F** [comment]
Can I assign this bug on me? I'd like to contribute to it.

**Comment by rimolive** [comment]
@Yael-F only Kubeflow members can assign themselves to issues, but if you start contributing with KFP code you can request membership. More details in https://www.kubeflow.org/docs/about/contributing/#membership

**Comment by HumairAK** [comment]
> Can I assign this bug on me? I'd like to contribute to it.

Of course! 

/assign Yael-F
