### ISSUE TITLE
[sdk] <no API to add port in KFPV2>

### ISSUE THREAD

**Issue by 482170765** [kubeflow/pipelines#11174]
kfp == 2.8.0

kfp-kubernetes == 1.2.0

@dsl.component()
def server():
    ....

@dsl.pipeline()
def my_pipeline():
    server_task=server()
    server_task.add_port(V1ContainerPort(name='my-port', container_port=8080))
---> server_task.add_port(V1ContainerPort(name='my-port', container_port=8080))

AttributeError: 'PipelineTask' object has no attribute 'add_port'

In kfpv1 the code can work, but in kfpv2 'add_port' had been removed. Is there any method to add port on task ?

Impacted by this bug? Give it a 👍.

**Comment by rimolive** [comment]
Duplicated with #11184 

/close
