### ISSUE TITLE
[feature] Add support for a Google Cloud Strategy argument for create_custom_training_job_from_component

### ISSUE THREAD

**Issue by leandroni** [kubeflow/pipelines#11198]
### Feature Area

/area components

### What feature would you like to see?

Add support for defining which type of scheduling strategy to use (see [CustomJobSpec](https://cloud.google.com/vertex-ai/docs/reference/rest/v1beta1/CustomJobSpec#strategy)) via a strategy parameter on v1.custom_job.create_custom_training_job_from_component

### What is the use case or pain point?

For fault tolerant jobs, the user might prefer to use Spot resources to reduce google cloud costs.

### Is there a workaround currently?

Without this feature the user needs to create custom jobs using workerPoolSpecs, creating a container component and calling CustomTrainingJobOp.

---

Love this idea? Give it a 👍.

**Comment by gbentim** [comment]
Part of the object
https://google-cloud-pipeline-components.readthedocs.io/en/google-cloud-pipeline-components-2.18.0/api/v1/custom_job.html#v1.custom_job.CustomTrainingJobOp
