### ISSUE TITLE
[sdk] kfp-kubernetes ImagePullSecrets not working

### ISSUE THREAD

**Issue by ksgnextuple** [kubeflow/pipelines#11218]
### Environment

*  KFP version: 1.8.0

*  KFP SDK version: kfp-2.7.0

*  All dependencies version: 

        kfp                       2.7.0
        kfp-kubernetes            1.3.0
        kfp-pipeline-spec         0.3.0
        kfp-server-api            2.0.5
 
Getting the below error when using the set_image_pull_secrets function:

    F0917 12:02:28.761279      17 main.go:76] KFP driver: failed to unmarshal Kubernetes config, error: unknown field "imagePullSecret" in kfp_kubernetes.KubernetesExecutorConfig

Impacted by this bug? Give it a 👍.

**Comment by Naegionn** [comment]
Hi,
I am facing the same issue.
I found that suprisingly kfp-kubernetes did not support ImagePullSecrets initially.

My guess here is that oder version of kfp-server-api do not support it as well but i am not aware of which version is required.

On my kubeflow installation with kf 1.8 and kfp-api 2.0 i get this error. On another installation kf=1.9 kfp-api=2.2 it is working.

I would think that ImagePullSecrets to allow pulling from private registries is one of the most common features.

**Comment by AxoyTO** [comment]
I have KFP deployed with versions KFP Runtime 2.5.0, KFP SDK 2.7.0 and all other dependencies versions are the same. I don't face this issue.
