### ISSUE TITLE
Create a chore task issue template

### ISSUE THREAD

**Issue by hbelmiro** [kubeflow/pipelines#11263]
There are several issues that don't fit on the existing templates. Currently, we have only bugs and features templates. We need at least a "chore" template.

![image](https://github.com/user-attachments/assets/6785479e-f475-4598-902f-0d524cd482ec)

Impacted by this bug? Give it a 👍.

**Comment by varodrig** [comment]
please assign to me . @hbelmiro

**Comment by varodrig** [comment]
@hbelmiro  do you want a chore per area ? such as chore backend - chore frontend as the bugs templates? or just one chore  and the contributors will include the area related once creating the chore?

**Comment by hbelmiro** [comment]
> @hbelmiro do you want a chore per area ? such as chore backend - chore frontend as the bugs templates? or just one chore and the contributors will include the area related once creating the chore?

One chore is enough. I left a [suggestion](https://github.com/kubeflow/pipelines/pull/11317#discussion_r1808808123) for allowing users to specify labels, like we already do in [other templates](https://github.com/kubeflow/pipelines/blob/c2a77134265dbbe7ca8492e6e429fd3cc60b8419/.github/ISSUE_TEMPLATE/BUG_REPORT.md?plain=1#L35).
