### ISSUE TITLE
[CRUD][SDK] Need to support upload/delete of pipeline tarballs. 

### ISSUE THREAD

**Issue by mameshini** [kubeflow/pipelines#1130]
Currently Python DSL provides an API to create an experiment run, but there is no API to upload a new pipeline template from tarball file, without running it.  There is Upload pipeline API in Go, but a similar method is not available from Python:
`s.pipelineUploadClient.UploadFile("../resources/arguments-parameters.yaml", uploadParams.NewUploadPipelineParams())
`

Looks like the Python client is a wrapper around the API client, while the Go client is just the actual client.  It would be great to enable Upload and Delete of pipeline tarballs in Python as well.

**Comment by Ark-kun** [comment]
Python SDK has two clients - the auto-generated low-level API client and higher-level convenience wrapper.
At one point the pipeline upload method existed, but was removed later.

Our current vision is moving away from the "pipelines" to [pipeline] components - pipelines should become composable components just like other components. With thousands of components (in future) a plain list of all components might not be useful. 

I'd like to know the scenario where you want to upload a pipeline.

**Comment by mameshini** [comment]
The use case is to automate uploading of Pipeline templates to an existing KFP instance. Pipeline tarballs can be regularly updated by Ops team to provide data scientists with the latest templates. Automation of this process would help to ensure deployment of latest versions of pipelines and notebooks across multiple environments/clusters.  Data scientists or data engineers can use Pipeline templates to create new experiment runs and to retrain models based on new data, by providing input dataset location such as GCS or S3 bucket. In addition, data scientists can open notebooks to edit existing pipelines and create experiment runs. 

It would be great to have composable pipeline components too.

**Comment by neuromage** [comment]
Exposing the API client in Python just like we do in Go sounds like a good idea, and relatively simple to do as well. There is no reason the Python client should not have feature parity with the Go version.

**Comment by neuromage** [comment]
Would welcome community contributions for this one. The relevant code lives here:
https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/_client.py

**Comment by IronPan** [comment]
+1 we have swagger definition for all APIs. it would be really nice to have the same client apis for all language.

**Comment by Ark-kun** [comment]
Fixed in https://github.com/kubeflow/pipelines/pull/1535 and https://github.com/kubeflow/pipelines/pull/1536
