### ISSUE TITLE
[chore] ok-to-test label should run CI workflows on non Kubeflow members' PRs

### ISSUE THREAD

**Issue by DharmitD** [kubeflow/pipelines#11304]
As of now, if a non-Kubeflow member proposes a PR to the KFP repo, the CI workflow runs don't get triggered automatically on applying the `ok-to-test` label. Only repo maintainers have the permission to trigger the CI runs in this case:
![image](https://github.com/user-attachments/assets/a71da061-5f23-433a-832d-811baacf7945)

KSC would like to grow the community size so PR coming from non-members will probably be more frequent. 
As this approach isn't scalable, we need to update `ok-to-test` functionality to have CI workflows run automatically on PRs from non-members as well.

**Comment by hbelmiro** [comment]
Duplicates https://github.com/kubeflow/pipelines/issues/10981.
/close
