### ISSUE TITLE
`func_to_container_op` converting underscores to dashes

### ISSUE THREAD

**Issue by kevinbache** [kubeflow/pipelines#1135]
`func_to_container_op` is converting underscores in NamedTuple output variables to dashes

**Comment by kevinbache** [comment]
closing as dupe of #205

**Comment by Ark-kun** [comment]
I'd say this is a separate issue. Technically, the keys of the `task.outputs` dictionary can be any strings.
We could even have spaces in them.

@gaoning777 Now that the sanitization has been moved to the compiler, what do you think about allowing more free-form/human-readable output names?

**Comment by gaoning777** [comment]
I'm all for it to keep the user interface consistent.

**Comment by Ark-kun** [comment]
The naming rule change to the `func_to_container_op` (actually it was `load_component`) was done in https://github.com/kubeflow/pipelines/pull/938
