### ISSUE TITLE
Enable local test runner for Kubeflow Pipelines

### ISSUE THREAD

**Issue by neuromage** [kubeflow/pipelines#1138]
Today, there is no way to run a KFP pipeline on a local machine (outside of running a mini Kubernetes cluster locally). This makes testing pipelines for user difficult as they always have to go through the steps of uploading to a cluster to run even small tests on the correctness of the pipeline. 

To solve this problem, it would be nice if KFP offers a way to run pipelines locally. Such a mode does not have to have full fidelity with what's possible in a cluster run with Argo to begin with. A simple approach of using `docker run` to run each step sequentially, with a mounted local volume for passing parameters, will go a long way towards satisfying most local-run use-cases. 

As a suggestion, we can modify the pipeline decorator to enable this behaviour when the user adds a keyword like `test = True`, i.e.

```
@dsl.Pipeline(
   name = "..",
   test = True,
   ...
```

**Comment by vicaire** [comment]
Some ideal requirements to consider: 
- The local executor should support all the same features as execution within a GKE cluster. 
- The local executor should not duplicate the code of the controllers used to execute the pipeline. 
- The local executor should execute the yaml, not Python, so that both yaml and Python can be tested.

**Comment by Ark-kun** [comment]
>The local executor should support all the same features as execution within a GKE cluster.

I guess only the proper local kubernetes cluster can satisfy this requirement. The test environment needs Minikube installed.

**Comment by Ark-kun** [comment]
> As a suggestion, we can modify the pipeline decorator to enable this behaviour when the user adds a keyword like `test = True`, i.e.

I think it's better have a function to perform this instead of overloading the decorator:

```
kfp.run_pipeline_locally(my_pipeline, arguments={...})
```
If we want to differentiate, we can have
* run_pipeline_locally
* run_pipeline_using_docker
* run_pipeline_on_kubernetes
* run_pipeline_on_kfp

**Comment by vicaire** [comment]
BTW, what about providing users with a VM image that has all the tools installed (minikube and etc.) to make local execution easy?

**Comment by ucdmkt** [comment]
Thank you so much for tracking this issue. 

Another thing to consider is that we may want to have a way to inject a stub to a component inside the pipeline, if a component is making call to foreign services such as Dataflow.

**Comment by kevinbache** [comment]
related: #1104

**Comment by neuromage** [comment]
Closing as infeasible/obsolete for now.

**Comment by neuromage** [comment]
@Ark-kun not sure if you intentionally meant to re-open this issue? Are you working on local runner for KFP?

**Comment by Ark-kun** [comment]
> @Ark-kun not sure if you intentionally meant to re-open this issue? Are you working on local runner for KFP?

I think that your idea is still pretty valid and useful. It would be nice to have that feature for component testing and experimentation. I've recently started creating components in my free time and testing them was not that easy without having a Kubernetes cluster.
Our SDK already runs some tests in a local environment, but it would be less hacky to just use docker.
So I just wanted to keep this feature request in mind.
The priority of this is not P0 or P1 of course.

What do you think?

**Comment by rmgogogo** [comment]
FYI, I'm thinking on bring a lightweight local runner in a new design. It may rely on TFX SDK's docker launcher. It's still early investigation phase, together with IR work.

**Comment by numerology** [comment]
FYI, for testing TFX has this https://github.com/tensorflow/tfx/pull/1986 WIP.

That said it's pretty different than local dev.

**Comment by rmgogogo** [comment]
(in IR based impl, we may handle it with Docker runner)

**Comment by Bobgy** [comment]
/lifecycle frozen
we'd still want this open

**Comment by NikeNano** [comment]
Are we interested in adding instructions on how to deploy locally to Minikube based upon the local code for development @Bobgy? Will not be a big change but would require the user to build all the images and add an overlay that uses these images instead of the official released images.

**Comment by Bobgy** [comment]
@NikeNano I think that's a different topic, this issue is about creating a local runner that help experiment with KFP. Rather than developing KFP.

**Comment by lynnmatrix** [comment]
@Bobgy @Ark-kun @numerology I have create a PR trying to provide a local runner which will run Kubeflow pipeline on docker  or locally.
As @Ark-kun  suggested, `kfp.run_pipeline_func_locally(my_pipeline, arguments={...})` is picked.
