### ISSUE TITLE
[frontend] Can't get “Allow access to Kubeflow Pipelines” to appear after clicking on "Configurations"

### ISSUE THREAD

**Issue by Epochex** [kubeflow/pipelines#11489]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
Deployment via Kubeflow manifest 1.32
*  KFP version: 
KFP 2.9.0

### Steps to reproduce
![image](https://github.com/user-attachments/assets/28d1ad57-0115-46fa-8a17-3a891a73bc5c)
Nothing happens when you click on configuration
![image](https://github.com/user-attachments/assets/86c75ef8-0e76-4f6a-8aff-ee9c38acbb5e)
There is no “Allow access to Kubeflow Pipelines” button, even if the element is viewed By F12

and all other options are displayed correctly, so I think this is a pretty serious bug, **which directly leads to the inability to trigger the pipeline when all the code in the workspace tries to construct it.**

ERROR:root:Failed to read a token from file '/var/run/secrets/kubeflow/pipelines/token' ([Errno 2] No such file or directory: '/var/run/secrets/kubeflow/pipelines/token').
WARNING:root:Failed to set up default credentials. Proceeding without credentials...
ApiException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'content-type': 'application/json', 'date': 'Sat, 28 Dec 2024 23:35:32 GMT', 'content-length': '811', 'x-envoy-upstream-service-time': '3', 'server': 'envoy'})
HTTP response body: {"error":"List experiments failed: Failed to authorize with API: Failed to authorize with API: Unauthenticated: Failed to check authorization. User identity is empty in the request header: Unauthenticated: Request header error: there is no user identity header.: Request header error: there is no user identity header.","code":16,"message":"List experiments failed: Failed to authorize with API: Failed to authorize with API: Unauthenticated: Failed to check authorization. User identity is empty in the request header: Unauthenticated: Request header error: there is no user identity header.: Request header error: there is no user identity header.","details":[{"@type":"type.googleapis.com/google.rpc.Status","code":16,"message":"Failed to check authorization. User identity is empty in the request header"}]}
![image](https://github.com/user-attachments/assets/82c967d3-9303-49ef-b79d-afa2979accfe)

### Materials and Reference
https://github.com/kubeflow/pipelines/issues/11457

Impacted by this bug? Give it a 👍.

**Comment by Epochex** [comment]
```bash
root@vmi2182569:/data/mlops/manifests# grep -rl "Allow access to Kubeflow Pipelines" .
./proposals/20230323-end-to-end-testing.md
./tests/gh-actions/kf-objects/poddefaults.access-ml-pipeline.kubeflow-user-example-com.yaml
kubectl apply -f poddefaults.access-ml-pipeline.kubeflow-user-example-com.yaml
```
Allow access to Kubeflow Pipelines will appear in the Configuration.
Check the box to build the pipeline normally

**Comment by reyhanekordli** [comment]
> root@vmi2182569:/data/mlops/manifests# grep -rl "Allow access to Kubeflow Pipelines" .
> ./proposals/20230323-end-to-end-testing.md
> ./tests/gh-actions/kf-objects/poddefaults.access-ml-pipeline.kubeflow-user-example-com.yaml
> kubectl apply -f poddefaults.access-ml-pipeline.kubeflow-user-example-com.yaml
> 
> Allow access to Kubeflow Pipelines will appear in the Configuration. Check the box to build the pipeline normally


You saved my day.
Thank you so much.
