### ISSUE TITLE
Runs leaked into archived page

### ISSUE THREAD

**Issue by IronPan** [kubeflow/pipelines#1150]
All runs are now showing in archived page as well as in the all run page
![image](https://user-images.githubusercontent.com/2348602/56020408-f0cb3600-5cbb-11e9-8be5-edef35a39967.png)

Archive functionality is also broken that it does't do anything.

**Comment by rileyjbauer** [comment]
were you able to confirm that this was fixed by #1151 ?

**Comment by IronPan** [comment]
yes i'll close it
