### ISSUE TITLE
Compare experience – UX changes 

### ISSUE THREAD

**Issue by ajayalfred** [kubeflow/pipelines#117]
1. Rows selected for comparison should not display selection styling in the 'Overview' section. The checkboxes remain active and rows aren't highlighted. See below for row styling.
<img width="903" alt="screen shot 2018-11-06 at 6 56 15 pm" src="https://user-images.githubusercontent.com/2425179/48107774-ba155f00-e1f5-11e8-95ed-075eb0c81ea9.png">

2. Run overview section cannot be collapsed. Remove collapse action.

3. Parameters section table style below. Run (objects) are shown as rows, and parameters (attributes) are shown as columns. Match table font style with 'Overview' table (Roboto, 14px, for cell content)
<img width="944" alt="screen shot 2018-11-06 at 6 55 04 pm" src="https://user-images.githubusercontent.com/2425179/48107782-c4375d80-e1f5-11e8-80ed-1ce9f32f2b85.png">

4. Metrics is to be its own section and not part of overview section
<img width="755" alt="screen shot 2018-11-06 at 6 58 42 pm" src="https://user-images.githubusercontent.com/2425179/48107919-0eb8da00-e1f6-11e8-8b79-aefb80826132.png">

5. Title of the aggregate view should read "All selected runs"

6. Vertical top-align all charts in a section

**Comment by rileyjbauer** [comment]
#4 was partly completed by #1284

**Comment by rileyjbauer** [comment]
Closing in favor of #322
