### ISSUE TITLE
Feature request: Ability to edit recurring run config in UI

### ISSUE THREAD

**Issue by JohnPaton** [kubeflow/pipelines#1180]
Currently it's only possible to view and enable/disable recurring runs in the UI. It would be nice to also be able to edit them, or at least edit the trigger/schedule. 

One use case would be the adjustment of a schedule on a run with a lot of input parameters. Since there is no "create recurring run from run config" option (which would also be nice, now that I think of it), the user would have to manually input all the run parameters again in order to change the schedule.

**Comment by jonasdebeukelaer** [comment]
hey @JohnPaton I'd be interested in working on this feature, if you haven't already? @rileyjbauer is that fine with you?

**Comment by jonasdebeukelaer** [comment]
/assign @jonasdebeukelaer 
I'm currently working on this btw
