### ISSUE TITLE
Bug: Unable to delete recurring run configs in UI

### ISSUE THREAD

**Issue by JohnPaton** [kubeflow/pipelines#1181]
I currently have an experiment with a few recurring runs configured:

![image](https://user-images.githubusercontent.com/18459252/56276171-59724280-6102-11e9-8c4a-44a2501900dc.png)

If I try to delete one, I get the success message, but also an error popup saying that the delete operation failed

![image](https://user-images.githubusercontent.com/18459252/56276234-7b6bc500-6102-11e9-9a04-792ae83d1a7a.png)

For people searching, the error message is:
> #### Failed to delete recurring run config
> Failed to delete recurring run config: <config_id> with error: "Cannot read property 'configuration' of undefined"

This happens on both first and subsequent tries to delete recurring runs.

After the failed deletion attempt, the pipeline is still running on schedule, so I can confirm that it has in fact not been deleted:

![image](https://user-images.githubusercontent.com/18459252/56276496-e3221000-6102-11e9-9166-e3044644fc19.png)

I'm on Kubeflow 0.5.0 on GKE.

**Comment by rileyjbauer** [comment]
This appears to foremost be a frontend issue, so I'm unassigning IronPan for now
