### ISSUE TITLE
Feature request: Ability to hide arguments in pipeline UI

### ISSUE THREAD

**Issue by randxie** [kubeflow/pipelines#1183]
Some components have more than 15 arguments. Many of the arguments already have good defaults but we still need to expose them for more granular controls. 

However, it introduces some trouble to pipeline UI, as the UI currently does not have ability to hide arguments. In addition, we can not even separate required arguments from optional arguments in the UI. 

It will be great to provide a mechanism to hide arguments from pipeline UI, as well as a way to distinguish required arguments from optional arguments.

**Comment by Bobgy** [comment]
I think this is a subset of https://github.com/kubeflow/pipelines/issues/2621.
/close
