### ISSUE TITLE
KFP dashboard UI: run archiving doesn't seem to work

### ISSUE THREAD

**Issue by amygdala** [kubeflow/pipelines#1189]
It's cool that we can now archive runs, but it doesn't seem to quite work. 
The UI spins for a bit, but the run is still listed.

This is for the KFP version that gets installed by the current KF click-to-deploy webapp
(the KFP dashboard says 'Build commit: c938247'... should we tag with version number instead?)

**Comment by rileyjbauer** [comment]
This is likely the same as #1150 which was fixed in #1151 (7 days ago, whereas the commit you listed was merged 13 days ago).

Therefore, using a later version should resolve this issue. @IronPan is there anything else we need to do besides wait for the next release?

**Comment by vicaire** [comment]
Closing, please reopen if this is not resolved.
