### ISSUE TITLE
Will pipelines support the same behavior as `argo retry`

### ISSUE THREAD

**Issue by cheyang** [kubeflow/pipelines#1198]
I'm wondering if `pipelines` will support the behavior of `argo retry`. The benefit of doing this is to avoid rerun the successful step, only starting from the failed step without the end user input.

**Comment by vicaire** [comment]
Yes, we can support this if it is not already supported. Would you like to contribute the change?

**Comment by cheyang** [comment]
I'd like to contribute!

**Comment by vicaire** [comment]
I have assigned this item to you. Thanks!

**Comment by xiaogaozi** [comment]
@cheyang May I ask, is there any progress about this feature?

**Comment by cheyang** [comment]
I didn't have chance to work on it. @xiaogaozi , if you'd like to pick it, it will be great. Thanks.

**Comment by IronPan** [comment]
https://github.com/kubeflow/pipelines/pull/1720 should cover it.

**Comment by shotarohorai** [comment]
Is it possible to use the rerun the pipeline API (https://github.com/kubeflow/pipelines/pull/1720) from kfp?
