### ISSUE TITLE
Allocate additional space/lines for node names in pipeline graph

### ISSUE THREAD

**Issue by rileyjbauer** [kubeflow/pipelines#1205]
Nodes in the static and runtime graphs only display around 15 characters today. Users can hover over individual nodes to display the full labels as tooltips, but this is not as useful as immediately readable labels, especially if there are many.

Perhaps nodes should be made larger, vertically and/or horizontally to fit more text

**Comment by rileyjbauer** [comment]
@ajayalfred suggested wrapping the text to a second line and truncating beyond that

**Comment by Bobgy** [comment]
I have never found this a problem. @Ark-kun do you think it's still sth valuable to consider?

**Comment by Bobgy** [comment]
This has been fixed though
