### ISSUE TITLE
Pass TF-Job and/or K8 resource output from one pipeline step to another. 

### ISSUE THREAD

**Issue by cheyang** [kubeflow/pipelines#1213]
How to support `file_outputs` defined by user in  [tfjob ops](https://github.com/kubeflow/pipelines/blob/master/components/kubeflow/launcher/kubeflow_tfjob_launcher_op.py#L30)?

As we know, the user can leverage `file_outputs` in `dsl.ContainerOps` to pass the output value to next step. But it doesn't work for tfjob ops, because the tfjob-launcher is not the tfjob itself.  It should get the files back from the tfjob. But because `kubectl cp` doesn't support copying the file from the complete pod. See the issue: https://github.com/kubernetes/kubectl/issues/454

Any ideas?

**Comment by IronPan** [comment]
I think tfjob launcher is not very well maintained now. 
How about creating a volumes to pass the models and artifacts instead? The file_outputs is limited as far as I can tell.

**Comment by cheyang** [comment]
The problem is how to get the output values from the step, such as the accuracy or output file produced in the current step.

**Comment by Ark-kun** [comment]
The fundamental problem is as follows:
Component represents a function defined signature. It can have any fixed number of inputs and outputs.
Launchers can potentially launch any kind of trainer components.
A launcher with fixed signature thus has trouble to accommodate arbitrary trainer components.
There is a workaround for inputs, but currently there is no workaround for outputs.
I'm thinking on how to make it possible to launch trainers with arbitrary number of outputs, but it's not finalized.

So, for now the launcher only has a single output (plus UI metadata output pointing to that path).
