### ISSUE TITLE
When creating a notebook option to allocated .5 cpu seems odd

### ISSUE THREAD

**Issue by SinaChavoshi** [kubeflow/pipelines#1216]
https://screenshot.googleplex.com/P6bfLSv7vtt

Status	Name	Created	Image	CPU	Memory	Volumes	Actions
Scheduling Pod	apr-demo1	4 mins ago	tensorflow-2.0.0a-notebook-gpu	0.5	1.0Gi	storage

**Comment by IronPan** [comment]
just to confirm, is it odd because it's not integer?
FYI K8s support fractional request 
https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu

**Comment by SinaChavoshi** [comment]
Closing as it matches the experience on k8
