### ISSUE TITLE
Terminate run is only available on run details page

### ISSUE THREAD

**Issue by SinaChavoshi** [kubeflow/pipelines#1218]
Inconsistent user experience, i can not terminate the run from experiments or run page.

**Comment by Dhaval08** [comment]
Hello @SinaChavoshi 

Is there a way to terminate a run using the Python kfp SDK client?

Thank you.

**Comment by numerology** [comment]
It does not seem so, can you confirm? @Ark-kun 
BTW @Dhaval08 could you please elaborate more on your use case? Thanks!

**Comment by Dhaval08** [comment]
@numerology I am building a REST API using which the end user can submit runs, check run status and even terminate a run if need be.
The kfp python sdk provides client functions for creating a run and even checking its status. I am unable to figure out how to enable end suer to terminate a run, check/get logs, get artifacts.

Any help on this would be highly appreciated.
Thank you.

**Comment by Bobgy** [comment]
We can add the UI feature. Contribution welcomed
