### ISSUE TITLE
Pipeline API Server Swagger Client (Go) for Pipeline Upload returns incomplete output

### ISSUE THREAD

**Issue by vicaire** [kubeflow/pipelines#122]
The Pipeline API Server Swagger Client (Go) returns incomplete output for the pipeline.upload method. 

For instance, using the CLI in the directory:

kubeflow/pipelines/backend/src/cmd/ml

With the command: 

go run main.go pipeline --namespace kubeflow upload ./samples/hello-world.yaml --name pipleline87 -o json

We get the output: 

{
  "created_at": "0001-01-01T00:00:00.000Z",
  "parameters": null
}

**Comment by vicaire** [comment]
Raw request/response for the PIPELINE GET call: 

GET /api/v1/namespaces/kubeflow/services/ml-pipeline:8888/proxy/apis/v1beta1/pipelines/1b02b12c-21ff-4216-a610-22c6a5b9881d HTTP/1.1
Host: 35.224.113.48
User-Agent: Go-http-client/1.1
Accept: application/json
Accept-Encoding: gzip
 
 
HTTP/2.0 200 OK
Content-Length: 98
Audit-Id: d1759187-0d5f-4351-b816-1072c5a30982
Content-Type: application/json
Date: Fri, 09 Nov 2018 06:21:00 GMT
Grpc-Metadata-Content-Type: application/grpc
 
{"id":"1b02b12c-21ff-4216-a610-22c6a5b9881d","created_at":"2018-11-09T06:20:22Z","name":"toto106"}
created_at: "2018-11-09T06:20:22.000Z"
id: 1b02b12c-21ff-4216-a610-22c6a5b9881d
name: toto106
parameters: null

**Comment by vicaire** [comment]
Raw request/response for the PIPELINE UPLOAD call:

POST /api/v1/namespaces/kubeflow/services/ml-pipeline:8888/proxy/apis/v1beta1/pipelines/upload?name=toto106 HTTP/1.1
Host: 35.224.113.48
User-Agent: Go-http-client/1.1
Transfer-Encoding: chunked
Accept: application/json
Content-Type: multipart/form-data; boundary=0cf8a8d5b4b3e59d424a44a79e2ccc39362b82f6acff7d4fb621ee43f769
Accept-Encoding: gzip
 
1f8
--0cf8a8d5b4b3e59d424a44a79e2ccc39362b82f6acff7d4fb621ee43f769
Content-Disposition: form-data; name="uploadfile"; filename="hello-world.yaml"
Content-Type: application/octet-stream
 
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
--0cf8a8d5b4b3e59d424a44a79e2ccc39362b82f6acff7d4fb621ee43f769--
 
0
 
 
HTTP/2.0 200 OK
Content-Length: 98
Audit-Id: 6a849149-4d3e-4cde-b8bd-ce26a5c2179e
Content-Type: text/plain; charset=utf-8
Date: Fri, 09 Nov 2018 06:20:23 GMT
 
{"id":"1b02b12c-21ff-4216-a610-22c6a5b9881d","name":"toto106","created_at":"2018-11-09T06:20:22Z"}

**Comment by vicaire** [comment]
For PIPELINE GET, the swagger config specifies that the output is of content-type application/json

https://github.com/kubeflow/pipelines/blob/master/backend/api/swagger/pipeline.swagger.json#L15

This is correct. 

For PIPELINE UPLOAD, the swagger config specifies that the output is of content-type application/json

https://github.com/kubeflow/pipelines/blob/master/backend/api/swagger/pipeline.upload.swagger.json#L15

but the output is in fact of type text/plain

**Comment by IronPan** [comment]
fix https://github.com/kubeflow/pipelines/pull/112

**Comment by vicaire** [comment]
Looks like the fix has been checked in
