### ISSUE TITLE
sample "DSL Static Type Checking" link to types needs to be updated

### ISSUE THREAD

**Issue by SinaChavoshi** [kubeflow/pipelines#1220]
If you define the component using the function decorator, there are a list of core types. For example, the following component declares a core type Integer for input field_l while declares customized_type for its output field_n.

Core types . links to https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/dsl/_types.py

Should be : 
https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/dsl/types.py

**Comment by gaoning777** [comment]
Thanks for reporting this. 
Fixed at https://github.com/kubeflow/pipelines/pull/1221
