### ISSUE TITLE
TFX comps

### ISSUE THREAD

**Issue by animeshsingh** [kubeflow/pipelines#1231]
what does 'type' refer to in the link below? how can we specify "optional" vs "required" arguments in components.yaml? if we need to run this on TFX pipeline on KF on IBM Cloud, shall we create our own versions of TFX comps, or can we make these more generic?
@Ark-kun 
https://github.com/kubeflow/pipelines/blob/master/components/dataflow/predict/component.yaml

**Comment by Ark-kun** [comment]
>what does 'type' refer to?

Component is analogous to a function. Component has interface - the set named of inputs and outputs which are analogous to function parameters and return value[s]. Like in many languages the parameters can have types. The purpose of the specifying the input type is to prevent user errors - to prevent them from passing incompatible variables or values to a function. Same for the components. If you pass some output to other component's input and both have types, the types have to match. In future we'll also add value validation in the UX and SDK.

>how can we specify optional arguments?

What is the exact scenario that you want to implement? Can it be accomplished by specifying default values for the inputs?

>if we need to run this on KF on IBM Cloud, should we create our own versions of TFX comps, or can we make these more generic?

Can you please rephrase the question?

The `components/dataflow` are obsoleted by `components/gcp/dataflow`.
Old "TFX" will eventually be obsoleted by the components recently released by the TFX team.

**Comment by animeshsingh** [comment]
> > how can we specify optional arguments?
> 
> What is the exact scenario that you want to implement? Can it be accomplished by specifying default values for the inputs?

A component may have some parameters which are optional - if specified it behaves differently. and some a required. Taking your analogy of functions forward - some input params may or may not required.

**Comment by animeshsingh** [comment]
> > if we need to run this on KF on IBM Cloud, should we create our own versions of TFX comps, or can we make these more generic?
> 
> Can you please rephrase the question?
> 
> The `components/dataflow` are obsoleted by `components/gcp/dataflow`.
> Old "TFX" will eventually be obsoleted by the components recently released by the TFX team.

So TFX is open source, and we would like to run TFX on our cloud. The current component implementation seems tied to GCP - hence the question

**Comment by Ark-kun** [comment]
>Taking your analogy of functions forward - some input params may or may not required.

Well, in most computer languages (including Python) only the arguments with default values are optional...

> A component may have some parameters which are optional - if specified it behaves differently. and some a required.

There is some limited compile-time support for this:
https://github.com/kubeflow/pipelines/blob/b0147bdbed9f25212408e0468a475289e80e0406/sdk/python/tests/components/test_components.py#L454..L460

**Comment by Ark-kun** [comment]
> So TFX is open source, and we would like to run TFX on our cloud. The current component implementation seems tied to GCP - hence the question

@neuromage , @hongye-sun Can you answer this question?

Also, can you point to the concrete TFX components you're interested in?

**Comment by animeshsingh** [comment]
TFDV, TFX, and TFMA

**Comment by neuromage** [comment]
@animeshsingh You can run TFX components on-prem, without the use of GCP components. The chicago_taxi_pipeline example in tensorflow/tfx uses GCP, but you can easily just choose to use just the components you care about and not use CMLE/BigQuery/Dataflow through appropriate use of flags and parameters.

I think the one thing that's missing now is an example of how to do this outside the TFX pipeline DSL. I am working on something like this for this quarter.

**Comment by animeshsingh** [comment]
@neuromage - currently the comp definitions in here are heavily tied to GCP, and no way can be used outside GCP in sample pipelines which rely on these yamls

https://github.com/kubeflow/pipelines/blob/master/components/dataflow/tfdv/component.yaml
https://github.com/kubeflow/pipelines/blob/master/components/dataflow/tfma/component.yaml
https://github.com/kubeflow/pipelines/blob/master/components/dataflow/tft/component.yaml

**Comment by animeshsingh** [comment]
So we can either look at recreating these for open source in a generic way, or make the existing comp definitions itself generic

**Comment by hongye-sun** [comment]
@neuromage, are you still working on this? I don't think it's p0 bug. I move it to P1 and please change as needed.

**Comment by neuromage** [comment]
Thanks @hongye-sun . I think we'll end up replacing these components eventually in favour of the TFX OSS components rather than update these. I will close this bug instead.
