### ISSUE TITLE
add SDK support to retrieve pipeline IDs

### ISSUE THREAD

**Issue by amygdala** [kubeflow/pipelines#1243]
(as per a discussion with @hongye-sun )

The SDK allows deploying a pipeline by indicating its ID, but doesn't yet support a way to grab the pipelines & their IDs dynamically. However, to fully support remote deployment it's necessary to do this.

**Comment by alicelee0606** [comment]
Also, would it be possible to support **create_pipeline()** as well? The current **run_pipeline()** only upload the pipeline implicitly without giving it a name.

**Comment by kevinbache** [comment]
#1588

**Comment by kevinbache** [comment]
@alicelee0606 does https://github.com/kubeflow/pipelines/pull/1535 address your issue?

**Comment by alicelee0606** [comment]
> @alicelee0606 does #1535 address your issue?

Yes. I think it does. Thanks.
