### ISSUE TITLE
Cannot set the (set_gpu_limit) gpu num from user params

### ISSUE THREAD

**Issue by zwqjoy** [kubeflow/pipelines#1252]
The set_gpu_limit only accept const number, cannot get input from user  parmas

**Comment by kevinbache** [comment]
This is dependent on a broader [Argo issue](https://github.com/argoproj/argo/issues/703) .  A [workaround](https://github.com/argoproj/argo/issues/703#issuecomment-494183536) is to create several templates for different GPU counts and pass a parameter which selects between those templates.

**Comment by Snapple49** [comment]
I was following the Argo issue and it seems they (finally) have a proposed [solution](https://github.com/argoproj/argo/issues/703#issuecomment-538547792) for this. It would be fantastic if this could be adopted by KFPipelines as well in some neat way, like adding a `set_memory_request_from_param` or some such method similar to the already available `ContainerOp` methods

**Comment by Bobgy** [comment]
/reopen
Makes sense, this is now possible to implement

**Comment by nicokuzak** [comment]
Any updates on this?

**Comment by Bobgy** [comment]
I think https://github.com/kubeflow/pipelines/pull/5972 is the fix to this

**Comment by nicokuzak** [comment]
@Bobgy FYI this compiles, but even if the pipeline parameter is > 1, it only creates a job with 1 GPU. It still seems like the only way to get > 1 GPU is to explicitly write the integer in the pipeline function.
