### ISSUE TITLE
KFP UI: Add links to pipeline docs and samples

### ISSUE THREAD

**Issue by paveldournov** [kubeflow/pipelines#1253]
To help users explore the KFP capabilities it would be great to link the documentation page from the KFP dashboard.
Also to discover samples code and content - provide links to the github samples and AI Hub KFP components.

**Comment by ajayalfred** [comment]
![image](https://user-images.githubusercontent.com/2425179/57259260-c5660d80-7013-11e9-87fa-602bf435f22f.png)

![image](https://user-images.githubusercontent.com/2425179/57259263-c9922b00-7013-11e9-9098-967a6c85e82b.png)

Clicking the 3-dots in collapsed nav mode will open the nav (similar to chevron in collapsed mode)

**Comment by ajayalfred** [comment]
AI Hub link can open AI Hub page pre-filtered with KFP components

**Comment by rileyjbauer** [comment]
@paveldournov Are you saying the KFP UI should link to the main Kubeflow docs (and not just rely on the central dashboard UI to provide that link?)

**Comment by Bobgy** [comment]
Besides mentioned links, I also think putting a link to [Compile pipeline doc](https://www.kubeflow.org/docs/pipelines/sdk/build-component/#compile-the-pipeline) in "Pipeline Upload" dialog would be very useful.

When I just recently started on KFP, I was stuck at this phase because I didn't find that doc before getting to here. The upload dialog has no hint for what I should upload at all.

Thoughts?

**Comment by Bobgy** [comment]
Hi @ajayalfred, I made an initial attempt at implementing this. Can I get some feedback from you?

**Comment by ajayalfred** [comment]
Thanks. Can you add a screenshot for review please?

**Comment by Bobgy** [comment]
@ajayalfred https://github.com/kubeflow/pipelines/pull/2068#issuecomment-529542208

**Comment by Bobgy** [comment]
@paveldournov and @ajayalfred, what do you think of my implementation?

**Comment by paveldournov** [comment]
/lgtm
+1 on the link to the compiling the pipeline as well

**Comment by Bobgy** [comment]
@paveldournov Great, I will continue on the implementation

**Comment by Bobgy** [comment]
This is already resolved in https://github.com/kubeflow/pipelines/pull/2068.
/close
