### ISSUE TITLE
Watson sample errors and inconsistencies

### ISSUE THREAD

**Issue by mpoqq** [kubeflow/pipelines#1254]
While going through the watson example I noticed the following errors:

1. The Kubernetes serviceaccount pipeline-runner has no rights to create secrets ([affected line](https://github.com/kubeflow/pipelines/blob/3df8a4432b6bb6be6ebcb7b6d30e80f0cabeaa35/components/ibm-components/commons/config/src/config.py#L41)).
2. All labels in the component.yaml are not allowed values (`IBM Watson Machine Learning`). Space characters are not allowed.
3. [wml-train.py](https://github.com/kubeflow/pipelines/blob/master/components/ibm-components/watson/train/src/wml-train.py) needs the `cos_endpoint` in two different formats. Minio needs the endpoint without scheme (https://) and the model metadata connection endpoints ([line](https://github.com/kubeflow/pipelines/blob/3df8a4432b6bb6be6ebcb7b6d30e80f0cabeaa35/components/ibm-components/watson/train/src/wml-train.py#L89)) needs the endpoint with scheme. More specific error occurs at the attempt to monitor the training run ([line](https://github.com/kubeflow/pipelines/blob/3df8a4432b6bb6be6ebcb7b6d30e80f0cabeaa35/components/ibm-components/watson/train/src/wml-train.py#L120))
4. Due to assumption that the input parameter is `created` in [wm-train.py](https://github.com/kubeflow/pipelines/blob/3df8a4432b6bb6be6ebcb7b6d30e80f0cabeaa35/components/ibm-components/watson/train/src/wml-train.py#L142), the sample will not work any more. The [output](https://github.com/kubeflow/pipelines/blob/master/samples/ibm-samples/watson/watson_train_serve_pipeline.py#L59) of the config step will not return "created". Additional is the order of the input parameter in the train step is incorrect. 

Locally I was able to fix all of this bugs. If I should create a pull request let me know.
@animeshsingh and @Ark-kun  I think this issue is interesting for you.

**Comment by animeshsingh** [comment]
@mpoqq there is PR pending merge 2, 4, and in our deployments  by default we give increased  permissions to pipeline runner. Once that PR is merged will be good to get to get yours on top
https://github.com/kubeflow/pipelines/pull/1246

**Comment by Ark-kun** [comment]
@animeshsingh @mpoqq Is this issue still relevant?

**Comment by mpoqq** [comment]
No, sorry. The bugs are fixed.
