### ISSUE TITLE
Pipeline UI (version 0.5) works abnormally on Firefox

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/pipelines#1255]
Pipeline UI (version 0.5) works abnormally on Firefox, seems it's a bug on Firefox here, the samples cannot be shown and cannot upload my pipelines. As below screenshot.

<img width="1334" alt="图片" src="https://user-images.githubusercontent.com/13673199/56886159-e329f480-6aa0-11e9-933f-d3e41adbbd70.png">

**Comment by rileyjbauer** [comment]
@avdaredevil 
This seems like it's an issue with the Kubeflow dashboard in general, not KFP. All of the iframed pages appear truncated for me in Firefox, but KFP looks fine when loaded on its own (i.e. https://CLUSTER.endpoints.PROJECT.cloud.goog/pipeline/#/pipelines )

**Comment by avdaredevil** [comment]
It seems based on the toolbar color, you're using a very old version of CentralDashboard, which did not have the firefox fix added in.

This is how it looks with the new version:
![image](https://user-images.githubusercontent.com/5303018/58056828-8ca85700-7b30-11e9-9c62-bed9e5aff14e.png)

**Comment by avdaredevil** [comment]
In fact, @prodonjs updated the 0.5.0 image last week to include the firefox change, so if you redeployed your cluster, that issue would no longer be present.

**Comment by avdaredevil** [comment]
/close

@rileyjbauer If you still seem to have the issue, lmk. Closing for now
