### ISSUE TITLE
Add Experiments remove 

### ISSUE THREAD

**Issue by yylin1** [kubeflow/pipelines#1263]
When I have a lot of experiments and want to delete the past experiments. 
We can delete Pipelines source code, but can't delete the experiment ?  Need to use `kubectl` delete Pipelines experiment?

Environment kubeflow v0.5.0
![](https://i.imgur.com/WW0NZgv.png)

**Comment by gaoning777** [comment]
@kevinbache Were you implementing this, surfacing the API interface to the middle layer APIs in Python SDK?

**Comment by Ark-kun** [comment]
Isn't this mostly about the UX?

**Comment by rileyjbauer** [comment]
@yylin1 out of curiosity, if you were to delete an experiment, what would you want to happen to the runs that were contained within/associated with that experiment?

@IronPan thoughts?

**Comment by yylin1** [comment]
@rileyjbauer  Sorry for the late reply. 
When I write my pipeline source code. I will try several experiments.
But found that if there are multiple experiments or unnecessary experiments, it is very confusing to display on the UI at the same time.

I think in UI can try using experiments and archives to use dependencies. (For important experimental tag storage.)

**Comment by Ark-kun** [comment]
> what would you want to happen to the runs that were contained within/associated with that experiment?

A feedback data point from me:

If experiment is a grouping construct (each run can belong to 0 or more experiments) then I expect that deleting experiment does not do anything to the runs. On a DB level it just removes the links from the experiment to the runs and the experiment itself.

**Comment by strangemonad-faire** [comment]
@Ark-kun how does 1 run belong to multiple experiments? I can see 1 pipeline being run multiple times with different parameters – each run could belong to a different experiment?  Maybe I'm missing something obvious about experiments?

**Comment by Ark-kun** [comment]
> how does 1 run belong to multiple experiments? I can see 1 pipeline being run multiple times with different parameters – each run could belong to a different experiment? Maybe I'm missing something obvious about experiments?

Maybe we do not support it now, but there are use cases for that. If the experiment is just a group of runs then it's not unusual for run to be part of multiple groups. Imagine Experiments that correspond to model improvement projects. Then the final runs of one experiment are starting runs of another experiment. Experiments can be even used like branches or tags (e.g. contain the latest stable versions of several pipelines).

**Comment by Bobgy** [comment]
@jingzhang36 I think this is very important.
It's a missing API we need to support in both client and UI.

I'd think "archive" would be most suitable for the case, so that we don't need to actually delete any data.

**Comment by lucinvitae** [comment]
Experiment removal/archival would be a great feature to have. 

Without it, the experiments view (`/#/experiments`) becomes cluttered and less useful over time.

**Comment by Bobgy** [comment]
Work is being tracked in https://github.com/kubeflow/pipelines/issues/3283

**Comment by jingzhang36** [comment]
@yylin1 we are working on deleting runs/experiments from UI at https://github.com/kubeflow/pipelines/issues/3283. Please check out the current status there. Thank you!
