### ISSUE TITLE
Run creation failed - when cloning a recurring run

### ISSUE THREAD

**Issue by SinaChavoshi** [kubeflow/pipelines#1266]
cloned a previously ran sample pipeline,  got the following error  (screen shot  - https://screenshot.googleplex.com/PujO5xHzwQZ )

Run creation failed
{"error":"Failed to create a new run.: InternalServerError: Failed to create a workflow for (recurringrunkqhd9-246-814723153): resourceVersion should not be set on objects to be created","message":"Failed to create a new run.: InternalServerError: Failed to create a workflow for (recurringrunkqhd9-246-814723153): resourceVersion should not be set on objects to be created","code":13,"details":[{"@type":"type.googleapis.com/api.Error","error_message":"Internal Server Error","error_details":"Failed to create a new run.: InternalServerError: Failed to create a workflow for (recurringrunkqhd9-246-814723153): resourceVersion should not be set on objects to be created"}]}

**Comment by rileyjbauer** [comment]
As mentioned in #1217, it'd probably be good to have a way to toggle between normal and recurring runs from the new run page itself.

Aside from that though, when cloning a recurring run, are you expecting the clone to also be a recurring run, or just a one-shot?

**Comment by Ark-kun** [comment]
> are you expecting the clone to also be a recurring run, or just a one-shot?

It should probably have the same initial config. I.e. clicking "Clone" on a recurring run should show the page for creating recurring run.
