### ISSUE TITLE
UI: different rendering for different kinds of steps

### ISSUE THREAD

**Issue by gaoning777** [kubeflow/pipelines#1270]
Run a workflow with retries and the runtime rendering looks as follows:
![Screenshot from 2019-05-01 13-11-59](https://user-images.githubusercontent.com/3826739/57039931-ddecb700-6c12-11e9-9f33-a571680262d9.png)
A retry node(virtual, no actual pod created) is always created on top of the node that does the real work. When the retry node is rendered the same way as other working pods, it is a little confusing. 
On the other hand, there are no logs for this retry node because there is no real pod.

To differentiate the two nodes in the argo runtime yaml: there is a type field: (Pod, Retry).

**Comment by gaoning777** [comment]
For example, the condition is also a virtual node and it looks good.
![Screenshot from 2019-05-01 13-17-35](https://user-images.githubusercontent.com/3826739/57040187-81d66280-6c13-11e9-8ade-4acb0ad42fac.png)

**Comment by gaoning777** [comment]
@rileyjbauer @ajayalfred WDYT?

**Comment by ajayalfred** [comment]
Doesn't seem like there is any UI change here? Or is the request to support representing retry nodes in the UI?

**Comment by gaoning777** [comment]
Yes, condition node looks good. This issue is requesting to support retry node representation.

**Comment by rileyjbauer** [comment]
I believe this issue is about visually differentiating these retry nodes from the "regular" nodes since they represent different concepts and don't contain the same kinds of data

**Comment by ajayalfred** [comment]
I'm going to tackle this with a combined design effort to represent recursive steps, loops, retry nodes, conditionals, etc. Give me about 1.5 weeks to come back with a design pattern for all the DAG node requests.

**Comment by elikatsis** [comment]
Hey @ajayalfred!
#926 introduced an additional `nodeType`: the `resource`.
To cut a long story short, there are nodes creating kubernetes resources.
After @rileyjbauer 's review, we decided to make UI changes differentiating them in a following PR and this seems like the right opportunity!

I'd love to help and contribute to your work.
We've been thinking maybe adding emblems for the different node types, as well as recognize the resource and use a corresponding kubernetes emblem for that node.

What do you think? Ping me on Slack if you'd like :)

**Comment by ajayalfred** [comment]
Hi Ilias!
Thanks for sharing your ideas and volunteering to help! Feel free to use the DAG mockup to visualize the changes you are thinking of.

![image](https://user-images.githubusercontent.com/2425179/57734047-d76c2f80-7655-11e9-9cfe-d7c3c02d2db8.png)

I designed this in Sketch. Let me know if you need the source file.

**Comment by Bobgy** [comment]
The idea sounds useful to me.
