### ISSUE TITLE
Make sdk/python/setup.py use requirements.txt

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#1271]
Currently we have two places in SDK where the list of dependencies is specified - `setup.py` and `requirements.txt`. There should be a single list so that there is a single source of truth.

It's a bit non-trivial. It might sound strange, but there is no built-in requirements.txt parser and also setup does not have full support by design.

The position of the python devs is that setup.py requirements and requirements.txt serve different purposes and they do not want to fully support intermixing them.

**Comment by vicaire** [comment]
@Ark-kun, could you please provide more details about why this needs to be done? Thanks!

**Comment by Ark-kun** [comment]
> @Ark-kun, could you please provide more details about why this needs to be done? Thanks!

Done.

**Comment by Ark-kun** [comment]
>The position of the python devs is that setup.py requirements and requirements.txt serve different purposes and they do not want to fully support intermixing them.

`setup.py` will continue to have a flexible list of directly required packaged while requirements.txt should serve as a known-good configuration that can be used for image building and should be periodically upgraded.
