### ISSUE TITLE
Kubeflow installed on Kubernetes which is running on aws - how to open kubeflow pipeline GUI

### ISSUE THREAD

**Issue by vackysh** [kubeflow/pipelines#1273]
Hi,

I have a Kubernete running on AWS and the requirement is to deploy the machine learning model on kubeflow pipeline. From the documentation, i have installed the Kubeflow on kubernetes and below are the status of the PODS.

NAME                                                        READY     STATUS    RESTARTS   AGE
ambassador-7b8477f667-4h7zj                                 1/1       Running   0          21h
ambassador-7b8477f667-kb4dx                                 1/1       Running   0          21h
ambassador-7b8477f667-tssj4                                 1/1       Running   0          21h
jupyter-web-app-7dc5bd9b85-45bz4                            1/1       Running   0          21h
metacontroller-0                                            1/1       Running   0          21h
minio-594df758b9-5ntv4                                      0/1       Pending   0          21h
ml-pipeline-79fb6d49db-vlkp8                                1/1       Running   161        21h
ml-pipeline-persistenceagent-6f75c6f87c-nx28f               1/1       Running   175        21h
ml-pipeline-scheduledworkflow-59dd649bff-fqgjp              1/1       Running   0          21h
ml-pipeline-ui-bd7dc7495-8crqv                              1/1       Running   0          21h
ml-pipeline-viewer-controller-deployment-75677bd8bf-4nthb   1/1       Running   0          21h
mysql-5d5b5475c4-q2mg2                                      0/1       Pending   0          21h
notebooks-controller-685db44f8c-2z8kc                       1/1       Running   0          21h
pytorch-operator-9996bcb49-69vg4                            1/1       Running   0          21h
tensorboard-76dffc9ffc-qmzkn                                1/1       Running   0          21h

My question is how to open the Kubeflow Pipeline GUI now ?

**Comment by Ark-kun** [comment]
AFAIK, you should use `kubectl port-forward` to port-forward to ambassador.

**Comment by Jeffwan** [comment]
@vackysh which documentation are you following? I will make sure the documentation cover this part.

**Comment by Bobgy** [comment]
@Jeffwan is there any updates on this?

**Comment by Jeffwan** [comment]
We have docs to either use `port-forward` or public endpoint to visit Kubeflow UI. I don't know which doc the issuer was talking..  There's no action items from me unless there's clear requirement something is not clear or need updates

**Comment by Bobgy** [comment]
Thanks, then I think we can close, because there are no extra requests for a long time.
/close
