### ISSUE TITLE
pypi version 0.1.18 not installable

### ISSUE THREAD

**Issue by abieler** [kubeflow/pipelines#1292]
On pypi the latest version is 0.1.18
(https://pypi.org/project/kfp/)

But
`pip3 install kfp`      installs 0.1.16
`pip3 install kfp --upgrade` installs 0.1.16
`pip3 install kfp==0.1.18` does not work (No matching distribution found for kfp==0.1.18)
`pip3 search kfp` shows
```
kfp (0.1.18)               - KubeFlow Pipelines SDK
  INSTALLED: 0.1.16
  LATEST:    0.1.18
```

requirements are ok: Python &gt;=3.5.3 (tested on 3.7.3).

The following does work:
`pip3 install https://storage.googleapis.com/ml-pipeline/release/0.1.18/kfp.tar.gz --upgrade`

Checking out 
https://pypi.org/simple/kfp/
reveals this:

```
kfp-0.1.11-py3-none-any.whl
kfp-0.1.11.tar.gz
kfp-0.1.16-py2-none-any.whl
kfp-0.1.16.tar.gz
kfp.tar.gz
```

Cheers
Andre

**Comment by Ark-kun** [comment]
Thanks for the report. I'll investigate.

**Comment by Ark-kun** [comment]
0.1.19 is working now

**Comment by Ark-kun** [comment]
BTW, do you know the exact PyPI behavior? It looks pretty strange and inconsistent. On one hand it takes the release version from the package metadata (so you cannot upload the same file twice). On the other hand it seems to rely on pre-upload file names for versioning.

**Comment by vicaire** [comment]
Closing, please re-open if anything is outstanding.
