### ISSUE TITLE
Quickstart notebook should indicate that it can't be run in cluster

### ISSUE THREAD

**Issue by rileyjbauer** [kubeflow/pipelines#1301]
https://github.com/kubeflow/pipelines/blob/master/samples/notebooks/quickstart.ipynb
includes multiple `docker` commands which will fail if run within the GKE cluster as Docker is not present in the cluster.

The notebook should indicate that it is meant to be run locally

**Comment by gaoning777** [comment]
solved here: https://github.com/kubeflow/pipelines/pull/1302
