### ISSUE TITLE
It looks like this repo has webhooks configured incorrectly.

### ISSUE THREAD

**Issue by cjwagner** [kubeflow/pipelines#1304]
I noticed that many PRs in this repo are getting duplicated responses from Prow. This suggests that Prow is receiving each webhook twice. This wastes our API rate limit and can result in two comments being posted instead of one. I suspect that webhooks are configured to be sent to Prow at both the repo and org level (GitHub isn't smart enough to dedupe). Please confirm that this is the case by inspecting the GitHub settings, and if it is, please remove the repo level webhook config for Prow.

**Comment by Ark-kun** [comment]
> I noticed that many PRs in this repo are getting duplicated responses from Prow.

I do not see this in my PRs. Can you show some examples?
Kubeflow deployments are pretty flaky and leaky, so we often have to re-run failed tests. Maybe that's what you're seeing.

> I suspect that webhooks are configured to be sent to Prow at both the repo and org level (GitHub isn't smart enough to dedupe).

@IronPan Can you check please?

**Comment by cjwagner** [comment]
> I do not see this in my PRs. Can you show some examples?

This isn't guaranteed to happen on all PRs if the problem is what I suspect because Prow tries to delete old messages when it posts a new one. This doesn't always happen though when the webhooks arrive simultaneously because there is an inherent race with the plugins looking for existing comments.

Here are some examples of the behavior I'm describing:
https://github.com/kubeflow/pipelines/pull/1256#issuecomment-488473389
https://github.com/kubeflow/pipelines/pull/1200#issuecomment-485574575
https://github.com/kubeflow/pipelines/pull/1125#issuecomment-481500505
https://github.com/kubeflow/pipelines/pull/898#issuecomment-486479723

**Comment by Ark-kun** [comment]
I only see a single test run per commit for most of them:
https://prow.k8s.io/pr-history/?org=kubeflow&repo=pipelines&pr=1200
https://prow.k8s.io/pr-history/?org=kubeflow&repo=pipelines&pr=1125
https://prow.k8s.io/pr-history/?org=kubeflow&repo=pipelines&pr=898
And with https://prow.k8s.io/pr-history/?org=kubeflow&repo=pipelines&pr=1256 the tests were launched manually (using /test) commands.

**Comment by cjwagner** [comment]
The duplicate tests are likely aborted before they can ever report, but that still wastes API tokens and other actions are not successfully deduped. Every comment I linked to has a duplicate comment posted with identical content. e.g. 
![Screenshot from 2019-05-13 11-31-11](https://user-images.githubusercontent.com/5334145/57645561-60f70100-7573-11e9-8e55-e3511c668231.png)

From the logs I can confirm that the Prow instance is receiving duplicate webhook events as suspected (notice the event GUID):
```
{
  author:  "Ark-kun"   
  component:  "hook"   
  event-GUID:  "c1d2b870-7393-11e9-9e1e-0aca9c4dd307"   
  event-type:  "pull_request"   
  level:  "info"   
  msg:  "Pull request assigned."   
  org:  "kubeflow"   
  pr:  1256   
  repo:  "pipelines"   
  url:  "https://github.com/kubeflow/pipelines/pull/1256"   
}
{
  author:  "Ark-kun"   
  component:  "hook"   
  event-GUID:  "c1d2b870-7393-11e9-9e1e-0aca9c4dd307"   
  event-type:  "pull_request"   
  level:  "info"   
  msg:  "Pull request assigned."   
  org:  "kubeflow"   
  pr:  1256   
  repo:  "pipelines"   
  url:  "https://github.com/kubeflow/pipelines/pull/1256"   
}
```

We have seen this behavior before and it has always been because webhooks were configured at both the repo and org level in the GitHub settings. Someone with adequate permissions needs to confirm this is the case and resolve it by removing the repo level webhook configuration.

**Comment by Ark-kun** [comment]
> Someone with adequate permissions needs to confirm this is the case and resolve it by removing the repo level webhook configuration.

/cc @IronPan Can you please check this?

**Comment by Ark-kun** [comment]
@cjwagner You suspicion was true. @vicaire helped me disabled the `kubeflow/pipelines` webhook in favor of the `kubeflow` webhook.
Let's see how this goes.
