### ISSUE TITLE
[kaniko] - reduce dependency on kubeflow namespace

### ISSUE THREAD

**Issue by IronPan** [kubeflow/pipelines#1316]
Instead of assuming kubeflow namespace exist, the kaniko should get the current runtime environment. 
Ref:
https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/compiler/_component_builder.py#L263

**Comment by gaoning777** [comment]
The namespace is configurable: https://github.com/kubeflow/pipelines/blob/e9aa69e353769ac20f9fbfd1f7bf82be0240ea90/sdk/python/kfp/compiler/_component_builder.py#L490

**Comment by Ark-kun** [comment]
@gaoning777 Can we just omit the namespace? Can we get the namespace from the cluster?

**Comment by gaoning777** [comment]
what do you mean? the same namespace as the pipeline system?
In fact, there is not really any particular reason to run it in the same namespace as the pipeline system, is there?

**Comment by Ark-kun** [comment]
It probably should be run in the same namespace as the pipeline pods.

**Comment by IronPan** [comment]
@gaoning777 FYI the context here is that we are not expecting 'kubeflow' namespace to always exist. user can choose an arbitrary namespace to deploy KFP to, and things should still work
in that context, any place we hardcoding the ns is not considered a good thing to do.  i'm scanning the code base for all the places and this is a place i think we should fix. WDYT?

**Comment by gaoning777** [comment]
Maybe changing it to "default" namespace as the default. The "default" namespace always exists such that it at least does not output errors.

**Comment by gaoning777** [comment]
WDYT? I can send a PR to change the default namespace to "default"?

**Comment by IronPan** [comment]
https://github.com/kubeflow/pipelines/pull/1394/files
does this look good?

**Comment by gaoning777** [comment]
Configure the ns to 'default' by default: https://github.com/kubeflow/pipelines/pull/1473

**Comment by gaoning777** [comment]
Close this issue in favor of https://github.com/kubeflow/pipelines/issues/345
