### ISSUE TITLE
[UI] - reduce dependency on kubeflow namespace

### ISSUE THREAD

**Issue by IronPan** [kubeflow/pipelines#1319]
The UI seems depend on kubeflow namespace.
https://github.com/kubeflow/pipelines/blob/master/frontend/server/server.ts#L36

Instead it can set the namespace as env variable when pod starts, similar to 
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/pipeline/pipeline-apiserver.libsonnet#L169

and refer in the code.

**Comment by rileyjbauer** [comment]
What is the priority for this work?

**Comment by eterna2** [comment]
@rileyjbauer @IronPan 
Hey, I have urgent need of this as I am deploying pipelines in multiple namespace. I am currently using my custom image of a fork. 

I have made a PR to effect this change in #1324

**Comment by IronPan** [comment]
awesome! approved
