### ISSUE TITLE
Tensorboard CRD integration

### ISSUE THREAD

**Issue by IronPan** [kubeflow/pipelines#1320]
Here are some thoughts of how things should work with Viewer CRD (Tensorboard CRD)
- The namespace it's deployed to is parameterized, and the instance will always be launched to the same namespace as the UI, for now (before multi-user support is in place, and instances are launched in user's ns). 
- The TB instance is proxied through UI, so when user port-forward UI, the TB is automatically accessible. 
- The TB spec template is parameterized to be able to launch data from S3/GCS/Volume. 
- The TB spec should assume the google application credential optional, and only mount the secret when the deployment is from classic GCP kubeflow deployment, when this credential is created. In other case, it should assume the default VM SA should have the access to the data and not need to mount anything. 
https://github.com/kubeflow/pipelines/blob/24d69cbb81f60307f5807a4c2129dab493ce52f4/frontend/server/k8s-helper.ts#L46-L79

**Comment by jingzhang36** [comment]
@IronPan @rileyjbauer @neuromage the template used is a little different from the one here https://github.com/kubeflow/pipelines/pull/1237/files. Can we have a quick meeting helping me understanding the value used in each field?

**Comment by IronPan** [comment]
SG Feel free to set up a meeting.

**Comment by IronPan** [comment]
One more item 
- Viewer CRD should support namespaced mode that runs under a role instead of a clusterrole. For now, when running CRD controller using a role, i got following

```
E0514 08:23:49.907693       1 reflector.go:205] pkg/mod/k8s.io/client-go@v0.0.0-20180718001006-59698c7d9724/tools/cache/reflector.go:99: Failed to list *v1beta1.Viewer: viewers.kubeflow.org is forbidden: User "system:serviceaccount:foobar:ml-pipeline-viewer-crd-service-account" cannot list viewers.kubeflow.org at the cluster scope
```

**Comment by rileyjbauer** [comment]
@jingzhang36 can this be closed?

**Comment by jessiezcc** [comment]
@jingzhang36, can u pls verify and close this?
