### ISSUE TITLE
support for git artifacts

### ISSUE THREAD

**Issue by ryandawsonuk** [kubeflow/pipelines#1326]
I'm trying to port workflows from https://github.com/kubeflow/example-seldon/tree/master/workflows to pipelines to produce seldon pipelines examples. Each involves a step where [code is cloned from git](https://github.com/kubeflow/example-seldon/blob/master/workflows/serving-r-mnist-workflow.yaml#L47) and becomes an argo input artifact. I can see [argo artifacts were looked at before](https://github.com/kubeflow/pipelines/issues/336) and that examples instead [seem to clone code into GCS buckets first](https://github.com/kubeflow/pipelines/blob/master/samples/tfx-oss/TFX%20Example.ipynb).

It would be nice if we could get artifacts from git as input parameters in the argo way. However an alternative would be to have a component for performing git operations. I guess I can use an i[mage that has git installed](https://hub.docker.com/r/alpine/git/) and use it to clone the repo and move it to the volume.

**Comment by Ark-kun** [comment]
> Each involves a step where code is cloned from git and becomes an argo input artifact.

I'm not sure it's the best for reproducibility and autonomy.

>It would be nice if we could get artifacts from git as input parameters in the argo way. 

This probably won't happen. It's simple to implement and I do not think there is much value in adding a specialized feature like this. Kubernetes which also had 1st-party GIT support has now deprecated it.

I believe that a good common storage solution is very important for Pipelines.

> However an alternative would be to have a component for performing git operations. 

It can easily be done, yes.

But I'd like you to think your reason for cloning particular code repo. You probably want to run that code as a pipeline task. A task is like a function call where you're calling a function with some arguments. The analog of a function is a "component". Both have static signatures. Meanwhile a random GIT repo or a script does not have a static signature.
It might be better to create components that are specific to your needs and have specialized interfaces/signatures and just clone the code before executing the command-line.

Also the particular workflow that you've linked is pretty low-level. It clones the repo to build the container image. But for Pipelines we usually use `func_to_container_op` or `build_python_component` to turn source code into a pipeline component.

What's the high-level pipeline that you want to build?

**Comment by ryandawsonuk** [comment]
The main [seldon kubeflow example](https://github.com/kubeflow/example-seldon) creates a multi-armed bandit - one arm of the bandit is an R model, another is SKLearn and the third is TF. If we take the TF arm in isolation then it is basically like the [pipelines end-to-end MNIST example](https://www.kubeflow.org/docs/pipelines/tutorials/pipelines-tutorial/) in that the aim for both is train and serve a model for MNIST.

The seldon example is rather different in that we build an image for training the model and deploy that with a TFJob by deploying the k8s resource explicitly. We then build an image that contains the model to be served and deploy a SeldonDeployment resource that points to that image. It may seem counter-intuitive to treat the TF model as part of the image rather than as data (and we don't necessarily need to do that for this case) but we use this approach across the board as it works for a wide range of languages and tools.

The built model images can then be served together in an inference graph, such as a multi-armed bandit. That graph is a custom resource that the user defines. I expect a new component will be needed for that as the[ job launcher](https://github.com/kubeflow/pipelines/tree/master/components/kubeflow/launcher) also deploys a resource and it has a custom component to do so. Not sure yet whether it would be possible to deploy a custom resource using [ResourceOp](https://github.com/kubeflow/pipelines/blob/master/samples/resourceops/resourceop_basic.py).

I've started[ building out an example pipeline](https://github.com/ryandawsonuk/pipelines/blob/seldon-examples/samples/seldon/mnist_tf.py) but it is early days for this. 

The main point is that we'd like to provide an easy way for people to plug into a pipeline their custom model code, training code and training data and for the pipeline to serve the model. The current thinking is that the data will come from a volume (as we want it to work on-prem) and that the code would come from git (which could be done via the docker image as I have now).

@vicaire does this sound good to you as a general approach?

**Comment by ryandawsonuk** [comment]
To put this more succinctly, I think these are the key specific reasons to want to do git clone operations in pipelines:
- The model of installing code dependencies at runtime in a common base image for the language in a container op doesn’t fit well with R. You want to install the dependencies in the Dockerfile to use them as binaries. See https://docs.seldon.io/projects/seldon-core/en/latest/R/r_wrapping_docker.html
- If you’re looking to promote through environments then likely the code needs to be in git anyway. There should be a stable tag that can be referenced and the code used when the pipeline is run for dev/staging/prod. If you’ve got the code in git anyway you’re not likely to want to maintain it in two places by duplicating it in a ContainerOp. 
- Given that there are these situations where a custom image needs to be built from source code, better to support doing that through pipelines rather than leave it as something to be done at CI-level.
- Supporting git clone would also allow the same pipeline definition to be used to build different projects by changing the clone url/tag parameters and would therefore be more re-usable.

**Comment by Ark-kun** [comment]
> * If you’ve got the code in git anyway you’re not likely to want to maintain it in two places by duplicating it in a ContainerOp.

Can you elaborate on this? Why do you think that some GIT code is duplicated in `ContainerOp`? Components and `ContainerOp` instances just point to some program inside some container. They do not copy the container code.

>Supporting git clone would also allow the same pipeline definition to be used to build different projects by changing the clone url/tag parameters and would therefore be more re-usable

Do all these projects have the same API? The exact same inputs and outputs?

>Supporting git clone

Can you explain why you cannot execute `git clone` right now using the current SDK?

**Comment by ryandawsonuk** [comment]
Sorry @Ark-kun, I realise now that I've been expressing this problem in a confusing way so am now closing this issue in favour of https://github.com/kubeflow/pipelines/issues/1375
