### ISSUE TITLE
ResourceOp to support pvolumes

### ISSUE THREAD

**Issue by ryandawsonuk** [kubeflow/pipelines#1345]
[ResourceOp](https://github.com/kubeflow/pipelines/blob/master/samples/resourceops/resourceop_basic.py#L38) currently doesn't have a way to depend upon a volume. If I try to add [pvolumes](https://github.com/kubeflow/pipelines/blob/master/samples/resourceops/volumeop_sequential.py#L36) I get `got an unexpected keyword argument 'pvolumes'`

The ResourceOp supports creating a resource or even [deploying a Custom Resource](https://github.com/kubeflow/pipelines/issues/429) such as a [TFJob](https://github.com/ryandawsonuk/pipelines/blob/71ca63e26b8a1e01a2ede4314ff0d818adb8bfd2/samples/seldon/mnist_tf.py#L102) (just using TFJob for illustration here - it's really [other kinds of training jobs](https://github.com/kubeflow/example-seldon/blob/master/workflows/training-r-mnist-workflow.yaml#L70) I'd like to use this for). But what I don't see a way to do right now is make sure the custom resource depends on a volume created or modified in a previous step.

I don't think the modification needed here would have to do anything to mount a volume. The resource definition itself could do that. It would just need to force the step to depend on the one that created or modified the volume. Another approach might be support the dependency through `inputs` but that isn't presently available either.

@elikatsis , @vkoukis - any thoughts on this?

**Comment by elikatsis** [comment]
Hello Ryan,
actually I was just reading #1344 and was composing an answer (containing questions!).

I will first answer to the main question of this issue.
A `ResourceOp` is a step of the pipeline which manipulates a Kubernetes resource. It executes nothing but a `kubectl <action> ...`.
Therefore, it shouldn't (and can't) mount volumes. It is totally agnostic about the resource.

I believe what you mean is to create a resource, and make **that** resource mount some volumes.

I don't have much experience with `TFJob`s and launching them. Reading it diagonally, though, the deployment of a `TFJob` you mention in #1344 seems very strict.

I guess I'll need more context, but what would you say if there was a `TFJobOp`, subclass of `ResourceOp`, which would initiate a `TFJob`. This would expose any useful mechanism to customize the `TFJob`'s manifest.

These thoughts have also been expressed by @jlewi and @hongye-sun
https://github.com/kubeflow/pipelines/issues/801#issuecomment-462182776
https://github.com/kubeflow/pipelines/issues/801#issuecomment-467999259

A `TFJobOp` could then have a `pvolumes` argument and parse the values passed to append its dependencies, as well as use them in the manifest respectively.

This issue could actually be the design document of this subclass, and your feedback using it can help us a lot.

**Comment by hongye-sun** [comment]
ResourceOp is different from ContainerOp. It starts with a "launcher" pod which calls k8s API to create another custom resource like TFJob. When you add a pvolumes to ResourceOp, usually you mean adding a volume to the custom resource but not the "launcher". The [PipelineVolume](https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/dsl/_pipeline_volume.py#L26) derives from k8s volume, so you can directly use it in your code when building k8s custom resource. 

For example, you can build a pod spec for a TFJob:
```python
pod_spec = V1PodSpec(..., 
  volumes=[vop.volume], 
  containers=[V1Container(..., 
    volume_mounts=[V1VolumeMount(name=vop.volume.name, mount_path='...')]
)
tf_job = TFJob(worker=V1PodTemplate(spec=pod_spec))
tf_job_op = ResourceOp(k8s_resource=tf_job, ...)
```

**Comment by ryandawsonuk** [comment]
I probably shouldn't have used TFJob as my example in this issue. I do want to be able to mount volumes to a TFJob but I intended to cover that with https://github.com/kubeflow/pipelines/issues/1344 A TFJobOp could well be the way to address that concern.

What I had in mind when raising particular issue was other types of resource, though the only concrete example I have immediately is a [vanilla kubernetes Job](https://github.com/kubeflow/example-seldon/blob/master/workflows/training-r-mnist-workflow.yaml#L70). I am not sure whether there is a way to do create Jobs ([CreateJobOp](https://github.com/kubeflow/pipelines/blob/e09a8ffb0e915c7aae50d69428ae8a4857f94c99/component_sdk/python/kfp_component/google/ml_engine/_create_job.py) looks related but I think that might be CMLE-specific).

**Comment by elikatsis** [comment]
>[...] I think that might be CMLE-specific

Yes, that's my opinion as well. A `JobOp` would not serve much of purpose since a `Job` could be anything.

What you could do is to use the `after()` method on the `ResourceOp` and explicitly specify these dependencies. (Note that if `PipelineParam`s exist in the `k8s_object` passed, the corresponding dependencies will be produced, but I get such parameters don't always exist).

`ResourceOp` is a subclass of [`BaseOp`](https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/dsl/_container_op.py#L642) (I should move it to a separate module, but I've been postponing it).
While `BaseOp` is of no use to the user, it does have all the common attributes and methods `ContainerOp` and `ResourceOp` (both derive from it).
So you may try
```
step1 = dsl.ContainerOp(...)
step2 = dsl.ContainerOp(...)
job = dsl.ResourceOp(...).after(step1).after(step2)
```
(TODO: I will modify after to accept multiple arguments and be able to do `op.after(step1, step2)` just as `PipelineVolume`'s `after()` works)

**Comment by ryandawsonuk** [comment]
Thanks @elikatsis ! Adding .after does indeed [do what I need for this case](https://github.com/ryandawsonuk/pipelines/commit/cf0c36d9dbb356746b6712b43766aa7bb5b5a23d).

I agree about JobOp not being necessary. If I really need to create a plain Job rather than use a ContainerOp (and I'm not sure I do) then I can use ResourceOp and if the Job has dependencies I can use .after (thanks again!).

 I share the sense that a TFJobOp would be useful, if for no other reason then because it would be more intuitive than creating TFJobs through ContainerOps or ResourceOps.

**Comment by elikatsis** [comment]
That's nice, you are welcome!
Shall we close this issue and discuss `TFJobOp` in #1344?

**Comment by ryandawsonuk** [comment]
Yep, cool
