### ISSUE TITLE
Support Output Viewers With Non-Minio Default Artifact Repository

### ISSUE THREAD

**Issue by alicelee0606** [kubeflow/pipelines#1359]
I follow the instructions on https://github.com/kubeflow/pipelines/pull/1297 and change my default artifact repository to gcs in workflow-controller-configmap. The output artifact part works. However, I am not able to view the outputs on the UI of "Artifact" Tab. I then find out that my request URL is still /pipeline/artifacts/get?source=**minio**.

I am wondering if this line is the root cause: https://github.com/kubeflow/pipelines/blob/2da723c2faf5228e646f12fb57e4d5f491e69c82/frontend/src/lib/WorkflowParser.ts#L216
Or would you please give me some hints on what I might possibly get wrong?

**Comment by alicelee0606** [comment]
Hi, is there any update with this issue?

**Comment by jingzhang36** [comment]
Hi @alicelee0606, the code you've pointed out does seem to indicate that our frontend hardcoded the artifact configuration storage to be minio typed source. Let me check with someone on my team for some context and further information. Will update this thread when I get anything new.

**Comment by Ark-kun** [comment]
Frontend uses Minio client which supports all S3 locations. The particular issue you have is probably caused by something like secrets. AFAIK, @rileyjbauer has recently looked at that part of code.

**Comment by Bobgy** [comment]
/close
because this seems fixed
Please reopen if it's still an issue
