### ISSUE TITLE
ml-pipeline-persistenceagent restarts continuously

### ISSUE THREAD

**Issue by hemantha-kumara** [kubeflow/pipelines#1360]
Kubeflow v0.5.1
On Prem(installed setting KUBEFLOW_DOCKER_REGISTRY to local images)
ksonnet version ks_0.13.1_linux_amd64
kubernetes version v1.13.4

all pods are up and running except ml-pipeline-persistenceagent pod
`ml-pipeline-persistenceagent-58bc77c97b-fpgjs               0/1     Error               153        18h`
 
Installed kubeflow using kftcl.sh
```
curl https://raw.githubusercontent.com/kubeflow/kubeflow/${KUBEFLOW_TAG}/scripts/download.sh | bash
${KUBEFLOW_SRC}/scripts/kfctl.sh init ${KFAPP} --platform none
cd ${KFAPP}
${KUBEFLOW_SRC}/scripts/kfctl.sh generate k8s
${KUBEFLOW_SRC}/scripts/kfctl.sh apply k8s
```
logs from ml-pipeline-persistenceagent pod
```
[root@cluster01-control-host02 kfapp]# kubectl logs -f ml-pipeline-persistenceagent-58bc77c97b-fpgjs -nkubeflow
W0521 09:39:16.583731       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2019-05-21T09:41:18Z" level=fatal msg="Error creating ML pipeline API Server client: Failed to initialize pipeline client. Error: Waiting for ml pipeline API server failed after all attempts.: Get http://ml-pipeline.kubeflow.svc.cluster.local:8888/apis/v1beta1/healthz: dial tcp 10.254.188.45:8888: i/o timeout: Waiting for ml pipeline API server failed after all attempts.: Get http://ml-pipeline.kubeflow.svc.cluster.local:8888/apis/v1beta1/healthz: dial tcp 10.254.188.45:8888: i/o timeout"
```

when I tried to do curl manually to above link, I get error saying page not found
```
[root@cluster01-control-host02 kfapp]# curl http://ml-pipeline.kubeflow.svc.cluster.local:8888
404 page not found
[root@cluster01-control-host02 kfapp]#  curl http://ml-pipeline.kubeflow.svc.cluster.local:8888/apis/v1beta1/healthz
{"commit_sha":"c9382474d688a34d3dd3b6d943cd71fea8f62e76"}
```
please let me know if any otherr logs are required.

**Comment by mpoqq** [comment]
Hi @hemantha-kumara, do you find the bug or a solution?
Are you sure that the _ml-pipeline_ service is running correctly?
The ml-pipeline service has a higher timeout to connect to the mysql server. Therefore, it sometimes looks as if the ml pipeline service is running correctly, but has also failed (take also a look of the amount of restarts).

**Comment by jessiezcc** [comment]
closing stale issues since no response.
