### ISSUE TITLE
Can't delete a scheduled workflow through the ui

### ISSUE THREAD

**Issue by strangemonad-faire** [kubeflow/pipelines#1362]
Running kubeflow 0.5 on gcp as installed by the gui "1-click" installer.

With an experiment that has a scheduled workflow:
- In the pipelines UI
- "Experiments" -> [EXPERIMENT_NAME] -> "Manage" (under recurring run configs)
- Click on the scheduled workflow you want to delete
- Click delete (top right)

You get this error:
'Failed to delete recurring run config: bf2d5d81-773c-11e9-b048-42010a800059 with error: "Cannot read property 'configuration' of undefined" '

**Comment by strangemonad-faire** [comment]
related to #1363

**Comment by jingzhang36** [comment]
@strangemonad-faire do you still have this issue? I tried on my deployment (deployed through kustimized manifest here https://github.com/kubeflow/pipelines/blob/f8b06387b8da9145081fe257d69b411a16ff9266/manifests/README.md) and the swf got deleted properly.

**Comment by GarrettMooney** [comment]
I'm running into the same issue. I had tried to disable and kill a recurring run via the UI and the Python sdk but it keeps running.

The runs don't show up in the UI and don't appear to have an associated experiment so it has been running up a hefty bill on stackdriver.

The swf is visible via `kubetcl get swf --all-namespaces`, but I don't know enough to delete it.

Please let me know what info I can provide for clarification.

**Comment by Bobgy** [comment]
Hi @GarrettMooney, is there a way you can reproduce this problem?

> The runs don't show up in the Kubeflow UI and don't appear to have an associated experiment so it has been running up a hefty bill on stackdriver.

Does it actually create runs? Or is it just the logs causing a problem for you?

> I had tried to disable and kill a recurring run via the UI and the Python sdk but it keeps running.

Did you try to delete the recurring run from KFP UI? Did it succeed?

**Comment by GarrettMooney** [comment]
Hi @Bobgy, 

I _believe_ that the way to reproduce this would be to create a recurring run under an experiment, __tmp_exp__, and then use the Python SDK to delete this experiment (on `v1.0.2` of kubeflow). It is unclear to me whether or not this recurring run was disabled or not before deletion.

It was creating runs. The logs and their associated bill were how we noticed the recurring run's persistence. We did not see the recurring run in the KFP UI after the experiment was deleted so we were unsure how to delete it.

Eventually* a `kubectl delete swf <id>` successfully deleted the `swf`.

*(It seemed like GC and a periodic sync kept generating logs related to the swf for another hour or two after issuing the comand).

Thanks for getting back to me and please let me know what info I can provide to help!

**Comment by Bobgy** [comment]
@GarrettMooney thanks for the detailed report

> I _believe_ that the way to reproduce this would be to create a recurring run under an experiment, **tmp_exp**, and then use the Python SDK to delete this experiment (on `v1.0.2` of kubeflow). It is unclear to me whether or not this recurring run was disabled or not before deletion.

It's not, I guess documentation wasn't visible enough: https://kubeflow-pipelines.readthedocs.io/en/stable/source/kfp.server_api.html#kfp_server_api.api.experiment_service_api.ExperimentServiceApi.delete_experiment.

> Deletes an experiment without deleting the experiment’s runs and jobs. To avoid unexpected behaviors, delete an experiment’s runs and jobs before deleting the experiment.

> Eventually* a `kubectl delete swf <id>` successfully deleted the `swf`.

Yes, that's the right way to workaround this problem. However, we recommend deleting all the runs, jobs before deleting the experiment.

**Comment by Bobgy** [comment]
I believe the question (different from the original issue) is answered, so I'm going to close the issue again.
If you are interested in making api server delete all owned resources from an experiment, feel free to create a new issue.
