### ISSUE TITLE
Deleting a swf through kubectl is not reflected in the UI

### ISSUE THREAD

**Issue by strangemonad-faire** [kubeflow/pipelines#1363]
I think the underlying source of this bug leads to some other subtle issues.

Ultimately the SWF crd controller and the backend apiserver end up in a split brain scenario.

- The manual fix is to log into the database and delete the row matching that "job"
- I'd assume it's possible to make the apiserver smarter and watch for changes to swf crd's and update the job_store accordingly but I feel like all bugs of this nature will be hard to stamp out so long as there are effectively 2 sources of truth (the job_store in apiserver backed by mysql and the custom scheduled workflow resource backed by the state in k8s).

**Comment by strangemonad-faire** [comment]
related to 1362

**Comment by Bobgy** [comment]
I think after https://github.com/kubeflow/pipelines/issues/1362 is fixed, there's no need to use kubectl to delete swf.

Supported options to delete swf:
1. use kfp ui
2. use kfp python client
