### ISSUE TITLE
How can I dynamic change the output file path by parameter?

### ISSUE THREAD

**Issue by sshuair** [kubeflow/pipelines#1369]
Hi, guys! How can I dynamic change the output file path by parameter?

Just like this or something else ?

![image](https://user-images.githubusercontent.com/5787131/58164423-657c9180-7cb8-11e9-8084-69691eabd8ae.png)

**Comment by Ark-kun** [comment]
You should probably not do that. The best situation is when the paths are completely under the system control.

What is the high-level scenario where you want this?

In any case you can always have a mini wrapper script that renames the output files from dynamic path to the system-expected one.

**Comment by Ark-kun** [comment]
We see no need to support dynamic file paths. You can always use hard links to link arbitrary file on disk to the static output path location.
