### ISSUE TITLE
Kubeflow-pipeline running with aws sagemaker throws an error passing K-Mean and feature_dim parameters

### ISSUE THREAD

**Issue by vackysh** [kubeflow/pipelines#1370]
Hi, 

I have copied the git code for aws sagemaker to execute through the Kubeflow pipeline

https://github.com/kubeflow/pipelines/blob/master/samples/aws-samples/mnist-kmeans-sagemaker/mnist-classification-pipeline.py

While executing the kubeflow pipeline, I am getting the error of assigning the hyperparameters, although in pipeline parameters there are no such parameters define.

error:

Training failed with the following error: ClientError: No value(s) were specified for 'k', 'feature_dim' which are required hyperparameter(s) (caused by ValidationError)

pipeline parameters are:

@dsl.pipeline(
    name='MNIST Classification pipeline',
    description='MNIST Classification using KMEANS in SageMaker'
)
def mnist_classification(region='us-east-1',
    image='174872318107.dkr.ecr.us-west-2.amazonaws.com/kmeans:1',
    dataset_path='s3://s3-sagemaker-us-east-1/mnist_kmeans_example/data',
    instance_type='ml.c4.8xlarge',
    instance_count='2',
    volume_size='50',
    model_output_path='s3://s3-sagemaker-us-east-1/mnist_kmeans_example/model',
    batch_transform_input='s3://s3-sagemaker-us-east-1/mnist_kmeans_example/input',
    batch_transform_ouput='s3://s3-sagemaker-us-east-1/mnist_kmeans_example/output',
    role_arn=''
    ):

Please let me know why this error is appeared and how should it get resolved ?

Regards,
Varun

**Comment by vackysh** [comment]
Hi @Jeffwan ,

need your support on this.

I am using training image "382416733822.dkr.ecr.us-east-1.amazonaws.com/kmeans:1" and it is throwing an error for mising values for parameters K and feature_dim. Although we are not using these parameters anywhere in pipeline.

Can you please provide the solution ?

Regards,
Varun

**Comment by Jeffwan** [comment]
em. I may delete the configuration fields in clean up. Let me double check and come back to you @vackysh

**Comment by Jeffwan** [comment]
I can not reproduce this issue. 

`HyperParameters` was removed by me in this commit
https://github.com/kubeflow/pipelines/commit/26f2719c28a731d8925ae2ce96252be1df2562aa

Add it back will solve this problem

**Comment by Jeffwan** [comment]
Image has been rebuilt and it should be good now.

**Comment by vackysh** [comment]
Hi @Jeffwan ,

Thanks for your response.

I again executed the pipeline using image "382416733822.dkr.ecr.us-east-1.amazonaws.com/kmeans:1" , but getting the same issue

"Training failed with the following error: ClientError: No value(s) were specified for 'k', 'feature_dim' which are required hyperparameter(s) (caused by ValidationError)"

The pipeline parameters are:

@dsl.pipeline(
name='MNIST Classification pipeline',
description='MNIST Classification using KMEANS in SageMaker'
)
def mnist_classification(region='us-east-1',
image='382416733822.dkr.ecr.us-east-1.amazonaws.com/kmeans:1',
dataset_path='s3://s3-sagemaker-us-east-1/mnist_kmeans_example/data',
instance_type='ml.c4.8xlarge',
instance_count='2',
volume_size='50',
model_output_path='s3://s3-sagemaker-us-east-1/mnist_kmeans_example/model',
batch_transform_input='s3://s3-sagemaker-us-east-1/mnist_kmeans_example/input',
batch_transform_ouput='s3://s3-sagemaker-us-east-1/mnist_kmeans_example/output',
role_arn=''
):

Please suggest how to get through it if issue has already fixed at your end.

**Comment by Jeffwan** [comment]
@vackysh I think the problem is your machine already has this image. could you go to the machine and do a force pull? 
```
seedjeffwan/kubeflow-pipeline-aws-sm:20190501-05
```

**Comment by vackysh** [comment]
HI @Jeffwan ,

I refreshed the image It is now working fine.
Thank you so much.

Regards,
Varun

**Comment by vackysh** [comment]
Hi @Jeffwan,

Where can i get the actual source code (ML code ) reading from the image seedjeffwan/kubeflow-pipeline-aws-sm:20190501-05 (not a docker file, but actual logic for train, predction) ?

I actually working on similar automation and want to analyse the source code.

Regards,
Varun

**Comment by Jeffwan** [comment]
@vackysh This is a component example for training. 
https://github.com/kubeflow/pipelines/blob/master/components/aws/sagemaker/train/src/train.py

Not sure if your work is internal or public. It would be perfect if you can make some contribution! Feel free to ping me on Slack or shoot me an email.

**Comment by vackysh** [comment]
Hi @Jeffwan  ,

Thanks for information. But i am looking for the main Kmean algorithms code that is used for training the model. I couldn't find that anywhere on path.

I have a requirement where Scikit SVM model to get deploy on kubeflow pipeline using aws sagemaker services and S3. So i want to have a look on source ML code that has been passed through image as an input to pipeline.

Regards,
Varun

**Comment by Jeffwan** [comment]
@vackysh Now I get your point, in the example, I am using the container images from SageMaker. I think KMEANS one is first-party models and you might don't have access to it. What I suggest you to do is bring your own training image if you have customization request.

**Comment by vackysh** [comment]
This issue is resolved. Now closing

**Comment by Jeffwan** [comment]
> This issue is resolved. Now closing

Have you figured out a way to make it? Did you try bring your own container?
