### ISSUE TITLE
Tide and GitHub merge requirements don't match

### ISSUE THREAD

**Issue by michelle192837** [kubeflow/pipelines#1371]
Tide is continually failing to merge PR #1367 (https://prow.k8s.io/tide-history?repo=kubeflow%2Fpipelines&branch=master) with:

failed merging [1367]: [PR is unmergable. Do the Tide merge requirements match the GitHub settings for the repo? Required status check "Travis CI - Pull Request" is queued.]

The GitHub repo settings should be updated to match Tide requirements, after which it should be fine to remove the hold label from the PR and let it merge.

**Comment by IronPan** [comment]
this seems not an issue any more? close for now. feel free to reopen if you see this again. 
/close
