### ISSUE TITLE
validate workflow on upload

### ISSUE THREAD

**Issue by strangemonad-faire** [kubeflow/pipelines#1373]
Sorry if this is a dupe, I couldn't find anything obvious.

When uploading a pipeline or workflow yaml file, it seems like minimal validation happens. If you then create a manual run of a workflow that has an error in it, the run fails (since the Argo workflow resource is validated by the workflow custom resource controller when it's created

**Comment by Ark-kun** [comment]
We could run Argo lint to check the pipeline spec.
