### ISSUE TITLE
Annotating components that require GCP secrets to work

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#1374]
Some components need GCS credentials to access GCP services.
Currently we use `.apply(use_gcp_secret(...))` to add secret volume mounts to the task container.

It might be better to just mark the component as requiring GCP credentials and leave the particular way the credentials are made available  to the backend (which can use the same secrets volume for now).

Let's add some marker annotation to the GCP components.

**Comment by Ark-kun** [comment]
I propose the following annotation based on IAM permissions:

```yaml
annotations:
  cloud.google.com/required_iam_permissions: 'bigquery.tables.get,bigquery.tables.update'
```

The value is a ','-delimited (or maybe JSON-serialized) list of IAM permission IDs. See https://cloud.google.com/iam/docs/permissions-reference for the full reference.

**Comment by SinaChavoshi** [comment]
I'm removing myself from this issue as I will not have capacity to help.

**Comment by SinaChavoshi** [comment]
reopening as closed by accident only meant to remove myself :)

**Comment by Ark-kun** [comment]
@SinaChavoshi I've included you since this seems to be related to the pipeline validation and diagnose_me tool/component.
