### ISSUE TITLE
Support changing step name for ContainerOp created from load_component_from_*

### ISSUE THREAD

**Issue by hongye-sun** [kubeflow/pipelines#1378]
Right now, there is no way to change the name of it. The name is currently generated from the component name in the yaml file.

**Comment by Ark-kun** [comment]
> Right now, there is no way to change the name of it. The name is currently generated from the component name in the yaml file.

What exactly is "step name" (in Argo terms)? Is it "template name" or "task name"?

Currently the step name is considered opaque implementation detail (the compiler does some generation and transformation in any case). The generated name can be changed by changing the component name or by changing the compiler. We could switch to hash-based IDs for instance.

What scenarios require setting explicit step name?

**Comment by hongye-sun** [comment]
It should be the name displayed in the KFP UI. I think it should be the task name. The use case is that user wants to customize the name of GCP component when it is displayed on the UI. It is fine to add suffix after it in case of duplication.

**Comment by Ark-kun** [comment]
>The use case is that user wants to customize the name of GCP component when it is displayed on the UI.

I see. What do you think about adding the custom name to annotations and making the UI show it instead of the component name if available?

```
my_task = my_op(...).add_pod_annotation('kubeflow.org/pipelines/task_display_name', 'My custom name')
```

We can hide it behind a sugar method like `set_custom_display_name`:
```
my_task = my_op(...).set_custom_display_name('My custom name')
```

WDYT?

**Comment by hongye-sun** [comment]
Any reason why we don't let user change the task name directly? I think we support it in the ContainerOp. How about we provide a cop_kvargs parameter on the component factory method to let user to change ContainerOP's default settings.
```
my_task = my_op(..., cop_kvargs = {'name': 'custom name'})
```

Or we can expose name as a property:
```
my_task = my_op(...)
my_task.name = 'custom name'
```

**Comment by hongye-sun** [comment]
Make the bug as p1. It is currently blocking a customer demo.

**Comment by Ark-kun** [comment]
Fixed by https://github.com/kubeflow/pipelines/pull/1463
