### ISSUE TITLE
Option for disabling using .tar.gz when uploading artifact

### ISSUE THREAD

**Issue by alicelee0606** [kubeflow/pipelines#1383]
Wondering if KFP is planning to support uploading artifacts without archiving to tar.gz since Argo supports this feature as well:
https://github.com/argoproj/argo/commit/11e57f4dea93fde60b204a5e7675fec999c66f56#diff-2ecc5d66cfc406141926d272bab09f2f

This is useful because we might want to upload some result images as artifacts and later visualize them in html with output viewer. Since current output viewer does not support referencing to other files in the filesystem, we can only upload the images first.

**Comment by Ark-kun** [comment]
@gaoning777 @IronPan 
I think we can just completely switch to non-compressed artifacts.
It will require a bit of changes to the metrics-gathering in the backend and some test infrastructure changes.

**Comment by Ark-kun** [comment]
@gaoning777  WDYT?

**Comment by IronPan** [comment]
SGTM
@hongye-sun WDYT?

**Comment by gaoning777** [comment]
SGTM

**Comment by gaoning777** [comment]
SG

**Comment by Bobgy** [comment]
Sorry for the delay. Is the use case showing it in visualization in ml-pipeline-ui?

I assume you are talking about reading files from minio: https://github.com/kubeflow/pipelines/blob/c74a9d8cd286f70ddd357ef5e4c352ddbcf6645c/frontend/server/server.ts#L225

It doesn't support raw files as for now. We can easily implement that I believe though.
What would use case for folders look like?

**Comment by Ark-kun** [comment]
>It doesn't support raw files as for now. We can easily implement that I believe though.

It would be great to do so at least for single files.

> Besides, what would use case for folders look like?

Folders are used by saved Tensorflow models/estimators. TF stores the network structure and the weights/checkpoints separately.

**Comment by Bobgy** [comment]
@Ark-kun what is priority for this? It sounds like needing a lot of changes + testing to make sure the whole system is switched. Can we add this to quarterly planning?
