### ISSUE TITLE
Research dill vs. cloudpickle for pickling functions

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#1387]
We now use function pickling to capture python code and it's dependencies when creating components form python code. Fairing and Pipelines use the cloudpickle library for that, but some other projects use dill. We need to research the differences and possibly switch to a different library.

Cloudpickle: https://github.com/cloudpipe/cloudpickle
Dill: http://trac.mystic.cacr.caltech.edu/project/pathos/wiki/dill

Some relevant discussions:
https://github.com/RaRe-Technologies/gensim/issues/558#issuecomment-217445542 
https://github.com/uqfoundation/multiprocess/issues/22#issuecomment-243120410

**Comment by vicaire** [comment]
@Ark-kun, could you please add details about the feature that this research is related to?

**Comment by Ark-kun** [comment]
> @Ark-kun, could you please add details about the feature that this research is related to?

Done.

**Comment by gaoning777** [comment]
I think you are working on the codegen part of the component authoring, I'll let you lead the efforts.
