### ISSUE TITLE
Working with TF.Dataset in Pipeline

### ISSUE THREAD

**Issue by josefkorbel** [kubeflow/pipelines#1391]
I am playing around with Kubeflow Pipelines, what I want to achieve is have one step (python function) where I create an `Iterator` (`generator`), from which I want to create a `TF.Dataset`

Connections between Kubeflow steps are only allowed to have primitive-type inputs/outputs, thus I am not able to pass the Iterator or the iterator-initialized-dataset into the next step.

This is overview of the pipeline
```bash
+-------------+   +-------------------+   +------------------------------+
| Data Ingest +---> Create TF.Dataset +---> Consume Tf.Dataset in Model  |
+-------------+   +-------------------+   +------------------------------+
```
Since I can pass around only primitive types, is there any possibility for storing the Iterator-Initialized Dataset? 

Data are on Google Storage, the size is big enought to not fit into memory, how would anyone achieve this?

I know this is kind of broad question, but since Kubeflow is pretty new, I cannot find any helpful resources anywhere.

**Comment by Ark-kun** [comment]
>Since I can pass around only primitive types, is there any possibility for storing the Iterator-Initialized Dataset?

When your producer and consumer are executed on different machines in a distributed system it's inevitable that the data must be at some point serialized to byte blobs to be sent over network.
For some primitive types this already happens automatically, but for most types there is no automatic support for serialization/deserialization. You cannot just pass in-memory objects right now. Everythiong needs to be serialized to bytes or strings.

More so, unfortunately, the system right now does not support directly passing big blobs of data yet.

This leaves you with a couple of options:

1. Serialize the data, saving it to external storage (e.g. GCS) and then pass the URI of the data to downstream task which will load the data from the external storage
2. Mount a volume (preferably ReadWriteMany) to producer and serialize the data to a file in that volume, then pass the file path to the downstream task. Mount the volume to the consumer task which will load the data from the file path provided to it.

You can also read https://www.kubeflow.org/docs/pipelines/sdk/component-development/

**Comment by josefkorbel** [comment]
Thank you for your fast response @Ark-kun 

We've ultimately decided we will store the processed data on GCS since storage is cheap nowadays, so I'll pass the URI around and initialize the the `TF.Dataset` in the Model step from gcs-client-created iterator for blobs.

**Comment by vicaire** [comment]
Resolving. Please re-open if there is anything outstanding.
