### ISSUE TITLE
Setting custom domain for pipeline

### ISSUE THREAD

**Issue by Kyrremann** [kubeflow/pipelines#1411]
I'm trying to run Kubeflow on-prem, where we use custom domain, `nais.local` instead of `cluster.local`.

This crashes the `ml-pipeline-persistenceagent`, and I've haven't found a way to set the custom domain.

Logs:
```
W0531 06:39:19.094285       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2019-05-31T06:41:26Z" level=fatal msg="Error creating ML pipeline API Server client: Failed to initialize pipeline client. Error: Waiting for ml pipeline API server failed after all attempts.: Get http://ml-pipeline.dataverk.svc.cluster.local:8888/apis/v1beta1/healthz: dial tcp: lookup ml-pipeline.dataverk.svc.cluster.local: no such host: Waiting for ml pipeline API server failed after all attempts.: Get http://ml-pipeline.dataverk.svc.cluster.local:8888/apis/v1beta1/healthz: dial tcp: lookup ml-pipeline.dataverk.svc.cluster.local: no such host"
```

The interesting part:
```
dial tcp: lookup ml-pipeline.dataverk.svc.cluster.local: no such host
```

Any tips to what I can do?

**Comment by Kyrremann** [comment]
Turns out I wasn't using the latest version of persistence agent image.

**Comment by jobvarkey** [comment]
I am getting similar error. Can you please tell how it was fixed? Thanks

**Comment by Kyrremann** [comment]
> I am getting similar error. Can you please tell how it was fixed? Thanks

As I said, I needed to use a newer version of the persistence agent image, as the older ones didn't  support custom domain. 
If you're using the latest, maybe the support has been removed again?
