### ISSUE TITLE
Issue with link to Stackdriver logs. 

### ISSUE THREAD

**Issue by gaoning777** [kubeflow/pipelines#1414]
The current stackdriver log link is generated based on the project id and cluster name, which is retrieved from GCE metadata servers. For example http://metadata/computeMetadata/v1/instance/attributes/cluster-name. 
It is recommended by the GKE group to store the metadata in the configmap and retrieve them from the configmap afterwards. Since these metadata is static throughout the cluster's lifecycle, it is better than accessing the GCE metadata servers, which might not be reliable. 
Another motivation to use the configmap is to support GKE on-prem where no GCE metadata server is available.

**Comment by gaoning777** [comment]
@Bobgy Do you think we can add the info during the deployment?

**Comment by Bobgy** [comment]
Does GKE on-prem mean Anthos? How would that info be retrieved initially if no GCE metadata server?

After a short consideration, I think there are some complexities, especially in garbage collection of the configmap (similar to https://github.com/kubeflow/pipelines/pull/2391).

We can start with caching the response in UI server if that's a problem.

**Comment by gaoning777** [comment]
In case of GKE on-prem, there is no such metadata, thus only default metadata for project id and cluster name. 
we can probably start with adding a configmap during the deployment with project id and cluster name if deployed in GKE. Otherwise, add a configmap for a default value. When the UI fetches the configmap, it will detect the default value in case of on-prem and output meaningful messages instead of output a link that does not work. WDYT?
In terms of the garbage collection. I guess the life span of metadata configmap is the same as the KF deployment. Why do we need to garbage collect the configmap?

**Comment by Bobgy** [comment]
> In case of GKE on-prem, there is no such metadata, thus only default metadata for project id and cluster name.
> we can probably start with adding a configmap during the deployment with project id and cluster name if deployed in GKE. Otherwise, add a configmap for a default value. When the UI fetches the configmap, it will detect the default value in case of on-prem and output meaningful messages instead of output a link that does not work. WDYT?
> In terms of the garbage collection. I guess the life span of metadata configmap is the same as the KF deployment. Why do we need to garbage collect the configmap?

Hosted KFP is usually deleted by deleting the application. It doesn't delete the namespace. If a configmap is created afterwards, it will not be owned by the application.

**Comment by gaoning777** [comment]
> > we can probably start with adding a configmap during the deployment with project id and cluster name if deployed in GKE. Otherwise, add a configmap for a default value. When the UI fetches the configmap, it will detect the default value in case of on-prem and output meaningful messages instead of output a link that does not work. WDYT?
> 
> When we cannot fetch info from cluster name, we shouldn't show stackdriver link to users. I think that solves the UX problem too. (I haven't checked stackdriver link related code, but it was the case with #2789)

Agreed. 
> 
> > In terms of the garbage collection. I guess the life span of metadata configmap is the same as the KF deployment. Why do we need to garbage collect the configmap?
> 
> Hosted KFP is usually deleted by deleting the application. It doesn't delete the namespace. If a configmap is created afterwards, it will not be owned by the application.

Thanks

**Comment by Bobgy** [comment]
I think we can adding caching is good enough for now
