### ISSUE TITLE
PipelineParam class should not expose TypeMeta

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#1420]
TypeMeta is an implementation detail type that we do not want to expose in public API
https://github.com/kubeflow/pipelines/blob/87b96a0a7a5bec3ad502714f21d69694e46b2f4f/sdk/python/kfp/dsl/_pipeline_param.py#L154

https://github.com/kubeflow/pipelines/pull/938/files#diff-3ce4e39a5176a4d398491d2a85fea5c9R70

/cc @gaoning777

**Comment by gaoning777** [comment]
agreed
