### ISSUE TITLE
SDK - Change Lightweight component code gen to not require cloudpickle at runtime

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#1430]
The cloudpickle runtime dependency was inadvertently introduced in https://github.com/kubeflow/pipelines/pull/1372 which caused issue at runtime https://github.com/kubeflow/pipelines/issues/1426 . The issue was fixed short term in https://github.com/kubeflow/pipelines/pull/1429, but for long-term I should research how to get rid of the cloudpickle runtime dependency.

**Comment by Ark-kun** [comment]
Will be fixed by https://github.com/kubeflow/pipelines/issues/1430

**Comment by gaoning777** [comment]
> Will be fixed by #1430

This links back to this issue. Wrong link?

**Comment by Ark-kun** [comment]
> This links back to this issue. Wrong link?

My mistake. Deleted that line.
