### ISSUE TITLE
katib launcher image is out of date

### ISSUE THREAD

**Issue by hougangliu** [kubeflow/pipelines#1436]
gcr.io/ml-pipeline/ml-pipeline-kubeflow-studyjob:2c2445df83fa879387a200747cc20f72a7ee9727 in https://github.com/kubeflow/pipelines/blob/master/components/kubeflow/katib-launcher/component.yaml#L22 is out of date now, we need build a new image and update it in 
https://github.com/kubeflow/pipelines/blob/master/components/kubeflow/katib-launcher/component.yaml#L22

build new image as below
```
bash build_image.sh
```

**Comment by Tomcli** [comment]
cc @animeshsingh
