### ISSUE TITLE
FR Pipelines UI -  Back arrow nav should be smarter.

### ISSUE THREAD

**Issue by strangemonad-faire** [kubeflow/pipelines#1438]
Pipeline detail and run detail pages should be smarter about how the "<-" back arrow works. It currently just blindly goes back in history.

e.g. 1) share a deep link to a run (.../pipeline/#/runs/details/2dc039dd-8662-11e9-84ac-42010a800070) open a new browser tab load that page. There is no browser history, the back arrow leaves the kubeflow UI.

Desired: return to the either pipeline/#/experiments or the experiment that run belonged to

e.g. 2) upload a pipeline (or choose an existing one), load that pipeline's details and create a run. You're taken to the experiment details page for the experiment the pipeline was run in. The back arrow takes you to the "New Run" pipeline/#/runs/new?... dialog with empty fields (except for the pipeline field).

Desired: There's not much value in returning to the empty "New Run: dialog. the arrow should behave more like a way to dismiss pages within the pipelines taxonomy (e.g. go back to the the experiments page). Additionally, it would be nice if creating a new run went right to that run's detail page (there might currently a race condition with the UI popping up an error if the detail page is loaded too soon after the run is created)

**Comment by Bobgy** [comment]
@strangemonad-faire Thanks for the concrete examples. I agree current behavior seems problematic.

Properly defining ideal back arrow behavior needs some design for every valid case. I remember seeing another thread about this that argued against just going a level up.
