### ISSUE TITLE
Problem in running the create_cluster.py(Dataproc)  pipeline script in local

### ISSUE THREAD

**Issue by hitesh1907nayyar** [kubeflow/pipelines#1452]
Hi,

I am facing an issue where I want to run the create_cluster.py script of pipeline from local system to decode as how the script is working. Link - https://github.com/kubeflow/pipelines/blob/master/components/dataproc/create_cluster/src/create_cluster.py.  I am getting an error 

D:\python create_cluster.py  --project bradley-playground --zone us-central1-a --name ten4 --staging gs://bradley-playground
Traceback (most recent call last):
  File "create_cluster.py", line 26, in <module>
    from common import _utils
ImportError: cannot import name '_utils'

Can somebody please help on this.

**Comment by Ark-kun** [comment]
You can copy the https://github.com/kubeflow/pipelines/tree/master/components/dataproc/common dir alongside or include its parent in `PYTHONPATH`.

**Comment by hitesh1907nayyar** [comment]
Thanks @Ark-kun .

I tried with the above steps and the above problem was resolved. But now i am facing another issue. When i run  : python create_cluster.py --project softwarization-net --region us-central1-a --name kubesparkless --staging gs://playgroundbucket1234 then i get the below error:

Copying file://D:\MACHINE LEARNING\Kubeflow\pipelines\components\dataproc\create_cluster\src\initialization_actions.sh [Content-Type=application/x-sh]...
\ [1 files][  802.0 B/  802.0 B]
Operation completed over 1 objects/802.0 B.
Creating cluster...
Omitting bucket "gs://playgroundbucket1234\xgb_190608_194538\initialization_actions.sh/". (Did you mean to do rm -r?)
CommandException: No URLs matched
Traceback (most recent call last):
  File "create_cluster.py", line 58, in <module>
    main()
  File "create_cluster.py", line 47, in main
    create_response = _utils.create_cluster(api, args.project, args.region, args.name, dest_files[0])
  File "D:\MACHINE LEARNING\Kubeflow\pipelines\components\dataproc\create_cluster\src\common\_utils.py", line 48, in create_cluster
    body=cluster_data).execute()
  File "C:\Users\hitesh_n\AppData\Local\Programs\Python\Python36-32\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\hitesh_n\AppData\Local\Programs\Python\Python36-32\lib\site-packages\googleapiclient\http.py", line 851, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://dataproc.googleapis.com/v1/projects/softwarization-net/regions/us-central1/clusters?alt=json returned "Object URI 'gs://playgroundbucket1234\xgb_190608_194538\initialization_actions.sh' must include an object name">

An cluster is not created. Can you help me with the same ?

Best Regards
Hitesh Nayyar

**Comment by hitesh1907nayyar** [comment]
This is resolved. Please close this.

**Comment by Ark-kun** [comment]
> This is resolved

Happy to hear that.
