### ISSUE TITLE
[KeyError: u'UNIQUE'] error in analyze xgboost-spark pipline example

### ISSUE THREAD

**Issue by hitesh1907nayyar** [kubeflow/pipelines#1477]
Hi, 

I am trying to run the analyze.py script which is there in xgboost-spark pipeline example ( Link - https://github.com/kubeflow/pipelines/tree/master/samples/xgboost-spark).In order to run the script and understand the flow i copied the schema.json and train.csv from bradley-playground to my storage directly.  Now when i a running the script i am getting below error:

root@instance-1:/home/hcl_google_pri_infra/pipelines/components/dataproc/analyze/src# python3 analyze.py --project softwarization-net --region us-central1 --cluster kubesparkless1 --output gs://playgroundbucket1234/analysis --train gs://playgroundbucket1234/sfpd/train.csv --schema gs://playgroundbucket1234/schema.json
Activated service account credentials for: [kubespark@softwarization-net.iam.gserviceaccount.com]
Copying file:///home/hcl_google_pri_infra/pipelines/components/dataproc/analyze/src/analyze_run.py [Content-Type=text/x-python]...
/ [1 files][  3.7 KiB/  3.7 KiB]                                                
Operation completed over 1 objects/3.7 KiB.                                      
Submitting job...
Job request submitted. Waiting for completion...
Removing gs://playgroundbucket1234/analysis/xgb_190610_075032/analyze_run.py...
/ [1/1 objects] 100% Done                                                       
Operation completed over 1 objects.                                              
Traceback (most recent call last):
  File "analyze.py", line 62, in <module>
    main()
  File "analyze.py", line 52, in main
    _utils.wait_for_job(api, args.project, args.region, job_id)
  File "/home/hcl_google_pri_infra/pipelines/components/dataproc/analyze/src/common/_utils.py", line 81, in wait_for_job
    raise Exception(result['status']['details'])
Exception: Job failed with message [KeyError: u'UNIQUE']. Additional details can be found in 'gs://dataproc-67063ea6-e22f-4176-b121-855bccd9a014-us-central1/google-cloud-dataproc-metainfo/45dc16e1-b341-454a-aab8-ff0e19f2d3ad/jobs/ce17266a-1aad-430d-b5f8-a84fc15fa7fc/driveroutput'.

In the detail logs these lines are mentioned:

Traceback (most recent call last):
  File "/tmp/ce17266a-1aad-430d-b5f8-a84fc15fa7fc/analyze_run.py", line 54, in <module>
    schema_json, schema = load_schema(args.schema)
  File "/tmp/ce17266a-1aad-430d-b5f8-a84fc15fa7fc/analyze_run.py", line 40, in load_schema
    fields = [StructField(x['name'], type_map[x['type']]) for x in schema_json]
KeyError: u'UNIQUE'

Can anybody please help me on this as how to resolve this error ?

**Comment by jessiezcc** [comment]
@gaoning777, have you tried xgboost sample in the past?

**Comment by gaoning777** [comment]
The xgboost sample are covered by the sample tests. 
Could you try the data from https://github.com/kubeflow/pipelines/blob/377464f2f4232b68294f7f7829a46898bab3cedf/samples/xgboost-spark/xgboost-training-cm.py#L204?
Let me know if you can still see the issue using the data above.

**Comment by gaoning777** [comment]
Cannot reproduce it.
