### ISSUE TITLE
Handling of boolean input types

### ISSUE THREAD

**Issue by kvalev** [kubeflow/pipelines#1488]
I have a pipeline that has a boolean parameter:

```
def test(
    param: dsl.PipelineParam = dsl.PipelineParam(name='param', value=True, param_type=TypeMeta('bool')),
) -> None:
    pass
```

When starting a new pipeline via the UI, the input field is a textbox, prefilled with the input string 'True'. Given that the input value is evaluated using `bool(value)`, the only way to start the pipeline with a `False` value is to leave the input textbox empty.

It seems that currently the pipeline does not gracefully handle boolean parameters?

**Comment by jessiezcc** [comment]
@jingzhang36, can you see whether it's addressable at UI layer?

**Comment by Ark-kun** [comment]
Thanks for the report.
I'll be releasing support for boolean input types very soon.

P.S. You do not have to use PipelineParam anywhere in your code. Just write the pythonic function signature:

```python
def my_pipeline(
    param : bool = True),
) -> None:
    pass
```

**Comment by logicbomb421** [comment]
hey guys just wondering when this will be published? really need the fix in here. been on 0.1.27 for several days now :(

is there an established release schedule?

**Comment by Ark-kun** [comment]
Usually we release a new version every week. Last week release was not finished.
There would be a new release tomorrow unless some bugs are found.
