### ISSUE TITLE
Support deep links in web ui

### ISSUE THREAD

**Issue by jdelfino** [kubeflow/pipelines#1498]
It would be useful to be able to create URLs that point to specific individual experiments, runs, and maybe even component instances within a run. The use case I have in mind is wanting to share results with a colleague - sending them a URL is easier than pointing them at the dashboard, and telling them to search around for an experiment/run/etc.

**Comment by ryan-williams** [comment]
I just ran into this issue as well.

IIRC the UI did deep-links in earlier versions of KFP.

I've upgraded to 0.1.19 and indeed everything seems to just be at `https://….endpoints.….cloud.goog/_/pipeline-dashboard`

**Comment by ryan-williams** [comment]
xref https://github.com/kubeflow/pipelines/issues/1364

If you go to `https://….endpoints.….cloud.goog/pipeline/#` you get a similar dashboard, but the links actually change the browser bar; paths under that root all resolve sensibly, e.g. `https://….endpoints.….cloud.goog/pipeline/#/experiments`.

`/_/pipeline-dashboard` seems to be a SPA that links to equivalent pages under `/pipeline/#`, but intercepts clicks, changes the data on the page, and keeps the browser at `/_/pipeline-dashboard`.

Seems like an oversight or bug in the SPA machinery: not updating the browser bar with the virtual page changes.

**Comment by jessiezcc** [comment]
@rileyjbauer, can u evaluate?

**Comment by rileyjbauer** [comment]
@avdaredevil This is a result of the way the Kubeflow dashboard handles the various Kubeflow apps, correct? Can we make it so that the URL updates along with the current page?

**Comment by avdaredevil** [comment]
Hey @rileyjbauer thanks for linking me in, this is something @prodonjs was working on. We didn't have a conclusive decision on how the links should be passed back up to the Central-Dashboard since page updates behind an iframe work differently.

**Comment by prodonjs** [comment]
https://github.com/kubeflow/kubeflow/issues/3042 is where we're tracking this issue and hopefully something will be in place for the next release of KF some time later in the third quarter.

**Comment by prodonjs** [comment]
This was addressed by https://github.com/kubeflow/kubeflow/issues/3042.

/close
