### ISSUE TITLE
Pipeline UI shows "Sorry, /pipeline/ is not a valid page"

### ISSUE THREAD

**Issue by nakfour** [kubeflow/pipelines#1501]
Hi,
I installed Kubeflow version 0.5.1, and from the ambassador route, I can get to all the UI elements (Kubeflow doc, Notebooks, TFJob dashboard, etc) except pipelines. the page shows an error message: Sorry, /pipeline/ is not a valid page.
ambassador pod shows this message but no error
-------
ACCESS [2019-06-12T22:05:46.226Z] "GET /pipeline/ HTTP/1.1" 304 - 0 0 0 0 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/
---------
Has anyone seen this? What happens after GET /pipeline is handled by ambassador?

**Comment by durandom** [comment]
@nakfour the issues seems similar to https://github.com/kubeflow/kubeflow/issues/3414



Although the `pipeline` route is'nt even registered with ambassador:
http://ambassador-admin-kubeflow.10.16.208.2.nip.io/ambassador/v0/diag/


URL | Service | Weight
-- | -- | --
http://ambassador-admin-kubeflow.10.16.208.2.nip.io/seldon/ai-library/m-detectfraud/ | detectfraud-m-detectfraud.ai-library:8000 | 100.0%
http://ambassador-admin-kubeflow.10.16.208.2.nip.io/seldon/ai-library/m-regression/ | regression-m-regression.ai-library:8000 | 100.0%
http://ambassador-admin-kubeflow.10.16.208.2.nip.io/seldon/ai-library/m-assoc/ | assoc-m-assoc.ai-library:8000 | 100.0%
http://ambassador-admin-kubeflow.10.16.208.2.nip.io/tensorboard/ tensorboard/ | tensorboard.kubeflow:9000 | 100.0%
http://ambassador-admin-kubeflow.10.16.208.2.nip.io/ambassador/v0/check_ready | 127.0.0.1:8877 | 100.0%
http://ambassador-admin-kubeflow.10.16.208.2.nip.io/ambassador/v0/check_alive | 127.0.0.1:8877 | 100.0%
http://ambassador-admin-kubeflow.10.16.208.2.nip.io/seldon.protos.Seldon/ seldon: m-detectfraud namespace: ai-library | detectfraud-m-detectfraud.ai-library:5001 | 100.0%
http://ambassador-admin-kubeflow.10.16.208.2.nip.io/seldon.protos.Seldon/ seldon: m-regression namespace: ai-library | regression-m-regression.ai-library:5001 | 100.0%
http://ambassador-admin-kubeflow.10.16.208.2.nip.io/seldon.protos.Seldon/ seldon: m-assoc namespace: ai-library | assoc-m-assoc.ai-library:5001 | 100.0%
http://ambassador-admin-kubeflow.10.16.208.2.nip.io/seldon.protos.Seldon/ seldon: m-detectfraud | detectfraud-m-detectfraud.ai-library:5001 | 100.0%
http://ambassador-admin-kubeflow.10.16.208.2.nip.io/seldon.protos.Seldon/ seldon: m-regression | regression-m-regression.ai-library:5001 | 100.0%
http://ambassador-admin-kubeflow.10.16.208.2.nip.io/seldon.protos.Seldon/ seldon: m-assoc | assoc-m-assoc.ai-library:5001 | 100.0%
http://ambassador-admin-kubeflow.10.16.208.2.nip.io/seldon/m-detectfraud/ | detectfraud-m-detectfraud.ai-library:8000 | 100.0%
http://ambassador-admin-kubeflow.10.16.208.2.nip.io/seldon/m-regression/ | regression-m-regression.ai-library:8000 | 100.0%
http://ambassador-admin-kubeflow.10.16.208.2.nip.io/seldon/m-assoc/ | assoc-m-assoc.ai-library:8000 | 100.0%
http://ambassador-admin-kubeflow.10.16.208.2.nip.io/ambassador/v0/ | 127.0.0.1:8877 | 100.0%
http://ambassador-admin-kubeflow.10.16.208.2.nip.io/jupyter/ | jupyter-web-app.kubeflow | 100.0%
http://ambassador-admin-kubeflow.10.16.208.2.nip.io/tfjobs/ | tf-job-dashboard.kubeflow | 100.0%
http://ambassador-admin-kubeflow.10.16.208.2.nip.io/katib/ | katib-ui.kubeflow | 100.0%
http://ambassador-admin-kubeflow.10.16.208.2.nip.io/argo/ | argo-ui.kubeflow | 100.0%
http://ambassador-admin-kubeflow.10.16.208.2.nip.io/ | centraldashboard.kubeflow | 100.0%

**Comment by durandom** [comment]
accessing the pipeline pod directly via creating a route to :8888 gives `404 page not found`.
So the pod is accepting HTTP requests.
Here's the log from the `ml-pipeline` pod

```

  | I0614 13:06:40.999584       8 client_manager.go:114] Initializing client manager
-- | --
  | [mysql] 2019/06/14 13:06:41 packets.go:427: busy buffer
  | [mysql] 2019/06/14 13:06:41 packets.go:408: busy buffer
  | E0614 13:06:41.063159       8 db_status_store.go:74] Failed to commit transaction to initialize database status table
  | I0614 13:06:41.066427       8 client_manager.go:274] We already own mlpipeline
  | I0614 13:06:41.066438       8 client_manager.go:279] Successfully created bucket mlpipeline
  | I0614 13:06:41.070721       8 client_manager.go:142] Client manager initialized successfully
  | I0614 13:06:41.071346       8 main.go:144] Samples already loaded in the past. Skip loading.
  | I0614 13:06:41.071359       8 main.go:92] Starting Http Proxy
  | I0614 13:06:41.071381       8 main.go:71] Starting RPC server


```

Do we need a mysql pod?

**Comment by durandom** [comment]
ok. so `mysql` is up and running. How does the pipeline UI get to the mysql service?

**Comment by nakfour** [comment]
@durandom the ambassador logs when receiving GET /pipeline/ HTTP/1.1, are not complaining about the page not found. I am still not clear what happens after ambassador receives this GET request. And I am not sure if the mysql service has anything to do with this. Also I think this issue is different than ** kubeflow/kubeflow#3414**

**Comment by durandom** [comment]
but the ambassador doesnt even have a route to the `ml-pipeline` pod. 
So, lets get ambassador out of the equation.

Why do we get a `404` when connecting to the `ml-pipeline` pod?

**Comment by jessiezcc** [comment]
@IronPan to shed some light

**Comment by hridyeshpant** [comment]
i am also getting the same error when hitting /ml-pipeline. I created ingress rule for this service with port 8888 but getting ```404``` error when trying to hit ml-pipeline API outside the cluster. Same this is working if I used port forwarding ```kubectl port-forward svc/ml-pipeline -n kubeflow 8888:8888```

**Comment by rmgogogo** [comment]
I believe it's not an issue now. Here close but feel free to reopen if issue still there.
