### ISSUE TITLE
Enable resubmit feature

### ISSUE THREAD

**Issue by alicelee0606** [kubeflow/pipelines#1509]
Argo provides resubmit feature based on memoized results from failed workflow (https://github.com/argoproj/argo/blob/8bf7578e1884c61128603bbfaa677fd79cc17ea8/cmd/argo/commands/resubmit.go). Wondering if it is also possible to enable such feature on KFP as well? For basic usage, the support from backend and SDK might be enough. But it would be also great if users can do it on the UI (maybe like how Airflow does?).

**Comment by Bobgy** [comment]
We already have retry, I think it's using the argo feature you mentioned.
Please take a look.
