### ISSUE TITLE
TFMA errors when trying to visualize Chicago Taxi example results

### ISSUE THREAD

**Issue by cvenets** [kubeflow/pipelines#1514]
Hello all, I'm running the TFX (Chicago Taxi) example Pipeline on-prem, which completes successfully. The analysis step produces the 4 corresponding files: `plots`, `output_display.html`, `metrics`, `eval_config`.

The Docker Image for the Analysis step inside my Pipeline is:
`gcr.io/ml-pipeline/ml-pipeline-dataflow-tfma:6ad2601ec7d04e842c212c50d5c78e548e12ddea`

I have the 4 resulting files accessible from inside a Jupyter Notebook, and I'm trying to visualize the results using the TFMA library from inside a Notebook. What is the best way to do it?

When trying to use this Notebook:
https://github.com/tensorflow/tfx/blob/master/tfx/examples/chicago_taxi/chicago_taxi_tfma.ipynb

I run the following successfully:
```
import os
import tensorflow_model_analysis as tfma

PATH_TO_RESULT = os.path.join('/home/jovyan/data', 'tfx-taxi-cab-classification-pipeline-example-for-on-prem-cfz885/analysis');
```

but in the next cell I get:

```
result = tfma.load_eval_result(PATH_TO_RESULT)

DecodeErrorTraceback (most recent call last)
<ipython-input-10-15e24d0c29bf> in <module>()
----> 1 result = tfma.load_eval_result(PATH_TO_RESULT)

/opt/conda/envs/py2/lib/python2.7/site-packages/tensorflow_model_analysis/api/model_eval_lib.pyc in load_eval_result(output_path)
    109   """Creates an EvalResult object for use with the visualization functions."""
    110   metrics_proto_list, plots_proto_list = serialization.load_plots_and_metrics(
--> 111       output_path)
    112 
    113   slicing_metrics = [(key, _convert_metric_map_to_dict(metrics_data))

/opt/conda/envs/py2/lib/python2.7/site-packages/tensorflow_model_analysis/api/impl/serialization.pyc in load_plots_and_metrics(output_path)
    128     output_path):
    129   slicing_metrics = _load_and_deserialize_metrics(
--> 130       path=os.path.join(output_path, _METRICS_OUTPUT_FILE))
    131   plots = _load_and_deserialize_plots(
    132       path=os.path.join(output_path, _PLOTS_OUTPUT_FILE))

/opt/conda/envs/py2/lib/python2.7/site-packages/tensorflow_model_analysis/api/impl/serialization.pyc in _load_and_deserialize_metrics(path)
    105   result = []
    106   for record in tf.python_io.tf_record_iterator(path):
--> 107     metrics_for_slice = metrics_for_slice_pb2.MetricsForSlice.FromString(record)
    108     result.append((
    109         deserialize_slice_key(

DecodeError: Error parsing message
```

Thank you!

**Comment by jlewi** [comment]
http://gcr.io/ml-pipeline/ml-pipeline-dataflow-tfma:6ad2601ec7d04e842c212c50d5c78e548e12ddea

Looks like the image is from February.

**Comment by jessiezcc** [comment]
@krazyhaas, anyone from TFX can take a look at this?

**Comment by ruoyu90** [comment]
@cvenets could you provide some more info on how to reproduce the error? The notebook works fine on TFX 0.13 release on my end following [this](https://github.com/tensorflow/tfx/tree/master/tfx/examples/chicago_taxi) instruction.

**Comment by jessiezcc** [comment]
closing since no response for 8 days, feel free to reopen when there is an update.

**Comment by cvenets** [comment]
Hello @jessiezcc @ruoyu90

I got the previous when running TFMA v0.9.2. I re-ran the Notebook with the latest Tensorflow (1.14.0) and TFMA (0.13.2) and it seems I'm getting the same error:

```
result = tfma.load_eval_result(PATH_TO_RESULT)

W0723 19:36:45.922904 140527909868800 deprecation.py:323] From /opt/conda/envs/py2/lib/python2.7/site-packages/tensorflow_model_analysis/evaluators/metrics_and_plots_evaluator.py:83: tf_record_iterator (from tensorflow.python.lib.io.tf_record) is deprecated and will be removed in a future version.
Instructions for updating:
Use eager execution and: 
`tf.data.TFRecordDataset(path)`
DecodeErrorTraceback (most recent call last)
<ipython-input-4-15e24d0c29bf> in <module>()
----> 1 result = tfma.load_eval_result(PATH_TO_RESULT)

/opt/conda/envs/py2/lib/python2.7/site-packages/tensorflow_model_analysis/api/model_eval_lib.pyc in load_eval_result(output_path)
    185   """Creates an EvalResult object for use with the visualization functions."""
    186   metrics_proto_list = metrics_and_plots_evaluator.load_and_deserialize_metrics(
--> 187       path=os.path.join(output_path, _METRICS_OUTPUT_FILE))
    188   plots_proto_list = metrics_and_plots_evaluator.load_and_deserialize_plots(
    189       path=os.path.join(output_path, _PLOTS_OUTPUT_FILE))

/opt/conda/envs/py2/lib/python2.7/site-packages/tensorflow_model_analysis/evaluators/metrics_and_plots_evaluator.pyc in load_and_deserialize_metrics(path)
     82   result = []
     83   for record in tf.python_io.tf_record_iterator(path):
---> 84     metrics_for_slice = metrics_for_slice_pb2.MetricsForSlice.FromString(record)
     85     result.append((
     86         slicer.deserialize_slice_key(metrics_for_slice.slice_key),  # pytype: disable=wrong-arg-types

DecodeError: Error parsing message
```

I can provide the actual 4 files produced by the KFP pipeline (`plots`, `output_display.html`, `metrics`, `eval_config`), if that would be helpful. Is there a chance the metrics file has changed format?

**Comment by cvenets** [comment]
@jlewi  @jessiezcc @ruoyu90 did you get the chance to look at this?

How can we debug this? Should I be sending the 4 files your way?

**Comment by cvenets** [comment]
@jlewi @jessiezcc @ruoyu90 kind reminder on this. How can we debug this? Any pointers are highly appreciated.

Thank you!

**Comment by jlewi** [comment]
@cvenets I don't have much to add here; I'll defer to the TFX and pipelines folks.

**Comment by jessiezcc** [comment]
@ruoyu90 will follow up

**Comment by ruoyu90** [comment]
Hey @cvenets are you following [this](https://github.com/tensorflow/tfx/tree/master/tfx/examples/chicago_taxi) instruction? I cannot reproduce the aforementioned error. If no, can you share the steps to reproduce the error? Also since this is TFMA specific, feel free to redirect the issue to TFMA [repository](https://github.com/tensorflow/model-analysis/issues)

**Comment by gaoning777** [comment]
we are transitioning to the new tfx oss sample: https://github.com/kubeflow/pipelines/tree/master/samples/core/parameterized_tfx_oss
Closing it for now.
