### ISSUE TITLE
[Doc] Improve doc about input and output parameters

### ISSUE THREAD

**Issue by hongye-sun** [kubeflow/pipelines#1516]
In current KFP doc, there is very limited doc about how data is passed between steps and how inputs are passed into user's container and how outputs are passed out from container.

**Comment by Ark-kun** [comment]
The original Component development guidelines had a big section dedicated to it. In current document version the section is much smaller, but it can be a starting point https://www.kubeflow.org/docs/pipelines/sdk/component-development/#passing-the-data-to-and-from-the-containerized-program

**Comment by Ark-kun** [comment]
Can you please point to to the sections of the doc that you'd like to be expanded and what information is missing?
