### ISSUE TITLE
[Sample] add a sample for multiple outputs

### ISSUE THREAD

**Issue by hongye-sun** [kubeflow/pipelines#1517]
Add a basic sample to demonstrate returning multiple outputs from a single step. It seems that all samples today are have only single output.

**Comment by Ark-kun** [comment]
The Lightweight components sample has multiple outputs https://github.com/kubeflow/pipelines/blob/master/samples/notebooks/Lightweight%20Python%20components%20-%20basics.ipynb

But I agree that we need more components and samples demonstrating that.

What do you think about just making a component like `Split lines` that can for example split table into train/test.

**Comment by Ark-kun** [comment]
Can you look at the Lightweight sample? WDYT?

**Comment by zanedurante** [comment]
For me, the lightweight sample is good -- I only found it by first finding this GitHub issue though.

**Comment by zanedurante** [comment]
This issue has been documented here: https://github.com/kubeflow/pipelines/issues/1580

**Comment by gaoning777** [comment]
I'm including this as part of the sample efforts.
