### ISSUE TITLE
terminate does not stop retrying

### ISSUE THREAD

**Issue by tinkerer** [kubeflow/pipelines#1519]
If you use set_retry on your ContainerOp, and then later want to terminate your pipeline, it will continue retrying.

**Comment by Ark-kun** [comment]
> If you use set_retry on your ContainerOp, and then later want to terminate your pipeline, it will continue retrying.

What backend version do you have?

**Comment by tinkerer** [comment]
Kubeflow Central Dashboard says "build version v0.5.0"

**Comment by Ark-kun** [comment]
What about the Pipelines dashboard? It should show the commit link. Or maybe you remember the version you've installed.

**Comment by Ark-kun** [comment]
Nevertheless, this is probably upstream issue. I'm just checking whether you Argo version is 2.3.0 or earlier...

**Comment by Ark-kun** [comment]
Probably upstream issue. No response.

**Comment by gaoning777** [comment]
This issue could be reproduced. Amy also reported it recently.
Looks like terminate sets the activedeadlineseconds to 0 but the retry logic is not overridden. 
argo delete overrides the retry logic but the job deletion also deletes all logs.

**Comment by gaoning777** [comment]
argo bug: https://github.com/argoproj/argo/issues/1620

**Comment by Ark-kun** [comment]
> argo bug: [argoproj/argo#1620](https://github.com/argoproj/argo/issues/1620)

Thank you!

**Comment by Ark-kun** [comment]
Closed as upstream issue
