### ISSUE TITLE
usage document for ml command line

### ISSUE THREAD

**Issue by jameswnl** [kubeflow/pipelines#1520]
https://github.com/kubeflow/pipelines/tree/master/backend/src/cmd/ml
E.g. Does it support creating a run?

**Comment by IronPan** [comment]
We'll have a new python SDK replacing the go one. 
WIP 

https://github.com/kubeflow/pipelines/commit/a39ae8eb779e69e4e85e424abba8ecac3f60435f#diff-eae18bc41e1434dd98fa2dd989531da8
