### ISSUE TITLE
Can't read full text in "Choose a pipeline" dialog

### ISSUE THREAD

**Issue by sijieamoy** [kubeflow/pipelines#154]
The parts that are visible in the _Pipeline name_ and the _Description_ columns are too short to decide which one to choose.
![image](https://user-images.githubusercontent.com/3463757/48232293-f962bd80-e365-11e8-8652-d11f4f66f357.png)

Maybe allow text wrapping with a max row height, and/or narrowing the timestamp column?
![image](https://user-images.githubusercontent.com/3463757/48232388-4050b300-e366-11e8-8f6d-12f438879d5c.png)

**Comment by yebrahim** [comment]
I personally prefer giving description more horizontal space, but I'm ok with allowing it to wrap around, although maybe 5 lines is a bit too heigh.

**Comment by yebrahim** [comment]
@sijieamoy are you up for sending a PR for this?

**Comment by cwbeitel** [comment]
Second this issue.

**Comment by vicaire** [comment]
Riley, is this one still an issue?

**Comment by rileyjbauer** [comment]
Yes, this is still an issue

**Comment by rileyjbauer** [comment]
@yebrahim what would you think about expanding the dialog horizontally a bit, but also adding a tooltip to the description cell?

**Comment by yebrahim** [comment]
I think the right solution would involve a more dedicated experience, perhaps a catalog-like UI, for picking the right pipeline. As a fix for this issue, I think what @sijieamoy suggested is good enough, perhaps with a limit on the number of characters or height of the description preview.

**Comment by Bobgy** [comment]
I agree with wrapping description and narrowing timestamp, but we need to rethink about the paging behavior here too.

Maybe an gradual loading list as you scroll with wrapped description sounds like a good idea?

That takes some thorough design. At the meantime, as a fast fix, we can add a title attribute to description that shows full text pop-up on hover. What do you think about this?

**Comment by Bobgy** [comment]
Bump priority, because it will be worse in latest release: 
<img width="866" alt="Screen Shot 2019-10-25 at 9 52 08 AM" src="https://user-images.githubusercontent.com/4957653/67537341-7b7dfa80-f70d-11e9-9ac1-f34326af544c.png">

**Comment by Bobgy** [comment]
I made the dialog bigger first, I think that's enough for usual use case.
![download (20)](https://user-images.githubusercontent.com/4957653/67564157-ee5e9400-f754-11e9-82f5-f2a614415106.png)
