### ISSUE TITLE
Oath setup instruction is not clear for setting up redirect URL

### ISSUE THREAD

**Issue by SinaChavoshi** [kubeflow/pipelines#1541]
The instruction for setting up redirect URL indicates: 

... 
In the Authorized redirect URIs box, enter the following (if it’s not already present in the list of authorized redirect URIs):

https://iap.googleapis.com/v1/oauth/clientIds/<CLIENT_ID>:handleRedirect
<CLIENT_ID> is the OAuth client ID, something like XXX.apps.googleusercontent.com.
...

At this step of the instruction the user does not know their client ID. This specially becomes an issue if they click on automatically generated Authorized redirect URIs  and over write the existing one. 

The work around is for the user to go ahead and complete the step without providing the client id. in the next page they receive the client id and can come back and use it to populate the redirect URL.

**Comment by jessiezcc** [comment]
@SinaChavoshi is following up on this

**Comment by SinaChavoshi** [comment]
instructions are now updated, resolving as fixed.
