### ISSUE TITLE
docker magic component should support requirements file

### ISSUE THREAD

**Issue by SinaChavoshi** [kubeflow/pipelines#1547]
Docker magic  (pipelines/sdk/python/kfp/notebook/_magic.py_) currently only accepts two input parameters as follows
 if len(line.split()) != 2:
    raise ValueError("usage: %%docker [gcr.io/project/image:tag] [gs://staging-bucket]")

However it is common to have a requirements file along with the docker build file. That does not seem to be supported.

**Comment by Ark-kun** [comment]
This would probably be implemented as support for including any files in the Docker context.

**Comment by Ark-kun** [comment]
Related: https://github.com/kubeflow/pipelines/issues/1659

**Comment by Ark-kun** [comment]
Support for `requirements.txt` was implemented in https://github.com/kubeflow/pipelines/pull/1970
