### ISSUE TITLE
Issues with Build 1.21 

### ISSUE THREAD

**Issue by SinaChavoshi** [kubeflow/pipelines#1559]
running the light weight pipeline sample using SDK 1.21 I get the following error , this does not repro if i switch to 1.20 of KFP

You are using pip version 18.0, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "<string>", line 20, in <module>
  File "<ipython-input-4-64f5ff6c312a>", line 4, in add
TypeError: bad argument type for built-in operation

**Comment by Ark-kun** [comment]
As we've discovered couple of weeks ago, 1.21 has multiple problems. Please use the later version.
