### ISSUE TITLE
customization step refers to using KS which is deprecated 

### ISSUE THREAD

**Issue by SinaChavoshi** [kubeflow/pipelines#1560]
https://www.kubeflow.org/docs/gke/customizing-gke/

----> To customize the Kubeflow resources running within the cluster you can modify the ksonnet app in ${KFAPP}/ks_app. For example, to mount additional physical volumes (PVs) in Jupyter:

cd ${KF_APP}/ks_app
**ks param** set jupyter disks "kubeflow-gcfs"
You can then redeploy using kfctl:

cd ${KFAPP}
kfctl apply k8s
or using ksonnet directly:

cd ${KFAPP}/ks_app
**ks apply default**

**Comment by jessiezcc** [comment]
this is not pipeline specific, moving to kubeflow/website
