### ISSUE TITLE
Kubeflow Filestore documentation is out dated 

### ISSUE THREAD

**Issue by SinaChavoshi** [kubeflow/pipelines#1564]
Documentation instructions refer to using KS.. this can be simply done with Kubectl and directly deploying yamls for pv / and pvc. 

Documentation link: https://www.kubeflow.org/docs/gke/cloud-filestore/ 

Example for out dated documentation : 
cd /<path-to-kubeflow-deployment>/${KFAPP}/ks_app
ks generate google-cloud-filestore-pv google-cloud-filestore-pv --name="kubeflow-gcfs" \
   --storageCapacity="${GCFS_STORAGE}" \
   --serverIP="${GCFS_INSTANCE_IP_ADDRESS}"

**Comment by jessiezcc** [comment]
This is not pipeline specific, need to move to Kubeflow.
