### ISSUE TITLE
Upgrading from 0.1.16 to 0.1.22 did not delete ml-pipeline-viewer-controller

### ISSUE THREAD

**Issue by strangemonad-faire** [kubeflow/pipelines#1566]
**What happened:**
Originally had installed KF 0.5 on gcp via the web ui. Upgraded kfp by applying the manifests in the process described here https://github.com/kubeflow/pipelines/tree/master/manifests

ml-pipeline-viewer-controller has been renamed to ml-pipeline-viewer-crd 

**What did you expect to happen:**
I know the upgrade process is not yet meant to be robust but I wonder what the plan is, in a kustomize world, how old resources get deleted version to version when kubetcl-applying

**What steps did you take:**
I manually deleted the old controller (deployment, rs and pod)

**Comment by IronPan** [comment]
Thanks @strangemonad-faire. This is indeed a breaking change. 
We are aiming to provide kustomize upgrade overlay and migration script from Kubeflow v0.6 on.

**Comment by Bobgy** [comment]
Reference: I'm working on upgradability. Progress is tracked in https://github.com/kubeflow/pipelines/issues/1638
