### ISSUE TITLE
Kubeflow UI does not show GCS authorization error

### ISSUE THREAD

**Issue by zanedurante** [kubeflow/pipelines#1568]
**What happened:**
I created a component that uploads a numpy array to a GCS bucket.  The source code for the docker image is below:
```import numpy as np 
import argparse
from tensorflow.python.lib.io import file_io
from io import StringIO


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("--dest", type=str, required=True, help="numpy file destination (GCS)")
    args = parser.parse_args()

    variables = vars(args)
    dest = variables['dest'] # args.dest
    
    arr = np.ones((100,))

    np.save(file_io.FileIO(dest, 'w'), arr)

    f = open('output.txt', 'w')
    f.write(dest)
    f.close()


if __name__== "__main__":
    main()
```
After creating a docker image and uploading it to GCR, I created a pipeline with the following python file:
```
import kfp
from kfp import dsl
from kfp import gcp


def create_np_op(dest):
    return dsl.ContainerOp(
        name='Create numpy array',
        image='gcr.io/intro-to-kubeflow-1/maker:latest',
        arguments = [
            '--dest', dest
        ],
        file_outputs={
            'file': 'output.txt',
        }
    )#.apply(gcp.use_gcp_secret('user-gcp-sa'))

@dsl.pipeline(
    name='Numpy save testing',
    description='Saves numpy array with kubeflow.'
)
def numpy_pipeline(arr_location='gs://hello_world_example_bucket/arr.npy'):
    create_np_task = create_np_op(arr_location)
    
if __name__ == '__main__':
    kfp.compiler.Compiler().compile(numpy_pipeline, __file__ + '.zip')
```

Uncommenting the `.apply(gcp.use_gcp_secret('user-gcp-sa'))` will cause the program to work as expected, however leaving the program as is gives no errors in the kubeflow UI or in the logs even though it cannot successfully access the GCS bucket.

**What did you expect to happen:**
It should error/indicate that something went wrong.

**Comment by jessiezcc** [comment]
@IronPan, can u comment whether it needs API level work?

**Comment by IronPan** [comment]
@zanedurante Thanks for reporting this. 
Pipeline do propagate errors if there is any, and fail the pod which can be reflected in the UI. 

In this specific case, the code ```np.save(file_io.FileIO(dest, 'w'), arr)``` itself doesn't emit error if dest is not exist or don't have permission (ran locally and verified). There is no way for pipeline to know that. 

I'd recommend check with tensorflow file_io doc to see if there is better way to detect the access before calling that line.

**Comment by zanedurante** [comment]
I see--that makes sense.  Thanks for the explanation!

**Comment by IronPan** [comment]
NP. close this issue for now. 
/close
