### ISSUE TITLE
SDK should require kubernetes client lib

### ISSUE THREAD

**Issue by amygdala** [kubeflow/pipelines#158]
It doesn't look like this install:
`pip3 install https://storage.googleapis.com/ml-pipeline/release/0.1.2/kfp.tar.gz --upgrade`
includes the kubernetes client lib, which I think is intended to be included, as the `%%docker` "magic" requires it.

**Comment by gaoning777** [comment]
already merged: https://github.com/kubeflow/pipelines/pull/133

**Comment by gaoning777** [comment]
Feel free to reopen this if problems persist
