### ISSUE TITLE
KFP stackdriver logs link points to internal google UI, not GCP

### ISSUE THREAD

**Issue by strangemonad-faire** [kubeflow/pipelines#1584]
**What happened:**
View the logs of an evicted pod, see the links to view logs in gcp / stackdriver

The link points to pantheon.corp.google.com

https://pantheon.corp.google.com/logs/viewer?project=faire-data&interval=NO_LIMIT&advancedFilter=resource.type%3D%22container%22%0Aresource.labels.cluster_name:%22datascience%22%0Aresource.labels.pod_id:%22relationship-graph-updategsdjb-1539-1358779107-3014928661%22

https://pantheon.corp.google.com/logs/viewer?project=faire-data&interval=NO_LIMIT&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name:%22datascience%22%0Aresource.labels.pod_name:%22relationship-graph-updategsdjb-1539-1358779107-3014928661%22

**Comment by strangemonad-faire** [comment]
related to #1489

**Comment by rileyjbauer** [comment]
Thank you for reporting this. This issue was fixed in #1552 as part of [0.1.23](https://github.com/kubeflow/pipelines/blob/master/CHANGELOG.md#0123-2019-06-26)

Please reopen if there is anything more that is needed
