### ISSUE TITLE
Jupyter  environment does not have permission to access GCS

### ISSUE THREAD

**Issue by SinaChavoshi** [kubeflow/pipelines#1590]
This seems to be a similar issue as https://github.com/kubeflow/kubeflow/issues/3571 creating an issue in KPF as this is particularity confusing for KPF users when using build_python_component.

users receive the following error 

`Forbidden: 403 POST https://www.googleapis.com/upload/storage/v1/b/kf_demo_pipeline/o?uploadType=multipart: (Request failed with status code, 403,Expected one of, <HTTPStatus.OK: 200>)`

However in this state the service account `${KFAPP}-user` is added to the bucket and the user can access the bucket from the jupyter environment without an issue. 

**Recommendation**
1. Verify environment setting and notify users with an actionable error message / instructions on how to mitigate this.
2. Add instructions in common GKE debug issues 

**Work around and resolution**
There are three work around/resolutions for this, 

1. Restarting the deployment gcp-cred-webhook should fix this issue. 
2. Manually add environment variable to the Yaml config as described in [kubeflow#3571](https://github.com/kubeflow/kubeflow/issues/3571) .  
3. [not a permanent fix though quickly resolves the issue ] Add the credentials manually. This needs to be done only once for the Jupyterhub instance. Using ([reference](https://cloud.google.com/sdk/gcloud/reference/auth/application-default/login))
gcloud auth application-default login --client-id-file=CLIENT_ID_FILE
Where the credentials file is downloaded from IAM page for the  ${KFAPP}-user  service account. ([reference](https://www.kubeflow.org/docs/gke/deploy/deploy-cli/#gcp-service-accounts))

**Comment by jessiezcc** [comment]
@SinaChavoshi, where is "Add instructions in common GKE debug issues"?

**Comment by SinaChavoshi** [comment]
I was referring to : https://www.kubeflow.org/docs/gke/troubleshooting-gke/

**Comment by jessiezcc** [comment]
@jlewi, is this better to address this at KF level?

**Comment by jlewi** [comment]
@jessiezcc we can address it if we can reproduce it and identify the bug. From the bug report its not clear where the problem is; e.g. is it in the python library not getting the right credential or is the right credential not attached to the VM.

Hence the instructions in https://github.com/kubeflow/kubeflow/issues/3571#issue-461873165 
If users follow those instructions we can help narrow down where the bug is and fix it.

**Comment by SinaChavoshi** [comment]
@jlewi, unfortunately the user overwrote the environment and this issue is no longer reproducing. I will close for now and reopen if we have a repro.

**Comment by SinaChavoshi** [comment]
This issue is now consistently reproducing in 0.6 . When trying to use any GCP service I get the error 

`AccessDeniedException: 403 kubeflow-vm@....iam.gserviceaccount.com does not have storage.buckets.list access to project ....`

**Comment by jlewi** [comment]
See: https://github.com/kubeflow/kubeflow/issues/3571#issue-461873165

**Comment by gaoning777** [comment]
Was the VM SA got injected instead of the User SA?
