### ISSUE TITLE
Crate VolumeOP from  k8s_resource error

### ISSUE THREAD

**Issue by TaylorHere** [kubeflow/pipelines#1593]
**What happened:**
when I run
```
 dsl.VolumeOP(k8s_resource=my_vpc)
```

```
 Raises:
            ValueError: if k8s_resource is provided along with other arguments
```

I think the reason is :
``` 
    if "k8s_resource" in kwargs:
            if resource_name or size or storage_class or modes or annotations:
                raise ValueError("You cannot provide k8s_resource along with "
                                 "other arguments.")
```
```
    def __init__(self,
                 resource_name: str = None,
                 size: str = None,
                 storage_class: str = None,
                 modes: List[str] = VOLUME_MODE_RWM,
                 annotations: Dict[str, str] = None,
                 data_source=None,
                 **kwargs):
```

but the mode has a default value
sdk/python/kfp/dsl/_volume_op.py
**What did you expect to happen:**
I think, I should only put k8s_resource and name in it.
**What steps did you take:**
[A clear and concise description of what the bug is.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by elikatsis** [comment]
Hello @TaylorHere !

Thank you for your report!
I've submitted the PR #1595 fixing this issue.
