### ISSUE TITLE
run pipeline task in arm,  err log level=fatal msg="open /argo/secret/mlpipeline-minio-artifact/accesskey: no such file or directory"

### ISSUE THREAD

**Issue by malixian** [kubeflow/pipelines#1596]
**What happened:**
i want to run a pipeline task in arm node, so i build a arm version argoexec with golang Cross compiling,but i find some error log it said ""open /argo/secret/mlpipeline-minio-artifact/accesskey: no such file or directory",what's the problem?
**What did you expect to happen:**

**What steps did you take:**
[A clear and concise description of what the bug is.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jessiezcc** [comment]
@gaoning777, can you take an initial look as oncall?

**Comment by malixian** [comment]
> @gaoning777, can you take an initial look as oncall?
version of argoexec bin is v2.4.0, and version of workflow-controller is v2.2.0, i find source code has some different in workflow-controller, workflow-controller v2.4.0 has additional function “createSecretVolumes” in addVolumeReferences but v2.2.0 don't own it。why add this function？
i has changed version of argoexec to v2.2.0, but it does't work and has the same error log in argoexec container.

**Comment by malixian** [comment]
> > @gaoning777, can you take an initial look as oncall?
> > version of argoexec bin is v2.4.0, and version of workflow-controller is v2.2.0, i find source code has some different in workflow-controller, workflow-controller v2.4.0 has additional function “createSecretVolumes” in addVolumeReferences but v2.2.0 don't own it。why add this function？
> > i has changed version of argoexec to v2.2.0, but it does't work and has the same error log in argoexec container.

by the way, argoexec run in arm node and workflow-controller run in another am64 node.

**Comment by malixian** [comment]
this problem has solved, i degrade the version of argoexec to v2.2.0 that equals the version of workflow-controller,and no error log.

**Comment by gaoning777** [comment]
Hey, @malixian sorry for the delay. Glad it worked out, though.
