### ISSUE TITLE
Allow including arbitrary files when building containers

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#1597]
Clients request that we add ability to build container image which includes specific local files.
I propose adding the `include_files` parameter to `kfp.compiler.build_docker_image` which maps local file/directory paths to context-local paths.

Example usage:
```
kfp.compiler.build_docker_image(
    staging_gcs_path='gs://my-bucket/tmp/',
    target_image='gcr.io/my-images/my-component',
    dockerfile_path='./Dockerfile',
    include_files={
        './src': 'src', #This directory will be included in the build context
        '../common', 'common',
    },
)
```

**Comment by Ark-kun** [comment]
Waiting for @gaoning777 's refactoring to complete.

**Comment by gaoning777** [comment]
Completed. Go ahead

**Comment by Ark-kun** [comment]
Fixed by https://github.com/kubeflow/pipelines/pull/1970
