### ISSUE TITLE
GKE: Can't edit cluster after creating with kfctl

### ISSUE THREAD

**Issue by jdelfino** [kubeflow/pipelines#1599]
**What happened:**
I created my cluster with the CLI, following the instructions here: https://www.kubeflow.org/docs/gke/deploy/deploy-cli/. 

Afterward, I wanted to edit my cluster - upgrade the master/nodes, change the node instance types, etc. I tried to do this through the GKE console, but was unable to, presumably because kfctl uses Deployment Manager to create the cluster. I also tried updating from the command line, but got an error from GCP indicating that cluster resources can't be edited (details below).

**What did you expect to happen:**
I expect to be able to edit my cluster somehow. As it stands, I can't even upgrade my kubernetes version.

**What steps did you take:**
I edited `gcp_config/cluster-kubeflow.yaml` to change the instance type and cluster version. Then I ran `kfctl apply platform` from `${KFAPP}` (as described here: https://www.kubeflow.org/docs/gke/customizing-gke/). I got an error.

I then tried to run the `gcloud` command directly from the `gcp_config` directory (`gcloud deployment-manager --project=canodevcave deployments update training-dev --config=cluster-kubeflow.yaml`)

And got the same error: 

```
The fingerprint of the deployment is ZhX1PB4wIY43vnRHePJDrA==
Waiting for update [operation-1562618935834-58d319296f737-b74e9614-4378e4fb]...failed.
ERROR: (gcloud.deployment-manager.deployments.update) Error in Operation [operation-1562618935834-58d319296f737-b74e9614-4378e4fb]: errors:
- code: NO_METHOD_TO_UPDATE_FIELD
  message: No method found to update field 'cluster' on resource 'training-dev' of
    type 'container-v1beta1'. The resource may need to be recreated with the new field.
```

**Anything else you would like to add:**
I assume the root "bug" here is that GCP doesn't support editing GKE clusters via Deployment Manager - if that is the case, the docs should at least be updated to note this, ideally with pointers to an alternative installation method that will allow users to customize their clusters.

**Comment by jessiezcc** [comment]
@gaoning777, any idea?

**Comment by gaoning777** [comment]
It seems to be deployment manager issue: https://issuetracker.google.com/issues/38131324.
Let's add some documentation at first and find an upgrade approach.

**Comment by gaoning777** [comment]
@jlewi Do you have any comments on this? Thanks

**Comment by gaoning777** [comment]
Since this is not kubeflow pipeline specific error, I will close it for now.
However, feel free to reopen it if not.
