### ISSUE TITLE
pipeline can't parse input parameters in volumes field

### ISSUE THREAD

**Issue by TaylorHere** [kubeflow/pipelines#1602]
**What happened:**
when I do this:
``` 
    dop = DataBrokerOP(query=query, return_key=query_return_key, data_path=data_path)
    volume = V1Volume(
        name='train-data',
        host_path=V1HostPathVolumeSource(
            path=volume_path
            )
        )
    dop.add_pvolumes({data_path: volume})

```

I got a YAML file in where I got:

```
  volumes:
  - hostPath:
      path: '{{inputs.parameters.volume-path}}'
    name: train_data

```

but when I run it, and describe the pod, I got:

```
Volumes:
  podmetadata:
    Type:  DownwardAPI (a volume populated by information about the pod)
    Items:
      metadata.annotations -> annotations
  docker-lib:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/docker
    HostPathType:  Directory
  docker-sock:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/docker.sock
    HostPathType:  Socket
  train-data:
    Type:          HostPath (bare host directory volume)
    Path:          {{inputs.parameters.volume-path}}
    HostPathType:
  pipeline-runner-token-jzpd6:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  pipeline-runner-token-jzpd6
    Optional:    false
```
the {{inputs.parameters.volume-path}} is stil a string here, not traslate to the input arguments
**What did you expect to happen:**
I want to change my volume host path by the input parameters
**What steps did you take:**
[A clear and concise description of what the bug is.]
like above
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by TaylorHere** [comment]
In our use case,
we will create a data broker which will download train data into {{input.parameters.volume-path}}
like: /data/vol/001, we will use this path to create a volume named train-volume
later, the volume will attach to train op and mounted as /data/vol/
so, in our train code,  it will ignore the train data path detail, always get data from /data/vol/
so this bug matters.
hope someone can fix this.
thx.

**Comment by elikatsis** [comment]
Hello.
This seems like duplicate of #1327. 
Could you check if the solution described there solved your problem?

Note: in [the solution](https://github.com/kubeflow/pipelines/issues/1327#issuecomment-492336904) I mention the Argo version `v2.3.0-rc3`. Since the release `v2.3.0` is available, you should use this instead.

**Comment by elikatsis** [comment]
In Kubeflow 0.6 this issue is resolved. All the required updates are patched.

**Comment by TaylorHere** [comment]
thank you for your replay! that might be helpful!
