### ISSUE TITLE
Update the Kubeflow Pipeline documentation for KF v0.6

### ISSUE THREAD

**Issue by IronPan** [kubeflow/pipelines#1604]
Here are the documents need to be updated 
https://www.kubeflow.org/docs/pipelines/pipelines-quickstart/
https://www.kubeflow.org/docs/pipelines/sdk/pipelines-metrics/
https://www.kubeflow.org/docs/pipelines/upgrade/
https://www.kubeflow.org/docs/pipelines/tutorials/build-pipeline/
https://www.kubeflow.org/docs/pipelines/tutorials/pipelines-tutorial/
https://www.kubeflow.org/docs/pipelines/reference/component-spec/

TODO @hongye-sun : Go over https://www.kubeflow.org/docs/pipelines/sdk/ directory.

**Comment by hongye-sun** [comment]
https://www.kubeflow.org/docs/pipelines/sdk/install-sdk/
* Update kfp version from 0.1.20 to $RELEASE placeholder

https://www.kubeflow.org/docs/pipelines/sdk/build-component/
https://www.kubeflow.org/docs/pipelines/sdk/static-type-checking/
* update tar.gz to zip

**Comment by numerology** [comment]
https://www.kubeflow.org/docs/gke/gcp-e2e/

The section _(Optional) Test the code in a Jupyter notebook_ needs to be updated. 
https://github.com/kubeflow/examples/blob/master/mnist/model.py cannot be directly called from a notebook cell.

**Comment by numerology** [comment]
https://www.kubeflow.org/docs/gke/gcp-e2e/

In the section _Build the container for your training application_, Docker build might need sudo, depending on the docker installation.

**Comment by Bobgy** [comment]
I will work on https://www.kubeflow.org/docs/pipelines/upgrade/ first.

**Comment by Bobgy** [comment]
and FYI, @sarahmaddox has been updating some screenshots for KFP too in https://github.com/kubeflow/website/pull/1029. No need to duplicate.

**Comment by Bobgy** [comment]
- [ ] https://www.kubeflow.org/docs/pipelines/pipelines-quickstart/
- [ ] https://www.kubeflow.org/docs/pipelines/sdk/pipelines-metrics/
- [ ] https://www.kubeflow.org/docs/pipelines/upgrade/
- [ ] https://www.kubeflow.org/docs/pipelines/tutorials/build-pipeline/
- [ ] https://www.kubeflow.org/docs/pipelines/tutorials/pipelines-tutorial/
- [ ] https://www.kubeflow.org/docs/pipelines/reference/component-spec/
- [ ] https://www.kubeflow.org/docs/pipelines/sdk/install-sdk/
- [ ] https://www.kubeflow.org/docs/pipelines/sdk/build-component/
- [ ] https://www.kubeflow.org/docs/pipelines/sdk/static-type-checking/
- [ ] https://www.kubeflow.org/docs/gke/gcp-e2e/

**Comment by sarahmaddox** [comment]
@SinaChavoshi @Bobgy regarding the last item in the list (https://www.kubeflow.org/docs/gke/gcp-e2e/ ): I'm working on this doc. See PR https://github.com/kubeflow/website/pull/1079

@SinaChavoshi I get errors while running through the tutorial - the same errors that others encounter. See comment on issue https://github.com/kubeflow/website/issues/844#issuecomment-521537154. If you can help, please do comment on that issue.

**Comment by IronPan** [comment]
@Ark-kun do you mind check and update  https://www.kubeflow.org/docs/pipelines/reference/component-spec/

**Comment by Ark-kun** [comment]
> @Ark-kun do you mind check and update https://www.kubeflow.org/docs/pipelines/reference/component-spec/

I'll do that, thanks.

**Comment by SinaChavoshi** [comment]
@sarahmaddox sorry for the delay looking at the issue and PR  now.

**Comment by numerology** [comment]
Checked https://www.kubeflow.org/docs/pipelines/tutorials/pipelines-tutorial/, it still looks good to me.

**Comment by Ark-kun** [comment]
> @Ark-kun do you mind check and update https://www.kubeflow.org/docs/pipelines/reference/component-spec/

I've checked the doc and I think it's up to date.

**Comment by Bobgy** [comment]
Thanks folks!
This is done. Also FYI @sarahmaddox 

/close
