### ISSUE TITLE
Add a graph/chart for given experiment? 

### ISSUE THREAD

**Issue by gautamkmr** [kubeflow/pipelines#1608]
It would be good to see the graph on pipeline component along with various parameters. Some sort of error curve, training performance etc.

**Comment by gaoning777** [comment]
There is visualization graph in each step of the pipeline. 
Would you mind elaborating this Feature Request? Thanks

**Comment by Ark-kun** [comment]
Are you asking for run-time visualization of pipeline tasks?
I had some design to that, but this feature is not requested often.
