### ISSUE TITLE
feature request: in SDK support 'get_or_create_experiment()'

### ISSUE THREAD

**Issue by amygdala** [kubeflow/pipelines#161]
feature request: In the SDK, support `get_or_create_experiment()` in addition to `create_experiment()`
(Bradley has the context).

**Comment by vicaire** [comment]
Yang, do you think we should have API support for this as well?

**Comment by IronPan** [comment]
out of curious, what is the use case for this api?

**Comment by hongye-sun** [comment]
This is resolved. I changed the create_experiment to return the existing experiment instead of reporting error. This is needed so that client doesn't have to change when it runs multiple times.

**Comment by vicaire** [comment]
Thanks @hongye-sun. @amygdala, is your use case met? Can we close?

**Comment by amygdala** [comment]
yes, I have successfully used the new version to do what I want.  
Thank you!  We can close.
