### ISSUE TITLE
consistent interface with func_to_container_op and build_python_component

### ISSUE THREAD

**Issue by hongye-sun** [kubeflow/pipelines#1611]
Currently, there are some feature gaps between func_to_container_op and build_python_component. For example, build_python_component doesn't support outputs namedtuple while func_to_container_op supports. 

The bug is to figure out the gaps and make sure both interfaces are consistent, so later, we can just keep single one.

**Comment by Ark-kun** [comment]
Fixed by https://github.com/kubeflow/pipelines/pull/1889
