### ISSUE TITLE
Pipeline input cleansing

### ISSUE THREAD

**Issue by gaoning777** [kubeflow/pipelines#162]
It might make sense to cleanse the pipeline input. 
For example, if there is a parameter that requires a GCS path, with a negligible SPACE before the GCS path(e.g. " gs://pipeline/input-bucket") would lead to the pipeline failure. This type of bugs are hard to detect.

**Comment by yebrahim** [comment]
It's surprising that parameter values aren't whitespace-trimmed on any of the many level it travels through.
Is this a pipeline change? API/DB server change? UI change?

**Comment by vicaire** [comment]
+1

I don't think the API server should automatically trim spaces. This would be a feature for the front-end.
