### ISSUE TITLE
Cron dependency breaking ml CLI installation

### ISSUE THREAD

**Issue by pjo256** [kubeflow/pipelines#1620]
**What happened:**

Installing `ml` CLI fails with `src/github.com/kubeflow/pipelines/backend/src/cmd/ml/cmd/util.go:129:12: undefined: cron.Parse`. 

**What did you expect to happen:**

Successful installation

**What steps did you take:**

```
docker run -it --entrypoint bash golang:1.12
go get -u github.com/kubeflow/pipelines/backend/src/cmd/ml
````

**Anything else you would like to add:**

There was a recent release of a cron dependency - `https://github.com/robfig/cron/releases`. `v3` removed a top-level `Parse` function from `parser.go`, breaking https://github.com/kubeflow/pipelines/blob/master/backend/src/cmd/ml/cmd/util.go#L129. It's not clear why this is breaking, since the version is pinned in [WORKSPACE](https://github.com/kubeflow/pipelines/blob/master/WORKSPACE#L611).

**Comment by pjo256** [comment]
Looks like the default branch was switched from `master` to a `v3` branch and has since been reverted back to `master`. `v3` is branched off of master and contains the commit we pin on - `b41be1df6967`. Despite this, we were pulling in a later commit containing the breaking changes. Should we be pinning based on tags here, or is this an issue with `go get` and version pinning when the default branch is changed?

**Comment by jessiezcc** [comment]
ML CLI is no longer supported, it's being replaced by python CLI under https://github.com/kubeflow/pipelines/tree/master/sdk/python/kfp/cli. I will open an issue to remove ML CLI
