### ISSUE TITLE
Upgradability for Kubeflow Pipeline

### ISSUE THREAD

**Issue by IronPan** [kubeflow/pipelines#1638]
Kubeflow Pipeline upgradability was depending on the ksonnet registry. 
https://www.kubeflow.org/docs/pipelines/upgrade/

As KF v0.6 switch from Ksonnet to kustomize, the upgrade functionality is not working anymore. We need a new solution for pipeline upgrade/reinstall.

**Comment by Bobgy** [comment]
* Instructions for reinstall: https://github.com/kubeflow/website/pull/972

**Comment by Bobgy** [comment]
Plan
* [ ] Upgrade test coverage.

**Comment by Bobgy** [comment]
/reopen

There's one last step to enable the presubmit test and verify it is stable

**Comment by Bobgy** [comment]
Turn on the test as optional in https://github.com/kubernetes/test-infra/pull/16709.
Once I verified the test is stable, I can change it to always run.

**Comment by Bobgy** [comment]
`kubeflow-pipeline-upgrade-test` is now running stably.
I also made a change to auto clean up upgrade test clusters: https://github.com/kubeflow/pipelines/pull/3282.

All the work for the test infra is done, I will continually supervise upgrade test in individual PRs.
/close
