### ISSUE TITLE
Kubeflow pipeline is not getting triggered through CLI for cluster running on AWS

### ISSUE THREAD

**Issue by vackysh** [kubeflow/pipelines#1642]
Hi @Jeffwan ,

I have a requirement to trigger the Kubeflow pipeline and model serving on aws sagemaker through terminal for which i have written below code.

client = kfp.Client("10.152.183.136:8888/pipeline")
my_experiment = client.create_experiment(name='exp-1')
my_run = client.run_pipeline(my_experiment.id,
'pipeline_serve_model_py3','pipeline_serve_model_py3.py.zip')

Note: IP 10.152.183.136:8888 is taken from service ml-pipeline

I am getting the below error:

"2019-07-18 06:29:32,590 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe4b44af128>: Failed to establish a new connection: [Errno 110] Connection timed out',)': /pipeline/apis/v1beta1/experiments?page_token=&page_size=100&sort_by= "

Although, the pipeline is working properly from kubeflow UI.

I dig into client.py and it is expecting host and client_id. Host is supplied but we dont have client_id and i feel it is meant for GCP.

Can you please assist me how to run the pipeline through terminal ?

Regards,
Vackysh

**Comment by Jeffwan** [comment]
@vackysh Honestly, I have not run in notebook yet. I can help try it out. I will come back to you later.
