### ISSUE TITLE
FR: caching to avoid long-running steps repetitively

### ISSUE THREAD

**Issue by gaoning777** [kubeflow/pipelines#1648]
This is a feature request to support caching in KFP such that the pipeline can skip steps that are run before and nothing have changed since. This is really useful for fast experimentation that involve heavy processing, such as training.

**Comment by jessiezcc** [comment]
this is part of metadata project.

**Comment by neuromage** [comment]
Caching is now supported by KFP UI.

**Comment by Padarn** [comment]
Is there any documentation on this feature @neuromage?

**Comment by sadeel** [comment]
+1 on documentation request.

**Comment by Bobgy** [comment]
FYI, latest issue for caching service is in https://github.com/kubeflow/pipelines/issues/2904.
I'm not actually sure what this issue refers to
