### ISSUE TITLE
tide errors: merge requirements do not match github setttings

### ISSUE THREAD

**Issue by BenTheElder** [kubeflow/pipelines#1653]
A maintainer of this repo / the CI setup should configure Prow / Tide (the merge robot) to have accurate merge requirements matching the `Required` statuses configured on pull requests. AFAIK these need to be kept in sync to work properly (?) cc @cjwagner to confirm...

> failed merging [1652]: [PR is unmergable. Do the Tide merge requirements match the GitHub settings for the repo? Required status check "Travis CI - Pull Request" is failing.]

https://prow.k8s.io/tide-history

This is showing on https://github.com/kubeflow/pipelines/pull/1652

cc @jlewi for kubeflow prow

**Comment by cjwagner** [comment]
That isn't a normal status check, it is a GitHub check (https://github.com/kubeflow/pipelines/pull/1652/checks) which Tide cannot support because it is not a GitHub App.

Can you move the Travis CI tests to a ProwJob?

**Comment by gaoning777** [comment]
Discussed with cjwagner offline. This issue causes Tide to continually try to merge an unmergable PR which burns through the bots API rate limit.
@jessiezcc

**Comment by BenTheElder** [comment]
ping, we still have error spam from this and AFAIK burning bot API rate limit

**Comment by cjwagner** [comment]
I also opened an issue about this in march, but I have been struggling to get anyone to address it. https://github.com/kubeflow/pipelines/issues/930

**Comment by jlewi** [comment]
@gaoning777 @jessiezcc  can you please look into this?

@cjwagner @gaoning777 its not clear to me how to how fix this. If you can help me figure out what to do I will be happy to do it.

Here's a script for the list of status checks for the repo.

If I uncheck "Travis CI" will that fix it.
![pipelines](https://user-images.githubusercontent.com/777219/68638936-ed996200-04b7-11ea-9ec6-939b0580ee74.png) ?

**Comment by Bobgy** [comment]
I can move frontend part of the travis tests to prow.

**Comment by IronPan** [comment]
@Bobgy Thanks moving travis to prow would be great.

**Comment by Bobgy** [comment]
Efforts for moving frontend unit tests:
* [ ] Add test configuration to prow: https://github.com/kubernetes/test-infra/pull/15332 and https://github.com/kubernetes/test-infra/pull/15349
* [ ] Configure coveralls repo token to allow reporting of coverage statistics

**Comment by cjwagner** [comment]
This is still an issue. Please address!
https://github.com/kubeflow/pipelines/pull/3197
https://prow.k8s.io/tide-history?repo=kubeflow%2Fpipelines

**Comment by Bobgy** [comment]
/assign @jingzhang36 
for backend tests
/assign @Ark-kun 
for python tests

We will prioritize this after recent release.

**Comment by Bobgy** [comment]
@jingzhang36 has migrated backend test to prow: https://github.com/kubeflow/pipelines/issues/2885

**Comment by jingzhang36** [comment]
Backend unit tests are off Travis now (https://github.com/kubeflow/pipelines/issues/2885 is closed).
We'll need to take care of python tests now /assign @Ark-kun

**Comment by chases2** [comment]
This issue is occurring currently, see #3876 
I placed a `/hold` to deal with this in the short-term

**Comment by Bobgy** [comment]
Sorry about that @chases2, @Ark-kun said he would migrate off travis in a few days

**Comment by cjwagner** [comment]
Please address this. This has been negatively impacting our infrastructure for more than 15 months.
https://prow.k8s.io/tide-history?repo=kubeflow%2Fpipelines&branch=master

**Comment by cjwagner** [comment]
Please be warned that we intend to disable Tide for this repo if the issue has not been resolved by August.

**Comment by Bobgy** [comment]
Hi @cjwagner, sorry for your inconvenience. Thanks for maintaining the infra!

FYI, a few weeks ago, I removed required status of Travis tests before @Ark-kun can migrate them to prow.

So I believed this issue should have been solved.

However, the issue that occured this time is different, cla requirement is not matching tide configuration. I will go ahead and fix that.

**Comment by Bobgy** [comment]
took a quick look, cla check seems also a github check. How does other repos use it with tide?

**Comment by Ark-kun** [comment]
@cjwagner

> Please address this.

I think this issue has already been fixed several weeks ago.
The Travis tests are no longer a requirement and the failures do not prevent PR merges.

Are you sure the issue still remains?

**Comment by Ark-kun** [comment]
Is Prow compatible with the Google CLA?

**Comment by Bobgy** [comment]
It seems we need a plugin similar to the existing `cla` plugin for cncf cla in https://prow.k8s.io/plugins.
It syncs github status to labels in the PR, so tide can set criteria on labels.

**Comment by Bobgy** [comment]
`cla` plugin lives in https://github.com/kubernetes/test-infra/tree/master/prow/plugins/cla, if we can make it configurable like `which github status check should be converted to which labels`, then it could potentially also be used to allow us using travis tests.

**Comment by cjwagner** [comment]
IDK the details of how the google CLA is managed, but I do know that is used with Prow by the Knative org without issue. e.g. https://github.com/knative/serving/pull/8487
Notice that a `google-bot` manages a CLA label in addition to the status context.

> It seems we need a plugin similar to the existing `cla` plugin for cncf cla in https://prow.k8s.io/plugins.
> It syncs github status to labels in the PR, so tide can set criteria on labels.

This isn't necessary. 1) It looks like `google-bot` can be made to manage a label. 2) Tide can be configured to require the `CLA: yes` label or require the CLA status context directly, but you need to configure at least one so that Tide's requirements match whatever you have configured in the GitHub settings for the repo.

**Comment by jlewi** [comment]
We use the Google CLA on all other repos within KF and it doesn't appear to be an issue.

**Comment by Bobgy** [comment]
Thanks @cjwagner and @jlewi!

I found out googlebot requires the repo to already have labels named `cla: yes` and `cla: no`. I just added them and the bot is starting to add labels automatically: https://github.com/kubeflow/pipelines/pull/4094.

**Comment by Bobgy** [comment]
Sent a PR https://github.com/kubernetes/test-infra/pull/18095 to update kubeflow org configuration.

**Comment by Bobgy** [comment]
the config change had permission issues
/reopen

**Comment by Bobgy** [comment]
Latest status:

k8s-ci-bot needs admin permission on kubeflow org to enforce above mentioned branch protection rule.
context: https://github.com/kubernetes/test-infra/issues/18397#issuecomment-662060833

ref rom @jlewi:
repo permissions are granted via GitOps using periobolous so you could configure an appropriate PR.
https://github.com/kubeflow/internal-acls/blob/f6e2bdb4a92b1ae6b808f2c7b81ab1077acfa69a/github-orgs/kubeflow/org.yaml#L672

We can grant those permissions, but do we think that's safe?

@jlewi do you think https://github.com/kubernetes/test-infra/issues/18397#issuecomment-662066679 convinced you these permissions are required and acceptable?

If not, another backup option is to add "cla: yes" label to all the repos and configure the requirement by github labels.

**Comment by jlewi** [comment]
@Bobgy yes; I think I'm convinced by @cjwagner 's comment. @Bobgy If possible can we point at the Kubernetes test infra as prior art that they are granting the ci-bots admin permissions at the org level?

**Comment by cjwagner** [comment]
FYI I am also seeing 403s from GH in the Prow logs when trying to interact with the kubeflow/blog repo. It appears that repo has revoked the permissions for the bot or never granted them.  Org level admin permissions should resolve this though.

**Comment by jlewi** [comment]
@cjwagner I think when we created kubeflow/blog we initially didn't add the ci-bots team but it should be added now; if your still seeing 403s let me know (preferablly in a new issue on kubeflow/blog).

@Bobgy I think we can also set the permissions at the org level now.

**Comment by Bobgy** [comment]
Okay, let me do that tomorrow

**Comment by Bobgy** [comment]
Fixed by https://github.com/kubernetes/test-infra/pull/18837
