### ISSUE TITLE
Request to deprecate %%docker magic 

### ISSUE THREAD

**Issue by SinaChavoshi** [kubeflow/pipelines#1660]
Also closes #1547 

This is a request to eliminate redundant methods of building docker / components. Specifically to remove %% docker magic wrapper.  

This will ensure that 
1. methods of building docker and component are kept update as there are fewer of them to maintain. 
2. The path for building components and docker is clear ( less confusing ) by reducing the multiple ways that the same code can be written.

**Comment by Ark-kun** [comment]
Related: https://github.com/kubeflow/pipelines/issues/1659

**Comment by Ark-kun** [comment]
Fixed by https://github.com/kubeflow/pipelines/pull/2266
