### ISSUE TITLE
Request to deprecate compiler.build_python_component(build_image=,..) flag

### ISSUE THREAD

**Issue by SinaChavoshi** [kubeflow/pipelines#1661]
This is a request to eliminate redundant methods of building docker / components. specifically to remove compiler.build_python_component(build_image=,..) flag. This flag eliminates the container build operation from build_python_component however it will not inject the python function into the container or pass it on. This allows for modification of component definition without changing the base container image. However this is redundant as  dsl.ContainerOp provides the same functionality.

This will ensure that 
1. methods of building docker and component are kept update as there are fewer of them to maintain. 
2. The path for building components and docker is clear ( less confusing ) by reducing the multiple ways that the same code can be written.

**Comment by hongye-sun** [comment]
@gaoning777, will it be covered by your component builder work?

**Comment by Ark-kun** [comment]
Related: https://github.com/kubeflow/pipelines/issues/1659

**Comment by gaoning777** [comment]
This flag was added initially to avoid rebuilding the image if the image already exists. E.g. when users has run the notebook once and need to run it again without building the image, setting the flag will only generate the containerop. 

Since we will have a fast build that takes very little time, the new version will not have this configuration any more. I will cover that.
@Ark-kun, if you do not mind, I will address this issue in my efforts for the new component build.

**Comment by Ark-kun** [comment]
>setting the flag will only generate the containerop

But that `ContainerOp` might be in compatible with the container (e.g. when the function has changed).
Can the user just save component to a file (`build_python_component(target_component_file='my_component.yaml', ...)`) once and then call `load_component_from_file('my_component.yaml')` in subsequent runs?

> @Ark-kun, if you do not mind, I will address this issue in my efforts for the new component build.

Sure.

**Comment by Ark-kun** [comment]
Waiting for @gaoning777 's refactoring to complete.

**Comment by gaoning777** [comment]
Completed. Go ahead.

**Comment by Ark-kun** [comment]
@gaoning777 Can you please LGTM https://github.com/kubeflow/pipelines/pull/1657 ?
