### ISSUE TITLE
Page indicator does stay in place when scrolling page in KFP UI

### ISSUE THREAD

**Issue by ajchili** [kubeflow/pipelines#1669]
**What happened:**
Page indicator does stay in place when scrolling page in KFP UI (view screenshot below).

**What did you expect to happen:**
Page indicator should remain on the same x/horizontal index as the selected page. However, the pages do not scroll as a user scrolls. Perhaps the pages should scroll with the page indicator to remain in the users view.

**What steps did you take:**
1. Open KFP UI.
2. Select **Experiments** tab.
3. Set **Rows Per Page** (located at the bottom of the table) to be 100.
4. Scroll down and notice page indicator moves while scrolling.

**Anything else you would like to add:**
![image](https://user-images.githubusercontent.com/7911799/61838222-2516cc80-ae3d-11e9-8d95-41f8e246901c.png)

**Comment by jessiezcc** [comment]
@rileyjbauer can you take a look?

**Comment by rmgogogo** [comment]
it looks good for me. here close
