### ISSUE TITLE
[GCP] pipelines supports workload identity

### ISSUE THREAD

**Issue by jlewi** [kubeflow/pipelines#1691]
We would like to support using workload identity on GCP.

See kubeflow/kubeflow#3638

Opening this bug to track adding support for workload identity with KFP

A couple questions

* Which namespaces will KFP pipelines running in? Are users still running in the "kubeflow" namespace or can pipelines run in other namespaces e.g. "kf-${USER}"

* Does KFP support specifying which K8s service account is used by Argo pods?
 
  * The K8s service account will determine which GCP service account is used.
  * Current pattern in Kubeflow is that the profile resource will create a namespace with a default-editor K8s service account which would be bound to an appropriate GCP service account
  * So pipelines might be able to use that KSA (K8s Service account by default.)

/cc @jessiezcc 
/cc @IronPan

**Comment by jessiezcc** [comment]
Pipeline namespace is configurable, https://github.com/kubeflow/pipelines/issues/304 tracked the ask and [this PR](https://github.com/kubeflow/pipelines/pull/306/files) addressed it. 
As for service account, pipeline runs under user-gcp-sa which reflects the default active service account based on https://github.com/kubeflow/pipelines/issues/374. @IronPan can confirm.

**Comment by jlewi** [comment]
@IronPan @jessiezcc Does Kubeflow pipelines plan to support workload identity? 

Here are the [docs](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) for workload identity.

With workload identity Kubernetes Service Accounts (KSA) can be bound to GCP Service Accounts (GSA).

So with workload identity pipeline users would probably want the ability to specify what service account the pods in the pipeline use as that would determine what GSA the pod uses.

**Comment by gaoning777** [comment]
Yes. We will support the workload identity within the multi-user efforts in the Q4 such that users are authenticated to use GCP resources.

**Comment by Bobgy** [comment]
Note, one work item:
* pipeline-ui needs gcs read permission when using workload identity https://github.com/kubeflow/pipelines/issues/2501, quick fix is done in https://github.com/kubeflow/manifests/pull/594 without workload identity.

**Comment by IronPan** [comment]
+1 we are planning on migrating the full stack to WI. Thanks Jeremy.

**Comment by IronPan** [comment]
We also need clean documentations how to use WI when authoring the pipeline component, after WI is completed.

**Comment by Bobgy** [comment]
Work items for standalone deployment:
* [x] Migrate standalone deployment to workload identity on GCP https://github.com/kubeflow/pipelines/pull/2619
* [ ] Deploy doc in https://www.kubeflow.org/docs/pipelines/installation/standalone-deployment/
* [ ] GCP authentication doc in https://www.kubeflow.org/docs/gke/authentication/#authentication-from-kubeflow-pipelines
* [ ] SDK doc in https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.extensions.html#kfp.gcp.use_gcp_secret
* [ ] Sample doc in samples changed in https://github.com/kubeflow/pipelines/pull/2619

**Comment by Bobgy** [comment]
Work items for kubeflow deployment:
* [ ] GCP authentication doc in https://www.kubeflow.org/docs/gke/authentication/#authentication-from-kubeflow-pipelines
* ... TODO: complete this list

**Comment by Bobgy** [comment]
Work items not specific to any deployments:
* [ ] Sample doc in samples changed in https://github.com/kubeflow/pipelines/pull/2619
* [ ] parameterized tfx oss sample should stop using use_gcp_secret by default: https://github.com/kubeflow/pipelines/blob/master/samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py#L153

**Comment by Bobgy** [comment]
Work items blocking multi user support and hosted are done. Changed to p1 priority.

**Comment by jlewi** [comment]
@Bobgy is it possible for a user to set the KSA when using TFX?

/cc @ucdmkt

**Comment by numerology** [comment]
> @Bobgy is it possible for a user to set the KSA when using TFX?
> 
> /cc @ucdmkt

@jlewi 
If you're talking about using [KubeflowDagRunner](https://github.com/tensorflow/tfx/blob/master/tfx/orchestration/kubeflow/kubeflow_dag_runner.py#L205), currently it's not supported, but I think it's definitely doable.

Is there any use case/feature depending on this? Thanks!

**Comment by Bobgy** [comment]
Work Items for GCP hosted deployment:
* Documentation of how to set up Workload Identity: https://github.com/kubeflow/website/pull/1832

**Comment by numerology** [comment]
@jlewi 
Sounds good. However it depends on the ability of specifying the KSA in use through KFP SDK, which is currently missing. @Bobgy can correct me if I'm wrong, I think it's the planned as a "phase 3" work.

**Comment by Bobgy** [comment]
@numerology Yes, that's right.
But in phase 2, we'd support choosing KSA in KFP API at pipeline level. @jlewi will that be enough for your use case?

**Comment by jlewi** [comment]
@Bobgy I think setting a per pipeline KSA is fine.

**Comment by Ark-kun** [comment]
> However it depends on the ability of specifying the KSA in use through KFP SDK, which is currently missing.

Can we set that on cluster-level instead (e.g. using a configmap)? I'd prefer not to have any account-specific information in the pipeline file.

**Comment by Bobgy** [comment]
Choosing a KSA when running a pipeline is suppported now.
