### ISSUE TITLE
Support DAG templates for exit handlers

### ISSUE THREAD

**Issue by IronPan** [kubeflow/pipelines#1697]
Pipeline SDK currently support specifying single exit handler
```
with ExitHandler(exit_op=exit_op): 
    op1 = ContainerOp(name='op1', image='image')
```
Argo supports [multiple exit handlers](https://github.com/argoproj/argo/blob/master/examples/exit-handlers.yaml) and there are valid Pipeline use cases to support multiple handlers.

Here is one proposed syntax for Pipeline SDK to support it
```
@graph_component
def exit_handler():
  op1()
  op2()

@pipeline(exit_op=exit_handler)
def pipeline():
    ...
```

**Comment by Ark-kun** [comment]
> Here is one proposed syntax for Pipeline SDK to support it

I like the syntax.

P.S. Exit handlers have some design problems. An exit handler usually means that there is some global state which is not explicitly tracked. Adding support for caching would expose these issues and make pipelines with exit handlers fail in surprising ways.

**Comment by liuyl** [comment]
Any update on this issue? The reason I need this is because my pipeline creates some deployments, services and configs, which should be ideally deleted in exit_handler.

**Comment by hongye-sun** [comment]
This FR should be feasible now as Argo supports per-template exit handler. https://github.com/argoproj/argo/pull/1716

**Comment by solovyevt** [comment]
Would be a great feature to have to handle removal of multiple volumes

**Comment by Nagarajj** [comment]
@Bobgy and others, any guidance on this issue. Would be happy to contribute, this is blocking us. Thanks.

**Comment by Bobgy** [comment]
/reopen
We do have plans to support DAG exit handlers for KFP v2 (it'll take a while), but didn't plan about v1.
/assign @chensun @neuromage 
are v1 compiler owners
