### ISSUE TITLE
ContainerBuilder support for non-GCR registries

### ISSUE THREAD

**Issue by gaoning777** [kubeflow/pipelines#1700]
Currently, the ContainerBuilder only supports the GCR. 
Expose the secret configurations for other content registries: https://github.com/GoogleContainerTools/kaniko#pushing-to-different-registries

**Comment by sarahmaddox** [comment]
@gaoning777 Can we close this issue, after the merge of the above PRs? We have a note in the docs that we can remove when this issue and https://github.com/kubeflow/pipelines/issues/337 are closed.

**Comment by gaoning777** [comment]
Unfortunately, the container builder does not support other registries other than the GCR, yet.

**Comment by HassanOuda** [comment]
Any updates on this? What are the implications for container builder not supporting non-GCR registries? We cannot push our images to our own registries?

**Comment by Trezorro** [comment]
I'm trying to evaluate the proposition of using KubeFlow for my company's future ML training workflows. We want to use our local kubernetes cluster, to maintain data security, but this issue has me puzzled on whether we will be forced to set up our experiments via GCP instead.

Can anyone shed a light on this for a novice user?

**Comment by sallamander** [comment]
I'd like to echo what @Trezorro asked.. is it possible to use kubeflow and kubeflow pipelines with registries other than GCR? From the docs it sounds like it is possible, but I can't find a clear cut example (in the docs or elsewhere online) that spells out how to do this. Has anybody been able to pull an image from Amazon's ECR, or a private docker hub registry, and run a Kubeflow pipeline on it?

**Comment by jarednielsen** [comment]
Same here - has anyone pulled an image from Amazon ECR or Docker Hub?

**Comment by Bobgy** [comment]
To answer above questions, the container builder doesn't block any usage. You can use dockerfile to build component base images too.
