### ISSUE TITLE
ContainerBuilder support for on-prem build files

### ISSUE THREAD

**Issue by gaoning777** [kubeflow/pipelines#1701]
Currently ContainerBuilder uses GCS to store the build files temporarily. 
Potentially with configmap support in kaniko(https://github.com/GoogleContainerTools/kaniko#running-kaniko-in-a-kubernetes-cluster), we can remove the dependency on the GCS.

**Comment by hongye-sun** [comment]
configmap might not work as it has the size limitation of etcd. 

Kaniko supports S3: https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts Option 1 is to support S3 in the future. 

Option 2 is to use an init wait container and use "kubectl cp" to copy the context file to an in-memory volume.

**Comment by pankajxyz** [comment]
when can we expect ContanierBuilder class to have option of being completely independent of GCP and work on-prem without GCS staging or GCR?
