### ISSUE TITLE
Set TTL for argo workflow

### ISSUE THREAD

**Issue by IronPan** [kubeflow/pipelines#1708]
Argo supports ttl https://github.com/argoproj/argo/blob/master/examples/gc-ttl.yaml
When DSL compiles pipeline to argo workflow, we should set this so that it can be GCed after finish. The TTL should leave enough time for Persistence agent to persist the data.

**Comment by gaoning777** [comment]
Are you suggesting an default ttl for all pipelines?
BTW, the DSL already exposes the ttl conf: https://github.com/kubeflow/pipelines/blob/3dc73bac699a3dc468ebbd9f29b5b324f2773244/sdk/python/kfp/dsl/_pipeline.py#L84

**Comment by gaoning777** [comment]
Is the purpose to reduce the storage size? in which case we can set the default value to a large number to prevent large pipelines from failing due to small ttl.

**Comment by paveldournov** [comment]
The TTL seems to kick off after the workload completes, so we don't need to worry about long running workflows. I think we should consider setting a low TTL by default to GC the resources promptly after the run is recorded in metadata. It would probably affect the logging UX experience and we will need to switch over to showing the persisted logs (stackdriver, etc) instead by default.

**Comment by IronPan** [comment]
With change https://github.com/kubeflow/pipelines/pull/1802 this issue can be closed.

**Comment by IronPan** [comment]
Agreed with @paveldournov we need find a better way to persist logs with aggressive GC. 
For GCP stackdriver is ok. 
For non-GCP, we need a better story.

**Comment by IronPan** [comment]
File an issue for on-prem logs https://github.com/kubeflow/pipelines/issues/1803
/close
