### ISSUE TITLE
Pipeline-UI does not render HTML artifact from Minio

### ISSUE THREAD

**Issue by crauterb** [kubeflow/pipelines#1731]
**What happened:**

I did set up a Pipeline where I train an Xgboost-Model. For evaluation purposes, I want to show the plot of the feature importance as an artifact of the pipeline step.

However, I am shown only a blank rectangle in the artifact window.

**What did you expect to happen:**

I expected the HTML code to be rendered correctly and the image to be shown accordingly.

**What steps did you take:**

In the pipeline component, I pushed the `.html` file to Minio and added the file to the `metadata`:
```
metadata = {
    'outputs' : [{
      'type': 'web-app',
      'storage': 'minio',
      'source': 'minio://%s/%s' % (html_output_bucket_name, minio_file_path),
    }]
  }
```

Now, once the pipeline executes, I can see that the file is stored in Minio.
Once I open the run in the Pipeline UI and click on the according pipeline step. I can see, that a request is send - first to get the metadata via
`.../pipeline/artifacts/get?source=minio&bucket=mlpipeline&key=artifacts%2FPIPELINE-NAME-72ljw%2FPIPELINE-NAME-72ljw-1340310380%2Fmlpipeline-ui-metadata.tgz` and then the `.html` file via
`.../pipeline/artifacts/get?source=minio&bucket=html-files&key=27d7f1a5-bcfc-432d-bc31-25f76013c32d_feature_importance.html`
I can also see in the log of the pod, that the request arrives:
```
GET /pipeline/artifacts/get?source=minio&bucket=mlpipeline&key=artifacts%2Fbandwidth-prediction-72ljw%2Fbandwidth-prediction-72ljw-1340310380%2Fmlpipeline-ui-metadata.tgz
Getting storage artifact at: minio: mlpipeline/artifacts/bandwidth-prediction-72ljw/bandwidth-prediction-72ljw-1340310380/mlpipeline-ui-metadata.tgz
GET /pipeline/artifacts/get?source=minio&bucket=html-files&key=27d7f1a5-bcfc-432d-bc31-25f76013c32d_feature_importance.html
Getting storage artifact at: minio: html-files/fa104780-c2d5-4bd9-989d-97e26670f493_feature_importance.html
```

However the request returns with code `304 Not Modified` and no data is returned, resulting in an empty frame. 

**Anything else you would like to add:**
Running in v.0.5.

Hope I did not miss anything :-)

**Comment by crauterb** [comment]
Well, apparently all works fine.

There is a note missing in the documentation that - when you want to use `.html` files using the `web-app` - you need to wrap files in a `.tar` ball. 
The frontend will unpack that ball and then check the content, as can be seen [here](https://github.com/kubeflow/pipelines/blob/dd59bc25975fd648fbbaad02d10fddd484b2154c/frontend/server/server.ts#L196).

Once I wrap the `.html` in said `.tar` ball, all is displayed correctly.

**Comment by damien75** [comment]
To be clear if you want to use **any** type of file (`html`, `csv` or else apart from [tensorboard](https://github.com/kubeflow/pipelines/issues/699)) to be displayed in the Kubeflow Pipeline UI, then you need to wrap the file in a `.tar` ball, and reference in the source the `.tar` file.

```json
{
            'outputs': [{
                'type': 'confusion_matrix',
                'format': 'csv',
                'schema': [
                    {'name': 'target', 'type': 'CATEGORY'},
                    {'name': 'predicted', 'type': 'CATEGORY'},
                    {'name': 'count', 'type': 'NUMBER'},
                ],
                'source': 'minio://%s/%s' % (bucket_name, tar_file_name),
                'labels': list(map(str, vocab)),
            }]
        }
```
