### ISSUE TITLE
E2E tests do not catch build image failure

### ISSUE THREAD

**Issue by gaoning777** [kubeflow/pipelines#1735]
E2E tests passed for this PR: https://github.com/kubeflow/pipelines/pull/1710
However the cloudbuild job fails after the PR merge.

Looks like the imagebuilder in the E2E tests continue the execution even if one of the RUN command in the dockerfile fails.

**Comment by Ark-kun** [comment]
There was no failure, because the code is different: https://pantheon.corp.google.com/logs/viewer?interval=NO_LIMIT&project=ml-pipeline-test&minLogLevel=0&expandAll=false&timestamp=2019-08-05T21:19:09.959000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22ml-pipeline-test%22%0Aresource.labels.location%3D%22us-east1-b%22%0Aresource.labels.cluster_name%3D%22sample-b3cd43c-593%22%0Aresource.labels.namespace_name%3D%22kubeflow%22%0Aresource.labels.pod_name%3D%22build-images-56xn4-1576479617%22%0Aresource.labels.container_name%3D%22main%22&scrollTimestamp=2019-08-05T21:12:33.000000000Z

```
I 2019-08-05T21:11:58.239306637Z Step 15/26 : RUN  find core -maxdepth 2 -name '*.py' -type f | while read pipeline; do dsl-compile --py "$pipeline" --output "$pipeline.tar.gz"; done 
I 2019-08-05T21:11:58.294784217Z  ---> Running in 5ec425210635 
I 2019-08-05T21:12:25Z  ---> fcc37f6b0684
 

```

**Comment by Ark-kun** [comment]
> There was no failure, because the code is different:

Or maybe not. Investigating further.

**Comment by Ark-kun** [comment]
Here is the DinD build of the image - the error is skipped. https://pantheon.corp.google.com/logs/viewer?interval=NO_LIMIT&project=ml-pipeline-test&minLogLevel=0&expandAll=false&timestamp=2019-08-05T21:19:09.959000000Z&customFacets=&limitCustomFacetWidth=true&scrollTimestamp=2019-08-01T23:53:03.893354093Z&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22ml-pipeline-test%22%0Aresource.labels.location%3D%22us-east1-b%22%0Aresource.labels.namespace_name%3D%22kubeflow%22%0Aresource.labels.pod_name%3D%22build-images-5qwxz-3407253935%22%0Aresource.labels.container_name%3D%22main%22
```
I 2019-08-01T23:52:32.185566597Z Step 15/26 : RUN  find . -maxdepth 3 -name '*.py' -type f | while read pipeline; do dsl-compile --py "$pipeline" --output "$pipeline.tar.gz"; done
 
I 2019-08-01T23:52:32.241726583Z  ---> Running in 6850900945e3
 
I 2019-08-01T23:52:37Z ValueError: A function with @dsl.pipeline decorator is required in the py file.
 
I 2019-08-01T23:52:37Z [91mTraceback (most recent call last):
 
I 2019-08-01T23:52:37Z   File "/usr/local/bin/dsl-compile", line 11, in <module>
 
I 2019-08-01T23:52:37Z     load_entry_point('kfp==0.1.25', 'console_scripts', 'dsl-compile')()
 
I 2019-08-01T23:52:37Z   File "/usr/local/lib/python3.5/site-packages/kfp-0.1.25-py3.5.egg/kfp/compiler/main.py", line 117, in main
 
I 2019-08-01T23:52:37Z     compile_pyfile(args.py, args.function, args.output, not args.disable_type_check)
 
I 2019-08-01T23:52:37Z   File "/usr/local/lib/python3.5/site-packages/kfp-0.1.25-py3.5.egg/kfp/compiler/main.py", line 106, in compile_pyfile
 
I 2019-08-01T23:52:37Z     _compile_pipeline_function(pipeline_funcs, function_name, output_path, type_check)
 
I 2019-08-01T23:52:37Z   File "/usr/local/lib/python3.5/site-packages/kfp-0.1.25-py3.5.egg/kfp/compiler/main.py", line 56, in _compile_pipeline_function
 
I 2019-08-01T23:52:37Z     raise ValueError('A function with @dsl.pipeline decorator is required in the py file.')
 
I 2019-08-01T23:52:37.195521651Z [91mTraceback (most recent call last):
 
I 2019-08-01T23:52:37.195563039Z   File "/usr/local/bin/dsl-compile", line 11, in <module>
 
I 2019-08-01T23:52:37.195571654Z     load_entry_point('kfp==0.1.25', 'console_scripts', 'dsl-compile')()
 
I 2019-08-01T23:52:37.195578207Z   File "/usr/local/lib/python3.5/site-packages/kfp-0.1.25-py3.5.egg/kfp/compiler/main.py", line 117, in main
 
I 2019-08-01T23:52:37.195584896Z     compile_pyfile(args.py, args.function, args.output, not args.disable_type_check)
 
I 2019-08-01T23:52:37.195590823Z   File "/usr/local/lib/python3.5/site-packages/kfp-0.1.25-py3.5.egg/kfp/compiler/main.py", line 106, in compile_pyfile
 
I 2019-08-01T23:52:37.195596990Z     _compile_pipeline_function(pipeline_funcs, function_name, output_path, type_check)
 
I 2019-08-01T23:52:37.195602844Z   File "/usr/local/lib/python3.5/site-packages/kfp-0.1.25-py3.5.egg/kfp/compiler/main.py", line 56, in _compile_pipeline_function
 
I 2019-08-01T23:52:37.195608870Z     raise ValueError('A function with @dsl.pipeline decorator is required in the py file.')
 
I 2019-08-01T23:52:37.195614649Z ValueError: A function with @dsl.pipeline decorator is required in the py file.
 
I 2019-08-01T23:53:02Z [0m ---> 8ccc10258c12
 
I 2019-08-01T23:53:02Z Step 16/26 : FROM debian:stretch
 
```

Here is the CloudBuild build of the same image - the error fails the build: https://pantheon.corp.google.com/cloud-build/builds/42e0d412-794e-4d17-a6fe-8f2c0cc23d38?project=ml-pipeline-test
```
Step #8 - "buildApiServer": Step 15/26 : RUN  find . -maxdepth 3 -name '*.py' -type f | while read pipeline; do dsl-compile --py "$pipeline" --output "$pipeline.tar.gz"; done
Step #8 - "buildApiServer":  ---> Running in 4f79acc4f8de
Step #8 - "buildApiServer": [91mTraceback (most recent call last):
Step #8 - "buildApiServer":   File "/usr/local/bin/dsl-compile", line 11, in <module>
Step #8 - "buildApiServer":     load_entry_point('kfp==0.1.25', 'console_scripts', 'dsl-compile')()
Step #8 - "buildApiServer":   File "/usr/local/lib/python3.5/site-packages/kfp-0.1.25-py3.5.egg/kfp/compiler/main.py", line 117, in main
Step #8 - "buildApiServer":     compile_pyfile(args.py, args.function, args.output, not args.disable_type_check)
Step #8 - "buildApiServer":   File "/usr/local/lib/python3.5/site-packages/kfp-0.1.25-py3.5.egg/kfp/compiler/main.py", line 106, in compile_pyfile
Step #8 - "buildApiServer":     _compile_pipeline_function(pipeline_funcs, function_name, output_path, type_check)
Step #8 - "buildApiServer":   File "/usr/local/lib/python3.5/site-packages/kfp-0.1.25-py3.5.egg/kfp/compiler/main.py", line 56, in _compile_pipeline_function
Step #8 - "buildApiServer":     raise ValueError('A function with @dsl.pipeline decorator is required in the py file.')
Step #8 - "buildApiServer": ValueError: A function with @dsl.pipeline decorator is required in the py file.
Step #8 - "buildApiServer": The command '/bin/sh -c find . -maxdepth 3 -name '*.py' -type f | while read pipeline; do dsl-compile --py "$pipeline" --output "$pipeline.tar.gz"; done' returned a non-zero code: 1
Finished Step #8 - "buildApiServer"
ERROR
ERROR: build step 8 "gcr.io/cloud-builders/docker" failed: exit status 1
Step #8 - "buildApiServer": [0m
```

**Comment by gaoning777** [comment]
The issue you mentioned is resolved in https://github.com/kubeflow/pipelines/pull/1733.
This issue is not about that. It is about why our e2e test infra does not catch the api image build failure in the cloudbuild.

**Comment by Ark-kun** [comment]
>It is about why our e2e test infra does not catch the api image build failure in the cloudbuild.

You meant the DockerInDocker builds, right?

**Comment by gaoning777** [comment]
Correct. It seems that Dind skips the error and continues the image build while the cloudbuild fails immediately once the exit code is non-zero.

**Comment by IronPan** [comment]
Thanks for investigation. Cross check and saw the error got ignored when building image locally too.

**Comment by Ark-kun** [comment]
I've finished the investigation and opened a fix PR.
Problem: Docker implicitly prepends "sh -c " to the RUN commands (no "-e"). Without "-e", the exit code of the shell script is the exit code of the last executed command. So the sample compilation script will only fail if the last sample failed the compilation.

Fix: Explicitly adding "set -e" to the command fixes the issue.

**Comment by gaoning777** [comment]
Thanks @Ark-kun for fixing this issue.
