### ISSUE TITLE
Can't find the notebook samples

### ISSUE THREAD

**Issue by xauthulei** [kubeflow/pipelines#1743]
**What happened:**
From the tutorial guide to download the sample notebooks from https://github.com/kubeflow/pipelines/tree/master/samples/notebooks. however it will report "404"
**What did you expect to happen:**
I want use the follow the guide to have a try in my local. 
**What steps did you take:**
[A clear and concise description of what the bug is.]
Maybe the tutorial guide have some errors, but what is real one for this. 
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by xauthulei** [comment]
Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]
tutorial guide 's URL is : https://www.kubeflow.org/docs/pipelines/tutorials/build-pipeline/#building-a-pipeline-in-a-jupyter-notebook

**Comment by gaoning777** [comment]
Thanks. I will update it soon.

**Comment by xauthulei** [comment]
Thanks @gaoning777
