### ISSUE TITLE
Option for max concurrent runs in an experiment

### ISSUE THREAD

**Issue by devonkinghorn** [kubeflow/pipelines#1744]
It would be nice if you could set the max concurrent runs in an experiment. 
We have a use case where we run analysis over a days worth of data using a pipeline, but we don’t want to run more than n processes at once. 

It would be great if we could set a value for max concurrent runs in an experiment not just recurring runs.

**Comment by calvinleungyk** [comment]
We have a similar use case where we only want at most 1 concurrent run of an experiment. Did you end up implementing that outside of Kubeflow? @devonkinghorn

**Comment by devonkinghorn** [comment]
@calvinleungyk We used AWS codepipeline for that specific job need.

**Comment by calvinleungyk** [comment]
@devonkinghorn is this still desirable/ beneficial to you? I opened #7261 to see if there are recommendations/ if this can be worked on
