### ISSUE TITLE
Improve the sample test infra.

### ISSUE THREAD

**Issue by numerology** [kubeflow/pipelines#1750]
Currently, there is some inefficiency in the sample test infra. This issue tracks some initial efforts in improving it.

Some action items:
- [x] Reduce the code complexity of the test infra. PR #1730 
- [x] Reduce repeated/unnecessary environment setup/imports to speed up the tests.
- [x] ~~Unify the naming convention. Currently the naming convention in kfp repo is not consistent. This needs to be corrected before further confusion/issues are invoked.~~ Leaving this for future work, it should be part of the coding style adoption.
- [x] Add guideline/readme
- [x] Pythonic migration for test infra
- [x] Config yaml file schema validation
- [x] Add sample test coverage by including more core samples.

**Comment by numerology** [comment]
Currently many repeated occurrences are observed under samples/core and sdk/python/tests/. Some work might be done to dedup and make sure everything is maintainable.

For, e.g., imagepullsecrets PR #1767

**Comment by numerology** [comment]
TODO: Sync with kubeflow/website with these changes.

**Comment by numerology** [comment]
Plan to approach this in the following PRs:
- #1730 to reduce code complexity of sample test scripts.
- Move test-specific environment setup into individual test files, e.g. .py or .ipynb
- Move argo installation to Dockerfile
- Sync with kubeflow/website.
Low priority (but still worth some efforts):
- Unification of naming conventions across samples (and pipeline's repo)
- Issue #193 
- Move some of the tests from sdk/python/tests to samples/core.

**Comment by numerology** [comment]
PR #1897 switch the entry-point from bash script to python, by adopting python fire, to improve manageability and readability.
Two remaining todo items:
1. reduce the usage of subprocess call by directly invoking check_notebook_results.py and run_sample_test.py as python modules.
2. (P1) add unit tests

**Comment by gaoning777** [comment]
Should we close this?

**Comment by numerology** [comment]
> Should we close this?

I think it's better to close this after investigating the ongoing issue:
See #2070

**Comment by numerology** [comment]
#2070 is closed.
