### ISSUE TITLE
persistence agent should delete successful runs right after sync

### ISSUE THREAD

**Issue by hlu09** [kubeflow/pipelines#1755]
**What happened:**

Argo workflow CRD pileup (100K+) caused GKE cluster API times out, causing issues for all namespaces in the cluster.

Excessive workflows (5K+) also caused significant UI slow down.  

**What did you expect to happen:**

Persistence Agent deleted successful workflows right after sync.
Failed workflow can be GCed per workflow TTL since users may want to rerun the pipeline by skipping successful steps.

**What steps did you take:**
[A clear and concise description of what the bug is.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by hlu09** [comment]
Cluster CRD limit info: 

https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20180415-crds-to-ga.md#scale-targets-for-ga

**Comment by IronPan** [comment]
/close
GC is implemented.
