### ISSUE TITLE
Feature ask: Version check for DSL & Run time environment 

### ISSUE THREAD

**Issue by SinaChavoshi** [kubeflow/pipelines#1757]
This is a feature ask to support version check for two specific scenarios 

1. When compiling with DSL allow users to specify the min version of DSL that is supported for that code. This is mostly applicable for samples. This can be verified at compile time to make sure the correct version of DSL compiler is being used. 

2. Version check against Run time Environment - Allow users to specify the min version of the run time that the code supports. Verify this when submitting a compiled pipeline against a run time environment.

**Comment by Ark-kun** [comment]
Proposed design for SDK version check:

```python
if kfp.version < "0.1.23":
    raise Exception("The kfp SDK version is too old to run this sample.")
```

Pros:
* Explicit.
* Easy to understand what's going on.
* Easy to override.

**Comment by paveldournov** [comment]
@SinaChavoshi - does this work?

**Comment by SinaChavoshi** [comment]
I like it. It is explicit and simple. 

This only covers the SDK version validation in development environment. Run time environment validation will still require a solution. I can separate that out in a different issue and turn this issue to a tracker to update all samples with Min version requirement code above. Does that sound ok?

**Comment by Ark-kun** [comment]
> Run time environment validation will still require a solution.

We need some clear user scenario for this. We never had a breaking change, so there was never a real use case to work with.

If we hypothetically decide to make a breaking change in the SDK, then the DSL compiler should start adding the SDK version to the pipeline, so that older backend can refuse it.

>update all samples with Min version requirement code above

We should start properly setting and exposing the kfp SDK version first.

**Comment by SinaChavoshi** [comment]
Agreed on both points, closing this issue.
