### ISSUE TITLE
Fix the component tests with the yaml reference in the samples 

### ISSUE THREAD

**Issue by gaoning777** [kubeflow/pipelines#1758]
The component test infra replaces the image tag with the new ones from the cloudbuild. Since now we use the yaml reference instead of the image tag, the component tests need to be fixed to accommodate the change.

**Comment by paveldournov** [comment]
@gaoning777 are the test broken now or this makes the maintenance harder?

**Comment by gaoning777** [comment]
The component integration tests are broken. However, The purpose of the component tests is to catch the component errors early. The release is not blocked since the sample tests are run when the PR to release the components are merged.

**Comment by Ark-kun** [comment]
> The component test infra replaces the image tag with the new ones from the cloudbuild. Since now we use the yaml reference instead of the image tag, the component tests need to be fixed to accommodate the change.

Sample tests replace the image names in the final compiled Argo workflow yaml, so they are replaced regardless of whether or not the component was loaded from component.yaml.

We need to check whether the postsubmit tests actually replace any image.

**Comment by Ark-kun** [comment]
AFAIK this is fixed. The postsubmit tests build the new component images, compile the samples and replace the images inside the compiled workflows. @numerology can you confirm?

**Comment by numerology** [comment]
> AFAIK this is fixed. The postsubmit tests build the new component images, compile the samples and replace the images inside the compiled workflows. @numerology can you confirm?

Currently in the post-submit test we only have XGboost sample test, whose images are replaced by the latest cloud build tag versions. It works fine. 

However I agree that if we would like to add more to the post-submit test it won't be very manageable. Need a better way to specify the image version used in post-submit tests.

**Comment by Ark-kun** [comment]
@gaoning777 WDYT?

**Comment by numerology** [comment]
/close

Let's fix this right now because the tests are okay right now.
