### ISSUE TITLE
Sample packaging is failing in CloudBuild

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#1761]
https://pantheon.corp.google.com/cloud-build/builds/b6678b41-ee42-49d8-8d1f-9a1f892f1ae0?project=ml-pipeline-test
`Step #29 - "prepareVersionedSamples": sed: can't read samples/*/*.py: No such file or directory`

**Comment by gaoning777** [comment]
https://github.com/kubeflow/pipelines/pull/1764
