### ISSUE TITLE
The compiler tests are brittle: They check that "nothing has changed" instead of verifying the intended behavior.

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#1763]
Good tests check the intended behavior of a feature.
Most of our compiler tests are only checking that "nothing has changed". Every small change affecting the attributes of a pipeline requires changing dozens of tests. https://travis-ci.com/kubeflow/pipelines/jobs/223317709 or https://github.com/kubeflow/pipelines/pull/1381/files
When the tests are brittle, it's also easy to overlook an actual error, since the tests break so often and in hard to debug ways.

We should replace many of the compiler tests with test that check for the feature behavior.
Good examples: 
https://github.com/kubeflow/pipelines/blob/6f2decf2b1660d16047e477b311cce21c3df1331/sdk/python/tests/compiler/compiler_tests.py#L526
https://github.com/kubeflow/pipelines/blob/6f2decf2b1660d16047e477b311cce21c3df1331/sdk/python/tests/compiler/compiler_tests.py#L543
https://github.com/kubeflow/pipelines/blob/6f2decf2b1660d16047e477b311cce21c3df1331/sdk/python/tests/compiler/compiler_tests.py#L568

**Comment by Bobgy** [comment]
/assign @Ark-kun 
totally agree on the idea
