### ISSUE TITLE
Add Cloud SQL connection support

### ISSUE THREAD

**Issue by IronPan** [kubeflow/pipelines#1772]
For production use cases, it's better to use managed service such as cloud sql, instead of in-cluster self hosted mysql. 

We should add an example how to set up API server to use cloud sql.

**Comment by SinaChavoshi** [comment]
Added sample for switching to MySQL here: https://github.com/SinaChavoshi/pipelines/tree/use-cloud-sql/manifests/kustomize/base/mysql 

You will need to make the following two changes in the sqlproxy_deployment.yaml 

Line 23 - Replace the “Instance connection name” from "cloudsql-for-kfp:us-central1:cloudsql-for-fkp-prite-nopass"  to the actual value  from Cloud SQL overview page 

Line 47 - Change the secret name to your service account secret that has edit access on the Cloud SQL instance. Note that SQL proxy assumes credentials are in credentials.json. If you can create a service account specifically for this purpose ( recommended ) or use any service account with project/cloud SQL edit permission.  

After adding the credentials to the cluster run kubectl -n kubeflow get secrets to make sure the secret is added correctly. 

You will need to restart the pipeline pod for it to pick up the new connection.

**Comment by SinaChavoshi** [comment]
Marking as closed this is addressed by PR  #1910
