### ISSUE TITLE
ContainerBuilder support default namespace, gcs, and gcr.

### ISSUE THREAD

**Issue by gaoning777** [kubeflow/pipelines#1775]

**Comment by gaoning777** [comment]
@hongye-sun What do you think the default gcs path should be?  create a randomly gcs bucket?
For target_image gcr tag, also a randomly generated one?

**Comment by Ark-kun** [comment]
@IronPan mentioned the possiblity of using volume instead of GCS storage.
Another option is to change the Pod entrypoint to a program which waits until the data is uploaded to the pod before starting the Kaniko builder.

**Comment by gaoning777** [comment]
Thanks, would you mind following the on-prem support in the issue: https://github.com/kubeflow/pipelines/issues/1701
This issue is for default values not for on-prem scenarios.

**Comment by gaoning777** [comment]
https://github.com/kubeflow/pipelines/pull/1795
