### ISSUE TITLE
Show Recurring run name instead of id in run page 

### ISSUE THREAD

**Issue by IronPan** [kubeflow/pipelines#1786]
**What happened:**
![image](https://user-images.githubusercontent.com/2348602/62795890-a05abe00-ba8c-11e9-9ebe-3d63e27583bf.png)

**What did you expect to happen:**
Show recurring run name

**What steps did you take:**
[A clear and concise description of what the bug is.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by rileyjbauer** [comment]
Are you okay with the frontend making additional calls for each of these, or are you thinking of providing some solution via the backend?

**Comment by IronPan** [comment]
The job name should be surfaced through resource_reference.name field now. UI should be able to just use it.

**Comment by Bobgy** [comment]
we can do this now
