### ISSUE TITLE
Persist Pod Logs for non-GCP Pipeline Deployment

### ISSUE THREAD

**Issue by IronPan** [kubeflow/pipelines#1803]
Current we surface K8s Pod logs to the UI. 
The pod log availability is affected by the evict policy of the cluster and thus not robust enough. 

For GCP deployment, the UI forward the log link to stackdriver. 
For non-gcp case the log will be lost. 

With the change https://github.com/kubeflow/pipelines/pull/1802 this problem will be more surfaced. The workflow will be GCed right after finish, and pod will be cascade deleted.

**Comment by eterna2** [comment]
The workaround for my AWS deployment is to use argo's artifactory backup config to persist the log to s3/minio.

A quick fix is to add an environment var to pipeline UI server to point to the backup url if pod log is unavailable.

I can make a PR to demonstrate my idea.

**Comment by rmgogogo** [comment]
@eterna2 Thanks. Since your PR got merged, here I close this one.
