### ISSUE TITLE
Add sample tests for all core samples

### ISSUE THREAD

**Issue by gaoning777** [kubeflow/pipelines#1813]

**Comment by jessiezcc** [comment]
@gaoning777, pls assign to whoever is helping on this project

**Comment by gaoning777** [comment]
This will depend on some test infra improvement that jiaxiao is working on.

**Comment by gaoning777** [comment]
adding some core sample tests: #2030

**Comment by gaoning777** [comment]
List of not-tested core samples:
https://github.com/kubeflow/pipelines/tree/master/samples/core/ai-platform
https://github.com/kubeflow/pipelines/tree/master/samples/core/artifact_location
https://github.com/kubeflow/pipelines/tree/master/samples/core/component_build
https://github.com/kubeflow/pipelines/tree/master/samples/core/execution_order
https://github.com/kubeflow/pipelines/tree/master/samples/core/imagepullsecrets
https://github.com/kubeflow/pipelines/tree/master/samples/core/kubeflow_tf_serving
https://github.com/kubeflow/pipelines/tree/master/samples/core/multiple_outputs
https://github.com/kubeflow/pipelines/tree/master/samples/core/preemptible_tpu_gpu
https://github.com/kubeflow/pipelines/tree/master/samples/core/resource_ops
https://github.com/kubeflow/pipelines/tree/master/samples/core/retry
https://github.com/kubeflow/pipelines/tree/master/samples/core/sidecar
https://github.com/kubeflow/pipelines/tree/master/samples/core/tfx-oss
https://github.com/kubeflow/pipelines/tree/master/samples/core/volume_snapshot_ops

**Comment by gaoning777** [comment]
adding multiple output sample test: https://github.com/kubeflow/pipelines/issues/2109

**Comment by numerology** [comment]
Suggestion: Maybe not cover retry sample for now due to its non-deterministic behavior.

**Comment by gaoning777** [comment]
Thanks Jiaxiao for the efforts.

**Comment by gaoning777** [comment]
sidecar test: https://github.com/kubeflow/pipelines/pull/2106

**Comment by gaoning777** [comment]
component build sample: https://github.com/kubeflow/pipelines/issues/2109

**Comment by gaoning777** [comment]
There are some sample tests that require extra work:
Category 1) non-determinism. Samples such as retry is non-deterministic. There is no sample test infra support for such non-deterministic behaviors. First, we will run the DSL compiler against it without running the pipeline. Since retry is part of the argo support, this is sufficient for now to only test the DSL compilation.
Category 2) platform support. Samples such as preemptible_tpu_gpu requires more platform configurations, which is not supported by the sample test infra. This is P1 work.

**Comment by gaoning777** [comment]
retry: https://github.com/kubeflow/pipelines/pull/2141

**Comment by gaoning777** [comment]
artifact location: https://github.com/kubeflow/pipelines/pull/2142

**Comment by gaoning777** [comment]
Updated the assignment.

**Comment by gaoning777** [comment]
preemptible vm&volume snapshot: https://github.com/kubeflow/pipelines/pull/2149

**Comment by gaoning777** [comment]
@Ark-kun any progress on the multiple output test?

**Comment by gaoning777** [comment]
resource_ops sample test: https://github.com/kubeflow/pipelines/pull/2274
