### ISSUE TITLE
CloudBuild fails - visualization-server image is missing

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#1815]
[CloudBuild fails](https://pantheon.corp.google.com/cloud-build/builds/368847f6-feb1-49bb-96b2-540d14191b0f?project=ml-pipeline-test) - [logs](  
   https://00e9e64bac45f39910a5915d8867c1492f59345d4a0d065c2a-apidata.googleusercontent.com/download/storage/v1/b/363997316495.cloudbuild-logs.googleusercontent.com/o/log-368847f6-feb1-49bb-96b2-540d14191b0f.txt?qk=AD5uMEuJwqtT56rGPZii9BR4TEh7XReM3-YGZNFcvZyAlei6DyloWjQSE11XDjMSLYhCyOjP3yyy9En-h3mE7nqZM7iSmMXxop6RwU3RpofBjZ7Je8SEGZTIPgy7Vl1ZejuHTJlAn_Srqsp3VmtFddWQNW9Now1s6ejVj8bBjBYtUEj6R_k4DB3TmeN7zQjDeQNlcrS41jShrJBOzF6zfwIJMjOCgPgedVZB4FQohxejKMgKNwlflQ0v19MEQAtH4_mwg3tf_qwK3j9d948sf8LWGfrK04MmN7menACKlvcvtkiG8IUc91ZNHJGi7IslmJnMYc5QMuKrbrXU1NmBv0T9OQgqf5bR_wb1UIwUcer6mH9s-JgoNPXWn37XDolN2iPFwaoYsG7t2SLXNgA83myOzsSK7ZnZ08xcGU_L7mCGbXFwpCNs8hrjweif7n1DoG4Ohx-yPOkxjjzMvWTmCqmS0-f_qvAvpsntxi_5hCuQZo34uvNpsCI-EsykHTF0mrUZNQnTTsWHhgaZy6g1PoXy1xwOxtTj3HaZQiWVIZTeIhax0qHDu_ho48LSWfvUphaiJywLziu0M8LWZZ_c8FkULcDJOB2SzcXuD2e4hXHedjaofcqImloOw0cQ2zrWjrbOeFiGgQba9GcU91NNWhdbKYwpP_ze1sbas8nkVL4NgsjcV9TQZJwS8yNYb6A7ytvKDLXNKJTvz0RjAsuVFu-unaYeyrau6UiIyow0eLvVudt7Cj3rBWhNEcSZyX7Cc5Q7DmAcvAZUU3s0XdVc1e-1Lb6JDlBuLjjJxe88LksSUy_2MSPQIwYzzM1iBxEGgmYXpefuS1Dcu-QMv5_KbYdmI2NELeNB0RY8kCsUF_Jf5JgJ0gwKfsw)

I see th following error:
```
   ERROR: failed to find one or more images after execution of build steps: ["gcr.op/ml-pipeline-test/visualization-server:2d6a314e549cf27dd260c9777c4da7314caa9a80"]
```

Looks like the image is being build, but not pushed: https://github.com/kubeflow/pipelines/pull/1738/files#diff-ea967cf037de3503a92911b5c390b596

We need to add the missing step.

**Comment by Ark-kun** [comment]
I found the error and produced the fix.

**Comment by ajchili** [comment]
Whoops, I didn't realize I made a typo. Thank you for the fix!
