### ISSUE TITLE
Embeddable run view page

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#182]
I'd like to insert the run view page into a notebook when I submit the run.

For this I'd like to have a minimal page without left or top navigation, with only the run view and the refresh button.

**Comment by yebrahim** [comment]
The run details page is one of the more complicated parts of the frontend. What's the use case for this?

**Comment by Ark-kun** [comment]
The scenario is embedding the run view in the Notebook.
Submit the run and immediately see it in your notebook.

**Comment by yebrahim** [comment]
But why? Assuming you're talking about a Jupyter notebook hosted from a Kubeflow cluster, why not just click a link to see the run in the Pipelines UI? Is the goal to save this click?

Or is the above assumption incorrect? Are you talking about a completely standalone notebook, with visualizations packaged into it?

**Comment by Ark-kun** [comment]
> But why? Assuming you're talking about a Jupyter notebook hosted from a Kubeflow cluster, why not just click a link to see the run in the Pipelines UI? Is the goal to save this click?

Yes. This is about saving a click each time you want to check the run. This is even more important when the user runs JupyterLab as a separate application and not as a browser tab.

**Comment by Ark-kun** [comment]
Is it hard to add support for query parameter like `hide_navigation=true` ?

**Comment by yebrahim** [comment]
Can you elaborate on the JupyterLab-as-separate-application part? Is it still backed by the KF cluster kernel manager?

This isn't about changing the view or removing the chrome, it's about hosting our entire UI webapp in the notebook's cell output iframe, and most importantly finding a way around CORS. If the only motive here is saving a single click, I don't see why we should pursue this.

**Comment by yebrahim** [comment]
I'll close this as I don't see a good reason for it, nor do I see a good way of doing it.
We can continue the discussion separately if you still feel a need for this.

**Comment by Bobgy** [comment]
> Can you elaborate on the JupyterLab-as-separate-application part?

I also wanted clarification on this. What would be different in JupyterLab?


Does jupyter use an iframe to show KFP UI page? Did you try so? It should already show the UI, just with the navigation. If you already verified that works, this feature isn't very hard. Although I kind of doubt how many people actually wants it. Does the efforts worth saving a click?

**Comment by Ark-kun** [comment]
>Does jupyter use an iframe to show KFP UI page? Did you try so? It should already show the UI, just with the navigation.

As far as I remember, I've verified that Jupyter can show iframes with arbitrary pages. That IFrame has limited height by default, so the top navigation obscures most of it.

>Although I kind of doubt how many people actually wants it. Does the efforts worth saving a click?

The idea is to be able to stay in the development environment (Jupyter) while monitoring the work progress. I think this will look pretty cool can unique for demos.

**Comment by Bobgy** [comment]
I can follow up on a demo with this, shouldn't be too hard

**Comment by Bobgy** [comment]
/cc @jamxl @StefanoFioravanzo 
about this interesting request
but it's not a priorrity
