### ISSUE TITLE
Enable s3 to store temporary staging build files 

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/pipelines#1821]
`compiler.build_python_component` doesn't work for non-gcp environment, instead of using gcs to store temporary files, I also like to use s3 to store staging files. Otherwise, I can not use sdk to build pipeline.

I will take the work to add the support and make it generic

**Comment by Ark-kun** [comment]
AFAIK, the staging URI already supports S3. But only GCP secrets are being mounted to Kaniko pod. That is the part that can be generalized.

**Comment by Jeffwan** [comment]
@Ark-kun Thanks. I will check that part.

**Comment by jerrylam** [comment]
Does this work? I hit the same problem and I specified s3 path but it said:
`2019-08-23 20:17:32:ERROR:Error: s3://a_bucket/dev/ should be a GCS path.`

**Comment by jerrylam** [comment]
@Ark-kun I just checked the source code for `ContainerBuilder` in the master branch, it does not yet work with s3.

**Comment by gaoning777** [comment]
it does not support s3, yet. Contributions are mostly welcome.

**Comment by Ark-kun** [comment]
> it does not support s3, yet. Contributions are mostly welcome.

Is that due to secrets?
