### ISSUE TITLE
Instruction for running it on minikube

### ISSUE THREAD

**Issue by smartnose** [kubeflow/pipelines#184]
Hey. I would like to try this project out on minikube without GKE. Can't really find any docs around this.

**Comment by Ark-kun** [comment]
Do you already have minikube set up? The installation instructions are the same.

https://github.com/kubeflow/pipelines/wiki/Installation---Minikube

**Comment by Ark-kun** [comment]
I think there was another comment here with some MySQL persistent disc problem. Did you solve it?

**Comment by smartnose** [comment]
I did not. MySQL persistent disc problem does not repro on MacBook, but does appear on my ubuntu 16.04 box

**Comment by Ark-kun** [comment]
Can you please get the failing pod logs?

**Comment by vicaire** [comment]
Resolving as this has been idle for several months.
