### ISSUE TITLE
Minor changes should not invoke presubmit e2e/sample test

### ISSUE THREAD

**Issue by numerology** [kubeflow/pipelines#1848]
Minor changes, including doc fixing, lint, etc., should not invoke e2e/sample test, which is very time consuming and increases workload on Prow cluster as well.

This can be fixed by changing the config in [prow config](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubeflow/kubeflow-presubmits.yaml).

**Comment by Bobgy** [comment]
We should keep this open.

A fix can be configuring these tests' run_if_changed to exclude '*.md' files.
another option is to give explicit folder constraints

**Comment by numerology** [comment]
/lifecycle frozen

I tried to file https://github.com/kubernetes/test-infra/issues/14958 for this but got no replies :(
