### ISSUE TITLE
Sample consistency: Add a compile step at the end of all core samples 

### ISSUE THREAD

**Issue by gaoning777** [kubeflow/pipelines#1865]

**Comment by numerology** [comment]
Q: Shall we add some result checks, too?

**Comment by gaoning777** [comment]
> Q: Shall we add some result checks, too?

For the basic ones, I think it is sufficient to call it correct if the pipeline runs successfully. The downsides of adding the checking codes in the samples, which makes the sample convoluted, might outweigh its benefit, which is correctness checking. 
For complex ones, I think the checks would be useful. In terms of priority, I would categorize the result checking feature as P1/P2.
