### ISSUE TITLE
Error in retrieving list of pipelines (KubeFlow v0.6.1)

### ISSUE THREAD

**Issue by kimchitsigai** [kubeflow/pipelines#1881]
**What happened:**
I've installed kubeflow v0.6.1, with kfctl_existing_arrikto.yaml.
From the KubeFlow Central Dashboard, I click on Pipelines and I get the error message + Details, shown in the attached screenshot.

![pipelines](https://user-images.githubusercontent.com/5181623/63250439-ef160e00-c26b-11e9-8c86-6896a7e2264b.PNG)

**What did you expect to happen:**
I expect an empty list of pipelines or the list of samples, being displayed without error message.

**What steps did you take:**

**Anything else you would like to add:**
I've also attached the output from kubectl describe the pipeline-related pods.

[pipeline_log.txt](https://github.com/kubeflow/pipelines/files/3514852/pipeline_log.txt)

**Comment by kimchitsigai** [comment]
I'm adding the outputs from kubectl logs for the pipeline related pods.
There seems to be something wrong  with ml-pipeline:
`Failed to commit transaction to initialize default experiment table`

[pipeline_log2.txt](https://github.com/kubeflow/pipelines/files/3515025/pipeline_log2.txt)

**Comment by rmgogogo** [comment]
I also got few times same issue on it. On our radar now.

-- please ignore following --
b/144082994

**Comment by akshayuppal3** [comment]
Having the same issue ..

**Comment by akshayuppal3** [comment]
had to do with low on disk space..

**Comment by ReggieCarey** [comment]
this is still a bug.  Stop closing it.

**Comment by Bobgy** [comment]
/reopen


Can you provide more details and error message?

**Comment by bvboca** [comment]
have the same issue

**Comment by bvboca** [comment]
have the same issue

**Comment by bvboca** [comment]
I did a fresh install on a clean kubernetes 1.16. The issue is not seem for now.  Before this, I install kubeflow on an existing istio cluster and skip some steps. Maybe some functions are broken in my installation.

**Comment by Bobgy** [comment]
Kubeflow 1.2 on dex is not supported by any party participating, I'd suggest waiting for 1.3 where @yanniszark said they will maintain.

**Comment by santhosh261190** [comment]
This is due to the race conditions while creating the resources. In my case, once after all the resources are up and running i did executed "kubectl delete namespace kubeflow", this will re-create and possibly the issue will go away.

**Comment by DeepFlame-JR** [comment]
In my case, the error message was "Error: failed to retrieve list of pipelines" and detail message "No healthy upstream".
And I got the logs in pod of ml-pipeline-xxxx
```
I0329 08:27:53.106414       6 client_manager.go:160] Initializing client manager
I0329 08:27:53.106781       6 config.go:57] Config DBConfig.ExtraParams not specified, skipping
[mysql] 2020/12/04 00:28:19 packets.go:36: unexpected EOF
[mysql] 2020/12/04 00:28:23 packets.go:36: unexpected EOF
[mysql] 2020/12/04 00:28:26 packets.go:36: unexpected EOF
[mysql] 2020/12/04 00:28:32 packets.go:36: unexpected EOF
[mysql] 2020/12/04 00:28:38 packets.go:36: unexpected EOF
```

I solved this problem by just commading `kubectl delete po ml-pipeline-xxx`
Then new pod will be created by ml-pipeline deployment.
