### ISSUE TITLE
Support retry to completion in DSL

### ISSUE THREAD

**Issue by gaoning777** [kubeflow/pipelines#1883]
argo supports retry to completion feature: https://github.com/argoproj/argo/blob/master/examples/retry-container-to-completion.yaml

This issue tracks surfacing it in the DSL

**Comment by rmgogogo** [comment]
Is it already be supported? I remember was told we already can support retry (maybe just Argo already support)

**Comment by rmgogogo** [comment]
Another ticket: https://github.com/kubeflow/pipelines/issues/1846

**Comment by gaoning777** [comment]
The DSL also supports retrying. However, there is not a verb as retry_to_completion. This FR was a request for such a DSL verb.
