### ISSUE TITLE
Missing Affinity for Containerop

### ISSUE THREAD

**Issue by hamedhsn** [kubeflow/pipelines#1884]
**What happened:**
currently we are missing function to setup the affinity for containerop. 
Am gonna create a PR to support that shortly

**Comment by paveldournov** [comment]
@hamedhsn can you please described the proposed feature in more details?

**Comment by hamedhsn** [comment]
we are using affinity over node selector to request for different types of instances when users request nodes in our platform. We have it outside kfp but As we are integrating kfp into our platform we need to support that. 
PR: https://github.com/kubeflow/pipelines/pull/1886
