### ISSUE TITLE
FR: new components to demonstrate how to send requests to exising seldon/tfserving instances

### ISSUE THREAD

**Issue by gaoning777** [kubeflow/pipelines#1885]
Kubeflow has several serving components: https://www.kubeflow.org/docs/components/serving/
It's great to have some generic components that send prediction request to these serving services.

**Comment by paveldournov** [comment]
@gaoning777 should the serving components (e.g. KF Serving) expose an interface to discover the way to call the prediction endpoint (for example through a swagger schema) and a client lib to make such calls easier? I think the artifacts store should also declare a type to represent a deployed model with necessary properties to describe how to invoke the endpoint, which would make it possible for the UI to dynamically construct the request.

/cc: @neuromage
