### ISSUE TITLE
Inconsistent ExitHandler behavior

### ISSUE THREAD

**Issue by logicbomb421** [kubeflow/pipelines#1899]
This is an expansion on #999.

<hr/>

**What happened:**
It appears currently the only valid way to create an `ExitHandler` is using `dsl.ContainerOp`, with `is_exit_handler` set to `True`. When the pipeline runs, duplicate nodes are spawned at the beginning of the workflow and execute the exit handler logic immediately. Attempting to set `is_exit_handler` manually on an ad-hoc component created with `func_to_container_op`, or one loaded via `load_component[*]`, appears to do nothing.

**What did you expect to happen:**
Regardless of where the component came from, marking it as an exit handler should inform Kubeflow the component is an exit handler, and said handler should only be invoked once upon exiting the pipeline.

**What steps did you take:**

### `func_to_container_op` exit handler

```python
import kfp.dsl as dsl
import kfp.components as components

def print_message(message: str) -> None:
  print(message or 'NO MESSAGE SUPPLIED!')
print_op = components.func_to_container_op(print_message, base_image='python:3.7-alpine')

@dsl.pipeline(name='simple pipeline')
def pipeline_func():
  exit_handler = print_op('EXITED')
  exit_handler.is_exit_handler=True
  with dsl.ExitHandler(exit_handler):
    first = print_op(message='first')
    second = print_op(message='second').after(first)
    third = print_op(message='third').after(second)
```

This design produces the following result:
<img width="440" alt="Kubeflow_Pipelines" src="https://user-images.githubusercontent.com/18082086/63378387-fa8a3780-c346-11e9-9ab4-d3c6c898dddf.png">

### `load_component_from_text` exit handler

```python
import kfp.components as components
from kfp import dsl

exit_op = components.load_component_from_text("""
name: 'Print Message Component'
description: Prints a message.
inputs:
  - {name: message, type: String, description: 'Required. The message to print.'}
implementation:
  container:
    image: python:3.7-alpine
    command: [python]
    args: [
      -c,
      import sys; print(sys.argv.pop() or 'FALLBACK MESSAGE'),
      {inputValue: message},
    ]
""")

def print_message(message: str) -> None:
  print(message or 'NO MESSAGE SUPPLIED!')
print_op = components.func_to_container_op(print_message, base_image='python:3.7-alpine')

@dsl.pipeline(name='simple pipeline')
def pipeline_func():
  exit_handler = exit_op(message='EXITED')
  exit_handler.is_exit_handler=True
  with dsl.ExitHandler(exit_handler):
    first = print_op(message='first')
    second = print_op(message='second').after(first)
    third = print_op(message='third').after(second)
```

This design produces the following result:
<img width="411" alt="Kubeflow_Pipelines" src="https://user-images.githubusercontent.com/18082086/63378523-40df9680-c347-11e9-8c64-e72eb51eb238.png">

### pure `dsl.ContainerOp` exit handler

```python
import kfp.dsl as dsl
import kfp.components as components

def print_message(message: str) -> None:
  print(message or 'NO MESSAGE SUPPLIED!')
print_op = components.func_to_container_op(print_message, base_image='python:3.7-alpine')

@dsl.pipeline(name='simple pipeline')
def pipeline_func():
  exit_handler = dsl.ContainerOp(
    name='Exit Handler',
    is_exit_handler=True,
    image='python:3.7-alpine',
    command='python',
    arguments=[ 
      '-c',
      "print('EXITED')"
    ]
  )
  with dsl.ExitHandler(exit_handler):
    first = print_op(message='first')
    second = print_op(message='second').after(first)
    third = print_op(message='third').after(second)
```

This design **correctly** produces the following result:
<img width="190" alt="Kubeflow_Pipelines" src="https://user-images.githubusercontent.com/18082086/63378620-7a180680-c347-11e9-9ead-988b8a7ca710.png">

**Anything else you would like to add:**
Ideally this boolean value would be supplied with all calls that return a component factory function (to avoid needing to set it explicitly on the resulting operation).

**Comment by Ark-kun** [comment]
Fixed by https://github.com/kubeflow/pipelines/pull/2411
