### ISSUE TITLE
Clean duplicate/outdated TFX components in favor of the TFX OSS components

### ISSUE THREAD

**Issue by gaoning777** [kubeflow/pipelines#1903]

**Comment by gaoning777** [comment]
To replace the tfx-cab-classification with tfx-oss, there are several steps:
1) use a versioned tfx-oss example
2) resolve errors with the current tfx-oss sample
3) wait for the metadata service to be deployed
4) reduce data size such that tfx-oss example runs faster
5) add the tfx-oss sample to the sample tests
6) replace the tfx-cab-classification with tfx-oss and have tfx-oss sample to be uploaded to the KFP during deployment.

**Comment by gaoning777** [comment]
blocked by the https://github.com/tensorflow/tfx/issues/362 to support parameterization in the TFX DSL.

**Comment by gaoning777** [comment]
Deleting the old tfx cab classification sample: https://github.com/kubeflow/pipelines/pull/2160

**Comment by gaoning777** [comment]
We are not supporting the old dataflow components and will use the TFX components in the https://github.com/tensorflow/tfx. 
We are currently writing a TFX sample using these components that can work without calling GCP services. It should be merged in the near future.

**Comment by cvenets** [comment]
Since this will be a regression for on-prem deployments, shouldn't we keep both, until we have the new one working without calling GCP services?

Then we can remove the old one, but currently people working on-prem won't be able to run the Taxi Cab example at all.

@gaoning777, @jlewi what do think?

**Comment by jinchihe** [comment]
I think @cvenets suggestion makes sense, that's better to support on-prem Kubeflow cluster for the import E2E sample :-) and I think effort is not big, just need to enhance the notebook and add some description to support that.

**Comment by gaoning777** [comment]
Could you use the TFX sample: https://github.com/kubeflow/pipelines/blob/a71d5b0f28ab4bcd235ba162e55b1561d2e734ec/samples/core/tfx_cab_classification/tfx_cab_classification.py
which should be working since it fixes the component versions?
@neuromage

**Comment by gaoning777** [comment]
https://github.com/kubeflow/pipelines/pull/2319
