### ISSUE TITLE
_output_files is not defined with func_to_container_op

### ISSUE THREAD

**Issue by knkski** [kubeflow/pipelines#1907]
**What happened:**

I compiled a pipeline with `func_to_container_op`, and didn't specify any outputs, since there aren't any. It then failed with `NameError: name '_output_files' is not defined`

**What did you expect to happen:**

I expected the pipeline step to work without having to specify an output.

**What steps did you take:**

Here's the function that I'm converting to a container op:

```python
def ensure_bucket_task(endpoint: str, bucket: str):
    from minio import Minio
    from minio.error import BucketAlreadyOwnedByYou, BucketAlreadyExists

    mclient = Minio(
        endpoint,
        access_key=...,
        secret_key=...,
    )

    try:
        mclient.make_bucket(bucket)
    except (BucketAlreadyExists, BucketAlreadyOwnedByYou):
        pass
```

There isn't anything useful to return, since the bucket name is parameterized in the workflow parameters.

**Anything else you would like to add:**

This is the relevant bit from the auto-generated wrapper that is failing:

```python
for idx, filename in enumerate(_output_files):
    _output_path = Path(filename)
    _output_path.parent.mkdir(parents=True, exist_ok=True)
    _output_path.write_text(str(_outputs[idx]))
```

I can fix this issue by specifying a return value. Even something like `-> str` and not returning anything works, but it would be nice to avoid unnecessary boilerplate.

**Comment by Ark-kun** [comment]
I'm sorry you got bitten by this bug.
It was fixed in https://github.com/kubeflow/pipelines/pull/1726
Please run `pip3 install kfp --upgrade` to update your SDK.
