### ISSUE TITLE
Convert the XGBoost sample to use the new GCP components

### ISSUE THREAD

**Issue by gaoning777** [kubeflow/pipelines#1913]
1. The current XGBoost uses the old dataproc components. We need to convert it to use the new GCP components.
2. Also remove the old dataproc components.

**Comment by jessiezcc** [comment]
@gaoning777, is it already done? or feel free to re-assign.

**Comment by gaoning777** [comment]
This one is not complete yet. 
@numerology will you be willing to take over this task?

**Comment by numerology** [comment]
NP.

**Comment by gaoning777** [comment]
Thanks Jiaxiao.

**Comment by numerology** [comment]
/close
Fixed by #2220
