### ISSUE TITLE
GCP components markdown display error

### ISSUE THREAD

**Issue by gaoning777** [kubeflow/pipelines#1915]
**What happened:**
![Screenshot from 2019-08-21 12-31-53](https://user-images.githubusercontent.com/3826739/63462400-b0b95400-c40f-11e9-8da0-b8a14b4282ea.png)
When I click the 'Job Details' button, it shows pantheon refuses to connect'
**What did you expect to happen:**

**What steps did you take:**
[A clear and concise description of what the bug is.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by gaoning777** [comment]
@hongye-sun Would you mind taking a look? Thanks

**Comment by rmgogogo** [comment]
What's the link of the "Job Detalis"?

**Comment by Bobgy** [comment]
@gaoning777 @hongye-sun Is this still an issue?
Can we close?
