### ISSUE TITLE
feature request: grab an existing pipeline ID via the SDK

### ISSUE THREAD

**Issue by amygdala** [kubeflow/pipelines#1919]
We can now pass a pipeline id to the `run_pipeline` method (thanks!).

To make it easier to use this method in scripts, would it make sense to have a 'get pipeline id from name' method, for existing pipelines? Similar to how `create_experiment` returns an ID if the experiment name already exists.  Apologies if there is such a method and I missed it.

Related: the UI does not make it easy to find the ID of an existing pipeline (in case you want to pass it to `run_pipeline`). You have to mouse-over the pipeline in the listing-- you can see it there.  But actually clicking in to the details obscures the ID. 
Maybe we could show it in the 'Summary' card at bottom left or something.

**Comment by Ark-kun** [comment]
What do you think about getting the list of pipelines and doing the filtering, selecting the pipelines you're interested in?

**Comment by amygdala** [comment]
It would be nicer UX for the user to not have to do that filtering themselves, if they're wanting a specific pipeline, as I expect this would be a common task.  Though of course, having some way of doing this programmatically is better than no way.

I saw there was a `list_pipelines` method but didn't try it yet — does the returned info include both the name and the ID?  If so, maybe we could also build a utility method that takes name(s) as arg, calls list_pipelines and then does the selection.
