### ISSUE TITLE
Tests sometimes run multiple times for the same commit (creating multiple GKE clusters).

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#192]
| sampletest-7280c8b777-12936 | us-central1-a | 3 | 6 vCPUs | 22.50 GB |   |   | Connect
  | sampletest-7280c8b777-18221 | us-central1-a | 3 | 6 vCPUs | 22.50 GB |   |   | Connect
  | sampletest-c39a63680f-14885 | us-central1-a | 3 | 6 vCPUs | 22.50 GB |   |   | Connect
  | sampletest-c39a63680f-6684 | us-central1-a | 3 | 6 vCPUs | 22.50 GB |   |   | Connect

**Comment by vicaire** [comment]
@IronPan, is this issue resolved? Can we close?
