### ISSUE TITLE
[FR] Add support for Vega/Vega Lite visualizations

### ISSUE THREAD

**Issue by ajchili** [kubeflow/pipelines#1924]
[Vega](https://vega.github.io/vega/) and [Vega Lite](https://vega.github.io/vega-lite/) are visualizations built with JSON to specify the appearance and interactive behavior of a visualization. This is similar to #1472 but rather than being Python based, it is based in Javascript and is built with support for [Protovis](http://mbostock.github.io/protovis/) and [D3.js](https://d3js.org/). Introducing Vega or Vega Lite as a visualization tool (as recommended by @eterna2) would vastly improve the extensible of the visualizations offered within Kubeflow Pipelines. To help guide this FR, I plan on writing a doc for implementing Vega/Vega Lite within Kubeflow Pipelines given the current visualization solution that is being implemented.

**Comment by eterna2** [comment]
Hi any updates on this? If not, I don't mind contributing as vega is one of my fav viz lib?

**Comment by ajchili** [comment]
Hey @eterna2, I unfortunately did not make any progress for this FR. If possible, I would recommend writing up a design doc and have it be reviewed by the Pipelines team. This will ensure that the desired feature aligns with the goals of Pipelines and prevents work from being duplicated or scraped. Please let me know how I can help!
