### ISSUE TITLE
Support pipeline parameter definition by interacting with dsl.Pipeline

### ISSUE THREAD

**Issue by numerology** [kubeflow/pipelines#1942]
Currently the only way to define pipeline params in KFP dsl is through the signature of the pipeline function. A more systematic and dynamic way is needed to support use cases where the set of pipeline parameters are passed from external.

Example:
[TFX's KFP dag runner](https://github.com/tensorflow/tfx/blob/4b20a6f57fb4cff14f2f570f3042f824aef2fffb/tfx/orchestration/kubeflow/kubeflow_dag_runner.py#L204)

**Comment by merlintang** [comment]
do you mean that we can run a pipeline by passing the parameter into pipeline?  for example, we load a pipeline file, then run the pipeline with new parameters? I have done this before, I can send a pr for this.

**Comment by numerology** [comment]
> do you mean that we can run a pipeline by passing the parameter into pipeline? for example, we load a pipeline file, then run the pipeline with new parameters? I have done this before, I can send a pr for this.

Actually a bit of different. Currently through the signature of the pipeline function, we can define pipeline parameters. However, pipeline function signature is immutable in itself. If we further need to specify the pipeline parameter (not only their runtime values) in a more programmatical way, some alternatives are needed.

**Comment by merlintang** [comment]
I see, you mean that user can add more parameters to the pipeline ?

**Comment by numerology** [comment]
Yes. But this feature is not of high priority, though.

**Comment by Ark-kun** [comment]
`dsl.Pipeline` is a context class that's supposed to be compiler-internal. We were planning to take it private.
Did you mean the `dsl.pipeline` decorator?

**Comment by numerology** [comment]
> `dsl.Pipeline` is a context class that's supposed to be compiler-internal. We were planning to take it private.
> Did you mean the `dsl.pipeline` decorator?

That would be ideal if we can support that without interacting with dsl.Pipeline. However I couldn't think of an easy way to that.
If we can introduce a field to specify pipeline parameter in the decorator, still we need to think carefully how we are going to use that in each component.

**Comment by numerology** [comment]
> `dsl.Pipeline` is a context class that's supposed to be compiler-internal. We were planning to take it private.
> Did you mean the `dsl.pipeline` decorator?

Let me give another look. I think we have some publc APIs that can be used currently. Maybe I don't need to directly manipulate dsl.Pipeline

**Comment by gaoning777** [comment]
Are we planning to take dsl.Pipeline private? If so, why? 
Exposing a Pipeline class similar to the TFX Pipeline is not a bad idea to me. Strongly typed, support dynamic parameters, dynamic pipeline configurations(https://github.com/kubeflow/pipelines/blob/a4fa1edb423c35f4b2d33c62c4a856398807f3ac/sdk/python/kfp/dsl/_pipeline.py#L54). 
Of course, having a simple interface and having the SDK generate the dsl.Pipeline is great for new users. However, exposing the full control of the Pipeline can unblock advanced users for custom scenarios.

**Comment by numerology** [comment]
> Are we planning to take dsl.Pipeline private? If so, why?
> Exposing a Pipeline class similar to the TFX Pipeline is not a bad idea to me. Strongly typed, support dynamic parameters, dynamic pipeline configurations(
> 
> https://github.com/kubeflow/pipelines/blob/a4fa1edb423c35f4b2d33c62c4a856398807f3ac/sdk/python/kfp/dsl/_pipeline.py#L54
> 
> ).
> Of course, having a simple interface and having the SDK generate the dsl.Pipeline is great for new users. However, exposing the full control of the Pipeline can unblock advanced users for custom scenarios.

I'm good with either private or public dsl.Pipeline. However I feel like we need a way to do something like (tentatively, did not carefully think it through)
author_pipeline(
  pipeline_func, # where ContainerOp is initialized, perhaps with PipelineParam in its args.
  pipeline_name, 
  pipeline_description,
  pipeline_params)

**Comment by merlintang** [comment]
thanks @num

**Comment by numerology** [comment]
Added an API in #2082, which allows users to generate the workflow spec of the pipeline in a programmable way.

Marked as fixed for now.
