### ISSUE TITLE
Tide cannot merge the batch due to error in script

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#1957]
https://prow.k8s.io/tide-history?author=Ark-kun
https://prow.k8s.io/?repo=kubeflow%2Fpipelines&type=batch
https://prow.k8s.io/log?job=kubeflow-pipeline-e2e-test&id=1166128972417732608
```
 source /home/prow/go/src/github.com/kubeflow/pipelines/test/build-images.sh
++ set -ex
++ IMAGES_BUILDING=false
+++ gcloud container images list --repository=gcr.io/ml-pipeline-test/
ERROR: (gcloud.container.images.list) Image name cannot end with '/'. Remove the trailing '/' and try again.
++ BUILT_IMAGES=
[test-timing] It took 0m0.597s.
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"prow/entrypoint/run.go:79","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","time":"2019-08-26T23:23:23Z"}
```

**Comment by Bobgy** [comment]
Thanks for the fix. Sorry I didn't know this could be run as batch test too. I'm not super clear what a batch test does.

The only thing I found is: https://github.com/kubernetes/test-infra/tree/master/prow/tide#features
Do you know if there are more detailed explanation of how batch test is run.
