### ISSUE TITLE
Presubmit test CloudBuild failures are hard to debug without logs

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#1978]
Presubmit tests submit CloudBuild builds asynchronously and do not print any of the error messages:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/1970/kubeflow-pipeline-sample-test/1166784286871785473

Running CloudBuild synchronously can solve this issue.

**Comment by Bobgy** [comment]
For the time being, you can go to gcp console, choose ml-pipeline-test project and see log by the build id.

To make this easier, print the logs when the build fails would be a good option. I don't think we have to switch to cloud build synchronously.

**Comment by Bobgy** [comment]
I can work on this
