### ISSUE TITLE
Prow code, test image code and code being tested can still desync.

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#198]
When Prow runs tests it clones the repo and merges the PR branch into master at time T0. This includes `test/presubmit_tests.sh` and `test/*.yaml`

When build-image builds test images, it clones the repo and merges the PR branch into master at time ~T1 separately for each image. This includes `test/*/run_test.sh` and the whole frontend test suite

When a test runs, it clones the repo and merges the PR branch into master at time ~T2 separately for each test. 

This was the issue that most likely caused https://github.com/kubeflow/pipelines/issues/196

That issue got fixed when I explicitly re-run build-image step for all problematic PRs.

I do not fully understand how the unit test image has caused problem, since it should only contain the `run_test.sh` script and couple of Go packages.

**Comment by IronPan** [comment]
Please see comment in https://github.com/kubeflow/pipelines/issues/196 for more details.

**Comment by Ark-kun** [comment]
Fixed in https://github.com/kubeflow/pipelines/pull/315
