### ISSUE TITLE
SOme inputs are not passed to the program in components/gcp/ml_engine/deploy/component.yaml

### ISSUE THREAD

**Issue by JohnMBrandt** [kubeflow/pipelines#1994]
In the component.yaml, `python_version` is specified as a parameter, but the arg is not parsed in the implementation.

`--python_version, {inputValue: python_version},` is needed to be added to the following code block:

https://github.com/kubeflow/pipelines/blob/180f00394700bff97e6c93b12e062750158c8a53/components/gcp/ml_engine/deploy/component.yaml#L98

The component works fine with python 3 if the component.yaml is manually edited, or of the resulting pipeline is manually edited.

**Comment by randxie** [comment]
Friendly ping
