### ISSUE TITLE
Support pipeline uploads via kfp command line

### ISSUE THREAD

**Issue by siganakis** [kubeflow/pipelines#1998]
The current kfp command line interface only supports activities related to runs.  It is possible to upload a new pipeline via a the submit method, but this also executes the pipeline which may not be required (e.g. if Pipeline upload is part of a CI/CD process).

This means it is not possible to upload a compiled pipeline 

I propose that we add a command which wraps `Client.upload_pipeline`

Proposed usage
`kpf pipeline upload --pipeline-name <PipelineName> --package-file <PATH_TO_ARCHIVE>`
`kpf pipeline upload -n <PipelineName> -f <PATH_TO_ARCHIVE>`

**Comment by rmgogogo** [comment]
+Jing. one more step we may also consider versioned pipeline case.
+Sina. FYI.

**Comment by gautamkmr** [comment]
This would be really nice feature to have for on-perm and other cloud providers.

**Comment by gautamkmr** [comment]
@jingzhang36 would you please confirm, looks like its possible to submit pipeline now 
https://www.kubeflow.org/docs/pipelines/tutorials/sdk-examples/

If so we can close this issue then.

**Comment by Tauranis** [comment]
Unfortunately, uploading a new version is crashing.

When I run
```
kfp --endpoint <URL> pipeline upload-version -p <PIPE_ID> -v <PIPE_VERSION> ./dist/pipeline.tar.gz
```
It throws `Reason: Internal Server Error`

Currently I'm using Kubeflow deployed at Google AI Platform with `kfp==0.5.1` and  `kfp-server-api==0.5.0`

Does someone else have the same problem?
