### ISSUE TITLE
Full solution to tests and code desync problem

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#200]
To solve all code desync problems we need to get rid of all `git clone` calls and most likely remove the split between build-images and the tests.

* We can use Kaniko or Bazel to build images that contain the source code that Prow has prepared. See https://github.com/GoogleContainerTools/kaniko and https://github.com/bazelbuild/rules_docker
* Images should be built as part of the Prow test, not as a separate test entry.
* We should use the current Prow commit hash (`git rev-parse HEAD`) when tagging and pushing the images. I've seen Prow tests being run multiple times per PR's SHA, so we should make sure nothing is overwritten. If we want to make it easier to locate the images, we can use `pr_sha/head_sha` in the path.
* For unit tests, there is probably no need to build images. These tests can just run directly on Prow (with the right base image specified).

**Comment by vicaire** [comment]
@Ark-kun , could you elaborate of the advantages/disadvantages of Kaniko VS Bazel?

**Comment by Ark-kun** [comment]
> @Ark-kun , could you elaborate of the advantages/disadvantages of Kaniko VS Bazel?

Kaniko is just Docker-in-Docker on Kubernetes. It's a full Docker running in a privileged container.

Bazel does not have full Docker support. It does not even support Dockerfile. AFAIK, it can only add files to the base image (and maybe add apt packages). It cannot `RUN` anything as it does not execute a container - it only manipulates the image.

**Comment by Ark-kun** [comment]
Fixed in https://github.com/kubeflow/pipelines/pull/315
