### ISSUE TITLE
kfp compiler can not use a docker context as a directory

### ISSUE THREAD

**Issue by pahask8** [kubeflow/pipelines#2014]
**What happened:**

Currently kfp compiler can not use a docker context as a directory, see the code [link](https://github.com/kubeflow/pipelines/blob/efe9d87b31146ac29e38fb9f1b3ce3092ac9376e/sdk/python/kfp/compiler/_component_builder.py#L443)

```
with tempfile.TemporaryDirectory() as local_build_dir:
    dockerfile_rel_path = 'Dockerfile'
    dst_dockerfile_path = os.path.join(local_build_dir, dockerfile_rel_path)
    shutil.copyfile(dockerfile_path, dst_dockerfile_path)
```
**What did you expect to happen:**
I think it is good to support a docker context instead of just a relational path to a Dockerfile.

**What steps did you take:**
Here is my example of code:

```
import os
from kfp import compiler

os.environ["GOOGLE_CLOUD_PROJECT"] = "my-project"
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "gcp.json"

build = compiler.build_docker_image(
    staging_gcs_path="gs://kfp-build-stage",
    target_image="gcr.io/mmy-project/kfp-build",
    dockerfile_path="/kubeflow_pipelines/docker_build/src/Dockerfile",
    timeout=600,
    namespace="kubeflow"
)
```
As a result, I can not build a docker image that requires a docker context.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Will submit a pull request.

**Comment by pahask8** [comment]
Pull request https://github.com/pahask8/pipelines/pull/new/2014

**Comment by pahask8** [comment]
Could someone please take a look at https://github.com/kubeflow/pipelines/pull/2015 ? Thank you

**Comment by Ark-kun** [comment]
Fixed by https://github.com/kubeflow/pipelines/pull/1970
