### ISSUE TITLE
Add component run time to UI

### ISSUE THREAD

**Issue by sngahane** [kubeflow/pipelines#2029]
While we know the total duration of a run in the "Runs" page, it would be useful to know how long it took to run a single component as part of the UI.

**Comment by sngahane** [comment]
Hi @jessiezcc, would you mind providing an update on this feature? Thanks!

**Comment by jessiezcc** [comment]
Given it's P2, not on top of Jing's to-do list. 
@jingzhang36 to provide the latest ETA. If it's urgent for you, @sngahane feel free to pick it up.

**Comment by rmgogogo** [comment]
https://github.com/kubeflow/pipelines/issues/2159

Close this one as duplicated.
