### ISSUE TITLE
Make it easy for people to write pipeline tests in python

### ISSUE THREAD

**Issue by cwbeitel** [kubeflow/pipelines#203]
When using kubeflow/pipelines, as in https://github.com/kubeflow/examples/pull/322, someone might define a new container op like so: 

```python
def training_op(learning_rate: float,
                num_layers: int,
                optimizer='ftrl',
                step_name='training'):
  return kfp.ContainerOp(
    name=step_name,
    image='katib/mxnet-mnist-example',
    command=['python', '/mxnet/example/image-classification/train_mnist.py'],
    arguments=[
      '--batch-size', '64',
      '--lr', learning_rate,
      '--num-layers', num_layers,
      '--optimizer', optimizer,
    ]
  )
 @kfp.pipeline(
  name='Pipeline GPU Example',
  description='Demonstrate the Kubeflow pipelines SDK with GPUs'
)
```

It would be nice if kubeflow/pipelines made it simple to write a test for this. Currently my understanding is that in order to trigger a pipeline run you have to manually upload the compiled tgz, correct? If it were also possible to programmatically trigger a pipeline run, poll for completion, then check the resulting status - any codebase using pipelines could be made more robust with these sorts of tests. It would also broaden the relevance of pipelines as a convenient means of building test workflows.

/cc @jlewi @texasmichelle

**Comment by Ark-kun** [comment]
Right now it's possible to auto-submit a pipeline when working from a hosted JupyterHub (use the "Notebooks" link in the pipelines UI). See the end of [Lightweight components notebook](https://github.com/kubeflow/pipelines/blob/master/samples/notebooks/Lightweight%20Python%20components%20-%20basics.ipynb) for sample code.

I've created an issue to enable submitting the pipelines from local machine: https://github.com/kubeflow/pipelines/issues/206

**Comment by cwbeitel** [comment]
So just to summarize we'd like to be able to launch a pipeline like so, from the test deployment:

```python
import kfp
client = kfp.Client()
experiment = client.create_experiment(experiment_name)
run_result = client.run_pipeline(experiment.id, run_name, pipeline_filename, arguments)
```

Taking a closer look at kfp.Client, [here](https://github.com/kubeflow/pipelines/blob/b39435765d83f9cf58c21961ae048ac574992d57/sdk/python/kfp/_client.py#L48),

```python
class Client(object):

  def __init__(self, namespace='kubeflow'):

    ...

    host='ml-pipeline.' + namespace + '.svc.cluster.local:8888'
    config = kfp_run.configuration.Configuration()
    config.host = host
    api_client = kfp_run.api_client.ApiClient(config)
    self._run_api = kfp_run.api.run_service_api.RunServiceApi(api_client)

  def run_pipeline(self, experiment_id, job_name, pipeline_package_path, params={}):

    ...

    response = self._run_api.create_run(body=run_body)

```

it looks like this would work from any node in the cluster with access to 

```python
'ml-pipeline.' + namespace + '.svc.cluster.local:8888'
```

correct? Would that work as long as it was run from the same namespace as where kf pipelines is deployed? Or is there additional complexity in talking to that endpoint?

/cc @Ark-kun @qimingj @texasmichelle

**Comment by vicaire** [comment]
Resolving in favor of https://github.com/kubeflow/pipelines/issues/360
