### ISSUE TITLE
Support all container APIs through container op

### ISSUE THREAD

**Issue by IronPan** [kubeflow/pipelines#204]
It looks like currently we only expose a subset of the container API through container op. 
https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/dsl/_container_op.py#L30

Does it make sense to expose all container APIs? Or is it already supported? 
For example, I have a shared container with multiple source code directories available. I wish to be able to customize the workingdir for my container.

**Comment by IronPan** [comment]
Another use case would be setting environment variable.

**Comment by IronPan** [comment]
Another use case would be attaching volumes with secret for accessing GCP, S3 etc.

**Comment by vicaire** [comment]
@hongye-sun, I am guessing that this will be resolved as part of this PR: https://github.com/kubeflow/pipelines/pull/879. Could you please confirm?

**Comment by hongye-sun** [comment]
Yes.

**Comment by vicaire** [comment]
Thanks!

**Comment by vicaire** [comment]
Pending  #879.

**Comment by Ark-kun** [comment]
Done.
