### ISSUE TITLE
Show links to GCP services in the UI when needed

### ISSUE THREAD

**Issue by neuromage** [kubeflow/pipelines#2054]
If a step has submitted a job to Cloud AI Platform training/serving, or is running a Dataflow job, we should be able to parse the logs in the UI and find the relevant URL that points to the relevant job link on GCP. We should then show this link to the user in the KFP UI when she clicks on the relevant pipeline step.

In the long term, we should also explore exposing capabilities to the container to do real-time reporting of arbitrary key-value statuses, which will be displayed in the UI. Similar to the metadata produced for artifact visualization, but not constrained by Argo's post-execution artifact upload model to make this work. We could potentially export a new set of APIs in APIServer that containers are free to use if they wish to record statuses to be displayed in our UI.

**Comment by jessiezcc** [comment]
Renmin, can u evaluate how much the cost of this work?

**Comment by Bobgy** [comment]
> If a step has submitted a job to Cloud AI Platform training/serving, or is running a Dataflow job, we should be able to parse the logs in the UI and find the relevant URL that points to the relevant job link on GCP. We should then show this link to the user in the KFP UI when she clicks on the relevant pipeline step.

I think current pipeline markdown visualization with links to created resources is a good way to do that in each component's implementation already. WDYT?

> In the long term, we should also explore exposing capabilities to the container to do real-time reporting of arbitrary key-value statuses, which will be displayed in the UI. Similar to the metadata produced for artifact visualization, but not constrained by Argo's post-execution artifact upload model to make this work. We could potentially export a new set of APIs in APIServer that containers are free to use if they wish to record statuses to be displayed in our UI.

I like the idea.

**Comment by rmgogogo** [comment]
My understanding is that we can close this ticket, SG?

**Comment by rmgogogo** [comment]
pantheon log link, CMLE link, Dataproc link are all done.
