### ISSUE TITLE
Improvements to metadata pages in UI

### ISSUE THREAD

**Issue by neuromage** [kubeflow/pipelines#2086]
Now that metadata pages are in KFP's UI thanks to Riley's work, there are still a few more items to take care of in terms of polish:

* We should add a column showing the creation time of each artifact. In order to get this, we'll need to query the metadata API server for events, and find the associated event that produced any given artifact. The event will have a timestamp.

* The list of executions page seems a little buggy. When I click on an execution, the first one in the group (they are grouped by pipeline) works, but the following items don't seem to be working.

* For each execution, other than properties, we should also show the inputs and outputs that went into it. It would also be nice to be able to link to the said input and output.

Assigning to Yuan to start work on this. I'll update this issue with any other outstanding items I find. Yuan, we can also chat in person to clarify these items as required. Thanks!

/assign @Bobgy 

/cc @jessiezcc 
/cc @paveldournov 
/cc @dushyanthsc 
/cc @gaoning777

**Comment by neuromage** [comment]
For reference, here's a simple pipeline you can run (it's using TFX DSL) which will output some basic metadata in your cluster:

```
import argparse
import os
import tensorflow as tf

from typing import Text

import kfp
from tfx.components.evaluator.component import Evaluator
from tfx.components.example_gen.csv_example_gen.component import CsvExampleGen
from tfx.components.example_validator.component import ExampleValidator
from tfx.components.model_validator.component import ModelValidator
from tfx.components.pusher.component import Pusher
from tfx.components.schema_gen.component import SchemaGen
from tfx.components.statistics_gen.component import StatisticsGen
from tfx.components.trainer.component import Trainer
from tfx.components.transform.component import Transform
from tfx.orchestration import metadata
from tfx.orchestration import pipeline
from tfx.orchestration.kubeflow import kubeflow_dag_runner
from tfx.proto import evaluator_pb2
from tfx.utils.dsl_utils import csv_input
from tfx.proto import pusher_pb2
from tfx.proto import trainer_pb2
from tfx.extensions.google_cloud_ai_platform.trainer import executor as ai_platform_trainer_executor

_output_bucket = 'gs://your-bucket-here'

def _create_test_pipeline(pipeline_name: Text, pipeline_root: Text,
                          csv_input_location: Text, taxi_module_file: Text)
  """Creates a simple Kubeflow-based Chicago Taxi TFX pipeline for testing.

  Args:
    pipeline_name: The name of the pipeline.
    pipeline_root: The root of the pipeline output.
    csv_input_location: The location of the input data directory.
    taxi_module_file: The location of the module file for Transform/Trainer.
    container_image: The container image to use.

  Returns:
    A logical TFX pipeline.Pipeline object.
  """
  examples = csv_input(csv_input_location)

  example_gen = CsvExampleGen(input_base=examples)
  statistics_gen = StatisticsGen(input_data=example_gen.outputs.examples)
  infer_schema = SchemaGen(
      stats=statistics_gen.outputs.output, infer_feature_shape=False)
  validate_stats = ExampleValidator(
      stats=statistics_gen.outputs.output, schema=infer_schema.outputs.output)
  transform = Transform(
      input_data=example_gen.outputs.examples,
      schema=infer_schema.outputs.output,
      module_file=taxi_module_file)
  trainer = Trainer(
      module_file=taxi_module_file,
      transformed_examples=transform.outputs.transformed_examples,
      schema=infer_schema.outputs.output,
      transform_output=transform.outputs.transform_output,
      train_args=trainer_pb2.TrainArgs(num_steps=10000),
      eval_args=trainer_pb2.EvalArgs(num_steps=5000))
  model_analyzer = Evaluator(
      examples=example_gen.outputs.examples,
      model_exports=trainer.outputs.output,
      feature_slicing_spec=evaluator_pb2.FeatureSlicingSpec(specs=[
          evaluator_pb2.SingleSlicingSpec(
              column_for_slicing=['trip_start_hour'])
      ]))
  model_validator = ModelValidator(
      examples=example_gen.outputs.examples, model=trainer.outputs.output)
  pusher = Pusher(
      model_export=trainer.outputs.output,
      model_blessing=model_validator.outputs.blessing,
      push_destination=pusher_pb2.PushDestination(
          filesystem=pusher_pb2.PushDestination.Filesystem(
              base_directory=os.path.join(pipeline_root, 'model_serving'))))

  return pipeline.Pipeline(
      pipeline_name=pipeline_name,
      pipeline_root=pipeline_root,
      components=[
          example_gen, statistics_gen, infer_schema, validate_stats, transform,
          trainer, model_analyzer, model_validator, pusher
      ],
      enable_cache=False,  # Or True to use cache
  )


if __name__ == '__main__':
  # Copy sample CSV file from chicago taxi pipeline example to this location
  data_root = 'gs://your-bucket/data' 
  taxi_module_file = 'gs://your-bucket/taxi_utils.py'

  pipeline_name = 'kubeflow-simple-taxi-metadata'
  pipeline_root = 'gs://your-bucket/test'
  pipeline = _create_test_pipeline(pipeline_name, pipeline_root, data_root,                                  taxi_module_file)
  config = kubeflow_dag_runner.KubeflowRunnerConfig()

  kubeflow_dag_runner.KubeflowDagRunner(config=config).run(pipeline)
```

**Comment by Bobgy** [comment]
Thanks @neuromage! I'm taking a day off today and will start on these tomorrow.

Can you send me a reference to MLMD api?
Is frontend codebase here: https://github.com/kubeflow/metadata/tree/master/frontend?
or already in KFP repo?

**Comment by Bobgy** [comment]
@neuromage How do you deploy pipeline with metadata?
I tried kfp lite, it has some errors of missing 'mysql-credential' when starting up metadata server.
Should I use helm to deploy the marketplace one?

**Comment by dushyanthsc** [comment]
@Bobgy The mysql credentials are picked up using K8 secret object. Basically create a Kubernetes Secret object named - "mysql-credential" with keys- "username" and "password" rest should be automatically be taken care of

**Comment by neuromage** [comment]
Thanks @Bobgy!

> * Can you send me a reference to MLMD api?
Yes, here it is: https://github.com/google/ml-metadata/blob/master/ml_metadata/proto/metadata_store_service.proto

> * Is frontend codebase here: https://github.com/kubeflow/metadata/tree/master/frontend? or already in KFP repo?
It's in the KFP repo (kubeflow/pipelines) under /frontend

**Comment by Bobgy** [comment]
> The list of executions page seems a little buggy. When I click on an execution, the first one in the group (they are grouped by pipeline) works, but the following items don't seem to be working.

@neuromage Can you explain what is expected behavior of execution list page?
This is what I can see now: https://drive.google.com/file/d/1LJbth1bK-_ZCTe5d60M8nDRzrFjgux-n/view
* What should happen when we click on expanded rows?
* When we click on the first row, it should open execution detail page right? I will try to fix this.

> For each execution, other than properties, we should also show the inputs and outputs that went into it. It would also be nice to be able to link to the said input and output.

Do we need this in execution list page or detail page, (or both)?

**Comment by neuromage** [comment]
Thanks @Bobgy !

* For name, yeah, that looks wrong. Can we use component_id for the name instead?
* For execution inputs/outputs, I think it's ok to put it in the execution details page. Unfortunately, there is no mock for this, so I'll leave it up to you on how best to implement. I imagine a simple section for inputs, with a listing of Artifact name and id would be great. If the id is deep-linked to the artifact detail page, that would be nice too. Similarly for output.

**Comment by Bobgy** [comment]
@neuromage thanks a lot!
* Sure, I will use component_id instead
* Then I will use my own judgement about that.

**Comment by neuromage** [comment]
@Bobgy I have a few more requests :-)

* Can we show URIs in the artifact detail page? 
* Can we make GCS URIs clickable, in both artifact detail page and artifact listings page?
* If a field has serialized json, can we attempt to parse and pretty print this? 
* The execution list still does not show the name of the execution, and I'm unable to click on any execution except the first one still (ignore if you already fixed this)

Stretch goal, which I think we can discuss and track in a separate issue if needed: show a preview for each artifact type. How we preview would be based on the type of the artifact. For example, if it's a SchemaPath, we can show the schema text proto as JSON or something. If it's ExamplesPath, we can show the first 10 rows maybe. This could use ajchili's visualization server. This may need some in depth discussion, so feel free to schedule something on my calendar.

**Comment by Bobgy** [comment]
@neuromage 

> Can we show URIs in the artifact detail page?
SG, will do so
> Can we make GCS URIs clickable, in both artifact detail page and artifact listings page?
I need to investigate, which page should it link to? A page on google cloud console?
> If a field has serialized json, can we attempt to parse and pretty print this?
SG, will do so.
> The execution list still does not show the name of the execution, and I'm unable to click on any execution except the first one still (ignore if you already fixed this)
Already fixed in https://github.com/kubeflow/pipelines/pull/2135, I think it didn't make it to the version you tested.

**Comment by Bobgy** [comment]
@neuromage regarding the stretch goal, can you create a separate issue for this? What would be the priority? I have other p0 issues on hand, so I will only be able to take a look after other things.

**Comment by neuromage** [comment]
> I need to investigate, which page should it link to? A page on google cloud console?

Yes, a page showing the bucket on Pantheon would be great. Thanks!

**Comment by Bobgy** [comment]
@neuromage Do you think if there are further gaps in UI that should be p0? Shall we close this and make another dedicated issue for tracking the stretch goal?

**Comment by neuromage** [comment]
Yes, this looks great now, thanks @Bobgy!
