### ISSUE TITLE
"Manifest" tab in RunDetails view is often blank

### ISSUE THREAD

**Issue by mattnworb** [kubeflow/pipelines#2090]
**What happened:**

This is perhaps more a question or just something that is unclear, but the "Manifest" tab seems to be always blank - I would have expected this to display the Pod that the component/step ran as in YAML or another format, based on the name and label:

![image](https://user-images.githubusercontent.com/113840/64734515-c2dd5e00-d4b4-11e9-96ce-8f19f1b5f3b6.png)

**What steps did you take:**
- Launch a pipeline run, for example the `[Sample] Basic - Conditional execution` pipeline
- once it has succeeded, open any step that has run
- view the empty Manifest tab

**Anything else you would like to add:**
Just for reference, what is the tab meant to display?

**Comment by mattnworb** [comment]
The workflow from the example pipeline run in the above screenshot is https://ghe.spotify.net/gist/mattbrown/b78b415ad91cac0f5c7424c22501488b

From viewing the source in Chrome's inspector, it seems like the workflow node fails this check (there is no `.resource` value):

https://github.com/kubeflow/pipelines/blob/812ca7f8836c47039c3b1f3daf23e68fbcee1a92/frontend/src/lib/WorkflowParser.ts#L210-L212

**Comment by neuromage** [comment]
/assign @Bobgy 

Yuan, would you mind taking a look at this one?

**Comment by mattnworb** [comment]
Looking at the Git history of `getNodeManifest()` in WorkflowParser.ts more, it seems like the code might be meant to only be used in displaying details about a volume related to the pod/component, as opposed to displaying the general purpose pod manifest?

**Comment by Bobgy** [comment]
Makes sense to me to hide this tab if it's not `ResourceOp`.

/priority p2
/area front-end

**Comment by Bobgy** [comment]
/close
This will be tracked in https://github.com/kubeflow/pipelines/issues/3033
