### ISSUE TITLE
idea: display component's Pod as YAML in RunDetails view of frontend

### ISSUE THREAD

**Issue by mattnworb** [kubeflow/pipelines#2094]
Related to #2090, I think it would be very helpful for troubleshooting if the "RunDetails" view when clicking on a component in the UI would show the manifest for the k8s Pod (i.e. PodSpec, PodStatus) that the component runs as.

I know that the current view in the frontend has access to the Argo workflow object, I am not sure if it has the same level of access to the Pod objects itself - but wanted to create this issue to discuss the idea to see how useful it might be before trying to go off and implement it.

**Comment by Bobgy** [comment]
I also think this would be very useful for debugging. Bumping priority
