### ISSUE TITLE
pipeline apisever pod failed :Please specify flag "ML_PIPELINE_VISUALIZATIONSERVER_SERVICE_HOST"

### ISSUE THREAD

**Issue by xauthulei** [kubeflow/pipelines#2101]
I have used the latest pipeline source : 
```
~/llhu/pipelines/viewerCrdControllerImage/pipelines/backend# kubectl logs ml-pipeline-68d4c6df7d-fwhh7  -n kubeflow
I0907 04:44:36.152338       8 client_manager.go:128] Initializing client manager
[mysql] 2019/09/07 04:44:36 packets.go:427: busy buffer
[mysql] 2019/09/07 04:44:36 packets.go:408: busy buffer
E0907 04:44:36.272021       8 default_experiment_store.go:73] Failed to commit transaction to initialize default experiment table
[mysql] 2019/09/07 04:44:36 packets.go:427: busy buffer
[mysql] 2019/09/07 04:44:36 packets.go:408: busy buffer
E0907 04:44:36.274499       8 db_status_store.go:71] Failed to commit transaction to initialize database status table
[mysql] 2019/09/07 04:44:36 packets.go:427: busy buffer
[mysql] 2019/09/07 04:44:36 packets.go:408: busy buffer
E0907 04:44:36.280634       8 default_experiment_store.go:73] Failed to commit transaction to initialize default experiment table
I0907 04:44:36.293984       8 client_manager.go:279] We already own mlpipeline
I0907 04:44:36.294017       8 client_manager.go:284] Successfully created bucket mlpipeline
I0907 04:44:36.298782       8 client_manager.go:159] Client manager initialized successfully
I0907 04:44:36.301229       8 main.go:156] Samples already loaded in the past. Skip loading.
I0907 04:44:36.301712       8 resource_manager.go:686] Default experiment already exists! ID: febe7a3c-ff67-4231-afdf-89737366d0c8
I0907 04:44:36.301759       8 main.go:103] Starting Http Proxy
I0907 04:44:36.301886       8 main.go:75] Starting RPC server
F0907 04:44:36.302208       8 config.go:28] **Please specify flag** **ML_PIPELINE_VISUALIZATIONSERVER_SERVICE_HOST**
```
and I saw that we have added the new [Dockerfile.visualization](https://github.com/kubeflow/pipelines/blob/master/backend/Dockerfile.visualization),  I thought we should added this `manifests` so that we could install it by kfctl. Am I right ?

**Comment by ajchili** [comment]
Hey @xauthulei, I had not realized that `manifests` would also require updates when introducing the visualization service, thanks for the issue. I will talk with @IronPan offline to get a fix deployed. It seems like we only need to add YAML configuration files to `manifests`.

**Comment by xauthulei** [comment]
Thanks @ajchili,  That 's great, I will try to do some test in my local, when your fixes merged.

**Comment by ajchili** [comment]
Hey @xauthulei, the fix was merged!

**Comment by xauthulei** [comment]
@ajchili , Thanks, I will test it many thanks.

**Comment by xauthulei** [comment]
@ajchili ,  I am still get the same error :
```
F0907 04:44:36.302208       8 config.go:28] **Please specify flag** **ML_PIPELINE_VISUALIZATIONSERVER_SERVICE_HOST**
```
I have deployed the service:
```
~/llhu/pipelines# kubectl get pod -n kubeflow | grep visualizationserver
ml-pipeline-ml-pipeline-visualizationserver-855796c589-s6wnr   1/1       Running             0          36m
~/llhu/pipelines# kubectl get svc  -n kubeflow  | grep visualiza
ml-pipeline-ml-pipeline-visualizationserver   ClusterIP   10.0.0.220   <none>        8888/TCP            36m
```

**Comment by jlewi** [comment]
Here's the docker file for the backend server
https://github.com/kubeflow/pipelines/blob/master/backend/Dockerfile

It looks like the Dockerfile is hardcoding the use of a config file baked into the docker image.
The config file is specified here.
https://github.com/kubeflow/pipelines/blob/master/backend/src/apiserver/config/config.json

That config flag doesn't appear to be specifying ML_PIPELINE_VISUALIZATIONSERVICE_HOST which I suspect is the problem.

**Comment by jlewi** [comment]
@xauthulei @ajchili I have a draft PR https://github.com/kubeflow/manifests/pull/392 that appears to fix this issue by updating the config to set the visualization server host and port.  It looks like there is still more work to be done to get the manifest updated. Right now with that PR the UI is making requests to 

Cannot POST /ml_metadata.MetadataStoreService/GetArtifacts

And that is failing

**Comment by IronPan** [comment]
The service host/port environment variable should be auto populated to API server pod and doesn't need to be injected through pipeline API server config file thus this should not be necessary https://github.com/kubeflow/manifests/pull/392/files#diff-887500ac1090b63dfc98e7589e1a070a

I suspect the manifests didn't include visualisation server. The deployment from KF pipeline-lite deployment is working fine https://github.com/kubeflow/pipelines/tree/master/manifests/kustomize/base/pipeline so I suspect there are something missing in here https://github.com/kubeflow/manifests/tree/master/pipeline
