### ISSUE TITLE
Add e2e test for the component build(use multiple output sample)

### ISSUE THREAD

**Issue by gaoning777** [kubeflow/pipelines#2109]
This issue is to track adding a sample test for the component build(func_to_containerop).
Currently we have a sample https://github.com/kubeflow/pipelines/tree/master/samples/core/multiple_outputs, which uses the build_python_component function. We can convert it to use the new func_to_containerop and add the test to the e2e.

**Comment by gaoning777** [comment]
https://github.com/kubeflow/pipelines/tree/master/samples/core/component_build

**Comment by gaoning777** [comment]
https://github.com/kubeflow/pipelines/issues/1813

**Comment by gaoning777** [comment]
multiple_output sample is not tested, yet

**Comment by Ark-kun** [comment]
> multiple_output sample is not tested, yet

Tracking that in https://github.com/kubeflow/pipelines/issues/2208
Also https://github.com/kubeflow/pipelines/issues/2209 https://github.com/kubeflow/pipelines/issues/2210

**Comment by gaoning777** [comment]
Is the func_to_container_op conversion necessary for the tests?

**Comment by Ark-kun** [comment]
> Is the func_to_container_op conversion necessary for the tests?

It's not necessary. I was just going with what you put in the description of this issue: "We can convert it to use the new func_to_containerop and add the test to the e2e.".

**Comment by gaoning777** [comment]
SGTM. Let's add the test first then.

**Comment by Ark-kun** [comment]
@gaoning777 Should we close this issue since both samples are now covered by sample tests?
