### ISSUE TITLE
Support pipeline run events

### ISSUE THREAD

**Issue by robin5540** [kubeflow/pipelines#2120]
### Background

Currently the only way to get pipeline run state transitions is by polling the api server.

Could we add a plug-in layer in the persistent agent that will allow publishing these transitions as a stream of events. AWS can have a SNS plug-in, GCP pub/sub, etc.

**Comment by jessiezcc** [comment]
great idea, looking for community help

**Comment by robin5540** [comment]
I'll put in a PR
