### ISSUE TITLE
Feature request: Ability provide hint/help in UI for all the parameters in drop-down menu? 

### ISSUE THREAD

**Issue by Akashdesarda** [kubeflow/pipelines#2124]
Ability to provide brief hint/help about that particular parameter in UI like the '--help' in argument parser.

**Comment by Ark-kun** [comment]
Are you talking about pipeline parameters?

**Comment by Akashdesarda** [comment]
YES

**Comment by Ark-kun** [comment]
Do you have any python syntax in mind on how to specify the pipeline parameter descriptions?

**Comment by rmgogogo** [comment]
Track here: https://github.com/kubeflow/pipelines/issues/2621
Close this one.
