### ISSUE TITLE
Type checking is enforced when output names are not with underscore

### ISSUE THREAD

**Issue by post2web** [kubeflow/pipelines#2130]
**What happened:**
When a pipeline is compiled with components that have input/output names with spaces, the type checking doesn't work as expected.

**What did you expect to happen:**
The pipeline should throw an `InconsistentTypeException` exception because types of input and output don't match.

**What steps did you take:**
Install KFP: `pip3 install kfp==0.1.30 --upgrade`

Compile a pipeline:
```python
import kfp

data_component = kfp.components.load_component_from_text("""
outputs:
    - {name: Output Data, type: String}
implementation:
  container:
    image: ubuntu
    args: []
    fileOutputs: 
      Output Data: /tmp/data.txt
""")

trainer_component = kfp.components.load_component_from_text("""
inputs:
    - {name: Data, type: GcsUri}
implementation:
  container:
    image: ubuntu
    args: [
      --data, {inputValue: Data}
    ]
""")

@kfp.dsl.pipeline(name='test', description='')
def pipeline_fn():
    data = data_component()
    trainer_component(data=data.outputs['output_data'])
    
kfp.compiler.Compiler().compile(pipeline_fn, '/tmp/pipeline.tar.gz')
```

The above snippet complies without any issues which isn't expected because the types of input and output don't match. When you modify the name of the `data component` to `output_data` it throw an `InconsistentTypeException` exception as expected:

```python
import kfp

data_component = kfp.components.load_component_from_text("""
outputs:
    - {name: output_data, type: String}
implementation:
  container:
    image: ubuntu
    args: []
    fileOutputs: 
      output_data: /tmp/data.txt
""")

trainer_component = kfp.components.load_component_from_text("""
inputs:
    - {name: Data, type: GcsUri}
implementation:
  container:
    image: ubuntu
    args: [
      --data, {inputValue: Data}
    ]
""")

@kfp.dsl.pipeline(name='test', description='')
def pipeline_fn():
    data = data_component()
    trainer_component(data=data.outputs['output_data'])
    
kfp.compiler.Compiler().compile(pipeline_fn, '/tmp/pipeline.tar.gz')
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

I experiance the same issue when name is `output-data` as well.

**Comment by Ark-kun** [comment]
Thank you. I've found and fixed the bug.
As an aside, do you think it would be good idea to have the `task.outputs` dictionary contaihne the original output names, not the "pythonic" versions?
E.g.: `task.outputs['Output data']` instead of `task.outputs['output_data']`

**Comment by post2web** [comment]
I think task.outputs should use the "pythonic" versions e.g. `task.outputs['output_data']`

**Comment by Ark-kun** [comment]
> I think task.outputs should use the "pythonic" versions e.g. `task.outputs['output_data']`

Ok.
I also though about using the original names in the dict, but also adding pythonic attributes:
`task.outputs.output_data == task.outputs['Output data']`

**Comment by post2web** [comment]
Yes, I like that attribute and key rule. It will be similar to working with column names in pandas.
