### ISSUE TITLE
Tensorboard failed to visualize embedding

### ISSUE THREAD

**Issue by randxie** [kubeflow/pipelines#2131]
**What happened:**
The tensorboard UI failed to render embedding. It will get frozen with "computing PCA" and then the page becomes unresponsive.
![failed](https://user-images.githubusercontent.com/10520307/64982855-ff71d680-d873-11e9-98a9-068c83a378eb.png)

**What did you expect to happen:**
Here's a normal tensorboard output.
![expected](https://user-images.githubusercontent.com/10520307/64982899-1dd7d200-d874-11e9-9e45-92bb0fe30df0.png)

**What steps did you take:**
I tried to upgrade the tensorboard version in the pod but no luck.

**Comment by neuromage** [comment]
Are you relying on a specific new version of Tensorboard? Can you reproduce the 'freeze' on a local machine using TB 1.11? This is the version we currently deploy in Pipelines:
https://github.com/kubeflow/pipelines/blob/578e8231d01074b9dbe40ace1db8cc444a6a1bd8/backend/src/crd/controller/viewer/reconciler/reconciler.go#L168

/cc @jingzhang36

**Comment by randxie** [comment]
Hi @neuromage , thanks for pointing me to the image version. I downgraded my tensorflow version to 1.11 and was able to reproduce the error. Looks like such visualization requires TF 1.13.

**Comment by neuromage** [comment]
Ah ok makes sense. I think we can upgrade our TB version. 
@jingzhang36 do you foresee any issues with this? If not, I'll go ahead and send a PR out in the morning.

**Comment by jingzhang36** [comment]
@neuromage Thanks for looking into this! Please go ahead with the version bump.

**Comment by randxie** [comment]
Btw, is there a way we can upgrade the tensorboard version in an existing cluster?

**Comment by jessiezcc** [comment]
@randxie, can you pls close this issue since it seems the issue is being resolved.
