### ISSUE TITLE
TFX sample failed at kf-serve-tf-model step

### ISSUE THREAD

**Issue by IronPan** [kubeflow/pipelines#2139]
![image](https://user-images.githubusercontent.com/2348602/65026744-be5ced80-d96b-11e9-9185-e3471e13b7d2.png)

This happens when I'm deploying KFP in non "kubeflow" namespace. 
The serve component might hard coded ns somewhere.

**Comment by numerology** [comment]
Observed a similar issue when trying [KF TF serving sample](https://github.com/kubeflow/pipelines/tree/master/samples/core/kubeflow_tf_serving)

**Comment by gaoning777** [comment]
we currently have the kf serving sample tests. Does it still exist? @IronPan

**Comment by gaoning777** [comment]
If it is reproducible, feel free to reopen.
