### ISSUE TITLE
Sample test infra: inconsistent behavior of dynamically injected arguments for output and experiment_name

### ISSUE THREAD

**Issue by gaoning777** [kubeflow/pipelines#2148]
The current behavior is:
The output argument is injected for both normal python sample and notebook sample when it is specified in the config yaml. 
The experiment_name is only injected for notebook samples and will be injected even though it is not specified in the config yaml.

Expected behavior:
Both are injected only when they are specified in the config yaml. Since the assumption is that the notebook submits a job programmatically while the python samples do not, experiment_name arg will not be for notebook samples.

**Comment by gaoning777** [comment]
@numerology any updates?

**Comment by numerology** [comment]
Made a PR, PTAL

**Comment by numerology** [comment]
FYI, @Ark-kun  made PR #2292 that might help this

**Comment by Ark-kun** [comment]
https://github.com/kubeflow/pipelines/pull/2292 removes the need for injecting the `experiment_name` (and also makes it consistent between notebooks and python samples).

It might be possible to fix the output issue by using placeholders (e.g. `kfp.dsl.RUN_ID_PLACEHOLDER`) or digging into the workflow status.

**Comment by gaoning777** [comment]
After the #2292, the behavior is:
The output argument is injected for both normal python sample and notebook sample only when it is specified in the config yaml.
The experiment_name is not injected at all. The SDK uses the 'default' namespace if not specified.
