### ISSUE TITLE
Our tests fail on external PRs

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#215]
See the failing tests in these PRs:
https://github.com/kubeflow/pipelines/pull/164
https://github.com/kubeflow/pipelines/pull/212

The root cause: image builders fail, because they try to check-out the PR's commit themselves and fail to do so. I've written about a long-term solution to this problem in https://github.com/kubeflow/pipelines/issues/200 

Note that this issue is **not** caused by #165 . This problem existed even in our private repo. (See https://github.com/googleprivate/ml/pull/1535)
Truth is #165 makes a step in the direction of short-term fixing this, but it's only half way there. 

As short term fix would be to add `git fetch https://github.com/<fork_org>/<fork_repo>.git <fork_branch>` before the merge.

**Comment by vicaire** [comment]
@Ark-kun, could you please provide more details? Why do the test fail on external PRs? 

Note that tests should ideally not be automatically triggered on external PR.

**Comment by vicaire** [comment]
Assuming that this is resolved.

**Comment by Ark-kun** [comment]
Fixed by #315
