### ISSUE TITLE
Pipelines dashboard: Error occured while trying to proxy to: localhost:31380/apis/v1beta1/experiments

### ISSUE THREAD

**Issue by cyrilthank** [kubeflow/pipelines#2154]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
after completing the installation and setup steps in
 https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/

i get the below error for accessing any links on the centraldashboard

Error occured while trying to proxy to: localhost:31380/apis/v1beta1/experiments

**What did you expect to happen:**

The  links to work and create experiment/create run/create pipeline

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`):
kfctl v0.6.2-0-g47a0e4c7
- Kubernetes platform: (e.g. `minikube`)
- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from `/etc/os-release`):
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by jessiezcc** [comment]
@cyrilthank, can you pls check whether ssh or IAP is enabled?

**Comment by cyrilthank** [comment]
@jessiezcc  you are right ssh was not installed but I have ever since scrapped the environment

can you please share the document where I can find the step listed so I can try in new environment
