### ISSUE TITLE
Show small artifacts in UX inputs/outputs

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#2172]
Currently the UX run node details page only shows the values of the input/output parameters.
That page should also show small artifacts.
For each artifact, frontend should query the size and if it's less than, say, 1KiB, then the data should be downloaded, optionally unpacked and then shown in the same list. If the data size is bigger then the UX could show the size and optionally a download link.

So this run detail page should look the same (or better) regardless of whether outputs are artifacts or parameters:

![image](https://user-images.githubusercontent.com/1829149/65366142-e8fdaf00-dbd4-11e9-9903-c69198357ae8.png)

**Comment by Ark-kun** [comment]
@eterna2 What do you think?

**Comment by eterna2** [comment]
Sure I can have a look at this.

**Comment by eterna2** [comment]
@Ark-kun 
hey i was looking at the codes. There are a few ways I can see how this can be done:

### purely front-end
front-end consumes the run data, and makes artifact requests if it detects that the parameters are artifacts.

### purely back-end (node)
hijack the response from the proxied run request, and scan for artifacts (and their size) and return an updated response.

**Comment by Ark-kun** [comment]
Which one would be easier for you to implement? The artifact requests should probably come from the node backend (is that how it's done today?).

**Comment by rmgogogo** [comment]
Hi Alex, I turn to P2. Is it a request from customer?
I assume we may invest more on MLMD based artifacts. Correct me.

**Comment by Ark-kun** [comment]
> Hi Alex, I turn to P2. Is it a request from customer?
> I assume we may invest more on MLMD based artifacts. Correct me.

Yes. There were multiple reports from people that they no longer see the pipeline outputs in the UX. The issue talks about bringing back that functionality.
Judging by the user feedback, for now they find the existing UX more useful as the data actually shows there and they can see the data by just clicking on the graph node.

**Comment by eterna2** [comment]
My 2 cents. I was trying to get my team to start using metadata store in v0.6. 

Seems overly complicated. As I need to create workspace -> run -> execution
For each step before I can even start registering the dataset, models, and metrics.

Would be nice to have a function to decorate an op on what to log in a pipeline level workspace/run.

Or am I doing it wrong?

**Comment by Ark-kun** [comment]
> Seems overly complicated. As I need to create workspace -> run -> execution
> For each step before I can even start registering the dataset, models, and metrics.
> 
> Would be nice to have a function to decorate an op on what to log in a pipeline level workspace/run.
> 
> Or am I doing it wrong?

I get your feedback. For now the Metadata DB is only populated by several TFX components and requires using the TFX runner.

I had experimented with enabling metadata logging for normal KFP pipelines. You can add your feedback and thumb-up this: https://github.com/kubeflow/pipelines/issues/2604

**Comment by Bobgy** [comment]
It seems there's no longer a clear need in this.
/close
If someone feels this is useful, please reopen

**Comment by Ark-kun** [comment]
>It seems there's no longer a clear need in this.

I think this remains useful. There is a regression where the users were previously seeing the output values, but now only see the URIs (clickable).

**Comment by Bobgy** [comment]
Thanks! Then I bumped to p1 and added to kfp 1.0 plan.

**Comment by Bobgy** [comment]
Hi @eterna2! Do you have plan to continue the UI implementation?
We are wrapping up on KFP 1.0 release. So we'd need to decide if this can be part of it or not.

If you don't have bandwidth, I may try to find if I can have enough time on this.

**Comment by eterna2** [comment]
Ok. I will get a PR out by end of this week.

**Comment by Bobgy** [comment]
@eterna2 Awesome, super thanks!

**Comment by Ark-kun** [comment]
Implemented by @eterna2 https://github.com/kubeflow/pipelines/pull/3707
