### ISSUE TITLE
[Components/GCP] Dedicated visualization component using customized metadata

### ISSUE THREAD

**Issue by numerology** [kubeflow/pipelines#2177]
Context #1913 .
In the XGBoost training sample, we rely on component file_output to pass metadata and information around, which is not trivially support in the new GCP component, which only support default UI metadata output and job ID output.

A possible solution to this gap is to create a dedicated GCP visualization component digesting customized metadata (possibly in a json format). Before that, the new version of XGBoost sample using GCP component will be without visualization.

**Comment by Ark-kun** [comment]
The XGBoost training component is different from the generic "PySpark" component even if one can be implemented on top of another. "PySpark" runs arbitrary code while "XGBoost" performs model training.  They do different operations with different data signatures and thus should be separate components.

"XGBoost" component could be switched to use the PySpark code for execution of its code though. But this is implementation detail and users should not care about how "XGBoost" is implemented.

The same is true for most of the "launcher-style" "components" - pyspark, CMLE, TFJob, Katib, etc.

We could design some generic support for launchers in the SDK.
