### ISSUE TITLE
Let user choose the version of Tensorboard deployed by UI

### ISSUE THREAD

**Issue by neuromage** [kubeflow/pipelines#2185]
We should allow the user to manually customize the version of Tensorboard deployed by the UI, defaulting to latest. This will let them easily get around bugs like that in #2140 

/assign @jingzhang36
 to take a first stab or re-assign as needed.

**Comment by Bobgy** [comment]
/close
duplicate of https://github.com/kubeflow/pipelines/issues/2514
and already resolved in https://github.com/kubeflow/pipelines/pull/2690
