### ISSUE TITLE
[Frontend] Server Testing - test infra for pipeline ui node server

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#2215]
Pipeline UI node server has 0 test coverage at the moment. It prevents adding new features into the node server with confidence. In order to test more nuanced features like added in #2081.

We should add
* (lower effort, lower confidence) some basic jest tests that just test the node server
* (higher effort, higher confidence) some e2e tests that test the node server with a real cluster

Starting with jest tests would be the best

Work Items:
* [x] (p0) test infra and unit tests, thanks @eterna2 https://github.com/kubeflow/pipelines/pull/2745
* [x] (p0) set up coverage reporting https://github.com/kubeflow/pipelines/pull/2877
* [x] (p1 0.2w) Finish k8s-helper unit tests: https://github.com/kubeflow/pipelines/blob/2ec2fd23c51caafd66de4478ea874633c3292666/frontend/server/app.test.ts#L354 fixed together in https://github.com/kubeflow/pipelines/pull/3304
* [ ] (p2 0.6w) Unit tests for low coverage files according to coverage report.

/priority p0
/area testing

**Comment by Ark-kun** [comment]
Can you clarify the e2e tests item? I think we run some frontend tests as part of 2e2 tests.

**Comment by Bobgy** [comment]
I saw there are some UI e2e tests, but I don't think they cover all usages of the node server.
I need to look deeper for a list of things it didn't cover.

**Comment by Bobgy** [comment]
Thanks to @eterna2, https://github.com/kubeflow/pipelines/pull/2745#pullrequestreview-333402262 will be the first step.

**Comment by Bobgy** [comment]
All p0 issues resolved

**Comment by Bobgy** [comment]
The last p2 item of Unit tests for low coverage files according to coverage report can be improved in a separate issue. This one can be considered done.

/close
