### ISSUE TITLE
Remove experiment column from runs list inside experiment

### ISSUE THREAD

**Issue by ajayalfred** [kubeflow/pipelines#222]
The experiment column is unnecessary as it provides redundant information. Remove from runs list inside the experiment.

**Comment by vicaire** [comment]
@rileyjbauer, has this already been implemented? Can we close?

**Comment by rileyjbauer** [comment]
This has not yet been fixed at this time. It should be a very easy fix.

**Comment by rileyjbauer** [comment]
This was fixed in #1144
