### ISSUE TITLE
KFP SDK fails in sample with syntax error: "TypeError: pop() takes no keyword arguments"

### ISSUE THREAD

**Issue by axelmagn** [kubeflow/pipelines#2225]
**What happened:**

Environment:  I am running a v0.6.2 Kubeflow cluster on GKE, deployed via [the UI](https://deploy.kubeflow.cloud/#/deploy).

I was running through the component build sample (`samples/core/component_build/component_build.ipynb`), which I had uploaded to my kubeflow cluster.  When I got to the step "Build a Component With the Above Function", execution failed with the following error:

```
2019-09-24 21:38:49:INFO:Build an image that is based on google/cloud-sdk:latest and push the image to gcr.io/saltierl-policy/component:latest
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-c8afb6891cdc> in <module>
      6     dependency=[kfp.compiler.VersionedDependency(name='google-api-python-client', version='1.7.0')],
      7     base_image=BASE_IMAGE,
----> 8     target_image=TARGET_IMAGE)

/opt/conda/lib/python3.6/site-packages/kfp/compiler/_component_builder.py in build_python_component(component_func, target_image, base_image, dependency, staging_gcs_path, timeout, namespace, target_component_file, python_version)
    224   # After:  python3 -u main.py --param1 ...
    225   command_line_args[program_code_index] = program_container_path
--> 226   command_line_args.pop(index=dash_c_index)
    227 
    228   if python_version == 'python2':

TypeError: pop() takes no keyword arguments
```

![image](https://user-images.githubusercontent.com/1660665/65553884-ca512e00-dedc-11e9-93c1-7ea692bb3202.png)

**What did you expect to happen:**
Cell to execute successfully.

**What steps did you take:**
1. Set up a GKE Kubeflow cluster v0.6.2
2. Create a notebook server within the cluster (Tensorflow 2.0.0 CPU)
3. Upload the "core/component_build" sample notebook to the notebook server
4. Execute cells in sample notebook sequentially.

**Anything else you would like to add:**
Nothing at this time.

**Comment by Ark-kun** [comment]
Sorry about this bug. It has already been fixed in SDK v0.1.31. https://github.com/kubeflow/pipelines/issues/2108 https://github.com/kubeflow/pipelines/pull/2107
Please upgrade your SDK to fix it:
```shell
pip3 install --upgrade kfp
```

**Comment by Ark-kun** [comment]
BTW, What is the container-building scenario that you want to achieve?
Have you tried the Lightweight components feature - [kfp.components.func_to_container_op](https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.components.html#kfp.components.func_to_container_op) which creates components without building containers.

**Comment by axelmagn** [comment]
Thanks!  I will likely use `func_to_container_op` in my model then.  Right now I am just running through examples to make sure I understand the semantics.

**Comment by janeman98** [comment]
@Ark-kun 

I cannot find `samples/core/component_build/component_build.ipynb`  in master branch anymore. May I know where the new location is? Or it is replaced by [Lightweight python components](https://github.com/kubeflow/pipelines/blob/master/samples/core/lightweight_component/lightweight_component.ipynb)?

**Comment by Ark-kun** [comment]
@janeman98 Yes. The build_python_component had been deprecated in favor of Lightweight python components. Container building APIs have also been upgraded. See the new sample:  https://github.com/kubeflow/pipelines/blob/master/samples/core/container_build/container_build.ipynb
