### ISSUE TITLE
Is there a way to specify namespace for kfp.dsl.ContainerOp ? 

### ISSUE THREAD

**Issue by hemantha-kumara** [kubeflow/pipelines#2235]
I am trying to create a container(pod) which uses pvc which is under other namespace.

```
def create_tf_record_job(vol):
    return dsl.ContainerOp(
        name="tf-record-job",
        image=training:12345",
        pvolumes={mount_path: vol}
    )

tf_volume = k8s_client.V1Volume(
        name="training",        persistent_volume_claim=k8s_client.V1PersistentVolumeClaimVolumeSource(claim_name="training")
    )
```
`create_tf_record_job(tf_volume)`

but problem is by default containerOp is creating a pod in 'kubeflow' namespace but pvc is in another namespace.
is there a way to speciy namespace in containerop ?

**Comment by Ark-kun** [comment]
How would you do this (create pod with volume from other namespace) in plain Kubernetes YAML?

**Comment by hemantha-kumara** [comment]
In kubernetes yaml, we can't do this. Hence I am asking is there any way we can call containerop with namespace. So that I can specify PVC namespace to pod also. Currently pipeline is creating pod only in kubeflow namespace.
________________________________

**Comment by shotarohorai** [comment]
Is there any update on this issue?? @hemantha-kumara  @Ark-kun

**Comment by hemantha-kumara** [comment]
closing this issue as this is invalid. problem is described in https://github.com/kubeflow/pipelines/issues/2858
