### ISSUE TITLE
Consider only re-releasing the envoy container image if upgrading to new version

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#2238]
See https://github.com/kubeflow/pipelines/pull/2201#issuecomment-535221280 for similar observations.

**Comment by Bobgy** [comment]
I've made one implementation for argo and minio. Any feedback -- start with reading https://github.com/kubeflow/pipelines/pull/2201/files#diff-829c80b08fc7a4553b83c4a055a98069?
and then we can apply the same pattern to envoy.

**Comment by rmgogogo** [comment]
https://github.com/kubeflow/pipelines/blob/master/manifests/gcp_marketplace/chart/kubeflow-pipelines/values.yaml#L15

So I assume we can close this ticket. Feel free to correct me and reopen.

**Comment by Ark-kun** [comment]
The issue is about using the envoy's own release schedule and versions as opposed to releasing a new envoy image every week with the KFP images.

**Comment by Bobgy** [comment]
Hi @Ark-kun, our envoy image also contains our **non-trivial** config. I think it make more sense to consider the image to contain our code. Thus it should be released per our release cycle. https://github.com/kubeflow/pipelines/blob/2d4480afff701a4ce269b8fb9a1e7d9415ed6060/third_party/metadata_envoy/Dockerfile#L20

I remember @dushyanthsc also held the same opinion, but I cannot exactly find his comment link now.

**Comment by Ark-kun** [comment]
> Hi @Ark-kun, our envoy image also contains our **non-trivial** config. I think it make more sense to consider the image to contain our code. Thus it should be released per our release cycle.

Oh. I see. That makes sense.

**Comment by Bobgy** [comment]
SG, close since we agreed on this

/close
