### ISSUE TITLE
Update kubeflow/manifests to ship correct version of KFP in 0.7? 1.31

### ISSUE THREAD

**Issue by jlewi** [kubeflow/pipelines#2239]
We are trying to finalize Kubeflow 0.7 by end of month.

Which version of KFP should be shipped in 0.7.

We are currently shipping KFP 0.1.23.
It looks like this is about 1 month old.
It looks like there was a fairly recent release 
0.1.31
https://github.com/kubeflow/pipelines/releases

@IronPan @jessiezcc  Should we ship 0.1.31 in 0.7? Are there additional improvements that we would like to ship in 0.7? If so do we have an ETA for when they will land?

**Comment by jlewi** [comment]
P0 because blocking 0.7.

**Comment by jessiezcc** [comment]
@jingzhang36, should we include version API to .7 release?

**Comment by jingzhang36** [comment]
@jlewi @jessiezcc We are working on a new release 0.1.32. If it can be completed by end of this month, let's use it. Otherwise, we can use 0.1.31. I'll update soon after I get more information on 0.1.32.

**Comment by jingzhang36** [comment]
@jlewi @jessiezcc Update: (1) we can't make version API to kubeflow 0.7 unfortunately. (2) synced with Yuan on his license related change, which doesn't need to be included in kubeflow 0.7. 

So in short, I believe kubeflow 0.7 could just use kfp 0.1.31. 

Thanks!

**Comment by jlewi** [comment]
Thanks @jingzhang36.

@jessiezcc @jingzhang36 @jessiezcc Can someone from KFP update the KFP package in kubeflow/manifests to deploy 0.1.31?

**Comment by jingzhang36** [comment]
@jlewi two things: (1) does kubeflow side has some extra tests we need to do before bumping kfp version (2) I'll do the version change after getting final confirmation from Yang @IronPan

**Comment by jingzhang36** [comment]
@jlewi @jessiezcc I did a quick estimation of the workload and it turns out that this time we'll have to include much more than just kfp server image change. Here are two lists of changes inside KFP that we need to sync to Kubeflow https://github.com/kubeflow/pipelines/commits/master/manifests/kustomize and https://github.com/kubeflow/pipelines/commits/master?after=7735a1469478af0d3f5f24a5d0de908031175337+34&path%5B%5D=manifests. 

Given the number of items that are needed to be synced,  I'll have to put a very generous time estimation on this sync, especially when this is the first time I am doing it.  Moreover, since this sync would be my second priority item (the first is CI and version API), it is unlikely that I can finish all the changes in 4 days before the end of Sept. And from Sept 30, I'll be on an 8 days OOO  until Oct 8.

@jlewi , do you have any concern on the timeline?

**Comment by jlewi** [comment]
@jingzhang36 You might have to run make generate in kubeflow/manifests to regenerate the kustomize tests to pick up the updated image. I don't think we have any specific pipelines tests.

**Comment by jlewi** [comment]
If the update happens after Oct 8 it will likely miss the 0.7 release. Which means we would just continue to ship 0.1.23.

**Comment by jlewi** [comment]
0.1.31 appears to be broken because of #2101

**Comment by jlewi** [comment]
I have a draft PR to upgrade to 0.1.31
https://github.com/kubeflow/manifests/pull/392

It looks like the UI is unable to contact the metadata service for artifacts and executions. Javascript console shows errors like

```
Cannot POST /ml_metadata.MetadataStoreService/GetArtifacts
```

In 0.1.31 is the pipelines UI using gRPC to contact the metadata service? 

Do the manifests need to be updated to create a new virtual service for this endpoint?

Are we going to run into issues trying to communicate from the client to the backend using gRPC? i.e. what if the loadbalancer and ingress don't support gRPC?

@dushyanthsc @neuromage @rileyjbauer  @zhenghuiwang can anyone shed some light here?

**Comment by dushyanthsc** [comment]
My understanding was that UI should still be talking to kf-metadata and the work to port the changes from pipelines is not done yet. Adding @rmgogogo @Bobgy who are also working on metadata UI.

**Comment by neuromage** [comment]
> In 0.1.31 is the pipelines UI using gRPC to contact the metadata service?

Yes, KFP has switched to using the MLMD gRPC server. 

> Do the manifests need to be updated to create a new virtual service for this endpoint?

@dushyanthsc has been working with @zhenghuiwang to update the manifests in KF Metadata so it follows the same setup as well.

> Are we going to run into issues trying to communicate from the client to the backend using gRPC? i.e. what if the loadbalancer and ingress don't support gRPC?

Can you clarify this? Which loadbalance and ingress point are you referring to? Thanks.

**Comment by Bobgy** [comment]
I'd like to confirm what we want to do in KF.

Will we still deploy a metadata-envoy server that proxies from grpc-web to MLMD gRPC server?

If my understanding is right, there won't be UI work for these ports. Is that correct?

**Comment by dushyanthsc** [comment]
With this change - https://github.com/kubeflow/manifests/pull/370  we are deploying - mlmd-grpc (( K8-deployment & service) and envoy(deployment & service) along with the kf-metadata server which means we currently have two mlmd servers running (gRPC & kf-metadata).

**Comment by jlewi** [comment]
@neuromage the error I'm seeing is that the pipelines UI I unable to display artifacts and executions. The call to 

POST /ml_metadata.MetadataStoreService

Is failing.

I believe this request is being issued by client side Javascript.

This means the metadata service needs to be exposed through  the cluster ingress and ISTIO gateway; i.e. we probably need a virtual service adding an appropriate mapping through the gateway.

What is the backend service this request is supposed to be routed to?

Is this request using gRPC or regular http?

If it's using gRPC does that create a risk that the UI will break if people's networking setup doesn't support gRPC.

For example I think GCP L7 load balancer might have added gRPC support only recently.

**Comment by jessiezcc** [comment]
@Ark-kun who is taking over the 0.7 release work on pipeline side

**Comment by Bobgy** [comment]
Let me try to explain how requests are routed. (Please correct me if there's something wrong/inaccurate)

Browser sends HTTP requests encoding gRPC data  using grpc-web library to Frontend node server.
Node server proxies these requests library to metadata-envoy (still in HTTP).
metadata-envoy converts requests to native gRPC and proxies them to metadata-grpc-server.

Does ISTIO gateway only needs to expose those accessed from public? If my understanding is correct, there's no risk. Browser still only talks to the frontend node server. All the extra routing happens in the cluster.

**Comment by Bobgy** [comment]
> With this change - [kubeflow/manifests#370](https://github.com/kubeflow/manifests/pull/370) we are deploying - mlmd-grpc (( K8-deployment & service) and envoy(deployment & service) along with the kf-metadata server which means we currently have two mlmd servers running (gRPC & kf-metadata).

Maybe I'm missing something, why do we still need kf-metadata?

**Comment by neuromage** [comment]
> This means the metadata service needs to be exposed through the cluster ingress and ISTIO gateway; i.e. we probably need a virtual service adding an appropriate mapping through the gateway.
@jlewi 
Sorry, but I'm not sure I understand. The KFP UI is proxying those requests to the gRPC backend via Envoy. By virtual service, do you mean the Envoy proxy config? If so, this is already set up.

> What is the backend service this request is supposed to be routed to?

It goes to the gRPC MLMD server.

> Is this request using gRPC or regular http?

It uses [gRPC-Web](https://github.com/grpc/grpc-web)
 
> If it's using gRPC does that create a risk that the UI will break if people's networking setup doesn't support gRPC.

Sorry, I don't understand this. Whose UI set up would we break?

**Comment by neuromage** [comment]
@Bobgy 
 
> Maybe I'm missing something, why do we still need kf-metadata?

KF-Metadata is the metadata stack, and when we deploy KFP in Kubeflow (not lightweight), we should be using this stack for metadata storage, as well as for reading back metadata in KFP UI. @dushyanthsc's work on bringing the gRPC server + Envoy config in KF Metadata should enable this functionality.

**Comment by jlewi** [comment]
@neuromage and @Bobgy the client is getting a 404

Request URL: https://jlewi-0926-002.endpoints.jlewi-dev.cloud.goog/ml_metadata.MetadataStoreService/GetArtifacts
Request Method: POST
Status Code: 404 

Is this request supposed to be routed to the frontend node server? If it is is there a virtual service that sets up a reverse proxy route for this rule?

I've attached all the virtual services in my cluster. I don't see any routes for /ml_metadata.MetadataStoreService
[allvirtualservices.yaml.txt](https://github.com/kubeflow/pipelines/files/3665919/allvirtualservices.yaml.txt)

Here's a list of all the services in my cluster

```
NAME                                           TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
admission-webhook-service                      ClusterIP   10.11.240.99    <none>        443/TCP             39h
application-controller-service                 ClusterIP   10.11.250.45    <none>        443/TCP             39h
argo-ui                                        NodePort    10.11.255.144   <none>        80:30141/TCP        39h
centraldashboard                               ClusterIP   10.11.253.53    <none>        80/TCP              39h
cloud-endpoints-controller                     ClusterIP   10.11.254.249   <none>        80/TCP              39h
jupyter-web-app-service                        ClusterIP   10.11.241.97    <none>        80/TCP              39h
katib-controller                               ClusterIP   10.11.255.210   <none>        443/TCP             39h
katib-db                                       ClusterIP   10.11.243.190   <none>        3306/TCP            39h
katib-manager                                  ClusterIP   10.11.251.115   <none>        6789/TCP            39h
katib-manager-rest                             ClusterIP   10.11.254.252   <none>        80/TCP              39h
katib-suggestion-bayesianoptimization          ClusterIP   10.11.242.97    <none>        6789/TCP            39h
katib-suggestion-grid                          ClusterIP   10.11.246.253   <none>        6789/TCP            39h
katib-suggestion-hyperband                     ClusterIP   10.11.249.33    <none>        6789/TCP            39h
katib-suggestion-nasrl                         ClusterIP   10.11.245.14    <none>        6789/TCP            39h
katib-suggestion-random                        ClusterIP   10.11.254.71    <none>        6789/TCP            39h
katib-ui                                       ClusterIP   10.11.251.106   <none>        80/TCP              39h
kfserving-controller-manager-metrics-service   ClusterIP   10.11.246.53    <none>        8443/TCP            39h
kfserving-controller-manager-service           ClusterIP   10.11.248.36    <none>        443/TCP             39h
kfserving-webhook-server-service               ClusterIP   10.11.249.53    <none>        443/TCP             39h
metadata-db                                    ClusterIP   10.11.240.36    <none>        3306/TCP            39h
metadata-envoy-service                         ClusterIP   10.11.250.155   <none>        9090/TCP            39h
metadata-grpc-service                          ClusterIP   10.11.247.161   <none>        8080/TCP            39h
metadata-service                               ClusterIP   10.11.252.35    <none>        8080/TCP            39h
metadata-ui                                    ClusterIP   10.11.240.158   <none>        80/TCP              39h
minio-service                                  ClusterIP   10.11.250.42    <none>        9000/TCP            39h
ml-pipeline                                    ClusterIP   10.11.243.53    <none>        8888/TCP,8887/TCP   39h
ml-pipeline-ml-pipeline-visualizationserver    ClusterIP   10.11.246.225   <none>        8888/TCP            33h
ml-pipeline-tensorboard-ui                     ClusterIP   10.11.252.80    <none>        80/TCP              39h
ml-pipeline-ui                                 ClusterIP   10.11.241.156   <none>        80/TCP              39h
mysql                                          ClusterIP   10.11.244.187   <none>        3306/TCP            39h
notebook-controller-service                    ClusterIP   10.11.246.79    <none>        443/TCP             39h
profiles-kfam                                  ClusterIP   10.11.251.72    <none>        8081/TCP            39h
pytorch-operator                               ClusterIP   10.11.244.137   <none>        8443/TCP            39h
seldon-operator-controller-manager-service     ClusterIP   10.11.248.24    <none>        443/TCP             39h
tensorboard                                    ClusterIP   10.11.242.44    <none>        9000/TCP            39h
tf-job-dashboard                               ClusterIP   10.11.253.238   <none>        80/TCP              39h
tf-job-operator                                ClusterIP   10.11.242.214   <none>        8443/TCP            39h
webhook-server-service                         ClusterIP   10.11.244.198   <none>        443/TCP             39h
```
Which service should this traffic be directed to?

Why would we proxy it through the pipeline front end server rather than sending it directly to the appropriate metadata service.

**Comment by neuromage** [comment]
@jlewi what client is sending this request? This setup is intended for the KFP UI.

**Comment by Bobgy** [comment]
Realized difference between Kubeflow and KFP lite deployment. In KFP lite, we don't have a reverse proxy, so the frontend node server is used as a reverse proxy to route different API requests to their correct services.

In Kubeflow, looks like we can set up a global reverse proxy. Then we can also choose to let the request directly go to metadata-envoy-service too.

Just adding my understanding here, I'm on vacation, so won't follow up further.

**Comment by jlewi** [comment]
@neuromage Is coming from the artifacts tab in the KFP UI.

**Comment by Ark-kun** [comment]
@neuromage @Bobgy  Do you remember what was the last KFP version where the UI worked in both lite and one-click deployments?

**Comment by Bobgy** [comment]
@Ark-kun The problem described here (metadata UI) is newly implemented in KFP UI for KFP lite. It never worked before in Kubeflow.

**Comment by jlewi** [comment]
@Bobgy just to clarify I'm talking about the KFP UI. Here are two screenshots

Clicking the artifacts tab in pipelines UI shows error code 5

![pipelines_artifacts](https://user-images.githubusercontent.com/777219/65904595-5b4e6a80-e3f1-11e9-8ee4-2742fbe065b0.png)

Looking at the JS network I see a 404 to
 https://jlewi-0926-002.endpoints.jlewi-dev.cloud.goog/ml_metadata.MetadataStoreService/GetArtifacts

Here's the executions tab
![pipelines_executions](https://user-images.githubusercontent.com/777219/65904725-9cdf1580-e3f1-11e9-81f5-857425867263.png)

The developer console at the JS network shows a 404 to
https://jlewi-0926-002.endpoints.jlewi-dev.cloud.goog/ml_metadata.MetadataStoreService/GetExecutions

Which service are these requests supposed to be routed to? 

It looks like these are grpc-web requests?

My guess is that these should be directed to the metadata-grpc-service. Since its using gRPC-web we need to leverage envoy to do http to gRPC proxying.

Since Kubeflow is using ISTIO we should be able to configure ISTIO to do the http to gRPC proxying for metadata rather then explicitly installing a separate envoy proxy.

I found this blog post.
https://venilnoronha.io/seamless-cloud-native-apps-with-grpc-web-and-istio

The standalone metadata UI looks fine.

My conjecture is that the standalone (separate from KFP) metadata UI is still using http to contact the metadata service.

I'm guessing the latest release of KFP was updated to use gRPC-web in its javascript client. The corresponding ISTIO changes to properly proxy web to gRPC however are missing in Kubeflow and that's why the Artifact and Executions UIs in KFP aren't working.

**Comment by jlewi** [comment]
To reproduce this follow these instructions to deploy a kubeflow cluster with https://github.com/kubeflow/manifests/pull/392

1. Clone https://github.com/kubeflow/manifests/pull/392 
1. Edit the kfctl_gcp_iap.yaml  definition
    * Change the location of the manifests repo to point to the local path where you have  https://github.com/kubeflow/manifests/pull/392  checked out
1. Use kfctl deo ploy that kfctl_gcp_iap.yaml spec

**Comment by Bobgy** [comment]
Sorry for mentioning metadata UI, it's a confusing term in this context. I meant exactly artifact and execution tabs in KFP UI.

I haven't worked on metadata UI before, so I don't know much about it.

@jlewi, I think you are right with other parts.

and using ISTIO for grpcweb proxy sounds like a reasonable solution to me too.

**Comment by zhenghuiwang** [comment]
As discussed offline, we may want to route `ml_metadata.MetadataStoreService` to `metadata-envoy-service`. Similar to
https://github.com/kubeflow/manifests/blob/master/metadata/overlays/istio/virtual-service.yaml

**Comment by neuromage** [comment]
Sent out https://github.com/kubeflow/manifests/pull/424 to hopefully fix this.

**Comment by neuromage** [comment]
Keeping this open until we've verified the fix with Jeremy's changes as well.

**Comment by jlewi** [comment]
Update:

* kubeflow/manifests#424 got reverted as part of kubeflow/manifests#426
* kubeflow/manifests#430 rolls kubeflow/manifests#424
* I've updated kubeflow/manifests#392 to pull in kubeflow/manifests#430
* I'm currently testing the combined fixes

**Comment by jlewi** [comment]
* I hit one issue with kubeflow/manifests#424 - the newly defined metadata-grpc virtual service wasn't included in the kustomization.yaml file

* Even after making that change its still not working for me.

JS developers console shows a 503  for the following URL
https://jlewi-1003-kfp-001.endpoints.jlewi-dev.cloud.goog/ml_metadata.MetadataStoreService/GetArtifacts

**Comment by jlewi** [comment]
Looks like it was an issue with the port; kubeflow/manifests#424 should be updated.

**Comment by jlewi** [comment]
Manifests have been merged.

**Comment by Ark-kun** [comment]
Is there a 0.7 branch? In the master considered to be the 0.7?
