### ISSUE TITLE
Pipeline with TFX components - no table headers in output artifacts

### ISSUE THREAD

**Issue by vicaire** [kubeflow/pipelines#224]
When running the notebook sample pipeline with TFX components, the displayed table for the prediction step does not show any headers.

**Comment by vicaire** [comment]
The headers show up when expanding the table however:

**Comment by vicaire** [comment]
![prediction-output-expended](https://user-images.githubusercontent.com/25757005/48383487-c9375980-e69a-11e8-87df-440d9d63f852.png)

**Comment by yebrahim** [comment]
This was done on purpose to compress the view as much as possible, to optimize for showing a lot of data in little space, especially in the comparison view.
But the header row is data too, so maybe we should remove that optimization.

**Comment by vicaire** [comment]
Agree. Showing the table without any header is a problematic user experience. The table also has two columns without any data.

**Comment by vicaire** [comment]
@rileyjbauer, can this be closed or is there some work remaining?

**Comment by rileyjbauer** [comment]
This has not yet been fixed at this time.

**Comment by rileyjbauer** [comment]
Fixed by #1261
