### ISSUE TITLE
client.get_experiment is case-sensitive, but create_experiment is case-insensitive

### ISSUE THREAD

**Issue by hlu09** [kubeflow/pipelines#2240]
**What happened:**
1. Create an experiment name "Aaa".
2. The code below will fail. get_experiment is not going to find the "AAA" because case is different. create_experiment will also fail because it is case insensitive.

   experiment_name = "AAA"
    try:
        experiment_id = client.get_experiment(experiment_name=experiment_name).id
    except:
        experiment_id = client.create_experiment(experiment_name).id

**What did you expect to happen:**
get_experiment and create_experiment shall be consistent.

**Possible solution**
Make get_experiment case insensitive too.

**Comment by Ark-kun** [comment]
@IronPan What's the prescribed backend behavior?
