### ISSUE TITLE
IAP host shouldn't be restricted to a cloud endpoint url

### ISSUE THREAD

**Issue by andrewsmartin** [kubeflow/pipelines#2244]
In https://github.com/kubeflow/pipelines/commit/8d5ec83f5e26312ee6cecabe647e79f3c7bf1e9b#diff-1f65a44a2187458da0f00e0ebbe730e5R142-R145, the logic for `self._is_iap_host` uses a regex to ensure that the host name is of the form `https://<deployment>.endpoints.<project>.cloud.goog/pipeline`. This breaks for us, because we use a different hostname, and thus when trying to connect via IAP an auth token is not generated.

We are able to workaround this by overriding the client and `def _is_iap_host(self, host, client_id)`, but just wanted to raise this issue here.

**Comment by james-jwu** [comment]
Assigning to Renmin for triage
