### ISSUE TITLE
build_python_component does not work in KF 6.2 

### ISSUE THREAD

**Issue by SinaChavoshi** [kubeflow/pipelines#2246]
compiler.build_python_component uses the default name space for pod creation. As of KF 6.2 the notebooks are running under a user name space( ex kubeflow-<username>) with editor service account. This service account does not have access to default kubeflow name space by design. 

SDK needs to be updated to use the user service account instead. 

sample error: 

`HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods is forbidden: User \"system:serviceaccount:kubeflow-chavoshi:default-editor\" cannot create resource \"pods\" in API group \"\" in the namespace \"kubeflow\"","reason":"Forbidden","details":{"kind":"pods"},"code":403}
`
screen shot: 
https://screenshot.googleplex.com/QotFfe0hgnW.png

**Comment by SinaChavoshi** [comment]
a short work around is to specify the parameter `namespace=` when calling the `build_python_component(` api and set it to the user name space. By default this is set to kubeflow. 

`def build_python_component(component_func, target_image, base_image=None, dependency=[], staging_gcs_path=None, timeout=600, namespace='kubeflow', target_component_file=None, python_version='python3'):`

**Comment by gaoning777** [comment]
The default namespace is configured incorrectly. We can change the namespace in the component builder API since the container builder API correctly retrieves the current namespace.
