### ISSUE TITLE
Remove container build magic 

### ISSUE THREAD

**Issue by SinaChavoshi** [kubeflow/pipelines#2251]
This request is to remove the container build magic, this is an alternative path that can become out dated and create confusion for customers. 

Suggestion is to remove the functionality and add a proper error message indicating that the library is deprecated and removed. 

there are two sections that need to be removed , pipelines/sdk/python/kfp/notebook/_magic.py as well as the corresponding library def build_docker_image under pipelines/sdk/python/kfp/containers/_component_builder.py

**Comment by Ark-kun** [comment]
There is a PR to deprecate it. Should we remove it right away? https://github.com/kubeflow/pipelines/pull/2266

**Comment by Ark-kun** [comment]
Fixed by #2266 and https://github.com/kubeflow/pipelines/pull/2276
