### ISSUE TITLE
Need instructions on how to use the deployed models in sample pipelines with TFX components

### ISSUE THREAD

**Issue by vicaire** [kubeflow/pipelines#226]
The sample notebook linked here deploys model using either the Tensorflow Serving container, or the Cloud ML Engine prediction service. 

https://github.com/kubeflow/pipelines/blob/77a1da75dd6663346985f1e098a36792d04e846e/samples/notebooks/KubeFlow%20Pipeline%20Using%20TFX%20OSS%20Components.ipynb

The instructions to make sample calls to the deployed service should be readily available in both cases.

**Comment by gaoning777** [comment]
Not complained by the customers for the past six month. Close and feel free to reopen if this is important.
