### ISSUE TITLE
UI should display documentations for the steps of a pipeline

### ISSUE THREAD

**Issue by vicaire** [kubeflow/pipelines#227]
It would be very useful to have the documentation of a pipeline and its steps readily available in the UI. 

Ideally: 
- The user should be able to specify documentation using our Python library. 
- The documentation would be part of the pipeline package. 
- The UI would display the documentation

Example documentation needed: 
- What does the step do? 
- What are the parameters? 
- How to make calls to the deployed server? (Cloud ML engine serving, in-cluster TF serving)
- Etc.

**Comment by ajayalfred** [comment]
Good point. I'll make a note of design mocks needed.

**Comment by vicaire** [comment]
@Ark-kun, please get a review before proceeding with this implementation.

**Comment by vicaire** [comment]
Closing in favor of https://github.com/kubeflow/pipelines/issues/525
