### ISSUE TITLE
TFDV and TFMA visualizations in KFP UI?

### ISSUE THREAD

**Issue by JakeTheWise** [kubeflow/pipelines#2283]
Are there yaml component specifications that can do this already? Is AI Hub the only repo for pipelines/components? I don't know how to write the visual outputs/widgets from TFDV/TFMA to HTML for display in the KFP UI via writing to `mlpipeline-ui-metadata.json` as per the [tutorial](https://www.kubeflow.org/docs/pipelines/sdk/output-viewer/), and the links on that page to the example code are broken.

**Comment by andrewsmartin** [comment]
@JakeTheWise here's the commit that removed those files causing the broken links, hopefully this can set you in the right direction. https://github.com/kubeflow/pipelines/commit/86163ecd3882a610f9709d96705613d9a151bf87#diff-ef180dd8899f69cbf7b44c78a23e042eL196-L221

**Comment by ajchili** [comment]
Hey @JakeTheWise, I recently implemented support for Python Based Visualizations within KFP. This method of visualizing data allows for TFDV/TFMA and other Python visualization libraries to be easily used within the KFP UI without extensive knowledge of HTML or how to export visualizations. This might be the best option for your use case, you can checkout my post about them on [Medium](https://medium.com/@kirinpatel/python-based-visualizations-within-kubeflow-pipelines-2e19da43d0b2) or the documentation within KFP [here](https://github.com/kubeflow/pipelines/blob/master/backend/src/apiserver/visualization/README.md) for details on how to get started. As a heads up, KFP needs to be at version 0.1.29 or later. Please let me know if you have any questions about the feature!

**Comment by Ark-kun** [comment]
> Are there yaml component specifications that can do this already?

Yes, that should be possible. It's just that the outputs need to be explicit now. https://github.com/kubeflow/pipelines/blob/9a9bd904aca5faa5444fa9c4e30574937aceda03/components/local/confusion_matrix/component.yaml#L20

The `component.yaml` just describes the component inputs and outputs and how to call the program. That spec does not care about the contents of those output files. Only the frontend does.

>Is AI Hub the only repo for pipelines/components?

This repo is more up to date usually.

>as per the tutorial, and the links on that page to the example code are broken.

We're sorry about this. I'll create an issue to fix those.

>here's the commit that removed those files

BTW, Just because those files have been removed does not mean that those components should stop working. If they no longer work I'd consider that a bug that needs to be fixed.

Do you see any visualizations working at all? Including the 1st-party components from this repo.

**Comment by JakeTheWise** [comment]
Thanks for the help, everyone! With the old commit provided by @andrewsmartin, I was able to make my TFDV display properly in the KFP UI. I have only had partial success with the TFMA visual, however. It displays incorrectly, and upon inspection it seems there is a CORS issue with a javascript file that TFMA uses. Here's the seemingly troublesome piece of my html I'm rendering for the TFMA viz:
```
<link rel="import" href="https://cdn.rawgit.com/tensorflow/model-analysis/v0.6.0/tensorflow_model_analysis/static/vulcanized_template.html">
```
And here's the error I get in the browser console when inspecting the KFP UI:
```
Access to imported resource at '....cloud.goog/pipeline/nullnbextensions/tfma_widget_js//vulcanized_template.html' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
I tried adding ` crossorigin="anonymous"` to the `link` tag but that didn't help. I'm quite unfamiliar with CORS/frontend dev, so I plan to research this issue further, but if anyone has already encountered or solved this issue, it would be sweet to hear from you.

**Comment by JakeTheWise** [comment]
The source of the issue seems to be documented here https://github.com/tensorflow/model-analysis/issues/10. Has anyone figured out how to resolve this issue?

**Comment by ajchili** [comment]
Hey @JakeTheWise, I investigated something similar in tensorflow/data-validation#80, where visualizations could not be rendered outside of a Jupyter Notebook generated environment. After a very quick look at the issue you provided it does not seem like the same approach can be provided. I will continue to investigate as I have time and keep you informed.

**Comment by Bobgy** [comment]
/assign @jingzhang36 
Is this something you already tried or fixed?

**Comment by Bobgy** [comment]
Two changes needed to support this better:
1. [ ] https://github.com/kubeflow/pipelines/pull/3111
2. [ ] Improve loading speed of the hack by fixing KFP UI infinite redirection.

Users can use custom visualization as mentioned in https://github.com/tensorflow/model-analysis/issues/10#issuecomment-587422929 now (but there's only one tfma version support).

**Comment by Bobgy** [comment]
p0 issues solved
