### ISSUE TITLE
apis/v1beta1/pipeline filter not working, always returning all pipelines

### ISSUE THREAD

**Issue by discordianfish** [kubeflow/pipelines#2294]
**What happened:**
When trying to search/filter for a workflow in the pipeline UI, all pipelines get returned no matter what you search for.

**What did you expect to happen:**
Only pipelines should show up that include the string I'm searching for.

**What steps did you take:**
- Have a bunch of pipelines
- Search for a string certain to be not part of any pipeline
- See that still all pipelines get returned

**Anything else you would like to add:**
Could be maybe fixed by implementing https://github.com/kubeflow/metadata/issues/73?

**Comment by rmgogogo** [comment]
https://github.com/kubeflow/pipelines/blob/47aaf08280c60de064c6d4ec66ee116414709a45/backend/src/apiserver/storage/pipeline_store.go#L85

No filter logic there.

Not sure normally how many pipelines user have. I assume won't too much. So mark as P2 for now.

**Comment by rmgogogo** [comment]
MLMD has same limitation but require actions in MLMD project.
https://github.com/kubeflow/metadata/issues/73

**Comment by rmgogogo** [comment]
@jingzhang36 maybe we can simply add filter in ORM layer

**Comment by Bobgy** [comment]
I believe this has been fixed in one of recent versions. Please reopen by
typing "/reopen" if this still applies
