### ISSUE TITLE
move Data passing in python components.ipynb to core samples

### ISSUE THREAD

**Issue by SinaChavoshi** [kubeflow/pipelines#2298]
Sorry i missed this during code review. This sample should be under core -> Data passing -> Data passing.ipynb or a similar folder / file name under core.

**Comment by Ark-kun** [comment]
I think we should have some organization in the samples. Currently samples are like the "Index" of a technical book - they're organized alphabetically. There is no order, no curriculum. There is no distinction between notebooks and python files. Niche topics come before fundamental topics. Etc.

There should be a place where the users see clearly structured tutorials:

```
Pipelines 101 - Creating pipeline from existing components
Pipelines 102 - Creating pipeline that access GCP resources
Pipelines 103 - Creating components from python functions
Pipelines 104 - Passing data for python components
Pipelines 105 - Creating components from container images
Pipelines 106 - Creating components from command-line programs
Pipelines 107 - Creating components from Airflow operators

Pipelines 201 - Control structures: Conditionals
Pipelines 202 - Control structures: ParallelFor loops
Pipelines 203 - Control structures: Recursive loops
Pipelines 204 - Code generation
Pipelines 205 - Execution options: Retries
Pipelines 206 - Control structures: Exit handlers

Pipelines 301 - Execution options: Kubernetes container options
Pipelines 302 - Execution options: Kubernetes pod options
Pipelines 303 - Pipeline packages - create, submit, upload
Pipelines 304 - Kubeflow Pipelines server API client
```

What do you think about this curriculum?

**Comment by gaoning777** [comment]
But, before the reorg discussion, can we conform to the core/contrib structure for now, which we agreed upon? 
On the other hand, the current structure is not too big an issue though. Similar to the Argo examples, all examples live in the same directory, which I think is useful. User can search the key word in the same directory.
With that being said, the notebook could live in core/notebooks, though.

**Comment by Ark-kun** [comment]
> But, before the reorg discussion, can we conform to the core/contrib structure for now, which we agreed upon?

Sure. I'll move the tutorial and try to make it discoverable using different means.

>With that being said, the notebook could live in core/notebooks, though.

I also think that it's better to separate notebooks and other samples.

>On the other hand, the current structure is not too big an issue though. Similar to the Argo examples, all examples live in the same directory, which I think is useful.

I've seen multiple repositories like tensorflow that have `examples` and `tutorials`. examples are pretty random, while tutorials are structured in a way that make it easier for the user to learn the product.

As a user, I cannot look at every sample. I do not know which samples are essential, which are advanced and which are very niche. If I look at the list, the top sample was `artifact_location` for quite a long time. And this is a very advanced feature that I really do not even want to expose to the users.

I'll move the tutorial, but I'll also try to rename/restructure the samples inside core. WDYT?

**Comment by SinaChavoshi** [comment]
resolving as per recent discussions / contributions we are going with the demo, tutorials and templates.
