### ISSUE TITLE
Feature Request: more than one ROC curve per component and add name arg

### ISSUE THREAD

**Issue by tanguycdls** [kubeflow/pipelines#2304]
Hi, 
Thank's for the work ! In our team we're currently trying KubeFlow and using outputs artifacts to save metrics and ROC, in the future I think we will try exporting HTML as well. 

We noticed it's currently not clear what the UI can do when more than one curve is outputted in the artifacts json file: is it possible and what would be displayed? A nice feature would also be to add a name to the roc to know what we're dealing with and display it in the UI: it would be really necessary in case we can export more than one. 

Best,

**Comment by jessiezcc** [comment]
What's recommended is to produce separate artificats.json file for each ROC. 
We don't have plan right now to support more than one ROC in the single json file.
