### ISSUE TITLE
Consider using standard cron syntax

### ISSUE THREAD

**Issue by discordianfish** [kubeflow/pipelines#2318]
Most cron implementation, including Kubernetes own CronJob implementation, don't have a leading seconds field as scheduledworkflows have.

While this would be a breaking change, it's pretty unexpected and will cause issues for people moving from standard cron implementations.

**Comment by rmgogogo** [comment]
The UI shows "Allow editing cron expression. ( format is specified here)"
The "here" link to 
https://godoc.org/github.com/robfig/cron#hdr-CRON_Expression_Format

So I assume we are OK. Here close but feel free to reopen and provide more feedback.

**Comment by discordianfish** [comment]
@rmgogogo What feedback do you need?

- I'm talking about the CRD format, that requires leading seconds
- This is also due kubeflow using an old robfig/cron version
- I don't see the link  in the 0.6 UI at least
- If it's the same link as you posted, it's wrong because robfig/cron dropped the leading seconds field

Of course it's up to the maintainers to decide which cron format but it seems like a odd choice to go with this format. It's probably just that it was the default format of robfig/cron.

All this has essential the same reasoning as https://github.com/robfig/cron/issues/58

**Comment by discordianfish** [comment]
@rmgogogo Can you please respond and/or re-open this issue?

**Comment by rmgogogo** [comment]
oops, didn't notice this reply. thought you can reopen it.
Link the issue you created in another ticket here. Let's move to that one.
https://github.com/kubeflow/pipelines/issues/2654
