### ISSUE TITLE
Distinction between 'core' and 'contrib' samples

### ISSUE THREAD

**Issue by animeshsingh** [kubeflow/pipelines#2322]
In Kubeflow Pipelines sample repo, we have made a distinction between core and contrib. In contrib we have samples which are more vendor oriented, for e.g. AWS/IBM etc. 

A lot of samples going in 'core' are very GCP specific, where a user needs to have a GCP account to run them. We shall move them to 'contrib' as well, and keep the core specific only to Kubeflow open source components.

**Comment by gaoning777** [comment]
The core samples also mean they are tested by the test infra. Since we currently only run the samples on GCP, we place the tested samples in the core directory.
