### ISSUE TITLE
Verify KFP 0.31 in Kubeflow 0.7

### ISSUE THREAD

**Issue by jlewi** [kubeflow/pipelines#2329]
Kubeflow has been updated on master to ship the KFP 0.31.

See kubeflow/pipelines#2239. 

Opening this issue to track if there is any automatic or manually testing that should be done to verify everything works.

One big change is that Kubeflow 0.7 will be enabling workload identity on GKE (see also #1962). 
For backwards compatibility the secrets should still be created in the Kubeflow namespace which I believe is where pipelines is running but this will change in subsequent releases.

/cc @jessiezcc @IronPan

**Comment by jessiezcc** [comment]
@Ark-kun, can you pls validate?

**Comment by Ark-kun** [comment]
Working on this.

**Comment by Ark-kun** [comment]
@jlewi I do not see the 0.7 branch in kubeflow repo. Are you releasing the latest master as v0.7?

**Comment by jlewi** [comment]
@Ark-kun @richardsliu we are in the process of getting in the final fixes and cutting the branch and the release. In the interim you can build from master.

This is the doc: http://bit.ly/demo-v0-7
We use to qualify the release. It has instructions for how to deploy and points out known issues and potential work arounds.

**Comment by Ark-kun** [comment]
Ongoing list of issues:
* Two users/namespaces created during installation
* One notebook fails to connect with "no healthy upstream" https://github.com/kubeflow/kubeflow/issues/4284
* One notebook fails to connect with "404 not found" https://github.com/kubeflow/kubeflow/issues/4285
* The version of KFP SDK is very old (0.1.22) and has known issues. Please merge https://github.com/kubeflow/kubeflow/pull/4286

**Comment by Ark-kun** [comment]
The `user-gcp-sa` secret is missing. All pipeline that use GCP stall at `ContainerCreating`.
@jlewi Previously Kubeflow deployed those secrets. The Kubeflow deployment guide does not mention the creation of that secret.

**Comment by jlewi** [comment]
Thanks @Ark-kun 

kubeflow/kfctl#46 is tracking the creation of the user_gcp_sa secret. We are switching to workload identity in 0.7 but we will continue to create the uesr_gcp_sa secret for backwards compatibility in the kubeflow namespace.

Regarding the SDK. I thought @IronPan wanted to stop installing the SDK because of the mismatch in release cadence and instead explicitly install the SDK in the notebook.
    * @IronPan has kubeflow/kubeflow#3632 to remove it.

**Comment by Ark-kun** [comment]
> we will continue to create the uesr_gcp_sa secret for backwards compatibility 

Let's brainstorm a better way to specify the need for access to some resource in Pipelines. From DSL standpoint it might be good to use something like `task.needs_access_to(gcp.Storage('editor', 'my-bucket'))` or hopefuully something easier. But how should the backend act on this?

> Regarding the SDK. I thought @IronPan wanted to stop installing the SDK because of the mismatch in release cadence and instead explicitly install the SDK in the notebook.
> * @IronPan has [kubeflow/kubeflow#3632](https://github.com/kubeflow/kubeflow/pull/3632) to remove it.

I'm OK with either option.

**Comment by jlewi** [comment]
@Ark-kun I recommend going with the kubeflow/kubeflow#3632 and adding a pip install step to the notebook. We are doing the same thing in other Kubeflow examples because it just works better.

kubeflow/kubeflow#4281 is tracking the centraldashboard image bug.

**Comment by Ark-kun** [comment]
> I recommend going with the [kubeflow/kubeflow#3632](https://github.com/kubeflow/kubeflow/pull/3632)

Let's do that then.

**Comment by Ark-kun** [comment]
> Let's do that then.

Merged.

**Comment by jlewi** [comment]
@Ark-kun Could you try again with the latest RC
https://github.com/kubeflow/kubeflow/releases/tag/v0.7.0-rc.5

And this config
https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_gcp_iap.0.7.0.yaml

Updated instructions are pending in https://github.com/kubeflow/website/pull/1234

**Comment by jlewi** [comment]
@Ark-kun  Latest RC 
https://github.com/kubeflow/kubeflow/releases/tag/v0.7.0-rc.7

www.kubeflow.org is now up to date.

There are currently no known blocking issues and we are aiming to finalize 0.7.0 today assuming we don't learn of any new release blocking issues.

**Comment by Ark-kun** [comment]
> @Ark-kun Latest RC
> https://github.com/kubeflow/kubeflow/releases/tag/v0.7.0-rc.7

I'll try checking it.

**Comment by Bobgy** [comment]
FYI, I met problem: https://github.com/kubeflow/kubeflow/issues/4446

I think it's in central dashboard.

**Comment by IronPan** [comment]
I believe the empty artifact page fix is not in 0.1.31. 
@numerology Do you think we should include that? The new release 0.1.33 will be ready soon which will include all fixes.

**Comment by numerology** [comment]
> I believe the empty artifact page fix is not in 0.1.31.

Thanks for looping me in. Is that the empty artifact bug when running pipeline written in TFX DSL?

**Comment by Ark-kun** [comment]
I noticed the the `metadata-configmap` is not deployed in Kubeflow installation. @neuromage Can we make the Kubeflow installation closer to standalone and marketplace in this aspect?

**Comment by Ark-kun** [comment]
> I believe the empty artifact page fix is not in 0.1.31.

I think this issue is quite important to fix in KF 0.7.

**Comment by numerology** [comment]
> I noticed the the `metadata-configmap` is not deployed in Kubeflow installation. @neuromage Can we make the Kubeflow installation closer to standalone and marketplace in this aspect?

That explains why artifact page is empty, I think we definitely need to include that in the Kubeflow manifest.

**Comment by jlewi** [comment]
@Ark-kun @numerology @IronPan we are finalizing 0.7.0 this morning. If this fix is critical please submit a fix ASAP and we will include it in a minor release.

In the interim can someone please provide a description of what the problem is or what won't work that we can include in the release notes for 0.7.0.

**Comment by numerology** [comment]
Hi @jlewi , sorry for the delayed response.

The problem is as follows. We've noticed that KF 0.7 release is using KFP 0.1.31, which actually does not include this [preload sample](https://github.com/kubeflow/pipelines/tree/master/samples/contrib/parameterized_tfx_oss) that demonstrates the latest execution/artifacts UI and metadata functionalities etc. Those functionalities actually rely on a correct metadb config map, which is currently missing from kubeflow's manifests. 

If KF 0.7 is shipped with KFP 0.1.31, I would say it'll still be a 'self-consistent' one because the broken features are not implemented in 0.1.31 at all. However if it is the version that customers will be using in the next couple of months, IMO it'll be a bit of out of date shortly.

I think it's KF's call whether to include that or not. If KF wish to ship 0.7 ASAP, we're okay with that, too.

**Comment by jlewi** [comment]
Thanks for the details @numerology. 

KF 0.7.0 will be shipping 0.1.31 because that's what we've been qualifying. 

Including a later version of KFP in a minor release 0.7.X is a possibility. The first step would be to get the manifests on master updated to ship a later version of KFP. 

What is the next version of KFP that should be targeted and do we have a tracking bug to update the manifests?

**Comment by Ark-kun** [comment]
> What is the next version of KFP that should be targeted and do we have a tracking bug to update the manifests?

@IronPan Let's update the manifests to 0.1.33 and update them every week as part of weekly KFP release.

**Comment by jlewi** [comment]
I'm closing this issue because we have released 0.7.0 with KFP 0.31.
Thank you everyone for all your help.
