### ISSUE TITLE
`command` section only support either a string or a placeholder in component.yaml

### ISSUE THREAD

**Issue by TomomasaTakatori** [kubeflow/pipelines#2337]
I'm running a component that execute maven project.

On local, my command is like below.
```
mvn exec:java -Dexec.mainClass=my.test.project -Dexec.args="-argop1 arg1 -argop2 arg2"
```
So, I have written command section in component.yaml.
```
command: [
      mvn, exec:java, -Dexec.mainClass=my.test.project,
      -Dexec.args=-argop1, {inputValue: arg1},
      -argop2, {inputValue: arg2}
    ]
```
An error was occurred because "-argop1 arg1 -argop2 arg2" is recognized as one argument for maven.(*1)

I wonder if I can combine {inputValue: } and String in yaml,
```
command: [
      mvn, exec:java, -Dexec.mainClass=my.test.project,
      -Dexec.args=-argop1 {inputValue: arg1} -argop2, {inputValue: arg2}
    ]
```
but can't. The reason should be `command: Entrypoint array. The Docker image’s ENTRYPOINT is used if this is not provided. Each item is either a string or a placeholder. The most common placeholders are {inputValue: Input name} and {outputPath: Output name}.` . 
(https://www.kubeflow.org/docs/pipelines/reference/component-spec/)

In addition, I've tried to reproduce the same command as command line one.  
```
command: [
      mvn, exec:java, -Dexec.mainClass=my.test.project,
      -Dexec.args="-argop1, {inputValue: arg1},
      -argop2, {inputValue: arg2},
     \"
    ]
```
Of course, It's failed.

In that case, how to write `command` section ? 

(*1)
I've checked whether the below section that was hard code worked well. 
```
command: [
      mvn, exec:java, -Dexec.mainClass=my.test.project,
      -Dexec.args=-argop1 arg1 -argop2 arg2,
    ]
```
It works.

**Comment by Ark-kun** [comment]
>`exec:java`

This should probably quoted. Otherwise it might be considered a map.

>I wonder if I can combine {inputValue: } and String in yaml,

We have a solution for this - the `Concat` placeholder:

```yaml
command:
- mvn
- 'exec:java'
- -Dexec.mainClass
- my.test.project
- -Dexec.args
- Concat: ['-argop1 ', {inputValue: arg1}, ' -argop2 ', {inputValue: arg2}] # Note the spaces around the flags
```

BTW, Do you think it's possible to create a function like `func_to_container_op`, but for Java?
We'll need some ability to reflect the function signature and to call a Java function from command-line.

**Comment by TomomasaTakatori** [comment]
Thank you for your replying.
Your advices almost works well.

My yaml is
```
    command:
      - mvn
    args:
      - exec:java
      - -Dexec.mainClass=my.test.project
      - concat: ['-Dexec.args=argop1 ', {inputValue: arg1},
                 ' -argop2 ', {inputValue: arg2},
                ]
```

If we use `concat`, the every characters is lower case.

**Comment by Ark-kun** [comment]
> If we use `concat`, the every characters is lower case.

Thanks. Fixed.
