### ISSUE TITLE
Store the information about the user who created each run

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#2348]
This will open path for improving the experience for teams using the same cluster by only showing user's own runs in the UX by default.

**Comment by numerology** [comment]
This sounds sweet. Is this a feature related with the multi-tenant scenario? @gaoning777

**Comment by Bobgy** [comment]
I think this is great. Something I couldn't figure out -- what can we use as a user identity?

**Comment by rmgogogo** [comment]
Close this one as we have another one there.
https://github.com/kubeflow/pipelines/issues/2397

**Comment by Ark-kun** [comment]
> Close this one as we have another one there.
> #2397

That issue seems to be newer and has bigger scope.
