### ISSUE TITLE
Client SDK Bug in the create_run_from_pipeline_package function

### ISSUE THREAD

**Issue by gaoning777** [kubeflow/pipelines#2357]
lacking the run_id param to the wait_for_run_completion func:
https://github.com/kubeflow/pipelines/blob/709d7e2b44b87e30ab8219eab617d9176dca4110/sdk/python/kfp/_client.py#L361

**Comment by gaoning777** [comment]
fixing in https://github.com/kubeflow/pipelines/pull/2355

**Comment by Ark-kun** [comment]
Fixed in https://github.com/kubeflow/pipelines/pull/2355
Thank you for discovering it.
