### ISSUE TITLE
[Test/Sample test] Permission issue in ai-platform

### ISSUE THREAD

**Issue by numerology** [kubeflow/pipelines#2363]
Currently there is ongoing permission issue blocking the presubmit testing. See:

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/2362/kubeflow-pipeline-sample-test/1182370644122144768
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/2360/kubeflow-pipeline-sample-test/1182368127246143492

**Comment by Ark-kun** [comment]
A side question - why did the test not fail for the PR that added it?

**Comment by numerology** [comment]
> A side question - why did the test not fail for the PR that added it?

This was added at PR #2327 

cc @gaoning777 do you know if there is any special permission needed for the SA?

**Comment by numerology** [comment]
Fixed by #2355
