### ISSUE TITLE
Sample tests do not test SDK changes since many tests install released SDK

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#2368]
The sample tests should be testing the SDK changes.
However, those changes are overriden by samples re-installing a release version of the SDK.

**Comment by numerology** [comment]
This is an interesting topic. IIRC for python samples the head version of SDK was used, but for notebook samples the released version was used.

It seems like we need a way to prevent notebooks from doing that. Maybe string substitution?

**Comment by numerology** [comment]
cc @gaoning777  WDYT? Shall we suppress the package installation by comment them out? Or we handle that in the sample test infra?

**Comment by Ark-kun** [comment]
For short term I propose either commenting out the package installation lines or setting the minimum version and removing `--upgrade`:
```
!pip3 install 'kfp>=0.1.31' --quiet
```

**Comment by numerology** [comment]
Another thought on this.
After each release, can we bump the [version number of sdk](https://github.com/kubeflow/pipelines/blob/26a244de242cc694d6cfb9377891ec1cee1e2d15/sdk/python/kfp/__init__.py#L16) so that `pip install --upgrade` realizes the head version is a higher version and does not override it?

Will give it a shot when I have time.

**Comment by Ark-kun** [comment]
> After each release, can we bump the [version number of sdk](https://github.com/kubeflow/pipelines/blob/26a244de242cc694d6cfb9377891ec1cee1e2d15/sdk/python/kfp/__init__.py#L16) so that `pip install --upgrade` realizes the head version is a higher version and does not override it?

We were already bumping the version, but there was some issue that caused pip to re-install the SDK from PyPI.

The installation was fixed as party of https://github.com/kubeflow/pipelines/pull/2292
