### ISSUE TITLE
Get experiment by name, create run in experiment by name

### ISSUE THREAD

**Issue by yebrahim** [kubeflow/pipelines#237]
Currently, getting an experiment, and creating a run in a given experiment, requires specifying the experiment's ID in the API call. This makes the API and CLI UX more complicated since we already have unique experiment names. User should be able to reference experiment by name.

**Comment by SinaChavoshi** [comment]
+1 There is no way to get experiment ID from UI, this will be very handy.

**Comment by rileyjbauer** [comment]
I support this change, but just for the record, if you navigate to a specific experiment's page, you can get its ID from the url. It will be as follows: `localhost:3000/#/experiments/details/EXPERIMENT_ID`

**Comment by vicaire** [comment]
Resolving in favor of https://github.com/kubeflow/pipelines/issues/506
