### ISSUE TITLE
SDK versioning in samples

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#2375]
Problems:
Some samples need some newer versions of the SDK.
Installing the latest SDK version might be interfering with sample tests.

Solution:
Samples should install the minimum SDK version they support:
```
!python3 -m pip install 'kfp>=0.1.31' --quiet
```

Changes to samples should ideally result in testing them on their minimum SDK version (this needs to be implemented somehow).
Changes to SDK should result in checking the samples against the newest SDK changes.

**Comment by gaoning777** [comment]
Samples testing 

> Problems:
> Some samples need some newer versions of the SDK.
> Installing the latest SDK version might be interfering with sample tests.
> 
> Solution:
> Samples should install the minimum SDK version they support:
> 
> ```
> !python3 -m pip install 'kfp>=0.1.31' --quiet
> ```
> 
> Changes to samples should ideally result in testing them on their minimum SDK version (this needs to be implemented somehow).

The notebook samples should be working as it is(install the newest released version.) If we want to have a good sample-SDK versioning, it should be part of the DSL such that the normal python samples are also covered.
> Changes to SDK should result in checking the samples against the newest SDK changes.

Agreed. But it does not have to be the sample tests that cover the SDK testing.

**Comment by Ark-kun** [comment]
> The notebook samples should be working as it is(install the newest released version.)

I'm not sure I've seen many examples of this in the wild. AFAIK, usually the notebooks do not modify the user environment.
Note that `pip install 'kfp>=0.1.31'` will install the latest version if the package is older or not installed.

>Agreed. But it does not have to be the sample tests that cover the SDK testing.
I think it makes sense to use the same samples to test the SDK changes. I consider the sample tests to be an important part of SDK testing.
