### ISSUE TITLE
Upload Error Invalid response: 404

### ISSUE THREAD

**Issue by SinaChavoshi** [kubeflow/pipelines#239]
Connected through google cloud shell, when trying to upload a notebooks from jupyter lab by clicking upload I get "Upload Error Invalid response: 404". Also tried uploading from Jupyter notebook tree interface, that also fails ( silently ) 

Everything else seems to be working fine including Jupiter lab / notebook.

**Comment by yebrahim** [comment]
- Is this a fresh deployment? Sometimes it takes a while for the backend to be ready. Were you able to list pipelines with no error?
- Curious, can you paste the pipelines page (the one you're on when trying to upload) URL here?

**Comment by SinaChavoshi** [comment]
I can upload pipelines without any issues. 

I was trying to upload "Lightweight Python components - basics.ipynb"  notebook to Jupiter hub. When I connect via Cloud shell I could not upload files to jupyter hub ( either in tree or lab mode) , however when I port forward locally on my dev box it works fine.

**Comment by yebrahim** [comment]
Ah, I totally misread your issue, apologies.
This looks like another incarnation of https://github.com/kubeflow/pipelines/issues/179. CORS issues on Cloud Shell. Will close as a dup.
