### ISSUE TITLE
[Sagemaker] Pytorch Container / BYO Container

### ISSUE THREAD

**Issue by tanguycdls** [kubeflow/pipelines#2421]
Hi guys, I'm currently testing Sagemaker to train a model directly on a ec2 instance and not in the cluster. I'm using Sagemaker notebook to call the SDK api.

- Right now I installed the python sdk in a ubuntu based docker and i'm calling the api using a script using a Pytorch Estimator and a custom image: I then call it as a python component using func to container op. 
   - I don't find it so clean since that docker has to have a copy of the training function and upload it to S3 so that the training image can use it. 

- I found https://github.com/kubeflow/pipelines/blob/master/samples/contrib/aws-samples/mnist-kmeans-sagemaker/mnist-classification-pipeline.py but I dont understand how I could pass a Pytorch Estimator or a custom image instead.
  - Do you know how is configured that docker image : 174872318107.dkr.ecr.us-west-2.amazonaws.com/kmeans:1

- I found out that Sagemaker provides Airflow op, could we use it w/ Kubeflow component from airflow op ? 

Thank you by advance for your help, 

Best,

**Comment by Ark-kun** [comment]
>I don't find it so clean since that docker has to have a copy of the training function and upload it to S3 so that the training image can use it.

Can you elaborate more on the problem you are having?

> dont understand how I could pass a Pytorch Estimator or a custom image instead.
>Do you know how is configured that docker image

Where do you need to pass the image?

>I found out that Sagemaker provides Airflow op, could we use it w/ Kubeflow component from airflow op ?

It would be nice if you tried that and reported your findings. We did not have a big library of AirflowOperators to test.

**Comment by Jeffwan** [comment]
1. `174872318107.dkr.ecr.us-west-2.amazonaws.com/kmeans:1` here is a Sagemaker built-in algorithm, to understand details, please check https://docs.aws.amazon.com/sagemaker/latest/dg/k-means.html

2. I think anyway you need to copy your training function to base image and build your own training image. What do you want to achieve here? 

3. Airflow Sagemaker Operator should be similar to KFP Sagemaker components. If you determine to use KFP as orchestrator, you are not supposed to use airflow op. vice versa.

**Comment by tanguycdls** [comment]
Hi Thanks for your answers and sorry for the delay. 

I had some response from AWS Support, to pass an entrypoint path without having to copy it through the high level api you can use hyperparameters:
```
'sagemaker_submit_directory': 's3://path_to_tar_gz', (for example Model: s3://sagemaker/code/***.tar.gz)
 'sagemaker_program': 'entrypoint.py', 
 'sagemaker_region': 'eu-west-1'}
```
Using those you can use the boto3 sagemaker api with Pytorch Sagemaker Image. I did not had time to try with Kubeflow Sagemaker component but i'm pretty confident it should work. 

On the question on how to use a custom image for Sagemaker the explanations are here:
https://docs.aws.amazon.com/sagemaker/latest/dg/your-algorithms-training-algo-dockerfile.html and  https://github.com/aws/sagemaker-containers/. 

Thanks for the help, i'm closing
