### ISSUE TITLE
ModuleNotFoundError when trying to compile a pipeline file

### ISSUE THREAD

**Issue by OfficePop** [kubeflow/pipelines#2426]
**What happened:**

I am trying to follow the [Experiment with the Pipelines Samples](https://www.kubeflow.org/docs/pipelines/tutorials/build-pipeline/) guide and am not able to compile the `sequential.py` file into a `.tar.gz` file. 

I have already installed the pipelines SDK, miniconda, and have activated a python3 environment. I am running Windows.

**What did you expect to happen:**

I expected the python file to be converted to a `.tar.gz` file

**What steps did you take:**

I entered the following:

"dsl-compile --py [C:\{PATH}\Documents\GitHub\pipelines-master\samples\core\sequential\sequential.py] --output [C:\{PATH}\Documents\GitHub\pipelines-master\samples\core\sequential\sequential.tar.gz]"

And received the following response:

```
Traceback (most recent call last):
  File "c:\{PATH}\miniconda3\envs\mlpipeline\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)  
  File "c:\{PATH}\miniconda3\envs\mlpipeline\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)  
  File "C:\{PATH}\Miniconda3\envs\mlpipeline\Scripts\dsl-compile.exe\__main__.py", line 9, in <module>  
  File "c:\{PATH}\miniconda3\envs\mlpipeline\lib\site-packages\kfp\compiler\main.py", line 123, in main compile_pyfile(args.py, args.function, args.output, not args.disable_type_check)  
  File "c:\{PATH}\miniconda3\envs\mlpipeline\lib\site-packages\kfp\compiler\main.py", line 111, in compile_pyfile__import__(os.path.splitext(filename)[0])  
ModuleNotFoundError: No module named 'sequential'```

**Comment by Ark-kun** [comment]
It just cannot find the input file. Are you sure the paths are correct?
Can you run the `dsl-compile` from the same directory?
BTW, you can just run the .py file - they're self-compiling.

P.S. You might want to take a look at these tutorial notebooks that show how to create and use python-based components: https://github.com/kubeflow/pipelines/blob/8dfa2d9/samples/tutorials/Data%20passing%20in%20python%20components.ipynb https://nbviewer.jupyter.org/github/kubeflow/pipelines/blob/8dfa2d9/samples/tutorials/Data%20passing%20in%20python%20components.ipynb https://github.com/kubeflow/pipelines/blob/1e6ce6b/samples/core/lightweight_component/lightweight_component.ipynb https://nbviewer.jupyter.org/github/kubeflow/pipelines/blob/1e6ce6b/samples/core/lightweight_component/lightweight_component.ipynb

**Comment by OfficePop** [comment]
Hi, just tried again by going into the directory and running `dsl-compile` and it worked without a problem. I was copying the file path right out of windows explorer and than adding "\sequential.py" to the end so I guess something about that was incorrect. Thanks for the help and resources!

**Comment by Ark-kun** [comment]
>it worked without a problem
>Thanks for the help and resources!

I'm glad I could help.
