### ISSUE TITLE
Getting tons of "Workflow missing the Run ID label" error on api-server 0.1.31

### ISSUE THREAD

**Issue by daikeshi** [kubeflow/pipelines#2427]
**What happened:**
After we have upgraded kfp api server from 0.1.25 to 0.1.31 on Kubeflow cluster, we are seeing tons of errors in `ml-pipeline` service log:
```
I1018 02:02:08.917029       1 error.go:218] Invalid input error: Workflow missing the Run ID label
github.com/kubeflow/pipelines/backend/src/common/util.NewInvalidInputError
	backend/src/common/util/error.go:165
github.com/kubeflow/pipelines/backend/src/apiserver/resource.(*ResourceManager).ReportWorkflowResource
	backend/src/apiserver/resource/resource_manager.go:521
github.com/kubeflow/pipelines/backend/src/apiserver/server.(*ReportServer).ReportWorkflow
	backend/src/apiserver/server/report_server.go:39
github.com/kubeflow/pipelines/backend/api/go_client._ReportService_ReportWorkflow_Handler.func1
	bazel-out/k8-opt/bin/backend/api/linux_amd64_stripped/go_client_go_proto%/github.com/kubeflow/pipelines/backend/api/go_client/report.pb.go:174
main.apiServerInterceptor
	backend/src/apiserver/interceptor.go:30
github.com/kubeflow/pipelines/backend/api/go_client._ReportService_ReportWorkflow_Handler
	bazel-out/k8-opt/bin/backend/api/linux_amd64_stripped/go_client_go_proto%/github.com/kubeflow/pipelines/backend/api/go_client/report.pb.go:176
google.golang.org/grpc.(*Server).processUnaryRPC
	external/org_golang_google_grpc/server.go:966
google.golang.org/grpc.(*Server).handleStream
	external/org_golang_google_grpc/server.go:1245
google.golang.org/grpc.(*Server).serveStreams.func1.1
	external/org_golang_google_grpc/server.go:685
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1333
Report workflow failed.
```

**What did you expect to happen:**
I expected kfp should automatically add run id when it launches the workflow.

**What steps did you take:**
[A clear and concise description of what the bug is.]
Getting the logs using command `kubectl logs -n kubeflow svc/ml-pipeline`
api-server image: gcr.io/ml-pipeline/api-server:0.1.31 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I wonder if this should be a warning instead of an error if it's not critical.

**Comment by rmgogogo** [comment]
https://github.com/kubeflow/pipelines/blob/master/backend/src/apiserver/resource/resource_manager.go#L266

We already set it.
Is it still an issue in your cluster? 
"upgraded kfp api server from 0.1.25 to 0.1.31", how you upgrade it? workflow is on Argo, not sure whether you correctly upgrade whole.

**Comment by Bobgy** [comment]
superceded by https://github.com/kubeflow/pipelines/issues/3584
