### ISSUE TITLE
[SDK] Code style enforcement

### ISSUE THREAD

**Issue by numerology** [kubeflow/pipelines#2442]
As discussed offline, currently KFP does not adopt a consistent coding style on its Python side. This is not the best practice. 

Here we propose to use [yapf](https://github.com/google/yapf) to help contributors to enforce [Google python coding style](https://github.com/google/styleguide/blob/master/pyguide.md). I will send out a PR for the yapf configuration. The default configuration does not work very well :(

Also, I propose to use [pylint](https://github.com/PyCQA/pylint) to check the coding style in Travis CI.

[Update 10/21] Since yapf does do much to docstring, [docformatter](https://github.com/myint/docformatter) is recommended to auto-lint the docstring if a contributor found it hard to pass pylint checks.

**Comment by eterna2** [comment]
I would love to have mypy included too.

**Comment by numerology** [comment]
> I would love to have mypy included too.

Sounds good. However it seems like before we enforce mypy we need some additional works to make sure we can pass its tests

**Comment by Bobgy** [comment]
FYI, tracker issue for frontend part is https://github.com/kubeflow/pipelines/issues/2406
