### ISSUE TITLE
[Frontend] Document how to set up frontend dev env using mock server/kubeflow deployment

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#2461]
Documentation that helps people to use an existing backend to develop frontend code.

/assign @Bobgy 
/priority p1
/area front-end

**Comment by Bobgy** [comment]
Bump priority to p0 because I think documentation for using mock server is super useful, it can help contributors work on UI without any external dependency.

**Comment by rmgogogo** [comment]
hi Yuan, since it's done, so I think we can close it, right?

**Comment by Bobgy** [comment]
/reopen

@rmgogogo this is not yet done. There is documentation for standalone, but we need doc for mock server and kubeflow.
