### ISSUE TITLE
sort_by request parameter error on API runservice

### ISSUE THREAD

**Issue by OfficePop** [kubeflow/pipelines#2467]
I am testing the API calls for the RunService resource and received an error when trying to use the `sort_by` request parameter on the [GET /apis/v1beta1/runs](https://www.kubeflow.org/docs/pipelines/reference/api/kubeflow-pipeline-api-spec/#operation--apis-v1beta1-runs-get) request type.

I have several runs I can pull with `{endpoint}/apis/v1beta1/runs`, but I if try `{endpoint}/apis/v1beta1/runs?sort_by=field_name` as the reference suggests I get following response.

```{  
    "error": "Failed to create list options: Invalid input error: Invalid sorting field: \"field_name\": %!s(<nil>)",  
    "message": "Failed to create list options: Invalid input error: Invalid sorting field: \"field_name\": %!s(<nil>)",  
    "code": 3,  
    "details": [  
        {
            "@type": "type.googleapis.com/api.Error",  
            "error_message": "Invalid sorting field: \"field_name\": %!s(<nil>)",  
            "error_details": "Failed to create list options: Invalid input error: Invalid sorting field: \"field_name\": %!s(<nil>)"  
        }  
    ]  
}
```

In fact, looking at the body of a successful /apis/v1beta1/runs request, `field_name` doesn't appear to occur anywhere as a JSON key/value pair.

**Comment by eterna2** [comment]
You should replace `field_name` with the actual name of the field you want to sort by (e.g. name, created_at). Not the literal string `field_name`.

**Comment by OfficePop** [comment]
Gotcha, thanks!
