### ISSUE TITLE
Make backend build not depend on Tensorflow

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#2468]
I see the following lines in `WORKSPACE`:

```
load("@org_tensorflow//tensorflow:workspace.bzl", "tf_workspace")
tf_workspace()
```

Since MLMD service was extracted from the API-server, the build files no longer need tensorflow.
We should clean up the references.

This should fix https://github.com/kubeflow/pipelines/issues/1288

**Comment by neuromage** [comment]
/assign @Ark-kun 

Thanks for finding this. Please feel free to remove those lines and send me a PR.

**Comment by rmgogogo** [comment]
+1 to this issue. I also mentioned once with Ajay before.
We can benefit a lot from this one. Introducing tf_workspace forced a lot of build constraints.

Alex, if you are not working on it, I would be happy to send out one. mark as P0 and XS cost.

**Comment by dushyanthsc** [comment]
@Ark-kun @rmgogogo I can take a quick look at this to see the work invovled. Will send a status update by tomorrow, if that works?

**Comment by Ark-kun** [comment]
Thanks for helping with this issue.
