### ISSUE TITLE
On Mac, cannot copy truncated input or output text completely in KFP UI.

### ISSUE THREAD

**Issue by hlu09** [kubeflow/pipelines#2471]
**What happened:**

KFP UI started to truncate long input or output text. On Mac, select-and-then-copy-paste only gives visible text portion. On Linux, it works fine with all text including truncated portion.

**What did you expect to happen:**

it should work on Mac too.

**What steps did you take:**
[A clear and concise description of what the bug is.]

KFP UI version 0.1.32.

On Mac mojave  10.14.1, go to input/output tab with truncated text, try to select and then copy and past to a text editor. 

You will see that only visible text is copied. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Bobgy** [comment]
Can you provide a screenshot? Are you talking about `Input Artifacts` and `Output Artifacts`?

**Comment by hlu09** [comment]
Not artifacts, just operator output. e.g.,
e.g.,   if the output vale is "On Mac mojave 10.14.1, go to input/output tab with truncated text, try to select and then copy and past to a text editor", it will be truncated to "On Mac mojave 10.14.1, go to ..."

**Comment by hlu09** [comment]
We actually discovered that on both Linux and Mac,  we can select full text (including invisible part) by double clicking text a few times till the whole text is selected.   Thus, problem solved. 
though, it will be nice to have hover over and show whole text using hover css such as. 
.valueText:hover{
    overflow: visible; 
    white-space: normal;
    height:auto; 
}

**Comment by Bobgy** [comment]
@hlu09 thanks for the suggestion, I created https://github.com/kubeflow/pipelines/issues/2505 to track following up efforts.
