### ISSUE TITLE
dsl-compile --py pipeline.py --output pipeline.tar.gz outputs a .tar.gz, not a .zip

### ISSUE THREAD

**Issue by hilliao** [kubeflow/pipelines#2474]
the pipeline compile command outputs a .tar.gz, not a .zip:
`dsl-compile --py [path/to/python/file] --output [path/to/output/tar.gz]`
[The code line](https://github.com/kubeflow/pipelines/blob/416bab1acb85c7ffa029620ce7b99f6556a436dc/samples/core/sequential/sequential.py#L52) should return .tar.gz, not .zip

**Comment by Ark-kun** [comment]
The file format is chosen based on the extension.
If you run the self-compiling pipeline it will produce a pipeline package in some format.
If you compile it using dsl-compile, you can choose a different format.

**Comment by hilliao** [comment]
Did you mean if the code changes to _kfp.compiler.Compiler().compile(sequential_pipeline, \_\_file\_\_ + '.tar.gz')_, it would change to the .tar.gz format?

**Comment by numerology** [comment]
> Did you mean if the code changes to _kfp.compiler.Compiler().compile(sequential_pipeline, __file__ + '.tar.gz')_, it would change to the .tar.gz format?

Yes it would.

**Comment by Ark-kun** [comment]
> dsl-compile
>kfp.compiler.Compiler().compile

@hilliao
JFYI, you can now submit pipeline for execution without explicitly compiling it yourself by using
```python
kfp.Client().create_run_from_pipeline_func(func, arguments={})
```
