### ISSUE TITLE
GCP credentials instructions w/ lightweight deploy needs additional info on envir var setup

### ISSUE THREAD

**Issue by amygdala** [kubeflow/pipelines#2479]
For the marketplace guide GCP setup:
https://github.com/kubeflow/pipelines/blob/master/manifests/gcp_marketplace/guide.md#gcp-service-account-credentials
we should also specify that they need to set the `NAMESPACE` and `APP_INSTANCE_NAME` env vars.  Otherwise, when they create the `secret.yaml` file, those fields won't be filled in and things will fail silently when it's applied.  

If they're coming to this page from the console,  they probably need to use the same `APP_INSTANCE_NAME` as created there?  If so, we should specify.  And of course the `NAMESPACE` needs to be the same— that should be indicated as well.

**Comment by rmgogogo** [comment]
https://github.com/kubeflow/pipelines/pull/2394/files
Jiaxiao already fix it in upper CL to use NAMESPACE.

**Comment by numerology** [comment]
Thanks for noting this @amygdala . We switch to a leaner way for applying secret after deployment, which no longer requires `APP_INSTANCE_NAME`
