### ISSUE TITLE
Pipeline description not fully shown in UI

### ISSUE THREAD

**Issue by IronPan** [kubeflow/pipelines#2485]
![image](https://user-images.githubusercontent.com/2348602/67514659-013c7000-f652-11e9-8586-b463561fe7ce.png)

**Comment by Bobgy** [comment]
@IronPan I don't quite follow, what is not correct?

**Comment by Bobgy** [comment]
Source code should also be a link.

**Comment by Bobgy** [comment]
@IronPan Looks like there's a 255 character length limit for pipeline description in backend API. It didn't return the complete description to frontend for both cases. They all stop at 255

**Comment by Bobgy** [comment]
/assign @Bobgy
I will try to fix it

**Comment by Bobgy** [comment]
We need to configure [here](https://github.com/kubeflow/pipelines/blob/master/backend/src/apiserver/model/pipeline.go#L33) to make description field a long text.

However, gorm auto migration doesn't update data type: [reference](http://gorm.io/docs/migration.html). We need to write some migration code.

**Comment by Bobgy** [comment]
A migration sample I can reference: https://github.com/kubeflow/pipelines/blob/7aaecb150114d358c886ab85f01f327428b2a253/backend/src/apiserver/client_manager.go#L207
