### ISSUE TITLE
[MKP] GCP secret files are empty

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#2489]
```
> kubectl get secret user-gcp-sa -o yaml
Fetching cluster endpoint and auth data.
kubeconfig entry generated for cluster-1.
apiVersion: v1
data:
  application_default_credentials.json: ""
  user-gcp-sa.json: ""
```

**Comment by numerology** [comment]
Just wanna confirm. Did you go through the procedure in the [guide](https://github.com/kubeflow/pipelines/blob/master/manifests/gcp_marketplace/guide.md#gcp-service-account-credentials)

**Comment by numerology** [comment]
This is the current intended behavior for alpha launch. Will be fixed in beta launch.
For alpha launch please follow [guide](https://github.com/kubeflow/pipelines/blob/master/manifests/gcp_marketplace/guide.md#gcp-service-account-credentials) to setup user-gcp-sa secret.
