### ISSUE TITLE
Cannot get back to my hosted Jupyter notebook

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#250]
I've authored many notebooks in a GKE Pipelines cluster hoster Jupyter Notebook.

Today I wanted to do more tests and opened an old tab with some notebook, but I got redirected to the JupyterHub login screen. After entering the user name, I'm prompted to spawn a new instance instead of being redirected to the existing one.

How can I get my notebooks back?

I still see the existing notebook server pod:

    kubeflow      jupyter-av                                                       1/1       Running     1          11d

**Comment by yebrahim** [comment]
Jupyterhub issues should be filed on kubeflow/kubeflow I think, they're managing its deployment.

What does going to `/hub/home` show you?

**Comment by Ark-kun** [comment]
After login it shows the "Start my server" button.

**Comment by vicaire** [comment]
Resolving since this has been idle for a while. Please re-open if this is still needed or hasn't been fixed.

**Comment by Ark-kun** [comment]
This has happened to me again.
The notebook pod is running.
The UI redirects me to the spawner instead of showing my notebook.

**Comment by paveldournov** [comment]
@Ark-kun are you using the new Notebook UI for creating the new instances?

**Comment by Ark-kun** [comment]
> @Ark-kun are you using the new Notebook UI for creating the new instances?

I have an older cluster.
The problem occurs after couple of months, so I did not have a chance to experience it with the new notebooks yet.

**Comment by jlewi** [comment]
If you're using a cluster older than v0.5 then this is likely an issue with JupyterHub or the JupyterHub spawner. You could look at the logs for the spawner to try to figure out what's going on.

You could also try deleting your pod and recreating it. It looks like there is a problem with JupyterHub not realizing that the pod is still running.

**Comment by gaoning777** [comment]
@Ark-kun Do you still the issue on v0.5 or after?

**Comment by hongye-sun** [comment]
I don't think this issue is still in 0.5. Closing this bug.
