### ISSUE TITLE
Failed to retry run (v0.7.0rc6)

### ISSUE THREAD

**Issue by JakeTheWise** [kubeflow/pipelines#2500]
When I click `Retry` in the KFP UI to re-run a pipeline run, I get the following in a popup dialog:

```
InternalServerError: Retry run failed. Failed to clean up the failed pods from previous run.: InternalServerError: Failed to delete pods
```

**Comment by IronPan** [comment]
This should only happen in kf deploy. 
This is due to the discrepancy between kf manifest and manifest in kfp
https://github.com/kubeflow/pipelines/blob/master/manifests/kustomize/base/pipeline/ml-pipeline-apiserver-role.yaml#L11
https://github.com/kubeflow/manifests/blob/master/pipeline/api-service/base/role.yaml

**Comment by mattnworb** [comment]
I believe this is still an issue with how the `ml-pipeline` Role is defined in https://github.com/kubeflow/manifests.

With kubeflow/pipelines having its own kustomize setup in https://github.com/kubeflow/pipelines/tree/master/manifests/kustomize now, are we expected to deploy KFP through those manifests, or will the changes be synced back to https://github.com/kubeflow/manifests?

**Comment by JakeTheWise** [comment]
This issue still happens with kubeflow 0.7.1. The error is
```
Failed to retry run: e8e1840f-4615-4327-b20c-85c98a981372 with error: "{"error":"InternalServerError: Retry run failed. Failed to clean up the failed pods from previous run.: InternalServerError: Failed to delete pods.: pods \"basic-training-rlq27-2856773258\" is forbidden: User \"system:serviceaccount:kubeflow:ml-pipeline\" cannot delete resource \"pods\" in API group \"\" in the namespace \"kubeflow\"","message":"InternalServerError: Retry run failed. Failed to clean up the failed pods from previous run.: InternalServerError: Failed to delete pods.: pods \"basic-training-rlq27-2856773258\" is forbidden: User \"system:serviceaccount:kubeflow:ml-pipeline\" cannot delete resource \"pods\" in API group \"\" in the namespace \"kubeflow\"","code":13,"details":[{"@type":"type.googleapis.com/api.Error","error_message":"Internal Server Error","error_details":"InternalServerError: Retry run failed. Failed to clean up the failed pods from previous run.: InternalServerError: Failed to delete pods.: pods \"basic-training-rlq27-2856773258\" is forbidden: User \"system:serviceaccount:kubeflow:ml-pipeline\" cannot delete resource \"pods\" in API group \"\" in the namespace \"kubeflow\""}]}"
```

**Comment by numerology** [comment]
> This issue still happens with kubeflow 0.7.1. The error is
> 
> ```
> Failed to retry run: e8e1840f-4615-4327-b20c-85c98a981372 with error: "{"error":"InternalServerError: Retry run failed. Failed to clean up the failed pods from previous run.: InternalServerError: Failed to delete pods.: pods \"basic-training-rlq27-2856773258\" is forbidden: User \"system:serviceaccount:kubeflow:ml-pipeline\" cannot delete resource \"pods\" in API group \"\" in the namespace \"kubeflow\"","message":"InternalServerError: Retry run failed. Failed to clean up the failed pods from previous run.: InternalServerError: Failed to delete pods.: pods \"basic-training-rlq27-2856773258\" is forbidden: User \"system:serviceaccount:kubeflow:ml-pipeline\" cannot delete resource \"pods\" in API group \"\" in the namespace \"kubeflow\"","code":13,"details":[{"@type":"type.googleapis.com/api.Error","error_message":"Internal Server Error","error_details":"InternalServerError: Retry run failed. Failed to clean up the failed pods from previous run.: InternalServerError: Failed to delete pods.: pods \"basic-training-rlq27-2856773258\" is forbidden: User \"system:serviceaccount:kubeflow:ml-pipeline\" cannot delete resource \"pods\" in API group \"\" in the namespace \"kubeflow\""}]}"
> ```

@JakeTheWise FYI, Kubeflow is still using KFP 0.1.31 in their head version:
https://github.com/kubeflow/manifests/blob/master/pipeline/api-service/base/kustomization.yaml#L14

A workaround can be deploy KFP standalone as https://github.com/kubeflow/pipelines/tree/master/manifests/kustomize

**Comment by mattnworb** [comment]
@numerology seems like that has now been upgraded to KFP 0.2.0 https://github.com/kubeflow/manifests/commit/16c20a9cd736f168d82d161f2a5d82e127d518a9
