### ISSUE TITLE
KeyError for dsl.ContainerOp.after

### ISSUE THREAD

**Issue by mereldawu** [kubeflow/pipelines#2503]
**What happened:**

I am trying to specify the execution order of dsl.ContainerOp, but fail to compile during the kfp.compiler.Compiler() step if I add container_op1.after(container_op2).

I am on Kubeflow 0.6.2. 

**What did you expect to happen:**

Successfully compile the pipeline.

**What steps did you take:**

I followed the sdk examples, without `train.after(fe_bulk)` the pipeline compiles, but once added the .after receive a `KeyError feature_engineering_bulk`.

Code below:
(Although the code below may seem trivial, but this is just a snippet of a longer pipeline that has multiple conditions.)

```python
@dsl.pipeline(
    name='My Pipeline',
    description='Training an XGBoost Model.'
)
def pipeline_example( #pylint: disable=unused-argument
    bucket='my-gcp-bucket-name',
    raw_path='data/raw/',
    input_path='data/interim/',
    results_path='data/processed/',
    models_path='models/',
    version='1'
):
    fe_bulk = dsl.ContainerOp(
        name='feature_engineering_bulk',
        image='my-fe-image',
        command=['python', 'src/features/data_processing.py'],
        arguments=['--bucket', bucket, 
                   '--raw-path', raw_path,
                   '--input-path', input_path,
                   '--results-path', results_path,
                  '--output-path', '/tmp/data.txt'],
        file_outputs={'output_path': '/tmp/data.txt'}
    ).apply(gcp.use_gcp_secret('user-gcp-sa'))


    with dsl.Condition(fe_bulk.output == 'true'):
        train = dsl.ContainerOp(
            name='Train',
            image='my-train-image',
            command=['python', 'src/models/train_model.py'],
            arguments=['--bucket', bucket,
                       '--input-path', results_path,
                       '--models-path', models_path,
                       '--version', version,
                       '--output-path', '/tmp/data.txt'],
            file_outputs={'output_path': '/tmp/data.txt'}
        ).apply(gcp.use_gcp_secret('user-gcp-sa'))

        train.after(fe_bulk)
```

Error below:

```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-58-35ee86ca026c> in <module>
----> 1 kfp.compiler.Compiler().compile(pipeline_example, 'pipeline_example.tar.gz')

/opt/conda/lib/python3.6/site-packages/kfp/compiler/compiler.py in compile(self, pipeline_func, package_path)
    562       package_path: the output workflow tar.gz file path. for example, "~/a.tar.gz"
    563     """
--> 564     workflow = self._compile(pipeline_func)
    565     yaml.Dumper.ignore_aliases = lambda *args : True
    566     yaml_text = yaml.dump(workflow, default_flow_style=False)

/opt/conda/lib/python3.6/site-packages/kfp/compiler/compiler.py in _compile(self, pipeline_func)
    552     p.ops = sanitized_ops
    553 
--> 554     workflow = self._create_pipeline_workflow(args_list_with_defaults, p)
    555     return workflow
    556 

/opt/conda/lib/python3.6/site-packages/kfp/compiler/compiler.py in _create_pipeline_workflow(self, args, pipeline)
    449 
    450     # Templates
--> 451     templates = self._create_templates(pipeline)
    452     templates.sort(key=lambda x: x['name'])
    453 

/opt/conda/lib/python3.6/site-packages/kfp/compiler/compiler.py in _create_templates(self, pipeline)
    411     op_groups = self._get_groups_for_ops(new_root_group)
    412     inputs, outputs = self._get_inputs_outputs(pipeline, new_root_group, op_groups)
--> 413     dependencies = self._get_dependencies(pipeline, new_root_group, op_groups)
    414     groups = self._get_groups(new_root_group)
    415 

/opt/conda/lib/python3.6/site-packages/kfp/compiler/compiler.py in _get_dependencies(self, pipeline, root_group, op_groups)
    188 
    189       for op_name in unstream_op_names:
--> 190         upstream_op = pipeline.ops[op_name]
    191         upstream_groups, downstream_groups = self._get_uncommon_ancestors(
    192             op_groups, upstream_op, op)

KeyError: 'feature_engineering_bulk'

```

**Anything else you would like to add:**

I first defined the ContainerOp as kfp.components yaml file, and it gives the same KeyError.

**Comment by Ark-kun** [comment]
Can you please try updating the KFP SDK package?
AFAIK, this bug has already been fixed.

**Comment by Ark-kun** [comment]
I'm pretty certain that the issue is caused by KF 0.6.2 shipping with pretty ancient version of KFP SDK in the Notebooks.
Please update the SDK by executing `!python3 -m pip install --upgrade kfp --user`  and restart the kernel.

**Comment by ritabanchowdhury319** [comment]
I am running into the same issue while using Kubeflow 0.7 in GCP 
Trying to run named_entity_recognition example. Followed all the instructions and everything ran fine. When I am trying to make pipeline getting following error. Even after running !python3 -m pip install --upgrade kfp --user and restarting the kernel 
![Screen Shot 2019-12-05 at 8 55 29 AM](https://user-images.githubusercontent.com/56565560/70245184-aa8f7f00-1743-11ea-8633-e2254b182e11.png)

**Comment by Ark-kun** [comment]
@ritabanchowdhury319 
Your issue is different: Currently all output keys are converted to "pythonic" names that use underscores. JUst replace `output-x-uri` with `output_x_uri`. You can inspect the available keys by calling `print(preprocess_task.outputs)`

P.S. Please check the [Data passing tutorial](https://github.com/kubeflow/pipelines/blob/8dfa2d9/samples/tutorials/Data%20passing%20in%20python%20components.ipynb) on potentially easier way to pass data between components. Are you using python for the components?

**Comment by ritabanchowdhury319** [comment]
Thanks  Alex it worked
