### ISSUE TITLE
Duration of a retry run does not reflect how much the run actually takes

### ISSUE THREAD

**Issue by cwu24** [kubeflow/pipelines#2515]
**What happened:**
After I retry a failed run, the duration of the run shown on the UI on the takes into account of the time before the retry is triggered. For example, my first run fails 1 hour after it was triggered. I retry the run after 5 hours since it fails and takes another 1 hour until it finishes. Then, the duration shows as 7 hours rather than 2 hours.

**What did you expect to happen:**
Duration should show the total time the run is actually executed, or at least an indicator saying the run has been retried so it can be differentiated from the normal runs.

**What steps did you take:**
Pick a run to retry and check the duration on the UI after the retried run is done.

**Anything else you would like to add:**
Build commit: aab5a50
The duration is probably calculated using the difference between create time and finish time and retry update the finish time to when the retried run is done.

**Comment by Bobgy** [comment]
Thanks for the report, I will take a look when I have time.
