### ISSUE TITLE
Run links are broken in JupyterLab

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#252]
The links point to URLs like
    http://localhost:8080/user/av/files/pipeline#/runs/details/3c7ff7b0-de7e-11e8-bcc5-42010a800195
instead of 
    http://localhost:8080/pipeline#/runs/details/3c7ff7b0-de7e-11e8-bcc5-42010a800195

In Jupyter Notebook the links works fine.

There is the JupyterLab action plan concerning this: https://github.com/jupyterlab/jupyterlab/issues/5211

This should be a small change to https://github.com/jupyterlab/jupyterlab/blob/d908577e59fc6ba624138fb9119068b158186252/packages/rendermime/src/renderers.ts#L701 and they're willing to accept PRs

@yebrahim, Can you please look how hard is it to fix this bug in the JupyterLab's TypeScript code?

**Comment by vicaire** [comment]
Can this be close? Is it still an issue?

**Comment by rileyjbauer** [comment]
@Ark-kun is this still being seen?

**Comment by Ark-kun** [comment]
It might have been fixed by https://github.com/jupyterlab/jupyterlab/pull/5814 . I need to check.

**Comment by Ark-kun** [comment]
Still broken in the 0.1.21 release. I guess Kubeflow hasn't updated Jupyter yet.

**Comment by Ark-kun** [comment]
I've verified that the issue is finally fixed in KF.
