### ISSUE TITLE
Presubmit tests are leaking persistence disks

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#2523]
**What happened:**
Presubmit test failed with
```
 message: u"Instance 'gke-e2e-9e5b441-16593-default-pool-758b3c0e-fn98' creation failed: Quota 'DISKS_TOTAL_GB' exceeded.  Limit: 150000.0 in region us-east1.">]
 detail: u"Deploy error: Not all instances running in IGM after 49.778650849s. Expect 2. Current errors: [GCE_QUOTA_EXCEEDED]: Instance 'gke-e2e-9e5b441-16593-default-pool-758b3c0e-fn98' creation failed: Quota 'DISKS_TOTAL_GB' exceeded.  Limit: 150000.0 in region us-east1."
```

**What did you expect to happen:**
Persistence disks created in presubmit tests should be cleaned up periodically.

**What steps did you take:**
Go to https://pantheon.corp.google.com/compute/disks?organizationId=433637338589&project=ml-pipeline-test page to take a look at persistence disks.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Bobgy** [comment]
Clean up steps should be added in https://github.com/kubeflow/pipelines/blob/master/test/tools/project-cleaner/main.go

**Comment by Bobgy** [comment]
Command that deletes some unused disks
```
gcloud compute disks delete $(gcloud compute disks list --format='value(name)' --limit 1000 --filter='users="" and zone:us-east1-b') --zone us-east1-b --quiet
```

**Comment by Bobgy** [comment]
This is happening again in https://github.com/kubeflow/pipelines/issues/5021.

**Comment by Bobgy** [comment]
Deleted all leaked disks in one batch

**Comment by zijianjoy** [comment]
I found this article for using Cloud Functions to delete orphan and old persistent disks: https://cloud.google.com/architecture/automating-cost-optimizations-with-cloud-functions-cloud-scheduler-and-stackdriver#cleaning_up_unused_and_orphaned_persistent_disks

**Comment by zijianjoy** [comment]
persistent disk deletion via Go: https://cloud.google.com/go/docs/reference/cloud.google.com/go/latest/compute/apiv1#cloud_google_com_go_compute_apiv1_DisksClient_Delete
