### ISSUE TITLE
UI no longer shows job link and log link from GCP ML component

### ISSUE THREAD

**Issue by hlu09** [kubeflow/pipelines#2531]
**What happened:**
The code below generates very handy artifacts that will show up in KFP UI (0.1.26). However, after upgrading to 0.1.32, they no longer show up in UI.

https://github.com/kubeflow/pipelines/blob/master/components/gcp/container/component_sdk/python/kfp_component/google/ml_engine/_common_ops.py#L109

    display.display(display.Link(
        'https://console.cloud.google.com/mlengine/jobs/{}?project={}'.format(
            job_id, project_id),
        'Job Details'
    ))
    display.display(display.Link(
        'https://console.cloud.google.com/logs/viewer?project={}&resource=ml_job/job_id/{}&interval=NO_LIMIT'.format(
            project_id, job_id),
        'Logs'
    ))

**What did you expect to happen:**

KFP UI still shows them so that users can easy find logs and CMLE job links

**What steps did you take:**
[A clear and concise description of what the bug is.]
Version 0.1.32.  Launch CMLE job and then use wait-job https://github.com/kubeflow/pipelines/blob/master/components/gcp/container/component_sdk/python/kfp_component/google/ml_engine/_wait_job.py#L21

No job link or log link show up in the UI.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Ark-kun** [comment]
You need to explicitly declare the "MLPipeline UI metadata" output:

See
https://github.com/kubeflow/pipelines/blob/c063a050ed25310d784da73cd8c6d6cd548b6210/components/gcp/ml_engine/train/component.yaml#L102 and https://github.com/kubeflow/pipelines/blob/7b6957a/samples/core/lightweight_component/lightweight_component.ipynb

P.S. Please make sure your program can get the paths of that metadata JSON file from the command-line. Do not hard-code the path. This will make your component more future-proof.

**Comment by hlu09** [comment]
@hongye-sun Looks like the best way is to explicitly declare the "MLPipeline UI metadata" output inside ml_engine package. What do you think?

**Comment by Ark-kun** [comment]
> Looks like the best way is to explicitly declare the "MLPipeline UI metadata" output inside ml_engine package. What do you think?

All the components in `components/gcp/*` already have those outputs in the component definitions. I've linked to them.

What's your user scenario? If you write custom component code, then you need to explicitly specify the outputs in the component definition (either `component.yaml` or the function to which you apply `func_to_container_op`).

Can you please explain your scenario more?

**Comment by hlu09** [comment]
I am using wait-job function there. What is the good way to  declare the "MLPipeline UI metadata" output?  Thanks! 
        dsl.ContainerOp(
            name=name,
            image=wait_component_image,
            arguments=[
                "kfp_component.google.ml_engine",
                "wait-job",
                "--project_id",
                gcp_project_id,
                "--job_id",
                job_id,
                "--wait_interval",
                wait_interval_in_seconds,
            ],
        )

**Comment by Ark-kun** [comment]
```python
dsl.ContainerOp(
    ...
    file_outputs = {
        "mlpipeline-ui-metadata": '/mlpipeline-ui-metadata.json',
    },
)


>dsl.ContainerOp(

P.S. It's better to create a `component.yaml` definition of your component instead of instantiating the `ContainerOp`s directly. Creating components makes the definitions reusable and shareable.

**Comment by hlu09** [comment]
Cool!  It works. Thanks!
