### ISSUE TITLE
[GCP] ml-pipelines-ui needs to use workload identity on GCP

### ISSUE THREAD

**Issue by jlewi** [kubeflow/pipelines#2537]
The ml-pipelines UI when deployed as part of Kubeflow on GCP needs to be configured to use GCP workload identity.  This means it needs to be running using a Kubernetes Service Account(KSA) that is bound to a Google Service Account (GSA)

Here are some possible options

Here are possible options

## Option 1 - Use an existing KSA already bound to a GSA

In the kubeflow namespace kfctl create kubernetes service accounts

* kf-user
* kf-admin

which are bound to the GSA's ${KFAPP}-user@ and ${KFAPP}-admin respectively

So one solution would be for the pipelines UI to run with one of those service accounts 

In which case you would need to make sure that any RBAC permissions needed by pipelines is also granted to those service accounts.

Kubeflow uses [ClusterRole aggregation](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles) to aggregate application specific roles (e.g. roles needed by pipelines up to those roles).

## Option 2 use pipelines KSA and add a GSA workload identity binding

You could continue to use the ml-pipeline-ui service account but add logic e.g. in kfctl to add the appropriate workload identity bindings 

In 0.7 kfctl continued to provision GCP secrets in the kubeflow namespace to provide backwards compatibility (#1962). The ml pipeline UI is relying on this as a temporary fix (#2501).

But in the next Kubeflow release we will stop creating GCP secrets in the K8s cluster and rely entirely on workload identity.

@Bobgy  and @jessiezcc can we fix this in time for the next release i.e. by end of quarter?

Related:

#1691 - Uber tracking bug for workload identity in pipelines

**Comment by Bobgy** [comment]
done
