### ISSUE TITLE
[GCP] pipelines docs and samples need to be updated for workload identity

### ISSUE THREAD

**Issue by jlewi** [kubeflow/pipelines#2538]
In 0.7 Kubeflow is switching to relying on [workload identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) to provide pods with GCP credentials.

In 0.7 we are continuing to provision Kubernetes secrets (eg. `user-gcp-sa`) containing a Google Service Account (GSA) for backwards compatibility. We will stop provisioning those secrets though in the next release (kubeflow/kfctl#47).

ml-pipeline samples and docs will need to be updated to use workload identity.

Instead of attaching a secret and setting the environment variable  "GOOGLE_APPLICATION_CREDENTIALS", the pod should use a kubernetes service account which is bound to a Google service account with appropriate IAM roles.

kfctl and the profiles resource will automatically create KSA and bind them to appropriate GSA. So one option is for pipelines to just update the samples to use one of those service accounts.

For more info refer to the docs.
https://www.kubeflow.org/docs/gke/authentication/#starting-in-0-7-gke-workload-identity

Related to:
#1691 - workload identity support in pipelines
kubeflow/kfctl#47 - Stop provisioning secrets in the Kubernetes cluster

@SinaChavoshi and @jessiezcc can we get this done this quarter?

**Comment by numerology** [comment]
@Ark-kun Does kfp.dsl have a way to specify KSA in a pod?

**Comment by Ark-kun** [comment]
AFAIK we always use the `pipeline-runner` SA. @IronPan knows the details.

**Comment by rmgogogo** [comment]
@numerology @Ark-kun 
API side for now uses default KSA. (resource_manager.go L262). It can be specified via envar.
(https://github.com/kubeflow/pipelines/search?q=DefaultPipelineRunnerServiceAccount&unscoped_q=DefaultPipelineRunnerServiceAccount)

To let the workload identity be isolated, we need DSL side changes to allow user specify other KSA and handle over to server side when creating a run.

For now, this ticket just to track doc/sample for WI.

**Comment by Bobgy** [comment]
already updated
