### ISSUE TITLE
Delete or update outdated deployer component for TFServing

### ISSUE THREAD

**Issue by jlewi** [kubeflow/pipelines#2542]
There is a pipeline component to deploy models for TFServing here
https://github.com/kubeflow/pipelines/tree/ba64bd3866023c36c93cf2b46a066a1b008bb6c4/components/kubeflow/deployer

But it looks very outdated

* It is using ksonnet and the old TFServing ksonnet component which has long since been deleted

I'm classifying this as a P1 bug as I suspect this component doesn't work since its so outdated and the ksonnet package has likely been deleted.

/cc @jinchihe @animeshsingh

**Comment by jinchihe** [comment]
Agree, we can use KFServing to do last mile for model serving, that's common and easy using.

**Comment by gaoning777** [comment]
This component is still working since the sample test covers this kubeflow-serving.
Now we have seldon samples for the serving. We could potentially remove this one after adding the seldon serving in the core samples. 
@jinchihe Would you mind adding the sample test for the seldon samples?
/assugn @jinchihe 
/unassign @gaoning777

**Comment by jinchihe** [comment]
@gaoning777 Why not using KFServing to deploy serving in the sample? Thanks.

**Comment by Bobgy** [comment]
/lifecycle frozen

/cc @numerology @chensun 
I just found this issue and looks like we should delete the tf serving sample.

**Comment by numerology** [comment]
Sounds good. Should we use new KF serving instead?

**Comment by Bobgy** [comment]
@jinchihe @animeshsingh will you be interested in contributing a kfserving sample?

From my understanding, that requires a kfserving install to properly run, so we need to run it in full Kubeflow, is that right?
