### ISSUE TITLE
VolumeOp with ReadWriteMany fails to provision on AWS

### ISSUE THREAD

**Issue by karlschriek** [kubeflow/pipelines#2548]
**What happened:**

Upon creating a small pipeline like this the PVC cannot be bound on EKS:

@kfp.dsl.pipeline(name="test", description="blah")
def dev_evaluation_pipeline():

    vop = kfp.dsl.VolumeOp(
        name="my_pvc",
        resource_name="new_pvc",
        size="10Gi",
        modes=kfp.dsl.VOLUME_MODE_RWM )

        download_images_task = download_images_op( ...) .add_pvolumes({"/images": vop.volume})

  `kubectl -n kubeflow describe persistentvolumeclaim/test-7ps7q-new-images-pvc` yields:

```
Failed to provision volume with StorageClass "gp2": invalid AccessModes [ReadWriteMany]: only AccessModes [ReadWriteOnce] are supported
```

This is because by default Kubernetes only supports EBS volumes. To have ReadWriteMany you would need EFS, for which you need to deploy an EFS Provisioner. Shouldn't this be something that is deployed automatically when Kubeflow is installed on an EKS cluster?

**Comment by Ark-kun** [comment]
> Shouldn't this be something that is deployed automatically when Kubeflow is installed on an EKS cluster?

Currently we do not have platform-specific configurations in the deployment.
What is the effort required to deploy the provisioner?

**Comment by Ark-kun** [comment]
BTW, What's your use case for creating volumes?

Please check the tutorials for big data passing for python and non-python components https://github.com/Ark-kun/kfp_samples/blob/master/2019-10%20Kubeflow%20summit/104%20-%20Passing%20data%20for%20python%20components/104%20-%20Passing%20data%20for%20python%20components.ipynb https://github.com/Ark-kun/kfp_samples/blob/master/2019-10%20Kubeflow%20summit/106%20-%20Creating%20components%20from%20command-line%20programs/106%20-%20Creating%20components%20from%20command-line%20programs.ipynb

**Comment by karlschriek** [comment]
Well, the real use case I suppose is that the using for insample InputPath / OutputPath provisions disk space that eventually runs out, you've already provided an answer to my separate question on that here https://github.com/kubeflow/pipelines/issues/2545

Deploying the provisioner is not entirely straightforward. There is an EFS Provisioner deployment available here https://github.com/kubernetes-incubator/external-storage/tree/master/aws/efs. Deploying it is simple enough, but are some holes in the instructions with respect to setting up permissions on AWS side to get it up and running.

**Comment by eterna2** [comment]
It is non trivial. A more detailed instruction can be found here:

https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html

**Comment by LeonardAukea** [comment]
@karlschriek  Are you aware that you can specify `storage_class: 'efs'`  in `kfp.dsl.VolumeOp`
https://github.com/kubeflow/pipelines/blob/e704067d156ad9aec292c5af4ebc6d9c6cbfc209/sdk/python/kfp/dsl/_volume_op.py#L43
That works for me at least.
