### ISSUE TITLE
Add an icon button to start experiment from pipeline list

### ISSUE THREAD

**Issue by ajayalfred** [kubeflow/pipelines#256]
Explore icon button shortcut in the pipeline list row to start an experiment directly from this page.

**Comment by ajayalfred** [comment]
Add overflow menu for this action and other pipeline actions at the end of the row. Explore surfacing one primary action next to overflow as icon button.

**Comment by vicaire** [comment]
@rileyjbauer, is there anything left to do on this one?

**Comment by rileyjbauer** [comment]
We do not currently support this gesture, so the issue should remain open, unless there isn't actually a desire for this feature. Do you know if this is still something we want?

**Comment by ajayalfred** [comment]
Based on our most recent discussion about Experiments/Workspaces, this shortcut will be a simple 'Create run' from the pipelines list and NOT to create an experiment. See screenshots for context.

![image](https://user-images.githubusercontent.com/2425179/55104852-6ca46c00-5088-11e9-8588-108f5b013945.png)

![image](https://user-images.githubusercontent.com/2425179/55104832-62826d80-5088-11e9-9537-5f8b82168c4e.png)

**Comment by Bobgy** [comment]
/close
This has been implemented as top toolbar
