### ISSUE TITLE
Pipelines UI: Logs window content is lost when output has 'curses'-like logging

### ISSUE THREAD

**Issue by amygdala** [kubeflow/pipelines#2560]
When a pipeline step's output uses 'curses'-like cursor manipulation*, as is the case when running a keras `model.fit()` training job, the logging window doesn't handle this well -- the logged output prior to this line is  'lost' , or at least no longer visible.

I assume this will be a common glitch, as many will include keras training as part of a pipeline.

If this is hard to fix, maybe we could at least include a link to the stackdriver logs under all circs, not just if the pod has been deleted.

*Not sure of the common term for this behavior.  What I mean is that rather than generate successive new lines, the output just continually rewrites one line by moving the cursor.
If you don't know what I'm talking about :), I can share an example that shows it.

**Comment by Bobgy** [comment]
An example and also a screenshot how it looks like in UI now would be helpful.

Besides, consistently showing stackdriver link is a common ask. I will do that nevertheless.

**Comment by amygdala** [comment]
Here is what this looks like.  Initially the logs look normal:

<img width="923" alt="Screenshot 2019-11-08 12 51 40" src="https://user-images.githubusercontent.com/115093/68510198-b3b22c80-0227-11ea-945f-8d296c36cba0.png">

Then after some period of time, the log output looks like this, with the output of the previous screenshot no longer available.  (but, the cursor is not moving/rewriting as you would see in a terminal):
<img width="1214" alt="Screenshot 2019-11-08 12 59 13" src="https://user-images.githubusercontent.com/115093/68510216-c2004880-0227-11ea-8fbe-3f15197346d4.png">

I'll update again soon w/ a pipeline example that shows this.  But a Keras training job of any reasonable length would probably flush it out.

**Comment by Bobgy** [comment]
This looks strange, I'm not sure it's a bug in UI.

and thanks, an example pipeline I can run will be the best.

**Comment by amygdala** [comment]
> I'm not sure it's a bug in UI.

Well, it doesn't behave like a terminal window, but it's not clear that it necessarily should. 

Try running this example to see it in action: https://github.com/amygdala/code-snippets/blob/sbtb/ml/kubeflow-pipelines/sbtb/example_pipelines/bw.py
Specify some GCS path for the working_dir and keep the other defaults.

**Comment by marrrcin** [comment]
The same happens when you use tqdm lib (https://tqdm.github.io/) for terminal progress bars (and writing to stdout). Kubeflow UI does not show the output properly.

**Comment by Bobgy** [comment]
Sorry I don't currently have time to look into this. I tried @amygdala's sample, but it needed GPUs to run. I don't know how to configure that yet

**Comment by Bobgy** [comment]
I followed @amygdala's instruction and removed the gpu limit there. Now I see the output.

Basically, when you use curses like logging, the log is too long that k8s doesn't handle it well. UI uses the same mechanism to get log like `kubectl logs` and it cannot show full log too in this case. Log can be viewed on stackdriver, I will
* [ ] Always show a stack driver link
* We cannot support this feature in our UI because k8s cannot handle it

**Comment by jtlz2** [comment]
@amygdala @bobgy I use tqdm when doing the training interactively. Is there a good way to disable it when it's running inside kubeflow rather than when the component is being run standalone/locally in a notebook?

**Comment by Bobgy** [comment]
@jtlz2 I don't think the question is related to Kubeflow though.
Consider adding a special flag / env var that your program recognizes and do not use tqdm?
