### ISSUE TITLE
Metadata UX - Artifacts and Executions should be grouped based on Metadata Context

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#2562]
Currently, UX ignores context of artifacts and executions and groups based on different properties.

**Comment by Bobgy** [comment]
@Ark-kun thanks for the idea, can you clarify what is context?

**Comment by Ark-kun** [comment]
> @Ark-kun thanks for the idea, can you clarify what is context?

Context is a generalization of run - a grouping of Executions. https://github.com/google/ml-metadata/blob/ed9f5729185622ab1cef226e484f2e8cee5f4995/ml_metadata/proto/metadata_store.proto#L201
Execution is connected with Context through Association.
Artifact is connected with Context through Attribution.
Artifact is connected with Execution through Event.

**Comment by Bobgy** [comment]
Thanks, I am trying to understand. After taking a look at the proto file https://github.com/google/ml-metadata/blob/ed9f5729185622ab1cef226e484f2e8cee5f4995/ml_metadata/proto/metadata_store.proto#L191

It seems there could be many context types. Are you proposing we group by run context type?

**Comment by Ark-kun** [comment]
I think we'll have a single common context type like 'run', so we do not need to group by that.

I think that just joining `Context <- Association -> Execution` is enough.
For artifacts we can do either
`Context <- Attribution -> Artifact`
or
`Context <- Association -> Execution <- Event -> Artifact` (event has `.path` that might be needed).

**Comment by Ark-kun** [comment]
This issue becomes urgent since TFX has recent changes that will stop adding the `pipeline_name` property to the artifacts (initially it will still be available as custom property).
This will cause the artifacts to stop being grouped.

**Comment by Bobgy** [comment]
So required data are all available with KFP 0.1.40 using tfx taxi sample, is that right?
I will investigate this soon

**Comment by Bobgy** [comment]
Looks like this is already supported in recent lineage changes.
/close

**Comment by Bobgy** [comment]
/reopen
actually, the fix didn't put run context as first priority

**Comment by Bobgy** [comment]
/close
implemented
