### ISSUE TITLE
Metadata UX - Artifacts and Executions should probably be grouped by run_id not pipeline_name

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#2564]
Currently, when you run pipeline multiple times, everything is put in the same group.
We should probably group by run, not by pipeline.
WDYT, @neuromage

**Comment by Bobgy** [comment]
This sounds reasonable. Is data already available in MLMD?

**Comment by Bobgy** [comment]
actually, this seems superceded by https://github.com/kubeflow/pipelines/issues/2562
/close
