### ISSUE TITLE
UI feature ask: Search experiments and runs

### ISSUE THREAD

**Issue by SinaChavoshi** [kubeflow/pipelines#257]
There is no way to search for runs or experiments, as the list of experiments grow it becomes very difficult to find the related experiments. search or filter would be very useful.

**Comment by yebrahim** [comment]
We can use this issue to track the frontend work needed for this, I opened https://github.com/kubeflow/pipelines/issues/270 to track the API support.

**Comment by vicaire** [comment]
@rileyjbauer, is there any work left on this once? Can we close?

**Comment by rileyjbauer** [comment]
We currently support searching by name for experiments, runs, and pipelines.
We intend to expand this filtering to other columns in the future, but this issue can be closed.
