### ISSUE TITLE
ParallelFor parameter parsing does not retain user input format

### ISSUE THREAD

**Issue by karlschriek** [kubeflow/pipelines#2570]
When running a pipeline with a ParallelFor condition over a list of dictionaries, camelCase and snake_case inputs are altered.

This won't work:

    with kfp.dsl.ParallelFor([{"helloWorld": "blah"}]) as item:
        my_op(item.helloWorld)

    with kfp.dsl.ParallelFor([{"hello_world": "blah"}]) as item:
        my_op(item.hello_world)

If I am reading this correctly, then the `my_op` is parsing `item.hello_world` as `item.hello-world` (and `helloWorld` as `helloworld`. However, the ParallelFor operation isn't  performing the same parsing. (I presume it is delivering `item.hello_world`, exactly as written in the dictionary, but I cannot confirm this).

The following works correctly:

    with kfp.dsl.ParallelFor([{"helloworld": "blah"}]) as item:
        my_op(item.helloWorld)

    with kfp.dsl.ParallelFor([{"hello-world": "blah"}]) as item:
        my_op(item.hello_world)

**Comment by numerology** [comment]
Thanks for reporting. It seems like the sanitization of var name is not consistent b/w the declaration of the loop var and its usage. We'll fix it quickly.

**Comment by hongye-sun** [comment]
Instead of being smart to sanitize the name here, I feel it's better to add constraint on the key names of the dictionary and add validation in DSL compiler.

**Comment by numerology** [comment]
> Instead of being smart to sanitize the name here, I feel it's better to add constraint on the key names of the dictionary and add validation in DSL compiler.

Either way sounds good to me. One nit issue, if we enforce the convention of k8s naming, the user need to access a attribute in a way like `item.prefix-suffix`, but that's not possible in python.

So do which naming convention we want to pick? Or actually, I feel like the easiest way is to block the usage of `-` and `_`

**Comment by hongye-sun** [comment]
I wonder if we should use dict here instead of attribute?

**Comment by numerology** [comment]
> I wonder if we should use dict here instead of attribute?

+1

**Comment by numerology** [comment]
Keep this open until a better solution

**Comment by numerology** [comment]
Memo: there are a following workitems to optimize the code
- [ ] Refactor the sanitization into the compiler and minimize the level of sanitization.
