### ISSUE TITLE
Load/Perf test for Pipeline API server

### ISSUE THREAD

**Issue by IronPan** [kubeflow/pipelines#2571]
Since this is mostly cared in production scenarios, we should prioritize CloudSQL/GCS test over in-cluster storage.

Related issues
https://github.com/kubeflow/pipelines/issues/2071

**Comment by rmgogogo** [comment]
Move to Jing's queue and put to KFP 1.0.

Jing, feel free to mark as duplicated as you may also created one.

**Comment by jingzhang36** [comment]
Merge this to https://github.com/kubeflow/pipelines/issues/3259. Close this one as duplicate.
