### ISSUE TITLE
rename mysql and Minio with more pipeline prefix

### ISSUE THREAD

**Issue by hougangliu** [kubeflow/pipelines#2578]
**What happened:**
Now when I install kubeflow, I cannot find which components belongs to `pipelines` based on deployment name.
**What did you expect to happen:**
In fact, mysql and Minio also belongs to `pipelines`, we had better to make their name with pipeline prefix

**What steps did you take:**
[A clear and concise description of what the bug is.]

```
# kubectl get deploy|grep ml-
ml-pipeline                                         1         1         1            1           25h
ml-pipeline-ml-pipeline-visualizationserver         1         1         1            1           25h
ml-pipeline-persistenceagent                        1         1         1            1           25h
ml-pipeline-scheduledworkflow                       1         1         1            1           25h
ml-pipeline-ui                                      1         1         1            1           25h
ml-pipeline-viewer-controller-deployment            1         1         1            1           25h
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Bobgy** [comment]
@hougangliu 
What's your use case? Would adding a common label work for you. I think labels are designed to support this.

https://github.com/kubeflow/manifests/blob/4763c64a85d088c06169b9597ed4f58f9bb536ba/pipeline/api-service/base/kustomization.yaml#L4

@IronPan Do you have any concerns changing deployment names in Kubeflow? I think we don't expose Kubeflow manifests and there's no upgrade support yet. So we can still make the change.

What do you think?

**Comment by hougangliu** [comment]
@Bobgy in fact, when I install kubeflow and check each Pod, I can know most Pod's kubeflow component by Pod name, but for Minio and mysql, it confuse me. I think we should rename them before Kubeflow 1.0, after then, it would cause complexity for upgrade case.
BTW, I think effort of renaming it is not big for now

**Comment by Bobgy** [comment]
@hougangliu I agree with your arguments. Pod name is easier to see.

**Comment by Bobgy** [comment]
@IronPan What's your opinion?

**Comment by IronPan** [comment]
I don't have very strong opinion. But note the work to rename a deployment won't be trivial. 
I think mysql in theory shouldn't just belong to pipeline. Katib also creates a in-cluster mysql and by talking with @richardsliu it seems make sense to dedup. 

I think a good approach is to add the labels for the resources to indicate what the component belongs. Shared components can have multiple such labels.

**Comment by Bobgy** [comment]
@IronPan I think different applications should better use their own instance of mysql. One of the issues for sharing is, they may have different security requirements. When KFP supports multi user, it will block all external traffic to the mysql.

Coordinating several applications' usage of the mysql db would need a more complex security solution to separate their privileges.

**Comment by Bobgy** [comment]
I think we still want this open.

**Comment by rimolive** [comment]
This is is opened for more than a year, but so far the Manifests WG adopted the common labels approach that's used in other components. I'll close this issue but if you think it needs more input from the community we can reopen.

/close
