### ISSUE TITLE
don't have 'resources' key in ContainerSpec

### ISSUE THREAD

**Issue by zyfzjsc988** [kubeflow/pipelines#2579]
**What happened:**

In pipelines/sdk/python/kfp/components/_structures.py/ 
there is no 'resources' key in ContainerSpec class;

_**but if a component doesn't limit resources, how can many pipelines run together with the right resources scheduling.**_ 

class ContainerSpec(ModelBase):
    '''Describes the container component implementation.'''
    _serialized_names = {
        'file_outputs': 'fileOutputs', #TODO: rename to something like legacy_unconfigurable_output_paths
    }
    def __init__(self,
        image: str,
        command: Optional[List[CommandlineArgumentType]] = None,
        args: Optional[List[CommandlineArgumentType]] = None,
        env: Optional[Mapping[str, str]] = None,
        file_outputs: Optional[Mapping[str, str]] = None, #TODO: rename to something like legacy_unconfigurable_output_paths
    ):
        super().__init__(locals())

**What did you expect to happen:**

add RESOURCES key as k8s did.

**What steps did you take:**
[A clear and concise description of what the bug is.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Ark-kun** [comment]
Hello, Joy.

The components specifications are designed to be portable.
Resource requirements are usually only applicable when we know something about input arguments for an instance of some component - a task.
Thus the resource requirements are usually specified by the pipeline authors, on specific instance of components.

`resources` can be set on the `.container.resources` property of the component instance:
 `some_task1.container.resources = {...}`. You can also use `add_resource_request` and `add_resource_limit` methods (e.g. `some_task1.container.add_resource_request('cpu', 1)`. ).
