### ISSUE TITLE
Can't find kustomization dir for standalone KFP

### ISSUE THREAD

**Issue by JakeTheWise** [kubeflow/pipelines#2581]
Following the steps [here](https://www.kubeflow.org/docs/pipelines/standalone-deployment-gcp/#deploying-kubeflow-pipelines-standalone-from-scratch), specifically step 4, `kubectl apply -k github.com/kubeflow/pipelines//manifests/kustomize/env/dev?ref=0.1.33`, yields `Got a Retry-After 1s response for attempt 1 to https://35.225.197.210/openapi/v2?timeout=32s`.

**Comment by Bobgy** [comment]
I tried once and got a similar error:
```
unable to recognize "github.com/kubeflow/pipelines//manifests/kustomize/env/dev?ref=0.1.33": Get https://35.229.178.96/api?timeout=32s: error executing access token command "/usr/lib/google-cloud-sdk/bin/gcloud config config-helper --format=json": err=exit status 1 output= stderr=Reauthentication required.
ERROR: gcloud crashed (AttributeError): 'ReauthUnattendedError' object has no attribute 'message'
```

It's because you need to authenticate kubectl with gcloud. The command to authenticate is `gcloud auth login`. I'm not sure if that's the problem you met.

I will add this step to documentation if that's the problem.

**Comment by Bobgy** [comment]
@JakeTheWise can you try above command and retry there? Does it solve it?

Is there any further error message besides the part you pasted?

**Comment by JakeTheWise** [comment]
I ran `gcloud auth login` and also ensured my `kubectl` was configured to the proper cluster, but I am still getting the same error.

**Comment by Bobgy** [comment]
@JakeTheWise this is strange. Did you try if other `kubectl` commands work? Like `kubectl get namespace`?
And can you provide your `kubectl version`?

**Comment by JakeTheWise** [comment]
I got things to work by running the commands on a cloud shell in GCP connected to my cluster. I'm still unsure why it didn't work from my local machine; maybe something to do with our enterprise firewall? Idk. But I think I can close this issue as I'm confident now it isn't kfp-related...
