### ISSUE TITLE
Tensorboard artifact not working

### ISSUE THREAD

**Issue by JakeTheWise** [kubeflow/pipelines#2582]
Tensorboard artifact is broken, it gives me `Error occured while trying to proxy to: kubeflow.endpoints.PROJECTID.cloud.googviewer-c8f77f09de96f6cffdb078d7630578b0a1dbdcda-service.kubeflow.svc.cluster.local:80/tensorboard/viewer-c8f77f09de96f6cffdb078d7630578b0a1dbdcda/`

EDIT: using KFP v 0.1.33

**Comment by numerology** [comment]
Hi,

Recent upgrade of TB is a breaking change. We've fixed that in #2440 . Can you specify which KFP version are you using? Thanks!

**Comment by JakeTheWise** [comment]
using KFP v 0.1.33

**Comment by numerology** [comment]
> using KFP v 0.1.33

The fix should already be included in 0.1.33. One possible transient issue could be the viewer pod is still being provisioned. Could you please confirm this problem is still there after several retries? Thanks!

**Comment by numerology** [comment]
Friendly ping @JakeTheWise  Are you still observing this issue?

**Comment by rmgogogo** [comment]
didn't reproduce in latest release. turn to P2 and keep open for Jake's reply.

**Comment by numerology** [comment]
Mark as closed for now. Feel free to re-open if needed.

**Comment by JakeTheWise** [comment]
I am still observing this issue with kubeflow version 0.7. Inspecting the tensorboard container says it's running tensorboard 1.8 — although the containerOp running it has a base image running tensorboard 2.1.

**Comment by numerology** [comment]
> I am still observing this issue with kubeflow version 0.7. Inspecting the tensorboard container says it's running tensorboard 1.8 — although the containerOp running it has a base image running tensorboard 2.1.

Yes because Kubeflow 0.7 is using a really old version of KFP. This exact bug is fixed in KFP version > 0.1.40 already.

**Comment by kim-sardine** [comment]
please check stackdriver log of `viewer-###-service` in [here](https://console.cloud.google.com/kubernetes/discovery)

maybe this is related to https://github.com/kubeflow/kubeflow/issues/4735
