### ISSUE TITLE
FR: dry-run validation. apparent issue in terminating a pipeline run via UI whose first step is stuck in 'ImagePullBackOff'

### ISSUE THREAD

**Issue by amygdala** [kubeflow/pipelines#2588]
I have a pipeline run whose first step is stuck in `ImagePullBackOff` (due to my specifying the wrong container).  
I don't seem to be able to actually terminate this pipeline run via the UI, despite the fact that I get a little popup indicating that termination was successful.  If I look the pod via kubectl, it hasn't been deleted and is still in that state.
(I'm wondering if the bug is related to having no workflow pods actually `Running` yet?)

(This is with whatever Pipelines version is bundled w/ KF 0.6.2)

**Comment by rmgogogo** [comment]
"due to my specifying the wrong container"
hi Amy, would you help add me to your GCP project and give me the pipeline codes? Didn't get the meaning of "wrong container".

**Comment by amygdala** [comment]
sorry -- I just meant: in my component definition, I'd accidentally used a container registry link that the project did not have access to, so it was stuck repeatedly trying to d/l the container.  Therefore the pod never did get to the 'running' stage. 
(I've long since deleted the workflow run, but it would be easy for you to repro).

**Comment by rmgogogo** [comment]
Got it. Thanks.
We need some validations/dry-run when user upload pipelines.
I'm organize/plan the issues/workloads. Will update later. Here mark as triaged first.
