### ISSUE TITLE
Perf issue - All runs page loads very slowly with >100 runs 

### ISSUE THREAD

**Issue by SinaChavoshi** [kubeflow/pipelines#259]
I have about 500 runs in in one experiment, it takes about 3-5 seconds for the all runs page to load.

**Comment by rileyjbauer** [comment]
@IronPan, to get the experiment name and pipeline name we have to make a separate call for each, for every run.

IIRC, the issue is that there were some concerns around how updates would work if the names were stored within the run itself?

**Comment by yebrahim** [comment]
There's been some discussion on this in https://github.com/kubeflow/pipelines/issues/149.
I'll close this as a dup, but it's good to push the original issue. :)
