### ISSUE TITLE
Unable to create Jupiter notebook server in different namespaces.

### ISSUE THREAD

**Issue by abramovi** [kubeflow/pipelines#2602]
**What happened:**
Kubeflow Jupiter Notebook only allow me to create server in "admin" namespace.
**What did you expect to happen:**
see all namespace available  
![image](https://user-images.githubusercontent.com/770839/68788675-882aaa00-064c-11ea-842a-083d7c4e31a0.png)

**Comment by jessiezcc** [comment]
@jlewi to help triage this one

**Comment by jlewi** [comment]
This is working as intended. The namespace selector will only show Kubeflow namespaces you have access to.

There's more info on our docs here
https://www.kubeflow.org/docs/other-guides/multi-user-overview/#managing-contributors-through-ui

If you have an existing namespace not created by a profile you can create role bindings as mentioned on that page to share it with a user.

If you can I would suggest using namespaces created by the profile resource. If you try to use an existing namespace that will likely like not have all the resources that are expected in a Kubeflow namespace (i.e. various service accounts and role bindings).

If you have an existing namespace you could try creating a profile resource that would map to that namespace. I believe that would create all the required resources in that namespace. If it doesn't that's probably something we should fix.

/cc @kunmingg
