### ISSUE TITLE
packages_to_install parameter in func_to_container_op not working

### ISSUE THREAD

**Issue by abramovi** [kubeflow/pipelines#2605]
I am unable to use func_to_container_op with packages_to_install parameter.

got :

TypeError: func_to_container_op() got an unexpected keyword argument 'packages_to_install'

**Comment by numerology** [comment]
Hi @abramovi  can you let me know which version of KFP you have? Thanks

**Comment by Ark-kun** [comment]
Please update the SDK by running `python3 -m pip install --upgrade kfp --user`.
