### ISSUE TITLE
TFJob version out of date

### ISSUE THREAD

**Issue by ryandawsonuk** [kubeflow/pipelines#2615]
[TFJob is now](https://www.kubeflow.org/docs/components/training/tftraining/) `apiVersion: kubeflow.org/v1` - that's the version you get when you install kubeflow. Several components and examples [still use v1alpha2](https://github.com/kubeflow/pipelines/search?q=v1alpha2&unscoped_q=v1alpha2) and v1beta1. With the new kubeflow you get an error if you try to deploy a TFJob of that version.

**Comment by jessiezcc** [comment]
@jlewi to triage this one

**Comment by jlewi** [comment]
@jessiezcc what's the question? TFJob went v1 in 0.6 I think. So examples and components should be updated.

@jessiezcc  does someone on your team want to update the TFJob launcher or should we just delete it?

**Comment by Ark-kun** [comment]
@jlewi Is there any place where I can see the API breaking changes for TFJob?
Otherwise I'll just bump the version.

**Comment by Ark-kun** [comment]
> [TFJob is now](https://www.kubeflow.org/docs/components/training/tftraining/) `apiVersion: kubeflow.org/v1` - that's the version you get when you install kubeflow. Several components and examples [still use v1alpha2](https://github.com/kubeflow/pipelines/search?q=v1alpha2&unscoped_q=v1alpha2) and v1beta1. With the new kubeflow you get an error if you try to deploy a TFJob of that version.

Thanks for the report. I've bumped the TFJob version in the component. https://github.com/kubeflow/pipelines/pull/2617

Do you think there are more changes needed when upgrading to v1?
