### ISSUE TITLE
Input Validation and DryRun

### ISSUE THREAD

**Issue by rmgogogo** [kubeflow/pipelines#2621]
(1) In FE when input a parameter, it can be typed and validated and has hint msg.
(2) In BE we need to provide a dry-run API before/in uploading a pipeline (e.x. it's possible user made a pipeline which has no permission to read the docker image). Dry-run can check these. SDK can trigger the Dry-Run before upload the pipeline.

**Comment by numerology** [comment]
Imagine we have a multi-step pipeline, in dry run what should be the input of the downstream steps when the upstreams steps are not really executed?

I think a more general question is, what is the scope of dry-run checks?

**Comment by Ark-kun** [comment]
> (2) In BE we need to provide a dry-run API before/in uploading a pipeline (e.x. it's possible user made a pipeline which has no permission to read the docker image). Dry-run can check these. SDK can trigger the Dry-Run before upload the pipeline.

We do compile-time type checks in SDK.
The pipeline arguments are not checked right now.
Solving https://github.com/kubeflow/pipelines/issues/2534 can fix that issue.

**Comment by Bobgy** [comment]
https://github.com/kubeflow/pipelines/issues/1183 gave more context about why this would be useful.
