### ISSUE TITLE
IAP SA token expires, but the Client does not detect or refresh it

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#2625]
When working from a [JAAS] notebook, the created Client objetc works for some time, but if you step away for an hour, it stops working. The only way to fix that is to re-create the Client object.
I think we should fix that and have Client check and refresh the token on failure.

```python
client.list_pipelines()
```
>{'next_page_token': None, 'pipelines': None, 'total_size': None}

```
curl https://www.googleapis.com/oauth2/v1/tokeninfo?access_token=ya29.c.KmG...Gp
{
  "error": "invalid_token",
  "error_description": "Invalid Value"
}

```

**Comment by gaoning777** [comment]
To clarify, the SDK will fetch new access tokens. However, refresh tokens are not refreshed. Usually, refresh tokens do not expire. In cases when users have not used the refresh token once for six month, it expires.

**Comment by Ark-kun** [comment]
> To clarify, the SDK will fetch new access tokens. However, refresh tokens are not refreshed. Usually, refresh tokens do not expire. In cases when users have not used the refresh token once for six month, it expires.

This issue is about significantly more frequent expiration (~10 minutes or less).

**Comment by gaoning777** [comment]
'''
curl https://www.googleapis.com/oauth2/v1/tokeninfo?access_token=ya29.c.KmG...Gp
{
  "error": "invalid_token",
  "error_description": "Invalid Value"
}
'''
This is misuse of the token. The tokens stored are not intended to be used manually in curl. If really needed, one needs to get the access token through curl command and then use the access token for api requests.

**Comment by Ark-kun** [comment]
@gaoning777 Remember, we've investigated this issue. We got the full REST client configuration and then used curl to verify that the issue is being caused by a fast-expiring token.

**Comment by Ark-kun** [comment]
> @gaoning777 Remember, we've investigated this issue. We got the full REST client configuration and then used curl to verify that the issue is being caused by a fast-expiring token.

Client is getting the token, but it's short-lived and the Client never refreshes it.

**Comment by Ark-kun** [comment]
Updated the title and description.
