### ISSUE TITLE
[FeatureRequest] Add the ability to concatenate strings at the pipeline level

### ISSUE THREAD

**Issue by tanguycdls** [kubeflow/pipelines#2632]
Hi, in our use case we would like to format paths inside the pipeline dynamically given the inputs of a pipeline. We do that to keep our components path agnostic and let the pipeline decide where we store the data. 

For now we use a container op that takes all the inputs of the pipeline as param and output all the paths in a namedtuple. 

We would like to be able to concatenate strings (PipelineParams) and pass them to the operator (does not work the compiler breaks). 
We tried using {{worflow.parameters.<NAME>}} as described in https://github.com/argoproj/argo/blob/master/docs/variables.md but it doesnot work also only uid seems to be accepted. 

```
def test(path):
    print(path)
TEST = func_to_container_op(test, base_image=SMALL_DOCKER_IMAGE)
PIPE_ID = "{{workflow.uid}}"
PIPE_VAR_a = "{{worflow.parameters.a}}"
PIPE_ANNOTATIONS = "{{worflow.annotations}}"

def pipe(a, b):
    TEST(f"{PIPE_ID}") # works display the uid
    TEST(f"{PIPE_VAR_a}") # does not work
    TEST(f'{PIPE_ANNOTATIONS}') # does not work
    TEST(a)
# pipe is called as a pipeline
```
Could we do something like 
`a+'/test/'+b
`

Thanks, 
Best,

**Comment by eterna2** [comment]
U can do it this way.

```
var concated = "%s%s" % (a, b)
```

Where a and b are pipeline params. The compiler will serialize them properly.

**Comment by tanguycdls** [comment]
Ok thanks a lot ! Did not think of trying that one. It works with {} and format or %s.
