### ISSUE TITLE
MKP installation should use GCS instead of Minio

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#2649]
Minio Persistent Volume is pretty small and hard to access for the users.

**Comment by Bobgy** [comment]
Also cc @rmgogogo 

I think that's a good idea. Can we only offer managed storage for MKP installation? It will be easier to maintain for users I believe.

**Comment by rmgogogo** [comment]
it's already on track in MKP. For MKP feature, please use b/. Here close this one.

**Comment by Ark-kun** [comment]
> it's already on track in MKP.

Is this feature already implemented in MKP?
