### ISSUE TITLE
Cron Scheduler timezone is set to always be UTC, should be local timezone for the cluster

### ISSUE THREAD

**Issue by NikeNano** [kubeflow/pipelines#2653]
**What happened:**
When scheduling a pipeline using a cron expression the job are not run on the expected time. The hours are not aligned between the displayed time in the UI(correct time and local timezone in my case) and the execution of the cron jobs.
 
**What did you expect to happen:**
I was expecting the cron job to be executed at 10:15 when i set it to 
``` 0 15 10 * * ? ```, this is not the case. Instead i have to set this to ```0 15 9 * * ?```. I seams to be a difference in the set timezones.... 

**What steps did you take:**
I have scheduled a Kubeflow pipeline to execute once a day using the UI, editing the cron expression. 

**Anything else you would like to add:**
Happy to make a contribution if this is something that needs to be fixed :)

**Comment by Bobgy** [comment]
duplicate of https://github.com/kubeflow/pipelines/issues/3935

let's track in the new issue because it has more accurate information

**Comment by Bobgy** [comment]
Sorry for wrong dup

**Comment by NikeNano** [comment]
Based upon the findings presented in https://github.com/kubeflow/pipelines/issues/3935 should we move towards using time timezones or stay on using Unix timestamp and shift the cron schedules to UTC? Is it also worth allowing users to set the timezone as a parameter instead of using the local cluster timezone, but default to the cluster timezone?

**Comment by Bobgy** [comment]
Sounds reasonable moving towards local timezones + config.

Note, we might be refactoring the implementation to use K8s cronjobs in the future, so it's better align with their behavior.

**Comment by NikeNano** [comment]
> Sounds reasonable moving towards local timezones + config.
> 
> Note, we might be refactoring the implementation to use K8s cronjobs in the future, so it's better align with their behavior.

Thanks for the feedback, great will do so!

**Comment by kim-sardine** [comment]
Any progress with it? still have same issue

**Comment by Bobgy** [comment]
@kim-sardine this will be released in next KFP release

**Comment by hamko** [comment]
Hi, I tested this feature in [1.4.1 on GCP Marketplace](https://console.cloud.google.com/marketplace/details/google-cloud-ai-platform/kubeflow-pipelines-test), but looks not yet fixed. I set a periodic run trigger `utc` with the cron expression `0 57 12 * * ?` and confirmed the corresponding run was triggered at 21:57 JST, displayed on the kubeflow dashboard UI (9 hours ahead of UTC). Do I misunderstand the fix #4641?

![2021-02-28](https://user-images.githubusercontent.com/3013271/109420299-04e5c100-7a15-11eb-8b11-eb033af98745.png)
![2021-02-28 (1)](https://user-images.githubusercontent.com/3013271/109420300-0911de80-7a15-11eb-8406-1f360ae6a3a5.png)
![2021-02-28 (2)](https://user-images.githubusercontent.com/3013271/109420305-0adba200-7a15-11eb-8045-a13388809d24.png)

**Comment by NikeNano** [comment]
@hamko did you make any changes to the default settings in order to change the timezone for the scheduler? Currently the default is `UTC` [to be backwards compatible](https://github.com/kubeflow/pipelines/pull/4641#issuecomment-751395093), . For more info about the changes specifically to `gcp_market place` this [PR](https://github.com/kubeflow/pipelines/pull/4977) refers to the file that sets it for `gcp_market place`. I have not used  `gcp_market place` so will not be able to support you on the specific for it and how the deployment works in this case :(.

**Comment by akiyamasho** [comment]
I'm aware the devs have already solved it for non-GCP deployments, but just FYI I can confirm @hamko 's test. I have a cluster running on `asia-northeast1-a` and the recurring runs still require UTC time to be set. e.g. - I need to put `13:14 UTC` to have the recurring run be performed at `22:14 JST`

<img width="467" alt="スクリーンショット 2021-05-16 22 16 18" src="https://user-images.githubusercontent.com/35907066/118398693-b9969280-b694-11eb-9036-e2089ca42844.png">
<img width="994" alt="スクリーンショット 2021-05-16 22 16 01" src="https://user-images.githubusercontent.com/35907066/118398700-c0250a00-b694-11eb-9631-034c5467207b.png">
<img width="139" alt="スクリーンショット 2021-05-16 22 19 24" src="https://user-images.githubusercontent.com/35907066/118398705-c74c1800-b694-11eb-987e-8cd8faade5d1.png">

**Comment by Bobgy** [comment]
FYI, as NikeNano said, for any deployment, the default time zone is always UTC (to be backwards compatible).

So you need to configure the time zone to your local one manually. It might make sense to change GCP marketplace default to local time zone, because it doesn't support in-place upgrade. Curious about your thoughts

**Comment by akiyamasho** [comment]
I see. That does make sense. For non-international teams, UX-wise it would make sense to have it listen to the local time zone. 

However, for international teams in different time zones, a single source of truth would be the best alternative. Either UTC which is the default, or the timezone of the cluster's location (e.g. - `us-central1-a` defaults to `UTC -6h`).

Looking at this, I think keeping the default at UTC and simply adding some notes about:

1. the default is UTC 
2. a short procedure on how to change the timezone setting
  a. for new KF pipelines
  b. for existing KF pipelines (when upgrading)

to the [Recurring Runs](https://www.kubeflow.org/docs/components/pipelines/overview/concepts/run/#:~:text=A%20recurring%20run%2C%20or%20job,specified%20and%20a%20run%20trigger.&text=You%20can%20enable%2Fdisable%20the,from%20the%20Kubeflow%20Pipelines%20UI.) documentation would be the best way to proceed.

I'd be willing to make a PR for the documentation but I need to check the code first on how 

```
2. a short procedure on how to change the timezone setting
  a. for new KF pipelines
  b. for existing KF pipelines (when upgrading)
```

is done on GCP marketplace.

**Comment by akiyamasho** [comment]
I think we can do either the documentation update solution above, or much more simply just add the deployment's timezone to the UI as an initial improvement. 

In the next iteration, we can then change the UI to use the user's local time zone but adjust and send a UTC time (or whatever the deployment's timezone is) from the frontend when making requests.

**Comment by Windfarer** [comment]
I tried to set env CRON_SCHEDULE_TIMEZONE by edit deployment.apps/ml-pipeline-scheduledworkflow, but it seems no effect, the the cron runs are still scheduled with UTC. Anyone could tell me the correct way to modify the schedule timezone? Thanks.

**Comment by Bobgy** [comment]
Reopening the issue because of multiple requests. For anyone who wants to contribute, welcome debugging this issue and provide instructions.

**Comment by NikeNano** [comment]
@Windfarer for kubeflow standalone(not GCP) it should be set using https://github.com/kubeflow/pipelines/blob/0d84877c98726be6417474816b38baac92b45ee7/manifests/kustomize/base/installs/generic/pipeline-install-config.yaml#L62. I have tried it out locally as well and it might seems like it is a bug actually, will check and update!

**Comment by NikeNano** [comment]
>I have tried it out locally as well and it might seems like it is a bug actually, will check and update!

For some reason my local minikube cluster used UTC as timezone(my local timezone is CET), so everything should be fine, let me know if you still have issues @Windfarer

**Comment by Windfarer** [comment]
> > I have tried it out locally as well and it might seems like it is a bug actually, will check and update!
> 
> For some reason my local minikube cluster used UTC as timezone(my local timezone is CET), so everything should be fine, let me know if you still have issues @Windfarer

I tried to set cronScheduleTimezone in pipeline-install-config.yaml (in [manifests repo](https://github.com/kubeflow/manifests)) and redeploy the pipeline, but It seems to have no effect. I also tried to do the same thing with pipelines repo (the latest version 1.6.0), the result is same.

My host's timezone is Asia/Shanghai, and I exec into the ml-pipeline-scheduledworkflow pod to check the environment variables, it shows CRON_SCHEDULE_TIMEZONE=Asia/Shanghai has been set. But the schedule timezone is still UTC.

Here's the log of ml-pipeline-scheduledworkflow pod

```
time="2021-06-04T05:59:02Z" level=info msg="Syncing ScheduledWorkflow (testrun8d7j2): success, processing complete." ScheduledWorkflow=testrun8d7j2
time="2021-06-04T05:59:02Z" level=info msg="Event(v1.ObjectReference{Kind:\"ScheduledWorkflow\", Namespace:\"comic\", Name:\"testrun8d7j2\", UID:\"01152589-3f3a-49bc-a2fa-c99d3a5a4dbc\", APIVersion:\"kubeflow.org/v1beta1\", ResourceVersion:\"1892997\", FieldPath:\"\"}): type: 'Normal' reason: 'Synced' Scheduled workflow synced successfull: All done"
time="2021-06-04T05:59:12Z" level=info msg="Submitting workflow for ScheduledWorkflow (testrun8d7j2): nothing to submit (next scheduled at: 2021-06-04 13:59:00 +0000 UTC)" ScheduledWorkflow=testrun8d7j2

```

**Comment by NikeNano** [comment]
Made some more testing and you are correct @Windfarer, awesome finding in #5800
