### ISSUE TITLE
Referenced Cron format docs misleads

### ISSUE THREAD

**Issue by consideRatio** [kubeflow/pipelines#2654]
## Summary

I was led to believe from kubeflow/pipelines frontend that I could and should specify a Cron expression with only five parts, [as described here](https://godoc.org/github.com/robfig/cron#hdr-CRON_Expression_Format), but in reality six parts should be used.

## Investigation

kubeflow/pipelines is currently using [robfig/cron](https://github.com/robfig/cron) (v2) to parse cron specifications provided in ScheduledWorkflows, but not the latest version [robfig/cron/v3](https://github.com/robfig/cron#upgrading-to-v3-june-2019) that has a breaking change: seconds are now excluded by default in the cron job specification.

In the kubeflow/pipelines frontend though, we reference the latest versions documentation:

https://github.com/kubeflow/pipelines/blob/b72de99f0ed5536f5fb6697d9b8d60db6fc271fe/frontend/src/components/Trigger.tsx#L289-L295

This [latest version of the robfig/cron documentation](https://godoc.org/github.com/robfig/cron#hdr-CRON_Expression_Format) excludes the seconds field that we still use as we still use the old v2 version of robfig/cron to parse the expression.

I don't know how to make a fix to point to the v2 version of robfig/cron though, because GoDoc 
[doesn't seem to support that](https://forum.golangbridge.org/t/how-to-read-godoc-of-certain-release/8370).

## Related

Issue #2318 suggest the use of the v3 version.

**Comment by consideRatio** [comment]
I investigated the situation in this Go playground that left me a lot wiser about the issue overall. See https://play.golang.org/p/O6-WnL8343u.

I'd love for someone to suggest a course of action that is suitable for this project. Some preliminary ideas in my mind are:
1. We could update the frontend to not point to the new cron parsing scheme, but the current used cron parsing scheme.
2. We could change the cron expression parsing behavior, for all or for specifically new recurring jobs, by updating to use robfig/cron/v3 and ensuring old jobs behave the same still.
3. Something else

**Comment by discordianfish** [comment]
I'm quite disappointed that my issue just was closed without discussion..

**Comment by shotarok** [comment]
I had the same confusion. The link explains the standard format but the default value for the cron format used by [the Quartz Scheduler](http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/tutorial-lesson-06.html).


I'm using KFP v0.5.1 with AI Platform Pipeline. It looks like both formats work. So how about changing the default value to follow the standard format? Or how about changing the link to [the Quartz Scheduler](http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/tutorial-lesson-06.html)?

**Comment by rmgogogo** [comment]
> I'm quite disappointed that my issue just was closed without discussion..

Sorry I thought you can reopen it while I missed your reply 
https://github.com/kubeflow/pipelines/issues/2318

**Comment by consideRatio** [comment]
@NikeNano was this something you worked on btw? Is it resolved and ready for closure?

**Comment by NikeNano** [comment]
> @NikeNano was this something you worked on btw? Is it resolved and ready for closure?

Hi, as far as I know this is not resolved. I am currently working on the CronJobScheduler so will also look in to this! Thanks for the bump!

**Comment by NikeNano** [comment]
Will fix this after https://github.com/kubeflow/pipelines/pull/4641 is merged.
