### ISSUE TITLE
Frontend - Metadta - Execution detail page fails to show executions with some type names

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#2669]
When clicking on an execution in the Executions list

>tfx-pipeline-p7mfm
> Git clone
> 300
> components.Git clone@sha256:ab0c0e1bbd0f3d939599aeb5b1c923a09405abb5ec45be6765

I get to the page with URL: https://34c40cdd21e49f0a-dot-us-central1.notebooks.googleusercontent.com/#/execution_types/components.Git%20clone@sha256/executions/ab0c0e1bbd0f3d939599aeb5b1c923a09405abb5ec45be676582de881d12124f

The page shows error:

>Invalid execution id: ab0c0e1bbd0f3d939599aeb5b1c923a09405abb5ec45be676582de881d12124f Click Details for more information.

I think that UX is confused by ":" in the execution type

**Comment by Bobgy** [comment]
@Ark-kun Sorry, I forgot about this issue.
Is this still relevant? Can you give me an example cluster or detailed reproduction steps? I don't fully get the problem.

**Comment by Ark-kun** [comment]
It's probably still relevant.
The issue was that the generated URIs, that point from ExecutionList page to ExecutionDetails pages, are broken when the ExecutionType contains colon.

I'll try to give you repro steps a bit later.

**Comment by Ark-kun** [comment]
Generated URI:
`https://34c40cdd21e49f0a-dot-us-central1.notebooks.googleusercontent.com/#/execution_types/components.Git%20clone@sha256/executions/ab0c0e1bbd0f3d939599aeb5b1c923a09405abb5ec45be676582de881d12124f`

Correct URI:
`https://34c40cdd21e49f0a-dot-us-central1.notebooks.googleusercontent.com/#/execution_types/components.Git%20clone@sha256:ab0c0e1bbd0f3d939599aeb5b1c923a09405abb5ec45be676582de881d12124f/executions/????`

**Comment by Bobgy** [comment]
@Ark-kun thanks! Added to the plan
a sample pipeline will be welcomed

**Comment by Bobgy** [comment]
@Ark-kun I plan to remove type from the url. I don't know the context why it was added, but from data, looks like id is the only unique_key for an artifact/execution.
