### ISSUE TITLE
pipeline generate yaml wrong

### ISSUE THREAD

**Issue by TaChao** [kubeflow/pipelines#2684]
**What happened:**
use add_env_variable like this

```step.container.add_env_variable(V1EnvVar(name='AAA',value='008'))```
will get yaml like this
```
- name: AAA
  value: 008
```
but k8s treat '008' as a number
 
**What did you expect to happen:**
```
- name: AAA
  value: '008'
```
**What steps did you take:**
[A clear and concise description of what the bug is.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by numerology** [comment]
Ack. Will take a look. Thanks for reporting @TaChao !

**Comment by numerology** [comment]
Hi @TaChao ,

Can you upgrade to the latest version where we use the block style yaml?
Now it should generate something like:
```yaml
      - "name": |-
          AAA
        "value": |-
          008
```

**Comment by TaChao** [comment]
great !

> Hi @TaChao ,
> 
> Can you upgrade to the latest version where we use the block style yaml?
> Now it should generate something like:
> 
> ```yaml
>       - "name": |-
>           AAA
>         "value": |-
>           008
> ```
