### ISSUE TITLE
[WIP] Extend Kubeflow Pipelines DSL with support for Databricks operations

### ISSUE THREAD

**Issue by magencio** [kubeflow/pipelines#2685]
# Introduction

Our customer's data scientists have a need for large scale Spark jobs. Our customer wants integration between Databricks and their Kubeflow platform to allow seamless use of Spark on Databricks by their teams. They want Kubeflow pipelines that include both Databricks jobs and components running in-cluster. This integration will offload work out of the Kubernetes cluster and simplify operation.

A data scientist could write a standard Kubeflow pipeline using [existing dsl classes](https://github.com/kubeflow/pipelines/tree/master/sdk/python/kfp/dsl) in [Kubeflow Pipelines Python SDK](https://www.kubeflow.org/docs/pipelines/sdk/sdk-overview/) and leveraging [Azure Databricks Operator for Kubernetes](https://github.com/microsoft/azure-databricks-operator) to manage Databricks resources such as Clusters, to schedule Spark Jobs, and to submit one-time Job Runs in those clusters. 

However, the way this is done is via the [ResourceOp](https://www.kubeflow.org/docs/pipelines/sdk/manipulate-resources/#resourceop), and it requires the Kubeflow pipeline user to define these Databricks resources in terms of k8s resources, defined within a large Python dictionary.

# Proposal

We would like to make changes to the Kubeflow Pipelines DSL such that these tasks become first class citizens of the DSL and give Kubeflow Pipelines users a better user experience.

## Example 1: The Current Mechanism for Deploying a Databricks One-Time Run

The following shows how a user can create an operation to submit a one-time run with implicit cluster creation:

``` python
import kfp.dsl as dsl

dsl.ResourceOp(
  name = "submitrun",
  k8s_resource = {
    "apiVersion": "databricks.microsoft.com/v1alpha1",
    "kind": "Run",
    "metadata": {
      "name":"test-run",
    },
    "spec":{
      "run_name":"test-run",
      "new_cluster": {
        "spark_version":"5.3.x-scala2.11",
        "node_type_id": "Standard_D3_v2",
        "num_workers": 2
      },
      "libraries": [
        {
          "jar": "dbfs:/my-jar.jar"
        },
        {
          "maven": {
            "coordinates": "org.jsoup:jsoup:1.7.2"
          }
        }
      ],
      "spark_jar_task": {
        "main_class_name": "com.databricks.ComputeModels"
      }
    },
  },
  action = "create", 
  success_condition = "status.metadata.state.life_cycle_state in (TERMINATED, SKIPPED, INTERNAL_ERROR)",
  attribute_outputs={
    "name": "{.metadata.name}",
    "job_id": "{.status.metadata.job_id}",
    "number_in_job": "{.status.metadata.number_in_job}",
    "run_id": "{.status.metadata.run_id}",
    "run_name": "{.status.metadata.run_name}",
    "life_cycle_state": "{.status.metadata.state.life_cycle_state}",
    "result_state": "{.status.metadata.state.result_state}",
    "notebook_output_result": "{.status.notebook_output.result}",
    "notebook_output_truncated": "{.status.notebook_output.truncated}",
    "error": "{.status.error}"
  }
)
```

## Example 2: Deploying a Databricks One-Time Run with the Proposed Improvements to the DSL

We would like to extend the dsl with Databricks specific classes that would wrap dsl.ResourceOp and allow us to create those operations while abstracting the end user from Azure Databricks Operator specifics (e.g. api version, kinds, success conditions). 

Using Databricks specific classes we could replace the above code with something like this instead:

``` python
import kfp.dsl.databricks as databricks

databricks.SubmitRunOp(
    name = "submitrun",
    spec = {
        "run_name" = "test-run"
        "new_cluster": {
            "spark_version":"5.3.x-scala2.11",
            "node_type_id": "Standard_D3_v2",
            "num_workers": 2
        },
        "libraries": [
            {
                "jar": "dbfs:/my-jar.jar"
            },
            {
                "maven": {
                    "coordinates": "org.jsoup:jsoup:1.7.2"
                }
            }
        ],
        "spark_jar_task": {
            "main_class_name": "com.databricks.ComputeModels"
        }
    }
)
```

Or, with this equivalent code:

``` python
import kfp.dsl.databricks as databricks

databricks.SubmitRunOp(
    name = "submitrun",
    run_name = "test-run",
    new_cluster = {
        "spark_version":"5.3.x-scala2.11",
        "node_type_id": "Standard_D3_v2",
        "num_workers": 2
    },
    libraries = [
        {
            "jar": "dbfs:/my-jar.jar"
        },
        {
            "maven": {
                "coordinates": "org.jsoup:jsoup:1.7.2"
            }
        }
    ],
    spark_jar_task = {
        "main_class_name": "com.databricks.ComputeModels"
    }
)
```

Additionally, we could provide a class method to e.g. create the operation but with the spec in json format:

``` python
import kfp.dsl.databricks as databricks

_JSON_SPEC = """
{
    "new_cluster": {
        "spark_version":"5.3.x-scala2.11",
        "node_type_id": "Standard_D3_v2",
        "num_workers": 2
    },
    "libraries": [
        {
            "jar": "dbfs:/my-jar.jar"
        },
        {
            "maven": {
                "coordinates": "org.jsoup:jsoup:1.7.2"
            }
        }
    ],
    "spark_jar_task": {
        "main_class_name": "com.databricks.ComputeModels"
    }
}
"""

databricks.SubmitRunOp.from_json_spec(
    name = "submitrun",
    run_name = "test-run",
    json_spec = _JSON_SPEC
)
```

And we could also provide another class method to create the operation but with the spec in an external json file:

```
import kfp.dsl.databricks as databricks

databricks.SubmitRunOp.from_file_name(
    name = "submitrun",
    run_name = "test-run",
    file_name = "run_spec.json"
)
```

# Feedback required by the Kubeflow Pipelines team

We would like to get your feedback on this, and if this enhancement to the DSL is acceptable we would look to raise a PR to implement it.

- Does this DSL extension feel appropriate and, if so, should we go ahead and raise a PR?
- Are there things we should change/adjust in the proposal before raising a PR?

The following branch, within a fork of this repo, contains Work In Progress code that would become part of that Pull Request:

https://github.com/magencio/pipelines/tree/databricks-wrapper/sdk/python/kfp/dsl/databricks

This code, and associated docs, may well help to better illustrate the DSL enhancements. The following section contains links into specific parts of that potential Pull Request:

## Additional Information and Working Samples

- Databricks DSL README: [magencio/pipelines/tree/databricks-wrapper/sdk/python/kfp/dsl/databricks/README.md](https://github.com/magencio/pipelines/blob/databricks-wrapper/sdk/python/kfp/dsl/databricks/README.md)
- Potential implementation for Run related Ops: [magencio/pipelines/sdk/python/kfp/dsl/databricks/_run_op.py](https://github.com/magencio/pipelines/blob/databricks-wrapper/sdk/python/kfp/dsl/databricks/_run_op.py).
- Sample Kubeflow pipeline using Run related Ops: [magencio/examples/blob/databricks/pipelines/azuredatabricks_operator/databricks_dsl_run_pipeline.py](https://github.com/magencio/examples/blob/databricks/pipelines/azuredatabricks_operator/databricks_dsl_run_pipeline.py)
- More usage examples in tests for Run related Ops: [magencio/pipelines/blob/databricks-wrapper/sdk/python/tests/dsl/databricks/test_run_op.py](https://github.com/magencio/pipelines/blob/databricks-wrapper/sdk/python/tests/dsl/databricks/test_run_op.py)

**Comment by Ark-kun** [comment]
Hello Alejandro.

Thank you for a thorough proposal. Databricks support will be a welcome addition.

In KF Pipelines we believe in building a vast ecosystem of component where every author is empowered to create any component they are missing. We focus on the reusable components experience and making every component a first-class citizen regardless of who creates it. For this reason we try keeping the SDK minimal and very generic. We believe all executing code should be part of components and Pipelines SDK just providing "glue" that ties those components together.

We think that Databricks components would be a great addition to our collection of components.

>Does this DSL extension feel appropriate and, if so, should we go ahead and raise a PR?
>Are there things we should change/adjust in the proposal before raising a PR?

Making a component for Databricks would be great. We have some similar components for Google AI Platform Training, Kubeflow TFJob, Dataflow, Katib, Seldon, PySpark etc.

Here is how this could look for the end user:

```python
databricks_submit_run_op = kfp.components.load_component('.../databricks/submit_run/from_json_spec/component.yaml')
databricks_submit_run_op(
    run_name = "test-run",
    json_spec = _JSON_SPEC,
)
```

```python
databricks_submit_run_op = kfp.components.load_component('.../databricks/submit_run/from_json_spec/component.yaml')
databricks_submit_run_op(
    run_name = "test-run",
    json_spec = json.loads("run_spec.json"),
)
```

or maybe

```python
databricks_submit_run_op = kfp.components.load_component('.../databricks/submit_run/from_json_spec/component.yaml')
databricks_submit_run_op(
    run_name = "test-run",
    new_cluster = {
        "spark_version":"5.3.x-scala2.11",
        "node_type_id": "Standard_D3_v2",
        "num_workers": 2
    },
    libraries = [
        {
            "jar": "dbfs:/my-jar.jar"
        },
        {
            "maven": {
                "coordinates": "org.jsoup:jsoup:1.7.2"
            }
        }
    ],
    spark_jar_task = {
        "main_class_name": "com.databricks.ComputeModels"
    }
)
```

WDYT?

**Comment by magencio** [comment]
Thank you Alexey,

We understand the component approach you mention and it makes a lot of sense. 
We've been taking a look to other 3rd party components in https://github.com/kubeflow/pipelines/tree/master/components, and their approach to manage cloud resources is different than ours. When working with Databricks we are following the [Kubernetes Operator Pattern](https://coreos.com/operators/), so we just need to create k8s [CRDs](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#create-custom-objects) to manage Databricks resources and the [Databricks operator](https://github.com/microsoft/azure-databricks-operator) will take care of the rest. And we can create those CRDs with e.g. kubectl or in Kubeflow Pipelines with ResourceOp. 
So creating full-fledged Kubeflow components as explained here: [Kubeflow: Create Reusable Components](https://www.kubeflow.org/docs/pipelines/sdk/component-development), and spinning up additional docker containers just to create a CRD seems to be quite cumbersome and much harder to maintain than simple Python functions wrapping up ResourceOp. 

Now, we've seen other components that provide Python functions that wrap dsl classes like ContainerOp: https://github.com/kubeflow/pipelines/blob/master/components/arena/python/arena/_arena_standalone_op.py

Would it then be ok if we just move Databricks Ops in sdk/python/kfp/dsl/databricks to e.g. components/azure/databricks and document how to use them? Would that be appropriate and, if so, should we go ahead and raise a PR?
Any other things we should change/adjust?

**Comment by Ark-kun** [comment]
> spinning up additional docker containers just to create a CRD seems to be quite cumbersome

That's what happens when ResourceOp is used (which currently translates to Argo's ResourceTemplate). Argo creates a pod with container that literally runs kubectl, waits for condition and grabs outputs. https://github.com/argoproj/argo/blob/cd04ab8bb923012182f2dc2b35dbf14726f7b1a4/workflow/executor/resource.go#L23

>So creating full-fledged Kubeflow components as explained here: Kubeflow: Create Reusable Components,

There is also the [Lightweight python components](https://github.com/Ark-kun/kfp_samples/blob/3b6ecb1/2019-10%20Kubeflow%20summit/103%20-%20Creating%20components%20from%20python%20functions/103%20-%20Creating%20components%20from%20python%20functions.ipynb) feature that lets you easily generate component from a python function. We use it to make component creation and maintenance of some python-based components easier: https://github.com/kubeflow/pipelines/blob/88b4757d5be17fbe18c9d1c3de22fe7eb2a76e62/components/gcp/automl/create_model_for_tables/component.py#L58

>seems to be quite cumbersome and much harder to maintain than simple Python functions wrapping up ResourceOp.

Maybe you can use some common CRD launching code like https://github.com/kubeflow/pipelines/blob/848fbe0bceb786c8db72e88b3bc986d42ac768b9/components/kubeflow/common/launch_crd.py

>Now, we've seen other components that provide Python functions that wrap dsl classes like ContainerOp:

Functions like these exist (3rd-party code), but I want to note that they are not full-fledged components. Components have portable declarative definitions that can be shared and loaded. Those functions do not have that, which makes them more cumbersome to use. (The user first needs to install them. They cannot be indexed. They're python-bound.)

>Would it then be ok if we just move Databricks Ops in sdk/python/kfp/dsl/databricks to e.g. components/azure/databricks and document how to use them? 

Yes, this would be more appropriate.

The ideal long-term solution would still be the creation of `component.yaml` definitions (either manually or using `func_to_container_op`).

**Comment by magencio** [comment]
Thank you Alexey for your feedback. We will proceed to do the PR then.

**Comment by pwzhong** [comment]
Hi, may I ask do these operators support AWS Databricks? Are there any ways to submit a run on AWS Databricks from Kubeflow?

**Comment by magencio** [comment]
> Hi, may I ask do these operators support AWS Databricks? Are there any ways to submit a run on AWS Databricks from Kubeflow?

Sorry, I work for Microsoft, so my focus is Azure. Haven't worked with AWS

**Comment by thanhpt55** [comment]
Hi @Ark-kun, When I created a DatabricksStep with existing_cluster_id (with valid cluster-id), pipeline had failed without any error. Cluster logs do not indicate anything. Same step without a cluster-id works (creating a new job cluster).
Status Run in kubeflow:
`Name:         databricksrun-m7bf7
Namespace:    develop
Labels:       <none>
Annotations:  <none>
API Version:  databricks.microsoft.com/v1alpha1
Kind:         Run
Metadata:
  Creation Timestamp:  2022-02-21T09:43:56Z
  Finalizers:
    run.finalizers.databricks.microsoft.com
  Generation:  1
  Managed Fields:
    API Version:  databricks.microsoft.com/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        .:
        f:existing_cluster_id:
        f:run_name:
        f:spark_python_task:
          .:
          f:parameters:
          f:python_file:
    Manager:      kubectl
    Operation:    Update
    Time:         2022-02-21T09:43:56Z
    API Version:  databricks.microsoft.com/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"run.finalizers.databricks.microsoft.com":
    Manager:         manager
    Operation:       Update
    Time:            2022-02-21T09:43:56Z
  Resource Version:  544695419
  UID:               82dacac7-9d14-428d-86ba-3bd4681b631a
Spec:
  existing_cluster_id:  0920-020715-spume881
  run_name:             databricksrun-m7bf7
  spark_python_task:
    Parameters:
      azure
      https://aiscalerint.blob.core.windows.net/exported-dataset/1551_2021-09-23T03%3A16%3A41.240015Z.json
    python_file:  dbfs:/aiscaler/data_storage/transform_coco_segmentation.py
Events:
  Type     Reason             Age                   From            Message
  ----     ------             ----                  ----            -------
  Normal   Added              3m14s                 run-controller  Object finalizer is added
  Warning  Submitting object  23s (x16 over 3m14s)  run-controller  Failed to submit object: failed to get ClusterID of 0920-020715-spume881`
  
I get cluster id from url: https://adb-8864828201665766.6.azuredatabricks.net/?o=8864828201665766#setting/clusters/0920-020715-spume881/configuration
