### ISSUE TITLE
Visualize TFX component output in metadata UI

### ISSUE THREAD

**Issue by neuromage** [kubeflow/pipelines#2687]
It would be great to visualize the various outputs of TFX components in the metadata UI. Since output metadata is strongly typed, we can use the visualization backend to generate dynamic visualizations using TFMA, TFDV Facets etc. 

The interactive notebook in [1] provides a good starting point for determining what can be visualized based on the type of the output metadata.

One idea would be to embed these visualizations in the view for individual artifacts. For example when viewing the output metadata for Evaluator, we could embed TFMA visualization based on the specified slice.

[1] https://github.com/tensorflow/tfx/blob/3a8f2956977fc716e3d07bdb8487ad05abda2823/docs/tutorials/tfx/components.ipynb

/assign @Bobgy 

/cc @paveldournov

**Comment by Ark-kun** [comment]
Is your plan to execute the TFMA and TFDV code in the backend itself, or should we offload this work to other services?

I propose running visualizations the exact same way we run component tasks.

Visualizer can be a component that takes input of some type (e.g. TF Model or Schema) and outputs HTML.
We can put those visualizers in subdirectories of `/components/visualizers` based on the data type (e.g. `/components/visualizers/tensorflow.metadata.v0.Schema`).

The UX can check whether the visualizer for some type exists, then run a Pod with the visualizer code and cache the results.

**Comment by neuromage** [comment]
The plan is to execute the code on the Python visualization server.

**Comment by Ark-kun** [comment]
> The plan is to execute the code on the Python visualization server.

I see. What's your thought about security and performance?
Treating executions of components and visualizers the same way can make the system easier to implement since we won't need to duplicate the infrastructure (e.g. caching).

**Comment by Bobgy** [comment]
@Ark-kun That sounds interesting. Do you mean users putting visualizers part of a pipeline, or visualization server triggers and manages these components and their output?

**Comment by Bobgy** [comment]
@neuromage SG, definitely sth we want to do. What is priority for this?

**Comment by neuromage** [comment]
@Bobgy let's say P1 for now. Let's discuss this offline to discuss relative prioritization with other pieces of work you have in flight.

/cc @jessiezcc 
/cc @rmgogogo

**Comment by neuromage** [comment]
We may want to fix some issues with visualization server first, as discussed during team meeting earlier today.

**Comment by Ark-kun** [comment]
The issue that tracks the problems with existing visualizations is tracked here: https://github.com/kubeflow/pipelines/issues/2670
