### ISSUE TITLE
Documentation around public URL/reverse proxy

### ISSUE THREAD

**Issue by michaelbeaumont** [kubeflow/pipelines#2704]
I'm installing pipelines standalone and having trouble understanding the reverse proxy component, both its purpose as well as how it works.

I'd love to get some clarification and improve the documentation around it.

The documentation at [Standalone deployment GCP](https://www.kubeflow.org/docs/pipelines/standalone-deployment-gcp/) simply mentions a "public URL" which immediately alarms me. It turns out it's protected by some sort of IAM, although this isn't mentioned.
How does this IAM work? [The `inverting-proxy` documentation](https://github.com/google/inverting-proxy) suggests that some resources are provisioned when launching the proxy. What's happening in the background here?

Should this really be the default? It seems a bit silly for me to fork the repo and comment out a line to disable a component that seems only useful for playing around with pipelines and even for that rather unnecessary. `port-forward` is easy enough and I suspect most people would create an `Ingress` resource here, although perhaps I'm off base.

**Comment by Bobgy** [comment]
/area doc
/kind question

Yes, we should add documentation there.

**Comment by Bobgy** [comment]
Already documented in https://cloud.google.com/ai-platform/pipelines/docs/access-control#accessing
