### ISSUE TITLE
If one step of pipeline fails, there should be one way to modify the step and restart this step easily.

### ISSUE THREAD

**Issue by umialpha** [kubeflow/pipelines#2710]
/kind feature
/kind enhancement

Hi, I am new to kubeflow pipeline, when I am trying '/pipelines/azurepipeline' example, I meet a lot of errors for each step(I have already fixed these bugs). Each time I fix any bug, I need to rebuild the pipeline(although I could modify the <pipeline.yaml> directly), kill the previous one and start a new pipeline. It really annoys me. 

So I tried some tricky ways to work around.
First, I get noticed each pipeline is a 'Workflow' object, so I edit the workflow yaml, hoping it could restart the failed pod with newer config, but it turned out seamlessly not working(maybe). 
Then, I try another way. I edit the failed pod's yaml directly, it works.

Conclusion
Maybe the pipeline board could offer one way to modify each step. There must be a better way to meet my requests.

**Comment by numerology** [comment]
Hi @umialpha , thanks for your feedback!

What if we allow cache across pipeline runs so that each time you submit the re-compiled package, correctly executed steps can be preserved?

**Comment by umialpha** [comment]
> What if we allow cache across pipeline runs so that each time you submit the re-compiled package, correctly executed steps can be preserved?

That sounds great. I think if we could revise the step directly in front UI would be better. 

Yesterday, I look into the Argo project, it claims the feature "Retry (step & workflow level)" and "Resubmit (memoized)". I haven't tried these features yet, but I think it is possible for within kubeflow.

**Comment by numerology** [comment]
> Yesterday, I look into the Argo project, it claims the feature "Retry (step & workflow level)"

Currently we support retry failed steps, but without modification.

**Comment by umialpha** [comment]
> > Yesterday, I look into the Argo project, it claims the feature "Retry (step & workflow level)"
> 
> Currently we support retry failed steps, but without modification.

Thanks for your reply. So do we have some plan that allow users modify come code, bash, yaml, etc, on the fly
