### ISSUE TITLE
Waste of UI real estate on a run's "config" tab

### ISSUE THREAD

**Issue by martin-laurent** [kubeflow/pipelines#2713]
**What happened:**

I used a JSON string as one of my run parameters.
It shows pretty enough but it seems to be hardcoded to show a snippet of about 10 lines of JSON. If I have less than 20 lines it will show blank space which is annoying as a user. If it's more than 20 lines, it will have a scroll bar which is also annoying.

**What did you expect to happen:**
snippet block to be trimmed down if it's a small snippet.
A scroll bar to appear only when it's a much bigger block of JSON (50 lines? 100 lines?)

**What steps did you take:**
Included a snapshot. The run parameters or JSONified strings.
<img width="1148" alt="Screen Shot 2019-12-10 at 3 31 26 PM" src="https://user-images.githubusercontent.com/17744754/70566893-e753df80-1b62-11ea-9b98-0dfe9a97da7d.png">

**Comment by Bobgy** [comment]
Sounds reasonable to me.

**Comment by Bobgy** [comment]
I don't currently have time to work on this, anyone is welcome to contribute before that.

/priority p2

**Comment by Bobgy** [comment]
/priority p1
bumping a little priority because this is low effort and a solid use case.

**Comment by fenglixa** [comment]
I would like to provide PR for this, it would be my first PR for pipelines, Great thanks for any help/info on this issue.

BR
-Feng
