### ISSUE TITLE
Clone from Run UI is terrible with JSON

### ISSUE THREAD

**Issue by martin-laurent** [kubeflow/pipelines#2714]
**What happened:**
Try to clone a run (via the clone run button) that uses JSON strings as run parameters.
While the JSON run parameters show decently enough on the run's config tab (see https://github.com/kubeflow/pipelines/issues/2713 for issues about that),
cloning such a run shows minified JSON in the form. This is a terrible user experience for someone that just wants to iterate on hyperparameters for example.

**What did you expect to happen:**
A similar but editable snippet of JSON to be rendered instead of the minified line of text

**What steps did you take:**
Cloned a run that contains JSON like run parameters

Attached is a screenshot of the config page that renders JSON snippet:
<img width="1148" alt="Screen Shot 2019-12-10 at 3 31 26 PM" src="https://user-images.githubusercontent.com/17744754/70567344-c5a72800-1b63-11ea-9712-028f74e6dad3.png">

and its direct equivalent when clicking on the clone run button:
<img width="659" alt="Screen Shot 2019-12-10 at 3 31 58 PM" src="https://user-images.githubusercontent.com/17744754/70567348-c8a21880-1b63-11ea-960c-3e8836016b97.png">

**Comment by Bobgy** [comment]
Thanks! That sounds useful.

I don't currently have time to work on this, anyone is welcome to contribute before I've got some bandwidth on this.
/priority p2

**Comment by Bobgy** [comment]
Providing a button nearby that can change the text box to a multiline editor might be helpful.

**Comment by Bobgy** [comment]
/priority p1
bumping a little priority because this is low effort and a solid use case.

**Comment by fenglixa** [comment]
I would like to provide PR for this issue
BR
-Feng

**Comment by Bobgy** [comment]
Thanks @fenglixa! You are welcome, but @drewbutlerbb4 has already made a PR. Let's avoid duplicate efforts.

**Comment by fenglixa** [comment]
Yes, I found that already PR on this issue. Thanks @Bobgy @drewbutlerbb4

**Comment by Bobgy** [comment]
Removing the label, as it is obviously more complex than I thought. Thanks @drewbutlerbb4! Well thought through the use case.
