### ISSUE TITLE
Failed to list pipelines

### ISSUE THREAD

**Issue by Kyrremann** [kubeflow/pipelines#2718]
First of, I tried to fix a different bug (#796) in my cluster. After a time I got the idea to clean out all the piplines, expereiments, and workflows. Started with deleting the workflows via `kubectl`, then continue by deleting stuff from the mysql-database. It was after this things stopped working.

**What happened:**
After uploading a pipeline via `+ Upload pipeline` I get the following error, and no pipelines are shown.
```
List pipelines failed.: InternalServerError: Failed to list pipelines: sql: expected 7 destination arguments in Scan, not 6: sql: expected 7 destination arguments in Scan, not 6
```

**What did you expect to happen:**
See my newly uploaded pipeline in the list of pipelines.

I'm worried that I deleted some references to pipelines that have been uploaded, that it somehow sees, but can't find in the database.

**Comment by IronPan** [comment]
Thanks @Kyrremann 
Which version are you using?

**Comment by Kyrremann** [comment]
Should of course added that. We're running Kubeflow 0.6.2. We've opted to wait for 1.0 before upgrading.

**Comment by Kyrremann** [comment]
I'm still trying to solve this, and I think I know where the error originates from.
https://github.com/kubeflow/pipelines/blob/6e88e8eeb2c7c8099408c269df64312bd3012d26/backend/src/apiserver/storage/pipeline_store.go#L90

buildQuery := func(sqlBuilder sq.SelectBuilder) sq.SelectBuilder {
		return sqlBuilder.
			From("pipelines").
			LeftJoin("pipeline_versions ON pipelines.DefaultVersionId = pipeline_versions.UUID").
			Where(sq.Eq{"pipelines.Status": model.PipelineReady})
	}


`pipelines` looks like this:
```
mysql> select * from pipelines;
+--------------------------------------+----------------+-----------+-------------+------------+--------+------------------+
| UUID                                 | CreatedAtInSec | Name      | Description | Parameters | Status | DefaultVersionId |
+--------------------------------------+----------------+-----------+-------------+------------+--------+------------------+
| c2944297-af96-4353-8697-9187b12277dc |     1576231947 | kyrretest |             | []         | READY  | NULL             |
+--------------------------------------+----------------+-----------+-------------+------------+--------+------------------+
1 row in set (0.00 sec)
```

`pipeline_versions` on the other hand is empty:
```
mysql> select * from pipeline_versions;
Empty set (0.00 sec)
```

So I'm guess that I'm missing a `pipeline_versions` row, or something. Is there supposed to be a default `DefaultVersionId`?

**Comment by Kyrremann** [comment]
Turns out upgrading the ml-pipelines-images changes the database, so when you downgrade you need to remove the changes.

So for me, upgrading from `0.1.23` to a newer one added the column `pipelines. DefaultVersionId` in the `mlpipeline` database. This needed to be removed to get the API working again.
