### ISSUE TITLE
Failed to save output artifacts into GCS

### ISSUE THREAD

**Issue by shotarohorai** [kubeflow/pipelines#2719]
**What happened:**
I am trying to build Kubeflow pipelines using Kustomize manifests and integrate GCS as an object storage by following the instruction.(https://github.com/kubeflow/pipelines/tree/master/manifests/kustomize/env/gcp)

It succeeds to save pipelines in my GCS bucket specified here (https://github.com/kubeflow/pipelines/blob/master/manifests/kustomize/env/gcp/gcp-configurations-patch.yaml#L14), but when it saves output artifacts, it fails because it seems to try to save files in different bucket named `mlpipeline`.

Minio pod emits the log below.
```
 API: PutObject(bucket=mlpipeline, object=artifacts/my-pipeline-kst2w/my-pipeline-kst2w-2016865322/my-out-cop0-out.tgz)
 Time: 11:26:49 UTC 12/11/2019                                                                                         
 RequestID: 15DF4D807F6767F2                                                                                           
 RemoteHost: 10.60.1.51                                                                                                
 Host: minio-service.kubeflow:9000                                                                                     
 UserAgent: Minio (linux; amd64) minio-go/v6.0.5                                                                       
 Error: googleapi: Error 403: {{my service account}} does not have storage.buckets.get access to mlpipeline., forbidden
        3: cmd/gateway/gcs/gateway-gcs.go:896:gcs.(*gcsGateway).PutObject()                                            
        2: cmd/object-handlers.go:1255:cmd.objectAPIHandlers.PutObjectHandler()                                        
        1: net/http/server.go:1995:http.HandlerFunc.ServeHTTP() 
```

**What did you expect to happen:**
It saves output artifacts in the bucket specified in `OBJECTSTORECONFIG_BUCKETNAME` env var.

**What steps did you take:**
[A clear and concise description of what the bug is.]
Followed the instruction below to build kubeflow pipelines.
https://github.com/kubeflow/pipelines/blob/master/manifests/kustomize/README.md

And run the sample workflow of `pipelines/samples/core/loop_parameter/loop_parameter.py`

**Comment by shotarohorai** [comment]
It seems I also need to change the configmap: https://github.com/kubeflow/pipelines/blob/master/manifests/kustomize/base/argo/workflow-controller-configmap.yaml#L12 

It will be nice that it's written in the README in env/gcp.

**Comment by Bobgy** [comment]
Thanks! We should fix this.
/priority p1
