### ISSUE TITLE
Point pre-installed sample source links to permanent URIs

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#2721]
Otherwise the links stop working when the samples are moved.

**Comment by Bobgy** [comment]
It seems @numerology has already been doing this: https://github.com/kubeflow/pipelines/pull/2722

**Comment by numerology** [comment]
Summarize some discussion in #2722 here.

Pointing source links to permalinks can fix the 404 error for now, but it falls short in that our future update to READMEs and source codes won't be reflected in the preload samples in a timely manner.

One possible solution of that would be include some `link checks` in presubmit tests, to guarantee all the links in the docs and samples are not broken by the PR.

**Comment by Ark-kun** [comment]
> it falls short in that our future update to READMEs and source codes won't be reflected in the preload samples in a timely manner.

But the source code would be correct (corresponding to the preloaded sample).

We can use version tag instead of commit hash to make it easier to update the samples config.

Another option might be to build/modify the config during the image building.

**Comment by numerology** [comment]
> But the source code would be correct (corresponding to the preloaded sample).

Not exactly sure I understand... Are you suggesting there is a way to use permalink while keep the source code up-to-date at the same time?

**Comment by Bobgy** [comment]
> Another option might be to build/modify the config during the image building.

This sounds like a good idea to me.

**Comment by Bobgy** [comment]
Adjusting on that
1. Pin sample links to current commit SHA during image build
2. Add a presubmit test using a tool like https://github.com/remarkjs/remark-validate-links to detect anything is moved or no longer valid.

Extra benefit comparing to pinning directly in source code:
* github repo links are always pointing to current version (instead of doc links are only updated on release)
* no extra step in release management

**Comment by numerology** [comment]
@Bobgy That looks good to me. I can try to do item 2.

**Comment by Bobgy** [comment]
We've done this in above PRs.
