### ISSUE TITLE
Seemingly impossible to ignore errors in steps that kill the pod, e.g. OOMKilled

### ISSUE THREAD

**Issue by grischa** [kubeflow/pipelines#2726]
**What happened:**
Running a pipeline where some steps fail by needing too much memory.
The step does not seem to be wrappable in a script that swallows the error as suggested in https://github.com/kubeflow/pipelines/issues/2372

**What did you expect to happen:**
I would like a way to complete a pipeline even when some "optional" steps fail really badly, ie. the pod gets killed

**What steps did you take:**
Running a pipeline that occasionally blows out on memory requirements

This may be only useful for parallel processing tasks, otherwise, as mentioned in the other issue, there are no outputs for the next step's input.

**Comment by hasansalimkanmaz** [comment]
Any progress about this issue? @grischa
