### ISSUE TITLE
FR: GCP DataFlow Python Pipeline Component - support for more than one python file or support for python module

### ISSUE THREAD

**Issue by dhodun** [kubeflow/pipelines#2728]
The GCP Dataflow component currently only supports a single python file. This can be cumbersome for larger jobs that import from helper files or where a module has been built. The following options would help:

- Support for uploading more than one file (via list or fuzzy match)
- Support for indicating a module
- Support for a packaged (via Setuptools) module already in GCS

GCP AI Platform training supports several of these: https://cloud.google.com/ml-engine/docs/packaging-trainer#manual-build

**Comment by numerology** [comment]
SGTM, I can give it a shot.
