### ISSUE TITLE
Modify container images so that they support multiple data store options depending on parameters

### ISSUE THREAD

**Issue by vicaire** [kubeflow/pipelines#274]
For instance, in the case of TensorFlow container images, all the data stores supported by TensorFlow should be supported (GCS/HDFS/etc.). 

For container images that use GCS, the client used by the container image could be replaced by MinioClient, which can get data from GCS/MinioServer/etc. depending on the container parameters.

**Comment by vicaire** [comment]
@jlewi

**Comment by Ark-kun** [comment]
One of the strong points of Argo is the automatic and transparent handling of artifacts. Containers work with files and the system makes it so that the data is stored in the configured storage system.

**Comment by vicaire** [comment]
Resolving in favor of https://github.com/kubeflow/pipelines/issues/801
