### ISSUE TITLE
Visulizaiton Creator - DOC:  need explicit documentation on what types may apply to what component

### ISSUE THREAD

**Issue by jessiezcc** [kubeflow/pipelines#2741]
Today on UI, we show three types for each component, however it's very hard for end user to understand which types may apply to which components, and what sources are supposed to be input to the source field. Explicit instructions and examples will definitely help.

**Comment by jessiezcc** [comment]
@rmgogogo @Bobgy, pls assess the usability of this feature.

**Comment by Bobgy** [comment]
/assign @jingzhang36 
Jing is currently taking a look at these
