### ISSUE TITLE
Python DSL should support multiple storage options (GCS, PVC, etc.)

### ISSUE THREAD

**Issue by vicaire** [kubeflow/pipelines#275]

**Comment by vicaire** [comment]
@jlewi

**Comment by Ark-kun** [comment]
I think this should mostly be managed on the backend side and be transparent to the containers/components. See https://github.com/argoproj/argo/blob/master/ARTIFACT_REPO.md

**Comment by IronPan** [comment]
The argo is limited to s3 compatible storage. Pipeline component should support arbitrary store. E.g. accessing HDFS.

**Comment by vicaire** [comment]
Resolving in favor of https://github.com/kubeflow/pipelines/issues/801
