### ISSUE TITLE
api server Docker image build is failing

### ISSUE THREAD

**Issue by chetanoruganti** [kubeflow/pipelines#2756]
I was trying to build the api server Docker image following developer_guide.md 
steps followed :
      1. Downloaded the master pipeline code to the local system .
      2.  trying to build the api server image by running the backend/Dockerfile

step   bazel --bazelrc=tools/bazel_builder/bazelrc   build -c opt backend/src/apiserver:apiserver
is failing with error 
  ERROR: /go/src/github.com/kubeflow/pipelines/backend/src/apiserver/BUILD.bazel:3:1: no such package '@io_k8s_client_go//kubernetes/typed/core/v1': failed to fetch io_k8s_client_go: 2019/12/19 07:10:01 unrecognized import path "k8s.io/client-go"
 and referenced by '//backend/src/apiserver:go_default_library'
ERROR: Analysis of target '//backend/src/apiserver:apiserver' failed; build aborted: no such package '@io_k8s_client_go//kubernetes/typed/core/v1': failed to fetch io_k8s_client_go: 2019/12/19 07:10:01 unrecognized import path "k8s.io/client-go"

**Comment by neuromage** [comment]
I was not able to reproduce. Can you try this with latest version?
