### ISSUE TITLE
maybeDeleteOldestViewer of viewer controller isn't working

### ISSUE THREAD

**Issue by descampsk** [kubeflow/pipelines#2757]
**What happened:**

When the number of viewers exceed MAX_NUM_VIEWERS, the viewer controller crashed.

**What did you expect to happen:**

The viewer controller must delete the oldest pods when there are more viewers than MAX_NUM_VIEWERS and then create a new viewer.

**What steps did you take:**
[A clear and concise description of what the bug is.]

*  change the MAX_NUM_VIEWERS env to 5.
*  create 6 tensorboard viewers through pipeline-ui, with the button Create Tensorboard

```python
from typing import NamedTuple
def mock_tb() -> NamedTuple('tb', [ ('mlpipeline_ui_metadata', 'UI_metadata')]):
    from collections import namedtuple
    import json
    metadata = {
    'outputs' : [{
      'type': 'tensorboard',
      'source': "s3://<path-to-reports>",
    }]
  }
    divmod_output = namedtuple('MyDivmodOutput', ['mlpipeline_ui_metadata']) 
    return divmod_output(json.dumps(metadata))
```

* see the viewer controller pods chain crash

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

I add the log file of the viewer controller:
[logs-from-ml-pipeline-viewer-controller-in-ml-pipeline-viewer-controller-deployment-844cd745d7-nlkqf.txt](https://github.com/kubeflow/pipelines/files/3982387/logs-from-ml-pipeline-viewer-controller-in-ml-pipeline-viewer-controller-deployment-844cd745d7-nlkqf.txt)

It seems that:
https://github.com/kubeflow/pipelines/blob/1b04983d96d097a12245a2d79469d3c51af5c7f4/backend/src/crd/controller/viewer/reconciler/reconciler.go#L266-L285

Will at a moment call: 
https://github.com/kubernetes-sigs/controller-runtime/blob/efbeb2728794b105247bbf27c76a5c4949a73010/pkg/client/typed_client.go#L72
```go
func (c *typedClient) Delete(ctx context.Context, obj runtime.Object, opts ...DeleteOption) error {
	o, err := c.cache.getObjMeta(obj)
	if err != nil {
		return err
	}


	deleteOpts := DeleteOptions{}
	deleteOpts.ApplyOptions(opts)
```

With opts ...DeleteOption = nil

It will then call:
https://github.com/kubernetes-sigs/controller-runtime/blob/efbeb2728794b105247bbf27c76a5c4949a73010/pkg/client/options.go#L222-L227
```go
func (o *DeleteOptions) ApplyOptions(opts []DeleteOption) *DeleteOptions {
	for _, opt := range opts {
		opt.ApplyToDelete(o)
	}
	return o
}
```

With ops = nil

It seems that ops can't be nil, that cause the nil pointer dereference.

I'm not a go developer so maybe i'm wrong.

Thanks !

**Comment by Bobgy** [comment]
It seems this is already fixed in #2853
/close

Please reopen if it's not the case
