### ISSUE TITLE
Question: Recomended way to work on big data

### ISSUE THREAD

**Issue by SpontaneousDuck** [kubeflow/pipelines#2758]
So I currently have a pipeline on our local cluster that has a good amount of storage but not infinite. I have a pipeline that pulls 250GB of data in to the cluster. Currently I am creating a PVC to put that data in so it can get passed between steps in the pipeline. Is there a good way with the python SDK to remove that large PVC after I am done with it? Or is there a better way to work on all that data between containers. Just don't want our large PVCs ballooning up to fill all our storage when they are no longer needed after executing the pipeline.

**Comment by parthmishra** [comment]
Not sure if you solved this already, but my possibly naive method to solve this would be using `dsl.ExitHandler` op that removes PVC and any other temporary resources upon Pipeline completion.

**Comment by Ark-kun** [comment]
There are some benefits of storing the intermediate data between pipeline runs as the system could cache executions instead of re-running the components every time.

The future solution will probably involve expiration time and garbage collection for the intermediate data.
