### ISSUE TITLE
Not able to deploy standalone deployment

### ISSUE THREAD

**Issue by Svendegroote91** [kubeflow/pipelines#2767]
**What happened:**
When following the instructions on https://www.kubeflow.org/docs/pipelines/installation/standalone-deployment/, more specifically when trying to execute 
```
kubectl apply -k github.com/kubeflow/pipelines//manifests/kustomize/env/dev?ref=$PIPELINE_VERSION
```

I get the following error `no matches found: github.com/kubeflow/pipelines//manifests/kustomize/env/dev?ref=0.1.38`
It looks like the reference to the installation files are not correct.

I tried to remove the double / between 'pipelines' and 'manifests' but that did not help either.

**What did you expect to happen:**
I would expect the github reference to be found.

**Comment by numerology** [comment]
/assign @Bobgy 
Seems like the file is not there. Can you confirm?
@Svendegroote91 You can also follow the guideline [here](https://github.com/kubeflow/pipelines/tree/master/manifests/kustomize) by replacing the `PIPELINE_VERSION`.

**Comment by Bobgy** [comment]
I will take a look

**Comment by Bobgy** [comment]
I verified it's still working well for me.
My kubectl version:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

I suspect this may be a version problem.

@Svendegroote91 can you share your kubectl version, which OS you are using?

**Comment by Bobgy** [comment]
url format seems to recently changed to not require that double slash: https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md#url-format

old format is consistent with the documentation: https://github.com/kubernetes-sigs/kustomize/blob/423a8a6e0dd3e6aa81d4f0aa82f86bb4007be342/examples/remoteBuild.md#url-format

I'm not sure which version support do they have

**Comment by Bobgy** [comment]
@Svendegroote91 ping after holiday
Can you still reproduce the issue?

**Comment by Svendegroote91** [comment]
Hey,

I am still getting the same issue:
![image](https://user-images.githubusercontent.com/33965133/71910617-85db5c80-3172-11ea-93e2-b33e00d35687.png)

Any thoughts?

The other [documentation](https://github.com/kubeflow/pipelines/tree/master/manifests/kustomize) works for me.

**Comment by Bobgy** [comment]
https://github.com/ohmyzsh/ohmyzsh/issues/31
It seems to be a zsh issue?

Svendegroote91 <notifications@github.com> 于 2020年1月8日周三 上午12:24写道：

**Comment by Bobgy** [comment]
/close
@Svendegroote91 please reopen if above issue doesn't solve your problem

**Comment by Bobgy** [comment]
/reopen
to wait for documentation
