### ISSUE TITLE
Compiling a pipeline produces: unknown field "volumes" error in argo

### ISSUE THREAD

**Issue by akranga** [kubeflow/pipelines#2768]
**What happened:**

1. Create a pipeline. Example can be found below
```python
@dsl.pipeline(
  name='PV pipeline',
  description='Lorem ipsum'
)
def my_pipeline():
    container_op(
        # job params
    ).add_pvolumes({
        '/mnt/s3': dsl.PipelineVolume(pvc=MY_PVC),
    })
        
Compiler().compile(my_pipeline, 'argo-wf.yaml')
```
2. Try to submit: `argo submit -f argo-wf.yaml`
3. See error 
`Failed to parse workflow: error unmarshaling JSON: while decoding JSON: json: unknown field "volumes"`

If you look inside of `argo-wf.yaml` you will see. It will try to create a "volumes" definition under `spec.templates.container[].volumes[]` when argo expects `spec.volumes[]`. See example [here](https://github.com/argoproj/argo/blob/master/examples/volumes-existing.yaml)

**What did you expect to happen:**
Compiler would generate valid argo yaml file.

**What steps did you take:**
At present I was forced to manually patch compiled workflow. See code below

**Anything else you would like to add:**

```python
def patch_pvolumes(file, write_to=None):
    """
    Writes container `spec.template.container.volumes` to `spec.volumes`
    incorrectly generated by kfp Compiler.compile(...) 
    """
    if not write_to:
        write_to=file
    
    import yaml
    with open(file) as f:
        yamldoc = yaml.load(f, Loader=yaml.FullLoader)

    def extract_vol(d, vols=[]):
        if isinstance(d, list):
            for v in d:
                vols = extract_vol(v, vols)
        if isinstance(d, dict):
            vols += d.pop('volumes', [])
            for k,v in d.items():
                vols = extract_vol(v, vols)
        return vols

    vols = yamldoc['spec'].get('volumes', []) + extract_vol(yamldoc['spec']['templates'])
    yamldoc['spec']['volumes'] = vols

    with open(write_to, 'w') as f:
        yaml.dump(yamldoc, f)

Compiler().compile(build_image, 'argo-wf.yaml')
patch_pvolumes('argo-wf.yaml')
```

Version info:
- KFP: v0.1.38
- Kubeflow: v0.5.1
- Argo: v2.2.0

**Comment by parthmishra** [comment]
This may be a dumb question, but are do Kubeflow pipelines compile directly to an Argo workflow definition? For some reason, I thought they were a custom resource on top of Argo.

**Comment by Ark-kun** [comment]
> * Argo: v2.2.0

The current SDK targets Argo 2.3.0. Argo can probably be upgraded without upgrading the rest of the system, but I'm not 100% sure.

>Kubeflow: v0.5.1

JFYI, this is really old.

>This may be a dumb question, but do Kubeflow pipelines compile directly to an Argo workflow definition? For some reason, I thought they were a custom resource on top of Argo.

We consider this to be an internal implementation detail of the current version of the system. It is true that currently the workflow is passed to Argo with very few tweaks. But we only support the workflows generated by the SDK (e.g. `steps` are not supported in the UX) and can technically change the format in the future.

There are some small tweaks that are done in backend at submission time: https://github.com/kubeflow/pipelines/blob/90b701d9ec2ce5e5b217896a42232ab75fb4df64/backend/src/apiserver/resource/resource_manager.go#L288

**Comment by akranga** [comment]
@Ark-kun any plans to make a corrective action regarding the issue? I am willing to get rid of `patch_pvolumes('argo-wf.yaml')` in my KFP generated pipelines code?

I may also do a PR however will need some guidelines where to apply a fix

**Comment by akranga** [comment]
@parthmishra you are correct. The Argo WFs are the custom resources :)... So, KFP indeed compiles directly. It took me a while to understand why my KFP jobs are failing. So, I started to tear down moving parts until realised the volumes issue (this)

**Comment by Ark-kun** [comment]
> @Ark-kun any plans to make a corrective action regarding the issue?

We have moved from workflow-wide volume definitions to per-template volume definition. https://github.com/kubeflow/pipelines/pull/2229 This makes the generated workflows less buggy and closer to Kubernetes. This has been supported since Argo 2.3.0 and Argo is now at v2.4.3 already.
I'm not sure it's desirable for us to revert the change.
The suggested fix is to upgrade Argo workflow controller.
Is there a problem with that approach?
