### ISSUE TITLE
invalid spec: spec.templates[1].name 'model-image-recognition' is not unique

### ISSUE THREAD

**Issue by praveen049** [kubeflow/pipelines#2769]
**What happened:**
When running a pipeline created with `func_to_container_op`, i am getting the error
`
invalid spec: spec.templates[1].name 'model-image-recognition' is not unique
`
**What did you expect to happen:**
I am expecting that the run will be successful and model created.

**What steps did you take:**
Below is the code
```
@func_to_container_op
def model_image_recognition(X_train, Y_train, X_test, Y_test, num_iterations = 2000, learning_rate = 0.5, print_cost = False):
    w, b = initialize_with_zeros(X_train.shape[0])
    parameters, grads, costs = optimize(w, b, X_train, Y_train, num_iterations, learning_rate, print_cost = True)
    
    w = parameters["w"]
    b = parameters["b"]
    
    Y_prediction_test = predict(w, b, X_test)
    Y_prediction_train = predict(w, b, X_train)

    d = {"costs": costs,
         "Y_prediction_test": Y_prediction_test, 
         "Y_prediction_train" : Y_prediction_train, 
         "w" : w, 
         "b" : b,
         "learning_rate" : learning_rate,
         "num_iterations": num_iterations}
    
    return d
```

I have tried creating a pipeline and loading it
```
kfp.compiler.Compiler().compile(model_image_recognition, '/mlblr-data/model_image_recognition.zip')
```

And also creating a run directly using `create_run` as below
```
kfp.Client().create_run_from_pipeline_func(model_image_recognition, arguments={'X_train': train_set_x, 'Y_train':train_set_y, 'X_test':test_set_x, 'Y_test':test_set_y})
```
And getting the same error.

I checked a previous similar [issue](https://github.com/kubeflow/pipelines/issues/428) where the problem was with the pipeline name and Op name are the same.  I suspect I am having the same issue as the pipeline is directly created from the function.
Is there a way to avoid this issue ?

Thanks

**Anything else you would like to add:**
i have uploaded the pipeline yaml for reference.
[model_image_recognition.zip](https://github.com/kubeflow/pipelines/files/3997188/model_image_recognition.zip)

**Comment by parthmishra** [comment]
I believe this is intended? Logically, the Pipeline is a collection of Components and since `func_to_container_op` generates a Kubeflow Component definition file this should be an invalid operation since a component != pipeline. If you want a Pipeline consisting of a single component, you need to define a pipeline function separately. If you want just the YAML of the component, you can specify the `output_yaml_file` argument in the `@func_to_container_op()`  decorator.

**Comment by numerology** [comment]
Thanks @parthmishra  for your answer. @praveen049 `func_to_container_op` only converts a python function into a container op, but not a pipeline function. You have to author a one-step pipeline explicitly and pass it into `compile()`.
