### ISSUE TITLE
advance k8s sdk requirements 

### ISSUE THREAD

**Issue by yaronha** [kubeflow/pipelines#2771]
currently KFP requires k8s 8.0-9.0 SDK, we have other packages in the same setups which require k8s 10.0 SDK, any reason we don't advance the k8s API ver limit?

**Comment by Ark-kun** [comment]
The version was fixed in https://github.com/kubeflow/pipelines/pull/1159
@gaoning777 Do you remember what the breaking change was?

**Comment by gaoning777** [comment]
Thanks Alexey for the fix.
/unassign @gaoning777
