### ISSUE TITLE
Configure Coveralls to keep track of test coverage for Go. 

### ISSUE THREAD

**Issue by vicaire** [kubeflow/pipelines#280]
Instructions for various languages can be found here:

https://docs.coveralls.io/go

**Comment by vicaire** [comment]
Sample PR: 

https://github.com/kubeflow/pipelines/pull/176

**Comment by IronPan** [comment]
@neuromage Do you mind taking a look this since the backend is now using bazel I think this tool might not be applicable. 
/assign @neuromage

**Comment by neuromage** [comment]
go test should work again once we remove MLMD dependency, which should happen over the next month. I'm assigning this back to you to decide whether you want coveralls test for the backend or not.
/assign @IronPan
