### ISSUE TITLE
Ability to set ImagePullPolicy on a per pipeline or cluster global level

### ISSUE THREAD

**Issue by goldenberg** [kubeflow/pipelines#2802]
We would like to set a default ImagePullPolicy on a per pipeline, or possibly cluster global level. 

Could this be implemented on the `PipelineConf` object? e.g. `PipelineConf.set_default_image_pull_policy()` Or is there another pattern you'd recommend?

Rationale: We've implemented a CI-driven semantic versioning scheme for our Docker images where we push an image with a semantic version tag of the form vX.Y.Z. When we build new images, we also push vX.Y and vX so that pipelines can reference a major.minor version and automatically pick up bug fixes.

We would like to set `ImagePullPolicy` to `Always` to ensure that we are always pulling the latest tagged version of these major versions. The layers should still cache pretty well, so we're not concerned about the additional latency on pipeline runs.

At the moment, we manually set image pull policy on every ContainerOp using the dsl and try not to forget on any new ones.
 
**What happened:**

We see different Docker containers pulled on different pipeline runs depending on whether the nodes already have an image present from a recent run or not.

**What did you expect to happen:**

Expected to see an ability to set image pull policy on a per pipeline level.

**What steps did you take:**

Examined documentation and code of PipelineConf.

**Anything else you would like to add:**
Let us know if this is not the right venue for this request. Thanks!

**Comment by NikeNano** [comment]
Sounds cool, would also appreciate this a lot. I will take a stab at fixing this!
