### ISSUE TITLE
Create experiment from Notebook and use link to open KFP UI. Back button doesn't work.

### ISSUE THREAD

**Issue by ajayalfred** [kubeflow/pipelines#281]
I ran a code cell to create an experiment. And used the link generated to open the Experiment details page. When I click the back button, nothing happens.

![image](https://user-images.githubusercontent.com/2425179/48571238-375a6700-e8bb-11e8-8d40-69290c1bd3fe.png)

**Comment by ajayalfred** [comment]
Same problem with using the 'Job link' from Notebook to view Run details. Back button doesn't do anything.

**Comment by rileyjbauer** [comment]
Closing as a dup of #221
