### ISSUE TITLE
Feature: 'arguments' to kfp.compiler.Compiler().compile 

### ISSUE THREAD

**Issue by plang85** [kubeflow/pipelines#2816]
It would be great to be able to pass `arguments` to `compiler.Compiler().compile` similar to `Client.create_run_from_pipeline_func` or am I missing something?

**Comment by numerology** [comment]
Hi @plang85 thanks for bringing this up.

Actually I am little bit of confused regarding your usage of pipeline parameter and argument. Pipeline parameters are only placeholders in the pipeline workflow def, while arguments are provided in `create_run_from_pipeline_func()` as the runtime values of pipeline parameters. Thus I don't see the point of providing argument at the compilation time.

Can you elaborate more on your use case?

**Comment by Ark-kun** [comment]
> It would be great to be able to pass `arguments` to `compiler.Compiler().compile` similar to `Client.create_run_from_pipeline_func` or am I missing something?

Can you elaborate more on your user scenario?

The compiled pipeline is still analogous to the pipeline function from which it was created.
If the function has parameters, then the pipeline will have them too. Then the user can create multiple runs from the pipeline just supplying new arguments. If the pipeline does not have free parameters, it will always do the same thing which limits its usefulness.

Maybe "default values" can help you:
```python
def my_pipeline(a: int = 42):
    ...
```
Parameter with default value does not require passing an argument for that parameter, so this does something similar to what you're asking.

**Comment by plang85** [comment]
@numerology @Ark-kun thanks for getting back to me - I'm new to this and was missing something. The default values do the trick, I can override these on argo submit (my use case is that we have an internal argo-as-a-service and I'm compiling kfp to the workflow definition and submitting those).

**Comment by aleksandra-sp** [comment]
Hi

I agree the arguments can be useful. I am setting up an automated release pipeline, one of the steps is the creation of a kubeflow pipeline. Since we have several environments with several container registries, I need to be able to pass the container image depending on the environment the kubeflow pipeline should be created for. I make use of environment variables to accomplish this now, but arguments would be handier.

**Comment by Bobgy** [comment]
/reopen
What prevents you from specifying the arguments when you submit the pipeline?
