### ISSUE TITLE
Cannot use AWS S3 bucket in region other than us-east-1

### ISSUE THREAD

**Issue by asaff1** [kubeflow/pipelines#2819]
Unable to use S3 bucket in region other than us-east-1.
The following `ml-pipeline` env configuration:

            - name: OBJECTSTORECONFIG_BUCKETNAME  
              value: kubeflow-bucket  
            - name: MINIO_SERVICE_SERVICE_HOST  
              value: s3.amazonaws.com  
            - name: MINIO_SERVICE_SERVICE_PORT  
              value: '80'  
            - name: OBJECTSTORECONFIG_ACCESSKEY  
              value: <aws-access-key>  
            - name: OBJECTSTORECONFIG_SECRETACCESSKEY  
              value: <aws-secret-access-key>  

Works only if the bucket is in us-east-1.

The problem is the code is hardcoded to use us-east-1.
In `client_manager.go`, when passing an empty string to the `region` parameter, the minio client will consider it as us-east-1:
https://github.com/kubeflow/pipelines/blob/10a4f55e3ae5ed0e47466ec3bd4f0d56b9333cec/backend/src/apiserver/client_manager.go#L326

https://docs.min.io/docs/golang-client-api-reference.html#MakeBucket

There should be an option to set it using environment variables, e.g `OBJECTSTORECONFIG_MINIO_REGION`.

**Comment by Jeffwan** [comment]
@asaff1 region has been added in #2080. Working on including this change into 1.0

**Comment by Jeffwan** [comment]
region has been added. This can be closed.

/close

**Comment by FGXZ2JO** [comment]
This problem still exists in the aws-v1.4.1 version. It will be very appreciated if you could provide me a hint about where to find this hard-coded region. @Jeffwan
