### ISSUE TITLE
KF favicon in incognito mode

### ISSUE THREAD

**Issue by ajayalfred** [kubeflow/pipelines#282]
Favicon not visible in incognito mode.

![image](https://user-images.githubusercontent.com/2425179/48571976-2579c380-e8bd-11e8-8317-1bb578928f4e.png)

**Comment by rileyjbauer** [comment]
This is just a matter of creating a new asset, although it may just be obsolete due to the Kubeflow dashboard work

**Comment by rmgogogo** [comment]
Please allow me close this one as 1.5 years past
