### ISSUE TITLE
Pipeline UI: logs keep force scrolling to bottom even after step has finished

### ISSUE THREAD

**Issue by amygdala** [kubeflow/pipelines#2824]
Using whatever pipelines version is included in 0.7.1.

In the Pipelines UI, the pod logs for a step keep autoscrolling back down to the bottom even after the step has finished and no new output is being generated.

That makes the logs essentially unusable for post-run debugging (since you can never keep earlier output in view long enough to read it properly...).  

(See also https://github.com/kubeflow/pipelines/issues/1790 from 08/19... however, it doesn't seem to have been fixed yet, and it's super annoying.  I don't have permissions to re-open that bug.)

**Comment by Bobgy** [comment]
Yes, it's still the case unfortunately. pipeline wasn't upgraded in KF 0.7.1, it is the same as kf 0.7. Can you open an issue to ask about integrating latest KFP instead？

**Comment by amygdala** [comment]
ah, okay (sorry, since it had been several months since the other bug was closed, I felt sure that a newer pipeline version must be included by now :).  Feel free to close this bug then. 

This one is related to KFP versioning: https://github.com/kubeflow/pipelines/issues/2826 — if we can make it workable/straightforward to upgrade the KFP version in-place, in a KF install, that would address such issues.

**Comment by Bobgy** [comment]
No worries, I understand the confusion. I will see what I can do for better KF upgrade support.

/close
