### ISSUE TITLE
It needs to be possible to upgrade a KFP installation in an existing KF cluster

### ISSUE THREAD

**Issue by amygdala** [kubeflow/pipelines#2826]
Following the instructions here: https://www.kubeflow.org/docs/pipelines/installation/standalone-deployment/
to upgrade the KFP part of an existing KF installation, I get a PVC-related error.  
There really should be some way to do this upgrade given the lag on the KFP versions bundled with the KF releases.  Am I missing something?

```
Error from server (Invalid): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"kind\":\"PersistentVolumeClaim\",\"metadata\":{\"annotations\":{},\"name\":\"mysql-pv-claim\",\"namespace\":\"kubeflow\"},\"spec\":{\"accessModes\":[\"ReadWriteOnce\"],\"resources\":{\"requests\":{\"storage\":\"20Gi\"}}}}\n"},"labels":null},"spec":{"storageClassName":null,"volumeName":null}}
to:
Resource: "/v1, Resource=persistentvolumeclaims", GroupVersionKind: "/v1, Kind=PersistentVolumeClaim"
Name: "mysql-pv-claim", Namespace: "kubeflow"
Object: &{map["apiVersion":"v1" "kind":"PersistentVolumeClaim" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"kind\":\"PersistentVolumeClaim\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"mysql\",\"app.kubernetes.io/component\":\"mysql\",\"app.kubernetes.io/instance\":\"mysql-0.1.31\",\"app.kubernetes.io/managed-by\":\"kfctl\",\"app.kubernetes.io/name\":\"mysql\",\"app.kubernetes.io/part-of\":\"kubeflow\",\"app.kubernetes.io/version\":\"0.1.31\"},\"name\":\"mysql-pv-claim\",\"namespace\":\"kubeflow\"},\"spec\":{\"accessModes\":[\"ReadWriteOnce\"],\"resources\":{\"requests\":{\"storage\":\"20Gi\"}},\"storageClassName\":\"\",\"volumeName\":\"mysql-pv\"}}\n" "pv.kubernetes.io/bind-completed":"yes"] "creationTimestamp":"2019-12-13T18:24:35Z" "finalizers":["kubernetes.io/pvc-protection"] "labels":map["app":"mysql" "app.kubernetes.io/component":"mysql" "app.kubernetes.io/instance":"mysql-0.1.31" "app.kubernetes.io/managed-by":"kfctl" "app.kubernetes.io/name":"mysql" "app.kubernetes.io/part-of":"kubeflow" "app.kubernetes.io/version":"0.1.31"] "name":"mysql-pv-claim" "namespace":"kubeflow" "resourceVersion":"2640" "selfLink":"/api/v1/namespaces/kubeflow/persistentvolumeclaims/mysql-pv-claim" "uid":"d08cf939-1dd5-11ea-9148-42010af0016d"] "spec":map["accessModes":["ReadWriteOnce"] "resources":map["requests":map["storage":"20Gi"]] "storageClassName":"" "volumeMode":"Filesystem" "volumeName":"mysql-pv"] "status":map["accessModes":["ReadWriteOnce"] "capacity":map["storage":"20Gi"] "phase":"Bound"]]}
for: "github.com/kubeflow/pipelines/manifests/kustomize/env/dev?ref=0.1.39": PersistentVolumeClaim "mysql-pv-claim" is invalid: spec: Forbidden: is immutable after creation except resources.requests for bound claims
```

**Comment by numerology** [comment]
/assign @Bobgy 
I'm not very familiar with the full fledge KF deployment, but if I remember correctly it was different than the standalone deployment. Perhaps it's currently not possible to update KFP in full fledge KFP using the standalone manifest.

Yuan will be the best person to answer this and correct me if I was wrong.

**Comment by Bobgy** [comment]
This specific problem may be solvable by simply not applying pvcs, delete them from your standalone manifests might fix it.
However, the two deployments are different in many ways. We can never guarantee applying standalone on Kubeflow deployment can upgrade it without problems.
I think we can only make a test suite for KFP on Kubeflow and update Kubeflow with latest KFP within a timely period.

**Comment by Bobgy** [comment]
@amygdala Is the reason you cannot use https://www.kubeflow.org/docs/pipelines/installation/standalone-deployment/ that you are also using other Kubeflow services?
What if you install a kubeflow without pipelines and argo, then install KFP standalone in the same cluster. Does that work for you?

**Comment by amygdala** [comment]
Yes -- correct that I am also using other KF services. This is in the context of a codelab. 

Ideally— though this might be too hard to accomplish— I would like to see a scenario where the user could deploy the KF install via the c2d app, then run a single command-line call (maybe accessing a kustomize config) to upgrade the KFP components if need be. Anything else I think is too complex for a codelab, both w.r.t being too time-consuming and error-prone for novices, and also not giving a good first impression of KF/P being 'easy' to use.  It sounds like this might be too hard to set up though.

**Comment by Bobgy** [comment]
Thanks, I got the context.

I agree with your ideal user journey, but I think that's hard to achieve from KFP side alone. Current KF upgrade design didn't try to support component level upgrade, that's the part we need to support this scenario. We could provide individual patched manifests (for upgrade KFP only) if there's an important KFP change you want for a workshop.

Applying KFP standalone in KF would never be stable enough for your use case (for workshops).

**Comment by amygdala** [comment]
thanks, okay, good to know.  We could close this if you want, or leave it open as 'aspirational' :).  It sounds like there would need to be a joint effort between KF Core and KFP to really address it.

**Comment by Bobgy** [comment]
Let's leave this open, if more users care about this. We can prioritize.

**Comment by jlewi** [comment]
@amygdala it looks like the problem is that you are trying to apply a patch to the PVC claim mysql-pv-claim which includes immutable changes. So one potential work around is just delete that claim and then run apply. 

It would be good to better understand though what the problem is could you post the following. The YAML spec for your existing PVC claim e.g.

```
kubectl get pvc -o yaml mysql-pv-claim 
```

And then also attach the YAML spec that you are trying to apply.

**Comment by amygdala** [comment]
Actually, there were a lot of errors when I tried again: https://gist.github.com/amygdala/d88e6304d3023e386b2f1f7bac3289bd
This was attempting to upgrade a KF 1.0.2 IAP installation to use KFP 0.5.1. via these upgrade instructions: https://www.kubeflow.org/docs/pipelines/installation/standalone-deployment/#upgrading-kubeflow-pipelines
(It has been a while, so I can't remember if I saw the same set of errors before or had some reason to latch on to the last PVC issue as particularly important.)

I haven't dug in carefully, but it seems that the 2 sets of configs are just not compatible? At any rate, one result of the attempt is 'no healthy upstream' for the KF IAP endpoint.

**Comment by Bobgy** [comment]
/lifecycle frozen

It is now possible to upgrade KFP from Kubeflow 1.1 on GCP, updating the upstream KFP manifest is enough.
I'd want to document this when there are user requests.

**Comment by jonasdebeukelaer** [comment]
@Bobgy it'd be great to see a guide for this. Just installed KF 1.1 and would love to get KFP 1.0 on there 🙏  

Tried hacking the standalone version into it but got shutdown

**Comment by jonasdebeukelaer** [comment]
Oh actually swapping in `pipelines/manifests/kustomize` into `kubeflow/upstream/manifests/pipelines/upstream` seems to have done the trick. Note: I had to do it _before_ deploying anything, otherwise I was getting `no healthy upstream` type errors.

**Comment by Bobgy** [comment]
Yes, that's right.

But KF 1.1 already comes with KFP 1.0

**Comment by jonasdebeukelaer** [comment]
oh really? is https://www.kubeflow.org/docs/reference/version-policy/ just outdated then?

**Comment by Bobgy** [comment]
Yes, it's outdated

**Comment by sachdevayash1910** [comment]
Having similar issues as mentioned here when upgrading KFP to 2.0.0-alpha7. I have Kubeflow 1.6.1 installed but the 2.0-alpha7 has some fixes that I want to try out. I am running into several of the patch errors.

`Error from server (Invalid): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"cache-server\",\"application-crd-id\":\"kubeflow-pipelines\"},\"name\":\"cache-server\",\"namespace\":\"kubeflow\"},\"spec\":{\"replicas\":1,\"selector\":{\"matchLabels\":{\"app\":\"cache-server\",\"application-crd-id\":\"kubeflow-pipelines\"}},\"template\":{\"metadata\":{\"labels\":{\"app\":\"cache-server\",\"application-crd-id\":\"kubeflow-pipelines\"}},\"spec\":{\"containers\":[{\"args\":[\"--db_driver=$(DBCONFIG_DRIVER)\",\"--db_host=$(DBCONFIG_HOST_NAME)\",\"--db_port=$(DBCONFIG_PORT)\",\"--db_name=$(DBCONFIG_DB_NAME)\",\"--db_user=$(DBCONFIG_USER)\",\"--db_password=$(DBCONFIG_PASSWORD)\",\"--namespace_to_watch=$(NAMESPACE_TO_WATCH)\"],\"env\":[{\"name\":\"DEFAULT_CACHE_STALENESS\",\"valueFrom\":{\"configMapKeyRef\":{\"key\":\"DEFAULT_CACHE_STALENESS\",\"name\":\"pipeline-install-config\"}}},{\"name\":\"MAXIMUM_CACHE_STALENESS\",\"valueFrom\":{\"configMapKeyRef\":{\"key\":\"MAXIMUM_CACHE_STALENESS\",\"name\":\"pipeline-install-config\"}}},{\"name\":\"CACHE_IMAGE\",\"valueFrom\":{\"configMapKeyRef\":{\"key\":\"cacheImage\",\"name\":\"pipeline-install-config\"}}},{\"name\":\"CACHE_NODE_RESTRICTIONS\",\"valueFrom\":{\"configMapKeyRef\":{\"key\":\"cacheNodeRestrictions\",\"name\":\"pipeline-install-config\"}}},{\"name\":\"DBCONFIG_DRIVER\",\"value\":\"mysql\"},{\"name\":\"DBCONFIG_DB_NAME\",\"valueFrom\":{\"configMapKeyRef\":{\"key\":\"cacheDb\",\"name\":\"pipeline-install-config\"}}},{\"name\":\"DBCONFIG_HOST_NAME\",\"valueFrom\":{\"configMapKeyRef\":{\"key\":\"dbHost\",\"name\":\"pipeline-install-config\"}}},{\"name\":\"DBCONFIG_PORT\",\"valueFrom\":{\"configMapKeyRef\":{\"key\":\"dbPort\",\"name\":\"pipeline-install-config\"}}},{\"name\":\"DBCONFIG_USER\",\"valueFrom\":{\"secretKeyRef\":{\"key\":\"username\",\"name\":\"mysql-secret\"}}},{\"name\":\"DBCONFIG_PASSWORD\",\"valueFrom\":{\"secretKeyRef\":{\"key\":\"password\",\"name\":\"mysql-secret\"}}},{\"name\":\"NAMESPACE_TO_WATCH\",\"valueFrom\":{\"fieldRef\":{\"fieldPath\":\"metadata.namespace\"}}}],\"image\":\"gcr.io/ml-pipeline/cache-server:2.0.0-alpha.7\",\"imagePullPolicy\":\"Always\",\"name\":\"server\",\"ports\":[{\"containerPort\":8443,\"name\":\"webhook-api\"}],\"volumeMounts\":[{\"mountPath\":\"/etc/webhook/certs\",\"name\":\"webhook-tls-certs\",\"readOnly\":true}]}],\"serviceAccountName\":\"kubeflow-pipelines-cache\",\"volumes\":[{\"name\":\"webhook-tls-certs\",\"secret\":{\"secretName\":\"webhook-server-tls\"}}]}}}}\n"},"labels":{"app.kubernetes.io/component":null,"app.kubernetes.io/name":null}},"spec":{"selector":{"matchLabels":{"app.kubernetes.io/component":null,"app.kubernetes.io/name":null}},"template":{"metadata":{"labels":{"app.kubernetes.io/component":null,"app.kubernetes.io/name":null}},"spec":{"$setElementOrder/containers":[{"name":"server"}],"containers":[{"$setElementOrder/env":[{"name":"DEFAULT_CACHE_STALENESS"},{"name":"MAXIMUM_CACHE_STALENESS"},{"name":"CACHE_IMAGE"},{"name":"CACHE_NODE_RESTRICTIONS"},{"name":"DBCONFIG_DRIVER"},{"name":"DBCONFIG_DB_NAME"},{"name":"DBCONFIG_HOST_NAME"},{"name":"DBCONFIG_PORT"},{"name":"DBCONFIG_USER"},{"name":"DBCONFIG_PASSWORD"},{"name":"NAMESPACE_TO_WATCH"}],"args":["--db_driver=$(DBCONFIG_DRIVER)","--db_host=$(DBCONFIG_HOST_NAME)","--db_port=$(DBCONFIG_PORT)","--db_name=$(DBCONFIG_DB_NAME)","--db_user=$(DBCONFIG_USER)","--db_password=$(DBCONFIG_PASSWORD)","--namespace_to_watch=$(NAMESPACE_TO_WATCH)"],"env":[{"name":"DEFAULT_CACHE_STALENESS","valueFrom":{"configMapKeyRef":{"key":"DEFAULT_CACHE_STALENESS","name":"pipeline-install-config"}}},{"name":"MAXIMUM_CACHE_STALENESS","valueFrom":{"configMapKeyRef":{"key":"MAXIMUM_CACHE_STALENESS","name":"pipeline-install-config"}}},{"name":"NAMESPACE_TO_WATCH","value":null,"valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}}],"image":"gcr.io/ml-pipeline/cache-server:2.0.0-alpha.7","name":"server"}]}}}}
to:
Resource: "apps/v1, Resource=deployments", GroupVersionKind: "apps/v1, Kind=Deployment"
Name: "cache-server", Namespace: "kubeflow"
for: "github.com/kubeflow/pipelines/manifests/kustomize/env/dev?ref=2.0.0-alpha.7": error when patching "github.com/kubeflow/pipelines/manifests/kustomize/env/dev?ref=2.0.0-alpha.7": Deployment.apps "cache-server" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"cache-server", "application-crd-id":"kubeflow-pipelines"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable`

This is happening for metadata-writer, ml-pipeline, ml-pipeline-persistenceagent, ml-pipeline-scheduledworkflow, ml-pipeline-ui, ml-pipeline-viewer-crd as well as the visualization server.

ANy advice on how I can fix it? @Bobgy

**Comment by juliusvonkohout** [comment]
/close

Since Kubeflow/manifests is now very close to the KFP releases
