### ISSUE TITLE
Pipeline run error: This step is in Error state with this message: volume 'mypvc' not found in workflow spec

### ISSUE THREAD

**Issue by kbentaleb** [kubeflow/pipelines#2828]
I am using the python code in this [link](https://github.com/kubeflow/pipelines/blob/master/samples/contrib/volume_ops/volumeop_sequential.py) to generate a kubeflow pipeline, but when I try to run the pipeline I have this issue "This step is in Error state with this message: volume 'mypvc' not found in workflow spec" in the container called "step1"

Kubelofw V0.5
Kubernetes V1.14

@elikatsis do you have an idea how can I resolve this issue ?

Thank you

![Sélection_055](https://user-images.githubusercontent.com/7852160/72211232-03cb9a80-34c8-11ea-83c8-74819631a76d.png)

**Comment by eterna2** [comment]
Which version of kfp sdk are u using? And can u provide the compiled yaml?

**Comment by kbentaleb** [comment]
@eterna2 
Thank you for your answer, I'm using kfp 0.1.40
You will find the compiled yaml in the attached file bellow.

[test-kfp.zip](https://github.com/kubeflow/pipelines/files/4050461/test-kfp.zip)

Thank you

**Comment by numerology** [comment]
@kbentaleb Can you try to use a latest version Kubeflow pipeline deployment?

Kubeflow 0.5 is very old and I'm pretty sure there are many incompatible features in KFP 0.1.40, which is the latest SDK

**Comment by eterna2** [comment]
I can't recall which version of Argo kubeflow 0.5 is on, but we upgraded to Argo 2.3 sometime in June (was 2.2 prior). 

This could be a possible reason. I will try a run on my cluster with ur yaml. If it works, most probably vol ops are not supported in Argo 2.2 (which I believe so, as there are a lot of new features added to 2.3).

**Comment by eterna2** [comment]
yeah. it works on my cluster.

**Comment by kbentaleb** [comment]
@eterna2 
Did you run the pipeline on kubeflow 0.5 ?
Can I just upgrade Argo or I have to upgrade Kubeflow to a recent version (v0.7) ?
Thank you

**Comment by Ark-kun** [comment]
> Can I just upgrade Argo or I have to upgrade Kubeflow to a recent version (v0.7) ?

You only need to upgrade Argo to v2.3.0.

**Comment by kbentaleb** [comment]
> You only need to upgrade Argo to v2.3.0.

@Ark-kun could you give me the command line to upgrade it on Ubuntu server please?

Thank you!

**Comment by Ark-kun** [comment]
> @Ark-kun could you give me the command line to upgrade it on Ubuntu server please?

It should be something like this:
```
kubectl set image deployment/workflow-controller workflow-controller=gcr.io/ml-pipeline/workflow-controller:v2.3.0-license-compliance --record
```
(With kubectl pointing to your cluster.)

Please let me know how this goes.

**Comment by kbentaleb** [comment]
Thank you @Ark-kun 
I upgraded Agro but it still gives the same issue, so I installed kubeflow 0.7 and uploaded a pipeline so I have always an issue. 
I noticed that the PVCs created from the pipeline are in pending status, and any PV was created. Is it normal ? Do you have some idea how to resolve the issue ?
Thank you

Pipeline used: [test-kfp.zip](https://github.com/kubeflow/pipelines/files/4058236/test-kfp.zip)
Issue: 
![Sélection_056](https://user-images.githubusercontent.com/7852160/72329614-5cac5600-36b5-11ea-9d7e-28202a221400.png)

**Comment by elikatsis** [comment]
It seems like your (default) storage class doesn't provision PVs for your PVCs.
If you know that your cluster has a storage class with a provisioner and you know its name, then you can try editing the `VolumeOp` in  your `.py` file adding the argument `storage_class`:
```python
...
vop = dsl.VolumeOp(
    ...,
    storage_class='provisioner-name'
)
```

**Comment by kbentaleb** [comment]
@elikatsis Thank you, 

I created two storage classes using a command line in the first one and YAML file in the second one

==> The first one was created by this command line:

> helm install --name-template nfs-client-provisioner   --set nfs.server=10.65.122.17   --set nfs.path=/exported/path   --set storageClass.name=nfs   --set storageClass.defaultClass=true   stable/nfs-client-provisioner

==> And the second one with an YAML file:

> ---
> apiVersion: storage.k8s.io/v1
> kind: StorageClass
> metadata:
>   name: standard
> provisioner: kubernetes.io/gce-pd
> parameters:
>   type: pd-standard
> volumeBindingMode: WaitForFirstConsumer
> ---

but I still have the same issue the PVC and pod are in pending status and no PV created

Any idea ?

**Comment by elikatsis** [comment]
Ok, so you have set the NFS one as your default storage class.
Have you tried to manually create a PVC and see that it gets bound?
