### ISSUE TITLE
Include kubectl install command in Github page

### ISSUE THREAD

**Issue by ajayalfred** [kubeflow/pipelines#284]
I tried installing pipeline using gcloud sdk and followed instructions on this [page](https://github.com/kubeflow/pipelines/wiki/Deploy-the-Kubeflow-Pipelines-Service). However when I tried running the kubectl commands it wouldn't work because it wasn't installed. Would be nice to include the code snippet below on the page for first-time users.

gcloud components install kubectl

**Comment by sarahmaddox** [comment]
This issue was moved to kubeflow/website#320
