### ISSUE TITLE
attempt to upload a pipeline of the same name is not handled gracefully

### ISSUE THREAD

**Issue by amygdala** [kubeflow/pipelines#2841]
This is for whatever KFP version the marketplace install is using.

If I try to upload a pipeline with the same name as an existing one, I get this error (rather than e.g. a warning that multiple pipelines can't have the same name):
![image](https://user-images.githubusercontent.com/115093/72388917-fc7cda80-36db-11ea-87b6-b258e3c4cc52.png)

**Comment by numerology** [comment]
Throwing an error is the intended behavior I believe. Though the error msg is messy.

**Comment by numerology** [comment]
/assign @jingzhang36 
/assign @Bobgy 
Do you have any input on this? Thanks!

**Comment by amygdala** [comment]
It used to give a better message (along the lines of 'can't have 2 pipelines with the same name').  Here's an example from an older KFP version (whatever is bundled with KF):
![image](https://user-images.githubusercontent.com/115093/72479612-d3c31680-37a9-11ea-8ad5-7eec642d6640.png)

**Comment by Bobgy** [comment]
I tried to install a marketplace KFP and uploaded the same pipeline twice. I got the meaningful error message.

I'm not sure what went wrong in your first screenshot. Can you share the cluster to me for debugging purposes?
![Screenshot from 2020-01-16 18-08-07](https://user-images.githubusercontent.com/4957653/72515737-5d96e080-388b-11ea-93d3-4ce1f0ed3e5a.png)

**Comment by amygdala** [comment]
Hmm, I can't repro it either on a new install, though unfortunately I've taken down the marketplace KFP install where I saw it.  Maybe it is some kind of transient issue.  Let's just keep an eye out for for its reoccurrence.

**Comment by amygdala** [comment]
fwiw, I have seen this error msg again.  (But I don't know how to particularly reproduce it :)

**Comment by numerology** [comment]
My theory would be that this is an error thrown by inverse proxy server. 

It's trying to render a error 500 page like [this one](https://lh3.googleusercontent.com/-uiMXLTTuCfU/WaBo_jagppI/AAAAAAAAT5I/f07EEDOM23A_mi8kGYBVitk1ZBas7G5vACLcBGAs/s1600/google%2Berror%2B500.png) @amygdala do you know which region this cluster is and exactly when did you hit this error? Thanks

**Comment by Bobgy** [comment]
Hey, actually I think it's not hard showing all error messages just as the text message without the object structure

/assign @Bobgy
