### ISSUE TITLE
Upload error when using `gcp.use_preemptible_nodepool()`

### ISSUE THREAD

**Issue by jadechip** [kubeflow/pipelines#2847]
**What happened:**

Uploading a pipeline with the `apply(gcp.use_preemptible_nodepool())` modifier results in the following error:

```
{"error_message":"Error creating pipeline: Create pipeline failed: Failed to get parameters from the workflow: InvalidInputError: Failed to parse the parameter.: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal object into Go struct field NodeAffinity.preferredDuringSchedulingIgnoredDuringExecution of type []v1.PreferredSchedulingTerm","error_details":"Error creating pipeline: Create pipeline failed: Failed to get parameters from the workflow: InvalidInputError: Failed to parse the parameter.: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal object into Go struct field NodeAffinity.preferredDuringSchedulingIgnoredDuringExecution of type []v1.PreferredSchedulingTerm"}
```

![image](https://user-images.githubusercontent.com/5690384/72442124-857c3a80-37de-11ea-9267-2b09264b0f3f.png)

This is true for both my own custom pipeline, and the example in the docs:
```
import kfp.dsl as dsl
import kfp.gcp as gcp

class FlipCoinOp(dsl.ContainerOp):
  """Flip a coin and output heads or tails randomly."""

  def __init__(self):
    super(FlipCoinOp, self).__init__(
      name='Flip',
      image='python:alpine3.6',
      command=['sh', '-c'],
      arguments=['python -c "import random; result = \'heads\' if random.randint(0,1) == 0 '
                 'else \'tails\'; print(result)" | tee /tmp/output'],
      file_outputs={'output': '/tmp/output'})

@dsl.pipeline(
  name='pipeline flip coin',
  description='shows how to use dsl.Condition.'
)

def flipcoin():
  flip = FlipCoinOp().set_gpu_limit(1, 'nvidia').apply(gcp.use_preemptible_nodepool())
if __name__ == '__main__':
  import kfp.compiler as compiler
  compiler.Compiler().compile(flipcoin, __file__ + '.zip')
```
https://www.kubeflow.org/docs/gke/pipelines/preemptible/

If I remove `apply(gcp.use_preemptible_nodepool())`, the pipeline gets uploaded without error.

**What did you expect to happen:**

The compiled pipeline should upload without error.

**What steps did you take:**

1. Compiled the pipeline.
2. Uploaded the compressed file via the pipelines UI.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

My cluster is on GCP, and was deployed with the latest version of kfctl and the following manifest:
https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_gcp_basic_auth.0.7.1.yaml

I've added a gpu pool to my cluster with the following command:

```
gcloud container node-pools create preemptible-gpu-pool \
    --cluster=kubeflow-labs-4-cluster \
    --enable-autoscaling --max-nodes=4 --min-nodes=0 \
    --preemptible \
    --node-taints=preemptible=true:NoSchedule \
    --service-account=kubeflow-labs-4-cluster-vm@kubeflow-labs-4.iam.gserviceaccount.com \
    --accelerator=type=nvidia-tesla-t4,count=1
```

Any and all assistance is very much appreciated 🙏

**Comment by jadechip** [comment]
On second thought, could this be related to the node taint that are sometimes associated with preemptible GPUs?

**Comment by Ark-kun** [comment]
> On second thought, could this be related to the node taint that are sometimes associated with preemptible GPUs?

Probably not related. The issue seems to be related wither to wrong structure format or JSO truncation.

**Comment by jadechip** [comment]
Cool, let me know if I can be of any help from my end!

**Comment by alimhanif** [comment]
similar issue, but i tried to use this:
```
.apply(gcp.use_preemptible_nodepool({'effect': 'NoSchedule',
 'key': 'preemptible',
 'operator': 'Equal',
 'toleration_seconds': None,
 'value': 'true'},
    True))
```
I don't no why, but it works.

i just change the `hard_constraint` value to be True

**Comment by rmgogogo** [comment]
it works, here close

**Comment by jnmclarty** [comment]
Should some info be added to the docs?  Or is there a legit bug with the serialization?  Fwiw, using that snippet worked for me too.

**Comment by Ark-kun** [comment]
I think this is a valid issue with the `use_preemptible_nodepool` extension.

`hard_constraint` switches code paths from a broken one to the correct one.
