### ISSUE TITLE
Proxy agent failed to claim URL

### ISSUE THREAD

**Issue by IronPan** [kubeflow/pipelines#2848]
The error message 
2020/01/15 18:55:19 Failed to read pending requests: "A proxy request failed: \"Get nullagent/pending: unsupported protocol scheme \\\"\\\"\""

This is due to a malformed backend Id given by the agent. this is might be introduced by 
https://github.com/kubeflow/pipelines/commit/b5c54e1ba7aaf052a9a2bd21826429454b5f300c#diff-986b1153a97bee60b4f31250ea1ed45c

**Comment by IronPan** [comment]
Temporarily comment out the component to unblock the deployment
https://github.com/kubeflow/pipelines/pull/2585/files#diff-3a0f0bc1ff508db606c9f7b3c30f90ec

**Comment by rmgogogo** [comment]
as synced, it's due to use "dev/latest" manifest with old image (0.1.40), aka manifest and image not match.

The released 0.1.40 is OK.

So turn to P1. TODO things:
(1) revert #2849 in 0.1.41 release
(2) add daily images mark as "dev" so that it can better match with latest manifest.

**Comment by rmgogogo** [comment]
Mark as fixed, to use dev, we need to use latest corresponding image.
A new release on the flight will fix this.
