### ISSUE TITLE
Convert samples and docs from ContainerOp to components

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#2855]
We'd like to promote reusable component creation.
Creating components using Python (`func_to_container_op`), YAML (`component.yaml`) or `ComponentSpec` is not significantly harder than instantiating a ContainerOp, but results in actual components that can be reused and shared.

We need to replace the instances of direct `ContainerOp` usage with appropriate components.
All instances of `ContainerOp(...)` in samples and docs should be replaced with one of the following:

* `load_component_from_uri(...)` / `load_component_from_file(...)`
* `load_component_from_text(...)`
* `func_to_container_op(...)`

**Comment by eterna2** [comment]
Just wondering if there is anywhere I can read up on future plans for reusable components?

Becuz this is one of the things our team are exploring to make things even easier for data scientists that are not that familiar with devops concepts. 

We are also considering migrating from light-weight python components to reusable components concept.

**Comment by eterna2** [comment]
Just another question, how is component spec better than just exporting my containerop as a python package?

As in other can reuse my op by importing it like regular py modules?

**Comment by Ark-kun** [comment]
>Just wondering if there is anywhere I can read up on future plans for reusable components?

Reusable components are very important for our future. We want to build more functionality around them. (Some functionality is already checked in, but not fully documented.)

>We are also considering migrating from light-weight python components to reusable components concept.

Lightweight components feature is built on top of the reusable components / `ComponentSpec`. It just auto-generates the ComponentSpec from python function. You can export the component file nby adding `func_to_container_op(..., output_component_file='component.yaml')`. So, Lightweight components ARE reusable components.  See https://github.com/kubeflow/pipelines/tree/ee527c8/components/gcp/automl/create_model_for_tables Maybe you can elaborate on your migration plans and reasons.

>Just another question, how is component spec better than just exporting my containerop as a python package?
>As in other can reuse my op by importing it like regular py modules?

I've seen several people try doing that and I'm not sure they succeeded.
There are many reasons why declarative approach is significantly better that using a powerful imperative language like Python just to describe a data structure.

Shareable component definition should be:
* Portable
* * Generic
* * Should be as system-independent as possible
* * Can be created from any language or manually
* * Can be read in any language (Python, Javascript, Go)
* Minimal representation of the component
* Easy to create
* * Easy to maintain (less ways to break backwards compatibility)
* * Indexable and safe to inspect
* Format should be declarative to satisfy portability and safety
* * Industry standard format like YAML or JSON
* Easy and safe to load:
* * No installation required
* * No system modification
* * No code execution
* * Load specific version
* * * Multiple versions can coexist
* * * Load by immutable hash-digest
* * * Load by mutable tag

Using python packages as components is also pretty cumbersome.
Creating: Create a python package vs creating a JSON/YAML file.
Sharing: Registering and uploading a package to PyPI vs. just uploading a single file anywhere.
Loading: Installing and running executable code vs. just loading a text file.
Versioning: Loading by name, not version; global installation or virtual environments vs. just easily loading a specific version or even using multiple versions.
