### ISSUE TITLE
[FeatureRequest] Write the code tree on developer_guide.md

### ISSUE THREAD

**Issue by sakaia** [kubeflow/pipelines#2857]
**What happened:**
It is difficult to find the specific code and its software archtecture of kubeflow/pipeline.
Hopefully the code tree is written on developer_guide.md

**What did you expect to happen:**
Easily to find the specific code and understands software archtecture of kubeflow/pipeline.

**What steps did you take:**
This is document feature request (bug?) so no step to reproduce 

**Anything else you would like to add:**
The software code tree should be added in developer_guide.md

The current document is follows
https://github.com/kubeflow/pipelines/blob/master/developer_guide.md

**Comment by Bobgy** [comment]
@sakaia friendly ping
