### ISSUE TITLE
Why KFP mark a step/op as success when an op receives an unexpected Sigterm?

### ISSUE THREAD

**Issue by wzhou18** [kubeflow/pipelines#2861]
**What happened:**
we use kfp's wait_job function (https://github.com/kubeflow/pipelines/blob/master/components/gcp/container/component_sdk/python/kfp_component/google/ml_engine/_wait_job.py) to wait for a MLEngine job to finish. But there was one execution where the application received an unexpected Sigterm, and KFP thought the MLEngine job should not be cancelled and marked that task/step as success. This is not our expected, since the wait_job didn't wait till job finished and continued to run following steps.
The kfp Sigterm exit_handler code: https://github.com/kubeflow/pipelines/blob/8e119e7cd382734086aad7e20c2bbafd98afd936/components/gcp/container/component_sdk/python/kfp_component/core/_kfp_execution_context.py#L103

**What did you expect to happen:**
We expect that KFP should raise an exception and mark that step/op as a failure when a task/op receives an unexpected Sigterm signal.

**What steps did you take:**
[A clear and concise description of what the bug is.]
dsl.ContainerOp(
    name=name,
    image=wait_component_image,
    arguments=[
       "kfp_component.google.ml_engine",
        "wait-job",
         "--project_id",
          gcp_project_id,
          "--job_id",
          job_id,
         "--wait_interval",
         wait_interval_in_seconds,
         "--show_tensorboard",
         "False",
   ],
)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
We would like to know why KFP treat such situation as a success. Is it by design?

**Comment by rmgogogo** [comment]
Hi Alexy/Jessie, not sure who handles these part (CMLE component)
