### ISSUE TITLE
[FeatureRequest] Add nodeselector to pipelineconfig in kfp sdk

### ISSUE THREAD

**Issue by descampsk** [kubeflow/pipelines#2863]
Today the only way to use NodeSelector with the kfp sdk is to use the following function:

https://github.com/kubeflow/pipelines/blob/c0153a0b199eb4ec1323fc87d5cc31ca92be7dca/sdk/python/kfp/dsl/_container_op.py#L823

I think it will be a good idea to be able to use nodeSelector at the Worflow level:

https://github.com/argoproj/argo/blob/5868982bcddf3b9c9ddb98151bf458f6868dce81/pkg/apis/workflow/v1alpha1/workflow_types.go#L188

To do this, we have to add a nodeSelector attribut in pipeline conf: 

https://github.com/kubeflow/pipelines/blob/c0153a0b199eb4ec1323fc87d5cc31ca92be7dca/sdk/python/kfp/dsl/_pipeline.py#L54-L62

And use it inside the compiler in the same way we define ttls:

https://github.com/kubeflow/pipelines/blob/c0153a0b199eb4ec1323fc87d5cc31ca92be7dca/sdk/python/kfp/compiler/compiler.py#L668-L670

We could just add the following lines:

```python
if pipeline_conf.node_selector != None:
      workflow['spec']['nodeSelector'] = pipeline_conf.node_selector
```

What do you think ?

If I have some times, I will try a PR.

**Comment by NikeNano** [comment]
I will look in to this, seams very similar to https://github.com/kubeflow/pipelines/pull/3534

**Comment by NikeNano** [comment]
I think this can be closed @Ark-kun
