### ISSUE TITLE
Is there a way to perform post pipeline run operations

### ISSUE THREAD

**Issue by keeplearnin** [kubeflow/pipelines#2869]
Is there a way that I could perform post-pipeline operations so that I can do things like:
* retry when failing
* send notification when complete with the run result
* run another pipeline when the current one is finished

Thanks!

**Comment by numerology** [comment]
Currently, such functions are provided through [ExitHandler](https://github.com/kubeflow/pipelines/blob/master/samples/core/exit_handler/exit_handler.py). By using it you can:

- send notifaction
- garbage collection
- maybe run another pipeline, if you can somehow package another 'pipeline' as a single task

For the retry when failing we do not really have auto-retry yet, but there is a button in our UI to do that easily.

**Comment by keeplearnin** [comment]
Let me have a try on the ExitHandler. For retry I guess I could probably just use the ExitHandler to call the pipeline API to run it again?

**Comment by numerology** [comment]
> Let me have a try on the ExitHandler. For retry I guess I could probably just use the ExitHandler to call the pipeline API to run it again?

Good question. I think if you can find a way to put the workflow_id or run_id in the ExitHandler in principle you should be able to do that.

**Comment by numerology** [comment]
Another resort could probably be the set_retry function ([example](https://github.com/kubeflow/pipelines/blob/master/samples/core/retry/retry.py)). Though it works on a step instead of the whole pipeline.

**Comment by rmgogogo** [comment]
I think if step failed and retried, not necessary to retry whole pipeline. 

Here mark as closed.
