### ISSUE TITLE
Compliance to Kubeflow 1.0 Guideline

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#2884]
Reference: [Kubeflow 1.0 Guideline](https://github.com/kubeflow/community/blob/master/guidelines/application_requirements.md)

The following is the original doc and a column for Kubeflow Pipelines' status with each requirement.

**Comment by Bobgy** [comment]
* [ ] (p0, 0.2w) Liveness/Readiness signals for metadata grpc server to resolve issue https://github.com/kubeflow/metadata/issues/198
* [ ] (p1, 1w) Basic Liveness/Readiness signals for other servers

**Comment by Bobgy** [comment]
* [ ] (p0, 0.2w) app.kubernetes.io labels on every resource
* [ ] (p0, 0.2w) Separate cluster scoped and namespace scoped resources

**Comment by Bobgy** [comment]
## Logging and monitoring
* [ ] (p1, 1w) Prometheus metrics
* [ ] (p2, 2w) Json logging

**Comment by Bobgy** [comment]
## Docker Images
* (p1, 2w) Vulnerability Scanning
* (p2, 1w) Licensing, add license presubmit tests as documented [here](https://github.com/kubeflow/testing/tree/master/py/kubeflow/testing/go-license-tools#add-ci-tests-for-license-information)

**Comment by Bobgy** [comment]
Custom Resources

The following requirements were mentioned, but I don't think they apply to Kubeflow Pipelines. All CRDs of Kubeflow Pipelines are meant to be internal implementation details, rather than sth users should directly use.

| Description | Category | Explanation |
|-------------|----------|-------------|
| Version stability | Required  | <ul><li>No deprecative API changes </ul> |
| Multi Version Support | Required  | <ul><li>Serves multiple versions of the [CR per K8s docs](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/#specify-multiple-versions) </ul> |
| Supports status subresource | Required  | <ul><li>Status subresource documented [here](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#status-subresource) </ul> |
| CRD schema validation | Required  | <ul><li>Validation documented [here](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#validation) <li>Example: [TFJob](https://github.com/kubeflow/kubeflow/blob/v0.6.1/kubeflow/tf-training/tf-job-operator.libsonnet#L81) </ul> |
| Training operators follow kubeflow/common conventions | Required  | <ul><li>Conventions defined [here](https://github.com/kubeflow/common/blob/master/job_controller/api/v1/types.go) <li>Examples: [TFJob](https://github.com/kubeflow/kubeflow/blob/v0.6.1/kubeflow/tf-training/tf-job-operator.libsonnet) and [PyTorchJob](https://github.com/kubeflow/kubeflow/blob/v0.6.1/kubeflow/pytorch-job/pytorch-operator.libsonnet) </ul> |

**Comment by Bobgy** [comment]
## CI/CD

| Description | Category | Status | Explanation |
|-------------|----------|--------|-------------|
| E2E tests | Required  | OK | <ul><li>E2E tests should be run on presubmit, postsubmit, and periodically <li> Tests should cover deployment (kustomize packages) <li> As well as the application functionality </ul> |
| Scalability / load testing | Required  | WIP #2571  | <ul><li>Applications must have scalability and or load testing demonstrating that the application meets appropriate requirements for the application (e.g. # of concurrent CRs) </ul> |
| Continuous building of docker images | Recommended  | OK | <ul><li>On post-submit, docker images should be automatically built and pushed  </ul> |
| Continuous updating of Kustomize manifests | Recommended  | Not planned | <ul><li>On post-submit, kustomize packages should be automatically updated to point to latest images </ul> |

**Comment by Bobgy** [comment]
## Docs

| Description | Category | Status | Explanation |
|-------------|----------|--------|-------------|
| API Reference docs | Required  | WIP #3216 | <ul><li>Applications exposing APIs (e.g. CRs) need reference docs documenting the API </ul> |
| Application docs | Required  | OK | <ul><li>There must be docs on kubeflow.org explaining what an application is used for and how to use it </ul> |

**Comment by Bobgy** [comment]
## Ownership/Maintenance

| Description | Category | Status | Explanation |
|-------------|----------|--------|-------------|
| Healthy number of committers and commits | Required  | OK | <ul><li> Committers are listed as approvers in owners files <li> Number to be determined by TOC based on size and scope of application </ul> |
| At least 2 different organizations are committers | Required  | OK | |

**Comment by Bobgy** [comment]
## Adoption

| Description | Category | Status | Explanation |
|-------------|----------|--------|-------------|
| List of users running the application | Recommended  | Not yet planned, but we can do this | <ul><li>Suggest listing adopters willing to be identified publicly in ADOPTERS.md </ul> |

**Comment by Bobgy** [comment]
All actionable items done for 1.0

**Comment by zijianjoy** [comment]
/close

I believe this issue can be closed now.
