### ISSUE TITLE
Add KFP backend presubmit test to prow config at prow/prowjobs/kubeflow/kubeflow-presubmits.yaml

### ISSUE THREAD

**Issue by jingzhang36** [kubeflow/pipelines#2885]

**Comment by jingzhang36** [comment]
@jlewi do you know the ETA of these two PRs #93 and #177? If they are not planned to be merge soon, I'll probably still add Prow tests of KFP backend to the old place.

**Comment by jlewi** [comment]
@jingzhang36 I think you linked to the wrong PRs.

Assuming you meant the migration of the Kubeflow prow instance; I think that is stalled.

**Comment by jingzhang36** [comment]
@jlewi Since the migration of the Kubeflow prow instance is stalled, I revived this PR of adding KFP backend presubmit test to prow. https://github.com/kubeflow/pipelines/issues/2885. Could you take a look? Thanks!
