### ISSUE TITLE
Kubeflow pipelines in other languages?

### ISSUE THREAD

**Issue by ConnorBarnhill** [kubeflow/pipelines#2887]
Is there a way to define kubeflow pipelines for training models in other languages (not python)?

**Comment by numerology** [comment]
/assign @numerology 

@ConnorBarnhill  Can you clarify whether you want to **write a pipeline in other language** or **write the training code in other language** and then use it in a pipeline (written in Python)? Thanks

**Comment by ConnorBarnhill** [comment]
I guess both. Presumably it's possible to write the training code in another language and specify the pipeline in python referencing the image. Is it possible to specify the pipeline in another language?

**Comment by numerology** [comment]
> I guess both. Presumably it's possible to write the training code in another language and specify the pipeline in python referencing the image. Is it possible to specify the pipeline in another language?

At least for now the pipeline SDK is only in Python. Another option is perhaps directly working with yaml format.
