### ISSUE TITLE
Using custom DNS with Python SDK (kfp)

### ISSUE THREAD

**Issue by kelvins** [kubeflow/pipelines#2888]
The `_is_iap_host` method is being called in the `Client` initialization, but it is using a `regex` based on the default DNS (e.g. `kubeflow.endpoints.my-project.cloud.goog/pipeline`):

https://github.com/kubeflow/pipelines/blob/0577fe10fdc3c57cd56ca3b65198c03636ae4520/sdk/python/kfp/_client.py#L156-L161

In this case, how can we use a custom DNS?

**Comment by Ark-kun** [comment]
Maybe we should add the optional `use_iap` parameter, so that the user can specify this explicitly.

**Comment by kelvins** [comment]
Sounds good, but as far as I know `client_id` is only used for IAP, so passing `client_id` and `use_iap` seems to be a little redundant.

Another option would be to change the regular expression to not be so restricted, for example:

```python
def _is_iap_host(self, host, client_id):
    if host and client_id:
        if re.match(r'\S+/{0,1}$', host):
            warnings.warn('Suffix /pipeline is not ignorable for IAP host.')
        return re.match(r'\S+/pipeline', host)
    return False
```

**Comment by Ark-kun** [comment]
@numerology @hongye-sun WDYT?

**Comment by Bobgy** [comment]
/close
Already fixed by https://github.com/kubeflow/pipelines/pull/3003
