### ISSUE TITLE
Pipeline Summary is blocking the graph

### ISSUE THREAD

**Issue by lluunn** [kubeflow/pipelines#289]
<img width="653" alt="screen shot 2018-11-15 at 13 52 46" src="https://user-images.githubusercontent.com/32310205/48584148-db550a00-e8dd-11e8-92a6-ebbc2d3aa683.png">

I think summary should not be rendered on top of the graph?

**Comment by yebrahim** [comment]
We can also add some bottom margin where the hidden summary won't overlap with the graph.
@ajayalfred any preference here?

**Comment by ajayalfred** [comment]
The hidden summary should be a button. See the two states below:

Summary open
![image](https://user-images.githubusercontent.com/2425179/48586703-83ba9c80-e8e5-11e8-888d-2b70aa9bfef8.png)

Summary closed
![image](https://user-images.githubusercontent.com/2425179/48586720-903ef500-e8e5-11e8-8e52-8b9c5d8112fe.png)
