### ISSUE TITLE
KFP Deployment upgrade is broken due to immutable field

### ISSUE THREAD

**Issue by jingzhang36** [kubeflow/pipelines#2892]
How to reproduce?

1. Create a cluster
2. Deploy standalone KFP with release 0.1.40
kubectl apply -k github.com/kubeflow/pipelines//manifests/kustomize/env/dev?ref=0.1.40
3. The above deployment is good
4. Upgrade to KFP release 0.2.0
kubectl apply -k github.com/kubeflow/pipelines//manifests/kustomize/env/dev?ref=0.2.0
5. Got error on immutable field "LabelSelectorRequirement", due to trying to add value for "app" and "application-crd-id"

**Comment by hanneshapke** [comment]
@jingzhang36 Did you find a workaround? Facing the same issue now.

**Comment by Bobgy** [comment]
@hanneshapke You can delete all KFP related deployments via kubectl and apply again.

To get deployments: `kubectl get deployment -n $NAMESPACE`
To delete: `kubectl delete deployment XXX -n $NAMESPACE`

Deployments are stateless, so it's safe to delete.

**Comment by hanneshapke** [comment]
Great! that's what I ended up doing. Thank you for your reply.

**Comment by Bobgy** [comment]
We've provided workaround.
