### ISSUE TITLE
Deploy visualization service for each namespace

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#2899]
A topic brought up in https://github.com/kubeflow/pipelines/issues/1610.

>  As a temporary solution, our engineers grant GCS read permissions to the UI service account to view their GCS bucket objects. But we are wondering if there could be a way to use the proper secrets when the call to GCS is made in the UI backend.

> Is this something others have thought about, especially in a multi-user context?

Currently, UI server needs GCP/AWS permissions to visualize artifacts in GCS/S3. We need a design to support permission separation for multiple users sharing a KFP cluster.

**Comment by Bobgy** [comment]
This is part of https://github.com/kubeflow/pipelines/issues/1223

**Comment by IronPan** [comment]
This should be done by deploying visualization service for each namespace.

**Comment by Bobgy** [comment]
@chensun I'm blocked by https://github.com/kubeflow/pipelines/pull/3495#discussion_r413068687 for adding this to UI. Can you help me troubleshoot?

**Comment by Bobgy** [comment]
UI PR to use namespaced api: https://github.com/kubeflow/pipelines/pull/3603
