### ISSUE TITLE
[FeatureRequest] Reusable Component Registry

### ISSUE THREAD

**Issue by parthmishra** [kubeflow/pipelines#2905]
It would be cool if there was a way to maintain a catalog/registry of reusable components for sharing. I would want to be able to view a component in the UI and see inputs, outputs, description, version, etc. Basically the information in the README for the sample components but perhaps auto-generated in some way from the component definition file. I think the [Terraform public module registry](https://registry.terraform.io/browse/modules) is a good example of how this could look/work.

I assume GCP will do something like this on AI Hub (have they? I don't look there very often) but it would nice to have components colocated in the UI. Perhaps in the future, if there's a visual pipeline editor, this could be integrated somehow.

**Comment by Bobgy** [comment]
I like the idea too! Thanks for writing it down here.
We are focusing on polishing existing features now, contributions welcomed on this.

**Comment by Ark-kun** [comment]
> I assume GCP will do something like this on AI Hub

That was one of the goals for AI-Hub



> it would nice to have components colocated in the UI. Perhaps in the future, if there's a visual pipeline editor, this could be integrated somehow.

Totally agree. I have a design for this: The user has an editing canvas and there is a Components pane where the user can search for components and drag them to the canvas to connect together and configure.

**Comment by alexlatchford** [comment]
Not sure if this is 100% related to this well defined issue but in larger enterprises I could see the need for an internal component registry for sharing best practices between teams/orgs but not necessarily be able to publish these publicly for one reason or another.

**Comment by parthmishra** [comment]
@alexlatchford That's a good point and in AI Hub, they seem to handle this by having a concept of "private assets" which is the same functionality as public shareable components/pipelines, but just for an organization/team

**Comment by Ark-kun** [comment]
> Not sure if this is 100% related to this well defined issue but in larger enterprises I could see the need for an internal component registry for sharing best practices between teams/orgs but not necessarily be able to publish these publicly for one reason or another.

The private components can just be loaded from URIs.
Also the kfp.components.ComponentStore class allows to add a URI search prefixes and then load components just by name. This should make it easier for private repos. 
The ComponentStore class does not have any listing or search capabilities yet.
