### ISSUE TITLE
Failed to retry run

### ISSUE THREAD

**Issue by prcastro** [kubeflow/pipelines#2908]
**What happened:**

Clicked on the `Retry` button and we got the following error:

```
Failed to retry run: 333fb6ab-e074-4814-bc85-524289076d60 with error: "
{
  "error": "InternalServerError: Retry run failed. Failed to clean up the failed pods from previous run.: InternalServerError: Failed to delete pods.: an empty namespace may not be set when a resource name is provided",
  "message": "InternalServerError: Retry run failed. Failed to clean up the failed pods from previous run.: InternalServerError: Failed to delete pods.: an empty namespace may not be set when a resource name is provided",
  "code": 13,
  "details": [
    {
      "@type": "type.googleapis.com/api.Error",
      "error_message": "Internal Server Error",
      "error_details": "InternalServerError: Retry run failed. Failed to clean up the failed pods from previous run.: InternalServerError: Failed to delete pods.: an empty namespace may not be set when a resource name is provided"
    }
  ]
}"
```

**What did you expect to happen:**

I excepted it to retry the failing Op

**What steps did you take:**
Deployed a failing pipeline and clicked Retry

**Anything else you would like to add:**
Pipelines version 0.2.0, but was happening since version 0.1.37. If you need any other info, please ask.

My feeling is that the namespace is `nil` when we make this call:

https://github.com/kubeflow/pipelines/blob/ca58b2227fe4a5e46f3d45c7c80a4707d652b0b7/backend/src/apiserver/resource/resource_manager.go#L443

**Comment by shotarohorai** [comment]
I got the same error.
It seems that it becomes successful with retrying a run if I specify the namespace passed to `create_run_from_pipeline_func` function whether or not kubeflow is deployed in the default namespace `kubeflow`.

```
kfp.Client().create_run_from_pipeline_func(pipeline_func=pipeline, arguments={}, namespace='kubeflow')
```

**Comment by rmgogogo** [comment]
I can reproduce the issue.

**Comment by rmgogogo** [comment]
@jingzhang36 the issue we just mentioned

**Comment by Bobgy** [comment]
It seems in some cases, db doesn't store namespace info to the run.

**Comment by Bobgy** [comment]
https://github.com/kubeflow/pipelines/blob/c125c52ec7668bc479f846740fc4c0c2e051b5f9/backend/src/apiserver/resource/resource_manager.go#L308
Found the root cause, when run is created and no namespace provided, we should add namespace in to the api object similar to experiment below.

**Comment by Bobgy** [comment]
On the other hand, https://github.com/kubeflow/pipelines/blob/ca58b2227fe4a5e46f3d45c7c80a4707d652b0b7/backend/src/apiserver/resource/resource_manager.go#L443

Should default to pod namespace (not empty) if db doesn't have namespace data.
