### ISSUE TITLE
Pipeline Run UI does not load on large data / 1k pods while executing, when done, displays "No graph to show"

### ISSUE THREAD

**Issue by yoni-taranis** [kubeflow/pipelines#2913]
**What happened:**
While running a pipeline that contains about 1k pods performing tasks parallelic, the UI does not load after re-loading it from the 1st time entering to the page. It is simply showing the "lodader" icon without stopping.

When the Run finishes, going into it will display "No graph to show" although the pods still exist on the cluster with the Succeeded status.

**What did you expect to happen:**
Expected to view all the pods and their status.

**What steps did you take:**
It does not seem to have any backend  side errors when looking at the Network section in Dev Tools.

**Anything else you would like to add:**
We would really like to get this solved and if we can help with the process of doing it we will be glad! Any pointers would be helpful.

I do understand it might be worthless to see a graph of 1k pods (or even less) - but it would actually be helpful to visualize errors (or just pods names with errors) - especially in production env

**Comment by Bobgy** [comment]
You can follow instructions in https://github.com/kubeflow/pipelines/blob/master/frontend/README.md for running a local UI instance and connect API requests to your real backend.

Feel free to let me know if you have any further questions.

**Comment by yoni-taranis** [comment]
I will try and take a look.

In general - I have a feeling it is related to the refresh interval of the UI that is created when entering that screen.

**Comment by yoni-taranis** [comment]
Just updating, that I've added a few short lines of code to add a "Summary" tab to the view
By not defaulting the graph view (which is very heavy to process I guess on a large amount of pods + retries) we are now utilizing the frontend much more.

**Comment by Bobgy** [comment]
@yoni-taranis Awesome, that sounds a reasonable solution.

Do you want to contribute the solution here? I think it makes sense if UI detects how many nodes there are in the graph, and if it is huge, fallback to display the overview.

**Comment by yoni-taranis** [comment]
@Bobgy I will need to refactor it a little bit to make to contribute, I will find the time to do it soon and create a PR.

**Comment by cp2587** [comment]
Hello @yoni-taranis,

As we have the same issue, would it be possible for you to show me what you change in the UI in order to handle 1k+ pods pipeline ?

Thank you,
