### ISSUE TITLE
Service account setup instruction should not use admin roles

### ISSUE THREAD

**Issue by SinaChavoshi** [kubeflow/pipelines#2921]
Currently setup instruction for service account credentials at 
https://github.com/kubeflow/pipelines/blob/master/manifests/gcp_marketplace/guide.md#gcp-service-account-credentials 

Instructs users to give roles/dataproc.admin, roles/dataflow.admin , roles/storage.admin etc. This privilege is beyond what the account needs, for example for storage reader and writer role will be sufficient. 

In particular this causes an issue when user is performing the setup via a notebook instance as notebook instance is ran under default compute instance that only has editor access.  Editor role can give reader / write access , however it can not give admin access to a service account. 

Therefore my recommendation is to modify the instructions to lower the role requirements.

**Comment by rmgogogo** [comment]
That's just example showcase. For different pipeline, people need different permission, it's more to user's choose.
