### ISSUE TITLE
 Best practice for maintaining GCP patch kustomizations

### ISSUE THREAD

**Issue by parthmishra** [kubeflow/pipelines#2927]
I'm new to Kustomize and have a few questions regarding how to maintain overlays for KFP. The [docs example](https://www.kubeflow.org/docs/pipelines/installation/standalone-deployment/#maintain-a-repo-for-your-manifests) uses the `...env/dev?ref=0.2.0` configuration as a remote git base which works, but if you try the same strategy with `...env/gcp?ref=0.2.0`  it won't work because KFP expects there to be an `application_default_credentials.json` file in the directory. I feel like if a dummy file was there I could then simply override the secretGenerator from my overlays. 

My attempted workaround: 

1. Clone repo into my overlays repo as `base` resulting in something similar to the following structure:
```
my-repo
├── base (kfp repo) 
└── overlays
    ├── dev
    │   └── kustomization.yaml
    └── prod
        └── kustomization.yaml
```

2. Place `application_default_credentials.json` into `base/.../env/gcp`
3. Run `kubectl apply -k overlays/dev` 

I think the problem with this method is that the bases for both `dev` and `prod` can't use different refs from each other (e.g. dev is on `0.2.0` and prod is `0.1.40`) without checking out the ref manually prior to applying. 

Aside: Why does `gcp-configurations-patch.yaml` require you to edit the values in the patch file directly as opposed to using config and secret generators?

**Comment by rmgogogo** [comment]
@Bobgy did you change it recently? I don't remember we have such change.

**Comment by Bobgy** [comment]
@parthmishra Sorry for the late reply. Thank you for the good question.
@rmgogogo It's not something we changed. We never had good support for this issue.

Short answer, `...env/gcp` manifest hasn't been maintained according to best practices introduced. What you suggested of putting a dummy file seems like a great idea. @parthmishra, If you can get that approach working, I'd really appreciate a PR to change our manifest structure.

**Comment by NikeNano** [comment]
I would be happy to work on this @Bobgy! 
/assign

**Comment by Bobgy** [comment]
@NikeNano FYI, @rmgogogo has done refactoring mentioned above. Now the manifest we provide for `env/gcp` expects user to use either node default service account or workload identity. So that the secret will no longer be needed.

I think we can close this issue now.
Feel feel to open a new issue if the secret approach is still useful for you.
/close

**Comment by Bobgy** [comment]
Here's an example of best practice we recommend: https://github.com/kubeflow/pipelines/tree/master/manifests/kustomize/sample
