### ISSUE TITLE
UX - Show inputs/outputs page when there are no visualizations

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#2933]
When the component does not have any visualized outputs, we still show an empty artifact visualization page (more so, the page is pretty confusing and complicated for an average user).

I propose to show the Inputs/outputs page in that case.
Maybe we should just combine those pages showing all outputs at one page - some are visualized with simple text (numbers and strings), and some have rich visualizations.

/cc Realsen

**Comment by Bobgy** [comment]
@Ark-kun I like this idea, also found that very confusing.

However, the visualizer has a manual mode to let user provide their own arguments. Would hiding that feature be a problem?

**Comment by Ark-kun** [comment]
We can use UX where every output has a link and an button to visualize it. That button can lead to the page/pane where the a custom visualizer can be specified.

Outputs:
Model (TFModel) | --link- | link | size: 32MB | Visualize
<Model visualization>

Loss (Float) | 0.731 | link | size: 4 | Visualize

**Comment by Bobgy** [comment]
Could the visualizer visualize based on multiple outputs?

**Comment by Ark-kun** [comment]
> Could the visualizer visualize based on multiple outputs?

I'm not sure this feature is requested. Visualizing individual outputs seems to be sufficient for now. (mlpipeline-ui-metadata is also an output).

**Comment by Bobgy** [comment]
> more so, the page is pretty confusing and complicated for an average user

I feel like this is the real problem we need to solve. Defaulting to a different tab just hides the problem shortly.

After rethinking about implementation, I don't think this is doable, we cannot know if there are any visualizations before fetching the data, but we fetch data when in the tab. It would be confusing to show a tab and it loads for a while and (because it's empty), it auto redirects to a different tab.

**Comment by Bobgy** [comment]
/close
@Ark-kun I'm moving the discussion to https://github.com/kubeflow/pipelines/issues/3328

**Comment by Ark-kun** [comment]
@Bobgy Is it possible to just move the tab to the far right when there are no visualizations?

**Comment by Bobgy** [comment]
@Ark-kun 
similar to
> After rethinking about implementation, I don't think this is doable, we cannot know if there are any visualizations before fetching the data, but we fetch data when in the tab. It would be confusing to show a tab and it loads for a while and (because it's empty), it auto redirects to a different tab.

we cannot (and shouldn't) adjust UI element's position based on dynamic data, the UI wouldn't be consistent to users too
