### ISSUE TITLE
Question - Is "versioning" an existing pipeline exists in the kfp Client upload params?

### ISSUE THREAD

**Issue by yoni-taranis** [kubeflow/pipelines#2940]
I have tried going through the docs and the code and I couldn't find a proper way to do it.

Does it exist? Can I version an existing pipeline?

Thanks

**Comment by JakeTheWise** [comment]
I'd like to know this, too.

**Comment by numerology** [comment]
The SDK side client support is currently missing. We're working on that right now.

For now, if you would like to call that through SDK, you can do the following:
```python
client = kfp.Client(host='<your-end-point>')	
package_url = '<your package url>'
version_body = {
  "name": "<your version name>", 
  "code_source_url": "<your code source url>", 
  "package_url": {"pipeline_url": package_url}, 
  "resource_references": [{"key": {"<your pipipeline id>", "type":3}, "relationship":1}]}

response = client.pipelines.create_pipeline_version(version_body)
```
Basically you'll need to hand-craft the request payload.

**Comment by yoni-taranis** [comment]
@numerology Thanks for the reply!

Is there any plan to support uploading a pipeline version from a file like the current upload API?

**Comment by yoni-taranis** [comment]
Also, while implementing this - I found an issue with Google Signed URLs - When I enter them as the source url it says the file is invalid, when using a public URL for the same file, it works fine.

**Comment by numerology** [comment]
> Is there any plan to support uploading a pipeline version from a local file like the current upload API?

Sure that's in the plan.

> I found an issue with Google Bucket Signed URLs.

Yes currently we only support public URL because fetching files with sign in logic will be a bit more complex. I think @jingzhang36 can better comment on this.

**Comment by yoni-taranis** [comment]
@numerology Again thanks for the reply.

I did not mean files with log in logic - But Signed URLs of Google Buckets (They are private files, but can be shared with a public URL signed with a key + expiry/mode), it should actually behave the same.

I have a feeling this relates to an issue with parsing the of the URL itself.
Example of an URL:
https://storage.googleapis.com/kubeflow-temporary-pipeline-deployments/d72e083f-a690-44ea-b44f-6c1984b2346e.yaml?Expires=1580747764&GoogleAccessId=kubeflow-auth%40taranis-api.iam.gserviceaccount.com&Signature=hQHu5nxlnKwpHyIPWxErBaPoGzv2DRmR0zHfEkZOeJCBeFGBqjePCD87rWyVz7lE%2BIQ%2F5NoeFevhIUezXlqHx3T8lrJhitRota%2FnQQ%2FWJlfVyZIwbX1IVmPil6oJUx7opwFBAF9QYLTCL2QN0KdrtE0Xw1Cc3XWVk55XNiGJN%2F6oDZXLKo%2Flyt50AQtqmOf%2BGHdeWgcK8sh5p%2FWIhiLLx08N%2FWsDYTWr0OiSL4rxmAbwEu7p9xPfv%2Bbs%2B16uSjQxILLu8uVktvDCMqUwLAnXXtupgx5zcg%2FQVgBQ5a8anb1Co9A0KqIJ0vXrH4duKVX456vaKt7lgDMzhHd3TgIabg%3D%3D

**Comment by parthmishra** [comment]
I was able to generate a signed GCS url and create a pipeline version via the SDK

**Comment by rsalmond** [comment]
I'm not having much luck with this workaround. When I provide the payload as described above and populate it with an existing pipeline name and ID I'm getting nothing but 404's. Is this still expected to work?

```
$ kfp pipeline list

+--------------------------------------+--------------------------------------------------------+---------------------------+
| Pipeline ID                          | Name                                                   | Uploaded at               |
+======================================+========================================================+===========================+
| 70628821-ccbe-4553-95be-246deb2285cb | foo                                                    | 2020-02-03T17:52:29+00:00 |
+--------------------------------------+--------------------------------------------------------+---------------------------+
$ python create.py


Payload: {'code_source_url': 'https://<url>',
 'name': 'foo',
 'package_url': {'pipeline_url': 'https://<url>/foo.py.zip'},
 'resource_references': [{'key': {'id': '70628821-ccbe-4553-95be-246deb2285cb', 'type': 3 },'relationship': 1}]}
********************************************************************************
2020-02-04 14:41:09,222 DEBUG Starting new HTTPS connection (1): <host>:443
send: b'POST /api/v1/namespaces/kubeflow/services/ml-pipeline:http/proxy//apis/v1beta1/pipeline_versions HTTP/1.1\r\nHost: <host>\r\nAccept-Encoding: identity\r\nContent-Length: 249\r\nAccept: application/json\r\nContent-Type: application/json\r\nUser-Agent: Swagger-Codegen/0.1.40/python\r\nauthorization: Bearer ya29.<token>\r\n\r\n'
send: b'{"name": "foo", "code_source_url": "https://<url>", "package_url": {"pipeline_url": "https://<url>/foo.py.zip"}, "resource_references": [{"key": {"id": "70628821-ccbe-4553-95be-246deb2285cb", "type": 3}, "relationship": 1}]}'
reply: 'HTTP/1.1 404 Not Found\r\n'
header: Audit-Id: b512580a-2cb5-4ac3-8c00-bb5d500e712e
header: Content-Length: 10
header: Content-Type: text/plain; charset=utf-8
header: Date: Tue, 04 Feb 2020 21:41:09 GMT
header: X-Content-Type-Options: nosniff
2020-02-04 14:41:09,443 DEBUG https://<host>:443 "POST /api/v1/namespaces/kubeflow/services/ml-pipeline:http/proxy//apis/v1beta1/pipeline_versions HTTP/1.1" 404 10
2020-02-04 14:41:09,444 DEBUG response body: Not Found
```

**Comment by parthmishra** [comment]
@rsalmond What version of KFP are you using? Do the logs for the `ml-pipeline` deployment say anything? 

One subtle thing I noticed was that the initial upload of a pipeline creates a default pipeline version of the same name which causes an error since you can't upload the same-named version twice. This wouldn't cause your 404s though so I'm not sure why that's happening. 

Here is my working payload on version 0.2.1:

```python
version_body = {
        "name": "test-v2.0", # version name should not be same as pipeline name or other versions
        "package_url": {
            "pipeline_url": "https://storage.googleapis.com/..."  # signed url
        },
        "resource_references": [
            {
                "key": {
                    "id": "84b6c36d-4b4d-473c-bf9a-801dbf91bcbe",
                    "type": "PIPELINE",
                },
                "name": "test",  # pipeline name, not version name!
                "relationship": "OWNER",
            },
        ],
    }
```

**Comment by rsalmond** [comment]
@parthmishra thanks for the quick reply! I'm using kfp 0.2.0. The ml-pipeline pod doesn't log anything when I call `create_pipeline_version`, tried your payload without luck but based on the type change (int to string for relationship and type) I think I need to update my ml-apiserver to get some schema changes.

**Comment by parthmishra** [comment]
Yeah try updating since I believe the schema changed sometime between 0.1.38 (last documented API reference) and 0.2.1

**Comment by rmgogogo** [comment]
@jingzhang36

**Comment by yoni-taranis** [comment]
I have successfully used the workaround suggested here of crafting the body.
I still see the issue with the GCS signed urls, but it is not so critical as I made the bucket public for now.

Thanks

**Comment by pselden** [comment]
If possible I would like to see this be coalesced into one command for pipeline uploads via the CLI.

Example: `kfp pipeline upload -p "My Pipeline" --version 1`my_pipeline.tar.gz

Which would create if it doesnt exist, and upload a new version if it does exist.

**Comment by pselden** [comment]
It is also quite a strange client api-mismatch that `upload_pipeline` accepts a local file (and does not allow a remote file), whereas `create_pipeline_version` only accepts remote files.

**Comment by jingzhang36** [comment]
We have an example at https://github.com/kubeflow/pipelines/issues/2977#issuecomment-595011702
