### ISSUE TITLE
Preserving step config in create_graph_component_from_pipeline_func

### ISSUE THREAD

**Issue by JakeTheWise** [kubeflow/pipelines#2942]
I was unable to use `kfp.components.create_graph_component_from_pipeline_func` to import a pipeline function as a step in another pipeline. I'd like to preserve "inner pipeline" resource requests for GPU steps but it seems this isn't possible. Am I correct to say that `create_graph_component_from_pipeline_func` fuses the inner pipeline's steps into one pipeline step to run in one pod?

```python
import kfp

@kfp.dsl.pipeline(
    name='Basic Training',
    description='A simple machine learning pipeline'
)
def basic_training(...):
    my_step = ...
    mystep.set_gpu_limit(1)

kfp.components.create_graph_component_from_pipeline_func(basic_training, 'tmp.yaml', embed_component_specs=False)
```

```
Traceback (most recent call last):
  File "rig_state/pipeline.py", line 80, in <module>
    kfp.components.create_graph_component_from_pipeline_func(basic_training, 'tmp.yaml', embed_component_specs=False)
  File "/mapr/houmaprdev/user/jschmidt2/.conda/envs/pip_py36/lib/python3.6/site-packages/kfp/components/_python_to_graph_component.py", line 57, in create_graph_component_from_pipeline_func
    component_spec = create_graph_component_spec_from_pipeline_func(pipeline_func, embed_component_specs)
  File "/mapr/houmaprdev/user/jschmidt2/.conda/envs/pip_py36/lib/python3.6/site-packages/kfp/components/_python_to_graph_component.py", line 100, in create_graph_component_spec_from_pipeline_func
    pipeline_func_result = pipeline_func(**pipeline_func_args)
  File "rig_state/pipeline.py", line 72, in basic_training
    train_and_tune.set_gpu_limit(1)
AttributeError: 'TaskSpec' object has no attribute 'set_gpu_limit'
```
I've tried with `embed_component_specs=True` as well.

**Comment by Ark-kun** [comment]
This is not supported yet.
Although you can set the resource requests using something like `some_op(...).execution_options.kubernetes_options.main_container = Container(resources=....)` (https://github.com/kubeflow/pipelines/blob/ebd77a7a12f86f8a975337e6336fa6efb498a01e/sdk/python/tests/components/test_graph_components.py#L131), but right now this won't be used when instantiating the graph component. It's easy to implement, but it's just not implemented yet.

I'll keep this as a missing feature request. (Thanks for the feedback - it gives me information that someone is interested in this feature.)

>AM I correct to say that create_graph_component_from_pipeline_func fuses the inner pipeline's steps into one pipeline step to run in one pod?

No. Graph component is a serialized pipeline that can be loaded and used as a step (just like the container components). Currently, when graph component is being instantiated inside the outer pipeline, all inner tasks are just added to the outer pipeline. So, there is no difference in execution.

**Comment by JakeTheWise** [comment]
@Ark-kun tell me if I'm not answering your question precisely — right now, our main user scenarios for using graph components is to implement a TFX-like model training pipeline. We have one project where we need to run this pipeline in parallel, thus the experimentation with fanouts + sub-pipelines.

**Comment by Ark-kun** [comment]
> We have one project where we need to run this pipeline in parallel, thus the experimentation with fanouts + sub-pipelines.

Graph components will allow you to automatically parallelize and intermix all child components.

I'll try to fix/implement the preservation of the task kubernetes options.

**Comment by JakeTheWise** [comment]
Awesome, thank you!
