### ISSUE TITLE
Pipeline list api doesn't do filtering

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#2945]
**What happened:**
demo: https://screencast.googleplex.com/cast/NTE2MjYwMTg3MDc4NjU2MHwwMDRlNGUzNS1hOA

**What did you expect to happen:**
pipelines should be filtered by name

**What steps did you take:**
[A clear and concise description of what the bug is.]
No matter what filter string I typed for pipeline list, the api returns all pipelines.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I checked the network request included the filter, so I think this is a backend bug.
```
"page_token=&page_size=10&sort_by=created_at desc&filter=%7B%22predicates%22%3A%5B%7B%22key%22%3A%22name%22%2C%22op%22%3A%22IS_SUBSTRING%22%2C%22string_value%22%3A%22tfx%22%7D%5D%7D"
```
and decodes to
```
"page_token=&page_size=10&sort_by=created_at desc&filter={"predicates":[{"key":"name","op":"IS_SUBSTRING","string_value":"tfx"}]}"
```
Tested on 0.1.40 release

**Comment by rmgogogo** [comment]
added to 1.0

**Comment by Bobgy** [comment]
/close
fixed by https://github.com/kubeflow/pipelines/pull/3040
