### ISSUE TITLE
Is it possible to specify memory to an Op when using the func_to_container_op?

### ISSUE THREAD

**Issue by keeplearnin** [kubeflow/pipelines#2956]
Hi

I'm wondering if it's possible to add set_memory_request or set_memory_limit to a Op that is created from func_to_container_op's factory.

Thanks

**Comment by Ark-kun** [comment]
You should set the memory request on the *task* object which you get when you call a component with some arguments.

```python
train_task = train_classifier(training_data=....).set_memory_request(...)
```
