### ISSUE TITLE
Retrying and failing cannot be terminated

### ISSUE THREAD

**Issue by rmgogogo** [kubeflow/pipelines#2963]
It seems that currently tasks that are retrying   and failing cannot be terminated (an issue from Argo which seems to be related to it https://github.com/argoproj/argo/issues/1620)

**Comment by rmgogogo** [comment]
reproduce step:

def echo_op(value):

   return dsl.ContainerOp(

       name='echo',

       image='does-not-exist',

       command=['sh', '-c'],

       arguments=['echo

**Comment by rafaelbarreto87** [comment]
Running into this same issue.

**Comment by rmgogogo** [comment]
Paste Yang's rely: for the upper reproduce step, regarding imagePullBackoff, this is by design that Kubernetes will treat this as an infinite retriable issue instead of a failure. This retry is different from the argo retry.

**Comment by rmgogogo** [comment]
@IronPan
