### ISSUE TITLE
[UI] troubleshooting doc link is not valid

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#2965]
**What happened:**
When I meet an error, the troubleshooting doc link shown doesn't work. It shows "https://www.kubeflow.org/docs/pipelines/troubleshooting" but the url isn't valid.

**What did you expect to happen:**
The url should be valid.

/assign @SinaChavoshi

**Comment by SinaChavoshi** [comment]
We have not populate the page yet. I will work with Joe to push out a simple place holder page for now.

**Comment by rmgogogo** [comment]
"The link is accurate, we have not populate the page yet."
turn down to P1.
