### ISSUE TITLE
How to build an image for KubeFlow pipeline?

### ISSUE THREAD

**Issue by avarf** [kubeflow/pipelines#2969]
Hi, I recently found about kubeflow and kubeflow pipeline but it is not clear for me how to build an image from my python program.

Let's assume that I have a simple python function that crops images:
```pytohn
class Image_Proc:
    def crop_image(self, image, start_pixel, end_pixel):
        # crop
        return cropped_image
```
How shall I containerize this and use it in the KubeFlow pipeline? Do I need to wrap it in an API (with Flask for example) Or do I need to connect to some media/data broker?

How KubeFlow pipeline sends input to this code and transfers the output of this code to the next step?

**Comment by Ark-kun** [comment]
For components that can be implemented as a standalone python function, you can use `func_to_container_op` (renamed to `create_component_from_func` in newer SDK versions). See the [Data passing tutorial](https://github.com/kubeflow/pipelines/blob/8dfa2d9/samples/tutorials/Data%20passing%20in%20python%20components.ipynb)

```python
def crop_image(
    image: ImputPath('Image'),
    start_pixel: int,
    end_pixel: int,
):

crop_image_op = create_component_from_func(
    func=crop_image,
    base_image='python:3.7',
    packages_to_install=['pandas==0.24'],
    output_component_file='crop_image.component.yaml',
)
```

**Comment by avarf** [comment]
Thanks for the answer but that is not my intention, I just wrote that class as an example to start with. Imagine that I have a big component that already has a docker image, how shall I change it to be compatible with kubeflow?

Based on my understanding I need to receive the input from some port (which is OK) but I have to write the output to the disk to a specific path, is this correct?

**Comment by Ark-kun** [comment]
> Based on my understanding I need to receive the input from some port (which is OK) but I have to write the output to the disk to a specific path, is this correct?

KF Pipelines orchestrates command-line programs in containers. You command line program arguments can contain input paths, outputs paths and input parameter values. You describe the components using a serialized ComponentsSpec file (component.yaml). Components can be loaded and used as for pipeline tasks. Check the [documentation](https://www.kubeflow.org/docs/pipelines/sdk/component-development/) and this [tutorial](https://github.com/Ark-kun/kfp_samples/blob/master/2019-10%20Kubeflow%20summit/106%20-%20Creating%20components%20from%20command-line%20programs/106%20-%20Creating%20components%20from%20command-line%20programs.ipynb)
