### ISSUE TITLE
with pipeline version UI, allow upload via file as well as URL

### ISSUE THREAD

**Issue by amygdala** [kubeflow/pipelines#2973]
Unlike the Pipeline upload UI, the pipeline *version* upload UI does not allow uploading a file. 

This seems really high friction, because during testing/development it will be a big pain to have to upload a pipeline to a public URL each prior to testing something new.
(It's particularly problematic since github urls don't seem to work : https://github.com/kubeflow/pipelines/issues/2922 )

(cc @jingzhang36 )

**Comment by amygdala** [comment]
looks like https://github.com/kubeflow/pipelines/issues/2977 is essentially the same.

**Comment by rmgogogo** [comment]
close this one, track via #2977
