### ISSUE TITLE
Support local file upload when creating new pipeline version

### ISSUE THREAD

**Issue by jingzhang36** [kubeflow/pipelines#2977]

**Comment by Bobgy** [comment]
@jingzhang36 I think all work is done here, is that right?
Can you link all relevant PRs for tracking purpose?

**Comment by pselden** [comment]
Does the sdk still need to be updated? I looked through some of the client.py files and couldn't find anything related to this.

**Comment by Bobgy** [comment]
@numerology @Ark-kun Do you know answer to above question?
Is regenerating server api client enough? (I did that in 0.2.5 release)

**Comment by jingzhang36** [comment]
I feel using the generated server api client would be ok as long as I can find a way to load a local file to io object and pass to the generated api method. Let me try to make up an example and post it here

**Comment by jingzhang36** [comment]
@pselden with kfp 0.2.5, you can do

import os
import kfp
myfile = os.path.join(<your local pipeline file>)
client = kfp.Client(<host>)
client.pipeline_uploads.upload_pipeline_version(myfile, pipelineid=<id of the pipeline you want to create version under>, name=<version name by your choice>)

Also note: pipelineid and name are both strings.

**Comment by Bobgy** [comment]
To add to above comment, you also need to upgrade `kfp-server-api` package to 0.2.5

**Comment by pselden** [comment]
Thanks. Do you happen to know if this will be added to the CLI as well?

like `kfp upload --name <name> --version <version>`?

**Comment by pahask8** [comment]
> @pselden with kfp 0.2.5, you can do
> 
> import os
> import kfp
> myfile = os.path.join(<your local pipeline file>)
> client = kfp.Client(<host>)
> client.pipeline_uploads.upload_pipeline_version(myfile, pipelineid=<id of the pipeline you want to create version under>, name=<version name by your choice>)
> 
> Also note: pipelineid and name are both strings.

@jingzhang36 Thank you for sharing this example. Right now the kfp  package does not support this version: https://github.com/kubeflow/pipelines/blob/ee525b91cb40c4dee7c64019a857cc8bbdc6b7fc/sdk/python/requirements.txt#L13. Will it be updated soon?
Thank you

**Comment by numerology** [comment]
> Will it be updated soon?

Sorry for the confusion. `kfp-server-api` does not have a consistent version number with KFP SDK package.

So if you deploy KFP with version 0.2.5 and use KFP SDK version higher than 0.2.5, it works.

**Comment by Bobgy** [comment]
@numerology I just released kfp-server-api 0.2.5
Looks like we need to update https://github.com/kubeflow/pipelines/blob/ee525b91cb40c4dee7c64019a857cc8bbdc6b7fc/sdk/python/setup.py#L35

**Comment by numerology** [comment]
> @numerology I just released kfp-server-api 0.2.5
> Looks like we need to update
> 
> https://github.com/kubeflow/pipelines/blob/ee525b91cb40c4dee7c64019a857cc8bbdc6b7fc/sdk/python/setup.py#L35

Ah got it.

**Comment by pselden** [comment]
Just checking -- this is NOT available in any officially published version of the KFP client sdk right?

**Comment by Bobgy** [comment]
@pselden it's available in 0.2.5 and 0.3.0.
Refer to https://github.com/kubeflow/pipelines/issues/2977#issuecomment-595011702

but you need to make sure your kfp server is the same version.

**Comment by Tauranis** [comment]
Unfortunately, uploading a new version is crashing.

When I run
```
kfp --endpoint <URL> pipeline upload-version -p <PIPE_ID> -v <PIPE_VERSION> ./dist/pipeline.tar.gz
```
It throws `(500) Bad Request. Reason: Internal Server Error`

The same happens when I use the Python SDK

```
import os
import kfp
client = kfp.Client()
client.pipeline_uploads.upload_pipeline_version(<FILE>, pipelineid=<PIPE_ID>, name=<PIPE_VERSION>)
```

Currently I'm using Kubeflow deployed at Google AI Platform with `kfp==0.5.1` and  `kfp-server-api==0.5.0`

Does someone else have the same problem?

**Comment by jingzhang36** [comment]
I tested with  kfp===0.4.0  kfp-server-api===0.3.9 and kfp standalone deployment with 0.5.1
By following the example at https://www.kubeflow.org/docs/pipelines/tutorials/sdk-examples/
I can not reproduce the error.
So that means the API server's feature is fine. Suspecting issues with cluster setting up. 
Since this is for feature request and the feature is good per my test, let's close this one and open another issue for investigating this particular use issue. 
@Tauranis, do you mind moving to https://github.com/kubeflow/pipelines/issues/3805

**Comment by Tauranis** [comment]
I found the error.
I was passing the pipeline name and not the pipeline id.
My bad. Sorry.

For those who  want to get the pipeline id from its name the following will work.

```
PIPELINE_ID=$(kfp --endpoint ${KUBEFLOW_ENDPOINT} pipeline list | grep -w  ${PIPELINE_NAME}  | grep -E -o -e "([a-z0-9]){8}-([a-z0-9]){4}-([a-z0-9]){4}-([a-z0-9]){4}-([a-z0-9]){12}")
```

I'm currently using this for my CI/CD pipeline.
