### ISSUE TITLE
Update Watson components to use v4 API

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/pipelines#2987]
**What happened:**
IBM Watson recently migrated the API version from v3 to v4, so we need to update the Watson components to use the latest API version. 

**What did you expect to happen:**

**What steps did you take:**
[A clear and concise description of what the bug is.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

/assign @Tomcli 
/assign @kevinyu98

**Comment by rmgogogo** [comment]
Can't find user "kevinyu98".
