### ISSUE TITLE
[UI] Show KFP version text on UI

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#3000]
Currently we only show version commit sha on UI, but we refer to version more common as semver like `0.2.0`. It helps user get more intuitive idea about their deployment if we show semver directly on UI.

Requested by @katieole

**Comment by dragonwarp** [comment]
I would like to claim this issue and start working on it. Can someone hold my hand through the proccess or should I jump right in?

**Comment by Bobgy** [comment]
@dragonwarp Thank you for offering the help!
I can give you some start links.

Instructions to build images: https://github.com/kubeflow/pipelines/blob/master/developer_guide.md#build-image.
You can `kubectl edit deployment <xxx-deployment-name>` and change the image field to change image running in an existing cluster.

### Architecture of this feature from end to end
1. Version info is in api server during docker build: https://github.com/kubeflow/pipelines/blob/master/backend/Dockerfile#L52.
2. It is served from api server in healthz endpoint: https://github.com/kubeflow/pipelines/blob/9b8e14cd9f33d6bde4f6ab914c65f40d956bd111/backend/src/apiserver/main.go#L144
3. Frontend node server calls the endpoint in https://github.com/kubeflow/pipelines/blob/master/frontend/server/handlers/healthz.ts
4. UI fetches data from frontend node server and displays it in https://github.com/kubeflow/pipelines/blob/9b8e14cd9f33d6bde4f6ab914c65f40d956bd111/frontend/src/components/SideNav.tsx#L533

COMMIT_SHA is still useful, so in this issue. We need to do the following:
1. Store another

**Comment by Bobgy** [comment]
@dragonwarp This feature involves many parts from end to end, so it's actually a little complicated for a starter issue. However, don't feel pressured, each step is fairly trivial to change, you just need to learn how to verify them.

And you don't need to do all of them, you can start from api server. Feel free to ask any questions if you are stuck somewhere. : )

**Comment by dragonwarp** [comment]
Ah, alas, my hardware is too flimsy to handle virtualization and thus I apologize for wasting your time. I hope your comment will be of help for someone else claiming this issue.

**Comment by Bobgy** [comment]
@dragonwarp no worries, these are good for anyone picking this issue

**Comment by Bobgy** [comment]
@chensun assigned the issue back to you as @dragonwarp doesn't have resources to work on the issue.
I've already left most of related information about the issue. Feel free to ask any more questions.

**Comment by Bobgy** [comment]
/reopen
I noticed a bug, the .cloudbuild.yaml won't have $TAG_NAME.
