### ISSUE TITLE
How can I use Kubeflow "submit_pyspark_job" function with --properties of gcloud dataproc

### ISSUE THREAD

**Issue by mathieulallier807** [kubeflow/pipelines#3014]
I want to use the "submit_pyspark_job" kubeflow function from https://github.com/kubeflow/pipelines/tree/master/components/gcp/dataproc/submit_pyspark_job

but I need to add some dependancy using the --properties option like so:

gcloud dataproc jobs submit pyspark prepare_data.py \
        --cluster test \
        --project test \
        --region us-central1 \
        --properties spark.jars.packages='com.johnsnowlabs.nlp:spark-nlp_2.11:2.4.0'

Where and how should I input this, thank you

**Comment by rmgogogo** [comment]
welcome contribution to the component. I think essentially the component issues request to dataproc and new parameters can be added there.

**Comment by mathieulallier807** [comment]
After much trying, this is how I managed to do it:

In the pyspark operator, you can have a pyspark_job parameter where you can add a dictionary of properties like so:

``` pyspark_job={"properties": {"spark.jars.packages": "com.johnsnowlabs.nlp:spark-nlp_2.11:2.4.0"}}```
