### ISSUE TITLE
[UI] TFDV visualization frame is blank in Chrome 80

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#3025]
**What happened:**
Visualization UI is broken after upgrading to Chrome 80. It turns blank and console has a line of warning: 

> HTML Imports is deprecated and has now been removed as of M80. See https://www.chromestatus.com/features/5144752345317376 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.

/priority p0

**What did you expect to happen:**
It should show up.

**What steps did you take:**
[A clear and concise description of what the bug is.]
1. Upgrade to chrome 80
2. Visit existing visualizations that used to work

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Bobgy** [comment]
Did some investigation, it seems not our UI is broken, the visualization itself is broken.

According to https://developer.mozilla.org/en-US/docs/Web/Web_Components/HTML_Imports.
Html import means links like the following (rel="import" is the special part):
```
<link rel="import" href="myfile.html">
```

**Comment by Bobgy** [comment]
Opened issue in upstream repo facets (used by tfdv): https://github.com/PAIR-code/facets/issues/207

**Comment by Bobgy** [comment]
Updated title, this only affects tfdv

**Comment by rmgogogo** [comment]
@rmgogogo

**Comment by rmgogogo** [comment]
Upstream issue: https://github.com/PAIR-code/facets/issues/207

**Comment by Bobgy** [comment]
TFDV upstream issue is https://github.com/tensorflow/data-validation/issues/108

**Comment by Bobgy** [comment]
/cc @Realsen 
FYI, you probably may hit the issue in TFMA too.

**Comment by Bobgy** [comment]
Upstream issue already fixed, we are waiting for a tfdv release to include the fix.

**Comment by Bobgy** [comment]
/close
Fixed by https://github.com/kubeflow/pipelines/pull/3060

**Comment by Bobgy** [comment]
/reopen
The last fix wasn't enough. It is still blank like
![dVp3kyXdouk](https://user-images.githubusercontent.com/4957653/74517076-79ee7180-4f4c-11ea-936f-1fe4a059d491.png)

I found it was caused by </script> in string breaking wrapping <string> tags. Sent a CL to fix upstream issue again.

**Comment by Bobgy** [comment]
This also needs https://github.com/kubeflow/pipelines/issues/3079 to be fixed first

**Comment by Bobgy** [comment]
Another upstream bug fixed in https://github.com/tensorflow/data-validation/commit/8cb3ca836a64d36a5c57d6d01775c0f5d789117b

**Comment by Bobgy** [comment]
We can use https://github.com/tensorflow/data-validation/releases/tag/v0.21.2.

**Comment by Bobgy** [comment]
Changed to p1, because @rmgogogo has https://github.com/kubeflow/pipelines/pull/3089 to workaround the issue. We can switch back to tfdv package now as a clean-up.

**Comment by Bobgy** [comment]
/assign @jingzhang36 
Can you do the follow up clean up?
