### ISSUE TITLE
feature ask: support for loops

### ISSUE THREAD

**Issue by SinaChavoshi** [kubeflow/pipelines#303]
could we add loop operations to _ops_group.py 

There is strong need for ability to run steps within a pipeline in a loop, for example train on ### epochs if accuracy is below X% rerun the training. 

current work arounds are very cumbersome and messy: 
1. Schedule job at start up check for last run status
2. Create a massive graph with early stopping 
3. Manage the loop out side of the pipeline

**Comment by gaoning777** [comment]
The recursion is supported now. https://github.com/kubeflow/pipelines/blob/master/samples/basic/recursion.py
