### ISSUE TITLE
Configurable namespaces

### ISSUE THREAD

**Issue by gaoning777** [kubeflow/pipelines#304]
Currently there are lots of places where namespaces are hardcoded, we need to make it configurable such that users can deploy the pipeline in a certain namespace, use DSL/python_sdk in a certain namespace and the tests work with the configurable namespaces.

List of places(Feel free to add more):
1) deployment
2) DSL
3) Python SDK
4) Test including e2e test, sample test, etc.(not directly exposed to the users).

**Comment by gaoning777** [comment]
PR: https://github.com/kubeflow/pipelines/pull/306, making the Python SDK and sample test namespace-configurable.

**Comment by IronPan** [comment]
FYI deployment and e2e/integration tests are already wired with namespaces.

**Comment by IronPan** [comment]
Please add links to the places that have ns hardcoded if you find any

**Comment by gaoning777** [comment]
TODO in DSL: https://github.com/kubeflow/pipelines/blob/d313a9c623646e5910315682ba1a7040ea41acca/sdk/python/kfp/compiler/compiler.py#L57

**Comment by Ark-kun** [comment]
> TODO in DSL:

I'd like to solve this by only adding this information in the backend: https://github.com/kubeflow/pipelines/issues/363

**Comment by AdrianLsk** [comment]
The namespace has to be changed also in the frontend 
https://github.com/kubeflow/pipelines/blob/81341d3aa67268d25d8c5ae1dc31df2e59e610b8/frontend/server/server.ts#L36

**Comment by IronPan** [comment]
backend and tests infra code should be namespaced. let me know if anything that's not the case.

**Comment by gaoning777** [comment]
Closing this issue now. If there are more configurable ns, please reopen it.
