### ISSUE TITLE
[Feature request] deep link to pipeline for demos on starting page deep link to the pipeline itself 

### ISSUE THREAD

**Issue by SinaChavoshi** [kubeflow/pipelines#3045]
Currently demos listed on starting page link to the pipeline list page, this is a feature request to deep link to the actual pipeline creation page.  This is not currently possible as part of the deeplink is based on the pipeline id that changes for each deployment. 

This requires a change in the back-end API to allow for referencing a pipeline by it's name instead of the database deployment id, and then change the starting page to deep link to the demo pipeline.

**Comment by rmgogogo** [comment]
Yuan already did it via another type of dynamic link
