### ISSUE TITLE
No (obvious) way to specify that one container should run after another

### ISSUE THREAD

**Issue by retnuh** [kubeflow/pipelines#3048]
**What happened:**

There is no apparent way to specify that one container should run after another.  I have a situation where I have, say, containers A, B, C that need to be run in serial - A generates stuff that B needs, which generates stuff that C needs.  But it writes to S3, or a database - not the local file system.  So I'm unable to use the artifact repository, or `PipelineParams` to build a dependency chain.

**What did you expect to happen:**

It would be nice if ContainerOps had a param `depends_on` which is a list of other ContainerOps that it needs to run after.

**Anything else you would like to add:**

I can work around this with a bogus `file_outputs` for containers and then consume that bogus output by, say, setting an ignored environment variable, but that's pretty horrible.  I just want a bit of basic control of my DAG.

**Comment by Ark-kun** [comment]
>There is no apparent way to specify that one container should run after another.

Tasks have `.after` method that does exactly what you want.
We discourage its usage though.

>A generates stuff that B needs, which generates stuff that C needs. But it writes to S3, or a database - not the local file system. So I'm unable to use the artifact repository, or PipelineParams to build a dependency chain.

Good components still pass the information as outputs. If the upstream writes to S3, it should output the URI. If it writes to DB, it can output ID.

**Comment by retnuh** [comment]
These are legacy containers that already have things like locations defined.  I understand your point though.

Thanks for the tip about `.after`, it's exactly what I need.
