### ISSUE TITLE
Mark all KFP 'core' components that don't work on KF as such

### ISSUE THREAD

**Issue by amygdala** [kubeflow/pipelines#3051]
See the discussion here: 
https://github.com/kubeflow/pipelines/issues/3037

I suspect there may be other such components as well.  In their READMEs, we should clearly indicate the conditions under which they work correctly, and where they don't.
I don't think we need to (necessarily) do this for the 'contrib' ones, but we should for the 'core' ones.

**Comment by Ark-kun** [comment]
Note that there are many contributed components that are located outside of the contrib folder...

**Comment by amygdala** [comment]
Let's leave this open until confirmed... it may soon be obsolete what with WI, but not sure.

**Comment by amygdala** [comment]
/reopen

Has this been addressed?

**Comment by Bobgy** [comment]
I feel like there's no clear ownership to those components, so it's hard to address this issue.
/assign @numerology @Ark-kun 
Any suggestions?

**Comment by amygdala** [comment]
Is there some broader 'component overhaul' bug that this could be subsumed by?
