### ISSUE TITLE
Jest Snapshot Test didn't well handle time string

### ISSUE THREAD

**Issue by rmgogogo** [kubeflow/pipelines#3057]
In our codes we use Date.toLocalDateString which depends on local time format. It may generate different snapshot.

**Comment by Bobgy** [comment]
@rmgogogo I cannot find any usages by code search, what are you referring to?

**Comment by rmgogogo** [comment]
UI uses local timezone/localization to output time string and so does Snapshot.
So dev's localization matters. I set my Mac to be Chinese locoalization so the generated snapshot is not suitable to be runned in test-infra.

I didn't find the way to override localization for npm while still keep my mac to be on Chinese.

**Comment by Bobgy** [comment]
@rmgogogo Can you point me to one example test case?
I guess it's related to system language then, because I have the same China timezone, but hasn't hit this issue.

**Comment by rmgogogo** [comment]
(maybe the SideNav), will you ping next time I hit it.
Last time I fixed it via change codes. (will dig out later, remember I changed FE codes to be hardcoded as us-en which is not a good change, it was done in my late night to catch up timeline, will revert when find the part)

**Comment by Bobgy** [comment]
I've fixed it later by fixing a timezone for unit tests.
