### ISSUE TITLE
upgrade Bazel from 0.23 to 2.1 and remove TF from WORKSPACE

### ISSUE THREAD

**Issue by rmgogogo** [kubeflow/pipelines#3061]
1. we don't have direct source dependency on TF. Removing it from WORKSPACE make sense as it introduced a lot of others.

2. upgrade Bazel from 0.23 to 2.1

3. golang dependency file is not updated for a very long time. Since we use Docker builder more which will update it in run time but if we use Bazel, we will find many not up to date

**Comment by Ark-kun** [comment]
>we don't have direct source dependency on TF. Removing it from WORKSPACE make sense as it introduced a lot of others.

https://github.com/kubeflow/pipelines/pull/2856

**Comment by rmgogogo** [comment]
@jingzhang36 FYI.
Alexy's PR2856 would help a lot to simplify the bazel stuff.

**Comment by Ark-kun** [comment]
Thanks. I'm not sure how to detect any other unused entries...

**Comment by Bobgy** [comment]
@rmgogogo Can you assign a priority for this?

**Comment by rmgogogo** [comment]
(1) is done by Alexy.
We can continue (2) and (3).

@jingzhang36 I can help upgrade the bazel version, here quickly ping you in case we have other blockers.
