### ISSUE TITLE
GitHub ref file path returns 404

### ISSUE THREAD

**Issue by rmgogogo** [kubeflow/pipelines#3074]
https://www.kubeflow.org/docs/pipelines/installation/standalone-deployment/
Document mentioned the path
github.com/kubeflow/pipelines//manifests/kustomize/base/crds?ref=$PIPELINE_VERSION

It returns 404. Not sure whether github changed behavior.

workaround: directly clone codes and kubectl on it.
fix: find the new Github file path pattern and update document

**Comment by rmgogogo** [comment]
@Bobgy feel free to correct, I hit the issue not sure whether it's transient (Github outage)

**Comment by rmgogogo** [comment]
another issue in standalone CLI deployment:
minio can't be launched. it said can't find "minio-pvc" while log says: persistentvolumeclaim/minio-pvc created. However I can't find the minio-pvc in kubeflow namespace.

**Comment by rmgogogo** [comment]
Yuan mentioned offline that possible my network got throtting by Github. will retry a little bit later.

**Comment by Bobgy** [comment]
/assign @Bobgy 
Let me verify

**Comment by Bobgy** [comment]
First clarification, `github.com/kubeflow/pipelines//manifests/kustomize/base/crds?ref=$PIPELINE_VERSION` is not a url. It is a special format supported by kustomize: https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md

One thing we might want to change though, is that the double slash is no longer needed according to doc.

**Comment by Bobgy** [comment]
Verified the urls are still working, it's network errors.
