### ISSUE TITLE
[Engprod] Stable python package management

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#3078]
We have done many hotfixes like
* https://github.com/kubeflow/pipelines/pull/3067
* https://github.com/kubeflow/pipelines/pull/3035
* https://github.com/kubeflow/pipelines/issues/3079

Also e.g. things don't work when we upgrade base google/cloud-sdk image.

Can we set up a stable python package management strategy that pins all the packages we use?

Some options:
* https://github.com/pypa/pipenv
* https://github.com/jazzband/pip-tools

UPDATE: we have decided to go with pip-tools, because it's lightweight and just focus on the dependency pinning task we wanted.

/cc @numerology 
/cc @Ark-kun 
/area engprod

**Comment by Ark-kun** [comment]
I think we have two goals here:

* Test the SDK in a stable environment
* Test the SDK in a more recent environment that the user might have

Python's way of pinning dependencies is to freeze the packages to a file: `pip3 freeze > requirements.txt` which can then be used to reproduce the environment: `pip3 install -r requirements.txt`.

So, we should probably test both ways - test with pinned packages installed from requirements.txt and test with latest packages installed by running the setup.py.

We should probably use pinned versions for the image building.

**Comment by Bobgy** [comment]
> Test the SDK in a more recent environment that the user might have

@Ark-kun Thanks, totally make sense to me. Can we handle this goal in post submit test instead, so it is not presubmit blocking?

**Comment by Ark-kun** [comment]
> Can we handle this goal in post submit test instead, so it is not presubmit blocking?

Sounds good.

**Comment by Bobgy** [comment]
TODOs:
* [x] backend and sample-test: https://github.com/kubeflow/pipelines/pull/3161
* [ ] metadata writer image
* [ ] visualization server
* Please add if there's other things I missed

**Comment by Ark-kun** [comment]
- [ ] SDK

**Comment by discordianfish** [comment]
Metadata writer image: https://github.com/kubeflow/pipelines/pull/3408

**Comment by Ark-kun** [comment]
The visualization-server licenses seem to be broken after some package got updated.

**Comment by Bobgy** [comment]
@Ark-kun OK, I will try to do the same for visualization-server.
