### ISSUE TITLE
UI says "Successfully created new Run", but it isn't  in the list

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#308]
We need to make the UX and Backend synchronized.
Backend probably needs to verify the uploaded pipelines. E.g. using argo lint.

**Comment by IronPan** [comment]
I am not sure I followed the description. 
Is it a bug? If so could you provide more detail how to reproduce it?

**Comment by vicaire** [comment]
Resolving as it has been idle for several months.
