### ISSUE TITLE
kfp requires valid https certificates

### ISSUE THREAD

**Issue by andaag** [kubeflow/pipelines#3095]
### What steps did you take:
I installed kubeflow using microk8s

### What happened:
Install went fine, but using the python kfp client to deploy, either from outside of kubeflow or from a notebook within kubeflow fails due to invalid https certificates.

### What did you expect to happen:
It'd be nice if it worked, to experiment/demo locally... but I totally understand why it doesn't.

### Environment:
microk8s on ubuntu 18.04

How did you deploy Kubeflow Pipelines (KFP)?
https://www.kubeflow.org/docs/other-guides/virtual-dev/getting-started-multipass/

KFP version:
- Outside of environment, 0.2.2.1
- Inside of environment : what was installed originally in a default setup + latest

KFP SDK version: 
kfp                      0.2.2.1   
kfp-server-api           0.1.40 

### Anything else you would like to add:
I'm almost inclined to not call this a bug, as ignoring invalid https certificates is a fairly sane thing to do, but it'd be nice if this also worked when demoing stuff locally. 

It's a super cool feature!

/kind bug
/area sdk

**Comment by Ark-kun** [comment]
is it possible to just use http in this case?

**Comment by andaag** [comment]
That would be great, but I don't think that's currently possible in the sdk.

**Comment by Bobgy** [comment]
Sounds like we should support using http in sdk?
/area sdk/client

**Comment by rmgogogo** [comment]
I think KFP installation didn't handle things like CertBot etc. (correct me if I'm wrong). Would suggest you deploy a small cluster to GCP via clicks (Google Cloud - AI Platform - Pipelines) and connect to it via HTTPS.

As for local sdk -> local server, if you want to avoid use https, you may try directly hit the KFP API Server without go thought the Inverse Proxy. I didn't try it but think it can work.
