### ISSUE TITLE
[Feature request] How to create recurring run like cronjob through SDK

### ISSUE THREAD

**Issue by sh-tatsuno** [kubeflow/pipelines#3105]
I want to create recurring run like cronjob through SDK

I found two kinds of ways to create run described below, but I have no idea how I set scheduling parameter through SDK.
`run_pipeline` or `create_run_from_pipeline_func`

If possible, it would be appreciated if anyone tell me the way.

**Comment by rmgogogo** [comment]
@Ark-kun

**Comment by Bobgy** [comment]
I think there are two related PRs, but I'm not sure about lateset status.
https://github.com/kubeflow/pipelines/pull/2978
https://github.com/kubeflow/pipelines/pull/2981
/assign @Ark-kun 
/assign @numerology

**Comment by Bobgy** [comment]
FYI, I wrote an example for how to use it in https://github.com/kubeflow/pipelines/issues/3207#issuecomment-595022025

**Comment by Bobgy** [comment]
@sh-tatsuno
