### ISSUE TITLE
Executions page does not render name and state properly

### ISSUE THREAD

**Issue by rafaelbarreto87** [kubeflow/pipelines#3109]
### What steps did you take:

Execute the steps in the metadata demo notebook: https://github.com/kubeflow/metadata/blob/master/sdk/python/sample/demo.ipynb.

### What happened:

Executions are created properly. I can query the metadata store and see that the information is there. However, the name does not get rendered correctly in the UI. As a consequence, there are no links for the executions, which means there's not a good way to accessing past executions.

<img width="1323" alt="Screen Shot 2020-02-18 at 3 28 24 PM" src="https://user-images.githubusercontent.com/367830/74787211-7700c300-5263-11ea-8147-4b7fb151c67f.png">

### What did you expect to happen:

The name of the execution gets listed in the execution page.

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

Using `kfctl` and https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.0.yaml.

KFP version: 881cde2

KFP SDK version: 

```
$ pip list | grep kfp
kfp                        0.2.2.1   
kfp-server-api             0.1.40
```

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by Bobgy** [comment]
Thanks for the report, I will try to reproduce

**Comment by Bobgy** [comment]
Okay, I reproduced the issue, digging what was wrong here.
