### ISSUE TITLE
Container op should expose method to append volume/mount/envs

### ISSUE THREAD

**Issue by IronPan** [kubeflow/pipelines#311]
Currently it only exposes set() which will override any existing values. 
https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/dsl/_container_op.py#L158

Since these fields are list, we should support appending instead of setting.

**Comment by gaoning777** [comment]
Could this be closed since we have them in the DSL?

**Comment by vicaire** [comment]
Resolving. Please reopen if anything is missing.
