### ISSUE TITLE
[SDK] Python light-weight component generated argo template will encounter "argument list too long" error if pickled codes are too big

### ISSUE THREAD

**Issue by eterna2** [kubeflow/pipelines#3130]
### What steps did you take:
- create and compile a pipeline with light-weight python components
- run the pipeline

### What happened:
- op will fail with the error msg "argument list too long"

### What did you expect to happen:
- op to execute normally

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

KFP version: 

KFP SDK version: 

### Anything else you would like to add:

The current implementation for light-weight py component is to pickle the code and pass in as a base64 string through the argument to the container.

shell (or k8s/docker container args) has a limit to the number of characters to the arg, this cause the "argument list too long" error to occur if the pickled base64 string is too big. 

Below is a fragment of the generated argo yaml.

```yaml
"templates":
  - "container":
      "args":
      - |-
        python3
      - |-
        -u
      - |-
        -c
      - |
        import sys
        try:
            import cloudpickle as _cloudpickle
        except ImportError:
            import subprocess
            try:
                print("cloudpickle is not installed. Installing it globally", file=sys.stderr)
                subprocess.run([sys.executable, "-m", "pip", "install", "cloudpickle==1.1.1", "--quiet"], env={"PIP_DISABLE_PIP_VERSION_CHECK": "1"}, check=True)
                print("Installed cloudpickle globally", file=sys.stderr)
            except:
                print("Failed to install cloudpickle globally. Installing for the current user.", file=sys.stderr)
                subprocess.run([sys.executable, "-m", "pip", "install", "cloudpickle==1.1.1", "--user", "--quiet"], env={"PIP_DISABLE_PIP_VERSION_CHECK": "1"}, check=True)
                print("Installed cloudpickle for the current user", file=sys.stderr)
                # Enable loading from user-installed package directory. Python does not add it to sys.path if it was empty at start. Running pip does not refresh `sys.path`.
                import site
                sys.path.append(site.getusersitepackages())
            import cloudpickle as _cloudpickle
            print("cloudpickle loaded successfully after installing.", file=sys.stderr)

        pickler_python_version = (3, 7, 3, 'final', 0)
        current_python_version = tuple(sys.version_info)
        if (
            current_python_version[0] != pickler_python_version[0] or
            current_python_version[1] < pickler_python_version[1] or
            current_python_version[0] == 3 and ((pickler_python_version[1] < 6) != (current_python_version[1] < 6))
            ):
            raise RuntimeError("Incompatible python versions: " + str(current_python_version) + " instead of " + str(pickler_python_version))

        if current_python_version != pickler_python_version:
            print("Warning!: Different python versions. The code may crash! Current environment python version: " + str(current_python_version) + ". Component code python version: " + str(pickler_python_version), file=sys.stderr)

        import base64
        import pickle

        dummy_op_fn = pickle.loads(base64....somebase64codes...dFIu'))

        import argparse
        _parser = argparse.ArgumentParser(prog='Dummy op fn', description='')
        _parsed_args = vars(_parser.parse_args())
        _output_files = _parsed_args.pop("_output_paths", [])

        _outputs = dummy_op_fn(**_parsed_args)

        if not hasattr(_outputs, '__getitem__') or isinstance(_outputs, str):
            _outputs = [_outputs]

        _output_serializers = [

        ]

        import os
        for idx, output_file in enumerate(_output_files):
            try:
                os.makedirs(os.path.dirname(output_file))
            except OSError:
                pass
            with open(output_file, 'w') as f:
                f.write(_output_serializers[idx](_outputs[idx]))
```

We probably should change the base64 pickle to a raw artifact instead and read in from fs.

https://github.com/argoproj/argo/blob/master/examples/input-artifact-raw.yaml

I can provide a PR to fix this.

/kind bug

**Comment by eterna2** [comment]
![Screenshot 2020-02-20 at 5 30 13 PM](https://user-images.githubusercontent.com/1248825/74921645-072c3d00-5409-11ea-9d61-449d5852f76a.png)

**Comment by Bobgy** [comment]
/assign @Ark-kun 
/assign @hongye-sun 
/assign @numerology 
Sounds like a good idea to me, but I am not familiar with this area.

**Comment by Ark-kun** [comment]
What's the size of the command-line where you experience the problem? BTW, we can also gzip the pickle data to make it smaller.

The fix that you propose might be pretty hard given the current architecture.
The component architecture does not let you specify argument values in the component (that would make the Component a Task). There are default input values, but putting the code there looks like a pretty ugly hack.

BTW, the limits of command-line (AFAIK, it's usually 4MiB) should be higher than the limits of Kubernetes' object size of 1MiB, so I though that we should not be getting this issue. Let's investigate.

Which OS or base image are you using?

**Comment by Ark-kun** [comment]
> this cause the "argument list too long" error to occur if the pickled base64 string is too big.

This seems a bit heavy-weight =)

**Comment by eterna2** [comment]
> What's the size of the command-line where you experience the problem? BTW, we can also gzip the pickle data to make it smaller.
> 
> The fix that you propose might be pretty hard given the current architecture.
> The component architecture does not let you specify argument values in the component (that would make the Component a Task). There are default input values, but putting the code there looks like a pretty ugly hack.
> 
> BTW, the limits of command-line (AFAIK, it's usually 4MiB) should be higher than the limits of Kubernetes' object size of 1MiB, so I though that we should not be getting this issue. Let's investigate.
> 
> Which OS or base image are you using?

I need to check, we used a combination of Alpine and Debian, not sure which one for this error.

We hit this error when our code is only moderately big. 

Let me check with our data scientist.

**Comment by ustcyue** [comment]
The size of the command-line is around 130k chars.
This is just an operator with less than 10k lines, so not really that heavy weight :)

**Comment by reem** [comment]
Still experiencing this problem with only moderately sized components, it's quite easy to hit this limit and am also seeing it with pickles of only roughly 140k-150k characters, which do not seem like they are large enough to warrant this blocker.

/reopen

**Comment by reem** [comment]
Still an active issue, original fix of pushing the pickled code to an artifact and reading from it is what we've been doing internally to work around and would be a wonderful feature to have by default - it would also shrink the generated component yaml and make it more readable and less boilerplate if much of the other boilerplate code could also be moved to an artifact.
