### ISSUE TITLE
Support inline sources in all visualizations

### ISSUE THREAD

**Issue by enriquedacostacambio** [kubeflow/pipelines#3133]
### Problem
Some visualizations do not support an inline source forcing a superfluous upload to a storage service. (eg: confusion matrix)

#### Option 1: Add inline handling in each visualization type.
Following the current pattern a branch for inlined content can be added to each visualization type that doesn't have inline support already, see the [markdown visualization as an example](https://github.com/kubeflow/pipelines/blob/master/frontend/src/lib/OutputArtifactLoader.ts#L359).
- Pros: It follows the current approach,
- Cons: It requires the handling needs to be done over and over.

#### Option 2: Add an "Inline" storage service
Following what is done for specific storage providers an inline storage service can be added so that it matches the "inline://" scheme. (see [parseStoragePath](https://github.com/kubeflow/pipelines/blob/master/frontend/src/lib/WorkflowParser.ts#L332))

In addition, support for plaintext and binary content *may* be handled by adding a qualifier to the path:
```
inline://plain/this-is-my-plain-text-content
```
```
inline://base64/dGhpcy1pcy1teS1iaW5hcnktY29udGVudA==
```
(or at least it may be a good idea to just support plaintext but to keep in the path so that it can be extended in the future)

- Pros: It seamlessly integrates to every ui component that needs to fetch content without further changes.
- Cons: It requires a new storage service.

**Note**: See [Apis.readFile]( https://github.com/kubeflow/pipelines/blob/3b072b2ff7e98b96afd232e1c18baf0e51c9d2c2/frontend/src/lib/Apis.ts#L175), there are at least three options:
- change `Apis.readFile` to return the content immediately when the storage service is inline.
- change the backed api to understand the inline storage service (this may be needed anyway for other reasons beyond my knowledge)
- or both of the above to save a roundtrip.

/kind feature
/area frontend

**Comment by Bobgy** [comment]
That sounds like a good idea. Do you want to contribute?

**Comment by Bobgy** [comment]
I tried to use this in https://github.com/kubeflow/pipelines/issues/3162.
Inlining source file content is sooo much easier to integrate.

Bumped priority.
/assign @Bobgy 
I will do this.

**Comment by Bobgy** [comment]
FYI, I chose option 1, because of consistency with existing example, and the duplication can be easily avoided by sharing a common utility function.

**Comment by Bobgy** [comment]
/reopen
One last TODO item:
* [ ] Update documentation after release: https://www.kubeflow.org/docs/pipelines/sdk/output-viewer/

**Comment by Bobgy** [comment]
/close
Documentation also done

**Comment by enriquedacostacambio** [comment]
@Bobgy thanks a lot! i'm just coming back to this, i'd love contribute pr next time!

**Comment by Bobgy** [comment]
Thanks for offering help, you can bring up new ideas, look at issues with help wanted tag or work on issues in KFP 1.0 project
