### ISSUE TITLE
"Request Entity too Large" when saving artifacts

### ISSUE THREAD

**Issue by parthmishra** [kubeflow/pipelines#3134]
### What steps did you take:
In my component, I create 2 large CSV files and write them to the file paths given from `outputPath` parameters. These files total to around ~1GB uncompressed.

### What happened:
The files are saved to GCS just fine but the `wait` Argo container in the component Pod fails with these logs:

```
level=info msg="Annotating pod with output"
level=error msg="executor error: Request entity too large: limit is 3145728"
level=info msg="Alloc=4518798 TotalAlloc=11263514 Sys=6497150 NumGC=23 Goroutines=8"
level=fatal msg="Request entity too large: limit is 3145728"
```

### What did you expect to happen:
- Save artifacts to GCS

### Environment:
- I'm using GCS as artifact storage (as configured by the GCP Kustomization patch)
- I don't have any volumes mounted besides secrets

How did you deploy Kubeflow Pipelines (KFP)?

Standalone deployment with GCP patch to use Cloud SQL and GCS

KFP version: v0.2.2

KFP SDK version: v0.2.2

### Anything else you would like to add:
Am I misusing the artifact storage in this way? i.e. am I only supposed to save small artifacts to this?

/kind bug

**Comment by parthmishra** [comment]
I think I am probably misusing artifacts registry and should probably look towards using something like [Cloud Filestore](https://www.kubeflow.org/docs/gke/cloud-filestore/) seems to fit the use case I was going for. I would still like to understand what this error message means though.

**Comment by Ark-kun** [comment]
Usually this error means that you're **consuming** those artifacts as values. This causes Argo to inject the value in the Workflow spec and later inject it in the command-line. This is impossible with large files.
Check your consumers -they should be using `inputFile`, not `inputValue`.

**Comment by Ark-kun** [comment]
Closing dues to lack of response.
@parthmishra Please reopen the issue if the issue occurs again.

**Comment by johan-andersson01** [comment]
> Usually this error means that you're **consuming** those artifacts as values. This causes Argo to inject the value in the Workflow spec and later inject it in the command-line. This is impossible with large files.
> Check your consumers -they should be using `inputFile`, not `inputValue`.

Ran into this issue and this fixed it, thanks! Note for future readers though: `inputPath` instead of `inputFile`.
