### ISSUE TITLE
[Process] Deprecate Python 2 dependencies

### ISSUE THREAD

**Issue by numerology** [kubeflow/pipelines#3155]
Python 2 is deprecated and stopped being maintained since this year. We should work on gradually get rid of the Py2 environment.

Some issues already emerged as discussed in https://github.com/kubeflow/pipelines/pull/3152#issuecomment-589936697

**Comment by Ark-kun** [comment]
The SDK is already Python3 only.

Some 1st-party components might still use use Python2, but they're standalone.
