### ISSUE TITLE
[UI] Support Artifacts/Executions list sorting and filtering

### ISSUE THREAD

**Issue by rmgogogo** [kubeflow/pipelines#3157]
### What steps did you take:
Go to Artifacts/Executions list. Click sort/filtering.

### What happened:
Artifacts/Executions list's sort and filtering can't work.

### What did you expect to happen:
Let it work or hide the filter/sort before it can work.

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

KFP version: 

KFP SDK version: 

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug
/area frontend
/area backend

**Comment by Bobgy** [comment]
Note, this is related to https://github.com/kubeflow/pipelines/issues/3226. I will likely tackle both together.

**Comment by Bobgy** [comment]
Because backend hasn't supported these. Delay to after 1.0

**Comment by Bobgy** [comment]
Thanks

**Comment by Bobgy** [comment]
Current MLMD order by field feature is very limited, we can only order by [ID, Create Time, Last Updated Time]: https://github.com/kubeflow/pipelines/blob/fd72b3c9d59803726c41f287cd1ee98b8f95cc5a/third_party/ml-metadata/ml_metadata/proto/metadata_store.proto#L645-L662

So this feature still needs upstream improvements.

**Comment by rimolive** [comment]
Closing this issue. No acitivity for more than a year.

/close
