### ISSUE TITLE
Metadata SDK compatability with KFP standalone

### ISSUE THREAD

**Issue by parthmishra** [kubeflow/pipelines#3169]
I'm confused on what the status of the Metadata service with regards to full Kubeflow versus standalone KFP since I seem to recall they have diverged for some reason. Specifically, I want to know if it's supposed to be possible to use the Metadata SDK within KFP standalone.

I tried using it but got an unknown type for `kubeflow.org/alpha/execution`. Has the schema changed at all?

**Comment by eterna2** [comment]
I have not got time to try the metadata service, but from what I understand PR #2674 adds a metadata writer service which logs the execution and artifacts input/outputs automatically for any running pipelines.

And I dun think it diverge, rather the main manifest is slower? (I am not sure, i think the sdk moved from rest to grpc, which some breaking change - i probably need to use the right version).

The last time i tried it works, but it was the older version. Haven't tried with the recent one yet - I also see that they moved the repo back to main metadata repo (https://github.com/kubeflow/metadata/tree/master/sdk/python).

**Comment by parthmishra** [comment]
That metadata writer seems interesting, are there any docs for it or tutorials?

**Comment by amitripshtos** [comment]
The metadata write automatically writes executions and artifacts to the MLMD and it works (version 0.2.2). You can connect to the MLMD manually inside a pipeline using the python SDK.
