### ISSUE TITLE
Python fire interprets string incorrectly

### ISSUE THREAD

**Issue by gaoning777** [kubeflow/pipelines#318]
According to the Python fire argument parsing guide(https://github.com/google/python-fire/blob/master/docs/guide.md#argument-parsing). Some strings might be incorrectly interpreted, then purified.
For example, Amy recently had a problem of passing 1.10 as the argument but it unfortunately interpreted as float and passed as 1.1 to the container.

**Comment by gaoning777** [comment]
solved by PR: https://github.com/kubeflow/pipelines/pull/384

**Comment by Ark-kun** [comment]
Fixed
