### ISSUE TITLE
[Tutorial] lightweight component tutorial has bad metadata usage

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#3182]
### What steps did you take:
[A clear and concise description of what the bug is.]
This tutorial: https://github.com/kubeflow/pipelines/blob/master/samples/tutorials/mnist/01_Lightweight_Python_Components.ipynb.
It doesn't send metadata output correctly, because https://github.com/kubeflow/pipelines/issues/3162#issuecomment-591540614

### What happened:
The metadata doesn't show up in UI.

### What did you expect to happen:
The metadata should be recorded.

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

/area docs
/area sdk

**Comment by Ark-kun** [comment]
> This tutorial: https://github.com/kubeflow/pipelines/blob/master/samples/tutorials/mnist/01_Lightweight_Python_Components.ipynb.
> It doesn't send metadata output correctly

Please note that this is not our 1st-party tutorial. It's contributed by external people and should be moved to contrib.

Our main Lightweight component sample in `samples/core` has correct usage.

**Comment by luotigerlsx** [comment]
Hey, I am happy to get it fixed.

**Comment by Bobgy** [comment]
@luotigerlsx Thanks for the fix!
