### ISSUE TITLE
[Design Proposal] Vega/Vega-Lite as visualization dsl for Kubeflow metadata-ui

### ISSUE THREAD

**Issue by eterna2** [kubeflow/pipelines#3187]
### Background
Currently, kfp manages visualization through a collections of [`viewer` components](https://github.com/kubeflow/pipelines/tree/master/frontend/src/components/viewers). 

Ignoring viewers like markdown, html, tensorboard, etc, visualization in kfp can be separated into 2 groups:
- pre-created vis by kfp developer with `react-vis` (usually via metadata-ui artifacts)
- pre-defined and user-defined vis based on python (generated via jupyter notebook `display` function)

### Proposal
Vega/Vega-Lite to be used as a visualization dsl for
- specifying metadata-ui artifact, and 
- generating custom vis for data (that do not have a readily-available python lib for visualizing the data) - i.e. alternative to python custom vis.

**Pros**
- language agnostic: Uses a JSON-based dsl to describe visualization

- simple: Simple and concise grammar to generate most common visualization (esp Vega-Lite)
Example: barchart
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A", "b": 28}, {"a": "B", "b": 55}, {"a": "C", "b": 43},
      {"a": "D", "b": 91}, {"a": "E", "b": 81}, {"a": "F", "b": 53},
      {"a": "G", "b": 19}, {"a": "H", "b": 87}, {"a": "I", "b": 52}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative"}
  }
}
```
- supports multiple data format: e.g. csv, tsv, geojson/topojson (for maps), json, etc

- supports multiple/custom loader types: e.g. http request, inlined, data stream, etc

- composable: Vega dsl is designed to be composable, which makes it easy to create visualization from existing vis components - i.e. easy to wrap the dsl as composable vis components in UI.

- can be implemented entirely on client-side: Do not need to have any backend service to generate the html for the visualization

**Cons**

Non I can think of.

### Concept Details

1. Propose for `mlpipeline-ui-metadata.json` artifact to support Vega and Vega-Lite:

i.e.
```js
{
  "version": 1,
  "outputs": [
    {
      "type": "vega-lite",
      "data": { "my-matrix": "my-dir/my-matrix.csv" },  // data to be passed to vega spec to be rendered
      "spec": { ... },  // vega or vega-lite spec or reference pre-defined vega/vega-lite specs
    }
  ]
}
```

2. Replace existing vis component created with `react-vis` with [`react-vega`](https://github.com/vega/react-vega):

It is easier to map existing ui-metadata schema to a vega-lite spec then generate the corresponding vis component, rather than implementing individual vis component, each time we need to support a new vis.

```ts
import { Vega } from 'react-vega';

export const RocCurve = props => {
  const spec = {...}  // pre-defined spec
  return <Vega spec={spec} data={props.data} />
}

```

3. Enhance custom vis creator to support Vega/Vega-Lite
  - provides a simple UI to edit Vega/Vega-Lite spec and renders the vis (does not need a backend)

See https://vega.github.io/editor/#/examples/vega-lite/airport_connections

**Comment by Bobgy** [comment]
Thanks for the suggestion. This is a great idea!
I have some concerns about integrating vega as a first party visualization:
1. How popular is it among data scientists?
2. How big is bundle size, do we need to include both vega and vega-lite?

Would it be enough if we provide some documentation of using them with embeded HTML?
e.g.  https://vega.github.io/vega-lite/usage/embed.html#start-using-vega-lite-with-vega-embed
After my recent change of supporting inline HTML visualization in https://github.com/kubeflow/pipelines/pull/3177, I think it's fairly straight forward to generate a HTML using vega without any change from KFP. And we can also make a python wrapper for that, if there isn't already one.

**Comment by eterna2** [comment]
`How popular is it among data scientists?`

Hard to quantify it's popularity as there are too many vis tools out there. 

It is probably more an engineer tool rather than a data scientist tool - as in it is generally used more as a specification for vis (i.e. instead of saving png of the charts, you save the spec together with ur experiment metadata, params, dataset, etc).

For data scientist, they probably use an abstraction layer on top of it, e.g. altair or py-vega.

`How big is bundle size, do we need to include both vega and vega-lite?`

Fairly big as it is quite comprehensive.
165 kb for Vega. Not sure about Vega lite. U only need Vega lite to transpile Vega lite spec into Vega spec. 

U probably can do tree shaking to remove features u don't intend to support. But probably we can do it as a viewer.

`Would it be enough if we provide some documentation of using them with embeded HTML?`

That would work, but that adds overheads to data scientist. Or do u think it is a better solution for me to add a ui-metadata sdk? 

Because one of the issue I have is that I always have to search for the format of ui-metadata and where to store it, and how to generate it for my kfp operator. In the ideal world, I would prefer a simple sdk to generate whatever vis I wants, without needing to know the actual io.

```py
import kfp.dsl

from kfp.dsl.vis import ConfusionMatrix, WebVis

@kfp.dsl.pipeline()
def some_pipeline():
    op = some_op()
    conf_mat = ConfusionMatrix(..., source= op.outputs.data1)
    // Or
    op.add_vis(WebVis(html=some_html_creator_func))

```

It is probably not important enough a justification to switch to Vega unless kubeflow is going to provider a richer sets of vis.

But I like Vega particularly because the grammar is elegant and easy to remember. And switching between diff vis for same data is quite trivial - i.e. because it is composition rather than templates (unlike many other solutions, diff chart types have diff params - Vega has very good separation).

Essentially, I wanted to package vis artifacts as Vega spec together with data artifacts. And the front end can render vis artifacts as is, w/o much additional work. 

And this vis artifacts can be used at different parts of kubeflow. E.g. as part of metadata service.

**Comment by eterna2** [comment]
Something like this

![](https://api.e2.fyi/vega?mode=img&spec=GYcwkgglYNYMYCYByB7AWgdQIwAsIBEooAhFAEwAkAlAdzgC8UA3AGQGY0AbNBAUQFcenAAwBDCgDUAliwC2nVmyQArUQHEJAFwCaAZQCcCTGRwsMADwAOZNQFUmZZQEV+ogHZImAIxAQn6iUseHGEIAAUUIgI0NQAxYW0nAGEpKIg3CQBPLwhiPCJxKmE4CgBZADYWTP0YUtlYmCRZMGEyAA0wNgBTNrQ6XQBWZS81fSwYtGyEAeE5Ac4yJP1+bTaqLDh6gGdMWMybEE1SzIAWehZlCG9ZCWBSgBVeGi8JfWe2YiwR+MwqYDg1OYcNoEBJ6G0lJYvG1iDtBm5MPoAI6IZZQJpeNgAKR0bScEAA0jQoljhD1iJwoLYiMQUQg0RAsXRZG80G1SV18ViomgbjhKFk2aUorxKFicF4PLJMTiIAB5fFEfDCiAAJzSsjQUOonDgvlEPLirQwwn4JSxTABWRsnF1mQGOBiwnMXnqmjQiog9F4EBVRCxslEFmEbMgFGJUDUVH5kk0LDcxGyH11bioQTapTN9VcWH0uJAIDCSQg5j9XsgcojUCxym0FmUZAs-LsEDUvkj0YFcYTSYpcFT6czdaoRwwDq8GGpEHq9CpNJW2EpUGVxP0GqQErUSC+Ro9EDQhvijdN5stGn2altcHt72IwAnsRO1ZwcGJkCIALebQQuC6aRxqxYuqfg0lIqzvqCKz0jAQYDG4EBgD6Sp-hAoRRJqQQWDAc4kAuWBLhyMJLu2uT8F4P5Qts1b0DKaFlponJEGw2FOCRjKOggZCZMYzbUsQUQUNuXj4kkvK2iMIkCcQlqxHmqztqmAwAtS+CehQsRYHWMyiGszacEYnpQAAvEAA)

I have a simple cloud function to render my chart (that takes a data from a http source) as a png.

Or event as a web app
https://e2.fyi/vega?spec=GYcwkgglYNYMYCYByB7AWgdQIwAsIBEooAhFAEwAkAlAdzgC8UA3AGQGY0AbNBAUQFcenAAwBDCgDUAliwC2nVmyQArUQHEJAFwCaAZQCcCTGRwsMADwAOZNQFUmZZQEV+ogHZImAIxAQn6iUseHGEIAAUUIgI0NQAxYW0nAGEpKIg3CQBPLwhiPCJxKmE4CgBZADYWTP0YUtlYmCRZMGEyAA0wNgBTNrQ6XQBWZS81fSwYtGyEAeE5Ac4yJP1+bTaqLDh6gGdMWMybEE1SzIAWehZlCG9ZCWBSgBVeGi8JfWe2YiwR+MwqYDg1OYcNoEBJ6G0lJYvG1iDtBm5MPoAI6IZZQJpeNgAKR0bScEAA0jQoljhD1iJwoLYiMQUQg0RAsXRZG80G1SV18ViomgbjhKFk2aUorxKFicF4PLJMTiIAB5fFEfDCiAAJzSsjQUOonDgvlEPLirQwwn4JSxTABWRsnF1mQGOBiwnMXnqmjQiog9F4EBVRCxslEFmEbMgFGJUDUVH5kk0LDcxGyH11bioQTapTN9VcWH0uJAIDCSQg5j9XsgcojUCxym0FmUZAs-LsEDUvkj0YFcYTSYpcFT6czdaoRwwDq8GGpEHq9CpNJW2EpUGVxP0GqQErUSC+Ro9EDQhvijdN5stGn2altcHt72IwAnsRO1ZwcGJkCIALebQQuC6aRxqxYuqfg0lIqzvqCKz0jAQYDG4EBgD6Sp-hAoRRJqQQWDAc4kAuWBLhyMJLu2uT8F4P5Qts1b0DKaFlponJEGw2FOCRjKOggZCZMYzbUsQUQUNuXj4kkvK2iMIkCcQlqxHmqztqmAwAtS+CehQsRYHWMyiGszacEYnpQAAvEAA

**Comment by Bobgy** [comment]
I think my main argument is that, vega support is a feature that can be made convenient completely by 3rd party library/components, so I'm not seeing strong enough reason to integrate it in KFP system.

Because there are also other visualization libraries and new libraries coming out. If we re-implement or introduce new first-party visualizations using vega directly, then it's probably worth it to support vega json spec directly though.

**Comment by eterna2** [comment]
yeah, i agree with you on that. I probably can build it as an extension/plugin outside of kfp. 

But what do u think about my suggestion of adding a vis sdk in the kfp dsl? Not about vega but more on my pain with `/mlpipeline-ui-metadata.json`.

Cuz the biggest pain point for me when creating kfp ops is remember the path and the format (i.e. how to populate this json).

I am proposing to add a `kfp.dsl.vis` module which can either:
- append a vis to the op inside a pipeline, or
- or serve as a lib like `tf.io` to generate the  `/mlpipeline-ui-metadata.json` inside the op itself.

Maybe I will do an actual mvp as a `kfp.contrib` to demonstrate my idea.

**Comment by Bobgy** [comment]
@eterna2 I'm no expert on sdk, but personally it also took me some hard time to figure out how to write metadata with sdk, so I'd prefer sdk have builtin support.

/cc @Ark-kun 
/cc @hongye-sun 
/cc @numerology 
for sdk related proposal

**Comment by eterna2** [comment]
Ok, I created a kfx package at https://github.com/e2fyi/kfx/ to demonstrate my idea.

It works now, although I feel it is abit convoluted.

In this example, I am using `ArtfactLocationHelper` to modify the kfp task with env variables that contains metadata about the Argo configs (needs to be inputted by user)
- then I use `KfpArtifact` to retrieve these metadata to generate the url (to be used as source for mlpipeline-ui-metadata) to the artifact as well as the API call to UI to get the artifact (for data loading in Vega).

This is bad mostly because it relies on the user to know the Argo configmap and to set it.

I would prefer the UI artifact API to be able to support `workflow.name` or some identifier - i.e. instead of just source, bucket and key, we can support `workflow.name` + `artifact name`, where these can be used to retrieve the necessary info to get the artifact (similar to what I did to get the pod logs from Argo artifactory).

This removes the need for user to know anything about Argo. And we can meta-declare a source or url to be an artifact generated by kfp tasks.
 

```py
import kfp.components
import kfp.dsl
import kfx.dsl


# creates the helper that has the argo configs (tells you how artifacts will be stored)
# see https://github.com/argoproj/argo/blob/master/docs/workflow-controller-configmap.yaml
helper = kfx.dsl.ArtifactLocationHelper(
    scheme="minio", bucket="mlpipeline", key_prefix="artifacts/"
)

@kfp.components.func_to_container_op
def test_op(
    mlpipeline_ui_metadata: OutputTextFile(str), markdown_data_file: OutputTextFile(str)
):
    "A test kubeflow pipeline task."

    import json

    import kfx.dsl
    import kfx.vis
    import kfx.vis.vega

    data = [
        {"a": "A", "b": 28},
        {"a": "B", "b": 55},
        {"a": "C", "b": 43},
        {"a": "D", "b": 91},
        {"a": "E", "b": 81},
        {"a": "F", "b": 53},
        {"a": "G", "b": 19},
        {"a": "H", "b": 87},
        {"a": "I", "b": 52},
    ]
    vega_data_file.write(json.dumps(data))

    # `KfpArtifact` provides the reference to data artifact created
    # inside this task
    spec = {
        "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
        "description": "A simple bar chart",
        "data": {
            "url": kfx.dsl.KfpArtifact("vega_data_file"),
            "format": {"type": "json"},
        },
        "mark": "bar",
        "encoding": {
            "x": {"field": "a", "type": "ordinal"},
            "y": {"field": "b", "type": "quantitative"},
        },
    }

    # write the markdown to the `markdown-data` artifact
    markdown_data_file.write("### hello world")

    # creates an ui metadata object
    ui_metadata = kfx.vis.kfp_ui_metadata(
        # Describes the vis to generate in the kubeflow pipeline UI.
        [
            # markdown vis from a markdown artifact.
            # `KfpArtifact` provides the reference to data artifact created
            # inside this task
            kfx.vis.markdown(kfx.dsl.KfpArtifact("markdown_data_file")),
            # a vega web app from the vega data artifact.
            kfx.vis.vega.vega_web_app(spec),
        ]
    )

    # writes the ui metadata object as the `mlpipeline-ui-metadata` artifact
    mlpipeline_ui_metadata.write(kfx.vis.asjson(ui_metadata))

    # prints the uri to the markdown artifact
    print(ui_metadata.outputs[0].source)


@kfp.dsl.pipeline()
def test_pipeline():
    "A test kubeflow pipeline"

    op: kfp.dsl.ContainerOp = test_op()

    # modify kfp operator with artifact location metadata through env vars
    op.apply(helper.set_envs())

```

**Comment by eterna2** [comment]
I also written the pydantic data models for the `mlpipeline-ui-metadata` and generated the corresponding json scheme for the file.

**Comment by Bobgy** [comment]
@eterna2 Looks great!
A quick question: is it a requirement to store visualization data in external source? If you just store it inline inside mlpipeline-ui-metadata, then user doesn't need to know so much other context.

I guess you have good reasons to do so, just wanting to know.

**Comment by eterna2** [comment]
Depends on the data size. For small dataset, we probably can inline.

Becuz my prev use cases are mostly geospatial simulation which generates quite a bit of logs. 

And usually we want to store these logs separately.

**Comment by eterna2** [comment]
But I agree that inline shld solve 90% of the use cases.

**Comment by eterna2** [comment]
In this case, I probably can provide helper classes to convert sklearn confusion matrix etc into inline UI metadata.

**Comment by Bobgy** [comment]
I see, external source is definitely needed if data size is huge or ACL is needed on the data. That seems like complexity unrelated to KFP. A helper sdk will be helpful in this case.

Also for inline cases, helper is as good as 1st party integrations.

**Comment by eterna2** [comment]
I encountered some issues getting my artifacts to work inside the iframe as the iframe does not provide `allow-same-origin` permission - request origin = null.

The only 3 solutions I see are:
- only support inlined data
- add CORs flag to the node server (as a param)
- add allow-same-origin permission to the iframe.

Both seems equally risky from security pov.

**Comment by Bobgy** [comment]
Yes, the visualization is expected to only access inline data and open data for security reasons.
