### ISSUE TITLE
Released code in PyPI doesn't match tagged version + release from github

### ISSUE THREAD

**Issue by jangold-miovision** [kubeflow/pipelines#3207]
### What steps did you take:

I'm installing the kubeflow pipelines sdk (`kfp=0.2.5`) through the conda feedstock https://github.com/conda-forge/kfp-feedstock/blob/master/recipe/meta.yaml , which just repackages the archive from https://pypi.org/project/kfp/#files . However, the contents of that archive do not match the contents of the github-released archive from https://github.com/kubeflow/pipelines/releases/tag/0.2.5

### What happened:

The source code installed by the conda feedstock -> pypi package pathway is different from the github release. In particular, I'm looking at https://github.com/kubeflow/pipelines/blame/0.2.5/sdk/python/kfp/_client.py (which has the changes from https://github.com/kubeflow/pipelines/pull/3173 ). The version of this package in PyPI has an older version that hardcodes the `cron_schedule` in `schedule_pipeline`.

You can see the difference in `_client.py` by downloading the archives from those sources and comparing them.

### What did you expect to happen:

Version 0.2.5 should be the same across github and pypi.

/kind bug
// /area sdk

**Comment by rmgogogo** [comment]
thanks, the reason is that we released 0.2.5 for 3 times due to some issues found in backend. No changes in SDK but it's rebuilt and I didn't upload the last build. So no feature diff.

I will upload it to PyPI to avoid confusion. ETA: <8 hours.

**Comment by rmgogogo** [comment]
I just tried to replace the PyPI 0.2.5 with the github one but PyPI doesn't allow replace a released binary. So I can't replace that one.

We have two options:
1. Release a 0.2.5.1 to it. However it also introduce issue that people may wondering why there is no 0.2.5.1 in Github.
2(preferred). We wait for next release to include it. Meanwhile, you can use the one in Github which contains PR3173.

Thanks for creating this ticket.

**Comment by Bobgy** [comment]
I have been using 0.2.5.1 like versions before to just patch sdk, I think it's good too.

**Comment by jangold-miovision** [comment]
What's the ETA on the next release? I'm evaluating KubeFlow at the moment (i.e. until the end of this week) and it'd be really handy to have working scheduling in the client.

**Comment by Bobgy** [comment]
Usually, it will be next week.
But I'd rather suggest you to use auto-generated apis instead, current sdk implementation hasn't exposed all features.
I'll put up an example here.

**Comment by Bobgy** [comment]
@jangold-miovision 
Here's an example you can follow

```python
import kfp
import kfp_server_api.models as models

client = kfp.Client(host='https://4909e80ebc96be52-dot-asia-east1.pipelines.googleusercontent.com/')
experiment_id='98c40077-459d-45ef-8e1d-136f3c5ba704'
pipeline_id='8a199f86-2769-44c5-afce-239d3d461d7f'

# This is for cron schedule
# trigger = models.ApiTrigger(
#     cron_schedule=models.ApiCronSchedule(
#         cron='0 * * * * ?', # per minute
#         start_time='2020-03-01T00:00:00Z',
#         end_time='2020-03-02T00:00:00Z'
#     )
# )
trigger = models.ApiTrigger(
    periodic_schedule=models.ApiPeriodicSchedule(
        interval_second=60,
        start_time='2020-03-01T00:00:00Z',
        end_time='2020-03-02T00:00:00Z'
    )
)
pipeline_spec = models.ApiPipelineSpec(pipeline_id=pipeline_id, parameters=[])

def experiment_ref(id):
    key = models.ApiResourceKey(id=id, type=models.ApiResourceType.EXPERIMENT)
    return models.ApiResourceReference(key=key, relationship=models.ApiRelationship.OWNER)

schedule_body = models.ApiJob(
    name='job-example',
    description='test description',
    pipeline_spec=pipeline_spec,
    resource_references=[experiment_ref(experiment_id)],
    max_concurrency=10,
    no_catchup=False,
    trigger=trigger,
    enabled=False)
response = client._job_api.create_job(body=schedule_body)
response.pipeline_spec = 'omitted' # this field is too long
print(response)
```
And here's respnose
```python
{'created_at': datetime.datetime(2020, 3, 5, 4, 23, 32, tzinfo=tzutc()),
 'description': 'test description',
 'enabled': None,
 'error': None,
 'id': 'a835580b-7957-4d9e-b5e0-41e99aa4c4cc',
 'max_concurrency': '10',
 'mode': None,
 'name': 'job-example',
 'no_catchup': None,
 'pipeline_spec': 'omitted',
 'resource_references': [{'key': {'id': '98c40077-459d-45ef-8e1d-136f3c5ba704',
                                  'type': 'EXPERIMENT'},
                          'name': 'catchup-test',
                          'relationship': 'OWNER'}],
 'status': 'NO_STATUS',
 'trigger': {'cron_schedule': None,
             'periodic_schedule': {'end_time': datetime.datetime(2020, 3, 2, 0, 0, tzinfo=tzutc()),
                                   'interval_second': '60',
                                   'start_time': datetime.datetime(2020, 3, 1, 0, 0, tzinfo=tzutc())}},
 'updated_at': datetime.datetime(2020, 3, 5, 4, 23, 32, tzinfo=tzutc())}
```

**Comment by Bobgy** [comment]
And you can reference api in https://github.com/kubeflow/pipelines/blob/master/backend/api/job.proto#L194.

**Comment by Bobgy** [comment]
@rmgogogo I think release inconsistency is also an issue we'd like to solve, shall we plan for branch based release to solve this?
Feels like p1 to me because it may constantly be a confusion.
/priority p1

**Comment by rmgogogo** [comment]
0.3.0 is out.
