### ISSUE TITLE
Conditions are not visualized properly

### ISSUE THREAD

**Issue by yupbank** [kubeflow/pipelines#321]
Right now the conditions in a pipeline is being visualized as a pod which is wrong

**Comment by yebrahim** [comment]
@rileyjbauer, does https://github.com/kubeflow/pipelines/pull/293 fix this?

**Comment by rileyjbauer** [comment]
@yupbank, thanks for filing this.
Can you clarify a bit what you mean? Are you talking about the static pipeline graph that you reach by clicking on a pipeline, or the runtime graph that you reach by clicking into a run?

**Comment by yupbank** [comment]
the runtime graph that you reach by clicking into a run

**Comment by vicaire** [comment]
Assuming that this is resolved. Please reopen if anything is outstanding.
