### ISSUE TITLE
Compare experience design changes

### ISSUE THREAD

**Issue by ajayalfred** [kubeflow/pipelines#322]
Moving to a split-page menu on left, content on right layout for the comparison experience. Requires a design spec for implementation.

**Comment by vicaire** [comment]
Assuming that this has been done as part of the design changes before the initial release to OSS. Please reopen if not the case.

**Comment by ajayalfred** [comment]
Nope this is not complete, new design changes have not been implemented. Mocks here – https://gallery.googleplex.com/projects/MCHbtQVoQ2HCZV4FTvhm3v2g/files/MCH8EUVCsrm7WMaPxZ9mYERE

**Comment by vicaire** [comment]
Thank you Ajay. Reopening.
