### ISSUE TITLE
Visualisations aren't displayed in pipeline UI

### ISSUE THREAD

**Issue by aaaaahaaaaa** [kubeflow/pipelines#3229]
### What steps did you take:
Created a component which writes the metadata file to display some markdown:
```
metadata = {
    "outputs": [
        # Markdown that is hardcoded inline
        {
            "storage": "inline",
            "source": "# Inline Markdown\n[A link](https://www.kubeflow.org/)",
            "type": "markdown",
        }
    ]
}

with open("/mlpipeline-ui-metadata.json", "w") as f:
    json.dump(metadata, f)
```

The pipeline runs successfully and I can confirm the file is correctly written in the container.

### What happened:
The run output or the component Artifact tab doesn't display any visualisation.

If I manually try to create a visualisation though the UI based on a csv file hosted on GCS, I get the same error as here: https://github.com/kubeflow/pipelines/issues/2883

### What did you expect to happen:
Markdown visualisation to be displayed.

### Environment:

Deployed Kubeflow on GCP using the CLI following the documentation for a customised deployment (https://www.kubeflow.org/docs/gke/deploy/deploy-cli/#customizing-your-kubeflow-deployment). Only updated cluster.jinja to specify the network and subnetwork configuration before creating the deployment.

KFP version: Build commit: ca58b22

KFP SDK version: 0.2.5

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by Bobgy** [comment]
Does https://github.com/kubeflow/pipelines/issues/3162#issuecomment-591540614 solve your problem?
Or if you use lightweight components, you can refer to https://github.com/kubeflow/pipelines/issues/3162#issuecomment-591764099

I think the documentation in https://www.kubeflow.org/docs/pipelines/sdk/output-viewer/ didn't clarify that very well.

**Comment by aaaaahaaaaa** [comment]
Yes, the documentation is missing the bit of information that the metadata file as to be defined as an output of the component.
