### ISSUE TITLE
retry pipeline always fail

### ISSUE THREAD

**Issue by xiaohanhuang** [kubeflow/pipelines#3230]
### What steps did you take:
Run the built-in retry pipeline in kubeflow
### What happened:
Retry sample pipeline always fail
### What did you expect to happen:
No error with the pipeline
### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

KFP version: 

KFP SDK version: 

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by rmgogogo** [comment]
https://github.com/kubeflow/pipelines/pull/3231/files is merged.
Here close. Feel free to reopen if think it still has issues in your side.
