### ISSUE TITLE
[UI] Execution page link from Run Details Page

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#3234]
/area frontend

## Problem
It's a confusion for me how we can find connection between artifacts/executions and KFP runs.

## Proposal
Show a link to corresponding execution detail page from run details page.

/cc @neuromage @numerology @Ark-kun 
What do you think?

**Comment by numerology** [comment]
This sounds helpful. I think there are multiple tasks associated here:

1. Currently in MLMD data model an execution maps to a step in KFP, so first we might need to group executions by run_id.
2. Then we can connect each group of execution with the run details page.

I think a more high-leveled question is that, shall we utilize the context concept in UI as well, to make the grouping story more aligned with MLMD?

**Comment by Bobgy** [comment]
Done in https://github.com/kubeflow/pipelines/pull/3457
