### ISSUE TITLE
Aggregated Tensorboard viewer does not work for Tensorflow 2.x

### ISSUE THREAD

**Issue by rafaelbarreto87** [kubeflow/pipelines#3236]
### What steps did you take:

Start an Aggregated Tensorboard viewer with Tensorflow 2.x.

### What happened:

It fails with "No dashboards are active for the current data set." because the `logdir` parameter is as such:

```
Series1:path_to_model_dir_1,Series2:path_to_model_dir_2
```

Tensorboard 1.x accepts this type of path in which more than one directory is passed separated by comma. However, in Tensorboard 2.x this is only supported through `--logdir_spec` parameter.   Since `viewer-crd-controller` does hot distinguish this case, the aggregated view does not work.

### What did you expect to happen:

Aggregated Tensorboard should work with both Tensorboard 1.x and 2.x

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

kfctl 1.0.0 with kfctl_istio_dex.v1.0.0.yaml manifests

KFP version: 0.2.5

KFP SDK version: 0.2.5

/kind bug

**Comment by Bobgy** [comment]
/reopen

I think we want to keep this open

**Comment by rafaelbarreto87** [comment]
This continues to be an issue as far as I'm aware. Should we keep it open?

**Comment by Bobgy** [comment]
sure

/reopen
/frozen
