### ISSUE TITLE
Using 'in' operator inside dsl.Condition

### ISSUE THREAD

**Issue by jamesandres** [kubeflow/pipelines#3242]
Hello 👋, I'm trying to implement a fan-out type of system with Kubeflow Pipelines. It would be lovely if `dsl.Condition` was capable of understanding `in` for this task.  It's entirely possible I'm just "doing it wrong" or unable to locate the documentation..

What would be nice to have:

```python
def a_pipeline(only_these_ids: List[int] = None):
    objects = get_the_objects_op()  # Returns list of dicts which have an 'id'
    with dsl.ParallelFor(objects.output) as obj:
        with dsl.Condition(obj.id in only_these_ids):  # <<< Is this possible?
            do_a_thing(obj)
```

I have managed to hack around the problem by passing the two operands (`obj.id` and `only_these_ids`) into the container of `do_a_thing`, and having the container exit immediately `if obj.id not in only_these_ids`. But this is a hack solution and causes unnecessary pods/containers to be spun up.

Help?

I'm using `python3.7` with `kfp==0.2.5` to compile the pipelines. We're running this on Kubeflow 0.7.0, which runs a really old version of KFP (ee207f2)..

**Comment by parthmishra** [comment]
I'm not sure if this would work, but another hacky solution could be: 

```python
with dsl.ParalellFor(objects.output) as obj:
    with dsl.ParalellFor(only_these_ids) as id:
        with dsl.Condition(obj.id == id):
            do_a_thing(obj)
```
You're still spinning up pods but they're just the KFP/Argo condition check pod and not your own container so it would be a bit quicker and less overhead.

**Comment by jamesandres** [comment]
That's a useful idea, thanks @parthmishra!

For now I've ended up pushing the problem into a small python-based container which is able to do the `in` logic natively.

**Comment by Ark-kun** [comment]
> For now I've ended up pushing the problem into a small python-based container which is able to do the `in` logic natively.

I think this is a best workaround for now.
This will also help you for more advanced filtering.
Or you can do a filtering component.

```python
from typing import NamedTuple
from kfp.components import create_component_from_func

# There is a bug that will be fixed soon https://github.com/kubeflow/pipelines/pull/3263
#@create_component_from_func
#def intersect_lists_op(list1: list, list2: list) -> list:
#     return [item for item in list1 if item in list2]

@create_component_from_func
def intersect_lists_op(list1: list, list2: list) -> NamedTuple('Out', [('Filtered_items', list)]):
     return ([item for item in list1 if item in list2], )


def a_pipeline(only_these_ids: List[int] = None):
    objects = get_the_objects_op()  # Returns list of dicts which have an 'id'
    filter_task = intersect_lists_op(objects.output, only_these_ids)
    with dsl.ParallelFor(filter_task .output) as obj:
            do_a_thing(obj)
```
