### ISSUE TITLE
[Component] AutoML Tables component should show link as an artifact

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#3246]
/cc @jessiezcc 
/cc @jingzhang36 
/assign @Ark-kun 

It will be helpful if components in 
https://github.com/kubeflow/pipelines/tree/b89aabbce5d48fca10817c3ed3ecc2acf6c0066a/components/gcp/automl can show related AutoML tables url as markdown artifacts.

e.g.
> We would like to be able to click on a link that would take us from the component’s page to an AutoML Tables models page

**Comment by Bobgy** [comment]
@Ark-kun would you have time to work on this? Shall we sync about the plan?

**Comment by Ark-kun** [comment]
Is it possible to make it so that the UX visualizes all artifacts of type 'Markdown'?

**Comment by Bobgy** [comment]
@Ark-kun Yes, that's doable.
Do AutoML tables component already have these artifacts?

**Comment by Ark-kun** [comment]
> Do AutoML tables component already have these artifacts?

No, but it would be pretty easy to add.

**Comment by Bobgy** [comment]
Yep, that sounds like a good idea.
Shall we make an one-pager design doc for this? or go right into the implementation.

It is some duplication of existing features, I think that will be my only concern.

**Comment by Ark-kun** [comment]
@Bobgy I've looked at the URLs and I now I wonder whether hard-coding the URL format in the code is a good idea. The UX and URLs can change, breaking the existing outputs of components.

Here is the model_id artifact that's already returned by the component: `projects/140626129697/locations/us-central1/models/TBL6224612401770135552`

The model page URL is currently `https://pantheon.corp.google.com/automl-tables/locations/us-central1/datasets/TBL5661697632720912384;modelId=TBL6224612401770135552;task=basic/train?project=140626129697`

Do you want me to add the transformation to the component code?

**Comment by Ark-kun** [comment]
The URL for external users is probably different.

**Comment by Bobgy** [comment]
@Ark-kun I understand the concerns, but I don't see a better place to add the transformation.

It wouldn't be a scalable solution if each component needs some UI code change for integration, nor would it be suitable for visualization server I think.

We can only rely on AutoML team to make url backward compatible e.g. when they change url format, they should have auto redirect from old location to the new one.

**Comment by Ark-kun** [comment]
OK. I'll add the transformation to the code.
The funny thing is that I cannot really check what the real URL should be since I'll need a non-Google account for that. But I am pretty confident that I know what it should be.

In the future I think that visualizations might be a good place for the transformation. They could even embed some model vis/view in the node details page and they can update when AutoML web pages update.

**Comment by Bobgy** [comment]
> The funny thing is that I cannot really check what the real URL should be since I'll need a non-Google account for that. But I am pretty confident that I know what it should be.

Not sure about AUTOML url situation, for other GCP urls, if I figured out the external url and paste it in my browser, it correctly redirects to corresponding internal url. I use this method to verify if it is correct. Does it work for you?

> In the future I think that visualizations might be a good place for the transformation. They could even embed some model vis/view in the node details page and they can update when AutoML web pages update.

How about 3rd party components? I think they also want the same integration. I'm imagining visualization server should save some snippets in the db, so 3rd party components can add new visualization types to visualization server that integrate with their components.

**Comment by Ark-kun** [comment]
> How about 3rd party components? I think they also want the same integration. I'm imagining visualization server should save some snippets in the db, so 3rd party components can add new visualization types to visualization server that integrate with their components.

My vision for visualizations:

Visualizations are just normal components (component.yaml) with one input of certain type and an output of type `HTML` or `Markdown`.
The visualizations are put in a certain directory with subdirectories named after type names  (`components/visualizations/<type name>/`).
KFP has some 1st-party visualizations, but user can also specify more repos to search for them.
Given a certain output, Visualization server should search for the visualization component, run it and then just show the HTML/Markdown that the component outputs.

**Comment by Bobgy** [comment]
> > How about 3rd party components? I think they also want the same integration. I'm imagining visualization server should save some snippets in the db, so 3rd party components can add new visualization types to visualization server that integrate with their components.
> 
> My vision for visualizations:
> 
> Visualizations are just normal components (component.yaml) with one input of certain type and an output of type `HTML` or `Markdown`.
> The visualizations are put in a certain directory with subdirectories named after type names (`components/visualizations/<type name>/`).
> KFP has some 1st-party visualizations, but user can also specify more repos to search for them.
> Given a certain output, Visualization server should search for the visualization component, run it and then just show the HTML/Markdown that the component outputs.

@Ark-kun Great ideas! I think letting 3rd party visualizations get integrated easily (and without dependency conflict) is really important, because that's the only way this solution can scale.

Let's continue the discussion in https://github.com/kubeflow/pipelines/issues/3510
