### ISSUE TITLE
Pipeline graph node style updates

### ISSUE THREAD

**Issue by ajayalfred** [kubeflow/pipelines#325]
Present graph orientation is top-down

![old-graph](https://user-images.githubusercontent.com/2425179/48748474-e5ec0800-ec2b-11e8-9005-909c5de14594.png)

Change orientation – graph orientation must be left-right for easy interpretation of flow of information between steps.
Note style of nodes on Pipeline details page.

![100_graph 2x](https://user-images.githubusercontent.com/2425179/48748518-0b791180-ec2c-11e8-8e1e-5c704c78df9b.png)

Note style of nodes on Run details page

![101_graph 2x](https://user-images.githubusercontent.com/2425179/48748538-1b90f100-ec2c-11e8-8378-99ca5a2dfc1f.png)

Graph node spec below

![102_graph 2x](https://user-images.githubusercontent.com/2425179/48748556-251a5900-ec2c-11e8-8f59-5ad87265b16f.png)

If possible, use the margins below for spacing nodes uniformly

![103_graph 2x](https://user-images.githubusercontent.com/2425179/48748562-28ade000-ec2c-11e8-9c94-e7c1c9b4992c.png)

**Comment by vicaire** [comment]
@rileyjbauer, can we close? Is this already implemented?
