### ISSUE TITLE
suggest merging components/gcp and components/google-cloud

### ISSUE THREAD

**Issue by amygdala** [kubeflow/pipelines#3265]
There's a 'storage' component under `components/google-cloud`.  For discoverability, am wondering why it's not under `components/gcp`.  Could we merge those two subdirs?

**Comment by numerology** [comment]
Sure I think that's doable.

The historical reason was, perhaps, components under `components/google-cloud` do not require maintaining/building our own image, instead they are based on an existing public image.

**Comment by Ark-kun** [comment]
> The historical reason was, perhaps, components under `components/google-cloud` do not require maintaining/building our own image, instead they are based on an existing public image.

That's true (exception: `gcp/AutoML` actually belongs to the `google-cloud` group).
These component groups have been created by different people and have pretty different implementation - one uses public image and command-line gcloud SDK tools while the other uses a framework library and needs custom image. The maintainers are also different (me and Hongye).
One reason for separate directory is for a possible case when there are different style components for the same service (for example if I create some component for AI Platform training).

**Comment by amygdala** [comment]
commenting to leave open; I assume we still want to consider this...

**Comment by Ark-kun** [comment]
Most likely, components/gcp will remain as legacy while more components will be added to components/google-cloud over the time.
