### ISSUE TITLE
Request add BigQuery quick link

### ISSUE THREAD

**Issue by rmgogogo** [kubeflow/pipelines#3268]
### What steps did you take:
BigQuery component outputs links in log. We may show the link in KFP UI so that user may easily open BQ and modify query/examine outputs on the fly.

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

KFP version: 

KFP SDK version: 

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind feature
/area frontend

**Comment by Bobgy** [comment]
/assign @Bobgy @Ark-kun 
This is a similar request to https://github.com/kubeflow/pipelines/issues/3246
