### ISSUE TITLE
Better integration with AutoML Table & BQ

### ISSUE THREAD

**Issue by rmgogogo** [kubeflow/pipelines#3269]
More features related with AutoML Table component.
E.x. export eval to BQ. We may provide custom component sample or 1p component for it.

**Comment by rmgogogo** [comment]
Another few request is in 1.0 planned here:
https://github.com/kubeflow/pipelines/issues/3246

**Comment by Bobgy** [comment]
@rmgogogo FYI, recommend not using the bug template when you create a feature request
