### ISSUE TITLE
引用了两个不存在的变量 (refer to 2 non-existing vars in arena component)

### ISSUE THREAD

**Issue by ivanbrave** [kubeflow/pipelines#3271]
代码路径：https://github.com/kubeflow/pipelines/blob/8495eb1a6f643c0091b57b9c9328b1b6f8bdf605/components/arena/python/arena/_arena_distributed_tf_op.py
metric_name和metric_unit不存在，会报错

**Comment by ivanbrave** [comment]
@cheyang

**Comment by cheyang** [comment]
What's error?

**Comment by ivanbrave** [comment]
> What's the error?
File "/opt/conda/lib/python3.7/site-packages/arena/_arena_distributed_tf_op.py", line 115, in distributed_tf_op
    "--output-data", output_data,
NameError: name 'output_data' is not defined
