### ISSUE TITLE
dsl.ParallelFor fails if file_outputs key is not "out"

### ISSUE THREAD

**Issue by hlu09** [kubeflow/pipelines#3277]
### What steps did you take:
https://github.com/kubeflow/pipelines/blob/master/samples/core/loop_output/loop_output.py#L26

Change 
  file_outputs={'out': '/tmp/out.json'},
to
  file_outputs={'test_out': '/tmp/out.json'},

Then 
  Pipeline run fails

### What happened:

loop_output fails with output key name change.  Looks like only 'out' works.

### What did you expect to happen:

It should succeed since there is only one output. 

And we should support 
 with dsl.ParallelFor(op0.outputs["test_out"]) as item:

### Environment:
0.1.34

**Comment by numerology** [comment]
I think it's been fixed previously. It works on my end.

@hlu09 do you mind updating to the latest SDK version and try again? Thanks

**Comment by hlu09** [comment]
Right. I tried 0.2.5 client. It works. Thanks!
