### ISSUE TITLE
TFX CLI / KFP SDK - Basic validation for ENDPOINT field

### ISSUE THREAD

**Issue by rmgogogo** [kubeflow/pipelines#3280]
Currently we didn't provide good error msg if user input a wrong ENDPOINT value.

1. Doc mentioned user better to remove HTTPS/HTTP. Better we correct it for user
2. Doc mentioned ENDPOINT should be full hostname but still have user just input the InverseProxy ID part. For such case, better SDK provide early validation error msg.

**Comment by numerology** [comment]
Ack. I can take a shot when got some cycles.

FYI [this](https://github.com/kubeflow/pipelines/blob/d9bb1be25b838142267acbf83ca8f1a5bf33ef54/sdk/python/kfp/_client.py#L159) is the code involved if we want to investigate how to do that

**Comment by numerology** [comment]
Fixed by #3287 
Close for now
