### ISSUE TITLE
Metadata Store Upgrade for KFP

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#3284]
Public doc: https://docs.google.com/document/d/1gF-mx3lMyU9h7MAAOXP-KGV-BF-UabDsAlFrWNNhKBo/edit?usp=sharing

/assign @dushyanthsc

**Comment by Bobgy** [comment]
Hi @dushyanthsc! I'm opening this issue to track this progress under KFP 1.0 project.

**Comment by dushyanthsc** [comment]
@Bobgy  Thanks. I am almost done with the implementation testing right now, should send out a PR by EOD today.

**Comment by Bobgy** [comment]
@dushyanthsc Can you link related PRs here? Is this done?
