### ISSUE TITLE
uninstall failed, there are twenty pod has not been deleted

### ISSUE THREAD

**Issue by hackenzheng** [kubeflow/pipelines#329]
![image](https://user-images.githubusercontent.com/16522546/48773005-15207900-ed01-11e8-930f-59186e4e6911.png)
When uninstall ml-pipeline, the deploy.sh terminated. The error was as above iamge.

**Comment by vicaire** [comment]
Assuming that this is resolved since it has been idle for a long time. Please re-open if there is still an issue.
