### ISSUE TITLE
[Multi User] UI should react when user changes namespace

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#3296]
/cc @chensun 
/area frontend
Pointed out by https://github.com/kubeflow/pipelines/pull/3252#issuecomment-598351676

A few changes we need when user changes namespace:
* experiment list page -> needs auto refresh
* experiment detail page -> needs auto redirect to experiment list page

I think these two changes are enough right now, will adjust based on user feedback later.

**Comment by Bobgy** [comment]
/reopen
There's a minor bug with this implementation.

Steps:
* Refresh the page on experiment list
* Sometimes, the page shows an error message of
```
{"error":"Invalid input error: Invalid resource references for experiment. ListExperiment requires filtering by namespace.","message":"Invalid input error: Invalid resource references for experiment. ListExperiment requires filtering by namespace.","code":3,"details":[{"@type":"type.googleapis.com/api.Error","error_message":"Invalid resource references for experiment. ListExperiment requires filtering by namespace.","error_details":"Invalid input error: Invalid resource references for experiment. ListExperiment requires filtering by namespace."}]}
```
but experiment list is correct
* That's because namespace hasn't been selected when the page loads, so it shows the error message
* Then namespace is synced from kubeflow central dashboard, so it refetches automatically, but that doesn't clear the page error message.

**Comment by lomori** [comment]
I'm seeing the same error as @Bobgy  when trying to compile and run a project with Kale enabled:

Message: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'content-type': 'application/json', 'trailer': 'Grpc-Trailer-Content-Type', 'date': 'Wed, 21 Oct 2020 20:16:43 GMT', 'x-envoy-upstream-service-time': '2', 'server': 'envoy', 'transfer-encoding': 'chunked'})
HTTP response body: {"error":"Invalid input error: Invalid resource references for experiment. ListExperiment requires filtering by namespace.","message":"Invalid input error: Invalid resource references for experiment. ListExperiment requires filtering by namespace.","code":3,"details":[{"@type":"type.googleapis.com/api.Error","error_message":"Invalid resource references for experiment. ListExperiment requires filtering by namespace.","error_details":"Invalid input error: Invalid resource references for experiment. ListExperiment requires filtering by namespace."}]}

Details: You can find more information under /home/jovyan/kale.log

**Comment by subodh101** [comment]
@Bobgy 
Could you help me which kubeflow deployment/image will have your two updated changes?
Thanks.

**Comment by Bobgy** [comment]
@subodh101 they were merged very early: https://github.com/kubeflow/pipelines/commit/124067a58d0d000924f4d9dcf39464f65e1a1ee8

KFP 0.4.0 already have them

**Comment by subodh101** [comment]
Thank you @Bobgy .
When we deployed kubeflow1.1 around 3 months ago. All the images were old. 
I have updated most of the images manually since then. But still, we got the same error today.

We were using frontend image version `1.0.0-rc.3`. I have also updated that to `1.0.0` from env config controller.
UI seems responsive as for now. But it doesn't last responsive very long and ends up with the same error on UI.

```zsh
▶ kubectl -n kubeflow get deploy -o yaml | grep -i "image: "                       
          image: gcr.io/kubeflow-images-public/admission-webhook:v1.1.0-g3ac3d08b
          image: argoproj/argoui:v2.3.0
          image: gcr.io/ml-pipeline/cache-deployer:1.0.0
          image: gcr.io/ml-pipeline/cache-server:1.0.0
          image: gcr.io/kubeflow-images-public/centraldashboard:v1.1.0-g35d7484a
        - image: gcr.io/cloud-solutions-group/cloud-endpoints-controller:0.2.1
        - image: gcr.io/kubeflow-images-public/katib/v1alpha3/suggestion-goptuna:917164a
          image: gcr.io/kubeflow-images-public/jupyter-web-app:v1.1.0-gd3377cbd
          image: gcr.io/kubeflow-images-public/katib/v1alpha3/katib-controller:917164a
          image: gcr.io/kubeflow-images-public/katib/v1alpha3/katib-db-manager:917164a
          image: mysql:8
          image: gcr.io/kubeflow-images-public/katib/v1alpha3/katib-ui:917164a
          image: python:3.7
          image: mysql:8.0.3
          image: gcr.io/kubeflow-images-public/metadata:v0.1.11
        - image: gcr.io/ml-pipeline/envoy:metadata-grpc-1.0.1
          image: gcr.io/tfx-oss-public/ml_metadata_store_server:v0.21.1-patched
        - image: gcr.io/kubeflow-images-public/metadata-frontend:v0.1.9
          image: gcr.io/ml-pipeline/metadata-writer:1.0.4
          image: gcr.io/ml-pipeline/minio:RELEASE.2019-08-14T20-37-41Z-license-compliance
          image: gcr.io/ml-pipeline/api-server:1.0.0
          image: gcr.io/ml-pipeline/persistenceagent:1.0.0
          image: gcr.io/ml-pipeline/scheduledworkflow:1.0.4
          image: gcr.io/ml-pipeline/frontend:1.0.0
          image: gcr.io/ml-pipeline/viewer-crd-controller:1.0.0
        - image: gcr.io/ml-pipeline/visualization-server:1.0.0
          image: gcr.io/ml-pipeline/mysql:5.6
          image: gcr.io/kubeflow-images-public/notebook-controller:v1.1.0-gd3377cbd
          image: gcr.io/kubeflow-images-public/profile-controller:v1.1.0-ga49f658f
          image: gcr.io/kubeflow-images-public/kfam:v1.1.0-g9f3bfd00
          image: gcr.io/kubeflow-images-public/pytorch-operator:v1.1.0-gd596e904
          image: gcr.io/kubeflow-images-public/tf_operator:v1.1.0-g92389064
          image: argoproj/workflow-controller:v2.3.0
```

I am thinking of updating our `kubeflow/instance` with gcp-blueprint. What would you suggest?

**Comment by subodh101** [comment]
@Bobgy 
Let's leave this for now. Today I made a lot of changes it is difficult to tell.
I will let you know if I face the error again.
Thank you!
