### ISSUE TITLE
Unclear how much cpu/memory actually available

### ISSUE THREAD

**Issue by lakshmanok** [kubeflow/pipelines#330]
I created a GKE cluster with 4 n1-standard-2 nodes (8 vCPUs and 30 GB memory)

Yet, I'm not able to submit a task with these requirements:
 ```
   train_tuned.set_memory_request('6G')
    train_tuned.set_cpu_request('4')

```

**Comment by vicaire** [comment]
Resolving as this has been idle for a while. Please re-open if there is still an issue.
