### ISSUE TITLE
Define Kubeflow Pipelines' Stable Requirements using Kubeflow Community's Process (as defined in Application Requirements Template)

### ISSUE THREAD

**Issue by jbottum** [kubeflow/pipelines#3300]
### What steps did you take:
[A clear and concise description of what the bug is.]

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

KFP version: 

KFP SDK version: 

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by jbottum** [comment]
@jessiezcc Kubeflow Pipelines should define its requirements for a Stable version using the process defined by the Kubeflow Community.   This includes creating Applications Requirements, please see this doc as an example.  https://github.com/kubeflow/community/blob/master/guidelines/application_requirements.md

**Comment by Bobgy** [comment]
Hi @jbottum, sounds like already tracked in https://github.com/kubeflow/pipelines/issues/2884
