### ISSUE TITLE
minimist security alert after Github integrated with NPM

### ISSUE THREAD

**Issue by rmgogogo** [kubeflow/pipelines#3302]
### What steps did you take:
Security alert after Github integrated with NPM.
https://github.com/kubeflow/pipelines/network/alert/frontend/package-lock.json/minimist/open

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

KFP version: 

KFP SDK version: 

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by Bobgy** [comment]
This is not fixable for now, we need to wait for jest pick up new minimist as dependency.

**Comment by Bobgy** [comment]
Depends on https://github.com/facebook/create-react-app/issues/8672
