### ISSUE TITLE
MKP: Bucket and project placeholders are not replaced in preloaded samples.

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#3308]
When I submit the preloaded XGBoost sample in KFP v0.2.5 I get the following errorr:
```
Could not find the bucket gs://{{kfp-default-bucket}} in project {{kfp-project-id}}Please verify that you have provided the correct GCS bucket name.
```

**Comment by numerology** [comment]
@Ark-kun Are you using a MKP deployment or standalone deployment?

**Comment by Ark-kun** [comment]
> @Ark-kun Are you using a MKP deployment or standalone deployment?

It's marketplace deployment.
/cc @rui5i has deployed it just couple of days ago.

**Comment by numerology** [comment]
@rui5i do you mind sharing the project name and cluster so that I can take a look? Thanks

**Comment by Ark-kun** [comment]
> @rui5i do you mind sharing the project name and cluster so that I can take a look? Thanks

Shared in chat.

**Comment by rui5i** [comment]
I am using the standalone deployment. Project name: rui-helloworld-264417, cluster: demo-cluster.

**Comment by numerology** [comment]
@Ark-kun 
@rui5i 
Umm... Standalone deployment does not support such placeholder, yet, but I agree that we shall either 1) make the error msg more informative, or 2) come up with an approach to override the placeholders in the prebuilt example for standalone deployment.

1) can be done in the frontend to warn the user when placeholders are detected but cannot be replaced by the default bucket;
2) can be done when the api server spins up itself.

WDYT?

**Comment by Ark-kun** [comment]
> I am using the standalone deployment.

I thought that an entry in Google Cloud/AI Platform/Pipelines means that the pipeline was deployed through the marketplace.
@numerology Do standalone deployments show there?

**Comment by numerology** [comment]
> Do standalone deployments show there?

Yes they do now. After we adding the proper app CRD.

**Comment by susan-shu-c** [comment]
Same error here about the default buckets

**Comment by onetonfoot** [comment]
Yeahh me as well, wouldn't be nice if you could use the minio server deployed with kubeflow as the bucket instead
