### ISSUE TITLE
regression with metrics viz?

### ISSUE THREAD

**Issue by amygdala** [kubeflow/pipelines#3309]
This is with whatever version is used by the Hosted KFP installation.
It seems that metrics rendering as described here: https://www.kubeflow.org/docs/pipelines/sdk/pipelines-metrics/#export-the-metrics-file
no longer works.  
Nor does writing to an OutputPath appear to work.
Interestingly, metadata rendering does still work okay.

my test code here:
https://github.com/amygdala/code-snippets/blob/tables_e2e/ml/automl/tables/kfp_e2e/create_model_for_tables/tables_eval_metrics_component.py#L163
Neither of the two variants for writing 'metrics' work.  
However,  this code for writing 'metadata' does work okay: https://github.com/amygdala/code-snippets/blob/tables_e2e/ml/automl/tables/kfp_e2e/create_model_for_tables/tables_eval_metrics_component.py#L160

**Comment by Bobgy** [comment]
@amygdala I'm not 100% sure, is this realted to https://github.com/kubeflow/pipelines/pull/2964?

To confirm, can you try viewing metrics column from experiment page? `All runs` tab will no longer show metric column.

**Comment by amygdala** [comment]
I'm not seeing anything listed in the 'experiments' listing either.  (I don't see a 'metrics' col either, though maybe it doesn't show up unless things are working properly).

**Comment by Bobgy** [comment]
Yes, the column doesn't show up unless there are metrics.

**Comment by Ark-kun** [comment]
> Then this seems more like a problem on component side.

There are several components that produce metrics (e.g. RoC or ConfusionMatrix). Do those metrics show up in the UX?

**Comment by Bobgy** [comment]
I tried xgboost sample and metrics show up in experiment page.
We'd need to run @amygdala's sample and see if we can reproduce.

**Comment by Bobgy** [comment]
@amygdala sorry to get back to this late.

I ran xgboost sample and it outputs metrics successfully. To figure out whether this is a component problem or a backend/UI problem, you can run xgboost sample on your cluster to see if it has the same error.

But xgboost component is using a different format from @amygdala's example. I'm not familiar with component spec. https://github.com/kubeflow/pipelines/blob/0.2.5/components/local/confusion_matrix/src/confusion_matrix.py#L92-L100
https://github.com/amygdala/code-snippets/blob/tables_e2e/ml/automl/tables/kfp_e2e/create_model_for_tables/tables_eval_metrics_component.py#L146

**Comment by Ark-kun** [comment]
> I ran xgboost sample and it outputs metrics successfully.

Can you please click on the `mlpipeline-metrics` output link and paste here a snippet of the metrics in that file.

**Comment by Bobgy** [comment]
@Ark-kun I got
```
{"metrics": [{"numberValue": 0.9160367026006055, "name": "roc-auc-score"}]}
```

**Comment by amygdala** [comment]
I know how to get the metrics to show up using a `ContainerOp`-based step definition (and I'll just revert to that if need be), but it seems that either something is not quite supported properly with the function-based building of a component, or else I am doing something wrong— except it does work for metadata rendering, but not metrics, which makes me think it's a bug.

Btw, the line numbers in the code have changed a bit, so here are the new links:
output path defined: https://github.com/amygdala/code-snippets/blob/master/ml/automl/tables/kfp_e2e/create_model_for_tables/tables_eval_metrics_component.py#L24
metrics json defined: https://github.com/amygdala/code-snippets/blob/master/ml/automl/tables/kfp_e2e/create_model_for_tables/tables_eval_metrics_component.py#L128
json written to the given path: https://github.com/amygdala/code-snippets/blob/master/ml/automl/tables/kfp_e2e/create_model_for_tables/tables_eval_metrics_component.py#L140

**Comment by amygdala** [comment]
okay, I FINALLY figured out what was going on.  The 'name' field in the metrics dict can not have any capital letters.  That was apparently what broke it.
(why????? 😬😬)

**Comment by Bobgy** [comment]
@amygdala Ohhh, that reminds me of https://github.com/kubeflow/pipelines/issues/3499
Looks like we should bump its priority then.

Thanks a lot for finding the root cause! and sorry for confusion.

**Comment by amygdala** [comment]
hah.  Yeah, that does seem similar.  It would indeed be useful to get some kind of UI error if there exists a metrics dict as output but it is 'not legal' in some way (like use of capital letters).

Also, before we close this issue... I was wondering why the constraint to not use capital letters?  Is this a restriction we could loosen?

**Comment by Bobgy** [comment]
@hongye-sun Do you remember any context? I searched through history and it seems you implemented the feature.

**Comment by hongye-sun** [comment]
I don’t remember very clear not the specific reason. It might be align with API resource name constraint as we treat metrics as a resource name in pipeline API. I don’t feel there is a strong reason behind it.

**Comment by amygdala** [comment]
created an issue to see if we can loosen the naming constraints... closing this one.

**Comment by hongye-sun** [comment]
Thanks, Amy.
