### ISSUE TITLE
kfp.Client cannot access Marketplace-deployed KFP cluster when URI has training slash

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#3310]
`kfp.Client(host='https://XXXXXXXXXXXXXX-dot-us-central2.pipelines.googleusercontent.com/')` does not work
`kfp.Client(host='https://XXXXXXXXXXXXXX-dot-us-central2.pipelines.googleusercontent.com')` works

**Comment by numerology** [comment]
This was fixed in #3287

**Comment by numerology** [comment]
Hold on. @Ark-kun which version of the SDK are you using? I'm curious why the second case works (with the prefix https://)

**Comment by Ark-kun** [comment]
> Hold on. @Ark-kun which version of the SDK are you using? I'm curious why the second case works (with the prefix https://)

It works for me in 0.1.40 and 0.2.5

**Comment by numerology** [comment]
> > Hold on. @Ark-kun which version of the SDK are you using? I'm curious why the second case works (with the prefix https://)
> 
> It works for me in 0.1.40 and 0.2.5

Interesting...Anyway I think #3287 should fix the slash problem.

**Comment by Ark-kun** [comment]
>Anyway I think #3287 should fix the slash problem.
Sounds good.
