### ISSUE TITLE
Kubeflow trigger to dataflow throws UnicodeDecode error

### ISSUE THREAD

**Issue by ClaudioDavi** [kubeflow/pipelines#3315]
### What steps did you take:
After building a pipeline using python dataflow and running fine with DirectRunner and DataflowRunner from my local machine, I built a docker container to use as a component into a kubeflow pipeline.
When I run the pipeline from kubeflow I get an unexpected error building the dataflow module [see logs] 

### What happened:
When using Kubeflow Pipelines to trigger a Dataflow Job using apache_beam, an UnicodeDecode error is thrown from building the requirements for dataflow.

### What did you expect to happen:
The pipeline should run Fine.

### Environment:
Google Cloud Platform
Docker running Ubuntu 18:04 
Python 3.7

How did you deploy Kubeflow Pipelines (KFP)?
http://deploy.kubeflow.cloud/

KFP version: 0.7

KFP SDK version: 
kfp                      0.1.22              
kfp-server-api     0.1.18.3   

### Anything else you would like to add:
Log from kubeflow pipeline:
[log.log](https://github.com/kubeflow/pipelines/files/4355976/log.log)

Requirements file in question
[requirements.txt](https://github.com/kubeflow/pipelines/files/4355981/requirements.txt)

component file: (Apparently github doesnt support yaml)
[component.txt](https://github.com/kubeflow/pipelines/files/4355991/component.txt)

Dockerfile
[Dockerfile.txt](https://github.com/kubeflow/pipelines/files/4355996/Dockerfile.txt)

/kind bug
/area backend
/area sdk
/area engprod

**Comment by yantriks-edi-bice** [comment]
I was getting a similar unicode decoding error and it turned out to be TFX CSVExampleGen not handling compressed CSV. So I thought I'd look at your error log which I did and I don't see any unicode issues - maybe I'm missing something. Instead I see a missing file exception FileNotFoundError: [Errno 2] No such file or directory: \'cc\': \'cc\'

**Comment by Ark-kun** [comment]
Can you please provide more information about your pipeline? How do you submit Dataflow job, etc?
