### ISSUE TITLE
FE is requesting manifest.json which is in public/index.html (it always fails)

### ISSUE THREAD

**Issue by rmgogogo** [kubeflow/pipelines#3317]
### What steps did you take:
FE is requesting manifest.json which is in public/index.html. It always fails in my side (guess no or not generated ).

Per https://stackoverflow.com/questions/45186993/what-is-public-manifest-json-file-in-create-react-app, it is for mobile homescreen shortcut. So we may either create it or delete the line in index.html ?

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

KFP version: 

KFP SDK version: 

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by Bobgy** [comment]
Thanks @rmgogogo for pointing out the issue!
We can safely remove it.
