### ISSUE TITLE
Cloud platform scope not carried through on autoscaling

### ISSUE THREAD

**Issue by lakshmanok** [kubeflow/pipelines#332]
I set up a GKE version (v 1.11) with autoscaling and submitted a job that triggers autoscaling.

When the job is run, I get an error that it is not able to do "gcloud mlengine jobs describe" because it doesn't have the right permissions

**Comment by IronPan** [comment]
The issue seem to be that the new node created by autoscaling doesn't have cloud platform scope. This might be an GKE issue. 

This issue should go away when we switch to use proper service account instead. We should re-test the scenario when that is ready.

**Comment by vicaire** [comment]
Assuming that this as been fixed. Please re-open if it is not the case.
