### ISSUE TITLE
[UX] Visualization tab in run details page is confusing

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#3328]
Continuing the discussion on https://github.com/kubeflow/pipelines/issues/2933#issuecomment-602150326

I think there are a few problems:
* The tab has no explanation at all.
* The tab shows visualization creator when there are no visualizations, but the creator is a fairly advanced feature that users wouldn't usually need it anyway (and they cannot figure out how to use it without documentation).

### Proposal
1. Add url to related documentation
2. Show a line of text "there are no visualizations in this step" when empty
3. Hide the manual visualization creator with an extra click -- provide a text button with caption like "or create visualization manually". User needs to first click this button, before visualization creator shows up.

**Comment by Bobgy** [comment]
Another proposed solution is to merge visualization tab with input/outputs tab, also sounds like a good idea to me: https://github.com/kubeflow/pipelines/issues/2933#issue-557213389.

**Comment by Bobgy** [comment]
Welcome community feedback on what was confusing (was it) and if you have any suggestions.

**Comment by Bobgy** [comment]
/cc @Ark-kun 
What do you think about my proposals here?
The easiest fix, I think is combining input outputs tab and artifact tab.

**Comment by Ark-kun** [comment]
> What do you think about my proposals here?
> The easiest fix, I think is combining input outputs tab and artifact tab.

I agree with both proposals.
Let's append the visualizations at the bottom of the Inputs/Outputs tabs.
And also (can be done later/separately):

>* Add url to related documentation
>* Show a line of text "there are no visualizations in this step" when empty
>* Hide the manual visualization creator with an extra click -- provide a text button with caption like "or create visualization manually". User needs to first click this button, before visualization creator shows up.
