### ISSUE TITLE
GPU with Kubeflow Pipeline

### ISSUE THREAD

**Issue by rmgogogo** [kubeflow/pipelines#3332]
### What steps did you take:
Our default manifest and GCP Hosted Pipeline didn't install GPU related stuff. We can either wrap GPU stuff into KFP installation or provide post-installation manual for GPU.

Since GPU env in different cloud and even same cloud but different region is different (e.x. some region doesn't have K80), this issue is more to track the task to provide post-installation manual for well use GPU. Since GPU is expensive than other resource, it should also help user to well detach GPU resource form cluster to save costs.

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

KFP version: 

KFP SDK version: 

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by rmgogogo** [comment]
@amygdala FYI. Plan to provide post-installation GPU guide first.

**Comment by Jeffwan** [comment]
What `GPU related stuff.` you plan to bring into KFP? like GPU device plugin?

**Comment by rmgogogo** [comment]
step-1: provide manual/doc on how to configure GPU node pool etc. so that KFP workload can use GPU.
step-2: if stable enough, bring it to UI so it can be supported durning installation phase. (e.x. a zero-sided GPU node pool so that users won't be over billed but still can get GPU provisioned when run the workload).

I didn't start work on it yet, feel free to contribute.

**Comment by rmgogogo** [comment]
https://github.com/kubeflow/pipelines/pull/3484 fix step-1.

step-2: we will provide better CLI tool for admin user to easily configure things in one-off manner. It's target to be done in Q2/Q3. It's only for GCP.

**Comment by Bobgy** [comment]
sounds like we want this remain open

**Comment by Ark-kun** [comment]
Perhaps we can deploy a zero-sized auto-scaling node-pool with the marketplace deployment.

**Comment by paveldournov** [comment]
We should also write a manual with very specific steps to take to create a GPU node pool in GKE and set it up for auto-scaling with KFP, and provide pipeline examples that would utilize that.

**Comment by amygdala** [comment]
Step 2 of this codelab does that (minus the autoscaling part): https://codelabs.developers.google.com/codelabs/cloud-kubeflow-pipelines-gis/index.html?index=..%2F..index#1

**Comment by juliusvonkohout** [comment]
We support GPUs very well and this might belong to kubeflow/manifests 

/close
