### ISSUE TITLE
[SDK] Unable to choose pipeline version in run_pipeline

### ISSUE THREAD

**Issue by pselden** [kubeflow/pipelines#3335]
Currently it does not look like there is a way to choose a pipeline version when running in the kfp SDK.

https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/_client.py#L304

The UI allows you to do with a request like:

```json
{
  "description": "",
  "name": "Run of 15a3ef1 (a7a1d)",
  "pipeline_spec": {
    "parameters": []
  },
  "resource_references": [
    {
      "key": {
        "id": "2d5b7fa6-dff8-41b4-b0a3-66ba57d73124",
        "type": "PIPELINE_VERSION"
      },
      "relationship": "CREATOR"
    }
  ]
}
```

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?
One click installer

KFP version: 0.2.5

KFP SDK version: 0.2.5

### Anything else you would like to add:

/kind bug

**Comment by numerology** [comment]
/assign @jingzhang36 
Hi @jingzhang36 I believe that it's in our plan, right?

**Comment by jingzhang36** [comment]
@pselden Thanks for the PR! Including version param in run_pipeline would come handy. Meanwhile, we also have an alternative to always use the latest backend api interface in client. I.e., we can use client.runs.create_run directly with our kfp client. The good thing about client.runs.create_run is that this method is automatically synced to the latest backend api interface. Similar usage includes client.pipelines.create_pipeline, client.experiments.create_experiment, client.pipeline_uploads.xxxx etc. 

We have an upload example at https://www.kubeflow.org/docs/pipelines/tutorials/sdk-examples/
