### ISSUE TITLE
(405) Reason: Method Not Allowed invoking client.pipeline_uploads.upload_pipeline_version

### ISSUE THREAD

**Issue by apryiomka** [kubeflow/pipelines#3342]
### What steps did you take:
I am trying to upload a version of the exiting pipeline using kfp SDK upload_pipeline_version method. 

### What happened:
Running this python:
```
client.pipeline_uploads.upload_pipeline_version(package_file,
                                                        name=version_name,
                                                        pipelineid=current_pipeline.id)
```
Causes the error:

> (405)
> Reason: Method Not Allowed
> HTTP response headers: HTTPHeaderDict({'Audit-Id': '1289ddd2-4ab3-4a34-9a1c-9844b6c3d1db', 'Content-Length': '19', 'Content-Type': 'text/plain; charset=utf-8', 'Date': 'Mon, 23 Mar 2020 19:16:46 GMT', 'X-Content-Type-Options': 'nosniff'})
> HTTP response body: Method Not Allowed

### What did you expect to happen:
The version of the pipeline to be created
### Environment:

> kfp                      0.2.5
> kfp-server-api           0.2.5

How did you deploy Kubeflow Pipelines (KFP)?

KFP version: gcr.io/ml-pipeline/api-server:0.2.0
KFP SDK version: 0.2.5

**Comment by numerology** [comment]
Hi @apryiomka I think you might need to re-deploy your KFP instance because this requires a newer version of backend API.

**Comment by apryiomka** [comment]
@numerology what is the compatible version of the KFP?

**Comment by numerology** [comment]
> @numerology what is the compatible version of the KFP?

I believe 0.2.5 should be good.

**Comment by apryiomka** [comment]
@numerology , how do you change the version of KFP that is being installed? We currently use this manifest: https://github.com/kubeflow/manifests/archive/v1.0.1.tar.gz and we install whatever comes with it.

**Comment by numerology** [comment]
> how do you change the version of KFP that is being installed? 

Oh I see. So you're actually using Kubeflow full-fledged deployment which comes with KFP 0.2.0

One option you have is to follow [this guide](https://www.kubeflow.org/docs/pipelines/installation/standalone-deployment/) to deploy a KFP standalone and to see if that solves the problem.

**Comment by apryiomka** [comment]
> One option you have is to follow this guide to deploy a KFP standalone and to see if that solves the problem.

I am a bit reluctant to go that route since we want KFPs to play well with the rest of the components. We don't anticipate KFP standalone without the rest of Kubeflow. I ideally I am looking for a solution to the existing Kubeflow version / installation. it does seem like an SDK / API bug at this point as we user the SDK sand don't call the API directly.

**Comment by numerology** [comment]
The reason why it happens is that there is a breaking change making 0.2.5 SDK incompatible with 0.2.0 deployment.

@Bobgy Is there an easy way to upgrade KFP as part of the full-fledged KF deployment without breaking other components?

**Comment by Bobgy** [comment]
There's no easy way to upgrade any component in Kubeflow, this is a common complaint with Kubeflow I believe.

There's an open issue tracking upgrading KFP to 0.2.5 in Kubeflow: https://github.com/kubeflow/manifests/issues/984
(I plan to provide a PR shortly.)

And another long term issue that may drastically reduce cost of syncing KFP upgrades with Kubeflow: https://github.com/kubeflow/manifests/issues/1048

**Comment by Bobgy** [comment]
/close
As https://github.com/kubeflow/manifests/issues/984 is fixed
