### ISSUE TITLE
GCP VPC-SC with Kubeflow Pipelines

### ISSUE THREAD

**Issue by rmgogogo** [kubeflow/pipelines#3347]
We need a detailed doc for community on how to configure GCP VPC-SC with Kubeflow Pipelines.

Phase-1: we use GCP Notebook API as VPC-SC control panel to protect both Notebook and Pipeline endpoints (xx.notebook/pipeline.googleusercontent.com).

Phase-2: later we may introduce dedicated GCP Pipeline API to just protect pipeline.googleusercontent.com. This part still is TBD.

This issue is to track the manual/doc on how to let GCP VPC-SC, private cluster and KFP work together and also typical GCS etc. in one VPC-SC Perimeter.

**Comment by jlewi** [comment]
@rmgogogo When you say you are using GCP Notebook API as VPC-SC control plane; do you just mean that you are using it to proxy web traffic  to the cluster inside the VPC-SC?

**Comment by rmgogogo** [comment]
Summarize the info here for external visibility.

1. Current state: it's in phase-1 and done. Currently we don't have plan/resource to continue to phase-2.

2. Currently it is using 'AI Platform Notebooks API' VPC Service Control. So when defining VPC Service Controls, put 'AI Platform Notebooks API' to "Restricted Services", AI Platform Pipelines (Kubeflow Pipelines UI & API) also will be protected, aka inside the perimeter.
![notebook](https://user-images.githubusercontent.com/3444479/82855937-4eadf200-9f3f-11ea-8b11-d7dce01863ee.png)

We originally plan to provide a new item here represents AI Platform Pipelines but the plan got hold for now.

**Comment by rmgogogo** [comment]
@jessiezcc @karthikv2k
