### ISSUE TITLE
Creating Pipeline with duplicate name fails in UI with 500

### ISSUE THREAD

**Issue by rmgogogo** [kubeflow/pipelines#3353]
### What steps did you take:
Creating Pipeline with duplicate name fails in UI with 500

### What did you expect to happen:
Either allow create pipeline with same name or provide better msg.

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

KFP version: 

KFP SDK version: 

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by Bobgy** [comment]
This is expected behavior, but we can improve on error message I think. (in fact every api call needs some improvement on error message)
