### ISSUE TITLE
Stop/kill queued Dataflow job upon pipeline termination

### ISSUE THREAD

**Issue by yantriks-edi-bice** [kubeflow/pipelines#3364]
### What steps did you take:

Launched a TFX pipeline using the KubeflowDagRunner with one component using Dataflow to transform the data. Component was configured to optimize cost using --flexrs_goal=COST_OPTIMIZED which apparently queues the job for up to 6 hours. 

### What happened:

Terminating the Kubeflow pipeline left the Dataflow job active.

### What did you expect to happen:

Stop the launched/queued Dataflow job.

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

Bundled with Kubeflow on GCP. Then upgraded via pip in Kubeflow notebook.

KFP version: 

ca58b22

KFP SDK version: 

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug
 /area backend
 /area sdk

**Comment by numerology** [comment]
Hi @yantriks-edi-bice thanks for reporting!

Yes the invocation for other remote services won't be automatically canceled if the pipeline is terminated. However in KFP SDK we have [exit handler](https://github.com/kubeflow/pipelines/blob/master/samples/core/exit_handler/exit_handler.py) designed for this, which will be invoked if the pipeline succeeds/fails/terminates. So it's very suitable for such garbage collection task.

The current problem is that exit handler is not compatible with TFX pipeline, yet. Though I think it's a reasonable ask to bring such GC functions into TFX.

@neuromage @Ark-kun WDYT?

**Comment by numerology** [comment]
> which will be invoked if the pipeline succeeds/fails/terminates

Sorry for the back-n-forth. Manual termination does not invoke exit handler either. It seems like we'll need to investigate if there's a better way to do GC for manual termination.

**Comment by Ark-kun** [comment]
> the invocation for other remote services won't be automatically canceled if the pipeline is terminated

Kubernetes has sends a signal to the containers in a pod and waits for several seconds before actually terminating them.

KFP's GCP components already support graceful termination and cancel the job they wait for.

**Comment by neuromage** [comment]
> The current problem is that exit handler is not compatible with TFX pipeline, yet. Though I think it's a reasonable ask to bring such GC functions into TFX.
> 
> @neuromage @Ark-kun WDYT?

I think this is a nice idea. It sounds like a good issue to file and track in the tensorflow/tfx repository as well, since most likely, this will need to be implemented there as well.

**Comment by numerology** [comment]
> KFP's GCP components already support graceful termination and cancel the job they wait for.

That's great. I think it'll be nice if we have something similar in TFX pipeline.

**Comment by Ark-kun** [comment]
> I think it'll be nice if we have something similar in TFX pipeline.

Here is the code, BTW: https://github.com/kubeflow/pipelines/blob/0e0f84c6970bff89c57516678f2bc839e03f1800/components/gcp/container/component_sdk/python/kfp_component/core/_kfp_execution_context.py#L52

It's more complicated than it could be because it tries to distinguish user termination from system termination (for example when the pod is preempted). The code only cancels the job if the user terminates the workflow.
