### ISSUE TITLE
pipeline python functions don't work with functools.wraps

### ISSUE THREAD

**Issue by alan-krumholz** [kubeflow/pipelines#3367]
### What steps did you take:
I'm authoring my pipelines using the kfp python SDK.
I wanted to create a function wrapper (using functools.wraps) so that I don't have to add the exit_handler logic to all of my pipelines.
I can build my pipeline fine using such wrapper, but then KFP thinks my pipeline doesn't have any arguments when I  load it (which isn't true)
I think the  wrapper is messing up the data the pipeline compiler gets. I assumed the pipeline compiler would know how to handle functools.wraps the same way docstring does, but it doesn't seem to be the case

### What happened:
KFP thinks my pipeline doesn't have any arguments 
### What did you expect to happen:
KFP knows about my pipeline arguments 
### Environment
How did you deploy Kubeflow Pipelines (KFP)?
Tried running pipeline in both a KF UI deployment and a KFP standalone deployment (both in GCP)

KFP version: Tried on both 812ca7f ( KF UI deployment) and on ca58b22 (standalone KFP)

KFP SDK version: 0.3.0

### Anything else you would like to add:
Here is some code so you can try this out. If you run as is, the pipeline will add the exit handler however, the resulting pipeline doesn't expose any arguments to be modified. If you comment out the `@exit_decorator` then the pipeline exposes the argument (but obviously doesn't add the exit handler) 

```
from functools import wraps
from kfp import components
from kfp import compiler
from kfp import dsl 
from kfp import gcp

def print_comp(
    a:str) -> str:
    print(a)
    return(a)

components.func_to_container_op(
    print_comp,
    output_component_file = 'my_comp.yaml',
    base_image = 'python:3.6.7')


def exit_decorator(f):
    @wraps(f)
    def wrapper(*args, **kwds):
        exit_handler = components.load_component_from_file(
            'my_comp.yaml')
        exit_task = exit_handler(
            '{{workflow.status}}')

        with dsl.ExitHandler(exit_task):
            f(*args, **kwds)

    return wrapper 

@dsl.pipeline(
        name='My Pipeline',
        description='This is a test pipeline')
@exit_decorator
def my_pipe(
    arg1 = 'test'):

    my_comp = components.load_component_from_file(
        'my_comp.yaml')
    my_comp(arg1)

compiler.Compiler().compile(
        my_pipe,
        'my_pipe.tar.gz')
```

/kind bug
/area sdk

**Comment by Ark-kun** [comment]
The root issue is that `inspect.getfullargspec` does not support `@wraps`.
I'll try to switch the compiler to use something else.

**Comment by alan-krumholz** [comment]
@Ark-kun 
Seems like `inspect.signature` should do the trick:
```
inspect.getfullargspec(my_pipe)
```

> FullArgSpec(args=[], varargs='args', varkw='kwds', defaults=None, kwonlyargs=[], kwonlydefaults=None, annotations={})

```
inspect.signature(my_pipe)
```

> <Signature (arg1='test')>

**Comment by alan-krumholz** [comment]
Hi @Ark-kun,
We were wondering if you guys been able to make progress on these?

This will help us make all our pipelines code cleaner and easier  to maintain :)

Thanks!
