### ISSUE TITLE
Support multi-platform storages for Tensorboard 

### ISSUE THREAD

**Issue by IronPan** [kubeflow/pipelines#337]
Currently tensorboard pod mounts the GCP service accounts and can access to GCS. 
https://github.com/kubeflow/pipelines/blob/24d69cbb81f60307f5807a4c2129dab493ce52f4/frontend/server/k8s-helper.ts#L46-L79
The credential should be a configurable parameter that user specifies, to read data from various storage, S3, PV, etc.

**Comment by Jeffwan** [comment]
@IronPan 

Any idea how could we improve this manifest? The most straightforward way is check logdir protocol? 
1. for gcs, s3 and minio, pod can mount cloud provider specific environment and secrets
2. for local disk, we need pvc name and mountPath?

**Comment by sarahmaddox** [comment]
@IronPan  Can we close this issue, after the merge of the above PRs? We have a note in the docs that we can remove when this issue and https://github.com/kubeflow/pipelines/issues/1700 are closed.

**Comment by IronPan** [comment]
@sarahmaddox thanks! close it for now
