### ISSUE TITLE
Permission control for UploadPipeline/RunPipeline/Viewer

### ISSUE THREAD

**Issue by rmgogogo** [kubeflow/pipelines#3375]
Permission control for UploadPipeline/RunPipeline/Viewer.

UploadPipeline: more used by CI/CD
RunPipeline: used by other system/trigger/admin
ViewPipeline: used by users

It's better we can handle it without depends on Multi-user features. 
Option-1. One quick options is just depends on Workload Identity.
Option-2. Gateway outside of KFP to control it.

/kind feature
/area backend
/priority P1

**Comment by Bobgy** [comment]
@rmgogogo Thanks for the idea!
A quick feedback is, the template is specific for bugs, recommend not using it for feature requests.

**Comment by Bobgy** [comment]
> Option-1. One quick options is just depends on Workload Identity.

I don't understand, workload identity is used to control IAM for GCP resources. How can we add these to it?

I think I need more explanation about the context. What's typical scenario for such a need, is it for separating pipeline UI view/run/upload permissions?

I think the prerequisite for any authorization policy is to be able to verify who the user is. So we need an authentication step first. Are you thinking about letting inverse proxy pass user email first?

**Comment by rmgogogo** [comment]
Please ignore option-1. Yuan is right, WI is not related with it as the permission check happens before user workload. It should be tested before author works.

Option-1 can be changed to "not depends on whole multi-user ready" but pass in user email to KFP world and then ACL it. I didn't deeply think on it yet. Let's discuss in next meeting and dump notes here and feel free to leave comments anytime when have ideas.

**Comment by Bobgy** [comment]
Sounds good, let's follow up later

**Comment by rmgogogo** [comment]
(Arikato may already working on it)
