### ISSUE TITLE
[Standalone] env/gcp manifest should support workload identity

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#3377]
https://github.com/kubeflow/pipelines/tree/master/manifests/kustomize/env/gcp

part of https://github.com/kubeflow/pipelines/issues/1691#issuecomment-568991297

**Comment by rmgogogo** [comment]
MKP side here:
https://github.com/kubeflow/pipelines/issues/3392

**Comment by Bobgy** [comment]
@rmgogogo Can you link related issue/PRs here? I think we can close, is that right?

**Comment by rmgogogo** [comment]
yes
