### ISSUE TITLE
Tensorboard is very slow when running a PCA visualization 

### ISSUE THREAD

**Issue by daikeshi** [kubeflow/pipelines#3380]
### What steps did you take:
[A clear and concise description of what the bug is.]
Train a ML model and launch the tensorboard viewer from KFP UI 

### What happened:
PCA visualization on tensorboard viewer takes forever, but when I run the same tensorbaord on my laptop it takes only a few seconds.

### What did you expect to happen:
PCA visualization should run

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

KFP is deployed via Kubeflow

KFP version: 
1.40.0
KFP SDK version: 
1.40.0

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]
Tensorboard viewer pod is launched by viewer controller, and I don't see any resource request is specified (https://github.com/kubeflow/pipelines/blob/578e8231d01074b9dbe40ace1db8cc444a6a1bd8/backend/src/crd/controller/viewer/reconciler/reconciler.go#L161). 

I wonder if that's related. If so, is it possible to make it configurable in the deployment or on the UI.  

/kind bug

**Comment by Bobgy** [comment]
@daikeshi sorry for late reply.

This seems an interesting problem. Can try adjusting tensorboard deployment in the cluster directly and see if can fix your problem?

I think missing `resource request` is a common problem with KFP deployments, (and it's hard to  address from OSS side, we need to make them configurable)

**Comment by daikeshi** [comment]
Thanks, @Bobgy! Yes, we can adjust individual tensorboard viewer deployment. I was thinking if it's possible that the resource request can be configured on UI along with the tensorflow version. Current version on KFP UI is not very powerful, a lot of people end with running tensorboard cli locally.

**Comment by Bobgy** [comment]
@daikeshi Thanks for the input. I asked for trying with changing the deployment was because I wanted to make sure resource request was the correct fix.

We can improve on extra options provided for sure. A clear summarization of which options are often used and why will be a great starting point for us.

**Comment by Bobgy** [comment]
@daikeshi any updates? Was resource request able to solve the issue you met?

**Comment by daikeshi** [comment]
@Bobgy I think so, but our cluster is currently on multiuser milestone one version, so tensorboard viewer is temporarily disabled and our users launch it through their own local dev env. I'll revisit it after we upgrade the cluster to multiuser milestone two.

**Comment by Bobgy** [comment]
Thanks for confirmation!
Let's keep this open.
