### ISSUE TITLE
GCP Pipeline Authentication Issue

### ISSUE THREAD

**Issue by markmirch** [kubeflow/pipelines#3381]
### What steps did you take:
Using a sample notebook: https://github.com/kubeflow/pipelines/tree/master/components/gcp/bigquery/query

Set up Kubeflow 1.0.0 installation using the UI deployer (https://deploy.kubeflow.cloud/)
Created a new notebook with the image: gcr.io/kubeflow-images-public/tensorflow-1.15.2-notebook-cpu:1.0.0
-- including the "add gcp credential" configuration option

Cloned the pipelines repo, executed each cell in the notebook, on the run of the experiment I get the following error:

google.api_core.exceptions.Unauthorized: 401 GET 
https://www.googleapis.com/bigquery/v2/projects/{{PROJECT_ID}}/jobs/query_3d8702cd20bed0786c2c1bf0b6ef87ce?projection=full&location=US
: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
https://developers.google.com/identity/sign-in/web/devconsole-project
.

(substituted the PROJECT_ID)
 
### What happened:
The one-component pipeline fails to execute due to the authentication issue and stops

### What did you expect to happen:
The pipeline succeeds and is able to authenticate to fetch data from BigQuery

### Environment:

BQ API is enabled

How did you deploy Kubeflow Pipelines (KFP)?
https://deploy.kubeflow.cloud

KFP version:
Build commit: ca58b22

KFP SDK version:
Name: kfp
Version: 0.3.0
Summary: KubeFlow Pipelines SDK

### Anything else you would like to add:
/kind bug

**Comment by markmirch** [comment]
In case anyone else runs into this, explicitly specifying the auth on the op fixes this:

job_config=job_config)

becomes

job_config=job_config).apply(gcp.use_gcp_secret('user-gcp-sa'))

**Comment by Bobgy** [comment]
And the fix will be released in Kubeflow 1.0.2 soon
https://github.com/kubeflow/kubeflow/issues/4803
