### ISSUE TITLE
show  '--scopes cloud-platform' cluster creation option for CLI install of hosted kfp?

### ISSUE THREAD

**Issue by amygdala** [kubeflow/pipelines#3382]
With these instructions for command-line installation of hosted kfp:
https://github.com/kubeflow/pipelines/blob/master/manifests/gcp_marketplace/cli.md
we should probably include the option of adding something like `--scopes cloud-platform` to the cluster creation command.  Otherwise, the story gets inconsistent and confusing.  WDYT?

**Comment by Bobgy** [comment]
@rmgogogo I don't think the cli.md documentation is for user facing. It was more internal debugging.

Shall we remove it/hide it with some warning?

**Comment by amygdala** [comment]
We've had some customers specifically ask about this option so as to automate the process (deploy programmatically).  So I don't believe we should remove this info.

**Comment by Bobgy** [comment]
/cc @rmgogogo 
I believe https://www.kubeflow.org/docs/pipelines/installation/standalone-deployment/ is our answer to deploy programmatically. It is the same (almost) as AI Platform Pipelines.

The only missing feature right now is lack of setup for default bucket.

I think @rmgogogo is actively working on a standard CLI installation path for AI Platform Pipelines based on standalone. That will be our recommendation for GCP as soon as it's ready.

Maybe not all I heard is accurate, @rmgogogo should know the best about these.

**Comment by rmgogogo** [comment]
yes, I'm refactory the CLI path now.
Please expected big changes related CLI codes/docs in upcoming weeks. This one is included.

**Comment by rmgogogo** [comment]
more info: 

in CLI path, we will provide 3 options related with authentication.
- workload identity (preferred)
- application default credential
- scopes=cloud-platform

**Comment by amygdala** [comment]
I assume this should remain open...
