### ISSUE TITLE
--scope cloud-platform at nodepool level and not cluster level?

### ISSUE THREAD

**Issue by pselden** [kubeflow/pipelines#3383]
### What steps did you take:
1. Created a private GKE cluster with default oauth scopes, and then created a nodepool on it and granted that nodepool the cloud-platform oauth scope.
2. Attempted to use the GKE marketplace to deploy Kubeflow Pipelines to that cluster

### What happened:
1. Got a message "Insufficient oauth scopes" and it would not allow me to select that cluster to install Kubeflow Pipelines.

### What did you expect to happen:
1. The cluster-level oauth-scope is really just a template for what happens when new nodepools are created, so I would have expected that since I created a node pool with that scope manually, the installer would have allowed it to proceed.

### Environment:
Google cloud platform.

How did you deploy Kubeflow Pipelines (KFP)?
GCP Marketplace.

**Comment by Bobgy** [comment]
@rmgogogo for removing that restriction.

In the meantime, I think you should deploy following https://www.kubeflow.org/docs/pipelines/installation/standalone-deployment/. AI platform pipelines deploys the same thing as standalone.

**Comment by gyant** [comment]
I'm having issues with this as well using the deployment tool in a shared vpc environment.

Currently in the process of running a sanity check on this.

Here's what I've tried so far:

1. Full API Scope access on the service account bound to the GKE nodepool.
2. All Project Service APIs enabled on both the service and host project.
3. `roles/owner` for the k8s service accounts and the gke node pool service account in both projects.

Still no luck.

**Comment by Bobgy** [comment]
@gyant It's not very likely we can fix marketplace permission checking shortly.
Would you mind installing via https://www.kubeflow.org/docs/pipelines/installation/standalone-deployment/? AI platform pipelines deploys the same thing as standalone.

/assign @rmgogogo

**Comment by rmgogogo** [comment]
MKP checkes the first node-pool and then find it doesn't have the required permission. It's the expected behavior. If you delete the first node-pool I think it can be selected. Or you create the cluster with the scope since the begining.

+1 with Bobgy that standalone is suggested for most flexibility.
