### ISSUE TITLE
Does it make sense to add volumeMounts and volumes to component specification?

### ISSUE THREAD

**Issue by ethanyanjiali** [kubeflow/pipelines#3385]
It seems like the only way to add persistent volume to a container is through the pipeline python sdk. I'll need to either declare pvolumes when create a ContainerOp, or use `add_pvolumes` method on an existing ContainerOp. Since  I created most of my pipeline components through the yaml specification approach, I'm wondering if it makes sense to add volume there.

My first impression is that yaml specification is used for sharing, but usually resources like PV are not shareable, so we should define them in the pipeline code where we use it. Is this the reason that we don't have such option to configure volume in Component Specification? Would love to see how does the team think about it.

**Comment by derekhh** [comment]
I was under the impression you can use [volumeClaimTemplates](https://github.com/argoproj/argo/blob/f33624d67d0cf348dcdece46832081346c26bf80/examples/volumes-pvc.yaml#L11) in KFP YAML too.

**Comment by Ark-kun** [comment]
>My first impression is that yaml specification is used for sharing, but usually resources like PV are not shareable, so we should define them in the pipeline code where we use it. Is this the reason that we don't have such option to configure volume in Component Specification?

This is correct. The component specification is designed to be portable and environment-independent. This is why cluster-specific options like volumes or secrets are not supported.

BTW, I have a PR pending that enables using volumes for all artifact passing: https://github.com/kubeflow/pipelines/pull/3371 This will allows you to store all intermediate data in a shared voume.

**Comment by Ark-kun** [comment]
Have you tried to make pipeline not use volumes? KFP has data passing support where you do not need to manually mount or download the data.

Please check the following two tutorials: https://github.com/kubeflow/pipelines/blob/fd5778d/samples/tutorials/Data%20passing%20in%20python%20components.ipynb https://github.com/Ark-kun/kfp_samples/blob/ae1a5b6/2019-10%20Kubeflow%20summit/106%20-%20Creating%20components%20from%20command-line%20programs/106%20-%20Creating%20components%20from%20command-line%20programs.ipynb

`declare pvolumes when create a ContainerOp` or use add_pvolumes

Just note that `pvolumes`, `add_pvolumes` and `VolumeOp` are community contrib features and have some portability and support implications. The officially supported methods are `add_volume` and `add_volume_mount`.

**Comment by elikatsis** [comment]
@ethanyanjiali hi!

Based on various samples and use cases, I believe that, ideally, your component should define (and maybe parse) input/output paths as input arguments.
That way, the path can either be `gs://....`, `/my/mount/path`, or anything you desire. Then, you will be able to decide on the fly (when writing the DSL) what to use.

So for the case of a local path usage, you should have a volume mounted on your step (note that PVC names may contain pipeline parameters).
