### ISSUE TITLE
[Question] Open port in Kubeflow pipeline op

### ISSUE THREAD

**Issue by msalvaris** [kubeflow/pipelines#3386]
This is more of a question than anything else. I am using Dask within a Kubeflow pipeline and would like to sometimes open a port to the scheduler so that I can view the Dask dasboard. Is there a way to forward ports from a container running in the pipeline?

**Comment by Bobgy** [comment]
How do you deploy KFP?
If you are using Kubeflow Deployment, I think you can use the same approach as how other services are exposed.

Your pipeline should create a `service`, a `VirtualService` (it's istio specific) to expose it.

Examples:
* service: https://github.com/kubeflow/manifests/blob/master/pipeline/pipelines-ui/base/service.yaml
* virtual service: https://github.com/kubeflow/manifests/blob/master/pipeline/pipelines-ui/overlays/istio/virtual-service.yaml

Does this answer your question?

I think it's not very related to Kubeflow Pipelines.
/close
