### ISSUE TITLE
Managed Storage (CloudSQL/GCS-Minio) - let standalone installation support Workload Identity

### ISSUE THREAD

**Issue by rmgogogo** [kubeflow/pipelines#3391]
Current GCP standalone manifest still is using ADC for CloudSQL and GCS-minio. To fully support workload identity, we need to change the manifest. Otherwise, user has to configure both App Default Credential and Workload Identity.

MKP part of work is tracked in another ticket. Here this is for standalone.

**Comment by Bobgy** [comment]
Hi @rmgogogo,
this is dup of https://github.com/kubeflow/pipelines/issues/3377
/close
