### ISSUE TITLE
Support CloudSQL/GCS-Minio in Standalone CLI & MKP/Hosted 

### ISSUE THREAD

**Issue by rmgogogo** [kubeflow/pipelines#3399]
Current codebase is on an interim state. We need additional changes to unlock it.
(1) MLMD manifest requires changes to connect with CloudSQL.
(2) Minio requires changes together with Workload Identity.
(3) CloudSQL requires light changes to work together with Workload Identity.

Same changes need to be applied to both Standalone manifest and MKP/Hosted manifest.

**Comment by bharathkkb** [comment]
@rmgogogo I was looking into this for the TF module and I saw this issue.
Will this issue enable using WI instead of using a service account in [here](https://github.com/kubeflow/pipelines/tree/master/manifests/kustomize/env/gcp)

**Comment by Bobgy** [comment]
Yes, that's part of this

**Comment by rmgogogo** [comment]
Yes. I may try to extend it to also support other auth-mode (e.x. Application Default Credential).

For status of this issue. It's done in gcp_marketplace.
For the standalone (manifest/kustomize), it's not done yet and WIP.

**Comment by Bobgy** [comment]
@rmgogogo Can you link related PRs here and can we consider this done?

**Comment by Ark-kun** [comment]
What is the status of "Support GCS-Minio in Standalone CLI & MKP/Hosted"?
Does this feature re-point the [workflow-configmap](https://github.com/kubeflow/pipelines/blob/master/manifests/kustomize/base/argo/workflow-controller-configmap.yaml) from Minio to GCS when installed from the Marketplace? 
I think this is a pretty important feature. The Minio volume is pretty small and we want the users to be able to pass bigger datasets between steps.

**Comment by rmgogogo** [comment]
It's in 0.5.1. (I remember I close this one, maybe we have two ticket on it)

For CLI, it's tracked in another ticket. Here close this one.

**Comment by rmgogogo** [comment]
> What is the status of "Support GCS-Minio in Standalone CLI & MKP/Hosted"?
> Does this feature re-point the [workflow-configmap](https://github.com/kubeflow/pipelines/blob/master/manifests/kustomize/base/argo/workflow-controller-configmap.yaml) from Minio to GCS when installed from the Marketplace?
> I think this is a pretty important feature. The Minio volume is pretty small and we want the users to be able to pass bigger datasets between steps.

yes, we originally call it "managed storage" (use CloudSQL/GCS for out-cluster storage). It's a feature done before but we didn't enable it for many other auth reasons.
