### ISSUE TITLE
GCS is not accessible from pipeline components

### ISSUE THREAD

**Issue by nihil0** [kubeflow/pipelines#3402]
### What steps did you take:

On executing the sample, the `gcs-download` step of the pipeline fails. A screenshot of the error message is attached. The input to this pipeline is a bucket which I have full control over, with the `shakespeare1.txt` file uploaded.

![Screenshot 2020-03-31 at 14 30 12](https://user-images.githubusercontent.com/2157667/78007762-59437500-735c-11ea-86f0-936eaa83b16e.png)

### What happened:

Unexpected error when downloading from GCS in sample pipelines

### What did you expect to happen:

Pipeline should execute successfully

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

CLI deployment on GCP

KFP version: 

`ca58b22`

KFP SDK version: 

`0.3.0`

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

// /area backend

**Comment by nihil0** [comment]
This might have something to do with Workload identity not being available in Kubeflow Pipelines when installed as bart of Kubeflow. I don't know any workarounds for this. This issue might be related: #2773

**Comment by Bobgy** [comment]
You are right, that's a duplicate of https://github.com/kubeflow/pipelines/issues/2773.
The fix will be released in Kubeflow 1.0.2
