### ISSUE TITLE
URLs in Artifact viewer do not display underscores right "_"

### ISSUE THREAD

**Issue by paveldournov** [kubeflow/pipelines#3424]
In the artifact pane the URLs shown for Metadata artifacts do not display underscores and instead turn the text to italic. When the user copies the URL - it gets copied without the underscores and thus does not point to a valid file.

![image](https://user-images.githubusercontent.com/4884947/78301345-c6d2db00-74ed-11ea-93a3-77e476e9bd99.png)

![image](https://user-images.githubusercontent.com/4884947/78301305-ba4e8280-74ed-11ea-8db0-0898e0dfd265.png)

**Comment by numerology** [comment]
The culprit is that underscore is not properly escaped when TFX image writing the markdown string

See [1]

[1] https://github.com/tensorflow/tfx/blob/master/tfx/orchestration/kubeflow/container_entrypoint.py#L218

**Comment by Bobgy** [comment]
There may be other formatting conflicts later, I think instead of escaping, we should wrap data with `\`

**Comment by rmgogogo** [comment]
if quick fix, we may put it to OSS 1.0

**Comment by Bobgy** [comment]
I'm leaning avoid escaping underscore in UI, adding hack on top of a proper markdown parser is fragile.

e.g. how do we not escape underscores that are already escaped? how many other corner cases there are?

**Comment by Bobgy** [comment]
I think the best fix is to render execution detail page as a tab and let tfx side remove the markdown. Execution detail page has all the information in the best accessible form.

**Comment by Bobgy** [comment]
@numerology did you fix the issue? With https://github.com/kubeflow/pipelines/pull/3457 we may also remove the markdown. (but we can keep it for a while before people can upgrade KFP installation).

**Comment by numerology** [comment]
> @numerology did you fix the issue? With #3457 we may also remove the markdown. (but we can keep it for a while before people can upgrade KFP installation).

It should be fixed in https://github.com/tensorflow/tfx/commit/3ea79f9bd9fcc903b8a7eb890fd33c984af4366e

**Comment by Bobgy** [comment]
@numerology thanks!
let's close this then
/close
