### ISSUE TITLE
[Backend][Multi-user] Access Pipeline SDK with Dex Auth enabled

### ISSUE THREAD

**Issue by dagondagon666** [kubeflow/pipelines#3426]
### What did you expect to happen:

I want to access the Pipeline API but right now I'm blocked by the Dex Auth. Any idea where could I get the bearer token for it?

### Environment:

kfctl_istio_dex.v1.0.1.yaml

How did you deploy Kubeflow Pipelines (KFP)?

kfctl_istio_dex.v1.0.1.yaml

/kind bug
/area backend
/area api

**Comment by Bobgy** [comment]
@dagondagon666 The other issue is correct, it's a kubeflow problem.

/close
