### ISSUE TITLE
TFX Cache Behavior (BQ + Dataflow + TFX + KFP)

### ISSUE THREAD

**Issue by rmgogogo** [kubeflow/pipelines#3432]
It seems an issue (or wrong doc) in TFX Template. Here log a ticket to well track whole integration to make sure KFP user is happy on the cache behavior (not the KFP-cache worked by Rui, we need doc to detail these two cache's difference).

Repro steps from Pavel.

1. Run the pipeline with BQ example gen running in-cluster (no dataflow)
2. Observe it succeed
3. Change the pipeline config to use Dataflow (for the example gen, data validation, etc)
4. Build and update the pipeline in the cluster (usign the same name)
5. Run the pipeline, observe it succeeding. 
6. Look at the Dataflow jobs. None found.
7. Turn off the cache. 
8. Rebuild and update the pipeline in cluster. 
9. Run the pipeline, see the pipeline creating Dataflow job (expected). 

The bug is at step #6. When the beam config changed, the cache should have been invalidated.

**Comment by rmgogogo** [comment]
We also need to make sure KFP side's Cache-server can well work with TFX SDK and well document the common and diff part.

**Comment by Ark-kun** [comment]
> We also need to make sure KFP side's Cache-server can well work with TFX SDK

Currently the KFP's execution cache excludes all TFX pods.

**Comment by Bobgy** [comment]
/assign @numerology 
Not sure, can you own this?

**Comment by numerology** [comment]
> Not sure, can you own this?

Of course.

> The bug is at step #6. When the beam config changed, the cache should have been invalidated.

The problem is that `beam_pipeline_args` is not treated as execution properties (or custom properties). In fact, semantically, it's not something that has an impact to the actual output artifacts so the cache will be used if only `beam_pipeline_args` is changed. 

Let's follow up with TFX team to see if they wish to change this logic.
