### ISSUE TITLE
Dataflow component crash only when scheduling jobs

### ISSUE THREAD

**Issue by dfeldell** [kubeflow/pipelines#3449]
Hi,

When using this component to run Dataflow jobs in a pipeline: 
https://raw.githubusercontent.com/kubeflow/pipelines/master/components/gcp/dataflow/launch_python/component.yaml

The pipeline will crash with the following error:
_This step is in Error state with this message: failed to save outputs: path /tmp/outputs/MLPipeline_UI_metadata/data does not exist (or /tmp/outputs/MLPipeline_UI_metadata/data is empty) in archive /argo/outputs/artifacts/mlpipeline-ui-metadata.tgz_

This only happens when the job is scheduled but not when I run the pipeline manually. 

Anyone know what is causing this?

kubeflow 1.0
1.14.10-gke.32

**Comment by Bobgy** [comment]
@chensun @jingzhang36 
I vaguely remember one of you fixed a similar issue. Do you have any context?
