### ISSUE TITLE
Support mutl-platform storage for kaniko

### ISSUE THREAD

**Issue by IronPan** [kubeflow/pipelines#345]
Currently kaniko pod mounts the GCP service accounts so it can access to GCP API.

https://github.com/kubeflow/pipelines/pull/343

We should consider make this a configurable setting so people can switch to non GCP stack as they want.

**Comment by IronPan** [comment]
see related feature request https://github.com/kubeflow/pipelines/issues/641

**Comment by gaoning777** [comment]
duplicate of https://github.com/kubeflow/pipelines/issues/1700
