### ISSUE TITLE
Argument type "String" is incompatible with the input type "GCPProjectID"

### ISSUE THREAD

**Issue by salexashenko** [kubeflow/pipelines#3452]
### What steps did you take:
I am going through this notebook:

https://github.com/kubeflow/pipelines/blob/master/samples/tutorials/mnist/04_Reusable_and_Pre-build_Components_as_Pipeline.ipynb

 Everything is fine until submitting a pipeline run session. When I run the following cell:
```
experiment_name = 'minist_kubeflow'

arguments = {"model_path":"mnist_model",
             "bucket":GCS_BUCKET}

run_name = pipeline_func.__name__ + ' run'

# Submit pipeline directly from pipeline function
run_result = client.create_run_from_pipeline_func(pipeline_func, 
                                                  experiment_name=experiment_name, 
                                                  run_name=run_name, 
                                                  arguments=arguments)
```

### What happened:

I get the following exception:

`InconsistentTypeException: Incompatible argument passed to the input "project_id" of component "Deploying a trained model to Cloud Machine Learning Engine": Argument type "String" is incompatible with the input type "GCPProjectID"`

### What did you expect to happen:
I expected a pipeline run to be scheduled.
### Environment:

How did you deploy Kubeflow Pipelines (KFP)?
Google AI Platform Pipelines

KFP version: kfp-0.3.0

KFP SDK version:
 kfp                                0.3.0              
kfp-server-api                     0.3.0      

### Anything else you would like to add:
I am running the notebook in Google AI Notebooks, and my Kubernetes cluster is running a Google AI Pipeline

/kind bug

**Comment by Ark-kun** [comment]
The contributed MNIST tutorial seems to have some issues. We'll try to address them
Meanwhile, please try fixing the pipeline signature:
```
def mnist_reuse_component_deploy_pipeline(
    project_id: "GCPProjectID" = PROJECT_ID,
```
