### ISSUE TITLE
Kubeflow Pipelines without Google Cloud Storage

### ISSUE THREAD

**Issue by tech348712013870132** [kubeflow/pipelines#3453]
Is it possible to replace the usage of Google Cloud Storage buckets with an alternative on-premise solution so that it is possible to run e.g. Kubeflow Pipelines completely in-depended from the Google Cloud Platform?

**Comment by Ark-kun** [comment]
Are you sure Kubeflow Pipelines uses GCS buckets by default?
As far as I know, KFP is platform-independent.
Can you please provide specific examples?

**Comment by tech348712013870132** [comment]
I mean e.g. at this point (screenshot) if you intend to create a new run of a pipeline.
The default value of the pipeline-root input field is **gs://your-bucket/...**

Is it possible to use another storage backend at this point?
I would prefer something open-source + on-premise host-able, independent
of GCS..

Screenshot:
<img width="638" alt="Screenshot 2020-04-07 at 02 48 43" src="https://user-images.githubusercontent.com/45794753/78618289-51af2f00-787a-11ea-9dd9-a2582595cb52.png">

**Comment by numerology** [comment]
> Is it possible to use another storage backend at this point?

The storage backend is not part of KFP system. It depends on how the business logic is written for the components/samples.

The pipeline you mentioned here, for example, is the TFX taxi pipeline. Under the hood it uses tf.io.gfile module therefore IMO it should be able to run on other storage backend (S3 etc.) but I did not validate myself.

Briefly speaking, the IO logic within the component, which determines the types of storage backend supported, is transparent to KFP itself.

**Comment by tech348712013870132** [comment]
@numerology Thank you for your very great answer.

Know I understand this better :)

**Comment by Bobgy** [comment]
/close
Looks like question answered.

Do we need to add more documentation about this? If yes, please reopen
