### ISSUE TITLE
[Metadata Writer] Consistency with tfx

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#3462]
There have been two issues when implementing https://github.com/kubeflow/pipelines/pull/3457.

* kfp_pod_name custom property is not available in metadata writer (it is used to connect a kfp pod with an execution in mlmd, very useful in UI)
* a run's context type is `KfpRun` in metadata writer, but a `run` in tfx

Can we increase consistency with tfx, so UI can easily handle both logic?

**Comment by Ark-kun** [comment]
> * kfp_pod_name custom property is not available in metadata writer (it is used to connect a kfp pod with an execution in mlmd, very useful in UI)

Adding this would be useful.

>a run's context type is KfpRun in metadata writer, but a run in tfx

I'm concerned about possible ContextType conflicts between the two.

**Comment by Bobgy** [comment]
@Ark-kun Thanks!

> I'm concerned about possible ContextType conflicts between the two.

I see, I guess if two libraries create the same context type, then it's really hard to handle context type schema upgrade/conflict, is that right?

It's okay, UI can query two types instead too.

**Comment by Bobgy** [comment]
Adding as p1, but you can adjust

**Comment by Ark-kun** [comment]
Made a PR to include the pod name.
