### ISSUE TITLE
Tests that verify that pipelines successfully log metadata

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#3481]
Currently there are no integration tests that verify that when the pipelines run, the executions, artifacts and contexts are successfully logged.
It might be useful to add a test for this feature.

**Comment by Bobgy** [comment]
Would UI e2e test help?
sounds like coverage to UI metadata integration will also be useful

**Comment by numerology** [comment]
We have one in [tensorflow/tfx](https://github.com/tensorflow/tfx/blob/ac8a421117c0eeed38bab2fd9a4fb7c18b68376f/tfx/orchestration/kubeflow/kubeflow_e2e_test.py#L58)

It sounds not bad to have that in KFP, too

**Comment by neuromage** [comment]
We already have this coverage internally @Ark-kun. Shall we close this issue, or do you think there's insufficient coverage here?

**Comment by numerology** [comment]
> We already have this coverage internally @Ark-kun. Shall we close this issue, or do you think there's insufficient coverage here?

I think @Ark-kun meant that we should have test coverage to verify the metadata writer logs properly.

**Comment by Ark-kun** [comment]
> We already have this coverage internally @Ark-kun. Shall we close this issue, or do you think there's insufficient coverage here?

Is this verified for a pipeline that uses KubeflowDagRunner?

**Comment by numerology** [comment]
> > We already have this coverage internally @Ark-kun. Shall we close this issue, or do you think there's insufficient coverage here?
> 
> Is this verified for a pipeline that uses KubeflowDagRunner?

Yes it is.

**Comment by Ark-kun** [comment]
> Yes it is.

I guess this is on my plate then =)

**Comment by numerology** [comment]
> > Yes it is.
> 
> I guess this is on my plate then =)

I can help as well :) BTW [this](https://github.com/tensorflow/tfx/blob/master/tfx/orchestration/kubeflow/test_utils.py#L369) is the code setting port-forward to talk to MLMD

**Comment by Bobgy** [comment]
/lifecycle frozen

we still need this
