### ISSUE TITLE
Missing fields in upload_pipeline

### ISSUE THREAD

**Issue by omarzouk** [kubeflow/pipelines#3491]
### What steps did you take:
There is no `description` field in the `Client.upload_pipeline` function.
I also tried using `Client._upload_api.upload_pipeline` field but it didn't support it either. It seems this is missing from the `kfp-server-api` despite it working in the UI

### What did you expect to happen:
To be able to submit the fields listed in https://www.kubeflow.org/docs/pipelines/reference/api/kubeflow-pipeline-api-spec/#/definitions/apiPipeline

### Environment:
kfp                      0.4.0          
kfp-server-api           0.3.0   

/kind feature

/area sdk

**Comment by Bobgy** [comment]
@jingzhang36 sounds like we should fix this before 1.0
feel free to adjust

**Comment by jingzhang36** [comment]
The spec at https://www.kubeflow.org/docs/pipelines/reference/api/kubeflow-pipeline-api-spec/#/definitions/apiPipeline is actually for our backend CreatePipeline method, not for upload pipeline method. While CreatePipeline method belongs to our pipeline server, upload pipeline method belongs to a different and separate server. Their parameters are not fully aligned.

So, a couple of things we can do.

(1) If it is possible for you to have your pipeline file available through a url, you can use our  CreatePipeline method, e.g.,

client = kfp.Client(host)
api_url = kfp_server_api.models.ApiUrl(pipeline_file_url)
api_pipeline = kfp_server_api.models.ApiPipeline(
       name='pipeline-' + random_suffix(),
       url=api_url)
pipeline = client.pipelines.create_pipeline(body=api_pipeline)

(2) If it is not possible for you, then we'll use this github issue to track the work update our upload pipeline server interface.

**Comment by omarzouk** [comment]
Thanks for your responses!

@jingzhang36 interesting, I thought it belonged to the upload_pipeline because description works with file uploads in the UI, when I examine the network request I see this `https://XXXXXX.pipelines.googleusercontent.com/apis/v1beta1/pipelines/upload?name=asd&description=test`. I'm wondering what version of the API/Server do they use in the UI?

To answer your question however, I don't think I can have the pipeline file available via a url. Our pipelines need to be private and I would rather not expose any code on a url.

**Comment by jingzhang36** [comment]
@omarzouk The above merged PR should allow you to specify description when uploading pipeline.
