### ISSUE TITLE
Docs to install KFP on AWS

### ISSUE THREAD

**Issue by awcchungster** [kubeflow/pipelines#3496]
### What steps did you take:
[A clear and concise description of what the bug is.]
I followed the Standalone KFP install guide, but it is only for GCP.

### What happened:

It didn't work. 

### What did you expect to happen:

Install KFP standalone.

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

https://www.kubeflow.org/docs/pipelines/installation/standalone-deployment/
KFP version: 

0.4.0
KFP SDK version: 
0.4.0

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by Jeffwan** [comment]
What's the error message do you see? Could you describe more details on "it didn't work"?

**Comment by awcchungster** [comment]
These two lines should be added to the instructions for AWS.

# Patch the ClusterIP UI service to LoadBalancer
kubectl patch service -n kubeflow ml-pipeline-ui --patch '{"spec":{"type":"LoadBalancer"}}'
# Get the UI URL
kubectl get service -n kubeflow ml-pipeline-ui --output json | jq -r ".status.loadBalancer.ingress[0].hostname"

**Comment by Jeffwan** [comment]
@awcchungster 

This is not a blocker. user doesn't have to use LB, This will expose a public endpoint without auth. Does port-forward work for you?

**Comment by awcchungster** [comment]
Both LB or portforward options should be used in the docs so users can understand how to set this up on their own.

**Comment by Ark-kun** [comment]
> It didn't work.

Can you please list the particular error message that you saw.
Thank you.

**Comment by Bobgy** [comment]
Will https://github.com/kubeflow/pipelines/tree/master/manifests/kustomize/env/aws be a good tutorial?

**Comment by Jeffwan** [comment]
@Bobgy Default manifest works for all the platform. https://github.com/kubeflow/pipelines/tree/master/manifests/kustomize/env/aws points to some manifest with deep AWS integration like managed MySQL and artifact store. 

I think if user looks for basic standalone setup, existing https://github.com/kubeflow/pipelines/tree/master/manifests/kustomize#tldr is good enough.

If user looks for customization, then check the link you give. I will work with @eterna2 to backport some of his changes to upstream.

**Comment by Bobgy** [comment]
@Jeffwan I think we need to remove proxy-agent from default manifest and make it truly generic

**Comment by Jeffwan** [comment]
Agree. this may make people confused. Besides that, we need some guidance to tell user how to use port-forward to visit UI for some entry level user as well. I actually see some questions on this.
