### ISSUE TITLE
[UX, MLMD] - Artifacts - grpc-message: no healthy upstream on Windows

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#3500]
### What steps did you take:

Install KFP
Open UX
Run some pipelines
Click on Artifacts in the left nav pane
Click on Executions in the left nav pane

### What happened:

The Executions page is empty and I get erorrs "Error: Failed getting executions: no healthy upstream. Code: 14"
The Artifacts page is empty.

I see the following in the Network browser tool:
```
GET http://localhost:8080/ml_metadata.MetadataStoreService/GetArtifactTypes

Response:
HTTP/1.1 200 OK
X-Powered-By: Express
content-type: application/grpc-web+proto
grpc-status: 14
grpc-message: no healthy upstream
access-control-allow-origin: http://localhost:8080
access-control-expose-headers: custom-header-1,grpc-status,grpc-message
date: Mon, 13 Apr 2020 09:47:41 GMT
server: envoy
connection: close
content-length: 0
```

### Environment:
Docker for Windows

>How did you deploy Kubeflow Pipelines (KFP)?

KFP version: 0.4.0 standalone deployment

/kind bug
/area frontend

P.S. It's also strange that GRPC returns 200 status even on failure.

**Comment by Bobgy** [comment]
`no healthy upstream` usually means a problem with metadata grpc server

Did you try deleting its pod and let it restart?

**Comment by Bobgy** [comment]
Also, I think grpc doesn't use http status code, it will always be 200

**Comment by Ark-kun** [comment]
The logs did not show any errors:

```
kubectl logs --namespace kubeflow  metadata-grpc-deployment-ff8b979bb-vj89h
2020-04-13 01:43:52.290961: I ml_metadata/metadata_store/metadata_store_server_main.cc:238] Server listening on 0.0.0.0:8080
```

Same log after restarting the pod.

**Comment by Bobgy** [comment]
@Ark-kun sent PR to fix this: https://github.com/kubeflow/pipelines/pull/3502

**Comment by Bobgy** [comment]
Shall we consider patch this and rerelease 0.4.0?

**Comment by Ark-kun** [comment]
> Shall we consider patch this and rerelease 0.4.0?

I think we should make a [re]release with the fix.

/cc @rmgogogo @dushyanthsc  @numerology
