### ISSUE TITLE
Better local dev/test experience

### ISSUE THREAD

**Issue by rmgogogo** [kubeflow/pipelines#3503]
1. Easy install KFP core to Minikube or Kind or Docker Desktop.
2. Local easy dev/test for KFP users based on (1).

**Comment by Bobgy** [comment]
I'm not sure this will be useful for all cases.

If the pipeline requries cluster-specific setup or specific permission, local may not be a good way to test.
I think caching will be a key improvement to fast testing iterations already implemented.

Do you think there are any other frictions that make local better than remote? Maybe we should fix them instead.
