### ISSUE TITLE
TestInfra - Use KFP to test KFP

### ISSUE THREAD

**Issue by rmgogogo** [kubeflow/pipelines#3505]
Currently we use bash + Argo etc. to test KFP.
KFP naturally can be a tool to test KFP.
1. long-run cluster installed KFP (also can test upgrade)
2. prow trigger job runs in KFP

**Comment by Bobgy** [comment]
Expand a little bit, we can have:
* A single long-running stable KFP cluster as test orchestrator
* KFP pipelines running in above cluster that provisions additional GKE clusters as test KFP clusters.

Benefits:
* We can dogfood long running KFP cluster and cluster upgrade capabilities in a real use-case.
* KFP pipelines are much easier to maintain than bash scripts
* It will be easier to identify which specific step failed in KFP UI

**Comment by numerology** [comment]
> We can dogfood long running KFP cluster, its scalability and cluster upgradability in a real use-case.

+1 I think it can be also treated as a scale test: how our system scale in the time dimension. That being said, there's already some known issue re: MLMD in this department. As we accumulate many entries in the database the query can be slow and even choke gRPC.

**Comment by rmgogogo** [comment]
> > We can dogfood long running KFP cluster, its scalability and cluster upgradability in a real use-case.
> 
> +1 I think it can be also treated as a scale test: how our system scale in the time dimension. That being said, there's already some known issue re: MLMD in this department. As we accumulate many entries in the database the query can be slow and even choke gRPC.

yes!
/cc Jingzhang36

**Comment by Bobgy** [comment]
/lifecycle frozen

we want to keep investing in this

**Comment by Bobgy** [comment]
I finally get the chance to do this in https://github.com/kubeflow/pipelines/pull/5337.

**Comment by Bobgy** [comment]
TODOs:
* [ ] Configure correct permissions in https://github.com/kubeflow/testing/blob/master/test-infra/kfp/iam/iam.yaml
* [ ] Let #5337 pass the new run KFP on KFP presubmit test
* [ ] Enable test config https://github.com/GoogleCloudPlatform/oss-test-infra/blob/dcb26401364e95b0df512cde5a551d191664f56b/prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml#L187-L189

**Comment by Bobgy** [comment]
Current error message when running the pipeline:

```
+ gsutil cp gs://kfp-ci/b9a845b76d61453f4a390718f08a2b0032802d6f/v2-sample-test/src/context.tar.gz artifact.tar.gz
AccessDeniedException: 403 Insufficient OAuth2 scope to perform this operation.
Acceptable scopes: 
https://www.googleapis.com/auth/cloud-platform
```

I checked permission on the nodepool, the GSA has correct permissions, but the nodepool does not enable all cloudplatform OAuth2 scope as stated in the error message.

**Comment by Bobgy** [comment]
Getting the following error message when config sync is updating nodepool resource:
> KNV2010: unable to create resource: KNV2010: failed to create "container.cnrm.cloud.google.com/v1beta1, Kind=ContainerNodePool", "kfp-ci/kfp-standalone-1-nodepool-v2": Internal error occurred: failed calling webhook "annotation-defaulter.cnrm.cloud.google.com": Post "https://cnrm-validating-webhook.cnrm-system.svc:443/annotation-defaulter?timeout=30s": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0

Upstream issue seems to be https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/335.

We need to upgrade config connector in kf-ci-management, or downgrade the cluster to regular channel (1.18).

**Comment by Bobgy** [comment]
Hmmm, it's not possible to downgrade kubernetes version channel. I can only upgrade config connector.
We may need to consider getting rid of the current management cluster and redeploy one using regular channel.

**Comment by Bobgy** [comment]
> : KNV2010: failed to create "container.cnrm.cloud.google.com/v1beta1, Kind=ContainerNodePool", "kfp-ci/kfp-standalone-1-nodepool-v2": admission webhook "deny-unknown-fields.cnrm.cloud.google.com" denied the request: unknown field "spec.oauthScopes"

I made a mistake, it should be `spec.nodeConfig.oauthScopes`.

**Comment by Bobgy** [comment]
> Error:   KNV2010: unable to update resource: could not patch: admission webhook "deny-immutable-field-updates.cnrm.cloud.google.com" denied the request: the IAMPolicyMember's spec is immutable

One last error unrelated to current changes.

**Comment by Bobgy** [comment]
Verified new nodepool is created `kfp-standalone-1-nodepool-v2`

**Comment by Bobgy** [comment]
> gsutil ls
> AccessDeniedException: 403 kfp-standalone-1-vm@kfp-ci.iam.gserviceaccount.com does not have storage.buckets.list access to the Google Cloud project.

We also need bucket list permission.

**Comment by Bobgy** [comment]
> kfp_server_api.exceptions.ApiException: (401)
Reason: Unauthorized

I'm getting this error when using KFP client to talk to the same endpoint.

**Comment by Bobgy** [comment]
> "message": "kf-ci-v1-prow@kubeflow-ci.iam.gserviceaccount.com does not have storage.objects.create access to kfp-ci/225ed8883cc762b4b5fa3b2dcc574257d66bd6ee/v2-sample-test/src/context.tar.gz."

Another permission issue

**Comment by Bobgy** [comment]
TODOs done, p0 requirements have all been implemented.
See documentation: https://github.com/kubeflow/pipelines/tree/master/v2/test
