### ISSUE TITLE
Support notification after a pipeline run done

### ISSUE THREAD

**Issue by rmgogogo** [kubeflow/pipelines#3516]
It's a request mentioned in today's community meeting.
After a pipeline run got done, we can provide a notification to trigger other tasks/systems.

Without this feature, it's still can be handled via user-codes.

Option-1: Last step in pipeline write a file to some place, e.x. GCS. File watcher get the signal and trigger things outside of KFP.

Option-2: Last step in pipeline put msg to certain certain Queue (e.x. Pubsub) to trigger other work.

We will treat this FR with low priority for now but keep this ticket open to let community aware the other options and get more feedback on better proposals.

**Comment by rmgogogo** [comment]
@jessiezcc

**Comment by rmgogogo** [comment]
@Bobgy

**Comment by rmgogogo** [comment]
Option-3: we provide a sample component and tutorial to demo how to use user-codes to handle notification. (It would also help mitigate the requests on providing Workflow styled requests).

Option-3 will be treated with priority.

**Comment by Bobgy** [comment]
FYI: argo has examples we can follow: https://github.com/argoproj/argo/blob/master/docs/workflow-notifications.md

**Comment by shotarok** [comment]
I read the workflow-notifications.md. Thanks! Let me confirm my understanding. 

The 2nd option ["Default Workflow Spec"](https://github.com/argoproj/argo/blob/master/docs/default-workflow-specs.md) is available from v2.7. The 3rd option ["Workflow Events"](https://github.com/argoproj/argo/blob/master/docs/workflow-events.md) is available from v2.7.2. 

However, the v0.5.1 of kubeflow/pipelines uses [v2.3.0 of workflow-controller](https://github.com/kubeflow/pipelines/blob/51f5a5a9ed90b97fe8cf332329f9312902db56a9/third_party/argo/Dockerfile.argoexec#L25-L26). Therefore, the 2nd and 3rd option wouldn't work. Is this correct?

**Comment by Bobgy** [comment]
the next release has been using argo 2.7.5

**Comment by Bobgy** [comment]
Hi @jli, before KFP invents its own way to notify, you can use argo's ways -- see above https://github.com/argoproj/argo/blob/master/docs/workflow-notifications.md

These are configurable transparently

**Comment by jli** [comment]
Thanks @Bobgy! I will give that a try.

I see in my k8s cluster that there's a `workflow-controller-configmap` - do I just need to update this value with my desired `workflowDefaults` config? Is it possible that KFP or Argo would remove/update the configmap in the future and cause my configuration to be lost?

**Comment by Bobgy** [comment]
@jli

1. yes, you can use KFP exit handler.

2. No, your configmap won't be changed, unless you upgrade KFP/argo. You can maintain a kustomize overlay if you care about infra as code.

**Comment by jli** [comment]
Is there any way in KFP or Argo to know which user launched a workflow? (I would like to be able to to send more targeted alerts.)

If not, are there common patterns you know of for how we can add this type of metadata to KFP?

Thanks!

**Comment by Bobgy** [comment]
@jli I don't think we have separate metadata, can you send a feature request?

Current workaround can be adding pipeline parameters that default to author of the pipeline.
