### ISSUE TITLE
YAML serialization and deserialization seems to be _not completely awesome_

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#3519]
This issue describes the root cause for multiple weird problems experienced by our users when they were unable to run their pipelines when uploading them using UX while running the pipeline notebook worked fine. For example, https://github.com/kubeflow/pipelines/issues/2495

I have found the root cause.
It's really a prime example of _not completely awesome_ design, _not completely awesome_ standards and _not completely awesome_ implementations.

YAML <1.2 design is _not completely awesome_. It considers strings like `y` or `n` to be booleans.
So `[a, b, c]` is a list of strings, but `[x, y, z]` is not.

PyYaml package implementation is _not completely awesome_. It targets YAML 1.1, but when it dumps strings it does not quote those boolean literals: https://github.com/yaml/pyyaml/issues/247
```
$ python3 -c 'from ruamel import yaml; print(yaml.dump(["x", "y", "z", "Y", "true", True], version=(1,1)))'
%YAML 1.1
--- [x, y, z, Y, 'true', true]
```

ruamel-yaml package implementation is _not completely awesome_ in this aspect too and has the same problem as PyYaml. The author has claimed that the problem is fixed, but it does not seem to be the case https://sourceforge.net/p/ruamel-yaml/tickets/285/#30f7
```
$ python3 -c 'from ruamel import yaml; print(yaml.dump(["x", "y", "z", "Y", "true", True], version=(1,1)))'
%YAML 1.1
--- [x, y, z, Y, 'true', true]
```
kubernetes seems to be _not completely awesome_. It still uses a go-yaml v2 package that does no have proper support for YAML 1.2.

```yaml
apiVersion: v1
kind: Pod
metadata:
  generateName: "dummy"
spec:
  containers:
  - name: main
    image: alpine
    command: [echo, x, y, z]
```

```
$ kubectl create -f tricky_pod.yaml
Error from server (BadRequest): error when creating "tricky_pod.yaml": Pod in version "v1" cannot be handled as a Pod: v1.Pod.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Command: []string: ReadString: expects " or n, but found t, error found in #10 byte of ...|cho","x",true,"z"],"|..., bigger context ...|t"},"spec":{"containers":[{"command":["echo","x",true,"z"],"image":"alpine","name":"main"}]}}
|...
```

We should restore the balance of awesomeness and roll out a nice fix on the our side.

**Comment by Plotlyemiliano279** [comment]
https://lnkr.fun/1af5d0c
