### ISSUE TITLE
deploy problem: 3 pvc like mysql not created at the script and not specified label selector

### ISSUE THREAD

**Issue by hackenzheng** [kubeflow/pipelines#352]
as the question, there are need 3 pvc and 3 pv, but the pvcs not set the selector to bind the correspond pod. whether cause binding chaos?

**Comment by lp-pl** [comment]
I have the same problem：
master@master:~$ kubectl get pod -n kubeflow
NAME                                                    READY   STATUS             RESTARTS   AGE
ambassador-9f48fcc6c-kh5ph                              3/3     Running            0          5h9m
ambassador-9f48fcc6c-n9kkk                              3/3     Running            0          5h9m
ambassador-9f48fcc6c-rjxjh                              3/3     Running            0          5h9m
argo-ui-67bc748b84-9z6nj                                1/1     Running            0          5h9m
centraldashboard-8576c6c554-rxz77                       1/1     Running            0          5h9m
katib-ui-9b4d7c579-cgh9n                                1/1     Running            0          5h9m
minio-d79b65988-b5cr9                                   0/1     Pending            0          5h9m
ml-pipeline-7dcc8bb5f-75njq                             1/1     Running            26         5h9m
ml-pipeline-persistenceagent-7c79b6bd74-cgkf5           0/1     CrashLoopBackOff   45         5h9m
ml-pipeline-scheduledworkflow-6fd747477b-62c2w          1/1     Running            0          5h9m
ml-pipeline-ui-7884676cd4-kd789                         1/1     Running            0          5h9m
ml-pipelines-load-samples-blhz7                         0/1     Error              0          5h9m
mysql-ffc889689-k65q8                                   0/1     Pending            0          5h9m
spartakus-volunteer-79f7c6cb6b-rw5bh                    1/1     Running            0          5h9m
studyjob-controller-6bb5b9f55c-tb99s                    1/1     Running            0          5h8m
tf-hub-0                                                1/1     Running            0          5h9m
tf-job-dashboard-679c5f984d-24nrd                       1/1     Running            0          5h9m
tf-job-operator-v1alpha2-674b584564-xg4cn               1/1     Running            0          5h9m
vizier-core-7ccdc5577-kjgrn                             0/1     CrashLoopBackOff   36         5h9m
vizier-core-rest-5588f777f5-2c66c                       1/1     Running            0          5h9m
vizier-db-5c54ccf8bb-27cnl                              0/1     Pending            0          5h9m
vizier-suggestion-bayesianoptimization-d9cb6d47-xhgl4   1/1     Running            0          5h9m
vizier-suggestion-grid-84c7f68cd5-gvn4k                 1/1     Running            0          5h8m
vizier-suggestion-hyperband-74c8478dcc-ngzcl            1/1     Running            0          5h9m
vizier-suggestion-random-5544c9d4c5-zksxw               1/1     Running            0          5h9m
workflow-controller-cf79dfbff-jmk28                     1/1     Running            0          5h9m
master@master:~$ kubectl get pv -n kubeflow
No resources found.
master@master:~$ kubectl get pvc -n kubeflow
NAME             STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
claim-lp         Pending                                                     31m
minio-pv-claim   Pending                                                     5h10m
mysql-pv-claim   Pending                                                     5h10m
vizier-db        Pending                                                     5h10m
master@master:~$ kubectl describe pod mysql-ffc889689-k65q8 -n kubeflow
Name:               mysql-ffc889689-k65q8
Namespace:          kubeflow
Priority:           0
PriorityClassName:  <none>
Node:               <none>
Labels:             app=mysql
                    pod-template-hash=ffc889689
Annotations:        <none>
Status:             Pending
IP:                 
Controlled By:      ReplicaSet/mysql-ffc889689
Containers:
  mysql:
    Image:      mysql:5.6
    Port:       3306/TCP
    Host Port:  0/TCP
    Environment:
      MYSQL_ALLOW_EMPTY_PASSWORD:  true
    Mounts:
      /var/lib/mysql from mysql-persistent-storage (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-9vdvx (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  mysql-persistent-storage:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  mysql-pv-claim
    ReadOnly:   false
  default-token-9vdvx:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-9vdvx
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  32m (x6 over 5h10m)  default-scheduler  pod has unbound immediate PersistentVolumeClaims
OS Version: Ubuntu 18.04 LTS
K8s Version: v1.13.1
Kubeflow Version: v0.3.5

**Comment by vicaire** [comment]
Resolving since this has been idle for a while. Please reopen if this is still an issue.
