### ISSUE TITLE
client.schedule_pipeline not working with cron

### ISSUE THREAD

**Issue by yaronha** [kubeflow/pipelines#3523]
Seems like there is a bug in `client.schedule_pipeline()` call, the cron schedule is not set properly 

### What steps did you take:
i tried the API using:
```
client.schedule_pipeline(experiment_id="aa1291bd-3998-42a9-b5ec-a000d9516f73", 
                         pipeline_id="d2268136-b8e9-41be-9342-59cf727ece11",
                         job_name="Testjob",
                         cron_schedule="0 0 9 ? * 2-6")
```

### What happened:

the job didn't get the schedule part since the job json seem to be malformed:

```json
bad: {"id": "BGI6RKC3K1", "name": "myjob", "pipeline_spec": {"pipeline_id": "461dd261-cc0f-4b6a-9589-7b5981f739db", "parameters": []}, "resource_references": [{"key": {"type": "EXPERIMENT", "id": "e3072e91-0de9-4c1e-8f77-447b104dd452"}, "relationship": "OWNER"}], "max_concurrency": 10, "trigger": {"cron": "0 0 9 ? * 2-6"}, "enabled": true}
```

should have been:

`"trigger":{"cron_schedule":{"cron":"0 0 * * * ?"}}`

looking at the code there seem to be an issue:
https://github.com/kubeflow/pipelines/blob/56d519e9f76c57bdffc593742e23b790a0505310/sdk/python/kfp/_client.py#L537

instead it should be:

```
trigger = kfp_server_api.models.api_cron_schedule.ApiCronSchedule(cron=cron_schedule) #Example:cron_schedule="0 0 9 ? * 2-6"
trigger = kfp_server_api.models.api_trigger.ApiTrigger(cron_schedule=trigger)
```

when i changed the source (added the 2nd line) it worked for me

### Environment:
KFP SDK version: 0.40

/kind bug
/area sdk

**Comment by jonasdebeukelaer** [comment]
@yaronha do you plan to implement the fix? If not, I'm happy to take it on. 
Not sure if anyone else should be in the loop?

**Comment by jonasdebeukelaer** [comment]
also am I looking in the wrong place or are there no unit tests for the sdk client?

**Comment by yaronha** [comment]
@jonasdebeukelaer there is already a fix in a nother PR, waiting for it to merge:

https://github.com/kubeflow/pipelines/pull/3490

**Comment by Bobgy** [comment]
https://github.com/kubeflow/pipelines/pull/2978 was the earliest fix as far as I know.
@Ark-kun @numerology for interface review

**Comment by Ark-kun** [comment]
This should be fixed now.
