### ISSUE TITLE
Backend should not rely on presence of samples.

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#355]
In https://github.com/kubeflow/pipelines/pull/110 the bootstrapper silently fails to start the backend due to missing samples.

Missing samples should not be fatal. https://github.com/kubeflow/pipelines/blob/master/backend/src/apiserver/main.go#L57

My opinion is that the backend should not know about samples at all. The samples should be injected in the cluster instance by the bootstrapper.

**Comment by vicaire** [comment]
Resolving in favor of https://github.com/kubeflow/pipelines/issues/455
