### ISSUE TITLE
ml-pipeline memory leak and no HPA support

### ISSUE THREAD

**Issue by descampsk** [kubeflow/pipelines#3550]
### What steps did you take:
[A clear and concise description of what the bug is.]

ML-pipeline seems to have a memory leak and it doesn't support HPA.

### What happened:

As this two screens shows, ml-pipeline seems to use all memory available for its pods until it is OOM and killed. It seems that it never free the memory.

If we have two pods of ml-pipeline only one is used. When the first one is OOM and killed, the second one become used and the first one idle. Then we can't put HPA because it will never scale up as one pod has always 0%cpu used

![image](https://user-images.githubusercontent.com/22590202/79692853-c1082400-8267-11ea-9a8d-e2091fb6fe95.png)

![image](https://user-images.githubusercontent.com/22590202/79692871-dc732f00-8267-11ea-9de8-008d25f8bb6b.png)

### What did you expect to happen:

- The pods should free some memory and not becomes OOM even if we give him 1Gb Memory.
- The requests should be loadbalanced between all ml-pipelines pods

### Environment:
How did you deploy Kubeflow Pipelines (KFP)?
AWS EKS 1.14 environment with kubeflow 0.7 manifest

KFP version: 0.1.40

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug
/area backend

**Comment by rmgogogo** [comment]
kindly ping, we may treat this one with priority

**Comment by jingzhang36** [comment]
@descampsk some quick thoughts: first of all, would it be possible for you to upgrade your KFP version to our latest release? Let's check if the memory abnormality disappear with the more up-to-date release of KFP; also, I personally haven't run into this memory issue or received similar reports, but given that all my instances are on GCP instead of AWS, I can't be sure if this issue is particular to AWS or something inside KFP implementation. Therefore, if you can try to upgrade your version first and if that doesn't solve this issue, we can either  try to find a way to first reproduce it on GCP (which I would say is unlikely) or we'll solely rely on your server log to debug on AWS since I don't have access to AWS resources.

**Comment by descampsk** [comment]
I upgrade to kubeflow 1.0.2 witk kfp version equals to 2.5.0 and i can see a similar issue: 

![image](https://user-images.githubusercontent.com/22590202/84755423-ef815180-afc1-11ea-8dec-c3e4c089eed0.png)

Two pods and only one is used.

It is not so remarkable as with our older cluster but the new one is still young so I will have more data in the following weeks.

**Comment by Bobgy** [comment]
@descampsk to help troubleshoot/reproduce the problem:

Can you take a look at `ml-pipeline` pod logs and see if there's anything that looks abnormal?

Can you share some other usage scale data, e.g.
* how many concurrent workflows?
* `kubectl get workflow -n kubeflow --no-header | wc -l` how many workflows at a certain time?
@jingzhang36 do you think any other data might be helpful?

**Comment by radcheb** [comment]
Hi @Bobgy we are facing the same issue:
![image](https://user-images.githubusercontent.com/5963615/99687563-1833d880-2a85-11eb-9186-78be32370b57.png)

> Can you share some other usage scale data, e.g.

* At some point we may have 20-30 concurrent workflows.
* When I run this command `kubectl get workflow -n kubeflow --no-header | wc -l` I get `528` ! I got come with `47h` as age.

**Comment by Bobgy** [comment]
@radcheb is `ml-pipeline` pod or argo pod leaking memory? This issue is about `ml-pipeline`

**Comment by radcheb** [comment]
> @radcheb is `ml-pipeline` pod or argo pod leaking memory? This issue is about `ml-pipeline`

It's the `ml-pipeline` pod using `ml-pipeline/api-server` docker image. I am not sure it comes from argo 🤔 ?

**Comment by Bobgy** [comment]
No, it's different. let's keep this open then.
Contribution welcomed on investigating how it's leaking in `ml-pipeline` pod, a.k.a. KFP api server.
