### ISSUE TITLE
Always show GettingStart page for Standalone

### ISSUE THREAD

**Issue by rmgogogo** [kubeflow/pipelines#3551]
Currently GettingStart page is only visiable in MKP deployment.
We may let it be visiable always as long as it's standalone  KFP (& MKP).

**Comment by rmgogogo** [comment]
@Bobgy SG?

**Comment by Bobgy** [comment]
@rmgogogo Sounds reasonable, it's stable enough for all.

**Comment by Bobgy** [comment]
Changed to KFP 1.0, because low efforts

**Comment by Bobgy** [comment]
Moved to post 1.0, because this requires fixes to frontend integration tests, which I don't have bandwidth right now.
