### ISSUE TITLE
[Metadata Writer] TypeError: create_new_execution_in_existing_context() got an unexpected keyword argument 'custom_properties'

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#3552]
Follow up bug of https://github.com/kubeflow/pipelines/issues/3462

### What steps did you take:
1. I used image: gcr.io/ml-pipeline-test/18bfbfcbc01e6da63f1357fd70079996ed51d512/metadata-writer@sha256:80637db1522432ce7da87c3533d397bbd3c2f0d3e4d68323a9ae9fdcac02a8a3 from https://github.com/kubeflow/pipelines/pull/3479
2. Ran a pipeline

### What happened:
No executions are logged, found error log in metadata-writer pod:
```
Kubernetes Pod event:  MODIFIED file-passing-pipelines-mbzrz-3001099438 1555702
Traceback (most recent call last):
  File "/kfp/metadata_writer/metadata_writer.py", line 183, in <module>
    KFP_POD_NAME_EXECUTION_PROPERTY_NAME: pod_name,
  File "/kfp/metadata_writer/metadata_helpers.py", line 280, in create_new_execution_in_existing_run_context
    custom_properties=custom_properties,
TypeError: create_new_execution_in_existing_context() got an unexpected keyword argument 'custom_properties'
```

### What did you expect to happen:
Executions are logged with kfp_pod_name custom property.

### Environment:
How did you deploy Kubeflow Pipelines (KFP)? standalone
KFP version: 0.4.0

/kind bug

/assign @Ark-kun

**Comment by Bobgy** [comment]
Looks like function interface didn't add the new property: https://github.com/kubeflow/pipelines/blob/152c91c705911239a71ff9400c40805799cfd85f/backend/metadata_writer/src/metadata_helpers.py#L195

**Comment by Ark-kun** [comment]
@Bobgy Thanks for finding the bug. I've created a fix PR: https://github.com/kubeflow/pipelines/pull/3556

**Comment by Bobgy** [comment]
/reopen
@Ark-kun I'm not sure if I tested it correctly, after upgrading metadata-writer to the test image in your PR. I got the following error instead:
```
Kubernetes Pod event:  MODIFIED file-passing-pipelines-cdl4g-4254340033 1625686
Traceback (most recent call last):
  File "/kfp/metadata_writer/metadata_writer.py", line 183, in <module>
    KFP_POD_NAME_EXECUTION_PROPERTY_NAME: pod_name,
  File "/kfp/metadata_writer/metadata_helpers.py", line 290, in create_new_execution_in_existing_run_context
    custom_properties=custom_properties,
  File "/kfp/metadata_writer/metadata_helpers.py", line 216, in create_new_execution_in_existing_context
    type_properties=execution_type_properties,
  File "/kfp/metadata_writer/metadata_helpers.py", line 131, in create_execution_with_type
    custom_properties=custom_properties,
TypeError: Parameter to MergeFrom() must be instance of same class: expected ml_metadata.Value got str.
```

**Comment by Ark-kun** [comment]
Sorry for the error. I wanted to fix the issue ASAP and I made a mistake.

I've opened a fix PR: https://github.com/kubeflow/pipelines/pull/3563

I've verified that it now works without errors: https://pantheon.corp.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22ml-pipeline-test%22%0Aresource.labels.location%3D%22us-east1-b%22%0Aresource.labels.cluster_name%3D%22e2e-4f11163-11929%22%0Aresource.labels.namespace_name%3D%22kubeflow%22%0Aresource.labels.pod_name%3D%22metadata-writer-6996fc89b6-dvhrg%22%0Aresource.labels.container_name%3D%22main%22?project=ml-pipeline-test

**Comment by Bobgy** [comment]
@Ark-kun no problem at all, thanks for fixing again.
I tried the new image in UI and got most of metadata logged with kfp_pod_name successfully.

However, it seems some components do not get metadata. I can find error logs like
```
Error: Not found upstream artifact with URI=minio://mlpipeline/artifacts/file-passing-pipelines-5shnq/file-passing-pipelines-5shnq-3295017605/sum-numbers-output.tgz.
New execution id: 78, context id: 37 for pod file-passing-pipelines-znrt2-694761583.
Execution: {'context_id': 37, 'context_name': 'file-passing-pipelines-znrt2', 'execution_id': 78, 'execution_name': 'file-passing-pipelines-znrt2-694761583', 'component_name': 'Print text'}
```
any clues?

**Comment by Ark-kun** [comment]
> @Ark-kun no problem at all, thanks for fixing again.
> I tried the new image in UI and got most of metadata logged with kfp_pod_name successfully.
> 
> However, it seems some components do not get metadata. I can find error logs like
> 
> ```
> Error: Not found upstream artifact with URI=minio://mlpipeline/artifacts/file-passing-pipelines-5shnq/file-passing-pipelines-5shnq-3295017605/sum-numbers-output.tgz.
> New execution id: 78, context id: 37 for pod file-passing-pipelines-znrt2-694761583.
> Execution: {'context_id': 37, 'context_name': 'file-passing-pipelines-znrt2', 'execution_id': 78, 'execution_name': 'file-passing-pipelines-znrt2-694761583', 'component_name': 'Print text'}
> ```
> 
> any clues?
> 
> data passing sample should have more steps, but it only successfully logged print ops
> 
> control structure sample however got all steps logged successfully

Can you please send the link to the full log?

Maybe there is some error when registering the upstream executions in the data passing sample.

**Comment by Bobgy** [comment]
will update here

**Comment by Bobgy** [comment]
@Ark-kun I tried again, and it successfully logged all data now (with a fresh cluster)...
I'm not sure what went wrong last time, might be an upgrade issue.

Thanks for the quick implementation! Now we get a much better metadata UI experience I believe

/close

**Comment by Ark-kun** [comment]
> I'm not sure what went wrong last time, might be an upgrade issue.

That's still weird... If you remember the name of the cluster, then the logs in the StackDriver remain forever.

**Comment by Bobgy** [comment]
@Ark-kun You can find logs here: https://pantheon.corp.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22gongyuan-pipeline-test%22%0Aresource.labels.location%3D%22asia-east1-c%22%0Aresource.labels.cluster_name%3D%22standalone2%22%0Aresource.labels.namespace_name%3D%22kubeflow%22%0Alabels.k8s-pod%2Fapp%3D%22metadata-writer%22%0Alabels.k8s-pod%2Fapplication-crd-id%3D%22kubeflow-pipelines%22;timeRange=2020-04-22T08:00:00.000Z%2F2020-04-22T09:00:00.000Z?project=gongyuan-pipeline-test

**Comment by Bobgy** [comment]
I didn't see any other error messages from the one I pasted above.

Additionally, I guess something special is that the cluster had a broken metadata-writer for a while (previous patch), I've ran some pipelines. Then I updated the image to the fixed metadata-writer. Do you think this scenario could cause problems? If yes, maybe we need to improve its final-consistency guarantee
