### ISSUE TITLE
While building the Frontend Dockerfile, it fails with compilation error

### ISSUE THREAD

**Issue by ICDS-Offering** [kubeflow/pipelines#3555]
While doing the docker build of frontend Dockerfile of 0.4.0 tag, I see the below error

> pipelines-frontend@0.1.0 lint /src
> eslint --ext js,ts,tsx src

Creating an optimized production build...
Failed to compile.

/src/src/pages/NewRun.tsx
TypeScript error in /src/src/pages/NewRun.tsx(50,26):
Cannot find module '../../../frontend/third_party/argo-ui/argo_template'.  TS2307

    48 | import { ToolbarProps } from '../components/Toolbar';
    49 | import { URLParser } from '../lib/URLParser';
  > 50 | import { Workflow } from '../../../frontend/third_party/argo-ui/argo_template';
       |                          ^
    51 | import { classes, stylesheet } from 'typestyle';
    52 | import { commonCss, padding, color } from '../Css';
    53 | import { logger, errorToMessage } from '../lib/Utils';

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pipelines-frontend@0.1.0 build: `npm run lint && EXTEND_ESLINT=true react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pipelines-frontend@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-20T07_14_42_992Z-debug.log
Error: error building at STEP "RUN npm run build": error while running runtime: exit status 1
[root@k8s-master frontend]# pwd

**Comment by rmgogogo** [comment]
I believe it can work now. Here close but feel free reopen if you still can't.
