### ISSUE TITLE
pods running in kubeflow namespace

### ISSUE THREAD

**Issue by miramar-labs** [kubeflow/pipelines#3569]
### What steps did you take:
I ran the example exit handler pipeline

### What happened:
I noticed the pods ran in the kubeflow namespace

### What did you expect to happen:
I expected them to run in *my* user namespace (generally speaking this would be better for security reasons)

### Environment:
vanilla K8s (3masters/8workers onprem ESXi cluster)

How did you deploy Kubeflow Pipelines (KFP)?
kfp

KFP version: ca58b22

KFP SDK version: 
kfp                              0.4.0              
kfp-server-api           0.3.0 

### Anything else you would like to add:
Q: is there a way I can specify which namespace the pipeline component pods run in?

/kind bug

**Comment by Ark-kun** [comment]
> I ran the example exit handler pipeline

Does this happen with other samples?

>Q: is there a way I can specify which namespace the pipeline component pods run in?

This will be enabled as part of the multi-user feature. @chensun

**Comment by chensun** [comment]
Yes, this is covered by the multi-user feature.
We have stage 1 work delivered last December, here's the instruction doc you can try out: https://drive.google.com/file/d/1aqiBrYzTJQ9dUrjOjB2OWfTBD6MKrbt6/view

We're currently working on stage 2. The progress is tracked by #1223. 

/cc @Bobgy  @IronPan

**Comment by Bobgy** [comment]
/close
Please see #1223
