### ISSUE TITLE
pipeline visualization image build process is not moving further when try  "RUN /usr/local/gcloud/google-cloud-sdk/install.sh" instruction in docker file

### ISSUE THREAD

**Issue by abhishek-tyagi87** [kubeflow/pipelines#3571]
### What steps did you take:
[A clear and concise description of what the bug is.]

### What happened:
i am trying to build image from Dockerfile.visualization file. when instruction 'RUN /usr/local/gcloud/google-cloud-sdk/install.sh' is running , it is prompt and asking y or N  .even giving this, its not moving futher.

STEP 6: **RUN /usr/local/gcloud/google-cloud-sdk/install.sh**
Welcome to the Google Cloud SDK!
WARNING: You appear to be running this script as root. This may cause 
the installation to be inaccessible to users other than the root user.

To help improve the quality of this product, we collect anonymized usage data
and anonymized stacktraces when crashes are encountered; additional information
is available at <https://cloud.google.com/sdk/usage-statistics>. This data is
handled in accordance with our privacy policy
<https://policies.google.com/privacy>. You may choose to opt in this
collection now (by choosing 'Y' at the below prompt), or at any time in the
future by running the following command:

    gcloud config set disable_usage_reporting false

**D**o you want to help improve the Google Cloud SDK (y/N)?  y****

even after giving y or N 
 

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

KFP version: 

KFP SDK version: 

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]
ICDS

/kind bug
 area backend

**Comment by Bobgy** [comment]
I'll investigate, but our image building process in presubmit tests are still working fine. I don't know what was the difference.

@abhishek-tyagi87 can you share your exact command to start the build?
