### ISSUE TITLE
Request Jupyter Server Connect/Disconnect

### ISSUE THREAD

**Issue by miramar-labs** [kubeflow/pipelines#3579]
At the moment you can add multiple Notebook Server definitions and connect to them to use them. I'd like to see a Disconnect button too, so that I can keep the server definition around but stop the server (unloading it's pods) when i'm not using it to minimize cluster resources used.

**Comment by rmgogogo** [comment]
seems not a ticket to pipeline.
feel free to reopen if misunderstand
