### ISSUE TITLE
Generate release notes failed

### ISSUE THREAD

**Issue by hongye-sun** [kubeflow/pipelines#3589]
Found 52 tags                                                                                                                                                                             
Fetching tags dates: 52/52                                                                                                                                                                
Sorting tags...                                                                                                                                                                           
Received issues: 3088                                                                                                                                                                     
Pull Request count: 2200                                                                                                                                                                  
Filtered pull requests: 1931                                                                                                                                                              
#<Thread:0x00007f09f8661828@/var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:193 run> terminated with exception (report_on_except
ion is true):                                                                                                                                                                             
Traceback (most recent call last):                                                                                                                                                        
        32: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:195:in `block (3 levels) in fetch_events_async'                
        31: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:370:in `iterate_pages'                                         
        30: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:397:in `check_github_response'                                 
        29: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'                                                                                              
        28: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'                                                                                                  
        27: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'                                                                                     
        26: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:398:in `block in check_github_response'                        
        25: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:370:in `block in iterate_pages'                                
        24: from /var/lib/gems/2.5.0/gems/octokit-4.14.0/lib/octokit/client/events.rb:134:in `issue_events'                                                                               
        23: from /var/lib/gems/2.5.0/gems/octokit-4.14.0/lib/octokit/connection.rb:84:in `paginate'                                                                                       
        22: from /var/lib/gems/2.5.0/gems/octokit-4.14.0/lib/octokit/connection.rb:156:in `request'                                                                                       
        21: from /var/lib/gems/2.5.0/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'                                                                                                   
        20: from /var/lib/gems/2.5.0/gems/faraday-0.17.1/lib/faraday/connection.rb:138:in `get'                                                                                           
        19: from /var/lib/gems/2.5.0/gems/faraday-0.17.1/lib/faraday/connection.rb:387:in `run_request'                                                                                   
        18: from /var/lib/gems/2.5.0/gems/faraday-0.17.1/lib/faraday/rack_builder.rb:143:in `build_response'                                                                              
        17: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:115:in `call'                                                                                
        16: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:142:in `call!'                                                                               
        15: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:195:in `process'                                                                             
        14: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:290:in `fetch'                                                                               
        13: from /var/lib/gems/2.5.0/gems/faraday-0.17.1/lib/faraday/response.rb:8:in `call'                                                                                              
        12: from /var/lib/gems/2.5.0/gems/faraday-0.17.1/lib/faraday/adapter/net_http.rb:38:in `call'                                                                                     
        11: from /var/lib/gems/2.5.0/gems/faraday-0.17.1/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'                                                                 
        10: from /var/lib/gems/2.5.0/gems/faraday-0.17.1/lib/faraday/adapter/net_http.rb:43:in `block in call'                                                                            
         9: from /var/lib/gems/2.5.0/gems/faraday-0.17.1/lib/faraday/adapter/net_http.rb:85:in `perform_request'                                                                          
         8: from /usr/lib/ruby/2.5.0/net/http.rb:1216:in `get'                                                                                                                            
         7: from /usr/lib/ruby/2.5.0/net/http.rb:1458:in `request'                                                                                                                        
         6: from /usr/lib/ruby/2.5.0/net/http.rb:909:in `start'                                                                                                                           
         5: from /usr/lib/ruby/2.5.0/net/http.rb:920:in `do_start'                                                                                                                        
         4: from /usr/lib/ruby/2.5.0/net/http.rb:935:in `connect'                                                                                                                         
         3: from /usr/lib/ruby/2.5.0/timeout.rb:103:in `timeout' 
         2: from /usr/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'                                                                                                                  
         1: from /usr/lib/ruby/2.5.0/net/http.rb:936:in `block in connect'                                                                                                                
/usr/lib/ruby/2.5.0/net/http.rb:939:in `rescue in block in connect': Failed to open TCP connection to api.github.com:443 (Connection timed out - connect(2) for "api.github.com" port 443)
 (Faraday::TimeoutError)                                                                                                                                                                  
#<Thread:0x00007f09f86612b0@/var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:193 run> terminated with exception (report_on_except
ion is true):                                                                                                                                                                             
Traceback (most recent call last):                                                                                                                                                        
        32: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:195:in `block (3 levels) in fetch_events_async'                
        31: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:370:in `iterate_pages'                                         
        30: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:397:in `check_github_response'                                 
        29: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'                                                                                              
        28: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'                                                                                                  
        27: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'                                                                                     
        26: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:398:in `block in check_github_response'                        
        25: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:370:in `block in iterate_pages'                                
        24: from /var/lib/gems/2.5.0/gems/octokit-4.14.0/lib/octokit/client/events.rb:134:in `issue_events'                                                                               
        23: from /var/lib/gems/2.5.0/gems/octokit-4.14.0/lib/octokit/connection.rb:84:in `paginate'                                                                                       
        22: from /var/lib/gems/2.5.0/gems/octokit-4.14.0/lib/octokit/connection.rb:156:in `request'                                                                                       
        21: from /var/lib/gems/2.5.0/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'                                                                                                   
        20: from /var/lib/gems/2.5.0/gems/faraday-0.17.1/lib/faraday/connection.rb:138:in `get'                                                                                           
        19: from /var/lib/gems/2.5.0/gems/faraday-0.17.1/lib/faraday/connection.rb:387:in `run_request'                                                                                   
        18: from /var/lib/gems/2.5.0/gems/faraday-0.17.1/lib/faraday/rack_builder.rb:143:in `build_response'                                                                              
        17: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:115:in `call'                                                                                
        16: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:142:in `call!'                                                                               
        15: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:195:in `process'                                                                             
        14: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:290:in `fetch'

**Comment by rmgogogo** [comment]
I'm releasing 0.5.1 and here close this one.
If still can't, will manually update few notes to changlog
