### ISSUE TITLE
Store hosted JupyterHub notebooks in a persistent storage.

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#359]

**Comment by IronPan** [comment]
Should this be a JupyterHub feature request instead?

**Comment by Ark-kun** [comment]
Maybe. But it looks like we need the persistent storage more than they do.
JupyterHub might already support this.

**Comment by vicaire** [comment]
@IronPan, did we cover this as part of the persistence storage story for kubeflow/pipeline?

**Comment by IronPan** [comment]
no this is out of scope of what pipeline could support. Jupyter CRD ( the replacement of jupyter hub) should ensure the notebook can be accessed when cluster is upgrade.

**Comment by IronPan** [comment]
alternatively pipeline can snapshot notebook one artifact for a given experiment. but this is a TBD.

**Comment by IronPan** [comment]
Notebook should already support backing by PV. @Ark-kun I'll close this one for now. Please file an issue to JH CRD if needed.
