### ISSUE TITLE
Feature Request : Allow runs to be filtered on run attributes like metrics, time, duration etc[UI]

### ISSUE THREAD

**Issue by thebinaryone1** [kubeflow/pipelines#3591]
Multiple runs with different metrics can be easily sorted to see which runs were the best. 

All the metrics don't show up in the metrics column and there is no way to scroll right to view all the metrics in the "Runs" page of an experiment.
For the metrics that do show up, they always have a a tooltip saying "Cannot sort by this column"

The UI to view metrics or sort by them feels unusable right now.

**Comment by Bobgy** [comment]
@thebinaryone1 Can you give a screenshot or further explain `All the metrics don't show up in the metrics column`?
Is there a metric count limit in the UI?

Sounds like a reasonable request. Will all your runs fit in one page in the UI? (we can list more runs by choosing page size)

@jingzhang36 I believe backend cannot sort by metric, is that true?
I'm thinking about if a client side sort solution would be enough.

**Comment by thebinaryone1** [comment]
![image](https://user-images.githubusercontent.com/23407392/80061203-7693db00-84e5-11ea-8e3f-b45f9031eff9.png)

This only shows two metrics in the UI display, whereas my runs write more than 2  metrics.

The issue is not with how many runs I can list in one page.

**Comment by Bobgy** [comment]
@thebinaryone1 thanks for the information!
A design that allows choosing which metrics to show seems important to unblock your use-case.

> The issue is not with how many runs I can list in one page.

I was asking about the sort feature you were requesting, would it be enough if you can sort runs in one page?

**Comment by thebinaryone1** [comment]
It doesn't help much to sort it in just that one page. Ideally sorting should be done in the backend itself.

This is specially important when running a hyper-parameter sweep where each trial is writing an objective value and then in the end we want to see which trial did the best. Currently doing a list_runs() using KFP python client and then sorting it seems to be the best option. Would be great if UI/backend could support it.

**Comment by Bobgy** [comment]
@thebinaryone1 thanks for the clarification. Now I understand the scenario. Agree on your conclusions.

/assign @jingzhang36 
for whether backend can support that

for `cannot show more than two metrics`, I can prioritize later

**Comment by jingzhang36** [comment]
Seems that our backend doesn't support sorting/filtering by metric values yet. The fields that can be used in backend filter for Run are listed here https://github.com/kubeflow/pipelines/blob/ebd77a7a12f86f8a975337e6336fa6efb498a01e/backend/src/apiserver/model/run.go#L72

The earliest time we can get to the implementation of the sorting/filtering with metric values in backend is May, given our current work plan. Alternatively, you are very welcome to contribute your own implementation if you want, and we can review it for you.

Thanks!

**Comment by jingzhang36** [comment]
We have enabled, in kubeflow pipelines backend, *filtering* on run status, aka 'success', 'failed' etc. 

As for the sorting on duration, it would be a little bit tricky to do on backend, since the backend stores created_at and finished_at instead. The frontend displays duration by computing the difference between created_at and finished_at.

As for the sorting on metrics, let me experiment on it to see if we can at least enable it in backend. The situation here is that when we list runs, those listed runs might have different metrics. Therefore, when we specify sorting on a particular metric name, the storing is meaningless for some of the runs. A simple solution to that is we list the runs that do contain that particular metric in the front of the list, and have the runs that don't contain that particular metric in the tail of the list.

**Comment by Bobgy** [comment]
> A simple solution to that is we list the runs that do contain that particular metric in the front of the list, and have the runs that don't contain that particular metric in the tail of the list.

+1

**Comment by jingzhang36** [comment]
TODO: add an integration test to run api with a larger pipeline manifest.

**Comment by Bobgy** [comment]
Looks like done
