### ISSUE TITLE
with standalone KFP 0.4 install, artifacts and executions not showing in UI

### ISSUE THREAD

**Issue by amygdala** [kubeflow/pipelines#3597]
I did a standalone installation of KFP 0.4 following these instructions: https://www.kubeflow.org/docs/pipelines/installation/standalone-deployment/ 
Everything else seems to be working properly, but I'm not seeing artifacts and execution info being logged.  
(I looked at the various metadata pod logs and while I did see some warnings, there were no obvious connection-related errors.... though I might have missed something)

**Comment by amygdala** [comment]
That standalone deployment by default installs into the `kubeflow` namespace... (not `default`, which is the CAIP Pipelines default...) -- I don't suppose something is hardwired to a particular namespace?

**Comment by Ark-kun** [comment]
I think there was a problem with envoy causing UX to fail connecting to MLMD. The UX was showing errors in the Artifacts and Executions tabs though. https://github.com/kubeflow/pipelines/issues/3500

Can you please share the logs of the metadata-writer pod (and also kubectl describe that pod)?

Maybe it's looking at wrong namespace.

**Comment by amygdala** [comment]
[Here's](https://paste.googleplex.com/5375623595819008) the metadata-writer logs (for googlers). 
I am noticing periodic errors like this:
![image](https://user-images.githubusercontent.com/115093/80233762-dc7a8280-860b-11ea-9295-ae3d824c0f75.png)

Here's the pod description:
```
Name:           metadata-writer-84f799f4d7-xvcd8
Namespace:      kubeflow
Priority:       0
Node:           gke-kfp-test-default-pool-552279a7-0cnx/10.240.0.87
Start Time:     Wed, 22 Apr 2020 18:55:56 -0700
Labels:         app=metadata-writer
                application-crd-id=kubeflow-pipelines
                pod-template-hash=84f799f4d7
Annotations:    <none>
Status:         Running
IP:             10.20.2.6
IPs:            <none>
Controlled By:  ReplicaSet/metadata-writer-84f799f4d7
Containers:
  main:
    Container ID:   docker://d30f5f741a12108ad5a2989456b55a19f9ec249b10575a73ca0ec2b80e589fb4
    Image:          gcr.io/ml-pipeline/metadata-writer:0.4.0
    Image ID:       docker-pullable://gcr.io/ml-pipeline/metadata-writer@sha256:4bff074df4fa4f24f734a7cfeaef6a75dd7a6b6fc2ef85a29cec7ef3cc68ac60
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Thu, 23 Apr 2020 18:32:44 -0700
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 23 Apr 2020 18:30:09 -0700
      Finished:     Thu, 23 Apr 2020 18:32:18 -0700
    Ready:          True
    Restart Count:  3
    Environment:
      NAMESPACE_TO_WATCH:  kubeflow (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kubeflow-pipelines-metadata-writer-token-94bdr (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  kubeflow-pipelines-metadata-writer-token-94bdr:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubeflow-pipelines-metadata-writer-token-94bdr
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
```

**Comment by Ark-kun** [comment]
>I am noticing periodic errors like this:

This one is fine. (Although I should do some cosmetic fix there). Kubernetes watches cannot last forever and after some time you get error instead of a proper object. But Metadata Writer swallows the error and starts a new watch. 

> but I'm not seeing artifacts and execution info being logged.

Are you seeing no UX errors? I've seen MLMD problems on 0.4. See https://github.com/kubeflow/pipelines/issues/3500#issuecomment-613260165 That problem might be fixed by changing the envoy image: https://github.com/kubeflow/pipelines/pull/3502/files#diff-a619d7972910ec61ac433cc6d5cb8ee3R19

Can you try the preloaded TFX pipeline. It should log artifacts itself. Then we can see whether they show up (e.g. differentiate between UX/MLMD issue and Metadata Writer issue).

**Comment by amygdala** [comment]
Hmm, I think it's the former, as the TFX pipeline also shows no output, and I'm seeing this UI error:
![image](https://user-images.githubusercontent.com/115093/80403152-fb7b4d80-8873-11ea-968c-74fcc6b10f4a.png)

**Comment by Ark-kun** [comment]
I've applied the fix from https://github.com/kubeflow/pipelines/issues/3500#issuecomment-613260165 and the executions are now visible.
