### ISSUE TITLE
[FR] Expose Argo retryStrategy

### ISSUE THREAD

**Issue by hongye-sun** [kubeflow/pipelines#3599]
Argo supports [RetryStrategy](https://github.com/argoproj/argo/blob/master/docs/fields.md#retrystrategy), which supports:

* Always
* OnError
* OnFalure

The FR is to expose the interface in DSL and make sure the backend argo version supports the strategies.

**Comment by Ark-kun** [comment]
Can you please describe the use case that you want to enable that its currently not supported?

**Comment by twitchax** [comment]
@Ark-kun, it can help resolve pipeline failures in cases where pod pre-emption and other weird errors occur.

**Comment by Ark-kun** [comment]
> @Ark-kun, it can help resolve pipeline failures in cases where pod pre-emption and other weird errors occur.

Do you only want to retry on errors, but not on failures?

**Comment by twitchax** [comment]
Yes, both.

**Comment by Ark-kun** [comment]
> Yes, both.

Both errors and failures?

**Comment by Ark-kun** [comment]
I looked at Argo source code. The default `RetryPolicy` is `OnFailure`.
What if we change the default to Always?
Do we have scenarios when we do not want the `Always` behavior?

**Comment by twitchax** [comment]
I think, in some cases, you might choose not to always retry `OnFailure`, especially if the operator calls some type of costly underlying compute.

I think it would be best if _all_ of the options were exposed through KFP.

**Comment by Ark-kun** [comment]
We will implement this feature

**Comment by jiezhang** [comment]
@Ark-kun Can you please provide an ETA for this feature?

**Comment by Ark-kun** [comment]
> @Ark-kun Can you please provide an ETA for this feature?

RetryStrategy has been added to Argo 2.5.0, but the latest released version of KFP is still on Argo 2.4.3 (the master is already using 2.7.5). I'll try to release the feature next week.

**Comment by AntPeixe** [comment]
Is there any update on the status of this?

**Comment by Bobgy** [comment]
This has been implemented and released

https://github.com/kubeflow/pipelines/pull/5060
