### ISSUE TITLE
TFX-KFP SDK: Rename KubeflowDagRunner as KubeflowDagCompiler

### ISSUE THREAD

**Issue by rmgogogo** [kubeflow/pipelines#3604]
KubeflowDagRunner doesn't run the pipeline like other Runner.
It actually just compile the pipeline to be formatted on KFP.

So here two options:
(1) rename it from Runner to Compiler
(2) add more feature to let it upload pipeline and create run.

**Comment by rmgogogo** [comment]
@neuromage SG? guess you discussed it before.

**Comment by rmgogogo** [comment]
After few retries and it can upload to KFP server and output msgs.
In such case, I think it's not really necessary to rename it as cost is big (need to rename docs everywhere. 

So here close this issue.

I assume we don't have plan to trigger the run via KubeflowDagRunner, right?

**Comment by numerology** [comment]
> I assume we don't have plan to trigger the run via KubeflowDagRunner, right?

Right we don't.
