### ISSUE TITLE
TFX-KFP: created experiement which can't be deleted and stop upload another one

### ISSUE THREAD

**Issue by rmgogogo** [kubeflow/pipelines#3606]
### What steps did you take:
```
tfx pipeline create --engine kubeflow ...
```
It will create/upload a KFP pipeline to KPF server. Meanwhile it also create an experiment with the same name of the pipeline.

I delete the pipeline so that "tfx pipeline create" can create a newer one.

### What happened:
I can't delete the Experiment from the UI.
Run "tfx pipeline create" gave me error msg: pipeline already exist.

### What did you expect to happen:
1. I can delete Experience
2. "tfx pipeline create" dont' create experiment

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

KFP version: 

KFP SDK version: 

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by rmgogogo** [comment]
@jingzhang36 is this issue already been processing by you and Jiyong?
Remember we mentioned similar case before but I didn't expect it also create Experiment.

**Comment by numerology** [comment]
Just saw this.

I think the current `blessed` way to update a pipeline is to use `pipeline update`

**Comment by numerology** [comment]
@rmgogogo 
I think `pipeline already exists` error is triggered because the local pipeline file was not cleaned up. It's not sufficient to delete the pipeline in KFP server but also some local pipeline files need to be cleaned up as well.

You can refer to the code at https://github.com/tensorflow/tfx/blob/master/tfx/tools/cli/handler/base_handler.py#L186

BTW, the 'blessed way' of updating a pipeline should be invoking `tfx pipeline update` IMO

**Comment by Bobgy** [comment]
@rmgogogo From the error message, I cannot find any mention of experiment. Did you misread the message?

**Comment by rmgogogo** [comment]
> @rmgogogo From the error message, I cannot find any mention of experiment. Did you misread the message?

"tfx pipeline create --engine kubeflow ..." will give you a new experiment (not default) with the same name of the pipeline and I can't find a way to delete it.

**Comment by rmgogogo** [comment]
I expect "tfx pipeline create --engine kubeflow ..." just create pipeline in default experiment.
Or allow me to delete the auto-created experiment.

**Comment by rmgogogo** [comment]
@jingzhang36 believe it has some BE API issue related with this path.

**Comment by Bobgy** [comment]
I see, added area/backend label too
