### ISSUE TITLE
Getting pipeline run metrics from SDK

### ISSUE THREAD

**Issue by martfl** [kubeflow/pipelines#3607]
Hi,
I'm currently trying to gather the metrics outputted by several scheduled runs.
I'm using `create_run_from_pipeline_func` for submitting the run and waiting for completion.

The issue is, even if a run outputs a metric showing correctly on the Kubeflow UI, I cannot find a way to get the metrics dictionary for a particular run using the SDK, or the REST API for that matter.

Running the following script, the metric is displayed correctly in the Kubeflow UI. 

Environment:

KFP version: 0.6.2
KFP SDK version: 0.4.0

```python
import kfp
from kfp.components import func_to_container_op

from typing import NamedTuple

@func_to_container_op
def write_metrics(metric: str) -> NamedTuple('output', [('var', str), ('mlpipeline_metrics', 'Metrics')]):
    import json
    from collections import namedtuple
    out_tuple = namedtuple('output', ['var', 'mlpipeline_metrics'])
    return out_tuple("hi", json.dumps({'metrics':[{'name':'echo', 'numberValue': metric}]}))

@func_to_container_op
def print_text(text: str):
    print(text)

@kfp.dsl.pipeline(name="metric-test", description="test")
def pipeline():
    op = write_metrics("42")
    print_text(op.outputs['var'])

client = kfp.Client()
run = client.create_run_from_pipeline_func(
        pipeline_func=pipeline,
        arguments=dict(),
        run_name="echo"
    )

run.wait_for_run_completion(timeout=float("inf"))
print(run.run_info)
```
Now, I would expect `run_info` to hold the dictionary of the metrics the run outputs, instead it is always None.

Output for above script is as follows:

```
{'created_at': datetime.datetime(2020, 4, 24, 9, 9, 24, tzinfo=tzutc()),
 'description': None,
 'error': None,
 'finished_at': datetime.datetime(1970, 1, 1, 0, 0, tzinfo=tzutc()),
 'id': '4adb0732-860b-11ea-b03f-1662863989cf',
 'metrics': None,
 'name': 'echo',
 'pipeline_spec': ...
 'scheduled_at': datetime.datetime(1970, 1, 1, 0, 0, tzinfo=tzutc()),
 'status': None,
 'storage_state': None
}
```

I'm not sure if having the default dates in 'finished_at' and 'scheduled_at' has anything to do with it.
Also POSTing to /apis/v1beta1/runs/{run_id}:reportMetrics responds with an empty dict.

Perhaps the KFP version is too old.
I hope I'm not missing anything, or if pipeline metrics are currently only accesible through the UI.

My current workaround is to write the metrics json also to a separate volume, for later processing.

/kind bug

**Comment by Ark-kun** [comment]
> I'm not sure if having the default dates in 'finished_at' and 'scheduled_at' has anything to do with it.
> Also POSTing to /apis/v1beta1/runs/{run_id}:reportMetrics responds with an empty dict.

Now, I would expect run_info to hold the dictionary of the metrics the run outputs, instead it is always None.
Maybe there is something wrong with metrics collector in the backend. @rmgogogo @IronPan 

>My current workaround is to write the metrics json also to a separate volume, for later processing.

You can also just pass the metrics output to some "exporter" component. For example "Upload to GCS":


```
from kfp import components

upload_op = components.load_component_from_uri('https://raw.githubusercontent.com/kubeflow/pipelines/2dac60c/components/google-cloud/storage/upload_to_explicit_uri/component.yaml')

def pipeline():
    writer_task = write_metrics("42")
    print_text(writer_task.outputs['var'])
    upload_op(
        data=writer_task.outputs['mlpipeline_metrics'],
        gcs_path='gs://my+bucket/path/' + kfp.dsl.EXECUTION_ID_PLACEHOLDER,
    )
```

**Comment by Bobgy** [comment]
> KFP version: 0.6.2

I think this is Kubeflow 0.6.2. KFP has only released 0.5.0 recently.

/cc @jingzhang36 
Do we have a way to query metrics programmatically

**Comment by n3o-Bhushan** [comment]
@martfl Were you able to retrieve the Run Metrics eventually?

**Comment by tiru1930** [comment]
@martfl @n3o-Bhushan   were you guys able to retrieve metrics info from SDK , without storing it in any external storage like s3,gcp etc

**Comment by tiru1930** [comment]
@martfl @n3o-Bhushan  , I got solution for this,not with SDK, but using Rest API call I am able to get this info

```
kubeflow dashboardurl/pipeline/apis/v1beta1/runs/{run_id}
```
this one will give  kubeflow run details, if we can parse this response josn we can get artefacts path, so 

with artifacts path we have key, bucket name and namespace source as query params, we can give another api call

 url = f"{host}/artifacts/get" which will give the metrics

**Comment by minhdang241** [comment]
You can get the metrics from get_run like this.
```
run_detail = client.runs.get_run(run_id="7b9653d7-fc20-4d48-ad0a-bb16e573c671")
metrics = run_detail.run.metrics
```
