### ISSUE TITLE
Surface the sample test results to github

### ISSUE THREAD

**Issue by gaoning777** [kubeflow/pipelines#361]
By surfacing the sample test results to the github, users can choose the versions of the sample that work.

**Comment by IronPan** [comment]
> users can choose the versions of the sample that work.

@gaoning777 could you provide more details on this? not sure i quite follow.

**Comment by gaoning777** [comment]
It was previously brought up by Sina that there needs to be a table that shows the current sample test results for the master.
Since we always release correct samples. I will close the issue.
