### ISSUE TITLE
Multiple run termination option

### ISSUE THREAD

**Issue by thebinaryone1** [kubeflow/pipelines#3612]
There should be an option in the UI to support terminating multiple runs at the same time.

Also there seems to be no SDK method to terminate a run.

**Comment by Ark-kun** [comment]
> Also there seems to be no SDK method to terminate a run.

There should be an auto-generated method. Probably `kfp.Client().runs.terminate_run(...)`.
Discover all available methods using `dir(kfp.Client().runs)`

**Comment by Bobgy** [comment]
@thebinaryone1 is there any typical scenario you need to terminate multiple runs?
