### ISSUE TITLE
Alibaba Cloud OSS storage support to save artifacts

### ISSUE THREAD

**Issue by jhagege** [kubeflow/pipelines#3617]
Hi, can Kubeflow Pipeline save intermediate artifacts to Aliyun OSS storage (equivalent of S3, or GCS storage) ?
What does it require ? 
Thanks for any assistance.

**Comment by Ark-kun** [comment]
It might be possible when we upgrade Argo.
See https://github.com/argoproj/argo/issues/2358 
https://github.com/argoproj/argo/blob/master/docs/configure-artifact-repository.md
https://github.com/argoproj/argo/pull/1919/files#diff-81b3161712921356614ecd14405afbd1R19

**Comment by jhagege** [comment]
Thanks, looking forward.
