### ISSUE TITLE
cache-deployer-deployment crashes due to missing role permissions

### ISSUE THREAD

**Issue by yoni-taranis** [kubeflow/pipelines#3618]
### What steps did you take:
Upgrading kubeflow 0.2.5 to 0.5.0, all seemed to went smoothly, except of the mentioned deployment crashlooping.

### Anything else you would like to add:
I have fixed this by adding the missing **ClusterRole** with the apiGroups: 
  - 'certificates.k8s.io'
  - 'admissionregistration.k8s.io'

Then, binding them to the **kubeflow-pipelines-cache-deployer-sa** service account

**Comment by Ark-kun** [comment]
How did you deploy KFP? (Marketplace or Standalone)?

> I have fixed this by adding the missing ClusterRole with the apiGroups:

There should have been [kubeflow-pipelines-cache-deployer-clusterrole](https://github.com/kubeflow/pipelines/blob/45bc5823743ee9a2f3a67eddbf6e7d8f650323a4/manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/cache.yaml#L16) and [kubeflow-pipelines-cache-deployer-clusterrolebinding](https://github.com/kubeflow/pipelines/blob/45bc5823743ee9a2f3a67eddbf6e7d8f650323a4/manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/cache.yaml#L109) in your cluster.

Can you verify that you did not have them?

I wonder how this could have happened...

**Comment by Bobgy** [comment]
Did you deploy this step in https://www.kubeflow.org/docs/pipelines/installation/standalone-deployment/#deploying-kubeflow-pipelines?
```
kubectl apply -k github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=$PIPELINE_VERSION
```

**Comment by Ark-kun** [comment]
> did you deploy this step

What happens if you install everything in one go?

**Comment by Bobgy** [comment]
> > did you deploy this step
> 
> What happens if you install everything in one go?

There is an application CRD and its instance. If We deploy everything in a go, k8s api server may not accept the CR because CRD takes some time to be ready

**Comment by yoni-taranis** [comment]
Hi,

I didn't use a standalone deployment, but the upgrade process was like installing one since I thought I had to do customization to the configuration files

**Comment by Ark-kun** [comment]
Is your issue now fixed?

**Comment by yoni-taranis** [comment]
I have managed to work it around, but I do believe there is an issue with the setup.

**Comment by Ark-kun** [comment]
> I have managed to work it around, but I do believe there is an issue with the setup.

Did you run the two `kubectl` commands during your deployment process?

**Comment by rmgogogo** [comment]
I guess you didn't apply the cluster scoped resources.

kubectl apply -k github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=$PIPELINE_VERSION

sample:
https://github.com/kubeflow/pipelines/tree/master/manifests/kustomize/sample

Here close. Feel free to reopen if still find issue.

I test the sample for few times and didn't hit issue.
