### ISSUE TITLE
The DSL should not hardcode the Minio endpoint in the Kubernetes cluster. 

### ISSUE THREAD

**Issue by gaoning777** [kubeflow/pipelines#362]
Currently DSL hardcode the namespace of minio service to default. This would break when pipeline is deployed to another ns.
If possible, we should probably use the default argo repository to avoid DSL involvement.

**Comment by Ark-kun** [comment]
>Parameterize artifact namespace in DSL
I think it's better for this setting to be configured on the pipeline level, not in DSL.

**Comment by Ark-kun** [comment]
Fixed by https://github.com/kubeflow/pipelines/pull/1297
