### ISSUE TITLE
Argo upgrade - features and bugs

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#3621]
This issue will collect features and bugfixes that we want from newer Argo versions and the bugs they have.

Features:
* https://github.com/argoproj/argo/pull/1336 in v2.4.0+ Allow output parameters with .value, not only .valueFrom
* https://github.com/argoproj/argo/pull/1350 in v2.4.0+ Implemented support for WorkflowSpec.ArtifactRepositoryRef 
* https://github.com/argoproj/argo/pull/1782 in v2.5.0+ Add exponential back-off to retryStrategy
* https://github.com/argoproj/argo/pull/1821 in v2.6.0+ feat: ArtifactRepositoryRef ConfigMap is now taken from the workflow namespace
* https://github.com/argoproj/argo/pull/2166 in v2.6.0+ feat: Add failed node info to exit handler
* https://github.com/argoproj/argo/pull/2352 in v2.7.0+ feat: Add `argo stop` command

Bugfixes:
* https://github.com/argoproj/argo/issues/1445 in v2.4.0+ Fixes: Unable to write output artifacts when service account has limited permissions
* https://github.com/argoproj/argo/issues/1422 in v2.4.0+ Terminate all containers within pod after main container completes
* https://github.com/argoproj/argo/pull/1653 in v2.5.0+ Stop failing if artifact file exists, but empty
* https://github.com/argoproj/argo/pull/1860 in v2.5.0+ feat: Always archive logs if in config. Closes #1790

Problems:
* `argo lint` does not work in containers since v2.5.0+ (but we can use older version.) https://github.com/argoproj/argo/issues/2793

Efforts to upgrade Argo:

* https://github.com/kubeflow/pipelines/pull/2419 [WIP] Updated Argo to v2.4.1
* https://github.com/kubeflow/manifests/pull/642 Update manifests for argo 2.4.3
* https://github.com/kubeflow/pipelines/pull/3537 Upgraded Argo to v2.7.4. Problem: test workflows are "Pending" forever

**Comment by Bobgy** [comment]
Some existing required features were mentioned in https://github.com/kubeflow/pipelines/issues/3322

**Comment by Ark-kun** [comment]
Closing the issue since we've upgraded Argo to v2.7.5

**Comment by Ark-kun** [comment]
Remaining issues:

* https://github.com/argoproj/argo/issues/3069
