### ISSUE TITLE
Lineage UI no longer render artifact names

### ISSUE THREAD

**Issue by rmgogogo** [kubeflow/pipelines#3625]
### What steps did you take:
Add a custom component after CsvExampleGen.

https://www.tensorflow.org/tfx/guide/custom_component

### What happened:
Lineage UI didn't well visulize the output.

![aaa](https://user-images.githubusercontent.com/3444479/80327326-4befac80-886e-11ea-9f2d-989ea8d8c7d3.png)

### What did you expect to happen:

Correct visulization

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

KFP version: 

KFP SDK version: 

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug
/area frontend

**Comment by rmgogogo** [comment]
A sample here:
https://1c4774e7d442cc4c-dot-us-central2.pipelines.googleusercontent.com/#/pipelines/details/4ed92edb-431e-4e81-965b-1461d6e26d75

**Comment by Bobgy** [comment]
@rmgogogo Do you mean artifacts are unamed?

**Comment by Bobgy** [comment]
@rmgogogo renamed to make it clearer

**Comment by Bobgy** [comment]
@rmgogogo I sent a PR to fix it: https://github.com/kubeflow/frontend/pull/47
