### ISSUE TITLE
Pods mounting the same volume can not seem to run in parallel

### ISSUE THREAD

**Issue by husamaf** [kubeflow/pipelines#3628]
Hi, I hope I'm not missing something painfully obvious here but basically I can't seem to get 2 GPU components to run side-by-side.
(The components fine without a GPU constraint)

### What steps did you take:
1. Created 2 KFP components each representing a simple 300-sec `while` loop.
2. Added a GPU constraint to each component ('nvidia-tesla-p100').
3. Created a pipeline where the 2 components run concurrently.
4. Ran the pipeline on a GCP deployment.

### What happened:
The 2nd component gets stuck at "pending" until the 1st component is done (300 secs later).

### What did you expect to happen:
I expected both components to run at the same time

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

KFP version: 
Build commit: ca58b22

KFP SDK version: 
kfp                      0.4.0     
kfp-server-api           0.3.0 

### Anything else you would like to add:
"While" loop Component:
```python
  while_op1 = while_loop_op(image_name='tensorflow/tensorflow:1.15.2-py3')
  while_op1.name = 'while-1-gpu'
  while_op1.set_security_context(V1SecurityContext(privileged=True))
  while_op1.apply(gcp.use_gcp_secret('user-gcp-sa'))
  while_op1.add_pvolumes({pv_base_path: _volume_op.volume})
  while_op1.add_node_selector_constraint('cloud.google.com/gke-accelerator', 'nvidia-tesla-p100')
  while_op1.set_gpu_limit(1)
  while_op1.after(init_op)
```
Where `while_loop_op`:
```python
  def while_loop_op(image_name):
    def while_loop():
      import time
      max_count = 300
      count = 0
      while True:
        if count >= max_count:
          print('Done.')
          break
        time.sleep(10)
        count += 10
        print("{} seconds have passed...".format(count))
    op = comp.func_to_container_op(while_loop, base_image=image_name)
    return op()
```

/kind bug

**Comment by Ark-kun** [comment]
This looks like a Kubernetes issue.
Do you have 2 GPU nodes in the cluster? I'm not sure Kubernetes can schedule multiple GPU-using pods on a single node.

**Comment by rmgogogo** [comment]
I tested run 3 component parally at the same time and they can get GPUs (just that they are different typed GPUs in different node pool).
https://github.com/kubeflow/pipelines/tree/master/samples/tutorials/gpu

Based on the upper sample, you may quickly check whether can get same multiple GPU node from node pool. I think it can.

"I'm not sure Kubernetes can schedule multiple GPU-using pods on a single node."
I don't think it can support multi GPU-pods on a single node, aka GPU not virtualized into pod level. (feel free to correct me if you find it actually can)

**Comment by husamaf** [comment]
@Ark-kun @rmgogogo Thanks a lot both, I found the issue (kinda?).
So, the GPU availability was not the issue (I even set `--min-nodes=2`).
After testing with the gpu tutorial, it seems that adding a mounted volume (`VolumeOp`) is causing the issue.

Any idea why the 2 components in the linked pipeline run sequentially instead of concurrently? If not, I think I will just close the issue and maybe trying GCS Fuse instead.

https://gist.github.com/husamaf/2f3804aac652344f4b093a391bef7d79

**Comment by rmgogogo** [comment]
does the case want to mount same volume (PVC) to different component so that they can share the data across volume (e.x. component-1 write /volume/folder1 while component-2 read /volume/folder1?

Need @Ark-kun help on better answer.


Side question:
You mentioned GCS Fuse but not directly use GCS. Is it because the library you using can't access GCS? TF can. Which library you are using now?

**Comment by husamaf** [comment]
That's right. I would like to train on component-1, while component-2 loads and evaluates checkpoints (conditionally). 
Yea, exactly. I am using tensor2tensor + scipy + a bunch of my own custom code that will be a pain to refactor.

**Comment by rmgogogo** [comment]
@Ark-kun please help review the answer.

(1) create PVC before pipeline definition/run
(2) define pipeline with steps to use the common PVC

```
import kfp
import kfp.dsl as dsl

@dsl.pipeline(
    name="VolumeOp Basic",
    description="A Basic Example on VolumeOp Usage."
)
def volumeop_basic():    
    cop = dsl.ContainerOp(
        name="cop",
        image="library/bash:4.4.23",
        command=["sh", "-c"],
        arguments=["echo foo > /mnt/file1"],
        pvolumes={"/mnt": dsl.PipelineVolume(pvc="predefined-pvc")}
    )
```

**Comment by Ark-kun** [comment]
Here is a more canonical sample. We advice users to only use VolumeOp and pvolumes feature when absolutely necessary (and it never is necessary, because there is `kfp.onprem.mount_pvc`, `task.add_volume_mount` and `task.add_volume`).

```
from kfp import dsl
from kfp import onprem

def my_pipeline():    
    cop = dsl.ContainerOp(
        name="cop",
        image="library/bash:4.4.23",
        command=["sh", "-c"],
        arguments=["echo foo > /mnt/file1"],
    )
    cop.apply(mount_pvc(pvc_name='claim-name', volume_mount_path='/mnt/pipeline')))
```

**Comment by Ark-kun** [comment]
> I would like to train on component-1, while component-2 loads and evaluates checkpoints (conditionally).

You could write the checkpoints to a GCS directory. Pass the same URI to both components - one should write, another should read.

**Comment by Ark-kun** [comment]
You problem is probably caused by the fact that your volume can only be mounted to a single pod when writing.

**Comment by elikatsis** [comment]
Hi there! I've got some comments on the previous answers

>We advice users to only use VolumeOp and pvolumes feature when absolutely necessary (and it never is necessary, because there is `kfp.onprem.mount_pvc`, `task.add_volume_mount` and `task.add_volume`).

This is very odd, because you actually say that you advise users to either use a syntax that requires them to learn Kubernetes (`add_volume`, `add_volume_mount`) or one that is going to bug their pipeline if they attempt to mount multiple PVCs on their pods (if they follow your sample and they don't know Kubernetes).
However, isn't the purpose of the DSL to avoid such need (both for Kubernetes and Argo or any other workflow engine that will be used)? I think that pvolumes make this functionality more intuitive.

>You problem is probably caused by the fact that your volume can only be mounted to a single pod when writing.

Unless there are storage class implementations that (silently[1]) prohibit it (are there any?), there is no such access mode in Kubernetes:
* [Documentation](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes)
* Any `RW*` PVC can be mounted by two **pods**, but those pods will be scheduled on the _same cluster node_. Note that access modes refer to nodes, not pods. Kubernetes should schedule pods to run on the same node.

[1]: I'm using _silently_ because it's against Kubernetes notations

**Comment by husamaf** [comment]
@Ark-kun  I tried digging more into volume-mounting (and Kubernetes, in general), but eventually I gave up.

> You could write the checkpoints to a GCS directory. Pass the same URI to both components - one should write, another should read.

Yea, I ended up going with this suggestion of yours. I had to refactor my code, but it was not too bad and now it seems to be working fine. Thanks~

**Comment by Ark-kun** [comment]
> * Any `RW*` PVC can be mounted by two **pods**, but those pods will be scheduled on the _same cluster node_. Note that access modes refer to nodes, not pods. Kubernetes should schedule pods to run on the same node.

Interesting. Did not know that.

However this might help understand the issue: If two pods cannot be scheduled on the same node, then they'll run sequentially.

**Comment by Ark-kun** [comment]
>now it seems to be working fine

Glad to hear that.
