### ISSUE TITLE
Pipeline transformation hook in the backend

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#363]
Backend workflow transformation will provide many benefits for handling of namespaces, volumes, secrets, test image replacements etc. E.g. https://github.com/kubeflow/pipelines/issues/362 https://github.com/kubeflow/pipelines/issues/304

We can start with simple YAML conversion and move to more complicated augmentations later.

We could run transformation during the upload phase or when submitting the run. The later variant is preferred.

**Comment by vicaire** [comment]
Resolving as this will be covered by the pipeline yaml that will capture argo yaml + metadata.

**Comment by Ark-kun** [comment]
This issue remains regardless of the pipeline or component format.

Shared pipelines should not contain storage configuration and secrets. This information should be added by the backend right before submission.

**Comment by Ark-kun** [comment]
There is currently no explicit transformation hook, but the functionality is being added to `Run.CreateRun`  method https://github.com/kubeflow/pipelines/blob/d2ead9e056ee423b3a5254ef766d57948af5c403/backend/src/apiserver/resource/resource_manager.go#L214
