### ISSUE TITLE
[SDK] kfp.Client().wait_for_run_completion() cannot handle long execution

### ISSUE THREAD

**Issue by numerology** [kubeflow/pipelines#3630]
### What steps did you take:
If one tries to kick off kick off a pipeline using `kfp.Client()` and wait for its completion, the waiting process will error out in ~1 hour with the following error msg.

```
AttributeError                            
Traceback (most recent call last)
<ipython-input-8-8ebf2be6196c> in <module>
      1 client = kfp.Client(host='2c688415e5fe965e-dot-us-central2.pipelines.googleusercontent.com')
----> 2 client.wait_for_run_completion(run_id=run_result.run_id, timeout=36000)

~/Library/Python/3.7/lib/python/site-packages/kfp/_client.py in wait_for_run_completion(self, run_id, timeout)
    597     while status is None or status.lower() not in ['succeeded', 'failed', 'skipped', 'error']:
    598       get_run_response = self._run_api.get_run(run_id=run_id)
--> 599       status = get_run_response.run.status
    600       elapsed_time = (datetime.now() - start_time).seconds
    601       logging.info('Waiting for the job to complete...')

AttributeError: 'NoneType' object has no attribute 'status'
```

Note that the 1 hour limitation seems very deterministic. My initial investigation pointed to the `gcloud auth print-access-token` we use [here](https://github.com/kubeflow/pipelines/blob/de0747ec8b9a4d4a412457004b3bbac2cea2e6a4/sdk/python/kfp/_auth.py#L40) Note that by default GCP access token has an expiration time of 1 hour, which will cause authorization issue during the long waiting.

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

Hosted CAIP pipeline in GKE MKP.

KFP version: 
0.5.0

KFP SDK version: 
0.5.0

Though I believe other version might have the same issue.

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug
/priority p1
/area sdk
/area backend

**Comment by numerology** [comment]
/assign @numerology 
/assign @jingzhang36 

I believe here two things can be done to improve this (and perhaps, avoid similar issues from happening in the future):

1. Fix the authorization mechanism in SDK by adding refresh.
2. Currently our backend does not seem to return error when something wrong happen. Is there a way to improve the debugging experience by adding proper error message when responding to client request?

**Comment by Bobgy** [comment]
> Currently our backend does not seem to return error when something wrong happen. Is there a way to improve the debugging experience by adding proper error message when responding to client request?

Is this related to our backend? I think authorization checks happen at Google Cloud inverse proxy? Or do you mean the client should check if returned data is correct?

**Comment by numerology** [comment]
> > Currently our backend does not seem to return error when something wrong happen. Is there a way to improve the debugging experience by adding proper error message when responding to client request?
> 
> Is this related to our backend? I think authorization checks happen at Google Cloud inverse proxy? Or do you mean the client should check if returned data is correct?

Yes sorry I meant the client. For example, check the response integrity before looking into `response.run`

**Comment by numerology** [comment]
If no one is currently working on that I'll take a look at option 1 in https://github.com/kubeflow/pipelines/issues/3630#issuecomment-620070449 this week.

**Comment by Bobgy** [comment]
Thanks @numerology !
option 1 sounds good
