### ISSUE TITLE
[Cache-deployer] Verify that re-running the deployer does not break the installation

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#3633]
Running the deployer multiple times seems to be breaking the installation (leading to TLS handshake errors in the server).

We need to investigate this and fix any problems.

For now, I'll make a change to prevent deployer re-running.

https://pantheon.corp.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22aju-vtests2%22%0Aresource.labels.location%3D%22us-central1-c%22%0Aresource.labels.cluster_name%3D%22kfp-test2%22%0Aresource.labels.namespace_name%3D%22kubeflow%22%0Aresource.labels.pod_name%3D%22cache-deployer-deployment-5d9b5cb487-wk2q8%22%0Aresource.labels.container_name%3D%22main%22;timeRange=2020-04-25T17:52:01.391Z%2F2020-04-26T17:00:00.000Z?project=aju-vtests2

https://pantheon.corp.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22aju-vtests2%22%0Aresource.labels.location%3D%22us-central1-c%22%0Aresource.labels.cluster_name%3D%22kfp-test2%22%0Aresource.labels.namespace_name%3D%22kubeflow%22%0Aresource.labels.pod_name%3D%22cache-server-75f88895c-7pn78%22%0Aresource.labels.container_name%3D%22server%22;timeRange=P7D?project=aju-vtests2

**Comment by Bobgy** [comment]
@Ark-kun did you think your fix is a long term solution or a quick hack? Do we need to verify this again?
