### ISSUE TITLE
No default pipeline version value when cloning a pipeline run via UI

### ISSUE THREAD

**Issue by wzhou18** [kubeflow/pipelines#3643]
### What steps did you take:
1. In KFP UI, clone an existing pipeline run which does not have pipeline version 
2. The pipeline version field on UI is empty, and UI will force users to choose Pipeline Version field
3. After users choose a pipeline version, the UI will clear all the pipeline parameters values.

### What happened:
When cloning a pipeline run which does not have a pipeline version, the UI will force the user to select a pipeline version. After pipeline version is selected, the UI will clear all the values of the pipeline parameters.

### What did you expect to happen:
When users clone a pipeline run which does not have a pipeline version, KFP UI should automatically pick up the pipeline id as the pipeline version for users, instead of forcing users to choose one and clear out pipeline parameters after specifying pipeline version.

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

KFP version: 
0.2.5

KFP SDK version: 
0.1.34

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by rmgogogo** [comment]
@jingzhang36 is current behavior bydesign for the case user update version but want to clone other parameters for a quick run?
