### ISSUE TITLE
Does pipelines only support  on GKE?  And the workflow run with some problem.

### ISSUE THREAD

**Issue by hackenzheng** [kubeflow/pipelines#365]
1. I tried deployed pipeline on my local k8s cluster, but there are many problems. And the document just introduce the deployment on GKE.  Does pipeline only suport GKE?
2. As below, when I ran the samples/kubeflow-tf/kubeflow-training-classification.py, the preprocess node ran failed but the sign goes to green means it successful?
![image](https://user-images.githubusercontent.com/16522546/48889988-86336e00-ee72-11e8-8cb1-a8877030a45f.png)

**Comment by etheleon** [comment]
Hi i ran into the same error message.

**Comment by paveldournov** [comment]
The samples are currently GKE/GCP specific, they expect inputs as GCS locations for example. +@qimingj

**Comment by Ark-kun** [comment]
@yebrahim The error messages look a bit strange.

**Comment by govindKAG** [comment]
The docs on the site say that it currently only works with GCP.

**Comment by jlewi** [comment]
@paveldournov @vicaire @Ark-kun Can we close this issue? Do the docs still state that GKE is required?

We are using labels [platform/other](https://github.com/kubeflow/pipelines/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Aplatform%2Fother+) and [platform/aws](https://github.com/kubeflow/pipelines/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Aplatform%2Faws+) to track issues affecting specific platforms.

**Comment by vicaire** [comment]
@jlewi, I added the label "platform/other".

@hackenzheng, is our issue resolved? 

@govindKAG, please provide a reference to the problematic document so we can fix. KFP aims to run reliably on K8, independently of GCP.

**Comment by jlewi** [comment]
I think the relevant doc is
https://www.kubeflow.org/docs/pipelines/pipelines-overview/

And the snippet is

>> Due to kubeflow/pipelines#345 and kubeflow/pipelines#337, Kubeflow Pipelines depends on Google Cloud Platform (GCP) services and some of the functionality is currently not supported by non-GKE clusters.

**Comment by hackenzheng** [comment]
Yeah, the problem has been solved . Now kfp provides a simple way to deploy on any k8s cluster.

**Comment by govindKAG** [comment]
@vicaire I was referring to the link that @jlewi mentioned

**Comment by vicaire** [comment]
Thanks @govindKAG. 

@sarahmaddox, you have an issue tracking the update of the documentation, correct?

**Comment by sarahmaddox** [comment]
Yes, here's the doc issue:
https://github.com/kubeflow/website/issues/655
