### ISSUE TITLE
FR: allow capital letters in metrics`name` (for pipeline viz)

### ISSUE THREAD

**Issue by amygdala** [kubeflow/pipelines#3655]
See this issue for some background: https://github.com/kubeflow/pipelines/issues/3309.

It would be more robust to be able to use both caps and lower-case letters in the metrics name, not just lower-case.
The docs do [describe](https://www.kubeflow.org/docs/pipelines/sdk/pipelines-metrics/#export-the-metrics-file) this constraint, but it's not very intuitive or easy to notice, and if there is no reason for the restriction, it would helpful to allow caps as well.  (cc @hongye-sun )

(Side note that probably needs its own bug: in that docs page, it states that the file path must be `/mlpipeline-metrics.json`, but that does not seem to be true any more, as I was able to use that `OutputPath()` construct instead. Same goes for the metadata path).

**Comment by rmgogogo** [comment]
I'm wondering whether we depriotize the "mlpipeline-metrics" usage but more on TFX + MLMD and metrics in MLMD/TB.

@Bobgy

**Comment by Bobgy** [comment]
@rmgogogo currently MLMD metrics can not get shown in UI in a list. So I think we cannot fully deprioritize pipeline metrics

We may need to have a separate discussion on how many KFP features we want to be MLMD driven instead.

**Comment by Bobgy** [comment]
The restriction is in https://github.com/kubeflow/pipelines/blob/81341d3aa67268d25d8c5ae1dc31df2e59e610b8/backend/src/apiserver/server/run_metric_util.go#L27.
