### ISSUE TITLE
Disable caching for run-diagnose-me

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#3660]
But we probably still need the rest of the pipeline cached.

**Comment by rmgogogo** [comment]
can user codes set cache=false to certain step?
TFX SDK can't now but the design can.

**Comment by Ark-kun** [comment]
It's possible to do that in a KFP pipeline.

**Comment by Bobgy** [comment]
hmmm, this is not a pr

**Comment by SinaChavoshi** [comment]
Going through my bug back log, I'm not clear on the request on this issue is, diagnose_me does not cache data.  It always reads from current local/remote configuration. Closing the issue, if this is still relevant please reopen and add a comment on which data fields are being cached.
