### ISSUE TITLE
dataproc-create-cluster fails in XGBoost postsubmit test

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#3661]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/kubeflow-pipeline-postsubmit-integration-test/1255639085989498882
```
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/discovery/v1/apis/dataproc/v1/rest
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	INFO:root:Fetching latest pod metadata: xgboost-trainer-qkfx9-3906020698.
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	INFO:root:Start KFP context with ID: 209d8a58c298bad3d2651012dd334c57.
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	INFO:root:Cluster Details: https://console.cloud.google.com/dataproc/clusters/xgb-73f15525-e7d3-4cfa-93fe-2f9db382f64a?project=ml-pipeline-test&region=us-central1
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	INFO:googleapiclient.discovery:URL being requested: POST https://dataproc.googleapis.com/v1/projects/ml-pipeline-test/regions/us-central1/clusters?alt=json&requestId=209d8a58c298bad3d2651012dd334c57
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	INFO:googleapiclient.discovery:URL being requested: GET https://dataproc.googleapis.com/v1/projects/ml-pipeline-test/regions/us-central1/operations/00042658-663d-3891-8145-faafaea24e12?alt=json
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	INFO:root:Operation projects/ml-pipeline-test/regions/us-central1/operations/00042658-663d-3891-8145-faafaea24e12 is not done. Wait for 30s.
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	INFO:googleapiclient.discovery:URL being requested: GET https://dataproc.googleapis.com/v1/projects/ml-pipeline-test/regions/us-central1/operations/00042658-663d-3891-8145-faafaea24e12?alt=json
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	INFO:root:Operation projects/ml-pipeline-test/regions/us-central1/operations/00042658-663d-3891-8145-faafaea24e12 is not done. Wait for 30s.
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	INFO:googleapiclient.discovery:URL being requested: GET https://dataproc.googleapis.com/v1/projects/ml-pipeline-test/regions/us-central1/operations/00042658-663d-3891-8145-faafaea24e12?alt=json
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	INFO:root:Operation projects/ml-pipeline-test/regions/us-central1/operations/00042658-663d-3891-8145-faafaea24e12 is not done. Wait for 30s.
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	INFO:googleapiclient.discovery:URL being requested: GET https://dataproc.googleapis.com/v1/projects/ml-pipeline-test/regions/us-central1/operations/00042658-663d-3891-8145-faafaea24e12?alt=json
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	INFO:root:Operation projects/ml-pipeline-test/regions/us-central1/operations/00042658-663d-3891-8145-faafaea24e12 is not done. Wait for 30s.
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	INFO:googleapiclient.discovery:URL being requested: GET https://dataproc.googleapis.com/v1/projects/ml-pipeline-test/regions/us-central1/operations/00042658-663d-3891-8145-faafaea24e12?alt=json
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	INFO:root:Operation projects/ml-pipeline-test/regions/us-central1/operations/00042658-663d-3891-8145-faafaea24e12 is not done. Wait for 30s.
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	INFO:googleapiclient.discovery:URL being requested: GET https://dataproc.googleapis.com/v1/projects/ml-pipeline-test/regions/us-central1/operations/00042658-663d-3891-8145-faafaea24e12?alt=json
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	Traceback (most recent call last):
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	  File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	    "__main__", fname, loader, pkg_name)
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	    exec code in run_globals
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	  File "/ml/kfp_component/launcher/__main__.py", line 45, in <module>
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	    main()
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	  File "/ml/kfp_component/launcher/__main__.py", line 42, in main
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	    launch(args.file_or_module, args.args)
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	  File "kfp_component/launcher/launcher.py", line 45, in launch
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	    return fire.Fire(module, command=args, name=module.__name__)
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	  File "/usr/local/lib/python2.7/site-packages/fire/core.py", line 127, in Fire
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	    component_trace = _Fire(component, args, context, name)
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	  File "/usr/local/lib/python2.7/site-packages/fire/core.py", line 366, in _Fire
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	    component, remaining_args)
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	  File "/usr/local/lib/python2.7/site-packages/fire/core.py", line 542, in _CallCallable
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	    result = fn(*varargs, **kwargs)
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	  File "kfp_component/google/dataproc/_create_cluster.py", line 74, in create_cluster
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	    wait_interval)
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	  File "kfp_component/google/dataproc/_create_cluster.py", line 89, in _create_cluster_internal
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	    return _dump_cluster(operation.get('response'))
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	  File "kfp_component/google/dataproc/_create_cluster.py", line 109, in _dump_cluster
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	    cluster.get('clusterName'))
run-integration-tests-loop(0:xgboost_training_cm)(2):	dataproc-create-cluster:	AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by Bobgy** [comment]
I also saw this quite a few times recently. After trying manually it seems xgboost sample fail for 80% of the cases when creating the cluster.
Looking at cloud console UI, the only information is INVALID_ARGUMENT, I'm not sure what went wrong there. I tried creating a dataproc cluster from UI, it works well.

A random guess is, maybe our gcloud cli version is again out of date?

**Comment by Ark-kun** [comment]
>A random guess is, maybe our gcloud cli version is again out of date?

That component does not use gcloud CLI. However it uses the google-cloud-dataproc package that may be out of date.

A random though - maybe there is something wrong with the cluster name... But this can't be happening - the name is alphanumeric and should have the same length every time.

>Looking at cloud console UI, the only information is INVALID_ARGUMENT, I'm not sure what went wrong there.

How can you see that?

@hongye-sun Can you please add some check at that point in code and print the response if its incorrect?

**Comment by Bobgy** [comment]
I copied the sample and removed the exit handler. So after the run I Can still see It in cloud UI

**Comment by hongye-sun** [comment]
% curl -X GET -H "Authorization: Bearer "$(gcloud auth application-default print-access-token) "https://dataproc.googleapis.com/v1/projects/ml-pipeline-test/regions/us-central1/opera
tions/5fbb93bb-c58a-317e-b46d-78bbd58945d7?alt=json"                                                                                                                                   
{                                                                                                                                                                                      
  "name": "projects/ml-pipeline-test/regions/us-central1/operations/5fbb93bb-c58a-317e-b46d-78bbd58945d7",                                                                             
  "metadata": {                                                                                                                                                                        
    "@type": "type.googleapis.com/google.cloud.dataproc.v1.ClusterOperationMetadata",                                                                                                  
    "clusterName": "xgb-1196dc5e-70bc-44b7-9f1e-d6a302773b2a",                                                                                                                         
    "clusterUuid": "bdb5a89f-9a44-464b-aa9c-1d20a8b5c4fd",                                                                                                                             
    "status": {                                                                                                                                                                        
      "state": "DONE",                                                                                                                                                                 
      "innerState": "FAILED",                                                              
      "stateStartTime": "2020-04-30T00:18:08.233Z"                                         
    },                                                                                     
    "statusHistory": [                                                                     
      {     
        "state": "PENDING",                                                                
        "stateStartTime": "2020-04-30T00:16:21.313Z"    
      },                                                                                   
      {                                                                                    
        "state": "RUNNING",                                                                
        "details": "Multiple Errors:\n - Initialization action failed. Failed action 'gs://ml-pipeline-playground/dataproc-example/initialization_actions.sh', see output in: gs://dat$
proc-788e0848-9dd5-4ea6-9b78-eadcb7f5a23d-us-central1/google-cloud-dataproc-metainfo/bdb5a89f-9a44-464b-aa9c-1d20a8b5c4fd/xgb-1196dc5e-70bc-44b7-9f1e-d6a302773b2a-m/dataproc-initiali$
ation-script-0_output\n - Initialization action failed. Failed action 'gs://ml-pipeline-playground/dataproc-example/initialization_actions.sh', see output in: gs://dataproc-788e0848-$
dd5-4ea6-9b78-eadcb7f5a23d-us-central1/google-cloud-dataproc-metainfo/bdb5a89f-9a44-464b-aa9c-1d20a8b5c4fd/xgb-1196dc5e-70bc-44b7-9f1e-d6a302773b2a-w-0/dataproc-initialization-script$
0_output\n - Initialization action failed. Failed action 'gs://ml-pipeline-playground/dataproc-example/initialization_actions.sh', see output in: gs://dataproc-788e0848-9dd5-4ea6-9b7$
-eadcb7f5a23d-us-central1/google-cloud-dataproc-metainfo/bdb5a89f-9a44-464b-aa9c-1d20a8b5c4fd/xgb-1196dc5e-70bc-44b7-9f1e-d6a302773b2a-w-1/dataproc-initialization-script-0_output",   
        "stateStartTime": "2020-04-30T00:16:21.379Z"
      }                       
    ],                               
    "operationType": "CREATE",         
    "description": "Create cluster with 2 workers",                                        
    "warnings": [                                                                          
      "For PD-Standard without local SSDs, we strongly recommend provisioning 1TB or larger to ensure consistently high I/O performance. See https://cloud.google.com/compute/docs/dis$
s/performance for information on disk I/O performance.",                                   
      "Cluster xgb-1196dc5e-70bc-44b7-9f1e-d6a302773b2a failed to create. Beginning automated resource cleanup process."                                                               
    ]                                
  },                                                                                       
  "done": true,
  "error": {   
    "code": 3,                       
    "message": "Multiple Errors:\n - Initialization action failed. Failed action 'gs://ml-pipeline-playground/dataproc-example/initialization_actions.sh', see output in: gs://datapro$
-788e0848-9dd5-4ea6-9b78-eadcb7f5a23d-us-central1/google-cloud-dataproc-metainfo/bdb5a89f-9a44-464b-aa9c-1d20a8b5c4fd/xgb-1196dc5e-70bc-44b7-9f1e-d6a302773b2a-m/dataproc-initializati$
n-script-0_output\n - Initialization action failed. Failed action 'gs://ml-pipeline-playground/dataproc-example/initialization_actions.sh', see output in: gs://dataproc-788e0848-9dd5$
4ea6-9b78-eadcb7f5a23d-us-central1/google-cloud-dataproc-metainfo/bdb5a89f-9a44-464b-aa9c-1d20a8b5c4fd/xgb-1196dc5e-70bc-44b7-9f1e-d6a302773b2a-w-0/dataproc-initialization-script-0_o$
tput\n - Initialization action failed. Failed action 'gs://ml-pipeline-playground/dataproc-example/initialization_actions.sh', see output in: gs://dataproc-788e0848-9dd5-4ea6-9b78-ea$
cb7f5a23d-us-central1/google-cloud-dataproc-metainfo/bdb5a89f-9a44-464b-aa9c-1d20a8b5c4fd/xgb-1196dc5e-70bc-44b7-9f1e-d6a302773b2a-w-1/dataproc-initialization-script-0_output"        
  }                                                                                        
}

**Comment by hongye-sun** [comment]
% gsutil cat gs://dataproc-788e0848-9dd5-4ea6-9b78-eadcb7f5a23d-us-central1/google-cloud-dataproc-metainfo/bdb5a89f-9a44-464b-aa9c-1d20a8b5c4fd/xgb-1196dc5e-70bc-44b7-9f1e-d6a302773b
2a-m/dataproc-initialization-script-0_output
Searching for pip
Reading https://pypi.python.org/simple/pip/
Download error on https://pypi.python.org/simple/pip/: [Errno 101] Network is unreachable -- Some packages may not be found!
Couldn't find index page for 'pip' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or working download links found for pip
error: Could not find suitable distribution for Requirement.parse('pip')

**Comment by hongye-sun** [comment]
It appears that the pypi index page is unable to reach from a dataproc cluster. I do find a bug in dataproc component code that didn't properly handle error case. I will send a fix.

**Comment by hongye-sun** [comment]
I sent a fix for the error handling of LRO but it won't help with the pypi index issue. 

The pypi might be a temporary outage and I don't see it happening in recent failure: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/kubeflow-pipeline-postsubmit-integration-test/1255822418711154690

It seems to be other errors causing the test failure.

**Comment by Ark-kun** [comment]
> It appears that the pypi index page is unable to reach from a dataproc cluster. I do find a bug in dataproc component code that didn't properly handle error case. I will send a fix.

Thanks for investigating and fixing the code, Hongye and Yuan.
