### ISSUE TITLE
Support for an event-driven architecture

### ISSUE THREAD

**Issue by jhagege** [kubeflow/pipelines#3664]
Hi, is there any possibility to integrate a KFP with an event-driven architecture ?
I'd like to have steps in the pipeline trigger external jobs on different infra and block until those jobs communicate their response through existing pubsub infrastructure.
Then on successful receival of a response message, unblock the step and pass him the result from the pubsub message.
Can you think of any possibility to handle it, or alternatively suggest a better-fitted pattern for such flows ? 
Thanks.

**Comment by rmgogogo** [comment]
which SDK? 
TFX SDK: https://github.com/tensorflow/tfx/tree/master/tfx/examples/custom_components/slack
here is a sample.

KFP SDK is more flexible. Just the step will be hold there until meet conditions.

Another solution (preferred): don't handle it in-pipeline-steps, but handle it out of pipeline. 
You can divide your pipeline to two/multi parts when need to talk with external systems.

A trigger (e.x. in CloudFunction or your own binary) helps listen external system and create pipeline runs. 
Last step of a pipeline call/send msg to external system to trigger runs.

**Comment by rmgogogo** [comment]
The KFP it self still is DAG styled and no short term plan to change it to be fully event-driven.
