### ISSUE TITLE
Intermittent 503 and 504 errors when querying API to get runs and submit runs 

### ISSUE THREAD

**Issue by thebinaryone1** [kubeflow/pipelines#3669]
### What steps did you take:
I spawn multiple pipelines in parallel and monitors their status. 

### What happened:
Getting 504 errors intermittently. I have a 5s wait between calls, but that doesn't seem to help much.

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?
GCP AI Platform Pipelines

KFP version:  743746b

KFP SDK version: 0.3.0

/kind bug
/area backend
/area sdk

Logs from the API Server :
![image](https://user-images.githubusercontent.com/23407392/80770204-84101d00-8b04-11ea-91a8-fc2faaf4a78c.png)

**Comment by thebinaryone1** [comment]
![image](https://user-images.githubusercontent.com/23407392/80770333-d9e4c500-8b04-11ea-9715-a9ac5b02cc94.png)

**Comment by thebinaryone1** [comment]
Stack trace :

panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12f9bc4] goroutine 208 [running]: github.com/kubeflow/pipelines/backend/src/apiserver/resource.OverrideParameterWithSystemDefault(0xc000d83800, 0xc0006d35f0, 0xf, 0x0) backend/src/apiserver/resource/resource_manager_util.go:209 +0x2e4 github.com/kubeflow/pipelines/backend/src/apiserver/resource.(*ResourceManager).CreateRun(0xc0003e21c0, 0xc0006d35f0, 0xc000aafb60, 0xc000ac60b0, 0x1) backend/src/apiserver/resource/resource_manager.go:290 +0x2d6 github.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).CreateRun(0xc000840038, 0x1941ba0, 0xc000aafb60, 0xc000aafb90, 0xc000840038, 0x1, 0x1) backend/src/apiserver/server/run_server.go:43 +0xc5 github.com/kubeflow/pipelines/backend/api/go_client._RunService_CreateRun_Handler.func1(0x1941ba0, 0xc000aafb60, 0x1696ce0, 0xc000aafb90, 0x1, 0x0, 0xc000a58000, 0x0) bazel-out/k8-opt/bin/backend/api/linux_amd64_stripped/go_client_go_proto%/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:1269 +0x86 main.apiServerInterceptor(0x1941ba0, 0xc000aafb60, 0x1696ce0, 0xc000aafb90, 0xc000a57140, 0xc000a57160, 0x15a5ec0, 0x25ad330, 0x171cca0, 0xc000048a00) backend/src/apiserver/interceptor.go:30 +0xf4 github.com/kubeflow/pipelines/backend/api/go_client._RunService_CreateRun_Handler(0x16c95e0, 0xc000840038, 0x1941ba0, 0xc000aafb60, 0xc000abbbd0, 0x18060e0, 0x0, 0x0, 0xc000d5e000, 0x42b9) bazel-out/k8-opt/bin/backend/api/linux_amd64_stripped/go_client_go_proto%/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:1271 +0x158 google.golang.org/grpc.(*Server).processUnaryRPC(0xc00077e900, 0x194ea40, 0xc000980000, 0xc000048a00, 0xc00025e3f0, 0x2527f80, 0x0, 0x0, 0x0) external/org_golang_google_grpc/server.go:966 +0x4a2 google.golang.org/grpc.(*Server).handleStream(0xc00077e900, 0x194ea40, 0xc000980000, 0xc000048a00, 0x0) external/org_golang_google_grpc/server.go:1245 +0xd61 google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00016a190, 0xc00077e900, 0x194ea40, 0xc000980000, 0xc000048a00) external/org_golang_google_grpc/server.go:685 +0x9f created by google.golang.org/grpc.(*Server).serveStreams.func1 external/org_golang_google_grpc/server.go:683 +0xa1

**Comment by thebinaryone1** [comment]
![image](https://user-images.githubusercontent.com/23407392/80772307-19161480-8b0b-11ea-9bf3-b80e5d5a1793.png)


This looks to be the root cause, since the timing of crashes matches with the error requests.

**Comment by thebinaryone1** [comment]
Found the root cause : The issue was due to a kfp api version mismatch.
The client (0.5.0) was using a pipeline zip package compiled using 0.2.0 to start a run.

It would be nice to check this in the sdk or the api server instead of crashing the api server.

**Comment by numerology** [comment]
/assign @jingzhang36 
I roughly remember version check is already on our radar, right? Thanks @thebinaryone1

**Comment by rmgogogo** [comment]
Is it back to normal?

**Comment by Bobgy** [comment]
Thanks for the report! Even if version doesn't match, I think api server shouldn't crash and restart.
@jingzhang36 we should fix the crash too.

/cc @Ark-kun @numerology 
I think api server should be backward compatible for 0.2.0 compiled package, is my understanding right? Is this an intended backward incompatible change or a regression?

**Comment by jingzhang36** [comment]
A quick summary, @thebinaryone1 used KFP SDK 0.2.0 to compile a pipeline to a zip file and then used the zip file to create a run with KPF SDK 0.5.0. Then at the method OverrideParameterWithSystemDefault(...) a segmentation error is thrown.

**Comment by jingzhang36** [comment]
@thebinaryone1 do you mind providing me with the pipeline zip compiled with KFP SDK 0.2.0? So I can test with it. If the pipeline is confidential, do you mind removing the confidential parts and recompiling it with 0.2.0 and providing me the new pipeline zip? Thanks!

**Comment by Ark-kun** [comment]
> Found the root cause : The issue was due to a kfp api version mismatch.
> The client (0.5.0) was using a pipeline zip package compiled using 0.2.0 to start a run.

This should not be the case. The compiler has very broad backwards compatibility.
