### ISSUE TITLE
KFP UI truncates long parameter names in the "Input/Output" Tab

### ISSUE THREAD

**Issue by sadeel** [kubeflow/pipelines#3677]
### What steps did you take:
See "saved_model_path"

![z0sy5b68yTE](https://user-images.githubusercontent.com/5696932/80919470-02083a00-8d38-11ea-83bb-6d0d88b47ca4.png)

### What happened:
Unable to read the entire parameter
### What did you expect to happen:
It looks like there is a lot of space there, I expected the path to be readable.

### Environment:
Hosted KFP

How did you deploy Kubeflow Pipelines (KFP)?

KFP version: 

KFP SDK version: 

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by Ark-kun** [comment]
Did you mean values, rather than names?
@Bobgy Maybe we can increase the value truncation length.

As a workaround, all output values can be accessed in the Output Artifacts section.

**Comment by Bobgy** [comment]
This is surely something we want to address. Thanks for reporting!

**Comment by Bobgy** [comment]
Actually, I'll close this, because it's part of https://github.com/kubeflow/pipelines/issues/2897.
/close
