### ISSUE TITLE
Error running basic sample

### ISSUE THREAD

**Issue by jhagege** [kubeflow/pipelines#3678]
Hi, when following the quickstart, I get the following issue when running the Parallel pipeline:

![image](https://user-images.githubusercontent.com/7504908/80927014-aa071d00-8da3-11ea-9661-f95a8740c43e.png)

Any idea how to solve ? 
Thanks.

**Comment by Ark-kun** [comment]
Generally this error often indicates that the service account does not have permission to access the bucket.
How did you install KFP (Google Cloud Marketplace or command-line)?
The bucket should be public, so there should not be any errors. @numerology @Bobgy WDYT?

**Comment by jhagege** [comment]
Hi, thanks it was deployed through deploy.kubeflow URL with GCP IAP.

Could it be related to that I created another cluster before, deleted and
recreated ?

Maybe some leftovers from previous deployment are causing issues ?
What should I do to totally cleanup previous deployment ?

**Comment by numerology** [comment]
@jhagege 

I think it's also possible due to special permission configuration of the url that the pipeline is trying to download from. Are you trying with the default `gs://ml-pipeline-playground/shakespeare1.txt` and `gs://ml-pipeline-playground/shakespeare2.txt` or trying to download from your own buckets? Thanks

**Comment by Bobgy** [comment]
@jhagege a quick guess, did you deploy Kubeflow 1.0.0 or 1.0.1?
GCP permission bindings were automatically set up starting from Kubeflow 1.0.2, see https://github.com/kubeflow/kubeflow/issues/4803.

**Comment by jhagege** [comment]
> @jhagege a quick guess, did you deploy Kubeflow 1.0.0 or 1.0.1?
> GCP permission bindings were automatically set up starting from Kubeflow 1.0.2, see [kubeflow/kubeflow#4803](https://github.com/kubeflow/kubeflow/issues/4803).

Thanks for the reply, I deployed 1.0.0 with kubeflow deploy on GCP tool. 
Any option to deploy 1.0.2 with this tool ? 
Thanks.

**Comment by Bobgy** [comment]
@jhagege Did you use https://deploy.kubeflow.cloud/#/deploy?

I'm afraid it only supports 1.0.0, I'd suggest deploying through CLI: https://www.kubeflow.org/docs/gke/deploy/deploy-cli/

It will be relatively easy if you have already successfully deployed through UI, some setups like oauth client id and secret can be the same one as in UI.

**Comment by Bobgy** [comment]
Duplicates kubeflow/kubeflow#4803.
/close
