### ISSUE TITLE
'Clone run' does not update kfp.dsl.RUN_ID_PLACEHOLDER

### ISSUE THREAD

**Issue by sadeel** [kubeflow/pipelines#3681]
### What steps did you take:
I use kfp.dsl.RUN_ID_PLACEHOLDER to generate unique artifacts per run. I noticed that when I use the 'Clone Run' button, kfp.dsl.RUN_ID_PLACEHOLDER is set to the original run's ID, rather than the new one for the cloned run. 

### What happened:
kfp.dsl.RUN_ID_PLACEHOLDER not updated
### What did you expect to happen:
kfp.dsl.RUN_ID_PLACEHOLDER to be updated
### Environment:
Hosted KFP
How did you deploy Kubeflow Pipelines (KFP)?

KFP version: 

KFP SDK version: 

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by Ark-kun** [comment]
@IronPan If I remember correctly, the backend replaces the `{{workflow.uid}}` placeholders before the run submission. If we left them as is, then the Clone feature would work as expected in this scenario.

**Comment by Bobgy** [comment]
@Ark-kun When UI clones a run, it copies the run's arguments. `{{workflow.uid}}` was already replaced in the workflow's argument to work properly. If backend doesn't replace it, can the workflow get correct value?

**Comment by Bobgy** [comment]
One workaround (tedious) can be: when cloning the run, manually replace the workflow.uid back to {{workflow.uid}}
