### ISSUE TITLE
[FR] Implement optional component level usage tracking

### ISSUE THREAD

**Issue by numerology** [kubeflow/pipelines#3687]
As #3578 checked in, we have an example of how to set beacon to collect critical usage information to help us make the right business decision, without compromising user privacy.

One natural extension of that work is to instrument telemetry of our first-party components shipped with KFP. To be concrete, the proposed scope includes components under [1]. We can consider whether/how to include user-defined component later on.

Still my proposed approach will be facilitated by pod labels append to each ContainerOp.

1. We establish a whitelisting dictionary, only including first-party components; I am considering using the component url as signature.
2. In [2], when loading a component, we'll append telemetry pod labels, which will then surfaced in GKE.
3. We provide toggle to allow users to opt out this collection, at both component loading, and compiler.

[1] https://github.com/kubeflow/pipelines/tree/master/components

[2] https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/components/_components.py

Any input will be very helpful :) @Ark-kun @rmgogogo

**Comment by Ark-kun** [comment]
I want to note that the SDK already adds the `pipelines.kubeflow.org/component_spec` pod annotation for every component. This information includes the hole component definition, but does not contain the URI.
Adding `pipelines.kubeflow.org/component_ref` annotation that often contains the `.uri` attribute would be pretty trivial and also useful for UX.

P.S. Adding `pipelines.kubeflow.org/task_spec` is also an option. It will contain both `component_ref` and `arguments` which will fix the issue with input parameters experienced by the Metadata Writer.

>at both component loading

I'm not sure this is necessary. The annotation of pods is performed by the compiler, not the component loader.

**Comment by numerology** [comment]
> I want to note that the SDK already adds the pipelines.kubeflow.org/component_spec pod annotation

Thanks.IIRC we only have pod annotation for those information, right? For technical reason I think adding corresponding pod labels will be necessary. Do you see any problem with adding a pod label including part of the information in component_spec?

**Comment by Ark-kun** [comment]
> Do you see any problem with adding a pod label including part of the information in component_spec?

We can try to add some label, but it's not trivial. You cannot really put, say, a URL in a label. Or anything substantial. The size is limited to 63 mostly alphanumerical characters (so even some hashes do not fit). https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set

**Comment by numerology** [comment]
Thanks. I think we shall be smart about what to put in that label. Let me think about how to better leverage the 63 character budget.

**Comment by Ark-kun** [comment]
> Thanks. I think we shall be smart about what to put in that label. Let me think about how to better leverage the 63 character budget.

Technically, every component has a natural digest (SHA256 of the serialized ComponentSpec that was loaded from file or URL). SHA256 fits in the label. But associating it with a particular component version would be non-trivial.

We can also base-64 encode the component URL if it's not too long.

**Comment by rmgogogo** [comment]
qq: here it all for KFP SDK's component, right?

**Comment by numerology** [comment]
@rmgogogo  Yes that's what I am thinking

**Comment by Ark-kun** [comment]
Every pod created from a component now has the `component_ref` annotation in addition to the full `component_spec` annotation (which included component name and inputs/outputs).
```
annotations:
    pipelines.kubeflow.org/component_ref: '{
        "digest": "98381958ba8b0d2b83a23a78f482f08b48e665409820b3a6254bccdbcf206df3",
        "url": "https://raw.githubusercontent.com/kubeflow/pipelines/b3179d86b239a08bf4884b50dbf3a9151da96d66/components/gcp/automl/create_dataset_for_tables/component.yaml"
    }'

```

**Comment by numerology** [comment]
Thanks @Ark-kun . However we still need pod labels to do something similar because pod annotations do not persist in the internal GKE log.
