### ISSUE TITLE
Strange "Error 401 (Unauthorized)!!1" when submitting runs, but not with other APIs.

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#3688]
Submitting pipelines using `kfp.Client(host=kfp_endpoint).create_run_from_pipeline_func(pipeline, arguments={})` suddenly stopped working. It worked great just this morning. I have not updated the cluster or SDK or anything else. I've tried re-running a recent notebook and it also started failing.

A weird thing is that listing runs does not fail: `kfp.Client(host=kfp_endpoint).runs.list_runs()`.
Another weird thing is that the error seems to come from Google, not my cluster.

The error I'm getting:
```
...

~/kfp/sdk/python/kfp/_client.py in run_pipeline(self, experiment_id, job_name, pipeline_package_path, params, pipeline_id, version_id)
    403         pipeline_spec=job_config.spec, resource_references=job_config.resource_references, name=job_name)
    404 
--> 405     response = self._run_api.create_run(body=run_body)
    406 
    407     if self._is_ipython():

...

~/.local/lib/python3.5/site-packages/kfp_server_api/rest.py in request(self, method, url, query_params, headers, body, post_params, _preload_content, _request_timeout)
    226 
    227         if not 200 <= r.status <= 299:
--> 228             raise ApiException(http_resp=r)
    229 
    230         return r

ApiException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'X-Xss-Protection': '0', 'X-Frame-Options': 'SAMEORIGIN', 'X-Content-Type-Options': 'nosniff', 'Date': 'Wed, 06 May 2020 01:24:09 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '1452', 'Set-Cookie': 'S=cloud_datalab_tunnel=wDLDslTO0CzR204H7_evCuJ-YgbpzSfFtNEI0TolqX0; Path=/; Max-Age=3600'})
HTTP response body: 
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 401 (Unauthorized)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/logos/errorpage/error_logo-150x54.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/logos/errorpage/error_logo-150x54-2x.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/logos/errorpage/error_logo-150x54-2x.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/logos/errorpage/error_logo-150x54-2x.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>401.</b> <ins>That’s an error.</ins>
  <p>  <ins>That’s all we know.</ins>
```

### Environment:
How did you deploy Kubeflow Pipelines (KFP)?
Marketplace
KFP version: 0.2.4

KFP SDK version: 0.5.0

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by rky0930** [comment]
Same problem here.

**Comment by muik** [comment]
> I have the same problem.

Environment:
Kubeflow Pipielines 0.3.0 standalone on GKE

**Comment by Bobgy** [comment]
I just tried 0.5.0, but cannot reproduce it.
Maybe I need to try a lower version.

**Comment by Ark-kun** [comment]
> I just tried 0.5.0, but cannot reproduce it.
> Maybe I need to try a lower version.

Maybe it's the timing e.g. something has expired.

**Comment by Bobgy** [comment]
@Ark-kun Can you still reproduce?

**Comment by Ark-kun** [comment]
> @Ark-kun Can you still reproduce?

Yes. Just checked.

**Comment by numerology** [comment]
@Ark-kun 
Does it help to do `gcloud auth login` manually in the same environment?

**Comment by Ark-kun** [comment]
gsutil works fine and gcloud auth print-access-token also works.
All client methods I've tried do work (list_runs, list_experiments, get_experiment). Only create_run fails for some reason.

**Comment by rmgogogo** [comment]
Seems same issue hit by Jun.
I didn't reproduce it in 0.5.0

Alexy, would you help give me the access to your project and tell the instance?

**Comment by rmgogogo** [comment]
I can reproduce it with SDK 0.5.0 to Server 0.5.0 via Ark-kun's codes:

```
import kfp
from kfp.components import create_component_from_func

@create_component_from_func
def produce() -> str:
    return "produced data"

def pipeline():
    produce()

kfp_endpoint='https://1072fa24cb99ae4c-dot-us-central2.pipelines.googleusercontent.com'
print(kfp.Client(host=kfp_endpoint).list_experiments())

kfp.Client(host=kfp_endpoint).create_run_from_pipeline_func(pipeline, arguments={})
```

**Comment by rmgogogo** [comment]
> @Ark-kun Can you still reproduce?

Hi Yuan, 
Can your side still work? If it can, would you share the SDK version and Server version?

**Comment by numerology** [comment]
I can reproduce on my own project and kfp deployment, with both SDK and deployment of version 0.5.0

**Comment by rmgogogo** [comment]
Per friend team's info, a P0 issue happening in us-central1/2. 
Wondering whether Yuan's test is in another region. I'm verifying us-west region to see if it can work.

**Comment by Bobgy** [comment]
I was verifying in asia-east1-c, I guess that's why

**Comment by numerology** [comment]
Looks like us-central1 and 2 are impacted. @rky0930 @muik Can you confirm which region are you testing? Thanks

**Comment by muik** [comment]
> Looks like us-central1 and 2 are impacted. @rky0930 @muik Can you confirm which region are you testing? Thanks

We are using KFP installed in **us-central1-c**.

**Comment by rmgogogo** [comment]
update: friend team is rollback a release to us-central1/2. After that, we will verify again to see if issue gone.

Current finding: it only impact us-central1/2 on HTTP PUT methods (maybe also POST but didn't double verify yet). other regions should be OK.

**Comment by rmgogogo** [comment]
Rollback done.

It should can work in all region now.

Verified myside in us-central1-a

**Comment by rmgogogo** [comment]
Here close the issue but feel free to reopen if you still hit issue.

**Comment by rky0930** [comment]
We just checked our KFP in us-central1-c and it works. Thanks for the quick response.
