### ISSUE TITLE
[Multi User] Multi user mode early access release

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#3693]
Part of https://github.com/kubeflow/pipelines/issues/3645

Provide an EAP manifest people can try out right now.

/cc @chensun @IronPan @jlewi 

EDIT:
Instructions doc - KFP multi-user instructions for GCP: https://docs.google.com/document/d/1Ws4X1oNlaczhESNuEanZxbF-cnSfO78B1rBHWOkIAzo/
this is shared with kubeflow community

**Comment by Bobgy** [comment]
I merged kubeflow master to our forked manifest: https://github.com/kubeflow/manifests/pull/1154
Deployed this manifest and verified it works well.

**Comment by Mddct** [comment]
Can this version work on prim k8s？

**Comment by Bobgy** [comment]
@Mddct the design doesn't prevent us from running it on prem, but the first version of implementation requires https://cloud.google.com/iap. Therefore, it cannot be fully on prem.

**Comment by jlewi** [comment]
@Bobgy why is IAP required? Is it just a matter of integrating an identity provider that adds an appropriate JWT to incoming requests?

/cc @yanniszark

**Comment by yanniszark** [comment]
@Bobgy this seems very strange to me.
The Pipelines API Server should be relying on the HTTP Headers being set correctly.
Why do you say that IAP is required, if we can authenticate the user and set headers with the current Dex+AuthService approach?
Is it because the APIServer only looks at the Google-specific header? (https://github.com/kubeflow/pipelines/blob/54c490c07a51c94c67cef37b0fd4a23472ed74c9/backend/src/apiserver/server/util.go#L285)
In other Kubeflow apps, we expose a kubeflow-userid-header and kubeflow-userid-prefix setting, so that it works across environments.

**Comment by Bobgy** [comment]
@jlewi @yanniszark Your understandings are correct, it's only a matter of implementation.

We need to make the header configurable and its content parsable. (currently it must be of form `accounts.google.com:username@xxx.com`, we rely on the `:` to extract user identity).
https://github.com/kubeflow/pipelines/search?q=x-goog-authenticated-user-email&unscoped_q=x-goog-authenticated-user-email

What does the `kubeflow-userid-prefix` setting do? Does it mean the `accounts.google.com:` part?

Do you have capacity to contribute to these and test it with Dex+AuthService? Contributions welcomed.

**Comment by Bobgy** [comment]
Updated instructions doc in issue description

**Comment by shawnzhu** [comment]
> Do you have capacity to contribute to these and test it with Dex+AuthService? Contributions welcomed.

I'm interested since I don't want all Argo workflows runs in `kubeflow` namespace

**Comment by discordianfish** [comment]
Just my 2 cent: This should be make configurable like we do in the centraldashboard and notebook spawner etc.

**Comment by Bobgy** [comment]
@discordianfish Don't worry, it's already made configurable: https://github.com/kubeflow/pipelines/issues/3752.

/close
as early access release is already shared
