### ISSUE TITLE
Maybe bring the frontend code back from kubeflow/frontend

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#3697]
It might be easier to maintain the Kubeflow Pipelines UX code if it's not split between the repos.

**Comment by Bobgy** [comment]
I don't have a strong opinion:
1. I don't find it very troublesome, but it's definitely better if everything is in one repo.
2. I think it depends more on whether any one is still trying to contribute to kubeflow/metadata. If no one is going to maintain it, I think we can just get rid of the shared repo and move it back.

**Comment by Bobgy** [comment]
also
/cc @avdaredevil @jlewi @zhenghuiwang

**Comment by jlewi** [comment]
Who are the primary developers of the frontend? What is the future for the metadata front-end per kubeflow/metadata#225?

**Comment by Bobgy** [comment]
Hi @jlewi, @jingzhang36 and I are primary frontend developers. I don't think Kubeflow pipelines team has any bandwidth to maintain kubeflow/metadata UI. So it's more up-to you or the community if kubeflow/metadata can keep getting maintained.
