### ISSUE TITLE
API-server is constantly failing with ReadArtifact errors trying to read non-existing metrics artifacts

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#3699]
I constantly see these errors  in the stackdriver logs (even when I do not interact with the cluster).

The component mentioned in the log does not have `mlpipeline-metrics` output.

KFP backend v0.2.4

```
020-05-06 00:41:30.389 PDT
"ResourceNotFoundError: artifact runs/2e5e1591-b8b8-4cd0-938f-3b48742b448d/nodes/tfx-pipeline-7zzn4-832547870/artifacts/mlpipeline-metrics not found."
Error
2020-05-06 00:41:30.390 PDT
github.com/kubeflow/pipelines/backend/src/common/util.NewResourceNotFoundError
Error
2020-05-06 00:41:30.390 PDT
backend/src/common/util/error.go:150
Error
2020-05-06 00:41:30.390 PDT
github.com/kubeflow/pipelines/backend/src/apiserver/resource.(*ResourceManager).ReadArtifact
Error
2020-05-06 00:41:30.390 PDT
backend/src/apiserver/resource/resource_manager.go:884
Error
2020-05-06 00:41:30.390 PDT
github.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).ReadArtifact
Error
2020-05-06 00:41:30.390 PDT
backend/src/apiserver/server/run_server.go:151
```

**Comment by rmgogogo** [comment]
@jingzhang36 would you take a look? In TFX SDK path, I think we don't generate mlpipeline-metrics, if so, the BE codes may don't output the logs. Right?

**Comment by Ark-kun** [comment]
Also, most KFP components do not produce metrics either.

**Comment by jingzhang36** [comment]
Seems that mlpipeline-metrics can be optional and some workflow doesn't have. Therefore, not founding this artifact is not necessarily an error. In the Persistent Agent, we report this metrics without checking if the artifact present and hence this error log.

**Comment by jingzhang36** [comment]
@Ark-kun does component explicitly declare the artifacts they actually produce? Or if an artifact that is marked as optional can be considered not present? Otherwise, we'll keep report metrics in Persistent Agent as a best-effort approach.

**Comment by Ark-kun** [comment]
> Seems that mlpipeline-metrics can be optional and some workflow doesn't have. 

That's true. Only a small number of components produce that artifact.

> In the Persistent Agent, we report this metrics without checking if the artifact present and hence this error log.

Maybe we should fix that and check whether the output is present?

**Comment by nlarusstone** [comment]
Is there a workaround for this? We've encountered this error and it's producing an overwhelming amount of logs

**Comment by Bobgy** [comment]
I can try to do a fix next week

**Comment by Bobgy** [comment]
I've been reading through sdk and persistence agent code.
These are my understandings:
* sdk is no longer adding `mlpipeline-metrics.json` to every component
https://github.com/kubeflow/pipelines/blob/f738cb3ac38bc8b2ca485131561cb3ab488b71cd/sdk/python/kfp/dsl/_container_op.py#L939-L945
looks like the documentation is outdated, I don't find code occurrences that keep adding it.
* persistence agent is loading `mlpipeline-metrics.json` unconditionally despite it's declared in the component or not: https://github.com/kubeflow/pipelines/blob/f738cb3ac38bc8b2ca485131561cb3ab488b71cd/backend/src/agent/persistence/worker/metrics_reporter.go#L97

Therefore, I think the correct fix is persistence agent should only read mlpipeline-metrics.json when it exists in a node's output artifacts.

**Comment by Bobgy** [comment]
Hi @nlarusstone, if you want to workaround, you can change your `ml-pipeline-persistenceagent` deployment's image to gcr.io/ml-pipeline-test/112bdfa56ddb54dbc05499d51ba6386362838459/persistenceagent@sha256:bc95106ebc84292652abb41b0088fa55a9b11dd3e6939d70c81b8ba64105568d instead.
