### ISSUE TITLE
Marketplace test does not clean up the global cache-webhook object

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#3701]
This prevents subsequent test runs from working.

The object can be deleted by running `kubectl delete mutatingwebhookconfigurations/cache-webhook`

Maybe we should include the namespace in the name of the webhook to prevent conflicts.

P.S. Is the test supposed to allow multiple parallel runs?

**Comment by rmgogogo** [comment]
copy msg from chat:
1. it's expected to be runable parally
2. the cache-webhook-${NAMESPACE} can't be GCed as it's generated via codes not manifest, didn't set the OwerRef
3. If it can be reused in next install, it would be OK. 
Or propose we remove the L34-37 to let it re-apply again.

WDTY? I'm drafting a PR.

**Comment by Ark-kun** [comment]
> 3\. If it can be reused in next install, it would be OK.
>     Or propose we remove the L34-37 to let it re-apply again.

The webhook config is cluster-scoped, but the content is namespace-specific. (Technically, it's an array of configs, but we haven't tested how they're merged).
If we let next test overwrite it, then the already running test might fail.

We can try setting the owner reference. How should it look like?
