### ISSUE TITLE
Cant create Notebook in GCP, using Kubeflow service account

### ISSUE THREAD

**Issue by pkasson** [kubeflow/pipelines#3708]
Just installed Kubeflow from GCP Marketplace.

When trying to create a notebook, using the auto-created Kubeflow service account, user gets error:

The user does not have access to service account 'Kubeflow-deploy ...'.  Ask the project owner to grant you the iam.serviceAccountUser role on the service account.

Have done that grant and still fails.

**Comment by Bobgy** [comment]
@pkasson Sorry, I don't quite understand the error you are seeing.
Can you provide the url you followed to deploy it?

Kubeflow Pipelines deployed from GCP marketplace doesn't have notebooks.

**Comment by pkasson** [comment]
This was related to creating a notebook in Google cloud (GCP).

If after installing Kubeflow on GCP, you try to create an AI notebook, using the generated service account, it would fail.  There was a step that was missed, which ran a script that applied permissions to the users and service account allowing the notebook to be created ... no longer an issue.
