### ISSUE TITLE
Warning message is confusing when pod logs cannot be retrieved

### ISSUE THREAD

**Issue by jiezhang** [kubeflow/pipelines#3711]
### What steps did you take:
After the pod finishes successfully and is later reclaimed, the following warning is displayed. The message often confuses first-time users, and suggests them to check out the troubleshooting guide.

> Warning: failed to retrieve pod logs. Possible reasons include cluster autoscaling or pod preemption

![image](https://user-images.githubusercontent.com/37601164/81362079-db7a3400-9094-11ea-9e9e-a0417c6a4e0c.png)

### What happened:

In fact, the logs can be viewed in Stackdriver Kubernetes Monitoring.

### What did you expect to happen:

Remove the [warning message](https://github.com/kubeflow/pipelines/blob/master/frontend/src/pages/RunDetails.tsx#L880).

/kind bug
/area frontend

**Comment by Bobgy** [comment]
Thanks for the suggestion!
Sounds reasonable to me.

**Comment by jonasdebeukelaer** [comment]
happy to fix this
/assign @jonasdebeukelaer

**Comment by jonasdebeukelaer** [comment]
oh wait is this already done? i.e. just removing 'troubleshooting guide'?

**Comment by Bobgy** [comment]
@jonasdebeukelaer Thanks for offering help!
This still needs to be done.

Some helpful information for contribution:
1. frontend contribution guide: https://github.com/kubeflow/pipelines/tree/master/frontend
2. Banner component (that shows the troubleshooting link): https://github.com/kubeflow/pipelines/blob/master/frontend/src/components/Banner.tsx
3. Run Details Page's log viewer tab's banner: https://github.com/kubeflow/pipelines/blob/e52481a164e8b7d9a1352c592f51f47c46e4a576/frontend/src/pages/RunDetails.tsx#L472

My suggested UX would be to hide the troubleshooting link when the given banner is a warning (it still shows it when the banner is error), but you can take a look and decide if that feels reasonable to you. It already supports hiding the link on ad-hoc usage: https://github.com/kubeflow/pipelines/blob/master/frontend/src/components/Banner.tsx#L72, so we can also dynamically configure it on usages.

**Comment by jiezhang** [comment]
@Bobgy @jonasdebeukelaer I wonder if it is okay to remove the message completely, or at least lower the level to informational (without the exclamation mark and "Warning" prefix).

**Comment by Bobgy** [comment]
/reopen
I just tested on 1.0.0 and the problem still exists.

Now it shows fail to retrieve pod logs with error message:
```
Error response: Could not get main container logs: Error: Unable to retrieve workflow status: [object Object].
```

We didn't accommodate for the case when workflow was also missing.

**Comment by Bobgy** [comment]
@jonasdebeukelaer do you want to revisit this?
Or I can follow up too

**Comment by jonasdebeukelaer** [comment]
hey @Bobgy should be a quick one to fix so happy to do it. In what situations can a workflow be missing?

**Comment by Bobgy** [comment]
When user configures a TTL to GC workflows. (We have a default TTL of 1day)

In fact, workflow status should be persisted into run details DB rows. So UI shouldn't need to fetch the workflow

**Comment by jonasdebeukelaer** [comment]
hmm makes sense 👍

**Comment by Ark-kun** [comment]
@Bobgy The logs are already persisted to the storage the same way as other artifacts. AFAIK, @eterna2 added support to show these logs in the UX when the pod is not available, but this option is turned off by default. Maybe you can enable this option?

**Comment by Bobgy** [comment]
@Ark-kun this bug: https://github.com/kubeflow/pipelines/issues/3711#issuecomment-666877126 must be fixed before logs can be reused from archive.

**Comment by haydnkeung** [comment]
@Ark-kun How do you enable the option?

**Comment by ConverJens** [comment]
@Ark-kun @Bobgy Is there any update to this? How do you enable log persistence?

**Comment by Bobgy** [comment]
No update yet, we need someone from community to fix this problem.

For us, we are on GCP, so GCP stackdriver auto persists all Kubernetes pod logs.

**Comment by ConverJens** [comment]
@haydnkeung I managed to enable logs persistence.

Check the configmap workflow-controller-configmap and see if archiveLogs: true is set. For me it wasn't, even though I'm on KF 1.1, and I had to set it in the config-map.yaml found in your manifest dir under argo/base.

**Comment by ra312** [comment]
> @haydnkeung I managed to enable logs persistence.
> 
> Check the configmap workflow-controller-configmap and see if archiveLogs: true is set. For me it wasn't, even though I'm on KF 1.1, and I had to set it in the config-map.yaml found in your manifest dir under argo/base.

Dear @ConverJens , did you restart ml-pipeline-ui (kubeflow UX) after editing configmap? Have you resolved the issue?

**Comment by ConverJens** [comment]
@ra312 I actually redeployed all ml-pipieline components apart from Minio and Mysql so I don't know which is required. However, I don't think the UI has anythinh to do with this but rather it's the api server that needs restarting. The UI will simply pick up the logs as any other artifact.

**Comment by ra312** [comment]
Thanks, @ConverJens! I will try to do the same.

**Comment by rohitgujral** [comment]
@ConverJens @ra312 I'm also trying to persist the pipeline pod logs so that if pod gets deleted then logs should be available to the pipeline runs.
I added  `archiveLogs: true` to the argo/base config-map and restarted pipelines deployment but still after deleting the pod, im not seeing logs.

![image](https://user-images.githubusercontent.com/8684157/136512894-44b1463e-ce0e-472c-afc2-f4f56d8eb672.png)

Is there any other step which needs to be done ? 
kubeflow version - 1.0.2 and argo version - 2.3.0

**Comment by ra312** [comment]
closing since the issue has been reported as fixed in https://github.com/kubeflow/pipelines/pull/3848
