### ISSUE TITLE
AWS SageMaker : IAM Roles for Service Account

### ISSUE THREAD

**Issue by akartsky** [kubeflow/pipelines#3718]
Use [IAM Roles for Service Account](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) instead of aws-secret in all AWS SageMaker example pipelines

1] Change the example pipeline code 
2] Change Readme

**Comment by Bobgy** [comment]
/assign @PatrickXYS 
Do you want to take a look?

**Comment by PatrickXYS** [comment]
I think the [PR](https://github.com/kubeflow/pipelines/pull/3719) has addressed the issue and merged.

/close
