### ISSUE TITLE
Error installing package with ks

### ISSUE THREAD

**Issue by texasmichelle** [kubeflow/pipelines#372]
The registry for installing pipelines via ksonnet is formatted differently in `0.1.3-rc.2`. The file [parts.yaml](https://github.com/kubeflow/pipelines/blob/0.1.3-rc.2/pipeline/pipeline/parts.yaml) is missing quotation marks, which ks cannot parse correctly. The [file](https://github.com/kubeflow/pipelines/blob/0.1.2/ml-pipeline/ml-pipeline/parts.yaml) in `0.1.2` works properly.

WIth ks v0.12.0, I get this error:

`$ ks pkg install pipeline/pipeline`
`ERROR resolve registry library: error converting YAML to JSON: yaml: line 15: mapping values are not allowed in this context`

**Comment by texasmichelle** [comment]
Just saw the fix in [kubeflow-1981](https://github.com/kubeflow/kubeflow/pull/1981). Are we planning to keep manifests in both repos? If so, we need to make sure they are kept in sync.

**Comment by vicaire** [comment]
Assuming that this is resolved and closing.
