### ISSUE TITLE
Sagemaker Training Operator throws an error if custom image is not hosted on ECR

### ISSUE THREAD

**Issue by marwan116** [kubeflow/pipelines#3728]
### What steps did you take:
Attempted to run the Sagemaker training operator using a custom image that is not hosted on ECR

### What happened:
I got the following error:
```
Exception: Invalid training image. Please provide a valid Amazon Elastic Container Registry path of the Docker image to run.
```

### What did you expect to happen:
Our CI/CD pipeline is set up to push images to our own personal registry that is not hosted on ECR - ideally, I would want to run Sagemaker training jobs using images hosted from our personal registry instead of having to also push our images to ECR (much more error-prone + having to maintain two container registries ...)

How did you deploy Kubeflow Pipelines (KFP)?
Deployed kubeflow piplines as part of kubeflow deployment on AWS EKS

**Comment by gautamkmr** [comment]
Thank you @marwan116  for trying out the operator. Currently SageMaker has support for images hosted in ECR only. 
SageMaker has support for various frameworks like TensorFlow, XGBoost, PyTorch etc as well as some [in-built algorithms](https://docs.aws.amazon.com/sagemaker/latest/dg/algos.html).

If you have custom image, [here](https://docs.aws.amazon.com/AmazonECR/latest/userguide/docker-push-ecr-image.html) is the instruction to put them into ECR.

**Comment by gautamkmr** [comment]
https://github.com/kubeflow/pipelines/issues/3670

**Comment by Bobgy** [comment]
@marwan116 looks like question answered, I'm going to close this issue.
But feel free to reopen with `/reopen` comment.

/close
