### ISSUE TITLE
[Release] Branch based release

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#3729]
/cc @rmgogogo @jingzhang36 
We need branch based release so that we can easily patch bug fixes onto a released version.
This is important for stableness after 1.0.

**Comment by Ark-kun** [comment]
I agree with this idea (I also proposed it before).
We can create branch where we update changed components, versions, etc. The tip of that branch is tagged and released. Then we merge this branch into master.
If we need any bugfixes, but cannot make a new release from master, then we can cherry-pick a fix to the release branch.

**Comment by Bobgy** [comment]
I'm evaluating feasibility of doing branch based release today.

After some investigation, I think it can also reduce complexity of our release process, especially component and sample release process.

Current process in [components/release.sh](https://github.com/kubeflow/pipelines/blob/f0c8effb3a4284bb2899780eef4a697a79043e4a/components/release.sh):
* Re-tag all component images to gcr.io/ml-pipeline
* Add a commit to update component images in component yamls
* Add a commit to update component yaml urls from sample pipelines' usages
* Send a PR with above changes

My understanding is that, we didn't have a way to merge a PR that updates all urls to the version tag github url, because it will fail the presubmit test.

With branch based release, we can simplify it with:
* Add only one commit that updates all component yamls and sample pipelines' urls to the github url that refer to a version tag.
* Cloudbuild job triggered in https://github.com/kubeflow/pipelines/blob/master/.release.cloudbuild.yaml, will be responsible for copying component images to gcr.io/ml-pipeline

With this approach, a release can actually be simplified to just one commit, a commit that updates all components, samples, image tags, python setup.py versions, ... any version tag in the repo. And we can automate this single step to make release easier.

Some other release related processes like updating changelog can potentially also be done at the same time without waiting for any external event.

After the change, release process will be a lot faster, we only need to
1. push a few commit in the release branch that update all the versions and add changelog (this can be automated as just running one script)
1. create the github release
1. wait for the cloudbuild job to finish successfully.
1. release python packages
(marketplace release is the only thing that cannot be automated, but the improvement is enough for now.)

Pros:
* This will no longer be the experience of submitting one PR after another for release and always waiting for them.
* The release can be an atomic change now, instead of splitting to several commits.

**Comment by Bobgy** [comment]
Cons:
* CHANGELOG generation needs some fix, because now a 1.0.1 should be patched on 1.0.0, but no longer in master branch.

**Comment by Bobgy** [comment]
Found a blocker for merging component release + sample release to one commit:
```
Traceback (most recent call last):
  File "core/xgboost_training_cm/xgboost_training_cm.py", line 27, in <module>
    confusion_matrix_op = components.load_component_from_url('https://raw.githubusercontent.com/kubeflow/pipelines/1.0.0-test-5/components/local/confusion_matrix/component.yaml')
  File "/usr/local/lib/python3.5/site-packages/kfp-1.0.0_test_5-py3.5.egg/kfp/components/_components.py", line 77, in load_component_from_url
    component_spec = _load_component_spec_from_url(url)
  File "/usr/local/lib/python3.5/site-packages/kfp-1.0.0_test_5-py3.5.egg/kfp/components/_components.py", line 143, in _load_component_spec_from_url
    resp.raise_for_status()
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/kubeflow/pipelines/1.0.0-test-5/components/local/confusion_matrix/component.yaml
The command '/bin/sh -c line="import kfp;kfp.components.default_base_image_or_builder='gcr.io/google-appengine/python:2020-03-31-141326";    set -e; find core tutorials -maxdepth 2 -name '*.py' -type f | while read pipeline; do     awk -v text="$line" '!/^#/ && !p {print text; p=1} 1' "$pipeline" &&     python3 "$pipeline";     done' returned a non-zero code: 1
```

When building api server, it needs to bake in pipeline samples, but in above described new process. Pipeline samples using the version release tag hasn't been updated yet.

**Comment by Ark-kun** [comment]
>Found a blocker for merging component release + sample release to one commit:

It's generally impossible. A file cannot possibly contain the SHA of it's own commit. With commit-based component references the samples cannot refer to a component updated in the same commit.

Having multiple commits is not a problem in a branch-based release.

I also think we should continue updating the components and references only when the code is changed (AFAIR, I've added the line about that to the release playbook).

P.S. Some other solutions: We could stop using GIT commit hashes and switch to file hash-based filenames (`/components/<org>/<component_name>/versions/ba51...d78a`). We can also put component versions on GCS and reference that storage location instead of GIT.
But the easiest way is to just use the original component release script.

ANother solution could be to store all

**Comment by Bobgy** [comment]
I've found an easy workaround, now I use git tag urls like https://raw.githubusercontent.com/kubeflow/pipelines/1.0.0-test-5/components/local/confusion_matrix/component.yaml. And I push a new commit and a tag together to github, so that this becomes available immediately.

A minor change is that, now cloudbuild task triggered by new tag for copying images need to be retried after images built.

**Comment by Bobgy** [comment]
I've got one branch based release working:
```
PIPELINE_VERSION=1.0.0-test-5
kubectl apply -k "github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=$PIPELINE_VERSION"
kubectl wait --for condition=established --timeout=60s crd/applications.app.k8s.io
kubectl apply -k "github.com/kubeflow/pipelines/manifests/kustomize/env/dev?ref=$PIPELINE_VERSION"
```

**Comment by Bobgy** [comment]
@Ark-kun I think using release tags in urls provides better user visibility on the version.
I'm still open to whether we keep this optional, we can continue the discussion in the email thread.

**Comment by Bobgy** [comment]
implementation #3777 merged, further documentation will be added continuously

**Comment by Bobgy** [comment]
Found a great prow plugin to automate cherry picking: https://github.com/kubernetes/test-infra/tree/master/prow/external-plugins/cherrypicker

**Comment by Bobgy** [comment]
TODO:
* [ ] Update internal release documentation to be in sync with latest practice.

**Comment by Bobgy** [comment]
Updated internal release doc
