### ISSUE TITLE
Pipeline UI should work behind Kubeflow reverse proxy (Ambassador)

### ISSUE THREAD

**Issue by jlewi** [kubeflow/pipelines#373]
Opening this issue to track getting the pipelines UI to work with the Kubeflow proxy.

@yebrahim @IronPan @kunmingg Does anyone know the current status of this?

IIRC based on our discussions, I think the UI works with Kubeflow reverse proxy with the exception of the TensorBoard links. The short term fix for the tensorboard links was to explicitly map "/data" and maybe some other paths used by TensorBoard to the pipelines UI.

Do we already have issues tracking that?

**Comment by yebrahim** [comment]
As you said, the UI works fully behind Ambassador, including proxying Tensorboard with the /data route mapped to go to the Pipelines frontend service.

@neuromage is looking into better support for Tensorboard, possibly by using a CRD to manage instances.

**Comment by jlewi** [comment]
@neuromage Do we have issues tracking the tensorboard problems?

**Comment by neuromage** [comment]
There's an existing internal bug for tracking this, I'll cc you on that one. Also, I'll create a new github issue to track this externally as well.

**Comment by neuromage** [comment]
Created tracking issue #443

**Comment by yebrahim** [comment]
Closing this since it's not tracking anything now.
