### ISSUE TITLE
[BUG] Confusion matrix visualizes target and predictions on wrong axes

### ISSUE THREAD

**Issue by areshytko** [kubeflow/pipelines#3733]
### What steps did you take:

1. Run the following code:
```
from typing import NamedTuple
def conf_m() -> NamedTuple('conf_m_result', [('mlpipeline_ui_metadata', 'UI_metadata')]):
    import json
    from collections import namedtuple
    cm_data = 'False,False,22\nFalse,True,484\nTrue,False,12\nTrue,True,539\n'
    vocab = [False, True]
    metadata = {
        'outputs' : [{
            'type': 'confusion_matrix',
            'format': 'csv',
            'schema': [
                {'name': 'target', 'type': 'CATEGORY'},
                {'name': 'predicted', 'type': 'CATEGORY'},
                {'name': 'count', 'type': 'NUMBER'},
            ],
            'storage': 'inline',
            'source': cm_data,
            'labels': list(map(str, vocab)),
        }]
    }
    print(json.dumps(metadata))
    conf_m_result = namedtuple('conf_m_result', ['mlpipeline_ui_metadata'])
    return conf_m_result(json.dumps(metadata))

cm_op = kfp.components.func_to_container_op(conf_m)

@kfp.dsl.pipeline(name='test conf matrix')
def pipeline():
    op1 = cm_op()

kfp.Client().create_run_from_pipeline_func(pipeline, arguments={})
```
2. See result in KFP UI

### What happened:

Axes were mixed up:

![image](https://user-images.githubusercontent.com/7684174/81501463-3011ef00-92e1-11ea-9274-fde33691c0f1.png)

for the data:

![image](https://user-images.githubusercontent.com/7684174/81501504-651e4180-92e1-11ea-9f29-1f8b96a68e07.png)

### What did you expect to happen:

Targets on the y-axis, predictions on the x-axis

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

`kubectl apply -k`

KFP version: 0.5

KFP SDK version: 0.5.0

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug
/area frontend

**Comment by Bobgy** [comment]
/cc @numerology 
I'm not familiar with the scope, is this the usual convention of showing a confusion matrix?
If yes, can you switch your schema order, to put predicted as the first item?
```
'schema': [
                {'name': 'target', 'type': 'CATEGORY'},
                {'name': 'predicted', 'type': 'CATEGORY'},
                {'name': 'count', 'type': 'NUMBER'},
            ],
```

**Comment by Bobgy** [comment]
@areshytko is above workaround good for you?

**Comment by areshytko** [comment]
Hey @Bobgy. Thanks for the reply.
 
The thing is not about the convention, the data on the plot is wrong: if sum all targets on the plot you will get: 484+539 as True. And if you do it the original data in the table, you'll get: 539 + 12.

The workaround is confusing for the user because the order of columns in the data and in the provided metadata will differ.

**Comment by Bobgy** [comment]
@areshytko Thanks for the detailed explanation! I see, that's a bug indeed.
