### ISSUE TITLE
Abstract away argo workflow variables

### ISSUE THREAD

**Issue by omarzouk** [kubeflow/pipelines#3736]
### What steps did you take:
One often needs to use variables such as `{{workflow.status}}` however there is no abstraction around it and the current abstraction for `{{workflow.uid}}` ([here](https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/dsl/__init__.py#L29)) was created to serve some samples and tutorials as mentioned [here](https://github.com/kubeflow/pipelines/pull/1683#issuecomment-535228661).

### What did you expect to happen:
a function such as `get_run_information_placeholder` in dsl that allows fetching of various metadata about the run (listed [here](https://github.com/argoproj/argo/blob/master/docs/variables.md))

KFP version: 0.2.5

KFP SDK version: 
kfp                            0.4.0
kfp-server-api         0.3.0

/kind feature

**Comment by Ark-kun** [comment]
Generally abstracting away Argo is an important idea. However we should be careful with how we do this.
