### ISSUE TITLE
[Feature request] AWS SageMaker component log 

### ISSUE THREAD

**Issue by goswamig** [kubeflow/pipelines#3744]
Currently SageMaker component does not have log in KFP ui or artifact. Since the job runs inside the SageMaker, job's log gets pushed to AWS Cloudwatch.  We should have job's log available in KFP.

**Comment by gautamkmr** [comment]
https://github.com/kubeflow/pipelines/issues/3670

**Comment by akartsky** [comment]
This issue can be closed
