### ISSUE TITLE
[Multi User] Make user identity header configurable

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#3752]
/cc @yanniszark @jlewi 
as discussed in https://github.com/kubeflow/pipelines/issues/3645#issuecomment-625872980

Part of https://github.com/kubeflow/pipelines/issues/1223

* [x] UI Server #3753 
* [x] Api Server https://github.com/kubeflow/pipelines/pull/3772 and https://github.com/kubeflow/pipelines/pull/3842

**Comment by yanniszark** [comment]
@Bobgy thanks a lot!
I may be wrong, but is authorization happening in two places? (apiserver and ui-server)
If yes, is there any plan to consolidate authorization logic in one place?

**Comment by Bobgy** [comment]
> @Bobgy thanks a lot!
> After seeing the changes, I have a small question.
> I may be wrong, but is authorization happening in two places? (apiserver and ui-server)
> If yes, is there any plan to consolidate authorization logic in one place?

@yanniszark For clarification, authorization logic happens in only one place, the api server. Api server exposes an endpoint that ui-server queries. The usage of the header in ui-server was because ui-server needs to know what header to proxy to api-server, so api-server can authenticate correctly

**Comment by yanniszark** [comment]
@Bobgy awesome, thanks a lot for the explanation!
Is the endpoint you're talking about a special endpoint only for the UI-server to use?
Or is the UI-server making requests to the API-Server's usual endpoints on behalf of the user and includes the userid header in them (so requests happen to the usual endpoints)?

**Comment by Bobgy** [comment]
@yanniszark It's a special endpoint only for UI-server, because some features (e.g. tensorboard CRUD) is implemented in UI server. We'd want to keep current structure that UI server can implement some UI only apis, so that we don't need to rewrite too much in api server.

**Comment by yanniszark** [comment]
@Bobgy I see. Is this the endpoint you are talking about?
https://github.com/kubeflow/pipelines/blob/1dcea49472e725ab681db3d244d51837e291f5ba/backend/api/auth.proto

It seems like you're implementing a SubjectAccessReview-like endpoint but for the Pipelines API-Server.

**Comment by Bobgy** [comment]
@yanniszark yes, that's right. I made a thin wrapper following the same schema, to be compatible with future changes.

**Comment by elikatsis** [comment]
@Bobgy hi!
I found a bug on user id header parsing and opened this PR: kubeflow/pipelines#3842
It would be great if you included it in the main list of this issue, and it would be even greater if you took a look at it :smiley:

**Comment by Bobgy** [comment]
Regarding https://github.com/kubeflow/pipelines/issues/4091, the prefix env var cannot be set as empty string.

**Comment by Bobgy** [comment]
#4091 fixed
