### ISSUE TITLE
[KF 1.0 Compliance] app.kubernetes.io labels on every resource

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#3755]
Part of https://github.com/kubeflow/pipelines/issues/2884
Compliance doc: https://github.com/kubeflow/community/blob/master/guidelines/application_requirements.md
Description | Category | Explanation
-- | -- | --
app.kubernetes.io labels on every resource | Required | Every resource that is part of the application should include the labels recommended by Kubernetes, currently:app.kubernetes.io/nameapp.kubernetes.io/instanceapp.kubernetes.io/versionapp.kubernetes.io/componentapp.kubernetes.io/part-ofapp.kubernetes.io/managed-bySee example here

**Comment by Bobgy** [comment]
The problem is that common labels feature in kustomize cannot be used for applying these labels: https://github.com/kubeflow/manifests/issues/1131

Because it is applied to selectors too, while selectors have to be immutable for upgrade.

Due to the limitations, I think it's better to defer this requirement to post 1.0 until there's a maintainable solution.

Upstream kustomize has a solution to add labels commonly without changing selector: https://github.com/kubernetes-sigs/kustomize/issues/1009#issuecomment-559558000

but I tried, the feature wasn't even introduced in kustomize 3.1.0, it will take a long time before kubectl kustomize picks it up.

**Comment by Bobgy** [comment]
/cc @jlewi 
Sounds reasonable to defer this until later than KFP 1.0?

**Comment by rimolive** [comment]
Closing this issue. Looks like the resources are already annotated.

/close
