### ISSUE TITLE
"clone recurring run" doesn't clone the trigger method

### ISSUE THREAD

**Issue by andrewgdavis** [kubeflow/pipelines#3761]
### What steps did you take:
create a scheduledworkflow with a trigger method of "Cron" and an interval of 5 seconds.
from the recurring run config; select the "Clone recurring run" button.

### What happened:
After selecting the "clone recurring run" button,  the recurring run form with respective pipeline and version are applied; but the schedule configuration has the defaults applied ("Periodic" trigger method, catchup box enabled, etc.) and not the "Cron"

### What did you expect to happen:
apply the cron schedule from previous recurring run config.

KFP version: v0.4.0

/kind bug
/area frontend
/area backend

**Comment by Bobgy** [comment]
Thanks for the report!

**Comment by Bobgy** [comment]
Changed kind to feature, because this wasn't implemented at all. #3840 did the first implementation.
