### ISSUE TITLE
Add license to the kfp-server-api package

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#3764]
The package is generated by this script: https://github.com/kubeflow/pipelines/blob/master/backend/api/build_kfp_server_api_python_package.sh

**Comment by Bobgy** [comment]
Thanks @Ark-kun! This is required item

**Comment by Bobgy** [comment]
Part of https://github.com/kubeflow/pipelines/issues/2884

**Comment by Ark-kun** [comment]
I think we might need this even sooner.

**Comment by Bobgy** [comment]
It is a must have for KFP 1.0, do you mean sooner than that?

**Comment by Bobgy** [comment]
I will complete this
