### ISSUE TITLE
Upgrade Argo go client to v2.7.5

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/pipelines#3770]
We found out that KFP upgraded the Argo version to v2.7.5. Is there any plan to also upgrade the Argo go client for the backend to the same version? 

This can also help us solve some client-go dependency issues at #3647

**Comment by Ark-kun** [comment]
We would be glad is some Bazel expert can help us upgrade our backend workspace.

I've tried to update it, but got some issues: https://github.com/Ark-kun/pipelines/commits/Backend---Updated-BUILD-files-using-gazelle See https://github.com/kubeflow/pipelines/issues/3461

**Comment by Bobgy** [comment]
@rmgogogo @jingzhang36 Do you think we can handle this before release of 1.0?

**Comment by rmgogogo** [comment]
(need upgrade bazel to unlock Argo)

**Comment by StefanoFioravanzo** [comment]
@Ark-kun @rmgogogo @Bobgy We have some customers that are facing some issues due to the old version of the Argo Go client. Once such issue is documented in #3590 and already implemented by @Ark-kun in #3880 . We would love to see this resolved as soon as possible. Do you think it could be done in time before 1.0?

**Comment by Gsantomaggio** [comment]
@Ark-kun I tested your branch and by adding:

```
http_archive(
    name = "com_google_protobuf",
    sha256 = "9748c0d90e54ea09e5e75fb7fac16edce15d2028d4356f32211cfa3c0e956564",
    strip_prefix = "protobuf-3.11.4",
    urls = ["https://github.com/protocolbuffers/protobuf/archive/v3.11.4.zip"],
)

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")

protobuf_deps()
```

and I made some progress by building with Bazel 3.4.1

I have some problem on:

```
/home/gas/.cache/bazel/_bazel_xxx/34bbca79053fc2711cf0e6767c94a334/sandbox/linux-sandbox/856/execroot/__main__/external/com_github_argoproj_argo/pkg/client/clientset/versioned/typed/workflow/v1alpha1/workflow_client.go:58:32: undefined: serializer.DirectCodecFactory
```

**Comment by Bobgy** [comment]
FYI, @Gsantomaggio created a PR of his current progress at https://github.com/kubeflow/pipelines/pull/4343. Above mentioned problem was the blocker.

**Comment by Bobgy** [comment]
FYI, this has been done in https://github.com/kubeflow/pipelines/pull/4498.
