### ISSUE TITLE
Messy UI DAG in complex ParallelFor scenario

### ISSUE THREAD

**Issue by Peilun-Li** [kubeflow/pipelines#3790]
In complex ParallelFor scenario, the UI DAG (specifically the edges) will be messy.

Sample code:
```
import kfp.dsl as dsl
import kfp
import kfp.components as comp


def random_num_op(low, high):
    """Generate a random number between low and high."""
    return dsl.ContainerOp(
        name='Generate random number',
        image='python:alpine3.6',
        command=['sh', '-c'],
        arguments=['python -c "import random; print(random.randint($0, $1))" | tee $2', str(low), str(high), '/tmp/output'],
        file_outputs={'output': '/tmp/output'}
    )

def parallel(num: int) -> list:
    return [1] * num

parallel_op = comp.func_to_container_op(parallel)

@dsl.pipeline(name='my-pipeline')
def pipeline():
    op0 = random_num_op(0, 9)
    for i in range(3):
        with dsl.ParallelFor(parallel_op(5).output) as item:
            op1 = dsl.ContainerOp(
                name="my-in-coop1",
                image="library/bash:4.4.23",
                command=["sh", "-c"],
                arguments=["echo op1 %s" % (op0.output)],
            )

            op2 = dsl.ContainerOp(
                name="my-in-coop2",
                image="library/bash:4.4.23",
                command=["sh", "-c"],
                arguments=["echo op2 %s" % (op0.output)],
            ).after(op1)


if __name__ == '__main__':
    kfp.compiler.Compiler().compile(pipeline, __file__ + '.yaml')

```

UI Graph:
![image](https://user-images.githubusercontent.com/11920339/82363593-e43b0600-99c2-11ea-9804-ccceb55d6102.png)

As can be seen the `generate-random-number` makes the top part of UI unreadable.

It's good if we can have some control over the UI through pipeline definition, e.g., a `disable_UI_edge_rendering` parameter of ContainerOp (or some other ways such as a UI sdk) to control whether we render all edges linked with a vertex in UI.

**Comment by Ark-kun** [comment]
Are you sure the removal of the edges will make the UX useful in your case? I think you can try making them invisible by adjusting the styles in the Chrome Dev tools, but I'm not sure it will change much (the edges do not seem to obstruct anything).

**Comment by Ark-kun** [comment]
P.S. On an unrelated note: Please try always using components instead of constructing ContainerOp objects manually.

When you do quick iterations, just use `load_component_from_text` and `func_to_container_op`. Both allow you to quickly create reusable `component.yaml` files when you're done debugging.

**Comment by Peilun-Li** [comment]
![image](https://user-images.githubusercontent.com/11920339/82476309-ad2c2980-9a82-11ea-95b3-810a32020155.png)

As an example of not having those lines associated with `generate-random-number` (Of course this code won't work as desired since I remove the usage of op0.output in op1 and op2), but if we can have some control over UI we can achieve both (code logic and UI readability)

**Comment by Ark-kun** [comment]
In your real scenario, is `parallel_op` the same as you've  posted? Is there a reason for you not to use python's for loop?

I think you'll have the same issue if you pass two sources to many downstream tasks...

**Comment by Peilun-Li** [comment]
No it's just a simplified version (to showcase the messy UI). The real scenario will be a dynamic dispatch and run in parallel.

Yeah it will be an improvement if we have some simple control over UI.

**Comment by Bobgy** [comment]
@Peilun-Li Thanks for the report!
This seems like a complex case for UI to handle.

A quick idea: does it work for you if we can hide certain nodes and related arrows? I'm not sure there's a more general use-case for this.

Do you have any ideas what generic UI feature will unblock your use-case?

**Comment by Peilun-Li** [comment]
@Bobgy Yeah hiding certain node and its associated edges also helps for a better visualization and readability.

**Comment by Bobgy** [comment]
Here are some references, PRs welcomed!
Frontend of KFP UI is written with typescript + react.

Frontend contribution doc: https://github.com/kubeflow/pipelines/blob/master/frontend/README.md
The DAG graph component lives in https://github.com/kubeflow/pipelines/blob/master/frontend/src/components/Graph.tsx
