### ISSUE TITLE
[UX] Artifacts page should report errors just like the Executions page

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#3796]
When there is a problem connecting to MLMD the  Executions page shows an error `Error: Failed getting executions: upstream connect error or disconnect/reset before headers. reset reason: connection failure. Code: 14 Troubleshooting guide`. However the Artifacts page does not show any error.

**Comment by Bobgy** [comment]
For clarification, are those pages empty? Did artifact page load some items?

**Comment by Ark-kun** [comment]
Yes, both pages are empty. The MySQL is broken....

So the issue is only the lack of error.

**Comment by Bobgy** [comment]
Thanks for confirmation, I'll leave this to post 1.0 then. These pages need a rewrite, anyway.
