### ISSUE TITLE
[MKP] Allow using GCS Minio Gateway without using CloudSQL

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#3798]
Currently there is a single "Managed storage" checkbox that redirects MySQL to CloudSQL, not just Minio to GCS.

**Comment by Bobgy** [comment]
Agree, not sure it's because people want to put artifacts on a managed service more. I see more comments in slack asking about artifacts than cloudsql.

**Comment by Bobgy** [comment]
but generally, for a production system, I think we should suggest users to use both, even if they originally just want to use gcs

**Comment by Ark-kun** [comment]
> Agree, not sure it's because people want to put artifacts on a managed service more. I see more comments in slack asking about artifacts than cloudsql.

I might be one of those people =)

CloudSQL changes nothing for me - it's an implementation detail.

But artifact storage means much more. GCS is accessible while Minio's PD is hard to access. Also GSC does not have size limitations. I've seen multiple people on Slack struggling with tracing the artifacts and trying to download them from Minio using the backend APIs. Helping them use GCS might solve some problems.

**Comment by Ark-kun** [comment]
> but generally, for a production system, I think we should suggest users to use both, even if they originally just want to use gcs

Of course. For production they should use both.

**Comment by Bobgy** [comment]
/cc @rmgogogo 
I'm not sure we should prioritize this, because it takes really some efforts (it's not easy to add flexible options in manifests).
We may choose to wait until strong user feedback this is necessary.

there's work needed on google cloud platform UI too

**Comment by Ark-kun** [comment]
> We may choose to wait until strong user feedback this is necessary.

I think I saw some amount of people in slack having trouble accessing the artifacts. Also maybe some users of VolumeOp are using it because the GCS artifact storage is unavailable to them...

>it takes really some efforts (it's not easy to add flexible options in manifests).

Is it possible to check for empty values?

We could do the following (or is it too complicated)?:
```
# minio and workflow-configmap:
If managed storage:
  minio = Minio gateway
  workflow-configmap.bucket = GCS bucket
else:
  minio = minio
  workflow-configmap.bucket = minio bucket


# cloudsql and PD:
If CloudSQL connection != "":
  mysql = cloudsql gateway.
else:
  mysql = mysql
  PD = PD
```

**Comment by rmgogogo** [comment]
@IronPan 

I would prefer keep current logic. The DB has values points to minio. I prefer let me work together to provide full-managed-storage.

**Comment by Ark-kun** [comment]
Let's keep the issue open until it's fixed.

**Comment by Ark-kun** [comment]
I've updated https://github.com/kubeflow/pipelines/pull/3800 and I think it now fixes all issues relating to CloudSQL. Please take a look.
