### ISSUE TITLE
[MKP] gcp-default-config does not have owner reference

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#3799]
The `gcp-default-config` configMap is not deleted when Pipelines deployment is deleted.

P.S. There is a similar issue with the `webhook-server-tls` secret.

**Comment by Bobgy** [comment]
also
/assign @rmgogogo 

@Ark-kun quick question: does this prevent reinstallation?

**Comment by rmgogogo** [comment]
This is by design when providing this feature.
@numerology 

The reinstallation still can work and it can help reinstalled one use the previous created bucket.
