### ISSUE TITLE
[Feature request] Support European regions with Dataflow launch_template

### ISSUE THREAD

**Issue by DennisVis** [kubeflow/pipelines#3801]
The Dataflow launch_template component allows for setting a location paramater. This does not work for European regions though.

For supporting more regions the component should switch to the `projects.locations.templates` API endpoint instead of the `projects.templates` endpoint it uses currently.

**Comment by Bobgy** [comment]
Thanks for the report! PR welcomed if you already know the fix

**Comment by NikeNano** [comment]
Closing this issue since the PR is merge and this should be solved.
