### ISSUE TITLE
User encounters bad request when uploading version

### ISSUE THREAD

**Issue by jingzhang36** [kubeflow/pipelines#3805]

**Comment by jingzhang36** [comment]
Context:

From @Tauranis
Unfortunately, uploading a new version is crashing.

When I run

kfp --endpoint <URL> pipeline upload-version -p <PIPE_ID> -v <PIPE_VERSION> ./dist/pipeline.tar.gz
It throws (500) Bad Request. Reason: Internal Server Error

The same happens when I use the Python SDK

import os
import kfp
client = kfp.Client()
client.pipeline_uploads.upload_pipeline_version(<FILE>, pipelineid=<PIPE_ID>, name=<PIPE_VERSION>)
Currently I'm using Kubeflow deployed at Google AI Platform with kfp==0.5.1 and kfp-server-api==0.5.0

Does someone else have the same problem?

**Comment by jingzhang36** [comment]
From @jingzhang36 
I tested with kfp===0.4.0 kfp-server-api===0.3.9 and kfp standalone deployment with 0.5.1
By following the example at https://www.kubeflow.org/docs/pipelines/tutorials/sdk-examples/
I can not reproduce the error.
So that means the API server's feature is fine. Suspecting issues with cluster setting up or usage.

**Comment by jingzhang36** [comment]
@Tauranis
Can you provide a little more information to help us investigating?
1. Do you create a pipeline before you creating a pipeline version? Our pipeline version has to be added to an existing pipeline
2. Can you find the ml-pipeline server's log and see what are the errors there which are related to the upload_pipeline_version failure?

**Comment by jingzhang36** [comment]
3. Can you try list pipeline and list pipeline version commands as well? Just want to know if those two work in your setup.
Thanks!

**Comment by jingzhang36** [comment]
BTW, I did another test with kfp: 0.5.1, kfp-server-api: 0.5.0 and kfp standalone deployment 0.5.1
And still able to use upload_pipeline_version

**Comment by Tauranis** [comment]
I found the error.
I was passing the pipeline name and not the pipeline id.
My bad. Sorry.

For those who  want to get the pipeline id from its name the following will work.

```
PIPELINE_ID=$(kfp --endpoint ${KUBEFLOW_ENDPOINT} pipeline list | grep -w  ${PIPELINE_NAME}  | grep -E -o -e "([a-z0-9]){8}-([a-z0-9]){4}-([a-z0-9]){4}-([a-z0-9]){4}-([a-z0-9]){12}")
```

I'm currently using this for my CI/CD pipeline.

**Comment by Bobgy** [comment]
@jingzhang36 It seems we need to fix the internal server error. It should report we cannot find this pipeline as error messag
