### ISSUE TITLE
[UX] For steps reused from cache, the link to Stackdriver logs should point to the original pod

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#3820]
It's possible to obtain the original pod name. That pod name should be used to build the Stackdriver query.

**Comment by Bobgy** [comment]
@Ark-kun How do we get original pod name?

**Comment by Ark-kun** [comment]
> @Ark-kun How do we get original pod name?

We could parse if from the `main-logs` artifact URI or we can record that information just like the original start time and end time (I think you've showed a UI screenshot featuring them).

**Comment by Bobgy** [comment]
@Ark-kun I'm thinking, instead of trying to port over each attribute to cached step. Maybe we should just provide a link to the original step, so the user can check by his/herself

**Comment by Bobgy** [comment]
> We could parse if from the main-logs artifact URI or we can record that information just like the original start time and end time (I think you've showed a UI screenshot featuring them).

I didn't show a UI screenshot for start time and end time, not sure where the confusion comes from.

**Comment by Bobgy** [comment]
Think about this in terms of MLMD, will the execution have a ref to previous execution. If that's possible, it could enable a lot of UX fixes
