### ISSUE TITLE
Fix the documentation about the mlpipeline-ui-metadata

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#3821]

**Comment by Bobgy** [comment]
Duplicate of https://github.com/kubeflow/website/issues/2021

**Comment by Bobgy** [comment]
Well, kubeflow/website#2021 only covers metrics. We still need to update ui metadata documentation.

**Comment by Bobgy** [comment]
We need to update similar to https://github.com/kubeflow/website/pull/2171

**Comment by Bobgy** [comment]
/assign @zijianjoy 
is fixing this

**Comment by zijianjoy** [comment]
Is this issue related to https://github.com/kubeflow/pipelines/issues/5666?

**Comment by Bobgy** [comment]
Yes, this is a duplicate now
