### ISSUE TITLE
[QUESTION] How to add description to a pipeline when uploading it via SDK?

### ISSUE THREAD

**Issue by areshytko** [kubeflow/pipelines#3825]
# Motivation

Uploading pipelines from UI is a very long a laborious process. Uploading pipelines from SDK is quicker and simpler.

# Question

Is there a way to provide a pipeline description when uploading it from SDK. Couldn't find such an option in APIs.

**Comment by Ark-kun** [comment]
Thanks for reporting this issue. I've created a fix PR which adds the `description` parameter to `upload_pipeline`.
