### ISSUE TITLE
Minikube ECR: Could not pull image from private repo

### ISSUE THREAD

**Issue by Phelan164** [kubeflow/pipelines#3847]
### What steps did you take:
- Install minikube 
- Create secret ( kubectl -n kubeflow  create secret docker-registry ... ) for ECR registry
- Follow the sample https://github.com/kubeflow/pipelines/blob/master/samples/core/imagepullsecrets/imagepullsecrets.py
to pull my image from private repo ECR

### What did you expect to happen:
This step is in Pending state with this message: ImagePullBackOff: Back-off pulling image 

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

minikube version: v1.10.1
commit: 63ab801ac27e5742ae442ce36dff7877dcccb278

KFP version: 

KFP SDK version: 
kfp (0.5.1)
kfp-server-api (0.5.0)

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by Ark-kun** [comment]
Does it work for you with raw Kubernetes?
