### ISSUE TITLE
[Multi User] apiserver still requires ML_PIPELINE_VISUALIZATIONSERVER_SERVICE_*

### ISSUE THREAD

**Issue by elikatsis** [kubeflow/pipelines#3849]
I'm filing this issue due to this discussion: https://github.com/kubeflow/manifests/pull/1154#discussion_r430105919

### What steps did you take:
Deploy Multi-User KFP based on https://github.com/kubeflow/manifests/pull/1154

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-pipeline-config
data:
  config.json: |
    {
      "DBConfig": {
        "DriverName": "mysql",
        "DataSourceName": "",
        "DBName": "mlpipeline"
      },
      "ObjectStoreConfig":{
        "AccessKey": "minio",
        "SecretAccessKey": "minio123",
        "BucketName": "mlpipeline",
        "PipelinePath": "pipelines",
        "Secure": false
      },
      "InitConnectionTimeout": "6m",
      "DefaultPipelineRunnerServiceAccount": "pipeline-runner",
      "VisualizationService":{
        "Name": "ml-pipeline-visualizationserver",
        "Port": 8888
      },
      "MULTIUSER": true
    }
```

### What happened:
`apiserver` is in a `CrashLoopBackOff` requiring `ML_PIPELINE_VISUALIZATIONSERVER_SERVICE_HOST`

```
$ kubectl -n kubeflow logs ml-pipeline-565dc6f88b-b89rx
I0526 12:50:31.498547       1 client_manager.go:134] Initializing client manager
I0526 12:50:31.498826       1 config.go:50] Config DBConfig.ExtraParams not specified, skipping
I0526 12:50:31.670237       1 client_manager.go:356] We already own mlpipeline
I0526 12:50:31.672566       1 client_manager.go:164] Client manager initialized successfully
I0526 12:50:31.676288       1 main.go:168] Samples already loaded in the past. Skip loading.
I0526 12:50:31.676759       1 resource_manager.go:869] Default experiment already exists! ID: ef20ce9c-6c50-4812-b132-7f6319268d61
I0526 12:50:31.676781       1 main.go:113] Starting Http Proxy
I0526 12:50:31.677265       1 main.go:84] Starting RPC server
F0526 12:50:31.677345       1 config.go:36] Please specify flag ML_PIPELINE_VISUALIZATIONSERVER_SERVICE_HOST
```

When MultiUser is enabled, it should be that the changes of this PR take over: kubeflow/pipelines#3495
However, it must be that these lines run independently to whether the feature is enabled or not:
https://github.com/kubeflow/pipelines/blob/508f31aa0feea5f00d4960207dbe14b535513f99/backend/src/apiserver/main.go#L95-L101

/area backend
/cc @Bobgy

**Comment by Bobgy** [comment]
/cc @chensun 
For current workaround, can you deploy a `ml-pipeline-visualizationserver' service? The service doesn't need to be backed by a deployment. Just make KFP api server start normally is fine.

**Comment by Bobgy** [comment]
If you'd want to complete get rid of it, we'd help with reviews.

**Comment by Bobgy** [comment]
Part of #1223

**Comment by chensun** [comment]
> /cc @chensun
> For current workaround, can you deploy a `ml-pipeline-visualizationserver' service? The service doesn't need to be backed by a deployment. Just make KFP api server start normally is fine.

IIRC, `ML_PIPELINE_VISUALIZATIONSERVER_SERVICE_HOST` from manifest was never used. Instead, backend get such environment variable from the K8s auto-generated env variable as `<SERVICE_NAME>_SERVICE_HOST`. And we intentionally kept the visualizationserver service in the `kubeflow` namespace in addition to those in user namespaces to make it easier for user to decide which one they want to use. Is there anything changed so that we don't have the visualizationserver service in `kubeflow` namespace any more?

**Comment by Bobgy** [comment]
@chensun, thanks for pointing that out!

@elikatsis is preparing his own manifest. I think that's MiniKF, is that right? So it sounds reasonable if he prefers either way.

**Comment by elikatsis** [comment]
This must have been it:
KF manifests have wrong naming for the visualization server. The output is a double `ml-pipeline-` prefix.
```
$ kubectl -n kubeflow exec ml-pipeline-9c979d848-7frzh -it -- sh
# env | grep VIS
ML_PIPELINE_ML_PIPELINE_VISUALIZATIONSERVER_PORT_8888_TCP=tcp://10.111.87.45:8888
ML_PIPELINE_ML_PIPELINE_VISUALIZATIONSERVER_SERVICE_PORT_HTTP=8888
ML_PIPELINE_ML_PIPELINE_VISUALIZATIONSERVER_SERVICE_HOST=10.111.87.45
ML_PIPELINE_ML_PIPELINE_VISUALIZATIONSERVER_PORT=tcp://10.111.87.45:8888
ML_PIPELINE_ML_PIPELINE_VISUALIZATIONSERVER_SERVICE_PORT=8888
ML_PIPELINE_ML_PIPELINE_VISUALIZATIONSERVER_PORT_8888_TCP_ADDR=10.111.87.45
ML_PIPELINE_ML_PIPELINE_VISUALIZATIONSERVER_PORT_8888_TCP_PORT=8888
ML_PIPELINE_ML_PIPELINE_VISUALIZATIONSERVER_PORT_8888_TCP_PROTO=tcp
```

I submitted kubeflow/manifests#1210 fixing that

**Comment by elikatsis** [comment]
@Bobgy, I see you fix it by removing the `nameprefix` (I'm building manifests from scratch while taking into consideration your work, that's why I didn't have it on my branch). If you prefer this solution I can change the PR accordingly

**Comment by Bobgy** [comment]
Replied in the PR
