### ISSUE TITLE
Deprecate unofficial TFX components in the repository

### ISSUE THREAD

**Issue by neuromage** [kubeflow/pipelines#3853]
We should deprecate the TFX components in [1], as they are not supported by the TFX team, and also introduce a maintenance burden. Instead, we will ask users to use TFX SDK on KFP when running TFX components, and look to fill any feature gaps on the TFX SDK to ensure their experience of running TFX on KFP is a good one.

[1] https://github.com/kubeflow/pipelines/tree/master/components/tfx

**Comment by Ark-kun** [comment]
> Instead, we will ask users to use TFX SDK on KFP when running TFX components

I think we already explicitly doing that. See the README for the TFX components:
https://github.com/kubeflow/pipelines/blob/fa3b304/components/tfx/README.md

`These components were created to allow the users to use TFX components in their KFP pipelines, to be able to mix KFP and TFX components.`
`If your pipeline uses only TFX components, please use the official TFX SDK.`


>look to fill any feature gaps on the TFX SDK

The biggest gap which will be a major pain point for our users: The users cannot use their 300+ KFP components with TFX SDK. The second major pain is the lack of data passing support. Getting those two will make the experience significantly better for the users.
