### ISSUE TITLE
[Docuementation] recurring run parameters to get scheduled time

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#3855]
Asked in https://github.com/kubeflow/kubeflow/issues/5014#issuecomment-631977082

We need documentation on https://kubeflow.org about how to use arguments like `[[ScheduledTime]]` in recurring runs, currently documented in https://github.com/kubeflow/pipelines/blob/578e8231d01074b9dbe40ace1db8cc444a6a1bd8/backend/src/crd/samples/scheduledworkflow/parameterized.yaml#L29-L34
/cc @wenmin-wu
/assign @Bobgy @jingzhang36

**Comment by wenmin-wu** [comment]
Hi @Bobgy, here's a good reference for defining the time format 
 https://programming.guide/go/format-parse-string-time-date-example.html
According to this doc, I successfully got scheduled time in `%Y-%m-%d`  with `[[ScheduledTime.2006-01-02]]` as the macro.

**Comment by Amitg1** [comment]
Can anyone PLEASE share how can I use it inside a Kubeflow pipeline as an argument for a custom component? 
thanks.

**Comment by Amitg1** [comment]
bump? no one using it?

**Comment by Amitg1** [comment]
https://www.roelpeters.be/an-overview-of-macros-and-variables-in-kubeflow/
