### ISSUE TITLE
GET Pipeline Version API endpoint doesn't filter based on filter predicates

### ISSUE THREAD

**Issue by sudivate** [kubeflow/pipelines#3867]
### What steps did you take:
API Endpoint ([Documentation](https://www.kubeflow.org/docs/pipelines/reference/api/kubeflow-pipeline-api-spec/#operation--apis-v1beta1-pipeline_versions-get))

GET /apis/v1beta1/pipeline_versions

e.g. 
http://[_endpoint_]/pipeline/apis/v1beta1/pipeline_versions?resource_key.type=PIPELINE_VERSION&resource_key.id={[_pipeline_id_]}
&filter={"predicates":[{"key":"name","op":"EQUALS","string_value":"[_pipeline_version_name_]"}]}

### What happened:
Filter doesn't apply on results returned  

### What did you expect to happen:
Expecting  filtering results based on the filter predicate, this works for other endpoints like GET /apis/v1beta1/pipelines

KFP version: 0.5.0

// /area backend

**Comment by rmgogogo** [comment]
@jingzhang36

**Comment by rmgogogo** [comment]
With my understanding, "resource_key.id={[pipeline_id]}" is a must-have and it's supported.
I think in a production env, normally the version name is auto-generated. As for filtering based on version name, would you detail more info on how you normally name the versions? Any more story on it?

**Comment by sudivate** [comment]
Thank you for looking into it.  

http://[endpoint]/pipeline/apis/v1beta1/pipeline_versions?resource_key.type=PIPELINE_VERSION&resource_key.id={[pipeline_id]}
&filter={"predicates":[{"key":"name","op":"EQUALS","string_value":"[pipeline_version_name]"}]}

Yes. I'm providing all the values mentioned "[ ]" including resource_key.id and pipeline_id is auto-generated and I use **GET /apis/v1beta1/pipelines** to get particular pipeline id

**Comment by jingzhang36** [comment]
Thank you so much for reporting this bug. Will have a fix soon!
