### ISSUE TITLE
FE: Component access to run id variables

### ISSUE THREAD

**Issue by jimmy-hawkfish** [kubeflow/pipelines#3868]
Hi all,
At multiple points in our pipelines it would be useful for components to have access to:
- kfp_pod_name
- pipeline_name
- run_id
- component_run_id

for tracking purposes when interacting with external services (e.g. Katib). These values currently do not appear to be injected as environment variables. Could these environment variables be added and/or is there another way to access them currently?

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?
GCP Hosted ML pipelines

KFP version: 0.5.1

KFP SDK version: 0.5.1

**Comment by rmgogogo** [comment]
Thanks for the input.
I think it's better the component just care about its specific task execution for well decoupling with others. I prefer to keep the design to let the component decouple with its outside world. Would you help provide one or two detailed case on why need it inside component?

TFX SDK did a good design on it. Each component has a driver and a publisher which handles these things while in the core execution part, it just focus on it's task and no need to worry about external world.
