### ISSUE TITLE
kfp.containers.build_image_from_working_dir fails on AWS EKS looking for GCP Project ID

### ISSUE THREAD

**Issue by anupamag** [kubeflow/pipelines#3875]
### What steps did you take:
Using a notebook server, tried using the kfp.containers.build_image_from_working_dir() as build_python_component is deprecated. 

### What happened:
The API fails with below error
Valueerror: Cannot get the Google Cloud Project id. please specify the gcs_staging  argument

### What did you expect to happen:
Picks py files from local path (Same as notebook) and build the container

### Environment:
EKS and Juypter Notebook

How did you deploy Kubeflow Pipelines (KFP)?
Code Build+Cloud Formation

KFP v1.0.2 

KFP SDK version  Beta

### Anything else you would like to add:
This prevents from using the methods recommended when using SDK

- Creating components from existing application code
- Creating components within your application code

/kind bug

**Comment by rmgogogo** [comment]
Thanks for reporting this issue.

I think it originally is designed for GCP. Technically it can support other clouds.
https://github.com/kubeflow/pipelines/blob/2742a3ed9591df1327159a949ef9dcf235f642a9/sdk/python/kfp/containers/_container_builder.py#L174

@Ark-kun for better suggestion.

**Comment by blublinsky** [comment]
Any solution for this problem? Workarounds?

**Comment by bioshazard** [comment]
@blublinsky a year later and the workaround is to use v2 instead

https://github.com/kubeflow/pipelines/issues/7858#issuecomment-1164992413
