### ISSUE TITLE
Minio pod `Ready` condition turns to False after few days

### ISSUE THREAD

**Issue by surajkota** [kubeflow/pipelines#3885]
### What steps did you take:
Installed KFP v0.5.1 on an EKS cluster and running 7 [pipelines](https://github.com/kubeflow/pipelines/tree/master/components/aws/sagemaker/tests/integration_tests/resources/definition) every 15 mins since 3 days

### What happened:
**Ready** Condition of minio pod turns to `False` on EKS cluster with KFP running after a few days. 
```
ubuntu@ip-10-0-15-81:~$ kubectl describe pods -n kubeflow minio-7bb869bcfc-qcqts
. . . truncated output . . .

Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   True 
  PodScheduled      True

. . . truncated output . . .
```

Trying to understand why this is happening, 
probably because cluster is out of some resources ? Service also becomes unavailable when trying to create new runs

Is there some clean up that needs to be run after job is complete to remove it completely? (There are many workflow pods in completed/error state since job is running periodically)

In general, what are some ways to debug this further?
is there a way to check for the overall health of the service? All service pods are in running state

### What did you expect to happen:
Condition to stay `True`

### Environment:
EKS cluster version - 1.16
Instances - 2 x m5.large, disk size - 20G
KFP Version 0.5.1

How did you deploy Kubeflow Pipelines (KFP)?
https://github.com/kubeflow/pipelines/blob/master/components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests#L117-L128

KFP version:
0.5.1

### Anything else you would like to add:

```
kubectl get pods -n kubeflow minio-7bb869bcfc-qcqts
NAME                     READY   STATUS    RESTARTS   AGE
minio-7bb869bcfc-qcqts   1/1     Running   0          8d
```
```
ubuntu@ip-10-0-15-81:~$ kubectl describe pods -n kubeflow minio-7bb869bcfc-qcqts
Name:           minio-7bb869bcfc-qcqts
Namespace:      kubeflow
Priority:       0
Node:           ip-10-0-231-89.ec2.internal/10.0.231.89
Start Time:     Mon, 18 May 2020 23:50:14 +0000
Labels:         app=minio
                application-crd-id=kubeflow-pipelines
                pod-template-hash=7bb869bcfc
Annotations:    kubernetes.io/psp: eks.privileged
Status:         Running
IP:             10.0.232.118
IPs:            <none>
Controlled By:  ReplicaSet/minio-7bb869bcfc
Containers:
  minio:
    Container ID:  docker://6ee17f07efdea5df6e29f06941ccb0c983c40b814527d95ef76303a7e4fb6dc5
    Image:         gcr.io/ml-pipeline/minio:RELEASE.2019-08-14T20-37-41Z-license-compliance
    Image ID:      docker-pullable://gcr.io/ml-pipeline/minio@sha256:587abc14be9bbeed794473cf7290c40e377062f2f77f5e4e27742a77680f08e0
    Port:          9000/TCP
    Host Port:     0/TCP
    Args:
      server
      /data
    State:          Running
      Started:      Mon, 18 May 2020 23:50:19 +0000
    Ready:          True
    Restart Count:  0
    Environment:
      MINIO_ACCESS_KEY:  minio
      MINIO_SECRET_KEY:  minio123
    Mounts:
      /data from data (rw,path="minio")
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-wd2sw (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  minio-pvc
    ReadOnly:   false
  default-token-wd2sw:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-wd2sw
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
```

/kind bug
/area backend

**Comment by Ark-kun** [comment]
Is there something in the logs?

`kubectl logs -n kubeflow minio-7bb869bcfc-qcqts`

**Comment by surajkota** [comment]
minio pod logs only has pointer to the dashboard 
```
Endpoint:  http://10.0.229.145:9000  http://127.0.0.1:9000

Browser Access:
   http://10.0.229.145:9000  http://127.0.0.1:9000

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
``` 
when I last saw the dashboard it only had artifacts, any other place to see logs ?

**Comment by gautamkmr** [comment]
@surajkota  what is the output for `describe pod` ?

**Comment by surajkota** [comment]
Describe pod output for minio pod is in the section `Anything else you would like to add:` of the issue

**Comment by surajkota** [comment]
On further investigation we found the following

Cluster had 2 node, each in a different availability zone(AZ). The node in AZ which had the PVC for minio was not ready to schedule minio pod because of https://github.com/kubernetes/kubernetes/issues/45419 and hence was minio was stuck

Scaling the cluster by increasing the nodes to 2 per AZ resolved the conflict
