### ISSUE TITLE
newest image is not being pulled on minikf despite image_pull_policy=Always

### ISSUE THREAD

**Issue by NicoG94** [kubeflow/pipelines#3887]
### What steps did you take:
[A clear and concise description of what the bug is.]
tried to set the image pull policy to "Always" with two ways:
ContainerOp(container_kwargs={"image_pull_policy": "Always"})

pipelineConfig = dsl.PipelineConf()
pipelineConfig.set_image_pull_policy("Always")
Compiler().compile(train_recommender_model_pipeline, 'train_modell_pipeline2.zip', pipeline_conf=pipelineConfig)

Both showed in the zip-file. But when I uploaded the zip file to my local minikf and ran the pipeline, the newest image was not pulled. Instead an older version of my image was pulled.

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?
minikf

KFP version: 
build version v1.0-56-g5ae311f8

KFP SDK version: 
kfp                                0.5.1
kfp-server-api                     0.5.0

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by Ark-kun** [comment]
>Both showed in the zip-file. But when I uploaded the zip file to my local minikf and ran the pipeline, the newest image was not pulled. Instead an older version of my image was pulled.

If that's true, then this might be a problem in your Kubernetes cluster software. Can you verify that the image_pull_policy works with plain Kubernetes pods in your cluster?

**Comment by NicoG94** [comment]
I am using MiniKF. So I do not have any other Kubernetes cluster software

**Comment by Ark-kun** [comment]
> So I do not have any other Kubernetes cluster software

I think you might have Kubernetes software. Probably Minikube.

**Comment by NicoG94** [comment]
I followed these instructions:
https://www.kubeflow.org/docs/started/workstation/getting-started-minikf/

**Comment by rmgogogo** [comment]
> I followed these instructions:
> https://www.kubeflow.org/docs/started/workstation/getting-started-minikf/

May I say it only happens in MiniKF? how about your tries in GCP?
I think it's more of a Minikube question.

Similar question for Kind. It requires "kind load .." to stage the images.

Here close but feel free reopen.
