### ISSUE TITLE
Upload Pipeline Version If already exists

### ISSUE THREAD

**Issue by talhairfanbentley** [kubeflow/pipelines#3901]
It's not a bug or issue.
**In case it doesn't exists, then it's a suggestion**

Is there any way I can upload pipeline to kubeflow via sdk, and it just uploads a version if the main pipeline already exists. 

Versions:
```
kfp                      0.4.0
kfp-server-api           0.3.0
```

**Comment by rmgogogo** [comment]
I think it's already supported. Do you mean only-upload/insert versions if there is already a pipeline there? Please update the KFP version for a retry.

@jingzhang36

**Comment by talhairfanbentley** [comment]
No, I mean. I shouldn't need to get pipeline ID before uploading a version.
As of now, the flow is.

If Pipeline Exists > Get Pipeline ID > Upload Pipeline Version
If Pipeline Does not exists > Upload Pipeline

**Comment by talhairfanbentley** [comment]
Just a little update, I have update versions, but there's no change of sort that I was looking for.
```
kfp                      0.5.1              
kfp-server-api           0.5.0 
```

**Comment by dilip640** [comment]
Thank you @talhairfanbentley  for raising this issue, I was also looking for the same feature. It should ask the `name` and `version` of the pipeline. If the pipeline name exists then upload as version otherwise upload as a new pipeline.

**Comment by NikeNano** [comment]
I will work on a PR for this. 
/assign
