### ISSUE TITLE
Missing proper retry on error

### ISSUE THREAD

**Issue by frozeNinK** [kubeflow/pipelines#3902]
https://github.com/kubeflow/pipelines/blob/c517fc579da11725a54bacb3dac80a71d3dd33be/backend/src/agent/persistence/client/pipeline_client.go#L147-L151

**Comment by frozeNinK** [comment]
@hongye-sun

**Comment by Bobgy** [comment]
also
/assign @jingzhang36

**Comment by Bobgy** [comment]
@frozeNinK Can you explain what problem it caused for you?

**Comment by frozeNinK** [comment]
my colleague and I were reading the code and found this bug, i.e. if the underlying service is unavailable, this function will return nil error, causing caller to either panic, or unable to get the result.

this function should at least propagate the error
