### ISSUE TITLE
persistent-agent service account should not bind to the cluster-admin role

### ISSUE THREAD

**Issue by lilida** [kubeflow/pipelines#3903]
### What steps did you take:
Per https://github.com/kubeflow/manifests/blob/master/pipeline/persistent-agent/base/clusterrole-binding.yaml  The role binding binds service account to cluster-admin instead of the created cluster role.

**Comment by rmgogogo** [comment]
The pipeline manifest golden source is in kubeflow/pipelines/manifests.
https://github.com/kubeflow/pipelines/tree/master/manifests/kustomize/base/pipeline
It's correct here.

@Bobgy has an action item to do some changes for auto/semi-auto sync it to kubeflow/manifests repo.

**Comment by Bobgy** [comment]
KF manifest is now referring to KFP standalone
