### ISSUE TITLE
kfp.Client(host=...) & TFX SDK should work with istio and port-forwarding

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#3907]
When istio ?ingress? service is port-forwarded, there does not seem to be a way to connect to the api server.

**Comment by rmgogogo** [comment]
Would you provide more detailed info?
1. When using kubtctl port-forward, it will directly hit the API binary without going through InverseProxy server which handles authentication.
2. Istio, would you detail more?

**Comment by Ark-kun** [comment]
Unfortunately, I do not have full detail. I've seen the customer doing

`kubectl port-forward -n istio-xxx svc/istio-?egress?-yyy`

After that they can access the UX. But putting `host="localhost:8080"` does not work for them.

They said that they port-forward to istio and not to the actual services directly since they have no access.

**Comment by rmgogogo** [comment]
would you forward me the email for this case? It's expected. When using port forward, it directly hit API server while InverseProxyServer handles the authorization/authentication.

**Comment by rmgogogo** [comment]
But anyway, I think it's a good topic. Thanks for recording it.

we may put some logic to detect whether it's not via InverseProxy, if so, then we can simply ignore the token logics.

**Comment by rmgogogo** [comment]
renamed title + "& TFX SDK"
