### ISSUE TITLE
GCP components do not seem to work with workflow identity when the default SA is deleted

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#3908]

**Comment by rmgogogo** [comment]
hi Alexey, for saving Hongye bandwidth, feel free to assign to me.

Quick question: which component here you mean? Or all GCP components?

**Comment by Ark-kun** [comment]
> Quick question: which component here you mean? Or all GCP components?

I've seen this affecting `gcp/dataproc/create_cluster` component, but it might be affecting all gcp components since they use the same client instantiation code.

**Comment by Bobgy** [comment]
@Ark-kun Can you clarify, which default SA was deleted? The compute-xxxxxx@... default GSA?

**Comment by rmgogogo** [comment]
(as detailed in email, we may close as the root cause is that WI is not well configured)
