### ISSUE TITLE
[AWS SageMaker] Region availability of pre and post task lambdas for GroundTruth

### ISSUE THREAD

**Issue by MattRose153** [kubeflow/pipelines#3916]
Hi,

Is there a reason that only a subset of regions are used in `algorithm_arn_map` in https://github.com/kubeflow/pipelines/blob/master/components/aws/sagemaker/common/_utils.py to access the AWS Pre human and Post human lambda functions? In the SageMaker API docs there are more available: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker.html#SageMaker.Client.create_labeling_job.

I think it would be helpful to limit the use of these components as little as possible.

**Comment by MattRose153** [comment]
More than happy to submit a PR for this as well, it seems like a pretty simple fix - just add in the extra regions/ARN mappings from the SageMaker docs

**Comment by awcchungster** [comment]
Hi Matt, we'll help merge this in over the next few days.
