### ISSUE TITLE
[Release] Changelog Process after 1.0

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#3920]
## Background
The current changelog tool: https://github.com/github-changelog-generator/github-changelog-generator always queries all issues and PRs, it soon ran out of github quota even if a personal token is provided. Also it's no longer actively maintained. We need to investigate a new tool that suits our need.

## Requirements
Ideally, I think we have these requirements:
* works stably
* PR authors/maintainers can edit some metadata in PR to categorize PRs in changelog, e.g. we'd want different areas, and different types (bug, feature, misc).
* it can handle cherry picks

**Comment by rmgogogo** [comment]
Or we do it like TensorFlow: for each PRs, let author/reviewer decide whether add some notes to the CHANGELOG file.

**Comment by Bobgy** [comment]
@rmgogogo Sure, we can include that as an option.

Previously discussed with @numerology too.
I think major problem is: it might cause merge conflicts often.

One way to mitigate that is dividing the section by different parts beforehand.
e.g. we may first divide by area, `ui`, `api`, `sdk/client`, `sdk/dsl`, `metadata`, `swf`...
Then we should divide by features, bugs and miscs.
So that the likelihood of having two PRs on the same area and kind decreases.

Besides that, other cons:
* requires educating every contributor to also update release doc
* release message is essentially duplicate information from PR title

pros:
* The release message is clearly written and reviewed separately

**Comment by Bobgy** [comment]
I took a look at https://github.com/semantic-release/semantic-release.

but its core philosophy is to release a version on every commit: https://github.com/semantic-release/semantic-release/issues/1389#issuecomment-565683958

I don't think it's suitable for KFP.

**Comment by Bobgy** [comment]
Another option is https://github.com/conventional-changelog/standard-version.

It parses git commits using *conventional* format like `feat(lang): add polish language`.
https://www.conventionalcommits.org/en/v1.0.0/
It is node/npm centric, but can be integrated with other systems by
https://github.com/conventional-changelog/standard-version#can-i-use-standard-version-for-additional-metadata-files-languages-or-version-files

This is a valid option to consider.

**Comment by Bobgy** [comment]
Found some good resources on this topic:
* https://depfu.com/blog/changelogs-to-write-or-to-generate
* https://github.com/github-changelog-generator/github-changelog-generator/wiki/Alternatives

**Comment by Bobgy** [comment]
Kubernetes has its own release note tool: https://github.com/kubernetes/release/tree/master/cmd/release-notes.
It will probably be a good fit because we are sharing a lot other automation tools.

**Comment by Bobgy** [comment]
So far, I think https://github.com/conventional-changelog/standard-version is the best option, commit messages will be the source of truth, we won't need to rely on data from github, so it will be very reliable.

Additionally, we are already writing PR titles as `[area] title` by ourselves, because we have a need to let title clearly show which area and type it is working on. Formalizing PR title to conventional commit style seems a natural fit.

**Comment by Bobgy** [comment]
@rmgogogo What do you think above my proposal in https://github.com/kubeflow/pipelines/issues/3920#issuecomment-642384520? Maybe I should do that in design review too?

**Comment by rmgogogo** [comment]
SG. As for design review inside G, you may make the call. I'm OK with both.

The more important thing is that we may draft a MD file e.x. to the root README.md or linked by it. So that everyone can clearly know the steps.

> tide only squashes commits to PR title when there are more than one commits:

If I have multiple commits in one PR (I normally have 2~5 commits for a middle sized PR), can it well handle it? PR can easily be edited. For commits description, I'm wondering whether it will be too complex when reviewer asks PR author to update it (when PR is pretty good and no code changes required).

BTW, it's true that TensorFlow Extended repo process also is not perfect, I already feel the pain from merge conflict.

Another cheap option is that we just don't provide CHANGELOG detailed history but put a link to https://github.com/kubeflow/pipelines/commits which shows all details. As for senmatic and middle big sized changes, we can maintain a doc and update it for big sized changes. When release it, copy to CHANGELOG file.

Feel free to make the call.

**Comment by Bobgy** [comment]
> The more important thing is that we may draft a MD file e.x. to the root README.md or linked by it. So that everyone can clearly know the steps.

+1, will do when finalized.

> > tide only squashes commits to PR title when there are more than one commits:
> 
> If I have multiple commits in one PR (I normally have 2~5 commits for a middle sized PR), can it well handle it? PR can easily be edited. For commits description, I'm wondering whether it will be too complex when reviewer asks PR author to update it (when PR is pretty good and no code changes required).

If you have multiple commits, we only need to make sure PR title is following the convention, because it will automatically be the squashed commit's message. We may add a presubmit that checks PR title is in correct form.

> Another cheap option is that we just don't provide CHANGELOG detailed history but put a link to https://github.com/kubeflow/pipelines/commits which shows all details. As for senmatic and middle big sized changes, we can maintain a doc and update it for big sized changes. When release it, copy to CHANGELOG file.

I don't really consider that as an option because there are too many noise in commit history. When we have a correct process set up, most of the PRs that updates internal stuff should no longer be visible to users. Only bug fixes and real features should be included in changelog.

**Comment by Bobgy** [comment]
After the review, we decide to try conventional changelog.
TODOs:
* [ ] p0 Verifies the tool can show fixed issue in changelog and everything else works
* [ ] p0 Draft a doc introducing how to name PR titles
* [ ] p0 Add a checklist item in PR template to introduce PR title
* [ ] p1 Add presubmit test to guarantee PR title conforms to convention
* [ ] p1 Add `merge_commit_template` to make commit message constantly come from PR title even if there's only one commit, https://github.com/kubernetes/test-infra/issues/17915#issuecomment-644919700

**Comment by Bobgy** [comment]
In fact, argo created their own release note tool that depends on conventional commits: https://github.com/alexec/github-toolkit#release-notes

**Comment by Bobgy** [comment]
We can mark this as done now.
