### ISSUE TITLE
[Question] Tensorboard spams s3 service with meaningless repeating requests

### ISSUE THREAD

**Issue by anatolyzolotar** [kubeflow/pipelines#3936]
### What happened:
Hi everyone. We've recently managed to integrate our pipeline with s3 for storing tensorboard logs 
and noticed that running pod of tensorboard viewer keeps accessing s3 endlessly and it's quite expensive. As far as I understand, the reason is that tensorboard process in tensorflow container reloads data in accordance with `reload_interval`, which has value 0.5s by default. I checked it in local container (in logs and network stats) with default value (0.5s) and with reload turned off (`--reload_interval=0`). 

### What did you expect to happen:
I don't see any reason to allow tensorboard to update data twice a second when it's supposed to read logs only after execution of pipeline step and these logs doesn't change ever. However, I can be wrong. We would like to make tensorboard load data only once.

### Questions:
1) Is there any intention why current implementation reloads data?
2) Is there any way to add tensorboard cli argument? I couldn't find spec template for such pods where we can put `--reload_interval=0` in the list of arguments and it seems like this spec is being generated [here](https://github.com/kubeflow/pipelines/blob/master/backend/src/crd/controller/viewer/reconciler/reconciler.go#L178). The only solution I can see except changing this code is to use some kind of PodDefault.

How did you deploy Kubeflow Pipelines (KFP)?

Private AWS cluster

KFP version: 0.5.0
Used tensorboard container: tensorflow/tensorflow:2.0.0

/kind question

**Comment by Bobgy** [comment]
Sorry I don't have much knowledge of tensorboard usage

/assign @rmgogogo 
Do you know if that's expected or not? Should we change the default value?

**Comment by anatolyzolotar** [comment]
Hi @rmgogogo . I would like to re-escalate this issue. The problem is quite serious in terms of excess requests and costs. 
Do you agree that this can be fixed by adding `--reload_interval=0` parameter to tensorboard args as I've described in the first message? The fix seems to be easily implementable and reasonable since logs can not be changed. 
I can add PR if you approve.

**Comment by rmgogogo** [comment]
Labeled as "help wanted". Feel free to contribute.

**Comment by rmgogogo** [comment]
more info: the "reload" is necessary for making TensorBoard works to get latest changing data. E.x. a training log be refreshed in TensorBoard metrics chart. Turn off the refresh can work as user still can refresh manually.

Considering KFP TB e2e use case is that all done and then TensorBoard, so do feel free to send out your PR. I will leave the approve to other team mates.

**Comment by Bobgy** [comment]
Thanks @rmgogogo @anatolyzolotar !
SGTM

**Comment by Bobgy** [comment]
Hmm, actually maybe no, we also have a "prepare tensorboard component" that allows watching a training in real time: https://github.com/kubeflow/pipelines/issues/4431

So this is something user need to configure when starting a new tensorboard instance.

**Comment by Bobgy** [comment]
It seems a more general issue, so I created https://github.com/kubeflow/pipelines/issues/4714 as a placeholder for related discussion.

For this specific request, we already support customizing tensorboard config via a static patch -- example: https://github.com/kubeflow/pipelines/blob/master/docs/config/volume-support.md#deploy-ml-pipeline-ui-to-support-tensorboard-viewer. Probably you can use this as a workaround.

**Comment by Bobgy** [comment]
@anatolyzolotar does the workaround help you?
Going to close, but feel free to reopen

**Comment by anatolyzolotar** [comment]
> @anatolyzolotar does the workaround help you?
> Going to close, but feel free to reopen

Thanks for your help and sorry for a late response. I guess it doesn't help with this problem. At least, I couldn't figure out how to use that config customization from volume-support doc. It's not clear what should I add there and how it can help me to put a specific argument to tensorboard command (--reload_interval=0) to, I guess, [this place](https://github.com/kubeflow/pipelines/blob/master/backend/src/crd/controller/viewer/reconciler/reconciler.go#L178).

BTW, I was wrong in my original post and must have misread source code of tensorboard. Default --reload-interval value is [5.0s, not 0.5s](https://github.com/tensorflow/tensorboard/blob/2.0/tensorboard/plugins/core/core_plugin.py#L462)
