### ISSUE TITLE
Can't start cache server

### ISSUE THREAD

**Issue by Gsantomaggio** [kubeflow/pipelines#3941]
### What steps did you take:
- Downloaded https://github.com/kubeflow/pipelines/releases/tag/1.0.0-rc.1

- removed the `gcp/inverse-proxy`:
```
# - ../gcp/inverse-proxy
```

- Deployed the pipeline locally with KIND:

```
kubectl apply -k manifests/kustomize/cluster-scoped-resources
kubectl apply -k manifests/kustomize/env/dev/
```

### What happened:
The module cache-server can't start because of:
```
kubectl certificate approve cache-server.kubeflow 
No resources found       
...
Error from server (Forbidden): certificatesigningrequests.certificates.k8s.io "cache-server.kubeflow" is forbidden: user not permitted to approve requests with signerName "kubernetes.io/legacy-unknown" 
```

### Environment:
Localhost environment on [KIND](https://kind.sigs.k8s.io/)

How did you deploy Kubeflow Pipelines (KFP)?
```
kubectl apply -k manifests/kustomize/cluster-scoped-resources
kubectl apply -k manifests/kustomize/env/dev/
```

KFP version:  1.0.0-rc1

### Anything else you would like to add:
The command works  I execute it command manually 
```
➜ kubectl certificate approve cache-server.kubeflow
certificatesigningrequest.certificates.k8s.io/cache-server.kubeflow approved
```

/kind bug
/area backend

**Comment by Gsantomaggio** [comment]
I found the problem. 
I was using Kind with k8s 1.8.

With k8s 1.6.9 it works. 
Sorry for the noise!

**Comment by pretendhigh** [comment]
I met this problem too.
I was using k8s 1.18.9
kubeflow 1.1.0

**Comment by Bobgy** [comment]
We have fixed the compatibility in a recent PR

**Comment by pretendhigh** [comment]
[https://github.com/kubeflow/pipelines/pull/4246/commits/6a767d10547a3e6b88108cc16762013ef85b4ed7#diff-a4f0ddb278e77c9d8cb2dc3e4c5a6f4578ab2ff8237cc5315f506e85745a00b8](https://github.com/kubeflow/pipelines/pull/4246/commits/6a767d10547a3e6b88108cc16762013ef85b4ed7#diff-a4f0ddb278e77c9d8cb2dc3e4c5a6f4578ab2ff8237cc5315f506e85745a00b8) 
I think this pr show the reason and the besy way maybe is to change a another version kubeflow version.

**Comment by Bobgy** [comment]
Kfp 1.0.4 just released should work with these kubernetes versions
