### ISSUE TITLE
Option for providing Environment variable at run time of the pipeline

### ISSUE THREAD

**Issue by dilip640** [kubeflow/pipelines#3943]
Hi everyone, pipeline parameters are a good way to provide configuration of the pipeline. But it's not enough. Many of us people come from DevOps background, so they use ENV variables more. There is an option to pass those variables while writing pipelines. But, there is need to change at run time. Please add a feature to provide Environment variables at runtime in Kubeflow Pipeline.

**Comment by eterna2** [comment]
u can pass pipeline parameters to env vars.

```py
import kubernetes.client as k8s

def some_pipeline(param1):
  op1 = some_op(...)
  op1.add_env_variable(k8s.V1EnvVar(name, param1))
```

U can also create transformers to do it for u.

**Comment by Bobgy** [comment]
> Please add a feature to provide Environment variables at runtime in Kubeflow Pipeline.

Another option: when you add `k8s.V1EnvVar`? Can you let it refer to a configmap?
