### ISSUE TITLE
Permanent storage for pipeline system

### ISSUE THREAD

**Issue by IronPan** [kubeflow/pipelines#395]
The Pipeline system should integrate with permanent storage, such as GCS and Cloud SQL for persisting the user's metadata. This ensures data has the lifecycle beyond the single cluster.

**Comment by Ark-kun** [comment]
Related: https://github.com/kubeflow/pipelines/issues/359

**Comment by vicaire** [comment]
@IronPan, do you have an update on this one?

**Comment by IronPan** [comment]
this is done as part of pipeline upgrade.
