### ISSUE TITLE
KFP instance HOST url changed unexpectedly on Google AI Platform Pipelines

### ISSUE THREAD

**Issue by DeshuaiWang** [kubeflow/pipelines#3950]
### What steps did you take:
I created a KFP pipeline instance on GCP AI Platform Pipelines. The KFP instance HOST URL had changed to another URL address and then changed back without any notification. It happened twice.

### What happened:
(This KFP instance had been deleted)
The original host URL is  '3650c7b699e19a64-dot-us-central2.pipelines.googleusercontent.com',
Then the URL changed to  '4d0b178d5cb318cb-dot-us-central2.pipelines.googleusercontent.com', and changed back to the original URL.
Then again, the URL changed to '4248240b760eb7ee-dot-us-central2.pipelines.googleusercontent.com' , and changed back to the original URL again.

### What did you expect to happen:
The host URL of the KFP instance should not change.

### Environment:
KFP instance is on Google AI Platform Pipelines

KFP version: 
0.5.1

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]
I have deleted the above mentioned KFP pipeline and created a new one. will see if this issue would happen again

/kind bug
 /area backend
 /area sdk

**Comment by DeshuaiWang** [comment]
update:

The newly created KFP pipeline instance also experienced this issue.

**Comment by rmgogogo** [comment]
This is already fixed but not released yet, expected we will have a new release very soon.
As a quick workaround, can replace the binary of proxy-agent to be KFP 0.5.0 which is good.

**Comment by daniel-woolworths** [comment]
> This is already fixed but not released yet, expected we will have a new release very soon.
> As a quick workaround, can replace the binary of proxy-agent to be KFP 0.5.0 which is good.

Hi rmgogogo,

Thanks for the update. Looking forward to the new release!

Cheers,
Daniel

**Comment by rmgogogo** [comment]
> > This is already fixed but not released yet, expected we will have a new release very soon.
> > As a quick workaround, can replace the binary of proxy-agent to be KFP 0.5.0 which is good.
> 
> Hi rmgogogo,
> 
> Thanks for the update. Looking forward to the new release!
> 
> Cheers,
> Daniel

FYI, the 1.0.0-rc.1 and 1.0.0-rc.2 include the fix. (however 1.0.0-rc.x is not in UI based installation but you may install it directly from kustomize

**Comment by daniel-woolworths** [comment]
> > > This is already fixed but not released yet, expected we will have a new release very soon.
> > > As a quick workaround, can replace the binary of proxy-agent to be KFP 0.5.0 which is good.
> > 
> > 
> > Hi rmgogogo,
> > Thanks for the update. Looking forward to the new release!
> > Cheers,
> > Daniel
> 
> FYI, the 1.0.0-rc.1 and 1.0.0-rc.2 include the fix. (however 1.0.0-rc.x is not in UI based installation but you may install it directly from kustomize

Got it, thanks for the information! Very much appreciated!!

**Comment by Bobgy** [comment]
Closing the issue, FYI previous issue we made the fix https://github.com/kubeflow/pipelines/issues/3143.
