### ISSUE TITLE
FR: support storage: MinIO in Kubeflow Pipeline UI to render TFMA html artifact

### ISSUE THREAD

**Issue by Mar-ai** [kubeflow/pipelines#3951]
### What steps did you take:
In the pipeline component, I generated html output from tfma (according to instructions in https://github.com/tensorflow/model-analysis/issues/10), wrapped it in .tar ball and pushed to MinIO storage.

``` 
from IPython.core.display import display, HTML
from ipywidgets.embed import embed_minimal_html

analysis_path = '/tmp/titanic_config'
result = tfma.load_eval_result(output_path=analysis_path)  
slicing_metrics_view = tfma.view.render_slicing_metrics(result,slicing_column='Pclass')
embed_minimal_html('/tmp/tfma_export.html', views=[slicing_metrics_view], title='Slicing Metrics')
html = None
with open('/tmp/tfma_export.html', 'r') as view:
        html = view.read()

# wrap in .tar ball
subprocess.call(['tar', '-cvf', "/tmp/tfma_export.tar", "/tmp/tfma_export.html"])

# push to minio
minioClient.fput_object('mybucket', 'tfma.tar', '/tmp/tfma_export.tar')

# add file to metadata
 metadata = {"outputs":
                [
                    {
                        'type':'web-app',
                        'storage': 'minio',
                        'source': 'minio://mybucket/tfma.tar'
                    }  
                 ] }

```

The html is created correctly (can be viewed in browser) and the .tar file is stored in MinIO. 

### What happened:
The artifact window remains blank. 

### What did you expect to happen:
TFMA plot is rendered. 

### Environment:
TFMA version:  0.21.6
KFP SDK version: 0.5.1 

/kind feature

**Comment by Bobgy** [comment]
Hi @Mar-ai 
storage: minio is not supported.

For quick workaround, I'd suggest `storage: inline` instead and put the html content inside `source` entry.
see https://www.kubeflow.org/docs/pipelines/sdk/output-viewer/

**Comment by Bobgy** [comment]
Do you want to change the issue to be a feature request?

**Comment by Mar-ai** [comment]
Hi @Bobgy, thanks for the reply, I'd like to change the issue to be a feature request. 

Unfortunately, the workaround with```storage:inline``` does not work: using the example from https://www.kubeflow.org/docs/pipelines/sdk/output-viewer/ 

```
{
      'type': 'web-app',
      'storage': 'inline',
      'source': '<h1>Hello, World!</h1>',
    }
```

throws an Error: 

```
     Uncaught (in promise) Error: Unsupported storage path: <h1>Hello, World!</h1>
    at Function.e.parseStoragePath (WorkflowParser.ts:369)
    at Function.<anonymous> (OutputArtifactLoader.ts:192)
    at OutputArtifactLoader.ts:1
    at Object.next (OutputArtifactLoader.ts:1)
    at OutputArtifactLoader.ts:1
    at new Promise (<anonymous>)
    at l (OutputArtifactLoader.ts:1)
    at Function.e.buildHtmlViewerConfig (OutputArtifactLoader.ts:188)
    at Function.<anonymous> (OutputArtifactLoader.ts:79)
    at OutputArtifactLoader.ts:1
  
```

**Comment by Bobgy** [comment]
@Mar-ai 
> Be aware, support for inline visualizations, other than markdown, was introduced in Kubeflow Pipelines 0.2.5.

Was your KFP server above this version?

**Comment by Mar-ai** [comment]
Sorry for the late reply @Bobgy. Indeed we're still on version 0.2.0. 
Thank you!

**Comment by Bobgy** [comment]
No problem

**Comment by Bobgy** [comment]
Ohhh, forgot this is a FR

**Comment by Mar-ai** [comment]
Please leave this issue open, as this is a feature request

**Comment by Mar-ai** [comment]
Please keep Feature Request open

**Comment by Bobgy** [comment]
In fact, MinIO is now supported, your example should already work now.

Feel free to reopen if that's not the case
