### ISSUE TITLE
Process: using GCP eX (e.x. e2) machine type instead of nX (e.x. n2) for test infra

### ISSUE THREAD

**Issue by rmgogogo** [kubeflow/pipelines#3952]
Currently we using nX machine type. It's suggested and asked by other team that better we migrate to eX.

1. cloud build machine type
2. test scripts which create clusters
3. possible samples / docs

**Comment by Bobgy** [comment]
@rmgogogo do you want to pick it? If not, you can assign it to me

**Comment by rmgogogo** [comment]
Feel free to pick up when have time. 

I will revisit around Wednesday/Thursday and can handle it if your side has less bandwidth.

**Comment by Bobgy** [comment]
I'll take this today then, it should be relatively easy.
/assign @Bobgy
