### ISSUE TITLE
GCS components do not support parallel composite uploads

### ISSUE THREAD

**Issue by jackwhelpton** [kubeflow/pipelines#3955]
### What steps did you take:
Used the GCS components provided as part of the Kubeflow source code here:

https://github.com/kubeflow/pipelines/blob/master/components/google-cloud/storage/upload_to_explicit_uri/component.yaml

to upload large files.

### What happened:

These components did not allow setting of `parallel_composite_upload_threshold` to perform uploads of large files in parallel.

### What did you expect to happen:

Parallel composite uploads to be available.

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

KFP version:  Build commit: 9c16e12

KFP SDK version: 
kfp                      0.5.1
kfp-server-api           0.3.0

### Anything else you would like to add:
I have a PR open that adds this functionality, but raised this issue for discussion of that PR and to help get it merged.

https://github.com/kubeflow/pipelines/pull/3762

Since raising it, I've also found use for another GCS component, which I call `sync_dir_contents`: its purpose is to allow the uploading of a directory's contents without uploading the directory itself, which it does by using `rsync` rather than `cp`. I'm hoping I can get that functionality in at the same time, as it seems general enough to be useful to all.

/kind bug

**Comment by Ark-kun** [comment]
Thank you for your patience. We've been preparing several big releases and that has taken some of our resources.

I have several questions:

What are the downsides of parallel_composite_upload_threshold? I've heard that the clients will need to have crcmod installed to be able to download such blobs.

What is the typical size when this option becomes important?

**Comment by jackwhelpton** [comment]
No worries about the delay, I just wanted to make sure this hadn't escaped attention altogether. You're right, the principal downside to `parallel_composite_upload_threshold` is that downloading the file via `gsutil` requires a compiled version of `crcmod`. We've found this to be less of a problem than it sounds for the following reasons:

* "Novice" users tend to download files from GCS buckets via the GCP UI: this works regardless of the use of parallel composite uploads
* "Intermediate" users tend to be using either a Windows or MacOS platform: in the latter case, `gsutil` is bundled with a compiled `crcmod` so things just work. In the former I thought this was also the case—I actually run a Windows OS and have the required dependency—but `gsutil help crcmod` suggests there may be an additional installation step. It's possible I did this a while ago and forgot about it, or that recent Windows updates include a compiled `crcmod`. I can verify on a clean machine.
* "Advanced" users, running a Linux distro, just need to `pip install crcmod`
* Also worth noting: all of the gcloud docker images (`google/cloud-sdk`, `google/cloud-sdk:slim`, `google/cloud-sdk:alpine`) already include the compiled `crcmod`

So to sum up, my experience has been that the more likely this is to trip users up, the more likely that those are precisely the more advanced users that can handle this without problem.

The typical size when parallel uploads start to be substantially faster is around the 150MB mark, which is why this was chosen as the default value: that number also features in several examples in Google documentation that I can probably track down. For us it was _really_ pronounced with model files that were of the order of 1GB+.

Note that with the threshold set, parallel uploads will only be used when the file size exceeds that threshold, so the user doesn't have to do that checking themselves.

Google are apparently actively working with several common distros to get a compiled `crcmod` included by default, and have in turn not made this the default behavior until that happens. We could follow a similar tack: in that case I'd be tempted to introduce a further boolean parameter, say `compose`, which would enable the feature with the default 150MB threshold. This would also be implied to be `true` if the threshold was explicitly supplied. How to handle `compose: false, parallel_composite_upload_threshold='150M'` would need some thought: I suspect it should not perform a parallel composite upload.

My reason for not adopting that tack initially is that it requires every pipeline author to know about and opt in to parallel uploads, whereas defaulting to a 150MB threshold means that "the right thing" happens without requiring that thought process by every author.

**Comment by jackwhelpton** [comment]
Perhaps the most compelling argument for the 150MB threshold can be found in the `gsutil` source: for files above that size, `gsutil` will prompt users to enable parallel composite uploads.

https://github.com/GoogleCloudPlatform/gsutil/blob/11b9f1f4cc160180b85227ccf1df40b0797dab0e/gslib/utils/copy_helper.py#L274
