### ISSUE TITLE
kfservingdeployer doesn not expect --service-account

### ISSUE THREAD

**Issue by stampcrab** [kubeflow/pipelines#3960]
I tried component.yaml with the image aipipeline/kfserving-component:v0.2.1 using the --service-account and getting the following error:
usage: kfservingdeployer.py [-h] [--action ACTION] [--model-name MODEL_NAME]
[--default-model-uri DEFAULT_MODEL_URI]
[--canary-model-uri CANARY_MODEL_URI]
[--canary-model-traffic CANARY_MODEL_TRAFFIC]
[--namespace NAMESPACE] [--framework FRAMEWORK]
[--default-custom-model-spec DEFAULT_CUSTOM_MODEL_SPEC]
[--canary-custom-model-spec CANARY_CUSTOM_MODEL_SPEC]
[--kfserving-endpoint KFSERVING_ENDPOINT]
[--autoscaling-target AUTOSCALING_TARGET]
[--output_path OUTPUT_PATH]
kfservingdeployer.py: error: unrecognized arguments: --service-account kfsa --output-path /tmp/outputs/Service_Endpoint_URI/data

**Comment by rmgogogo** [comment]
please remove the kfserving issue to KF serving project.

Or correct me if I didn't get the problem root cause.
