### ISSUE TITLE
Visualize Results in table sorted by first columns as string, Can I turn off sort and just show as I write in mlpipeline-ui-metadata.json?

### ISSUE THREAD

**Issue by tarjintor** [kubeflow/pipelines#3974]
Hello,I am using pipeline 0.5.1
I am visualizing some results in table format, and find my table didn't sorted as I write in mlpipeline-ui-metadata.json,but sort by first column,and it's sorted as the type is string,which is not I want
![捕获](https://user-images.githubusercontent.com/12421352/84454582-787c4e00-ac8d-11ea-8421-1cc861d1c480.PNG)

I find in visualizing confusion matrix,it has a attr schema to tell column's type, but not in table

What can I do?

**Comment by Bobgy** [comment]
Thanks for the report!
We'd welcome contributions on this.

Frontend contribution guide: https://github.com/kubeflow/pipelines/tree/master/frontend
Related table component: https://github.com/kubeflow/pipelines/blob/master/frontend/src/components/viewers/PagedTable.tsx#L186

looks like it's sorting as string as you mentioned in the issue
