### ISSUE TITLE
Initialize kfp SDK Client on AWS

### ISSUE THREAD

**Issue by fakeburst** [kubeflow/pipelines#3988]
I'm trying to automate pipeline deployment with Jenkins and `kfp.Client().upload_pipeline()` but I cannot figure out how should I generate a token for Client initialization.  
```python
client = kfp.Client(
        host=host,
        existing_token=token,
    )
```
Could someone please point me to where should I get the token from?

Our cluster is deployed on AWS with Cognito login.

How did you deploy Kubeflow Pipelines (KFP)?
As a part of Kubeflow installation

KFP version: build commit 743746b
KFP SDK version: kfp 0.5.1; kfp-server-api 0.5.0

/kind question
/area sdk

**Comment by eterna2** [comment]
if i am not wrong, kfp.Client only support GCP IAP. The alternatives are running the notebook or code within the k8s cluster itself, or provide the k8s host and credentials. 

i.e. if ur jenkins is in the same k8s cluster, it shld work fine w/o the token.

**Comment by fakeburst** [comment]
@eterna2 I was told the same on kubeflow slack, thanks for the confirmation!

I ended up building a docker image with kubectl pointing to our kubeflow cluster, so that `kfp.Client()` automatically connects to the right host with no token provided.

**Comment by Ark-kun** [comment]
@eterna2 @Tomcli 
Is there a portable solution that could enable to connect to a KPF cluster on AWS? For example OAuth tokens, etc.

**Comment by joeyaza** [comment]
im trying to do the same as above. Have a Kubeflow instance access via Cognito but cannot seem to gain access with 
`client = kfp.Client(
        host=host,
        existing_token=token,
    )`

using the token I have gained from `/oauth2/token` endpoint. Is this route not possible with AWS? if not is there another way to programmatically access Kubeflow on aws?
thanks!
