### ISSUE TITLE
Component names are truncated in the UX

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#3989]
Maybe we can [wrap](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap) the component names (2-3 lines) so that it's possible to distinguish components in the UX:

![image](https://user-images.githubusercontent.com/1829149/84710675-89d98a80-af19-11ea-8427-683a86f913b9.png)

**Comment by Bobgy** [comment]
sounds reasonable to me.
