### ISSUE TITLE
Any guideline for updating the CI build to include new component images?

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/pipelines#3990]
/question

Related #1436
We had a similar issue last year on how to update the CI build for the new component images. The issue ended up buried so our team use the dockerhub to temporary hosting these images. We want to figure out what's the best practice for maintaining these new component images.

**Comment by Ark-kun** [comment]
I'm working on a script that would make updating individual components easier.

Adding new images to the existing release process is not easy at this moment due to strict licensing requirements. Adding image to CI is possible, but those images will be private until released semi-manually.
