### ISSUE TITLE
Update MLMD-envoy image to be on latest code changes

### ISSUE THREAD

**Issue by rmgogogo** [kubeflow/pipelines#3997]
[1] https://github.com/kubeflow/pipelines/pull/3413/files
[2] https://github.com/kubeflow/pipelines/blob/master/manifests/kustomize/base/metadata/metadata-envoy-deployment.yaml#L19

We have fix in [1] but [2] didn't catch it due to release process. We may manually update the image.

MKP version is correct. We may use tag based on MKP binary.

https://pantheon.corp.google.com/gcr/images/ml-pipeline/GLOBAL/google/pipelines/metadataenvoy?gcrImageListsize=30
https://github.com/kubeflow/pipelines/blob/master/.release.cloudbuild.yaml

**Comment by Bobgy** [comment]
Fixed by https://github.com/kubeflow/pipelines/pull/4026
