### ISSUE TITLE
Expose execution logs as a component output artifact that can be passed to other components

### ISSUE THREAD

**Issue by jackwhelpton** [kubeflow/pipelines#3998]
### What steps did you take:
Created a component with an output parameter called `model`. When using this component in a pipeline, two output artifacts are visible in the UI:

* `train-inception-resnet-v2-model-model` (effectively `step_name`-`output_param_name`)
* `main-logs`

I want to consume both of these in a subsequent step, i.e. upload both a trained model and the corresponding log file. I know the logs are available in the UI, but I want to copy them to a GCS bucket with the trained model so they are available to non-Kubeflow users.

I tried referencing the logs from this step using:

```
train_task.outputs["main-logs"]
```

### What happened:

```
KeyError: 'main-logs'
```

### What did you expect to happen:

To have access to the log artifact from a previous step.

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

KFP version: 
Build commit: 9c16e12

KFP SDK version: 
kfp                      0.5.1
kfp-server-api           0.5.0

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by Ark-kun** [comment]
`main-logs` is not a component output, so it's not possible to pass it to the next component. It's a orchestrator-added artifact which is an implementation detail. In the future we might stop showing it and just use it for showing logs in the Log tab instead.

If you need to output the logs, you should do it explicitly by adding an output and using `outputFile`/`OutputFile` to request a file path for that output. You can then setup the logging in your component so that it logs both to a file and to STDERR.

**Comment by jackwhelpton** [comment]
OK, that lets me do what I was trying to do, cheers. I was wondering if there was a more general pipeline-level approach which would allow stdout/stderr to be captured even in the case where, for example, the component is provided by a third party and the source is not available.

**Comment by Ark-kun** [comment]
We'd like to know your scenario where you want to pass logs to the next component.

BTW, log artifacts are only available if the component completes successfully.

**Comment by jackwhelpton** [comment]
Sure, here's a bit more background. We have a whole set of pipelines with a very similar three-component setup:

1. Pull training data from a GCS bucket
2. Use training data to train a model: in the example I'm looking at this is done using the Keras `applications` package
3. Push trained model to a (different) GCS bucket

In the middle component, the `stdout` output provides details about the accuracy of the model after each epoch, text like:

```
1536/1536 [==============================] - 365s 237ms/step - loss: 0.1701 - acc: 0.9444 - val_loss: 0.6407 - val_acc: 0.8700
Epoch 00100: acc improved from 0.94431 to 0.94457, saving model to weights.best.hdf5
```

It is useful to keep this information alongside the model in the output bucket, so it can be inspected by somebody evaluating the model who may not have access to the Kubeflow instance used to train it.

One thing I still need to investigate is the possibility of parsing this output and populating a metrics JSON file, but that's more of use for Kubeflow users and probably supplements rather than replaces this need for training logs to be available to people alongside the trained model.

Does that clarify things? If you've got any further questions let me know.

**Comment by Ark-kun** [comment]
> In the middle component, the `stdout` output provides details about the accuracy of the model after each epoch, text like:

I'd change the trainer components to explicitly output the metrics and other pieces of information that might be useful. It's also possible to have a predictor component that evaluates the model on a different dataset. The results can then be compared to the true results to calculate and output the metrics.

**Comment by jackwhelpton** [comment]
Right, in my case that's what I've done: this is possible because the middle component is something that we've written. That's why I indicated above that this workaround suffices for my case.

However, you can imagine a scenario in which that middle step is being loaded via `kfp.components.load_component_from_url` and is not something that the pipeline author has the ability to change. If it's worth keeping this ticket open, presumably it would be to provide the ability to access the logs for such a step within the pipeline.

**Comment by rmgogogo** [comment]
(I put this to post 1.0 backlog for a well track)
We need to abstract a layer to fetching task logs when we support IR.

@Bobgy

**Comment by Bobgy** [comment]
I believe this should be addressed by https://github.com/kubeflow/pipelines/pull/4493#issuecomment-694803381. If we expose an api server endpoint for logs.
