### ISSUE TITLE
Ensure the Metadata Artifact UI can work when all properties are replaced with custom properties

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#4000]
We need to check that all accesses to MLMD artifact properties try reading from custom_properties as well.
This is needed so that the Metadata Writer can switch to schema-less artifact types.

**Comment by Bobgy** [comment]
@Ark-kun I think it will be easier if you build a metadata-writer image first switching everything. I can get it running in a cluster and verify what fixes I need to do with UI.

**Comment by Ark-kun** [comment]
Here is the PR: https://github.com/kubeflow/pipelines/pull/4004

**Comment by Bobgy** [comment]
@Ark-kun did tfx already change?
So I guess this should better be in 1.0, is that right?

**Comment by Bobgy** [comment]
Nothing needs update per https://github.com/kubeflow/pipelines/pull/4004#issuecomment-645143372
/close
