### ISSUE TITLE
Update MLMD clients to 0.22.1

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#4013]
/assign @dushyanthsc 
Follow up of https://github.com/kubeflow/pipelines/pull/3982

**Comment by rmgogogo** [comment]
can we close this one?

**Comment by Bobgy** [comment]
No, @dushyanthsc also need to update metadata-writer's usage of mlmd client and frontend client
https://github.com/kubeflow/pipelines/pull/3982#issuecomment-644508517
https://github.com/kubeflow/pipelines/pull/3658/files#diff-ea967cf037de3503a92911b5c390b596R202

**Comment by Ark-kun** [comment]
> need to update metadata-writer's usage of mlmd client

That's completed: https://github.com/kubeflow/pipelines/pull/4027

**Comment by Bobgy** [comment]
Thanks Ark-kun! Then the only one left is upgrading frontend client.

**Comment by Bobgy** [comment]
@dushyanthsc Did you figure out how to upgrade frontend clients? If not we can also defer this to post 1.0 but with priority.

**Comment by dushyanthsc** [comment]
@Bobgy This was not a requirement for 1.0 release. I am working with Kwasi to get the front-end changes in.

**Comment by Bobgy** [comment]
Thanks! I won't explicitly wait for this then, but if it came up in time. I'll cherry pick them.

**Comment by Bobgy** [comment]
TODO:
* [ ] Update kubeflow/frontend version in kfp repo
