### ISSUE TITLE
Unable to Update annotations in component spec from pipeline parameters

### ISSUE THREAD

**Issue by ksonbol** [kubeflow/pipelines#4020]
### What steps did you take:
Create this component file `hello_component.yaml`
```
name: Hello component
description: Prints hello world
metadata:
  annotations:
    my_annotation: "some text"
implementation:
  container:
    image: image="library/bash:4.4.23",
    command: [sh, -c]
    args: [echo, "hello, World!"]
```
and this pipeline file `hello_pipeline.py`
```
import kfp
from kfp import dsl

hello_op = kfp.components.load_component_from_file('hello_component.yaml')

@dsl.pipeline(
    name="Hello World Pipeline",
    description="This pipeline prints hello, world!")
def hello_pipeline(input_annot: str):
    hello_op.component_spec.metadata.annotations['my_annot'] = input_annot
    hello_op() 
```

Try to compile the pipeline with:
`dsl-compile --py hello_pipeline.py --output hello_pipeline.yaml`

### What happened:
I receive this error,
```
Traceback (most recent call last):
  File "/Users/karim.sonbol/venv/bin/dsl-compile", line 8, in <module>
    sys.exit(main())
  File "/Users/karim.sonbol/venv/lib/python3.7/site-packages/kfp/compiler/main.py", line 148, in main
    not args.disable_telemetry
  File "/Users/karim.sonbol/adevinta/text_classifier/venv/lib/python3.7/site-packages/kfp/compiler/main.py", line 132, in compile_pyfile
    allow_telemetry=allow_telemetry)
  File "/Users/karim.sonbol/venv/lib/python3.7/site-packages/kfp/compiler/main.py", line 86, in _compile_pipeline_function
    pipeline_func, output_path, type_check, allow_telemetry=allow_telemetry)
  File "/Users/karim.sonbol/venv/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 926, in compile
    allow_telemetry=allow_telemetry)
  File "/Users/karim.sonbol/venv/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 983, in _create_and_write_workflow
    allow_telemetry)
  File "/Users/karim.sonbol/venv/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 847, in _create_workflow
    pipeline_conf,
  File "/Users/karim.sonbol/venv/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 642, in _create_pipeline_workflow
    templates = self._create_dag_templates(pipeline, op_transformers)
  File "/Users/karim.sonbol/venv/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 618, in _create_dag_templates
    templates.extend(op_to_templates_handler(op))
  File "/Users/karim.sonbol/venv/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 570, in <lambda>
    op_to_templates_handler = op_to_templates_handler or (lambda op : [_op_to_template(op)])
  File "/Users/karim.sonbol/venv/lib/python3.7/site-packages/kfp/compiler/_op_to_template.py", line 278, in _op_to_template
    template.setdefault('metadata', {}).setdefault('annotations', {})['pipelines.kubeflow.org/component_spec'] = json.dumps(op._metadata.to_dict(), sort_keys=True)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PipelineParam is not JSON serializable
```
### What did you expect to happen:
A successful compilation to YAML.

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

Did not deploy, just compiling the pipeline file fails.

KFP version: 
NA

KFP SDK version: 
0.5.1

### Anything else you would like to add:
It works fine if I update the annotation directly from a string:
`    hello_op.component_spec.metadata.annotations['my_annot'] = 'different text'
`

Also, this is probably related to this issue #4019, but imho it is not a duplicate.

/kind bug

**Comment by Ark-kun** [comment]
Currently, updating the loaded ComponentSpec is not supported.
Also by design *components* cannot have have any references like PipelineParams. Only *tasks (component instances)* can be customized and use something taken from pipeline parameters or task outputs.

What you want can be accomplished by the following:
```python
def hello_pipeline(input_annot: str):
    hello_task = hello_op()
    hello_task.add_annotation('my_annot', input_annot)
```

P.S. The scenario looks pretty weird. Can you tell us how you are going to use the annotations?

**Comment by Ark-kun** [comment]
Actually, it looks like you code is working to some extent. Although that's more of a bug than a feature - `component_spec.metadata.annotations` is a `Dict[str, str]`, so it's invalid to put `PipelineParam`s there.

**Comment by ksonbol** [comment]
Thanks for the quick response and for the clarification. Indeed, updating the task makes more sense and looks cleaner. However, does this method `add_annotation` actually exist? I couldn't find it in the code or docs except for [this example](https://github.com/kubeflow/pipelines/blob/ef381aafccf916482d16774cac3b8568d06dff9e/samples/core/pipeline_transformers/pipeline_transformers.py#L28).

In fact, could you perhaps explain that example a bit? Because it seems to be adding a hard-coded annotation which doesn't make much sense. Or I didn't understand transformers correctly.

**P.S**: about `Currently, updating the loaded ComponentSpec is not supported.`
Well, updating it works just fine if I use a string not a PipelineParam. Even more, with the same trick I was able to update the image field with a PipelieParam without problem! I only encountered this problem with annotations.

`P.S. The scenario looks pretty weird. Can you tell us how you are going to use the annotations?`
I would like to use a generic pipeline that can be customized for different models. So, I need to parameterize not just the inputs but also things the docker image and some annotations. 

For the annotations, I include the AWS IAM role to be able to use the same pipeline from different environments (using different accounts).

Generally speaking, I am trying to achieve something similar to what can be done with [Kustomize](https://kubectl.docs.kubernetes.io/pages/reference/kustomize.html) and Argo workflows (using base and an overlay for each environment). Can you recommend a better way to achieve this?

**Comment by ksonbol** [comment]
I should mention that I only tried this since input values are not supported in annotations spec #4019.

**Comment by Ark-kun** [comment]
> However, does this method `add_annotation` actually exist?

Sorry. The correct spelling is `add_pod_annotation`.

>I couldn't find it in the code or docs

Looks like our documentation generation has an issue with inherited members. Fixing it now.
`add_pod_annotation` is a method of `ContainerOp` (which represents KFP's tasks)
https://github.com/kubeflow/pipelines/blob/b63dd3f53237f74ae7f965441fd97698fafba7c9/sdk/python/kfp/dsl/_container_op.py#L843

>In fact, could you perhaps explain that example a bit? Because it seems to be adding a hard-coded annotation which doesn't make much sense.

That's true. It adds compile-time hardcoded annotations. It might still serve some purpose. Maybe there are some services installed in Kubernetes that modify pods based on annotations or labels.
The idea of transformers is to apply something to all ops in one go. It also allows separating customizations from the pipeline code, so that the same pipeline can be used with different customizations (e.g. different secrets). The full separation is obviously impossible when customizations use `PipelineParam`s though.

>>Currently, updating the loaded ComponentSpec is not supported.
>Well, updating it works just fine if I use a string
That's true. But even I, the author, was not sure it would work. We did not consider modification of loaded component structures, so YMMV. It's best to consider them immutable.

>For the annotations, I include the AWS IAM role to be able to use the same pipeline from different environments (using different accounts).

Ideally, these things should be set on the cluster side. AFAIK it's possible to specify the service account that will be used for all pipeline runs and on different clusters it can be different. Would that solve your need?

Generally, we try not to hard-code any environment-specific information in the compiled pipelines.

**Comment by ksonbol** [comment]
Thanks for the explanation.

About the service accounts, is there any method similar to `add_pod_annotation` that allows setting the service account for a single task or a pipeline? I couldn't find such a thing in the code.

**Comment by Ark-kun** [comment]
> About the service accounts, is there any method similar to `add_pod_annotation` that allows setting the service account for a single task or a pipeline? I couldn't find such a thing in the code.

We do not support setting the service account per-task. 
We decided not to support setting the service account in the pipeline. https://github.com/kubeflow/pipelines/pull/3361 Although it can be put there manually and it will work.

But the service account for the run can be specified in the UX at the run submission time. https://github.com/kubeflow/pipelines/pull/3651
And the backend API allows specifying the SA when submitting the run https://github.com/kubeflow/pipelines/blob/091316b8bf3790e14e2418843ff67a3072cfadc0/backend/api/python_http_client/kfp_server_api/models/api_run.py#L56 Although this is not exposed in the high-level kfp.Client.

We've done some work on namespace-based isolation and in that case each namespace can have `pipeline-runner` SA with different permissions.

What do you think?

**Comment by ksonbol** [comment]
I like the idea of setting the service account at run submission time but I need to set that using the kfp.Client as well. I think it is supposed to more or less have the same functionality as the UI, right?

**Comment by Ark-kun** [comment]
>be able to use the same pipeline from different environments (using different accounts).
I wonder whether those environments can all have the `pipeline-runner` service account with different roles/permissions attached.

>I think it is supposed to more or less have the same functionality as the UI, right?
That's true. The lower-level client has everything. `kfp.Client().runs.create_run(...)` supports service_account. But it's inconvenient to use.
 We'll work on exposing the service_account in `kfp.Client().create_run_from_pipeline_func(...)` as `kfp.Client().run_pipeline(...)`.
