### ISSUE TITLE
multi-user: Namespace Pipeline Definitions

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/pipelines#4022]
@Bobgy @IronPan I understand that the current state of Pipelines is that Runs/Experiments are namespaced, but pipeline definitions aren't.
I recall from an older discussion that:
* You mentioned that users want a global pipeline registry, which is a very valid use-case, so that's why you keep pipeline definitions global for now.
* We discussed about having both namespaced and global pipelines, based on an extra field in the database schema.
 
Given that pipeline definitions are essentially code and it doesn't seem reasonable to ask all teams to share all their code, what is your plan about supporting namespaced pipeline definitions (alongside global pipeline definitions), so that teams can keep their pipelines/code isolated?
I couldn't find a relevant issue so I created a new one.

**Comment by Bobgy** [comment]
/cc @IronPan 

I don't think we have a plan to support that unless we gather further feedback. You are welcome to contribute the feature flag.

**Comment by Bobgy** [comment]
/lifecycle frozen

This is one of the top feature requests from multi user support issue.

**Comment by Bobgy** [comment]
Duplicates https://github.com/kubeflow/pipelines/issues/4197

Let's use that issue to track this.
