### ISSUE TITLE
Trying to get run status with SDK returns None

### ISSUE THREAD

**Issue by sudivate** [kubeflow/pipelines#4028]
### What steps did you take:
I'm trying to get run status based on run id with kfp client. But the kfp.Client.get_run([run_id]) returns run with type None. 

However, I can get the run status through REST API  GET /apis/v1beta1/runs/{run_id}

KFP SDK version: 0.5.1

/kind bug
/area backend

**Comment by numerology** [comment]
Hi @sudivate , does any other Client function works? Like `.list_runs()`?

Also do you mind sharing how did you deploy your KFP?

**Comment by sudivate** [comment]
@numerology thanks for responding I got this working. I was configuring the client incorrectly with just host IP. 

Adding /pipeline to the host IP worked  

This is good to close :)

**Comment by Ark-kun** [comment]
> Adding /pipeline to the host IP worked

@numerology Do we have a clear documentation about when `/pipeline` is needed? (Also when `https://` is needed or not needed). Can we handle cases when users do not specify `/pipeline`?

**Comment by numerology** [comment]
@Ark-kun 

My understanding is that, currently when authenticated through IAP (i.e., full-fledged deployment), `/pipeline` and `https://` is needed. When authenticated through inverse proxy, `/pipeline` should not be included and `https://` does not matter. It seems like we shall improve our doc.

/cc @chensun in case I'm wrong re: IAP authentication.

**Comment by Bobgy** [comment]
Yes, they are right.
I've scheduled related doc as Part of KFP 1.0

**Comment by rmgogogo** [comment]
> This is good to close :)

close this one.
