### ISSUE TITLE
FR: allow fetching individual components\steps run status within pipeline using SDK

### ISSUE THREAD

**Issue by sudivate** [kubeflow/pipelines#4030]
Is there a way to pull the status of individual components\steps within a pipeline using SDK? 

**Scenario:**
I'm trying to use exit_handler to signal particular service on any component failure within the pipeline before the run completes. 

I understand that kfp.Client.get_run() will provide run status for entire run on completion, but I need the status for individual components **before the run completes.**   

/area sdk

**Comment by Ark-kun** [comment]
>I understand that kfp.Client.get_run() will provide run status for entire run on completion, but I need the status for individual components before the run completes.

Are you sure `get_run` does not not give up to date results in the middle of a run?

In any case, this needs to be supported by backend.

/cc @jingzhang36

**Comment by sudivate** [comment]
@Ark-kun  Yes `get_run  does not give details KFP SDK 0.5.1

**Comment by rmgogogo** [comment]
(put to post 1.0 backlog for a discussion on whether/when we support this).

> I'm trying to use exit_handler to signal particular service on any component failure within the pipeline before the run completes.
Quick question, why need this detailed status? I didn't connect it with the upper sentence. If you mean to use onExit to signal other system when certain step fails, I think it's already there and doable without this FR.

**Comment by Bobgy** [comment]
@sudivate Can you check the `run.pipeline_runtime.workflow_manifest` field using `get_run`?
It contains argo workflow **including status**. e.g. KFP UI is using it to visualize runtime status of the workflow.

the workflow object might delay for a few seconds (waiting for a persistence agent to sync it into KFP DB), so I'd suggest adding a wait and timeout in the exit handler to make sure you get the latest state.

**Comment by Bobgy** [comment]
We may consider a KFP native way without exposing argo details if this is a common request.

@rmgogogo I think an IR status representation will be the best approach (both UI and this requested API should be powered by IR status).

**Comment by rmgogogo** [comment]
> We may consider a KFP native way without exposing argo details if this is a common request.
> 
> @rmgogogo I think an IR status representation will be the best approach (both UI and this requested API should be powered by IR status).

definitelly.

However before we start expose it, I still didn't understand why @sudivate request it as the "Scenario" seems not the reason.

**Comment by Bobgy** [comment]
@rmgogogo from my understanding @sudivate want the pipeline to report which step/component failed in the exit handler step.
Thus exit handler needs to get runtime status info of the current (unfinished) pipeline.
