### ISSUE TITLE
Compilation should fail when user passes the whole task instead of one output to an input

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#4040]
Example broken code which should fail:
```
my_task1 = my_op1()
my_op2(my_task1)
```

The correct code:
```
my_task1 = my_op1()
my_op2(my_task1.output)
```

Currently the ContainerOp is silently converted to a big string constant and passed downstream which also triggers problems with data passing.

**Comment by PatrickXYS** [comment]
Looking to see if I can help
