### ISSUE TITLE
SDK -Python components - Replace the default image with the official python image

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#4041]
The tensorflow default image is big and outdated. It's also framework-specific while we want the SDK to be framework-neutral.

**Comment by rmgogogo** [comment]
+1, I remember we already have a ticket on it. will close that one and keep this one.

more info: current tfx image is 2G+ in gcr.io and "docker images" shows it's 5G+.

1. We use other images as Alexey mentioned for simplicity
2. (TFX) split it for detailed purpose, e.x. in upcoming new design for IR, we only need Driver and a simple publisher which should be small sized. It will be a dedicated image.
3. (TFX) TFX docker image can be improved, currently it directly packge the bazel built workspace which is too big. It can copy over the built result to a new base. It can save size a lot.

**Comment by Ark-kun** [comment]
It's also trivial for the users to go back to the tensorflow image if they want:

```python
my_op = create_component_from_func(my_func, base_image='tensorflow/tensorflow:1.3.0-py3')
```

>I remember we already have a ticket on it

Cool. Please link it here if you find it.
