### ISSUE TITLE
[Question] How can I connect my local environment to a remote Pipeline cluster running on EKS

### ISSUE THREAD

**Issue by jonasboecquaert** [kubeflow/pipelines#4048]
### What happened:
We have deployed Kubeflow on EKS using the provided documentation on the Kubeflow website, and it all works as expected. I however would like to develop my code locally and start a pipeline run remotely, instead of starting and using a notebook server. Is there a way to authenticate locally using `kfp.Client()` in AWS, in a similar way we can authenticate using IAP on GCP?
Is it even possible with our particular setup?

### Environment:
How did you deploy Kubeflow Pipelines (KFP)?
We used the following documentation: https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/
We have setup Kubeflow with authentication and authorization using OIDC.

KFP version: build commit - 743746b

/kind question

**Comment by PatrickXYS** [comment]
@Bobgy I wonder if this is expected behavior for users:

1. Develop code locally
2. Use `kfp.Client()` to **authenticate** themselves and submit a pipeline run. 

May I know other vendors solutions?

**Comment by Bobgy** [comment]
Yes, it's one of the supported develop options.
For GCP, we have some GCP native mechanisms that help users authenticate (e.g. they are required to authenticate through gcloud CLI, or using an OAuth2 token).

I think @Jeffwan is working on these for AWS in https://github.com/kubeflow/pipelines/pull/4182.

**Comment by PatrickXYS** [comment]
Cool, I think the PR will close this issue.
