### ISSUE TITLE
Pipeline GCP sample components need to switch to default gcp ops

### ISSUE THREAD

**Issue by IronPan** [kubeflow/pipelines#406]
Using default gcp ops will ensure those GCP samples still works 
https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/dsl/_default_gcp_op.py

**Comment by vicaire** [comment]
@IronPan, can you provide more details? I do not understand this issue really well.

**Comment by IronPan** [comment]
the gcp samples now mount gcp credentials so this is done.
