### ISSUE TITLE
FR: update default base image for lightweight python components

### ISSUE THREAD

**Issue by amygdala** [kubeflow/pipelines#4062]
kfp 0.5.1

It looks like the default base image for lightweight components is `tensorflow/tensorflow:1.13.2-py3`.  It would be good to update this (probably  best to use a TF 2 image?).

/kind feature

**Comment by numerology** [comment]
Looks like @Ark-kun is changing that to Python 3.7 image in https://github.com/kubeflow/pipelines/pull/4054
