### ISSUE TITLE
Unable to list pipeline versions using the kubeflow client

### ISSUE THREAD

**Issue by munagekar** [kubeflow/pipelines#4063]
### What steps did you take:
Unable to list pipeline versions using the kubeflow client.
Unable to reach endpoint : GET /apis/v1beta1/pipeline_versions

```python
    client = kfp.Client(namespace=PIPELINE_NAMESPACE)
    client.pipelines.list_pipelines() # This works
    client.pipelines.list_pipeline_versions() # This does not work
```

### What happened:
```
kfp_server_api.rest.ApiException: (503)
Reason: Service Unavailable
HTTP response body: Error: 'ssh: rejected: connect failed (Connection refused)'
Trying to reach: 'http://ip:8888/apis/v1beta1/pipeline_versions'
```
### What did you expect to happen:
Endpoint was working

### Environment:
 

How did you deploy Kubeflow Pipelines (KFP)?
 Kubeflow Pipelines as part of a full Kubeflow deployment.

KFP version:  Build commit: 743746b

KFP SDK version: 
kfp                           0.5.1
kfp-server-api        0.5.0

/kind bug

**Comment by Bobgy** [comment]
@munagekar KFP installation version was 743746b a.k.a 0.2.5, so it only guarantees features in kfp-server-api 0.2.5 or below.

**Comment by munagekar** [comment]
@Bobgy Thank you for your prompt reply.[This](https://www.kubeflow.org/docs/pipelines/reference/api/kubeflow-pipeline-api-spec/) is the reference spec for 0.5.1. How can I find the reference spec for 0.2.5 ? 

I guess this endpoint is a not a part of Kubeflow 0.2.5 and this issue can be closed.

**Comment by Bobgy** [comment]
@munagekar We didn't publish it, you may find open api definition in https://github.com/kubeflow/pipelines/blob/0.2.5/backend/api/swagger/pipeline.swagger.json.

You can also use swagger documentation site to visualize it https://petstore.swagger.io/, please paste https://raw.githubusercontent.com/kubeflow/pipelines/0.2.5/backend/api/swagger/pipeline.swagger.json into the UI's top url box.

**Comment by jingzhang36** [comment]
@munagekar when you are using 0.2.5 KFP api server with a 0.5.1 KFP sdk, there might have unexpected behavior. In other words, the behavior could be different from the expected behavior of either version.

**Comment by munagekar** [comment]
@jingzhang36 I can confirm this issue is present with KFP sdk client 0.2.5 as well. 

```python
pip list | grep kfp
kfp                           0.2.5
kfp-server-api                0.1.40
```
Same result.
I cannot test for the latest-api server since KFP was deployed as a part of Kubeflow.

**Comment by Gsantomaggio** [comment]
@munagekar I think it is a bug server side, I was trying the API and I got this error:

cc @Bobgy 
```
ml-pipeline-api-server I0811 08:29:31.313545       8 interceptor.go:37] /api.PipelineService/ListPipelines handler finished                                               │
│ ml-pipeline-api-server I0811 08:34:32.231208       8 interceptor.go:29] /api.PipelineService/ListPipelineVersions handler starting                                        │
│ ml-pipeline-api-server panic: runtime error: invalid memory address or nil pointer dereference                                                                            │
│ ml-pipeline-api-server [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1322694]                                                                            │
│ ml-pipeline-api-server goroutine 2022 [2020-08-11T08:34:32.23340735Z running]:                                                                                            │
│ ml-pipeline-api-server github.com/kubeflow/pipelines/backend/src/apiserver/server.(*PipelineServer).ListPipelineVersions(0xc000200f70, 0x196dc20, 0xc000ed6570, 0xc000810 │
│ ml-pipeline-api-server     backend/src/apiserver/server/pipeline_server.go:170 +0xc4                                                                                      │
│ ml-pipeline-api-server github.com/kubeflow/pipelines/backend/api/go_client._PipelineService_ListPipelineVersions_Handler.func1(0x196dc20, 0xc000ed6570, 0x16f8580, 0xc000 │
│ ml-pipeline-api-server     bazel-out/k8-opt/bin/backend/api/linux_amd64_stripped/go_client_go_proto%/github.com/kubeflow/pipelines/backend/api/go_client/pipeline.pb.go20 │
│ ml-pipeline-api-server main.apiServerInterceptor(0x196dc20, 0xc000ed6570, 0x16f8580, 0xc000810ae0, 0xc00041c380, 0xc00041c3a0, 0x15c1a80, 0x25f3a90, 0x173b080, 0xc000e7d │
│ ml-pipeline-api-server     backend/src/apiserver/interceptor.go:30 +0xf4                                                                                                  │
│ ml-pipeline-api-server github.com/kubeflow/pipelines/backend/api/go_client._PipelineService_ListPipelineVersions_Handler(0x16b67c02020-08-11T08:34:32.23345642Z , 0xc0002 │
│ ml-pipeline-api-server     2020-08-11T08:34:32.233467862Z bazel-out/k8-opt/bin/backend/api/linux_amd64_stripped/go_client_go_proto%/github.com/kubeflow/pipelines/backend │
│ ml-pipeline-api-server google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000e8f00, 0x197ad00, 0xc00089bc80, 2020-08-11T08:34:32.233480198Z 0xc000e7dc00, 0xc00086fc50, │
│ ml-pipeline-api-server     external/org_golang_google_grpc/server.go:966 +0x4a2                                                                                           │
│ ml-pipeline-api-server google.golang.org/grpc.(*Server).handleStream(0xc0000e8f00, 0x197ad00, 0xc00089bc80, 0xc000e7dc00, 0x02020-08-11T08:34:32.233503884Z )             │
│ ml-pipeline-api-server     external/org_golang_google_grpc/server.go:1245 +0xd61                                                                                          │
│ ml-pipeline-api-server google.golang.org/grpc.(*Server).serveStreams.func1.1(2020-08-11T08:34:32.233530044Z 0xc0002fb150, 0xc0000e8f00, 0x197ad00, 0xc00089bc80, 0xc000e7 │
│ ml-pipeline-api-server     external/org_golang_google_grpc/server.go:685 +0x9f                                                                                            │
│ ml-pipeline-api-server created by google.golang.org/grpc.(*Server).serveStreams.func1                                                                                     │
│ ml-pipeline-api-server     external/org_golang_google_grpc/server.go:683 +0xa1   
```

**Comment by Gsantomaggio** [comment]
I think I figured out what's happening,

So the `request.ResourceKey` [must be set](https://github.com/kubeflow/pipelines/blob/1.0.0/backend/src/apiserver/server/pipeline_server.go#L170)

if you try the last kubeflow pipeline version you will get the error:

```
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Tue, 11 Aug 2020 09:15:56 GMT', 'Trailer': 'Grpc-Trailer-Content-Type', 'Transfer-Encoding': 'chunked'})
HTTP response body: {"error":"Invalid input error: ResourceKey must be set in the input","message":"Invalid input error: ResourceKey must be set in the input","code":3,"details":[{"@type":"type.googleapis.com/api.Error","error_message":"ResourceKey must be set in the input","error_details":"Invalid input error: ResourceKey must be set in the input"}]}
```

[ResourceKey must be set in the input](https://github.com/kubeflow/pipelines/blob/master/backend/src/apiserver/server/pipeline_server.go#L171) error.

I think that there is an incongruence on the documentation since `"name": "resource_key.id"` [seems not to be required](https://github.com/kubeflow/pipelines/blob/master/backend/api/swagger/pipeline.swagger.json#L57)

**Comment by jingzhang36** [comment]
@munagekar @munagekar, I don't think this is a bug on server side. Let's try a couple of things to fix your issue.

First, client.pipelines.list_pipeline_versions() needs a parameter, specifying the pipeline id. That is because list pipeline version is meant to list versions under a given pipeline. E.g. https://github.com/kubeflow/pipelines/blob/d7e589491280f1645d5e733165435d78a0bd7732/sdk/python/kfp/_client.py#L467

Second, it is very important to have matched versions for (1) kfp, (2) kfp-server-api, and (3) KFP API server. E..g., if you use the latest sdk, which supports pipeline versions, and connects to an old api backend, which does't support pipeline versions. It will definitely break. Therefore, it is import to keep the afore-mentioned three components with a matched version.

**Comment by Gsantomaggio** [comment]
@jingzhang36 you are right,  the error I found was form and old pipeline version, fixed [here](https://github.com/kubeflow/pipelines/commit/6ced6ea6e6da8a5bd121d7dbfc788b05795f425c#diff-27fcc6c6331361f93e87542750e30976) 

With the last version, I get the [correct error message](https://github.com/kubeflow/pipelines/issues/4063#issuecomment-671833291)

```
kfp (1.0.0)
kfp-server-api (1.0.0)
```

**Comment by munagekar** [comment]
@Gsantomaggio Thank you for verifying this. Leaving this open for [this](https://github.com/kubeflow/pipelines/issues/4063#issuecomment-671833291)
> I think that there is an incongruence on the documentation since "name": "resource_key.id" seems not to be required

**Comment by Gsantomaggio** [comment]
You are welcome.
yes, Additional to https://github.com/kubeflow/pipelines/issues/4063#issuecomment-671833660 we should change `resource_key.id` to `  "required": false` :
```
   {
            "name": "resource_key.id",
            "description": "The ID of the resource that referred to.",
            "in": "query",
            "required": false,
            "type": "string"
          },
```

If it makes sense to @jingzhang36 I can prepare this tiny PR.

**Comment by Bobgy** [comment]
swagger json is generated from proto where everything is optional for a reason.
So I don't think we will want to change that, if something is required, we use documentation on the field to mention that.

**Comment by Bobgy** [comment]
e.g. the description is generated from https://github.com/kubeflow/pipelines/blob/d87c3be6114af867760d07f1d70f4d95d4456c52/backend/api/resource_reference.proto#L40

**Comment by Gsantomaggio** [comment]
@Bobgy  thank you for the clarification, I am still getting practise with the API code!
