### ISSUE TITLE
 Ability to List Resources by Name Instead of Id

### ISSUE THREAD

**Issue by munagekar** [kubeflow/pipelines#4069]
https://github.com/kubeflow/pipelines/blob/bc3c59aea1046ff6424149c897671c7b9ee48cb2/backend/api/swagger/experiment.swagger.json#L127 
A number of the resources in the kubeflow can be only be operated(CRUD) by id. Eg: Experiments, Pipelines.

Eg: To create a run with an existing experiment name.
I need to list all the experiments. Find out the experiment which has the give name, extract the id. And then create a run using experiment_id.

It would nice to have a CRUD operations using name.

**Comment by munagekar** [comment]
Related #3360

**Comment by Bobgy** [comment]
Hi @munagekar!

I guess we are missing the documentation, it's possible listing resources while filtering on the names.

An example usage in https://github.com/kubeflow/pipelines/pull/4087#discussion_r446060844 for frontend UI and it seems the PR author also figured out how to do it in python client. You may refer to them.

**Comment by munagekar** [comment]
Not stale
