### ISSUE TITLE
[Feature request] support workflow outputs for workflow composition

### ISSUE THREAD

**Issue by hlu09** [kubeflow/pipelines#4073]
Then we can 

1. make yaml url from a workflow, create_graph_component_from_pipeline_func. 
2. my_op = kfp.components.load_component_from_url(url)(in1, int2)
3. use my_op.outputs

**Comment by Ark-kun** [comment]
Thank you for your interest.
I think this feature is already supported.
Check the code in your comment - it should work =)

Check the example in the documentation for [create_graph_component_from_pipeline_func](https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.components.html#kfp.components.create_graph_component_from_pipeline_func) (the formatting is off).

```python
        producer_op = load_component_from_file('producer/component.yaml')
        processor_op = load_component_from_file('processor/component.yaml')

        def pipeline1(pipeline_param_1: int):
            producer_task = producer_op()
            processor_task = processor_op(pipeline_param_1, producer_task.outputs['Output 2'])

            return OrderedDict([
                ('Pipeline output 1', producer_task.outputs['Output 1']),
                ('Pipeline output 2', processor_task.outputs['Output 2']),
            ])
        
        pipeline1_op = create_graph_component_from_pipeline_func(pipeline1, output_component_file='pipeline.component.yaml')
        pipeline1_task = pipeline1_op(42)
        pipeline1_task.outputs
```

**Comment by hlu09** [comment]
That is great!

1. Looks like it's experimental. Can we make it work with any valid KFP pipeline?

2. Do you have example I can follow?  I tried the sample code above, and keep getting some error.

/kfp/components/_python_to_graph_component.py", line 161, in create_graph_component_spec_from_pipeline_func
    raise TypeError('Only TaskOutputArgument instances should be returned from graph component, but got "{output_name}" = "{}".'.format(output_name, str(output_value)))
KeyError: 'output_name'

**Comment by Ark-kun** [comment]
> 1. Looks like it's experimental. Can we make it work with any valid KFP pipeline?

What are the missing features you'd like to see the most?

>Do you have example I can follow?

Can you please check this unit test:
https://github.com/kubeflow/pipelines/blob/ceb860c59496c1cfb8432bcb301173aa51ddf078/sdk/python/kfp/components_tests/test_python_pipeline_to_graph_component.py#L26

>keep getting some error.

Can you please post the full code and error? What are the components you're using? Are you using the original output names?

**Comment by hlu09** [comment]
We use exit handler, condition, recursion, ParallelFor (the order is by the frequency of usage) in many pipelines. 

Here is the code I tried with error.
`
import kfp
from collections import OrderedDict
from kfp import dsl, components

def gcs_download_op(url):
    return dsl.ContainerOp(
        name="GCS - Download",
        image="google/cloud-sdk:216.0.0",
        command=["sh", "-c"],
        arguments=["gsutil cat $0 | tee $1", url, "/tmp/results.txt"],
        file_outputs={"data": "/tmp/results.txt"},
    )


@dsl.pipeline(name="Parallel download")
def download(url1, url2):
    download1_task = gcs_download_op(url1)
    download2_task = gcs_download_op(url2)
    return OrderedDict([
            ('Pipeline output 1', download1_task.outputs["data"]),
            ('Pipeline output 2', download2_task.outputs["data"]),
        ])

output_component_file='download.component.yaml'
components.create_graph_component_from_pipeline_func(download, output_component_file=output_component_file)


def echo2_op(text1, text2):
    return dsl.ContainerOp(
        name="echo",
        image="library/bash:4.4.23",
        command=["sh", "-c"],
        arguments=['echo "Text 1: $0"; echo "Text 2: $1"', text1, text2],
    )

@dsl.pipeline(name="pipeline from pipeline yaml")
def download_and_join():
    p = components.load_component_from_file(output_component_file)("gs://ml-pipeline-playground/shakespeare1.txt", "gs://ml-pipeline-playground/shakespeare2.txt")
    echo2_op(p.outputs['Pipeline output 1'], p.outputs["'Pipeline output 2'"])

if __name__ == '__main__':
    kfp.compiler.Compiler().compile(download_and_join, __file__ + '.yaml')


`

**Comment by Ark-kun** [comment]
Thank you for the whole example. It's has shown an important piece of information.

`create_graph_component_from_pipeline_func` only supports components. Manually constructed `ContainerOp` instances are not components. (We discourage directly creating ContainerOp instances). They do not have enough information (e.g. input definitions).

To fix the problem just use a component:
```python
gcs_download_op = kfp.components.load_component_from_text('''
name: GCS - Download
inputs:
- {name: url}
outputs:
- {name: data}
implementation:
    container:
        image: "google/cloud-sdk:216.0.0"
        command: ["sh", "-c"]
        args: ['mkdir -p "$(dirname "$1")"; gsutil cat "$0" | tee "$1"', {inputValue: url}, {outputPath: data}]
''')
```

>We use exit handler, condition, recursion, ParallelFor (the order is by the frequency of usage) in many pipelines.

Thank you for the feedback. It will help us prioritize the features to add. (Currently they're not supported.)

**Comment by Ark-kun** [comment]
```
    raise TypeError('Only TaskOutputArgument instances should be returned from graph component, but got "{output_name}" = "{}".'.format(output_name, str(output_value)))
KeyError: 'output_name'
```

The `KeyError` is a red herring. The `TypeError` error message is using incorrect format syntax. I'll fix this.
