### ISSUE TITLE
KFP Execution events

### ISSUE THREAD

**Issue by eedorenko** [kubeflow/pipelines#4079]
Embedded KFP approach to publish events (webhook) reflecting the pipeline execution (e.g. pipeline start, step "step1" start, step "step2" finish, exception, exit, etc.) so a subscriber (e.g CI orchestrator) can hook on that.

**Comment by Bobgy** [comment]
This is an interesting idea, but KFP depends on argo for execution. It's not very feasible to implement this from our side

**Comment by dtzar** [comment]
[This ](https://github.com/argoproj/argo/pull/2521) is a relevant existing feature in argo-workflow 2.8.0.

**Comment by eedorenko** [comment]
@Bobgy 
The implementation (first version) of this idea is here https://github.com/kaizentm/kfp-event-handler

**Comment by Bobgy** [comment]
Interesting, @eedorenko do you want to present on KFP community meeting?

**Comment by eedorenko** [comment]
@Bobgy Yes. Added a demo entry to the agenda.

**Comment by amygdala** [comment]
I assume we should keep this open...

**Comment by Bobgy** [comment]
Agree, KFP can think about providing native support.

**Comment by dtzar** [comment]
This idea is still valid.
