### ISSUE TITLE
KFP Run Context

### ISSUE THREAD

**Issue by eedorenko** [kubeflow/pipelines#4080]
In a KFP step container give access to the run context (run_id, run date, run params, pipeline attributes, step attributes, step params).

**Comment by Ark-kun** [comment]
Can you please describe your high-level scenarios that require this feature?
How you expect the syntax to look like (pipeline-side and component-side)?
What are step/pipeline attributes?
Doesn't step code already receive step parameters? Isn't it already possible to pass pipeline parameters to a step?

The component specifications describe the component inputs and how to pass them to the command-line. Is there something preventing you from using that mechanism to get the data to the component code?

**Comment by eedorenko** [comment]
>Can you please describe your high-level scenarios that require this feature?
Often in the step you need to know run_id for the logging in external system (mlflow), tagging the model, notifying CI orchestrator, etc. Same is true for run_date, run_params, pipeline_attributes, etc.

>How you expect the syntax to look like (pipeline-side and component-side)?
I would just expect environment variables inside the component container

>What are step/pipeline attributes?
Name, description, version

>Doesn't step code already receive step parameters? Isn't it already possible to pass pipeline parameters to a step?
>The component specifications describe the component inputs and how to pass them to the command-line. Is there >something preventing you from using that mechanism to get the data to the component code?
Yes, of course it's possible to pass almost everything as parameters. It's just the matter of convenience to have an environment context available.
