### ISSUE TITLE
 ResourceOp fails when providing a resource manifest from inside a pipeline

### ISSUE THREAD

**Issue by tholop** [kubeflow/pipelines#4081]
### What steps did you take:

I am using Kubeflow ResourceOp to query some custom resources from inside a pipeline, and I would like the list of the resources to be provided by another component of the pipeline. I have one component that is writing the k8s_resource, and then the ResourceOp gets this as input as follows:

```python
        get_blocks_task = dsl.ResourceOp(
            name='get-blocks',
            k8s_resource=task.outputs["blocks"],
            action='get'
        )
```
### What happened:

The first task produces a valid json output. However, the ResourceOp component fails to get this resource: `executor error: error: unable to decode \"/tmp/manifest.yaml\": json: cannot unmarshal string into Go value of type unstructured.detector`.

It turns out that instead of querying the proper JSON resource manifest, ResourceOp is trying to interpret a placeholder such as `'{{inputs.parameters.func-blocks}}' `. Since this is not a valid manifest, the component fails.

When I look into the .yaml pipeline specification, I see:

```yaml
...
    "resource":
      "action": |-
        get
      "manifest": |
        '{{inputs.parameters.func-blocks}}'
...
```

If I remove the extra quotation marks to obtain the following, the pipeline works and produces the expected result:

```yaml
...
    "resource":
      "action": |-
        get
      "manifest": |
        {{inputs.parameters.func-blocks}}
...
```
In this case, the manifest will be properly replaced by the input argument at runtime.

### What did you expect to happen:

I expected the ResourceOp container to take its input as a manifest, instead of a mis-serialized placeholder.

This issue seems related to https://github.com/kubeflow/pipelines/issues/2320. However the workaround is not clear to me in the case of ResourceOp. To reply to this question (https://github.com/kubeflow/pipelines/issues/2320#issuecomment-633718857), passing `ResourceOp(k8s_resource=str(op_name.outputs["resource_definition"]))` does not work.

### Environment:
GKE
KFP version: 1.0
KFP SDK version: 0.4, 0.5

/kind bug
/area sdk

**Comment by Ark-kun** [comment]
I think https://github.com/kubeflow/pipelines/issues/4083 will solve issues like this.

**Comment by tholop** [comment]
Great, I look forward to it. Indeed, in the meantime I use a container instead of ResourceOp, like you mention in https://github.com/kubeflow/pipelines/issues/4083.
