### ISSUE TITLE
K8s 1.11 fails on generateName when upgrading pipelines

### ISSUE THREAD

**Issue by timbuktuu** [kubeflow/pipelines#409]
When attempting to upgrade Kubeflow Pipelines by _kubectl apply -f_ [deploy.yaml](https://storage.googleapis.com/ml-pipeline/release/0.1.2/bootstrapper.yaml) leverages a k8s deployment job with generateName.   This works on initial Kubeflow Pipelines cluster creation as one calls _kubectl create -f_, but fails when upgrading via _kubectl apply -f_ in Kubernetes 1.11.   Backing the cluster down to 1.10 allows to work as expected.

'kubectl apply -f https://storage.googleapis.com/ml-pipeline/release/$PIPELINE_VERSION/bootstrapper.yaml"

Similar issues are being reportes [elsewhere](https://github.com/kubernetes/kubernetes/issues/44501#issuecomment-411898424).

**Comment by vicaire** [comment]
@IronPan, is this fixed as part of the Kubeflow/Pipeline upgrade story?

**Comment by IronPan** [comment]
bootstrapper is now deprecated.
