### ISSUE TITLE
API Server KUBEFLOW_USERID_PREFIX with empty string gets ignored. 

### ISSUE THREAD

**Issue by maganaluis** [kubeflow/pipelines#4091]
### What steps did you take:

The api-service service should take KUBEFLOW_USERID_PREFIX if set to an empty string and use it instead of  **accounts.google.com:** however it gets ignored and the default value is used.

### What happened:
I receive the following error when attempt to create a new experiment: 

```
{"error":"Failed to authorize the request.: Failed to authorize with API resource references: Bad request.: BadRequestError: Request header error: user identity value is incorrectly formatted. Expected prefix 'accounts.google.com:', but got the header 'admin@kubeflow.org': Request header error: user identity value is incorrectly formatted","message":"Failed to authorize the request.: Failed to authorize with API resource references: Bad request.: BadRequestError: Request header error: user identity value is incorrectly formatted. Expected prefix 'accounts.google.com:', but got the header 'admin@kubeflow.org': Request header error: user identity value is incorrectly formatted","code":10,"details":[{"@type":"type.googleapis.com/api.Error","error_message":"Request header error: user identity value is incorrectly formatted. Expected prefix 'accounts.google.com:', but got the header 'admin@kubeflow.org'","error_details":"Failed to authorize the request.: Failed to authorize with API resource references: Bad request.: BadRequestError: Request header error: user identity value is incorrectly formatted. Expected prefix 'accounts.google.com:', but got the header 'admin@kubeflow.org': Request header error: user identity value is incorrectly formatted"}]}
```

### What did you expect to happen:

I expect the api-service to not use the default value if I am passing an empty string for the prefix, or a way to disable the prefix check.

### Environment:
Cloud: Azure
Kubernetes Version: 1.15.x

How did you deploy Kubeflow Pipelines (KFP)?

I deployed KFP via a custom definition that enabled multi-user support for Dex + Istio:

https://github.com/maganaluis/manifests/blob/kfp-multiuser/kfdef/kfctl_istio_dex_luis.yaml

KFP version: 1.0.0-rc.2

KFP SDK version: N/A

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by Bobgy** [comment]
Thanks for trying to integrate multi user mode with dex + istio!

I will look into this soon.

**Comment by Bobgy** [comment]
Reading https://github.com/spf13/viper/issues/237, I think implementation in https://github.com/kubeflow/pipelines/pull/3772/files#diff-9596449476ef3dc0bc8a298cb78b7ecfR99 is calling `viper.isSet` for checking if an env var is present, but `isSet` doesn't distinguish between empty string and var not set.

Therefore you are facing this issue.

/assign @Bobgy

**Comment by Bobgy** [comment]
Found viper can be configured to distinguish empty env vars: https://github.com/spf13/viper#working-with-environment-variables.
