### ISSUE TITLE
Use display_name instead of name in UI to distinguish mlpipeline-metrics of different ops with the same name

### ISSUE THREAD

**Issue by BoecquaertJonas** [kubeflow/pipelines#4107]
### What steps did you take:
I created a pipeline where I reuse a containerOp used to export and visualize pipeline metrics multiple times called `create-metric-view`. Kubeflow pipelines generates a unique name for every consecutive use of the op: `create-metric-view`, `create-metric-view-2`, ... My pipeline is being used to process multiple features in parallel and the `create-metric-view` is being used to export amount of items processed which failed/succeeded for every feature.
![image](https://user-images.githubusercontent.com/29035046/85999266-23ba3080-ba0c-11ea-8125-5b14a0dc9256.png)
The automatically generated names are being used in the `Run output` UI (see under `What happened`). I however have no way of knowing which op is exporting metrics for what feature. So I tried to set the display_names, which are being used in the pipeline graph. But it seems that this display_name is not being used in the `Run output` UI.

### What happened:
The unique automatically generated names [`create-metric-view`, `create-metric-view-2`, ...] are being used in the `Run ouput` UI, which leaves me not knowing which exact Op is exporting metrics for a certain feature.
![image](https://user-images.githubusercontent.com/29035046/85997549-e9e82a80-ba09-11ea-854d-351a3aae0089.png)

### What did you expect to happen:
I expected that the display_name would be used in the metric table instead of the actual auto generated name. This way, I could for example set the display_names on <Opname>-feature1, <Opname>-feature2, ... This would allow me to basically 'label' the metrics I'm exporting, and see in the UI which feature processing failed and which succeeded.

### Environment:
How did you deploy Kubeflow Pipelines (KFP)?
GCP AI platform pipelines 0.5.1

KFP version: 9c16e12

KFP SDK version: 0.5.1

### Anything else you would like to add:
Is there any other way I could accomplish my main goal here, which is being able to 'label' the metrics I'm exporting without recreating the same Op X amount of times, with different names?

**Comment by Bobgy** [comment]
You are welcome to contribute.

Frontend developer guide: https://github.com/kubeflow/pipelines/tree/master/frontend
Related UI code lives in https://github.com/kubeflow/pipelines/blob/696036684674e947d5bbcb7fb226403c50c88a98/frontend/src/pages/RunDetails.tsx#L550

**Comment by Ark-kun** [comment]
This might require a backend change since the backend intercepts workflows and writes the metrics into DB.
