### ISSUE TITLE
docker  build failed ——gen_licenses

### ISSUE THREAD

**Issue by mockdone** [kubeflow/pipelines#4113]
### What steps did you take:
[A clear and concise description of what the bug is.]

### What happened:
when i want to build frontend docker image,i got this error 

Step 14/22 : RUN node gen_licenses . && node gen_licenses server && cat dependency-licenses.txt >> server/dependency-licenses.txt
210---> Running in cd289937aab4
211internal/modules/cjs/loader.js:796
212throw err;
213^
214
215Error: Cannot find module '/src/frontend/gen_licenses'
216at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
217at Function.Module._load (internal/modules/cjs/loader.js:686:27)
218at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
219at internal/main/run_main_module.js:17:11 {
220code: 'MODULE_NOT_FOUND',
221requireStack: []
222}
223The command '/bin/sh -c node gen_licenses . && node gen_licenses server && cat dependency-licenses.txt >> server/dependency-licenses.txt' returned a non-zero code: 1
224{"exitCode":8, "message":"docker build failed or timeout[1]"}

area frontend

/kind bug

**Comment by Bobgy** [comment]
Did you follow guide in https://github.com/kubeflow/pipelines/blob/master/developer_guide.md?

```
# Run in the repository root directory
$ docker build -t gcr.io/<your-gcp-project>/frontend:latest -f frontend/Dockerfile .
# Push to GCR
$ gcloud auth configure-docker
$ docker push gcr.io/<your-gcp-project>/frontend:latest
```

Note it needs to run in repository root dir.

**Comment by mockdone** [comment]
> Did you follow guide in https://github.com/kubeflow/pipelines/blob/master/developer_guide.md?
> 
> ```
> # Run in the repository root directory
> $ docker build -t gcr.io/<your-gcp-project>/frontend:latest -f frontend/Dockerfile .
> # Push to GCR
> $ gcloud auth configure-docker
> $ docker push gcr.io/<your-gcp-project>/frontend:latest
> ```
> 
> Note it needs to run in repository root dir.

I did this on AliCloud with the Dockerfile given by this project. now  I delete "RUN node gen_licenses . && node gen_licenses server && cat dependency-licenses.txt >> server/dependency-licenses.txt" , Because I don't think it will affect the use of functions, then ,it works
