### ISSUE TITLE
Make artifact pop-outs fullscreen

### ISSUE THREAD

**Issue by schmidt-jake** [kubeflow/pipelines#4115]
TFDV and TFMA visualizations would be much better if they used all the real estate available. Right now, they appear in a modal with significant padding/gutters.

**Comment by Bobgy** [comment]
Totally agree, PRs welcomed if someone can jump in before I have bandwidth.

**Comment by Bobgy** [comment]
Frontend contribution docs: https://github.com/kubeflow/pipelines/tree/master/frontend
