### ISSUE TITLE
Error on accessing registered Artifacts

### ISSUE THREAD

**Issue by sudivate** [kubeflow/pipelines#4125]
I'm registering artifacts using a metadata package to create a lineage (dataset- >execution->model)  On accessing the artifacts from the central dashboard throws an error saying **No identified by id: [id]** and points to troubleshooting guide with no details on this exception. 

![image](https://user-images.githubusercontent.com/28938855/86296862-b09cef80-bbae-11ea-932f-9d4c5611066d.png)

![image](https://user-images.githubusercontent.com/28938855/86296830-a0851000-bbae-11ea-8246-ff69ff788538.png)

/kind bug
/area sdk
/area frontend

**Comment by Bobgy** [comment]
Thanks for reporting the issue!

Can you share your KFP version?
> registering artifacts using a metadata package

Which metadata package were you using?

/cc @Ark-kun

**Comment by sudivate** [comment]
KFP=1.0.0-test-5
kubeflow-metadata=0.3.1

**Comment by Bobgy** [comment]
Sorry, 1.0.0-test-5 is not a public release, if you want to test latest features, you may try to use 1.0.0-rc.2.

However, we are not explicitly supporting visualization to kubeflow-metadata created artifacts. I am not sure about any plan supporting it TBH.

For your specific error, I think it's fixed in 1.0.0-rc.2 please have a try.

**Comment by sudivate** [comment]
@Bobgy I think I'm running KFP= 0.5.0  Just to be sure whats the best way to confirm the version? 

commit id on the bottom left of dashboard takes me to https://github.com/kubeflow/pipelines/commit/1d86111d8f152d3ed7506ea59cee1bfbc28abbf9

**Comment by Bobgy** [comment]
@sudivate It's a little hard for past builds, I think the easiest way is looking at that commit date, April 23th and find corresponding release 0.5.0 was also April 23th.

Starting from 1.0.0, we'll show version text directly in KFP UI so there won't be confusion.

**Comment by sudivate** [comment]
I see pods running pipeline shows 0.5.0

**Comment by Bobgy** [comment]
Right, that's also a good way
