### ISSUE TITLE
Pagination for "All experiments" on central dashboard doesn't work

### ISSUE THREAD

**Issue by sudivate** [kubeflow/pipelines#4150]
### What steps did you take:

The experiment tab renders only the top 10 experiments and pagination doesn't work.  

/area frontend

Commit ID=  https://github.com/kubeflow/pipelines/commit/1d86111d8f152d3ed7506ea59cee1bfbc28abbf9

**Comment by Bobgy** [comment]
thanks for the report!

What does pagination doesn't work exactly mean?
Can you open browser console to see if there's any error messages?

/assign @Bobgy

**Comment by sudivate** [comment]
@Bobgy I have more than 10 experiments but my dashboard was not rendering them all despite selecting more rows per page on the dashboard.  However, this seems to be resolved now,  might be something with my browser. 

This is good to close

**Comment by Bobgy** [comment]
FYI, current behavior is that rows per page only affect How many runs in one page.

/close
