### ISSUE TITLE
No information in error message when visualization server is not accessible

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#4157]
https://github.com/kubeflow/pipelines/blob/bd0f4d23b9e73082a3924d9f3869bbe537639557/backend/src/apiserver/server/visualization_server.go#L82

When visualization server is not responding, error message in api server is not helpful at all. It should show upstream error message to help troubleshooting.

**Comment by Bobgy** [comment]
Hi @PatrickXYS, I think this is a good first issue you can look at.

FYI, you can find backend develop instructions in https://github.com/kubeflow/pipelines/tree/master/backend.
Feel free to ask any questions

**Comment by PatrickXYS** [comment]
@Bobgy Thanks a lot! Will keep you updated about any progress
