### ISSUE TITLE
Replace links to deprecated components from docs

### ISSUE THREAD

**Issue by ksonbol** [kubeflow/pipelines#4174]
[This documentation page](https://www.kubeflow.org/docs/pipelines/sdk/build-component/) includes multiple references to the [deprecated dataproc component](https://github.com/kubeflow/pipelines/tree/master/components/deprecated/dataproc/train). I think [this](https://github.com/kubeflow/pipelines/tree/master/components/XGBoost/Train) can be used instead.

/area docs

**Comment by Bobgy** [comment]
Thank you for the report!

**Comment by rimolive** [comment]
Closing this issue. The references don't exist anymore.

/close
