### ISSUE TITLE
Use GCP credentials for existing samples

### ISSUE THREAD

**Issue by IronPan** [kubeflow/pipelines#418]
For current samples that requires GCP services, we need to 
- Use default_gcp_op instead of container_op
- Call `gcloud auth activate-service-account --key-file="${GOOGLE_APPLICATION_CREDENTIALS}"` for places using gcloud

**Comment by vicaire** [comment]
@hongye-sun, is this fixed as part of your work on GCP components?

**Comment by Ark-kun** [comment]
@IronPan I think this was fixed long time ago.
