### ISSUE TITLE
Minio GCS Gateway cannnot autheticate in a GKE Cluster

### ISSUE THREAD

**Issue by sbakiu** [kubeflow/pipelines#4183]
### What steps did you take:
While deploying Kubeflow Pipelines Standalone (v 1.0.0-rc.4), minio deployment does not fail, but however logs 401 error message. The reason is that in the deploymnet `manifests/kustomize/env/gcp/minio-gcs-gateway/minio-gcs-gateway-deployment.yaml` there is no `GOOGLE_APPLICATION_CREDENTIALS` envrionement variable or no `serviceAccountName` spec defined.

### What happened:
Minio pod cannot access GCS buckets

### What did you expect to happen:
Minio pod could access GCS buckets

### Environment:
Kubeflow Pipelines standalone deployment (v 1.0.0-rc.4), using kubectl
GKE Cluster

How did you deploy Kubeflow Pipelines (KFP)?
Kubeflow Pipelines standalone

KFP version: 1.0.0-rc4

KFP SDK version: 

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by Bobgy** [comment]
We are now recommending workload identity for transparent GCP authentication. Were there any issues blocking you from using it?

**Comment by sbakiu** [comment]
Also for workload identity one needs to specify `serviceAccountName` spec in the deployment manifest. Currently this is not there.  Or am I missing something?

**Comment by Bobgy** [comment]
@sbakiu You are totally right!
We should add service accounts for them.

**Comment by Bobgy** [comment]
Sent fix PR in https://github.com/kubeflow/pipelines/pull/4188.
@sbakiu
