### ISSUE TITLE
Generated recurring run cron is off by 1 day

### ISSUE THREAD

**Issue by taivokasper** [kubeflow/pipelines#4184]
### What steps did you take:
Create weekly recurring run (every Wednesday) with type cron

Generated cron denotes Wednesday with "3" when it should be "4" so it never fires when it should.

<img width="634" alt="Screenshot 2020-07-09 at 10 34 32" src="https://user-images.githubusercontent.com/5394129/87010889-e30ea400-c1cf-11ea-82a0-57dede1dd3c6.png">

### What happened:
Generated cron: 0 0 0 ? * 3

### What did you expect to happen:
Generated cron: 0 0 0 ? * 4

### Environment:
Google chrome Version 83.0.4103.116 (Official Build) (64-bit) on Macos Catalina. Laptop and browser in Eastern European Summer Time (Estonian time).

### How did you deploy Kubeflow Pipelines (KFP)?
GCP Hosted ML Pipelines. Deployed with the GCP UI builtin deployer to zone europe-west3-a

KFP version: 0.5.1, build commit: 9c16e12

KFP SDK version: 0.5.0

### Anything else you would like to add:
If the day in cron is manually fixed then everything works as expected.

/kind bug
/area frontend

**Comment by Bobgy** [comment]
I remember reading the spec, the weekday number there starts from 0. You may try Sunday.

**Comment by taivokasper** [comment]
Yes that is true, but this bug report is about the UI generating wrong cron

**Comment by Bobgy** [comment]
@taivokasper Reading the doc https://godoc.org/github.com/robfig/cron#hdr-CRON_Expression_Format.
It says 
> Day of week  | Yes        | 0-6 or SUN-SAT  | * / , - ?

So 0->Sunday, 1->Monday, 2->Tuesday, 3->Wednesday, that's correct.
I don't understand what's wrong here.

Can you please explain?

The behavior problem you are mentioning (not executing at your specified time) is probably because of https://github.com/kubeflow/pipelines/issues/3935.

**Comment by taivokasper** [comment]
Ah, thanks for looking into it @Bobgy. I think I got confused by it not triggering on time and behaviour being different from what docs are saying and trying to figure out what timezone the cron is using. For now it is better to use SUN-SAT because that seems to work correctly and is easier to understand.
