### ISSUE TITLE
UI for Recurring run configs reports subset of active configs

### ISSUE THREAD

**Issue by andrewgdavis** [kubeflow/pipelines#4191]
### What steps did you take:
Create an Experiment.
Place multiple (in my observation there are over 150) recurring pipeline cron configs in the experiment.
Toggle (Enable or Disable) some of the most recent created configs.
View the ui for recurring configs in the experiment while toggling between enabled and disabled.

### What happened:
The "Active configs" number did not change.

### What did you expect to happen:
The "Active configs" number should reflect the Enabled configs in the experiment.

### Environment:
KFP version: v0.4.0

### Anything else you would like to add:
I think that the number of configs returned in the ExperimentDetails List is limited by a pagination throttle.  (Im guessing for perf reasons it wouldn't make sense to slurp millions of experiment configs each time). Toggling one of the first recurring jobs that was created in the experiment increments / decrements respectively, and doing so is reflected in the UI.

/kind bug
/area frontend

**Comment by Bobgy** [comment]
@andrewgdavis your guess is totally right.
https://github.com/kubeflow/pipelines/blob/d4d692e4c2508328961e892acda03453f4b23600/frontend/src/pages/ExperimentDetails.tsx#L307-L327

/assign @jingzhang36 
Can you work on this replacing that implementation with your new state filters?

**Comment by marcossony** [comment]
@Bobgy @jingzhang36 I am experiencing very similar issue in experiments that have many disabled runs, creating new runs does not update the active run counter. Can this ticket be unfrozen?

**Comment by Bobgy** [comment]
Cc @zijianjoy

**Comment by zijianjoy** [comment]
Sounds like we need to 

1. add filter in ListJob API to be:

```
filter {
   predicate {
     key: "enabled"
     op: EQUALS
     string_value: "true"
   }
 }
```

2. Then on UI, we list jobs with a very high page size. 

Let me know if this makes sense.

**Comment by chensun** [comment]
The original issue was opened against KFP 0.4. While there was recent activities, but there's no response/follow up in the past year. Closing for now, and feel free to open a new issue if there's a need.
