### ISSUE TITLE
Tags for a pipeline version

### ISSUE THREAD

**Issue by eedorenko** [kubeflow/pipelines#4193]
Ability to add tags to a pipeline version. (e.g. CI build id, branch)

**Comment by Ark-kun** [comment]
Hello. How do you expect to use this feature? What is the syntax you want to add?

**Comment by eedorenko** [comment]
The syntax as the following:
```
def compile(
      self,
      pipeline_func,
      package_path,
      type_check=True,
      pipeline_conf: dsl.PipelineConf = None,
      allow_telemetry: bool = True,
      tags={}
  ):
```
where tags: a dictionary with key (string) as tag name and value (string) as as tag value.
e.g.:

```
pipeline_tags = {}
pipeline_tags["azdo_build_number"] = "20200703.1"
pipeline_tags["branch"] = "feature/add_tags_to_pipeline"

compiler.Compiler().compile(
    pipeline_func=tacosandburritos_train,
    package_path=__file__ + '.tar.gz',
    tags=pipeline_tags)
```

**Comment by Ark-kun** [comment]
How do you expect to see/use the tags after adding them. Are they for filtering only?

**Comment by eedorenko** [comment]
- Show on Dashboard 
- Filter on dashboard
- Return in response of GET /apis/v1beta1/pipeline_versions
- Filter on GET /apis/v1beta1/pipeline_versions e.g. &filter={"predicates":[{"key":"tags","op":"CONTAIN","string_value":"[tag_value]"}]}

**Comment by Bobgy** [comment]
/cc @jingzhang36 
you might be interested in this request

**Comment by jingzhang36** [comment]
Is it possible to use the pipeline version name as the tag? We can sort and filter on pipeline version name.

**Comment by eedorenko** [comment]
The benefit of having tags is that there can be multiple tags, adding extra information to the pipeline version. Besides version name. It's not only about filtering on the dashboard, but what is more important, the ability to get the pipeline versions with API by tag values

**Comment by Bobgy** [comment]
I think we acknowledge the use case. Is there any volunteer who would want to make a design doc (this is a complex addition)?
