### ISSUE TITLE
Deprecate the stale OpenVino components

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#4216]
@dtrawins We've found several issues with the OpenVino components you've contributed. The `component.yaml` syntax of some of the components seems broken. Do you have any cycles to fix those issues?

**Comment by Bobgy** [comment]
Since we received no response, let's delete them.

**Comment by Bobgy** [comment]
Bump

**Comment by rimolive** [comment]
Closing this issue as there were no response for a while.

/close
