### ISSUE TITLE
TFX Visualization broke in the KFP UI

### ISSUE THREAD

**Issue by IronPan** [kubeflow/pipelines#4217]
### What steps did you take:
[A clear and concise description of what the bug is.]
The TFDV Visualization can't be rendered in KFP UI for a dataset generated by a later version of TFX
Running the built-in samples with the matching TFX version can show the visualization without problem

### Environment:
This is broken in the latest released version of KFP

/area frontend

**Comment by Bobgy** [comment]
@IronPan can you share an example?

**Comment by Bobgy** [comment]
I believe this was fixed in https://github.com/kubeflow/pipelines/issues/3493.

The issue will be present in earlier KFP versions e.g. <0.5.0
