### ISSUE TITLE
Compiling a pipeline doesn't include name and description into the generated YAML.

### ISSUE THREAD

**Issue by post2web** [kubeflow/pipelines#422]
My understanding is that compiling a function decorated with `@kfp.dsl.pipeline` to a pipeline will include the pipeline name and description into the YAML. This way, after uploading it, the pipeline interface can show the description. However, the name and description are missing from the YAML.

Example:
```python
import kfp
import kfp.dsl as dsl
import kfp.compiler as compiler

@kfp.dsl.pipeline(name='Test name', description='Test description')
def test_pipeline():
    op2 = dsl.ContainerOp(
        name='echo',
        image='library/bash:4.4.23',
        command=['sh', '-c'],
        arguments=['echo test'])


compiler.Compiler().compile(test_pipeline, 'test-pipeline.tar.gz')
```

There is no mention of "Test description" inside test-pipeline.tar.gz.

**Comment by gaoning777** [comment]
Good point, the description of the pipeline does get thrown away instead of being exposed to the users(embedded in the yaml). We are working on exposing the pipeline descriptions as well as parameter descriptions.

**Comment by gaoning777** [comment]
This issue has been resolved in https://github.com/kubeflow/pipelines/pull/1335

**Comment by xiaogaozi** [comment]
@gaoning777 If my understanding is correct, what @post2web request is display pipeline description in the UI. #1335 seems like not related to this issue.

**Comment by gaoning777** [comment]
@rileyjbauer @Ark-kun Do we display the pipeline metadata in the UI?

**Comment by rileyjbauer** [comment]
Yes, today we do show the pipeline description, as a snippet on the list page, and in its entirety on the details page

**Comment by hemildesai** [comment]
I'm using kfp version 0.1.24 and I'm seeing the same issue. The compiler ignores the description and as a result the description is not visible in the UI. Any updates on this?

**Comment by xiaogaozi** [comment]
The real reason is [pipeline upload API](https://github.com/kubeflow/pipelines/blob/0.1.24/backend/api/swagger/pipeline.upload.swagger.json#L35-L49) doesn't support pass a `description` parameter. There's only `name` parameter now. DSL compiler is OK.

**Comment by hugzee3** [comment]
Hi all, 
While this is still a very old thread, I'd like to say that this is still the case in the KFP v2. 
Is this known? And is it being dealt with? 

I see myself having to pass the name and desc. explicitly in the `upload_pipleine` func. even after there is one defined in the `@pipeline` decorator. 
Although, the name that appears in the UI is small case and hyphen separated name of the pipeline as specified in the `@pipeline` decorator.  The `upload_pipeline` on the other hand preserves the name and desc. as specified without any mutation.
