### ISSUE TITLE
[Testing] travis tests failing "ImportError: cannot import name 'pipeline_pb2'"

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#4221]
https://travis-ci.com/github/kubeflow/pipelines/jobs/361545078#L3696
/kind bug
/area sdk
/area testing

**Comment by Bobgy** [comment]
/assign @Ark-kun 
I found it's failing constantly now

**Comment by Bobgy** [comment]
Do we need to fix something on 1.0 branch?

**Comment by Ark-kun** [comment]
> Do we need to fix something on 1.0 branch?

It looks like TFX just broke within itself. The issue does not seem to be KFP-related.

**Comment by Ark-kun** [comment]
Here is the PR that switched the proto codegen from `protoc` to `bazel` https://github.com/tensorflow/tfx/pull/2143
