### ISSUE TITLE
kfp.Client() does not work from inside a pipeline pod

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#4238]
Kubeflow is shipping with in-cluster notebook service. I remember that in hose notebooks you could use `kfp.Client()` (without arguments) to access the KFP cluster.

I've recently tried to use `kfp.Client().*` from inside a component pod, but it could not connect (AFAIK, the URL did not have any host part).

Is it by design ? Is there an easy fix to make it work?

**Comment by Bobgy** [comment]
Met the same issue, reading `kfp.Client()` code, it reads from a few env vars to get server url in cluster, but I don't understand how those env vars came from.

They are clearly not Kubernetes standard env vars. We can default host to `ml-pipeline.kubeflow.svc.cluster.local` and port to`8888`, I think that will be an easy fix.

**Comment by Ark-kun** [comment]
> ml-pipeline.kubeflow.svc.cluster.local

Will this work on Marketplace deployment?

**Comment by Bobgy** [comment]
if they deployed on kubeflow namespace

**Comment by Bobgy** [comment]
I discovered those env vars are injected by https://github.com/kubeflow/kubeflow/tree/master/components/admission-webhook#how-this-works `PodDefault` kubeflow service. Probably that's not working.

**Comment by Ark-kun** [comment]
> They are clearly not Kubernetes standard env vars. We can default host to `ml-pipeline.kubeflow.svc.cluster.local` and port to`8888`, I think that will be an easy fix.

There are probably env vars added by Kubernetes that we could check and fall back to.
