### ISSUE TITLE
FR - upload pipeline via private GCS bucket

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#4247]
Recording some pain points.

**Comment by Bobgy** [comment]
When I try to upload a pipeline to KFP instance through a private GCS bucket that KFP should have access to.
This is hard.

Context: when I develop remotely, I'm using a remote development machine, so I don't have the file local to my browser and want to upload by gcs.

However, KFP only accepts URLs or local files, but it doesn't support gs:// urls.
I need a way to convert a gcs file to a proper url.

https://cloud.google.com/storage/docs/access-control/signing-urls-with-helpers should be one way to do that, but I cannot run this tool successfully, partially because of https://github.com/GoogleCloudPlatform/gsutil/issues/983.

**Comment by Ark-kun** [comment]
> When I try to upload a pipeline to KFP instance

Can you describe the scenarios where you need to compile and upload pipeline instead of just running it?
I usually develop pipelines in a AI Platform Notebook instance. I submit the pipelines for execution by just calling `kfp.Client(host=...).create_run_from_pipeline_func(my_pipeline, arguments={})`

**Comment by Bobgy** [comment]
> > When I try to upload a pipeline to KFP instance
> 
> Can you describe the scenarios where you need to compile and upload pipeline instead of just running it?
> I usually develop pipelines in a AI Platform Notebook instance. I submit the pipelines for execution by just calling `kfp.Client(host=...).create_run_from_pipeline_func(my_pipeline, arguments={})`

I was running a tfx pipeline, I wasn't familiar with tfx sdk, so I used KFP UI to upload the pipeline.

**Comment by Ark-kun** [comment]
> I was running a tfx pipeline, I wasn't familiar with tfx sdk, so I used KFP UI to upload the pipeline.

Speaking of which, TFX runners should probably have separate `.compile` and `.run` methods.
