### ISSUE TITLE
Adding periodically sync functionality to persistence agent

### ISSUE THREAD

**Issue by frozeNinK** [kubeflow/pipelines#4253]
### What steps did you take:
According to my understanding, persistence agent / worker currently only listen on k8s event stream for workflow updates.

It maybe a good idea to add periodical logic comparing the workflow states stored in KFP vs k8s.

### What happened:
KFP, in some rare case, fail to update the workflow state (to failed?), when corresponding workflow definition on k8s is missing.

### What did you expect to happen:
Workflow state updated to end state, at least not shown as running.

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

KFP version: 
We are currently using 0.2.5
It seems that master branch may also missing this feature

KFP SDK version: 

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by Bobgy** [comment]
FYI, persistence agent also periodically look at all workflow resources, but it has no knowledge of what KFP runs are there.

Anyway, this seems a reasonable suggestion.
I'm not sure what perf implication it could have.
/assign @jingzhang36 

> KFP, in some rare case, fail to update the workflow state (to failed?), when corresponding workflow definition on k8s is missing.

For clarification, why did the workflow disappear by itself? I don't know any reasons, other than it was not created successfully in the first place.

**Comment by frozeNinK** [comment]
> FYI, persistence agent also periodically look at all workflow resources, but it has no knowledge of what KFP runs are there.
> 
> Anyway, this seems a reasonable suggestion.
> I'm not sure what perf implication it could have.
> /assign @jingzhang36
> 
> > KFP, in some rare case, fail to update the workflow state (to failed?), when corresponding workflow definition on k8s is missing.
> 
> For clarification, why did the workflow disappear by itself? I don't know any reasons, other than it was not created successfully in the first place.

Currently the root cause is unknown.

I would also suggest re-visit possible failure scenarios to make KFP more resilient to edge cases, since KFP does not have full control of Argo and k8s.
