### ISSUE TITLE
Cannot view graphs and run pipelines in Kubeflow 1.0.2 

### ISSUE THREAD

**Issue by slenky** [kubeflow/pipelines#4254]
### What steps did you take:
Hi. I upgraded my AWS cluster with Kubeflow from **1.0.1 to 1.0.2** (and thus KFP from **0.2.0 -> 0.2.5**).

### What happened:
After that, if I go to the Kubeflow UI -> Pipelines and click on my imported pipelines, graphs and YAML's tab are empty. 
Also, if I click on 'Create run' it fails with 'Cannot proxy request to /apis/v1beta1/runs'

entries ml-pipeline-ui logs:  
```
Proxied request:  /apis/v1beta1/runs
[HPM] Error occurred while trying to proxy request /apis/v1beta1/runs from <redacted> to http://10.100.89.102:8888 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
GET /pipeline/
--
--
Proxied request:  /apis/v1beta1/runs
[HPM] Error occurred while trying to proxy request /apis/v1beta1/runs from <redacted> to http://10.100.89.102:8888 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
POST /pipeline/apis/v1beta1/runs
```

Nothing helpful in the ml-pipeline logs.
I've tried to execute some curl's from alpine pod using both `curl http://ml-pipeline-ui/apis/v1beta1/runs` and `http://10.100.89.102:8888/apis/v1beta1/runs` and that works returning me a JSON payload with pipelines list.

If I manually rollback *ml-pipeline* deployment to the **0.2.0** it does a trick. 
I confirm that latest working version of apiserver is *0.2.2* - all the older versions (even 0.3+) gives me a bug like that.
### What did you expect to happen:
Pipeline graphs and YAML's are present.
### Environment:

How did you deploy Kubeflow Pipelines (KFP)?  
Kubeflow 1.0.2 deployment for AWS with Cognito&istio

KFP version: 0.2.5

/kind bug
/area backend

**Comment by slenky** [comment]
Can this be related to #2080 ?

**Comment by slenky** [comment]
Found a fix exactly in the PR mentioned above.
When I applied a new apiserver configmap and upgraded it again to 0.2.5 everything started to work properly.
```
# The configuration for the ML pipelines APIServer
# Based on https://github.com/kubeflow/pipelines/blob/master/backend/src/apiserver/config/config.json
apiVersion: v1
data:
  # apiserver assumes the config is named config.json
  config.json: |
    {
      "DBConfig": {
        "DriverName": "mysql",
        "DataSourceName": "",
        "DBName": "mlpipeline",
        "GroupConcatMaxLen": "4194304"
      },
      "ObjectStoreConfig": {
        "AccessKey": "minio",
        "SecretAccessKey": "minio123",
        "BucketName": "mlpipeline",
        "PipelineFolder": "pipelines"
      },
      "InitConnectionTimeout": "6m",
      "DefaultPipelineRunnerServiceAccount": "pipeline-runner",
      "ML_PIPELINE_VISUALIZATIONSERVER_SERVICE_HOST": "ml-pipeline-ml-pipeline-visualizationserver",
      "ML_PIPELINE_VISUALIZATIONSERVER_SERVICE_PORT": 8888
    }
kind: ConfigMap
metadata:
  name: ml-pipeline-config
```

There was a new keys named **PipelineFolder** and **GroupConcatMaxLen**.

Can this be addressed to kubeflow/manifests repository?
Those fields are still absent on master branch: https://github.com/kubeflow/manifests/blob/master/pipeline/api-service/base/config-map.yaml

**Comment by Bobgy** [comment]
PR welcomed on updating kubeflow/manifests, I can approve for you.
