### ISSUE TITLE
FR: support upgrade from hosted to standalone

### ISSUE THREAD

**Issue by amygdala** [kubeflow/pipelines#4261]
(tested for upgrade from 0.5.1 to 1.00).
/kind bug

There are several problems with the current upgrade process.  (For context with the following, hosted kfp by default uses the `default` namespace (but this can be changed), and the standalone installation uses the `kubeflow` namespace (though this can be changed by editing a set of config files).)

- the upgrade in place as per the instructions does not work even if the original hosted kfp installation also used the 'kubeflow' namespace; there are a series of immutability errors:
`"github.com/kubeflow/pipelines/manifests/kustomize/env/dev?ref=1.0.0": Deployment.apps "ml-pipeline-persistenceagent" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"ml-pipeline-persistenceagent", "application-crd-id":"kubeflow-pipelines"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable`and `for: "github.com/kubeflow/pipelines/manifests/kustomize/env/dev?ref=1.0.0": Deployment.apps "minio" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"minio", "application-crd-id":"kubeflow-pipelines"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable` etc.

- Yuan suggested also editing `params.env`  to make sure appName matches the one installed by marketplace

- however, that was not sufficient.  Via Yuan:
  Marketplace uses label `app.kubernetes.io/name: "{{ .Release.Name }}"` to select application content.
  Standalone uses label `      application-crd-id: kubeflow-pipelines`
  If we want to support upgrade transitioning from marketplace to standalone, we need to break in-place upgrade support for one of them once.  It was proposed to do this at the marketplace end (cc @rmgogogo )

- Next I tried first uninstalling the hosted kfp installation (but not its cluster) before installing standalone into the same cluster.  
  The hope was that this would avoid the immutability problems and that all all data in mysql and minio should be preserved. However, after uninstallation, running:
```
% kubectl apply -k "github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=$PIPELINE_VERSION"
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
```
I see this error when checking for the crd condition:
```
% kubectl -n kubeflow wait --for condition=established --timeout=60s crd/applications.app.k8s.io
Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "applications.app.k8s.ion" not found
```

- once we sort out the above issues, we need to clearly document the process for upgrading an installation that uses a different namespace than `kubeflow`; we need to enumerate how to d/l the release, list all the files that need to be edited, and how to run them locally.

/cc @joeliedtke 
/cc @Bobgy

**Comment by amygdala** [comment]
For now, perhaps we should just remove the upgrade instructions from the docs.

**Comment by Bobgy** [comment]
> For now, perhaps we should just remove the upgrade instructions from the docs.

FYI, the instructions were meant for in place upgrade for standalone. We should have a notice that it's not possible to transit from marketplace right now.

**Comment by Bobgy** [comment]
applications.app.k8s.ion not found

Did you have a typo?
The error message has an extra n at the end.

**Comment by amygdala** [comment]
> applications.app.k8s.ion not found
> 
> Did you have a typo?
> The error message has an extra n at the end, should be `applications.app.k8s.ion -> applications.app.k8s.io`

hmmm, good catch... I'm not sure if that was a cut & paste into the bug mistake or a typo when running the command.  I will try it again.

**Comment by amygdala** [comment]
Update: that was a typo on my part.  Once corrected, the manifests were applied with superficial success to a cluster where a previous MKP installation (in the same `kubeflow` namespace) had been deleted.  
However, the new installation did not preserve state.  The dashboard shows:
![image](https://user-images.githubusercontent.com/115093/88318189-3a803a00-cccf-11ea-98c7-1a6f7dca7c1e.png)

Additionally, the `metadata-grpc-deployment` and `ml-pipeline-persistenceagent` in the new deployment are crash-looping. 
(I didn't have time to dig in further yet).

**Comment by amygdala** [comment]
Are there a set of tests that confirm that the above doesn't happen when upgrading a non-MKP standalone installation?  Or should we check that as well?

**Comment by Bobgy** [comment]
Yes, we have test checking regression for upgrading standalone deployment. It's the `kubeflow-pipelines-upgrade-test`.
But there's no coverage for marketplace -> standalone (obviously it's broken right now).

**Comment by Bobgy** [comment]
Let's change this issue to a feature request of upgrading from marketplace to standalone.

**Comment by Bobgy** [comment]
@amygdala by the way, do you still have the cluster there? Can you share it with me for debugging purposes?

I'm going to try upgrading from marketplace to standalone quickly to see what blockers there are and how feasible we can support this.

**Comment by Bobgy** [comment]
Tried upgrading from marketplace to standalone using in-cluster storage. I didn't see the problems @amygdala met. Everything worked, except MLMD data is not restored because of the same problem for https://github.com/kubeflow/pipelines/issues/4300.

In standalone and marketplace we are using different db names for MLMD.
In standalone, it's static, we always use `metadb`, but in marketplace, we use `<application-name>_metadata`
https://github.com/kubeflow/pipelines/blob/70f47caaea84a0953cfe927364343b7c838b00bb/manifests/kustomize/base/params.env#L5
https://github.com/kubeflow/pipelines/blob/70f47caaea84a0953cfe927364343b7c838b00bb/manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/metadata.yaml#L150

**Comment by Bobgy** [comment]
Well, a workaround is, the standalone deployment can be customized https://github.com/kubeflow/pipelines/blob/70f47caaea84a0953cfe927364343b7c838b00bb/manifests/kustomize/base/params.env to use existing database names.

User needs to first find out current db names, so this isn't very straight forward.

**Comment by Bobgy** [comment]
I discussed with @rmgogogo , it will be a breaking change for marketplace if we rename its db, considering number of users we already have, we don't really want to do that.

We can document steps to upgrade from marketplace to standalone instead, it will roughly be:
1. Query the in-cluster mysql db about database name:
```
$ kubectl run -it -n <namespace> --rm --image=mysql:8.0.12 --restart=Never mysql-client -- mysql -h mysql
$ show databases;
```
2. Delete marketplace application from Google Cloud Console UI.
3. Deploy a standalone with namespace and db name override in https://github.com/kubeflow/pipelines/blob/70f47caaea84a0953cfe927364343b7c838b00bb/manifests/kustomize/base/params.env#L5.

**Comment by Bobgy** [comment]
@amygdala do you think above solution sounds good to you?

**Comment by Bobgy** [comment]
Moving this to a doc work item in KFP 1.0.

**Comment by amygdala** [comment]
> @amygdala by the way, do you still have the cluster there? Can you share it with me for debugging purposes?

sorry, no, I took it down.

**Comment by amygdala** [comment]
> @amygdala do you think above solution sounds good to you?

yeah, that seems reasonable... let's just make sure to document the process carefully, and in the upgrade docs make clear up front that there is a different process in the 2 cases (so that the user doesn't just jump in and apply the manifests without reading further).
