### ISSUE TITLE
Running pods are being deleted in kubeflow pipelines

### ISSUE THREAD

**Issue by luckyskg** [kubeflow/pipelines#4263]
### What steps did you take:
I ran a kubeflow pipeline which would start 10 parallel jobs. These pods has a node selector associated with them so that they can be scheduled with some specific nodes

### What happened:
few of the pods are deleted while it was being run. i have retry set to 2. so for some of them even in the second attempt the pod was deleted while running

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

KFP version:  Build commit: 743746b

KFP SDK version: 0.3.0
<img width="1782" alt="Screenshot 2020-07-23 at 8 32 34 AM" src="https://user-images.githubusercontent.com/22092616/88249311-c25f4780-ccc1-11ea-8199-58f678597d39.png">

/kind bug

**Comment by Bobgy** [comment]
Do you have some TTL, GC mechanism or preemption setting that caused this?
Pods being deleted cannot be done by KFP nor protected by KFP.

**Comment by Bobgy** [comment]
For example, did you set memory and cpu resource requests to those pods? If you didn't, when nodes are low on cpu/memory, it might kill your pods.

**Comment by luckyskg** [comment]
I had set the memory and cpu limit per pod . One thing i tried now is that assign higher memory and cpu limit and made sure that only one kubeflow pod is assigned to one machine. and i am seeing considerably less pod deleted issue than before.

**Comment by luckyskg** [comment]
The following metric i got for one node where is this deleted pod was scheduled. 
<img width="1777" alt="Screenshot 2020-07-23 at 4 29 44 PM" src="https://user-images.githubusercontent.com/22092616/88279454-bb582980-cd01-11ea-9092-498fd943bd1e.png">

**Comment by Bobgy** [comment]
I don't think I have more advice for you. This is a more kubernetes cluster management question, and I don't have enough expertise on that.

Would you consider asking in a different channel?

**Comment by luckyskg** [comment]
Sure. Thanks for comments @Bobgy
