### ISSUE TITLE
gcloud.beta.ai-platform.versions.create internal error (NER example deployment)

### ISSUE THREAD

**Issue by pxu20** [kubeflow/pipelines#4268]
### What steps did you take:
[A clear and concise description of what the bug is.]
I tried to run the kubeflow example of named entity recognition (https://github.com/kubeflow/examples/tree/master/named_entity_recognition). In Step 5 run the pipeline, preprocess and train worked fine, but deploy failed. 
![Screenshot 2020-07-23 at 5 53 47 PM](https://user-images.githubusercontent.com/67297700/88352109-7cc86c00-cd0d-11ea-962e-9f6ca19dae74.png)

### What happened:
Here is the logs of deploy in pipeline run:

`MODEL_PATH = gs://kf-ner/{workflow.uid}/model   
MODEL =    
MODEL_NAME = named_entity_recognition_kubeflow   
MODEL_REGION = us-central1   
MODEL_VERSION = version1   
RUNTIME_VERSION = 1.13    
MODEL_PREDICTION_CLASS = model_prediction.CustomModelPrediction    
MODEL_PYTHON_VERSION = 3.5    
MODEL_PACKAGE_URIS = gs://kf-ner/routine/custom_prediction_routine-0.2.tar.gz    
Using endpoint [https://ml.googleapis.com/]
Creating model named_entity_recognition_kubeflow in region    
Using endpoint [https://ml.googleapis.com/]   
Created ml engine model [projects/my-project-name/models/named_entity_recognition_kubeflow].   
Creating version version1 from gs://kf-ner/{workflow.uid}/model   
Using endpoint [https://ml.googleapis.com/]   
ERROR: (gcloud.beta.ai-platform.versions.create) INTERNAL: Internal error encountered.`   

### What did you expect to happen:
I have not idea since the pipeline run did not succeed.

### Environment:

tensorflow image: tensorflow/tensorflow:1.12.0-py3
keras: 2.2.4

How did you deploy Kubeflow Pipelines (KFP)?

I followed the tutorial to run a jupyter notebook. (https://github.com/kubeflow/examples/tree/master/named_entity_recognition)

KFP version: 

KFP SDK version: 
kfp                      1.0.0
kfp-server-api           1.0.0

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by Ark-kun** [comment]
This is notebook and components have been created by a contributor (@SaschaHeyer). He might be able to help you.

I think the main issue is that the runtime version 1.13 is not longer supported. See https://cloud.google.com/ai-platform/prediction/docs/runtime-version-list Please choose a more recent runtime version.

**Comment by pxu20** [comment]
@Ark-kun Thank you for the advice. I modified the runtime version of AI Platform Prediction to 2.1 (and Python to 3.7), but the same error still occurred.

**Comment by TabbieD** [comment]
@pxu20 have you been able to resolve this error?

**Comment by pxu20** [comment]
@TabbieD Not yet

**Comment by Sillians** [comment]
@pxu20 any solution yet? Actually experiencing same issue as well. 
![deploy log errros](https://user-images.githubusercontent.com/25388109/93711403-e4e8d200-fb45-11ea-8151-a110ae4df12c.png)

**Comment by Sillians** [comment]
> @Ark-kun Thank you for the advice. I modified the runtime version of AI Platform Prediction to 2.1 (and Python to 3.7), but the same error still occurred.
> I notice that "MODEL" is empty in the log. Is it possible to be a source of the bug?

@Ark-kun where in the code did you modify the runtime version to 2.1

**Comment by pxu20** [comment]
> @pxu20 any solution yet? Actually experiencing same issue as well.
> ![deploy log errros](https://user-images.githubusercontent.com/25388109/93711403-e4e8d200-fb45-11ea-8151-a110ae4df12c.png)

Sorry, not yet.
