### ISSUE TITLE
Persistence agent should record the workflow pods

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#4271]
Different controllers such as Argo, Metadata Writer and Execution Cache add information to pods' labels and annotations. The frontend can use these annotations in the UX. However when the pods are garbage collected, this information is no longer available. It might make sense to save this information in the DB, so that the frontend can get it even if the pod has been deleted.

**Comment by Bobgy** [comment]
That's a reasonable design, but I'd prefer implementing that with IR considered.
