### ISSUE TITLE
The compiler should not produce duplicate templates for instances of the same component

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#4272]
Currently, the DSL compiler produces a new Argo template for each pipeline task (usually, component instance). This increases the size of the compiled workflow limiting the maximum number of tasks. See https://github.com/kubeflow/pipelines/issues/4170

The compiler should only produce a single template for each component. achieving this is hard due to the architecture of the DSL compiler. The DSL does not retain any information about inputs, so the compiler uses the names of outputs that have produced the arguments instead, which makes the input names different for every template/component instance. It might still be possible to rename the template inputs and then deduplicate the templates.

(Edge case: component whose outputs are consumed by file in one place an by value in another place. Each variant should probably get its own template.)

P.S. It might be time to rewrite the compiler with a top-down recursive architecture and with component awareness. I did some experiments on this, but the experimental compiler lacked support for many DSL features.

**Comment by radcheb** [comment]
@Ark-kun how could I help with this?

**Comment by tanguycdls** [comment]
@Ark-kun Also interested by that issue, we're running into the max workflow size as well even with the simplify packaged ! Tell us if we can help and how. 
thks!

**Comment by Ark-kun** [comment]
Unfortunately I believe that this will require a major compiler rewrite and even some DSL changes.
Currently, ContainerOp does not have a concept of inputs. So each ContainerOp instance of the same component is slightly different that another. Also in the current compiler all generated input names are globally-unique (and as such are different).
Fully solving this issue might require moving to component-only DSL (we're moving in this direction).

It might also be possible to create a rewriter that will try to deduplicate Argo templates.
