### ISSUE TITLE
Kubeflow pipelines metrics

### ISSUE THREAD

**Issue by Dhaval08** [kubeflow/pipelines#4276]
### What steps did you take:
[A clear and concise description of what the bug is.]
I am trying to log some metrics for my run using the following code

```
print("Testing out kubeflow pipeline metadata")

metrics = {
    'metrics': [{
      'name': 'accuracy-score',
      'numberValue':  12,
      'format': "PERCENTAGE",
    }]
  }
with file_io.FileIO('/mlpipeline-metrics.json', 'w') as f:
    json.dump(metrics, f)
```

### What happened:
However, I keep getting `PermissionDeniedError: /mlpipeline-metrics.json; Read-only file system` when I try to write the json file. I am guessing this is because I do not have permission to write to the root folder.

For my use case, the end-user will never have this permission. How is the user supposed to log metrics for the run in this case?

Thank you.

I am currently using Kubeflow v0.7.0

**Comment by Ark-kun** [comment]
You should request the system to give you paths for outputs instead of hard-coding the paths in your code.

In your component definition you should use either `mlpipeline_metrics_path: OutputPath()` parameter annotation (in case of lightweight python components) or `outputPath: mlpipeline_metrics` placeholder in manually-created `component.yaml`.
To be recognized as metrics, the output name should be mlpipeline_metrics.

See https://github.com/kubeflow/pipelines/blob/ea94251143f300fafed8950a1b4ba0a6b6065094/components/XGBoost/Train/component.py#L5  and https://github.com/kubeflow/pipelines/blob/ea94251/components/XGBoost/Train/component.py

**Comment by Dhaval08** [comment]
I was following the steps listed here - https://v0-6.kubeflow.org/docs/pipelines/sdk/pipelines-metrics/
And it is still unclear to me what you meant by "request the system to give you paths for outputs instead of hard-coding the paths in your code".

Let me explain my use case in more detail:
1. User points me to the source code (usually on gitlab) along with the execution command
```
experiment: "kubeflow-pipeline-metrics"
source:
    repository: "<gitlab-repo>"
    branch: "<gitlab-branch>"
execution_command: "python entry.py"
output_artifact_location: "/repo/results"
```  
2. I then generate the argo workflow yaml file with a. init container that would clone the specific git repo and b. main container that will execute the "execution_command" provided by the user
3. This argo workflow yaml file is then used to generate a new run using Kubeflow Pipeline API

I want the end-user to somehow inform my service what metrics need to be logged for this specific run. I assumed if the user can output the mlpipeline-metrics.json file at the right location, kubeflow will pick it up. But the user is unable to do so due to the permission issue listed above.

**Comment by Mistobaan** [comment]
from: https://kubeflow-pipelines.readthedocs.io/en/latest/_modules/kfp/dsl/_container_op.html

```python
output_artifact_paths: Maps output artifact labels to local artifact file paths.
              It has the following default artifact paths during compile time.
              {'mlpipeline-ui-metadata': '/mlpipeline-ui-metadata.json',
               'mlpipeline-metrics': '/mlpipeline-metrics.json'}
          is_exit_handler: Deprecated. This is no longer needed.
```
in my code I have:

```python
    values = []
    for name in sorted(metrics_dict):
        value = metrics_dict[name]
        values.append({
            'name': name,
            'numberValue': value,
            'format': "RAW",
        }) 

    metrics = {
        'metrics': values
    }
    
    with tf.io.gfile.GFile('/mlpipeline-metrics.json', 'w') as fd:
        json.dump(metrics, fd)
```
and in the component I have:
```
dsl.ContainerOp(
    arguments=args,
            output_artifact_paths={
               'mlpipeline-ui-metadata': '/mlpipeline-ui-metadata.json',
               'mlpipeline-metrics': '/mlpipeline-metrics.json'
            }
        )
```
the UI metadata works, the metrics does not. 
Is there a way to explicitly annotate in python the metrics / metadata? something like 
```op.produces(metrics=True, metadata=True, metrics_path="/something.json")```
and takes care of setting all the details

**Comment by Dhaval08** [comment]
Where can I edit the default value for mlpipeline-metrics? I am not using dsl-ContainerOp for my use case? Is there an alternative to this like a Config-Map for example?

**Comment by Dhaval08** [comment]
Figured it out.
In the YAML configuration, for my main container, I had to add the following lines
```
outputs:
        artifacts:
        - {name: mlpipeline-ui-metadata, path: /home/jovyan/repo/mlpipeline-ui-metadata.json}
        - {name: mlpipeline-metrics, path: /home/jovyan/repo/mlpipeline-metrics.json}
```

This way, I could edit the default location of the json files. 
Thank you for the help.

**Comment by Ark-kun** [comment]
>if the user can output the mlpipeline-metrics.json file at the right location, kubeflow will pick it up

The important part is output name ("mlpipeline-metrics"), not file name (which can be anything.).
