### ISSUE TITLE
Kubeflow pipeline artifact visualization

### ISSUE THREAD

**Issue by Dhaval08** [kubeflow/pipelines#4282]
### What steps did you take:
I am trying to visualize artifacts for Pipeline runs.
Following is what I write to mlpipeline-ui-metadata.json
```
metadata = {
    'outputs': [{
        'type': 'markdown',
        'source': 'artifact.md',
    }]
}
```
I read that the supported source locations are http, https, Amazon S3, Minio, and Google Cloud Storage. Is there any way to use local file system as source for artifact visualization? If not, is there any work around to this? My training code simply writes certain files (like markdown or tensorboard logs) to local file system and I would like to visualize them on Kubeflow dashboard.

### What happened:
Artifact tab is not loading any artifact

**Comment by Ark-kun** [comment]
Please try the following:
```
metadata = {
    'outputs': [{
        'type': 'markdown',
        'source': 'your *markdown* here',
        'storage': 'inline',
    }]
}
```
P.S. @Bobgy I think resolving the following issues will make this significantly easier for the users:
https://github.com/kubeflow/pipelines/issues/3970
https://github.com/kubeflow/pipelines/issues/3510

**Comment by Dhaval08** [comment]
@Ark-kun Also, does Kubeflow support real time visualization of tensorboard logs? I did try out the steps from documentation. However, the visualization seems to get created only after the job has finished its execution.
Thank you.

**Comment by Bobgy** [comment]
There cannot be support for local. Do you mean volume?
