### ISSUE TITLE
Standalone deployment is not using the proxy in the correct region

### ISSUE THREAD

**Issue by numerology** [kubeflow/pipelines#4284]
If a standalone deployment is deployed to a us-central1 GKE cluster, it is supposed to talk to inverse proxy us-central1. However currently it seems like it's talking to us-central2, which is inconsistent with our proxy config.

**Comment by Bobgy** [comment]
@numerology can you provide more details?

Choosing which proxy is code we maintain vin KFP, so one of us need to investigate this.

**Comment by Bobgy** [comment]
https://github.com/kubeflow/pipelines/blob/0ff6d9cfa438119785b94b8802f4bf7d36f95bda/proxy/attempt-register-vm-on-proxy.sh

**Comment by numerology** [comment]
@Bobgy Sorry I dropped the ball on this one...

For example, if a user deploys KFP onto a GKE cluster in us-central1 region, then according to [this config](https://storage.googleapis.com/ml-pipeline/proxy-agent-config.json) inverse proxy should return a host name suffixed by `us-central1`, but it's currently `xxx-us-central2`. It's not blocking usage but suboptimal.

**Comment by Bobgy** [comment]
Understood, FYI code for deciding which proxy url to choose is in https://github.com/kubeflow/pipelines/blob/0ff6d9cfa438119785b94b8802f4bf7d36f95bda/proxy/get_proxy_url.py, so anyone who'll try to fix this problem should troubleshoot there.

**Comment by suryaavala** [comment]
@Bobgy I submitted a fix in #4702, would you be able to review it?
