### ISSUE TITLE
Procedure to enable TLS connection for external mysql database

### ISSUE THREAD

**Issue by SatwikBhandiwad** [kubeflow/pipelines#4286]
Please suggest the parameters to be set in ml-pipeline-config Configmap, so that Pipeline pods use TLS connection to communicate with the external MySQL database.

**Comment by HassanOuda** [comment]
@Bobgy @jingzhang36 
This is also something I'm interested in, maybe you can point me to where that code lives and I can make that pull request?

Thanks

**Comment by Bobgy** [comment]
https://github.com/kubeflow/pipelines/blob/master/backend/src/apiserver/client/sql.go

I think it's here

**Comment by tomaszstachera** [comment]
/reopen
Is there anybody succeeded in this (e.g. for AWS RDS)?
