### ISSUE TITLE
Workflow gets stuck with `This step is in Pending state with this message: controller is not configured with a default archive location`

### ISSUE THREAD

**Issue by janbe-ts** [kubeflow/pipelines#4287]
### What steps did you take:
- Deployed Kubeflow pipelines standalone on an existing AWS cluster
- Created a pipeline by running this [sample code](https://github.com/kubeflow/pipelines/blob/master/samples/tutorials/Data%20passing%20in%20python%20components/Data%20passing%20in%20python%20components%20-%20Files.py) from a notebook

### What happened:
- The workflow stops after the first step with the following message: `This step is in Pending state with this message: controller is not configured with a default archive location`
- I can view the correct output of the step in the Artifacts section, so it seems to have terminated successfully. 
- The workflow-controller logs also seem fine
```
│ time="2020-07-29T09:37:10Z" level=info msg="Processing workflow" namespace=kubeflow workflow=print-repeating-lines-pipeline-rxcvs                                                                            │
│ time="2020-07-29T09:37:10Z" level=info msg="Updated phase  -> Running" namespace=kubeflow workflow=print-repeating-lines-pipeline-rxcvs                                                                      │
│ time="2020-07-29T09:37:10Z" level=info msg="DAG node {print-repeating-lines-pipeline-rxcvs print-repeating-lines-pipeline-rxcvs print-repeating-lines-pipeline-rxcvs DAG print-repeating-lines-pipeline nil  │
│ time="2020-07-29T09:37:10Z" level=info msg="All of node print-repeating-lines-pipeline-rxcvs.repeat-line dependencies [] completed" namespace=kubeflow workflow=print-repeating-lines-pipeline-rxcvs         │
│ time="2020-07-29T09:37:10Z" level=info msg="Pod node {print-repeating-lines-pipeline-rxcvs-3205367312 print-repeating-lines-pipeline-rxcvs.repeat-line repeat-line Pod repeat-line nil    Pending print-repe │
│ time="2020-07-29T09:37:10Z" level=info msg="Created pod: print-repeating-lines-pipeline-rxcvs.repeat-line (print-repeating-lines-pipeline-rxcvs-3205367312)" namespace=kubeflow workflow=print-repeating-lin │
│ time="2020-07-29T09:37:10Z" level=warning msg="Error updating workflow: Operation cannot be fulfilled on workflows.argoproj.io \"print-repeating-lines-pipeline-rxcvs\": the object has been modified; pleas │
│ time="2020-07-29T09:37:10Z" level=info msg="Re-applying updates on latest version and retrying update" namespace=kubeflow workflow=print-repeating-lines-pipeline-rxcvs                                      │
│ time="2020-07-29T09:37:10Z" level=info msg="Update retry attempt 1 successful" namespace=kubeflow workflow=print-repeating-lines-pipeline-rxcvs                                                              │
│ time="2020-07-29T09:37:10Z" level=info msg="Workflow update successful" namespace=kubeflow phase=Running resourceVersion=170199677 workflow=print-repeating-lines-pipeline-rxcvs
``` 

### What did you expect to happen:
The pipeline runs through

### Environment:
How did you deploy Kubeflow Pipelines (KFP)?
Kubeflow Pipelines Standalone as described in the [docs](https://www.kubeflow.org/docs/pipelines/installation/standalone-deployment/#deploying-kubeflow-pipelines)

KFP version: 1.0.0 (also tried 0.5.1)

KFP SDK version:
```
kfp             0.5.1
kfp-server-api  0.5.0
```

### Anything else you would like to add:
![Screenshot 2020-07-29 at 11 48 48](https://user-images.githubusercontent.com/63344087/88785457-816ba500-d191-11ea-8218-5bf4eb45c501.png)

/kind bug
/area backend

**Comment by Ark-kun** [comment]
There should be a `workflow-controller-configmap` configmap deployed as part of the Argo deployment. Do you see it in the cluster?

**Comment by janbe-ts** [comment]
It turned out somebody else in my team had deployed another Argo `workflow-controller` in the default namespace which had a ClusterRole assigned allowing access to all pods in the cluster across namespaces. This controller seemed to modify the workflows I created in Kubeflow pipelines which also explains the error message:
 
`time="2020-07-29T09:37:10Z" level=warning msg="Error updating workflow: Operation cannot be fulfilled on workflows.argoproj.io \"print-repeating-lines-pipeline-rxcvs\": the object has been modified;`

After disabling the second controller, everything worked like a charm. :)

**Comment by sm-hawkfish** [comment]
I have also seen this issue and the root cause was similar -- a separate (more recent) version of Argo was installed in the same cluster (but in our case it was a different namespace, e.g. `argo`). 

It seems that even though the separate argo installation is in it's own namespace, the `workflow-controller` that KFP chooses to run components seems to be selected at random between either the one that comes bundled with KFP and the one that was manually installed.

@Ark-kun , short of disabling the secondary workflow-controller (which I want to keep since some components submit Argo workflows that use recent Argo features), are you aware of a method that we could use to ensure that KFP components are only executed using the `default` argo workflow-controller ?

**Comment by Bobgy** [comment]
As far as I know, an argo controller can only watch for one namespace or the whole cluster.
@sm-hawkfish can you ask the other argo controller to limit to only operating on one namespace?

**Comment by sm-hawkfish** [comment]
This was exactly the issue -- thank you very much for the tip @Bobgy !
