### ISSUE TITLE
Kubeflow Dashboard: "No graph to show" upon running the pipeline

### ISSUE THREAD

**Issue by nikhil-dce** [kubeflow/pipelines#4289]
### What happened:
The pipeline execution was successful. However, the kubeflow dashboard is unable to load the graph in the `Experiments` tab. See the attached screenshot.
![kubeflow_experiments_error](https://user-images.githubusercontent.com/7813163/88816448-69445780-d18a-11ea-9989-d5742fa29eaa.png)

### What did you expect to happen:
Expected the pipeline graph to appear. I am able to see the graph in the `Pipelines` tab. See below - 
![kubeflow_pipelines](https://user-images.githubusercontent.com/7813163/88816181-22eef880-d18a-11ea-9cb5-3f3d9eb2c203.png)

How did you deploy Kubeflow Pipelines (KFP)?
- The pipeline was created using `tfx pipeline create  --pipeline-path={pipeline_path} --endpoint={ENDPOINT} --build-target-image={CUSTOM_TFX_IMAGE} --build-base-image={TFX_IMAGE} --engine='kubeflow'`.
- The pipeline was deployed using `tfx run create --pipeline-name=<pipeline_name>  --endpoint=<ENDPOINT> --engine='kubeflow'`

Build commit: 9c16e12

KFP SDK version:
kfp 1.0.0
kfp-server-api 1.0.0

### Anything else you would like to add:
There are 150+ tfx components in the pipeline.

/kind bug
/area frontend

**Comment by Bobgy** [comment]
Probably duplicate of https://github.com/kubeflow/pipelines/issues/4179?

**Comment by rganeshsharma** [comment]
HI @nikhil-dce  did you find teh solution for this issue? please direct me if you know the solution to this issue? I also notice kubeflow controller-manager-6d7b565545-gqc6h POD is continuesly restart and policy is set to Always restart. Do you guys recommend to change policy to Never Restart? Please advise
