### ISSUE TITLE
the Run link here doesn't work when using hosts like `istio-ingressgateway.istio-system.svc.cluster.local`

### ISSUE THREAD

**Issue by shawnzhu** [kubeflow/pipelines#4297]
### What steps did you take:
Run below code in an in-cluster notebook in a Kubeflow deployment with KFP mult-user feature:
```Python
import kfp.dsl as dsl
import kfp
from kfp import components
import json
# Create kfp client
# Note: Add the KubeFlow Pipeline endpoint below if the client is not running on the same cluster.
#client = kfp.Client()
cookie="authservice_session=the-secretive-cookie-value"
client = kfp.Client(host=f'http://istio-ingressgateway.istio-system.svc/pipeline', cookies=cookie)
experiment = client.create_experiment(name="my_experiment", namespace="my-ns")
```

it will create HTML output `Experiment link here` but the link doesn't work. 

@adrian555 found this problem, I just filed this report.

### What happened:
When running kfp in an in-cluster notebook with KFP mult-user feature, it requires authentication against the istio ingressgateway, which can be a public endpoint or a local name like `istio-ingressgateway.istio-system.svc.cluster.local`. However, when using such a local name which can not be recognized by browser, the _Run link here_, link from notebook when running `client.run_pipline()` will not work. 

### What did you expect to happen:

When clicking "here" from `Experiment link here`, it should navigate to the very experiment from a pipelines page.

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

Deployed to IBM kubernetes service from https://github.com/kubeflow/manifests/pull/1428

KFP version: https://www.github.com/kubeflow/pipelines/commit/988f5b02e4211dfff1c02eb0b9a52cbc69793364

KFP SDK version: 
`kfp 1.0.0`

### Anything else you would like to add:

/kind bug

/area sdk

**Comment by PatrickXYS** [comment]
In AWS, we do
```
PUBLIC_ENDPOINT="http://XX-istiosystem-istio-XX-XX.us-west-2.elb.amazonaws.com" + "/pipeline"
client = kfp.Client(host=PUBLIC_ENDPOINT, cookies=cookie)
```
Not sure IBM side can do so or not?

**Comment by adrian555** [comment]
Yes, the public/external endpoint works too.

**Comment by Bobgy** [comment]
Thanks for reporting!
Help welcomed for a fix.

The problem is, KFP UI url in Kubeflow and KFP API url is different. So we need to make it configurable when initiating the client.

Do you have suggestions, what will be the best UX?
* host, ui_host args
* host, deployment_type args, ui_host inferred from them

**Comment by shawnzhu** [comment]
part of https://github.com/kubeflow/pipelines/issues/4297

**Comment by Bobgy** [comment]
https://github.com/kubeflow/pipelines/issues/4637 is the upstream issue
