### ISSUE TITLE
Metrics disappear from pipeline UI at end of run

### ISSUE THREAD

**Issue by lyschoening** [kubeflow/pipelines#4304]
### What steps did you take:
Run a pipeline with two tasks that generate metrics, one at the beginning, one at the end.

The first step contained 2 metrics, the second step around 25.

### What happened:

Metrics for the first task appeared in Run output once that task completed. When the run and second task generating metrics completed, all metrics disappeared and "No metrics found for this run." was shown.

### What did you expect to happen:

All metrics to be shown at the end of the run.

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

KFP version: 743746b 

KFP SDK version: 

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

This only appears to happen when there are quite a few metrics in the second task. Is there a limit for metrics that has not been documented?

/kind bug
/area frontend

**Comment by Bobgy** [comment]
I'm not sure about this, can you try `kubectl logs ml-pipeline-xxxxx` see the kfp api server log when fetching metrics?

I suppose something should be failing there.

**Comment by lyschoening** [comment]
There's the following error, omitting some of the records in the middle:

`Failed to parse metrics ({[{"RunUUID":"85f70ed7-2196-4f5c-b4f9-a2817cb674ca","NodeID":"my-pipeline-zkwdh-1135935994","Name":"example-count","NumberValue":xxx,"Format":"UNSPECIFIED","Payload":""},...,{"RunUUID":"85f70ed7-2196-4f5c-b4f9-a2817cb674ca","NodeID":"my-pipeline-zkwdh-1135935994]'. error: unexpected end of JSON input`

The length of the quoted string from ({[{ to ' is always 2097 characters.

**Comment by Bobgy** [comment]
looks like there's some length limit

**Comment by Bobgy** [comment]
Failing from here: https://github.com/kubeflow/pipelines/blob/5ebe6cf99f27e11938d1f5e0ab8941f8c38efe21/backend/src/apiserver/storage/run_store.go#L291

**Comment by chenyuzhi459** [comment]
I met the same problem
```
Failed to parse metrics ({[{"RunUUID":"42539d66-b326-4fc2-aa15-858031cb2582","NodeID":"mnist-train-pipeline-h5rbx-1277174427","Name":"test1","NumberValue":0.14,"Format":"PERCENTAGE","Payload":""},{"RunUUID":"42539d66-b326-4fc2-aa15-858031cb2582","NodeID":"mnist-train-pipeline-h5rbx-2 true}) from DB: failed unmarshal metrics '[{"RunUUID":"42539d66-b326-4fc2-aa15-858031cb2582","NodeID":"mnist-train-pipeline-h5rbx-1277174427","Name":"test1","NumberValue":0.14,"Format":"PERCENTAGE","Payload":""},{"RunUUID":"42539d66-b326-4fc2-aa15-858031cb2582","NodeID":"mnist-train-pipeline-h5rbx-2'. error: unexpected end of JSON input
```
but  I check `mlpipeline.run_metrics.Payload` in mysql, it's a json format data. However, I change the charset to utf8 for mysql db before,  thus, it may cause by the change of charset. When I run `ALTER TABLE run_metrics MODIFY COLUMN Payload longtext CHARACTER SET latin1;`,  it works and the metrics show up in the ui.  Is it a bug?
