### ISSUE TITLE
sdk/client/auth - it's hard to debug auth problems

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#4311]
Kubeflow standalone deployment on GCP uses https://github.com/google/inverting-proxy to expose KFP endpoint publically with auth/authz.

## Past Problems

In the past, there have been multiple issues raised asking about getting a response, but it's all "None" values.
> A call to `client.list_experiments` yields 
> ```python
> {'experiments': None, 'next_page_token': None, 'total_size': None}
> ```

For example: https://github.com/kubeflow/pipelines/issues/3793, https://github.com/kubeflow/pipelines/issues/4143 and https://github.com/kubeflow/pipelines/issues/4060#issuecomment-654591306, https://github.com/kubeflow/pipelines/issues/2954#issuecomment-580886794, https://github.com/kubeflow/pipelines/issues/2625, https://github.com/kubeflow/pipelines/issues/2516

What's worse, if the person is trying one of the more complex client helper methods, for example https://github.com/kubeflow/pipelines/blob/2a65eec1fa265ebbda69d5b8b1875e3e4b54ac82/sdk/python/kfp/_client.py#L785, it may crash in the middle, because these methods never check for return value is None or not. This leads to even harder to debug scenarios.

## Analysis and Root Cause

However, these shouldn't fail like this. I tried using a non-existent host or non existent paths, I get `ApiException` correctly from `kfp-server-api`. After some debugging, I realized the root cause:

Most KFP public endpoints have auth support with the form -- redirect to login page if not authenticated. However, the login page returns 200 status code. So if there's anything wrong with auth, `kfp-server-api` will follow the redirect and assume the login page is the response. Therefore, it gives all `None`s for responses without raising an exception.

## Solution

I think the easiest and root fix is to disable urllib3's redirection follow feature working with KFP endpoint, our api endpoint never return redirect. If redirect happens, it must be an auth failure in one of the platforms.

**Comment by Bobgy** [comment]
/cc @rmgogogo @numerology @Ark-kun 
I spent some time today tracking down the root cause of all those `None`s reports using kfp client.

I initially thought it was just because `kfp-api-server` package doesn't have error handling, but it turned out to be more complex than that. The problem arises from auth failure and redirection

**Comment by numerology** [comment]
Thanks @Bobgy ! This is really helpful.

I have one question on the phenomenon you described In the analysis and root cause section: the session will be redirected to a login page if no proper authentication was provided IIUC. Will this happen when the provided host name or path is invalid?

**Comment by Bobgy** [comment]
> I have one question on the phenomenon you described In the analysis and root cause section: the session will be redirected to a login page if no proper authentication was provided IIUC. Will this happen when the provided host name or path is invalid?

Exactly! When the host name or path is invalid, sdk fails to identify the hostname as an inverse proxy endpoint, so it doesn't send auth info there, so it became an auth problem again. e.g. there was a bug report that user actually appended `/pipeline` to KFP GCP hosted endpoint, therefore getting all `None`s.

The more important thing to this specific issue is, we need to update documentation for host: https://github.com/kubeflow/pipelines/blob/8014a44229664ebd4f9b6ec69fbb6900f104af85/sdk/python/kfp/_client.py#L94-L100
