### ISSUE TITLE
sdk/client/auth - KeyError: 'id_token' from _auth.py in id_token_from_refresh_token

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#4312]
If getting “KeyError: 'id_token'” from “File "/Users/gongyuan/miniconda3/envs/mlpipeline/lib/python3.7/site-packages/kfp/_auth.py", line 192, in id_token_from_refresh_token
    return (str(json.loads(res.text)[u"id_token"]))

The request to get id token from refresh token failed, but the client didn’t surface the underlying error message. The http response I got was
```
{
  "error": "invalid_grant",
  "error_description": "Bad Request"
}
```

And root cause: ~/.config/kfp/credentials.json has expired. I deleted it and got a new token: `rm ~/.config/kfp/credentials.json`.

## Solution

https://github.com/kubeflow/pipelines/blob/2a65eec1fa265ebbda69d5b8b1875e3e4b54ac82/sdk/python/kfp/_auth.py#L184-L185 and https://github.com/kubeflow/pipelines/blob/2a65eec1fa265ebbda69d5b8b1875e3e4b54ac82/sdk/python/kfp/_auth.py#L191-L192, we should first check request response status code by `Response.raise_for_exception`, it could be `401 unauthorized`.

**Comment by annajung** [comment]
Picking this up. Let me know if there is any problem in working on this issue. thanks!
