### ISSUE TITLE
Tensorboard viewer proxy error

### ISSUE THREAD

**Issue by blacksailer** [kubeflow/pipelines#4315]
Hello everyone!

I was trying to configure my workflow with pipelines and wanted to use tensorboard. I am managed to created two step pipeline, but clicking on "Open Tensorboard" gives:
```
Error occured while trying to proxy to: localhost:31380viewer-12603eeafa771bc2d749be395a03d8655b4ed0e1-service.kubeflow.svc.cluster.local:80/tensorboard/viewer-12603eeafa771bc2d749be395a03d8655b4ed0e1/
```

My cluster is on-premises, 1.15.11and behind corporate proxy
kubeflow version-1.0.2 without dex

Port-forwarding tensorboard pod is working, but not from pipelines UI.

Can you guide to some tutorial  howto configure tensorboard? Or help which pod generates such error?

**Comment by Bobgy** [comment]
`ml-pipeline-ui` pod proxies traffic to the tensorboard pod in the cluster

I'm not sure what went wrong

**Comment by blacksailer** [comment]
Suddenly after weekends it started to work, maybe it was intializing too long.Closing
