### ISSUE TITLE
GCP IAP - OpenID Connect token expired: JWT has expired

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#4321]
I'm getting the following error message after using a client for more than 1 hour.

> Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'X-Goog-IAP-Generated-Response': 'true', 'Content-Length': '45', 'Content-Type': 'text/html; charset=UTF-8', 'Date': 'Tue, 04 Aug 2020 11:59:03 GMT', 'Alt-Svc': 'clear'})
HTTP response body: OpenID Connect token expired: JWT has expired

**Comment by Bobgy** [comment]
Looks like IAP credentials also need to be refreshed.

**Comment by yanniszark** [comment]
Implementing the proposed interface could provide the refreshing functionality: https://github.com/kubeflow/pipelines/issues/4683
