### ISSUE TITLE
Update KFP doc for Kubeflow 1.1 and KFP 1.0

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#4324]
Use this issue as a centralized tracker for all doc updates needed.

**Comment by Bobgy** [comment]
*[ ] https://github.com/kubeflow/pipelines/issues/4317

**Comment by Bobgy** [comment]
* [ ] Document new `kfp.components` new methods @Ark-kun

**Comment by Bobgy** [comment]
> The pipeline component must write a JSON file specifying metadata for the output viewer(s) that you want to use for visualizing the results. The file name must be /mlpipeline-ui-metadata.json, and the component must write the file to the root level of the container filesystem.

in

**Comment by numerology** [comment]
Sent https://github.com/kubeflow/website/pull/2167 to address the SDK overview page.

**Comment by Bobgy** [comment]
* [ ] 
https://www.kubeflow.org/docs/pipelines/pipelines-quickstart/ https://github.com/kubeflow/pipelines/issues/4617

**Comment by Bobgy** [comment]
* [ ] p0 https://www.kubeflow.org/docs/pipelines/sdk/build-component/ https://github.com/kubeflow/pipelines/issues/4174

**Comment by Bobgy** [comment]
GKE docs
* [ ] https://kubeflow.org/docs/gke/cloud-filestore it uses deployment manager, that's not our recommendation now, but it should continue to work.
