### ISSUE TITLE
The sample tests should search for `gcr.io/ml-pipeline/*` container images in `gcr.io/ml-pipeline-test/*`

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#4329]
Currently there are several problems regarding to the CI/CD for components and samples.
Users work in branches to change components and samples.
The presubmit sample test builds container images for the components and pushes them to `gcr.io/ml-pipeline-test/*`.
When changing some component code, there should be a corresponding change in the `component.yaml` file and samples that use the component.
The sample or component.yaml should point to the new container image. The image in components/samples should point to `gcr.io/ml-pipeline/*`, not `gcr.io/ml-pipeline-test/*`. However the image is not moved from ml-pipeline-test to ml-pipeline until the PR is merged into master and released.
So there is an issue: the components/samples are pointing to an image location that does not exist yet.

Solution: The samples/components should point to the future location of the container image in `gcr.io/ml-pipeline/*`, but the sample test infra should patch that location to `gcr.io/ml-pipeline-test/*` so that the image can be found during the test.

To be able to implement this it should be possible to predict the full image name. This might be complicated currently since the image names use commit hashes that can only be known after the commit is submitted. The final name of the image only becomes known when the branch is merged into master. This prevents pointing the samples and components to that image in the same branch. A solution to this is to make the image names predictable. For example we could switch from GIT commit hashes to GIT tree hashes which are stable.

**Comment by Bobgy** [comment]
can we use tree hash as url?
