### ISSUE TITLE
Use more stable hashes for container image names

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#4330]
Related to https://github.com/kubeflow/pipelines/issues/4329

Components and samples depend on container images.
Users changing the component code want to make the corresponding changes to the components and samples using that code in the same PR.
To do that, the users need to be able to predict the final image name.
This currently not possible since the image names use commit hashes that can only be known after the commit is submitted. The final name of the image only becomes known when the branch is merged into master. This prevents pointing the samples and components to that image in the same branch.

A solution to this is to make the image names predictable.
We could switch from GIT commit hashes to GIT tree hashes which are stable.
Another option might be to switch to image digests, but with current CI/CD system it won't work: The images are released from the master branch. That image is not exactly the same as any image built from commits in the PR branch.

Proposed solution:
For each component with Dockerfile, use it's source code root to calculate GIT tree hash. Use that hash to construct the full image name. That image name should be used in the components/samples. When the PR is merged into master, that image should be released to public with the same hash in the name.

**Comment by Bobgy** [comment]
If we use git tree hash, I think we should make sure each dockerfile is deterministic, e.g. pin each image to a fixed version.
