### ISSUE TITLE
No retry on "Pod deleted"

### ISSUE THREAD

**Issue by yoni-taranis** [kubeflow/pipelines#4333]
### What steps did you take:
I've manually added a "retryStrategy" of "Always" to the op compiled yaml
I can see retry does occur when there is an actual code error 

I am quite sure that this issue started when upgrading from argo 2.4.x (it started after upgrading to 1.0.0), and might stop happening in argo 2.9.x as we are running also a a standalone argo deployment, and it stopped happening when upgrading it to 2.9.x

### What happened:
When a pod is deleted (for whatever reason), retry does not happen

### Environment:
How did you deploy Kubeflow Pipelines (KFP)?
Using GCP MarketPlace, standalone deployment 

KFP version: 1.0.0

KFP SDK version: 1.0.0

Attached screenshot, the retries are set right now to 2 retries.

![image](https://user-images.githubusercontent.com/32834556/89502786-34f61a00-d7ce-11ea-9251-c506015701b6.png)

**Comment by yoni-taranis** [comment]
Any comments on this issue?

This seems to be working when directly using argo, but when I try to manually add retryStrategy to Always, the module creating the argo annotations later ignores it and only sets the limit value.

IMO it is critical to address since any cluster preemption/auto scaler action risks the failure of the pipeline.

**Comment by yoni-taranis** [comment]
Another update: A quick workaround (but very hacky) that managed to resolve this for now - I repackaged argoexec and workflow-controller after changing the code in argo/operator.go to always use "Always" as a default retry policy

**Comment by Ark-kun** [comment]
> I repackaged argoexec and workflow-controller after changing the code in argo/operator.go to always use "Always" as a default retry policy

There is a PR to expose this setting in the SDK: https://github.com/kubeflow/pipelines/pull/3880
There were some design discussion there, but I wonder whether we should just go with what we have and possibly make amendments later.

**Comment by yoni-taranis** [comment]
I have tried adding it to the compiled yaml, and it still didn't go through to argo, could you think of any reason?

**Comment by Ark-kun** [comment]
I think I know what's happening. Can you please use `kubectl get workflow .... --output yaml` and check whether the option is still there? I think backend might be using an old version of Argo and losing "unknown" fields.

**Comment by yoni-taranis** [comment]
@Ark-kun indeed it is there,

This is why I wasn't sure if the PR mentioned will help, since it only handles the client side

**Comment by Ark-kun** [comment]
@yoni-taranis Thank you for your patience. 

>This is why I wasn't sure if the PR mentioned will help, since it only handles the client side (Correct me if I'm wrong)

Now we know that both parts need to be in place. SDK must give an ability to specify "Always". Backend must not lose that setting.

>I do not understand how can it work properly for anyone else in this use case without using the "Always" option.

I guess not many people used it on preemptible nodes.

**Comment by yoni-taranis** [comment]
Thank you! For now we're getting by with the workaround. By the way, I'm not sure if this happens only on preemtibility, but also when the cluster autoscaler moves pods between nodes when scaling down.
