### ISSUE TITLE
Outdated documentation on caching

### ISSUE THREAD

**Issue by xinbinhuang** [kubeflow/pipelines#4340]
### What steps did you take:
[A clear and concise description of what the bug is.]

Following steps from here: https://www.kubeflow.org/docs/pipelines/caching/#disabling-caching-in-your-kubeflow-pipelines-deployment

```bash
kubectl get mutatingwebhookconfiguration cache-webhook
```

### What happened:

Resource not found

### What did you expect to happen:

The actual resource name:

```bash
❯ kubectl get mutatingwebhookconfiguration
NAME                     CREATED AT
cache-webhook-kubeflow   2020-06-23T20:36:16Z
cert-manager-webhook     2020-04-14T20:36:22Z
```

Also even after I changed the correct resource name. It still fails:

```bash
❯ kubectl patch mutatingwebhookconfiguration cache-webhook-kubeflow -n ${NAMESPACE} --type='json' -p='[{"op":"replace", "path": "/webhooks/0/rules/0/operations/0", "value": "DELETE"}]'
Error from server (BadRequest): json: cannot unmarshal array into Go value of type map[string]interface {}
```

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

KFP version: 1.0.0 

KFP SDK version: 1.0.0  

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

```bash
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-gke.600", GitCommit:"0bd89e105de2e1718e7418e73db3312050551a2b", GitTreeState:"clean", BuildDate:"2020-07-20T18:10:21Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

/kind bug

**Comment by Ark-kun** [comment]
Thank you for your patience. We will update the documentation.

We'd also like to know the scenario that prompted you to disable the caching globally. Can you describe the reason? Usually it's enough to disable caching for a single component in a pipeline.

**Comment by xinbinhuang** [comment]
My use case is probably a bit rare and not apply to other people. We are currently developing a pipeline that takes a `specification.json` from cloud storage and then uses the specification to grab data, train models, and do predictions. The development process will take a while and we are using the same `specification.json` for testing purposes, which the schema is also subject to change... So it's just easier to turn off the cache all at once. Eventually, we will enable the cache again once the specification is more stable.

**Comment by Ark-kun** [comment]
>a pipeline that takes a specification.json from cloud storage

I think you can use the `Download from GCS` component to download the `specification.json` from cloud storage. And disable cache reuse for that component task.

**Comment by Bobgy** [comment]
Fixed by https://github.com/kubeflow/website/pull/2499
