### ISSUE TITLE
 Create pipeline failed, Storage backend has reached its minimum free disk threshold

### ISSUE THREAD

**Issue by zeeros** [kubeflow/pipelines#4342]
### What steps did you take:
Using the Kubeflow Dahsboard, I go to the Pipelines page and click Upload pipeline.
At this stage I want to create a new pipeline by uploading a zip file.

### What happened:
Suddenly I can't upload any pipeline, the following message appears

`
{"error_message":"Error creating pipeline: Create pipeline failed: InternalServerError: Failed to store 836b2e66-7496-4831-aab8-0c8c021538f9: Storage backend has reached its minimum free disk threshold. Please delete a few objects to proceed.","error_details":"Error creating pipeline: Create pipeline failed: InternalServerError: Failed to store 836b2e66-7496-4831-aab8-0c8c021538f9: Storage backend has reached its minimum free disk threshold. Please delete a few objects to proceed."}
`

### What did you expect to happen:
I would expect the pipeline to be uploaded and created

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

KFP version: v1.0.0

KFP SDK version: 1.0.0

### Anything else you would like to add:
This suddenly happens after months of working on Kubeflow. I don't know if it can be related but before this I run a notebook server to train a notebook for several hours. I don't know what I should delete to make this work.

**Comment by Bobgy** [comment]
Which Kubeflow version and which platform Did you deploy to

**Comment by zeeros** [comment]
I've solve the issue by deleting many old folders in /nfsroot/.
Does deleting a notebook server instance leave the related persitent volumes untouched?
Because this behavior is not evident from the Dashboard

**Comment by Bobgy** [comment]
I am not sure, you may move the issue to kubeflow/kubeflow repo.

this is just for pipelines

**Comment by gabrielvcbessa** [comment]
How can we increase minio's storage?

**Comment by Bobgy** [comment]
You may search for that on google.

But for production setup of KFP, we'd recommend using GCS or s3 as the object store behind minio.
