### ISSUE TITLE
Cannot use dynamic dataproc cluster name in ExitHandler

### ISSUE THREAD

**Issue by jackwhelpton** [kubeflow/pipelines#4344]
### What steps did you take:

Wrote a pipeline that creates a cluster and attempts to remove it in an ExitHandler:

```python
    dataproc_create_cluster_op = kfp.components.load_component_from_url(
        "https://raw.githubusercontent.com/kubeflow/pipelines/1.0.0/components/gcp/dataproc/create_cluster/component.yaml"
    )
    create_cluster_task = dataproc_create_cluster_op(  # pylint: disable=not-callable
        project_id=PROJECT_ID,
        region=REGION,
        cluster={...},
    )

    dataproc_delete_cluster_op = kfp.components.load_component_from_url(
        "https://raw.githubusercontent.com/kubeflow/pipelines/1.0.0/components/gcp/dataproc/delete_cluster/component.yaml"
    )

    with dsl.ExitHandler(
        dataproc_delete_cluster_op(  # pylint: disable=not-callable
            project_id=PROJECT_ID, region=REGION, name=create_cluster_task.output
        )
    ):
        dataproc_submit_job_op = kfp.components.load_component_from_url(...)
        ...
```

### What happened:
Pipeline does not compile:

```
ValueError: dataproc-create-cluster does not exist.
```

### What did you expect to happen:

Pipeline to compile, and create a temporary DataProc cluster which is torn down once the pipeline completes.

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

KFP version: Build commit: 9c16e12

KFP SDK version:
```
kfp                            1.0.0
kfp-server-api                 1.0.0
```

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by numerology** [comment]
@jackwhelpton 

Interesting question... Indeed this will fail because exit handler cannot depend on the output of the op group it is associated with. One question I have is, what if the op group fails before `create_cluster_task` succeed? I think we need to think hard on several edge cases before we can make exit handler dynamic.

**Comment by jackwhelpton** [comment]
That's a good point... I guess I assumed if the cluster creation failed, there'd be nothing to clean up, but that may not be true (in fact, I'm just looking at some failed creations atm).

Is there an interim approach to this where we could generate a name using the execution ID and pass that into both the create and the exit handler? I guess it's an open question whether you'd want parallel executions to share a cluster, but if they do there's a risk that one tears it down while the other is using it.

**Comment by numerology** [comment]
@jackwhelpton 

> Is there an interim approach to this where we could generate a name using the execution ID and pass that into both the create and the exit handler?

Yes there is. One can use `dsl.RUN_ID_PLACEHOLDER` to represent the execution ID. See https://github.com/kubeflow/pipelines/blob/d87c3be6114af867760d07f1d70f4d95d4456c52/samples/core/xgboost_training_cm/xgboost_training_cm.py#L213

**Comment by jackwhelpton** [comment]
Perfect, thanks. Not directly related to this, but still on the use of ExitHandlers... is there a way to tear down a Dataproc cluster once you're done with it, even if you want to perform subsequent steps in the pipeline?

Trying to include only the Dataproc steps within the exit handler yields:

```
Only one global exit_handler is allowed and all ops need to be included.
```

**Comment by numerology** [comment]
Ah my bad. I misunderstood our own codebase 🤦 

Currently it seems not supported in the DSL level. One workaround on top of my head would be to implement a try-catch logic inside of a container op to do the cluster tearing down, and add that step as the downstream step of all Dataproc usages.

**Comment by Ark-kun** [comment]
> is there a way to tear down a Dataproc cluster once you're done with it, even if you want to perform subsequent steps in the pipeline?

You could use `dataproc_delete_cluster_op` both in the pipeline (using `.after(last_task_to_use_cluster)`) and in the ExitHandler. Then it would be called both when the pipeline succeeds and when it fails.

>One workaround on top of my head would be to implement a try-catch logic inside of a container op to do the cluster tearing down, and add that step as the downstream step of all Dataproc usages.

AFAIK, Dataproc supports auto-deleting clusters (but our components should configure that).

@jackwhelpton As a user of Dataproc, do you think it would fine if the Dataproc components auto-created and auto-deleted the clusters?

**Comment by jackwhelpton** [comment]
That seems a fair approach (calling delete in both places), although in the event when the pipeline succeeds the ExitHandler would be attempting to remove a cluster that no longer exists, which I'm guessing is an error.

In this scenario auto-creation and deletion of the cluster would be ideal, but I could see wanting to submit jobs to an existing cluster too.

**Comment by Ark-kun** [comment]
> I could see wanting to submit jobs to an existing cluster too

What would be the main reasons to want this?

**Comment by jackwhelpton** [comment]
I was actually struggling to think of an example: perhaps the only thing that springs to mind would be if you had a chain of related jobs using local HDFS, although I think  so far all of our Dataproc cases have been solvable using GCS as the storage backend.

Speaking to some of our data scientists they were even more enthusiastic about your proposal:

>"I would actually like it if hadoop clusters worked more like Beam: starts automatically, scales automatically, shuts down automatically"

Sounds like a +1 from us.
