### ISSUE TITLE
memory leak in metadata-writer?

### ISSUE THREAD

**Issue by linkvt** [kubeflow/pipelines#4347]
### What steps did you take:
We have kubeflow-pipelines deployed in our Kubernetes cluster and noticed that the metadata-writer consumes quite a lot of memory even if no jobs are currently running.

### What happened:
We had about 2000 jobs finished by kubeflow-pipelines, the successful ones were deleted some hours ago and we kept only a few failed ones.
We currently set a memory limit of 2Gi on the metadata-writer pod but even hours after the jobs were cleaned up metadata-writer still consumes the same memory.
After deleting the pod it doesn't consume the same memory as before but only 200-300Mi.

### What did you expect to happen:
I would expect that the metadata-writer memory usage correlates with the running jobs scheduled by KFP, it seems that metadata-writer doesn't release the memory of removed pipelines?

### Environment:
k8s 1.14 on prem setup with kubespray.

How did you deploy Kubeflow Pipelines (KFP)?
As part of a kustomize setup, the yamls were generated with
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=1.0.0
  - github.com/kubeflow/pipelines/manifests/kustomize/env/platform-agnostic?ref=1.0.0
```

KFP version: 
1.0.0

KFP SDK version: 

### Anything else you would like to add:
An image showing the memory and cpu consumption of the last 24h, it shows when the pod was OOMKilled and restarted.
![image](https://user-images.githubusercontent.com/3075401/89765625-fbd3e780-daf6-11ea-87e4-f461a10adbc8.png)

/kind bug

**Comment by Ark-kun** [comment]
Although there is a known small leak, it's not expected to consume that much memory.
We just keep the map from pod names to executions etc.

```
# Caches (not expected to be persistent)
# These caches are only used to prevent race conditions. Race conditions happen because the writer can see multiple versions of K8s object before the applied labels show up.
# They are expected to be lost when restarting the service.
# The operation of the Metadata Writer remains correct even if it's getting restarted frequently. (Kubernetes only sends the latest version of resource for new watchers.)
# Technically, we could remove the objects from cache as soon as we see that our labels have been applied successfully.
pod_name_to_execution_id = {}
workflow_name_to_context_id = {}
pods_with_written_metadata = set()
```

It would be pretty strange is those maps would take any noticeable amount of memory for just 2000 runs.
I can try to limit the number of items in the maps (FIFO-style). I wonder whether this helps.

P.S.
>running jobs scheduled by KFP

Can you please tell a little bit about how you use KFP scheduling.
How often do you run jobs? What's the main motivation?
Do you use cron?
Do you use placeholders? Which ones? What's your opinion about placeholders? (e.g. what if they had the `{{scheduledTime.month}}` syntax)
How do you create schedules?

**Comment by linkvt** [comment]
Hi @Ark-kun , thanks for the quick reply on this issue.

I'm not directly involved in the scheduling but mostly responsible for the KFP deployment in a multi-tenant onprem k8s cluster - I forwarded your questions to my colleagues and below you can find the answers.
The main motivation is using kubeflow pipelines for running workflows that work on huge datasets to analyze them, filter stuff out, extract further information etc. and write the data back on a distributed file system.

I just checked again and there were about 850 jobs since in last 40mins, so now there are way more scheduled than before. The memory usage also went directly up to 2Gi+.
Is there a possibility that the jobs are cleaned up incorrectly? It seems like the current cleanup job only deletes the workflow CRs in Kubernetes, not sure what the correct steps are as I didn't find any official documentation on this.

I see that the Argo Workflow CRs were deleted on 9:16 but there happened nothing in the metadata-writer logs between 7.40 and 9:31:
```
│ 2020-08-12T07:40:46.714680059Z Kubernetes Pod event:  ADDED pod-xyz-f5r9p-4129753244 40158103
│ 2020-08-12T09:31:35.816968105Z Killed  
```

Answers regarding kubeflow usage

```
Can you please tell a little bit about how you use KFP scheduling.
We do not use KFP scheduling.

How often do you run jobs? What's the main motivation?
ContainerOp based workflows are being launched with client.run_pipeline as new data arrives.
We are processing large amount of data to extract metadata and features into our custom metadata and feature store (not kfp).

Do you use cron?
Just for periodic clean up of successful workflows and pods.

Do you use placeholders? Which ones? What's your opinion about placeholders? (e.g. what if they had the {{scheduledTime.month}} syntax)
Not yet.

How do you create schedules?
We do not use KFP schedules, yet.

P.P.S. Are you using any metadata features? (e.g. the Artifacts and Executions pages) What's your main use case?
No. We are using KFP only and we have our own custom metadata store.
```

Hope that helps, thanks!

**Comment by linkvt** [comment]
Hi @Ark-kun do you have any guidance on how we should delete workflows correctly to prevent memory leaks? Thanks

**Comment by Ark-kun** [comment]
> Hi @Ark-kun do you have any guidance on how we should delete workflows correctly to prevent memory leaks?

I do not think the issue is related to workflow deletion.

I'll try to limit the number of entries in the MW cache, but I would be surprised if that helps.

As a workaround, if you want Metadata Writer to consume less memory, then please limit the memory. Yes, it will restart more often, but it should be resilient to restarts.

**Comment by linkvt** [comment]
Looks good since a few weeks, the last blue pod was the upgrade to 1.0.3. TBH we didn't really change anything but IMO it doesn't make sense investigating stuff that seems to work since already quite some time.
![image](https://user-images.githubusercontent.com/3075401/96457480-1f668d00-1220-11eb-996f-ffc732e634a7.png)
Thanks!
