### ISSUE TITLE
Want to create ANY model and do batch transform in without Training in Amazon SageMaker 

### ISSUE THREAD

**Issue by swarnaditya** [kubeflow/pipelines#4352]
### What steps did you take: Removed the HPO and Training Jobs only creating the model and batch transforming in SageMaker 
[Automatically taking the HPO and Training on SageMaker facing some issue while kfp compile]

### Anything else you would like to add:
Any open source loan data model using KF would be appriciated 

/kind bug

<!--//compile(kfp.compile ) 
/

**Comment by Bobgy** [comment]
/assign @Jeffwan @PatrickXYS 
looks like aws specific

**Comment by PatrickXYS** [comment]
SageMaker KFP should works fine as regular KFP installed on EKS.

@RedbackThomson @akartsky Any idea you can share here?

**Comment by surajkota** [comment]
Hi @swarnaditya 
Thank you for using SageMaker Components for Kubeflow Pipelines. Could you provide more details about the issue:
- are you bringing your own model? Is it uploaded to S3?
- are you bringing your own container or using one of the [pre-built SageMaker algorithms](https://docs.aws.amazon.com/sagemaker/latest/dg/algos.html)?
- sample reproducible code

Here is a sample pipeline with only model and batch transform job - https://github.com/kubeflow/pipelines/blob/master/components/aws/sagemaker/tests/integration_tests/resources/definition/transform_job_pipeline.py

and here are the sample inputs for this pipeline - https://github.com/kubeflow/pipelines/blob/master/components/aws/sagemaker/tests/integration_tests/resources/config/kmeans-mnist-batch-transform/config.yaml#L6-L23. Note: the variables enclosed in `(( ))` are replaced at runtime by our integration tests so you will not be able to run with these inputs directly but we can help you with your use-case
