### ISSUE TITLE
Add tests for new comparison operators.

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#436]

**Comment by vicaire** [comment]
@Ark-kun, have the tests been implemented? Can we resolve?

**Comment by Ark-kun** [comment]
There is some e2e coverage in sample tests: https://github.com/kubeflow/pipelines/blob/866cc81dd9a75d3a024cf8a71d995e0268454512/samples/basic/condition.py#L61

**Comment by Ark-kun** [comment]
We should also add a DSL compiler unit test.
