### ISSUE TITLE
[Feature request] Change the outpout UI name of the predefined visualizations

### ISSUE THREAD

**Issue by MatteoFelici** [kubeflow/pipelines#4374]
### What steps did you take:
I created a pipeline with parallel independent operations, each one returning Confusion Matrix, ROC Curve and other metrics

### What happened:
Each output visualization has a default title, like "confusion-matrix" and "confusion-matrix-2" that does not permit to understand to which brach it comes from.

![image](https://user-images.githubusercontent.com/9342729/90240090-e5949700-de28-11ea-9892-c809a08246aa.png)

### What did you expect to happen:
I would like to be able to dynamically specify the title of the visualization, as for the pipeline steps.

### Environment:
Kubeflow Pipelines on GCP AI Platform

**Comment by Bobgy** [comment]
That's a good idea, we'd welcome contributions

**Comment by Bobgy** [comment]
Cc @zijianjoy, we are already supporting this feature for v2 visualization

**Comment by zijianjoy** [comment]
Thank you @Bobgy for the cc! 

Yes you can now use function parameter name to specify the visualization title. Example: https://github.com/kubeflow/pipelines/pull/5781, in this case the name is `metrics`, which comes from https://github.com/kubeflow/pipelines/blob/master/samples/test/metrics_visualization_v2.py#L90
