### ISSUE TITLE
Pipeline nodes shared by notebooks

### ISSUE THREAD

**Issue by ValdasK** [kubeflow/pipelines#4375]
### What steps did you take:
(everything happens on gcp)

1. Create pipeline which uses large machine due workload (e.g. 200G ram, which spawns ~216G node)
2. When pipeline is running, spawn a notebook on kubeflow which uses like 1G only
3. As there is free space on large node, it gets scheduled there
4. Pipeline completes, node keeps in use forever, you pay large $ for running a notebook

### What happened:

notebook pod kept node from downscaling

### What did you expect to happen:

pipeline spawned nodes to contain some kind of taint, so other unrelated pods do not go there

/kind bug
/area backend

**Comment by Bobgy** [comment]
My understanding is you have two types of nodes, a static nodepool with small nodes and a dynamic nodepool with large nodes.

Sounds to me it will be better to add node selector for notebook to only run on small nodes.

and pipeline doesn't spawn nodes, GKE spawns them. What feature do you need from pipelines to support this use case?

**Comment by Ark-kun** [comment]
We're sorry you've experienced this issue.
I'm not sure that KFP currently has a built-in ability to spawn notebooks.
You might want to transfer this issue to https://github.com/kubeflow/kubeflow

**Comment by ValdasK** [comment]
This issue is not limited to notebooks, same can happen if for example a KF serving is launched when large machine is spawned and partially empty, it will get scheduled onto it; blocking it from scaling down.

Pipelines should taint nodes and prevent them from being used for any other purpose, as whole KF ecosystem shares same resources created by them; but not efficiently (as nodes are only supposed to live as long as the pipeline run, and not longer).

**Comment by ValdasK** [comment]
Could someone remove this `upsteam issue` label as it has nothing to do with it? @Ark-kun @jlewi

**Comment by jlewi** [comment]
I don't have permissions to change labels.

**Comment by ValdasK** [comment]
When maintainers are unable to adjust labels for six months...

**Comment by rimolive** [comment]
Based on the description, it seems like [Elyra](https://www.kubeflow.org/docs/external-add-ons/elyra/) is what you are looking for. Closing this issue, but feel free to reopen if you feel like your request is not addressed.

/close
