### ISSUE TITLE
Moving and persist data: artifacts vs explicit output to GCS

### ISSUE THREAD

**Issue by xinbinhuang** [kubeflow/pipelines#4378]
Hi team,

So I have a pipeline step that download the data and I need to pass it to other steps while also persist the data.

As far as I know, there are basically two ways to moving data around and persist them: 

- write the data to a local path and utilize the artifact mechanisms to persist the data - this is easy, it does not need to handle how to upload to GCS. However the data would be zipped, and is not convenient to use later on)
- write the file to both local path (for passing to later steps) and explicit output to GCS (for persistence) - however, here is a extra step to write the files and it requires extra wrapper code.) 

I wonder what is the good practice or recommended approach to persist data files? Any suggestions would be much appreciated!

Thanks,
Bin

**Comment by Ark-kun** [comment]
We suggest to be explicit here.
Your components output intermediate data that can be passed to other components. This data is system-managed and you're not supposed to know how it's stored (or whether it's stored at all).
If you want to persist the data, then just export/upload/persist it explicitly:

```
upload_to_gcs_op = load_component_from_url('https://raw.githubusercontent.com/kubeflow/pipelines/112de249a2c252f0a636bbfdf469d7ef2456f286/components/google-cloud/storage/upload_to_explicit_uri/component.yaml')

train_task = train_op(...)
predict_task = predict_op(model=train_task.outputs['model'])
persist_task = upload_to_gcs_op(data=train_task.outputs['model'], gcs_path='gs://my-bucket/path/model')
```

This way you can have a single component that is responsible for persistence and the rest of the components do not need to be aware.

**Comment by xinbinhuang** [comment]
Thanks for the suggestion!  I think it would be nice to write down this point  in the documentation to avoid confusion in the future. (i.e. the system data is not supposed to be used outside the pipeline execution context)

**Comment by xinbinhuang** [comment]
@Ark-kun Not sure if this is the right place to ask. So if I am using the `upload_to_gcp_op` as you suggested, is this the right way to do?

```python
def upload_to_gcs_op(data: components.InputPath(), gcs_path_prefix: GCSPath()):
    """Upload data to GCS for persistence"""
    return dsl.ContainerOp(
        name="Persist data to GCS",
        image="gcr.io/google.com/cloudsdktool/cloud-sdk:alpine",
        command=["sh", "-c"],
        arguments=['gsutil cp "$0" "$1"', data, gcs_path_prefix,],
    )
```
However the `data` is passed in as `argument` rather than `artifacts` and it does not work..

**Comment by Ark-kun** [comment]
>is this the right way to write the component using ContainerOp

We do not advice our users to create ContainerOp objects directly. Please create and load components instead. You can create a component by either writing a [component.yaml](https://raw.githubusercontent.com/kubeflow/pipelines/112de249a2c252f0a636bbfdf469d7ef2456f286/components/google-cloud/storage/upload_to_explicit_uri/component.yaml) file manually or creating one from a python function using `kfp.components.create_component_from_func`.
