### ISSUE TITLE
FR: add retry to output handling on step termination

### ISSUE THREAD

**Issue by amygdala** [kubeflow/pipelines#4380]
I had a pipeline run terminate in error, and found this in the logs, apparently related to handling step outputs:
```
This step is in Error state with this message: failed to save outputs: Patch https://10.55.240.1:443/api/v1/namespaces/kubeflow/pods/bikes-weather-keras-tuner-gp5rf-2492357584: dial tcp 10.55.240.1:443: connect: connection refused
```
`10.55.240.1` is the `kubernetes` service.  Whatever the network error was, it was transient.  Could it make sense to add a retry/backoff loop when doing output handling?

**Comment by Ark-kun** [comment]
I think this can only be fixed on the Argo side.
