### ISSUE TITLE
[Feature Request] Artifacts store path.

### ISSUE THREAD

**Issue by Gsantomaggio** [kubeflow/pipelines#4381]
Per [discussion](https://kubeflow.slack.com/archives/CE10KS9M4/p1597654713376400) with @Bobgy and (internally) with @alfsuse 

Currently, there is no way to set the artefacts path, and the link is something like:

http://xxxx/artifacts/get?source=minio&namespace=kubeflow&bucket=mlpipeline&key=artifacts%2Firis-classification-w2r9z%2Firis-classification-w2r9z-2210686619%2Ftraining-tree-output.tgz

If you don't use the UI it is tough to map the pipeline with the artefact results, for example using the API

We have the following use case:

A lot of data-scientists that upload their pipeline using the HTTP API, they don't have access to the kubeflow/pipeline cluster.

We exposed Minio and each time is hard to retrieve the results, mainly if we want to divide the repository for user.

We'd like to have the possibility to set the path during the `run` so we can organise the repo.

Something like:

```
user1 --> pipelinexxxx-> artifact.zip
user2 --> pipelineyyyy-> artifact.zip
user3 --> pipelinezzzz-> artifact.zip
```
as:

![Screenshot from 2020-08-17 17-02-01](https://user-images.githubusercontent.com/386987/90411018-6bc01000-e0ab-11ea-83f3-c753da8ec37e.png)

Or situations like:
```
Dev --> pipelinexxxx -> artifact.zip
        --> pipelineyyyy -> artifact.zip 
Test --> pipelinexxxx -> artifact.zip
        --> pipelineyyyy -> artifact.zip 
Prod --> pipelinexxxx -> artifact.zip
        --> pipelineyyyy -> artifact.zip 
```
as:

![Screenshot from 2020-08-17 17-03-38](https://user-images.githubusercontent.com/386987/90411153-9e6a0880-e0ab-11ea-823f-9177e3482fb4.png)

What we have in mind is to expand the `run` API and pass another parameter like `storepath` to decide where to store the artefacts.

It should be [here](https://github.com/kubeflow/pipelines/blob/master/backend/src/apiserver/resource/resource_manager.go#L260)

**Comment by Ark-kun** [comment]
We consider the intermediate data passing/storage an implementation detail that can change in the future.


>it is tough to map the pipeline with the artefact results, for example using the API

I think it should be possible to map them using the MLMD.

>pass another parameter like storepath to decide where to store the artefacts

Currently the artifact storage is configured by the `workflow-controller-configmap` ConfigMap. I wonder whether it's possible to have different configmaps in different namespaces for different users. @chensun has more information on the multi-user support.

>We exposed Minio and each time is hard to retrieve the results

Generally, we suggest to be explicit here.
Your components output intermediate data that can be passed to other components. This data is system-managed and you're not supposed to know how it's stored (or whether it's stored at all).
If you want to persist the data, then just export/upload/persist it explicitly:

```
upload_to_gcs_op = load_component_from_url('https://raw.githubusercontent.com/kubeflow/pipelines/112de249a2c252f0a636bbfdf469d7ef2456f286/components/google-cloud/storage/upload_to_unique_uri/component.yaml')

train_task = train_op(...)
predict_task = predict_op(model=train_task.outputs['model'])
persist_task = upload_to_gcs_op(data=train_task.outputs['model'], gcs_path_prefix='gs://my-bucket/some-user/models/')
```

This way you can have a single component that is responsible for persistence and the rest of the components do not need to be aware.

**Comment by Bobgy** [comment]
> If you don't use the UI it is tough to map the pipeline with the artefact results, for example using the API


what if we solve this problem directly?
it's not impossible to find artifacts related to pipeline runs, just lack of documentation

I can show you a sample using KFP api client and probably we can provide better helper methods in the client.

What do you think? Will this help?

**Comment by Bobgy** [comment]
Hi @Gsantomaggio, any thoughts?

**Comment by Gsantomaggio** [comment]
>I can show you a sample using KFP api client and probably we can provide better helper methods in the client.
What do you think? Will this help?

Absolutely yes! 
Thank you  for your support

**Comment by Bobgy** [comment]
Hi @Gsantomaggio, sorry for the late reply. A contributor wrote a great sample https://github.com/kubeflow/pipelines/issues/4327#issuecomment-687255001

**Comment by Gsantomaggio** [comment]
@Bobgy We tried the example, but the example is for "reading" the artifacts not for writing. 

Reading the artifacts isn't a problem, the problem is the Minio organization folders.

btw, thank you for your support, I think we will create a sort of custom UI that wraps the links so we can create a relationship between users and artifacts.
