### ISSUE TITLE
Producing data from one component and be consumed by another.

### ISSUE THREAD

**Issue by Scagin** [kubeflow/pipelines#4388]
I tried to output data files from one component and I hope them can be loaded in downstream components. It works when I 
reference a volume, and I load datas from volume. But when I didn't use a volume, files can't be found downstream. Is it the only way to output datas using volume? Is there any ways can do this work without a volume?

**Comment by Ark-kun** [comment]
Have you checked the [Data passing in python components](https://github.com/kubeflow/pipelines/blob/master/samples/tutorials/Data%20passing%20in%20python%20components.ipynb) tutorial?
