### ISSUE TITLE
Persist pod logs to permanent storage

### ISSUE THREAD

**Issue by IronPan** [kubeflow/pipelines#439]
For clusters such as auto scaling clusters, the pod logs will be lost if the cluster is scaled. 
We should store the pod log so UI can still get it. 

The change includes
- Create a storage for storing log - Either database table, or object storage. 
- Storing the log in permanent storage using persist agent
- Surface the log through API
- Update UI to read log from the API

**Comment by jlewi** [comment]
Most clusters will already be configured to have cluster level logging that stores pods in permanent storage (e.g. StackdDriver, DataDog, etc...).

Can the UI just be configured to fetch the logs from one of those locations?

**Comment by IronPan** [comment]
As long as it's consistent for both onprem and gcp, I'm good with it.
