### ISSUE TITLE
Backend - Upgrade Argo module

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#4392]
We've seen multiple bug reports where the root cause was backend stripping options from workflows. Latest is https://github.com/kubeflow/pipelines/issues/4333
The most likely reason is that backend submits Argo workflows for execution using an old Argo client. The information is lost when YAML is being deserialized to an olf Argo Workflow structure.

We should update the version of the Argo client module used by the backend.

**Comment by NikeNano** [comment]
\assign

I will look in to this. Seems to effect some other stuff that I have issues with as well.

**Comment by Bobgy** [comment]
We've been removing bazel dependency in https://github.com/kubeflow/pipelines/pull/4417.

After it's merged, you can try upgrading argo module with just go.mod
