### ISSUE TITLE
Error in backend - minio server not initiated

### ISSUE THREAD

**Issue by HassanOuda** [kubeflow/pipelines#4399]
### What steps did you take:
I ran the v1.1 istio_dex manifest and installed the multi-user pipelines v1.0.0.

### What happened:
I got crashloopbackoff pod error for ml-pipeline pod, ml-pipeline-api-server container. The error when I do:
kubectl logs ml-pipeline-5df444d46d-6pksr -n kubeflow ml-pipeline-api-server

`I0821 19:17:05.405000       6 client_manager.go:134] Initializing client manager
I0821 19:17:05.405135       6 config.go:51] Config DBConfig.ExtraParams not specified, skipping
F0821 19:17:05.660087       6 client_manager.go:353] Failed to check if Minio bucket exists. Error: Server not initialized, please try again.
`
I checked all the minio deployment, pod, service, pvc, they are all running and ready, no errors or logs.

### What did you expect to happen:
Launch successfully and have the pod ready

### Environment:

Kubernetes 1.15

How did you deploy Kubeflow Pipelines (KFP)?
Installed KFP through manifests v1.1 branch using the istio dex 1.1 version for multiuser

KFP version:1.0.0

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug
/area backend

**Comment by Bobgy** [comment]
@krishnadurai Can you help with this issue?
Seems istio dex specific

**Comment by HassanOuda** [comment]
@swiftdiaries maybe you can help?

**Comment by HassanOuda** [comment]
@swiftdiaries @krishnadurai any updates?

**Comment by HassanOuda** [comment]
@Ark-kun I was wondering, how can I test to see if bucket name exists manually in kubernetes? The minio pvc is bound and minio deployment is running.
Thanks

**Comment by connorlwilkes** [comment]
I am also facing this issue

**Comment by dkowsley** [comment]
Can someone please respond to this issue?
