### ISSUE TITLE
Import components from AI-Hub

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#4408]
The KFP repository might currently be a good discovery mechanism.

We might want to import some of the components that currently only exist on AI-Hub

https://aihub.cloud.google.com/s?category=pipeline

We could also import pipelines as samples.

**Comment by SinaChavoshi** [comment]
Resolving as obsolete, If there are individual components in AI Hub that have demand / are relevant please create a separate issue for them. Otherwise I would edge on the side of not cluttering the repo with stale out dated components.
