### ISSUE TITLE
The released version of the SDK is really old

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#4409]
I've discovered that the SDK lacks the feature that has been committed on June 3.

I think we should make sure that the features are getting released in regular and timely manner.

If that's not possible, we should release the SDK on it's own schedule. Previously the release cadence was two weeks.

**Comment by Ark-kun** [comment]
It has now been almost 4 months.
I think we've discussed the release schedule during the branch-based release discussion. We've reached a decision to branch and release a minor version every month (extended from the two-week release cadence we had at the time).
We've decided to take a look and see how this goes.
I think the conclusion is that this strategy does not work for the SDK.
I think we need to return to release SDK versions every two weeks.

**Comment by Bobgy** [comment]
I agree we spent significant time stabilizing KFP 1.0, we should target a KFP 1.1 ASAP.

**Comment by Bobgy** [comment]
A different problem is, how can we ensure the docs correspond to latest released SDK, instead of master branch? We shouldn't incorrectly let people find unreleased features.

**Comment by Ark-kun** [comment]
> how can we ensure the docs correspond to latest released SDK, instead of master branch?

It's pretty easy to add documentation for certain branches.

**Comment by Bobgy** [comment]
I think we can use https://github.com/kubeflow/pipelines/issues/4565 to track all efforts towards solving this problem. What do you think?
Releasing a `1.1.0-alpha.1` should allow people start trying earliest SDK and we can improve from there to `1.1.0-alpha.2`, `1.1.0-beta.1`, `1.1.0-rc.1`... until a final stable version.

**Comment by Bobgy** [comment]
What do you think?

**Comment by Bobgy** [comment]
A remaining problem is that, I think we have many docs still pointing to latest version of the sdk reference website. We need to update them to reduce the confusion.

**Comment by Bobgy** [comment]
New version has been released
