### ISSUE TITLE
Question - Using custom DNS on GCP Marketplace deplyment

### ISSUE THREAD

**Issue by yoni-taranis** [kubeflow/pipelines#4411]
Hi,

Interested to know what would be the correct way to use a custom dns when deployed from the GCP Marketplace (Instead of the <uuid>....googleusercontent.com

Your help is appreciated, thanks!

**Comment by Bobgy** [comment]
Sorry, @yoni-taranis I don't think we support that.

**Comment by yoni-taranis** [comment]
Ok, thanks!
