### ISSUE TITLE
Upgrade remaining components to Python3

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#4414]
Dome of the old components still use Python2 which is no longer supported.

We should upgrade them to Python3.

This is not urgent since components are independent from the SDK, but this can improve maintenance.

This query helps find some of the components using python2: https://github.com/kubeflow/pipelines/search?p=1&q=python-dev&unscoped_q=python-dev

**Comment by Bobgy** [comment]
@Ark-kun what do you think priority is

**Comment by Ark-kun** [comment]
The priority is low, although there was a user who has asked for python 3 in DataFlow components. Maybe there is some version dependency there.
