### ISSUE TITLE
[Feature Request] Kubeflow-UI should support getting artifacts from local path 

### ISSUE THREAD

**Issue by Mar-ai** [kubeflow/pipelines#4418]
When running a TFX pipeline on-prem, the artifacts, which are stored in PVC mount path,  cannot be visualized. 
As already mentioned [here](https://github.com/kubeflow/pipelines/issues/1497) and [here](https://github.com/kubeflow/pipelines/issues/2670#issuecomment-632595030): would be great to have support for getting artifacts from a local path.

**Comment by Bobgy** [comment]
The requested feature is already supported in https://github.com/kubeflow/pipelines/blob/master/docs/config/volume-support.md


Already supported I believe, but it will be released as part of KFP 1.1

**Comment by Mar-ai** [comment]
Took us a little longer than expected, but here we are on Kubeflow 1.1.0. 


Unfortunately I did not succeed in making this work.  

### steps to reproduce 

- generated PV `my-pv` and PVC `my-pvc` in namespace `user`
- in Kubeflow-UI in namespace `user`: started notebook server, started run of [TFX-on-premise-Pipeline](https://github.com/tensorflow/tfx/blob/master/tfx/examples/chicago_taxi_pipeline/taxi_pipeline_kubeflow_local.py) in notebook
- pipeline is executed (without visualizations, for the time being)
- applied patch as [described](https://github.com/kubeflow/pipelines/blob/master/docs/config/volume-support.md):

```bash
kubectl patch deployment ml-pipeline-ui -nkubeflow --type strategic --patch '
spec:
    template:
      spec:
        containers:
        - env:
          - name: VIEWER_TENSORBOARD_POD_TEMPLATE_SPEC_PATH
            value: "/config/view_spec_template.json"
          name: ml-pipeline-ui
          volumeMounts:
            - mountPath: /config/view_spec_template.json
              subPath: view_spec_template.json
              name: view-template-config
            - mountPath: /mnt
              name: my-pv
        volumes:
          - name: view-template-config
            configMap:
              name: ui-view-spec-template-configmap
              items:
                - key: view-spec-template.json
                  path: view_spec_template.json
          - name: my-pv
            persistentVolumeClaim:
                  claimName: my-pvc,
                  readOnly: true
 '
```

- the rollout does not work: 

```bash
$ kubectl rollout status deploy/ml-pipeline-ui -n kubeflow
Waiting for deployment "ml-pipeline-ui" rollout to finish: 1 old replicas are pending termination...

$ kubectl describe pod ml-pipeline-ui-<pendingpod>  -n kubeflow
...

Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  45s (x7 over 9m42s)  default-scheduler  persistentvolumeclaim "my-pvc," not found

``` 


Is it possible that the PVC cannot be found as it is not in namespace `kubeflow`? 

Could you advise me how to fix this?

**Comment by Mar-ai** [comment]
Update: 

- indeed, the PV/PVC for this patch need to be created in namespace `kubeflow` 
- both PV/PVC need to be created with  `accessModes:    - ReadWriteMany`

**Comment by Bobgy** [comment]
To clarify, this feature will be released in KFP 1.1 (not yet released), not Kubeflow 1.1.
Kubeflow 1.1 comes with KFP 1.0

**Comment by Mar-ai** [comment]
thanks for the clarification @Bobgy! Could you perhaps give an estimate on the release date of KFP 1.1.? 
And in the meantime, would it be possible to use something like a KFP1.1-alpha-version?

**Comment by Bobgy** [comment]
@Mar-ai You can see updates on https://github.com/kubeflow/pipelines/issues/4565, it's our next focus after finishing 1.0.3 release.

For deploying KFP on master, you can refer to our test script: https://github.com/kubeflow/pipelines/blob/f445c09f8181b520caf53340aec217ace13290ed/test/deploy-pipeline-lite.sh#L54-L64
There are built test images for each commit in master branch in gcr.io/ml-pipeline-test/xxxx:<commit-sha>

**Comment by Bobgy** [comment]
I'll close this issue, and we suggest waiting for KFP 1.1 instead, because master branch isn't as stable as released versions.
