### ISSUE TITLE
UI doesn't correctly return logs

### ISSUE THREAD

**Issue by hsezhiyan** [kubeflow/pipelines#4425]
### What steps did you take:
Made a simple KFP run on using an MNIST PyTorch training/evaluation script.

### What happened:
When making a KFP run, occasionally the UI does not properly retrieve logs, and gives the error `Failed to retrieve pod logs.` By inspecting the Chrome browser network setting, it appears to be an API call issue with the following error: `Could not get main container logs: Error: Unable to retrieve workflow status: [object Object].`.

### What did you expect to happen:
All the steps in the pipeline UI should correctly return logs.

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?
Deployed KFP on Amazon EKS infrastructure.

KFP version: `v1.0.0`

KFP SDK version: `v1.0.0`

/kind bug

**Comment by eterna2** [comment]
I will look at it. But the error msg means that when the UI backend tries to parse the CR of the workflow, the status field is malformed.

Based on my experience, usually it means that Argo had failed in such a way which the status event is emitted or captured.

But let me see if I can reproduce it

**Comment by hsezhiyan** [comment]
Thank you @eedorenko, this is a closely related issue: https://github.com/kubeflow/pipelines/issues/2705#issuecomment-681967800. Let me know if you need help reproducing the bug.

**Comment by eterna2** [comment]
@hsezhiyan 

Is it possible for u to provide me with a dummy pipeline.yaml so I can reproduce it on my machine?

Did u use the `set_retry` method? 
```py
op.set_retry(2)
```

**Comment by hsezhiyan** [comment]
Hello @eterna2 ,

Of course! Thank you for getting back to me. I didn't use the `set_retry` method.

Here is the [pipeline yaml file](https://drive.google.com/file/d/1s3WsjsM3-IVQKsJP9B2SrbqWzVtq8mRK/view?usp=sharing). Here is the [workflow yaml file ](https://drive.google.com/file/d/14SBMWhMTHuvmdhNwu1QEvTxSgivIhaXO/view?usp=sharing)

Here are example of failed API calls (retrieved using the `inspect` functionality on Chrome):
`logs?podname=mnist-pytorch-example-f9prl-3877604630&podnamespace=hariharans`
`logs?podname=mnist-pytorch-example-f9prl-1107911560&podnamespace=hariharans`
`logs?podname=mnist-pytorch-example-f9prl-1507110387&podnamespace=hariharans`

**Comment by eterna2** [comment]
Ok I figured out the reasons for the errors. Although not too sure how can we solve this.

The reason for the error is because argo does not archive "Retry" pods at all. And it seems either the pod is never created or was gc the moment it errored out (before any logs can be archived to minio/s3). 

I might need to write a small pod event monitor app and track whether the pod is created or not, and whether was it gc too quickly (so I can know is it an argo issue or a kfp issue).

**Comment by eterna2** [comment]
Ok I did more investigation. The "Retry" pod was never created as I did not capture any pod events from it at all. 

I think we might need to raise a ticket upstream to argo. I have no idea why this happens (creating a virtual pod?).

**Comment by eterna2** [comment]
@Bobgy 

I did more tests. This is an UI bug. When u set a retry limit for your ops, argo will always create a `Retry` node which is not an actual physical pod, hence this node does not have any logs or pod info. 

And this node will always exist regardless if there is an actual retry or not.

So there are 2 solution to this issue. We do not render `Retry` nodes at all. Or we give `Retry` nodes a separate color scheme with no metadata at all (i.e. no artifacts, no logs, no pod info, etc) - as these info will be reflect in the actual `Pod` node.

**Comment by Bobgy** [comment]
Thank you for the detailed investigation!
Which solution Do you think is easier to implement?

I am still not fully understanding the topology here.

**Comment by eterna2** [comment]
I have looked at the DAG graph rendering code. There is an existing function to filter our virtual nodes. I just need to add `Retry` as another virtual node. 

I will be making a PR to reflect this. 

This is the original DAG with the `Retry` node (2nd node). 
![image](https://user-images.githubusercontent.com/1248825/92455940-e08ef180-f1f4-11ea-8eaf-60e85533e4a6.png)

My PR will remove this virtual node.
![image](https://user-images.githubusercontent.com/1248825/92455879-ce14b800-f1f4-11ea-9e21-e2b2acc61be0.png)
