### ISSUE TITLE
Re-integrate build-image "test" back into the test suites

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#444]
Reasons:
* This fixes the last code de-sync issue
* Improves test times since there is no need to wait for creation of another cluster
* Works around the test re-run bug caused by soon to be deprecated `run_after_success`: https://github.com/kubernetes/test-infra/issues/10244#issuecomment-442285835

**Comment by vicaire** [comment]
@Ark-kun, what is the status on this? Can we close?

**Comment by Ark-kun** [comment]
This has been completed.
