### ISSUE TITLE
Rerun specific successful KFP steps

### ISSUE THREAD

**Issue by eedorenko** [kubeflow/pipelines#4446]
To improve the development experience it would be very convinient to be able to rerun one single step or a few steps of a 
pipeline. It will help in scenarios when I am working on a specific component and want to test it in a pipeline taking the rest from the cache. There are two different scenarios where I want to specify which KFP steps should be re-executed (ignoring cache): 
- Rerun of an existing successful pipeline run, so it reuses the same run_id.
    -  Currently, rerun is possible only for failed runs. 
    - Helpful for situations when run_id is meaningful for KFP steps in the pipeline and passed as a parameter. Rerunning with the same run_id will allow to take inputs/outputs of those steps from the cache
- New Pipeline run. 

In both cases we can force re-execution of a pipeline step by updating an image tag or parameters, but it requires rebuilding the pipeline which is preferable to avoid.

**Comment by Ark-kun** [comment]
Usually when we work on a pipeline, every change is a component change. This automatically causes the changed component to be re-executed.
It might be unsafe to create pipelines where the behavior changes while the pipeline remains exactly the same.

Regarding run_id: A workaround might be to use a component to generate and output a random string or number. Then that number can be used in arguments to other components. This will allow you to easily control the run IDs and their generation.

**Comment by eedorenko** [comment]
The key points here:
1. I don't want to rebuild a pipeline to get a specific component re-executed
2. Of course I can implement this  by introducing an artificial parameter which I use to control what components should ignore cache. But this is very artificial approach and this is needed only in dev process. I don't need it in production. It should be handled out-of-the box without adding any parameters.
3. Using kfp_run_id is beneficial (instead of using some extra unique string) as it is native KFP identifier that I can use to connect whatever my component produces with a KFP run. So ability to rerun a successful KFP rerun would be very helpful.

**Comment by Bobgy** [comment]
@eedorenko When you rerun a few steps, do you rerun with the same components, or updated components?

**Comment by eedorenko** [comment]
Both.
1. Same component. It mostly happens when a component is dependent on some external conditions (data, externals systems, etc.). So, I change the external conditions and I want to rerun the component without changing it.
2. Updated component. If the component is updated or the parameters are updated it will rerun the component. But, I need to rerun it in the same run (not the cloned one). Currently I can rerun only failed run.

**Comment by Ark-kun** [comment]
TBH, I think it would be best if you augmented your reliance on kfp_run_id and aspects of its behavior (not changing during reruns).
You might want to generate your own run id and pass it to the components, but then record the connection between the `kfp_run_id` and `run_id`.

Example:

```python
hash_op = load_component_from_url('https://raw.githubusercontent.com/kubeflow/pipelines/8814c3d583be6604c2bbb56dd6c58692bc2630aa/components/basics/Calculate_hash/component.yaml')

import json
def my_pipeline(param1: int = 1, param2: str = 'hello', run_id_seed: str = '0'):
    pipeline_arguments = {str(k): str(v) for k, v in locals().items()}
    run_id = hash_op(data=json.dumps(pipeline_arguments)).output
    
    # record_op(kfp_run_id=dsl.RUN_ID_PLACEHOLDER, run_id=run_id)
```

**Comment by eedorenko** [comment]
@Ark-kun thanks a lot for the detailed answer. I think it will do and work in my use-cases.
