### ISSUE TITLE
Pipelines UI doesn't surface Argo errors appropriately

### ISSUE THREAD

**Issue by knkski** [kubeflow/pipelines#4447]
### What steps did you take:

- I ran a pipeline that should have worked
- The pipeline failed at an unexpected step with this message:
  - `This step is in Error state with this message: failed to save outputs: timed out waiting for the condition`
- I had to run this command to get an actual error message:
  - `kubectl logs --tail 100 failing-pipeline-123-asdf -c wait`
- The actual error message was:
  - `Failed to put file: Storage backend has reached its minimum free disk threshold. Please delete a few objects to proceed`
- I then cleaned up old artifacts in minio and the pipeline worked as expected

### What happened:

The pipeline failed at an unexpected step with an unhelpful error message

### What did you expect to happen:

Pipelines UI should have surfaced the underlying Argo error better

### Environment:
KFP version: 0.2.5
KFP SDK version: 1.0.0

### Anything else you would like to add:

It would be very useful if the UI could display all messages logged from the Argo sidecar container labelled as `level=warning` or above (including `level=error` and `level=fatal`).

/kind bug
/area frontend

**Comment by Bobgy** [comment]
Thanks for reporting that!
It's really hard for KFP to surface argo error message that only shows up in the logs. Do you have any suggestions we can improve?

**Comment by knkski** [comment]
@Bobgy: Thanks for the response. I was thinking similarly to how the logs from the `main` container are shown for each pipeline pod, we could also show logs from the `wait` container in the same pod. See here for what I mean by logs from the `main` container:

https://v0-5.kubeflow.org/docs/images/pipelines-mnist-logs.png

The Argo sidecar's logging messages wouldn't have to be displayed by default, even a button like "View sidecar logs" or similar would be helpful.

**Comment by Bobgy** [comment]
Thanks for the suggestion!
Sounds reasonable to me, PRs welcomed on implementing that.
