### ISSUE TITLE
Edges crossing in DAG pipeline UI

### ISSUE THREAD

**Issue by raphaelauv** [kubeflow/pipelines#4455]
Hi, a big thank for all your work , it's a real pleasure to use KB !

With big DAG , the pipeline UI is getting messy to read , there is a lot of edge crossing between tasks ,would be nice to reduce at maximum theses.

Is there any work on this , or could you indicate me where is the code computing the graph, so I could maybe contribute :)

we could use what is already done by  graphviz/dot

so this
![Screenshot from 2020-09-02 17-34-24](https://user-images.githubusercontent.com/10202690/92005299-9cf33e00-ed43-11ea-9605-b6b81cf4094e.jpg) 
become this when possible : 
![2](https://user-images.githubusercontent.com/10202690/92005310-9f559800-ed43-11ea-84e7-ece963aec5d1.png)

**Comment by Bobgy** [comment]
https://github.com/kubeflow/pipelines/blob/master/frontend/src/components/Graph.tsx

here it is.

Thank you for raising the issue! Contributions welcomed if there is a better way
