### ISSUE TITLE
Unable to run DEMO pipeline after configuring KUBEFLOW from marketplace

### ISSUE THREAD

**Issue by naresh4u-gitrepo** [kubeflow/pipelines#4458]
When we run DEMO for iris or xgboost example, we get error saying insufficient access to storage bucket that we use. This happens even after granting the permissions as mentioned in the DEMO pipeline section.

**Comment by Bobgy** [comment]
What was the exact error message?
Did you enable workload identity with the cluster(you shouldn't)?
