### ISSUE TITLE
Confusion Matrix UI Doesn't Work if My Labels are "True", "False"

### ISSUE THREAD

**Issue by qimingj** [kubeflow/pipelines#446]
For example, if your metadata is like:

  metadata = {
    'outputs' : [{
      'type': 'confusion_matrix',
      'storage': 'gcs',
      'format': 'csv',
      'schema': [
        {'name': 'target', 'type': 'CATEGORY'},
        {'name': 'predicted', 'type': 'CATEGORY'},
        {'name': 'count', 'type': 'NUMBER'},
      ],
      'source': cm_file,
      'labels': ['True', 'False'],
    }]
  }

And if your Data is like:

True, True, 100
True, False, 20
False, True, 10,
False, False, 200

UI won't work. Probably because the serialization and deserialization of metadata converts string to boolean, and when parsing the actual data it does not do the same.

**Comment by yebrahim** [comment]
This works for me, except that it complains about the `source` field. If I set it properly to some GCS source it works fine.

**Comment by qimingj** [comment]
turns out it is the saved metadata problem. The sample metadata I gave does not match the reality. In reality it is:

...
'labels': [True, False],
...

and it is saved to json file as boolean. I will fix it in the CM component. Sorry about the incorrect information!
