### ISSUE TITLE
Rest API for streaming pipeline logs

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/pipelines#4468]
Having a Rest API for log can be useful is we are using the CLI or SDK client. Is there any plan for adding a REST API to stream logs or it's by design due to security or performance concern? Thanks.

**Comment by Bobgy** [comment]
It's not by design, welcome contribution

**Comment by Bobgy** [comment]
@rafalbigaj would you want to create a new issue tracking leftover issues for this new endpoint?
