### ISSUE TITLE
Possible to import GCP component functions instead of load_component_from_url?

### ISSUE THREAD

**Issue by alex-dixon** [kubeflow/pipelines#4472]
`load_component_from_url` appears to be the recommended way to use GCP components (like dataproc create cluster and others).

Are there functions defined for GCP components somewhere that I could import as an alternative?

I'm looking to make the contracts clear in the code and allow IDE "go to definition", provide autocomplete, etc.

**Comment by Ark-kun** [comment]
KFP SDK is platform and cloud-agnostic. The SDK does not have any Google-specific functions.
This has an advantage of not coupling the SDK version with component versions.

In Jupyter environment you get help for components loaded using `load_component_from_url` by pressing Shift+Tab. You can also use `help(my_op)`.

If your IDE has troubles with the dynamic functions, you can create simple wrappers:

```
my_component = load_component_from_url(...)

def my_op(param1, param2)
    return my_component(param1, param2)
```
