### ISSUE TITLE
How can I close a Recurring Run?

### ISSUE THREAD

**Issue by BarleyXu** [kubeflow/pipelines#4475]
I create a recurring type run with pipeline UI. Some problems occured when I run it.
When I delete the recurring run with commad - kubectl get workflow -n kubeflow |grep xxxx | awk '{print "workflow/"$1" -n kubeflow"}' | xargs kubectl delete.  The recurring run restart after a while.

**Comment by Ark-kun** [comment]
AFAIK, RecurringJobs have their own CRD that spawns runs on schedule.

You can use the KFP API client (or maybe kubectl) to delete them.

**Comment by BarleyXu** [comment]
> AFAIK, RecurringJobs have their own CRD that spawns runs on schedule.
> 
> You can use the KFP API client (or maybe kubectl) to delete them.

Thanks response, I have tried to delete it with kubectl, but failed., There is no KFP client in company lan.

**Comment by Bobgy** [comment]
Recurring runs are called jobs in KFP API, you can delete them via https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.server_api.html#kfp_server_api.api.job_service_api.JobServiceApi.delete_job

**Comment by BarleyXu** [comment]
> Recurring runs are called jobs in KFP API, you can delete them via https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.server_api.html#kfp_server_api.api.job_service_api.JobServiceApi.delete_job

thanks , can i delete it with kubectl?

**Comment by Bobgy** [comment]
No, you cannot

**Comment by BarleyXu** [comment]
> > Recurring runs are called jobs in KFP API, you can delete them via https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.server_api.html#kfp_server_api.api.job_service_api.JobServiceApi.delete_job
> 
> thanks , can i delete it with kubectl?

Kfp API need job id param, it's strange that thres is no corresponding job of recurring run when i excute 'kubectl get  jobs -n kubeflow'.

**Comment by Bobgy** [comment]
Sorry, it's common confusion, but KFP job has nothing to do with k8s job.

You can list jobs with a name filter to get job by name.

**Comment by Bobgy** [comment]
https://www.kubeflow.org/docs/pipelines/tutorials/sdk-examples/#example-2-listing-pipelines-with-a-filter

**Comment by BarleyXu** [comment]
> https://www.kubeflow.org/docs/pipelines/tutorials/sdk-examples/#example-2-listing-pipelines-with-a-filter

ok, thank you very much.

**Comment by alinaSarwar** [comment]
```
kubectl get scheduledworkflows -n <namespace>
kubectl delete scheduledworkflow <job-name> -n <namespace>
```
