### ISSUE TITLE
[Deployment] Failed to deploy to local kind cluster

### ISSUE THREAD

**Issue by numerology** [kubeflow/pipelines#4481]
### What steps did you take:
Follow the step described in https://www.kubeflow.org/docs/pipelines/installation/localcluster-deployment/#deploying-kubeflow-pipelines

### What happened:
Hit 
```
error: evalsymlink failure on '/tmp/kustomize-168581962/manifests/kustomize/env/platform-agnostic-pns' : lstat /tmp/kustomize-168581962/manifests/kustomize/env/platform-agnostic-pns: no such file or directory
```

### Environment:
I was deploying to a linux machine with kind v0.8.1, and k8s v1.18.2

However I can deploy by following the standard standalone deployment at 
https://www.kubeflow.org/docs/pipelines/installation/standalone-deployment/#deploying-kubeflow-pipelines

/kind bug
/area deployment/standalone

**Comment by numerology** [comment]
@Bobgy do you have any suggestion? Thanks!

**Comment by numerology** [comment]
I think I know why: for version 1.0.0 there's no platform-agnostic-pns folder

**Comment by Bobgy** [comment]
Exactly, I've just updated doc to say master
