### ISSUE TITLE
is there a way to pass parameters to `kfp.compiler.Compiler().compile` in Python

### ISSUE THREAD

**Issue by zyxue** [kubeflow/pipelines#4488]
I wonder if there is a way to pass parameters for the pipeline to be complied to [`kfp.compiler.Compiler().compile`](https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.compiler.html#kfp.compiler.Compiler.compile) in Python directly instead of command line?

**Comment by Ark-kun** [comment]
The compiled pipeline is supposed to be configurable. It's like a function definition as opposed to a function call.

1. You could use `kfp.Client(host=...).create_run_from_pipeline_func(my_pipeline, arguments={...})`
2. You can specify default pipeline parameter values in the pipeline function definition.
