### ISSUE TITLE
Connect Timeout Issue with Istio proxy & Argo

### ISSUE THREAD

**Issue by connorlwilkes** [kubeflow/pipelines#4494]
### What steps did you take:
[A clear and concise description of what the bug is.]

Deploy 'no' auth kubeflow with Istio 1.4.3 and try and run any KF Pipeline.

### What happened:

On creation of a kubeflow pipeline the pipeline hangs and is unable to start with the following error in the 'wait' container:

`time="2020-09-14T13:23:01Z" level=warning msg="Failed to get pod 'conditional-execution-pipeline-with-exit-handler-ncxrj-3135351842': Get https://{kubeapiserverserviceip}/api/v1/namespaces/kubeflow/pods/conditional-execution-pipeline-with-exit-handler-ncxrj-3135351842: dial tcp {kubeapiserverserviceip}: connect: connection refused"`

This eventually leads to:

`time="2020-09-14T13:23:01Z" level=fatal msg="Get https://{kubeapiserverserviceip}/api/v1/namespaces/kubeflow/pods/conditional-execution-pipeline-with-exit-handler-ncxrj-3135351842: dial tcp {kubeapiserverserviceip}3: connect: connection refused\ngithub.com/argoproj/argo/errors.Wrap\n\t/go/src/github.com/argoproj/argo/errors/errors.go:88\ngithub.com/argoproj/argo/errors.InternalWrapError\n\t/go/src/github.com/argoproj/argo/errors/errors.go:71\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).getPod\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:620\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).GetMainContainerStatus\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:702\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).GetMainContainerID\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:719\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).SaveParameters\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:397\ngithub.com/argoproj/argo/cmd/argoexec/commands.waitContainer\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:48\ngithub.com/argoproj/argo/cmd/argoexec/commands.NewWaitCommand.func1\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:16\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/src/github.com/spf13/cobra/command.go:766\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/src/github.com/spf13/cobra/command.go:852\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/src/github.com/spf13/cobra/command.go:800\nmain.main\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/main.go:17\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:201\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1333"`

This is caused by the istio-proxy not starting until after the wait container meaning that requests out are blocked.

### What did you expect to happen:

Pipeline to run normally

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

Using kfdef to create manifests then individually applying with kubectl apply -f

KFP version: 

743746b

KFP SDK version: 

`kfp                      1.0.1
kfp-server-api           1.0.1`

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

I was able to resolve this issue temporarily by editing the namespace to prevent injection of istio sidecar but this isn't a great solution as I require the observability offered by Istio across my cluster.

This looks like it has visibility already in the Argo project (https://github.com/argoproj/argo/issues/1282) and looks like Istio has recently merged: https://github.com/istio/istio/pull/24737 that attempts to fix this issue. However I was unable to deploy any Istio greater than 1.4.3 due to profile controller issues (https://github.com/kubeflow/kubeflow/issues/5301).

There is also a k8s PR that looks to fix this issue too: https://github.com/kubernetes/enhancements/issues/753.

I am wondering how this issue is resolved when there is a proper namespace as currently everything for me runs in kubeflow namespace due to the fact that I don't have IAP etc set up

/kind bug

**Comment by Bobgy** [comment]
Right now, KFP will create argo workflows that always explicitly disable istio sidecar.
and we wait for upstream progress
