### ISSUE TITLE
ContainerOp.add_pvolumes does not support sub_path on kubernetes.client.models.V1VolumeMount

### ISSUE THREAD

**Issue by boarder7395** [kubeflow/pipelines#4500]
The method add_pvolumes on ContainerOp has only basic support of the V1VolumeMount but does support sub_path and sub_path_expr.

How add_pvolumes is currently implemented I can't see a nice way of adding the possibility of passing addition arguments to V1VolumeMount.

**Comment by Ark-kun** [comment]
Hello.
Can you please describe your high-level scenario for using volumes?
ContainerOp has `task.add_volume(...)` and `task.container.add_volume_mount`. Is there something missing in those two methods that prompt you to use the experimental contrib `add_pvolume`?

**Comment by boarder7395** [comment]
Sorry I actually thought add_pvolume was the preferred method I will take a look at add_volume and add_volume_mount!

My goal is to attach a single volume to my container and then use paths inside that volume at different container paths. 

For example:
I am running a ContainerOp and want the storage to be on volume A at path /dask mounted to container path /dask/tmp and volume A at path /data mounted to container path /data.

**Comment by boarder7395** [comment]
I took a look at task.add_volume, and task.container.add_volume_mount and those are exactly what I am looking for thanks Ark-Kun!!
