### ISSUE TITLE
Documentation: Generating API keys for KFP API authentication (on platforms other than GCP, GKE)

### ISSUE THREAD

**Issue by n3o-Bhushan** [kubeflow/pipelines#4502]
I want to access experiments or runs related data in multi-user isolation environment.
Is there any documentation available for generating user specific API keys that can be used with `kfp_server_api`? I am not able to find any documentation to do so.

**Comment by JV-DHL** [comment]
Hii , did you find the something to generate the API keys ? I too have the same doubts ...
