### ISSUE TITLE
Expected workflow with VolumeOp.delete()?

### ISSUE THREAD

**Issue by boarder7395** [kubeflow/pipelines#4506]
Using VolumeOp to create a volume works great, but when calling VolumeOp.delete() after the containerOp completes, the pvc is not being removed since it will be stuck in a terminating state until the pod created by containerOp is deleted. This is because the finalizer kubernetes.io/pvc-protection will prevent the pvc from being deleted even if the container is in a completed ("successful") state. From what I can tell the pods created by kfp will reach completed ("successful") state but are not terminated until manually called (or the max pod limit is reached).

Given this what is the expected workflow with VolumeOp.delete() should we be removing the finalizer on kfp pods? This seems risky. Or is there an alternative finalizer that allows volumes to be removed from containers that are in the completed ("successful") status.

**Comment by elikatsis** [comment]
Hi @boarder7395,

the `persistenceagent` is responsible for workflow GC, which, eventually, also GCs pods (and thus the terminated PVCs).
The default TTL is 7 days (see [1], [2]).
You can also set a different TTL by editing its deployment. I believe something like [this](https://github.com/kubeflow/pipelines/blob/d4e73989170cf5e44b2fe1064a904003c3c5a7ff/manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml#L22-L23) should do.

[1]: https://github.com/kubeflow/pipelines/blob/d4e73989170cf5e44b2fe1064a904003c3c5a7ff/backend/Dockerfile.persistenceagent#L21
[2]: https://github.com/kubeflow/pipelines/blob/d4e73989170cf5e44b2fe1064a904003c3c5a7ff/backend/Dockerfile.persistenceagent#L26

**Comment by munagekar** [comment]
Volume op could expose an option to set the TTL. This could be set as an annotation on the PVC. The persistence agent should refer this annotation for deletion.

**Comment by Ark-kun** [comment]
@boarder7395 Just to gather some feedback: Can you please describe the scenario leading to you using advanced and non-portable concepts like Kubernetes volumes instead of using common data-passing via inputPath/outputPath?

**Comment by boarder7395** [comment]
So if I understand correctly Ilias updating the persistence agent so the TTL is ~30 seconds or so will result in the pods created by containerOPs being cleaned up within 30 seconds allowing the PVC that was created to be cleaned up as well?

I tried updating my persistenceagent to 30 seconds and it doesn't seem to be removing pods with the completed status?

**Comment by boarder7395** [comment]
Hey Alexey I could entirely be using volumes incorrectly but I was attaching volumes to increase temporary storage for each pod. Is the preferred method of increasing storage for a pod to increase the storage for the nodes?

Basically I have a shuffle operation happening in one of my stages that writes a large amount of data to temporary storage which is filling up the space I have available on the nodes. To solve this I was attaching kubernetes volumes to the pods. 

I am not using the volumes to pass data between stages (steps) of the pipeline each step writes directly to s3 in my use case.

**Comment by munagekar** [comment]
We also use the VolumeOp feature in my organization. 
Certain pipeline use a massive dataset, ~1 TB.  By using PVC we eliminate copy from gcs, process ,copy back to gcs for each pipeline stage.

**Comment by boarder7395** [comment]
So in continuing to work on this I am wondering if we should use the pipeline_conf to change the ttl_seconds_after_finished this may clean up the pod as soon as it completes making the volume cleanup happen as expected.
```
pipeline_conf = PipelineConf()
pipeline_conf.ttl_seconds_after_finished = 10
```

**Comment by Bobgy** [comment]
> So in continuing to work on this I am wondering if we should use the pipeline_conf to change the ttl_seconds_after_finished this may clean up the pod as soon as it completes making the volume cleanup happen as expected.
> 
> ```
> pipeline_conf = PipelineConf()
> pipeline_conf.ttl_seconds_after_finished = 10
> ```

I'd recommend not do this, because KFP tries to persist workflow status into KFP's db, if the workflow is GCed too quickly, its content might not get persisted yet.

Recommend setting
https://github.com/kubeflow/pipelines/blob/f445c09f8181b520caf53340aec217ace13290ed/backend/Dockerfile.persistenceagent#L21

It will make sure the pipeline is persisted first before GCing it.

You can override it by env vars to deployment ml-pipeline-persistence-agent

**Comment by boarder7395** [comment]
After doing some testing I do not believe the TTL_SECONDS_AFTER_WORKFLOW_FINISH fix addresses the issue. My guess is that variable addresses the clean-up after the pipeline (argo workflow) has completed. If you are creating a volume at the start of the workflow and deleting the volume at the end of the workflow then the workflow will hang indefinitely since the pods with the volume attached will not be deleted until the workflow has completed but the workflow cannot complete until the pods are removed and the volume is deleted.

**Comment by elikatsis** [comment]
@boarder7395 
Nice catch. This happens because `kubectl` has a default behavior of waiting the deletion. We can fix this adding a flag `--wait=false` in the command.

Argo has enabled adding flags in `ResourceTemplate` but our deployment doesn't support it.
However, we are not using a `ResourceTemplate` for the `delete()` method. So we can add this flag without caring about Argo.

I will submit a PR for this.

**Comment by boarder7395** [comment]
I tested that fix locally and it solved my issue!

**Comment by elikatsis** [comment]
Same, I submitted a PR for it: https://github.com/kubeflow/pipelines/pull/4820

**Comment by elikatsis** [comment]
Closing this since we have merged the PR :smiley: 
/close
