### ISSUE TITLE
Support workflow and step level retry strategy 

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#451]

**Comment by gaoning777** [comment]
we already supported step level retry: https://github.com/kubeflow/pipelines/blob/895645c3e4e90df1c14ab0b4336be74a35d85a5d/sdk/python/kfp/dsl/_container_op.py#L799

**Comment by gaoning777** [comment]
Argo does not have workflow level retry. 
DSL has a sample to illustrate how to apply a transformer to all ops in a pipeline: https://github.com/kubeflow/pipelines/pull/1440

**Comment by llKetanll** [comment]
@gaoning777 Can we retry from the UI for a specific step?

**Comment by gaoning777** [comment]
Unfortunately not. Currently, the retry can be configured in the DSL and the backend automatically retries the steps if they fail. If your user scenario is to be able to rerun a specific step, we are working on the KFP caching such that a pipeline can be rerun without rerunning all steps.

**Comment by kevinpauli** [comment]
>  we are working on the KFP caching such that a pipeline can be rerun without rerunning all steps.

@gaoning777 can you please provide a link to the GH issue that is tracking this effort?

**Comment by amclay** [comment]
@gaoning777 I would also be interested in tracking this ticket if it exists. (for retrying individual steps)
