### ISSUE TITLE
Feature Request: Show descriptions of inputs on kubeflow ui

### ISSUE THREAD

**Issue by munagekar** [kubeflow/pipelines#4513]
It will be nice to have description of the arguments when creating a run.

## Creating a Run UI: Run Parameters does not have argument descriptions
![Screen Shot 2020-09-18 at 16 02 14](https://user-images.githubusercontent.com/10258799/93566830-9eba3400-f9c8-11ea-9e18-6b6036299602.png)

## Pipeline UI: Input Parameters in the Pipeline UI doesn't have argument descriptions
![Screen Shot 2020-09-18 at 16 01 26](https://user-images.githubusercontent.com/10258799/93566837-a24dbb00-f9c8-11ea-85a3-6ea32faebffe.png)

**Comment by munagekar** [comment]
Pipeline Code

```python
@dsl.pipeline(name="Secret Pipeline")
def pipeline(
    env_var: str,
    secret_name: str,
    secret_key: Optional[str] = None
    ) -> None:
    """
    Pipeline to Demonstrate Usage of Secret

    Args:
        env_var: Name of the variable inside the Pod
        secret_name: Name of the Secret in the namespace
        secret_key: Key for the value in the secret volume
    """
    pass
```

**Comment by Ark-kun** [comment]
This is a duplicate of https://github.com/kubeflow/pipelines/issues/448, but let's keep this open.

Thank you for proposing a way to specify the descriptions. This was one of the problems blocking the original issue.

And thank you for taking time to implement the needed SDK change!

**Comment by munagekar** [comment]
I would be interested in this feature.

**Comment by akiyamasho** [comment]
> I would be interested in this feature.

+1
