### ISSUE TITLE
Kubeflow Pipelines on GCP can't launch due to pods issues.

### ISSUE THREAD

**Issue by Sterls** [kubeflow/pipelines#4521]
I created multiple clusters on GCP using the default settings through the AI platform. When I open the pipelines tab in AI Platform, I get the error : "Error occured while trying to proxy to: ...".

I am getting this error on multiple pipelines on multiple clusters. None of the sample tutorials or templates work due to the same error. 

1) Is this a kubeflow issue or a GCP issue? 
2) I'm not too savvy on Kubernetes. I've tried creating clusters using different approaches on GCP. I don't think I'm doing anything wrong because I've been following a bunch of different tutorials and documentation etc etc.. they all lead to these 2 pods issues: ml-pipeline-65479485c8-mcj9x and ml-pipeline-persistenceagent-67db8b8964-mlbmv.  I made a S/O post here: https://stackoverflow.com/questions/63946871/gcp-ai-platform-pipelines-clusters-does-not-have-minimum-availability

**Comment by Ark-kun** [comment]
This is really strange.

Did you install using the Google Cloud Marketplace UX?

Did you create a new Kubernetes cluster in the process?

**Comment by Sterls** [comment]
I did the following:

On AI Platform -> Pipelines -> New Instance
This takes me to a Kubeflow pipelines config page. Here I am able to create a new cluster or select an existing one. I can create it by selecting a zone and clicking the "Create cluster" button (Here is where I think it creates it on the Google Cloud Marketplace). Then I select the checkbox "Use managed storage" and click "Deploy". 

Even if I create a cluster via the Kubernetes Engine, when I link the Kubeflow pipeline to it, the same problems with the 2 pods exist - "Does not have minimum availability".

Am I missing something obvious?

Below is the full pod description for one of the pods:
```
Name:         ml-pipeline-65479485c8-mcj9x
Namespace:    default
Priority:     0
Node:         gke-cluster-3-default-pool-007784cb-qcsn/10.150.0.2
Start Time:   Thu, 17 Sep 2020 22:15:19 +0000
Labels:       app=ml-pipeline
              app.kubernetes.io/name=kubeflow-pipelines-3
              pod-template-hash=65479485c8
Annotations:  kubernetes.io/limit-ranger: LimitRanger plugin set: cpu request for container ml-pipeline-api-server

Status:       Running
IP:           10.4.0.8
IPs:
IP:           10.4.0.8
Controlled By:  ReplicaSet/ml-pipeline-65479485c8
Containers:
  ml-pipeline-api-server:
    Container ID:   ...
    Image:          ...
    Image ID:       ...
    Ports:          8888/TCP, 8887/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Running
      Started:      Fri, 18 Sep 2020 10:27:31 +0000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Fri, 18 Sep 2020 10:20:38 +0000
      Finished:     Fri, 18 Sep 2020 10:27:31 +0000
    Ready:          False
    Restart Count:  98
    Requests:
      cpu:      100m
    Liveness:   exec [wget -q -S -O - http://localhost:8888/apis/v1beta1/healthz] delay=3s timeout=2s period=5s #success=1 #failure=3
    Readiness:  exec [wget -q -S -O - http://localhost:8888/apis/v1beta1/healthz] delay=3s timeout=2s period=5s #success=1 #failure=3
    Environment:
      HAS_DEFAULT_BUCKET:                   true
      BUCKET_NAME:
      PROJECT_ID:                           <set to the key 'project_id' of config map 'gcp-default-config'>  Optional: false
      POD_NAMESPACE:                        default (v1:metadata.namespace)
      DEFAULTPIPELINERUNNERSERVICEACCOUNT:  pipeline-runner
      OBJECTSTORECONFIG_SECURE:             false
      OBJECTSTORECONFIG_BUCKETNAME:
      DBCONFIG_DBNAME:                      kubeflow_pipelines_3_pipeline
      DBCONFIG_USER:                        <set to the key 'username' in secret 'mysql-credential'>  Optional: false
      DBCONFIG_PASSWORD:                    <set to the key 'password' in secret 'mysql-credential'>  Optional: false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from ml-pipeline-token-77xl8 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  ml-pipeline-token-77xl8:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ml-pipeline-token-77xl8
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                   From                                               Message
  ----     ------     ----                  ----                                               -------
  Warning  BackOff    52m (x409 over 11h)   kubelet, gke-cluster-3-default-pool-007784cb-qcsn  Back-off restarting failed container
  Warning  Unhealthy  31m (x94 over 12h)    kubelet, gke-cluster-3-default-pool-007784cb-qcsn  Readiness probe failed:
  Warning  Unhealthy  31m (x29 over 10h)    kubelet, gke-cluster-3-default-pool-007784cb-qcsn  (combined from similar events): Readiness probe failed: c
annot exec in a stopped state: unknown
  Warning  Unhealthy  17m (x95 over 12h)    kubelet, gke-cluster-3-default-pool-007784cb-qcsn  Liveness probe failed:
  Normal   Pulled     7m26s (x97 over 12h)  kubelet, gke-cluster-3-default-pool-007784cb-qcsn  Container image "gcr.io/cloud-marketplace/google-cloud-ai
-platform/kubeflow-pipelines/apiserver:1.0.0" already present on machine
  Warning  Unhealthy  75s (x78 over 12h)    kubelet, gke-cluster-3-default-pool-007784cb-qcsn  Liveness probe errored: rpc error: code = DeadlineExceede
d desc = context deadline exceeded
```

**Comment by Ark-kun** [comment]
>Then I select the checkbox "Use managed storage" and click "Deploy".

This is the likely issue.
I've had this problem before: https://github.com/kubeflow/pipelines/issues/3798 https://github.com/kubeflow/pipelines/issues/3795 https://github.com/kubeflow/pipelines/issues/3797
As a workaround, uncheck that box.

/cc @Bobgy
I think the current Marketplace UX could be more intuitive and easier to use out-of-the-box.

**Comment by Bobgy** [comment]
Yes, when you check "use managed storage", you must setup your managed storage beforehand and fill in the fields below to connect your KFP instance with your managed storages.

**Comment by Sterls** [comment]
Thank you so much! Starting fresh and doing everything without "using managed storage" fixed the pods issued. My pipelines are up and running successfully! 

Even when "Using managed storage" I felt like I messed up the setup for managed storage somewhere because it really isn't clear for ML Ops noobs.
