### ISSUE TITLE
ModuleNotFoundError: No module named <local-module> when running TFX module file in Kubeflow Pipelines

### ISSUE THREAD

**Issue by anineharto** [kubeflow/pipelines#4537]
I've created my own local code using both the TFX library and customized code. I've also created a pipeline on my on-prem minikube cluster resulting in a `tar.gz` file that I upload to Kubeflow Pipelines. I have created a Persistent Volume where I've stored my dataset, preprocessing module file: `module_file_transform.py` and train module file: `module_file_train.py`. My module files make use of other local modules (e.g config classes such as `DataConfig`) which is where I run into trouble. The following stack-trace indicates that it can't locate my local code inside the module files:

```
INFO:absl:Running driver for Transform
INFO:absl:MetadataStore with gRPC connection initialized
INFO:absl:Adding KFP pod name tf-template-pipeline-2nplz-2740531700 to execution
INFO:absl:Running executor for Transform
INFO:absl:Attempting to infer TFX Python dependency for beam
INFO:absl:Copying all content from install dir /tfx-src/tfx to temp dir /tmp/tmphwamj2jn/build/tfx
INFO:absl:Generating a temp setup file at /tmp/tmphwamj2jn/build/tfx/setup.py
INFO:absl:Creating temporary sdist package, logs available at /tmp/tmphwamj2jn/build/tfx/setup.log
INFO:absl:Added --extra_package=/tmp/tmphwamj2jn/build/tfx/dist/tfx_ephemeral-0.22.0.tar.gz to beam args
WARNING:tensorflow:From /tfx-src/tfx/components/transform/executor.py:511: Schema (from tensorflow_transform.tf_metadata.dataset_schema) is deprecated and will be removed in a future version.
Instructions for updating:
Schema is a deprecated, use schema_utils.schema_from_feature_spec to create a `Schema`
Traceback (most recent call last):
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 360, in <module>
    main()
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 353, in main
    execution_info = launcher.launch()
  File "/tfx-src/tfx/orchestration/launcher/base_component_launcher.py", line 205, in launch
    execution_decision.exec_properties)
  File "/tfx-src/tfx/orchestration/launcher/in_process_component_launcher.py", line 67, in _run_executor
    executor.Do(input_dict, output_dict, exec_properties)
  File "/tfx-src/tfx/components/transform/executor.py", line 391, in Do
    self.Transform(label_inputs, label_outputs, status_file)
  File "/tfx-src/tfx/components/transform/executor.py", line 849, in Transform
    preprocessing_fn = self._GetPreprocessingFn(inputs, outputs)
  File "/tfx-src/tfx/components/transform/executor.py", line 785, in _GetPreprocessingFn
    'preprocessing_fn')
  File "/tfx-src/tfx/utils/import_utils.py", line 67, in import_func_from_source
    loader.exec_module(user_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/mnt/module_files/module_file_transform.py", line 3, in <module>
    from tf_template.utils.configs import DataConfig
ModuleNotFoundError: No module named 'tf_template'
```
where `tf_template` is the name of my local module. 

* Do I have to use the `kfp` library to containerize my local python classes in order for this to work (even though these are only used indirectly in my module file)? If so, how do I do this? 
* Is a better option to add my local repo to the image used by my Persistent Volume?

**Comment by Ark-kun** [comment]
Please help us better understand  your issue.

It looks like your transform code imports from the `tf_template` module which does not exist in the TFX container image. Is that correct?

>these are only used indirectly in my module file

Can you elaborate this please?

**Comment by anineharto** [comment]
Yes, that's correct. I tried to git clone tf_template into my TFX container image and then running `pip install -e .` to make it run as a module. When running python inside my container I manage to import tf_template, but each the docker container created when the transform component in Kubeflow is not able to get a hold of it.

**Comment by anineharto** [comment]
@Ark-kun

**Comment by Ark-kun** [comment]
Can you please show the pipeline you're trying to run? A minimal example.
