### ISSUE TITLE
Issue using `ParallelFor(results.ouput)` when results is a list of objects

### ISSUE THREAD

**Issue by xinbinhuang** [kubeflow/pipelines#4551]
### What steps did you take:

I think this is an upstream bug from Argo: https://github.com/argoproj/argo/issues/2660

Attempting to loop through a list of objects using `dsl.ParallelFor` and call operations on it

```python
# simplified non-producible script - I can create a fully reproducible short snippet if you need
vintages_collection = create_vintage_op(timeseries_data.output)

with kfp.dsl.ParallelFor(vintages_collection.output) as vintage:
        estimation = estimation_op(vintage)
```

Here `vintages_collection` look something like this

```
[
  {
    "Dates": [
      "2018-05-31",
      "2018-04-30",
      "2018-03-31"
    ],
    "BenchmarkReturns": [
      [
        0.007215000000000001,
        0.007214,
        -0.035195
      ],
      [
        0.012107999999999999,
        0.012109,
        -0.004239
      ],
      [
        -0.021149,
        -0.02115,
        -0.018337
      ]
    ],
    {
    "Dates": [
      "2018-06-31",
      "2018-05-30",
      "2018-04-31"
    ],
    "BenchmarkReturns": [
      [
        0.007215000000000001,
        0.007214,
        -0.035195
      ],
      [
        0.012107999999999999,
        0.012109,
        -0.004239
      ],
      [
        -0.021149,
        -0.02115,
        -0.018337
      ]
    ],
   ...
]
```

### What happened:
Step failed with
> json: error calling MarshalJSON for type v1alpha1.ItemValue: impossible ItemValue.Type

### What did you expect to happen:
The object can be paralleled by the operation.

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?
  Standalone

KFP version:  1.0.0

KFP SDK version:  1.0.0

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by Ark-kun** [comment]
> I think this is an upstream bug from Argo: [argoproj/argo#2660](https://github.com/argoproj/argo/issues/2660)

Looks like that. Created an issue tracking upgrading Argo.
