### ISSUE TITLE
Up to three sample-test clusters are running at the same time for same PR commit

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#456]
centraldashboard | OK | Deployment | 1/1 | kubeflow | sample-2d7854a-29078
centraldashboard | OK | Deployment | 1/1 | kubeflow | sampletest-2d7854a4a0-13864
centraldashboard | OK | Deployment | 1/1 | kubeflow | sampletest-2d7854a4a0-1783
centraldashboard | OK | Deployment | 1/1 | kubeflow | sampletest-2d7854a4a0-24966

**Comment by vicaire** [comment]
Is this still an issue?

**Comment by Ark-kun** [comment]
I have not seen this a lot recently
