### ISSUE TITLE
[Release] Kubeflow Pipelines 1.2 umbrella tracker

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#4565]
/assign @Bobgy @Ark-kun 
This should temporarily resolve issues like https://github.com/kubeflow/pipelines/issues/4409.

TODOs:
* [x] p0 fix master branch post submit test failure https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/kubeflow-pipeline-postsubmit-integration-test/1320555010165051392

**Comment by Bobgy** [comment]
We should probably finish https://github.com/kubeflow/pipelines/issues/4540 first

**Comment by Bobgy** [comment]
Because we haven't been able to release a minor version for a while, this is our next priority

**Comment by Bobgy** [comment]
/cc @Ark-kun 
The top blocker is fixing master branch postsubmit tests.

**Comment by Bobgy** [comment]
The most important next step can be releasing a 1.1.0-alpha.1 to allow dogfooding.

**Comment by Bobgy** [comment]
I'm going to release a 1.1.0-alpha.1 for preview, some non-core sample tests are failing in postsubmit including container builder. I'll ignore them for this release.

**Comment by Bobgy** [comment]
Auto generated changelog has a problem:
https://github.com/kubeflow/pipelines/blob/7d36f48482d93f331664a851842276b733f1686a/CHANGELOG.md#110-alpha1-2020-11-02

It shows all changes from 0.5.1 to 1.1.0-alpha.1, because 1.0.0 was released on `release-1.0` branch.

**Comment by Bobgy** [comment]
1.1.0-alpha.1 is released, feedback welcomed if there are any problems: https://github.com/kubeflow/pipelines/releases/tag/1.1.0-alpha.1

**Comment by Bobgy** [comment]
/cc @rui5i 
We need to upgrade MLMD to 0.25.1

Reference: https://github.com/google/ml-metadata/issues/74#issuecomment-736731814

**Comment by Bobgy** [comment]
And we need to wait for a resolution of https://github.com/kubeflow/pipelines/issues/4847

**Comment by Bobgy** [comment]
@rui5i Handling https://github.com/kubeflow/pipelines/pull/4855 properly is still tricky.
I'll write about what we need to do here.

/cc @chensun

**Comment by Bobgy** [comment]
1. Merge https://github.com/kubeflow/pipelines/pull/4855 (I've updated dependency to `'kfp-server-api>=1.1.1b1, <2.0.0',` so the pre-released kfp-server-api 1.1.1b1 can be properly installed via pip)
2. Release 1.1.2-rc.1 as usual
3. During 1.1.2 release
    1. Run `./hack/release-imp.sh` instead of `./hack/release.sh` during release, the imp script add all changes to the local repo, so it's still possible editing the release commit before pushing it.
    2. Release `kfp-server-api 1.1.2` in pypi directly from the local folder
    3. Update https://github.com/kubeflow/pipelines/blob/982b506d4e2c2fe749e8b717ed88e30c737c71a8/sdk/python/setup.py#L34 to >=1.1.2
    4. Commit the release commit and push to master
    5. Continue normal release process

**Comment by Bobgy** [comment]
/cc @chensun @Ark-kun 
what do you think about above process for releasing this change?

Maybe, going forward, we should always release `kfp-server-api` package first in the release process, so `kfp` package can update its dependencies during release.

**Comment by chensun** [comment]
> 1. Merge #4855 (I've updated dependency to 'kfp-server-api>=1.1.1b1, <2.0.0'

The offending PR only exists in master, thus not available in 1.1.1b1, right? In that case, isn't 1.1.1b1 the same as 0.2.5?
If that's the case, then we can release 1.1.2-rc1 as usual without waiting for #4855, given we're not releasing `kfp` package 1.1.2-rc1. Instead, we are releasing `kfp` 1.1.2 from master. And only this step is blocked by the setup.py change with `kfp-server-api>=1.1.2-rc1` (or `>1.1.1`).

> Maybe, going forward, we should always release kfp-server-api package first in the release process, so kfp package can update its dependencies during release.

Agree.

**Comment by Bobgy** [comment]
@chensun the offending PR was released in 1.1.1b1 already, but yes, you are right this only blocks `kfp` release, we can skip this problem for backend release.

**Comment by chensun** [comment]
> @chensun the offending PR was released in 1.1.1b1 already, but yes, you are right this only blocks `kfp` release, we can skip this problem for backend release.

I see. Then we can merge $4855 as-is.

**Comment by Bobgy** [comment]
Release blocker: https://github.com/kubeflow/pipelines/issues/4903

**Comment by Bobgy** [comment]
All done
