### ISSUE TITLE
License collector causes failures of image builds during sample tests

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#457]
https://pantheon.corp.google.com/logs/viewer?interval=NO_LIMIT&project=ml-pipeline-test&minLogLevel=0&expandAll=false&timestamp=2018-12-04T01:54:47.909000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22container%22%0Aresource.labels.cluster_name%3D%22sampletest-2d7854a4a0-26499%22%0Aresource.labels.namespace_id%3D%22default%22%0Aresource.labels.project_id%3D%22ml-pipeline-test%22%0Aresource.labels.zone:%22us-central1-a%22%0Aresource.labels.container_name%3D%22main%22%0Aresource.labels.pod_id%3D%22sample-test-wkb4g-2286909636%22&scrollTimestamp=2018-12-04T01:51:58.000000000Z

https://pantheon.corp.google.com/logs/viewer?interval=NO_LIMIT&project=ml-pipeline-test&minLogLevel=0&expandAll=false&timestamp=2018-12-04T01:54:57.157000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22container%22%0Aresource.labels.cluster_name%3D%22sampletest-2d7854a4a0-26499%22%0Aresource.labels.namespace_id%3D%22default%22%0Aresource.labels.project_id%3D%22ml-pipeline-test%22%0Aresource.labels.zone:%22us-central1-a%22%0Aresource.labels.container_name%3D%22main%22%0Aresource.labels.pod_id%3D%22sample-test-wkb4g-3942394614%22&scrollTimestamp=2018-12-04T01:50:58.000000000Z

    The command '/bin/sh -c mkdir /usr/licenses && /ml/license.sh /ml/third_party_licenses.csv /usr/licenses' returned a non-zero code: 8

**Comment by Ark-kun** [comment]
```
I  [0m[91m--2018-12-04 01:51:57--  https://bitbucket.org/stoneleaf/enum34/raw/f24487b45cd041fc9406d67441d2186ac70772b7/enum/LICENSE
 
I  [0m[91mResolving bitbucket.org (bitbucket.org)... [0m[91m18.205.93.2, 18.205.93.0, 18.205.93.1, ...
 
I  Connecting to bitbucket.org (bitbucket.org)|18.205.93.2|:443... [0m[91mconnected.
 
I  [0m[91mHTTP request sent, awaiting response... [0m[91m500 Internal Server Error
 
I  [0m[91m2018-12-04 01:51:57 ERROR 500: Internal Server Error.
 
I  
 

```

**Comment by Ark-kun** [comment]
Python package metadata already contains the license name. Tools like https://pypi.org/project/pip-licenses/ or can extract it https://stackoverflow.com/questions/19086030/can-pip-or-setuptools-distribute-etc-list-the-license-used-by-each-install.

**Comment by Ark-kun** [comment]
Most of the licenses do not need to be downloaded. Less so every time a container builds.

**Comment by vicaire** [comment]
Is this still an issue?

**Comment by Ark-kun** [comment]
This issue is not as common at this time.
But we should really consider not downloading all the images every time.
