### ISSUE TITLE
As a user, I want to be alerted by e-mail in case of a pipeline or component failure!

### ISSUE THREAD

**Issue by julioyildo** [kubeflow/pipelines#4573]
Hi, 

Sorry I'm  new on Kubeflow. I'm currently looking for a way to be notified by e-mail when a pipeline or a component has failed.
I have read the documentation but haven't seen any information about it. 

Could someone help me ?

Thank you !  🙏

**Comment by parthmishra** [comment]
You can use [dsl.ExitHandler()](https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.dsl.html#kfp.dsl.ExitHandler) to set up an email alert when the pipeline fails.

**Comment by nrchakradhar** [comment]
You may also be interested in #4079

**Comment by eedorenko** [comment]
And in this https://github.com/kaizentm/kubemlops/pull/87/files

**Comment by julioyildo** [comment]
Thank you !

**Comment by Michallote** [comment]
Does somebody have examples of this being implemented with the ExitHandler?
