### ISSUE TITLE
When creating a new Profile and namespace with a ResourceQuotaSpec bootstrapped ml-pipeline-ui-artifact and ml-pipeline-visulisationserver fail due to failed quota

### ISSUE THREAD

**Issue by connorlwilkes** [kubeflow/pipelines#4576]
### What steps did you take:
[A clear and concise description of what the bug is.]

If you create a new Profile with a namespace that has a ResourceQuota attached to it when the namespace is created and is populated with ml-pipeline-ui-artifact and ml-pipeline-visulisationserver replicasets are stuck in Error because they fail quota checks befcause they don't specify cpu/memory

### What happened:

ml-pipeline-ui-artifact and ml-pipeline-visulisationserver replicasets are stuck

### What did you expect to happen:
ml-pipeline-ui-artifact and ml-pipeline-visulisationserver replicasets to be provisioned correctly on profile creation

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

through kf manifests

KFP version: 

1.0.0

KFP SDK version: 

N/A

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by Bobgy** [comment]
You can customize the https://github.com/kubeflow/manifests/blob/master/pipeline/installs/multi-user/pipelines-profile-controller/sync.py to decide what additional configs you want with these deployments.
