### ISSUE TITLE
Missing rate limiting

### ISSUE THREAD

**Issue by Jalmeida1994** [kubeflow/pipelines#4579]
### What steps did you take:
I used CodeQL scanning action to test the tool and found some security issues, don't know if somebody cares.

### What happened:
```
HTTP request handlers should not perform expensive operations such as accessing the file system, executing an operating system command or interacting with a database without limiting the rate at which requests are accepted. Otherwise, the application becomes vulnerable to denial-of-service attacks where an attacker can cause the application to crash or become unresponsive by issuing a large number of requests at the same time. 
A rate-limiting middleware should be used to prevent such attacks. (CodeQL)
``` 

`frontend/mock-backend/mock-api-middleware.ts - line 590 - app.get('/k8s/pod/logs', (req, res) => {`
_This route handler performs a file system access , but is not rate-limited._

/kind bug
/area frontend

**Comment by Jalmeida1994** [comment]
I'm sorry it's my first issue, I was just testing the Code Scanning tool and saw this vulnerability. I thought somebody should know.

**Comment by Ark-kun** [comment]
I think the issue it has discovered is in the frontend test code - in the mock backend.

**Comment by Bobgy** [comment]
Right, that's only used for local development, so not a risk.
