### ISSUE TITLE
Docs: Update base_image wording for create_component_from_func

### ISSUE THREAD

**Issue by joeliedtke** [kubeflow/pipelines#4589]
The SDK docs for create_component_from_func specify the following:

base_image – Optional. Specify a custom Docker container image to use in the component. For lightweight components, the image needs to have python 3.5+. Default is the python image corresponding to the current python environment.

I think that the phrase "current Python environment" is confusing. From the reader's perspective, I think it is reasonable to interpret this as "the Python environment that the code runs in". However, its been pointed out to me that this refers to a [default Python environment variable](https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/components/_python_op.py#L96).

Would it be possible to update the SDK docs to indicate that the default base image relies on that variable? Or, to indicate what the current Python version is. This affects create_component_from_func and similar functions. 

/kind bug
/area sdk

**Comment by Ark-kun** [comment]
This is indeed an issue.
I have a plan to make the default image version the same as the current running python version, but it's not finished yet.
So, the documentation here is "ahead of its time".
I'll either fix the documentation (to say that the default is python:3.7) or implement the image selection based on the current python environment.
