### ISSUE TITLE
Access Pipeline Steps via SDK (mainly to get the logs, maybe also for outputs)

### ISSUE THREAD

**Issue by thomas-mueller** [kubeflow/pipelines#4591]
Is there a way to access pipeline steps via the kubeflow pipelines SDK? The main reason for my question is that I am looking for a way to access logs (for debugging) in case the Kubeflow Central Dashboard only shows No graph to show when clicking on a run of an experiment. I find experiments/runs via the SDK, but it looks like there is no way further to get to the steps of the pipeline.

**Comment by Ark-kun** [comment]
You can check
```
argo list
```
or 
```
kubectl get workflows --namespace kubeflow
```

**Comment by Bobgy** [comment]
Or you can use kfp sdk to get argo status like in https://github.com/kubeflow/pipelines/issues/4327#issuecomment-687255001 and parse the argo workflow status

**Comment by Bobgy** [comment]
In the longer term, we want to provide a status representation that's native to KFP, but it will take some time

**Comment by thomas-mueller** [comment]
Thanks! I think this is more or less what I was looking for.
