### ISSUE TITLE
[Question] Can containerized pipeline components use languages other than Python?

### ISSUE THREAD

**Issue by luisquintanilla** [kubeflow/pipelines#4599]
I'm taking a look at this guide and one thing that's not clear to me is, if I'm containerizing my application, I should be able to use any languages/dependencies. Therefore, can I use something like C#/Julia/R?

https://www.kubeflow.org/docs/pipelines/sdk/component-development/#writing-a-dockerfile-to-containerize-your-application

**Comment by Ark-kun** [comment]
Yes. KFP orchestrates containerized command-line programs (written in any language).

In fact many components in this repo are written using non-python binaries and even shell scripts.
Components are `ComponentSpec` objects that can be serialized to `component.yaml` files for sharing and then loaded in any pipeline.

Check this simple component for example: https://github.com/kubeflow/pipelines/blob/55ef28a9d51edc4eeed2a5c6f44cc7457e8a41d8/components/json/Get_element_by_index/component.yaml

The reason that most components use python is that most ML libraries are written for python, the SDK is written in python.
Also scripting languages like python make it possible to release components without building new container images which significantly reduces licensing headaches associated with releasing binaries and images.

>Therefore, can I use something like C#/Julia/R?

Yes. It would be great to get some samples showcasing C#, R and Julia.

**Comment by luisquintanilla** [comment]
Perfect! That's what I figured but it wasn't clear on the docs page. Thanks for that detailed response @Ark-kun . Follow-up questions:

1. Although the component definition and container image contents can be in any language, the orchestration still has to happen with the Python SDK. Is that right?
2. Where is the docs repo so that I can make this distinction for users who may have a similar question?

Thanks again.

**Comment by luisquintanilla** [comment]
I take it this is the website/docs repo? https://github.com/kubeflow/website

**Comment by Ark-kun** [comment]
>the orchestration still has to happen with the Python SDK. Is that right?

The SDK compiles the whole pipeline to another orchestrator-specific YAML format and sends it to the backend for the execution. Currently we use the open-source Argo orchestrator which is written in Go.

>I take it this is the website/docs repo? https://github.com/kubeflow/website

This is correct. The Pipelines project documentation is hosted within the kubeflow.org website. The KF and KFP projects themselves are somewhat standalone though (although KF commonly deploys KFP).

**Comment by luisquintanilla** [comment]
Thanks! :)

**Comment by Bobgy** [comment]
Looks like question answered
