### ISSUE TITLE
Enrich samples list with AWS examples

### ISSUE THREAD

**Issue by adollar** [kubeflow/pipelines#4600]
While working with kubeflow pipelines I've noticed a short list of samples. 
https://github.com/kubeflow/pipelines/blob/master/backend/src/apiserver/config/sample_config.json

It would be great to extend the existing samples list with some widely used clouds. I propose to enrich existing list with a few new examples for kubeflow pipelines in AWS cloud from here: 
https://github.com/kubeflow/pipelines/tree/master/samples/contrib/aws-samples

**Comment by Bobgy** [comment]
/assign @PatrickXYS 
I'd suggest running those samples via KFP SDK.
The cost for maintaining KFP builtin samples is high and we cannot put sth without test coverage there.

**Comment by tidylobster** [comment]
Can we add tests for AWS samples as well?

**Comment by Bobgy** [comment]
I believe we can do that when aws test infra is built.
@PatrickXYS

**Comment by PatrickXYS** [comment]
> I believe we can do that when aws test infra is built.

That's correct
