### ISSUE TITLE
SDK reference doc shows master branch content

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#4616]
A different problem is, how can we ensure the docs correspond to latest released SDK, instead of master branch? We shouldn't incorrectly let people find unreleased features.

_Originally posted by @Bobgy in https://github.com/kubeflow/pipelines/issues/4409#issuecomment-700609878_

/assign @ark-kun

**Comment by Bobgy** [comment]
e.g. https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.server_api.html#kfp_server_api.api.pipeline_upload_service_api.PipelineUploadServiceApi.upload_pipeline_version
this hasn't been released yet

**Comment by Bobgy** [comment]
I'd prefer configuring readthedocs to allow choosing each previous released versions, so that users with old sdks can also use it as a reference.

**Comment by Bobgy** [comment]
also
/assign @numerology @chensun

**Comment by Ark-kun** [comment]
> Maybe not doing this right now, we can start by releasing docs for 1.0.0 and 1.0.3 at the same time

Do we really need separate documentation for both 1.0.0 and 1.0.3? Maybe the `release-1.0` branch? The `stable` docs point to 1.0.3 BTW.

**Comment by Bobgy** [comment]
Good point! I guess that's not necessary.
A version for each release branch sounds reasonable.

> The stable docs point to 1.0.3 BTW.

Great! Is it possible changing stable docs as the default for readthedocs?

**Comment by Ark-kun** [comment]
> Great! Is it possible changing stable docs as the default for readthedocs?

Done.
BTW, check the version switch in the lower left corner.

**Comment by Ark-kun** [comment]
Switched the default docs version to "stable" which corresponds to the latest release tag. Currently that's 1.0.3

**Comment by Bobgy** [comment]
@Ark-kun Thank you! Looks great!

Can you inform me how we can configure this? Can we include it in some README.md in this repo, so others know what to do next time?

**Comment by Ark-kun** [comment]
> e.g. https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.server_api.html#kfp_server_api.api.pipeline_upload_service_api.PipelineUploadServiceApi.upload_pipeline_version
> this hasn't been released yet

Hmm. That method seems to be available even in 1.0.0:
https://github.com/kubeflow/pipelines/blob/1.0.0/backend/api/python_http_client/kfp_server_api/api/pipeline_upload_service_api.py#L193

**Comment by Ark-kun** [comment]
>Can you inform me how we can configure this?

You need to log in to the RTFD website using the kubeflow-pipelines account using the credentials from the internal Google key store. Then you can activate arbitrary branches and change which is the default one.
