### ISSUE TITLE
[Documentation] Pipelines quickstart page outdated

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#4617]
https://www.kubeflow.org/docs/pipelines/pipelines-quickstart/

A few problems:
1. KFP should be stable instead of beta now.
2. Listed pipeline samples no longer exist, we should use data passing pipeline as the first sample and adjust xgboost sample's name.
3. The quickstart page does take multiple KFP installation methods into consideration.

/assign @joeliedtke

**Comment by Bobgy** [comment]
I think we should address 1. first

**Comment by NikeNano** [comment]
I will take a look at this.
