### ISSUE TITLE
Add s3fs dependency for visualization server

### ISSUE THREAD

**Issue by tidylobster** [kubeflow/pipelines#4618]
Hi!
At the moment there's a possibility to create custom visualizations using Visualization Creator from the UI. All you need to do is to select the type of visualization you want, specify a source file with the data and optional arguments. The source file must be placed on GCS beforehand. Looking into the [code](https://github.com/kubeflow/pipelines/blob/335323353fc7bf50d0573b82b49fdd24e0e6188a/backend/src/apiserver/visualization/types/table.py#L40) we can see that the source file is retrieved using the `read_csv` frunction from the pandas library. This function allows to fetch files from multiple sources according to [documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html). 

> Any valid string path is acceptable. The string could be a URL. Valid URL schemes include http, ftp, s3, gs, and file. For file URLs, a host is expected. A local file could be: file://localhost/path/to/table.csv.

But the problem is that we need s3fs dependency to retrieve files from S3. I'll provide with the example below. 

1. Using Table visualizaion on the plain setup with S3 source produces the following error.

![image](https://user-images.githubusercontent.com/7824882/95718967-dc347900-0c77-11eb-8fc1-b678a14acc7e.png)

2. Executing manual s3fs installation within the visualizations container (`pip install s3fs`) resolves the issues. 

![image (1)](https://user-images.githubusercontent.com/7824882/95719051-f706ed80-0c77-11eb-8f15-a08114a770a8.png)

I purpose to add this dependency to the visualization service and to change the placeholder on the source field in the UI accodingly.

**Comment by Bobgy** [comment]
I'd rather suggest using script like https://github.com/kubeflow/pipelines/issues/4327#issuecomment-687255001 to download the dataset you want and use your own jupyter notebook for visualization.

So far we've found visualization server's package management isn't really sth that can scale, visualization server will be deprecated in the future.
