### ISSUE TITLE
sample(contrib/e2e-mnist): header rule not supported by RBAC network filter

### ISSUE THREAD

**Issue by majorinche** [kubeflow/pipelines#4620]
kubeflow version: kfctl_k8s_istio.v1.1.0
istio versino:1.3.1 (installed along with kubeflow)
kubernetes version: 1.17.9 (installed in bare metal)

we try to test an example from: https://github.com/kubeflow/pipelines/tree/master/samples/contrib/e2e-mnist
this example pipeline has mainly three steps, including katib, train and inference

the pipeline has already finished "katib" process, but just stuck at "train" step
no error found in tensorflow container, but some errors exists in istio-proxy container logs:
[2020-10-12 08:07:53.117][24][warning][config] [external/envoy/source/common/config/grpc_mux_subscription_impl.cc:81] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) 10.233.92.135_2222: Found header(name: "kubeflow-userid"
exact_match: "anonymous@kubeflow.org"
) rule,not supported by RBAC network filter, virtualInbound: Found header(name: "kubeflow-userid"
exact_match: "anonymous@kubeflow.org"
) rule,not supported by RBAC network filter

so what is a possible problem about this?

thank you

**Comment by Bobgy** [comment]
@hougangliu Can you help for the sample you contributed?
