### ISSUE TITLE
[Cache Deployer] crashloopbackoff in Kubernetes 1.17

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#4627]
This is blocking KFP 1.0.3 release on GCP marketplace.
https://github.com/kubeflow/pipelines/issues/4540

### What steps did you take:
[A clear and concise description of what the bug is.]
1. Go to https://console.cloud.google.com/marketplace/details/google-cloud-ai-platform/kubeflow-pipelines (in fact, the test solution that's on 1.0.3)
2. Create cluster there (it will use regular channel and get 1.17)
3. Deploy KFP

### What happened:
cache deployer keeps crashing

+ kubectl apply -f ./cache-configmap-ca-bundle.yaml --namespace default
error: error validating "./cache-configmap-ca-bundle.yaml": error validating data: [ValidationError(MutatingWebhookConfiguration.webhooks[0]): missing required field "sideEffects" in io.k8s.api.admissionregistration.v1.MutatingWebhook, ValidationError(MutatingWebhookConfiguration.webhooks[0]): missing required field "admissionReviewVersions" in io.k8s.api.admissionregistration.v1.MutatingWebhook]; if you choose to ignore these errors, turn validation off with --validate=false
Error

### What did you expect to happen:
cache deployer should succeed

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

AI Platform Pipelines test solution with 1.0.3

KFP version: 
1.0.3

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by Bobgy** [comment]
I'm updating presubmit tests to regular channel to showcase the problem: https://github.com/kubeflow/pipelines/pull/4626

**Comment by Ark-kun** [comment]
> 2\. Create cluster there (it will use regular channel and get 1.17)

This is a bit strange. When I try to create a cluster it uses the Stable channel by default and shows the 1.16.13 version as default.

**Comment by Bobgy** [comment]
@Ark-kun I think the default version for creating a cluster from MKP is different from GKE UI.
MKP auto creates regular channel from my experimentation.
