### ISSUE TITLE
ComponentStore auth not available

### ISSUE THREAD

**Issue by jackwhelpton** [kubeflow/pipelines#4642]
### What steps did you take:
Attempted to use the ComponentStore's `auth` property, available in the master branch since Jun 17, 2020 (long before the most recent SDK release):

```python
    components = ComponentStore(
        url_search_prefixes=[...],
        auth={...},
    )
```

### What happened:
```Unexpected keyword argument 'auth' in constructor callpylint(unexpected-keyword-arg)```

### What did you expect to happen:
Code to compile.

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

KFP version: 
1.0.1

KFP SDK version: 
kfp                            1.0.3
kfp-server-api                 1.0.3

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by jackwhelpton** [comment]
Is there a scheduled SDK version where these changes will land? I guess releases aren't being made from `master`?

> Bobgy released this 7 days ago · 331 commits to master since this release

**Comment by munagekar** [comment]
This changes haven't been released yet. You can refer to to this [tag](https://github.com/kubeflow/pipelines/tree/1.0.3) for the latest release.

**Comment by jackwhelpton** [comment]
Thanks. Given that these changes were made back in June, and the most recent release was a few days ago, is there a rough ETA for when they might make it out? It'd be very helpful to be able to pull shared components from a secured private repo.

**Comment by munagekar** [comment]
Hope this helps. 

```python
    host = "https://raw.githubusercontent.com"
    org = <org>
    repo = <repo>

    repo_url = f"{host}/{org}/{repo}"
    tag = <tag>
    path = <path>

    component_url = f"{repo_url}/{tag}/{path}"
    token = os.getenv("GITHUB_TOKEN")
    response = requests.get(component_url, headers={"Authorization": f"token {token}"})

    if response.status_code != 200:
        raise RuntimeError(f"Failed to Load.{response.content.decode()}")

    return kfp.components.load_component_from_text(response.content)
```

**Comment by jackwhelpton** [comment]
Ah ha! I forgot about `load_component_from_text`. It's not as neat, but that'll do the trick until the `ComponentStore` stuff lands. Thanks! I'd still be curious where it is on the roadmap, though.

**Comment by Bobgy** [comment]
We plan to do a 1.1.0-alpha.1 release quickly, but it won't have any stability guarantee: https://github.com/kubeflow/pipelines/issues/4565

**Comment by Ark-kun** [comment]
Root cause: https://github.com/kubeflow/pipelines/issues/4409

**Comment by Bobgy** [comment]
Let's move the discussion to releasing KFP 1.1.0: https://github.com/kubeflow/pipelines/issues/4565
