### ISSUE TITLE
Deprecate python based visualization

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#4643]
Some problems we are facing with python based visualization (https://www.kubeflow.org/docs/pipelines/sdk/python-based-visualizations/):
* dependency management
    * we can only maintain one version of the python packages and it's a big cost syncing with external packages like tfx
    * we cannot expose ways to let users install their own dependencies or upgrade dependencies
* editor support
    * we do not want to reimplement editor features like saving code etc in KFP UI
    * we cannot support autocompletion etc

Therefore, I'd want to deprecate python based visualization. I recommend fetching data via Kubeflow Pipelines SDK and visualizing from your own notebook instead, which gives you full control over your visualization process.

If you want some visualization to show for every run, you can run a component as part of your pipeline, the component should run the python visualization and expose HTML content of the visualization via https://www.kubeflow.org/docs/pipelines/sdk/output-viewer/#web-app.

**Comment by rmgogogo** [comment]
+1

**Comment by Bobgy** [comment]
What this implies is that, the TFDV/TFMA auto visualizations should be components in the golden tfx pipeline sample.

**Comment by rmgogogo** [comment]
> What this implies is that, the TFDV/TFMA auto visualizations should be components in the golden tfx pipeline sample.

I personally OK with it, especially considering current e2e experiences.
@IronPan @james-jwu for review.

**Comment by Bobgy** [comment]
Blocker is to build a new way to visualize for tfx pipelines in #3970

**Comment by rimolive** [comment]
Closing this issue. #3970 is closed.

/close
