### ISSUE TITLE
Use source from minio in the Visualization creator (type custom)

### ISSUE THREAD

**Issue by gilbeckers** [kubeflow/pipelines#4659]
I would like to know how one can load data over minio as a `Source` in the visualization creator using the custom type:

![Screenshot from 2020-10-22 16-16-53](https://user-images.githubusercontent.com/29519238/96884848-44f2d100-1482-11eb-9067-4ae4befd5fa9.png)

I cannot not find anything in the documentation and an error is printed saying that `File system scheme 'minio' is not implemented` when providing a minio resource as input for the `source` field. As a result I'm afraid that this is currently not possible?
If the answer to the previous question is yes, is true that only gs is supported currently?

**Comment by Bobgy** [comment]
In fact we plan to deprecate python based visualization https://github.com/kubeflow/pipelines/issues/4643

Recommend downloading artifacts and use your own notebook

**Comment by gilbeckers** [comment]
Thanks for the answer @Bobgy . And what about TFDV? Can we load data over minio there?

**Comment by Bobgy** [comment]
I think it doesn't support that, but please refer to tfdv's official documentation
