### ISSUE TITLE
Attach generic metadata to recurring run (and all other) objects

### ISSUE THREAD

**Issue by alexlatchford** [kubeflow/pipelines#4665]
Hi all, we have a use case where we're using a configuration driven approach to drive the creation of many recurring run schedules. We have a directory of configuration files where each one corresponds to an experiment and on a schedule we re-trigger the pipeline using the configuration values as pipeline parameters. This approach works great and allows us to train many models using different hyperparameters on different pipelines.

One problem we have though is that when we remove a configuration file we want our CICD to be able to remove the corresponding recurring run schedule. To do this we need to identify which recurring run schedules are managed by this process, we're currently overloading the `description` field to do this as there is no equivalent to the `labels` or `annotations` fields for KFP native objects (ie. experiments, runs, recurring run job/tasks etc.).

Being able to attach arbitrary key/value pair metadata has been super useful in K8s and I could see the benefits to this for KFP objects too. Apologies if I missed a way to already do this, I searched the existing SDK & API docs and didn't find a solution like this.

**Comment by Bobgy** [comment]
Thanks @alexlatchford for writing up the detailed use-cases!
We've received similar requests before for different KFP resources in #4165 #4193 #4194.

I think your description is very generic, we can use this issue as the root tracker for similar requests.

I'd 100% agree and support this use-case. Right now, we don't have bandwidth to tackle this by ourselves. We are waiting for any community contributor who's willing to take over the design and drive it forward. I'll support any feature discussion, PR review and approvals.

**Comment by alexlatchford** [comment]
Thanks for clarifying @Bobgy seems unlikely we'd get the time allocated to contribute this at Zillow unfortunately given we have a somewhat working solution but thanks for the response. I'll keep tabs on the ticket and hopefully I can help out with reviewing/testing at least!
