### ISSUE TITLE
403 Forbidden on any update operations on all platforms all of a sudden

### ISSUE THREAD

**Issue by omarzouk** [kubeflow/pipelines#4667]
### What steps did you take:
We have been using Google Cloudbuild as a CI to upload our pipelines to KFP for the past ~6 months without issue. Suddenly today, jobs started failing.
The SDK fails to call the upload pipeline endpoint, getting a 403 error. The SDK however is able to access all read APIs, but no longer able to access update APIs.
Also, I have tried using the api manually, on my local machine and on a collaboratory notebook, I was able to access the read APIs but not the update APIs. I had actually just used the notebook to delete an experiment 2 days ago. I was authenticated with my personal user which is somehow still able to create and edit and delete from the KFP UI just fine, but not from the SDK.

This issue started happening on both our staging AND production environments.

This is the error we started seeing:
```
  File "/usr/local/lib/python3.7/dist-packages/kfp_server_api/api/pipeline_upload_service_api.py", line 157, in upload_pipeline_version
    (data) = self.upload_pipeline_version_with_http_info(uploadfile, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.7/dist-packages/kfp_server_api/api/pipeline_upload_service_api.py", line 240, in upload_pipeline_version_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.7/dist-packages/kfp_server_api/api_client.py", line 330, in call_api
    _preload_content, _request_timeout)
  File "/usr/local/lib/python3.7/dist-packages/kfp_server_api/api_client.py", line 161, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.7/dist-packages/kfp_server_api/api_client.py", line 373, in request
    body=body)
  File "/usr/local/lib/python3.7/dist-packages/kfp_server_api/rest.py", line 275, in POST
    body=body)
  File "/usr/local/lib/python3.7/dist-packages/kfp_server_api/rest.py", line 228, in request
    raise ApiException(http_resp=r)
kfp_server_api.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Content-Length': '1449', 'Content-Type': 'text/html; charset=utf-8', 'Date': 'Fri, 23 Oct 2020 18:13:24 GMT', 'Vary': 'Origin', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '0', 'Set-Cookie': 'S=cloud_datalab_tunnel=fYwb9VQdvhIhZOY9bF-bQHAniDdvJA-ccYOg4W4Avzs; Path=/; Max-Age=3600'})
HTTP response body: 
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 403 (Forbidden)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/logos/errorpage/error_logo-150x54.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/logos/errorpage/error_logo-150x54-2x.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/logos/errorpage/error_logo-150x54-2x.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/logos/errorpage/error_logo-150x54-2x.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>403.</b> <ins>That’s an error.</ins>
  <p>  <ins>That’s all we know.</ins>
```

### What happened:
Calling the api fails
### What did you expect to happen:
Calling the api to continue to work
### Environment:
Google Cloud, us-central2

How did you deploy Kubeflow Pipelines (KFP)?
KFP version: Marketplace, version 0.2.5

KFP SDK version:
kfp                           0.4.0          
kfp-server-api                0.3.0  

I have also tested newer versions, same result:
kfp                           1.0.4          
kfp-server-api                1.0.4

/kind bug
/area sdk

**Comment by omarzouk** [comment]
Looking at a previous similar issue, something similar has affected us-central1/2 beforehand: https://github.com/kubeflow/pipelines/issues/3688

**Comment by chensun** [comment]
There was a bad release with Inverse proxy, which was rolled back. Verified the error is gone now.

**Comment by Bobgy** [comment]
Reopening this issue to track efforts preventing it from happening again.

**Comment by Bobgy** [comment]
Update, some monitoring and pre release coordination were added.

**Comment by AiDataSciencer** [comment]
The problem Idescribed in my previous comment has been resolved now. We created a service account and are using it for authentification.

Unfortunately we don't understand, why this fixed the initial problem, since using the gcloud auth worked for quite a while and sudenly stopped working for the kfp SDK even though we could still use the storage SDK to transfer data from local machines to google storage buckets. The problem has only arisen for kfp operations. So there is probably still some authentification issue with kfp SDK.

Has anayone an explanation or at least an idea?

**Comment by Bobgy** [comment]
@AiDataSciencer do you think it's a duplicate of https://github.com/kubeflow/pipelines/issues/5230?

**Comment by AiDataSciencer** [comment]
It is indeed. It solved the problem for me. Thanks for refering to #5230.

**Comment by omarzouk** [comment]
Hi, this has happened again, getting 403s again in `us-central1`

**Comment by Bobgy** [comment]
Hi @omarzouk, did you check https://github.com/kubeflow/pipelines/issues/5230?
That's latest issue to track this.

**Comment by omarzouk** [comment]
@Bobgy that worked, thanks a lot!
