### ISSUE TITLE
Support the versioning of artifacts and/or pipelines. 

### ISSUE THREAD

**Issue by yebrahim** [kubeflow/pipelines#467]
This is a high level work item to track work needed to support pipeline versioning, including what links versions together, identifying a version when creating runs, comparing versions.. etc.

**Comment by vicaire** [comment]
Riley or Pavel, do you are more details on this one? I am not exactly sure of what the scope would be. 

Is it about versions of the pipeline system? 

Or is it about versioned pipelines?

**Comment by rileyjbauer** [comment]
This is about versioned pipelines, not the system itself.

Yes, this should not be frontend specific.

**Comment by vicaire** [comment]
Thanks @rileyjbauer. I am going to repurpose this issue to track the versioning of artifacts.

**Comment by JohnPaton** [comment]
I'm just checking out Pipelines at the moment but it's looking great, thanks for your work on it!

With the current UI, it doesn't seem there is any way to edit or upload a new version of a pipeline. Considering this, how do you test your pipelines? 

As an example, I had a typo in the URI for a container in my pipeline, and fixing that one typo required deleting and re-uploading the whole thing. Is that the current workflow, and is it the plan to add some flexibility here? 

"Upload a new version" or "edit the config in the browser" would be some nice features to have :)

**Comment by vicaire** [comment]
@JohnPaton, yes, at the moment, modifying a pipeline requires uploading/executing a new pipeline.

**Comment by jomach** [comment]
What about implementing a git clone from a url additionally to import from file ?

**Comment by Bobgy** [comment]
The support of pipeline versions was already added in
* https://github.com/kubeflow/pipelines/pull/1873
* https://github.com/kubeflow/pipelines/pull/2338
* https://github.com/kubeflow/pipelines/pull/2445
* https://github.com/kubeflow/pipelines/pull/2611
* https://github.com/kubeflow/pipelines/pull/2620
* https://github.com/kubeflow/pipelines/pull/2648
* https://github.com/kubeflow/pipelines/pull/2667

/close
