### ISSUE TITLE
A large number of Pipeline runs seems to overwhelm the UI

### ISSUE THREAD

**Issue by sm-hawkfish** [kubeflow/pipelines#4671]
### What steps did you take:

As the number of pipeline runs we have submitted has increased over the past weeks, we recently ran into an issue where the UI has either crashed or become unresponsive

### What happened:

1. We see that Experiments page is not able to load the Pipeline Runs, due to hitting a GRPC limit:

<img width="1391" alt="Screen Shot 2020-10-24 at 5 36 21 PM" src="https://user-images.githubusercontent.com/58445518/97094108-bae06f00-161f-11eb-920b-0645e166dd7d.png">

2. We see that individual pipeline runs are not able to display the component graph, and inspecting the page shows that a series of network calls run in a loop forever:

<img width="1391" alt="Screen Shot 2020-10-24 at 5 39 59 PM" src="https://user-images.githubusercontent.com/58445518/97094127-f4b17580-161f-11eb-9a41-d14d3cbb8b19.png">

### What did you expect to happen:

That the UI is able to scale to large numbers of runs, by fetching the data incrementally.

### Environment:

How did you deploy Kubeflow Pipelines (KFP)? GCP Marketplace

KFP version: 1.0.0

/kind bug

/area frontend

In addition to exploring longer-term fixes, I wonder whether you can advise on some short term workarounds like e.g. how to cleanup old runs to reduce the size of the network requests?

**Comment by sm-hawkfish** [comment]
An important piece of context I neglected to share above -- this issue does not affect _the entire KFP UI_, only certain experiments (with a large number of runs). Additionally, those runs generate some HTML files as artifacts that are rendered by the MLPipeline UI Metadata viewer.

**Comment by Bobgy** [comment]
1. Can you help me identify which API call reached limit?
2. I think it's a bug fixed in 1.0.4, when workflow size is big, Argo compresses status field, so KFP UI could not retrieve details.

**Comment by Bobgy** [comment]
1. Might have been fixed too, because I remember seeing PRs to increase the limit. Not sure which release it went into, might need a 1.1.0 release
