### ISSUE TITLE
VolumeSnapshotOp: api_version as a parameter

### ISSUE THREAD

**Issue by dav009** [kubeflow/pipelines#4674]
👋  I am playing with kubeflow on AKS.
For creating snapshots I need to pass `api_version : "snapshot.storage.k8s.io/v1beta1"`.
However  `VolumeSnapshotOp` currently hard coded `snapshot.storage.k8s.io/v1alpha1`.

 I wonder if `api_version` could be a paremeter of `VolumeSnapshotOp` I am happy to make a PR with that change if it makes sense.

**Comment by elikatsis** [comment]
Hi @dav009,
thank you for using the feature.

I think it's a valid use case and, thus, it definitely makes sense!
Feel free to open a PR and CC me :)

/assign @elikatsis

**Comment by DavidSpek** [comment]
I believe this issue can be closed as the related PR was merged.
