### ISSUE TITLE
Show metrics comparison table in Compare view

### ISSUE THREAD

**Issue by yebrahim** [kubeflow/pipelines#468]

**Comment by rileyjbauer** [comment]
@yebrahim this is about showing all metrics, not just the top 2 that are already displayed, correct?

**Comment by yebrahim** [comment]
I can't remember what we have now, but this was initially about showing a table for all metrics of the compared runs, just like the one we have for parameters.

**Comment by marrrcin** [comment]
In 0.5 there are only 2 metrics displayed in Experiment view as well as in the comparison view, which is odd - you cannot view all metrics anywhere.
