### ISSUE TITLE
Question: Job api specifing pipeline version

### ISSUE THREAD

**Issue by dav009** [kubeflow/pipelines#4686]
when creating a job via the kfp client (`client.jobs.create_job`), is it possible to specify a pipeline version?
I am taking a look at https://github.com/kubeflow/pipelines/blob/master/backend/api/python_http_client/docs/ApiPipelineSpec.md
but I cant find any parametr.

**Comment by NikeNano** [comment]
I checked the api:s and I actually don't think it is possible to select the pipeline_version, instead the default_version will be used. You will in future release be able to set the default pipeline version: https://github.com/kubeflow/pipelines/pull/4406 today the latest is selected. 

I might be missing something in the API, if not I think this would be a great contribution to the API.

**Comment by dav009** [comment]
@NikeNano  thanks!

**Comment by Bobgy** [comment]
@dav009 in fact, selecting version is supported, but not very obvious.

You need to add a resource reference that points to a pipeline version.

**Comment by Bobgy** [comment]
Similar to this example https://www.github.com/kubeflow/pipelines/tree/master/tools%2Fbenchmarks%2Frun_service_api.ipynb

**Comment by NikeNano** [comment]
ping @dav009

**Comment by dav009** [comment]
@Bobgy  @NikeNano  thanks!

**Comment by dav009** [comment]
@Bobgy  @NikeNano  sorry guys, reopened this. I am happy to document this somewhere. Where should I look in order to do that github.com/kubeflow/website ? or the docs within the kubeflow/pipelines repo?

**Comment by Bobgy** [comment]
Thanks @dav009 !
www.kubeflow.org will be the best place.
