### ISSUE TITLE
Question: Tasks not getting cached

### ISSUE THREAD

**Issue by dav009** [kubeflow/pipelines#4687]
👋  I am new to Kubeflow, I used kfctl to install kbf. Pipelines work fine, but caching is not working.
Tasks never get skipped.  There is nothing in the logs either:
```
kubectl logs -n kubeflow --selector app=cache-server
2020/10/28 17:13:34 Initing client manager....
2020/10/28 17:13:34 Database created
2020/10/28 17:13:34 execution_caches
```

I made sure that `mutatingwebhookconfiguration ` exists and that is setup as mentioned in https://www.kubeflow.org/docs/pipelines/caching/

**Comment by NikeNano** [comment]
Could you share an example? I know there are several PR:s open related to the caching https://github.com/kubeflow/pipelines/pulls?q=is%3Apr+is%3Aopen+cache, one which is an example https://github.com/kubeflow/pipelines/issues/4049 . Have not used it myself though :(

**Comment by dav009** [comment]
@NikeNano  this is the dummy task I am trying to get cached:

```python
import kfp
from kfp import dsl
from kfp.components import func_to_container_op, InputPath, OutputPath

@func_to_container_op
def calculate_v(n:int) -> str:
    import time
    from datetime import datetime
    print("sleeping...")
    time.sleep(3)
    print("finished sleeping..")
    now = datetime.now()
    current_time = now.strftime("%H:%M:%S")
    print("Current Time =", current_time)
    return "%s_number" % n

@func_to_container_op
def print_op(m: str) -> None:
    print(m)

@dsl.pipeline(
    name="dummy_sample"
)
def sample_pipeline(n):
    op1 = calculate_v(n)
    op1.execution_options.caching_strategy.max_cache_staleness = "P30D"
    print_op(op1.output)


if __name__ == '__main__':
    # Compiling the pipeline
    kfp.compiler.Compiler().compile(sample_pipeline, __file__ + '.yaml')

```

I also tried the sample in the tests of this PR https://github.com/kubeflow/pipelines/pull/4664/files
however the asserts checking that the random values are the same (thus cache was used) fail. It implies cache was not used.

**Comment by JakeTheWise** [comment]
Same. What version of kubeflow pipelines + kubernetes are you running?

I have a cluster running kubernetes 1.17.4. Upgrading from kubeflow <1 to 1.0.4 broke caching, even though it is supposed to work in 1.0.4 (https://github.com/kubeflow/pipelines/pull/4632)

**Comment by dav009** [comment]
kubernetes 1.18.8
kubeflow 1.1.0

**Comment by regorsmitz** [comment]
I'm running into this same issue with:
kubernetes 1.15
kubeflow 1.0.2

**Comment by Bobgy** [comment]
A quick reply is that:
1. The feature was added in Kubeflow 1.1.0, so Kubeflow 1.0.2 doesn't have it.
2. The feature had some bugs and also it wasn't compatible with Kubernetes 1.17+ before KFP 1.0.4 release (KF 1.1 comes with KFP 1.0.0)

So path forward for most of you, is to upgrade to Kubeflow 1.2.0 which will come with KFP 1.0.4.

**Comment by JakeTheWise** [comment]
Thanks Bobgy, good info. I updated my prior comment to clarify that I'm using a kubeflow pipelines standalone deployment (v1.0.4).

**Comment by Bobgy** [comment]
Thanks @JakeTheWise !
Can you fetch logs for several cache- deployments? Were there anything special about it?

**Comment by JakeTheWise** [comment]
Sorry for the delay. I'm no kubernetes expert (I don't manage the cluster or our kubeflow deployment); so I may not have found the right deployment... but I found the following suspicious logs in the `cache-server` (running image gcr.io/ml-pipeline/cache-server:1.0.4). Does this help?

```
2020/11/16 20:55:06 http: TLS handshake error from 192.168.108.64:46728: remote error: tls: bad certificate
```

**Comment by Bobgy** [comment]
@JakeTheWise Yes, that's the symptom. cache-deployer should be deploying the certificate. Did anything go wrong there?

**Comment by Ark-kun** [comment]
Can you please post more cache-server logs? Is there anything successful there?

**Comment by Ark-kun** [comment]
> I also tried the sample in the tests of this PR https://github.com/kubeflow/pipelines/pull/4664/files
> however the asserts checking that the random values are the same (thus cache was used) fail. It implies cache was not used.

That sample test is currently not feasible. Due to DSL compiler limitations, all tasks in the same pipeline have different input and output names leading to cache misses. So the cached executions can only be reused in subsequent runs, not in the same run.

Your test in https://github.com/kubeflow/pipelines/issues/4687#issuecomment-720821255 should be correct. You just take any piepline and run it multiple times and subsequent runs should reuse the cached executions.

**Comment by cah4444** [comment]
on behalf of @JakeTheWise, the logs for cache-server:

```
2020/11/03 21:23:54 Initing client manager....
2020/11/03 21:23:54 Database created
2020/11/03 21:23:54 execution_caches
2020/11/03 21:24:23 http: TLS handshake error from 192.168.136.128:39454: remote error: tls: bad certificate
2020/11/03 21:25:02 http: TLS handshake error from 192.168.136.128:41172: remote error: tls: bad certificate
2020/11/03 21:28:07 http: TLS handshake error from 192.168.136.128:49342: remote error: tls: bad certificate
2020/11/03 21:28:11 http: TLS handshake error from 192.168.136.128:49542: remote error: tls: bad certificate
...
...
...
2020/11/19 20:48:01 http: TLS handshake error from 192.168.16.64:45760: remote error: tls: bad certificate
2020/11/19 20:49:01 http: TLS handshake error from 192.168.16.64:48682: remote error: tls: bad certificate
2020/11/19 20:50:02 http: TLS handshake error from 192.168.16.64:51626: remote error: tls: bad certificate
2020/11/19 20:51:02 http: TLS handshake error from 192.168.16.64:54560: remote error: tls: bad certificate
2020/11/19 20:52:02 http: TLS handshake error from 192.168.16.64:57496: remote error: tls: bad certificate
2020/11/19 20:53:02 http: TLS handshake error from 192.168.16.64:60434: remote error: tls: bad certificate
2020/11/19 20:54:02 http: TLS handshake error from 192.168.16.64:35140: remote error: tls: bad certificate
2020/11/19 20:55:02 http: TLS handshake error from 192.168.16.64:38088: remote error: tls: bad certificate
```

With nothing but those same logs inbetween. The cache-deployer logs are as follows:

```
+ echo 'Start deploying cache service to existing cluster:'
+ NAMESPACE=kubeflow-prd
+ MUTATING_WEBHOOK_CONFIGURATION_NAME=cache-webhook-kubeflow-prd
+ WEBHOOK_SECRET_NAME=webhook-server-tls
+ mkdir -p /root/bin
Start deploying cache service to existing cluster:
+ export 'PATH=/root/bin:/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
+ kubectl version --output json
+ jq --raw-output '(.serverVersion.major + "." + .serverVersion.minor)'
+ tr -d '"+'
+ server_version_major_minor=1.17
+ curl -s https://storage.googleapis.com/kubernetes-release/release/stable-1.17.txt
+ stable_build_version=v1.17.13
+ kubectl_url=https://storage.googleapis.com/kubernetes-release/release/v1.17.13/bin/linux/amd64/kubectl
+ curl -L -o /root/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.17.13/bin/linux/amd64/kubectl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 41.5M  100 41.5M    0     0  59.8M      0 --:--:-- --:--:-- --:--:-- 59.7M
+ chmod +x /root/bin/kubectl
+ kubectl get mutatingwebhookconfigurations cache-webhook-kubeflow-prd --namespace kubeflow-prd --ignore-not-found
+ kubectl get secrets webhook-server-tls --namespace kubeflow-prd --ignore-not-found
+ webhook_config_exists=false
+ grep cache-webhook-kubeflow-prd -w
cache-webhook-kubeflow-prd   2020-08-19T21:12:42Z
+ webhook_config_exists=true
+ webhook_secret_exists=false
+ grep webhook-server-tls -w
webhook-server-tls   Opaque   2      74d
+ webhook_secret_exists=true
+ '[' true '==' true ]
+ '[' true '==' true ]
Webhook config and secret are already installed. Sleeping forever.
+ echo 'Webhook config and secret are already installed. Sleeping forever.'
+ sleep infinity
```

**Comment by Bobgy** [comment]
Could this issue be an duplicate of https://github.com/kubeflow/pipelines/issues/4505?

**Comment by Bobgy** [comment]
What's your kubernetes versions?

**Comment by JakeTheWise** [comment]
I believe is 1.17.9

**Comment by cah4444** [comment]
> I believe is 1.17.9

Its actually 1.17.4

**Comment by Bobgy** [comment]
Here's code for cache-deployer: https://github.com/kubeflow/pipelines/blob/master/backend/src/cache/deployer/deploy-cache-service.sh
and the most important k8s resources it manages are
https://github.com/kubeflow/pipelines/blob/9a20fc5137578df511645a2192a1908683184ab8/backend/src/cache/deployer/deploy-cache-service.sh#L47-L48

Can you try `kubectl get -oyaml` and `kubectl describe` on them and see if there's any sign of error in status and events?

**Comment by DavidSpek** [comment]
@Bobgy If this is related to https://github.com/kubeflow/pipelines/issues/4505, I don't think it is limited to recent kubernetes versions. When looking at the instructions [here](https://kubernetes.io/docs/concepts/cluster-administration/certificates/#easyrsa), it looks like the `ca.key` file is not deployed to the controller manager. If it indeed is not standard procedure to copy the ca.key to the controller manager, then this problem could be widespread. Here is the link to the docs regarding the certificate signer: https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/#a-note-to-cluster-administrators.

**Comment by cah4444** [comment]
I figured out the problem. When i deleted the kubeflow pipelines deployment to recreate is from scratch following [This](https://github.com/kubeflow/pipelines/tree/master/manifests/kustomize#uninstall), it left behind the mutatingwebhookconfiguration for the namespace (I wasn't aware that it was a cluster-wide resource). Manually deleting that before reinstalling fixed the cache server issue. 

I imagine it had been left from when i had done the kfp uninstall/reinstall before, and had mismatch between TLS certs. Not certain of this, however.

Also, i saw no events or errors in status messages on either of the two resources.

Thank you for all of your help!
