### ISSUE TITLE
ListRuns must filter by resource reference in multi-user mode.

### ISSUE THREAD

**Issue by kd303** [kubeflow/pipelines#4690]
### What steps did you take:
Installed Kubeflow 1.1 with istio with no authentication/authorizaton

### What happened:
Intermittently we are getting ```ListRuns must filter by resource reference in multi-user mode.``` exception with following exception stack trace and it gives ```RBAC``` error. This is on-premise installation non-GPU kubernetes cluster

We also get the similar behaviour when we call /upload endpoint, however it is not specific to upload only, the error is on the UI only

### What did you expect to happen:
I should not be seeing this particular error
### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

Installed using Installed using - https://github.com/kubeflow/kfctl/releases/tag/v1.1.0 
KFP version: 
1.1
KFP SDK version: 
NA

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

// /area backend

**stack trace***

```
1029 13:31:01.839685 6 error.go:218] Invalid input error: ListRuns must filter by resource reference in multi-user mode.

 github.com/kubeflow/pipelines/backend/src/common/util.NewInvalidInputError

 backend/src/common/util/error.go:165

 github.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).ListRuns

 backend/src/apiserver/server/run_server.go:78

 github.com/kubeflow/pipelines/backend/api/go_client._RunService_ListRuns_Handler.func1

 bazel-out/k8-opt/bin/backend/api/linux_amd64_stripped/go_client_go_proto%/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:1313

 main.apiServerInterceptor

 backend/src/apiserver/interceptor.go:30

 github.com/kubeflow/pipelines/backend/api/go_client._RunService_ListRuns_Handler

 bazel-out/k8-opt/bin/backend/api/linux_amd64_stripped/go_client_go_proto%/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:1315

 google.golang.org/grpc.(*Server).processUnaryRPC

 external/org_golang_google_grpc/server.go:966

 google.golang.org/grpc.(*Server).handleStream

 external/org_golang_google_grpc/server.go:1245

 google.golang.org/grpc.(*Server).serveStreams.func1.1

 external/org_golang_google_grpc/server.go:685

 runtime.goexit

 GOROOT/src/runtime/asm_amd64.s:1333

 /api.RunService/ListRuns call failed

 github.com/kubeflow/pipelines/backend/src/common/util.(*UserError).wrapf

 backend/src/common/util/error.go:206

 github.com/kubeflow/pipelines/backend/src/common/util.Wrapf

 backend/src/common/util/error.go:231

 main.apiServerInterceptor

 backend/src/apiserver/interceptor.go:32

 github.com/kubeflow/pipelines/backend/api/go_client._RunService_ListRuns_Handler

 bazel-out/k8-opt/bin/backend/api/linux_amd64_stripped/go_client_go_proto%/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:1315

 google.golang.org/grpc.(*Server).processUnaryRPC

 external/org_golang_google_grpc/server.go:966

 google.golang.org/grpc.(*Server).handleStream

 external/org_golang_google_grpc/server.go:1245

 google.golang.org/grpc.(*Server).serveStreams.func1.1

 external/org_golang_google_grpc/server.go:685

 runtime.goexit

 GOROOT/src/runtime/asm_amd64.s:1333

```

**Comment by Bobgy** [comment]
@kd303 thank you for the report!

The error usually shows when you didn't select namespace. In multi user mode, namespace must be selected to do anything.

Can you confirm if that's the case?

I didn't see anything about rbac error in your description, can you clarify?

**Comment by kd303** [comment]
@Bobgy Namespace is selected by default. Also to notice I have two installations of kubeflow 1.1 one with Dex and one without Dex, the RBAC error is intermittent on non-Dex environment. Also I am not even sure how is this re-producible. But this is error only comes on pipeline screen and no other. Just randomly clicking on the pipeline screen this error appears (any function, list runs, experiments, pipelines etc).

**Comment by Bobgy** [comment]
@kd303 Can you give an UI screenshot when this can be visible?
Or is it just backend getting these errors?

**Comment by kd303** [comment]
@Bobgy Attached are few screenshots, this time I could reproduce when I was trying to create a screen
[
![ss1](https://user-images.githubusercontent.com/16409185/98226661-5527a780-1f7c-11eb-98fe-92de7a5c84c9.JPG)
]

![ss2](https://user-images.githubusercontent.com/16409185/98226689-5fe23c80-1f7c-11eb-8488-b8676ec3b25f.JPG)

**Comment by Bobgy** [comment]
Note, `RBAC: access denied` is completely an Istio error message.

You might want to debug your istio configuration or update. Or ask kfdef dex manifest maintainer.

This isn't sth we can fix from KFP side.

**Comment by Bobgy** [comment]
Also, the backend error message is expected and completely irrelevant to rbac access denied.

So I think we can close this issue for KFP

**Comment by kd303** [comment]
Thanks for looking into it, its surprising that for Non-Dex installation also this particular issue pops up, will debug.

**Comment by speaknowpotato** [comment]
hi @kd303 , did you get it fixed? i see the same issue as yours and have no idea about it. 
thanks.
