### ISSUE TITLE
"Terminate" does not stop pipeline run execution

### ISSUE THREAD

**Issue by fakeburst** [kubeflow/pipelines#4692]
### What steps did you take:
Hitting "Terminate" fails to actually stop pipeline execution if there are steps with retryStrategies or running init containers

### What happened:
We are running a pipeline that has ±50 parallel step executions. If we want to stop pipeline run we have to delete Kubernetes Workflow resource rather than using "Terminate" UI button as it does not stop the run if:
1. There are steps = containers with `retryStrategy`, as they are restarting instead of being terminated
2. If there are any init containers, the step won't be stopped until they finish and the main one takes over

### What did you expect to happen:
All pipelines steps/pods are terminated the instant user hits "Terminate" with no retries, as if the corresponding Workflow is deleted

How did you deploy Kubeflow Pipelines (KFP)?
Kubeflow Pipelines are installed as a part of Kubeflow project

KFP version: Build commit: 743746b
KFP SDK version: 0.5.1

### Anything else you would like to add:
Please let me know if additional info is required 

/kind bug
/area frontend
/area backend

**Comment by Bobgy** [comment]
Thank you for the report! @fakeburst 
That sounds reasonable.

Welcome contribution on the behavior change you requested.

**Comment by fakeburst** [comment]
@Bobgy Could you possible help me locate the code that handles "Terminate"? I'll have my teammate look into this as he's willing to contribute

**Comment by Bobgy** [comment]
Sure, code is in
https://github.com/kubeflow/pipelines/blob/d6a2c23f56943ea8af35b5b2e5f6c6381bfb25ed/backend/src/apiserver/resource/resource_manager.go#L462

**Comment by parthmishra** [comment]
I think this issue affects steps that are stuck in imagepullbackoff pending state. Terminate doesn't seem to do anything.

**Comment by hsezhiyan** [comment]
@Bobgy I'm still seeing this issue in Kubeflow Pipelines v.1.0.0. The issue is that when I click `Terminate`, the run does not terminate and in the UI, the run is still listed as `Running`. Do you have any updates on what could be the issue?

Unlike fakeburst's situation though, I'm not seeing any init containers or retry strategies in the pod specs, so this may be a deeper issue.

**Comment by Bobgy** [comment]
Hi @hsezhiyan, can you try latest KFP releases? KFP 1.0.0 has been a while and I'm not seeing this problem in latest KFP releases.

**Comment by Bobgy** [comment]
For people coming here, https://github.com/argoproj/argo-workflows/issues/6256 might be another reason terminate does not work (it times out with 524 error)

**Comment by hsezhiyan** [comment]
@Bobgy sure our company is planning to upgrade KFP in the next few weeks, so I'll test it and report back here. Thanks for the response!

**Comment by juliusvonkohout** [comment]
We are experiencing similar issues on Kubeflow 1.3.1rc0

**Comment by axeltidemann** [comment]
I am seeing this in KFP 1.7.0. A recurring run was scheduled, but with a wrong image URL. The step is stuck in:
```This step is in Pending state with this message: ImagePullBackOff: Back-off pulling image```
Terminate does not do anything. The recurring run has been deleted. How can I stop this run?

**Comment by juliusvonkohout** [comment]
> I am seeing this in KFP 1.7.0. A recurring run was scheduled, but with a wrong image URL. The step is stuck in: `This step is in Pending state with this message: ImagePullBackOff: Back-off pulling image` Terminate does not do anything. The recurring run has been deleted. How can I stop this run?

Please try again with kubeflow 1.5rc2

**Comment by axeltidemann** [comment]
@juliusvonkohout are you suggesting I downgrade the Kubeflow cluster, or am I misunderstanding something?

**Comment by juliusvonkohout** [comment]
> @juliusvonkohout are you suggesting I downgrade the Kubeflow cluster, or am I misunderstanding something?

Kfp 1.7 is too old. Kubeflow 1.5rc2 uses pipelines 1.8.1 so you need to test against standalone pipelines 1.8.1 or Kubeflow 1.5rc2

**Comment by axeltidemann** [comment]
Just to be sure I am not mixing things up: this is version 1.7 I am referring to, which is what you see in the Kubeflow UI.

<img width="160" alt="Screenshot 2022-03-09 at 13 31 56" src="https://user-images.githubusercontent.com/6352118/157433821-e88c8e32-b131-4c59-b3a1-11cf2156c450.png">

**Comment by juliusvonkohout** [comment]
> Just to be sure I am not mixing things up: this is version 1.7 I am referring to, which is what you see in the Kubeflow UI.
> 
> <img alt="Screenshot 2022-03-09 at 13 31 56" width="160" src="https://user-images.githubusercontent.com/6352118/157433821-e88c8e32-b131-4c59-b3a1-11cf2156c450.png">
> 
> I guess I should not have referred to it as KFP 1.7, you are thinking of the Python package, perhaps? That is 1.8.0.

No i am not thinking about the python package. It is too old 

https://github.com/kubeflow/pipelines/commit/2a4b60ee2fa1d379959fdd769f56931909a3174a

https://github.com/kubeflow/pipelines/releases/tag/1.8.1 

https://github.com/kubeflow/manifests/commit/cfd9e043fa8d6885432f86bac5ca9cca5c907e8a

**Comment by axeltidemann** [comment]
I think you are misunderstanding - the pipeline is stuck in this step:

```This step is in Pending state with this message: ImagePullBackOff: Back-off pulling image "```

I want to terminate the run (similar to the first poster). I am not launching new pipelines.

**Comment by juliusvonkohout** [comment]
> I think you are misunderstanding - the pipeline is stuck in this step:
> 
> `This step is in Pending state with this message: ImagePullBackOff: Back-off pulling image [...]`
> 
> I want to terminate the run (similar to the first poster). I am not launching new pipelines.

No, you do not understand. If you test against an old version of the KFP no one will care, no matter whether you want to start or terminate pipelines. Uninstall 1.7.0 from your cluster, install 1.8.1 and test whether you can terminate pipelines successfully. Then the maintainers and other contributors might care.

**Comment by juliusvonkohout** [comment]
> 1.8.1. has been installed, but the "Terminate" button is greyed out entirely (both highlighted in red). Any suggestions? ![Screenshot 2022-04-12 at 16 43 22 (3)](https://user-images.githubusercontent.com/6352118/162989136-adfa1bca-6e23-4926-b064-7472e0e77844.png)

yes, you should provide the pipeline to reproduce the issue.

**Comment by axeltidemann** [comment]
The pipeline has since been removed, if I click on pipeline details I get an error message.

![Screenshot 2022-04-13 at 16 09 33](https://user-images.githubusercontent.com/6352118/163199451-506d9eb4-a647-4e20-a757-8acaf274eb3f.png)

The YAML file is there though, would you like me to paste that? 

![Screenshot 2022-04-13 at 16 16 16](https://user-images.githubusercontent.com/6352118/163200879-d2767112-8b4c-4ada-a2b5-161c806c2514.png)

**Comment by juliusvonkohout** [comment]
You just need to provide whatever is needed to reproduce this issue with the LEAST effort. This would be a Minimalistic yaml file. If you are using dangerous insecure stuff as for example root containers  or the docker instead of the emissary executor I will not be able to help you at all. Because in our enterprise environments such stuff is strictly forbidden. In this case you need to ask other people for help.

**Comment by juliusvonkohout** [comment]
It does seem to work with my own simple pipeline if I get imagepullbackoffs

![Bildschirmfoto vom 2022-04-14 03-04-02](https://user-images.githubusercontent.com/45896133/163294334-8261b68c-cbec-4beb-a61b-f7443245fd08.png)
![Bildschirmfoto vom 2022-04-14 03-04-28](https://user-images.githubusercontent.com/45896133/163294336-e48f156e-5e3f-46d5-a4eb-d3c149bc2999.png)
![Bildschirmfoto vom 2022-04-14 03-05-00](https://user-images.githubusercontent.com/45896133/163294337-2dfee5f3-3377-4852-b7b0-dc93901d3d5b.png)

**Comment by ketangangal** [comment]
This issue is still present in kf pipeline 1.8.0
