### ISSUE TITLE
Feature suggestion: expose the duration of each pipeline step

### ISSUE THREAD

**Issue by gcampax** [kubeflow/pipelines#4699]
It would be very useful to know how long each pipeline step took, in addition to the total duration of the pipeline.
This is especially useful when trying different hyperparameters that affect performance.

This information is already available on the Argo UI, but (1) one needs to know the UI exists (it is not exposed from the Kubeflow dashboard) and (2) one needs to cross reference the pod name from the kubeflow-pipelines UI and the Argo UI. It would be nice to have the duration in one place.

**Comment by Bobgy** [comment]
Contribution instructions: https://github.com/kubeflow/pipelines/tree/master/frontend

Run details page react component: https://github.com/kubeflow/pipelines/blob/e3992faf8305570ca56c5932d701eb8765305568/frontend/src/pages/RunDetails.tsx#L342
