### ISSUE TITLE
How to access run info within a run

### ISSUE THREAD

**Issue by santiagoolivar2017** [kubeflow/pipelines#4700]
Once a run is executed how can I retrieve information like the experiment name, run id, pipeline name, etc. I need this information to manage where the artifacts will be stored and woud like to organize the paths based on this information.

**Comment by santiagoolivar2017** [comment]
I figured it out.
I am using `kfp.dsl.EXECUTION_ID_PLACEHOLDER` and `kfp.dsl.RUN_ID_PLACEHOLDER` within the pipeline specification.

**Comment by Bobgy** [comment]
I'm glad you figured out by yourself

**Comment by santiagoolivar2017** [comment]
@Bobgy 
Those placeholders are very useful and I have been using them to uniquely identify a run. Nevertheless, I am still not able to get the run name and the experiment name (assuming that the run is part of one experiment). Any idea how this can be done?

**Comment by Bobgy** [comment]
I think we need to expose it

**Comment by Bobgy** [comment]
/cc @hongye-sun 
Have we thought about placeholder syntax for exposing run uuid?

The existing placeholders have `[[RunUUID]]` format as supported in scheduled workflow controller, but in IR we are now standardizing on
https://github.com/kubeflow/pipelines/blob/7ed110e9845237115591d04d82085d957e343795/api/v2alpha1/pipeline_spec.proto#L595-L613

I think it makes more sense to stick with IR format.

Context: @StefanoFioravanzo has already implemented PRs to add the placeholder? The major remaining concern is aligning on a preferred placeholder format.

**Comment by hongye-sun** [comment]
How about we introduce the following placeholders:

`$.job` returns the json payload of the job metadata which includes ID, name and pipeline name, etc.
`$.job.id` returns the unique ID of the job.

**Comment by Bobgy** [comment]
https://github.com/kubeflow/pipelines/pull/5086 adds support for [[RunUUID]] and the [[CurrentTime.<template>]] macros for one-off runs.

**Comment by Bobgy** [comment]
Hi @santiagoolivar2017, sorry for wrong reply previously. kfp.dsl.RUN_ID_PLACEHOLDER was already KFP run ID, so you can query KFP API to get its name and experiment name.

See sample https://github.com/kubeflow/pipelines/pull/5385.

**Comment by kvamshi** [comment]
When you submit a run, e.g. using create_run_from_pipeline_func, it returns RunPipelineResult, which has run_id attribute
```
client = kfp.Client(host)
result = client.create_run_from_pipeline_func(…) 
result.run_id
```
You can use this id to retrieve other details from [KFP API ](https://www.kubeflow.org/docs/components/pipelines/reference/api/kubeflow-pipeline-api-spec/)
