### ISSUE TITLE
Style: Conflicting indentation requirements between pylintrc and yapf config

### ISSUE THREAD

**Issue by suryaavala** [kubeflow/pipelines#4703]
### What steps did you take:
[A clear and concise description of what the bug is.]

1. formatted `proxy/*.py` with `yapf` using `.style.yapf` as per [CONTRIBUTING.md](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#coding-style)
2. `pylint` with the given `.pylintrc` started complaining  `W0311: Bad indentation. Found 4 spaces, expected 2 (bad-indentation)`

### What happened:
According to [Google Style Guide](https://google.github.io/styleguide/pyguide.html#s3.4-indentation):

> Indent your code blocks with 4 spaces.

However `.pylintrc` has `indent-string='  '` (two spaces)

### What did you expect to happen:
`indent-string=` in `.pylintrc` should probably be `'    '` (four spaces) inline with the google style guide that `yapf` uses to auto format `py` files

/kind misc

**Comment by NikeNano** [comment]
The background discussion to this can be found here: https://github.com/kubeflow/pipelines/pull/2446, how ever as I understand it we should strive for 4 spaces according to the google standard as you point out.

**Comment by numerology** [comment]
Thanks! Sent https://github.com/kubeflow/pipelines/pull/4706 to fix

**Comment by Bobgy** [comment]
/lgtm
/approve
Thank you @numerology !
