### ISSUE TITLE
ComponentStore fails to include filename when pulling by version or tag

### ISSUE THREAD

**Issue by jackwhelpton** [kubeflow/pipelines#4708]
Looking at the comments around `ComponentStore` more closely, I don't think this is a bug, but rather my misunderstanding of the intended behavior: I'll need to adjust how I publish my components. The further question about using ComponentStore to load standard components (in a comment below) still stands. Leaving this here to get clarification:

### What steps did you take:
* stored a Kubeflow component at https://www.example.com/kubeflow/components/gcp/storage/download_dirs/versions/tags/0.1.0/component.yaml

* configured a `ComponentStore`:
```python
components = ComponentStore(
    url_search_prefixes=[ "https://www.example.com/kubeflow/components/" ]
)
```

* fetched a versioned component using:
```python
download_from_gcs_op = components.load_component("gcp/storage/download_dirs", tag="0.1.0")
```

### What happened:
With appropriate debugging, it became apparent this was causing a failure because the ComponentStore is attempting to fetch https://www.example.com/kubeflow/components/gcp/storage/download_dirs/versions/tags/0.1.0 and not https://www.example.com/kubeflow/components/gcp/storage/download_dirs/versions/tags/0.1.0/component.yaml.

### What did you expect to happen:
Component to be retrieved from https://www.example.com/kubeflow/components/gcp/storage/download_dirs/versions/tags/0.1.0/component.yaml.

### Environment:

KFP SDK version: kfp 1.1.0a1

### Anything else you would like to add:
I'm unclear if this is intentional, and tagged components _should_ be stored in files bearing the tag as a filename (and no extension). If not, I could probably do a PR, as the reason for this is pretty clear:

https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/components/_component_store.py#L131

Note that the `component_file_name` is in an else block, so is only added if digest and tag are not specified.

/kind bug

**Comment by jackwhelpton** [comment]
As a related point, I'd hoped I could use the default ComponentStore to retrieve tagged versions of standard components, but:

```python
ComponentStore.default_store.load_component(
    "google-cloud/storage/upload_to_explicit_uri", tag="1.0.1"
)
```

attempts to retrieve:

https://raw.githubusercontent.com/kubeflow/pipelines/master/components/google-cloud/storage/upload_to_explicit_uri/versions/tags/1.0.1

rather than the correct path, which would be:

https://raw.githubusercontent.com/kubeflow/pipelines/1.0.1/components/google-cloud/storage/upload_to_explicit_uri/component.yaml

**Comment by jackwhelpton** [comment]
Perhaps if rather than `url_search_prefixes` we could define URI templates, with `tag` and `digest` as variables?

**Comment by parthmishra** [comment]
Is there any update on this? As was mentioned, the fix seems doable, but it's not clear to me if tags/digest are supposed to be actual file locations or the source ref.

What is the recommended way to load in versioned components?

**Comment by parthmishra** [comment]
Found an [old answer](https://github.com/kubeflow/pipelines/issues/1025#issuecomment-475808132) from @Ark-kun on the intended behavior for versioning which answers my question- the filename is supposed to be the file hash/tag and stored in sub-directory of the component. 

Unless I'm missing something, I feel like that workflow makes more sense in the context of an external storage system like GCS than with git because you're maintaining all historical versions of the component definitions alongside the source code which seems redundant compared to just referencing the commit in the URL.

**Comment by jackwhelpton** [comment]
I agree: if you're using a hosted service such as GitHub you're often at their mercy when it comes to the exact URI structure. The more I've thought about this, the more I like being able to define a URI template (RFC 6570), using `{tag}` and/or `{digest}`.

I'd propose this change as a PR, but at a quick look I couldn't see an RFC 6570 package as a dependency, and introducing new dependencies into the SDK felt above my paygrade. There are plenty of options, e.g. https://pypi.org/project/uri-template.

Thoughts?

**Comment by jackwhelpton** [comment]
I've published a sample PR for what URI template support might look like, as a prompt for further discussion: see link above (https://github.com/kubeflow/pipelines/pull/5434)

**Comment by jackwhelpton** [comment]
It'd still be really handy to have this feature: this is a blocker for us sharing component code directly from GitHub Enterprise... a review of the above PR would be great.
