### ISSUE TITLE
metadata_writter doesn't create input artifact and attributions for component inputs with no upstream

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/pipelines#4709]
### What happened:

https://github.com/kubeflow/pipelines/blob/master/backend/metadata_writer/src/metadata_writer.py#L226
https://github.com/kubeflow/pipelines/blob/1123489787a542d919ee1e9a97c30ac0df0709c3/backend/metadata_writer/src/metadata_helpers.py#L353-L381

From the logics in `https://github.com/kubeflow/pipelines/blob/1123489787a542d919ee1e9a97c30ac0df0709c3/backend/metadata_writer/src/metadata_helpers.py#L353-L381`. It tries to find artifact based on uri and then link execution to the context.

### What did you expect to happen:

This logic is different from the logic metadata_writer process output.  I would assume it should 

1.  Create ArtifactType and artifacts for the inputs from argo template 
2.  Create attribution and link artifact to the context. 

From below lines, I didn't see any logics there. Seems input artifact is created by some other components? 
https://github.com/kubeflow/pipelines/blob/1123489787a542d919ee1e9a97c30ac0df0709c3/backend/metadata_writer/src/metadata_writer.py#L233

/cc @Ark-kun 

### Environment:
master

How did you deploy Kubeflow Pipelines (KFP)?
KFP version:  master
KFP SDK version: master

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind question

**Comment by Ark-kun** [comment]
>metadata_writter doesn't create input artifact and attributions

MW should be doing that: 
https://github.com/kubeflow/pipelines/blob/e3992faf8305570ca56c5932d701eb8765305568/backend/metadata_writer/src/metadata_helpers.py#L402
Can you describe the scenarios where it doesn't?

>Seems input artifact is created by some other components?

Artifacts are created when outputting them from a component.

Then these existing artifacts are linked to the downstream component inputs.

>Create ArtifactType and artifacts for the inputs from argo template

I'm not sure whether this behavior would be correct. When passing an artifact between two components, it's a single artifact. The upstream component produces it as an output and the downstream component finds it and links to it as an input.

**Comment by Jeffwan** [comment]
@Ark-kun  Thanks for explanation. I think there's one case I am not clear. What if input artifact comes from the the first component/step in the pipeline? In MW, we rely upstream component to log the artifact. In that case, you can see it will lands 
on https://github.com/kubeflow/pipelines/blob/1123489787a542d919ee1e9a97c30ac0df0709c3/backend/metadata_writer/src/metadata_writer.py#L232-L234

in Kubeflow Pipeline, do we have any similar case we can pass input artifact? I barely use KFP in this way. For example, if I like to track my training dataset as an artifact, I would like to put it as pipeline input artifact. See Argo's case here
https://github.com/argoproj/argo/blob/master/examples/input-artifact-s3.yaml#L16

**Comment by Ark-kun** [comment]
>What if input artifact comes from the the first component/step in the pipeline?

I'm not sure I understand this.
It seems to be impossible to have a pipeline where some artifact argument does not come from the output of another component. Do you have an example?

**Comment by Jeffwan** [comment]
Got you. Let me run some examples using `Input Artifact` in the first component. I will report result back later.

**Comment by Ark-kun** [comment]
Just remembered that I made it possible to pass pipeline parameters and constant strings to "consumed-as-file" inputs. However even in this case there there is no artifact with a URI.

Is there a practical issue associated with this?

A workaround would be a "data importer" component that just passes-through the data resulting in it becoming an artifact.

**Comment by Jeffwan** [comment]
@Ark-kun 

No practical issue yet. I am trying to do make input artifact without upstream traceable and then raise this question.
