### ISSUE TITLE
Is backend/api/Makefile still being used?

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/pipelines#4717]
### What steps did you take:

I notice there're multiple files to generate codes. 

1.  https://github.com/kubeflow/pipelines/blob/master/backend/api/Makefile
This file seems doesn't have updates for long time. I notice some libraries like `go-swagger` is missing there after vendor dependencies, go.mod and go.sum doesn't have dependency as well. (we didn't explicitly import build tools)

2. https://github.com/kubeflow/pipelines/blob/master/backend/api/generate_api.sh && 
https://github.com/kubeflow/pipelines/blob/master/backend/api/build_kfp_server_api_python_package.sh
Does community suggest to use these shell to generate codes?

/question

**Comment by Bobgy** [comment]
> https://github.com/kubeflow/pipelines/blob/master/backend/api/generate_api.sh &&
https://github.com/kubeflow/pipelines/blob/master/backend/api/build_kfp_server_api_python_package.sh
Does community suggest to use these shell to generate codes?

These are what we use right now.

It'd be great to clean up others if they are not used.
