### ISSUE TITLE
Unable to visualize any HTML content with Output Viewer

### ISSUE THREAD

**Issue by post2web** [kubeflow/pipelines#473]
I have a test HTML file uploaded at `gs://notebook-output/test.html` with contents:
```HTML
<html>
    <body>
        TEST
    </body>
</html>
```
A component has `/metadata.json` with contents:
```json
{
  "outputs": [
    {
      "type": "web-app",
      "storage": "gcs",
      "source": "gs://notebook-output/test.html"
    }
  ]
}
```
The Pipelines UI doesn't show any Artifacts.

**Comment by yebrahim** [comment]
Can you check developer console log to see if there are any errors there? The network tab should also show you what kind of requests are being made, those would be helpful to see if it's a network issue while fetching artifact data, or if no requests are being made at all.

**Comment by vicaire** [comment]
Resolving since inactive for a while. Please reopen if needed.
