### ISSUE TITLE
Enable running the apiserver locally

### ISSUE THREAD

**Issue by elikatsis** [kubeflow/pipelines#4738]
During the review of #4723, @Bobgy brought up being able to run the apiserver locally.
This is currently not available because the code expects to be running inside a pod.

For example, in kubernetes client initializations, the apiserver tries to load an in-cluster config or fails, whereas it should also try loading a kubeconfig.

/assign @elikatsis @Bobgy

**Comment by Bobgy** [comment]
This is useful for debugging a local API server without building the image.

**Comment by arllanos** [comment]
@Bobgy @elikatsis
We came across this same thing while contributing in #4197. I documented a setup that worked out for me. Basically I deploy pipelines in a local a k3s cluster (I only do this to hava mysql and minio running) and do a bit of hack to make local code run as in-cluster. I documented that [here](https://github.com/arllanos/tekhno/blob/main/kubeflow-pipelines-dev.md) 
Might not be perfect but it works. I would love to have your feedback.

**Comment by Bobgy** [comment]
@arllanos that's a great start!

I think it will be better if we can reduce the number of hacky local setup required, e.g. API server can authenticate to kubernetes master via local kubeconfig, we just need to change the authentication process this issue presented
