### ISSUE TITLE
[UI] Namespace Filtering

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/pipelines#4739]
A common need that comes up when building a Kubernetes-based UI is a namespace selector.
Examples include the Kubeflow CentralDashboard.

How do we populate the namespace selector? How do we decide which namespaces the user can see?

The solution of https://github.com/kubeflow/kubeflow/issues/5390 should be used for the KFP UI as well.

/cc @Bobgy @elikatsis @StefanoFioravanzo @vkoukis

**Comment by Bobgy** [comment]
I have been thinking about listing all namespaces in the cluster filtered by a pipelines label. If perf has limitation, then we need a cache.

I think specific actions need RBAC, seeing the list of namespaces probably don't.

**Comment by Bobgy** [comment]
When there are a lot of users, we might want to add UI features to search namespaces, marking a namespace as default and bookmark some namespaces.

**Comment by Bobgy** [comment]
I propose the following:

On API side:
1. update profile controller to add a `pipelines.kubeflow.org/enabled: true` label to Kubeflow namespaces
2. add an endpoint in KFP API to list all namespaces with this label, return them as a response

On UI side:
* Add a namespace selector that send a request to KFP API added above to get the list of namespaces, for the initial version, I think it can get all namespaces without pagination, and we add a search box to allow searching for namespaces.
* The namespace selector persists namespace selected last time in local storage, so users won't need to select it each time.

**Comment by juliusvonkohout** [comment]
/close

I think this is already implemented
