### ISSUE TITLE
Kubeflow Pipelines Proper REST Interface

### ISSUE THREAD

**Issue by maganaluis** [kubeflow/pipelines#4742]
**Feature Request**

Currently the only way to execute Kubeflow Pipelines is using the SDK or using the backend services, it would be great to create a proper REST service. 

For example to get to the screen below, one would have to first get the existing pipelines for the given namespace (given that this becomes multi-user) then get existing experiments if not create one, etc... 

Finally one would have to execute the run with the desired parameters, and then watch for completion. T

This approach currently is pretty painful due to the lack of documentation and/or proper REST calls. 

The benefits of having a proper REST API is that Kubeflow Pipeline Services could more easily integrate with other services to enable Continuous Learning, especially services with Pub-Sub architectures. 

![Screen Shot 2020-11-09 at 7 42 47 PM](https://user-images.githubusercontent.com/15258405/98617080-d73d0680-22c3-11eb-8da8-8863e7a77716.png)

**Comment by marcjimz** [comment]
+1 on this, is this something we can pick up? Appreciate insights on the level of effort it would take to have this functional.

**Comment by chensun** [comment]
We do have REST API: https://www.kubeflow.org/docs/pipelines/reference/api/kubeflow-pipeline-api-spec/

**Comment by maganaluis** [comment]
@chensun Thank you, I will close this issue.
