### ISSUE TITLE
Docker images not being pulled on EKS pipelines

### ISSUE THREAD

**Issue by ajinkya933** [kubeflow/pipelines#4743]
### What steps did you take:
I am trying to execute the below code on Kubeflow - EKS. This code is running very well using Kubeflow - microk8s. 
Whenever I try to Run this code on EKS. The docker image is not being pulled. The code is stuck where docker image has to be  pulled.

Visually the error is seen as:

https://github.com/ajinkya933/Assignment_solution/blob/master/gitissue.png

Here is the python code:

```
import kfp
import kfp.dsl as dsl
import kfp.components as comp
from kubernetes import client

def train(data_path):
    '''
        Download test.tif file from google drive and save it at location of {data_path}
    '''
    import tensorflow


    data='Geojson export is complete'
    # Save test data file
    with open(f'{data_path}/test_data.txt', 'w') as f:
        f.write(data)


# Glue together training function to the docker container
train_op = comp.func_to_container_op(train, base_image='tensorflow/tensorflow:latest')


# define pipeline metadata like name, description etc.
@dsl.pipeline(
    name='file writer test',
    description='Pipeline that writes and reads from file'
)
# define virtual HDD space that the pipeline will take to run
def mnist_container_pipeline(data_path='/mnt'):
    vop = dsl.VolumeOp(
        name='create_volume',
        resource_name='data-volume',
        size='1Gi',
        modes=dsl.VOLUME_MODE_RWM
    )


# We have already created a volume and a Glued component(Docker+Python script). This Glued component needs
# to communicate with the volume so lets attach a volume to Glued component
    mnist_training_container = train_op(data_path) \
        .add_pvolumes({data_path: vop.volume})

        # Print the result of the prediction
    mnist_result_container = dsl.ContainerOp(
        name="print_prediction",
        image='library/bash:4.4.23',
        pvolumes={data_path: mnist_training_container.pvolume},
        arguments=['cat', f'{data_path}/test_data.txt']
    )


# pass these paths inside the volume that we made
pipeline_func = mnist_container_pipeline
run_name = pipeline_func.__name__ + ' run'


if __name__ == '__main__':
    kfp.compiler.Compiler().compile(pipeline_func, __file__ + '.yaml')

```
### What happened:
The code is stuck and not pulling the pipeline. Here is the yaml file for above code: https://github.com/ajinkya933/Assignment_solution/blob/master/githubissue.yaml

This yaml file is not running

### What did you expect to happen:
pipeline to run on EKS-kubeflow

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by PatrickXYS** [comment]
Can you paste the error message here?

**Comment by ajinkya933** [comment]
Can you tell me a right way to get this error message. As long as I see on the Dashbord there is no error shown. On Docker pull part of the pipeline, the pipeline is permanently stuck on pending execution

**Comment by ajinkya933** [comment]
Please run Pipeline : https://github.com/ajinkya933/Assignment_solution/blob/master/githubissue.yaml on your end to reproduce the issue

**Comment by PatrickXYS** [comment]
> As long as I see on the Dashbord, there is no error shown. 

Okay, so how did you figure out the error is caused by the image not pulling rather than other issues?

**Comment by ajinkya933** [comment]
@PatrickXYS Great question, initially I had run pipelines not involving docker images 
code for pipeline without docker involvement: https://github.com/ajinkya933/Assignment_solution/blob/master/magic.py
tar.gz file for pipeline without docker involvement:https://github.com/ajinkya933/Assignment_solution/blob/master/magic.tar.gz

The above code+tar.gz file runs well on Kubeflow pipelines UI, and `magic.py` dosent have docker image associated with it. Which lead me to conclusion that issue is being caused while pulling docker images

**Comment by ajinkya933** [comment]
![image](https://user-images.githubusercontent.com/17012391/98629673-663b3480-233f-11eb-94ac-230049604bd3.jpeg)![image](https://user-images.githubusercontent.com/17012391/98629693-74895080-233f-11eb-87bd-8c7f69e25e7c.jpeg)

**Comment by ajinkya933** [comment]
Issue is resolved. The problem was I was attaching a external 1GB volume to the pipeline which was causing communication issues to the docker hub, I removed the external attached volume. Which resolved the issue. Although the code works now I am not able to attach any volume to the pipeline. I will open this in another issue.
