### ISSUE TITLE
[Process] Update backend development README

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#4750]
We have https://github.com/kubeflow/pipelines/tree/master/backend, but it is highly outdated because we have moved away from bazel.
It'll be great if we can update it to reflect current best practices.

**Comment by Bobgy** [comment]
Hi @NikeNano, I think you recently developed backend, do you want to contribute to this?

**Comment by NikeNano** [comment]
Sure would be happy to help out! Will look at it after I sorted out the cron scheduler.
