### ISSUE TITLE
Correct use of Kf Pipelines API POST

### ISSUE THREAD

**Issue by texdade** [kubeflow/pipelines#4754]
Hi,

I've been working with Kubeflow Pipelines for two months now and, after having implemented different pipelines structures, I'm trying to benchmark them using the [Kubeflow pipelines benchmark script](https://www.kubeflow.org/docs/pipelines/tutorials/benchmark-examples/).

I can successfully contact my APIs when using GET requests, like "http://172.28.45.108:31380/_/pipeline/apis/v1beta1/pipelines", but POST requests always return a 404 error, like for example "Cannot POST /_/pipeline/apis/v1beta1/runs" when POSTing "http://172.28.45.108:31380/_/pipeline/apis/v1beta1/runs".

I don't understand if this is a problem with my configuration, or if I need to use the security apiKey, which is present in the [API reference page](https://www.kubeflow.org/docs/pipelines/reference/api/kubeflow-pipeline-api-spec/), but not in the benchmark script example.

/kind question

**Comment by Bobgy** [comment]
If my kubeflow host is
https://xxx.com/

Pipeline API is at https://xxx.com/pipeline/, not https://xxx.com/_/pipeline/. The second url is a link to central dashboard that shows Pipelines UI in an iframe

**Comment by texdade** [comment]
That was it, thank you!
