### ISSUE TITLE
How to give Run parameters when I run Kubeflow pipelines API ?

### ISSUE THREAD

**Issue by ajinkya933** [kubeflow/pipelines#4755]
### What steps did you take:

How do I specify Run parameters when I run Kubeflow pipelines API ?

Standard way to run a pipeline through Kubeflow pipelines  API   is :

```
curl -H "Cookie: authservice_session=MTY...WQ" -H "Content-Type: application/json" -X POST ${SVC}/apis/v1beta1/runs \
-d @- << EOF
{
    "name":"eq_run",
    "pipeline_spec":{
      "pipeline_id":"${PIPELINE_ID}"
    },
    "resource_references":[
      {
        "key":{
          "type":"EXPERIMENT",
          "id":"${EXP_ID}"
        },
         "name": "Default",
         "relationship": "OWNER"
      }
    ]
}
EOF
```

The above request attaches pipeline to experiment and runs pipeline under that experiment. However when I run there is Run parameters where I say data will be stored in /mnt location as shown in figure below:

https://github.com/ajinkya933/Assignment_solution/blob/master/runAPI.png

Now I want to specify this "data_path" to something else like "/ajinkya" . How Do I change that? How do I modify above curl request to do that

/kind question

@Bobgy

**Comment by Bobgy** [comment]
https://www.kubeflow.org/docs/pipelines/reference/api/kubeflow-pipeline-api-spec/#/definitions/apiRun
apiRun.pipelineSpec.parameters

Here it is

**Comment by Bobgy** [comment]
Another way to find out is by opening browser console and see what request KFP UI is sending

**Comment by ajinkya933** [comment]
Could you add this above curl request ? I did not understand what needs to be changed in curl command

**Comment by ajinkya933** [comment]
```
{
  
    "name":"snic_500",
    "pipeline_spec":{
      "pipeline_id":"06f...5",
      "apiParameter":{
          "name":"myarg",
          "value":"100"
      }
    },
    
    "resource_references":[
      {
        "key":{
          "type":"EXPERIMENT",
          "id":"2c394755-f6af-48d8-be05-cb85c91b8cf3"
        },
         "name": "Default",
         "relationship": "OWNER"
      }
        
      
    ]
}
```
