### ISSUE TITLE
Validating a compiled Kubeflow Pipeline with Argo v2.7+ fails

### ISSUE THREAD

**Issue by alexlatchford** [kubeflow/pipelines#4775]
### What steps did you take:

Since KFP [upgraded to Argo==2.7](https://github.com/kubeflow/pipelines/pull/3537), looks like the validation of compiled pipelines no longer works, see [this line](https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/compiler/compiler.py#L1000)

Running `argo lint /dev/stdin ''` will always fail now whereas looks like that was used as a check in `argo ~2.4`.

### What happened:

It errors when trying to validate a workflow.

### What did you expect to happen:

I expected it to validate the workflow.

### Environment:

KFP SDK version: v1.0.4 (actually a version of `master` from a few weeks back).

### Anything else you would like to add:

Ideally it'd be great to be able to disable validation via the `compile` API/CLI. For now I've just removed `argo` from the `PATH` but obviously not ideal.

/kind bug
/area sdk

**Comment by NikeNano** [comment]
Due to the lack of offline support for workflow validation in argo clients > 2.4.3, you still need to use the 2.4 client to validate workflows offline, and it will not be updated atm in sdk. See this closed issue for more information: https://github.com/kubeflow/pipelines/pull/4804
