### ISSUE TITLE
ScheduledWorkflow continues to try to sync with disabled recurring run workflow

### ISSUE THREAD

**Issue by hsezhiyan** [kubeflow/pipelines#4779]
### What steps did you take:
I created a recurring run on the KFP UI. I let it run for some time, then disable it.

### What happened:
When I view the logs of the `ml-pipeline-scheduledworkflow`, I notice the WorkflowScheduler continues to attempt to sync with the `ml-pipeline` pod on behalf of the now disabled recurring run. It produces the following logs:

`"Submitting workflow for ScheduledWorkflow (aip2682catchuponjjjjj): nothing to submit (next scheduled at: 2020-11-18 22:11:02 +0000 UTC)" ScheduledWorkflow=aip2682catchuponjjjjj`

When I delete the recurring run configuration, this no longer happens (as expected).

### What did you expect to happen:

The ScheduledWorkflow pod should not attempt to sync for a recurring run that's been disabled. It produces a lot of logs because we currently have a lot of recurring runs that we disable and no longer care about, but they still produce a lot of logs.

### Environment:
`KFP v.1.0.0`

How did you deploy Kubeflow Pipelines (KFP)?

KFP version: `1.0.0`
KFP SDK version: 
```
aip-kfp-sdk              1.0.0+38064f78 
kfp                      1.0.0          
kfp-pipeline-spec        0.1.2          
kfp-server-api           1.0.1  
```

### Anything else you would like to add:

I initially thought this was a Catchup (backfilling issue). The ScheduledWorkflow continues to sync with a recurring run with catchup turned on. When catched is turned off, it should no longer sync (but it still does).

/kind bug

**Comment by Bobgy** [comment]
Hi @hsezhiyan, this is expected behavior for how a Kubernetes operator works (basically a control loop).

The periodic sync still happens, so that when that job is enabled again, it will continue to submit runs.

**Comment by Bobgy** [comment]
Is the extra logs a huge problem?
There can be optimizations to delete the scheduled workflow when they are disabled, and recreate them when they are enabled again.

**Comment by alexlatchford** [comment]
Thanks @Bobgy, for Zillow (I work with @hsezhiyan) we have internal sample projects with CICD that automatically creates a schedule by default for new projects to allow our ML teams to quickly get started with KFP. Investigating that though it looks like a larger number than we anticipated have disabled that schedule. On our end we plan to mitigate this by defaulting these sample projects to not create a schedule by default. That'll solve this problem for us in the short/medium term.

Digging a little deeper about this though, is the call back to the Pipelines API service just checking to see if it's enabled? Can that data be stored on the CRD itself and then that'd negate the need to make another API call to check that status? I'm definitely quite naive around the structure of the Scheduled Workflows component so apologies if this is over simplifying the interactions!

**Comment by Bobgy** [comment]
@alexlatchford no worries, let me explain a bit.
The swf controller doesn't call back to the Pipelines API service to see if it's enabled, that information is already in the CRD itself.
See https://github.com/kubeflow/pipelines/blob/74a8178e1d68ad3dad28084673ab74605e0e735d/backend/src/crd/controller/scheduledworkflow/util/scheduled_workflow.go#L217-L217

It makes sense to exit earlier for scheduled workflows that are disabled and not produce logs (or produce logs that do not show up with default level of verbosity). You'll find related code in above link.

I'll mark this as a valid feature request, but this isn't very high priority for us.

**Comment by Bobgy** [comment]
We can probably early exit the controller loop right from the beginning: https://github.com/kubeflow/pipelines/blob/bbfe5e09cc4b4143854b19f4c46fabeadb75263e/backend/src/crd/controller/scheduledworkflow/controller.go#L379-L379

**Comment by alexlatchford** [comment]
Thanks for pointing this out @Bobgy, we'll see how our mitigation works and whether we need to tackle this too if it doesn't, thanks for being transparent on priorities. Will reach out if we have any more questions!
