### ISSUE TITLE
Simplify and optimize manifests installation for customized namespace

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/pipelines#4783]
There're two steps to install KFP. 

```
kubectl apply -k cluster-scoped-resources/
kubectl apply -k env/platform-agnostic/
```

1. Seems `../base/cache-deployer/cluster-scoped` might be used to generate namespace value. `cache-deployer` itself supports watching objects in specific namespace, there's unnecessary to install it under single user mode
https://github.com/kubeflow/pipelines/blob/aa162e6a2491fe8d9a718b27b8c628f7b4a10bee/manifests/kustomize/cluster-scoped-resources/kustomization.yaml#L12
https://github.com/kubeflow/pipelines/blob/aa162e6a2491fe8d9a718b27b8c628f7b4a10bee/manifests/kustomize/cluster-scoped-resources/namespace.yaml#L4

With this trick, if user likes to deploy KFP in a different namespace, they can easily change `namespace` field in `kustomization.yaml`. Without vars reference, user has to manually change the value in namespace.yaml. 

2.  in the second step, user has to change namespace again here
https://github.com/kubeflow/pipelines/blob/aa162e6a2491fe8d9a718b27b8c628f7b4a10bee/manifests/kustomize/base/kustomization.yaml#L3
and we can see `kfp-namespace` var is being used in other places as well. 
https://github.com/kubeflow/pipelines/blob/aa162e6a2491fe8d9a718b27b8c628f7b4a10bee/manifests/kustomize/base/kustomization.yaml#L21-L27

Based on above observation, I think it's better to move `namespace.yaml` in the first step to second step, since kustomize  support dependency, it will create namespace first and then rest of the objects in sequence. User doesn't have to specify namespace in the first step and only need to change one line if they want a different namespace

**Comment by Bobgy** [comment]
@Jeffwan https://github.com/kubeflow/pipelines/blob/aa162e6a2491fe8d9a718b27b8c628f7b4a10bee/manifests/kustomize/base/cache-deployer/cluster-scoped/cache-deployer-clusterrole.yaml#L21 is a cluster-scoped resource, thus you cannot grant this permission via `role`: https://kubernetes.io/docs/reference/access-authn-authz/rbac/#role-and-clusterrole

**Comment by Bobgy** [comment]
> cache-deployer itself supports watching objects in specific namespace, there's unnecessary to install it under single user mode

It sets up mutating webhook for the execution cache feature though, why would that not be useful for single user mode?

**Comment by Jeffwan** [comment]
@Bobgy I didn't clarify it clearly.  I mean cluster-role and cluster role binding for cache-deployer. They are not required for KFP single user mode

**Comment by Jeffwan** [comment]
@Bobgy I look at your comments in #4781, let's discuss there

**Comment by Jeffwan** [comment]
I think my assumption is incorrect. cache-deployer does need permissions to list, create webhooks and it requires a cluster role for cluster scoped resources . I will close the issue and thanks @Bobgy
