### ISSUE TITLE
ContainerOp's "after" accepting variable arguments, but OpsGroup's one is not?

### ISSUE THREAD

**Issue by Udiknedormin** [kubeflow/pipelines#4787]
Looks like the signature of [`OpsGroup`'s `after` method](https://github.com/kubeflow/pipelines/blob/7f32dde71190d46a132823e7d0ed59ae8df792f2/sdk/python/kfp/dsl/_ops_group.py#L96) is:

```python
def after(self, dependency): ...
```

...but for both [BaseOp](../blob/7f32dde71190d46a132823e7d0ed59ae8df792f2/sdk/python/kfp/dsl/_container_op.py#L791) and [PipelineVolume](../blob/7f32dde71190d46a132823e7d0ed59ae8df792f2/sdk/python/kfp/dsl/_pipeline_volume.py#L89) it's:

```python
def after(self, *ops): ...
```

Shouldn't `OpsGroup` be consistent with the other two and also accept `*ops`? Looks backward-compatible to me:

```python
# now it's:
def after(self, dependency): ...

group.after()               # invalid
group.after(op)             # valid
group.after(dependency=op)  # valied
group.after(op1, op2)       # invalid

# the other classes use:
def after(self, *ops): ...

group.after()               # valid (although quite useless)
group.after(op)             # valid
group.after(dependency=op)  # invalid
group.after(op1, op2)       # valid

# ...so for backwards-compatibility with by-keyward call:
def after(self, dependency, *ops): ...

group.after()               # invalid, but it's wouldn't be useful anyway
group.after(op)             # valid
group.after(dependency=op)  # valid
group.after(op1, op2)       # valid
```

...or did I miss something and it's intentional?

/area sdk
/kind question

**Comment by Ark-kun** [comment]
Likely, the person who added support for multi-argument `after` to `ContainerOp` just forgot to add it to the `OpsGroup`.

Thank you for taking on this issue.

**Comment by Udiknedormin** [comment]
Fixing PR was merged, so I'm closing the issue.
