### ISSUE TITLE
env variable parsing in component.yaml

### ISSUE THREAD

**Issue by mjurkus** [kubeflow/pipelines#4793]
I want to use `kaniko` to build the final image, but for that I need a variable to be passed to `kaniko` executor via `--build-arg`

How would one achieve that? If it's possible at all?

Example of component definition:
```
name: My Component
description: ...
inputs:
  - {name: arg1, description: 'description'}
implementation:
  container:
    image: gcr.io/kaniko-project/executor:v0.24.0
    args: [
      "--dockerfile", "Dockerfile",
      "--build-arg, GITHUB_TOKEN=$GITHUB_TOKEN,
      "--arg1", {inputPath: arg1},
      "--snapshotMode=redo",
      "--use-new-run=true",
      "--cache=true"
    ]
```

**Comment by Ark-kun** [comment]
>env variable parsing
>need a variable to be passed 

Can you please explain what exactly you want to achieve. What is `$MY_ARG`? Where does it exist? How is is supposed to make it inside the container?

Taking a guess, you might be asking about passing the value of an input argument (rather than a file path for it). In that case, you can use `{inputValue: arg1}` placeholder. And if you need to concatenate values, use `concat`:
```yaml
"--build-arg", {concat: ["MY_ARG=", {inputValue: arg1}]},
```

Also see the following sample that geuides you through building a pipeline that builds container images using Kaniko from a Git repo:
https://github.com/Ark-kun/kfp_samples/blob/ae1a5b6/2019-10%20Kubeflow%20summit/106%20-%20Creating%20components%20from%20command-line%20programs/106%20-%20Creating%20components%20from%20command-line%20programs.ipynb

P.S. 
>args: [

We advice our users to always specify the full command-line - to use the `command: [...]`, not just `args: [...]`. Certain techniques won't work without that.

**Comment by mjurkus** [comment]
@Ark-kun thanks for the quick reply.

I've renamed MY_ARG to GITHUB_TOKEN to give it more context. 
It is known when building the pipeline or could be retrieved from k8s secrets.

In the `Dockerfile` there is `ARG GITHUB_TOKEN` and I need to provide it when building the image with kaniko.

I'm trying to figure out how I could achieve that. Since the token is a secret - I don't can't use inputs.

**Comment by NikeNano** [comment]
You can add access k8s secrets to your components, code [here](https://github.com/kubeflow/pipelines/blob/0795597562e076437a21745e524b5c960b1edb68/sdk/python/kfp/dsl/extensions/kubernetes.py ), let me know if there is any issues with it :)

**Comment by mjurkus** [comment]
Yes, I can add secrets to components. I also tried `add_env_variable`.
But I guess `"--build-arg, GITHUB_TOKEN=$GITHUB_TOKEN,` is not parsed and treated as a literal.

```
ARG GITHUB_TOKEN

RUN echo GITHUB_TOKEN
```

will output "$GITHUB_TOKEN" instead of the actual value.

**Comment by Ark-kun** [comment]
>I'm trying to figure out how I could achieve that. Since the token is a secret - I don't can't use inputs.

Think of the data flow. Where is the information (token) initially? Where do you want it to get (in the command-line of some program)? How is it going to get there? How will the Kubernetes Pod look like? How will the container command-line look like?

> But I guess `"--build-arg, GITHUB_TOKEN=$GITHUB_TOKEN,` is not parsed and treated as a literal.

If it actually resolved that command-line, then the secret would be exposed in the pod spec.

>But I guess "--build-arg, GITHUB_TOKEN=$GITHUB_TOKEN, is not parsed and treated as a literal.

This is how Linux and most OSes work. Command-line is an array of strings. The OS launches an executable and gives it that array of strings. The OS does not modify them.

The "$GITHUB_TOKEN" notation is a syntax of a bash/sh script. But you're not using bash here, so it's not resolved.

Kubernetes has it's own env variable injection syntax, but it won't work for variables set inside the container.

So the closest workaround for you would be to use a bash script command-line. For example:

```
  container:
    image: gcr.io/kaniko-project/executor:v0.24.0
    command: [
      'sh', '-ec', 'GITHUB_TOKEN=....; "$0" "$@" "--build-arg" "GITHUB_TOKEN=$GITHUB_TOKEN"'
      "dunno....",
      "--dockerfile", "Dockerfile",
      "--arg1", {inputPath: arg1},
      "--snapshotMode=redo",
      "--use-new-run=true",
      "--cache=true"
      "--build-arg, GITHUB_TOKEN=$GITHUB_TOKEN,
    ]
```

**Comment by NikeNano** [comment]
I misunderstood you @mjurkus but @Ark-kun solution seems to solve your problems as I understand it.

**Comment by mjurkus** [comment]
The simplest way would be:
- GITHUB_TOKEN initially is an environment variable where the pipeline is being built
- GITHUB_TOKEN should be passed as `ARG` to the docker image that is defined in `Dockerfile` and created by `kaniko
- It should not be exposed as plain text at any time

I'll try the suggested workaround.

**Comment by Ark-kun** [comment]
> * It should not be exposed as plain text at any time

This means that the token cannot be anywhere in the compiled pipeline.

So if you want it to reach the containerized program running on Kubernetes, it must be put into some external location accessible to the future Kaniko Pod and the code should read it. One way would be to put the token into a Kubernetes secret and mount it. Another would be to upload the token somewhere and download it from inside the pod.

**Comment by mjurkus** [comment]
Adding this
```
command: ["/kaniko/executor", "--build-arg", "GITHUB_ACCESS_TOKEN"]
```
and adding env variable via `container_op.add_env_variable` from k8s secrets worked like a charm and the actual value was not exposed in the compiled pipeline.

Not sure which KFP feature parsed `GITHUB_ACCESS_TOKEN` in `command` correctly though...
