### ISSUE TITLE
SDK API standardization for running pipeline

### ISSUE THREAD

**Issue by xinbinhuang** [kubeflow/pipelines#4795]
There are 3 ways to run a pipeline currently:

- `create_run_from_pipeline_func`
- `create_run_from_pipeline_package`
- `run_pipeline`

The first two return a `RunPipelineResult` class while the last one returns a run object, where `RunPipelineResult.run_info = run object`. This is sometimes confusing to users.

Also, we use both `params` and `arguments` in our function signatures which also cause confusion when using the SDK. I think we should standardize them to use `arguments` as they are really just arguments to the functions.

I am not sure if there are other considerations or reasons to keep both of the versions. If not, I think it will be better to consolidate the APIs. The main issue would be to main backward compatibility and use deprecation warnings.

Potential paths to approach this:

- for `functions`: swap some of the functions to be internal API and put out deprecation warnings
- `arguments vs params`: provide both in the function signatures, and warn users if they choose to use the old signature.

**Comment by Ark-kun** [comment]
`run_pipeline` is legacy and is closer to the backend API. It's left there for backwards compatibility.

**Comment by xinbinhuang** [comment]
That makes sense. Do you think we should update the documentation to specify that this's a legacy SDK API? Or put a deprecated warning to the `run_pipeline` function?

**Comment by bencwallace** [comment]
If `run_pipeline` is legacy, then what's the recommended way to run a pipeline, given its ID?

**Comment by Bobgy** [comment]
Recommend using generated backend SDK to call backend api directly, see documentation: https://kubeflow-pipelines.readthedocs.io/en/stable/source/kfp.server_api.html#kfp_server_api.api.run_service_api.RunServiceApi.create_run

`kfp.Client().runs.create_run()`

**Comment by xinbinhuang** [comment]
Instead of calling the backend SDK directly. Would it be better to create a new function called `create_run_from_pipeline_id` which has a similar interface with the other two functions (`create_run_from_pipeline_func` and `create_run_from_pipeline_package`) ? Also putting a deprecate warnings on the legacy `run_pipeline`

I think calling a pipeline by id is common and should be easier to achieve this

**Comment by Bobgy** [comment]
Yes, that seems useful. Welcome contribution on this

**Comment by Bobgy** [comment]
Just an idea, what do you think about merging all 3 methods to 1, and accept one of pipeline package, id or func?

**Comment by xinbinhuang** [comment]
I think that's a good idea! Though that would put some deprecated warnings to end users, it's not a big deal. I will put up a PR to merge these 3 methods sometime this or next week
