### ISSUE TITLE
Add "Copy from run" gesture in new run page

### ISSUE THREAD

**Issue by yebrahim** [kubeflow/pipelines#480]
A "Copy from run" button on the new run page can show a modal to select a run to copy parameters (and perhaps pipeline spec) from.

This is needed to support cases where a recurring run is created "out of" a regular run. It will also be the only way a recurring run can be created from a run with an embedded pipeline (created through Python SDK or CLI).

**Comment by vicaire** [comment]
Riley, is there anything left to do on this one? Can we close?

**Comment by rileyjbauer** [comment]
We do not currently support this gesture, so the issue should remain open.

**Comment by rileyjbauer** [comment]
Closing as too low priority
