### ISSUE TITLE
Cannot list 100 runs

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#4809]
### What steps did you take:

1. Go to Experiments/ All Runs.
2. Set number of runs per page to 100.

### What happened:

UX shows the following error:
```
{"error":"grpc: received message larger than max (13632510 vs. 4194304)","message":"grpc: received message larger than max (13632510 vs. 4194304)","code":8}
```

This also happens after going to next page several times.

### What did you expect to happen:

I expect the runs to be listed.

I also expect the server results to be smaller.

How did you deploy Kubeflow Pipelines (KFP)?
GCP Marketplace

KFP version: 1.0.0: https://www.github.com/kubeflow/pipelines/commit/2d23cc1eec1bcee09dd1cafa43580188f4ddc029

/kind bug
/area backend

**Comment by Bobgy** [comment]
I believe this is either fixed in 1.0.4 or at least in 1.1.0, there was a PR that increased request size limit

**Comment by Ark-kun** [comment]
Perhaps we should have an API method that does not return the whole workflow structures. They can get pretty big (up to 1MiB). In that case, 100 runs will take 100MiB, which is really big for an API request.

**Comment by wenmin-wu** [comment]
I came across the same problem while just listing 10 runs.

**Comment by Bobgy** [comment]
I agree with Alexey, but we will need to add some extra fields in the db to store any info we need in the list, but was only on the argo workflow.
