### ISSUE TITLE
Caching - Fix basic handling of max_cache_staleness

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#4812]
It looks like non-zero and non-empty `max_cache_staleness` values have no effect.

**Comment by difince** [comment]
Hi @Bobgy, @Ark-kun I am a new contributor, looking for my first issues
Can I give a try to this issue ?

**Comment by Bobgy** [comment]
Hi @difince, sorry this issue can probably be closed. We are now standardizing caching behavior for v2 compatible mode. So it won't be worth much updating v1 caching.

This is just about our priority, if you are interested, feel free to investigate this.

**Comment by difince** [comment]
Thank you @Bobgy
