### ISSUE TITLE
Frontend - When retry enabled, UI says "Execution was skipped" while it's not

### ISSUE THREAD

**Issue by radcheb** [kubeflow/pipelines#4814]
### What steps did you take:
When **retry** is enabled on a container_op, the UI always says it's `execution was skipped and outputs are taken from cache` even if it's the first time executed.
Actually cache was never activated on our server.

To reproduce I run the following pipeline:
```python
from kfp import dsl, Client, components, compiler

def add_fn(a: int, b: int) -> int:
    from datetime import datetime
    print("Current Time =", datetime.now().strftime("%H:%M:%S"))
    return a + b

ADD_OP = components.func_to_container_op(add_fn, base_image="library/python:3.6")

@dsl.pipeline(name="test_cache")
def test_cache_pipeline(a: int, b: int):
    add_op_with_retry = ADD_OP(a=a, b=b)
    add_op_with_retry.set_retry(1)

    add_op_without_retry = ADD_OP(a=a, b=b)

client = Client()
compiler_instance = compiler.Compiler()
compiler_instance.compile(pipeline_func=test_cache_pipeline, package_path="test_pipeline_caching.yaml")
client.upload_pipeline(pipeline_package_path="test_pipeline_caching.yaml", pipeline_name="test_pipeline_caching")
```

### What happened:
We got a misleading message:
![image](https://user-images.githubusercontent.com/5963615/99942978-d484eb80-2d70-11eb-97a4-1fc9ecba500d.png)

While UI says the other with no retry was executed:
![image](https://user-images.githubusercontent.com/5963615/99943021-e8c8e880-2d70-11eb-9cb9-043a04fcca0b.png)

### What did you expect to happen:
Expected cache to work.

### Environment:
Kubeflow `1.0.0`.

How did you deploy Kubeflow Pipelines (KFP)?
Deployed on EKS `1.15`

KFP version: `1.0.0`

KFP SDK version: `1.0.0`

### Anything else you would like to add:
Caching was disabled by default.

/kind bug
/area frontend

**Comment by Ark-kun** [comment]
@Bobgy The actually skipped pods have the `pipelines.kubeflow.org/reused_from_cache` label set to `true`. We might want to use that for the reuse detection.

**Comment by elikatsis** [comment]
The problem for this is that the function that decides whether a node was cached is wrong.
So a proper fix for this would be to change this function: https://github.com/kubeflow/pipelines/blob/ab21ec98455976bbb1f1f8b3d23710d19fbcfc9a/frontend/src/lib/StatusUtils.ts#L107-L117

Lines 109-111 should be:
```ts
if (!artifacts || !node.id || node.type !== 'Pod') {
  return false;
}
```
I can submit a PR for it

**Comment by elikatsis** [comment]
Actually, I created the PR :smile: https://github.com/kubeflow/pipelines/pull/4819
