### ISSUE TITLE
[Multi User] Move manifests from kubeflow/manifests back

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#4816]
This issue answers https://github.com/kubeflow/manifests/pull/1659.

KFP's multi user manifest patches live in https://github.com/kubeflow/manifests/tree/master/pipeline/installs/multi-user, because it was only used by full Kubeflow.
However, we start to see it'll be better if everything related to an application are developed upstream and synced to consumers like kubeflow/manifests.

It'd be better if we move the multi-user manifests back to KFP repo.

**Comment by Jeffwan** [comment]
+1.

I know a few folks just use KFP in their environment. It would be great to bring multi-user manifest back to KFP. Technically, I think user can still customize their own KFP multi-user installation without full kubeflow to fit their environment. It's better to list dependent component like profile-controller, etc in the doc. 

kubeflow/manifest can reuse `upstream` directory synced from kubeflow/pipeline

**Comment by Jeffwan** [comment]
/assign @Jeffwan 

I can help this issue.

**Comment by HassanOuda** [comment]
@Jeffwan any updates on your work with this issue? Would help me in terms of upgrading pipelines from 1.0.4 in manifests in master branch to the latest of 1.3

**Comment by Bobgy** [comment]
let's use the new issue to track this: https://github.com/kubeflow/pipelines/issues/5133
