### ISSUE TITLE
Support logical operators in conditions (and, or, not)

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#482]

**Comment by vicaire** [comment]
What is the status on this?

**Comment by Ark-kun** [comment]
> What is the status on this?

Not implemented yet.

**Comment by Ark-kun** [comment]
I hear no user requests fro this feature. It's not that hard to implement, but not trivial either (needs to build and traverse the logical expression graph).

**Comment by gaoning777** [comment]
Workaround or simple '&&' and '||' is possible with the current conditions. For example, users can write two conditions(one in another one) to represent the '&&' logic.

**Comment by dkletran** [comment]
We are currently using KFP Pipelines v2, and the conditional branching options with dsl.If, dsl.Elif, and dsl.Else are not sufficient for our needs. The ability to combine conditions logically is essential for us, and we are currently patching KFP compiling code to achieve this functionality. It would be very helpful to have this feature available in Kubeflow Pipelines.

Could this issue be reopened, or would it be better to create a new one?

**Comment by xor-xor** [comment]
Would like to have that too. And yes, the workaround mentioned [here](https://github.com/kubeflow/pipelines/issues/482#issuecomment-516940529) does its job, but the result in Vertex AI Pipelines' GUI is suboptimal [1] if someone is not aware of why such nesting was necessary.

[1] too much of unnecessary nesting + the fact that such groups are collapsed by default = potential confusion. For example, one may have a situation where the outer condition is highlighted in green, while the inner is greyed out, but only the former is immediately visible, which may lead to a wrong conclusion.
