### ISSUE TITLE
Visualization with S3 datasource results in Access Denied

### ISSUE THREAD

**Issue by SirBubbls** [kubeflow/pipelines#4843]
I am currently trying to visualize some metadata stored in a S3 bucket, in this case a simple markdown file (`s3://<bucket>/test.md`).

### What steps did you take:

AWS credentials (in base64) are configured as a secret and assigned to `ml-pipeline-ui` and `ml-pipeline` as stated in [https://www.kubeflow.org/docs/aws/pipeline/#support-s3-artifact-store](https://www.kubeflow.org/docs/aws/pipeline/#support-s3-artifact-store).
The relevant pipeline source code is shown under 'Additional Information'.
```
spec:
      containers:
      - env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY_ID
              name: aws-secret
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: aws-secret
```
Credentials appear to be correctly configured, because the components can write and read to/from S3 with boto.
In addition to that, `AWS_ACCESS_KEY` and `AWS_SECRET_ACCESS_KEY` environment variables are correctly set in `ml-pipeline-ui` and `ml-pipeline`.

### What happened:
Unfortunately I still get ` Failed to get object in bucket <bucket> at path test.md: S3Error: Access Denied` on opening the visualization tab of the pipeline component.

![request](https://user-images.githubusercontent.com/30483183/100627241-0ecd2a80-3327-11eb-9b31-5fdc27a43995.PNG)

To rule out any permission problems I already gave the user S3 Full Access permissions and I didn't get any different results.
I don't use a custom AMI so #4436 seems to not be relevant in my case.

Is this a problem with minio interfering in some way or did miss something while configuring kubeflow?

### Environment:
During deployment, I followed the 'Install Kubeflow on AWS' Guide ([https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/](https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/)) and deployed to an AWS EKS cluster.
> Used the no authentication config: [https://raw.githubusercontent.com/kubeflow/manifests/v1.1-branch/kfdef/kfctl_aws.v1.1.0.yaml](https://raw.githubusercontent.com/kubeflow/manifests/v1.1-branch/kfdef/kfctl_aws.v1.1.0.yaml)

KFP version: `1.0.0`
KFP SDK version:
```
kfp                      1.1.1
kfp-pipeline-spec        0.1.2
kfp-server-api           1.0.4
``` 

#### Pipeline & Component
```python
def train() -> NamedTuple(
        'Outputs',
        [
            ('mlpipeline_ui_metadata', 'UI_metadata')
        ]
    ):
    from collections import namedtuple

    ...

    metadata = {
        'outputs': [
            {
                'source': 's3://<bucket>/test.md',
                'type': 'markdown'
            }
        ]
    }
    output = namedtuple('Outputs', ['mlpipeline_ui_metadata'])
    return output(json.dumps(metadata))

...

train_op = kfp.components.func_to_container_op(train, base_image='tensorflow/tensorflow:latest')

@dsl.pipeline(
    name='...',
    description='...'
)
def training_pipeline():
    t = train_op().apply(use_aws_secret('aws-secret', 'AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY'))
```

#### Artifact
```
{
  "name": "mlpipeline-ui-metadata",
  "optional": true,
  "path": "/tmp/outputs/mlpipeline_ui_metadata/data",
  "s3": {
    "accessKeySecret": {
      "key": "accesskey",
      "name": "mlpipeline-minio-artifact"
    },
    "bucket": "mlpipeline",
    "endpoint": "minio-service.kubeflow:9000",
    "insecure": true,
    "key": "artifacts/training-pipeline-7b4ch/training-pipeline-<...>/mlpipeline-ui-metadata.tgz",
    "secretKeySecret": {
      "key": "secretkey",
      "name": "mlpipeline-minio-artifact"
    }
  }
}
```

/kind bug
/area frontend

**Comment by mbaijal** [comment]
Hi @SirBubbls, 
I am seeing an issue similar to yours and was wondering what the fix was for you ?

Thanks,
Meghna Baijal
