### ISSUE TITLE
Sample tests should test the SDK the way the users install it

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#4848]
Related to https://github.com/kubeflow/pipelines/issues/4847

**Comment by DavidSpek** [comment]
When looking at the releases page, the SDK is installed alongside `kfp-server-api`. If installing from master, I think both the SDK and `kfp-server-api` should both be installed. Or is there a reason for allowing version mismatches between SDK and `kfp-api-server`?

**Comment by DavidSpek** [comment]
I think this can be closed as this was discussed in the linked issue. 

https://github.com/kubeflow/pipelines/issues/4847#issuecomment-737013872

**Comment by Bobgy** [comment]
agree with that
/close

Feel free to reopen if you doesn't think this way
