### ISSUE TITLE
kubeflow-pipelines-tfx-python36 test failing

### ISSUE THREAD

**Issue by chensun** [kubeflow/pipelines#4853]
Sample log:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/4845/kubeflow-pipelines-tfx-python36/1333561959861194752

**Comment by chensun** [comment]
Comparing the logs from the last passed run and the first failing one, it might be related to pip version.
Passed run: pip-20.2.4
Failed run: pip-20.3

**Comment by numerology** [comment]
Playing in https://github.com/kubeflow/pipelines/pull/4852
