### ISSUE TITLE
[Recurring Runs/Jobs] Cannot delete/disable/enable jobs after reinstalling to a new cluster when using managed storage

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#4862]
**UPDATE**: full instructions to recover recurring runs after a reinstallation using managed storage have been added in https://github.com/kubeflow/pipelines/issues/4862#issuecomment-759909555

### What steps did you take:

1. install via managed storage
2. create some jobs (recurring runs)
3. delete the cluster
4. reinstall to a different cluster with the same managed storage

### What happened:

try to delete/disable/enable any restored jobs, and get the following error message

> {"error":"Enable/Disable job failed: InternalServerError: Check job exist failed: scheduledworkflows.kubeflow.org "REDACTED_JOB_NAME" not found","message":"Enable/Disable job failed: InternalServerError: Check job exist failed: scheduledworkflows.kubeflow.org "REDACTED_JOB_NAME" not found","code":13,"details":[{"@type":"type.googleapis.com/api.Error","error_message":"Internal Server Error","error_details":"Enable/Disable job failed: InternalServerError: Check job exist failed: scheduledworkflows.kubeflow.org "REDACTED_JOB_NAME" not found"}]}

The jobs also no longer submit any runs when their schedule applies.

### What did you expect to happen:

The jobs should still be usable.

/kind bug

**Comment by Bobgy** [comment]
Workaround to re-enable a job is to clone it, either in KFP UI or from KFP SDK.

cloning a job via KFP SDK is essentially:
1. get the job's definition via job get api
2. create a new job with different name, but exactly the same payload as the gotten job

It's also possible to iterate through all the old jobs and cloning them to restore them.

However, without directly connecting to KFP DB, it's not possible to delete a job.

**Comment by Bobgy** [comment]
The root cause here is that, a scheduledworkflow custom resource is expected to live in the kubernetes cluster.
Restoring DB in a new cluster won't restore the CRs.

However, all the information in the CRs are still stored in the DB. So it's possible to recreate the CRs from information in the DB. The problem is, when shall we trigger this process?

A naive solution I am thinking about is that, maybe we can add a new job api endpoint to recreate/resync a scheduledworkflow CR from data in the DB, so that after reinstalling KFP, user also need to run a script to get all CRs restored.

These are my early thoughts, could there be a solution that restores CRs automatically while not creating too much extra workload when the process is not necessary.

**Comment by Bobgy** [comment]
I think #4871 and #4872 should be enough to address this problem:
1. When swf not found, delete should still succeed
2. When swf not found, enabling a job should recover swf according to data in DB

So after reinstallation with existing data in DB, user can run a script that goes over all the jobs and call job enable api to recover them all.

**Comment by chensun** [comment]
> However, all the information in the CRs are still stored in the DB. So it's possible to recreate the CRs from information in the DB. The problem is, when shall we trigger this process?
> 
> A naive solution I am thinking about is that, maybe we can add a new job api endpoint to recreate/resync a scheduledworkflow CR from data in the DB, so that after reinstalling KFP, user also need to run a script to get all CRs restored.

Might be a silly question, if all information about a CR is stored in the DB, why can't we just restore/resync it automatically during api-server start? Did I miss any technical challenge? or it's just some development cost?

**Comment by chensun** [comment]
> I think #4871 ~and #4872~ should be enough to address this problem:
> 
> 1. When swf not found, delete should still succeed
>    ~2. When swf not found, enabling a job should recover swf according to data in DB~
> 
> So after reinstallation with existing data in DB, user can run a script that
> 
> 1. goes over all the old jobs
> 2. call get job API to get existing information (and probably store it somewhere as backup)
> 3. call job delete API to unclutter UI from old Jobs
> 4. call job create API using information from step 2 + add noCatchup=true option to restore the jobs back to working state, because a caveat for this workaround is that, all user job's past run status are lost, if we do not provide noCatchup=true, it will try to backfill all scheduled time in the interval even if they are in the past.
> 
> TODO: give a sample of this script

Sounds reasonable to me. Thanks for driving this!

> (and probably store it somewhere as backup)

One nitpick on re this. If this is recommended, which I think it should, it better to also describe a plan on how to use this backup for recovery in case something went wrong. 
BTW, given the title of this issue mentions managed storage. Do you know if we use the daily backup (snapshot) feature of managed storage?

**Comment by Bobgy** [comment]
> One nitpick on re this. If this is recommended, which I think it should, it better to also describe a plan on how to use this backup for recovery in case something went wrong.

The upgrade instructions will be exactly the same as reinstallation (recovery).

> BTW, given the title of this issue mentions managed storage. Do you know if we use the daily backup (snapshot) feature of managed storage?

We leave it to users to configure backup, for example Cloud SQL already has this feature. They can read Cloud SQL documentation and do that by themselves.

**Comment by Bobgy** [comment]
P0 issue fixed and released
TODO(P1): sample script to restore recurring runs after reinstallation.

**Comment by Bobgy** [comment]
I tried to recover by myself e2e and realized a problem with the previous fix:
I'm getting this error message:
```
scheduledworkflows.kubeflow.org "datang2fb" is forbidden: User "system:serviceaccount:kfp:ml-pipeline" cannot delete resource "scheduledworkflows" in API group "kubeflow.org" in the namespace "kubeflow"
```

because I initially installed KFP in `kubeflow` namespace, and then deleted it and reinstalled in `kfp` namespace.
KFP kept DB data via managed storage, so it knows previously created scheduledworkflows (swf) were in "kubeflow" namespace. When we try to delete a recurring run, KFP API tries to delete the underlying swf, but the swf is in "kubeflow" namespace, so KFP API do not have permission to do so. So it fails.

**Comment by Bobgy** [comment]
I think for the moment, we should only support reinstalling KFP in the same namespace (but it can be the same namespace name in a different cluster).

**Comment by Bobgy** [comment]
I built some scripts as an example for how to recover recurring runs after a reinstall using managed storage:

This script dump recurring runs data as a local JSON file for backup purposes.
```
# dump_jobs.py

import kfp
import json
import datetime

HOST = '<KFP-HOST>'

client = kfp.Client(host=HOST)

page_token = None
jobs = []
while True:
    response = client.jobs.list_jobs(page_token=page_token)
    jobs.extend(response.jobs)
    print('Loaded {}/{} jobs'.format(len(jobs), response.total_size or 0))
    if not response.next_page_token:
        break
    else:
        page_token = response.next_page_token
print('Found {} jobs'.format(len(jobs)))
print('Dumping them to ./jobs_dump.json...')


def date_handler(obj):
    if not isinstance(obj, (datetime.datetime, datetime.date)):
        raise Exception('Unserializable object')
    else:
        # Serialize datetime as isoformat string.
        # isoformat strings are valid representation of datetime in requests to KFP API.
        return obj.isoformat()


with open('jobs_dump.json', 'w') as outfile:
    json.dump([job.to_dict() for job in jobs],
              outfile,
              indent=4,
              default=date_handler)
```

This script:
1. loads from local recurring run JSON data
2. delete recurring runs
3. clone new recurring runs from local data and by default mark them as disabled + no catchup, so that users can enable them one by one later (if I don't disable them, KFP will immediately start scheduling new runs)
```
# recover_jobs.py

import kfp
import json
import kfp_server_api

jobs = None
path = 'jobs_dump.json'
with open(path, 'r') as inputfile:
    jobs = json.load(inputfile)
print('Loaded {} jobs from {}'.format(len(jobs), path))

HOST = '<KFP-HOST>'
client = kfp.Client(host=HOST)
for job in jobs:
    print('=== recovering next job ===')
    refs = job.get('resource_references', [])
    has_creator_ref = [
        ref for ref in refs if ref.get('relationship') == 'CREATOR'
    ]
    if has_creator_ref:
        # a job with creator ref (either created by pipeline or version) do not need
        # the workflow manifest snapshot
        pipeline_spec = job.get('pipeline_spec')
        del pipeline_spec['workflow_manifest']
    # When recovering jobs, change their config to no catchup and disabled by
    # default to not trigger pipelines immediately.
    # You may edit the lines below to accommodate your own needs.
    job['no_catchup'] = True
    was_enabled = job.get('enabled') or False
    job['enabled'] = False
    try:
        client.jobs.delete_job(job.get('id'))
    except kfp_server_api.rest.ApiException as e:
        if e.status != 404:
            raise e
        print('Warning: Job with ID {} does not exist'.format(job.get('id')))
    cloned_job = client.jobs.create_job(body=job)
    print(
        'Job with name "{}" and ID "{}" cloned with no_catchup=True & enabled=False'
        .format(cloned_job.name, cloned_job.id)
    )
    if was_enabled:
        print(
            'ACTION REQUIRED: please manually enable cloned job "{}"'.format(
                cloned_job.id
            )
        )

```

**Comment by Bobgy** [comment]
Instructions provided and verified the reinstallation e2e by myself, closing for now.

Feel free to reply with more questions if you couldn't figure out sth.

**Comment by Bobgy** [comment]
Ohh, https://github.com/kubeflow/pipelines/issues/6001 is the right place to continue discussions
