### ISSUE TITLE
integer array is not passed to dsl.parallelfor

### ISSUE THREAD

**Issue by nurvenur12** [kubeflow/pipelines#4863]
I am sending a list of dictionary to dsl.parallelfor function. In the dictionary, one of the item is an array of integer.
dict1 =. [ {'a':1, 'b':2, 'c':[3,4]]]

    with dsl.ParallelFor(ADVERTISERS) as item:
        a = item.a
        b = item.b
        c = item.c

When I execute the operator, I receive the following error:

This step is in Error state with this message: withItems[0][c] expected string or number. received: [3 4]

Is it possible to support arrays in the dictionaries which are sent to parallelfor operator?

**Comment by Ark-kun** [comment]
This is a know Argo issue that's recently fixed.
This will be fixed in KFP once we upgrade to latest Argo.
