### ISSUE TITLE
ListExperiment requires filtering by namespace.

### ISSUE THREAD

**Issue by ajinkya933** [kubeflow/pipelines#4873]
### What steps did you take:
I am following Kubeflow Pipeline API: https://www.kubeflow.org/docs/pipelines/reference/api/kubeflow-pipeline-api-spec/

To get the list of pipelines I do GET request on url `http://<istiourl>/pipeline/apis/v1beta1/pipelines` as follows

POSTMAN response:
<img width="742" alt="Screenshot 2020-12-06 at 11 28 56 PM" src="https://user-images.githubusercontent.com/17012391/101288201-494d3080-381b-11eb-8a33-64a4804ff022.png">

For getting pipelines list everything works good. However, when I try to list the experiments using GET request on: http://<istiourl>/pipeline/apis/v1beta1/experiments

I get error: `Invalid input error: Invalid resource references for experiment. ListExperiment requires filtering by namespace.`

its as follows on postman:

<img width="737" alt="Screenshot 2020-12-06 at 11 34 31 PM" src="https://user-images.githubusercontent.com/17012391/101288271-bcef3d80-381b-11eb-99b3-9669928384bc.png">

I don't know how to mention namespace in this GET request. I have tried adding namespace into header section:

<img width="493" alt="Screenshot 2020-12-06 at 11 36 58 PM" src="https://user-images.githubusercontent.com/17012391/101288319-f2942680-381b-11eb-981d-7b3659730468.png">

but it gives same error: `ListExperiment requires filtering by namespace.` as above

How do I get experiment IDs properly ?
/kind bug

**Comment by ajinkya933** [comment]
^ @Bobgy  any pointers on what may be going wrong ?

**Comment by Bobgy** [comment]
@ajinkya933 starting from Kubeflow 1.1, KFP has enabled multi-user mode, so you can only filter by a namespace.
Take a look at `resource_key.type` and `resource_key.id` fields, they are the proper way to filter by namespace.

**Comment by ajinkya933** [comment]
I tried with `resource_key.type` as a Header in POSTMAN.   I get:

![Screenshot from 2020-12-07 19-05-21](https://user-images.githubusercontent.com/17012391/101357266-35f3a100-38bf-11eb-9923-3d6b9242b43e.png)

What will be a correct Postman request ?

**Comment by Bobgy** [comment]
Hi @ajinkya933, they are query params in the documentation, not headers.

**Comment by ajinkya933** [comment]
Please let me know correct body format. I tried passing these in the body as follows: (https://www.kubeflow.org/docs/pipelines/reference/api/kubeflow-pipeline-api-spec/#sw-default-produces)

![body](https://user-images.githubusercontent.com/17012391/101377584-056c3100-38d8-11eb-8b35-326afabb498a.png)

but still have same error :(

**Comment by Bobgy** [comment]
@ajinkya933 let me give you an example
```
GET https://<host>/pipeline/apis/v1beta1/experiments?page_token=&page_size=10&resource_reference_key.type=NAMESPACE&resource_reference_key.id=default-profile
```
They should be in query params in the URL, not in body nor header.

**Comment by ajinkya933** [comment]
Thanks I replaced `default-profile` with `ajadmin` which is my namespace name and it works well.
