### ISSUE TITLE
The KFP run ID should be a property of each ml-metadata execution

### ISSUE THREAD

**Issue by schmidt-jake** [kubeflow/pipelines#4876]
AFAIK, passing `RUN_ID_PLACEHOLDER` into a component is the only way to link the run ID to the `ml-metadata` system. However, the run ID obviously differs for every run and so causes cache misses.

The real issue is that kubeflow doesn't automatically link the kfp run id to the executions of each pipeline step. It seems to attempt this — there is a `run_id` property on each execution by default, but it is not the kfp run id. Instead, it is `my-pipeline-name-[a-z]{5}`, and it's always the same as the default `pipeline_name` property. What does this default `run_id` correspond to, and how is it useful? Why is it the same as `pipeline_name`?

The workaround is to pass `RUN_ID_PLACEHOLDER` / `"{{workflow.uid}}"` into the component and have it manually update the metadata execution object in the ml-metadata store. But this causes the cache missing issue.

Is there a better way to link the kfp run id to my executions or am I missing something?

I'm running KFP standalone v1.0.4.

**Comment by capri-xiyue** [comment]
This feature request is in our road map and we will resolve it in the near future.

**Comment by kvamshi** [comment]
create_run_from_pipeline_func returns RunPipelineResult, which has run_id attribute. This way you can link the runs you submitted with the run id.

```
client = kfp.Client(host)
result = client.create_run_from_pipeline_func(…) 
result.run_id
```

**Comment by schmidt-jake** [comment]
Thanks for that suggestion @kvamshi. Would that solve the cache missing issue?
