### ISSUE TITLE
Feature request: functionality abstraction based on metadata types

### ISSUE THREAD

**Issue by karlschriek** [kubeflow/pipelines#4878]
Somewhat overdue by now, but as promised, herewith a request on a feature I would like to  see incorporated into the next iteration of KFP.

@Bobgy, @aronchick, @neuromage, @IronPan, @lukemarsden

This relates to the discussions we have been having on well-defined types for Artifacts, Executions, Contexts etc. (as is also foreseen by the MLMD data model). Such types are I think not only useful because one could standardise their properties, thereby always knowing what information is potentially available for each type, but one could also think of these types in a programmatic sense, meaning they could be regarded as classes that have a certain set of methods associated with them.

There are a few different use-cases that could benefit from something like this, so let me sketch out a small example.

A Data Scientist writes small python function that takes a Keras model and a Numpy array as input. The function uses the model to make a prediction and returns that prediction as an output, i.e.:

```
def predict(model, data):
    return model.predict(data)
```

In this simple function we have the following relevant metadata types:
- Artifacts: model, data, predictions
- Execution: predict
- Context: pipeline run / experiment / project / etc.

The Data Scientist wants to run this function as a component within a pipeline and wants KFP to take care of:
1. Fetching the inputs from and writing the output to remote storage
2. Logging metadata related to all Artifacts, Executions and Contexts

The user could alter his `predict` function to do those things explicitly, e.g.:

```
def predict(model_uri, data_uri, predictions_uri):

     import load_keras_model_from_remote, load_numpy_array_from_remote, write_numpy_array_to_remote, write_metadata
     model = load_keras_model_from_remote(model_uri)
     data = load_numpy_array_from_remote(data_uri)
     predictions=model.predict(data)

    write_numpy_array_to_remote(data)

    log_metadata(uri=predictions_uri, type="Data.NumpyArray", properties={"..."})    
```

But he or she would rather this part be abstracted away completely.

Instead, we could offer the ability to compose classes (types) and associate methods such as `save`, `load`, `read_metadata`, `write_metadata` with them.

This would look something like the following:

```
@kfp.intelligent_component(
   inputs={ 
         "model": metatypes.artifacts.s3.model.KerasModel
         "data": metatypes.artifacts.s3.data.NumpyArray
    },
   outputs={
        "predictions": metatypes.s3.data.NumpyArray 
   },
  image="myrepo/myimage:latest"
  execution_type: "metatypes.executions.Prediction"
)
def predict(model, data):
    return model.predict(data)
```

The user would then define his pipeline as follows (passing only the URIs of the various data types)

```
@kfp.pipeline(...)
def my_pipeline()
     predict(model=model_uri, data=data_uri, predictions=prediction_uri)

```

And could execute this as follows (additionally adding additional "Contexts"):

`kfp.Client().create_run_from_pipeline_func(my_pipeline, context = {"project": "my project", "experiment": "my experiment", ...})`

the kfp compiler then takes care of laying all of this out as follows:

```
model = metatypes.artifacts.s3.model.KerasModel.load(model_uri) #fetches model from S3 and returns it a Keras model object
data = metatypes.artifacts.s3.data.NumpyArray.load(data_uri) #fetches data from S3 and returns is as Numpy array

def predict(model, data):
    return model.predict(data)

predictions = predict(model, data)

metatypes.artifacts.s3.data.NumpyArray.save(predictions) 
execution_id = metatypes.executions.Prediction.log()
run_id = metatypes.contexts.Run.log(execution_id) #log Run context
for context_type, context in contexts.items():
    metatypes.contexts.log(context_type, context ) #log all other custom contexts
```

One could also go a few steps further and even standardise `predict` as a specific type of Execution, thereby strongly typing which data types are expected as inputs and give as outputs. The "load" functions could also first perform a check against MLMD to see if the URI in question exists there and is of the correct type.

I realise that this would not be trivial to create. For one thing, this would only be useful if it is extensible and users are able to compose their own metatypes / associate their own methods with them. There is also the question of inheritence, i.e. what kind of base types we would offer and how they would be defined to interface nicely with MLMD.

Thoughts?

**Comment by neuromage** [comment]
Thanks Karl! Really nice write up!

We have been having very similar thoughts, except that we did not consider the auto-loading/auto-saving aspect of the artifact like you have here. That's a nice idea, but I think the loading/saving part will need to be bundled into the component rather than the pipeline itself.

Using Python classes to represent common Artifact metadata, combined with a simplified component interface, is also an approach we're keen to explore. As an example, we're considering a function that would look like the following, using type annotations to indicate inputs/outputs and their types:

```py
from kfp.dsl import InputArtifact, OutputArtifact, Dataset, Model

@dsl.component()
def my_trainer(training_data: InputArtifact[Dataset],  # Dataset is a reference to the passed in artifact
               model: OutputArtifact[Model],
               num_iterations: int = 10): 
  """My Training component."""
  # Access URI of input artifact.
  with tf.io.gfile.GFile(os.path.join(training_data.uri, '...'), 'r') as f:
    contents = f.read()
    ....

  # Access URI of output artifact.
  with tf.io.gfile.GFile(os.path.join(model.uri, '...'), 'r') as f:
    # Write to f
    ....
  
  # Update output metadata properties.
  model.properties['accuracy'] = 0.9
```

We're also considering grouping pipeline runs by pipeline name, so one can run something like this from the notebook to obtain the input parameters and output metrics for comparison/analysis:
```
kfp.get_pipeline_as_dataframe(pipeline='My-Pipeline', num_runs=5 # get 5 most recent runs)
```

Thoughts on the above?

/cc @chensun 
/cc @numerology 
/cc @james-jwu 
/cc @paveldournov

**Comment by numerology** [comment]
> except that we did not consider the auto-loading/auto-saving aspect of the artifact like you have here.

Yes the current plan we've been exploring delegates loading/saving of the actual content of artifacts to the user code. I think if we want to make it part of the artifact ontology then the SDK code baked in the user container needs to have the ability to handle different file systems (local/GCS/HDFS/S3 etc.), which is less scalable.

Other than that I think we're pretty aligned in the spirit.

**Comment by karlschriek** [comment]
I agree that loading/saving needs to be handled within the component and therefore either needs to be present on the base image (or there needs to be some pre-execution step that installs additional requirements, though I'm not really sure we want that).

I also don't think the KFP SDK should support all different types of file systems (though I think something like that could be a perfectly valid little open source project on it's own).  I more have in mind that KFP could provide a clean interface for this that would at least allow users to separate the core application code, i.e.: 

```
def predict(model, data):
    return model.predict(data)
```

from the data saving and loading (and metadata logging) parts. That allows the Data Scientist to maintain his core ML Code separately from what is needing for a Pipeline run and he (or perhaps an ML Engineer if the reponsibilities are split) can swap in different backends as needed when defining the component.

This could perhaps be dealt with via reflection, e.g:

```
@kfp.intelligent_component(
   inputs={ 
         "model": "my_metatypes.artifacts.s3.model.KerasModel"
         "data": "my_metatypes.artifacts.s3.data.NumpyArray"
    },
   outputs={
        "predictions": "my_metatypes.s3.data.NumpyArray"
   },
  image="myrepo/my_image_for_s3_backend:latest" #this image has to have the package "my_metatypes" installed
  execution_type="my_metatypes.executions.Prediction"
)
def predict(model, data):
    return model.predict(data)
```

I.e. when defining the component we pass text strings for where on the selected image to find the metatypes to use. These metatypes then follow a strict abstract base class definition, such as:

```
from kfp.metatype import Artifact, Execution
class KerasModel(Artifact):
    def save(**kwargs):
        ...
    def load(**kwargs):
        ...
    def log_metadata(**kwargs):
        ...

class Prediction(Execution):
    def log_metadata(**kwargs)
        ...
```

So when the component is actually executed, the decorator wraps `predict` as follows:

```
def get_metatype_object(metatype_string):
    # use reflection to import metatype objects
    # (at this point there should probably be some checks whether the modules are actually available)
    module_name, obj_name = metatype_string.rsplit(".",1) # split module name from object name
    module = importlib.import_module(module_name) # load for example  the module my_metatypes.artifacts.s3.data
    metatype = getattr(module, obj_name) # load NumpyArray from the module
    return metatype 
    
input_kwargs={}

for kwarg_name, metatype_string in inputs.items():
    input_kwargs[kwarg_name] = get_metatype_object(metatype_string).load() # load the artifact

# execute the application code
output = predict(**kwargs)

# log outputs
for kwarg_name, metatype_string in ouputs.items():
    metatype=get_metatype_object(metatype_string)
    metatype.save(output[kwarg_name]) # save the artifact
    metatype.log_metadata(output[kwarg_name]) # log its metadata

# log execution
get_metatype_object(execution_type).log_metadata()

# log run and other contexts (defined by pipeline, rather than be component, since context is only available then)
run_id = metatypes.contexts.Run.log(execution_id) #log Run context
for context_type, context in contexts.items():
    metatypes.contexts.log(context_type, context ) #log all other custom contexts
```


If you have a clearly defined interface like that you enable:
1. People to create their own metatypes with specific functionality they need and have KFP inject them as required.
2. Open up the possibility for someone to create a standalone library that deals with different backends / loading functions (e.g. what if instead of reading an entire numpy array I would rather stream it in batches? Or maybe I want to read individual pictures, in batches, preprocessed into an array?
3. Keep all of this outside of the core application code

**Comment by aronchick** [comment]
I'm similarly of the position that I'd prefer all underlying infra is abstracted from data scientists - that is to say I'd prefer that someone (SRE?) mounts a PV, and the data scientist simply says `my_metatypes.artifacts.model.KerasModel`. 

I worry a bit we're mixing code and configuration. As a silly example, what if we had an external file that described steps/types, and then the code implemented it.

So, to extend the above:
```
components:
  train:
    inputs:
        model:
            schema_type: my_metatypes.artifacts.model.KerasModel
            schema_version: 1.8.3
        data:
            schema_type: my_metatypes.artifacts.data.NumpyArra
            schema_version: 3.1.8
    execution_parameters:
        num_iterations: 10
        nodes: 20
        RAM: 8Gi
        GPU:
            number: 2
            type: A100
            optional_parameters:
                CUDA_version: 11.1.74x86
    outputs:
        predictions: 
            type: my_metatypes.s3.data.NumpyArray
            version: 1.0.1
```

Then the function gets even simpler:
```
@dsl.component(train)
def my_trainer(training_data, model, num_iterations):
    ...
```

Though this may be a bit too abstract. The reason I was angling in this direction is it means places where things need to change (e.g. object version types, execution parameters, etc) are now separated from code, so diffing/lineage/etc becomes much easier to track.

**Comment by aronchick** [comment]
> I.e. when defining the component we pass text strings for where on the selected image to find the metatypes to use. These metatypes then follow a strict abstract base class definition, such as:
> 
> ```
> from kfp.metatype import Artifact, Execution
> class KerasModel(Artifact):
>     def save(**kwargs):
>         ...
>     def load(**kwargs):
>         ...
>     def log_metadata(**kwargs):
>         ...
> 
> class Prediction(Execution):
>     def log_metadata(**kwargs)
>         ...
> ```

I like this a lot

> # execute the application code
> outputs = predict(**input_kwargs) #ouputs here should be a dict. Please just imagine I already magically dealt with that here

The challenge here is as a data scientist, it obscures all the details of the input. I'd prefer it was more visible.
