### ISSUE TITLE
TypeError: Sagemaker - Deploy Model() got an unexpected keyword argument 'update_endpoint'

### ISSUE THREAD

**Issue by jchaudari** [kubeflow/pipelines#4888]
### What steps did you take:
[A clear and concise description of what the bug is.]

I am use the re usable Sagemaker Components for building kubeflow pipelines.

sagemaker_train_op = components.load_component_from_url('https://raw.githubusercontent.com/kubeflow/pipelines/cb36f87b727df0578f4c1e3fe9c24a30bb59e5a2/components/aws/sagemaker/train/component.yaml')
sagemaker_model_op = components.load_component_from_url('https://raw.githubusercontent.com/kubeflow/pipelines/cb36f87b727df0578f4c1e3fe9c24a30bb59e5a2/components/aws/sagemaker/model/component.yaml')
sagemaker_deploy_op = components.load_component_from_url('https://raw.githubusercontent.com/kubeflow/pipelines/cb36f87b727df0578f4c1e3fe9c24a30bb59e5a2/components/aws/sagemaker/deploy/component.yaml')

When i am trying to update the endpoint that already exists 

piece of code i used to update the endpoint.

**#deploy the pipeline
prediction = sagemaker_deploy_op(
        region=aws_region,
        endpoint_name='Endpoint-price-prediction-model',
        endpoint_config_name='EndpointConfig-price-prediction-model',
        update_endpoint=True,
        model_name_1 = create_model.output,
        instance_type_1='ml.m5.large'
    )
# compiling the pipeline
kfp.compiler.Compiler().compile(car_price_prediction,'car-price-pred-pipeline.zip')**

### What happened:
I am getting this error 
TypeError: Sagemaker - Deploy Model() got an unexpected keyword argument 'update_endpoint'

I think while compile the pipeline kfp is throwing this error.can you suggest me or help me out in this

Traceback (most recent call last):
--
414 | File "pipeline.py", line 94, in <module>
415 | kfp.compiler.Compiler().compile(car_price_prediction,'car-price-pred-pipeline.zip')
416 | File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/kfp/compiler/compiler.py", line 920, in compile
417 | self._create_and_write_workflow(
418 | File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/kfp/compiler/compiler.py", line 972, in _create_and_write_workflow
419 | workflow = self._create_workflow(
420 | File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/kfp/compiler/compiler.py", line 813, in _create_workflow
421 | pipeline_func(*args_list)
422 | File "pipeline.py", line 85, in car_price_prediction
423 | prediction = sagemaker_deploy_op(
424 | TypeError: Sagemaker - Deploy Model() got an unexpected keyword argument 'update_endpoint'

### What did you expect to happen:
to update the endpoint without any issue
### Environment:

using kfp 1.1.2
sagemaker 2.1.0

How did you deploy Kubeflow Pipelines (KFP)?

KFP version: 

KFP SDK version: 
kfp-1.1.2.tar.gz 

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

Please help me out 

/kind bug

**Comment by numerology** [comment]
/assign @mameshini 
/assign @PatrickXYS 

Do you mind taking a look? Thanks

**Comment by PatrickXYS** [comment]
@numerology Thanks!

@akartsky @RedbackThomson Can you take a look?

**Comment by mbaijal** [comment]
Hi @jchaudari, 
Thanks for reporting the issue, we are taking a look at it. 

Thanks,
Meghna

**Comment by mbaijal** [comment]
Hi @jchaudari, 
Are you certain you are using the latest version of the components ? The attached yaml files show that you are using version 0.3.0 of the image which is very old. This feature was added more recently in version 0.9.0 - 
https://github.com/kubeflow/pipelines/blob/master/components/aws/sagemaker/Changelog.md. 

Could you please try with the newer version and let us know if that fixes your issue ?
Thanks,
Meghna Baijal

**Comment by RedbackThomson** [comment]
If there aren't any further issues, we'll close this by the end of the week. Otherwise, let us know.
