### ISSUE TITLE
Unable to visualize table in OutputViewer

### ISSUE THREAD

**Issue by StefanoFioravanzo** [kubeflow/pipelines#489]
I am trying to visualize some artifacts in the OutputViewer with no success.
I have the following `metadata.json` file in the root of the container's file system:

```json
{
	"version": 1,
	"outputs": [{
		"type": "table",
		"source": "/linear_model_metrics.csv",
		"header": ["Epoch", "Loss_te", "Acc", "Loss_tr"],
		"format": "csv"
	}]
}
```

The file `linear_model_metrics.csv` is in the file system root as well. _Comma separated_ with first line as header. In the Pipelines UI I have a blank page in the Artifacts tab, no errors thrown.

**Comment by yebrahim** [comment]
Currently, the Pipelines UI reads the artifact data from the storage service directly, and only GCS and minio are supported at the moment, adding support for more services is welcome of course. If your data is on GCS, the `source` should be a `gs://...` path.

We are currently exploring better ways to mount/read this data such that it's easier to keep the data in the cluster, or in other types of storage.

/cc @Ark-kun.

**Comment by StefanoFioravanzo** [comment]
Thank you for the response. For sure it would be helpful to be able to load files directly from the container's local file system. Any info regarding the timeline or priorities on these features?

**Comment by IronPan** [comment]
@StefanoFioravanzo Just wondering did you mount the volume through the container Op, and writes linear_model_metrics.csv to it directly?

**Comment by StefanoFioravanzo** [comment]
@IronPan I mounted the volume like you suggested in #477 . And yes I wrote `linear_model_metrics.csv` directly form the container.

**Comment by swiftdiaries** [comment]
Is this still the case? 
Does the source field have to be either in GCS or minio?

**Comment by SinaChavoshi** [comment]
+1 on supporting local mount. This is absolutely necessary for on-prem deployment. I'm loading the data to an nfs volume in preprocessing, training steps ... would be great to read it to tensor-board directly from there.

**Comment by jinchihe** [comment]
+1 for supporting local storage mounted from PersistentVolume.

**Comment by zwqjoy** [comment]
+1 for supporting local storage mounted from PersistentVolume or Volume

**Comment by Dhaval08** [comment]
Any update on this? +1 for support for local sources

**Comment by Bobgy** [comment]
https://github.com/kubeflow/pipelines/pull/4236 supports this feature request.
