### ISSUE TITLE
Kubeflow Pipeline upload from Enterprise GitHub OR Google Storage

### ISSUE THREAD

**Issue by saurovn** [kubeflow/pipelines#4897]
/kind feature

**Why you need this feature:**
We have Kubeflow (1.0) installed in GCP and would like to upload pipelines hosted in Enterprise GitHub Or Google Storage.

Currently "Import by URL" option provides option to import pipeline files only from public GitHub and "Upload a file" option provides option to import from local.

**Describe the solution you'd like:**

It would be helpful if the Upload Pipeline in Kubeflow UI provides a option to import from Google Storage or Enterprise GitHub.

**Anything else you would like to add:**
Question - If there is any existing option to import pipelines from Enterprise GitHub Or Google Storage ?

**Comment by Bobgy** [comment]
Transferred the issue to pipelines repo.

**Comment by Bobgy** [comment]
@saurovn the hard question is how should KFP API server authenticate to enterprise GitHub or Google Storage?

It's probably easier with Google Storage. Any ideas how enterprise GitHub can fit in?

**Comment by DavidSpek** [comment]
Initially I thought it might be possible to use a namespaces secret with a Personal Access Token. However, I don't think it would be (easily) possible to implement this for multiple users. 

As the discussion is regarding the UI, would it be an option to use the [web application flow](https://docs.github.com/en/enterprise-server@2.21/developers/apps/authorizing-oauth-apps#web-application-flow) with an "authenticate" button in the ui? The question then is, how does the KFP api keep the user access tokens separated by namespace? Even with a very quick time out, if 2 users would try to download something at the same time they could access files from one another.
