### ISSUE TITLE
Date pickers in NewRun do not handle invalid days well

### ISSUE THREAD

**Issue by rileyjbauer** [kubeflow/pipelines#49]
For example, if a user sets the `start date` to 2/31/2018, the form will show that date, but component will set the `start date` to `undefined`.

We should either add constraints on the days ourselves, or at least show an error message indicating that the date is invalid.

**Comment by vicaire** [comment]
Can we close this one?

**Comment by rileyjbauer** [comment]
This has not been fixed yet; it's hard to hit, but we should still address it

**Comment by Bobgy** [comment]
Sounds like an important bug to fix.

**Comment by Bobgy** [comment]
This should be relatively not as important as other issues
