### ISSUE TITLE
Discuss the validation and precendence of pipeline ID, workflow manifest and pipeline version

### ISSUE THREAD

**Issue by capri-xiyue** [kubeflow/pipelines#4900]
### What steps did you take:

1. Create a pipeline
2. Upload multiple versions to the same pipeline with different manifests (let's call the versions 1, 2, 3, and their respective manifests 1', 2', 3'. First created version is 1, official default version is 3)
3. Compile a pipeline in local and build the package with version 4 and its respective manifest is 4'

### What happened:
```
pipeline_id = "${pipeline_id}"
pipeline_package_path = "${path of version 4}"
version_2_id = "${version 2 id}"

# Run version 4
run_with_package_path_only = cl.run_pipeline(
    experiment_id, "run_with_package_path_only", pipeline_package_path=pipeline_package_path)

# Run version 3
run_with_pipeline_id_only = cl.run_pipeline(
    experiment_id, "run_with_pipeline_id_only", pipeline_id=pipeline_id)

# Run version 2
run_with_version_id_only = cl.run_pipeline(
    experiment_id, "run_with_version_id_only", version_id=version_2_id)

# Run version 2
run_with_version_id_and_package_path = cl.run_pipeline(
    experiment_id, "run_with_version_id_and_package_path", version_id=version_2_id,
    pipeline_package_path=pipeline_package_path)

# Run version 2
run_with_pipeline_id_and_version_id = cl.run_pipeline(
    experiment_id, "run_with_pipeline_id_and_version_id", version_id=version_2_id,
    pipeline_id=pipeline_id)

# Run version 2
run_with_pipeline_id_and_package_path_and_version_id = cl.run_pipeline(
    experiment_id, "run_with_pipeline_id_and_package_path_and_version_id", pipeline_id=pipeline_id,
    pipeline_package_path=pipeline_package_path, version_id=version_2_id)

# 400.
# Neither pipeline spec nor pipeline version is valid.
# Invalid input error: Please specify a pipeline version in Run's resource references:
# Invalid input error: Please either specify a pipeline ID or a workflow manifest, not both.
# This error is from server layer(validation logic)
try:
    run_with_pipeline_id_and_package_path = cl.run_pipeline(
        experiment_id, "run_with_pipeline_id_and_package_path", pipeline_id=pipeline_id,
        pipeline_package_path=pipeline_package_path)
except Exception as e:
    print("run run_with_pipeline_id_and_package_path encountered error {}".format(e))

# 404
# ResourceNotFoundError: WorkflowSpecManifest run_with_valid_pipeline_id_and_invalid_version_id  not found.
# Failed to fetch workflow spec manifest.
# The error is from Resource Manager layer
try:
    run_with_valid_pipeline_id_and_invalid_version_id = cl.run_pipeline(
        experiment_id, "run_with_valid_pipeline_id_and_invalid_version_id ", pipeline_id=pipeline_id,
        version_id=version_2_id + "invalid")
except Exception as e:
    print("run_with_valid_pipeline_id_and_invalid_version_id encountered error {}".format(e))

# 404 ResourceNotFoundError: Pipeline 9fce6aec-39a2-420b-88c9-a1f3e16d5f0dinvalid not found.
# This error came from Pipeline Store layer
try:
    run_with_invalid_pipeline_id_and_valid_version_id = cl.run_pipeline(
        experiment_id, "run_with_invalid_pipeline_id_and_valid_version_id ", pipeline_id=pipeline_id + "invalid",
        version_id=version_2_id)
except Exception as e:
    print("run_with_invalid_pipeline_id_and_valid_version_id encountered error {}".format(e))
```
I checked the code, the validation logic is here:
https://github.com/kubeflow/pipelines/blob/89e42105bd941e1d918d0bff9ba0c4f80b106ed4/backend/src/apiserver/server/run_server.go#L107
It will try to validate PipeLineSpec. If it encounters error when validating PipeLineSpec then it will try to validate PipelineVersionReference. It WON'T check PipelineVersionReference when PipeLineSpec is valid and it WON'T throw error when PipelineVersionReference  is valid and PipeLineSpec is invliad.

And the creation logic is here:
https://github.com/kubeflow/pipelines/blob/89e42105bd941e1d918d0bff9ba0c4f80b106ed4/backend/src/apiserver/resource/resource_manager.go#L317

For the precedence, pipeline id and workflow manifest has same priority.
version id has higher priority than pipeline id and workflow manifest

### What did you expect to happen:
1. When user specify both  pipeline_package_path(equal to pipeline_manifest) and  version_id, now the behavior is that version_id should take precedence. However, corner cases may happen. Based on the logic https://github.com/kubeflow/pipelines/blob/89e42105bd941e1d918d0bff9ba0c4f80b106ed4/backend/src/apiserver/resource/resource_manager.go#L317, if it encounters error in https://github.com/kubeflow/pipelines/blob/89e42105bd941e1d918d0bff9ba0c4f80b106ed4/backend/src/apiserver/resource/resource_manager.go#L327, it will try to  getWorkflowSpecBytesFromPipelineSpec. 
Not sure whether this fallback makes sense here. And not sure what pipeline version UI will show.

**I think when user can't set pipeline id or version id  when user set workflow manifest**

2.
Validation logic is confusing and incomplete
https://github.com/kubeflow/pipelines/blob/89e42105bd941e1d918d0bff9ba0c4f80b106ed4/backend/src/apiserver/server/run_server.go#L107 won't validate PipelineVersionReference when PipeLineSpec is valid.
For example, when user specify a valid pipeline id and an invalid version id, it will pass the validation logic and it will throw not found error when resource manager finds out the workflow.Workflow is nil https://github.com/kubeflow/pipelines/blob/89e42105bd941e1d918d0bff9ba0c4f80b106ed4/backend/src/apiserver/resource/resource_manager.go#L345.
The error msg is confusing here.  
**I think we should add validation logic when user specify any invalid input no matter whether it's pipeline id, version id or workflow manifest. 
If there is any invalid input, the validation layer will throw error and backend should not call resource manager layer or store layer**

The output should be as follows:
```
pipeline_id = "${pipeline_id}"
pipeline_package_path = "${path of version 4}"
version_2_id = "${version 2 id}"

# Run version 4
run_with_package_path_only = cl.run_pipeline(
    experiment_id, "run_with_package_path_only", pipeline_package_path=pipeline_package_path)

# Run version 3
run_with_pipeline_id_only = cl.run_pipeline(
    experiment_id, "run_with_pipeline_id_only", pipeline_id=pipeline_id)

# Run version 2
run_with_version_id_only = cl.run_pipeline(
    experiment_id, "run_with_version_id_only", version_id=version_2_id)

# invalid, 400, user can't set pipeline id or version id  when user set workflow manifest
run_with_version_id_and_package_path = cl.run_pipeline(
    experiment_id, "run_with_version_id_and_package_path", version_id=version_2_id,
    pipeline_package_path=pipeline_package_path)

# Run version 2
run_with_pipeline_id_and_version_id = cl.run_pipeline(
    experiment_id, "run_with_pipeline_id_and_version_id", version_id=version_2_id,
    pipeline_id=pipeline_id)

# invalid, 400, user can't set pipeline id or version id  when user set workflow manifest
run_with_pipeline_id_and_package_path_and_version_id = cl.run_pipeline(
    experiment_id, "run_with_pipeline_id_and_package_path_and_version_id", pipeline_id=pipeline_id,
    pipeline_package_path=pipeline_package_path, version_id=version_2_id)

# invalid, 400, user can't set pipeline id or version id  when user set workflow manifest
try:
    run_with_pipeline_id_and_package_path = cl.run_pipeline(
        experiment_id, "run_with_pipeline_id_and_package_path", pipeline_id=pipeline_id,
        pipeline_package_path=pipeline_package_path)
except Exception as e:
    print("run run_with_pipeline_id_and_package_path encountered error {}".format(e))

# invalid, 400, user can't specify invalid version id
try:
    run_with_valid_pipeline_id_and_invalid_version_id = cl.run_pipeline(
        experiment_id, "run_with_valid_pipeline_id_and_invalid_version_id ", pipeline_id=pipeline_id,
        version_id=version_2_id + "invalid")
except Exception as e:
    print("run_with_valid_pipeline_id_and_invalid_version_id encountered error {}".format(e))

# invalid, 400, user can't specify invalid pipeline id
try:
    run_with_invalid_pipeline_id_and_valid_version_id = cl.run_pipeline(
        experiment_id, "run_with_invalid_pipeline_id_and_valid_version_id ", pipeline_id=pipeline_id + "invalid",
        version_id=version_2_id)
except Exception as e:
    print("run_with_invalid_pipeline_id_and_valid_version_id encountered error {}".format(e))
```

 

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

KFP version:  1.1.2

KFP SDK version: .1.2

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by capri-xiyue** [comment]
fyi @Bobgy

**Comment by Bobgy** [comment]
Thanks @capri-xiyue for the investigation and proposing ideal behavior, totally agree with everything you said.
