### ISSUE TITLE
Error: `Failed getting executions: e.getOptions is not a function.` when opening execution tab in Pipeline UI.

### ISSUE THREAD

**Issue by m0hit-aggarwal** [kubeflow/pipelines#4903]
I have installed Kubeflow pipelines 1.1.2 on local cluster by running the following commands:

```
export PIPELINE_VERSION=1.1.2
kubectl apply -k "github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=$PIPELINE_VERSION"
kubectl wait --for condition=established --timeout=60s crd/applications.app.k8s.io
kubectl apply -k "github.com/kubeflow/pipelines/manifests/kustomize/env/platform-agnostic-pns?ref=$PIPELINE_VERSION"
```
I am getting the following error when i click the execution tab in pipelines UI.
![image](https://user-images.githubusercontent.com/33771685/102305810-e2501a00-3f86-11eb-9d0c-341185006e84.png)

Environment :
- minikube version: v1.15.1
- kubernetes version: 1.18.2
- KFP version: 1.1.2
- macOS Catalina: 10.15.6 

Am I following the wrong steps for installation or is it some bug?

**Comment by capri-xiyue** [comment]
I ran into the same issue with KFP version: 1.1.2

**Comment by chensun** [comment]
I was able to repro this as well. This issue exists since 1.1.2-rc.1

I suspect it might be due to some frontend dependency change:

https://github.com/kubeflow/pipelines/commit/982b506d4e2c2fe749e8b717ed88e30c737c71a8#diff-1cf387c012cd2d02f1923e589f86df4a4802427057dbc90f47b87f04d29d54bc

@Bobgy can you please take a look.

**Comment by chensun** [comment]
Adding a bit more context

The error is thrown here:

https://github.com/kubeflow/pipelines/blob/cb41f7ab1231b4f8aabe2875b59d67b2d8dce908/frontend/src/pages/ExecutionList.tsx#L146-L157

which reminds me the recent MLMD client upgrade. 

PS. I verified 1.1.1-beta.1 doesn't have this issue. @m0hit-aggarwal, you may consider using that version as a temporary workaround.
