### ISSUE TITLE
Stackdriver getting re-enabled by running Kubeflow pipelines

### ISSUE THREAD

**Issue by Imsurajkr** [kubeflow/pipelines#4908]
### What steps we took:
Created a GKE cluster and deployed kubeflow from Google AI.
Disabled the stackdriver api.

### What happened:
I have disabled the stackdriver api still whenever i run the sample pipelines of taxi tip it automatically re-enables the api and 
we get the options to check the logs on stackdriver api.

### What did we expect to happen:
I expect that it should not re-enable the stack driver API.
I have disabled the stack driver api  in GCP

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

KFP version: Version: 1.0.4

KFP SDK version: 

```bash
kfp                           1.1.0
kfp-server-api                1.0.4
```

/kind bug

**Comment by Bobgy** [comment]
Adding some questions to help scope down the problem:

which pipeline did you run that caused the service to be re-enabled?
What happens if you do not run any pipeline, will the service be re-enabled?
what happens if you run a different pipeline, like the simplest data passing sample pipeline?
