### ISSUE TITLE
Postsubmit integration tests are failing

### ISSUE THREAD

**Issue by chensun** [kubeflow/pipelines#4915]
Sample failure logs:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/kubeflow-pipeline-postsubmit-integration-test/1339679378589618176

Looks like we're running out of quota in `ml-pipeline-test` project

```
sample-test-8vjl5-4072358047: deploying-a-trained-model-to-cloud-machine-learning-engine:	googleapiclient.errors.HttpError: <HttpError 429 when requesting https://ml.googleapis.com/v1/projects/ml-pipeline-test/models?alt=json returned "Quota failure for project ml-pipeline-test. Quota failure for project 363997316495. Exceeded the max allowed number of models per project: 100. To read more about Cloud ML Engine quota, see https://cloud.google.com/ml-engine/quotas. To read more about Cloud ML Engine quota, see https://cloud.google.com/ml-engine/quotas.">
```

**Comment by chensun** [comment]
I'm going to manually delete al the old models. 

#4916 will make tests deleting the models automatically.

**Comment by Bobgy** [comment]
FYI, the issue was reported before as https://github.com/kubeflow/pipelines/issues/2356, but we haven't fixed it permanently

**Comment by chensun** [comment]
> FYI, the issue was reported before as #2356, but we haven't fixed it permanently

Thanks for the pointer. So #4916 doesn't fix this issue permanently either. If something went wrong in between the model deployment and the model deletion, we could still potentially leak the model. But we at least clean up the model in the happy paths, so likely it won't reach the quota limit as soon as it could before the change.

I've manually triggered the integration test in #4916, and verified that no model is left behind after the test run. 

Once the postsubmit tests for #4916 passed, I'll close this issue and cut a release.
