### ISSUE TITLE
Simplify pipeline graph from redundant dependencies

### ISSUE THREAD

**Issue by StefanoFioravanzo** [kubeflow/pipelines#4924]
Sometimes pipelines have a lot of dependencies between steps. When there are a lot of "redundant" dependencies, reading the pipeline graph can become awkward.

For example, if you want to use a VolumeOp to keep some state or pass data between the steps of a pipeline, the resulting graph could look like this:

![Screenshot 2020-12-21 at 11 46 23](https://user-images.githubusercontent.com/3354305/102769038-5ec96b00-4382-11eb-85ba-494733c7bc39.png)

The repeated dependencies on the first Volume step make the graph scrambled and hard to decipher.

A solution to this is to "simplify" the rendering of the pipeline graph, whenever there are "redundant" dependencies. This procedure is known in graph theory as "Transitive Reduction". 

From [1]:

> In mathematics, a transitive reduction of a directed graph `D` is another directed graph with the same vertices and as few edges as possible, such that for all pairs of vertices `v`, `w` a (directed) path from `v` to `w` in `D` exists if and only if such a path exists in the reduction.

[1]: https://en.wikipedia.org/wiki/Transitive_reduction

The algorithm to achieve this is fairly simple, and could be activated by the user using a simple toggle in the pipeline view like this:

![Screenshot 2020-12-21 at 11 45 50](https://user-images.githubusercontent.com/3354305/102769053-65f07900-4382-11eb-9292-cfd9205708af.png)

Toggling this option again would revert the graph to the original one.

I will shortly follow up with a PR with a proposed implementation.

**Comment by Udiknedormin** [comment]
Is there any particular reason not to reduce it on DSL or Argo yaml level and instead only add it as an optional feature in the UI? It's not really an optimization and redundancies are --- by definition --- not needed to the graph. The final graph doesn't always reflect the DSL 1:1 in all cases anyway, particularly pipelines containing corner cases of recursions, conditionals and loops, so is there any problem with simply reducing the dependencies in-pipeline?

It seems to me that is what [`PipelineVolume`'s `after` method](https://github.com/kubeflow/pipelines/tree/88dbfda02b240cb685f39bda37cb0e309d7102d1/sdk/python/kfp/dsl/_pipeline_volume.py#L92-L125) does:

```python
    def after(self, *ops):
        """Creates a duplicate of self with the required dependecies excluding
        the redundant dependenices.

        Args:
            *ops: Pipeline operators to add as dependencies
        """
        def implies(newdep, olddep):
            if newdep.name == olddep:
                return True
            for parentdep_name in newdep.dependent_names:
                if parentdep_name == olddep:
                    return True
                else:
                    parentdep = _pipeline.Pipeline.get_default_pipeline(
                    ).ops[parentdep_name]
                    if parentdep:
                        if implies(parentdep, olddep):
                            return True
            return False

        ret = self.__class__(volume=self)
        ret.dependent_names = [op.name for op in ops]

        for olddep in self.dependent_names:
            implied = False
            for newdep in ops:
                implied = implies(newdep, olddep)
                if implied:
                    break
            if not implied:
                ret.dependent_names.append(olddep)

        return ret
```

**Comment by StefanoFioravanzo** [comment]
@Udiknedormin I don't think changing the structure of the graph itself at definition time is a good idea. The user should always be in complete control over how the graph is defined, even if some dependencies are redundant. You can never know what edge/particular cases the reduction algorithm might miss, thus creating a wrong graph.

Having this as a UI feature instead mitigates this and still allows as to have a clean view

**Comment by Ark-kun** [comment]
This is an interesting idea, although it might be less feasible in some future UX.

It would be great to move to UX which shows actual data connections (outputs connected to inputs). With UX like that, this edge removal feature might produce unexpected results.

**Comment by StefanoFioravanzo** [comment]
@Ark-kun What do you mean exactly with this?

> It would be great to move to UX which shows actual data connections (outputs connected to inputs).

We can always revisit this as soon as a new UX comes up!
