### ISSUE TITLE
Discussion - shall we switch from glog to klog?

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#4943]
https://github.com/kubernetes/klog was forked to fix many problems present in glog,

The prominent problem I saw was that glog adds flags globally. In container env, it will fail by default because it doesn't have permission to write log to the /tmp/ folder (by default), so we always need to add a `--logtostderr` flag so that it redirects log to stderr.

**Comment by NikeNano** [comment]
+1, also glog is not under active development any longer as I understand.

**Comment by capri-xiyue** [comment]
For knative, they write their own logging pkg https://pkg.go.dev/knative.dev/pkg/logging which integrates with context and the  underlying library it uses is "go.uber.org/zap"
