### ISSUE TITLE
[frontend] Clone run with the latest pipeline version

### ISSUE THREAD

**Issue by vit-** [kubeflow/pipelines#4944]
Currently, the `Clone run` button opens a `New run` page with the exact same pipeline version as the original run. In our use case, however, we don't care about outdated pipeline versions, we always want to run the latest. When changing the pipeline version on the UI, the `Run parameters` form gets cleared, which is very inconvenient. 
I would like to have a button that opens a `New run` page with the latest pipeline version selected and all run parameters copied from the original run. 
Alternatively, I would like the `Run parameters` form to **not** get cleared when changing the pipeline version.

**Comment by niderhoff** [comment]
I second this proposal. Cloning a run and and having to enter all the parameters again is really frustrating.
