### ISSUE TITLE
force rerun of a component, skipping cache (newbie issue)

### ISSUE THREAD

**Issue by yarcyarc** [kubeflow/pipelines#4947]
### What steps did you take:

1. Installed Kubeflow Pipelines over AI marketplace (https://console.cloud.google.com/ai-platform/pipelines/clusters). Default invocation of both cluster and kfp.  
2. Created a pipeline based on https://github.com/kubeflow/pipelines/blob/master/samples/contrib/mnist/02_Local_Development_with_Docker_Image_Components.ipynb over upload button
3. Ran the mnist_train_op (referred to in the url of step 2 above) component successfully. An h5 model was written to a gcp bucket. 
4. Deleted the gcp bucket model 
5. Reran mnist_train_op, successfully, in that nothing was done, "Execution was skipped and output was taken from cache" as it states in the UI Experiments->Default->Run view. 

### What happened:

In step 5 nothing was written to the gcp bucket. 

### What did you expect to happen:

I did expect and understand why step 5 behaves as it does. It's just that I'd like, for debugging/development purposes to be able to rerun the step, i.e. bypass the cache if I so desire. I see from https://github.com/kubeflow/pipelines/issues/4857 and https://github.com/kubeflow/pipelines/issues/4446 that I'm not the first asking about this kind of issue. I've tried the resolutions proposed therein without success, see below.  

### Environment:

See step 1 above. 

How did you deploy Kubeflow Pipelines (KFP)?

See step 1 and 2. 

KFP version: 

From the UI, it sais version 1.0.4, build commit b604c61 built 10/22/2020. 

KFP SDK version:

$ pip list | grep kfp
kfp                      1.2.0
kfp-pipeline-spec        0.1.3.1
kfp-server-api           1.2.0

### Anything else you would like to add:

In https://github.com/kubeflow/pipelines/issues/4857 a solution is to disable the cache by following  https://www.kubeflow.org/docs/pipelines/caching/#disablingenabling-caching. 

This is unsuccessful for me, `kubectl get mutatingwebhookconfiguration cache-webhook -n XXX` returns with an `Error from server (NotFound)` for all namespaces XXX in the cluster. 

Given my low competence level, the only way I've found I can enforce a rerun of a component without relying on a cache is to delete the cluster and recreate it, as it does not help to upload a new version of the pipeline, upload the pipeline as a new pipeline, nor delete all pipelines and then upload. 

Any newbie advice on a better procedure is much appreciated. 
 

/kind bug

/area frontend
/area backend

**Comment by Ark-kun** [comment]
You can use the suggestion from the documentation:
```python
      task = some_op()
      task.execution_options.caching_strategy.max_cache_staleness = "P0D"
```

**Comment by saurovn** [comment]
Webhook name was different for my Kubeflow 1.2 instance. 
In my case it was "**cache-webhook-kubeflow**", so following fix worked -

`export NAMESPACE=kubeflow`
`kubectl get mutatingwebhookconfiguration cache-webhook-${NAMESPACE} -n ${NAMESPACE}`
`kubectl patch mutatingwebhookconfiguration cache-webhook-${NAMESPACE} -n ${NAMESPACE} --type='json' -p='[{"op":"replace", "path": "/webhooks/0/rules/0/operations/0", "value": "DELETE"}]'`

**Comment by Bobgy** [comment]
Question answered

**Comment by ferpitol** [comment]
hi, my function are created with create_component_from_func,

so how can i implement this

```
task = some_op()
task.execution_options.caching_strategy.max_cache_staleness = "P0D"
```

example of my code

```
def some_python_func():
    #do something
    return True
    
task1 = create_component_from_func(
    func=some_python_func(),
    base_image="one ddcoker image"
    #packages_to_install=['gensim'], # Optional
)

@dsl.pipeline(
    name='one name',
    description='one description'
)
def hello_world_pipeline():
    task1().output
    
if __name__ == '__main__':
    task = hello_world_pipeline()
    kfp.compiler.Compiler().compile(task, 'mypipeline.yaml')
```

when in the main I code

```
if __name__ == '__main__':
    task = hello_world_pipeline()
    task.execution_options.caching_strategy.max_cache_staleness = "P0D"
    kfp.compiler.Compiler().compile(task, 'mypipeline.yaml')
```

it gives me the error : AttributeError: 'NoneType' object has no attribute 'execution_options'

also I tried 

```
def hello_world_pipeline():
    task_nc = task1()
    task_nc..execution_options.caching_strategy.max_cache_staleness = "P0D"
    task_nc().output
```

but it give the error:
AttributeError: 'NoneType' object has no attribute 'caching_strategy'

please could someone help me I really need that any task of my pipeline runs cache and using configurations like` kubectl patch mutatingwebhookconfiguration ...`  is not an option

**Comment by TranThanh96** [comment]
I am missing this problem. Tried:
```
task.execution_options.caching_strategy.max_cache_staleness = "P0D"
```

```
export NAMESPACE=kubeflow
kubectl get mutatingwebhookconfiguration cache-webhook-${NAMESPACE} -n ${NAMESPACE}
kubectl patch mutatingwebhookconfiguration cache-webhook-${NAMESPACE} -n ${NAMESPACE} --type='json' -p='[{"op":"replace", "path": "/webhooks/0/rules/0/operations/0", "value": "DELETE"}]'
```

But seem like my component keep print log from cache (from old runs)

Any ideas please?

**Comment by mayankagarwal19911** [comment]
Any update on comments from @ferpitol and @TranThanh96 ?
