### ISSUE TITLE
How to fetch Kubeflow login username and password inside KFP components? 

### ISSUE THREAD

**Issue by ShilpaGopal** [kubeflow/pipelines#4948]
Question:

**Is there a way to fetch login username and password inside KFP components?** 
E.g: Pod name can be fetched as {{pod.name}}
(Available variable reference https://github.com/argoproj/argo/blob/master/docs/variables.md )

TLDR;

Kubeflow is deployed on an on-prem cluster with Keycloak integration. We have a datastore which is integrated with Keycloak as well. KF pipeline components need to fetch data from datastore with Kubeflow login username and password. Is there a variable which is exposed to container using which Kubeflow login username/email and password can be read? 

KFP SDK version:1.1.0

**Comment by munagekar** [comment]
Kubeflow Pipelines does not have any support for passing credentials.

Credentials can be passed using Kubernetes Secrets. The following snippets show how to add a secret to a Kubeflow Container Op.

https://github.com/kubeflow/pipelines/blob/7540ba5c3bf003758a5c2f46ccc586a0367c4dee/sdk/python/kfp/gcp.py#L37-L69

**Comment by prasadkyp7** [comment]
Is there any update on how to pass kubeflow login credentials using kfp client or a rest api to trigger the pipelines

**Comment by rimolive** [comment]
Closing this issue. The provided solution is the only and safest way to pass sensitive data.

/close
