### ISSUE TITLE
No way in the UI to upload a pipeline from the cluster itself

### ISSUE THREAD

**Issue by lakshmanok** [kubeflow/pipelines#495]
So, I used the Jupyter notebook to create a pipeline.tar.gz.  Unfortunately, there is no way to upload it using the UI.

(I can of course do it from Python, but the UI needs to allow uploading a file from the cluster).

**Comment by yebrahim** [comment]
I get the feeling of disconnect between the notebook and our UI, but I don't think there's much we can do there unfortunately. The two UIs runs in separate pods with potentially different authorization roles.

I think a better approach would be exploring adding a custom Jupyter widget to interact with the Pipelines backend. This can handle uploading pipelines, submitting runs, and perhaps even linking the current open notebook with a run on the backend, and providing a link to see it in the Pipelines UI. I can see this become very handy.

**Comment by lakshmanok** [comment]
A quicker option might be to allow the user to specify a gs://.../ or http://.../ URL to load the pipeline from.  This would also be useful to load directly from an AI Hub listing.

**Comment by yebrahim** [comment]
Agreed, we're planning to add an "import by url" feature in the upload dialog.

**Comment by yebrahim** [comment]
/assign @rileyjbauer 

https://github.com/kubeflow/pipelines/pull/554 adds ability to import by url. Closing this since it's not tracking anything else. We can continue the discussion if @lakshmanok feels otherwise.

/close
