### ISSUE TITLE
2 Pods created for every userprofile 

### ISSUE THREAD

**Issue by kd303** [kubeflow/pipelines#4953]
### What steps did you take:
WE have a Kubeflow 1.1 with Dex enabled on premise cluster with 2 worker nodes. We have enabled few of our data-science users with LDAP integration. However what we noticed during some sort of test (we wanted to create multiple profiles and see how many users can work simultaneously - since 220 pod limit would be there vs how many pods are reserved by Kubeflow and other pieces in order to determine our future cluster sizing). W

### What happened:
We saw that there are two pipeline pods created for every single profile created on Kubeflow, it wasnt very clear why these pods gets created everytime a profile is created and user is logged in. These would be mean if I on-board 20 users then 40 pods are utilized that means we have less capacity available for kf-serving, notebooks etc.

These two pods are created in a specific namespace for an individual user

### What did you expect to happen:
I am not sure whether this is a specific functionality or a bug, so I wanted to understand :
1. Why this behavior
2. Is this some configuration issue at our end, which we can rectify? 
### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

Kubeflow version 1.1.0
Kubeflow pipeline version: 1.0.0

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by kd303** [comment]
Is anyone else facing this issue? any pointers suggestion would be helpful

**Comment by kd303** [comment]
/kind featurrequest  changing the label as this is a default behaviour

**Comment by Bobgy** [comment]
Hi @kd303, this is expected behavior.
ui-artifact server and visualization server should run in user namespace.

You can customize https://github.com/kubeflow/pipelines/blob/master/manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/sync.py to suit your own needs (e.g. if you don't use the visualization server).
