### ISSUE TITLE
[UI] Allow users to filter pipeline runs by status

### ISSUE THREAD

**Issue by shotarok** [kubeflow/pipelines#4954]
We can filter pipeline runs by name on the KFP UI but we can't filter them by status because of the following code.

https://github.com/kubeflow/pipelines/blob/c8c9905bf2b2662a851c339afbd143cfdbdb603c/frontend/src/components/CustomTable.tsx#L515-L527

This feature allows users to see the failed pipeline only.

**Comment by Bobgy** [comment]
Thanks for the feature request, this is a very useful feature.
I believe we've supported more fields for the filter at the API layer, it'll be great if UI supports that too.

The major problem is designing either:
* the syntax to specify the filter
* UI elements that allow users compose the filter

**Comment by Bobgy** [comment]
Welcome contribution to define an ideal UX.

**Comment by shotarok** [comment]
I like the query syntax like [GitHub](https://docs.github.com/en/free-pro-team@latest/github/searching-for-information-on-github/understanding-the-search-syntax), which is expressed by a list of `<qualifier>:<value>`. One drawback is that it can't express [IN and IS_SUBSCRING](https://github.com/kubeflow/pipelines/blob/master/backend/api/filter.proto#L39-L45) although it's able to deal with [EQUALS, NOT_EQUALS, GREATER_THAN, GREATER_THAN_EQUALS, LESS_THAN, and LESS_THAN_EQUALS](https://github.com/kubeflow/pipelines/blob/7540ba5c3bf003758a5c2f46ccc586a0367c4dee/backend/api/filter.proto#L30-L37).

**Comment by pyxelr** [comment]
/reopen 

Hi, is there a chance that this functionality (to filter Kubeflow runs by status within Kubeflow UI) has been already implemented? If not, are there any plans to do it for the next versions?

**Comment by shotarok** [comment]
/reopen

@pyxelr No, I'm afraid the current master branch also has the same logic as the previous. I'll try to reopen this issue.
https://github.com/kubeflow/pipelines/blob/85c7901874f19b6e7ecf6e1b152f53ab429e6edc/frontend/src/components/CustomTable.tsx#L519-L531

**Comment by jlyaoyuli** [comment]
Hello @shotarok, We are still waiting for the community to define the UX behavior. Here is one of the example that we can explore to filter by status. https://react-select.com/home

**Comment by avito-ds** [comment]
Can we try to add filter?
