### ISSUE TITLE
Feature request:  Display who ran the pipeline on dashboard.

### ISSUE THREAD

**Issue by kim-sardine** [kubeflow/pipelines#4958]
It would be great if I can check who triggered kubeflow pipeline on kubeflow dashboard's experiment page.

It seems like argo workflow doesn't even store user information.

I found similar [issue](https://github.com/kubeflow/pipelines/issues/2348) but no progress with it.

**Comment by zijianjoy** [comment]
This is a very good idea in multi-user support! Thank you for creating this request.

However, currently this is not in our roadmap, welcome community to contribute to this request.
