### ISSUE TITLE
kubeflow-pipeline-upgrade-test keeps failing

### ISSUE THREAD

**Issue by numerology** [kubeflow/pipelines#4966]
Sample log: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/4963/kubeflow-pipeline-upgrade-test/1347266047027187712/build-log.txt

Looks like the deployment of `cache-deployer-deployment` gets stuck.

**Comment by numerology** [comment]
/assign @Bobgy 
/assign @rui5i 
/assign @Ark-kun 

Do you mind taking a look? Thanks!

**Comment by Bobgy** [comment]
@numerology which PR did you see it?
for example, I can see it passing in https://github.com/kubeflow/pipelines/pull/4965

**Comment by Bobgy** [comment]
My quick guess, I think @IronPan was releasing 1.3.0 at that moment, so the upgrade test tried to upgrade from 1.3.0 (whose images haven't been built).

It should pass after retry.

Any ideas to improve this?

**Comment by Bobgy** [comment]
I don't think it's immediately urgent though, probably better documentation to let people know it may happen during release.

**Comment by numerology** [comment]
Thanks Yuan! It comes from https://github.com/kubeflow/pipelines/pull/4963.

**Comment by numerology** [comment]
> Any ideas to improve this?

Given it's only a transient issue in a short period of time I think it's okay for now. Thanks for the information! Closing
