### ISSUE TITLE
Error 1114: The table 'run_details' is full"

### ISSUE THREAD

**Issue by brtasavpatel** [kubeflow/pipelines#4980]
### What steps did you take:
Kubeflow was already running ~50 pipelines at the time when new pipeline runs were submitted resulting in about ~500 pipeline runs running.
Volume size : 20 gigs, where `mysql` deployment was running.

### What happened:
Pipeline runs failed to run with error : 
```
{"error":"Failed to create a new run.: InternalServerError: Failed to store run abc-xyz to table: 
Error 1114: The table 'run_details' is full","message":"Failed to create a new run.: 
InternalServerError: Failed to store run abc-xyz to table: Error 1114: The table 'run_details' is full",
"code":13,"details":[{"@type":"type.googleapis.com/api.Error","error_message":"Internal Server Error",
"error_details":"Failed to create a new run.: InternalServerError: Failed to store run abc-xyz to table:
 Error 1114: The table 'run_details' is full"}]}
```
Kubeflow UI was also unresponsive when trying to check a pipeline run status.

### What did you expect to happen:
Kubeflow UI should return/display appropriate error.
Installation instructions should have this limitation documented. Also there should be a way to auto-clean this particular table or any other table which might be taking large amount of storage to keep KFP functional.

### Environment:
KFP version: 1.0.1

KFP SDK version: 1.0.1

### Anything else you would like to add:
checking `mlpipelines.run_details` table showed that table size has grown to 20 gigs.

/kind bug
/area frontend
/area backend

**Comment by Bobgy** [comment]
Which cloud platform do you deploy KFP? Is it part of a full Kubeflow installation?

Our suggestion for productionizing a KFP instance is to use a cloud provider's managed SQL instance.
e.g. in GCP we'd recommend using Cloud SQL, so that you'll be able to back up/resize/configure the SQL instance on your own

**Comment by Bobgy** [comment]
For KFP standalone, we have some documentation in https://github.com/kubeflow/pipelines/tree/master/manifests/kustomize/sample.

**Comment by Bobgy** [comment]
and how long did it take until your DB was full?

**Comment by Bobgy** [comment]
Immediate workaround could be resize the PV backing your mysql DB or delete old run records from the DB using KFP SDK/API

**Comment by brtasavpatel** [comment]
> Which cloud platform do you deploy KFP? Is it part of a full Kubeflow installation?
> 
> Our suggestion for productionizing a KFP instance is to use a cloud provider's managed SQL instance.
> e.g. in GCP we'd recommend using Cloud SQL, so that you'll be able to back up/resize/configure the SQL instance on your own

I am on AWS, but we deploy Kubeflow by our self. It's a full Kubeflow Installation.

**Comment by brtasavpatel** [comment]
> and how long did it take until your DB was full?

Little over 2 months. but our usage increased this month only.

**Comment by Bobgy** [comment]
/cc @PatrickXYS 
For providing more guidance

**Comment by PatrickXYS** [comment]
> > Which cloud platform do you deploy KFP? Is it part of a full Kubeflow installation?
> > Our suggestion for productionizing a KFP instance is to use a cloud provider's managed SQL instance.
> > e.g. in GCP we'd recommend using Cloud SQL, so that you'll be able to back up/resize/configure the SQL instance on your own
> 
> I am on AWS, but we deploy Kubeflow by our self. It's a full Kubeflow Installation.

@brtasavpatel  Then it's not on EKS I think, are you utilizing MySQL or RDS on AWS?

**Comment by brtasavpatel** [comment]
> > > Which cloud platform do you deploy KFP? Is it part of a full Kubeflow installation?
> > > Our suggestion for productionizing a KFP instance is to use a cloud provider's managed SQL instance.
> > > e.g. in GCP we'd recommend using Cloud SQL, so that you'll be able to back up/resize/configure the SQL instance on your own
> > 
> > 
> > I am on AWS, but we deploy Kubeflow by our self. It's a full Kubeflow Installation.
> 
> @brtasavpatel Then it's not on EKS I think, are you utilizing MySQL or RDS on AWS?

@PatrickXYS Kubernetes is on EKS. I meant we didn't use any hosted Kubeflow Solutions, and I am utilizing MySQL

**Comment by PatrickXYS** [comment]
So the way I would go is to check the log of `mysql` pod, see if anything wrong there

Another question is:

> Kubeflow was already running ~50 pipelines at the time when new pipeline runs were submitted resulting in about ~500 pipeline runs running.

Is the issue happening everytime when you reached to the same level of workload?

**Comment by brtasavpatel** [comment]
> So the way I would go is to check the log of `mysql` pod, see if anything wrong there
> 
> Another question is:
> 
> > Kubeflow was already running ~50 pipelines at the time when new pipeline runs were submitted resulting in about ~500 pipeline runs running.
> 
> Is the issue happening everytime when you reached to the same level of workload?

We probably first time got this burst of pipeline submissions, so would be hard to tell that.
