### ISSUE TITLE
Caching Documentation incorrect for 1.2

### ISSUE THREAD

**Issue by fvde** [kubeflow/pipelines#4984]
As far as I can tell the documentation for Caching (https://www.kubeflow.org/docs/pipelines/caching/) is incorrect for 1.2. The mutatingwebhookconfiguration is not called cache-webhook, but **cache-webhook-kubeflow**. I.e. all commands need to be updated from
`kubectl patch mutatingwebhookconfiguration cache-webhook -n ${NAMESPACE} --type='json' -p='[{"op":"replace", "path": "/webhooks/0/rules/0/operations/0", "value": "DELETE"}]'
`

to 

`kubectl patch mutatingwebhookconfiguration cache-webhook-kubeflow -n ${NAMESPACE} --type='json' -p='[{"op":"replace", "path": "/webhooks/0/rules/0/operations/0", "value": "DELETE"}]'
`

**Comment by Bobgy** [comment]
Moving to pipelines for better tracking

**Comment by Bobgy** [comment]
Yes, it will be `cache-webhook-{namespace}`, so for kubeflow, it's -kubeflow

@Ark-kun can you work on the documentation update?

**Comment by Bobgy** [comment]
Fixed by https://github.com/kubeflow/website/pull/2499
