### ISSUE TITLE
Discuss dependency update strategy of KFP

### ISSUE THREAD

**Issue by capri-xiyue** [kubeflow/pipelines#4999]
Currently, we do not usually update dependencies, so each time we update, they have already been pretty old and many things could be breaking after some dependencies are updated. 

 It's worth discussing the dependency update strategy of KFP.

Looks like there is no script or doc related to updating dependency. We may need to write a script  like https://github.com/knative/eventing/blob/master/hack/update-deps.sh and write some docs related to updating dependency.

**Comment by capri-xiyue** [comment]
fyi @NikeNano @Bobgy

**Comment by Ark-kun** [comment]
There are several main areas that might need updating:

* Python SDK deps
* Backend Go deps
* Kubernetes deps (e.g. Argo)
* Deps of micro services (Metadata Writer, Visualization Server, etc.)

For python (SDK and Visualizations) we already have update scripts.

**Comment by Bobgy** [comment]
And
* frontend deps
* MLMD client/server version

+1 for building scripts that automate upgrading dependencies so that we try and test an upgrade more often.

**Comment by Bobgy** [comment]
FYI, I've created an issue before with similar content: https://github.com/kubeflow/pipelines/issues/4682
@capri-xiyue shall we consolidate the two issues?

**Comment by capri-xiyue** [comment]
closed this since it‘s a duplicate of #4682
