### ISSUE TITLE
ScheduledWorkflow CRD: Investigate need for retries beyond the ones provided by Argo

### ISSUE THREAD

**Issue by vicaire** [kubeflow/pipelines#5]
Currently, the ScheduledWorkflow CRD reliably starts Argo workflows, but does not monitor that they complete successfully. It relies on retries embedded in the Argo workflow itself. 

The ScheduledWorkflow CRD could provide a retry functionality.

**Comment by vicaire** [comment]
Notes:

**Comment by ynqa** [comment]
> This issue tracks the case where retries should be performed by the ScheduledWorklfow instead of the Workflow.

Does it use configmap to trace how far pipelines are finished?

**Comment by ynqa** [comment]
Ah sorry, I was just misreading. I understood this issue objectives.
By the way, What is the main use cases? I think that is in order to training the ML model with some intervals.

**Comment by vicaire** [comment]
Yes, this is the main use case

**Comment by vicaire** [comment]
Resolving since Argo provides the needed retries.
