### ISSUE TITLE
pipeline step pod which come up with alpine image when cachedExecution is set don't run with restricted psp

### ISSUE THREAD

**Issue by orugantichetan** [kubeflow/pipelines#5005]
### What steps did you take:
installed kubeflow with kfp 1.0.4 manifest

### What happened:
pipeline step pod which come up with alpine image when cachedExecution is set don't run with restricted psp . Error: container has runAsNonRoot and image will run as root

Making the image name configurable through env var  or workflow controller adding some default securitycontext to the pipeline step will be helpful . 
[https://github.com/kubeflow/pipelines/blob/3b9fdff26be7d0f04563bbac8bc23807caa69ae2/backend/src/cache/server/mutation.go#L136](url)

**Comment by Bobgy** [comment]
/assign @Ark-kun 

Understood the issue, that's indeed a limitation of KFP caching.
Note, the feature is in Alpha stage, you can also disable it via https://www.kubeflow.org/docs/pipelines/caching/#disabling-caching-in-your-kubeflow-pipelines-deployment
(the doc is slightly outdated, the name of that configuration should be `cache-webhook-{namespace}` instead.
