### ISSUE TITLE
Pipeline component fails with [object Object] as pod log

### ISSUE THREAD

**Issue by ShilpaGopal** [kubeflow/pipelines#5008]
### What steps did you take:
Created a pipeline with two stages, On success of 1st stage status will be published in 2nd stage. 

![image](https://user-images.githubusercontent.com/13718648/105070966-ffa66580-5aa9-11eb-863b-d6ea791e2c55.png)

### What happened:
2nd stage always fails with exit code 255 and logs [object Object]. 

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

Custom build is deployed on on-prem cluster with Istio and Keycloak integration

KFP version:  1.2.0

KFP SDK version: 1.1.1

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by parthmishra** [comment]
Seems like something UI related. Does the container produce logs? Is it just this pipeline/pipeline step that does this?

**Comment by ShilpaGopal** [comment]
Yes @parthmishra container produces logs using python logger. The previous step is able to log currently but the next step fails. 

I tried the sample flip coin example(https://github.com/kubeflow/pipelines/blob/master/samples/core/condition/condition.py)  which has multiple steps, it was able to log the output.

I am not sure, I might be missing something! If its a UI related issue then it must affect all the pipelines with multiple steps right?

**Comment by ShilpaGopal** [comment]
I was able to solve this problem. Here are my findings. 

import-utility.Dockerfile
```
FROM import-utility:1.0.0-23
RUN mkdir import-utility
COPY /src /import-utility/src

WORKDIR /import-utility

ENTRYPOINT ["python"]
```
My pipeline step's image containers have WORKDIR set to /import-utility, I was writing the output file from step 1 in the path file_outputs={'output': '/import-utility/output.txt'}. 

By changing it to write to the path file_outputs={'output': '/tmp/output.txt'}, step 2 was able to fetch the output successfully. 

I am not sure about the effect of writing the output file inside the container's working dir v/s outside of it, on <your_previous_dsl.ContainerOp>.output! any input on this is appreciated.

**Comment by Bobgy** [comment]
/cc @chensun @Ark-kun 
Do you have an suggestions for him?
