### ISSUE TITLE
Tensorboard integration: UI timeout

### ISSUE THREAD

**Issue by amygdala** [kubeflow/pipelines#501]
When you click 'start tensorboard', the UI times out waiting for the pod to be created. (Possibly this is an issue only the first time Tensorflow is being deployed to the cluster).
Workaround: if the user reloads the page (after an interval), they'll see the 'launch tensorboard' button as intended and things work okay from there.
(cc @yebrahim )

**Comment by vicaire** [comment]
Riley, do you know if this is still an issue? Can we close?

**Comment by rileyjbauer** [comment]
@jingzhang36 @neuromage will this still be an issue after #1320 is merged?

**Comment by neuromage** [comment]
If the underlying cause was a timeout due to pod creation, then I imagine the problem may still manifest itself, especially during first launch in a brand new cluster without a cached image.

**Comment by rileyjbauer** [comment]
Closing, feel free to reopen if this issue is encountered again
