### ISSUE TITLE
UI loses state after being idle for a while

### ISSUE THREAD

**Issue by amygdala** [kubeflow/pipelines#502]
I've noticed that when I return to the Pipelines UI after it sitting idle in a tab for a while, it seems to lose its state, in the sense that clicking on something (e.g. clicking on an experiment, or clicking on a run to clone it), will give some kind of 'not found' error.  I get this a lot, so it should be fairly easy to repro. (can add screenshots from next time I see it if that would be helpful).
Reloading the page fixes things.

**Comment by yebrahim** [comment]
I'm assuming you're running behind IAP? Does reloading redirect you to Google OAuth screen?

**Comment by amygdala** [comment]
I am not 100% sure if I've only seen it behind IAP, but could be.  
No, reloading just re-renders the page.
That's a good thought though -- it might well be IAP-related.

**Comment by yebrahim** [comment]
Cool, is it ok to close this and re-open if it repo's without IAP then?

**Comment by amygdala** [comment]
Sure... though, if that is the source of the problem, I think the displayed error will be confusing to users (it doesn't look like an auth error), and we might think about how we could make it a bit friendlier.

**Comment by yebrahim** [comment]
That's true, although there's no way for the UI to distinguish between IAP issues and other sources of connection loss with the backend, but we can at least make the error a little better, something like "Could not connect to the backend. Try refreshing the page."

Let's close this one to keep it tracking potential IAP issues, and I'll open a different issue to track making the disconnected message more friendly.

**Comment by amygdala** [comment]
SGTM -- closing it. Let's also keep an ear out for reports of this happening outside the IAP setup, in case we've misdiagnosed.
