### ISSUE TITLE
NOTICE: migration to google-oss-robot

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#5020]
UPDATE: We have migrated to @google-oss-robot, there was an issue during the migration that caused all presubmit tests in existing PRs to succeed with message "Context retired without replacement". Please comment `/retest` on the PR to retry them.

=== original issues

For aws-kf-ci-bot: upstream issue - ~https://github.com/kubeflow/internal-acls/issues/354#issuecomment-764311315~ has already been resolved.

For google-oss-robot:
We are migrating to google-oss-prow, please ignore them during transition period. We'll disable k8s-ci-robot very soon.
ETA 1week
progress can be found on https://github.com/kubernetes/test-infra/issues/14343

**Comment by PatrickXYS** [comment]
I think this one can be closed @Bobgy  after fixed

**Comment by Bobgy** [comment]
Thanks, in fact google-oss-robot is still spamming, so we need to keep it for some time

**Comment by Bobgy** [comment]
We have migrated to @google-oss-robot, there was an issue during the migration that caused all presubmit tests in existing PRs to succeed with message "Context retired without replacement". Please comment `/retest` on the PR to retry them.

**Comment by Bobgy** [comment]
the migration has succeeded, closing this issue
