### ISSUE TITLE
Can't access the endpoint generated at the end of the process

### ISSUE THREAD

**Issue by Juggernaut1997** [kubeflow/pipelines#5029]
Hi team,

I am a ML Engineer and right now working on MLOps on GCP. So for that I developed my ML model and used `kfp functions` to deploy my model to Kubeflow and I successfully did that. Adding to that, I have also developed a simple UI to access my ML model using flask. 

So for now, my application consist of 3 steps:
1. Pre-process
2. Train
3. Predict

In the end of predict, I had an endpoint generated, which is some localhost link but as this is generated inside kubeflow I went to workloads on GCP and tried to expose the pod to a LoadBalancing port but that is not working. It gets exposed to that port but I am not able to access that endpoint. 
Can you guys help me with how can I access the endpoint?

Thank you so much in advance

**Comment by Bobgy** [comment]
@Juggernaut1997 Do you use full Kubeflow or AI platform pipelines?

You may take a look at KFServing, I think they provide mechanism to expose generic container endpoint.
