### ISSUE TITLE
`ml-pipeline-ui` cannot be configured for volume-support 

### ISSUE THREAD

**Issue by Mar-ai** [kubeflow/pipelines#5031]
### What steps did you take:

I'm starting a TFX-pipeline in a jupyter notebook in namespace `admin`. According to the [TFX kubeflow-on premise example](https://github.com/tensorflow/tfx/blob/master/tfx/examples/chicago_taxi_pipeline/taxi_pipeline_kubeflow_local.py),  the PV is mounted as follows: 
```python 
_persistent_volume_claim = 'pvc-tfx'
_persistent_volume = 'pv-tfx'
_persistent_volume_mount = '/mnt'
``` 

and used in 
```python 
...
    kfp.onprem.mount_pvc(_persistent_volume_claim, _persistent_volume,
                               _persistent_volume_mount)
...
```

PV and PVC have been created in namespace `admin`. 
The pipeline succeeds. Now I want to display the generated artifacts in the kubeflow UI. I'm following the instructions here to patch the `ml-pipeline-ui` in order to generate visualizations from volumes:  
https://github.com/kubeflow/pipelines/blob/master/docs/config/volume-support.md

### What happened:

Since the PVC is in namespace `admin` and the `ml-pipeline-ui` is in namespace `kubeflow`, the PVC cannot be found and
the patch is unsuccessful: 

```bash

$ kubectl rollout status deploy/ml-pipeline-ui -n kubeflow
Waiting for deployment "ml-pipeline-ui" rollout to finish: 1 old replicas are pending termination...

# analysis 
$ kubectl describe pod ml-pipeline-ui-76fcd74b66-j47pp  -n kubeflow
...

Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  45s (x7 over 9m42s)  default-scheduler  persistentvolumeclaim "pvc-tfx," not found
```

How could this be solved? 

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?
Full Kubeflow 1.2 deployment on an on-premise K8s cluster

KFP version: build version v1beta1
KFP SDK version: 
```python 
kfp                            1.3.0     
kfp-pipeline-spec              0.1.3.1   
kfp-server-api                 1.3.0   
```

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug
/area frontend

**Comment by Bobgy** [comment]
Note, in multi user mode, there's an kfp artifact server in each user's namespace. You should be able to mount the volume there.

**Comment by Bobgy** [comment]
but in general, this feature in in Alpha stage, it might not work out. I'd love to hear your feedback if it could be configured to work for you, or do you have any suggestions to improve it?
