### ISSUE TITLE
Kubeflow 1.0.2 - pipelines upgrade - failing ... 

### ISSUE THREAD

**Issue by pkasson-ascena** [kubeflow/pipelines#5032]
Referred to the upgrade website and ran the command:

kubectl apply -k "github.com/kubeflow/pipelines/manifests/kustomize/env/dev?ref=$PIPELINE_VERSION"

with pipeline version being:  1.3

Here is the output:

Error from server (Invalid): error when applying patch:

{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{},\"labels\":{\"application-crd-id\":\"kubeflow-pipelines\",\"component\":\"metadata-envoy\"},\"name\":\"metadata-envoy-deployment\",\"namespace\":\"kubeflow\"},\"spec\":{\"replicas\":1,\"selector\":{\"matchLabels\":{\"application-crd-id\":\"kubeflow-pipelines\",\"component\":\"metadata-envoy\"}},\"template\":{\"metadata\":{\"labels\":{\"application-crd-id\":\"kubeflow-pipelines\",\"component\":\"metadata-envoy\"}},\"spec\":{\"containers\":[{\"image\":\"gcr.io/ml-pipeline/metadata-envoy:1.3.0\",\"name\":\"container\",\"ports\":[{\"containerPort\":9090,\"name\":\"md-envoy\"},{\"containerPort\":9901,\"name\":\"envoy-admin\"}]}]}}}}\n"},"labels":{"app.kubernetes.io/component":null,"app.kubernetes.io/instance":null,"app.kubernetes.io/managed-by":null,"app.kubernetes.io/name":null,"app.kubernetes.io/part-of":null,"app.kubernetes.io/version":null,"application-crd-id":"kubeflow-pipelines","component":"metadata-envoy","kustomize.component":null}},"spec":{"selector":{"matchLabels":{"app.kubernetes.io/component":null,"app.kubernetes.io/instance":null,"app.kubernetes.io/managed-by":null,"app.kubernetes.io/name":null,"app.kubernetes.io/part-of":null,"app.kubernetes.io/version":null,"application-crd-id":"kubeflow-pipelines","component":"metadata-envoy","kustomize.component":null}},"template":{"metadata":{"labels":{"app.kubernetes.io/component":null,"app.kubernetes.io/instance":null,"app.kubernetes.io/managed-by":null,"app.kubernetes.io/name":null,"app.kubernetes.io/part-of":null,"app.kubernetes.io/version":null,"application-crd-id":"kubeflow-pipelines","component":"metadata-envoy","kustomize.component":null}},"spec":{"$setElementOrder/containers":[{"name":"container"}],"containers":[{"image":"gcr.io/ml-pipeline/metadata-envoy:1.3.0","name":"container"}]}}}}

**Comment by Bobgy** [comment]
The upgrade command is only supported by Kubeflow Pipelines standalone. You cannot use it to upgrade Kubeflow.

**Comment by Bobgy** [comment]
https://www.kubeflow.org/docs/pipelines/installation/overview/

**Comment by pkasson-ascena** [comment]
We were trying to upgrade only pipelines - possibly the pasted results from above were from the other approach, that being a frest install.  Does the upgrade to pipelines work, if you are on KF 1.0.2 and whatever the version of pipelines is for that ?
