### ISSUE TITLE
Issues with deploy model

### ISSUE THREAD

**Issue by devilmetal** [kubeflow/pipelines#5037]
### What steps did you take:
After trying to use the "model" parameter of the ml_engine deploy component, we are now facing issue regarding deployment of model with the same names.

https://github.com/kubeflow/pipelines/tree/master/components/gcp/ml_engine/deploy
### What happened:
While using 'replace_existing_version' parameter, the component raison 409 error.

### What did you expect to happen:
While using 'replace_existing_version' parameter, the model version is replace by the one provided

"returned "Field: model.name Error: A model with the same name already exists."

### Environment:
Jupyter hub - Running on GCP
KubeFlow - Running on GCP

How did you deploy Kubeflow Pipelines (KFP)?
Using kubeflow components and python.

KFP version: 1.3.0

KFP SDK version: 1.3.0

/kind bug

Our main problem is regarding deployment. When using the "model" parameter with the following values, a 409 error raise and the model is actually not deployed. Without the "model" parameter, the behaviour is correct as expected.

model={
          'name': 'some_name',
          'regions': [
                "europe-west1"
                ],  
          'onlinePredictionLogging': True,
          'onlinePredictionConsoleLogging': True,
          'labels': {
              'some_label': 'some_value'
          }  
        }

We spotted the faulty line here :

https://github.com/kubeflow/pipelines/blob/32ce8d8f90bfc8f89a2a3c347ad906f99ba776a8/components/gcp/container/component_sdk/python/kfp_component/google/ml_engine/_create_model.py#L69

It seems that the comparison between the existing model and the one passed by parameter is not matching.    

While looking at the code we also spotted a few potential issues 

At this line, the model name seems to be always overwritten, even if you specify it in the model object given as parameter.
https://github.com/kubeflow/pipelines/blob/32ce8d8f90bfc8f89a2a3c347ad906f99ba776a8/components/gcp/container/component_sdk/python/kfp_component/google/ml_engine/_create_model.py#L83

At this line, you might have omitted the field 'onlinePredictionConsoleLogging' and other new fields. https://github.com/kubeflow/pipelines/blob/32ce8d8f90bfc8f89a2a3c347ad906f99ba776a8/components/gcp/container/component_sdk/python/kfp_component/google/ml_engine/_create_model.py#L92

Here is the stacktrace

`Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/ml/kfp_component/launcher/__main__.py", line 45, in <module>
    main()
  File "/ml/kfp_component/launcher/__main__.py", line 42, in main
    launch(args.file_or_module, args.args)
  File "/ml/kfp_component/launcher/launcher.py", line 45, in launch
    return fire.Fire(module, command=args, name=module.__name__)
  File "/usr/local/lib/python3.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/usr/local/lib/python3.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/usr/local/lib/python3.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "/ml/kfp_component/google/ml_engine/_deploy.py", line 66, in deploy
    model_name_output_path=model_name_output_path,
  File "/ml/kfp_component/google/ml_engine/_create_model.py", line 39, in create_model
    model_object_output_path=model_object_output_path,
  File "/ml/kfp_component/google/ml_engine/_create_model.py", line 65, in execute
    model = self._model)
  File "/ml/kfp_component/google/ml_engine/_client.py", line 82, in create_model
    body = model
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 851, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 409 when requesting 
https://ml.googleapis.com/v1/projects/xxxxxxxxx/models?alt=json
 returned "Field: model.name Error: A model with the same name already exists.">`

**Comment by nielsdewulf** [comment]
Has a fix been implemented yet and is there a working version with the model object that we can use in the meantime?

**Comment by Bobgy** [comment]
@devilmetal Thank you for the detailed report!
This hasn't been implemented, PRs welcomed.
