### ISSUE TITLE
Kubeflow 1.2 PVC volume is not getting deleted

### ISSUE THREAD

**Issue by ajinkya933** [kubeflow/pipelines#5046]
### What steps did you take:
[A clear and concise description of what the bug is.]

### What happened:
I am able to train MNIST dataset and make predictions on Kubeflow using attached code:
[mnist.zip](https://github.com/kubeflow/pipelines/files/5885493/mnist.zip)

The execution of attached code on Kubeflow is as shown.
![volume_delete](https://user-images.githubusercontent.com/17012391/106105082-6510eb00-6169-11eb-8894-cd9ed123d102.png)

However even after deleting the volume, the actual volume on AWS ec2 is only getting detatched, its not getting deleted.

Detached volume on AWS ec2: 
![Screenshot from 2021-01-28 13-06-14](https://user-images.githubusercontent.com/17012391/106105236-ad300d80-6169-11eb-959f-592cf3ceba1a.png)

### What did you expect to happen:
I expected the volume to get deleted

How Do I properly delete the volume ?

### Environment:
kfp                      1.3.0
kfp-pipeline-spec        0.1.4
kfp-server-api           1.2.0

/kind bug
/area sdk
/area testing

**Comment by kim-sardine** [comment]
In my case, I manually delete volume using ResourceOp with delete action in ExitHandler

https://github.com/kubeflow/pipelines/issues/1779#issuecomment-674085829

**Comment by elikatsis** [comment]
This should be unrelated to KFP. It sounds like an issue/configuration of the storage class not deleting dynamically provisioned volumes on PVC deletion.

Do you confirm that the PVC is deleted?

I would expect some configuration to allow this sequence of actions:
1. User deletes PVC
2. CSI deletes PV
3. Volume is deleted from AWS

I may be missing something though

**Comment by Bobgy** [comment]
Agree with elikatsis on this
