### ISSUE TITLE
How to make file_outputs dynamic in the KFP SDK?

### ISSUE THREAD

**Issue by PatrickGhosn** [kubeflow/pipelines#5048]
/kind question

```
import json
import kfp
from kfp import components
from kfp import dsl
import os
import subprocess
from kfp.components import func_to_container_op, InputPath, OutputPath

def compute_test_features(
  input_test_path,
  output_path : OutputPath
):
  return dsl.ContainerOp(
      name='Compute Mesh Features',
      image='gcr.io/brightclue-mlops/component-featurecomputation:v1',
      arguments=[
          '--input-test-path', input_test_path,
      ],
     file_outputs={'output':output_path}, 
  )
```

But when I try to compile the pipeline I get the below:
`TypeError: Object of type PipelineParam is not JSON serializable`

How can I have the file output be a parameter/dynamic?

**Comment by zijianjoy** [comment]
file_outputs is deprecated, please refer to `component` for the use case: https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.components.html

**Comment by PatrickGhosn** [comment]
Thank you. Yes we ended up using outputs.
