### ISSUE TITLE
Support placeholder replacement for one-time-run

### ISSUE THREAD

**Issue by IronPan** [kubeflow/pipelines#505]
Currently for recurrent run, we support placeholder replacement 
https://github.com/kubeflow/pipelines/blob/master/backend/src/crd/samples/scheduledworkflow/parameterized.yaml

These won't be replaced when it's one-time-run, since one-time-run doesn't create a scheduled workflow CRD but a argo workflow CRD directly.

**Comment by vicaire** [comment]
Has this been resolved?

**Comment by IronPan** [comment]
No this is still an improvement to be done.
