### ISSUE TITLE
API: get experiment by name

### ISSUE THREAD

**Issue by jlewi** [kubeflow/pipelines#506]
It doesn't seem like the client SDK supports getting the experiment by name.

```
Help on method get_experiment in module kfp._client:

get_experiment(experiment_id) method of kfp._client.Client instance
    Get details of an experiment
    Args:
      id of the experiment.
    Returns:
      A response object including details of a experiment.
    Throws:
      Exception if experiment is not found.
```

This isn't helpful if you know the name of the expeirment but  not the id.

You can use the list method to search over the experiments and get it by name.

```
{'experiments': [{'created_at': None,
                  'description': None,
                  'id': 'd77fe1f6-ccd7-4256-a504-be29cdd8ca95',
                  'name': 'code search demo'},
                 {'created_at': None,
                  'description': None,
                  'id': 'cbe79181-ed79-4a81-a6d0-6b2b214143d2',
                  'name': 'code-search-25'},
                 {'created_at': None,
                  'description': None,
                  'id': '2e8eecf1-dbae-4d9f-9e77-4fcc9efb360a',
                  'name': 'jlewi-notebook-test'}],
 'next_page_token': None}
```

**Comment by qimingj** [comment]
Agree. It's good to provide a convenient method, especially the experiment name is unique.

**Comment by gaoning777** [comment]
In fact, the sample test has implemented the  get_experiment_by_name function: https://github.com/kubeflow/pipelines/blob/fa1886c39d9a39aff94d9276a8d55d54a162959b/test/sample-test/check_notebook_results.py#L55

**Comment by gaoning777** [comment]
Another good to have API might be get_runs_in_experiments. Again, the sample test implemented the function:
https://github.com/kubeflow/pipelines/blob/fa1886c39d9a39aff94d9276a8d55d54a162959b/test/sample-test/check_notebook_results.py#L62

**Comment by qimingj** [comment]
Great. @gaoning777 would you move it to SDK?

**Comment by gaoning777** [comment]
Sure thing. I'll send a PR.

**Comment by vicaire** [comment]
Should we have API support for this as well? (@IronPan)

**Comment by gaoning777** [comment]
SDK already supports "get experiment by name".

**Comment by Ark-kun** [comment]
I think this is fixed.
