### ISSUE TITLE
present KFP at the Argo Workflows community meeting

### ISSUE THREAD

**Issue by alexec** [kubeflow/pipelines#5061]
We'd love you to come and present at our community meeting! http://bit.ly/argo-wf-cmty-mtng

Or what about writing a guest blog post? https://blog.argoproj.io/

I think our community would be super interested.

**Comment by Bobgy** [comment]
Thank you for the invitation!
I'm recently very busy with KFP v2 design I just shared with community. I'd love to sign up for a slot after a while when I get more time.
