### ISSUE TITLE
Collapsing For-loop components in the UI for large number of components 

### ISSUE THREAD

**Issue by bakhtiary** [kubeflow/pipelines#5106]
### What steps did you take:
I ran a pipeline with a large fanout 

### What happened:
![image](https://user-images.githubusercontent.com/5190152/107065442-11437900-67dd-11eb-8d47-19131f64f738.png)

### What did you expect to happen:
It would be better if the items that are generated from the same statement would stay collapsed until clicked on. Or some other form of ui system that would allow a good view of what is going on.

### Environment:
kubeflow pipelines 1.3 stand alone installation

How did you deploy Kubeflow Pipelines (KFP)?
Stand alone on AWS

1.3

### Anything else you would like to add:
I understand this is a feature request. Is there a way for our company to put a bounty on this?

/kind feature
/area frontend

**Comment by Bobgy** [comment]
This is sth we are thinking about for KFP v2 UI
