### ISSUE TITLE
What is the Meaning for KFP_FLAGS.DEPLOYMENT

### ISSUE THREAD

**Issue by kudla** [kubeflow/pipelines#5117]
Please. Just can't find any info on `KFP_FLAGS.DEPLOYMENT` for pipelines implementation

According to 
[front](https://github.com/kubeflow/pipelines/blob/1.1.2/frontend/src/index.tsx#L59) 
```jsx
ReactDOM.render(
  KFP_FLAGS.DEPLOYMENT === Deployments.KUBEFLOW ? (
    <NamespaceContextProvider>{app}</NamespaceContextProvider>
  ) : (
    // Uncomment the following for namespace switch during development.
    // <NamespaceContext.Provider value='your-namespace'>{app}</NamespaceContext.Provider>
    <NamespaceContext.Provider value={undefined}>{app}</NamespaceContext.Provider>
  ),
  document.getElementById('root'),
);
```
and [api server](https://github.com/kubeflow/pipelines/blob/1.2.0/backend/src/apiserver/server/experiment_server.go#L136) 
```js
	if common.IsMultiUserMode() {
		if refKey == nil || refKey.Type != common.Namespace {
			return nil, util.NewInvalidInputError("Invalid resource references for experiment. ListExperiment requires filtering by namespace.")
		}
		namespace := refKey.ID
		if len(namespace) == 0 {
			return nil, util.NewInvalidInputError("Invalid resource references for experiment. Namespace is empty.")
		}
		resourceAttributes := &authorizationv1.ResourceAttributes{
			Namespace: namespace,
			Verb:      common.RbacResourceVerbList,
		}
		err = s.canAccessExperiment(ctx, "", resourceAttributes)
		if err != nil {
			return nil, util.Wrap(err, "Failed to authorize with API resource references")
		}
	} else {
		if refKey != nil && refKey.Type == common.Namespace && len(refKey.ID) > 0 {
			return nil, util.NewInvalidInputError("In single-user mode, ListExperiment cannot filter by namespace.")
		}
		// In single user mode, apply filter with empty namespace for backward compatibile.
		filterContext = &common.FilterContext{
			ReferenceKey: &common.ReferenceKey{Type: common.Namespace, ID: ""},
		}
	}

```
codebases  it seems `KFP_FLAGS.DEPLOYMENT` correlates tightly with `MULTIUSER` support. I.e. only `KUBEFLOW` deployment supports `MULTIUSER`  mode. And vice versa for a Single User Mode the `KUBEFLOW`  one should not be used. 

But what is a wider scope for this `KFP_FLAGS.DEPLOYMENT`? 
How this supposed to be really used for a Single User mode?
Or where can I read on this

Thanks

**Comment by Bobgy** [comment]
Hi @kudla, it's used to distinguish the three installation modes in https://www.kubeflow.org/docs/pipelines/installation/overview/.

And as you already understood, the major difference is multi user mode. It's not really used much for other ways.

**Comment by Bobgy** [comment]
Question answered, feel free to raise new issues or keep commenting if you have more questions.
