### ISSUE TITLE
Failed to install KFP due to Error: Error 1054: Unknown column 'idx_pipeline_version_uuid_name' in 'where clause

### ISSUE THREAD

**Issue by uhhc** [kubeflow/pipelines#5121]
### What steps did you take:
I'm installing KFP in a new k8s cluster.

### What happened:

In pod console log, it shows error as follows:

```
Failed to query pipeline_version table's indices. Error: Error 1054: Unknown column 'idx_pipeline_version_uuid_name' in 'where clause'
```

But it successfully deployed in the past. So we checked the difference between them and found the sql_mode in MySQL are not the same. The newer set 'ANSI_QUOTES' in sql_mode value, and no errors occur when remove this value.

The [MySQL doc](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_ansi_quotes) says:

> ANSI_QUOTES
> Treat " as an identifier quote character (like the ` quote character) and not as a string quote character. You can still use ` to quote identifiers with this mode enabled. With ANSI_QUOTES enabled, you cannot use double quotation marks to quote literal strings because they are interpreted as identifiers.

When I checked the [source code](https://github.com/kubeflow/pipelines/blob/master/backend/src/apiserver/client_manager.go#L271), I found you use **double quotation marks** in raw SQL clause: 

```
show index from pipeline_versions where Key_name="idx_pipeline_version_uuid_name"
```

and it would be **not compatible with different sql_mode**.

Change the double quotation marks to single quotes will solve this problem.

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

Through my Helm/Charts

KFP version: `0.1.38` (This problem affects all the versions include the latest master)

KFP SDK version: 

### Anything else you would like to add:

/kind bug

/area backend

**Comment by capri-xiyue** [comment]
@uhhc  Are you willing to take over this issue? In addition, if we change it to single quote, will it affects users using other mysql mode?

**Comment by uhhc** [comment]
> @uhhc Are you willing to take over this issue? In addition, if we change it to single quote, will it affects users using other mysql mode?

Okay, I'll commit a PR in a moment. The single quote is the right and compatible way to enclose string literals in MySQL, it will not be affected by sql mode. For more info please see [here](https://dev.mysql.com/doc/refman/5.7/en/string-literals.html).
