### ISSUE TITLE
Data Versioning with Kubeflow

### ISSUE THREAD

**Issue by Vindhya-Singh** [kubeflow/pipelines#5124]
Hello,

I am working on setting up an in-house ML infrastructure for my company and we decided to go with Kubeflow. We need to ensure that the pipelines have the provision for data versioning as well. I understand from the official documentation of Kubeflow that it is possible with Rok Data Management. However, we are interested in exploring other options as well. Thus, my question comes in two parts:

1. Is there any alternative to using Rok for data versioning with Kubeflow pipelines?
2. Is it possible to use DVC for data versioning with Kubeflow?

Thanks :)

**Comment by Bobgy** [comment]
Hi @VindhyaSRajan!

Did you look into https://github.com/pachyderm/pachyderm? I think they also have some integration with KFP.
KFP is very flexible to work with any external system by components.

Any feedback on gaps?

**Comment by DavidSpek** [comment]
Can KFP be set to take kubernetes snapshots after each step, and then pass the name of that snapshot as the `data_source` for the next step? If not, I think that is a solid place to start for having data versioning built into KFP. I have been working on code for Kale that, once working, should create pipelines that create snapshots after each step https://github.com/kubeflow-kale/kale/pulls.

**Comment by Bobgy** [comment]
That's an interesting idea, how do you envision that being a 1st party feature? Does it need to?

**Comment by DavidSpek** [comment]
Sorry, I completely missed your response. I’d need to think a bit about how this could be a first party feature, but I do think it is something people would be interested in. It would allow for data lineage which is needed in some environments (like research) and could help with debugging a pipeline. 

Am I right in thinking the implementation for a feature like this would greatly differ between KFP V1 and V2?

**Comment by springcoil** [comment]
Hey just wanted to comment on this to ask if there's any progress? I've a team of researchers and we're interested in using something like DVC in kfp.

**Comment by cenkbircanoglu** [comment]
+1

**Comment by sabarnwal** [comment]
+1

**Comment by rwathena** [comment]
+1

**Comment by gpotti** [comment]
+1

**Comment by rimolive** [comment]
I'm closing this issue because this seems out of scope of pipelines. Feel free to open another issue if you feel it's inaccurate.

/close
