### ISSUE TITLE
Upgrade gorm

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#5125]
@capri-xiyue  The creation of a unique index with (Namespace, Name) is done in the client manager. The reason we can't do this as part of the Pipeline struct definition is because the KFP repository is using a branch of the gorm package ```"github.com/jinzhu/gorm"``` which does not support it, the refactoring for this is not in scope. 

_Originally posted by @maganaluis in https://github.com/kubeflow/pipelines/pull/4835#discussion_r571721941_

**Comment by maganaluis** [comment]
@Bobgy 
By the way, I noticed that we are not using the main gorm repository ```"gorm.io/gorm"```, this will lead to conflict in the future. It should probably become a future refactoring task for the KFP team. 

For example the way to add a composite unique index is shows as below, but this gave me a syntax error with the current gorm repository being used... ```"github.com/jinzhu/gorm"```

```golang
package main

import (
	"gorm.io/driver/mysql"
	"gorm.io/gorm"
)

// ALTER TABLE dev.pipelines ADD UNIQUE `unique_index`(`Name`, `Namespace`);
type Pipeline struct {
	gorm.Model
	Namespace string `gorm:"column:Namespace; size:63; default:''; index:idx_name_ns, unique"`
	Name      string `gorm:"column:Name; not null; index:idx_name_ns"`
}

func main() {
	// db, err := gorm.Open(sqlite.Open("test.db"), &gorm.Config{})
	dsn := "root:@tcp(localhost:3306)/dev?charset=utf8mb4&parseTime=True&loc=Local"
	db, err := gorm.Open(mysql.Open(dsn), &gorm.Config{})
	if err != nil {
		panic("failed to connect database")
	}

	// Migrate the schema
	db.AutoMigrate(&Pipeline{})

	// Create
	db.Create(&Pipeline{Namespace: "admin", Name: "p2"})
}
```
