### ISSUE TITLE
Can not load pipeline 

### ISSUE THREAD

**Issue by dwu926** [kubeflow/pipelines#5126]
### What steps did you take:
When I tried to upload the pipeline which is in format of "pipeline.tar.gz" and there is always an error and can not load the pipeline.

### What happened:

Pipeline version creation failed
upstream connect error or disconnect/reset before headers. reset reason: connection termination

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

KFP version: 

KFP SDK version: 

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by Bobgy** [comment]
Can you answer the environment questions? I need more information to scope down the problem
