### ISSUE TITLE
Support textarea input for pipeline parameter

### ISSUE THREAD

**Issue by kim-sardine** [kubeflow/pipelines#5129]
### What steps did you take:

I'd like to get multi-line bash script from user and pass it into ContainerOp.

### What happened:

but for now, Pipeline frontend only support two types of pipeline parameter - one line text input, json editor.

of course I can do it by appending all lines with semi-colon or by using list type and joining dynamically, but it's not intuitive.
but I'm not sure how to make pipeline code tell frontend to use textarea input. beacuse there is no type hint for multi line string.
maybe we could use custom type or use textarea input as default

### Environment:

kfp_istio_dex_1.2.0 on Windows Docker Desktop

/kind feature
/area frontend

**Comment by Bobgy** [comment]
Hi, you can find frontend contribution guide in https://github.com/kubeflow/pipelines/tree/master/frontend,
and the create run page is implemented in https://github.com/kubeflow/pipelines/blob/master/frontend/src/pages/NewRun.tsx
