### ISSUE TITLE
Error pulling gcr.io/ml-pipeline/ml-pipeline-gcp:1.4.0

### ISSUE THREAD

**Issue by BorFour** [kubeflow/pipelines#5130]
I've been using a component that uses the image `gcr.io/ml-pipeline/ml-pipeline-gcp:1.4.0`. When I try to use it, the component's pod seems to be stuck with the `ImagePullBackOff` status and, eventually, the pipeline times out. I then tried to run the image locally like so:

```bash
docker pull gcr.io/ml-pipeline/ml-pipeline-gcp:1.4.0
```

And then I get this error message:

```bash
Error response from daemon: manifest for gcr.io/ml-pipeline/ml-pipeline-gcp:1.4.0 not found: manifest unknown: Failed to fetch "1.4.0" from request "/v2/ml-pipeline/ml-pipeline-gcp/manifests/1.4.0".
```

I then tried to pull `gcr.io/ml-pipeline/ml-pipeline-gcp:1.3.0` locally and it works just fine. My workaround was to use the same component but with the repo tag `1.3.0`, as it uses this image, but I can't figure out why 1.4.0 doesn't work.

**Comment by Bobgy** [comment]
Hey @BorFour, sorry about the inconvenience, there was a short period the image was not built yet.

You should be able to use it now.

The best source is to look at github releases, if the release note isn't appended, that means the release was not yet finished.
