### ISSUE TITLE
Kubeflow Pipelines: Move manifests development upstream

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/pipelines#5133]
### Background

Umbrella-Issue: https://github.com/kubeflow/manifests/issues/1740

As part of the work of wg-manifests for 1.3
(https://github.com/kubeflow/manifests/issues/1735), we are moving manifests
development to upstream repos. This gives the application developers full
ownership of their manifests, tracked in a single place.

To give an example from the `notebook-controller`, the diagram shows the current
situation. Manifests are in two repos, blurring separation of responsibilities
and making things harder for application developers.

![diagram_1](https://user-images.githubusercontent.com/6123106/107092187-c9881600-680b-11eb-9993-fc04c5e5b6dd.PNG)

Instead, we will copy all manifests from the manifests repo back to each
upstream's repo. From there, they will be imported in the manifests repo. The
following diagram presents the desired state:

![diagram_2](https://user-images.githubusercontent.com/6123106/107092197-cd1b9d00-680b-11eb-8123-7fa5424c5cb2.PNG)

### Current State

Kubeflow Pipelines has manifests:
- In the manifests repo, under folder `apps/pipeline/upstream`.
- In upstream repo (https://github.com/kubeflow/pipelines) under folder `manifests/kustomize`.

The current state of the manifests repo and the upstream repo is the following:
![image (8)](https://user-images.githubusercontent.com/6123106/107816463-78cd6b80-6d7d-11eb-94bb-b33a89cf43de.png)

The kubeflow/manifests part of pipelines consists of the following:
- An `upstream` folder, which contains the copied upstream manifests from kubeflow/manifests.
- A kustomization for the pipelines cache (cache folder).
- The `installs` folder, which contains various installation profiles for pipelines (generic, multi-user, tekton, multi-user-tekton). The kustomizations under `installs` refer to the `cache` folder and the `upstream` folder.
- A bunch of folders (`api-service`, `minio`, `mysql`, `persistent-agent`, `pipeline-visualization-service`, `pipelines-runner`, `pipelines-ui`, `pipelines-viewer`, `scheduledworkflow`) which seem unused, since those manifests already exist upstream (most are in kubeflow/pipelines under `manifests/kustomize/base/pipeline`, `minio` and `mysql` are under `manifests/kustomize/env/platform-agnostic`)

I understand that the `installs` folder would probably be transferred under `env` in this repo.
What about all the other folders? Are they maintained by KFP? Are they abandoned? cc @Bobgy 

### Desired State

The proposed folder in the upstream repo to receive the manifests is:
`manifests/kustomize`.

The goal is to consolidate all manifests development in the upstream repo.
The manifests repo will include a copy of the manifests under `apps/pipeline/upstream`.
This copy will be synced periodically.

### Success Criteria

The manifests in `apps/pipeline/upstream` should be a copy of the upstream manifests
folder. To do that, the application manifests in `kubeflow/manifests` should be
moved to the upstream application repo.

/assign @yanniszark
cc @kubeflow/wg-pipeline-leads

**Comment by Bobgy** [comment]
Thank you!

> I understand that the installs folder would probably be transferred under env in this repo.

Let me think about it, there might be too many types and they are not conceptually consistent. Current manifests in env all include mysql and minio, but those in kubeflow/manifest/.../installs don't.

> What about all the other folders? Are they maintained by KFP? Are they abandoned? cc

No, you can remove the other folders.

**Comment by yanniszark** [comment]
> Let me think about it, there might be too many types and they are not conceptually consistent\

@Bobgy I was wondering if you had any thoughts on this issue. I can start a PR making `installs` into `envs`. What do you think?

**Comment by Bobgy** [comment]
My current preference is to move installs into kustomize/base/installs/{generic,multi-user}
(Probably rename base to core, but that can be done later)

Move mysql and minio into kustomize/storage/mysql, kustomize/storage/minio.

And, use kustomize/env/xxx to compose them.

What do you think?
The main motivation is to make component role & boundary clearer.

**Comment by Bobgy** [comment]
@yanniszark pinging for status update, I want to make sure we don't have duplicate efforts

**Comment by yanniszark** [comment]
@Bobgy thanks for the ping. I want to ask for more info on your suggestion.
You proposed:

> kustomize/base/installs/{generic,multi-user}

Currently, the base folder is broken up per-component (application. argo, cache, metadata, pipeline).
This includes both pipelines (pipelines, cache) and non-pipelines apps (argo, application-controller, metadata).
Those are composed into a kustomization in `base/kustomization.yaml`. In addition, `base/kustomization.yaml` only contains namespaced resources.

The multi-user pipelines manifests adds/edits resources to pipelines components (api-service, cache, metadata-writer, persistence-agent, pipelines-profile-controller, pipelines-ui, scheduled-workflow, viewer-controller).

So if I understand correctly:
- `base/kustomization.yaml` will become `base/installs/generic`
- `base/installs/multi-user` will contain the resources for multi-user pipelines. However, these resources are both cluster and namespace-scoped. Personally, I don't see the reason for the namespaced/non-namespaced distinction but I see there was some quite some effort to structure this way, so I'd love to know more. Alternatively, we could do `base/installs/multi-user/cluster-scoped` too.

Finally, what about the tekton installs? Should they go under `env`?

**Comment by Bobgy** [comment]
That reminds me a few things,
`application` should now be moved out as optional, because we don't need it in kubeflow.

> Personally, I don't see the reason for the namespaced/non-namespaced distinction

Because in namespaced installation mode, cluster admin can be a separate group of people than namespace admins. So it's more convenient if there's a clear separation of cluster resources.

Therefore, this requirement isn't necessary for multi-user mode, because it's already meant to be shared across namespaces.

**Comment by Bobgy** [comment]
For tekton KFP, @animeshsingh what do you think?

My current thoughts are manifest should be next to where development is happening, so maintainence is easier if they are in kfp-tekton repo.

**Comment by Bobgy** [comment]
Fixed by #5256
