### ISSUE TITLE
Building component from Python function producing PendingDeprecationWarning

### ISSUE THREAD

**Issue by shaikmanu797** [kubeflow/pipelines#5139]
### What happened:
I have been using the below ContainerOp in a pipeline for unit tests and with `kfp>1.1.0` I started getting `PendingDeprecationWarning` while Compiling the pipeline using ContainerOp.

```python3
@pytest.fixture
def add_op() -> ContainerOp:
    def add_ints(a: int, b: int) -> int:
        return a + b
    add_comp = func_to_container_op(
        func=add_ints, base_image="python:3.7-slim-buster"
    )
    return add_comp
    
@dsl.pipeline("test", "test pipeline")
def test_pipeline(a: int, b: int):
   add = add_op(a, b)
   add.set_display_name("Add Two Integers")
   add.add_pod_label("component_name", "add_ints")

def test_pipeline_image_settings(self):
   with tempfile.NamedTemporaryFile(suffix=".yaml") as f:
       Compiler().compile(pipeline_func=test_pipeline, package_path=f.name)
```

```console
PendingDeprecationWarning: dsl.ContainerOp.image will be removed in future releases. Use dsl.ContainerOp.container.image instead
```

### What did you expect to happen:
Could someone let me know what is an alternative method to use to build component from a python function?

### Environment:
Python 3.8

How did you deploy Kubeflow Pipelines (KFP)?
Kubeflow on Kubernetes

KFP version: 

KFP SDK version: 1.4.0

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind question
/area sdk

**Comment by NikeNano** [comment]
In the documentation [here](https://www.kubeflow.org/docs/pipelines/sdk/python-function-components/) I think you can find the information you are looking for. It also points to some examples that should help guide you in the right direction. Let me know if you still have some issues.

**Comment by Bobgy** [comment]
I've written similar code, I think it's already fixed in later versions. Please correct me if I'm wrong
