### ISSUE TITLE
NYC Taxi Example Pipeline fails in AWS; can't find metadata server

### ISSUE THREAD

**Issue by pantelis** [kubeflow/pipelines#514]
We are working to adopt Kubeflow and more specifically Kubeflow Pipeline capabilities into the open source project Acumos (graduated from Deep Learning Foundation recently). We are facing issues in running complicated pipelines such as NYC Taxi that is shipped with Kubeflow.  The pipeline errors giving this message in the log: 

2018-12-10 19:57:48.003354: I tensorflow/core/platform/cloud/retrying_utils.cc:77] The operation failed and will be automatically retried in 0.881789 seconds (attempt 1 out of 10), caused by: Unavailable: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Couldn't resolve host 'metadata'
 
Is there anything that prevents the pipeline to successfully be executed in AWS ? Does the pipeline uses specific to google cloud services. Our setup is EKS and currently running with 2 x P3 instance GPU workers. Your timely response will be appreciated as we need to resolve any issues and determine Acumos - Kubeflow integration epics and stories for our next Release.

**Comment by gaoning777** [comment]
Kubeflow Pipeline should be successfully run in kubernetes cluster whether it being AWS or GCP. which sample exactly are you using? https://github.com/kubeflow/pipelines/tree/master/samples/tfx?

**Comment by jlewi** [comment]
@gaoning777 The error

```
'Couldn't resolve host name', error details: Couldn't resolve host 'metadata'
```

Could this be a reference to the GCE metadata server.

**Comment by gaoning777** [comment]
The TFX sample does not contain any codes to reach host 'metadata'.
Do you mind specifying the sample you tried, and the exact step that fails?
Thanks

**Comment by Jeffwan** [comment]
I will take over this one and add require supports.

**Comment by Jeffwan** [comment]
@pantelis @gaoning777 

@jlewi is right, code failed at 
https://github.com/kubeflow/pipelines/blob/ac7366b9d8fc453b982027e9198a5bb15efecb2c/components/kubeflow/deployer/src/deploy.sh#L63-L65

By default, `--cluster-name` is not part of arguments. User can skip query metadata service by adding  `--cluster-name`.  BTW, this is unnecessary to get access to kubernetes api server.  Cluster name can be arbitrary strings. Does GKE or GCP use this string? If this doesn't have special meaning, I can help remove this code snippet.

**Comment by Jeffwan** [comment]
I was wrong, just notice error message comes from tensorflow. Here's the problem, if `preprocessing_module` is not specified for `dataflow_tf_transform_op`, it will go make a preprocessing function, it retrieve `INCEPTION_V3_CHECKPOINT` which is gcs link `gs://cloud-ml-data/img/flower_photos/inception_v3_2016_08_28.ckpt`.

**Comment by jlewi** [comment]
Seems like there could be two different issues here

1. The pipelines component for deploying TFServing has a dependency on the GCE metadata server (not sure why that is)

1.  dataflow_tf_transform_op has a dependency on gcs?

**Comment by gaoning777** [comment]
1) If the user does not provide a preprocessing module, the default one uses a checkpointing and uses the file stored in GCS that the KFP published.

2) It looks like the tfserving component uses the [metadata server](https://cloud.google.com/compute/docs/storing-retrieving-metadata) to retrieve the cluster name if not provided in the user input. GKE cluster attach the cluster name as the attribute to the GCE cluster. 
BTW, is there anyway to easily configure the kubectl to connect to the cluster if it is running in a pod in the GKE.

However, there is no GCP dependency if these fields are provided by the users.

**Comment by Jeffwan** [comment]
> 2. It looks like the tfserving component uses the [metadata server](https://cloud.google.com/compute/docs/storing-retrieving-metadata) to retrieve the cluster name if not provided in the user input. GKE cluster attach the cluster name as the attribute to the GCE cluster.
>    BTW, is there anyway to easily configure the kubectl to connect to the cluster if it is running in a pod in the GKE.

I mean this ${CLUSTER_NAME} is used to create kubeconfig, it could be any string and doesn't have to be a real cluster name. The existing code base is straightforward to talk to API Server. 

> However, there is no GCP dependency if these fields are provided by the users.
Agree.

**Comment by jessiezcc** [comment]
@Jeffwan, will u take care of this issue? is it doc only?

**Comment by jessiezcc** [comment]
closing since there is no response and seems like it's a configuration issue, feel free to re-open.

**Comment by Jeffwan** [comment]
@jessesuen Miss your last comment. This can be improved in the example code. I will take it.
