### ISSUE TITLE
build_image_from_working_dir  Kubernetes job creation failed.

### ISSUE THREAD

**Issue by Adedolapo-Akin** [kubeflow/pipelines#5147]
### What steps did you take:
kfp v. 1.4.0

I'm trying build_image_from_working_dir() as per https://github.com/kubeflow/pipelines/blob/master/samples/core/container_build/container_build.ipynb, from an AI Platform notebook.

### What happened:

code
# Building and pushing new container image
image_with_packages = build_image_from_working_dir(
    #working_dir='.',                            # Optional. Default is the current directory
    #base_image='google/cloud-sdk:latest',       # Optional
    #image_name='gcr.io/my-org/my-image:latest', # Optional. Default is gcr.io/<project_id>/<notebook_id>/kfp_container
)
# Creating component while explicitly specifying the newly-built base image
read_data_op = func_to_container_op(read_data, base_image=image_with_packages)

Error

ERROR:root:Exception when calling CoreV1Api->create_namespaced_pod: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': '49f84f01-752c-4780-adfa-afd0fbdc184a', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Thu, 18 Feb 2021 10:41:35 GMT', 'Content-Length': '196'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \"kubeflow\" not found","reason":"NotFound","details":{"name":"kubeflow","kind":"namespaces"},"code":404}

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/kfp/containers/_k8s_job_helper.py", line 65, in _create_k8s_job
    api_response = self._corev1.create_namespaced_pod(yaml_spec['metadata']['namespace'], pod)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/api/core_v1_api.py", line 6174, in create_namespaced_pod
    (data) = self.create_namespaced_pod_with_http_info(namespace, body, **kwargs)  # noqa: E501
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/api/core_v1_api.py", line 6265, in create_namespaced_pod_with_http_info
    collection_formats=collection_formats)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 345, in call_api
    _preload_content, _request_timeout)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 176, in __call_api
    _request_timeout=_request_timeout)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 388, in request
    body=body)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/rest.py", line 278, in POST
    body=body)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/rest.py", line 231, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': '49f84f01-752c-4780-adfa-afd0fbdc184a', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Thu, 18 Feb 2021 10:41:35 GMT', 'Content-Length': '196'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \"kubeflow\" not found","reason":"NotFound","details":{"name":"kubeflow","kind":"namespaces"},"code":404}

### What did you expect to happen:

To build image

### Environment:

GCP
AI Platform Notebook

**Comment by Bobgy** [comment]
Hi @Adedolapo-Akin , looks like your KFP is not deployed in kubeflow namespace.
You can configure the namespace when using build_image_from_working_dir: https://kubeflow-pipelines.readthedocs.io/en/stable/source/kfp.containers.html#kfp.containers.build_image_from_working_dir
