### ISSUE TITLE
Default Notebook images cannot install KFP due to enum34

### ISSUE THREAD

**Issue by allenc97** [kubeflow/pipelines#5151]
### What steps did you take:
[A clear and concise description of what the bug is.]
I ran "pip install kfp" in the default notebook server image gcr.io/kubeflow-images-public/tensorflow-2.1.0-notebook-cpu:1.0.0. 
### What happened:
...
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/local/lib/python3.6/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-e1cn2jdf/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (14 lines):
  Traceback (most recent call last):
    File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.6/dist-packages/pip/__main__.py", line 16, in <module>
      from pip._internal.main import main as _main  # isort:skip # noqa
    File "/usr/local/lib/python3.6/dist-packages/pip/_internal/main.py", line 8, in <module>
      import locale
    File "/usr/lib/python3.6/locale.py", line 16, in <module>
      import re
    File "/usr/lib/python3.6/re.py", line 142, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/local/lib/python3.6/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-e1cn2jdf/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.

### What did you expect to happen:
It should install successfully. The above error happens because enum34 is installed. The notebook image uses python3.6, which does not need an enum backport. Also, I cannot uninstall inside the image without root privileges, which means the HEAD images need to be rebuilt.
### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

Azure with OIDC

KFP version: 1.2.0

KFP SDK version: Can't install..

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by allenc97** [comment]
Additional info:
enum34 is installed by jupyter-http-over-ws==0.0.7. The latest version, 0.0.8, has added restrictions in setup.py to prevent installing enum34 for python3.4+. A brute force fix would be changing the pip installs in the image to the following:

``RUN pip3 uninstall -y enum34 jupyter-http-over-ws &&     pip3 --no-cache-dir install     jupyter-console==6.0.0     jupyterlab     xgboost     kubeflow-fairing==1.0.1     kfp     jupyter-http-over-ws``

**Comment by sramirez** [comment]
Same here.

**Comment by Bobgy** [comment]
/cc @DavidSpek @kimwnasptd 
Looks like the issue should be fixed on notebook side

**Comment by DavidSpek** [comment]
The default notebook images contain KFP and I haven't seen this error come up when I built them.

**Comment by allenc97** [comment]
I believe this is no longer relevant. The default behavior changed with commit https://github.com/kubeflow/manifests/commit/d36fc9c0555c936c7b71fd273b8e4604985ebba8#diff-dcdcdee366160f43e5771e4d4ccbfcb180ea8fbcfa23b07be243a326f49a2a39, as spawner_ui_config was updated to use new docker images, which presumably have KFP preinstalled.

**Comment by Bobgy** [comment]
Thanks for the update!
