### ISSUE TITLE
Recommended Daemon Container Support Alternative?

### ISSUE THREAD

**Issue by jl-massey** [kubeflow/pipelines#5155]
# Argo Daemon Containers
I've looked through as many docs I could find and determined that Argo pipelines support daemon containers that suit my purposes pretty well  (spinning up database server to use as a cache for a pipeline). 

# Question:
1. Are there any examples of using daemon containers with KFP SDK in python?
2. If not, does someone have a 'solid' alternative to hacking the pipeline YAML?

Thanks a lot, also; I'm loving the work the team has done!

**Comment by omlomloml** [comment]
I was wondering about this too
does kfp have a Op which can start a container and just leave it there

Thanks

**Comment by jl-massey** [comment]
I've gotten around this by compiling the pipeline yaml, then adding the "daemon: true" line to the argo pipeline yaml before uploading to KFP server.   This feels like I've taken the long/wrong way around.
