### ISSUE TITLE
[FR] Configurable Image in Component.yaml

### ISSUE THREAD

**Issue by munagekar** [kubeflow/pipelines#5159]
Would it be possible to make the image name configurable in component.yaml specification, so that the end user could override the image.  It is possible to write a function to modify the yaml before it is read by ` kfp.components.load_component_from_text`, however I think this would be a useful addition to component.yaml specification, this is something that was supported by ContainerOp. 

For example the following component.yaml adds another additional inputValue to specify the docker image. However this does not work when loading the component.yaml. 

```yaml
name: echo
description: Academic Component. Echoes input to output.
metadata:
  annotations:
    version: "0.0.1"
inputs:
  - { name: Text, type: String, description: Text to be echoed }
  - { name: Docker Image, type: String, description: Docker Image to be used, default: alpine }
outputs:
  - { name: Echoed Text, type: String, description: Echoed Text }
implementation:
  container:
    image: {inputValue: Docker Image}
    command: [sh, -c]
    args: [
        echo $0 && mkdir -p "$(dirname "$1")" &&echo $0 > $1,
        { inputValue: Text },
        { outputPath: Echoed Text}
      ]
 ```
 
 However this does not work. Attempting to load this component gives an error.
 
 ```python
 kfp.components.load_component_from_text(manifest.read_text())
 ```
 
 # Traceback.
 ```
    kfp.components.load_component_from_text(manifest.read_text())
  File "/usr/local/lib/python3.8/site-packages/kfp/components/_components.py", line 115, in load_component_from_text
    component_spec = _load_component_spec_from_component_text(text)
  File "/usr/local/lib/python3.8/site-packages/kfp/components/_components.py", line 164, in _load_component_spec_from_component_text
    component_spec = ComponentSpec.from_dict(component_dict)
  File "/usr/local/lib/python3.8/site-packages/kfp/components/modelbase.py", line 285, in from_dict
    return parse_object_from_struct_based_on_class_init(cls, struct, serialized_names=cls._serialized_names)
  File "/usr/local/lib/python3.8/site-packages/kfp/components/modelbase.py", line 238, in parse_object_from_struct_based_on_class_init
    args[python_name] = parse_object_from_struct_based_on_type(value, param_type)
  File "/usr/local/lib/python3.8/site-packages/kfp/components/modelbase.py", line 158, in parse_object_from_struct_based_on_type
    raise TypeError('\n'.join(exception_lines))
TypeError: Error: ContainerImplementation.from_dict(struct=OrderedDict([('container', OrderedDict([('image', OrderedDict([('inputValue', 'Docker Image')])), ('command', ['sh', '-c']), ('args', ['echo $0 && mkdir -p "$(dirname "$1")" &&echo $0 > $1', OrderedDict([('inputValue', 'Text')]), OrderedDict([('outputPath', 'Echoed Text')])])]))])) failed with exception:
Error: ContainerSpec.from_dict(struct=OrderedDict([('image', OrderedDict([('inputValue', 'Docker Image')])), ('command', ['sh', '-c']), ('args', ['echo $0 && mkdir -p "$(dirname "$1")" &&echo $0 > $1', OrderedDict([('inputValue', 'Text')]), OrderedDict([('outputPath', 'Echoed Text')])])])) failed with exception:
Error: Structure "OrderedDict([('inputValue', 'Docker Image')])" is incompatible with type "<class 'str'>". Structure is not the instance of the type, the type does not have .from_dict method and is not generic.
Error: GraphImplementation.from_dict(struct=OrderedDict([('container', OrderedDict([('image', OrderedDict([('inputValue', 'Docker Image')])), ('command', ['sh', '-c']), ('args', ['echo $0 && mkdir -p "$(dirname "$1")" &&echo $0 > $1', OrderedDict([('inputValue', 'Text')]), OrderedDict([('outputPath', 'Echoed Text')])])]))])) failed with exception:
__init__() got an unexpected keyword argument 'container'
Error: Structure "OrderedDict([('container', OrderedDict([('image', OrderedDict([('inputValue', 'Docker Image')])), ('command', ['sh', '-c']), ('args', ['echo $0 && mkdir -p "$(dirname "$1")" &&echo $0 > $1', OrderedDict([('inputValue', 'Text')]), OrderedDict([('outputPath', 'Echoed Text')])])]))])" is not None.
Error: Structure "OrderedDict([('container', OrderedDict([('image', OrderedDict([('inputValue', 'Docker Image')])), ('command', ['sh', '-c']), ('args', ['echo $0 && mkdir -p "$(dirname "$1")" &&echo $0 > $1', OrderedDict([('inputValue', 'Text')]), OrderedDict([('outputPath', 'Echoed Text')])])]))])" is incompatible with type "typing.Union[kfp.components._structures.ContainerImplementation, kfp.components._structures.GraphImplementation, NoneType]" - none of the types in Union are compatible.
 ```

**Comment by munagekar** [comment]
Related : #5109

**Comment by Ark-kun** [comment]
What is you main usage scenario for this feature request?


Usually we advice out users to either use image tags (which are mutable) or use image replacement (in test scenarios). In KFP it's also possible to replace the container image after creating an instance of the component.
The `component.yaml` spec describes a command-line program inside container. So it is only compatible with specific family of images, making the `Docker Image` not a good candidate for an input.

**Comment by munagekar** [comment]
@Ark-kun Thank you for your response.

# Usage Scenarios

- Changes in Image, without changes in code. Example changes to python packages in the image, Changing the python docker version, etc. End users of the components could be able to customize the docker image. 
- For machine learning it is often necessary to ensure that the packages/versions used in training and serving are the exact same version. There can be subtle changes which might make training and serving different. A user will be able to use the same image for all steps of the training and serving process.
- Some clusters may have strong security requirements such as the images must be pulled in from authorized docker repository. Users on such cluster might want to simply change the image to an authorized docker registry.


> Usually we advice out users to either use image tags (which are mutable)

A mutable image tag does not give reproducibility. 

> it's also possible to replace the container image after creating an instance of the component.

I was not aware that this is possible. Could you point me to the relevant function or variable ?

Following is something I have resorted to.

```python
import yaml
def override_component_image(yaml_str: str, new_image: str) -> str:
    """
    Overrides the component image in yaml

    Args:
        yaml_str: Yaml file as a string
        new_image: The new image which it to be written.

    Returns:
        Modified yaml file with container image replaced
    """
    yaml_data = yaml.load(yaml_str, Loader=yaml.FullLoader)
    yaml_data["implementation"]["container"]["image"] = new_image
    return yaml.dump(yaml_data, sort_keys=False)

```

**Comment by Ark-kun** [comment]
>A mutable image tag does not give reproducibility.

Fair point. But the same is also true about components. For reproducibility you need a strict component version linking to a strict container image version.

>>it's also possible to replace the container image after creating an instance of the component.
>I was not aware that this is possible. Could you point me to the relevant function or variable ?

What instantiate a component, you get a task object. The task object is ContainerOp, which has `.container` property which allows you to configure any Kubernetes container properties (`image`, `resources`, etc).

So, you can tweak the container image after instantiating the component:

```python
task1 = op1(...)
task1.container.image = ...
```
Does this work for you?

>Following is something I have resorted to.

For a CI/CD scenario the best way would be to create a new version of component.yaml every time you create a new container version. This way, the pipeline can link to a strict component version and have reproducibility.

P.S. I had a thought about a building a compiler feature which allows substituting container images. I wonder whether this would be useful.

**Comment by munagekar** [comment]
```python
task1 = op1(...)
task1.container.image = ...
```
> Does this work for you?

This seems is reasonable and elegant solution for component users who have specific requirements. The scenarios I mentioned are rare and may be it is not worthwhile to build a compiler feature for this, especially when it is possible to override the image trivially.
