### ISSUE TITLE
client.create_experiment and client.get_experiment treat differences in case differently

### ISSUE THREAD

**Issue by ptitzler** [kubeflow/pipelines#5172]
### What steps did you take:

The following code snippet tries to create two experiments. The experiment names only differ in case, e.g. `Untitled` vs `untitled`

```
import kfp
client = kfp.Client(host='http://.../pipeline')
# create experiment succeeds if there is no experiment named `untitled` (ignoring case)
experiment = client.create_experiment('Untitled', namespace='anonymous')
# create experiment fails 
experiment = client.create_experiment('untitled', namespace='anonymous')

# output > Create experiment failed.: Already exist error: Failed to create a new experiment. The name untitled already exists. Please specify a new name.

experiment = client.get_experiment('untitled', namespace='anonymous')

# output > ValueError: No experiment is found with name untitled.
```

### What happened:

Create experiment fails because an experiment with the name already exists.

### What did you expect to happen:

`get_experiment` and `create_experiment` behave the same (ignore case or honor it).

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

KFP version: 1.0.4

KFP SDK version: 1.3.0

### Anything else you would like to add:
 Found https://github.com/kubeflow/pipelines/issues/2240 but the issue is stale.

/kind bug

**Comment by Bobgy** [comment]
Makes sense, I think we should distinguish case when creating an experiment too.
Welcome contribution on this change.

**Comment by NikeNano** [comment]
The error originates from that `mysql` is [not case sensitve](https://dev.mysql.com/doc/refman/8.0/en/case-sensitivity.html) in the comparisons as I understand it for CHAR, VARCHAR, TEXT. 
```sql
ERROR 1062 (23000): Duplicate entry 'new-' for key 'idx_name_namespace'
```
where I use `new` as the experiment name.  

Will use lowercase for the comparisons as well.
