### ISSUE TITLE
KFServing v0.5 component for Kubeflow Pipelines

### ISSUE THREAD

**Issue by animeshsingh** [kubeflow/pipelines#5181]
Needs to be updated/upgraded/tested

**Comment by pvaneck** [comment]
There are quite a few changes with the v1beta1 API that comes with KFServing v0.5.0. Here are some initial findings as I go over the component use case:

KFServing Component Use Cases


- Create InferenceService for available frameworks. General structure would look like:
```
V1beta1InferenceService(
  spec=V1beta1InferenceServiceSpec(
      predictor=V1beta1PredictorSpec(
         tensorflow=V1beta1TFServingSpec(
           storage_uri=’gs://…’
         pytorch=V1beta1TorchServeSpec
         sklearn=V1beta1SKLearnSpec
         xgboost=V1beta1XGBoostSpec
         onnx=V1beta1ONNXRuntimeSpec
         pmml=V1beta1PMMLSpec
         triton=V1beta1TritonSpec
      explainer=V1beta1ExplainerSpec
      transformer=V1beta1TransformerSpec
```
- Allow custom serving.
  - Example v1beta1 custom YAML: https://github.com/kubeflow/kfserving/blob/master/docs/samples/v1beta1/custom/simple.yaml 
  - General structure:
  ```
  V1beta1PredictorSpec(
    containers=client.V1Container(
  ```
- Deploy and promote canaries
  - Canaries work a bit differently in v1beta1 (https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1beta1/rollout)
  - You now specify `canaryTrafficPercent` in V1beta1PredictorSpec spec
  - Promoting a canary model is done by removing the canaryTrafficPercent field.
  - Sample canary: https://github.com/kubeflow/kfserving/blob/master/test/e2e/predictor/test_canary.py

**Comment by pvaneck** [comment]
For the first iteration, can aim to mirror the current v1alpha2 functionality of the current component (the use cases listed above). Will target this for next week.

Next iteration, can focus on adding support for explainers and transformers.

The v2 predict API and multi-model serving, I believe, are still experimental, so support for those can be added in the future when those become stable features.

**Comment by pvaneck** [comment]
Draft PR is up, but still needs a bit more testing with actual pipelines as I only tested using the CLI. A README will also probably need to be created for documenting  various ways of using the component.
