### ISSUE TITLE
[TFX] penguins example

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#5193]
TFX iris example was removed in new releases, it should be replaced by penguins example.

context: https://github.com/kubeflow/pipelines/pull/5189

**Comment by Bobgy** [comment]
/cc @chensun 
Do you have bandwidth to take this?

Not urgent, but I believe we should better have it in next release.

**Comment by NikeNano** [comment]
I would be happy to help out with this as well.

**Comment by NikeNano** [comment]
blocked by: https://github.com/tensorflow/tfx/pull/3484
