### ISSUE TITLE
[TFX] TFMA 0.27.0 broken in KFP UI

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#5194]
> I tried to upgrade some other TFX related deps, however, I'm getting the following errors in various places in parameterized_tfx_sample:
> 
> * when clicking visualizations on `evaluator`, the visualization js simply crashes without any clear error message. I tried to take a look at browser console, but it only shows. EDIT: workarounded in #5191
> 
> ```
> Uncaught Error: Script error for: tensorflow_model_analysis
> http://requirejs.org/docs/errors.html#scripterror
>     at C (require.min.js:8)
>     at HTMLScriptElement.onScriptError (require.min.js:29)
> ```

Originally posted in https://github.com/kubeflow/pipelines/issues/5137#issuecomment-785012674

**Comment by Bobgy** [comment]
Worked around by https://github.com/kubeflow/pipelines/pull/5191.

We need to report the issue upstream.

**Comment by Bobgy** [comment]
> I see that both old and new fail to load the tensorflow_model_analysis.js script.
But then the old version succeeds in loading https://unpkg.com/tensorflow_model_analysis@0.21.5/dist/vulcanized_tfma.js while the new version fails trying to load from https://24643bfacd9ed2e-dot-us-central1.pipelines.googleusercontent.com/nbextensions/tensorflow_model_analysis/vulcanized_tfma.js

> In the index.js:
> 
> Before:
> 	function loadVulcanizedTemplate() {	
>   const templateLocation = __webpack_require__.p + 'vulcanized_tfma.js';
> After:
> function loadVulcanizedTemplate() {
>   const templateLocation =
>       (document.querySelector('body').getAttribute('data-base-url') || '/') +
>       'nbextensions/tensorflow_model_analysis/vulcanized_tfma.js';
> 

@Ark-kun 's investigation

**Comment by vaskozl** [comment]
With kubeflow 1.4.0 and TFX 0.27.0 the visualisation works for me on the first run when there is no baseline model.

However at on the second run I get:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-81-95e408225f11> in <module>
     10 columns=[] if len(featureKeys) == 0 else featureKeys[0]['featureKeys']
     11 slicing_spec = tfma.slicer.SingleSliceSpec(columns=columns)
---> 12 eval_result = tfma.load_eval_result('s3://kubeflow/tfx/eb_lstm/Evaluator/evaluation/147')
     13 slicing_metrics_view = tfma.view.render_slicing_metrics(eval_result, slicing_spec=slicing_spec)
     14 view = io.StringIO()

/usr/local/lib/python3.6/dist-packages/tensorflow_model_analysis/api/model_eval_lib.py in load_eval_result(output_path, output_file_format, model_name)
    273       output_path, output_file_format):
    274     plots_list.append(
--> 275         util.convert_plots_proto_to_dict(p, model_name=model_name))
    276   if not model_locations:
    277     model_location = ''

/usr/local/lib/python3.6/dist-packages/tensorflow_model_analysis/view/util.py in convert_plots_proto_to_dict(plots_for_slice, model_name)
    584     raise ValueError('Fail to find plots for model name: %s . '
    585                      'Available model names are [%s]' %
--> 586                      (model_name, ', '.join(keys)))
    587 
    588   return (slicer.deserialize_slice_key(plots_for_slice.slice_key), plots_map)

ValueError: Fail to find plots for model name: None . Available model names are [candidate, baseline]
```

As the model_name isn't specified.

**Comment by vaskozl** [comment]
It works on the first run since the util.py accepts None if there is only a single model with evaluation results:

https://github.com/tensorflow/model-analysis/blob/master/tensorflow_model_analysis/view/util.py#L585-L587

**Comment by Bobgy** [comment]
Thank you for raising the issue

What would be suggested fix on the caller line?

**Comment by vaskozl** [comment]
This works for me both on first and second runs:

https://github.com/kubeflow/pipelines/pull/5260

There is no `name` key if only one model evaluation is available (on the first run), hence the `.get` method and extra check.
