### ISSUE TITLE
bug in compilier.Compiler._validate_exit_handler

### ISSUE THREAD

**Issue by HaozhengAN** [kubeflow/pipelines#5198]
### What steps did you take:
```python
@dsl.pipeline(
    name='Conditional execution pipeline with exit handler',
    description='Shows how to use dsl.Condition() and dsl.ExitHandler().'
)
def flipcoin_exit_pipeline():
    exit_task = print_op('Exit handler has worked!')
    exit_task2 = print_op('Exit handler has worked!')
    with dsl.ExitHandler(exit_task):
        flip = flip_coin_op()
        with dsl.Condition(flip.output == 'heads'):
            random_num_head = get_random_int_op(0, 9)
            with dsl.Condition(random_num_head.output > 5):
                print_op('heads and %s > 5!')
            with dsl.Condition(random_num_head.output <= 5):
                print_op('heads and %s <= 5!' % random_num_head.output)

        with dsl.Condition(flip.output == 'tails'):
            random_num_tail = get_random_int_op(10, 19)
            with dsl.Condition(random_num_tail.output > 15):
                print_op('tails and %s > 15!' % random_num_tail.output)
            with dsl.Condition(random_num_tail.output <= 15):
                print_op('tails and %s <= 15!' % random_num_tail.output)

        with dsl.Condition(flip.output == 'tails'):
            fail_op(message="Failing the run to demonstrate that exit handler still gets executed.")


if __name__ == '__main__':
    # Compiling the pipeline
    kfp.compiler.Compiler().compile(flipcoin_exit_pipeline, __file__ + '.yaml')
```
### What happened:
it compiled success, 

### What did you expect to happen:
raise Error such as follow:
```
Traceback (most recent call last):
  File "control_structures.py", line 125, in <module>
    kfp.compiler.Compiler().compile(flipcoin_exit_pipeline, __file__ + '.yaml')
  File "/Users/anhaozheng/pipelines-master/sdk/python/kfp/compiler/compiler.py", line 984, in compile
    self._create_and_write_workflow(
  File "/Users/anhaozheng/pipelines-master/sdk/python/kfp/compiler/compiler.py", line 1037, in _create_and_write_workflow
    workflow = self._create_workflow(
  File "/Users/anhaozheng/pipelines-master/sdk/python/kfp/compiler/compiler.py", line 874, in _create_workflow
    self._validate_exit_handler(dsl_pipeline)
  File "/Users/anhaozheng/pipelines-master/sdk/python/kfp/compiler/compiler.py", line 779, in _validate_exit_handler
    return _validate_exit_handler_helper(pipeline.groups[0], [], False)
  File "/Users/anhaozheng/pipelines-master/sdk/python/kfp/compiler/compiler.py", line 777, in _validate_exit_handler_helper
    _validate_exit_handler_helper(g, exiting_op_names, handler_exists)
  File "/Users/anhaozheng/pipelines-master/sdk/python/kfp/compiler/compiler.py", line 770, in _validate_exit_handler_helper
    raise ValueError('Only one global exit_handler is allowed and all ops need to be included.')
ValueError: Only one global exit_handler is allowed and all ops need to be included.
```
### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

KFP version: 

KFP SDK version: 
1.4.0

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by chensun** [comment]
@HaozhengAN , I cannot reproduce this. 

Can you maybe try again in a clean environment?

Here's what I did for your reference:
1. Create a new virtual environment
`python3 -m venv ~/venv/kfp1.4.0`
`source ~/venv/kfp1.4.0/bin/activate`
2. Install kfp 1.4.0
`pip3 install kfp==1.4.0`
3. Compile the pipeline file shown below
`python3 test.py`

```test.py
from kfp import components
from kfp import dsl
import kfp

@components.create_component_from_func
def get_random_int_op(minimum: int, maximum: int) -> int:
    """Generate a random number between minimum and maximum (inclusive)."""
    import random
    result = random.randint(minimum, maximum)
    print(result)
    return result

@components.create_component_from_func
def flip_coin_op() -> str:
    """Flip a coin and output heads or tails randomly."""
    import random
    result = 'heads' if random.randint(0, 1) == 0 else 'tails'
    return result

@components.create_component_from_func
def print_op(message: str):
    """Print a message."""
    print(message)

@components.create_component_from_func
def fail_op(message):
    """Fails."""
    import sys
    print(message)
    sys.exit(1)


@dsl.pipeline(
    name='Conditional execution pipeline with exit handler',
    description='Shows how to use dsl.Condition() and dsl.ExitHandler().'
)
def flipcoin_exit_pipeline():
    exit_task = print_op('Exit handler has worked!')
    exit_task2 = print_op('Exit handler has worked!')
    with dsl.ExitHandler(exit_task):
        flip = flip_coin_op()
        with dsl.Condition(flip.output == 'heads'):
            random_num_head = get_random_int_op(0, 9)
            with dsl.Condition(random_num_head.output > 5):
                print_op('heads and %s > 5!')
            with dsl.Condition(random_num_head.output <= 5):
                print_op('heads and %s <= 5!' % random_num_head.output)

        with dsl.Condition(flip.output == 'tails'):
            random_num_tail = get_random_int_op(10, 19)
            with dsl.Condition(random_num_tail.output > 15):
                print_op('tails and %s > 15!' % random_num_tail.output)
            with dsl.Condition(random_num_tail.output <= 15):
                print_op('tails and %s <= 15!' % random_num_tail.output)

        with dsl.Condition(flip.output == 'tails'):
            fail_op(message="Failing the run to demonstrate that exit handler still gets executed.")


if __name__ == '__main__':
    # Compiling the pipeline
    kfp.compiler.Compiler().compile(flipcoin_exit_pipeline, __file__ + '.yaml')
```

**Comment by HaozhengAN** [comment]
I've just followed your steps. It can be reproduced stably when I execute Python 3 test.py  No exception is thrown, but in the test.py  Inside, exit_task2&nbsp; does not belong to Exithandler, so an error should be reported， but&nbsp; it's not. 






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chen Sun"<notifications@github.com&gt;; 
发送时间: 2021年3月5日(星期五) 晚上6:28
收件人: "kubeflow/pipelines"<pipelines@noreply.github.com&gt;; 
抄送: "小安"<317291885@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [kubeflow/pipelines] bug in compilier.Compiler._validate_exit_handler (#5198)





 
@HaozhengAN , I cannot reproduce this.
 
Can you maybe try again in a clean environment?
 
Here's what I did for your reference:
  
Create a new virtual environment
 python3 -m venv ~/venv/kfp1.4.0
 source ~/venv/kfp1.4.0/bin/activate
 
Install kfp 1.4.0
 pip3 install kfp==1.4.0
 
Compile the pipeline file shown below
 python3 test.py
  from kfp import components from kfp import dsl import kfp @components.create_component_from_func def get_random_int_op(minimum: int, maximum: int) -&gt; int:     """Generate a random number between minimum and maximum (inclusive)."""     import random     result = random.randint(minimum, maximum)     print(result)     return result @components.create_component_from_func def flip_coin_op() -&gt; str:     """Flip a coin and output heads or tails randomly."""     import random     result = 'heads' if random.randint(0, 1) == 0 else 'tails'     return result @components.create_component_from_func def print_op(message: str):     """Print a message."""     print(message) @components.create_component_from_func def fail_op(message):     """Fails."""     import sys     print(message)     sys.exit(1) @dsl.pipeline(     name='Conditional execution pipeline with exit handler',     description='Shows how to use dsl.Condition() and dsl.ExitHandler().' ) def flipcoin_exit_pipeline():     exit_task = print_op('Exit handler has worked!')     exit_task2 = print_op('Exit handler has worked!')     with dsl.ExitHandler(exit_task):         flip = flip_coin_op()         with dsl.Condition(flip.output == 'heads'):             random_num_head = get_random_int_op(0, 9)             with dsl.Condition(random_num_head.output &gt; 5):                 print_op('heads and %s &gt; 5!')             with dsl.Condition(random_num_head.output <= 5):                 print_op('heads and %s <= 5!' % random_num_head.output)         with dsl.Condition(flip.output == 'tails'):             random_num_tail = get_random_int_op(10, 19)             with dsl.Condition(random_num_tail.output &gt; 15):                 print_op('tails and %s &gt; 15!' % random_num_tail.output)             with dsl.Condition(random_num_tail.output <= 15):                 print_op('tails and %s <= 15!' % random_num_tail.output)         with dsl.Condition(flip.output == 'tails'):             fail_op(message="Failing the run to demonstrate that exit handler still gets executed.") if __name__ == '__main__':     # Compiling the pipeline     kfp.compiler.Compiler().compile(flipcoin_exit_pipeline, __file__ + '.yaml')

**Comment by chensun** [comment]
> I've just followed your steps. It can be reproduced stably when I execute Python 3 test.py  No exception is thrown, but in the test.py  Inside, exit_task2&nbsp; does not belong to Exithandler, so an error should be reported， but&nbsp; it's not.

I see. sorry I misread your initial report -- I thought you unintentionally misplaced/swapped "what happened" and "what expect to happen". 
I agree the error message you pointed to might be a bit misleading. But in fact what you see is the expected behavior.
We do allow extra ops outside exithandler scope just that you can have only one op used as exithandler task.

For example, you can see in our xgboost sample that `_diagnose_me_op` is also outside exithandler but not the exithandler task.

https://github.com/kubeflow/pipelines/blob/5ffa2be1b9243773d5459b22406a3f2cd5e7881c/samples/core/xgboost_training_cm/xgboost_training_cm.py#L233-L244

**Comment by HaozhengAN** [comment]
```python
@dsl.pipeline(
    name='Conditional execution pipeline with exit handler',
    description='Shows how to use dsl.Condition() and dsl.ExitHandler().'
)
def flipcoin_exit_pipeline():
    exit_task = print_op('Exit handler has worked!')
    exit_task2 = print_op('Exit handler has worked!')
    exit_task3 =  print_op('Exit handler has worked!')
    with dsl.ExitHandler(exit_task):
        flip = flip_coin_op()
        with dsl.Condition(flip.output == 'heads'):
            random_num_head = get_random_int_op(0, 9)
            with dsl.Condition(random_num_head.output > 5):
                print_op('heads and %s > 5!')
            with dsl.Condition(random_num_head.output <= 5):
                print_op('heads and %s <= 5!' % random_num_head.output)

        with dsl.Condition(flip.output == 'tails'):
            random_num_tail = get_random_int_op(10, 19)
            with dsl.Condition(random_num_tail.output > 15):
                print_op('tails and %s > 15!' % random_num_tail.output)
            with dsl.Condition(random_num_tail.output <= 15):
                print_op('tails and %s <= 15!' % random_num_tail.output)

        with dsl.Condition(flip.output == 'tails'):
            fail_op(message="Failing the run to demonstrate that exit handler still gets executed.")


if __name__ == '__main__':
    # Compiling the pipeline
    kfp.compiler.Compiler().compile(flipcoin_exit_pipeline, __file__ + '.yaml')

```
but  this will raise an error:

```
Traceback (most recent call last):
  File "control_structures.py", line 125, in <module>
    kfp.compiler.Compiler().compile(flipcoin_exit_pipeline, __file__ + '.yaml')
  File "/Users/anhaozheng/pipelines-master/sdk/python/kfp/compiler/compiler.py", line 984, in compile
    self._create_and_write_workflow(
  File "/Users/anhaozheng/pipelines-master/sdk/python/kfp/compiler/compiler.py", line 1037, in _create_and_write_workflow
    workflow = self._create_workflow(
  File "/Users/anhaozheng/pipelines-master/sdk/python/kfp/compiler/compiler.py", line 874, in _create_workflow
    self._validate_exit_handler(dsl_pipeline)
  File "/Users/anhaozheng/pipelines-master/sdk/python/kfp/compiler/compiler.py", line 779, in _validate_exit_handler
    return _validate_exit_handler_helper(pipeline.groups[0], [], False)
  File "/Users/anhaozheng/pipelines-master/sdk/python/kfp/compiler/compiler.py", line 777, in _validate_exit_handler_helper
    _validate_exit_handler_helper(g, exiting_op_names, handler_exists)
  File "/Users/anhaozheng/pipelines-master/sdk/python/kfp/compiler/compiler.py", line 770, in _validate_exit_handler_helper
    raise ValueError('Only one global exit_handler is allowed and all ops need to be included.')
ValueError: Only one global exit_handler is allowed and all ops need to be included.
```

and the msg of valueError is: 
> Only one global exit_handler is allowed and all ops need to be included.

**Comment by chensun** [comment]
Thanks! The last example shows inconsistence in the check is indeed a bug then. 

Not sure if we want to enforce the check or remove the check though.
