### ISSUE TITLE
User should be able to upload a new pipeline when creating a new run.

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#52]
http://localhost:9090/pipeline/#/runs/new?experimentId=8348da85-566b-4b11-a286-da8615ae9c6c

**Comment by vicaire** [comment]
Riley, is this still needed? Can we close?

**Comment by rileyjbauer** [comment]
I think this is still a useful feature. It makes sense that this should be possible if the user is focusing on a single experiment
