### ISSUE TITLE
KubeFlow Pipeline example notebook is half way updated for 0.1.4

### ISSUE THREAD

**Issue by post2web** [kubeflow/pipelines#520]
The notebook: [KubeFlow Pipeline Using TFX OSS Components.ipynb](https://github.com/kubeflow/pipelines/blob/master/samples/notebooks/KubeFlow%20Pipeline%20Using%20TFX%20OSS%20Components.ipynb) is updated to have `.apply(gcp.use_gcp_secret('user-gcp-sa'))` to every container but all other content is written for 0.1.3-rc.2 release. 

To me, this notebook is the most useful reference for the pipeline creation and execution process and it is currently broken.

Simply updating the `pip3 install kfp` to 0.1.4 do not fix the issues with that notebook.

**Comment by gaoning777** [comment]
What is the error? Does it happen during compile time or runtime?
Do you mind posting the exact errors? Thanks

**Comment by post2web** [comment]
The first error would come from:
```python
import kfp.gcp as gcp

ModuleNotFoundError: No module named 'kfp.gcp'
```
because `KFP_PACKAGE = 'https://storage.googleapis.com/ml-pipeline/release/0.1.3-rc.2/kfp.tar.gz'`

There will be more errors on every `.apply(gcp.use_gcp_secret('user-gcp-sa'))`

After changing `KFP_PACKAGE` to use 0.1.4, the pipeline compiles. The run starts when I deploy it to a cluster with `pipelines 0.1.4` but get authentification errors from within the containers. This is probably because I haven't set anything for the `gcp.use_gcp_secret`. A hint on how to set this up will be much appreciated.

The pipeline compiles and runs as expected when I remove all `.apply(gcp.use_gcp_secret('user-gcp-sa'))` references from the notebook and run it on 0.1.3-rc.2 piplenes cluster.

**Comment by hongye-sun** [comment]
Have you tried restarting the kernal?

**Comment by post2web** [comment]
Yes, the above are errors raised after restarting of the kernel. To test:
```
KFP_PACKAGE = 'https://storage.googleapis.com/ml-pipeline/release/0.1.3-rc.2/kfp.tar.gz'
!pip3 install $KFP_PACKAGE --upgrade
import kfp.gcp as gcp
```
will raise `ModuleNotFoundError: No module named 'kfp.gcp'`

**Comment by hongye-sun** [comment]
Sorry. I meant to be 0.1.4 kfp package. It should have the gcp package. I
will update the sample to use that package tomorrow.

**Comment by Nick-Harvey** [comment]
For anyone who stumbles upon this between now and the sample getting updated, simply replace `KFP_PACKAGE = 'https://storage.googleapis.com/ml-pipeline/release/0.1.3-rc.2/kfp.tar.gz'`  to `KFP_PACKAGE = 'https://storage.googleapis.com/ml-pipeline/release/0.1.4/kfp.tar.gz'
