### ISSUE TITLE
Upgrade argo image to 2.12+

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#5232]
Part of https://github.com/kubeflow/pipelines/issues/4553

/cc @NikeNano

**Comment by Bobgy** [comment]
I found that there's now a maintained tool to extract licenses from go libraries: https://github.com/google/go-licenses.

We can use it instead of our home-made tool.

**Comment by Bobgy** [comment]
I'll have to keep using https://github.com/kubeflow/testing/tree/master/py/kubeflow/testing/go-license-tools

**Comment by Bobgy** [comment]
Noticed a problem with kubeflow go-license-tools, although

> The command `go list -m all` lists the current module and all its dependencies:

I found that when using this command in argo repo, it lists a dependency: `github.com/fasthttp-contrib/websocket`.

However, this repo doesn't have a license file.

**Comment by Bobgy** [comment]
In summary, two dependencies are problematic:

* https://github.com/yudai/pp mentions it is licensed under MIT, but it doesn't keep a copy of MIT license in the repo.
* https://github.com/fasthttp-contrib/websocket doesn't have a license

**Comment by Bobgy** [comment]
There are several images I'll need to generate license info, so I built a better tool to automate this: https://github.com/Bobgy/go-mod-licenses.

**Comment by DavidSpek** [comment]
@Bobgy Just came across this, thought it would be relevant. https://blog.argoproj.io/argo-workflows-v3-0-4d0b69f15a6e

**Comment by Bobgy** [comment]
@DavidSpek thanks, rationale for choosing 2.12 was recorded in https://github.com/kubeflow/pipelines/issues/4553#issuecomment-768018127

**Comment by Bobgy** [comment]
Hmm, I just discovered https://github.com/github/licensed, it's written in Ruby, but it seems to support a wide range of languages and a robust workflow for working with licenses & cache.

**Comment by Bobgy** [comment]
I'm starting to notice some limitations of my approach:
* dev dependencies are pulled in as well -- this greatly increases number of licenses and their problems to deal with (but in fact they may not be in the binary).
* only supports repos using one single license (not yet seeing an exception)
