### ISSUE TITLE
Issue in decoding the output artifact fetched using self._run_api.read_artifact() in Kubeflow client

### ISSUE THREAD

**Issue by vishalsmb** [kubeflow/pipelines#5238]
I'm fetching an artifact output using kubeflow client. When I try to decompress the returned value, its returning junk characters along with the actual content. Attaching the sample code. Please let me know if any is wrong with the decoding that I'm doing here.

Code :
`from kfp import Client
import base64
import gzip

kubeflowService = Client(host='')
artifact = kubeflowService ._run_api.read_artifact(run_id=run_id, node_id=key, artifact_name=artifact_name)
value = artifact.data
print(gzip.decompress(base64.b64decode(value))`

**Comment by Bobgy** [comment]
@vishalsmb I think https://github.com/kubeflow/pipelines/issues/4327#issuecomment-687255001 is probably a good example
