### ISSUE TITLE
Backend pipeline upload API should include description

### ISSUE THREAD

**Issue by rileyjbauer** [kubeflow/pipelines#525]
I believe the change will start here at [upload_pipeline_parameters.go#L80](https://github.com/kubeflow/pipelines/blob/6d8db6c45dba6dd0944c1195bd127d5b9e93b27c/backend/api/go_http_client/pipeline_upload_client/pipeline_upload_service/upload_pipeline_parameters.go#L80) with the addition of a new field `Description`

We can then surface this functionality in the UI during the pipeline upload process.

**Comment by wstian** [comment]
It'd be very nice if this issue fixed soon. Is there any work on this now? thanks

**Comment by Bobgy** [comment]
@jingzhang36 I think this is already fixed, right?
