### ISSUE TITLE
Pip package kfp 1.4.1 and kfp-server-api 1.4.0 missing

### ISSUE THREAD

**Issue by DavidSpek** [kubeflow/pipelines#5254]
While updating some images I noticed a discrepancy with the releases of `kfp` and `kfp-server-api` on PyPi. `kfp` 1.4.1 is not available on PyPi but `kfp-server-api` 1.4.1 is available. In turn `kfp` 1.4.0 is available and `kfp-server-api` 1.4.1 is not available. Is this intentional (were kfp 1.4.1 and kfp-server-api 1.4.0 never released) or has something gone wrong with pushing the package?

/cc @Bobgy

**Comment by Bobgy** [comment]
/cc @chensun 

Recently, KFP sdk has been released in separate schedule than backend. There hasn't been enough communication about it.

Kfp-server-api 1.4.0 missing was a mistake, but I no longer see the need to release it when 1.4.1 is out.

**Comment by DavidSpek** [comment]
Thanks for confirming this. This is something I wanted to clear up for the new Notebook images. Are you expecting to release new versions before the release still?

**Comment by Bobgy** [comment]
@chensun do you have a suggestion for David?

**Comment by DavidSpek** [comment]
I'm now running into a dependency issue when installing the latest `kfserving` package (0.5.1) and `kfp` 1.4.0: `kfp 1.4.0 requires kubernetes<12.0.0,>=8.0.0, but you have kubernetes 12.0.1 which is incompatible`

It would be nice to have this solved so the latest packages can be installed in the notebook images.

**Comment by Bobgy** [comment]
The kubernetes version issue is fixed by https://github.com/kubeflow/pipelines/pull/5349.

Also I think the question is answered.

**Comment by DavidSpek** [comment]
@Bobgy Will this require a push to PyPi?

**Comment by Bobgy** [comment]
@DavidSpek yes, it will be in the next release

**Comment by DavidSpek** [comment]
Thanks for confirming!

**Comment by DavidSpek** [comment]
@Bobgy It seems like https://github.com/kubeflow/pipelines/pull/5349 is not included in kfp 1.4.1rc1. Is there a timeline for an updated release of the kfp package?

**Comment by Bobgy** [comment]
@neuromage to comment on this

**Comment by DavidSpek** [comment]
@neuromage I could you chime in on this? It would be nice to have an updated version of the kfp SDK on PyPI so the notebook images can be updated.

**Comment by neuromage** [comment]
We're planning an SDK release this week. Probably have an RC version out mid-week at least.

/cc @chensun
