### ISSUE TITLE
userid propagation issue between pipeline services

### ISSUE THREAD

**Issue by raffaelespazzoli** [kubeflow/pipelines#5269]
### What steps did you take:
I'm running a multiuser pipeline environment with kubeflow 1.2.0. From what I am seeing the `ml-pipeline-ui` service calls the `ml-pipeline` service when some actions on the ui are take like for example: start a pipeline run or create an experiment
 I'm getting this error on the ui:

```
{"error":"Failed to authorize the request.: Failed to authorize with API resource references: Bad request.: BadRequestError: Request header error: there is no user identity header.: Request header error: there is no user identity header.","message":"Failed to authorize the request.: Failed to authorize with API resource references: Bad request.: BadRequestError: Request header error: there is no user identity header.: Request header error: there is no user identity header.","code":10,"details":[{"@type":"type.googleapis.com/api.Error","error_message":"Request header error: there is no user identity header.","error_details":"Failed to authorize the request.: Failed to authorize with API resource references: Bad request.: BadRequestError: Request header error: there is no user identity header.: Request header error: there is no user identity header."}]}
```
and I can see this on the `ml-pipeline` pod log:
```
I0309 16:31:31.191130       6 error.go:227] Request header error: there is no user identity header.
github.com/kubeflow/pipelines/backend/src/apiserver/server.getUserIdentity
	/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/util.go:304
github.com/kubeflow/pipelines/backend/src/apiserver/server.isAuthorized
	/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/util.go:377
github.com/kubeflow/pipelines/backend/src/apiserver/server.(*ExperimentServer).ListExperiment
	/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/experiment_server.go:74
```
from what I understand the `ml-pipline-ui service` should forward the userid via the header configured in the `kubeflow-config` configmap, but that does not seem to be happening.
Is there a flag to enable this behavior? Am I missing something?

### What did you expect to happen:
If the userid header field was passed I'd expect not to get the error and to be able to launch a pipeline.

### Environment:
kubeflow 1.2.0 on OCP 4.6

How did you deploy Kubeflow Pipelines (KFP)?
I used kfctl, with the `kfctl_k8s_istio.v1.2.0.yaml` config with a few adjustment for OCP.

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

/area frontend
/area backend

**Comment by raffaelespazzoli** [comment]
I'm also getting this error in the main landing page:
```json
{error: "Invalid input error: ListRuns must filter by resource reference in multi-user mode.",…}
code: 3
details: [{@type: "type.googleapis.com/api.Error",…}]
0: {@type: "type.googleapis.com/api.Error",…}
@type: "type.googleapis.com/api.Error"
error_details: "Invalid input error: ListRuns must filter by resource reference in multi-user mode."
error_message: "ListRuns must filter by resource reference in multi-user mode."
error: "Invalid input error: ListRuns must filter by resource reference in multi-user mode."
message: "Invalid input error: ListRuns must filter by resource reference in multi-user mode."
```
![image](https://user-images.githubusercontent.com/6179036/110525029-1fd5c680-80e2-11eb-9e1d-6b307bd7c6c4.png)

I think it's related to the same underlying root cause.

**Comment by raffaelespazzoli** [comment]
we can actually see that the userid header is propagated to the `ml-pipeline` service:
![image](https://user-images.githubusercontent.com/6179036/110526069-5cee8880-80e3-11eb-99ca-bff2a8a3061f.png)

any advice on what might be failing?

**Comment by raffaelespazzoli** [comment]
looking more at the issue and the code it looks like the code where the issue arise is here:
https://github.com/kubeflow/pipelines/blob/5445ce82c7cd79bd517565750f72cf6a893c8cee/backend/src/apiserver/server/run_server.go#L179

where `ReferenceKey` must be null. Looking at the function that is suppsoed to populate the value:
https://github.com/kubeflow/pipelines/blob/0795597562e076437a21745e524b5c960b1edb68/backend/src/apiserver/server/list_request_util.go#L68

it seems like if the values is passed, it is never set in the filterContext...else clause missing

```golang
func ValidateFilter(referenceKey *api.ResourceKey) (*common.FilterContext, error) {
	filterContext := &common.FilterContext{}
	if referenceKey != nil {
		refType, err := common.ToModelResourceType(referenceKey.Type)
		if err != nil {
			return nil, util.Wrap(err, "Unrecognized resource reference type.")
		}
		filterContext.ReferenceKey = &common.ReferenceKey{Type: refType, ID: referenceKey.Id}
	}
	return filterContext, nil
}
```
is this fixed an any subsequent version?

**Comment by Bobgy** [comment]
@raffaelespazzoli I'm not familiar with k8s_istio config, but can you confirm whether the following are configured properly for your env?

Env var config on ml-pipeline-ui deployment:
https://github.com/kubeflow/pipelines/blob/4c51b576f577e337049599cb85b098006664265f/frontend/server/configs.ts#L106-L113

Env var config on ml-pipeline deployment:
https://github.com/kubeflow/pipelines/blob/d9c019641ef9ebd78db60cdb78ea29b0d9933008/backend/src/apiserver/common/config.go#L31-L32

**Comment by raffaelespazzoli** [comment]
@Bobgy both variable are set in both services via a shared configmap. I can prove that the header is propagated looking at the traces with Jaeger.

**Comment by Bobgy** [comment]
@raffaelespazzoli sorry I didn't see the notification, maybe you can try Kubeflow 1.3 soon.

Now they have verified KFP multi-user mode working properly for installation on K8s cluster only.
