### ISSUE TITLE
parallelfor_item_argument_resolving test failed to run

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/pipelines#5270]
### What steps did you take:
Run the parallelfor_item_argument_resolving compiler test example on Kubeflow Pipeline, the pipeline will fail because item arguments are wrapped into list of list of items instead of list of items
https://github.com/kubeflow/pipelines/blob/master/sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving.py

### What happened:
The `func_to_container_op` wraps the containerOp result into a list. Because the containerOp output is already a list of items, `func_to_container_op` warps the output into a list of list of items. e.g. 

```python
@func_to_container_op
def produce_list_of_dicts() -> list:
    return ([{"aaa": "aaa1", "bbb": "bbb1"}, {"aaa": "aaa2", "bbb": "bbb2"}],)
# Actual output in containerOp: [[{"aaa": "aaa1", "bbb": "bbb1"}, {"aaa": "aaa2", "bbb": "bbb2"}]] 
```

<img width="1076" alt="Screen Shot 2021-03-09 at 1 44 30 PM" src="https://user-images.githubusercontent.com/10889249/110542224-a3d97f80-80dd-11eb-8b0a-134d04ec8870.png">

### What did you expect to happen:
The compiler example could be a typo and only need to remove the `[ ]` from the return statement.

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

KFP version:  1.4.0

KFP SDK version:  1.4.0

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by Ark-kun** [comment]
Good catch.
Some time ago the return value of the component function was not passed completely correctly. So the components had to whap output in a tuple when outputting a single list. The problem was fixed in the SDK, but the test was not updated.
