### ISSUE TITLE
[Testing] kubeflow-pipeline-postsubmit-integration-test flaky 2021-3-10

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#5272]
kubeflow-pipeline-postsubmit-integration-test has been failing consecutively.

I did a quick check, the following samples are both flaky:
* aiplatform
* container_build

Creating this issue to track solving this

/assign @zijianjoy

**Comment by zijianjoy** [comment]
For aiplatform, here is a sample of test failure log:

```

sample-test-92wvs-4170907803: Using endpoint [https://ml.googleapis.com/]
sample-test-92wvs-4170907803: ERROR: (gcloud.ai-platform.predict) HTTP request failed. Response: {
sample-test-92wvs-4170907803:   "error": {
sample-test-92wvs-4170907803:     "code": 404,
sample-test-92wvs-4170907803:     "message": "Field: name Error: Online prediction is unavailable for this version. Please verify that CreateVersion has completed successfully.",
sample-test-92wvs-4170907803:     "status": "NOT_FOUND",
sample-test-92wvs-4170907803:     "details": [
sample-test-92wvs-4170907803:       {
sample-test-92wvs-4170907803:         "@type": "type.googleapis.com/google.rpc.BadRequest",
sample-test-92wvs-4170907803:         "fieldViolations": [
sample-test-92wvs-4170907803:           {
sample-test-92wvs-4170907803:             "field": "name",
sample-test-92wvs-4170907803:             "description": "Online prediction is unavailable for this version. Please verify that CreateVersion has completed successfully."
sample-test-92wvs-4170907803:           }
sample-test-92wvs-4170907803:         ]
sample-test-92wvs-4170907803:       }
sample-test-92wvs-4170907803:     ]
sample-test-92wvs-4170907803:   }
sample-test-92wvs-4170907803: }
sample-test-92wvs-4170907803: 
```

**Comment by zijianjoy** [comment]
Possible related: https://github.com/kubeflow/pipelines/blob/master/samples/core/ai_platform/ai_platform.ipynb

**Comment by Bobgy** [comment]
it was because of argo pns executor, after reverting back to docker executor the first postsubmit succeeded

**Comment by Bobgy** [comment]
ohhh, you are right. There's another flakiness in aiplatform sample. keep this open

**Comment by zijianjoy** [comment]
Regarding `container_build`:

Error message is as followed:

```

sample-test-6gw5p-2308294888: KFP API host is 302db4d8b0ea18f8-dot-us-east1.pipelines.googleusercontent.com
sample-test-6gw5p-2308294888: Run the sample tests...
sample-test-6gw5p-2308294888: Traceback (most recent call last):
sample-test-6gw5p-2308294888:   File "/python/src/github.com/kubeflow/pipelines/test/sample-test/sample_test_launcher.py", line 260, in <module>
sample-test-6gw5p-2308294888:     main()
sample-test-6gw5p-2308294888:   File "/python/src/github.com/kubeflow/pipelines/test/sample-test/sample_test_launcher.py", line 256, in main
sample-test-6gw5p-2308294888:     'component_test': ComponentTest
sample-test-6gw5p-2308294888:   File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 141, in Fire
sample-test-6gw5p-2308294888:     component_trace = _Fire(component, args, parsed_flag_args, context, name)
sample-test-6gw5p-2308294888:   File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 471, in _Fire
sample-test-6gw5p-2308294888:     target=component.__name__)
sample-test-6gw5p-2308294888:   File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 681, in _CallAndUpdateTrace
sample-test-6gw5p-2308294888:     component = fn(*varargs, **kwargs)
sample-test-6gw5p-2308294888:   File "/python/src/github.com/kubeflow/pipelines/test/sample-test/sample_test_launcher.py", line 183, in run_test
sample-test-6gw5p-2308294888:     nbchecker.check()
sample-test-6gw5p-2308294888:   File "/python/src/github.com/kubeflow/pipelines/test/sample-test/check_notebook_results.py", line 74, in check
sample-test-6gw5p-2308294888:     experiment_id = client.get_experiment(experiment_name=experiment).id
sample-test-6gw5p-2308294888:   File "/usr/local/lib/python3.7/dist-packages/kfp-1.4.1rc1-py3.7.egg/kfp/_client.py", line 462, in get_experiment
sample-test-6gw5p-2308294888:     raise ValueError('No experiment is found with name {}.'.format(experiment_name))
sample-test-6gw5p-2308294888: ValueError: No experiment is found with name container_build-test.
```

Suspecting it has something to do with backend not able to return the experiment in request, or this experiment doesn't exist.

**Comment by zijianjoy** [comment]
Example logs: https://oss-prow.knative.dev/view/gs/oss-prow/logs/kubeflow-pipeline-postsubmit-integration-test/1374652399771193344

**Comment by Ark-kun** [comment]
[Prow](https://oss-prow.knative.dev/view/gs/oss-prow/logs/kubeflow-pipeline-postsubmit-integration-test/1374652399771193344)

[Pod](
https://00f74ba44b420418175dd31cb3c371cfc9ef2b71ab-apidata.googleusercontent.com/download/storage/v1/b/oss-prow/o/logs%2Fkubeflow-pipeline-postsubmit-integration-test%2F1374652399771193344%2Fartifacts%2Fpods_info%2Fkaniko-7v2gs.txt?jk=AFshE3WgSYrbaJ_tnqAP2uHklKC4QfRLQr2DCqSwJD9nn-3B25X_SpBMabvOAGh5QTEVwpFX7qqxyf1xZdrtLcciykBwxsSebvvHSvYAk8BtaSfFfN6ShsF6nb5CjV6DpyOUDen76mPvGGHR4ov0a1S-OHrB3UySfVJ9ur9XqFJJ6iowcb1yjFtol14JsxgtUnaHcxWIiZ7IKhVQGcx30Lp-YU--1H1efLZXu1eANHH8uwKp1nSQ6XYG8JnnzD-zlbuIuA0r93YmYvZpJXL6xcVeagEPniE4FHGjIC38jOz2zreM2ZZjKyRoGNnwAvWgk93EdrmFXyfw1Qd50ZC9iWjr6_AWl8Oake2pY2m4CYJ_3cVDAwKOeO6f8HC4fFA7Qff_WqBqqNz-F9EipRvcBLZ2yqve-zvb2u5WBNDmzKo-CdPdGFMDBtXuo36CQJnTP8BqqbLCciw6qwZqWRdMokhD705dvTUuTPJ3TM46WB5Cjwt5_5784BVBUyN96nRPgMwydMgOdOmoRwTGyScbjHDi9eFMNPPOXbwTUyAuOgKHuc8pkac9n-D3ya-J6sSjWrWZXoUeBkygOytxn9QVh_VxNSjx-cu0cnyrzlTeroWwr_nPqhjVNk5zE3FTavD1cDxknd_fB3qTgKQP9nRVEH6MrCnf0M13Uqtl46nma3Ql45LfJuZZISFA00N8u904Jr4MnU6ST2QXT8Q2c0dpGrECI5eN7G-M6I0bvT6gH5HZ6KyQkl_1Ys8wBW36e-BIyTHct7o-3X3CqAIy3uWFVi_fdUi2ip8R1Bg-xoPeR8q-QAJR1LN-RzcnJk55jMfyFQLup7ejzncOz0pqJgJ9_RC93UVYx3YrdlqBkTzImjY0axORxMcL7C7uLWdLixS9UfFXaZ94S1SglUdf8PGflzDcWgO22MTpqXcEosmeBCW-rI9PfviEkdvRWKI6pZpbjXHIDTzknCo6Uh1b8NiSnFC5pc7uua3I0zjqCAJq-lf0QN6xrtRJRXvZ0ESyo2dMN5XL0J4SQy1phSKAL4gTqJV8bB4tuMbkHvoSNCivFb33hrd4Mcxw0QgV3_YsSLVN5Bj2X3p5S0U&isca=1)

[Kaniko logs](
https://pantheon.corp.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22ml-pipeline-test%22%0Aresource.labels.location%3D%22us-east1-b%22%0Aresource.labels.cluster_name%3D%22sample-d9c0196-6848%22%0Aresource.labels.namespace_name%3D%22kubeflow%22%0Aresource.labels.pod_name%3D%22kaniko-7v2gs%22;timeRange=P7D;cursorTimestamp=2021-03-24T10:28:06.449898604Z?project=ml-pipeline-test)

Maybe it has failed to download the image.
```
[36mINFO[0m[0001] Resolved base name gcr.io/deeplearning-platform-release/tf-cpu.1-14 to gcr.io/deeplearning-platform-release/tf-cpu.1-14
[36mINFO[0m[0001] Resolved base name gcr.io/deeplearning-platform-release/tf-cpu.1-14 to gcr.io/deeplearning-platform-release/tf-cpu.1-14
[36mINFO[0m[0001] Downloading base image gcr.io/deeplearning-platform-release/tf-cpu.1-14
[36mINFO[0m[0001] Error while retrieving image from cache: getting file info: stat /cache/sha256:bd464d284317fdd4fedea19b72b6424710ed2a7695ce391f718d74278a3ab97a: no such file or directory
[36mINFO[0m[0001] Downloading base image gcr.io/deeplearning-platform-release/tf-cpu.1-14
[36mINFO[0m[0002] Built cross stage deps: map[]
[36mINFO[0m[0002] Downloading base image gcr.io/deeplearning-platform-release/tf-cpu.1-14
[36mINFO[0m[0002] Error while retrieving image from cache: getting file info: stat /cache/sha256:bd464d284317fdd4fedea19b72b6424710ed2a7695ce391f718d74278a3ab97a: no such file or directory
[36mINFO[0m[0002] Downloading base image gcr.io/deeplearning-platform-release/tf-cpu.1-14
[36mINFO[0m[0002] Using files from context: [/kaniko/buildcontext/requirements.txt]
[36mINFO[0m[0002] Checking for cached layer gcr.io/ml-pipeline-test/7841878234294039750/kfp_container/cache:ba7a7556fbb481e0dac58fa95852cd1657d89697c8e490d6d4a4299955fb85a6...
[36mINFO[0m[0002] No cached layer found for cmd RUN python3 -m pip install -r requirements.txt
[36mINFO[0m[0002] Unpacking rootfs as cmd RUN python3 -m pip install -r requirements.txt requires it.
[36mINFO[0m[0275] Taking snapshot of full filesystem...
```

Perhaps we should use a smaller image for that sample/test.

**Comment by Bobgy** [comment]
Obsolete
