### ISSUE TITLE
[Manifests] how to organize argo artifact repository config without duplication?

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#5276]
## The problem

Realized the problem from https://github.com/kubeflow/pipelines/pull/5273.

Argo artifact repository config is highly coupled to minio, so it's best put inside minio's manifests and get it reused in manifests envs that use minio.

However, if we save the config as a patch, it's only allowed to use patches in the kustomization.yaml 's same or sub-folders. So if we do not include the minio-argo-artifact-repository patch by default, all downstream manifests that use argo with minio will have to duplicate the config patch.

For Kubeflow, we have set up best practices for always using `--load_restrictor none`, so that there's no such restriction.
However, the argument is not available in `kubectl kustomize`.

### Solution 1 - Wait for kubectl to upgrade kustomize (from upstream issue, looks like there will soon be a release)

Pros:
* consistent with Kubeflow

Cons:
* requiring an extra argument is still a common confusion, and sort of hacky
* we need to wait for next kubectl release and people using the latest kubectl version (can be a quarter)

### Solution 2 - Use configmap called `artifact-repositories` to choose default artifact repository.

Ref: https://argoproj.github.io/argo-workflows/configure-artifact-repository/

Pros:
* we no longer need to reuse the config as a patch, it can be a resource, so not limited by load_restrictor anymore

Cons:
* it only takes effect in the namespace that has it, so multi-user mode KFP doesn't work very well with this approach
* the feature was added in argo 3.0, so we need to upgrade first

### Solution 3 - Use kustomize components

https://kubectl.docs.kubernetes.io/guides/config_management/components/
this seems like exactly the canonical solution

Pros:
* this kustomize feature is exactly built to solve this problem

Cons:
* we need to upgrade to kustomize 3.7+, so we can no longer ask users to `kubectl apply -k manifests`
* kustomize components seem to be an alpha API: `kustomize.config.k8s.io/v1alpha1`

### Analysis of the solutions

Solution 1 & 2 has fatal problems.
It seems we should take Solution 3, which should work long term (but it's also an alpha API).

A prerequisite is either of the following:
* Wait for kubectl release that includes latest kustomize
* Update all documentation that were using `kubectl apply -k` to `kubectl apply -f <prehydrated-manifest>` or `kustomize build xxx | kubectl apply -f -` (when the manifest needs some var config, so it requires local hydration) and introduce kustomize installation process.

Maybe the only acceptable short term solution is to default workflow-controller-configmap's artifact repository config to use minio, so that most of the manifests do not need to change it.

**Comment by NikeNano** [comment]
For long term 3 sound like the way to go.
