### ISSUE TITLE
Orchestration - Flakiness in small samples when using PNS executor

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#5285]
In https://github.com/kubeflow/pipelines/pull/5273, I switched to PNS executor by default. After that, it seems lightweight component sample fail more frequently than before.

(It failed 3 times consecutively in an example I found, but it seems to me that the last two failures should be fixed by https://github.com/kubeflow/pipelines/pull/5284, we can observe the actual flakiness rate after the change)

Symptom, pipeline components that run too fast fail with:
>  failed to save outputs: could not chroot into main for artifact collection: container may have exited too quickly

https://oss-prow.knative.dev/view/gs/oss-prow/pr-logs/pull/kubeflow_pipelines/4147/kubeflow-pipeline-sample-test/1369916972707352576#1:build-log.txt%3A5681

Root cause seems to be: https://github.com/argoproj/argo-workflows/issues/1256#issuecomment-481471276

And workarounds can be:

* (hacky) let the main container sleep for a while
* (stable fix) mount the artifacts on an emptyDir

**Comment by Bobgy** [comment]
/assign @chensun @neuromage 
/cc @Ark-kun @capri-xiyue 

I think we need to discuss this problem, from KFP side, we could automatically mount emptyDir for users.

**Comment by Bobgy** [comment]
/cc @jessesuen @alexec
Do you have any suggestions? Is my above understanding of the workarounds accurate?

**Comment by Bobgy** [comment]
Hmm, strange, I'm not seeing flakiness anymore

I'll keep observing this problem

**Comment by Ark-kun** [comment]
I see postsubmit flakyness. https://oss-prow.knative.dev/view/gs/oss-prow/logs/kubeflow-pipeline-postsubmit-integration-test/1371547567694811136

**Comment by Bobgy** [comment]
I'll revert back to docker as default for current release, but we should evaluate possibility of mounting emptyDir volumes for artifact paths for users.

**Comment by Bobgy** [comment]
We now recommend emissary executor instead: https://github.com/kubeflow/pipelines/issues/1654#issuecomment-903224028
