### ISSUE TITLE
[Bug] KeyValueStore fails to check the cached data with new data

### ISSUE THREAD

**Issue by lynnmatrix** [kubeflow/pipelines#5288]
Typo bug.

```
def store_value_bytes(self, key: str, data: bytes) -> str:
    ... 
     if cache_value_file_path.exists():
        old_data = cache_value_file_path.write_bytes()
    ...    
```
should be:
```
def store_value_bytes(self, key: str, data: bytes) -> str:
    ... 
     if cache_value_file_path.exists():
        old_data = cache_value_file_path.read_bytes()
    ...    
```

**Comment by lynnmatrix** [comment]
cc @Ark-kun

**Comment by zijianjoy** [comment]
Thank you @lynnmatrix ! This bug makes sense and would you like to contribute a PR for the fix?

**Comment by lynnmatrix** [comment]
@zijianjoy,  My colleague @michaelliqx has fixed it in PR #5290.

**Comment by Ark-kun** [comment]
Thank you for the discovery and the fix.
I wonder how this worked before....?

**Comment by lynnmatrix** [comment]
This bug raises exception: `TypeError: write_bytes() missing 1 required positional argument: 'data'`.

You are right, this code was unused.
KeyValueStore is only used in ComponentStore._refresh_component_cache,  and it will check the existence of the key before writing, so there is no chance to overwrite.
