### ISSUE TITLE
ML-Engine deploy model component missing region parameter

### ISSUE THREAD

**Issue by Amrit-Mann** [kubeflow/pipelines#5304]
Hi, 
I am using the ml-engine component to deploy a ML model to AI Platform Prediction (from a Kubeflow deployment in AI Platform Pipelines), however there is no available parameter to deploy the model into a particular region. This results in the model deployment defaulting to the us-central1 region. Is there any way to deploy a model using this component to a specific region?
Any help on this will be much appreciated!. 
Thanks. 

Link to component: https://github.com/kubeflow/pipelines/tree/master/components/gcp/ml_engine/deploy

**What steps did you take:**
1 - Trained a model using AI Platform Pipelines 
2 - Saved this model to Google Cloud Storage as a .pkl file 
3 - Tried to use the deploy component to deploy this model to AI Platform Prediction, however 
**What happened:**
There is no region parameter for this deploy component hence the deployment happens in the default region (us-central1)
**What did you expect to happen:**
Be able to specify the region parameter in the input for this component. (Since we can do this when deploying the model from either gcloud commands/GCP Console
**Anything else you would like to add:**
/kind feature
/kind component

**Comment by NikeNano** [comment]
@zijianjoy should we aim for making [all arguments](https://cloud.google.com/sdk/gcloud/reference/ml-engine/versions/create) available for the user or keep a selected few(I see that we currently only support some options)?

**Comment by NikeNano** [comment]
After looking in to this I believe this is actually already possible @Amrit-Mann,  if you look at the options:  for `model` and `version` the take a json following:
- model, https://cloud.google.com/ml-engine/reference/rest/v1/projects.models
- version , https://cloud.google.com/ml-engine/reference/rest/v1/projects.models.versions 

where in you have the options to specify the region that you like to deploy to. 

> @zijianjoy should we aim for making [all arguments](https://cloud.google.com/sdk/gcloud/reference/ml-engine/versions/create) available for the user or keep a selected few(I see that we currently only support some options)?

All available options should already be possible to set. Let me know if you still has some issues @Amrit-Mann

**Comment by zijianjoy** [comment]
Thanks @NikeNano for the research! Since you can use ML-engine REST API, looks like you should be able to call this endpoint to specify regions.
