### ISSUE TITLE
E2E-mnist sample not up-to-date with Katib launcher

### ISSUE THREAD

**Issue by chinhuang007** [kubeflow/pipelines#5306]
### What steps did you take:
Run the e2e mnist notebook

### What happened:
Got TypeError: Katib - Launch Experiment() got an unexpected keyword argument 'parallel_trial_count'
Trying to execute 
```
katib_experiment_launcher_op = components.load_component_from_url('https://raw.githubusercontent.com/kubeflow/pipelines/master/components/kubeflow/katib-launcher/component.yaml')

op1 = katib_experiment_launcher_op(
            experiment_name=name,
            experiment_namespace=namespace,
            parallel_trial_count=3,
            max_trial_count=12,
            objective=str(objectiveConfig),
            algorithm=str(algorithmConfig),
            trial_template=str(trialTemplate),
            parameters=str(parameters),
            metrics_collector=str(metricsCollectorSpec),
            # experiment_timeout_minutes=experimentTimeoutMinutes,
            delete_finished_experiment=False)
```

### What did you expect to happen:
Not throwing an error

### Environment:
kubeflow 1.2

How did you deploy Kubeflow Pipelines (KFP)?
part of kubeflow 1.2 on IBM cloud

KFP SDK version:
kfp                      1.0.4
kfp-pipeline-spec        0.1.6
kfp-server-api           1.4.1
kfp-tekton               0.4.0

### Anything else you would like to add:
Seems affected by this PR https://github.com/kubeflow/pipelines/pull/4798

/kind bug

**Comment by Tomcli** [comment]
This example is no longer maintained in this repo. I tried to fix it for kubeflow 1.0 at https://github.com/kubeflow/pipelines/pull/4126 a while ago, but seems like the original author is no longer active

**Comment by zijianjoy** [comment]
cc @andreyvelich : What is the current status of this component? Should we perform a fix or remove this example?

**Comment by andreyvelich** [comment]
Thank you for mentioning me @zijianjoy.
Yes, I have plans to refactor e2e mnist example with the new launchers for Katib, KFServing and TF-Operator.
I want to make it after the Kubeflow 1.3 release.

/assign @andreyvelich
