### ISSUE TITLE
pipeline cannot read data from pvc

### ISSUE THREAD

**Issue by summerisc** [kubeflow/pipelines#5307]
More like a question kind
Currently, I have a pipeline contains a op like:
```
def preprocess_op(input_path, output_path):
    op = dsl.ContainerOp(
        name='process data',
        image='image:latest',
        command=[
            'sh',
            '-c',
        ],
        arguments=[
            f'cd /home && python test.py'
            f'--input-path {input_path}'
            f'--output-path {output_path}'
        ],
        file_outputs={}
    )

    op.apply(onprem.mount_pvc(pvc_name="flow-test", volume_name="pipeline", volume_mount_path="/mnt/data"))

    return op
```
I have a pvc called flow-test already bound
![Screen Shot 2021-03-15 at 8 43 41 PM](https://user-images.githubusercontent.com/21230663/111239233-22975680-85cf-11eb-96c7-bbeaf743b7cf.png)

When I run:
`client.create_run_from_pipeline_func(test_pipeline, arguments={'input_path': '/mnt/data', 'output_path': '/'}, namespace='namespaceName')`
it shows  `No such file or directory` so it seems /mnt/data cannot be found by the ContainerOp. So just wondering is it the correct way to get data from pvc inside the pipeline? If not, could anyone share what would be the correct way? I am using kubeflow for on-prem servers with k8s deployed on them.

**Comment by Ark-kun** [comment]
I'm not sure this is related to Kubeflow Pipelines. Have you checked how the created pod looks like? You can also replace the command with `sleep 9999` and then use `kubectl exec` to probe and debug the pod.

We advice our users to avoid using volumes directly (and creating ContainerOp directly as well).

```python
preprocess_op = kfp.components.load_component_from_text('''
name: process_data
inputs:
- {name: input1}
outputs:
- {name: output1}
implementation:
  container:
    image: image:latest
    command:
    - sh
    - -exc
    - cd /home && python test.py
    - --input-path
    - - {inputPath: input1}
    - --output-path
    - - {outputPath: output1}
''')
```

Is there a reason this won't work for you?

If the data is too large for the standard artifact passing, then there is a compilation option that seamlessly replaces the intermediate artifact storage with a volume without changing the pipeline code.
