### ISSUE TITLE
[frontend] Make clickable items styling distinguish from non-clickable items

### ISSUE THREAD

**Issue by zijianjoy** [kubeflow/pipelines#5315]
### Issue description
Discussion: https://github.com/kubeflow/pipelines/pull/5311#pullrequestreview-613890507

We received report from users that the clickable items on Artifact list page are hard to discover, because they are grey color. You can only discover that they are clickable when you hover over to that item, which will turn the buttons into blue and underlined. But they are actually darker grey while non-clickable items are lighter grey. 

Our mitigation is to add underline strictly to clickable items on this page, but it breaks the existing styling consistency with other pages. 

### What decision we want to make

We need to determine a clickable styling and apply to all pages: This style needs to be `accessible`, `discoverable` and `visual friendly`.

/kind bug
/area frontend

@Bobgy

**Comment by Bobgy** [comment]
Moving this to v2 compatible project, because this especially affects MLMD artifacts etc, they are important in v2 compatible mode
