### ISSUE TITLE
Taxi sample tries to use hostpath which doesn't work on some deployments

### ISSUE THREAD

**Issue by jlewi** [kubeflow/pipelines#532]
At the Kubeflow BOF someone from Acumos mentioned that the Taxi sample example didn't work because it was using a hostpath and they couldn't use hostpaths on their deployment.

Is hostpath required for this sample.

**Comment by neuromage** [comment]
Marking as obsolete, as I'm guessing this was a problem with the old taxi sample (which no longer is being maintained).
