### ISSUE TITLE
New API to get Pipeline ID from it's name

### ISSUE THREAD

**Issue by AntPeixe** [kubeflow/pipelines#5328]
/kind feature

**Why you need this feature:**
Right now it isn't possible to (easily) get the pipeline ID by it's name. When creating a new pipeline it may happen that a name already exists and the POST request returns an error. I'd like to be able to then get ID of such pipeline using it's name.
I think currently there is a workaround by getting all pipelines and the filtering from the list of results but this isn't as handy.

**Describe the solution you'd like:**
A new API endpoint to find a single pipeline ID by providing it's name.

**Comment by zijianjoy** [comment]
Thank you @AntPeixe for this suggestion! Currently we are able to filter by pipeline name, but we might need to take an action to give some examples about how to use it, and improve reference documentation.
