### ISSUE TITLE
Database Connection Errors

### ISSUE THREAD

**Issue by maganaluis** [kubeflow/pipelines#5329]
### What steps did you take:

We recently switched from using the MySQL database that Kubeflow Pipelines comes with, to a managed database on Azure. We started observing errors such as the one below, the errors are not consistent but they do happen often enough to impact our workloads. 

I have not been able to replicate the issue outside of Kubeflow, more specifically this ```unexpected EOF``` error. As it is suggested by methane https://github.com/go-sql-driver/mysql/issues/674#issuecomment-345661869 the general advice is to set ```DB.SetConnMaxLifetime(time.Second)``` to something small like 1-3 minutes, but this is not a setting that's enabled by env variables by Kubeflow Pipelines. I believe it should be because I'm sure others will run into the same issue as Kubeflow gains more Enterprise Adoption. 

We are going to test if this change reduces or hopefully eliminates these errors, but at least from the research I've done it looks like the right approach. 

```golang
func (c *ClientManager) init() {
	glog.Info("Initializing client manager")
	db := initDBClient(common.GetDurationConfig(initConnectionTimeout))
	db.SetConnMaxLifetime(time.Second * 120)
```

```
[mysql] 2021/03/16 07:27:11 packets.go:36: unexpected EOF
[mysql] 2021/03/16 07:27:11 connection.go:141: write tcp 10.244.24.107:50550->40.71.8.203:3306: write: broken pipe
E0316 07:27:11.976783       6 experiment_store.go:78] Failed to start transaction to list jobs
I0316 07:27:11.976819       6 error.go:243] invalid connection
InternalServerError: Failed to list experiments: invalid connection
github.com/kubeflow/pipelines/backend/src/common/util.NewInternalServerError
	/go/src/github.com/kubeflow/pipelines/backend/src/common/util/error.go:142
github.com/kubeflow/pipelines/backend/src/apiserver/storage.(*ExperimentStore).ListExperiments.func1
	/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/storage/experiment_store.go:49
github.com/kubeflow/pipelines/backend/src/apiserver/storage.(*ExperimentStore).ListExperiments
	/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/storage/experiment_store.go:79
github.com/kubeflow/pipelines/backend/src/apiserver/resource.(*ResourceManager).ListExperiments
	/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/resource/resource_manager.go:145
github.com/kubeflow/pipelines/backend/src/apiserver/server.(*ExperimentServer).ListExperiment
	/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/experiment_server.go:162
github.com/kubeflow/pipelines/backend/api/go_client._ExperimentService_ListExperiment_Handler.func1
	/go/src/github.com/kubeflow/pipelines/backend/api/go_client/experiment.pb.go:619
main.apiServerInterceptor
	/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/interceptor.go:30
github.com/kubeflow/pipelines/backend/api/go_client._ExperimentService_ListExperiment_Handler
	/go/src/github.com/kubeflow/pipelines/backend/api/go_client/experiment.pb.go:621
google.golang.org/grpc.(*Server).processUnaryRPC
	/go/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:1082
google.golang.org/grpc.(*Server).handleStream
	/go/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:1405
google.golang.org/grpc.(*Server).serveStreams.func1.1
	/go/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:746
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
List experiments failed.
```

### What happened:

After switching Kubeflow to a managed database, we have been experiencing sporadic connection errors in the Kubeflow API service. 

### What did you expect to happen:

I would expect not to have any database connection issues. 

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

- Kustomize

KFP version: 
~ 1.3

KFP SDK version: 
~ 1.3

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by zijianjoy** [comment]
Thank you for the suggestion @maganaluis ! It makes sense to change the lifetime for DB connection, and make it configurable. Welcome to contribute this feature!

**Comment by maganaluis** [comment]
@zijianjoy I created the PR. After changing this configuration we did not experience any of these errors anymore, so seems to be the correct approach here.

**Comment by thesuperzapper** [comment]
For anyone coming across this issue, any time you see an error like `[mysql] XXXX/XX/XX XX:XX:XX packets.go:36: unexpected EOF` in the `cache-server` pods, you are almost certainly dealing with a network-level issue between your pods and the MySQL database.

The most likely case is that there is some __asymmetric routing__ going on. That is, your Pods might be able to create a connection to MySQL, but MySQL might not have a route back to your Pod. Note, [MySQL connections are complex](https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_connection_phase.html) and will sometimes initiate new TCP connections back to the client, which will fail in the previous case.

I have a more detailed write up on this issue: https://github.com/kubeflow/pipelines/issues/3763#issuecomment-1547009188
