### ISSUE TITLE
kubeflow pipelines recurring run fails intermittently due to minio service

### ISSUE THREAD

**Issue by rexshang** [kubeflow/pipelines#5335]
### What steps did you take:
I'm running kubeflow 1.0.4 in GCP.  There is a recurring job that runs every 15 min.  It would fail about 1 time a day and generate the following error.  Does anyone have any pointers to help me troubleshoot?

### What happened:
"time="2021-03-18T04:55:22Z" level=warning msg="Failed to put file: Get http://minio-service.default:9000/kubeflow-artifact/?location=: dial tcp x.x.x.x:9000: connect: connection refused"
"time="2021-03-18T04:55:22Z" level=error msg="executor error: timed out waiting for the condition"

### Environment:
Google Cloud Platform
Kubeflow 1.0.4

How did you deploy Kubeflow Pipelines (KFP)?
using GCP AI Platform Pipelines "NEW INSTANCE" process

KFP version: 1.0.4

KFP SDK version: N/A

### Anything else you would like to add:

/kind bug
/area backend

**Comment by Bobgy** [comment]
HI @rexshang,

I can think of three ways to improve:
* set up a retry strategy, so that the pipeline can auto retry a few times when the instability happens (you should always expect other services may fail)
* use managed storage, gcs is probably stabler than minio
* upgrade minio server, the default one is very old

**Comment by Itega** [comment]
Hi @Bobgy,

I have the exact same problem and it's happening really often. I already have a retry strategy but it's not retrying when this fail.
I'm on KFP 1.7.1 deployed on GKE via the marketplace, using managed storage and managed sql.

Can I upgrade minio without breaking KFP ? Is there anything else I could do ?
