### ISSUE TITLE
Deployment problem with private cluster

### ISSUE THREAD

**Issue by gaoning777** [kubeflow/pipelines#534]
I created a private cluster and try to deploy the pipeline from one of the virtual machine in the same project. Here is the error:

Configure ksonnet ...
Configure ksonnet completed successfully
Initialize a ksonnet APP ...
level=info msg="Using context \"default\" from kubeconfig file \"/root/.kube/config\""
level=error msg="unable to find SHA1 for repo: Get https://api.github.com/repos/ksonnet/parts/commits/master: dial tcp 
192.30.253.117:443: i/o timeout"
Initialized ksonnet APP completed successfully
ln: failed to create symbolic link 'ml-pipeline-app/vendor/pipeline': No such file or directory
/pipeline/deploy.sh: line 142: ml-pipeline-app/tmp.yaml: No such file or directory
mv: cannot stat 'ml-pipeline-app/tmp.yaml': No such file or directory
namespace kubeflow exist
/pipeline/deploy.sh: line 155: cd: ml-pipeline-app: No such file or directory
/pipeline/deploy.sh: line 156: cd: ml-pipeline-app: No such file or directory
/pipeline/deploy.sh: line 157: cd: ml-pipeline-app: No such file or directory
/pipeline/deploy.sh: line 158: cd: ml-pipeline-app: No such file or directory
/pipeline/deploy.sh: line 159: cd: ml-pipeline-app: No such file or directory
/pipeline/deploy.sh: line 160: cd: ml-pipeline-app: No such file or directory
/pipeline/deploy.sh: line 161: cd: ml-pipeline-app: No such file or directory
/pipeline/deploy.sh: line 162: cd: ml-pipeline-app: No such file or directory
/pipeline/deploy.sh: line 163: cd: ml-pipeline-app: No such file or directory
Operation "operations/acf.9558106a-a70c-47da-80b8-8be4a32e0692" finished successfully.
ERROR: (gcloud.iam.service-accounts.keys.create) RESOURCE_EXHAUSTED: Maximum number of keys on account reached.
- '@type': type.googleapis.com/google.rpc.RetryInfo
  retryDelay: 86401s

**Comment by jlewi** [comment]
Were you following https://www.kubeflow.org/docs/guides/gke/private-clusters/?

**Comment by gaoning777** [comment]
I got this error when I ran the bootstrap, which I knew was deprecated. 
Since yang has been working on the private cluster support, I'll close the issue for using the bootstrap in favor of the kubeflow deployment integration.

**Comment by vicaire** [comment]
@IronPan, is this resolved now? Can we close?
