### ISSUE TITLE
[frontend] Artifact preview can cause ml-pipeline-ui to crash

### ISSUE THREAD

**Issue by vstrimaitis** [kubeflow/pipelines#5367]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)? GCP Marketplace
*  KFP version: 1.4.1

### Steps to reproduce

1. Upload a relatively large (e.g. ~5G) file to a GCS bucket
2. Create a pipeline run using the code snippet below
3. Open the run in the KFP UI
4. Click on the "Download from GCS" component
5. Continuously open and close the "Input/Output" tab (e.g. by clicking on the "x" of the side pane, then on the component, then on the "x" again, etc.; or by clicking on "Visualizations", then "Input/Output", then "Visualizations", etc.)
6. You should see the resource usage of the `ml-pipeline-ui` pod skyrocket and eventually the pod will be restarted

Code snippet to build and run a pipeline:

```python
import kfp
from kfp.compiler import compiler

LARGE_FILE_URI = "gs://..."
KFP_HOST = "https://..."


@kfp.dsl.pipeline(
    name="UI Crashing Pipeline",
    description="Pipeline to help reproduce the KFP UI crash",
)
def pipeline():
    download_op = kfp.components.load_component_from_url(
        "https://raw.githubusercontent.com/kubeflow/pipelines/master/components/google-cloud/storage/download_blob/component.yaml"
    )
    _ = download_op(gcs_path=LARGE_FILE_URI,)


if __name__ == "__main__":
    compiler.Compiler().compile(pipeline, "pipeline.zip")

    client = kfp.Client(KFP_HOST)
    experiment = client.create_experiment(name="example")
    run = client.run_pipeline(experiment.id, "ui-crashing-pipeline", "pipeline.zip")
```

Some metrics graphs of `ml-pipeline-ui` extracted from GKE (the bumps correspond to the times that I was clicking around as specified in step 5):

![image](https://user-images.githubusercontent.com/14166032/112295068-36604e00-8c9c-11eb-852b-7e4ec047849a.png)
![image](https://user-images.githubusercontent.com/14166032/112295090-3bbd9880-8c9c-11eb-9fda-78d385b5cab1.png)
![image](https://user-images.githubusercontent.com/14166032/112295107-3fe9b600-8c9c-11eb-8872-125e9402e560.png)

### Expected result

The `ml-pipeline-ui` doesn't start using insane amounts of resources and doesn't crash.

### Materials and Reference

As far as I've investigated, clicking on the "Inputs/Outputs" tab sends a request to the backend to get 255 bytes of each file to use as a preview. However, the actual pod seems to download the whole file, which causes the network and CPU spikes I've shown above.

I'm not familiar enough with the implementation, but probably a thing to look into is whether it's possible to prevent the pod from downloading the whole file. Another option could probably be to use some sort of cache for the preview.

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by Bobgy** [comment]
Thank you for the report!
Contributions welcomed, the code path related is https://github.com/kubeflow/pipelines/blob/eb558423ecdca969f2dea55e0d1b0197fafbcb13/frontend/server/handlers/artifacts.ts#L200.
