### ISSUE TITLE
[frontend] Sometimes the "choose file" button doesn't work when trying to upload pipeline

### ISSUE THREAD

**Issue by capri-xiyue** [kubeflow/pipelines#5372]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?

*  KFP version: 1.4.0 （In fact, it also happened in 1.0.x and 1.3.x version)

### Steps to reproduce
It may not easy to reproduce the bug.
Sometimes the "choose file" button doesn't work when trying to upload pipeline, the screen won't pop up which allows the user to choose the file to upload. After I restarted the chrome, the "choose file" button started to work.

### Expected result
 After clicking "choose file" button when trying to upload pipeline, a screen pops up which allows the user to choose the file.

### Materials and Reference

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by capri-xiyue** [comment]
![Uploading Screen Shot 2021-03-24 at 2.21.49 PM.png…]()

**Comment by Bobgy** [comment]
Pending reproduction
