### ISSUE TITLE
[feature] get output of conditional step

### ISSUE THREAD

**Issue by alvercau** [kubeflow/pipelines#5380]
### Feature Area

 /area sdk 

### What feature would you like to see?

Currently it does not seem to be possible to get the output of a conditional step, like so:
```
with dsl.Condition(base_model == "", name="Skip-Pretraining"): 

            pretraining_step = pretraining_op(
                image=image,
            )
           outputs = pretraining_op.outputs["output"]
```

### What is the use case or pain point?

I have a pipeline with optional pretraining for transfer learning, and in further steps of my pipeline, I use either the pretrained model as a base model, which path is stored in the outputs of the step, or a different model mode in case there was no pretraining. The further steps need to know which base model to use, depending on whether there was pretraining or not. 

### Is there a workaround currently?

Now I check if the pretrained model file exists in the mounted volume, but it's not ideal.

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by Ark-kun** [comment]
We currently do not provide a way to re-join conditional branches.

This leads to some code duplication:
https://github.com/kubeflow/pipelines/blob/a80421191db917322ff312626409526b0a76aa68/samples/core/continue_training_from_prod/continue_training_from_prod.py

One workaround might be to have the training process encapsulated in a `@dsl.graph_component` function. Then you can call it with or without passing the pre-trained model.
(I'm not 100% sure it will work though.)

You could also do something similar with graph `component.yaml` components.
