### ISSUE TITLE
[bug] manifests: Include metacontroller manifests

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/pipelines#5400]
### What steps did you take

The multi-user pipelines installation includes the metacontroller component.
However, it doesn't include it under `third-party`, like for other apps.
Since metacontroller is something that KFP uses, we should move it to the KFP repo under third-party and not have it under `contrib` in kubeflow/manifests.

**Comment by Bobgy** [comment]
metacontroller is also used in GCP distribution, but since KFP needs it, I agree we can put it here.
