### ISSUE TITLE
[backend] Metrics Stopped Showing up when More than 5

### ISSUE THREAD

**Issue by tinahbu** [kubeflow/pipelines#5401]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)? we used [`kfctl`](https://github.com/kubeflow/manifests/blob/master/distributions/kfdef/kfctl_istio_dex.v1.2.0.yaml)
*  KFP version: `v1.2.0`
*  KFP SDK version: 
    ```
    kfp==1.4.0
    kfp-pipeline-spec==0.1.6
    kfp-server-api==1.4.1
    ```

### Steps to reproduce

this is not an exhaustive experiment by any means but our metrics stopped showing up in the run table & "run output" tab when we write more than 5 metrics to `/mlpipeline-metrics.json` and we are not sure if this is a bug or a restriction from kubeflow

can have up to 5 metrics:

![IMG_6526](https://user-images.githubusercontent.com/7570863/113187741-0ec63400-920e-11eb-9fc0-70aa6e8fadd2.JPG)

when 6 metrics (or more) were sent, none showed up:

* didn't show up in table

![IMG_6527](https://user-images.githubusercontent.com/7570863/113187794-1ede1380-920e-11eb-9c90-5db0e4b94796.JPG)

* didn't show up in "compare runs" (the whole metrics section is empty)

![IMG_6529](https://user-images.githubusercontent.com/7570863/113187836-2ac9d580-920e-11eb-8660-c99a33e79a37.jpg)

### Expected result

* all metrics should be visible when "compare runs"
* it would be great to have more than 2 visible columns in the table too

### Materials and Reference

i did some googling and it seems some people used 

```
file_outputs={
    "mlpipeline-metrics": "/mlpipeline-metrics.json",
    "mlpipeline-full-metrics": "/mlpipeline-full-metrics.json",
    "mlpipeline-ui-metadata": "/mlpipeline-ui-metadata.json",
}
```

in their pipeline component. i cant find `mlpipeline-full-metrics` with `ag` in the pipelines repo though. not sure if this is what i should be doing when sending too many metrics

i couldn't really find where to look in this repo for this issue. would love any pointers

**Comment by Bobgy** [comment]
This is one of the issues we plan to solve together in bit.ly/kfp-v2. Putting it in IR-based KFP project

**Comment by rimolive** [comment]
Closing this issue. In later releases the way you visualize metrics has changed.

/close
