### ISSUE TITLE
[manifests] metadata-envoy-deployment sidecar injection

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/pipelines#5414]
### What steps did you take

Deploy multi-user pipelines manifests. The `metadata-envoy-deployment` is injected with a sidecar and crashes.
The reason is that `metadata-envoy-deployment` runs an Envoy Pod and it seems 2 Envoys don't play well together.
Thus, we need to disable injection for this Deployment.

@Bobgy if possible, can you give some context how `metadata-envoy-deployment` is used?

I will open a PR for adding a sidecar injection annotation for `metadata-envoy-deployment`.

**Comment by Bobgy** [comment]
Thank you!
It's a gateway to allow using grpcweb from KFP UI.

**Comment by zijianjoy** [comment]
Do we also need to apply the same change to `metadata-grpc-deployment` as well?

My deployment looks like:
![metadatadeployment](https://user-images.githubusercontent.com/37026441/113367114-09511280-9310-11eb-811b-65ca37b02652.png)
