### ISSUE TITLE
[Testing] tests flaky when pulling from dockerhub

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#5425]
See https://oss-prow.knative.dev/view/gs/oss-prow/pr-logs/pull/kubeflow_pipelines/5424/kubeflow-pipeline-e2e-test/1378351440040300544#1:build-log.txt%3A1308

> Step #1 - "scheduledworkflow": Get https://registry-1.docker.io/v2/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

The same error message happens randomly during different image build process.

**Comment by Bobgy** [comment]
From PR https://github.com/kubeflow/pipelines/pull/5424

**Comment by NikeNano** [comment]
Do you know what this error comes from? These images should be on google container registry as I understand, are there any rate limiting?

**Comment by Bobgy** [comment]
Let me elaborate, the above error occurs when we are building KFP docker images, we need to pull some common images from dockerhub as the base.

**Comment by NikeNano** [comment]
Ok, thanks! Do you expect these errors to be due to the rate limit? Could we move the base images to gcr as well?

**Comment by Bobgy** [comment]
I agree. Looks like it recovered, if it keeps happening, we should do that
