### ISSUE TITLE
Unable to use tensorboard viewer using S3 path

### ISSUE THREAD

**Issue by shrinath-suresh** [kubeflow/pipelines#5426]
### What steps did you take

To view the output in tensorboard we have created the `mlpipeline-ui-metadata.json` file with following content (Followed the instructions from - https://www.kubeflow.org/docs/components/pipelines/sdk/output-viewer/#tensorboard )

```
{"outputs": [{"type": "tensorboard", "source": "s3://<S3_path>"}]}
```

to view the training output in tensorboard. 

### What happened:
In the visualizations tab, `Start Tensorboard` button is appearing as expected. 

![image](https://user-images.githubusercontent.com/63862647/113505495-e0718d00-955c-11eb-971e-f86c3acc1f6e.png)

Once `Start Tensorboard` is clicked, `Open Tensorboard` is appearing as expected. 

![image](https://user-images.githubusercontent.com/63862647/113505521-f8e1a780-955c-11eb-91dd-d6ba9fbe0f2f.png)

But when the `Start Tensorboard` is clicked, an empty dashboard is shown. 

![image](https://user-images.githubusercontent.com/63862647/113617492-00e03b00-9674-11eb-9fa8-92000c1368e9.png)

### What did you expect to happen:

Tensorboard should be opened as below

![image](https://user-images.githubusercontent.com/63862647/113505605-8e7d3700-955d-11eb-9116-583fc0977bd8.png)

### Environment:

*  KFP version: 1.4
To find the version number, See version number shows on bottom of KFP UI left sidenav. -->
*  KFP SDK version: 0.5.2

### Anything else you would like to add:

To test the above behavious in local machine,  we tried running

```
tensorboard --logdir s3://<S3_path>
```
Tensorboard is showing an empty dashboard.

However, the dashboard is working fine with the db argument as below

```
tensorboard --db s3://<S3_path>
```

From the https://www.kubeflow.org/docs/components/pipelines/sdk/output-viewer/#tensorboard i couldnt figure out a way to change from `logdir` to `db`. Or is there any other way to achieve this in kubeflow `mlpipeline-ui-metadata.json` ?

### Labels

/area frontend

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by Bobgy** [comment]
Hi @shrinath-suresh, can you explain the difference between --db and --logdir, are there any references?

KFP doesn't currently support changing the argument, but we can make it configurable.

What kind of configuration experience do you prefer? Do all s3 uris need to change the argument?


Or we can add an input textbox on KFP UI where users may come and configure their args?

Or do you have any other suggestions

**Comment by shrinath-suresh** [comment]
@Bobgy Thanks for the reply. 

We were able to log the tensorboard events to S3. Only the Dashboard was having issues when opened with S3 Path. I was looking into couple of blog posts related to the tensorboard S3 integration. One of them suggested to have the paramter as `db` instead of `logdir` (i will try to see if i can get the link). However, i couldnt do it in KFP, as there is no option to set the `db` parameter.

I have quick question before the suggestion. **Does KFP support Tensorboard with S3 urls as backend?**. 

It would be helpful to have an extra parameter in `mlpipeline-ui-metadata.json` file.

`{"outputs": [{"type": "tensorboard", "source": "s3://<S3_path>", "type" : "db"}]}`

**Comment by Bobgy** [comment]
It doesn't work out of the box, you may refer to this issue how to configure it:
https://github.com/kubeflow/pipelines/issues/4364

**Comment by Bobgy** [comment]
The suggestion sounds reasonable, but I'd still want to confirm why.

**Comment by shrinath-suresh** [comment]
@Bobgy 

`tensorboard --help` output shows the db argument help as below

`  --db URI              [experimental] sets SQL database URI and enables DB backend mode, which is read-only unless --db_import is also passed.`

Looks like it is used specifically for SQLITE databases. I couldnt find the link where db argument is suggested to be used for S3 URLs

**Comment by shrinath-suresh** [comment]
> It doesn't work out of the box, you may refer to this issue how to configure credentials:
> #4364

We have installed kubeflow-pipelines using this branch - https://github.com/e2fyi/kubeflow-aws/tree/master . And looks like,  the configuration which is mentioned in the #4364 is already part of installation.

**Comment by Bobgy** [comment]
@shrinath-suresh thanks for these additional information

just to be sure, I want to confirm this --

when you see "empty dashboard is shown", can you try to get logs of the tensorboard instance? It may have more detailed error messages.

**Comment by lechwolowski** [comment]
It doesn't wanna work for me either on tensorflow 2.0.0 with following Error message: Unable to connect to endpoint. While it works on tensorflow 2.3.2. Is there a way to bump up tensorflow version for this viewer?

**Comment by Bobgy** [comment]
@lechwolowski it's not currently, but I just filed https://github.com/kubeflow/pipelines/issues/5471 which tries to support customizing tensorboard image

**Comment by shrinath-suresh** [comment]
@Bobgy We have identified the solution. Tensorboard with S3 buckets works based on region. The bucket which we used was in different region. Once  we updated the AWS_REGION variable in cluster, we are able to see the tensorboard UI

**Comment by Bobgy** [comment]
Cool @shrinath-suresh it'll be helpful commenting what exactly is required (like an example patch of tensorboard), so other people finding this issue can get their problems solved

**Comment by shrinath-suresh** [comment]
Solution: Tensorboard with S3 URLs works **based on the region where bucket is placed**. Ensure to set `AWS_REGION` value as same as the bucket region.

**Comment by shrinath-suresh** [comment]
@Bobgy It will be more helpful if the documentation is updated about the supported systems - https://www.kubeflow.org/docs/components/pipelines/sdk/output-viewer/#tensorboard . What do you think ?

**Comment by Bobgy** [comment]
That's a very good point, do you want to contribute that?

**Comment by Bobgy** [comment]
Besides that, IIUC `AWS_REGION` can be different per pipeline?
So I think it'll be ideal to support https://github.com/kubeflow/pipelines/issues/4714, e.g. you can configure the AWS_REGION in your mlpipeline-ui-metadata as a field, and let it auto picked up by KFP started tensorboard.

**Comment by Bobgy** [comment]
WDYT @shrinath-suresh

**Comment by ConverJens** [comment]
@Bobgy @shrinath-suresh Generally, to use anything Tensorflow-based (e.g. TF serving, TFX) the following environment variables needs to be set:
ENDPOINT_URL
S3_USE_HTTPS
S3_VERIFY_SSL
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY

Additionally, one might need to add own certificates if you're self-hosting your S3 solution (e.g. Minio, Ceph) on-prem.

**Comment by shrinath-suresh** [comment]
> That's a very good point, do you want to contribute that?

Already occupied with  deliverables. I can pick it up after 2 weeks. I will make a note of it.

**Comment by shrinath-suresh** [comment]
> WDYT @shrinath-suresh

It makes more sense to have it as a parameter in the mlpipeline-ui-metatadata and it would be easy to configure as well.

**Comment by Bobgy** [comment]
Thanks for the feedback @ConverJens @shrinath-suresh!
Let's move the discussion to https://github.com/kubeflow/pipelines/issues/4714
