### ISSUE TITLE
[feature] Support other gcp project's gcr images to be pulled by service account with workload identity

### ISSUE THREAD

**Issue by Matts966** [kubeflow/pipelines#5427]
### Feature Area

/area backend

### What feature would you like to see?

Current workload identity supports multiple project for calling normal APIs, but we cannot pull images on other project's container registry even if the google service account has enough storage permissions (ErrImagePull occurs).

I don't know who can handle better (GCP's backend or Kubeflow Pipelines), but I confirmed that we can pull images after calling `gcloud configure-docker`.

### What is the use case or pain point?

With this supported, we can easily call other GCP project's API on Kubeflow Pipelines easily.

### Is there a workaround currently?

We can use normal kubernetes secret for imagePullSecret.

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by munagekar** [comment]
A GKE nodepool has a VM service account. This is used to pull images. You need to grant storage permission to this SA.

**Comment by Matts966** [comment]
Thank you for quick response!

So, workload identity cannot affect service account to pull images? I also bound the google service account that has enough permissions to some Kubeflow Pipelines service account such as `pipeline-runner`, but it does not work.

Is it only the node pool SA that can pull images?

In addition, I found problem of `set_image_pull_secrets` of `Config` object. It does not change the secret form `pipeline-runner-token-*****`.
Maybe related to https://github.com/kubeflow/pipelines/issues/3847. I will add another issue with more confirmation.

**Comment by munagekar** [comment]
> Is it only the node pool SA that can pull images?

In my organization we grant permission to nodepoolSA. I suppose docker pull secrets might work as well. 
However default-editor/pipeline-runner does not pull images and hence granting permission to it will not work.

**Comment by Matts966** [comment]
> In addition, I found problem of set_image_pull_secrets of Config object. It does not change the secret form pipeline-runner-token-*****.

This was my mistake. Maybe specifying `imagePullSecret` is the best way.

**Comment by Matts966** [comment]
Please close this issue if this is out of scope.

**Comment by capri-xiyue** [comment]
Closed because it sounds like GKE expected behavior
