### ISSUE TITLE
build_python_component without GCS

### ISSUE THREAD

**Issue by aronla** [kubeflow/pipelines#5438]
Hi! Is it possible to use `kfp.compile.build_python_component` without using google cloud storage (for the parameter `staging_gcs_path`)?

I'm trying to run the [pipeline SDK tutorial ](https://v0-7.kubeflow.org/docs/pipelines/sdk/sdk-overview/) locally and this step

```
OUTPUT_DIR = 'local_tmp_dir/
my_op = compiler.build_python_component(
  component_func=my_python_func,
  staging_gcs_path=OUTPUT_DIR,
  target_image=TARGET_IMAGE)
``` 

outputs 

`ValueError: Error: local_tmp_dir/ should be a GCS path.`

Thank you! :)

**Comment by rui5i** [comment]
According to @chensun , the `staging_gcs_path` is a required field in sdk code. 
This `kfp.compile.build_python_component` was deprecated before but was revived recently. We may want to deprecate it again sometime in the future.

**Comment by Ark-kun** [comment]
Could you try using `kfp.components.create_component_from_func` instead? You can base the component on an image you build and push independently.

**Comment by aronla** [comment]
Hi and thanks for your answers! Yes, I can build components using `kfp.components.create_component_from_func` sucessfully. But the functionality is different I guess - `build_python_component` creates a docker-image and `create_component_from_func` just "injects" the code into the manifest and runs it on a base-image.

To be honest, I was just trying to learn the SDK using the tutorial and a local minikube session and I stumbled on this part, but happy to close.
Thanks for your help!
