### ISSUE TITLE
[feature] Update MLMD version and add process to keep this up to date. 

### ISSUE THREAD

**Issue by davidspek** [kubeflow/pipelines#5439]
Currently pipelines uses gcr.io/tfx-oss-public/ml_metadata_store_server version `0.25.1` but `0.29.0` is the latest version. The image tag in [metadata-grpc-deployment.yaml](https://github.com/kubeflow/pipelines/blob/master/manifests/kustomize/base/metadata/base/metadata-grpc-deployment.yaml) needs updating. 
To automate this process, all image tags should be listed in the `images:` section of the `kustiomization.yaml` files ([here](https://github.com/kubeflow/pipelines/blob/master/manifests/kustomize/base/metadata/base/kustomization.yaml) for this specific case). Once that is done, Renovate can be setup to create PRs updating the image tags of the manifests. 

@Bobgy Would you like me to go through the manifests and set the images in the `kustomization.yaml` files and add the necessary Renovate config for kustomize?

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by Bobgy** [comment]
Note, updating MLMD is fairly complex, we need to update all the 7 locations listed in https://github.com/kubeflow/pipelines/blob/1128631cd5b4335080fb70ca35f864dbedb8b2cf/manifests/kustomize/base/metadata/base/metadata-grpc-deployment.yaml#L19-L24

Some of them are not well documented, so I'd suggest delaying the upgrade to next release -- unless you have absolute reasons.

**Comment by DavidSpek** [comment]
@Bobgy I have no particular reason for updating it, just something I noticed. Once things settle down a bit more I think it would be interesting to setup Renovate with the regex engine so that it can handle updating MLMD everywhere in the repo in a single PR so it can be tested properly. How does that sound?

**Comment by Bobgy** [comment]
Part of the upgrade requires regenerating a proto client using later proto definitions, so it's unlikely we can configure renovate to do this.

But it's very helpful to automate the upgrade, we may add this script to release process

**Comment by DavidSpek** [comment]
You can have Renovate execute a script as well, so it might still be possible to fully automate.

**Comment by DavidSpek** [comment]
Happy to see that theMLMD version has been upgraded in the latest release. @Bobgy is having this managed by Renovate something you would want to implement? I've been doing quite a bit of stuff with Renovate lately to automate keeping all the manifests for Kubeflow up to date so I might be able to help here.

**Comment by Bobgy** [comment]
@DavidSpek did you figure out the scriptable update? MLMD would need this, because one step is pulling in new proto definitions and regenerate proto clients.

**Comment by DavidSpek** [comment]
Do you maybe have a link to the script that needs to be run and the locations where MLMD needs to be updated? It would save me some time looking for it. If not, it isn't a problem either. Then I can test on my fork to try and get this setup.
Renovate has support for running scripts if it is self-hosted, but I'm not sure if that is an option or a path you want to go down. However, I think it might be possible to use another setup to run that script or pull those definitions into the PR.

**Comment by Bobgy** [comment]
/cc @zijianjoy 
Your new script addresses first part of this issue

**Comment by zijianjoy** [comment]
Thank you David and Yuan! This is the link to the MLMD upgrade script guide: https://github.com/kubeflow/pipelines/tree/master/third_party/ml-metadata#upgrade-mlmd-versions

**Comment by zijianjoy** [comment]
We are currently waiting for ML Metadata 1.14 to be released. Once it is available, we will upgrade to this version.

**Comment by rimolive** [comment]
Closing this issue as ML Metadata 1.14 is already released and manifests upgraded.

/close
