### ISSUE TITLE
[backend] grpc: received message larger than max

### ISSUE THREAD

**Issue by ConverJens** [kubeflow/pipelines#5440]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
kfctl and KubeFlow v1.1.0 istio dex
*  KFP version: 
v1.0.0
*  KFP SDK version: 
v1.1.2

### Steps to reproduce
Latest version of TFX (0.29.0rc0) introduced an IR of the pipeline definitions. For larger pipelines (>20 nodes) these are quite large (>5Mb), which exceeds the default gRPC limit and the UI gives the following error message:
`{"error":"grpc: received message larger than max (5429435 vs. 4194304)","message":"grpc: received message larger than max (5429435 vs. 4194304)","code":8}`

I update the backend limit in the deployment to be twice the default size:
-name: DBCONFIG_GROUPCONCATMAXLEN
value: "8388608"
under upstream/base/pipeline/ml-pipeline-apiserver-deployment.yaml and I can exec into the pod and verify that the value is indeed set.

Despite this, the UI still raised and error with the default size of 4194304.

I removed and redeployed all pipeline components as well as the mysql DB but this didn't change anything.

To be on the safe side I exec:ed into the api-server and ran:
sed -i 's/4194304/8388608/g' config.json
which updated config.json and viper should then repopulate this field but still no difference.

Following a comment in this issue kubeflow/pipelines#2310, I also tested running:
set GLOBAL group_concat_max_len=8388608;
but this had no effect either.

### Expected result
Changing the gRPC message limit in the DB config should also take effect in the UI.

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by capri-xiyue** [comment]
Can you provide a sample for us to verify the problem?

**Comment by capri-xiyue** [comment]
In addition, can you also deploy latest KFP to see whether it gets fixed?
