### ISSUE TITLE
[feature] Can reusable component output data be downloaded via SDK?

### ISSUE THREAD

**Issue by huihuang2015** [kubeflow/pipelines#5441]
### Feature Area

<area>sdk</area>

### What feature would you like to see?

SDK to download component output artifact after run

### What is the use case or pain point?

Output artifact can only be downloaded via UI, but not via SDK. Automation is difficult.

### Is there a workaround currently?

Don't know how to do it now.

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by Ark-kun** [comment]
The intermediate data storage is considered to be implementation detail.
We advice our users to make any data export explicit. This way they can easily control the location of the exported data.
If you want to put the artifact into a GCS bucket, just pass it to an `Upload to GCS` component.
See this pipeline for example:
https://github.com/kubeflow/pipelines/blob/a80421191db917322ff312626409526b0a76aa68/samples/core/continue_training_from_prod/continue_training_from_prod.py#L94

P.S. We could expose the ReadArtifact backend API method, but it would be pretty hard to use.
