### ISSUE TITLE
[backend] "platform-agnostic" missing "Viewer" CRD

### ISSUE THREAD

**Issue by nakfour** [kubeflow/pipelines#5452]
As part of the effort to get the Openshift distribution ready for KF 1.3 release, we tried to install the "platform-agnostic" pipeline kustomization and it is missing the "Viewer" CRD. Also discussed here https://github.com/kubeflow/manifests/issues/1810. 
PR here: https://github.com/kubeflow/manifests/blob/63c9026ee3e01ad8514882358d57d944d3a92b52/distributions/stacks/openshift/application/pipeline-agnostic/kustomization.yaml

**Comment by yanniszark** [comment]
cc @Bobgy

**Comment by Bobgy** [comment]
Thanks for the report @nakfour!
I want to confirm you are doing the right thing, read KFP standalone installation guide in https://www.kubeflow.org/docs/components/pipelines/installation/standalone-deployment/#deploying-kubeflow-pipelines.

CRDs are installed separated in:

```bash
kubectl apply -k "github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=$PIPELINE_VERSION"
```

Did you include `cluster-scoped-resources` in your kustomization.yaml?

**Comment by nakfour** [comment]
@Bobgy we followed the instructions from here https://github.com/kubeflow/manifests#install-individual-components and replaced "platform-agnostic-multi-user" with "platform-agnostic-multi-user"
As you can see the two are kustomizations are very different
https://github.com/kubeflow/manifests/blob/master/apps/pipeline/upstream/env/platform-agnostic/kustomization.yaml
https://github.com/kubeflow/manifests/blob/master/apps/pipeline/upstream/env/platform-agnostic-multi-user/kustomization.yaml

**Comment by Bobgy** [comment]
Yes, the difference is by design.

@yanniszark I think we should add documentation for standalone installation in kubeflow/manifests to avoid confusion like this

**Comment by nakfour** [comment]
@Bobgy please elaborate why by design? I find it hard to believe they are both different, it should be the same

**Comment by Bobgy** [comment]
There are 3 major ways to deploy KFP:

* Namespaced KFP standalone.
* Multi-user KFP.
* Multiple namespaced KFP standalone operating independently for several namespaces. Typically an administrator installs the cluster-scoped resources and namespace owners can install KFP by themselves.

The minimum maintenance way to support all the three types is to default to include cluster scoped resources for multi-user install and not include them for namespaced installs.

I am open for suggestions. Currently, I plan to document the difference better.

**Comment by nakfour** [comment]
@Bobgy thanks I understand. My suggestion is to add more information on the main Kubeflow installation Readme here: https://github.com/kubeflow/manifests#install-individual-components
Explain one option, and point to more documentation to install the other options you just explained.
