### ISSUE TITLE
[Discuss] Should KFServing Component use InputPath?

### ISSUE THREAD

**Issue by wilbry** [kubeflow/pipelines#5453]
Apologies if this is the wrong project, I am not sure if this component is developed here or over in kfserving, but should there be a version of KFServing (or maybe at way to do it with one version) such that the URI is an InputPath so a newly trained model can be served as part of a pipeline? I have searched the issues for a few days trying to see if this has been discussed before and have come up empty. 

https://github.com/kubeflow/pipelines/blob/02dbcfa062ea975fcf8793b711640ed20442389e/components/kubeflow/kfserving/component.yaml#L6

**Comment by Ark-kun** [comment]
I like the suggestion. Having file-based inputs always helps.
I think that KFServe consuming the model as file, rather than as URL is significantly easier for the pipeline authors.

The change might be non-trivial, since the KFServing component needs to copy the data to the serving pod[s].

You can try a naïve draft variant and see what happens (most likely it will fail): https://raw.githubusercontent.com/kubeflow/pipelines/2f6fd6ca7e19a39f8d838dc83f9d4ae059d354a9/components/kubeflow/kfserving/from_artifact/component.yaml

Perhaps the KFServe community can help with this improvement.

**Comment by wilbry** [comment]
I think you are correct that it may be non-trivial. I took the component.yaml you provided and modified the kfservingdeployer.py file in src to append `"file://"` if no prefix was given, but upon running it, I realize that kubeflow is most likely attaching the storage to the pod running the code in kfservingdeployer.py, and not the pod that gets launched by KFServing, so you still end up with an error like

```
RuntimeError: Local path file:///tmp/inputs/Model/data does not exist.
```

I was considering using the Minio URL, but I am not sure if that is possible to get from the pipeline param dynamically. I will keep playing around with this and let you know if I make any progress, but would be happy for others to jump in with their suggestions.

**Comment by wilbry** [comment]
Seems that there is a way to pass [PVC URI](https://github.com/kubeflow/kfserving/blob/a2e835f9c9d057e7bc04160ba903f715c175c757/pkg/webhook/admission/pod/storage_initializer_injector.go#L116), but I am a bit out of my depth to know how to format that using only the PipelineParam.

**Comment by Ark-kun** [comment]
I don't really know much about KFServing.
The general solution might be as follows:

* KFServe Launcher component creates a KFServe pod with an init container which will wait to receive the model. The init and main containers share an emptyDir volume where the model will be placed.
* The launcher component uses `kubectl cp` to copy the model into the init container FS, into the shared emptyDir volume. It then writes a completion flag file to indicate that the copying if finished.
* The init container notices the completion flag file and exists.
* The main container starts and reads the model from the emptyDir volume file.

The wait for model polling could also be integrated into KFServe itself.

WDYT?

**Comment by wilbry** [comment]
I also don't have much KFServing knowledge. I saw it it was part of the overall Kubeflow framework and wanted to use it to deploy models trained using KFP. Do you know who might be good to loop into this discussion or should I open an issue over in kfserving?

**Comment by wilbry** [comment]
Looking into this more, I found an earlier comment where you recommend explicit persisting: [#4381](https://github.com/kubeflow/pipelines/issues/4381#issuecomment-675083510). I think that is the path forward right now. Maybe this is outside the purview of this project, but for cloud providers that provide managed service, this may lead to duplicating the storage, so it would be nice to be able to know where the item was persisted already in that situation.

This may also be resolved in v2 of the SDK, using OutputArtifact rather than OutputPath. Please let me know if I am misunderstanding this.

Thanks

**Comment by Bobgy** [comment]
Agree with

> This may also be resolved in v2 of the SDK, using OutputArtifact rather than OutputPath. Please let me know if I am misunderstanding this.

/cc @neuromage @chensun 
I think we are missing a good example component & pipeline to demonstrate this use-case.
With the v2 InputArtifact input type, it's possible to get uri of the artifact in the component, so that it could directly pass the gcs/s3 uri to KFServing component.

**Comment by wilbry** [comment]
I think that is a good way forward. I have been playing with it a little bit, but I believe that the specific kfserving component will need to be upgraded to v2 to make it possible to work. The way I understand it is that you can't mix v2 components and v1 components, is that correct?

**Comment by wilbry** [comment]
I think this is a good path forward. I have a local version of the KFServing component I have edited to be compatible with the v2 pipeline compilation, but I can't test it because I am having trouble determining how to run a v2 pipeline on a stand-alone installation (if it is event possible at this point)

**Comment by neuromage** [comment]
@chensun and @Bobgy can you provide @wilbry with some pointers here for how to run v2 pipelines?

**Comment by Ark-kun** [comment]
> for cloud providers that provide managed service, this may lead to duplicating the storage

Models are pretty small, so this might be a small price to pay for convenience.

Even for cloud services, a supported URI schema might not mean that the service may be called directly without copying the data. As an example, many existing GCS buckets cannot be used with Google Cloud AutoML service. That service only supports single-region buckets in the `us-central1` region. Just giving a URI to a component or service does not guarantee that that URI would be used successfully. Using File-based I/O and shifting the data staging responsibility to components makes the components more portable and robust.

**Comment by Bobgy** [comment]
Updated documentation for v2 compatible mode in https://www.kubeflow.org/docs/components/pipelines/sdk/v2/v2-compatibility/
