### ISSUE TITLE
[frontend] Pipeline generic installation does not include a virtual service

### ISSUE THREAD

**Issue by nakfour** [kubeflow/pipelines#5462]
When installing "platform-agnostic" and trying to get to the pipeline UI from the Kubeflow central dashboard, we get "Sorry, /pipeline/ is not a valid page". Checking for virtualservices in namespace kubeflow, there are none for pipelines. Looking at the code, we dont see a VirtualService created : https://github.com/kubeflow/manifests/tree/master/apps/pipeline/upstream/base/installs/generic
While multi-user install does include a virtualservice: https://github.com/kubeflow/manifests/blob/master/apps/pipeline/upstream/base/installs/multi-user/virtual-service.yaml

**Comment by zijianjoy** [comment]
Thank you @nakfour for submitting this request!

@Bobgy and I have discussed about this issue and our initial thinking is to perform following refactorings:

1. For `ml-pipeline-ui` VirtualService, we need to create a folder called `ml-pipeline-ui` under https://github.com/kubeflow/pipelines/tree/master/manifests/kustomize/base/pipeline, and put all UI related items, including virtual service file there.
2. For `metadata-grpc` VirtualService, we will create a folder called `virtual-service` under `options` folder: https://github.com/kubeflow/pipelines/tree/master/manifests/kustomize/base/metadata/options. And put the virtual service definition to that folder. And put the remaining files under `istio` option to a new folder called `multi-user` option. Also we need to add a README to explain that if you want to use virtual service, you can install `virtual-service` option.

**Comment by zijianjoy** [comment]
For now, you can use the `kubeflow/pipelines` instead of `kubeflow/manifests` repo for the virtual service definition: https://github.com/kubeflow/pipelines/blob/master/manifests/kustomize/base/metadata/options/istio/virtual-service.yaml

**Comment by Bobgy** [comment]
@zijianjoy virtual service for ml-pipeline-ui should still be put in options folder, because it's not needed for env without istio.

**Comment by nakfour** [comment]
@Bobgy @zijianjoy sounds good. since these VRs are common for all options to install pipelines, good idea to place them under base/pipeline
