### ISSUE TITLE
Some error logs in sample for ML - TFX - Taxi Tip Prediction Model Trainer

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/pipelines#547]
Seup up kubeflow pipleine and try to run the Taix example cases, but failed, checked the k8s pod logs, see the schema validation failed?  See below logs. 

```bash
[root@test ~]#kubectl -n kubeflow logs tfx-taxi-cab-classification-pipeline-example-7lqmr-1004343013
INFO:root:Writing anomalies to /tmp/taix3/tfx-taxi-cab-classification-pipeline-example-7lqmr/validation/anomalies.pb2
ERROR:root:Anomaly in feature "company": Examples contain values missing from the schema: 2092 - 61288 Sbeih company (<1%), 2192 - 73487 Zeymane Corp (<1%), 2192 - Zeymane Corp (<1%), 2823 - 73307 Seung Lee (<1%), 3094 - 24059 G.L.B. Cab Co (<1%), 3319 - CD Cab Co (<1%), 3385 - Eman Cab (<1%), 3897 - 57856 Ilie Malec (<1%), 4053 - 40193 Adwar H. Nikola (<1%), 4197 - Royal Star (<1%), 585 - 88805 Valley Cab Co (<1%), 5874 - Sergey Cab Corp. (<1%), 6057 - 24657 Richard Addo (<1%), 6574 - Babylon Express Inc. (<1%), 6742 - 83735 Tasha ride inc (<1%). 
ERROR:root:Anomaly in feature "payment_type": Examples contain values missing from the schema: Prcard (<1%). 
```
Any suggestion to resovle the porblem? Thanks.

**Comment by jinchihe** [comment]
Seems there is a steps in the [model-analysis/examples/chicago_taxi](https://github.com/jinchihe/model-analysis/blob/master/examples/chicago_taxi/chicago_taxi_tfma_local_playground.ipynb), is the steps included in the pipeline? Thanks.

```bash
# Update the schema based on the observed anomalies.

# Relax the minimum fraction of values that must come from the domain for feature company.
company = tfdv.get_feature(schema, 'company')
company.distribution_constraints.min_domain_mass = 0.9

# Add new value to the domain of feature payment_type.
payment_type_domain = tfdv.get_domain(schema, 'payment_type')
payment_type_domain.value.append('Prcard')

# Validate eval stats after updating the schema 
updated_anomalies = tfdv.validate_statistics(eval_stats, schema)
tfdv.display_anomalies(updated_anomalies)
```

**Comment by jinchihe** [comment]
Seems only some error logs, and the pipeline process can be finished normally.

**Comment by zoux86** [comment]
hi, Had the problem been solved? 
i also met the problem. but my pipeline did not work normally. 
![image](https://user-images.githubusercontent.com/14087435/51434788-a7aeab80-1ca3-11e9-91cd-1f0a7be7444e.png)
### so i want to ask for advice how to sovle it.
Thanks!!!

**Comment by jinchihe** [comment]
@zoux86 You can go ahead, seems the following process can be finished with the scheme validation problem.

**Comment by zoux86** [comment]
yeah, these error doesn't matter. Thanks!!!

**Comment by zoux86** [comment]
yeah, these error doesn't matter. Thanks!!!

**Comment by jinchihe** [comment]
so I'd like to close the ticket. Thanks.
