### ISSUE TITLE
Assigning copyright to the project authors

### ISSUE THREAD

**Issue by jdavis34265** [kubeflow/pipelines#5470]
I wanted to start a discussion about the open-source nature of the Kubeflow projects.
Most Kubeflow projects already follow the opens-source guidelines, but I've noticed some issues in the Kubeflow Pipelines project.

I see that the Kubeflow Pipelines has a great developer community that takes a big part in development.
Despite that I've noticed that all copyrights are being assigned to the Google LLC corporation.

Most open-source projects, including major projects by Google (TensorFlow, Kubernetes etc) assign copyright to the project contributors.

To improve the openness of the Kubeflow Pipelines project **I propose to change the license messages to: "Copyright [year] The Kubeflow Pipelines Authors"**.

I found explicit guidance for this in the Google's open-source guidelines: https://opensource.google/docs/releasing/authors/
**Update the copyright statements in your LICENSE file and all file headers to list “The [Project] Authors” rather than “Google”:
Before: Copyright 2014 Google LLC
After: Copyright 2014 The [Project Name] Authors.**

---
Some examples of Google projects adopting this approach:

TensorFlow: "Copyright 2015 The TensorFlow Authors." https://github.com/tensorflow/tensorflow/blob/master/tensorflow/__init__.py

Knative: "Copyright <year> The Knative Authors" https://knative.dev/community/contributing/repository-guidelines/

Kubernetes: "Copyright 2015 The Kubernetes Authors." https://github.com/kubernetes/kubernetes/blob/master/hack/update-vendor-licenses.sh

Go: "Copyright (c) 2009 The Go Authors." https://golang.org/LICENSE

Kubeflow:
"Copyright 2018 The Kubeflow Authors" https://github.com/kubeflow/common/blob/master/hack/boilerplate/boilerplate.go.txt https://github.com/kubeflow/katib/issues/20 
"Copyright 2020 kubeflow.org." https://github.com/kubeflow/kfserving/blob/master/python/kfserving/kfserving/__init__.py

/cc @theadactyl @Bobgy @Ark-kun @chensun @SinaChavoshi @animeshsingh @elikatsis @NikeNano @Tomcli @RedbackThomson @eterna2 @zijianjoy @surajkota @Jeffwan @StefanoFioravanzo @jinchihe @DavidSpek

**Comment by Bobgy** [comment]
@jdavis34265 I think this is a very good point!
There were some early usages of "The Kubeflow Authors" in pipelines repo too, see https://github.com/kubeflow/pipelines/search?p=1&q=the+kubeflow+authors. However, we are not enforcing this style consistently.

I think it's reasonable to discuss this proposal, and if we accept it. IIUC, we should ask all the new contributions to copyright to `The Kubeflow Authors`. However, I'm not a lawyer, but my understand was that we cannot change existing headers. And also, copyrighting code to `The Kubeflow Authors` does not change the fact that copyright for a line of code still belongs to the company of that contributor.

Can I confirm the major rationale for making the change is making the project give credits to its contributors? (just confirmation, I think that's a good enough reason)

**Comment by Bobgy** [comment]
Our conclusion:

Google will initiate a PR to update all Google LLC copyright headers to "The Kubeflow Authors".
Google does not have the legal right to change other copyright headers.

Going forward, we'll suggest people to stick to "The Kubeflow Authors" headers.

**Comment by NikeNano** [comment]
Sound good!

**Comment by elikatsis** [comment]
This is great!

As https://opensource.google/docs/releasing/authors/ instructs, there should be an `AUTHORS` file. Do we have one? If not, how do we plan on populating it and where should it live (in which repository)?

**Comment by Bobgy** [comment]
Thanks for bringing this up @elikatsis!
I'll put up a PR to add the AUTHORS file.
