### ISSUE TITLE
[bug] Confusion matrix component task fails

### ISSUE THREAD

**Issue by Mullefa** [kubeflow/pipelines#5484]
### What steps did you take

I created a task in a pipeline using the [confusion matrix](https://github.com/kubeflow/pipelines/tree/ab63956f3a61d4d11b27ac26f097e1784588fed9/components/local/confusion_matrix) component.

### What happened:
The task failed with the following message:
```
Traceback (most recent call last):
  File "/ml/confusion_matrix.py", line 29, in <module>
    import pandas as pd
ImportError: No module named pandas
```
I believe this is because the Python dependencies are [installed for Python 3](https://github.com/kubeflow/pipelines/blob/master/components/local/base/Dockerfile), whereas the command in the component definition is `python2 ...`. 

### What did you expect to happen:

For the task to complete successfully.

### Environment:

*  How do you deploy Kubeflow Pipelines (KFP)? 
GCP AI Platform Pipelines
*  KFP version: 
1.4.1
*  KFP SDK version: 
1.4.0

### Anything else you would like to add:

If this issue is legitimate (and I haven't misinterpreted the error), I believe the [roc component](https://github.com/kubeflow/pipelines/tree/ab63956f3a61d4d11b27ac26f097e1784588fed9/components/local/roc) will suffer from the same issue.

### Labels

/area components

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by zijianjoy** [comment]
Thank you @Mullefa for identifying this issue! Would you like to create a PR to bump up python version for the fix?

**Comment by Ark-kun** [comment]
Thank you for identifying the issue.

We're interested to know more about your pipeline. What is the upstream component you use with the confusion matrix component?
