### ISSUE TITLE
default resource overhead for each individual profile

### ISSUE THREAD

**Issue by hsinhoyeh** [kubeflow/pipelines#5493]
**Question:**
Not sure whether this question has been discussed before, but I am curious about the resource overhead for each individual profile.
In the current configuration ( in v1.2, v1.3), when creating one single profile, there are two running pods are created by default:

```
ml-pipeline-ui-artifact-c8fbcb8f9-k88bz
ml-pipeline-visualizationserver-6b78c9646-s7q4c
```

each one takes additional istio sidecar container (cost 100m cpu/ 128Mi memory).
so in total cpu requested 100m * 2 + 128m * 2 = 0.5 CPU unit, memory requested 128 *2 + 128 * 2 = 512Mi.
(even the profile has been created but no further actions were conducted.)

so let say today we have to create 100 profiles (one for each individual participant) but only 20% of them are heavy users (80-20 rule), and our system wasted 100 * 80% * 0.5 CPU unit (and 512Mi + 100 * 80% memory).

This seems to be more like a resource leaking, not the design concept. any thoughts? or documents? thanks

---

transferred from https://github.com/kubeflow/kubeflow/issues/5832

**Comment by zijianjoy** [comment]
Hello @hsinhoyeh , you can disable the pipeline pods by setting the following label from your profile's namespace labels: `pipelines.kubeflow.org/enabled: false`.

You can do this for all the profiles that don't require Kubeflow Pipelines. For future roadmap, we plan to remove visualization server too. 

Does this solve your issue?

**Comment by Bobgy** [comment]
BTW, the mechanism @zijianjoy introduced is only available in Kubeflow 1.3.

To add to that, the deployment script https://github.com/kubeflow/pipelines/blob/a2d3f234eac1eff97f4ebdd99c69460a43ec0695/manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/sync.py is designed so that you can customize to your own requirements.

**Comment by hsinhoyeh** [comment]
@zijianjoy thanks, it did solve my issue.
@Bobgy seems that the design doc has access control, I got access denied.

**Comment by Bobgy** [comment]
@hsinhoyeh you can request access

**Comment by hsinhoyeh** [comment]
@zijianjoy @Bobgy this flag seems to disable all pipeline components (see [here](https://github.com/kubeflow/pipelines/blob/a2d3f234eac1eff97f4ebdd99c69460a43ec0695/manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/sync.py#L33)), not just these two components as I mentioned earlier. do you have any suggestion on how we can disable it without modifying python code?

**Comment by Bobgy** [comment]
Not really, if you only want to disable the two services, you need to modify the sync.py script.

**Comment by deepio-oc** [comment]
I agree with @hsinhoyeh. @Bobgy could you provide me the access to the document (I sent the request). I would like to understand why these services are launched per user.
