### ISSUE TITLE
[backend] Managed Storage Option Fails on KFP

### ISSUE THREAD

**Issue by bdoohan-goog** [kubeflow/pipelines#5504]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
On Google Cloud Platform via "AI Platform" > "Pipelines" > "New Pipeline"
*  KFP version: 
* 1.4.1
*  KFP SDK version: 
kfp                            1.4.0
kfp-pipeline-spec              0.1.7
kfp-server-api                 1.4.1

### Steps to reproduce

1) Log into console.cloud.google.com
2) Navigate to AI Platform > Kubeflow Pipelines
3) Click "New Instance" and then "Configure"
4) Choose your cluster and Namespace
5) Select "Use managed storage" and list Cloud SQL instance and Google Cloud Storage bucket
6) Click deploy

### Expected result

I expect there to be a working KFP instance that allows me to run the saple Chicago Taxi dataset pipeline. Instead I receive this error: `Error: failed to retrieve list of pipelines. Click Details for more information.` 

### Materials and Reference

@Bobgy , I messaged you in the Slack channel on this.

The GCP walkthrough for this option is available here: https://cloud.google.com/ai-platform/pipelines/docs/setting-up#full-access 
#4356 #3332 
---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by Bobgy** [comment]
After some offline troubleshooting, found that
> Artifact storage Cloud Storage bucket: With managed storage, Kubeflow Pipelines stores pipeline artifacts in a Cloud Storage bucket. Specify the name of the bucket you want Kubeflow Pipelines to store artifacts in. If the specified bucket doesn't exist, the Kubeflow Pipelines deployer automatically creates a bucket for you in the us-central1 region.

note the bucket name inputted should NOT contain "gs://" prefix.

**Comment by bdoohan-goog** [comment]
@Bobgy , that fixed the issue. Thank you! It would be great if the KFP setup UI had more proactive errors, alerting the user as soon as they enter in the "gs://". Thank you once again!
