### ISSUE TITLE
Can the workflow controller be upgraded to argo v2.12.6?

### ISSUE THREAD

**Issue by midhun1998** [kubeflow/pipelines#5511]
Hi,
We are looking to upgrade the workflow controller to v2.12.6 based on #4553 . The current version of Argo workflow controller installed is v2.3 which comes with Kubeflow v1.2. The main reason to upgrade is Argo v2.3 only outputs very few workflow metrics.
Will there be any incompatibilities? If no, will changing the image be enough or should we upgrade any other components? Please guide @Bobgy .(#5232 )

/kind question

**Comment by Bobgy** [comment]
Hi @midhun1998, kubeflow 1.3 is about to release and argo workflow controller has been upgraded to 2.12.9

**Comment by midhun1998** [comment]
Thanks for letting me know @Bobgy . I'm really excited for Kubeflow 1.3 🎉. But we are planning to upgrade to Kubeflow only post some analysis(Could take a while🙁) . Meanwhile, is it possible to upgrade the current workflow controller as asked in my first question?

**Comment by Bobgy** [comment]
Not sure, I think you should be good. Have a try?

**Comment by midhun1998** [comment]
Cool. Will test it and update here incase someone else is in the same situation. 👍🏻

**Comment by midhun1998** [comment]
Haven't done it. Found an alternative way to achieve what we wanted. Closing this.
