### ISSUE TITLE
Missing Markdown support: horizontal rule, emojis

### ISSUE THREAD

**Issue by jackwhelpton** [kubeflow/pipelines#5512]
### Environment

*  KFP version: 1.0.1

### Steps to reproduce

Output a markdown artifact containing the missing features: a horizontal rule, and an emoji, e.g. `:warning:`

```python
        metadata = {
          "outputs": [
          {
            "storage": "inline",
            "source": "line1\n---\n:warning: Item had multiple genre labels",
            "type": "markdown",
          }]
        }
```

### Expected result

The Visualizations tab and Run output should render the horizontal rule and emoji:

line1
---
⚠️ Item had multiple genre labels

Instead, the original markup code is visible:

`line1 --- :warning: Item had multiple genre labels`

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by jackwhelpton** [comment]
As a workaround, using the character ⚠️ directly works.

**Comment by jackwhelpton** [comment]
I'm expanding this ticket as I find other missing markdown features: let me know if each one should be spun off as a separate ticket.

**Comment by zijianjoy** [comment]
Hello @jackwhelpton , feel free to add more missing markdown features in this ticket. We can update the issue description to match the scope as well. Ideally we should use another markdown render which can fit all markdown feature requests. 

https://github.com/kubeflow/pipelines/blob/226079338b38b85ae3b63a5e289c6ca0cd9511d0/frontend/src/components/viewers/MarkdownViewer.tsx#L111-L114
