### ISSUE TITLE
[bug] Lexical error in pipeline samples

### ISSUE THREAD

**Issue by difince** [kubeflow/pipelines#5518]
### What steps did you take
It is just a lexical error in pipeline sample file - [Data passing in python components - Files.py](https://github.com/kubeflow/pipelines/blob/d79071c0bef19442483abc101769a0d893e72f42/samples/tutorials/Data%20passing%20in%20python%20components/Data%20passing%20in%20python%20components%20-%20Files.py) 
> Small lists, dictionaries and JSON structures are fine, but keep an eye on the size and consider switching to file-based data passing methods **taht** are more suitable for bigger data (more than several kilobytes) or binary data.

### What did you expect to happen:
**taht** to be written correctly: that
### Labels

/area samples 

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by zijianjoy** [comment]
Updated the text with https://github.com/kubeflow/pipelines/commit/acc2c2aaafa6c3a6b0cc90eef5d61cfd43440aef
