### ISSUE TITLE
[feature] GCP Cloud ML Engine Component Support Local Training

### ISSUE THREAD

**Issue by Gevorg-Minasyan** [kubeflow/pipelines#5519]
### Feature Area

[GCP Components](https://github.com/kubeflow/pipelines/tree/master/components/gcp/ml_engine)

### What feature would you like to see?

Support to run [AI Platform training job locally.]( https://cloud.google.com/sdk/gcloud/reference/ml-engine/local/train)

### What is the use case or pain point?

A pain point is the pipeline testing part, which took a long time to test changes by running the pipeline in GCP, which adds additional cost when every time spinning up the new machine during the training component development phase. After the local training support feature, developers can do it fully locally and once the pipeline is ready they can upload it in GCP.

### Is there a workaround currently?
Writing training component from scratch.

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by Bobgy** [comment]
/assign @Bobgy 
sounds like an useful idea

**Comment by Ark-kun** [comment]
What do you think about using custom containers for training?
It's easy to run them locally and there is beta support for running them on GCP: https://cloud.google.com/ai-platform-unified/docs/training/create-custom-job#create_custom_job-gcloud

**Comment by Gevorg-Minasyan** [comment]
I'm not sure if I clearly understand custom containers for training usage in KFP. If we are intended to create a custom training job independent from the kubeflow pipeline, then it would be a good choice, however, the local e2e KFP pipeline development and before GCP upload testing gap still will be there.
