### ISSUE TITLE
Kubeflow crashing

### ISSUE THREAD

**Issue by prasadkyp7** [kubeflow/pipelines#5529]
when we run many pipelines(more than 500) using KFP-API , the entire kubeflow and UI is crashing. when i look back in kubernetes its showing this error-failed to create a watcher for certificate files: inotify_init: too many open files. We are not able to track/understand this error. But this crash is happening because of running many pipelines. Any help would be greatly appreciated.

**Comment by zijianjoy** [comment]
Hello @prasadkyp7 ,

Would you like to provide more detail on the deployment environment?

Are.you using Full Kubeflow deployment, or KFP standalone? What kind of cloud provider you are using?

Versioning questions:
1. How do you deploy Kubeflow Pipelines (KFP)?
2. KFP version:
3. KFP SDK version:

What are the detailed steps to reproduce this issue?

**Comment by prasadkyp7** [comment]
We are using Full kubeflow deployment running on AWS cloud.
Build version is not showing for us in Kubeflow UI (Ui shows as build version:dev_local)

Steps to reproduce:

1.create a pipeline using kfp.compiler.Compiler().compile(pipeline,'pipeline.zip').
2. Upload the pipeline zip file using kubeflow UI.
3. Create a run by using kfp api 
4. payload for api-
payload={
   "name":"kfp_api_run",
   "pipeline_spec":{
      "pipeline_id":"pipeline id of this pipeline",
       "parameters":[{
           "name":"p",
           "value":"json value input"
       }
       ]
    }
}

**Comment by prasadkyp7** [comment]
Please provide the solution asap

**Comment by zijianjoy** [comment]
I am suspecting this issue is related to resource limitation (or open file cap), because you mentioned that this error happens when there are many pipelines. But I don't have access to AWS, so cannot reproduce this issue. 

Can you check your max file descriptors on AWS Kubernetes?

**Comment by prasadkyp7** [comment]
The crash is not because of resource limitation . we have large nodes in AWS cluster. 

The crash is because KUBEFLOW Is not deleting the pods in EKS even after the Pipelines are success. we tried deleting the pods using pipeline_conf.set_ttl_seconds_after_finished(seconds=10) . But this is not working.

Can you please tell us how to delete the pods of pipeline on its own after they get succeed .

This is big problem with kubeflow. Need an urgent guidance on this

**Comment by zijianjoy** [comment]
You can delete the pipeline runs from KFP UI: First `Archive` the run, then `Delete` the run: 
![archive](https://user-images.githubusercontent.com/37026441/117100770-74d03a80-ad29-11eb-863f-92412f4c07c0.png)

![delete](https://user-images.githubusercontent.com/37026441/117100774-7994ee80-ad29-11eb-9c00-2f3611338f1b.png)

Alternatively, you can also use the Python SDK to delete the run. API documentation is in https://kubeflow-pipelines.readthedocs.io/en/stable/source/kfp.server_api.html#kfp_server_api.api.run_service_api.RunServiceApi.delete_run


After you delete the run, the pods associated with this run will be deleted.

**Comment by prasadkyp7** [comment]
i have already tried both of them.

But the problem is, in real time we are running thousands of pods and to delete using kfp.client.runs.delete_run(run_id) we need run id which is unique and is determined by kubeflow but not us which makes very difficult to delete the thousands of runs manually.

Is there a way to delete the runs/pods on its own after the completion of run?

**Comment by Ark-kun** [comment]
There is a difference between Pods and runs. Runs are not Kubernetes objects and are just stored in the DB. I'm not sure your problem is caused by runs. Are you sure the runs are the problem, not Pods and Workflows?

AFAIK, there is some TTL on Pods as I see them removed after pretty short time.

**Comment by IronPan** [comment]
FYI You can set a different TTL to garbage collect the pod. By default it's 1 day
https://github.com/kubeflow/pipelines/blob/5d0f3a3d32f35d3dbca9cd27f4ee476e87f6d41e/manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml#L517

**Comment by prasadkyp7** [comment]
Each Run from Kubeflow is creating a pod in a kubernetes. When a Run completes, the pod in kubernetes is not deleted and is staying there in successful state.  So, if we delete the Run from kubeflow it will delete both the run details and pod as well.
My problem here is as 1000's number of success/ failed pods/ run are staying and not deleted-kubeflow is crashing.

So is there a way in kubeflow to delete 1000's of runs on its own after completion.

i tried to set TTL using pipeline_conf.set_ttl_seconds_after_finished(seconds=10). But its not working , it is not deleting the pods.

Please let me know a way to delete the runs after completion. This is big blocker for us in using kubeflow.

**Comment by prasadkyp7** [comment]
any update on how to delete the runs on its own after completion?

**Comment by prasadkyp7** [comment]
when we run thousands of jobs daily without deleting the runs, the details of run which is stored in the table is over loaded and we are not able to create the runs with the error.Failed to create a new run.: InternalServerError: Failed to store run x9hqb to table: Error 1114: The table 'run_details' is full"}]}


so we have to delete the runs on its own after completion, i tried to set TTL using pipeline_conf.set_ttl_seconds_after_finished(seconds=10). it didnot work.

There is no documentation or resource available to delete the runs automatically, this is a big problem and big blocker. 

Really Appreciate if you help us in providing a solution to this probelm asap
