### ISSUE TITLE
load_pipeline_from_file

### ISSUE THREAD

**Issue by iuiu34** [kubeflow/pipelines#5534]
Hi,
you can create components as a yaml, and load them with `load_component_from_file`.

Why there's not the same feature with pipelines? 
Instead of using `@dsl.pipeline`, define the pipeline also with a yaml, and then just having a py script with a `load_pipeline_from_file` function. Or even better, pass `--pipeline-file` as a parameter when uploading the pipeline to kubeflow?

Note: this is not to be confused with the static yaml that is upload to gcp kubeflow. This pipeline.yaml will contain same info as pipeline.py and then will generate the static.yaml

**Comment by zijianjoy** [comment]
@luiu1234 What is the reason for preferring yaml over python for loading pipeline from file? We are currently heading towards the direction of supporting pipeline construction using python only. 

/cc @chensun

**Comment by Iuiu1234** [comment]
Hi @zijianjoy ,
reason is consistency.
For me is (a little bit) inconsistent to use use yaml in one side (features) & py in the other (pipelines).

But if you're moving to py in both sides then that's fine by me.

**Comment by chensun** [comment]
Sorry, I missed this. Thank you @zijianjoy for bringing this to my attention.

> We are currently heading towards the direction of supporting pipeline construction using python only.

Just to clarify, Python has always been the only option to write pipelines. Component yaml is designed for authoring  components only but never the pipelines. 

> Note: this is not to be confused with the static yaml that is upload to gcp kubeflow. This pipeline.yaml will contain same info as pipeline.py and then will generate the static.yaml

@Iuiu1234, let's think about what actions you may take between loading this pipeline.yaml and generating the static.yaml (which is an Argo workflow template yaml). There's none. 
As of today, you cannot (re)use a pipeline in another pipeline definition (this is actually something we're going to explore soon). So for now the only available use case after loading a pipeline is to submit it for run (or upload it for later run). In that sense, we are doing exactly what we should do -- you can load the compilation result but not some intermediate representation of a pipeline. Does that make sense?

**Comment by chensun** [comment]
> For me is (a little bit) inconsistent to use use yaml in one side (features) & py in the other (pipelines).

Agree that inconsistence exists today. Also keep in mind that there're difference between component and pipeline as of today. When you write a component using yaml, you are only defining a template, like you're defining a function. But the pipeline contains how do you use such templates -- which arguments you passed to call a function. The current component yaml is not capable of express the later. In addition, it cannot express `dsl.ParallelFor`, `dsl.Condition`, for instance.

> But if you're moving to py in both sides then that's fine by me.

Yes, we're evaluating making Python the choice for both sides.
