### ISSUE TITLE
pipeline_conf.set_ttl_seconds_after_finished(seconds=10) NOT WORKING

### ISSUE THREAD

**Issue by prasadkyp7** [kubeflow/pipelines#5545]
*  How did you deploy Kubeflow Pipelines (KFP)?
**_WE are using full kubeflow deployment on AWS Cloud_**
*  KFP version: 

Kubeflow UI is not showing us any version
*  KFP SDK version: 

kfp                      1.4.0
kfp-pipeline-spec        0.1.6
kfp-server-api           1.4.1

### Steps to reproduce

1.create a pipeline code
2. set the ttl using pipeline config
pipeline_conf = kfp.dsl.PipelineConf()
x=pipeline_conf.set_ttl_seconds_after_finished(seconds=10)
3. create the pipline using 
 kfp.compiler.Compiler().compile(loadTrain_pipeline,'loadTrain_pipeline_2.zip',pipeline_conf=x) and upload it in UI.
4. TEST this pipeline by creating a run.

EXPECTED RESULT:
As per setting TTL to 10 seconds , the pods created must be deleted after 10 sec. 
But its not deleting the pods, in my case i am creating 1000's pods and as i am not deleting the successful pods Kubeflow UI is crashing.

**Comment by NikeNano** [comment]
I think [this issue](https://github.com/kubeflow/pipelines/issues/5234) could guide you to a solution @prasadkyp7

**Comment by Bobgy** [comment]
+1 to NikeNano's answer

**Comment by Bobgy** [comment]
@prasadkyp7 can you add more details?
What config did you set? What version are you using etc?

Ref: https://github.com/kubeflow/pipelines/issues/5234#issuecomment-805599988 this is my recommendation

**Comment by prasadkyp7** [comment]
@Bobgy i tried as you suggested , it worked.
But the problem here is . TTL is deleting the pods but not the run details. Because of this , run details SQL Table is becoming full.
when i tried to delete the pipelines using API it deletes both pods and run details.  we want TTL to delete both pod and run details. can you suggest a way to do this ?

**Comment by Bobgy** [comment]
I see, not deleting runs in the DB is the expected behavior.
We don't have TTL feature for the DB. So far, we recommend building a Cron pipeline/job that calls KFP API to list, filter old runs and GC them. Do you see any blockers in that direction?
