### ISSUE TITLE
[backend] Local install: proxy-agent error "Could not resolve host: metadata.google.internal"

### ISSUE THREAD

**Issue by soleares** [kubeflow/pipelines#5553]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
```
# Install k3d kubectl
brew install k3d kubectl
k3d cluster create kubeflow
k3d kubeconfig merge ml-kubeflow --kubeconfig-switch-context

# Install Kubeflow Pipelines
export PIPELINE_VERSION=1.5.0
kubectl apply -k "github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=$PIPELINE_VERSION"
kubectl wait --for condition=established --timeout=60s crd/applications.app.k8s.io
kubectl apply -k "github.com/kubeflow/pipelines/manifests/kustomize/env/dev?ref=$PIPELINE_VERSION"
```
*  KFP version: 
1.5.0
*  KFP SDK version: 
N/A

### Steps to reproduce

1. Install using steps above on MacOS w/ latest Docker running.
2. `kubectl get pods -A`
3. `proxy-agent-<suffix>` pod shows Error status
```
kubeflow      proxy-agent-<suffix>                        0/1     CrashLoopBackOff   13         49m
```
4. `kubectl logs proxy-agent-<suffux> -n kubeflow` shows the following error:
```
++ curl http://metadata.google.internal/computeMetadata/v1/instance/zone -H 'Metadata-Flavor: Google'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: metadata.google.internal
```

### Expected result

`proxy-agent-<suffix>` pod shows Running status

### Materials and Reference

I've seen this happen in versions 1.4.1 and 1.5. I would guess there's something GCP specific in the `dev` env manifest but I'm not sure. 
```
kubectl apply -k "github.com/kubeflow/pipelines/manifests/kustomize/env/dev?ref=$PIPELINE_VERSION"
```

I don't remember this happening in 1.3 and I think the manifest was different in the 1.3 install instructions and it used the `platform-agnostic-pns` env.
```
kubectl apply -k "github.com/kubeflow/pipelines/manifests/kustomize/env/platform-agnostic-pns?ref=$PIPELINE_VERSION"
```
---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by Bobgy** [comment]
Yes, for local install, you should use
```
kubectl apply -k "github.com/kubeflow/pipelines/manifests/kustomize/env/platform-agnostic-pns?ref=$PIPELINE_VERSION"
```

we should update documentation in KFP standalone

**Comment by Bobgy** [comment]
Actually, you should follow https://www.kubeflow.org/docs/components/pipelines/installation/localcluster-deployment/ to deploy locally

**Comment by soleares** [comment]
Thanks @Bobgy, you are correct. I followed the local guide for 1.3 but for some reason with 1.5 I used the incorrect manifest.
