### ISSUE TITLE
[Doc] Update "Visualize Results in the Pipelines UI" page

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#5564]
https://www.kubeflow.org/docs/components/pipelines/sdk/output-viewer/

**Comment by zijianjoy** [comment]
Update area:

```
  with open('/mlpipeline-ui-metadata.json', 'w') as f:
    json.dump(metadata, f)
```

**Comment by Bobgy** [comment]
Example of outputting mlpipeline-ui-metadata in component yaml component: https://github.com/kubeflow/pipelines/blob/d362cab2046b92efa5f015c6a980bc9371b4b63b/components/tensorflow/tensorboard/prepare_tensorboard/component.yaml

Example of outputting mlpipeline-ui-metadata in python lightweight component -- option 1 as return value:
https://github.com/kubeflow/pipelines/blob/d9c019641ef9ebd78db60cdb78ea29b0d9933008/samples/core/lightweight_component/lightweight_component.ipynb

we don't have a good example for emitting mlpipeline-ui-metadata with OutputPath in lightweight component, I think we need an example. For OutputPath, an example is https://github.com/kubeflow/pipelines/blob/d9c019641ef9ebd78db60cdb78ea29b0d9933008/components/dataset_manipulation/split_data_into_folds/in_CSV/component.py#L16
