### ISSUE TITLE
[frontend] The sort, filter of artifact does not work

### ISSUE THREAD

**Issue by capri-xiyue** [kubeflow/pipelines#5565]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)? Kubeflow Pipeline Standalone with GCP

*  KFP version: 1.5.0

### Steps to reproduce
Submit a pipeline which will generate artifatcs, then submit the pipeline run.
Go to the UI which shows the artifact list, click  `Created At` to sort by created time.  In addition, the filter also does not work.

### Expected result

The sort behavior should work

### Materials and Reference

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by capri-xiyue** [comment]
![Uploading Screen Shot 2021-04-29 at 11.33.56 AM.png…]()

**Comment by capri-xiyue** [comment]
<img width="1192" alt="Screen Shot 2021-04-29 at 11 33 56 AM" src="https://user-images.githubusercontent.com/52932582/116601525-763fd400-a8df-11eb-86aa-9be8708b2715.png">

**Comment by Bobgy** [comment]
Duplicate of https://github.com/kubeflow/pipelines/issues/3226
