### ISSUE TITLE
remove duplicate volumes in the DSL

### ISSUE THREAD

**Issue by gaoning777** [kubeflow/pipelines#557]
Currently, DSL adds a volume for each container op that has a volume. For example, the current samples are compiled into a yaml with multiple gcp secret volumes. The DSL should detect the duplicate ones and only add one.

**Comment by gaoning777** [comment]
solving it in https://github.com/kubeflow/pipelines/pull/558

**Comment by Ark-kun** [comment]
Duplicate of https://github.com/kubeflow/pipelines/issues/494

**Comment by gaoning777** [comment]
Close the issue in favor of the the other.
