### ISSUE TITLE
[backend] pipelines upload failes without parameters

### ISSUE THREAD

**Issue by padrian2s** [kubeflow/pipelines#5576]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?

deploy manually (kustomize build)

*  KFP version: 
KFP 1.3

*  KFP SDK version: 
kfp                      1.4.0
kfp-pipeline-spec        0.1.7
kfp-server-api           1.5.0

### Steps to reproduce

upload xgboost sample pipeline, which has no pipeline input parameters

{"error_message":"Error creating pipeline: Create pipeline failed: Failed to get parameters from the workflow: InvalidInputError: Failed to parse the parameter.: error unmarshaling JSON: json: cannot unmarshal array into Go value of type v1alpha1.Workflow","error_details":"Error creating pipeline: Create pipeline failed: Failed to get parameters from the workflow: InvalidInputError: Failed to parse the parameter.: error unmarshaling JSON: json: cannot unmarshal array into Go value of type v1alpha1.Workflow"}

### Expected result

TBD

### Materials and Reference

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by NikeNano** [comment]
I don`t get this issue on the latest version of Kubeflow pipelines.

**Comment by padrian2s** [comment]
I use the default XGB after KF install, the one that is already published into DB.

**Comment by Bobgy** [comment]
I vaguely remember this is already fixed in later KFP version
