### ISSUE TITLE
can metacontroller be upgraded to latest version from V0.3.0

### ISSUE THREAD

**Issue by orugantichetan** [kubeflow/pipelines#5578]
/kind question
/kind/question

can metacontroller be upgraded to latest version from V0.3.0
from v1.2.0 metacontroller have support for distroless image .

**Comment by zijianjoy** [comment]
We will upgrade metacontroller and investigate if there is any breaking change in this major version bump.

Another option is to remove metacontroller, and use kubeoperator or helm instead.

**Comment by juliusvonkohout** [comment]
The following is possible. If you are interested in a merge request please tell me.

I 
1. upgraded to 2.0.4 
2. removed insane permissions (e.g. privileged root container) 
3. removed insane cpu and memory ressources (4 cores 4 GB)
4. Added networkattachmentdefinitions for rootless istio-cni on Openshift and updated the profile-controller accordingly

Sadly it still needs cluster admin-rights, but mabye someone has an idea on how to restrict it.
