### ISSUE TITLE
In metacontroller statefulset container securitycontext block  allowPrivilegeEscalation and privileged are set to true . Does the controller container really need those privileges 

### ISSUE THREAD

**Issue by orugantichetan** [kubeflow/pipelines#5579]
/kind question
/kind/question

metacontroller statefulset container securitycontext block  allowPrivilegeEscalation and privileged are set to true . Does the container really need those privileges 
In metacontroller repo those privileged permissions are not set  [https://github.com/metacontroller/metacontroller/blob/v0.3.0/manifests/metacontroller.yaml](url)

**Comment by Bobgy** [comment]
@orugantichetan can you raise the issue in metacontroller repo instead?
