### ISSUE TITLE
[backend] metadata_execution_id is empty in ExecutionOutput of cache record due to race condition

### ISSUE THREAD

**Issue by ekesken** [kubeflow/pipelines#5584]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?

We deploy it via ArgoCD.

*  KFP version: 1.0.4

Two components involved in issue:
* ml-pipeline/metadata-writer:1.0.4
* ml-pipeline/cache-server:1.0.4

### Steps to reproduce

This is a race condition between metadata-writer and cache-server, so not easy to re-produce, but we observe it quite frequently.

If `cache-server/watcher` gets pod completed event before `metadata_writer` can inject the `pipelines.kubeflow.org/metadata_execution_id` label, metadata link becomes missing for the cache record forever.

### Expected result

Expecting `pipelines.kubeflow.org/metadata_execution_id` label values in ExecutionOutput field of cache record to reflect the real id, instead of an empty value, so that we can continue being able to see the linked metadata in UI for re-runs of cached steps later on.

### Materials and Reference

Both components watches for pod events to take action, see:

https://github.com/kubeflow/pipelines/blob/1.0.4/backend/src/cache/server/watcher.go#L30-L91
https://github.com/kubeflow/pipelines/blob/1.0.4/backend/metadata_writer/src/metadata_writer.py#L129-L258

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by Ark-kun** [comment]
I understand the issue.
I wonder how reliable `metadata_execution_id` is. Have you seen any cases where Metadata Writer failed to set it?

We're a little bit hesitant to introduce a dependency between cache server and metadata writer services.

**Comment by ekesken** [comment]
> I wonder how reliable metadata_execution_id is.

I believe instead of purely relying on `metadata_execution_id`, we should add another annotation in `metadata-writer` when create event arrives for the pod, like `pipelines.kubeflow.org/metadata_enabled`, if it's not a tfx job it should be set to true, and in cache-server it should wait until metadata_execution_id gets filled for the metadata enabled pods.

> Have you seen any cases where Metadata Writer failed to set it?

we had issues from time to time, but I can't give any concrete example/scenario, we were just mitigating the problems by deleting metadata-grpc and metadata-writer pods blindly without checking for a root cause.

> We're a little bit hesitant to introduce a dependency between cache server and metadata writer services.

But this has a serious impact for users, no? if this metadata linking is broken in the cache entry, they won't be able to see anything in metadata tab in UI for re-executions of the same step.

**Comment by Bobgy** [comment]
The issue is avoided in v2 compatible and v2 caching design.
See bit.ly/kfp-v2-compatible and bit.ly/kfp-v2
