### ISSUE TITLE
Managed storage default sql username is not root as described

### ISSUE THREAD

**Issue by halvgaard** [kubeflow/pipelines#5588]
@Svendegroote91 Sorry for the late reply, reading through your description, it sounds like
> database username & password left empty to default to root user without password.

this part is wrong, you need to type `root` into database username, it's not the default when you leave it to empty.

_Originally posted by @Bobgy in https://github.com/kubeflow/pipelines/issues/4973#issuecomment-768226895_

The GCP AI platform Pipelines description for managed storage also says that if username is empty then it defaults to 'root' but the default is an empty string at least when adding a password. I had to type in 'root' to make it work.

**Comment by halvgaard** [comment]
This issue gives the same errors as found here: https://stackoverflow.com/questions/66600365/gcp-ai-platform-pipelines-kfp-use-managed-storage-cloudsqlproxy-issue#

**Comment by Bobgy** [comment]
Thanks for reporting! This is a sub problem of https://github.com/kubeflow/pipelines/issues/5717.
Let's track this issue in the more generic issue
