### ISSUE TITLE
Unable to artifact output files in aws s3

### ISSUE THREAD

**Issue by swamat** [kubeflow/pipelines#5597]
### What steps did you take

I installed kubeflow v1.2 in AWS following official documentation -https://www.kubeflow.org/docs/distributions/aws/pipeline/

### What happened:
Created notebook server and executed kubeflow pipeline. AM able to view artifacts in UI stored in minio loation. Created secret.yaml file 
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: kubeflow
type: Opaque
data:
  AWS_ACCESS_KEY_ID: <YOUR_BASE64_ACCESS_KEY>
  AWS_SECRET_ACCESS_KEY: <YOUR_BASE64_SECRET_ACCESS>

Updated deployment ml-pipeline-ui to use AWS credential environment variables by running kubectl edit deployment ml-pipeline-ui -n kubeflow.

### What did you expect to happen:
Kubeflow to store the files in s3

### Environment:
AWS-ubuntu eks cluster

*  How do you deploy Kubeflow Pipelines (KFP)? --https://www.kubeflow.org/docs/distributions/aws/pipeline/

*  KFP version: 1.2

*  KFP SDK version: 

### Anything else you would like to add:
After applying secrets yaml am able to connect to s3 to read and write files using use_aws_secret but artifacts are not getting logged automatically in s3. Artifacts are logged in minio alone. How to log artifacts in s3

### Labels

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by swamat** [comment]
Can someone please help on this

**Comment by swamat** [comment]
Update: My pipeline is running on namespace 'admin'. created secret file for namespace admin and kubeflow.
Updated deployment ml-pipeline-ui in kubeflow namespace to use aws-secret. Still in kubeflow UI am getting the below error:

Failed to get object in bucket 'bucketname' at path README.md: S3Error: Access Denied

**Comment by swamat** [comment]
Can someone please help on this

**Comment by Bobgy** [comment]
/cc @DavidSpek 
In case you want to comment on this

**Comment by DavidSpek** [comment]
@Bobgy Thanks for the ping. Our deployment for AWS includes a couple different methods to integrate S3 and Pipelines, so I'll see if I can spin up a test cluster with a similar implementation to this one and replicate the behavior.

I did notice this behavior while I was experimenting with using upstream Argo Workflows. I doubt it is related, but I haven't looked into it yet so I thought it might be useful to mention here as well.

**Comment by swamat** [comment]
Can someone help on this

**Comment by swamat** [comment]
I am able to artifact files and logs in s3 now after following this https://github.com/e2fyi/kubeflow-aws/tree/master/pipelines
