### ISSUE TITLE
[backend] Cache Server is unable to deploy with external database using SSL

### ISSUE THREAD

**Issue by maganaluis** [kubeflow/pipelines#5598]
### Environment

Using Kustomize.

*  KFP version: 

KFP 1.3

*  KFP SDK version: 

KFP 1.4

### Steps to reproduce

We are unable to deploy the Cache Server with an external databases which uses SSL. In order to setup the correct parameters, the configuration should allow for extra parameters. 

### Expected result

We should be able to pass extra parameters to the Cache Server deployment: 

```
...
          - name: DBCONFIG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: password
          - name: DBCONFIG_EXTRAPARAMS
            value: '{"tls": "true"}'
          - name: NAMESPACE_TO_WATCH
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        args: ["--db_driver=$(DBCONFIG_DRIVER)",
               "--db_host=$(DBCONFIG_HOST_NAME)",
               "--db_port=$(DBCONFIG_PORT)",
               "--db_name=$(DBCONFIG_DB_NAME)",
               "--db_user=$(DBCONFIG_USER)",
               "--db_password=$(DBCONFIG_PASSWORD)",
               "--db_extra_params=$(DBCONFIG_EXTRAPARAMS)",
               "--namespace_to_watch=$(NAMESPACE_TO_WATCH)",
              ]
        imagePullPolicy: Always
...
```

### Materials and Reference

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by NikeNano** [comment]
Can we consider this fixed after merging https://github.com/kubeflow/pipelines/pull/5599 @maganaluis ?

**Comment by maganaluis** [comment]
@NikeNano Yes, I missed tagging this issue to the PR.
