### ISSUE TITLE
Error: persistentvolumeclaim "azure-managed-disk" not found

### ISSUE THREAD

**Issue by pangshengwei** [kubeflow/pipelines#5605]
**Question:**

I've followed the [azure end-to-end pipeline](https://www.kubeflow.org/docs/distributions/azure/azureendtoend/) tutorial, but am getting this error when running an experiment, does anyone know what might be the problem?

![image](https://user-images.githubusercontent.com/19318871/116953966-34d56d00-acc1-11eb-9708-cff2fd18f935.png)

I've run `kubectl apply -f pvc.yaml` but somehow I dont see the volume when I do `kubectl get pvc`...am I supposed to?

![image](https://user-images.githubusercontent.com/19318871/116954078-8bdb4200-acc1-11eb-9ede-f3a5449d67a9.png)

I also dont understand why I am unable to delete the PVC

![image](https://user-images.githubusercontent.com/19318871/116955260-9ea34600-acc4-11eb-8124-03148a28e7ec.png)

PVC.yaml

![image](https://user-images.githubusercontent.com/19318871/116956655-5e45c700-acc8-11eb-9a55-c47525b6d72b.png)

pipeline.py

![image](https://user-images.githubusercontent.com/19318871/116956626-4f5f1480-acc8-11eb-8eff-8fdb3ea1e941.png)

**Comment by Bobgy** [comment]
/assign @aronchick 
Do you have a good contact for this issue? This is one of the azure tutorials

**Comment by berndverst** [comment]
`kubectl delete pvc azure-managed-disk --namespace kubeflow`

If you look at the PVC's YAML you'll see it is created in namespace `kubeflow` which is not the default namespace and hence you aren't actually querying for.

https://github.com/kubeflow/examples/blob/master/pipelines/azurepipeline/kubernetes/pvc.yaml#L5

**Comment by berndverst** [comment]
In general the problem is that the PVC must exist in the same Kubernetes namespace as your Kubeflow pipeline. Just edit the PVC.yaml and change the namespace to wherever you are running your pipeline (probably the default namespace), then apply.
