### ISSUE TITLE
ERROR:Exception when calling CoreV1Api->create_namespaced_pod: (404) Reason: Not Found

### ISSUE THREAD

**Issue by jocelynbaduria** [kubeflow/pipelines#5620]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)? In GCP AI Platform

*  KFP version: : kfp-1.0.0
 
*  KFP SDK version: 

### Expected result

# Target images for creating components should be added in GCP container registry.
PREPROCESS_IMG = 'gcr.io/%s/ms-coco/preprocess:latest' % PROJECT_NAME
TOKENIZE_IMG = 'gcr.io/%s/ms-coco/tokenize:latest' % PROJECT_NAME
TRAIN_IMG = 'gcr.io/%s/ms-coco/train:latest' % PROJECT_NAME
PREDICT_IMG = 'gcr.io/%s/ms-coco/predict:latest' % PROJECT_NAME

Should update the container registry in GCP 
- It is empty only the added file is not there.
![Screen Shot 2021-05-08 at 5 56 41 PM](https://user-images.githubusercontent.com/62075076/117557352-d4c72980-b026-11eb-8095-d80c4271a5e3.png)

### Materials and Reference

 sample code - https://github.com/kubeflow/pipelines/blob/master/samples/contrib/image-captioning-gcp/Image%20Captioning%20TF%202.0.ipynb
I run it in GCP Kubeflow AI Platform notebook.
---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by zijianjoy** [comment]
@Ark-kun Hello Alexey, would you like to look at this example? Thank you!
