### ISSUE TITLE
New kfp sdk release (1.5.0)

### ISSUE THREAD

**Issue by HenryW95** [kubeflow/pipelines#5635]
The new use_k8s_secret function in the kfp_server_api sdk is very useful but it's not yet released in the kfp library (https://pypi.org/project/kfp/). Is there a plan for when the next release will be? Thanks much!

**Comment by DavidSpek** [comment]
"We're planning an SDK release this week. Probably have an RC version out mid-week at least."
From: https://github.com/kubeflow/pipelines/issues/5254#issuecomment-835991598

**Comment by HenryW95** [comment]
Thank you! I see it's been released now
