### ISSUE TITLE
[frontend] File format / path of the TFX artifacts from TFDV should be updated

### ISSUE THREAD

**Issue by jiyongjung0** [kubeflow/pipelines#5638]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)? - GCP Cloud AI Pipelines
*  KFP version: 1.4.1

### Steps to reproduce

1. Use TFX taxi template to create a pipeline
2. Add StatisticsGen component and run the pipeline.(Step 5)
3. Click "Visualizations" of `StatisticsGen` component after the run finished successfully.
   - This will result in `OSError: Invalid input path gs://jiyongjung-gke-kubeflowpipelines-default/tfx_pipeline_output/my_pipeline/StatisticsGen/statistics/257/eval/stats_tfrecord.`.

### Expected result

Visualization of TFDV analysis.

### Materials and Reference

TFX changed the file path and format of several artifact types recently. For example, [cl for statistics artifact](https://github.com/tensorflow/tfx/commit/2a1a00a675760e6c96887aa59ba67a91e0f8a4cc). But it seems like it is not propagated to KFP. [Related code](https://github.com/kubeflow/pipelines/blob/d9c019641ef9ebd78db60cdb78ea29b0d9933008/frontend/src/lib/OutputArtifactLoader.ts#L276-L327).

TFX started to record artifacts' [generated version as custom properties](https://github.com/tensorflow/tfx/blob/c78ed9678f790a55b444d8f4c57f584f3b3a4d53/tfx/types/artifact_utils.py#L36), so we might be able to use it to support both versions.

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by jiyongjung0** [comment]
FYI, @1025kb

**Comment by PyoJunCode** [comment]
Still same

**Comment by Bobgy** [comment]
@zijianjoy did you already fix this in your recent PR?

**Comment by zijianjoy** [comment]
Yes the change has been applied in https://github.com/kubeflow/pipelines/pull/6061/files#diff-388538ba7580c2729c010006b01837a9dbf9a04702c185970d025ab5dbcd22ba.
