### ISSUE TITLE
[feature] Add PVC File Browser to Viewer CRD

### ISSUE THREAD

**Issue by DavidSpek** [kubeflow/pipelines#5651]
### Feature Area
/area backend

### What feature would you like to see?

Add a `PVC Viewer`/`File Browser` spec to the Viewer controller.

### What is the use case or pain point?

This feature would allow people to launch a "File Browser" pod, which allows them to easily drag and drop files into a PVC or download files and folders present in a PVC. For KFP users, this can be useful if a pipeline step produces some form of data in a PVC that the user would like to easily download. The same CR would then be used to extend the Volumes Web App with a button that allows people to start a "File Browser" pod to easily upload and download file to and from their PVCs (most likely for the PVCs used with notebook servers). I currently have built a dedicated controller for this, but given that the pipelines viewer CRD is built to be extendable I thought it would make sense to add it to an existing controller. A demo of this functionality can be seen below.

![vwa-pvcviewer-demo](https://user-images.githubusercontent.com/28541758/118364973-10b83c80-b59b-11eb-9554-c373178c1dbe.gif)

### Is there a workaround currently?

There currently is no easy way for users to upload and download data to and from their PVCs, which is a large hurdle for people that have local data that they would like to use within their notebooks or pipelines.

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by jtfogarty** [comment]
👍🏽
This will come in very handy for my user!!

**Comment by zulissi** [comment]
This would also be very helpful for us. Especially when trying to figure out which PVCs can be safely cleaned up.

**Comment by karlschriek** [comment]
Looks great! Really handy feature and very much in line with the sort of functionality our our clients are looking for. What would need happen in order to implement this?

**Comment by blairdrummond** [comment]
This approach would be very useful for us. It would also help with a related functionality; ultimately artifacts that researchers create within these notebooks will need to be extracted out and sent to a vetting team to assess possible disclosures. This strategy would make it really easy for us to build a workflow for that use-case.

**Comment by ca-scribner** [comment]
Yeah this would definitely be helpful.  Having better support for this would make managing PVCs much easier, which in turn would make managing data generated by pipelines much easier.  Would be great for use cases that need some mix of automation and interactivity.

**Comment by Bobgy** [comment]
Hi folks, I'm sending out a proposal for building a generic viewer, see https://github.com/kubeflow/pipelines/issues/5681.
Curious about your thoughts there.
