### ISSUE TITLE
Failed to start Tensorboard app

### ISSUE THREAD

**Issue by rylynchen** [kubeflow/pipelines#5655]
### What steps did you take

Hi, I create a volume named 'nfs', and amount to the training pod in the pipeline. And training code generate tensorboard dir in the amount dir. But when I go to look tensorboard view, get error:
![p2](https://user-images.githubusercontent.com/1971286/118113863-682e9f00-b419-11eb-8e3d-ec38f1bba07f.png)

pipeline code:
```
def train_op(volume, image, cmd):
    # amount volume
    nfsVolume = dsl.PipelineVolume(volume=V1Volume(name="nfs",nfs={"server":"xxx","path":"/"}))
    svol = dsl.PipelineVolume(name='shm-vol', empty_dir={'medium': 'Memory'})
    op = dsl.ContainerOp(
        name="train",
        image=image,
        arguments=["/bin/sh", "-c", "%s" % (cmd)],
        pvolumes={
            "/output": nfsVolume,
            '/dev/shm': svol,
        },
        output_artifact_paths={
            'mlpipeline-ui-metadata': '/mlpipeline-ui-metadata.json',
        },
    )
    op.container.set_cpu_limit("0.5")
    op.container.set_gpu_limit("2")
    op.container.set_memory_limit("50G")
    return op
```
My training code generate tensorboard data in `/output/runs`, and the create metadata code:
```
metadata = {
    'outputs' : [
        {
            'type': 'tensorboard',
            'source': 'volume://nfs/runs',
        }
    ]
}
with open('/mlpipeline-ui-metadata.json', 'w') as f:
    print(metadata)
    json.dump(metadata, f)
```

### What happened:
![p2](https://user-images.githubusercontent.com/1971286/118113863-682e9f00-b419-11eb-8e3d-ec38f1bba07f.png)

### What did you expect to happen:
Tensorboard view show data

### Environment:
*  pipeline version: 1.0.0

Anyone has goods idea ?

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by zijianjoy** [comment]
You can follow the `deploy ml-pipeline-ui to support tensorboard viewer` in https://github.com/kubeflow/pipelines/blob/master/docs/config/volume-support.md to mount this volume for tensorboard. Note that this feature is in alpha phase, so it might not be stable.

**Comment by rylynchen** [comment]
> You can follow the `deploy ml-pipeline-ui to support tensorboard viewer` in https://github.com/kubeflow/pipelines/blob/master/docs/config/volume-support.md to mount this volume for tensorboard. Note that this feature is in alpha phase, so it might not be stable.

Thanks for your reply!
