### ISSUE TITLE
Add samples for volumes mount in containerop

### ISSUE THREAD

**Issue by gaoning777** [kubeflow/pipelines#566]
As the DSL support VolumeMount in containerop, it would be best to have samples illustrating how to use it.

**Comment by Ark-kun** [comment]
All our samples use volume mounting indirectly through the use_gcp_secret call.
Unless we have customers that have some other need for volume mounting by the user, I'm not sure we need to emphasize volumes.

**Comment by gaoning777** [comment]
I have been asked by customers and Sina about how to set up the volumes in the DSL. The use_gcp_secret is not straighforward to the users about how to use the volumes.

**Comment by vicaire** [comment]
@gaoning777, I am assigning the DSL sample issues to illustrate features to you. Please reassign to the most appropriate person as needed.

**Comment by gaoning777** [comment]
VolumeOp is illustrated here: https://github.com/kubeflow/pipelines/tree/master/samples/resourceops

**Comment by elikatsis** [comment]
_Minor Update:_

I opened #1433 to better organize these examples and also provide a mini documentation.
