### ISSUE TITLE
[v2compat] umbrella - KFP data model based caching

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#5667]
internal tracker: b/181133870

Work Items estimate:
* [x] #5726  (size/L)
* [x] #5816 (size/M)
* [x] #5817(size/M)
* [x] #5818(size/S)
* [x] #5819 (size/M)
* [x] #5820 (size/M)
* [x] #5977

total: 4w, 1d for SDK team

**Comment by Bobgy** [comment]
Needs further TODO item break down

**Comment by juliusvonkohout** [comment]
Hi @Bobgy do you have the following in mind ? https://github.com/kubeflow/pipelines/issues/5509
Or will there be a native way such that deleting runs from the pripelines webinterface will also delete the artifacts from minio and make the cacher aware that the files are gone?

**Comment by Bobgy** [comment]
@capri-xiyue can introduce more, but our implementation is basically what you described.

When runs are deleted, their entries will no longer be used for caching.

We haven't invented a way to delete external data for users yet, because data loss would be very frightening.

**Comment by Bobgy** [comment]
Hi @zijianjoy, I just realized you'll need to make a small change https://github.com/kubeflow/pipelines/issues/5977 for caching.
You can coordinate with @capri-xiyue for how to do that

**Comment by Bobgy** [comment]
All P0s are done, great work @capri-xiyue @zijianjoy
