### ISSUE TITLE
v2 metrics visualization

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#5668]
components can output metrics artifacts that are rendered in UI.
Sample pipeline: https://github.com/kubeflow/pipelines/blob/89364315e96ca0e14106ef178336f72265a8e91a/samples/test/metrics_visualization_v2.py

TODOs:
* [x] ~~add MLMD state verification of this pipeline: https://github.com/kubeflow/pipelines/blob/89364315e96ca0e14106ef178336f72265a8e91a/samples/test/metrics_visualization_v2_test.py#L21~~
* [x] scalar metric (no need to support showing scalar metrics in run list for now), wait for resolution of https://github.com/kubeflow/pipelines/issues/5669#issuecomment-845676621
* [x] ROC curve
* [x] confusion matrix
* [x] add v2 metrics visualization section in https://www.kubeflow.org/docs/components/pipelines/sdk/output-viewer/

Also suggest trying to write new UI code in recent best practices and try to separate them from existing components. We want to take a gradual approach to modernize the UI codebase.

**Comment by Bobgy** [comment]
b/186482243

**Comment by zijianjoy** [comment]
Do we visualize HTML, Markdown, Tensorboard in the new visualization tab?

**Comment by Bobgy** [comment]
> Do we visualize HTML, Markdown, Tensorboard in the new visualization tab?

Yes, they are tracked in a different issue in P1.

**Comment by zijianjoy** [comment]
We might need to update documentation https://www.kubeflow.org/docs/components/pipelines/sdk/output-viewer/

**Comment by Bobgy** [comment]
> We might need to update documentation https://www.kubeflow.org/docs/components/pipelines/sdk/output-viewer/

That's a good point! Note, the update work item is already tracked in https://github.com/kubeflow/pipelines/issues/5666#issue-894322129.

**Comment by zijianjoy** [comment]
Definition of `System.ClassificationMetrics`: https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/dsl/io_types.py#L122

**Comment by zijianjoy** [comment]
Hello Yuan @Bobgy , what is the goal of this item?

`add MLMD state verification of this pipeline`

Does it mean we check the status of `execution`? Or the status of complete pipeline run? What do we want to visualize when state is success?

**Comment by Bobgy** [comment]
@zijianjoy I just figured out moving custom properties to `metadata` field in a separate PR, so I think I can take `add MLMD state verification of this pipeline` task too in the same PR.

**Comment by Bobgy** [comment]
All is done

**Comment by kimkihoon0515** [comment]
@Bobgy Hi, I'm trying to use test code for visualizing confusion matrix metrics but it seems doesn't work well can you help me please??
https://github.com/kubeflow/pipelines/issues/8675
