### ISSUE TITLE
[UI] inputs/outputs tab in KFP semantics

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#5670]
KFP Inputs/Outputs tab in run details page is currently very coupled to argo.

For v2 compatible pipelines, we can use information from MLMD to render the Inputs/Outputs tab in KFP semantics.

**Comment by zijianjoy** [comment]
### Current INPUT/OUTPUT tab

Render Input Parameters, Input Artifacts, Output Parameters, Output Artifacts.

They are read from Workflow object.

### Use MLMD

Based on execution, we can find a list of events to identify artifact and input/output for this execution. Detail info is in https://github.com/kubeflow/pipelines/blob/d9c019641ef9ebd78db60cdb78ea29b0d9933008/third_party/ml-metadata/ml_metadata/proto/metadata_store.proto#L94-L161.

**Comment by zijianjoy** [comment]
### Questions

1. What is the relationship of Input/Output tab vs the ML metadata tab in https://github.com/kubeflow/pipelines/blob/d9c019641ef9ebd78db60cdb78ea29b0d9933008/frontend/src/pages/ExecutionDetails.tsx#L126-L145? How should we merge them into one? Possible solution: Move the INPUT/OUTPUT/DECLARED_INPUT/DECLARED_OUTPUT to Input/Output tab, and shows only Properties/Custom Properties in ML Metadata tab.
2. How do we differentiate Parameter and Artifact from MLMD? 
3. What is the relationship between DECLARED_INPUT and INPUT? How to show them in static pipeline mode?

**Comment by Bobgy** [comment]
These questions are right to the point! Let me try to explain some context, I don't have a clear answer to some of them, you'll need to do some designing.

> ### Questions
> 1. What is the relationship of Input/Output tab vs the ML metadata tab in https://github.com/kubeflow/pipelines/blob/d9c019641ef9ebd78db60cdb78ea29b0d9933008/frontend/src/pages/ExecutionDetails.tsx#L126-L145
>    ? How should we merge them into one? Possible solution: Move the INPUT/OUTPUT/DECLARED_INPUT/DECLARED_OUTPUT to Input/Output tab, and shows only Properties/Custom Properties in ML Metadata tab.

In KFP v1, input / output tab shows info parsed from argo workflows, but ML metadata tab shows info from MLMD. In v2 & v2 compatible, both will come from MLMD (and they are duplicate), so some merging or information rearrangement is necessary as you thought.

Here's my gut feeling arrangement (mostly similar to your proposal), feel free to discuss:

Input/output tab
* shows info from MLMD
* in addition to showing preview + download link, we can add a link to MLMD artifact details page

ML Metadata tab
* suggest remove the tab altogether, because in KFP v2 compatible, we do not allow users to customize execution metadata/custom properties, so there's not much left to show

Link to execution details page should probably be shown all the time (e.g. as the side content title, see below
![image](https://user-images.githubusercontent.com/4957653/120920091-adc84a00-c6ef-11eb-8105-5ff07a932ea0.png)

> 2. How do we differentiate Parameter and Artifact from MLMD?

![image](https://user-images.githubusercontent.com/4957653/120920151-05ff4c00-c6f0-11eb-968f-d20773284abc.png)
The KFP MLMD data model is that input parameters are logged as `input:<parameter-name>` custom properties of the execution.
Output parameters are logged as `output:<parameter-name>` custom properties.

Similar to PR: https://github.com/kubeflow/pipelines/pull/5793, we will soon standardize to move parameters to fields of a custom property `metadata`. `metadata` is of `Struct` type, so it can include key value pairs like `input:<param>`, `output:<param>` like mentioned above.

Artifacts are what you already observed in ML metadata tab, they are connected to executions by event.

> 3. What is the relationship between DECLARED_INPUT and INPUT? How to show them in static pipeline mode?

Answer (ref from proto file):
>  For example, the DECLARED_INPUT and DECLARED_OUTPUT events are part of the signature of an execution

https://github.com/google/ml-metadata/blob/47150524ee5ceee9766a034c4fbe5427440dd79e/ml_metadata/proto/metadata_store.proto#L100-L138

Thanks for the question, after re-reading the documentation, now I realized I had a wrong understanding of DECLARED_INPUT. For all inputs/outputs in KFP tasks, they should be declared input/outputs because they are part of the KFP component signature. Non-declared inputs/outputs is a concept only TFX uses.

However, until now, because KFP does not have the non-declared inputs/outputs concept, we are logging all inputs & outputs as pure inputs and outputs. We need to confirm whether this is sth we need to change.

Ref: [MLMD Terminology section of KFP v2 design](https://docs.google.com/document/d/1fHU29oScMEKPttDA1Th1ibImAKsFVVt2Ynr4ZME05i0/edit#heading=h.zv2ulr8vrvu)
