### ISSUE TITLE
Rest API to query pipeline run results

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#5674]
Umbrella issue, this tracks
1. coming up with a standard spec that describes pipeline run results for all the engines, e.g. we now have Argo, Tekton and Vertex AI pipelines.
1. implement REST API for this spec

**Comment by difince** [comment]
@Bobgy I am new contributor, looking for my first issue .. Could I work on this one ? 
As I understand a new rest endpoint need to be added ?

**Comment by difince** [comment]
Thank you for the response @Bobgy
