### ISSUE TITLE
Update sample pipeline names to recommended resource format

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#5683]
Good: "my-pipeline"
Bad: "my_pipeline"

No underscores, spaces etc special characters.

**Comment by difince** [comment]
@Bobgy, I am a new contributor looking for my first issue.  
Could I work on this ?

**Comment by Bobgy** [comment]
Thank you @difince ! Yes, this is suitable for first time contributor.

The desired change is to review all pipelines in samples folder, if they have @pipeline annotation, change the pipeline name to only contain lowercase letters, hyphen and numbers.

**Comment by Bobgy** [comment]
Example
https://github.com/kubeflow/pipelines/blob/63a59a7e765b18c2fad04fa9e8431e82467e0cbb/samples/core/dns_config/dns_config.py#L32

should be changed to 'dns-config-setting'

**Comment by difince** [comment]
Thank you @Bobgy for your explanatory response!

**Comment by difince** [comment]
@Bobgy  What about lowering the upper case latters ?  
https://github.com/kubeflow/pipelines/blob/54ac9a6a7173aecbbb30a043b2077e790cac6953/samples/contrib/ibm-samples/watson/watson_train_serve_pipeline.py#L42

should it be `name='kfp-on-wml-training'` or
`name='KFP-on-WML-training'`

**Comment by Bobgy** [comment]
Hi @difince, sorry I wasn't clear on the scope. It's enough updating all samples in samples/core folder.

ContainerOp/VolumeOp/VolumeSnapshotOp names do not need any changes. Right now, we are only moving towards restrictor name for pipelines, because they will be context names.

**Comment by Bobgy** [comment]
And uppercase should be lowered
