### ISSUE TITLE
[SDK] better compiler error message when input type mismatch between parameter/artifact

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#5684]
https://github.com/kubeflow/pipelines/blob/f757a8842fd6d1ed3d37ab38c0707d127ea2048c/samples/core/exit_handler/exit_handler_test.py#L24-L34

download_gcs component has input type 'GCS Path', it has a cryptic error message when the input is passed a string parameter:

> File "/Users/gongyuan/kfp/pipelines/sdk/python/kfp/compiler/v2_compat.py", line 108, in update_op artifact_info = {"fileInputPath": op.input_artifact_paths[artifact_name]} KeyError: 'GCS path'

Because this can be a common mistake, I think it deserves a better error message which includes:

* clearly indicates what is going wrong here, including related information in the error message
* a link to public documentation explaining the rules of parameters vs artifacts

**Comment by chensun** [comment]
Should have been covered by https://github.com/kubeflow/pipelines/pull/5759
