### ISSUE TITLE
[Samples] organize and document sample folder structure with v2 samples

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#5686]
Propose using the following convention to organize samples:

* all core samples are by default compatible with both v1 and v2.
* samples that only run on v2 should be added either in samples/v2/core folder, or next to a corresponding v1 sample and have a v2 suffix, e.g. exit_handler_v2.py
* core samples that do not currently run on v2, but we have plan to support so can stay in samples folder, but we should add a comment saying clarifying status and plan.

**Comment by Bobgy** [comment]
TODO:
* [ ] document sample folder structure in samples/README.md
* [ ] check samples, mark those only run on v1 with comments
* [ ] check samples, mark those only run on v2 with v2_ in example name, or move into v2 folder.

**Comment by rimolive** [comment]
Closing this issue. This looks done.

/close
