### ISSUE TITLE
Design doc for pipelines 

### ISSUE THREAD

**Issue by swiftdiaries** [kubeflow/pipelines#569]
It'd be great to have a design doc with the overall architecture and a roadmap for future releases. 
cc @paveldournov @vicaire

**Comment by paveldournov** [comment]
ack

**Comment by swiftdiaries** [comment]
Thanks :)

**Comment by govindKAG** [comment]
this needs to be a thing

**Comment by vicaire** [comment]
We are working on an OSS version of the design. ETA: one to two weeks. Thanks.

**Comment by swiftdiaries** [comment]
Thanks for the update @vicaire !
