### ISSUE TITLE
[sdk] Regression - func_to_container_op no longer handles backslash characters correctly

### ISSUE THREAD

**Issue by rclough** [kubeflow/pipelines#5709]
### Environment

*  KFP version: Works <1.2.0, broken in 1.2.0+

### Steps to reproduce

This is a super simplified version of what I've found:

```python
def break_ftco() -> str:
    print("Printing an escaped quote \\\" will break")
    return "something"

@pipeline(name="test-ftco", description="")
def pipeline():
    irrelevant = func_to_container_op(
        func=break_ftco,
        base_image="gcr.io/my-image/name:tag
    )()
```

### Expected result

Component should print:

```
Printing an escaped quote \" will break
```

This works in kfp<1.2.0, but not >=1.2.0, in >=1.2.0, the component fails and the following is logged:

```
File "/tmp/tmp.87n1N4N8zw", line 2
    print("Printing an escaped quote \\" will break")
                                            ^
SyntaxError: invalid syntax
```

### Materials and Reference

Context:

When updating kfp SDK recently, one of our customers reported that one of their func_to_container_op functions stopped working properly. It ran, but was producing invalid results. In their case, they were doing a regex substitution on a string, where the regex substitution contained a backslash (`\`).

I compared pod definitions between the two versions and discovered that KFP changed the way they were executing python code for func_to_container_op, found the location in the code, and the relevant PR that introduced this regression: https://github.com/kubeflow/pipelines/pull/4861

More info on the original use case can be found there, but I narrowed it down to an example where `func_to_container_op` will fail to run for what is otherwise valid python code.

It may also be worth noting that since the code changed from being directly run with python to being passed through `sh` into a file, there may be other similar special shell characters to be escaped, but that's beyond my knowledge

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by michaelwsherman** [comment]
@Ark-kun

**Comment by Ark-kun** [comment]
This was expected to be fixed in https://github.com/kubeflow/pipelines/pull/4993 v1.4.0
Looking...

**Comment by Ark-kun** [comment]
This does not reproduce for me in v1.4.0+
![image](https://user-images.githubusercontent.com/1829149/119393576-fd395f80-bc85-11eb-81bc-3a08eb469e23.png)

Here is the generated `component.yaml`:
```yaml
name: Break ftco
outputs:
- {name: Output, type: String}
implementation:
  container:
    image: python:3.7
    command:
    - sh
    - -ec
    - |
      program_path=$(mktemp)
      printf "%s" "$0" > "$program_path"
      python3 -u "$program_path" "$@"
    - |
      def break_ftco():
          print("Printing an escaped quote \\\" will break")
          return "something"

      def _serialize_str(str_value: str) -> str:
          if not isinstance(str_value, str):
              raise TypeError('Value "{}" has type "{}" instead of str.'.format(str(str_value), str(type(str_value))))
          return str_value

      import argparse
      _parser = argparse.ArgumentParser(prog='Break ftco', description='')
      _parser.add_argument("----output-paths", dest="_output_paths", type=str, nargs=1)
      _parsed_args = vars(_parser.parse_args())
      _output_files = _parsed_args.pop("_output_paths", [])

      _outputs = break_ftco(**_parsed_args)

      _outputs = [_outputs]

      _output_serializers = [
          _serialize_str,

      ]

      import os
      for idx, output_file in enumerate(_output_files):
          try:
              os.makedirs(os.path.dirname(output_file))
          except OSError:
              pass
          with open(output_file, 'w') as f:
              f.write(_output_serializers[idx](_outputs[idx]))
    args:
    - '----output-paths'
    - {outputPath: Output}

```

**Comment by rclough** [comment]
Ah, we're currently on 1.3.0, good to know it's already fixed, we'll update ASAP

**Comment by Ark-kun** [comment]
>Ah, we're currently on 1.3.0, good to know it's already fixed, we'll update ASAP

Note that only the SDK needs to be updated.
