### ISSUE TITLE
[feature] default to the emissary executor

### ISSUE THREAD

**Issue by juliusvonkohout** [kubeflow/pipelines#5718]
#### Update - 2021.9.13
edited by @Bobgy 

KFP 1.7.0 is released.
documentation is live: https://www.kubeflow.org/docs/components/pipelines/installation/choose-executor/
choosing an executor will be an option starting from KFP 1.7.

#### Update - 2021.8.6
edited by @Bobgy 

Discussed with @kramachandran and decided to delay the default change for at least one KFP minor version, because argo emissary executor is still in Alpha state. There can be other corner cases that we haven't found, so we should give people some time to test it out.

Therefore, I'd like to propose the following:
* still default to docker executor in 1.7.0 release
* provide emissary executor as an option and document how to migrate
* collect feedback from people who starts to try emissary executor

TODOs:
* [x] https://github.com/kubeflow/website/pull/2857
* [x] Make emissary available in installations
  * [x] #6294
  * [x] Make env/platform-agnostic-emissary
* [x] #6252
* [x] Upgrade kfp-ci test infra to argo v3.1.1 https://github.com/kubeflow/testing/commit/03c625828ac9cc13283bd226371280b0f5704c09

Issues discovered when testing argo v3.1.0 with KFP:
* [x] https://github.com/kubeflow/pipelines/issues/5930
* [x] https://github.com/kubeflow/pipelines/issues/5937 (fixed in v3.1.1)
* [x] https://github.com/kubeflow/pipelines/issues/5944 (fixed in v3.1.1)
* [x] https://github.com/argoproj/argo-workflows/issues/6238

=== the following are the original proposal ===

### What feature would you like to see?

Update argo to 3.11 such that we can use the emissary executor as decided by @bobgy in https://github.com/kubeflow/pipelines/pull/4645#issuecomment-845691359

### What is the use case or pain point?

The Docker, Kubelet, PNS and K8sapi executors have severe limitations that will be solved by Argo 3.1 and the emissary executor.

Here is an overview https://argoproj.github.io/argo-workflows/workflow-executors/

In a nutshell docker breaks security completely and is incompatible with kubernetes 1.19
https://github.com/kubeflow/pipelines/issues/5714 Kubernetes is also moving to containerd anyway and a lot of users want proper non-docker support for a long time https://github.com/kubeflow/pipelines/issues/1654

Kubelet needs some configuration and has the same limitation as k8sapi and rootless PNS: "Output artifacts must be saved on volumes (e.g. emptyDir) and not the base image layer (e.g. /tmp)" so it breaks the leightweight python components if there is no volume mounted or the output directory is inside the base layer https://github.com/kubeflow/pipelines/pull/4645

One can use a PNS with root rights (PTRACE and CHROOT) to circumvent this, but this obviously breaks the security again.

 So only the emissary executor https://argoproj.github.io/argo-workflows/workflow-executors/#emissary-emissary is feasible which does more ore less what i proposed in https://github.com/kubeflow/pipelines/pull/4645 and what was started by Argos @alexec in https://github.com/argoproj/argo-workflows/pull/4766

The Argo update has been done before in https://github.com/kubeflow/pipelines/pull/5266 and https://github.com/kubeflow/pipelines/pull/4693 by @xinbinhuang @Bobgy 

### Is there a workaround currently?

```
# Emmissary executor, needs argo 3.1+
# Sadly visualizations are broken(26.04.2021) for k8sapi and emissary

kubectl -n kubeflow patch configmap/workflow-controller-configmap --type='json' -p='[{"op": "replace", "path": "/data/containerRuntimeExecutor", "value": "emissary"}]'

kubectl edit deployment/workflow-controller -n kubeflow
...
    spec:
      containers:
      - env:
        - name: "LEADER_ELECTION_DISABLE"
       	  value: true
      - args:
	- --configmap
        - workflow-controller-configmap
        - --executor-image
        - docker.io/argoproj/argoexec:latest
        command:
        - workflow-controller
        image: docker.io/argoproj/workflow-controller:latest    
        env:
	- name: "LEADER_ELECTION_DISABLE"
          value: "true"
...
kubectl -n kubeflow patch configmap/workflow-controller-configmap --type='json' -p='[{"op": "replace", "path": "/data/containerRuntimeExecutor", "value": "emissary"}]'
kubectl rollout restart deployment workflow-controller -n kubeflow

or manually patching the sdk and using k8sapi as done in https://github.com/kubeflow/pipelines/pull/4645

Or use kfp-tekton
```

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by Bobgy** [comment]
@juliusvonkohout can you clarify how visualization is broken?
> # Sadly visualizations are broken(26.04.2021) for k8sapi and emissary

**Comment by juliusvonkohout** [comment]
> @juliusvonkohout can you clarify how visualization is broken?
> > Sadly visualizations are broken(26.04.2021) for k8sapi and emissary

It just does not show in the UI. As far as I remember the stuff was in minio but not properly displayed by pipeline-ui. But I would have to check again. Such problems are expected, since I just replaced the Argo images instead of properly updating Argo everywhere in kubeflow pipelines. Since it appeared with emissary AND k8sapi it should be fine with a proper Argo update in kubeflow.

If you need more information you can obtain them with my instructions above or tell me what exactly you want and I will check it on Tuesday.

**Comment by Bobgy** [comment]
/assign
I believe there is no doubt this is the right way to go.

**Comment by NikeNano** [comment]
I can help out updating argo to v3 @Bobgy 
/assign

**Comment by Ark-kun** [comment]
>"Output artifacts must be saved on volumes (e.g. emptyDir) and not the base image layer (e.g. /tmp)" so it breaks the leightweight python components if there is no volume mounted or the output directory is inside the base layer #4645

Each output is placed in it's own directory. And those directories are in `/tmp/outputs/`, not just in `/tmp/`. Couldn't Argo mount EmptyDir volumes under the outputs directories? Argo already does that for inputs.

P.S. The SDK could change the paths to `/outputs/` without a need to change components or pipelines. It was like that at some point in the past.

**Comment by juliusvonkohout** [comment]
@Ark-kun this has all been discussed extensively in the links provided above. You will find detailed answers there.

**Comment by juliusvonkohout** [comment]
The release of 3.1 is very close. 3.1.0-rc8 is already there https://github.com/argoproj/argo-workflows/releases and 3.0-rc9 https://github.com/argoproj/argo-workflows/releases/tag/v3.0.0-rc9 was the last prerelease for the 3.0 branch. Based on that 3.1.0 should land in 1-2 weeks.

**Comment by NikeNano** [comment]
Have started the work to upgrade should be easy to go to the next version when it is out.

**Comment by Bobgy** [comment]
TODO: I'll review argo v3 images for licenses and upgrade the manifests.

**Comment by juliusvonkohout** [comment]
I think we should add a test for a simple pipeline that runs as non-root. That way we know that the emissary executor works properly. 
The following tests runasnonroot and kubeflow profile quotas. 

``` python

python
from kfp.components import create_component_from_func
from typing import NamedTuple

def pod_defaults(op, user = 1000):
    from kubernetes import client as k8s_client
    from kubernetes.client.models import V1SecurityContext
    op.set_security_context(V1SecurityContext(run_as_user=user, run_as_group=0))
    op.set_memory_request('10Mi');# op.set_memory_limit('1000Mi')
    op.set_cpu_request('10m');# op.set_cpu_limit('1000m')
    return op

def produce_markdown() -> NamedTuple('Outputs', [('mlpipeline_ui_metadata', 'UI_metadata'), ('mlpipeline_metrics', 'Metrics')]):
    #https://www.kubeflow.org/docs/components/pipelines/sdk/output-viewer/
    metadata = {"outputs": [
        {"storage": "inline", "source": "*this should be bold*", "type": "markdown"}
    ]}
    # https://www.kubeflow.org/docs/components/pipelines/sdk/pipelines-metrics/
    metrics = {'metrics': [
        {
        'name': 'train-accuracy', # underscores are not allowed... https://github.com/kubeflow/pipelines/issues/3809
        'numberValue':  0.9,
        },
        {
        'name': 'test-accuracy', # underscores are not allowed...
        'numberValue':  0.7,
        }
    ]}
    #return [json.dumps(markdown)]
    from collections import namedtuple; import json
    return namedtuple('output', ['mlpipeline_ui_metadata', 'mlpipeline_metrics'])(json.dumps(metadata), json.dumps(metrics))

...

markdown_component = func_to_container_op(func=produce_markdown, base_image=BASE_IMAGE)()
pod_defaults(markdown_component)

```

But you have to use PSPs or consider https://argoproj.github.io/argo-workflows/workflow-pod-security-context/

**Comment by Bobgy** [comment]
Note, there's a breaking change. When using emissary executor, your components must specify the command explicitly.

> step group deemed errored due to child integration-test-vzl9f[0].build-initialization-test-image error: when using the emissary executor you must either explicitly specify the command, or list the image's command in the index: https://argoproj.github.io/argo-workflows/workflow-executors/#emissary-emissary  
 └───⚠ build-initialization-test-image(0)  build-image       integration-test-vzl9f-2173864179  0s        when using the emissary executor you must either explicitly specify the command, or list the image's command in the index: https://argoproj.github.io/argo-workflows/workflow-executors/#emissary-emissary

**Comment by Bobgy** [comment]
The breaking changes is also required for bit.ly/kfp-v2-compatible and bit.ly/kfp-v2. So I think we can introduce it now.

**Comment by Bobgy** [comment]
user facing documentation candidate

### Breaking change
Argo emissary executor requires that each container has explicit command and args defined, refer to https://argoproj.github.io/argo-workflows/workflow-executors/#emissary-emissary.

Why we decide to adopt the breaking change? We'd have the same breaking change in bit.ly/kfp-v2-compatible and bit.ly/kfp-v2. So I think it aligns with KFP's long term goal, and it's OK to introduce the breaking change now.

**Comment by Bobgy** [comment]
Filed upstream issue for using argo emissary executor with rootless container: https://github.com/argoproj/argo-workflows/issues/6238.

The current blocker in e2e test failure is at selenium image: https://github.com/kubeflow/pipelines/blob/76f8b3e9acf09bdc5a7e7729b0dfa64dd51b922a/test/frontend-integration-test/Dockerfile#L4. It runs as non-root.

**Comment by Bobgy** [comment]
Issues discovered in argo v3.1.0:
* [ ] input/output tab does not render artifact preview 
![image](https://user-images.githubusercontent.com/4957653/123645109-9c8add00-d858-11eb-8e42-61884bc22f50.png)

**Comment by Bobgy** [comment]
(added status update to the issue description itself: https://github.com/kubeflow/pipelines/issues/5718#issue-897774761)

**Comment by nongqiqin** [comment]
“This step is in Error state with this message: failed to save outputs: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?”

> I think we should add a test for a simple pipeline that runs as non-root. That way we know that the emissary executor works properly.
> The following tests runasnonroot and kubeflow profile quotas.
> 
> ```python
> python
> from kfp.components import create_component_from_func
> from typing import NamedTuple
> 
> def pod_defaults(op, user = 1000):
>     from kubernetes import client as k8s_client
>     from kubernetes.client.models import V1SecurityContext
>     op.set_security_context(V1SecurityContext(run_as_user=user, run_as_group=0))
>     op.set_memory_request('10Mi');# op.set_memory_limit('1000Mi')
>     op.set_cpu_request('10m');# op.set_cpu_limit('1000m')
>     return op
> 
> def produce_markdown() -> NamedTuple('Outputs', [('mlpipeline_ui_metadata', 'UI_metadata'), ('mlpipeline_metrics', 'Metrics')]):
>     #https://www.kubeflow.org/docs/components/pipelines/sdk/output-viewer/
>     metadata = {"outputs": [
>         {"storage": "inline", "source": "*this should be bold*", "type": "markdown"}
>     ]}
>     # https://www.kubeflow.org/docs/components/pipelines/sdk/pipelines-metrics/
>     metrics = {'metrics': [
>         {
>         'name': 'train-accuracy', # underscores are not allowed... https://github.com/kubeflow/pipelines/issues/3809
>         'numberValue':  0.9,
>         },
>         {
>         'name': 'test-accuracy', # underscores are not allowed...
>         'numberValue':  0.7,
>         }
>     ]}
>     #return [json.dumps(markdown)]
>     from collections import namedtuple; import json
>     return namedtuple('output', ['mlpipeline_ui_metadata', 'mlpipeline_metrics'])(json.dumps(metadata), json.dumps(metrics))
> 
> ...
> 
> markdown_component = func_to_container_op(func=produce_markdown, base_image=BASE_IMAGE)()
> pod_defaults(markdown_component)
> ```
> 
> But you have to use PSPs or consider https://argoproj.github.io/argo-workflows/workflow-pod-security-context/ and use a kubeflow profile with quotas.

Used 
`kubectl -n kubeflow patch configmap/workflow-controller-configmap --type='json' -p='[{"op": "replace", "path": "/data/containerRuntimeExecutor", "value": "emissary"}]'`

`kubectl edit deployment/workflow-controller -n kubeflow`

A new error:
"This step is in Error state with this message: failed to save outputs: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"

How solve this error?

**Comment by Bobgy** [comment]
@nongqiqin how did you deploy KFP and argo? You need at least KFP 1.7.0-alpha.2 to get an argo version of v3.1.1. v3.0.x and before do not support emissary executor

**Comment by juliusvonkohout** [comment]
> @nongqiqin how did you deploy KFP and argo? You need at least KFP 1.7.0-alpha.2 to get an argo version of v3.1.1. v3.0.x and before do not support emissary executor

Yes you need to upgrade to argo 3.1 first

**Comment by Bobgy** [comment]
Renaming to just default to emissary executor, because we've finished the upgrade.

**Comment by Bobgy** [comment]
Fixed by https://github.com/kubeflow/pipelines/pull/7137

**Comment by kotalakshman** [comment]
when using the emissary executor you must either explicitly specify the command, or list the image's command in the index: https://argoproj.github.io/argo-workflows/workflow-executors/#emissary-emissary

kubeflow version:1.7.1
