### ISSUE TITLE
[v2compat] caching design

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#5726]
Part of #5667

**Comment by juliusvonkohout** [comment]
@bobgy please keep in mind that cpu and memory ressource requests must be set for compatibility with kubeflow profile quotas. I tried something but could not get it working yet https://github.com/kubeflow/pipelines/pull/5743

**Comment by Bobgy** [comment]
Hi @juliusvonkohout , the problem you mentioned is with KFP v1 caching.

In v2 compatible caching design, we won't change the Pod spec when it's cached, so this will no longer be a problem.
In v2 design, we will skip the Pod entirely, so this won't be a problem either.

**Comment by capri-xiyue** [comment]
Design Doc finished
