### ISSUE TITLE
UI should allow creating a run with no experiment

### ISSUE THREAD

**Issue by yebrahim** [kubeflow/pipelines#573]
Follow up on #560.

/area front-end

**Comment by paveldournov** [comment]
A reference to a scenario/use case would be helpful.

**Comment by yebrahim** [comment]
Experiments are organizational concepts, and I think they shouldn't get in the way of someone wanting to create a run to always have an experiment to contain it. Thoughts?

**Comment by rileyjbauer** [comment]
This is already possible by creating a run from a pipeline (e.g. `PipelineDetails` -> "Create run").

Are you advocating for a more up-front button for this path?

**Comment by yebrahim** [comment]
I didn't know we fixed this, I thought the fix was blocked on the backend validation work, which I'm removing in #572. Is the current state broken?

**Comment by rileyjbauer** [comment]
The frontend path was added in #507 which was in when the latest (0.1.5) release was cut in #549, so yes, this is currently broken in the latest release
