### ISSUE TITLE
[bug] Can't run kubeflow pipeline

### ISSUE THREAD

**Issue by hanpeiyu94** [kubeflow/pipelines#5744]
### What steps did you take
Running Kubeflow on Microk8s cluster that is running on my local computer. 
Got access to Kubeflow dashboard and trying to run pipeline.

### What happened:
When I try to run any of the pipeline examples, The job never show up on `Runs` tab. And when I try to create experiment, it has this error:
```
{"error":"Validate experiment request failed.: Invalid input error: In single-user mode, CreateExperimentRequest shouldn't contain resource references.","code":3,"message":"Validate experiment request failed.: Invalid input error: In single-user mode, CreateExperimentRequest shouldn't contain resource references.","details":[{"@type":"type.googleapis.com/api.Error","error_message":"In single-user mode, CreateExperimentRequest shouldn't contain resource references.","error_details":"Validate experiment request failed.: Invalid input error: In single-user mode, CreateExperimentRequest shouldn't contain resource references."}]}
```
### What did you expect to happen:
To be able to run the example pipeline.
### Environment:
Microk8s v1.21

*  How do you deploy Kubeflow Pipelines (KFP)? 
I am not sure if KFP is need if Kubeflow is deployed by Microk8s

*  KFP version: 

*  KFP SDK version: 

### Labels

/area samples 

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by Bobgy** [comment]
What is the version of KFP when you use Kubeflow on MicroK8s?

**Comment by hanpeiyu94** [comment]
Sorry, I already deleted MicroK8s. I did not install KFP on my own, and I am not sure KFP is installed by MicroK8s or not. In case i am not understanding this correctly. Do you have to install Kubeflow pipeline after install Kubeflow in order to run pipeline?

**Comment by Bobgy** [comment]
No, you only need to install kubeflow, but I am not clear on the kubeflow pipelines version included

**Comment by hanpeiyu94** [comment]
how do you check kubeflow pipelines version? I'll reinstall Microk8s to check it for you.

**Comment by hanpeiyu94** [comment]
On the kubeflow dashboard under Experiment(KFP) tab, It shows Version: 1.5.0-rc.0. Hope this is what you are looking for.

**Comment by Bobgy** [comment]
Thank you, this seems a problem with microk8s's kubeflow distribution. Do you know how to contact them?

**Comment by hanpeiyu94** [comment]
Thanks for you help, I am not using Microk8s for right now, I'll ask them when I need to.
