### ISSUE TITLE
Error occured while trying to proxy to: pipelines/upload

### ISSUE THREAD

**Issue by gordonsilvera** [kubeflow/pipelines#5745]
When entering the Kubeflow Pipeline, received the error:

```
Error occured while trying to proxy to: 
#############-dot-us-central1.pipelines.googleusercontent.com/apis/v1beta1/pipelines?page_token=&page_size=10&sort_by=created_at%20desc&filter=
```

### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
Via the [GCP AI Platform Pipelines UI](https://console.cloud.google.com/ai-platform/pipelines/clusters). This instance uses managed storage.

*  KFP version:  **1.4.1**

To find the version number, See version number shows on bottom of KFP UI left sidenav. -->
*  KFP SDK version: 
```
kfp                            1.6.2
kfp-pipeline-spec              0.1.7
kfp-server-api                 1.6.0
```

### Steps to reproduce

1. Initially, I tried to load the pipeline from GCP hosted Jupyter Notebook via the Python API: 
```
  self.load_response = self.client.upload_pipeline(
      pipeline_package_path=self.pipeline_path,
      pipeline_name=self.pipeline_name,
      description=self.pipeline_description
  )
```

I also tried to enter `client.list_pipelines()` in a hosted Notebook. In both scenarios, I receive the error: "Error 504 (Gateway Timeout)!"

2. Secondly, I tried to upload the .zip from the Kubeflow dashboards interface. The screenshot below shows the error message I received.

[Error in Kubeflow Dashboard](https://storage.googleapis.com/algom-tmp-files/Screen%20Shot%202021-05-27%20at%2010.20.50%20PM.png)

### Expected result

Expect for pipeline to be added to Kubeflow interface.

### Materials and Reference

Based on the error logs, the source of the issue is the initialization of MySQL. The container logs show multiple errors after initialization, MySQL shuts down, reinitializes ... and this cycle repeats itself. Also, **this error did not occur when not using managed storage**.

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by gordonsilvera** [comment]
Note, this is corrected by specifying a namespace (rather than accepting "Default").

**Comment by Bobgy** [comment]
Strange, I don't expect it being a problem when namespace is default.
There might be sth else going wrong.

I guess we'll have to wait for more feedback
