### ISSUE TITLE
[v2compat] support s3 pipeline_root with endpoint, region, insecure etc

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#5753]
Part of https://github.com/kubeflow/pipelines/issues/5704

Support s3 pipeline_root with generic options: endpoint, region, insecure, etc, so that it can be used with user maintained MinIO or other compatible storages.

Credentials can be set similar to aws/gcp credentials, but not using the same env vars as AWS. (Needs a detailed design)

**Comment by ConverJens** [comment]
@bobgy TFX pipelines already supports this by appending pipeline wide env vars and by not assuming a default S3 instance. Using another Minio is basically the only viable option for on-prem deployments.

**Comment by chensun** [comment]
Closing as v2 compatible mode is no longer supported.
