### ISSUE TITLE
Kfp cli throwing an error: Error: No such command 'submit'.

### ISSUE THREAD

**Issue by priya170807** [kubeflow/pipelines#5756]
Hi,

I have created a pipeline and compile it. I am getting an error submitting a run to the end point.

Command:

`!kfp --endpoint $ENDPOINT run submit \ -e $EXPERIMENT_NAME \ -r $RUN_ID \ -p $PIPELINE_ID \ project_id=$PROJECT_ID \ gcs_root=$GCS_STAGING_PATH \ region=$REGION \ source_bucket_name=$SOURCE_BUCKET_NAME \ source_prefix=$SOURCE_PREFIX \ dest_bucket_name=$DEST_BUCKET_NAME \ dest_prefix=$DEST_PREFIX \ dest_file_name=$DEST_FILE_NAME \ evaluation_metric_name=$EVALUATION_METRIC \ evaluation_metric_threshold=$EVALUATION_METRIC_THRESHOLD \ model_id=$MODEL_ID \ version_id=$VERSION_ID \ replace_existing_version=$REPLACE_EXISTING_VERSION`

Error:

Usage: kfp [OPTIONS] COMMAND [ARGS]...
Try 'kfp --help' for help.
**Error: No such command 'submit'.**

Any help is appreciated.

Priya

**Comment by Bobgy** [comment]
Hi @priya170807, it seems you should move `--endpoint $ENDPOINT` argument to after `run submit`,

e.g.
```
kfp run submit --endpoint $ENDPOINT ...
```

**Comment by priya170807** [comment]
> 
> 
> Hi @priya170807, it seems you should move `--endpoint $ENDPOINT` argument to after `run submit`,
> 
> e.g.
> 
> ```
> kfp run submit --endpoint $ENDPOINT ...
> ```
