### ISSUE TITLE
[feature] Multiple choice pipeline parameter

### ISSUE THREAD

**Issue by skogsbrus** [kubeflow/pipelines#5757]
### Feature Area

/area frontend
/area backend
/area sdk

### What feature would you like to see?

Multiple choice pipeline parameters, as offered by e.g. Jenkins.

User experience:

- When triggering a run via UI, all valid multiple choice values are displayed as radio buttons. The user selects one of them. 
- When triggering a run via API with a bad parameter value, the user gets an error response (400) with a message explaining the valid values for the relevant parameter.

### What is the use case or pain point?

As of today, multiple choice parameters are implicit. Users have to know the implementation details of the pipeline in order to know which values are permitted.

This discourages unfamiliar users to use the pipeline, as well as being an obstacle in the workflow of the ordinary developer. Having it available as a native form of PipelineParam would:

1. Enable people that have not read the pipeline definition to trigger a run
2. Increase documentation: having multiple choice parameters is a form of 'documentation as code'

### Is there a workaround currently?

Validate parameter value inside the relevant component.

This is hidden from the user. The user has to trigger the pipeline, watch it fail, and then check the logs in order to find out what went wrong. This also assumes that the pipeline developer has put in the effort of making a well formatted error message.

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by johan-andersson01** [comment]
Haven't dived deep enough into kubeflow's implementation to know how compilation works and how this would propagate to the UI / API, but I'm thinking something along the lines of this (akin to the `@pipeline` decorator):

```
from functools import wraps

def pipeline_multiplechoice(**valid_kwargs):
    def verify_inputs(passed_kwargs):
        for k, v in passed_kwargs.items():
            if k in valid_kwargs and v not in valid_kwargs[k]:
                raise ValueError(f"{v} is not a valid value for {k}. Choose from {valid_kwargs[k]}")

    def decorator(f):
        @wraps(f)
        def wrapper(*f_args, **f_kwargs):
            verify_inputs(f_kwargs)
            return f(*f_args, **f_kwargs)
        return wrapper
    return decorator


@pipeline_multiplechoice(
    a={"a1", "a2", "a3"},
    b={"b1", "b2", "b3"},
    c={"c1", "c2", "c3"}
)
def function(a, b, c):
    print(f"{a=}")
    print(f"{b=}")
    print(f"{c=}")


if __name__ == "__main__":
    # valid
    function(a='a1',b='b2',c='c3')
    # invalid
    function(a=1,b=2,c=3)
```

**Comment by johan-andersson01** [comment]
So I've read up _a bit_ more on the [compiler](https://kubeflow-pipelines.readthedocs.io/en/stable/_modules/kfp/compiler/compiler.html#Compiler.compile) and this looks like a pretty easy add-on.

1. The decorator assigns e.g. `_multiplechoice` to the function object
2. The compiler checks if the pipeline function has a `_multiplechoice` field, and if it does writes these values to the pipeline yaml. 

`"inputs": [{"name": "num_batches", "type": "Integer"}` could for example become `"inputs": [{"name": "num_batches", "type": "Integer", "valid_values": [0, 100, 1000]}` if it had a multiplechoice decorator.

Finally, adding the necessary validations in frontend and API would also be necessary.

I'd be happy to do the work on this, but would appreciate any thoughts on the matter before I commence :slightly_smiling_face:

**Comment by johan-andersson01** [comment]
An alternative approach would be to add these options to the existing `pipeline` decorator.

For example:
```
@dsl.pipeline(
  name="training-pipeline",
  description="Trains a model"
  num_batches_options={0,100,1000},
  learning_rate_options={0.1, 0.01, 0.001, 0.0001},
  num_batches_description="Number of batches to train",
  learning_rate_description="Learning rate of the optimizer"
)
def my_training_pipeline(num_batches: int, learning_rate: float):
  pass

```

Then in order to match e.g. `num_batches` to `num_batches_options` and `num_batches_description`, we'd need `inspect.getfullargspec` to retrieve the parameter names in `my_training_pipeline`.

This would be a pretty nice solution IMO:
- We solve this and #5758 in one implementation
- We keep the dsl tidy: one pipeline decorator only
- No backwards compat. issues, since these would be optional keyword arguments in the decorator
- Extensible: if we need to pass more information in the future, we simply add support for new `<argname>_<specifier>` arguments to the pipeline decorator

**Comment by Bobgy** [comment]
/cc @chensun 
What do you think? We need to start from letting people specify extra metadata on parameters first to support this.

**Comment by pbarker** [comment]
Would be cool if we could make this into generic validations for parameters, I have a need for validating things like names so that they fit into the Kubenetes validations
