### ISSUE TITLE
[feature] Pipeline parameter description

### ISSUE THREAD

**Issue by skogsbrus** [kubeflow/pipelines#5758]
### Feature Area

/area frontend
/area backend
/area sdk

### What feature would you like to see?

Pipeline parameter descriptions / comments, as offered by e.g. Jenkins.

In the UI, pipeline parameters would have an optional field that describes that parameter. For example any considerations to make when deciding on the parameter value, how it would interact with other pipeline parameters, etc.

### What is the use case or pain point?

As of today, documentation is only visible in the source code of the pipeline definition (if it exists). Adding this to PipelineParam would make it visible in the UI, but still have it documented in the code.

Suggestions:
- parse docstrings
- add a 'description' field to PipelineParam

### Is there a workaround currently?

As of today, documentation is forced to be separate from the pipeline. Giving it a native place would increase developer productivity and onboarding.

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by johan-andersson01** [comment]
Implementing this in the SDK, one suggestion would be to follow the same principle as #5757 and add a description decorator that would assign a private field to the pipeline function (e.g. `_param_descriptions`). The compiler would read this field, and write it to the pipeline yaml.

`{"name": "num_batches", "type": "Integer"}` could then become `{"name": "num_batches", "type": "Integer", "description": "Number of batches to train"}` if it had the decorator `@pipeline_param_description(num_batches='Number of batches to train')`

**Comment by Bobgy** [comment]
/cc @chensun 
Another issue that requires adding metadata to parameters.

**Comment by meken** [comment]
While looking for a solution I ended up here, docs are not clear about this part, but looking at the source code I've found out that this is supported now through [docstrings](https://pypi.org/project/docstring_parser/).

**Comment by hahahannes** [comment]
Is this already reflected in the UI? E.g I don't see the description in the pipeline run creation page.
