### ISSUE TITLE
[bug] pipeline's child pods are not deleted after workflow's status became success

### ISSUE THREAD

**Issue by anencore94** [kubeflow/pipelines#5763]
### What steps did you take
- create kf pipeline
- all components were spawned well as pods.
- all components' status became COMPLETED
- pipeline's status became SUCCESS

### What happened:
- HOWEVER, child pods didn't killed automatically.
- I  should kill them manually.

### What did you expect to happen:
- They should be killed after pipeline succeeded.

### Environment:

*  How do you deploy Kubeflow Pipelines (KFP)? 
    * with kubeflow manifests repo, kustomize + kubectl apply
*  KFP version: 
    - tag : 1.5.0 (https://github.com/kubeflow/pipelines/tree/1.5.0/manifests/kustomize)
    - on UI : build version v1beta1
*  KFP SDK version: 
*  Kubernetes env:
    * on-premise k8s v1.19.3

### Anything else you would like to add:

I searched about this and I guess `spec.podGC.strategy` has some releation on this issue.

But, I didn't specify that parameter on my pipeline.yaml (kind : workflow).

In my case, is this situation is normal ? (all completed pods are not deleted until their parent pipeline will be deleted)

Also, if i want my pod would be deleted when my pipeline finished successfully, Do I have to specify spec.podGC.strategy everytime?

### Labels

/area backend

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by Bobgy** [comment]
This is expected behavior, default TTL is 1 day.
See https://github.com/kubeflow/pipelines/blob/5d0f3a3d32f35d3dbca9cd27f4ee476e87f6d41e/manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml#L24-L25

**Comment by anencore94** [comment]
Thanks @Bobgy !
I'm a bit confused, so I created new pipeline yesterday on success and see what's happen today. (after 24 hours)
And they really removed automatically.
Thank you for checking this :)  you may close this issue.
