### ISSUE TITLE
[UI] add link from execution to KFP run

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#5791]
A KFP task execution has one context of KFP run. So it's possible to get the related KFP run context (type `kfp.PipelineRun`), and extract run id from the context's custom properties.

After that, we can generate a link to the run and show it on MLMD UI.

**Comment by Bobgy** [comment]
/assign @zijianjoy 
logging an improvement I just came up with, I think we can add more links like this, to make KFP UI inter-connected. For any resource shown on the UI, we can link to a page where we can observe its details.

**Comment by zijianjoy** [comment]
Thank you Yuan!

I confirm that we can get the related `kfp.PipelineRun` context using `Execution ID`. However, I don't see custom properties for pipeline run ID, is there a reference to the code for adding this property?

**Comment by Bobgy** [comment]
You are right, it's not currently logged there.
Let me add it first

**Comment by zijianjoy** [comment]
Fixed by https://github.com/kubeflow/pipelines/pull/6556
