### ISSUE TITLE
[feature] support timeout option for watching

### ISSUE THREAD

**Issue by anencore94** [kubeflow/pipelines#5806]
### Feature Area

/area sdk

### What feature would you like to see?
- When we use `kfp run submit -w`, we have to wait forever when run stay at pending.
- However, I'd like to specify the timeout option with it.

### What is the use case or pain point?
- `kfp run submit -t 60` will wait 60 seconds max, until run be completed
- it would use [kfp client's wait_for_run_completion function](https://github.com/kubeflow/pipelines/blob/6a1b841db923e39016f5c6e66eac8698af27831d/sdk/python/kfp/_client.py#L922)

### Is there a workaround currently?

If you guys agree, I'd like to implement this feature.

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by Bobgy** [comment]
Welcome contribution! This seems useful
