### ISSUE TITLE
Declarative Pipeline deployment

### ISSUE THREAD

**Issue by jmendesky** [kubeflow/pipelines#5809]
/kind feature

Good morning, 

when deploying ML pipelines, we would like to build on existing tooling and follow similar patterns as when deploying other resources to our infrastructure. This would usually be done declaratively rather than programmatically. From our research, it seems that the only way to deploy Kubeflow pipelines at the moment is to use either kfctl or the Kubeflow Client libraries.

**Why you need this feature:**
Instead of having to execute Kubeflow clients, we'd like to have a declarative way of deploying Kubeflow Pipelines.

**Describe the solution you'd like:**
Provide a Kubeflow Pipeline Custom Resource Definition which gets picked up by an operator which then applies the changes to Kubeflow.

**Anything else you would like to add:**
We are considering implementing the above approach but would like to validate whether this would be useful for other people as well or whether something similar already exists.

**Comment by Bobgy** [comment]
Thanks for the proposal, I just transferred this issue

**Comment by Bobgy** [comment]
I'm curious how an operator would be preferred over kustomize manifests: https://github.com/kubeflow/pipelines/tree/master/manifests/kustomize.

See documentation: https://www.kubeflow.org/docs/components/pipelines/installation/standalone-deployment/

**Comment by jmendesky** [comment]
Thanks for getting back :)
I am referring to submitting an actual ML pipeline to a running KubeFlow Pipelines instance rather than installing Kubeflow Pipelines using an operator.

**Comment by Bobgy** [comment]
Understood, welcome contribution on this area

**Comment by jmendesky** [comment]
We are currently discussing a potential solution internally in our team. Once we have clarified our requirements and come up with an initial design we should be able to present our approach and then see whether it makes sense to contribute it to the community.
