### ISSUE TITLE
Cert Manager + Istio + Kubeflow + Azure + LetsEncrypt

### ISSUE THREAD

**Issue by pablofiumara-azumo** [kubeflow/pipelines#5815]
How can I setup SSL for a Kubeflow installation (using Istio and Cert Manager) on Azure? URL is https://mydns.westus.cloudapp.azure.com/

Thanks in advance

**Comment by DavidSpek** [comment]
I'm working together with @pablofiumara-azumo to get this solved, so the issue can be closed.

/close
