### ISSUE TITLE
[v2compat] wrong param passed when param contains JSON

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#5830]
### Environment

*  KFP SDK version: master branch

### Steps to reproduce

```python
import kfp
from kfp import dsl
from kfp.components import create_component_from_func


@create_component_from_func
def test(json_param: str):
    print(json_param)


@dsl.pipeline(name='bug-json-param')
def my_pipeline(
    json_param: str = '{"a":"b"}',
    value: str = 'c',
):
    test(json_param).set_display_name('test1')
    test('{"a":"' + f'{value}' + '"}').set_display_name('test2')


if __name__ == '__main__':
    kfp.Client().create_run_from_pipeline_func(
        my_pipeline,
        arguments={},
        mode=dsl.PipelineExecutionMode.V2_COMPATIBLE,
    )
```

I got the following log for `test2` task (`task1` is expected).
```
{\"a\":\"c\"}
```

### Expected result

```
{"a":"c"}
```

### Materials and Reference

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by Bobgy** [comment]
this is obviously a corner case we didn't think of for the "BEGIN-KFP-PARAM[...]END-KFP-PARAM" hack

**Comment by zijianjoy** [comment]
There is a corner case where we pass empty string to a component function: https://github.com/kubeflow/pipelines/pull/5938#discussion_r660498207.

In the example above, I passed empty string to `gcsPath` parameter, but I got `BEGIN-KFP-PARAM[]END-KFP-PARAM` within the component function. This behavior is unexpected to user, so recording this here.

**Comment by zijianjoy** [comment]
Currently FE implements a hack to workaround `MLPipeline UI Metadata` name conversion, we need to make sure to update frontend to remove the hack, once SDK has made corresponding change:

https://github.com/kubeflow/pipelines/pull/5961#discussion_r662785344

**Comment by Bobgy** [comment]
> Currently FE implements a hack to workaround `MLPipeline UI Metadata` name conversion, we need to make sure to update frontend to remove the hack, once SDK has made corresponding change:
> 
> [#5961 (comment)](https://github.com/kubeflow/pipelines/pull/5961#discussion_r662785344)

@zijianjoy we might consider keeping the sanitization in UI permanently, because artifact naming convention changed when going to KFP v2. In v2, we will no longer sanitize artifact names automatically.

**Comment by Bobgy** [comment]
After some investigation, I think I understood the root cause.

1. Compiler `json.dumps` when encoding runtime info
https://github.com/kubeflow/pipelines/blob/07ac566fcbaf12387e5e2bef89a029e5ef183ee6/sdk/python/kfp/compiler/v2_compat.py#L139-L141
   At this point, constant text will be encoded once, but text passed from parameters are written as "{{inputs.parameters.<name>}}", therefore they won't be JSON encoded. The difference is the root cause of this bug.
2. Launcher tries to JSON encode for the second time, because string value passed from parameters are not JSON encoded: https://github.com/kubeflow/pipelines/blob/bd6350dc2730514b53733be5890426b315d0eda9/v2/component/runtime_info.go#L83-L85
3. Launcher tries to JSON decode, but because of the difference in 1, some part of the parameters are JSON encoded for 1 extra time.

**Comment by Bobgy** [comment]
Therefore, I can think of two ways to fix:
* BEGIN-KFP-PARAM token should only be injected wrapping parameter placeholders, but I'm not sure whether further corner cases may exist.
* Design a new way to pass raw data, so that we do not need to play around with JSON encoding.

**Comment by Bobgy** [comment]
## Proposal

op.command + op.args will have the following sections:
1. args passed to kfp-launcher
2. a separator "--"
3. parameters in format "key1=value1", "key2=value2", ... (we need to assume keys cannot contain "=" character, is it a fair assumption?)
4. a separator "--" as end of arguments passed to launcher
5. (start of op.args) arguments of the original user program command + args

**Comment by zijianjoy** [comment]
> @zijianjoy we might consider keeping the sanitization in UI permanently, because artifact naming convention changed when going to KFP v2. In v2, we will no longer sanitize artifact names automatically in SDK.

I see, thank you for confirming!
