### ISSUE TITLE
[v2compat] support minio/s3 pipeline root for v2 python components

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#5838]
### Environment

*  KFP SDK version: head

### Steps to reproduce

1. run https://github.com/kubeflow/pipelines/blob/master/samples/test/lightweight_python_functions_v2_pipeline.py with minio pipeline root
2. it fails with

```
Traceback (most recent call last):
  File "/tmp/tmp.k9PitIcFpw", line 841, in <module>
    executor_main()
  File "/tmp/tmp.k9PitIcFpw", line 835, in executor_main
    function_to_execute=function_to_execute)
  File "/tmp/tmp.k9PitIcFpw", line 549, in __init__
    artifacts_list[0])
  File "/tmp/tmp.k9PitIcFpw", line 562, in _make_output_artifact
    os.makedirs(os.path.dirname(artifact.path), exist_ok=True)
  File "/usr/local/lib/python3.7/posixpath.py", line 156, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
F0611 06:22:43.823995       1 main.go:56] Failed to execute component: exit status 1
```

I further outputted v2 python component wrapper code and found that it only supports gs:// pipeline root:

![image](https://user-images.githubusercontent.com/4957653/121641507-d79fb900-cac1-11eb-95ca-221b4368bec9.png)

### Expected result

This pipeline should work regardless of pipeline root chosen.

### Materials and Reference

The current launcher contract for other types of storage is: https://github.com/kubeflow/pipelines/blob/a37ba15706f0f5c3e07afe42602a457c217e928c/v2/component/launcher.go#L472-L483

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by zijianjoy** [comment]
Thank you Yuan for the fix!

Validated artifact is created for minio path:

![7vZ3MV4RftpJiHy](https://user-images.githubusercontent.com/37026441/123294393-a6fc4e00-d4c9-11eb-97dd-b7f03779e9b7.png)
