### ISSUE TITLE
[samples] consistent main block for pipeline samples

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#5839]
### Feature Area

/area samples 

### What feature would you like to see?

I'd like to see a consistent __main__ block for pipeline samples.

### What is the use case or pain point?

Make samples easy to use with just `python xxxx.py`.

### Is there a workaround currently?

1. Use `dsl-compile` to compile a sample and run it
2. Edie the sample or copy the sample elsewhere to inject a `kfp.Client()` call

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by Bobgy** [comment]
I think the best experience is doing https://github.com/kubeflow/pipelines/issues/5381 first.

Then samples do not even need a main block.

To run a sample: `kfp run xxxxx.py`.
To compile a sample: `kfp compile xxxx.py`.

If env-specific args are needed (e.g. KFP host name), configure them as env vars / config files, so they are not needed in each `kfp` CLI run.

**Comment by chensun** [comment]
I suggest we keep v1_legacy mode as the default compilation mode for now. 
Some samples need to be updated, and some v2 compatible bugs needs to be fixed before it's ready to be the default mode in our sample. 

We have warning saying that v2 compatible is in beta state and many features may not work as expected. I think by the time we feel like we can remove this warning, then v2 compatible mode can be the default.

**Comment by Bobgy** [comment]
@chensun I think you made a great point!

Note that there are also v2 only samples, I think we should use v2 compatible mode for them as the default.

Therefore, the overall guideline is:
* any pipelines that work in v1 should default to compile in v1 legacy mode
* any pipelines that only work in v2 should default to compile to v2 compatible mode

Does this match your expectation?

**Comment by Bobgy** [comment]
Another Q: do we write main block as `kfp.Client().create_run_from_pipeline_func` or `kfp.Compiler().compile`?

create_run_from_pipeline_func requires some connection setup, so it has harder learning curve.
After finishing the config, it makes future iterations much easier (editing pipelines & resubmitting).

compile has minimum learning curve, just compile and then upload the compiled file in UI.
but it's cumbersome afterwards once the user knows how to use create_run_from_pipeline_func.

I haven't figured out the right default option by myself yet
