### ISSUE TITLE
[feature] Azure - Authenticating Kfp client using client id, secret id and tenant id

### ISSUE THREAD

**Issue by pablofiumara** [kubeflow/pipelines#5846]
Is that possible? Something like the following (point 3) but for Azure: https://www.kubeflow.org/docs/distributions/gke/pipelines/authentication-sdk/#connecting-to-kubeflow-pipelines-in-a-full-kubeflow-deployment

**Comment by zijianjoy** [comment]
cc @aronchick

**Comment by jtanios** [comment]
Can we re-open this issue? How can we authenticate a kfp client dynamically?
