### ISSUE TITLE
[frontend] [UI] [aws] [need help] Not able to retrieve the image to KFP UI from S3

### ISSUE THREAD

**Issue by dutingda** [kubeflow/pipelines#5848]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
Kubeflow pipeline runs normally, but the frontend is not working as expected.

*  KFP version:  1.1

### Steps to reproduce

By using the similar code in [`this example`](https://github.com/kubeflow/pipelines/tree/master/samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/visualize_html), I do not know how to do the configuration to let the UI have the access to S3 without making it public. 

<img width="1024" alt="Screen Shot 2021-06-11 at 2 27 51 PM" src="https://user-images.githubusercontent.com/38673967/121733706-d078ab00-cac1-11eb-8938-7d1e2a966c63.png">

### Expected result

It will show the image

### Materials and Reference

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by JODIN1727** [comment]
Thank you for your understanding

**Comment by JODIN1727** [comment]
No good PC and Tools to work on further. Need more times in learning more on how to smoothen enhanced works.

**Comment by dutingda** [comment]
@JODIN1727 Do you mean we do not have a solution to it now?

**Comment by JODIN1727** [comment]
It is moderately good to go as way out but need more times for tools to support

**Comment by dutingda** [comment]
I don't understand what you are trying to express here, please give comment directly answers the question

**Comment by capri-xiyue** [comment]
Currently we don't support this feature for security reason.
Workaround is to encode image and store it inline in html
