### ISSUE TITLE
"Waiting for the IAP setup to get ready..." after clicking "Skip IAP"

### ISSUE THREAD

**Issue by katherinez22** [kubeflow/pipelines#585]
I tried to create the deployment through the one-click system. 
[Screenshot of the set up](https://screenshot.googleplex.com/eEb9vVS6cHF)

Altough I skipped the IAP, the command line is hanging on "Waiting for the IAP setup to get ready...".

FYI, the GKE and Cluster have both sucessfully set up.

**Comment by kunmingg** [comment]
@TomNett 
Will fix in next version, should be available soon.
Thanks!

**Comment by yebrahim** [comment]
@kunmingg is this already fixed? Is there a kubeflow/kubeflow issue tracking it?

**Comment by kunmingg** [comment]
@yebrahim 
https://github.com/kubeflow/kubeflow/pull/2167

**Comment by kunmingg** [comment]
PR merged, will be available once image updated.

**Comment by yebrahim** [comment]
Great, thanks. Closing this one then.
/close
