### ISSUE TITLE
Unable to select the instance in kubeflow experiment

### ISSUE THREAD

**Issue by swamat** [kubeflow/pipelines#5855]
### What steps did you take

I have installed kubeflow 1.12 inAWS environment. Its running on EKS cluster with one gpu node and one cpu node

### What happened:
When am creating the kfp pipeline and creating run am unable to select the node(gpu/cpu) on which it can run 
### What did you expect to happen:
I can select the node on which it can run
### Environment:
AWS

*  How do you deploy Kubeflow Pipelines (KFP)? 
https://www.kubeflow.org/docs/distributions/aws/deploy/install-kubeflow/
*  KFP version: 1.12

*  KFP SDK version: 1.6.0

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by capri-xiyue** [comment]
You can use https://kubeflow-pipelines.readthedocs.io/en/stable/source/kfp.dsl.html?highlight=node#kfp.dsl.PipelineConf.set_default_pod_node_selector to add a constraint for nodeSelector for a pipeline.
You can use https://kubeflow-pipelines.readthedocs.io/en/stable/source/kfp.dsl.html?highlight=node#kfp.dsl.Sidecar.set_memory_limit to set the memory limit

**Comment by capri-xiyue** [comment]
Feel free to reopen the issue if you have further questions.

**Comment by swamat** [comment]
@capri-xiyue  Thank you
