### ISSUE TITLE
[backend] Dockerfile fails build

### ISSUE THREAD

**Issue by mishraprafful** [kubeflow/pipelines#5866]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
Not yet deployed

*  KFP version: Release v1.6.0

*  KFP SDK version: None

### Steps to reproduce
* Docker build `backend/dockerfile` fails with the following trail logs 
```bash
Setting up llvm-3.8 (1:3.8.1-24) ...
Setting up cmake (3.7.2-1) ...
Setting up llvm-3.8-dev (1:3.8.1-24) ...
Setting up clang-3.8 (1:3.8.1-24) ...
Setting up clang (1:3.8-36) ...
Processing triggers for sgml-base (1.29) ...
Processing triggers for libc-bin (2.24-11+deb9u4) ...
Removing intermediate container b0ebf531b1ac
---> a76cd53b1770
Step 3/36 : WORKDIR /go/src/github.com/kubeflow/pipelines
 ---> Running in 1e93112fe0a1
Removing intermediate container 1e93112fe0a1
 ---> d50ce7ad7ae0
Step 4/36 : COPY . .
 ---> 730bd4c847e8
Step 5/36 : RUN go mod vendor
 ---> Running in d94a1eeedc7f
268
go: cannot find main module; see 'go help modules'
```

### Expected result
* `backend` successfully built as a docker image

### Materials and Reference
Trying to build the backend service as a docker image, but it fails to build. 

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by capri-xiyue** [comment]
Did you build under root directory or under backend directory? You need to build under root directory

**Comment by mishraprafful** [comment]
Thanks @capri-xiyue. This was solved with your suggestions and a few other things we were doing wrong. 😄
