### ISSUE TITLE
[feature] Output artifacts from AI platform jobs and have them cached.

### ISSUE THREAD

**Issue by zygm0nt** [kubeflow/pipelines#5868]
### Feature Area

/area backend 
/area sdk 
/area samples

### What feature would you like to see?

Is it possible to cache steps in a pipeline if the output already exists? 

### What is the use case or pain point?

My scenario here is that I'm running a bunch of jobs with https://github.com/kubeflow/pipelines/tree/master/components/gcp/container/component_sdk/python/kfp_component/google/ml_engine (with Docker images) and if working on a specific pipeline need to constantly recalculate all the steps. This could be somewhat mitigated by creating a very small subset of the target data, but I'm wondering if there's a better approach here. 

I've found some indications that caching could solve this issue, but I don't see the connection here. Especially since AI platform jobs currently do not emit any artefacts.

### Is there a workaround currently?

The workaround I have for this right now is creating dummy jobs, that are fast to complete, but this is quite complex approach. 

Other one would be to have a relatively small subset of my data and iterate on that.

Both of theses approaches still need to rerun the whole pipeline over and over again.

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by capri-xiyue** [comment]
Can you share your pipeline?

**Comment by zygm0nt** [comment]
Hi, sorry for late reply.

So here is an illustrative example of my pipeline's behavior:

```
import kfp
from kfp import dsl
from kfp.dsl.types import GCSPath

from components.gcp.ml_engine_train import ml_engine_train_task_factory # this is our copy of https://github.com/kubeflow/pipelines/tree/master/components/gcp/container/component_sdk/python/kfp_component/google/ml_engine

def ml_job(task_id: str,
        endpoint: str,
        args: List[Tuple[str, Any]],
        master_type: str,
        gpu_type: Optional[str] = None
):
   return ml_engine_train_task_factory(
            ...
        ).set_display_name(task_id.replace("_", " "))


@dsl.pipeline(
    name="Content vectors training pipeline",
    description="Content vectors training pipeline",
)
def pipeline(
   input_path: GCSPath(),
   output_path: GCSPath(),
   output_path2: GCSPath(),
):

    infer_op = ml_job(
        task_id="infer",
        endpoint="make",
        args=[
            ("ifpath", input_path),
            ("ofpath", output_path),
        ],
        master_type="n1-highmem-16",
    )

    infer2_op = ml_job(
        task_id="infer",
        endpoint="make",
        args=[
            ("ifpath", output_path),
            ("ofpath", output_path2),
        ],
        master_type="n1-highmem-16",
    ).after(infer_op)
```

So, when I iterate over this pipeline, be it I need to change somewhat the pipeline internal parameters, or I have a bug along the pipeline, in the job itself, I always need to rerun the whole pipeline. 
What I'd like to do is:
* job `infer_op` passes, but `infer2_op` fails due to some error
* if I rerun the pipeline with the same parameters, then `infer_op` should find out that it already has the artifact (in this case `output_path`), and to silently skip `infer_op` (or mark as succeded), and run just `infer2_op`

So far I don't see how this could be done without a lot of manual code around each and every component. 
Any advice about to handle that kind of situation?

**Comment by Bobgy** [comment]
Hi @zygm0nt, to utilize cache, your pipeline / component inputs need to be the same each run.
Can you confirm?

Also, which Kubeflow distribution did you install? I've heard some that do not enable the caching feature.

**Comment by zygm0nt** [comment]
@Bobgy input params are the same in this case. I'm using the distribution provided by Google, deployable in GCP as AI Pipelines.

But this behaviour is about caching already run jobs, can this be extended to marking as finished jobs that have their outputs already calculated? Suppose I'm deploying a somewhat new pipeline, that has some steps borrowed from already running pipeline. There are some artifacts on GCS calculated by that previous pipeline, and I'd like the new pipeline to skip the steps due to already existing data.
