### ISSUE TITLE
CMLE/TFX failure: Exceeded the max allowed number of models per project: 100.

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#587]
```
run-notebook-tfx-tests:	<IPython.core.display.HTML object>
run-notebook-tfx-tests:	<HttpError 429 when requesting https://ml.googleapis.com/v1/projects/ml-pipeline-test/models?alt=json returned "Quota failure for project ml-pipeline-test. Quota failure for project 363997316495. Exceeded the max allowed number of models per project: 100. To read more about Cloud ML Engine quota, see https://cloud.google.com/ml-engine/quotas. To read more about Cloud ML Engine quota, see https://cloud.google.com/ml-engine/quotas.">

```
/assign @gaoning777

**Comment by gaoning777** [comment]
Thanks. The problem could be the models are left uncleaned for certain reasons.

**Comment by Ark-kun** [comment]
> Thanks. The problem could be the models are left uncleaned for certain reasons.

I do not remember any model cleanup code at all...

**Comment by Ark-kun** [comment]
Script to remove all model versions:

`gcloud ml-engine models list --project ml-pipeline-test | xargs -n 1 -P 8 gcloud ml-engine versions delete beta --quiet --project ml-pipeline-test --model`

**Comment by gaoning777** [comment]
resolved in https://github.com/kubeflow/pipelines/pull/622
