### ISSUE TITLE
[feature] Support specifying a pipline version when uploading a new pipeline

### ISSUE THREAD

**Issue by jmendesky** [kubeflow/pipelines#5881]
### Feature Area

/area backend 
/area sdk

### What feature would you like to see?

Currently, when uploading a new pipeline, no version can be specified and the name of the pipeline is used to create an initial version. Uploading a pipeline version without first creating a pipeline by uploading that initial version will fail. This is not intuitive and breaks automation or requires workarounds like first uploading the initial version and then creating the proper version.

### What is the use case or pain point?

We are currently building automation and continuous deployment around our ML infrastructure. As part of this, we want all of our pipelines to be versioned so that code changes can be tracked consistently. This should also be true when creating a new pipeline with the first version.

### Is there a workaround currently?

upload pipeline ( => version == name)
upload version  (=> version == 'abcdef')
delete version 'name'

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by capri-xiyue** [comment]
option 1: upload version api can accept pipeline line
option 2: combine upload pipeline and upload version in one api, which means user can specify pipeline and version at the same time.

**Comment by jmendesky** [comment]
> option 1: upload version api can accept pipeline parameter
It already accepts the pipeline name or id as a parameter. Do you mean that this could be optional so that the pipeline would be created if not present?
> option 2: combine upload pipeline and upload version in one api, which means user can specify pipeline and version at the same time.
I think something like this makes sense. Specifying the version when uploading would be of great benefit. We could still keep the default option of setting the version to the pipeline name if no version is specified.

**Comment by jmendesky** [comment]
any news on this?
