### ISSUE TITLE
[backend] column name same with reserved keyword of mysql 8.0

### ISSUE THREAD

**Issue by algs** [kubeflow/pipelines#5893]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
* create table in mysql and deploy the KFP services

*  KFP version: 
* 1.5

*  KFP SDK version: 

### Steps to reproduce
When creating table in mysql 8.0, it would report fail because there are columns name `Description` in tables `experiments`, `jobs`, `pipelines`, `run_details`, which is the reserved keyword of mysql

### Expected result
Creating tables without error.

Shall we use `Descriptions` as the columns' name?

### Materials and Reference

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

cc @Jeffwan

**Comment by Bobgy** [comment]
https://dev.mysql.com/doc/refman/8.0/en/keywords.html
It says description is a nonreserved keyword, am I missing anything?

Welcome contribution if anyone figures out how to deploy KFP with mysql 8.0

**Comment by algs** [comment]
> https://dev.mysql.com/doc/refman/8.0/en/keywords.html
> It says description is a nonreserved keyword, am I missing anything?
> 
> Welcome contribution if anyone figures out how to deploy KFP with mysql 8.0

It's been covered in [MySQL 8.0 New Keywords and Reserved Words](https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-new-in-current-series)

**Comment by NikeNano** [comment]
I have tried it out with MySQL 8 and [got it working](https://github.com/NikeNano/pipelines/tree/nikenano/mysql8), some [very minor things](https://stackoverflow.com/questions/49945091/latest-mysql-not-coming-up-in-kubernetes/49952285) needed to change. I can make a PR with it, could you point me to how we build the images for gcr @Bobgy?

As @Bobgy points out `description` is a `non-reserved` keyword:

```
DESCRIPTION; added in 8.0.4 (nonreserved)
```

and 

```
Nonreserved keywords are permitted as identifiers without quoting. Reserved words are permitted as identifiers if you quote them as ...
```

Source: https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-new-in-current-series. Maybe you could try to check out the branch @algs and see if it work for you? Let me know if you have any questions so I can help out.

**Comment by Bobgy** [comment]
Access to gcr is restricted to admins. I can help you upload : )

**Comment by sidpalas** [comment]
FWIW, I have successfully deployed KFP 1.5.0 on GKE with MySQL 8 running in CloudSQL. 

I haven't done much testing yet but was able to successfully run some pipelines and store the associated data.

**Comment by NikeNano** [comment]
> FWIW, I have successfully deployed KFP 1.5.0 on GKE with MySQL 8 running in CloudSQL.
> 
> I haven't done much testing yet but was able to successfully run some pipelines and store the associated data.

Awesome, let me know if you get some issues!

**Comment by rimolive** [comment]
Closing this issue as it seems fixed.

/close
