### ISSUE TITLE
[feature] Automatically json serialize pipeline run arguments that are of type list or dict

### ISSUE THREAD

**Issue by Eliacus** [kubeflow/pipelines#5896]
### Feature Area

 /area sdk 

### What feature would you like to see?
This feature concerns having list/dict inputs to pipelines when running them with the SDK. Right now, when starting runs with the python SDK, one must manually serialize lists to json, otherwise it will get falsely serialized and it can't be passed to components properly.

It would be nice if the `arguments` input to `client.create_run_from_pipeline_func` or the `params` input to `run_pipeline` could automatically json serialize values whos type is list/dict

### What is the use case or pain point?
The pain point is that this is a hard issue to track down, and it's unintuitive to have list/dict inputs to pipelines and running them from a python script

### Is there a workaround currently?

The current workaround is to manually use `json.dumps()` on any lists in the input argument to the run

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by Bobgy** [comment]
Agree the feature would be a nice to have!
Welcome contribution on this

**Comment by Eliacus** [comment]
Created a small fix and opened a pull request in https://github.com/kubeflow/pipelines/pull/5927
