### ISSUE TITLE
[bug] outputUri prevents caching

### ISSUE THREAD

**Issue by boarder7395** [kubeflow/pipelines#5897]
### What steps did you take

Ran a pipeline with an outputUri, and ran a pipeline with an outputValue.

### What happened:

The pipeline using outputValue cached the component correctly, while the pipeline using outputUri did not cache the component.

### What did you expect to happen:

I expected both pipelines to cache.

### Environment:

KFP 1.4.1
Launched with minikube locally. Also so similar behavior with KFP on EKS.

*  How do you deploy Kubeflow Pipelines (KFP)? 

*  KFP version: 
1.4.1

*  KFP SDK version: 
1.6.3

### Anything else you would like to add:
I'm not sure if caching support has been added to outputUri's yet so it could be that functionality has not yet been added for outputUri's.

### Labels
/area backend

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by Bobgy** [comment]
Hi @boarder7395, we are redesigning caching, see https://github.com/kubeflow/pipelines/issues/5667.
The problem will be solved with the brand new caching mechanism that understands KFP semantics.

**Comment by Bobgy** [comment]
The issue you reported is expected, and we'll not fix because of v1 caching design limitations.
