### ISSUE TITLE
kfp.components.structures.ComponentsSpec to create run in kubeflow

### ISSUE THREAD

**Issue by swamat** [kubeflow/pipelines#5900]
### Environment

*  KFP version:1.2

*  KFP SDK version: 1.6.0

*  All dependencies version:

### Steps to reproduce

 I am currently using containerop to create pipeline functions. But I see warnings saying that it will be deprecated. Is there any equivalent kfp package which uses docker image.? I tried kfp.components.structures.ComponentsSpec but this does not get executed. Created componentsspec, saved the yaml file and tried to load using load_component_from_file inside pipeline. Though the run gets triggered, it does not execute the module

### Expected result

Expected the run to happen executing the module

### Materials and Reference
 I am currently using containerop to create pipeline functions. But I see warnings saying that it will be deprecated. Is there any equivalent kfp package which uses docker image.? I tried kfp.components.structures.ComponentsSpec but this does not create container pods and am unable to see the logs as well

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by swamat** [comment]
Did kfp.components.structures.ComponentsSpec.save() and loaded the yaml file.. But unable to get how to pass file outputs from one component to other component.Right now we are using
 **kfp.components.structures.InputSpec(name=<file name which was output of the previous component> )**
This  shows below error
TypeError: Arguments for output is not compatible with type
can someone please help on this

**Comment by Bobgy** [comment]
Hi @swamat, we do not document ComponentsSpec very well. I'd recommend learning https://www.kubeflow.org/docs/components/pipelines/sdk/component-development/. They are the same format in different languages (python vs yaml)
