### ISSUE TITLE
How to use customized name of the component(pre build component) used in kubeflow.

### ISSUE THREAD

**Issue by motilalmeher** [kubeflow/pipelines#5901]
I am using GCP ml traning and deploying prebuild component for training and deployment. In my kubeflow pipliline, I am using multiple models for hyperparameter tuning and final model traing on best set of parameters. But I can not able to add a name to the pre build component. So in pipeline dashboard, every training component have same name. I want to add name by my own like for logistic regression model, I want different name and for other model like random forest, i want to give another name. So that from UI , I can able to know which component is for what.

**Comment by Bobgy** [comment]
Hi @motilalmeher, you can refer to https://github.com/kubeflow/pipelines/blob/d9c019641ef9ebd78db60cdb78ea29b0d9933008/samples/core/continue_training_from_prod/continue_training_from_prod.py#L63 which sets a display name for different tasks.
