### ISSUE TITLE
Gcp Ml training and deploying prebuild component from on premise

### ISSUE THREAD

**Issue by motilalmeher** [kubeflow/pipelines#5902]
In kubeflow prebuild component(Gcp Ml training and deploying) there is no option for giving credential to use AI platform of a GCP for training and deployment purpose from on premise. How to handle that? Do we need to write our customize code for traing job and deplying job?

**Comment by Bobgy** [comment]
Hi @motilalmeher, you can find how to mount GCP service account credentials in doc: https://www.kubeflow.org/docs/distributions/gke/pipelines/authentication-pipelines/#authoring-pipelines-to-use-gsa-keys
