### ISSUE TITLE
[sdk] Error from kfp Client 

### ISSUE THREAD

**Issue by shalankig** [kubeflow/pipelines#5907]
I have successfully deployed Kubeflow on a private GKE Cluster using https://github.com/kubeflow/manifests#install-with-a-single-command

GKE Version: 1.17.17-gke.9100
Kubeflow Version: 1.3
Workload Identity Enabled: Yes
Kfp Version: 1.5.0

Error while creating a kubeflow pipeline:
`Traceback (most recent call last): File "/path/to/pipeline.py" line 1073, in run_pipeline experiment_id = client.get_experiment(experiment_name=experiment_name).id File "/usr/local /lib/python3.7/dist-packages/kfp/client.py", line 359 in get_experiment list_experiments_response = self.list_experiments(page_size=100, page_token=next_page_token, namespace=namespace).............ApiException(http_resp=r) kfp_server_spi.exceptions.ApiException: (400) `

which further leads to the below error logs:
`HTTP: response body: {"error":"Validate experiment failed: Invalid input error: Invalid resource references for experiment. Expect one namespace type with owner relationship. Got []","code":3, "message":"Validate experiment failed: Invalid input error: Invalid resource references for experiment. Expect one namespace type with owner relationship. Got []", "details":[{"@type":"type.googleapis.com/api.Error","error_message":"Invalid resource references for experiment. Expect one namespace type with owner relationship. Got []","error_details":"Validate experiment failed: Invalid input error: Invalid resource references for experiment. Expect one namespace type with owner relationship. Got []"`

**Comment by midhun1998** [comment]
Hi @shalankig . Could you share your code to help us debug even further? From the above log, I think you are referring to a kfp experiment that doesn't exist or you might have missed to pass the namespace.

**Comment by Bobgy** [comment]
Hi @shalankig, did you specify namespace for your call? In KFP multi-user mode, namespace is required for each pipeline run (and experiment creation).

I guess the error message needs some improvement.
