### ISSUE TITLE
Pass pandas dataframe from one component to other without writing and reading

### ISSUE THREAD

**Issue by motilalmeher** [kubeflow/pipelines#5917]
I am currently working with a large dataset and in my pipeline there are many component. I want to make the process fast. Currently I am passing the data from one component to ther by storing it some storage and passing the path so that I can read the data from other component. Is there any way to pass the Pandas dataframe like passing strings.

**Comment by capri-xiyue** [comment]
I think argo does not support panda frame. As a workaround, can the user store panda dataframe in an artifact? @Bobgy  Can you confirm?

**Comment by Bobgy** [comment]
Thanks @capri-xiyue for the heads up!

IIUC, @motilalmeher is already writing the data to a storage as an artifact.

For clarification, the major reason data have to be in a storage between steps is that each step may run in a different node, so there has to be a way to pass the data.

Therefore @motilalmeher 's request implies that we need a way to run multiple components in one single Pod and avoid intermediate data passing using a remote storage.

I believe with argo v3.1 emissary executor and the support for container DAG in a single Pod, we are much closer to be able to implement this feature.

I'd like to know more feedback both from you and others about possible use cases for this feature.

**Comment by dashanji** [comment]
Hi @motilalmeher. For this problem, you might as well try our integrations, it may be helpful. Thanks.

https://medium.com/cncf-vineyard/optimizing-data-sharing-in-kubeflow-pipelines-358be85bc00e
