### ISSUE TITLE
TFMA output is empty

### ISSUE THREAD

**Issue by paveldournov** [kubeflow/pipelines#592]
The output of TFMA step is empty. It is expected to show the model analysis UI with data slice selection and model prediction charts.
![hvs5gw0fjly](https://user-images.githubusercontent.com/4884947/50440572-ae681f80-08ab-11e9-91c8-05f1ce11f56f.png)

(release 0.1.6)

**Comment by Ark-kun** [comment]
/assign @yebrahim 
I guess this is related to the UI metadata, not metrics.

**Comment by yebrahim** [comment]
@Ark-kun why do you guess so? We didn't change anything about the web-app metadata recently, but I guess we'll need to see the json to debug this properly.

**Comment by martin-laurent** [comment]
I can reproduce the issue on Firefox (64.0) but on Google Chrome (v 71.0.3578.98) the correct information is displayed (looking at the exact same step).

**Comment by yebrahim** [comment]
@martin-laurent this is possibly a bug in the TFMA component: https://github.com/tensorflow/model-analysis/issues/17. We need to update our TFMA version to the latest, which might fix this bug.
To confirm, can you check the browser's dev tools, point them to the iframe that should contain the TFMA component, and see if the file vulcanized_template.html has loaded? If not, then it's the issue I referenced above.

@paveldournov was this on Chrome or FF?

**Comment by martin-laurent** [comment]
@yebrahim Indeed, I don't see `vulcanized_template.html` in the files loaded (on click on the artifacts tab for TFMA). Here is the list of things loaded:
<img width="557" alt="screen shot 2019-01-07 at 3 43 13 pm" src="https://user-images.githubusercontent.com/17744754/50774243-33334000-1293-11e9-8e39-4f3cef6a82f9.png">

**Comment by vicaire** [comment]
Resolving since inactive for several months. Please reopen if needed.
