### ISSUE TITLE
Enable sorting by status in the UI

### ISSUE THREAD

**Issue by midhun1998** [kubeflow/pipelines#5920]
### Feature Area

More of a productivity improvement. 🚀 
/area frontend 

### What feature would you like to see?
Enable sorting by status for runs under the Experiment and Runs section of UI which would filter all Running pipelines to the top.

### What is the use case or pain point?
Currently, the Kubeflow pipeline experiment UI only sorts based on start time. But sometimes when there are a lot of pipelines running in the same experiment the running ones tend to be below completed ones which makes it difficult to search for a running pipeline especially when recurring runs have been configured. This feature will enable users to find and track pipelines quicker. 

### Is there a workaround currently?
No workarounds were found. At present, we manually search for the running ones.

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by zijianjoy** [comment]
We can use `filter` to obtain runs by specifying states: https://github.com/kubeflow/pipelines/blob/master/backend/api/filter.proto#L81-L88

**Comment by rimolive** [comment]
/close

Duplicate of #4954
