### ISSUE TITLE
[feature] Multi-User Pipeline Definition Isolation

### ISSUE THREAD

**Issue by ILLUM1N0X** [kubeflow/pipelines#5925]
Hey guys,

According to the [official documentation](https://www.kubeflow.org/docs/components/pipelines/multi-user/#current-limitations), Pipeline definitions are not isolated currently.

**What feature would you like to see?**
I would like to see Pipeline isolation similar to what we have in Notebooks/Runs/Experiments.

**What is the use case or pain point?**
The way Pipelines are exposed currently allows the deletion of Pipelines owned by other users.

**Is there a workaround currently?**
Not that I am aware of.

Are there intentions to add this to future versions?

Thanks

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by edwardzjl** [comment]
Same problem here, we followed the [manifests](https://github.com/kubeflow/manifests#kubeflow-pipelines) and deployed pipeline with multi-user support, but still all pipelines are public to everyone.

**Comment by edwardzjl** [comment]
Not stale

**Comment by koalalorenzo** [comment]
Any update?
