### ISSUE TITLE
Deployer component to output model URL

### ISSUE THREAD

**Issue by paveldournov** [kubeflow/pipelines#593]
The model deployment components has to output the model endpoint URL as an output parameter to be shown in Input/Ouput tab.

**Comment by vicaire** [comment]
Is this working now? Can it be closed?

**Comment by hongye-sun** [comment]
This has been covered by the new deploy component: https://github.com/kubeflow/pipelines/tree/master/components/gcp/ml_engine/deploy

The component outputs: a) the found gcs path to the model file; b) the full version resource name
It also display online prediction instructions in a markdown viewer which demonstrate the command line and oauth playground link to invoke online prediction.
