### ISSUE TITLE
[bug] <run Tutorial failed>

### ISSUE THREAD

**Issue by hellobiek** [kubeflow/pipelines#5948]
when I run this tutiol：Run of [Tutorial] Data passing in python components 

I met the error msg as follows:  This step is in Error state with this message: failed to save outputs: key unsupported: cannot get key for artifact location, because it is invalid

![Uploading 截屏2021-06-30 上午10.38.40.png…]()

**Comment by hellobiek** [comment]
new info: could not chroot into main for artifact collection

**Comment by capri-xiyue** [comment]
1. Can you help uploading the screenshot of error msg again?(You didn't upload it successfully)
2. Which KFP version are you using?
3. Which storage(minio, aws or gcp  XXX)provider do you choose for artifact storage?

**Comment by zijianjoy** [comment]
Hello @hellobiek , I am able to run `[Tutorial] Data passing in python components` successfully. Would you like to confirm the cluster provider you use and Kubernetes version as well?

**Comment by hellobiek** [comment]
using minio

**Comment by hellobiek** [comment]
fixed by myself

**Comment by OmriShiv** [comment]
> fixed by myself

Do you mind posting your fix? I'm wondering if I'm running into a similar issue
