### ISSUE TITLE
[v2compat] UI features for cached tasks (size/S)

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#5977]
For cached tasks, the following are helpful on UI:

- [x] *  cached status icon
- [x] * a link to cached execution
- [ ] * (p1) a link to original execution this cache is taken from
- [ ] * (p2) the original execution should have a link to the original run (deleting the original run will invalidate cache)
- [x] * (p2) the run details page should ideally support using url hash to select a node, so that we can generate a URL that directly selects a node in a run details page

**Comment by capri-xiyue** [comment]
Discussed with @zijianjoy  offline,
Currently with v2 compatible mode, 

- cached status icon
- a link to cached execution
The above tasks can be achieved now.

For the following tasks, currently we can't fetch original execution with current logic in launcher.(Maybe via a custom property called `cached_execution_id`
We may need to store the original mlmd execution id in the cache mlmd execution first. I'm not sure whether we need to support these in v2 compatible mode. I think these features will be useful to users once we support cache staleness. 
For my perspective, we can defer these two tasks until we support cache staless. @Bobgy What do you think of it?

- (p1) a link to original execution this cache is taken from
- (p2) the original execution should have a link to the original run (deleting the original run will invalidate cache)

**Comment by zijianjoy** [comment]
I think it will be great to describe the user scenario for referencing original execution from cached execution. Based on the discussion, looks like there is no cache management exposed to user in v2 compatible mode, so the linking from cached execution to original execution is informational at this point, and help user to understand more about the caching mechanism (debugging).

The solution with custom property `cached_execution_id` should work, but I suggest to get confirmation from the team about defining this field, so we can avoid changing/removing this property in the future, where FE needs to support property field compatibility across versions.
