### ISSUE TITLE
[v2compat] key samples to show off new features

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#5987]
Samples:
* [ ] Consume artifact by URI sample (use tfjob etc)
* [ ] Support for components that can produce/consume MLMD metadata
* [ ] Visualize v2 metrics -- components can output metrics artifacts that are rendered in UI. [Sample pipeline](https://github.com/kubeflow/pipelines/blob/307e91aaae5e9c71dde1fddaffa10ffd751a40e8/samples/test/metrics_visualization_v2.py#L103) (UI not working)
* [ ] Pipeline root documentation

**Comment by chensun** [comment]
Closing as v2 compatible mode is no longer supported.
