### ISSUE TITLE
Add the ability to delete experiment.

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#60]

**Comment by amygdala** [comment]
+1 to this being important.

**Comment by IronPan** [comment]
API would provided as part of this https://github.com/kubeflow/pipelines/pull/112

**Comment by yebrahim** [comment]
More context from @IronPan: That API orphans the deleted experiment's runs though, it doesn't delete them.
This is fine for now, but if we don't also offer a delete run API, the All runs view will be cluttered with all the orphaned runs.

@ajayalfred any thoughts here? What do you think of this as a starting point?

**Comment by ajayalfred** [comment]
Since runs are organized inside experiments, a user would expect deleting an experiment to delete the runs contained as well. I don't see a usecase where the user will expect this to behave otherwise and produce orphaned runs.

A delete run API is still needed for the case when a user wants to delete an individual run/set of runs inside an experiment.

Does that make sense?

**Comment by animeshsingh** [comment]
Ho folks - any progress on this one?

**Comment by yebrahim** [comment]
I don't think we have anyone working on this, feel free to pick up the discussion if you feel like it.
There is however some work I'm doing now to support archiving runs, which should help declutter the workspace. Experiments are still create-only though.

**Comment by JohnPaton** [comment]
+1 on this, in a multi-user settings experiments will pile up quickly

**Comment by Ark-kun** [comment]
> +1 on this, in multi-user settings experiments will pile up quickly

The solution to this is probably a default filter that only shows your own experiments.

**Comment by yaronha** [comment]
@ark-kun maybe we should have labels based filter, people can add labels like owner, project,..

**Comment by Ark-kun** [comment]
> maybe we should have labels based filter, people can add labels like owner, project,..

I like this approach.

**Comment by wcass77** [comment]
What if instead of deleting, we just had an option to archive, like with runs. There should also be an option to archive pipelines. That way no metadata is lost, but old experiments are out of the way

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by FaustineLi** [comment]
Why not allow archiving / deleting for experiments with no unarchived runs? Would be interested in this feature.

**Comment by Ark-kun** [comment]
> no metadata is lost, but old experiments are out of the wa

Would showing the experiments with recent runs first solve your issues? https://github.com/kubeflow/pipelines/issues/249

**Comment by FaustineLi** [comment]
> > no metadata is lost, but old experiments are out of the wa
> 
> Would showing the experiments with recent runs first solve your issues? #249

Probably. I just want to hide the experiments that aren't relevant to me. The filter ideally should only show experiments you create by default too (in the situation where multiple scientists are sharing a cluster).

**Comment by Bobgy** [comment]
Closing this as a duplicate of https://github.com/kubeflow/pipelines/issues/1263
We plan to support archiving experiments in KFP 1.0
