### ISSUE TITLE
[pH] prepare KFP for K8s 1.22

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#6014]
Deprecated APIs in k8s 1.22: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22

TODOs:
* [x] move CRDs to v1 version: https://github.com/kubeflow/pipelines/search?q=apiextensions.k8s.io%2Fv1beta1&type=  #6679
* [x] move cluster role and cluster role binding to v1 version, got warning message:
    ```
    Warning: rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
    ```
* [x] Upgrade third-party dependencies to a version with v1 crd, including application controller and metacontroller

**Comment by Bobgy** [comment]
I think we need to plan this for the next release.

**Comment by jli** [comment]
Hi KFP team, my team uses GKE and we got an email from GCP today: "[Action Required] Prepare for GKE 1.22 Open source upstream beta API Removal". The email includes:

> As of Kubernetes 1.22, API clients will no longer be able to use previously deprecated Beta API versions. Manifests using those versions will no longer be able to be applied.

Based on the [GKE release schedule](https://cloud.google.com/kubernetes-engine/docs/release-schedule), seems like k8s 1.22 is already available for the "rapid" release channel, and will affect the "regular" release channel in November 2021 (my team is on "regular", which I believe is the default and what most GKE users are likely using).

If I understand correctly, this means when our GKE cluster is updated to 1.22, then we won't be able to deploy *any* current version of KFP to it. And, even if the next KFP release (1.8) is updated, we won't be able to roll back to pre-1.8 KFP versions if we encounter any issues with the new release. Does that match your understanding?

If so, I think it's important to have a new KFP release soon so users can test it before GKE starts updating users' clusters to 1.22.

**Comment by zijianjoy** [comment]
Note: Application currently only has v1beta1 version: https://github.com/kubernetes-sigs/application/blob/master/config/crd/bases/app.k8s.io_applications.yaml#L46

**Comment by zijianjoy** [comment]
All manifests are upgraded to v1. I have personally deployed to a k8s 1.22 cluster and have validated the deployment.
