### ISSUE TITLE
[bug] Pipeline does not retain the logs as an artifact for failed/crash component: Failed to retrieve pod logs

### ISSUE THREAD

**Issue by jalola** [kubeflow/pipelines#6033]
### What steps did you take

1. Create a pipeline
2. Make a component with some bug so it will crash later in the pipeline
3. Run the pipeline until the component fail
4. Wait for the pod to be deleted

### What happened:
5. Check the Logs tab of that pod, it shows "Failed to retrieve pod logs."
6. Check the Input/Output of that pod, no main logs was saved

### What did you expect to happen:
I think 5 is expected because it get the logs directly from the Pod so when the Pod is deleted, the logs cannot be retrieved
But for 6, I think it should have the main-logs (main.log) so we can know what is wrong with the code

### Environment:

*  How do you deploy Kubeflow Pipelines (KFP)? 
Kubeflow manifest v1.3 bu kustomize 
https://github.com/kubeflow/manifests/tree/v1.3-branch

*  KFP version: 
build version dev_local

*  KFP SDK version: 
1.6.3

### Anything else you would like to add:

I notice that, 
If the pipeline failed because of a bug or manually terminate (error message: "This step is in Failed state with this message: failed with exit code 1" or "This step is in Failed state with this message: failed with exit code 137"), I cannot see the main-logs

If The component failed with error message "This step is in Failed state with this message: Step exceeded its deadline", the main-logs is there after the pod deleted

### Labels

/area backend 

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by zijianjoy** [comment]
Hello @jalola , this is related to Argo workflow issue, would you like to create an issue there to resolve this problem? https://github.com/argoproj/argo-workflows

**Comment by jalola** [comment]
Thanks @zijianjoy 
There is an issue related: https://github.com/argoproj/argo-workflows/issues/6201
