### ISSUE TITLE
[feature] Return a list of runs' metadata including run parameters sorted by run details

### ISSUE THREAD

**Issue by dutingda** [kubeflow/pipelines#6048]
### Feature Area

 area sdk 

### What feature would you like to see?

I just need help about the query the above result, is there a way to do that?
I need to query the list of runs that is filtered by the start time and get the metadata
of the run parameters for all the runs. But not sure about which SDK I need to use 
and how it should be used since the documentation does not provide enough details
of one possible API I can used (`list_runs`)

### What is the use case or pain point?

For the need of cleaning up the least recently used cache of the data I used stored in the PVC

### Is there a workaround currently?

Not sure

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by Bobgy** [comment]
Hi @dutingda, you can follow this example for filtering (same feature exists for runs too): https://www.kubeflow.org/docs/components/pipelines/tutorials/sdk-examples/#example-2-listing-pipelines-with-a-filter.

Please let us know what's missing from documentation and feature

**Comment by dutingda** [comment]
So what should be the key if I want to filter by start time and what should be the return value of this filter.

**Comment by dutingda** [comment]
@Bobgy How do I read the response object type and what is the type?

**Comment by Bobgy** [comment]
/assign @zijianjoy 
Can you help answer this question?
Thanks

**Comment by zijianjoy** [comment]
Hello @dutingda , 

- API definition for `list_runs`: https://kubeflow-pipelines.readthedocs.io/en/stable/source/kfp.server_api.html#kfp_server_api.api.run_service_api.RunServiceApi.list_runs
- Fields for time related filter: `created_at`, `finished_at`,  `scheduled_at`. Format of time value is `2021-08-26T23:00:34Z`.
- kfp 1.0.0 seems to be too old. You can find the new versions in https://pypi.org/project/kfp/#history. But makes sure you use the corresponded version of KFP backend too.
