### ISSUE TITLE
[frontend] Metrics not getting displayed in kubeflow UI after changing the storage to s3

### ISSUE THREAD

**Issue by swamat** [kubeflow/pipelines#6049]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?https://www.kubeflow.org/docs/distributions/aws/deploy/install-kubeflow/
kubeflow 1.2 on aws

*  KFP version: 1.0.1

### Steps to reproduce

The artifacts were getting stored in minio initially. Changed the storage to s3. After that am unable to see the metrics in run output

### Materials and Reference https://www.kubeflow.org/docs/distributions/aws/

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by Bobgy** [comment]
This is a current limitation. Welcome contributions!

**Comment by Bobgy** [comment]
Related code:
* persistence agent calls read artifact API in backend to read metrics artifacts: https://github.com/kubeflow/pipelines/blob/fff62e1521e89dd31c87eec03073b8f8627d73a3/backend/src/agent/persistence/worker/metrics_reporter.go#L149
* read artifact API gets object using the object store: https://github.com/kubeflow/pipelines/blob/fff62e1521e89dd31c87eec03073b8f8627d73a3/backend/src/apiserver/resource/resource_manager.go#L1163
* we only support the minio object store: https://github.com/kubeflow/pipelines/blob/fff62e1521e89dd31c87eec03073b8f8627d73a3/backend/src/apiserver/storage/object_store.go#L81
