### ISSUE TITLE
[sdk] building google_cloud_pipeline_components does not include YAML files

### ISSUE THREAD

**Issue by helinwang** [kubeflow/pipelines#6059]
### Steps to reproduce

Follow the instructions at https://github.com/kubeflow/pipelines/tree/master/components/google-cloud
e.g.,
```
source_root=$(pwd)

git clone https://github.com/kubeflow/pipelines.git
cd pipelines/components/google-cloud
python setup.py bdist_wheel clean

WHEEL_FILE=$(find "$source_root/pipelines/components/google-cloud/dist/" -name "google_cloud_pipeline_components*.whl")
pip3 install --upgrade $WHEEL_FILE
```
The resulting wheel file does not include the yaml files.

**Comment by helinwang** [comment]
The package from `pip install google_cloud_pipeline_components` does not include YAML files. But there should be YAML file in the SDK. E.g., https://github.com/kubeflow/pipelines/blob/master/components/google-cloud/google_cloud_pipeline_components/experimental/gcp_launcher/component.yaml

**Comment by helinwang** [comment]
I found a way, need to include lines like
    package_data={'google_cloud_pipeline_components': ['google/automl/tabular/*.yaml']},
in setup.py, reference: https://screenshot.googleplex.com/BFyR2qutgQs9GdH

I think we need to add the intended yaml.

**Comment by SinaChavoshi** [comment]
Thank you for raising this issue. fixed by https://github.com/kubeflow/pipelines/pull/6066
