### ISSUE TITLE
[frontend] console errors like "Unable to find corresponding tab name for MANIFEST" in run details page

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#6065]
/assign @zijianjoy 

there is an error message for each enum

```
Unable to find corresponding tab name for ML_METADATA
Unable to find corresponding tab name for POD 
```

**Comment by Bobgy** [comment]
I think the problem happens in the line
```
    for (let tab in SidePanelTab) {
```

In typescript, an enum object also contains look up map for the string -> enum conversion, so 'MANIFEST', 'INPUT_OUTPUT', each enum key is also iterated here.

**Comment by zijianjoy** [comment]
That is a good catch, thank you @Bobgy !

I created a PR to fix this: https://github.com/kubeflow/pipelines/pull/6077
