### ISSUE TITLE
Istio injection always disabled

### ISSUE THREAD

**Issue by karlschriek** [kubeflow/pipelines#6067]
While trying to put together a Kubeflow distribution that includes as many as possible elements inside the Istio mesh, we found that for Kubeflow Pipelines steps the istio sidecar injection is always overriden to "false". 

(This would for example make it impossible for a pipelines step to make calls to a KFServing model in the same namespace which has an istio sidecar enabled).

This seems to be hardcoded here:

https://github.com/kubeflow/pipelines/blob/fff62e1521e89dd31c87eec03073b8f8627d73a3/backend/src/apiserver/resource/resource_manager.go#L384

I presume that was done because the Pipelines owner are very sure that KFP would not work with injection enabled. As far as I know, newer versions of Argo Workflows should now support it.

Could we turn this into an ENV var?

**Comment by zijianjoy** [comment]
Can it be resolved by adding istio injection label to true as https://github.com/kubeflow/manifests/pull/1153?

cc @Bobgy to confirm the use case.

**Comment by Bobgy** [comment]
@karlschriek which argo executor supports Istio sudecars?

From what I learned from https://argoproj.github.io/argo-workflows/sidecar-injection/. It seems that Istio sidecar injection is still not supported.

**Comment by karlschriek** [comment]
The Argo Workflows team seem to be of the opinion that it should work with v3 onward, though I also cannot find a PR or release note that specifically mentions it, but the issue https://github.com/argoproj/argo-workflows/issues/1282 was closed with a note that this should now be supported. @Bobgy I just saw that you also asked for clarification there!

**Comment by alexec** [comment]
I've updated https://github.com/argoproj/argo-workflows/blob/master/docs/sidecar-injection.md with more detail for you.
