### ISSUE TITLE
[feature] Parameter parity in AIPlatformClient functions

### ISSUE THREAD

**Issue by axelmagn** [kubeflow/pipelines#6085]
### Feature Area

/area sdk

### What feature would you like to see?

`AIPlatformClient.create_run_from_job_spec` accepts parameters such as `labels` and `network` that are not accepted by `AIPlatformClient.create_schedule_from_job_spec`.  I think that any parameter I can specify in `create_run` should be specifiable in `create_schedule`.

### What is the use case or pain point?

 I would like to be able to specify `labels` for my scheduled jobs in order to enforce an organization regime on my pipeline jobs. 

### Is there a workaround currently?

I can implement this myself using Cloud Scheduler and Cloud Functions.

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by zijianjoy** [comment]
cc @sasha-gitg @SinaChavoshi

**Comment by SinaChavoshi** [comment]
Assigning to chen for comments/ triage.

**Comment by ji-yaqi** [comment]
This AIPlatformClient would be deprecated soon. Thanks for the FR, we have it in our options to add into Vertex SDK.

**Comment by axelmagn** [comment]
@ji-yaqi any updates on this?

**Comment by ji-yaqi** [comment]
Hi @axelmagn, we will deprecate AIplatformClient in v2.0.0. Meanwhile, you can use scheduling here: https://cloud.google.com/vertex-ai/docs/pipelines/schedule-cloud-scheduler
