### ISSUE TITLE
[feature] Add a delete_schedule and update_schedule functions to AIPlatformClient

### ISSUE THREAD

**Issue by axelmagn** [kubeflow/pipelines#6087]
### Feature Area

/area sdk 

### What feature would you like to see?

I would like to be able to delete and update existing schedules created via  `create_schedule_from_job_spec`.

### What is the use case or pain point?

Pipelines are updated over time, and need to be redeployed.  `create_schedule_from_job_spec` manages long-term resources in the form of cloud functions and schedules that will need to be updated as part of a redeployment event.  At the moment, I must manage these resources manually, which makes it easier to implement everything myself rather than using `AIPlatformClient`.

### Is there a workaround currently?

Circumvent AIPlatformClient.  Create and update schedule / functions / pubsub manually.

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by zijianjoy** [comment]
cc @sasha-gitg @SinaChavoshi @ji-yaqi

**Comment by ji-yaqi** [comment]
Close this since the client is moved to Vertex SDK.
