### ISSUE TITLE
[sdk] Wrong type hint of create_run_from_job_spec

### ISSUE THREAD

**Issue by sfujiwara** [kubeflow/pipelines#6092]
### Environment

*  KFP version: -
*  KFP SDK version: 1.6.5
*  All dependencies version:
   * kfp-pipeline-spec: 0.1.8
   * kfp-server-api: 1.6.0

### Steps to reproduce

The type hint of `create_run_from_job_spec` says `str`, but it actually returns `dict`.

https://github.com/kubeflow/pipelines/blob/74d27e7e7ec88c62154a3dc5fb19cb27fc2922e6/sdk/python/kfp/v2/google/client/client.py#L258-L268

```python
from kfp.v2 import compiler, dsl
from kfp.v2.google.client import AIPlatformClient

compiler.Compiler().compile(pipeline_func=pipeline_func, package_path=pipeline_json)
api_client = AIPlatformClient(project_id=project_id, region="us-central1")

# `response` is actually `dict`, but the type hint says `str`.
response = api_client.create_run_from_job_spec(...)
```

### Expected result

- The return types of `create_run_from_job_spec` should be `dict`
- The return types of `_submit_job` (called in `create_run_from_job_spec`) should be `dict`

https://github.com/kubeflow/pipelines/blob/74d27e7e7ec88c62154a3dc5fb19cb27fc2922e6/sdk/python/kfp/v2/google/client/client.py#L207-L211

### Materials and Reference

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by NikeNano** [comment]
You are always more than welcome to make a PR @sfujiwara if you find things like this.

**Comment by sfujiwara** [comment]
@NikeNano Thanks. I made PR #6098. Could you please review it?
