### ISSUE TITLE
How do I call Hosted KFP APIs programmatically when I have Google Cloud token?

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#6096]
Suppose I have several instances of KFP installed from Google Cloud Marketplace.
I also have Google Cloud token with `cloud-platform` scopes. (Similar to the one given by `gcloud auth print-access-token`). I can call any Google Cloud API using that token. But how can I call KFP API?

1) Can I programmatically list the Hosted KFP instances (as I see in the Google Cloud AI Platform UX) and get their inverse proxy URLs?
2) Given a KFP inverse proxy URL and token, how can I can any KFP API? I've tried to pass the token as `Authentication: Bearer: <token>`, but that did not quite work for me.

I've read some KFP documentation which mentioned creating service accounts and client IDs, but I did not see a solution that would work with just a token.

**Comment by zijianjoy** [comment]
1. I think you can list the endpoint via kubectl `kubectl describe configmap inverse-proxy-config -n kubeflow | grep googleusercontent.com`, you probably need some script to query for all k8s context you have. Reference: https://www.kubeflow.org/docs/components/pipelines/installation/standalone-deployment/#deploying-kubeflow-pipelines
2. I don't know approaches other than https://cloud.google.com/iap/docs/authentication-howto#authenticating_from_a_desktop_app, I would also be interested in any potential solution to it.

**Comment by Bobgy** [comment]
Strange, I think you can just get the token by `gcloud auth print-access-token` and add it to header `Authorization: Bearer <Token>`.

Did you make a typo there? It should be Authorization Bearer: https://swagger.io/docs/specification/authentication/bearer-authentication/

**Comment by Bobgy** [comment]
> Can I programmatically list the Hosted KFP instances (as I see in the Google Cloud AI Platform UX) and get their inverse proxy URLs?

It's not a public API from my understanding
