### ISSUE TITLE
Run status tooltip should include creation time

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#61]
-- EDIT
"Last 5 runs" - is the last one (the rightmost) the real last run?

**Comment by yebrahim** [comment]
I think the tooltip should include creation time not completion time, multiple runs can (it's common) be running in parallel.

**Comment by ajayalfred** [comment]
Can both be included?
Two attributes of a run is represented by the status icon - the run itself and it's status. Agree that creation time will be useful. Although a user may also want to know when the run finished/stopped/failed/etc.. Including both the timestamps will serve both these use cases.

**Comment by yebrahim** [comment]
Don't you think that's too much detail for the tooltip though? You can always check the run details to see all that information.
A mock would be useful.

**Comment by ajayalfred** [comment]
No it isn't be too much detail for a tooltip.
The tooltip must describe the status – if we want to include creation time then additional text has to be added to separate status description from run creation timestamp. See below.

![image](https://user-images.githubusercontent.com/2425179/49818943-f114ee00-fd28-11e8-8e79-b97504df9dbb.png)

Please note ellipsis at the end of first three status descriptions.

**Comment by rileyjbauer** [comment]
This is fixed as of #671, although I need to tweak the format of the tooltips a little to fully mirror Ajay's design
