### ISSUE TITLE
[pH] prepare for kpt v1.0.0-beta.1

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#6100]
349.0.0 (2021-07-20)
  Breaking Changes
      * **(Kpt)** kpt updated to v1.0.0-beta.1. This version has several
        breaking changes from previous versions. Documentation is available at
        <https://kpt.dev> and migration instructions can be found at
        <https://kpt.dev/installation/migration>. Old versions are available at
        <https://github.com/GoogleContainerTools/kpt>.

**Comment by Bobgy** [comment]
manifests presubmit test is already failing with kpt v1: https://oss-prow.knative.dev/view/gs/oss-prow/pr-logs/pull/kubeflow_pipelines/5926/kubeflow-pipelines-manifests/1417793964035018752

**Comment by Bobgy** [comment]
```
+ kpt cfg tree /home/prow/go/src/github.com/kubeflow/pipelines/manifests/kustomize/hack/..
error: unknown command "cfg" for "kpt"
Did you mean this?
	fn
	pkg
```

**Comment by Bobgy** [comment]
FYI, I temporarily disabled the test that uses kpt in https://github.com/kubeflow/pipelines/commit/efe22ca0a4c8b051c4284d7fd83be2aac58162d0

We can re-enable after upgrade

**Comment by Bobgy** [comment]
Candidate for Kubeflow 1.4 release

**Comment by zijianjoy** [comment]
Validated the manifest test is now adopted to kpt v1.0.0-beta.13
