### ISSUE TITLE
[sdk] Can't access local files on local KF deployment

### ISSUE THREAD

**Issue by Pedrohgv** [kubeflow/pipelines#6107]
### Environment

*  KFP version:
1.6.5

*  KFP SDK version: 
1.6.0

*  All dependencies version:
kfp                               1.6.5    
kfp-pipeline-spec        0.1.8    
kfp-server-api             1.6.0

### Steps to reproduce

Running Kubeflow on a K3s cluster on my machine. I built a simple python function that takes as input:

- Input folder path that contains some files to be transformed
- Output folder that will contain the transformed files
- A parameter to the transformation itself.

The inputs are passed to the python code by using the argparse library:

parser.add_argument('--input-path', type=str, required=True)
parser.add_argument('--output-path', type=str, required=True)
parser.add_argument('--classes', nargs='+', required=True)

Wrapped the python code in a container, tested it with mounted volumes and it works as expected. Wrote the .yaml file to build the pipeline component using the inputPath placeholder for both the output and input path. My interface looks like this:
```
inputs:
  - {name: input_path, type: string}
  - {name: output_path, type: string}
  - {name: classes, type: list}

outputs:
  - {name: output_path, type: string, description: 'Output path to save both images and Yolo converted annotations.'}
```
My command and args sections looks like this:
```
command: [python3, ./src/pascal_2_yolo_converter.py]
    args: [
      --input-path, {inputPath: input_path}, 
      --output-path, {outputPath: output_path},
      --classes, {inputValue: classes},
    ]
```
I'm trying to make the pipeline (composed ins this example by only this simple component) read the files from a local folder, transform them and write the transformed files on another local folder. 

When uploading the pipeline to kubeflow pipelines UI and filling the input fields, I do not get the expected results (the creation of the output folder with the transformed files). By modifying the code to print those inputs I can see in the logs that the 'classes' parameter is correctly managed, but the input and output paths are printed as '/tmp/inputs/input_path/data' and '/tmp/outputs/output_path/data' respectively.

I expected that using local files with kubeflow would be tricky because the applications are containerized, but I don't understand what's going on with the input/output.

Am I doing something wrong? Is there a better way to work with files locally on a local K8s cluster?

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by Ark-kun** [comment]
Kubernetes containers running on the usually remote compute nodes are not expected to get access to any local files.

Please read the Data-passing tutorial for [command-line programs](https://github.com/Ark-kun/kfp_samples/blob/ae1a5b6/2019-10%20Kubeflow%20summit/106%20-%20Creating%20components%20from%20command-line%20programs/106%20-%20Creating%20components%20from%20command-line%20programs.ipynb) and [Python-based components]( https://github.com/kubeflow/pipelines/blob/d902cae/samples/tutorials/Data%20passing%20in%20python%20components.ipynb).

In general you always need to put your data files to some place where they have a URI, then use some "downloader"component to import that data into the pipeline.

P.S. This naming here is not great. You seem to be getting a path of a path:
```
      --input-path, {inputPath: input_path}, 
      --output-path, {outputPath: output_path},
```
This naming is better:
```
      --input-path, {inputPath: input1}, 
      --output-path, {outputPath: output1},
```

**Comment by Pedrohgv** [comment]
I see, will take a look at the tutorials.

Thanks!
