### ISSUE TITLE
[feature] Support input artifact value placeholder in v2 compatible mode.

### ISSUE THREAD

**Issue by chensun** [kubeflow/pipelines#6108]
Follow up on https://github.com/kubeflow/pipelines/pull/6080

To make legacy data passing work in v2 compatible mode, we need to support `{{{{$.inputs.artifacts['{}'].value}}}}` placeholder in v2 launcher.

**Comment by Bobgy** [comment]
Sure, I can take this.

**Comment by Bobgy** [comment]
I'm scheduling to 1.8 release, do you want it earlier?

**Comment by chensun** [comment]
Closing this feature request, as we no longer want to move forward with https://github.com/kubeflow/pipelines/pull/6080.
