### ISSUE TITLE
[sdk] get_user_namespace method returns user not namespace

### ISSUE THREAD

**Issue by rawc0der** [kubeflow/pipelines#6113]
### Environment

*  KFP version: 1.6.0

*  KFP SDK version: 1.6.3

**All dependencies version:**

* kfp-pipeline-spec        0.1.8
* kfp-server-api           1.6.0

### Steps to reproduce

Creating a client using standard constructor and calling the method `get_user_namespace` is actually returning the user for the session and not the namespace.
```
client = kfp.Client() 
client.set_user_namespace('my-namespace')
client.get_user_namespace() != 'my-namespace'
```

### Expected result

`get_user_namespace()` method should return the namespace set for the current authenticated session.

### Materials and Reference

I am authenticating with custom script which is using cookie based session `kfp.Client(host=kfp_host_url, cookies=cookie)` and the username is added in Dex as a static member.
Namespace is different than the username (in my case the user is `ci@company.com` and the namespace is `ci`).

This method `set_user_namespace` doesen't seem to be changing session state and  somehow `get_user_namespace` is hardwired to return the user of the session, _maybe some other bug is responsible_, trying to wrap my head around the source of this. 

Anybody else has encountered this 🐝 havior?  

@Ark-kun  any ideas?

Thanks!
---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by chensun** [comment]
That's strange. Do you have any other code between `client.set_user_namespace('my-namespace')` and `client.get_user_namespace()`?

If you look at the code, they just set/read a dictionary entry using the same key. (The dictionary can be dump to or load from a local file).

https://github.com/kubeflow/pipelines/blob/27051ab9d1c9e8ca1464c17b10d12ed73c8227f1/sdk/python/kfp/_client.py#L335-L347


https://github.com/kubeflow/pipelines/blob/27051ab9d1c9e8ca1464c17b10d12ed73c8227f1/sdk/python/kfp/_client.py#L372-L378

**Comment by rawc0der** [comment]
Hey @chensun,

Thanks for the reply. I discovered the source for this, it's in my custom scripts .. 

There was a faulty line overriding the namespace as the username.
```
namespace = user or default_data.get("namespace")
```

Closing this as it's not relevant!  Thanks again.
