### ISSUE TITLE
[bug] pipeline ui runs status can not update

### ISSUE THREAD

**Issue by liguodongiot** [kubeflow/pipelines#6118]
When I use kfp1.5 to deploy to k8s.

I execute run, this pipeline ui has not been able to update the status.

![image](https://user-images.githubusercontent.com/13220186/126731820-c0f77592-8f7c-4be0-8a84-6d79d9582c74.png)

---
And I check that the pod has finished running

![image](https://user-images.githubusercontent.com/13220186/126731965-5d48bf63-8757-4999-b445-2b1b71684bf6.png)

I restarted k8s and kfp, the status is normal。

**Comment by Bobgy** [comment]
Is this a duplicate of https://github.com/kubeflow/pipelines/issues/3763?
@liguodongIOT

**Comment by liguodongiot** [comment]
你好,我是李国冬，我已收到你的邮件，我会尽快给您回复。
