### ISSUE TITLE
[v2compat] v1 metrics support

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#6132]
KFP v1 supports metrics feature https://www.kubeflow.org/docs/components/pipelines/sdk/pipelines-metrics/.

V2 compatible mode does not yet support it, because supporting this feature is relatively hard. I'd like some feedback how important this feature is for you. Please thumbs up on the issue and probably explain your use-case to help us triage.

## Idea
to support this feature, we need to update persistence agent, let it also parse MLMD data and extract the metrics artifacts and persist them in KFP DB.

**Comment by AlexandreBrown** [comment]
Hello, on our side this is one of the most important feature for v2.  
Being able to run multiple pipelines and then to easily be able to compare the metrics is key in our workflow.  
We loved that v1 offered this and we cannot wait for it to be available on v2.  
Cheers!

**Comment by chensun** [comment]
Closing as v2 compatible mode is no longer supported.
