### ISSUE TITLE
[backend] <not possible to use execution_options.caching_strategy.max_cache_staleness = "P0D" with create_component_from_func with >

### ISSUE THREAD

**Issue by ferpitol** [kubeflow/pipelines#6176]
hi, my function are created with create_component_from_func,

so how can i implement this

```
task = some_op()
task.execution_options.caching_strategy.max_cache_staleness = "P0D"
example of my code

def some_python_func():
    #do something
    return True
    
task1 = create_component_from_func(
    func=some_python_func(),
    base_image="one ddcoker image"
    #packages_to_install=['gensim'], # Optional
)

@dsl.pipeline(
    name='one name',
    description='one description'
)
def hello_world_pipeline():
    task1().output
    
if __name__ == '__main__':
    task = hello_world_pipeline()
    kfp.compiler.Compiler().compile(task, 'mypipeline.yaml')
when in the main I code

if __name__ == '__main__':
    task = hello_world_pipeline()
    task.execution_options.caching_strategy.max_cache_staleness = "P0D"
    kfp.compiler.Compiler().compile(task, 'mypipeline.yaml')
```
it gives me the error : AttributeError: 'NoneType' object has no attribute 'execution_options'

also I tried

```
def hello_world_pipeline():
    task_nc = task1()
    task_nc.execution_options.caching_strategy.max_cache_staleness = "P0D"
    task_nc().output
```
but it give the error:
AttributeError: 'NoneType' object has no attribute 'caching_strategy'

please could someone help me I really need that any task of my pipeline runs cache and using configurations like` kubectl patch mutatingwebhookconfiguration ... `is not an option

**Comment by NikeNano** [comment]
Can you try this example and see if this works for you: https://github.com/kubeflow/pipelines/blob/d9c019641ef9ebd78db60cdb78ea29b0d9933008/samples/core/caching/caching_sample.py. Uses `create_component_from_func` with `.execution_options.caching_strategy.max_cache_staleness = 'P0D'`

**Comment by NikeNano** [comment]
@ferpitol
