### ISSUE TITLE
Unable to plug-in default values to Pipeline

### ISSUE THREAD

**Issue by swiftdiaries** [kubeflow/pipelines#618]
I tried creating a custom pipeline but I'm ran into this error while compiling it.
`ValueError: Default values of argument has to be type dsl.PipelineParam or its child.`

```
@dsl.pipeline(
    name='Simple Pipeline for test',
    description='A simple pipeline for testing'
)
def run_step(project='some value'):
```
A workaround was to create a PipelineParam and then pass it.
`project = dsl.PipelineParam(name='run-step-parameter')`

But I'm unable to set default values to the parameter.
The default examples from [here](https://github.com/swiftdiaries/pipelines/tree/master/samples) don't compile as well. I'm getting the same error.

**Comment by gaoning777** [comment]
Which DSL Compiler version did you install?
It might be that your compiler is outdated.

**Comment by swiftdiaries** [comment]
I installed with the --upgrade flag. Tried it with a clean environment and a fresh install. It still gives out the same error.

**Comment by swiftdiaries** [comment]
Thanks for the reply :) That worked. I mixed up my environments.
Closing this issue now.
