### ISSUE TITLE
v2 backend API

### ISSUE THREAD

**Issue by zijianjoy** [kubeflow/pipelines#6199]
- [x] #6169 
- [x] #6170 
- [x] #6171
- [x] #7119

**Comment by Bobgy** [comment]
Hi @zijianjoy, I updated some tasks according to the plan

**Comment by zijianjoy** [comment]
Cool! Thank you @Bobgy for the update!

**Comment by zijianjoy** [comment]
Remaining task: Upload V2 images to gcr.io.

**Comment by chensun** [comment]
> Remaining task: Upload V2 images to gcr.io.

This doesn't really belong to API work. Tracking it in https://github.com/kubeflow/pipelines/issues/6184 instead.
