### ISSUE TITLE
[feature] Pipeline to continue after any steps fails

### ISSUE THREAD

**Issue by wiktorof** [kubeflow/pipelines#6225]
### Feature Area
/area sdk
### What feature would you like to see?
Handling exception during the failed step in workflow. so something similar to ExitHandler but on the step not pipeline level.
### What is the use case or pain point?
Some steps in pipeline might be optional or at least not critical. And if they fail we don't care albeit we would like pipeline to continue and finish with status set to warning e.g. 
### Is there a workaround currently?

In the step `try/finally return "Failure"` block ensures that we are always succesfull and then in pipeline:
```
        with dsl.Condition(step_x.output == "Failure"):
            step_x_fail = catch_fail(message="failure")
        step_y.after(step_x)
```
which makes pipeline less readable

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by Bobgy** [comment]
/cc @chensun 
I think v2 pipeline spec has more flexible support for exit handler, it's pending DSL change to expose the feature.
