### ISSUE TITLE
[feature] support setup.py in gcp/python/launch_dataflow 

### ISSUE THREAD

**Issue by ckchow** [kubeflow/pipelines#6237]
### Feature Area
 /area components 

### What feature would you like to see?
Allow the python dataflow launch component to pass `setup.py` to the dataflow stager program as a requirements-specification option. See [beam docs](https://beam.apache.org/documentation/sdks/python-pipeline-dependencies/#multiple-file-dependencies) for details.

Only one of `requirements.txt` or `setup.py` should be allowed to be specified.

### What is the use case or pain point?
`requirements.txt` works for most deps, but anything with numpy in the dependency chain takes an incredibly long time to stage / execute. This is due to how the beam stager explicitly downloads and tries to build **all** transitive dependencies for everything in `requirements.txt`.

### Is there a workaround currently?
We would either use a customized dataflow worker image or use a modified dataflow launcher component that has a different commandline.

---
Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by SinaChavoshi** [comment]
fix should be available in the next release.
