### ISSUE TITLE
KFP CLIENT CALL

### ISSUE THREAD

**Issue by prasadkyp7** [kubeflow/pipelines#6254]
I am trying to use the kfp.client in KUBEFLOW 1.2 and passing cookies for user authorization. I am not finding any other solution to use KFP API or kfp.client.

This is very weird way of creating/using kfp.client.

Is there any other way to pass username and password for authorization of using kfp.client or any other rest api and create a run??

**Comment by midhun1998** [comment]
Hi @prasadkyp7 . KFP now supports authentication using ServiceAccountTokens. This was implemented recently. You can find details in the ref issue. 
Ref issue: #5138 
Ref PR: #5676 
You can look at a sample PodDefault config here https://github.com/kubeflow/pipelines/pull/5676#issuecomment-874755408

**Comment by prasadkyp7** [comment]
How about ttl logic.

client.create_run_from_pipeline_func(TTL_pipeline,namespace="dev", arguments={},experiment_name="TEST",pipeline_conf=pipeline_conf.set_ttl_seconds_after_finished(seconds=10))

ttl is not working to delete the pods after completion. we upgraded to new kubeflow as it was mentioned that it was a new feature added. But its not working . any update on this?

**Comment by zijianjoy** [comment]
tracking issue in 
https://github.com/kubeflow/pipelines/issues/5545
