### ISSUE TITLE
[feature] Passing different data type (like pd.DataFrame or tf.data.Dataset) between stages

### ISSUE THREAD

**Issue by eddynelson** [kubeflow/pipelines#6255]
### Feature Area

 /area backend 

### What feature would you like to see?

When using python functions to create stages using `kfp.components.func_to_container_op` is not possible to return different kinds of data types like `pd.DataFrame` or `tf.data.Dataset`, just to mention a few, would be great if we could return different kinds of data types that are common use for **Dataset**.
### What is the use case or pain point?

Return the whole dataset between stages without having to create a persistent volume.

### Is there a workaround currently?

Building an image for each stage and adding a persistent volume.

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by zijianjoy** [comment]
duplicate #6304
