### ISSUE TITLE
large tarfile extraction: tarfile.ReadError: file could not be opened successfully 

### ISSUE THREAD

**Issue by yousefis** [kubeflow/pipelines#6269]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?

*  KFP version: 
kfp                               1.6.3
kfp-pipeline-spec                 0.1.8
kfp-server-api                    1.6.0
kfp-tekton                        0.9.0

### Steps to reproduce
Just run the below pipeline:

`import kfp

import kfp.components as comp

def extract_img(file_path: comp.InputPath('Tarball'),
):

	import glob
	import pandas as pd
	import tarfile
	import logging
	logging.basicConfig(level=logging.INFO)
	logging.info('opening tarfile: '+file_path)
	with tarfile.TarFile.open(name = file_path, mode = 'r:*') as archive:
		for member in archive:
			try: 
				file_obj = archive.extractfile(member)
			except zipfile.error as e:
				logging.info(file_obj)	

	ccreate_step_extract_img = kfp.components.create_component_from_func(
    func=extract_img,
    output_component_file='component.yaml', # This is optional. It saves the component spec for future use.
    base_image='python:3.7',
    packages_to_install=['pandas==1.1.4'])
	web_downloader_op = kfp.components.load_component_from_url(
    'https://raw.githubusercontent.com/kubeflow/pipelines/master/components/web/Download/component.yaml')
	def my_pipeline(url):
	  web_downloader_task = web_downloader_op(url=url)
	  extract_img_task = create_step_extract_img(file=web_downloader_task.outputs['data'])
	kfp.compiler.Compiler().compile(
    pipeline_func=my_pipeline,
    package_path='pipeline.yaml')
`

### Expected result
The tarfile should be extracted 

### Materials and Reference
I ran the pipeline on gcp kubeflow for a tarfile size of 150MB, it keep getting the below error. Is there any limitation with the size of file that I can extract in /tmp? If so how I can fix the issue?

`
INFO:root:opening tarfile: /tmp/inputs/file/data
Traceback (most recent call last):
  File "/tmp/tmp.HTDYHMwP7m", line 22, in <module>
    _outputs = merge_csv(**_parsed_args)
  File "/tmp/tmp.HTDYHMwP7m", line 10, in merge_csv
    with tarfile.TarFile.open(name = file_path, mode = 'r:*') as archive:
  File "/usr/local/lib/python3.7/tarfile.py", line 1580, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully`

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by zijianjoy** [comment]
https://argoproj.github.io/argo-workflows/examples/#artifacts: Artifacts are packaged as Tarballs and gzipped by default. 

You can try not to unzip the file when reading, because it is automatically unzip by argo.

Or you can try KFP v2 compatible to see whether it fixes your issue.
