### ISSUE TITLE
[backend] v2compat - recurring runs fail with "Failed to create component launcher: Invalid launcher options: must specify RunID"

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#6293]

**Comment by shengzhou1216** [comment]
same issue.

**Comment by Bobgy** [comment]
This will be released in rc4

**Comment by ckchow** [comment]
I get this when trying to run pipelines with tasks that were created from `kfp.components.create_component_from_func_v2`. an example of a compiled task:

```
kind: Pod
apiVersion: v1
metadata:
  name: <name>
  namespace: cchow
  selfLink: /api/v1/namespaces/cchow/pods/<id>
  uid: e295b3e5-c390-4e28-b1b0-0e3f2a6d92ad
  resourceVersion: '128321282'
  creationTimestamp: '2021-09-15T18:50:34Z'
  labels:
    RunID: blah  <-- I put this in here for testing
    pipelines.kubeflow.org/cache_enabled: 'true'
    pipelines.kubeflow.org/enable_caching: 'true'
    pipelines.kubeflow.org/kfp_sdk_version: 1.7.0
    pipelines.kubeflow.org/pipeline-sdk-type: kfp
    pipelines.kubeflow.org/v2_component: 'true'
    workflows.argoproj.io/completed: 'true'
    workflows.argoproj.io/workflow: <workflow>

<a lot of other stuff>
```

**Comment by Bobgy** [comment]
@chensun is `create_component_from_func_v2` a supported feature?
I'm not seeing usage of it in our samples.

@ckchow what is your KFP SDK version?

**Comment by ckchow** [comment]
I tried to write a v2 component (i.e. a component that outputs stuff via `model: Output[Model], Output[Metrics]` instead of returning a NamedTuple), and the kfp sdk told me I needed to use the `_v2` creation function.

I'm using `kfp==1.7.0`

**Comment by Bobgy** [comment]
Can you try https://www.kubeflow.org/docs/components/pipelines/sdk/v2/python-function-components/?

**Comment by ckchow** [comment]
ok. I think I have avoided this issue on some other pipeline by using the `@component` annotation, which I assume calls some other, non-deprecated function.

**Comment by ckchow** [comment]
update: I ran into this issue again when using a kubeflow cluster. I had only managed to avoid this problem when I was using kfp on vertex ai.

component
```
from kfp.v2.dsl import component

<...>

## preprocessor
@component(
  base_image='blah'
)
def preprocess(
   ...
)
```

kubeflow log
```
F1005 07:56:11.389530       1 main.go:50] Failed to create component launcher: Invalid launcher options: must specify RunID
```

I can post the pod yaml if necessary. (it's a bit large)

**Comment by ckchow** [comment]
To be clear, this seems to pop up beyond the original reported context of recurring runs. This just happened to be the only issue I saw in the project that had the same error text that I saw.

**Comment by Roman-Ka** [comment]
Hi, I am facing the same issue on version 1.8.9, does anyone know how to work around this?

**Comment by pbarker** [comment]
also seeing this on non-recurring runs on kfp `v1.7.1` and kube `v1.20.7`

**Comment by shekhar0413** [comment]
Facing the same issue on kfp version 1.8.9 without recurring runs. I used kfp v2 sdk to write my pipeline, then compiled it using `kfp.compiler.Compiler(mode=kfp.dsl.PipelineExecutionMode.V2_COMPATIBLE).compile(
    pipeline_func=pipeline_func,
    package_path='my_pipeline.yaml')` and then uploaded the yaml file to a local Arrikto MiniKF deployment. Get the following error message `Failed to create component launcher: Invalid launcher options: must specify RunID`

**Comment by Bobgy** [comment]
I recall that the Arrikto distribution does not have the same behavior for run ID. Can you use an official installation to test this.

**Comment by metanouvelle** [comment]
hi there, I am having the same issue by using SDK V2 to create a simple pipeline. I deployed kubeflow on a blank new EKS by following installation on kubeflow manifest, and using
```python
kfp==1.8.10
kfp-pipeline-spec==0.1.13
kfp-server-api==1.7.1

Code is as followed:

```python
import kfp
import kfp.dsl as dsl
from kfp.v2.dsl import component

@component
def add(a: float, b: float) -> float:
    return a + b

@dsl.pipeline(
  name='addition-pipeline',
  description='An example pipeline that performs addition calculations.',
)
def add_pipeline(a: float, b: float):
    add_task = add(a, b)
    
client = kfp.Client()
client.create_run_from_pipeline_func(
    add_pipeline,
    arguments={'a': 7, 'b': 8},
    mode=kfp.dsl.PipelineExecutionMode.V2_COMPATIBLE,
)
```
FYI: If I modified my code to SDK V1, it totally worked.

**Comment by Bobgy** [comment]
Closing because https://github.com/kubeflow/pipelines/issues/6829
