### ISSUE TITLE
[Minio] <Connecting kubeflow pipelines to a minio tenant>

### ISSUE THREAD

**Issue by Hmr-ramzi** [kubeflow/pipelines#6295]
### Feature Area

Hello Everyone,
I am currently trying to connect kubeflow pipelines to instead of using an own minio deloyment it would use minio tenant as an underlying file system to kubeflow pipelines. I was able to connect it to a minio gateway (just a simple gateway to a cloud provider) but i am unable to connect it to a minio tenant. Any advise or documentation on the matter ?

### What feature would you like to see?
Connecting Kubeflow pipelines to a minio tenant

### What is the use case or pain point?
Scaling up the file system

### Is there a workaround currently?
Not sure! Thats why i am asking

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by zijianjoy** [comment]
@Hmr-ramzi Hello, KFP is using Argo workflow, so you can use the same approach to configure artifact repository: https://argoproj.github.io/argo-workflows/configure-artifact-repository/.

How do you connect with a minio gateway, and how do you connect to a minio tenant? Appreciate it for sharing reproduce steps so we can dig in further.
