### ISSUE TITLE
[bug] sample - tfx builtin taxi sample visualizations broken

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#6296]
### What steps did you take

1. install AI platform pipelines 1.7.0-rc.3
2. run builtin tfx taxi sample
3. check tasks with visualizations

![image](https://user-images.githubusercontent.com/4957653/128999167-2f3c38af-1ab2-4a2a-b9e8-03097ace3722.png)

### What happened:

visualization failed:

example validator fails with

> NotFoundError: The specified path gs://gongyuan-dev-kubeflowpipelines-default/tfx_taxi_simple/540e7c51-ee89-4488-bc6a-b40a423b1988/ExampleValidator/anomalies/66/Split-train was not found.

statistics gen fails with

> NotFoundError: Could not find directory gs://gongyuan-dev-kubeflowpipelines-default/tfx_taxi_simple/540e7c51-ee89-4488-bc6a-b40a423b1988/StatisticsGen/statistics/60/Split-eval

### What did you expect to happen:
they should visualize properly

### Anything else you would like to add:

I think it might not be a problem for our visualization code. I believe we made a change to accommodate for TFX 1.0 -- there was a breaking change. Therefore, to run the sample properly, we need to upgrade the sample to use TFX 1.0+.

### Labels

/area samples

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by Bobgy** [comment]
a minor problem:
![image](https://user-images.githubusercontent.com/4957653/129000588-06edd906-d07c-4ec3-af30-0963317bb8bd.png)

the html visualization does not fill the width in the sidepanel

**Comment by zijianjoy** [comment]
I spent a very long time but couldn't install the TFX successfully in my notebook. Let me fix the minor issue first: https://github.com/kubeflow/pipelines/pull/6319

**Comment by zijianjoy** [comment]
cc @jiyongjung0 Would you like to validate the visualization after TFX upgrade is successful? And would you like to share the reproduce steps here too? Thank you!

**Comment by Bobgy** [comment]
let's keep tracking the issue in https://github.com/kubeflow/pipelines/issues/6138

no need to have two separate threads
