### ISSUE TITLE
"No runs were found for this experiment" is a misleading message when the list is still being loaded.

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#63]

**Comment by Ark-kun** [comment]
Is it possible to make the UX behave more like traditional websites where the navigation and content are shown at once?

**Comment by yebrahim** [comment]
What do you mean by navigation and content shown at once?

**Comment by yebrahim** [comment]
Fixed by https://github.com/kubeflow/pipelines/pull/405.
