### ISSUE TITLE
FR: add v2 DSL sample to the "Getting Started" page

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#6306]
FR: add v2 DSL sample to the "Getting Started" page

The sample was added as a built-in Pipeline sample. We should add it to the "Getting Started" page as well.

EDIT:
similar FR by @Bobgy: add v2 DSL documentation to "Getting Started" page

_Originally posted by @james-jwu in https://github.com/kubeflow/pipelines/issues/5779#issuecomment-897225710_

**Comment by zijianjoy** [comment]
Also update http://cloud/ai-platform/pipelines/docs/getting-started

**Comment by zijianjoy** [comment]
https://github.com/kubeflow/pipelines/blob/master/README.md
