### ISSUE TITLE
[sdk] v2compat - consistent naming of pipeline root parameter

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#6307]
pipeline root parameter is called `pipeline-output-directory` in KFP UI/SDK
can we rename it to `pipeline-root` to be consistent with SDK API?

_Originally posted by @Bobgy in https://github.com/kubeflow/pipelines/issues/5779#issuecomment-897227634_

**Comment by zijianjoy** [comment]
I agree with the consistency on naming it `pipeline-root`. Also TFX is using the term `pipeline-root`: https://www.tensorflow.org/tfx/guide/build_tfx_pipeline#using_the_pipeline_class.
