### ISSUE TITLE
[doc] v2 compatible mode -- pipeline root

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#6310]
We need documentation for pipeline root

_Originally posted by @Bobgy in https://github.com/kubeflow/pipelines/issues/5779#issuecomment-897254432_

**Comment by zijianjoy** [comment]
/assign @capri-xiyue 

Update kubeflow.org

**Comment by Bobgy** [comment]
TODO(Bobgy): update the configmap name to `kfp-runtime`
