### ISSUE TITLE
[testing] postsubmit test failure 2021-08-12

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#6311]
https://oss-prow.knative.dev/view/gs/oss-prow/logs/kubeflow-pipeline-postsubmit-standalone-component-test/1425587097510612992#1:build-log.txt%3A5394

For standalone components test, it fails when building sample test image:

> sample-test-rb7fv-2769807467: error: google-api-core 1.26.0 is installed but google-api-core<3.0dev,>=1.29.0 is required by {'google-cloud-storage'}
sample-test-rb7fv-2769807467: The command '/bin/sh -c cd /sdk/python && python3 setup.py install' returned a non-zero code: 1

**Comment by Bobgy** [comment]
before this error shows up, there was a different error that we should also fix:
https://oss-prow.knative.dev/view/gs/oss-prow/logs/kubeflow-pipeline-postsubmit-integration-test/1425263307043901440#1:build-log.txt%3A9072

The error seems like a bug, docker executor also do not support optional output artifacts:
> executor error: path /tmp/outputs/MLPipeline_UI_metadata/data does not exist in archive /tmp/argo/outputs/artifacts/launch-python-MLPipeline-UI-metadata.tgz\ngithub.com/argoproj/argo-workflows/v3/errors.New\n\t/go/src/github.com/argoproj/argo-workflows/errors/errors.go:49\ngithub.com/argoproj/argo-workflows/v3/errors.Errorf\n\t/go/src/github.com/argoproj/argo-workflows/errors/errors.go:55\

**Comment by neuromage** [comment]
Thanks @Bobgy. Can you point me to the pipeline sample that fails?

**Comment by Bobgy** [comment]
/reopen
postsubmit test is still failing: https://github.com/kubeflow/pipelines/commit/f743dde32f9c468afd6028c282d2440c3e01ecf6

**Comment by Bobgy** [comment]
Build starts to fail again, the error message shows up when building inverse proxy image:
> Digest: sha256:2e3c5ecd1a55b32056f3ce0c4aaac05e31b85c361d501bf3f8a81bec14c4fe87
Status: Downloaded newer image for gcr.io/inverting-proxy/agent@sha256:2e3c5ecd1a55b32056f3ce0c4aaac05e31b85c361d501bf3f8a81bec14c4fe87
 ---> ce436ce6c655
Step 2/14 : RUN apt-get update && apt-get install -y curl jq python-pip
 ---> Running in 29b8ef43d3d1
Get:1 http://deb.debian.org/debian buster InRelease [122 kB]
Get:2 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Reading package lists...
E: Repository 'http://security.debian.org/debian-security buster/updates InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
E: Repository 'http://deb.debian.org/debian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
E: Repository 'http://deb.debian.org/debian buster-updates InRelease' changed its 'Suite' value from 'stable-updates' to 'oldstable-updates'
The command '/bin/sh -c apt-get update && apt-get install -y curl jq python-pip' returned a non-zero code: 100

https://forums.linuxmint.com/viewtopic.php?t=355148&p=2053997 seems to describe the problem

**Comment by Bobgy** [comment]
The latest postsubmit test run still fails, but only container builder and parameterized tfx samples are failing.
container builder failed because kaniko job times out, it's expected flakiness.
TFX sample will be fixed by jiyong.

https://storage.googleapis.com/oss-prow/logs/kubeflow-pipeline-postsubmit-integration-test/1427197975674753024/build-log.txt

**Comment by Bobgy** [comment]
The TFX sample fails with:
```
sample-test-xcp5g-222029471: parameterized-tfx-oss-7qb9g-305390489: tensorflow.python.framework.errors_impl.InvalidArgumentError: Error executing an HTTP request: HTTP response code 400 with body '{
sample-test-xcp5g-222029471: parameterized-tfx-oss-7qb9g-305390489:   "error": {
sample-test-xcp5g-222029471: parameterized-tfx-oss-7qb9g-305390489:     "code": 400,
sample-test-xcp5g-222029471: parameterized-tfx-oss-7qb9g-305390489:     "message": "Invalid bucket name: '{{kfp-default-bucket}}'",
sample-test-xcp5g-222029471: parameterized-tfx-oss-7qb9g-305390489:     "errors": [
sample-test-xcp5g-222029471: parameterized-tfx-oss-7qb9g-305390489:       {
sample-test-xcp5g-222029471: parameterized-tfx-oss-7qb9g-305390489:         "message": "Invalid bucket name: '{{kfp-default-bucket}}'",
sample-test-xcp5g-222029471: parameterized-tfx-oss-7qb9g-305390489:         "domain": "global",
sample-test-xcp5g-222029471: parameterized-tfx-oss-7qb9g-305390489:         "reason": "invalid"
sample-test-xcp5g-222029471: parameterized-tfx-oss-7qb9g-305390489:       }
sample-test-xcp5g-222029471: parameterized-tfx-oss-7qb9g-305390489:     ]
sample-test-xcp5g-222029471: parameterized-tfx-oss-7qb9g-305390489:   }
sample-test-xcp5g-222029471: parameterized-tfx-oss-7qb9g-305390489: }
sample-test-xcp5g-222029471: parameterized-tfx-oss-7qb9g-305390489: '
sample-test-xcp5g-222029471: parameterized-tfx-oss-7qb9g-305390489: 	 when reading metadata of gs://{{kfp-default-bucket}}/tfx_taxi_simple/fe7841ca-0e29-4989-b13a-e32ea09b5d58/model_serving/1629110410
sample-test-xcp5g-222029471: 
```
so it seems parameterization isn't fully working in the test infra.

**Comment by Bobgy** [comment]
I got the the error message even though I filled in {{kfp-default-bucket}} from the pipeline parameter.
It seems that the placeholder in model pusher is not resolved.

cc @jiyongjung0

**Comment by Bobgy** [comment]
besides tfx pipeline issues, I see the following error message in test infra very often:
```
failed to wait for main container to complete: timed out waiting for the condition: container does not exist
```

identified the root cause and sent a fix to argo https://github.com/argoproj/argo-workflows/pull/6561

**Comment by Bobgy** [comment]
There's one last thing, we reached model count quota again, because of https://github.com/kubeflow/pipelines/issues/2356
