### ISSUE TITLE
[feature] kfp CLI support 'kfp run get <run_id>' in detailed information

### ISSUE THREAD

**Issue by anencore94** [kubeflow/pipelines#6315]
### Feature Area

/area sdk

### What feature would you like to see?
Currently, `kfp run get <run_id>` only shows ["run id", "name", "status", "created at"].
However, user could want to see other information of the run.

### What is the use case or pain point?
For my case, I want to fetch my **run's output metrics** with kfp CLI

### Is there a workaround currently?

Since `kfp.Client()` already have `get_run()` method in sdk, which have all information including metrics of run,
I think the UX is only what matters: Which information would be useful or useless, and how user could select them.

For example, I guess `pipeline_Spec.workflow_manifest` could always be omitted, since nobody wants such information.

Therefore, I think with `click.option('--detail')` in get() method in `pipelines/sdk/python/kfp/cli/run.py` shows all information except `pipeline_Spec.workflow_manifest` in json format would be fine.

However, if there is other suggestions, please let me know.
Also, If you guys are ok, I'd like to took this issue and implement this feature.

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by zijianjoy** [comment]
This feature makes sense, welcome contribution!
