### ISSUE TITLE
component migration tool for emissary executor and v2 compatible mode

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#6327]
For both emissary executor and v2 compatible mode, KFP components must specify `command` explicitly in the component yaml, refer to https://www.kubeflow.org/docs/components/pipelines/installation/choose-executor/#migrate-pipeline-components-to-run-on-emissary-executor

I think we could easily build a component migration tool which can be called like:
```
kfp component migrate <path-to-component-yaml>
```

The CLI does the following:
1. read the component yaml
2. verify if command is specified
2. if not, call docker pull && docker inspect to get the command, modify component yaml to include the command

it might be more helpful migrating a folder of components via:
```
kfp component migrate --recursive <folder-with-components>
```
However, there is no good way to identify KFP components, we should probably improve on that.

_Originally posted by @Bobgy in https://github.com/kubeflow/pipelines/issues/6252#issuecomment-895023582_

**Comment by Bobgy** [comment]
Please upvote the issue if it'll be helpful to you!
Thanks

**Comment by Bobgy** [comment]
Besides, a great improvement only possible with a tool is that, with `docker inspect`, you must pull the image locally before inspecting its command. However, if we can build a tool, the tool can directly call the container registry API to get the command and args without pulling the image locally.

**Comment by Bobgy** [comment]
For anyone interested, is it fair to assume you installed docker on your computer and we can use the docker-py library for accessing docker?
https://docker-py.readthedocs.io/en/stable/

**Comment by AseiSugiyama** [comment]
Hi, I am interested in this issue.

> is it fair to assume you installed docker on your computer

Yes, my team uses docker for each local machine.

> we can use the docker-py library for accessing docker?

I think it is acceptable for us. We hired poetry to manage our local & cloud (container) python environment to keep our environment separated from our system python environment. So any tools written in python are acceptable as well as they can be installed from PyPI.

**Comment by Bobgy** [comment]
Thanks for the confirmation @AseiSugiyama!
I'm still waiting for more interest feedback.

In the meantime, if anyone wants to build the tool, welcome doing so!
