### ISSUE TITLE
[feature] Expose run metrics

### ISSUE THREAD

**Issue by jmcarp** [kubeflow/pipelines#6336]
### What feature would you like to see?

I would like to be able to instrument runs with metrics for latency, status, retries, etc. Ideally it would be possible to set an instrumentation policy for all runs. For example, Apache Airflow exposes status and latency by DAG and task by default: https://airflow.apache.org/docs/apache-airflow/stable/logging-monitoring/metrics.html. In terms of implementation, I could imagine adding these metrics to the existing prometheus endpoint in KFP, or exposing the `metrics` option in the argo workflow definition to allow users to configure prometheus metrics for latencies and statuses: https://argoproj.github.io/argo-workflows/metrics/#metric-spec.

### What is the use case or pain point?

I'm interested in building dashboards and alerts without writing custom code to instrument each pipeline.

### Is there a workaround currently?

It's possible to poll the KFP API to generate metrics, but it's inefficient and requires custom code.

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by tzstoyanov** [comment]
hi @zijianjoy, is there any docs or at least high level idea how this should work ? I'm new to Kubeflow pipelines and looking for a good first issue.

**Comment by alexmirrington** [comment]
Would love to see this as well, currently it's possible to modify the `argo_workflows` workflow YAML after compiling a pipeline and inject the metric specs into the workflow's container templates, though this is far from ideal.
