### ISSUE TITLE
[sdk] Is "verify_ssl" configurable ?

### ISSUE THREAD

**Issue by pigbrain** [kubeflow/pipelines#6378]
I am getting this error in my environment.
```
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='..., port=443): Max retries exceeded with url: /apis/v1beta1/healthz (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))
```

To avoid this, `Configuration.verify_ssl` should be set to `False`.

However, there doesn't seem to be a way to set this value now. 

Do we have any alternatives?

**Comment by pigbrain** [comment]
@zijianjoy  Hello, yes, it works fine with http. but, If I add https, I get the above error.

**Comment by pigbrain** [comment]
@zijianjoy Could you check this issue ?

**Comment by zijianjoy** [comment]
@pigbrain , what is your deployment environment?

1. Is it full fledged Kubeflow? Or KFP standalone?
2. Which cloud provider do you use? Or is it on-prem environment?
3. How do you reproduce this error?
4. Do you have any failing Deployment in your cluster?

**Comment by dvaldivia** [comment]
We need support for custom CA's, not all certificates are publicly trusted, for example if you are using Kubernetes CSR's (Certificate Signing Requests) the certificate will be issued by the Control Plane CA, and the root CA needs to be added to the trusted certificates, just the same, when working inside an enterprise setup we would need to trust certificates issued internally.

In both of these cases we need to use `https` so having the capability to tell the pipeline software to trust certain certificates becomes a necessity
