### ISSUE TITLE
[frontend] Run frontend server locally for development with multi-user enabled in server(k8s)

### ISSUE THREAD

**Issue by Sharathmk99** [kubeflow/pipelines#6380]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?

on-prem Kubernetes cluster - using manifest repo
*  KFP version: 1.6.0

Kubeflow with multi tenancy is deployed in on-prem Kubernetes cluster. Everything is working as expected.
Now trying to do local development for frontend. Followed all instruction to build and run frontend by proxying node server to k8s. I started getting below error,

`Invalid input error: Invalid resource references for experiment. ListExperiment requires filtering by namespace.`

After making below changes, above error got resolved and started getting new error,

Under `index.tsx`
```
ReactDOM.render(
  KFP_FLAGS.DEPLOYMENT === Deployments.KUBEFLOW ? (
    <NamespaceContextProvider>{app}</NamespaceContextProvider>
  ) : (
    // Uncomment the following for namespace switch during development.
    <NamespaceContext.Provider value='kubeflow-sharath'>{app}</NamespaceContext.Provider>
    // <NamespaceContext.Provider value={undefined}>{app}</NamespaceContext.Provider>
  ),
  document.getElementById('root'),
);
```

New Error,
```
Internal error: Unauthenticated: Request header error: there is no user identity header.: Request header error: there is no user identity header
```

Can you please help me to start frontend application locally with multi-tenancy enabled?

### Expected result

Start frontend application locally for local development

### Materials and Reference

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by zijianjoy** [comment]
You can install https://modheader.com/guide/

Then add the request header: X-Goog-Authenticated-User-Email with value: `accounts.google.com:<user-email-address>`

**Comment by Sharathmk99** [comment]
Works as expected. Thank you

**Comment by droctothorpe** [comment]
@zijianjoy is there a way to get this work if you're running Kubeflow on GCP / not using google accounts for auth?
