### ISSUE TITLE
[sdk] How to substitute image name with KFP parameters using component.yaml

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/pipelines#6384]
### Environment

*  KFP version: 1.7.0-rc3
*  KFP SDK version: 1.7.0
*  All dependencies version:

### Steps to reproduce
We are trying to convert the [pipelineparams.py](https://github.com/kubeflow/pipelines/blob/master/sdk/python/tests/compiler/testdata/pipelineparams.py#L31) example to load from component.yaml, but we have a hard time to pass the pipeline parameter as the image name. The error we got is about the annotations have variables that are not substituted.

Here is the component we try to change:
```
from kfp import dsl, components
from kubernetes.client.models import V1EnvVar


@dsl.pipeline(name='pipeline-params', description='A pipeline with multiple pipeline params.')
def pipelineparams_pipeline(tag: str = 'latest', sleep_ms: int = 10):

    echo = dsl.Sidecar(
        name='echo',
        image='hashicorp/http-echo:%s' % tag,
        args=['-text="hello world"'],
    )

    op1 = components.load_component_from_text("""
    name: download
    description: download
    outputs:
      - {name: data, type: String}
    implementation:
      container:
        image: busy:%s
        command:
        - sh
        - -c
        args:
        - |
          sleep %s; wget localhost:5678 -O $0
        - {outputPath: data}
    """ % (tag, sleep_ms))()
​
```

Errors on unresolved PipelineParam in annotations:
```
Traceback (most recent call last):
  File "test.py", line 43, in <module>
    Compiler().compile(pipelineparams_pipeline, __file__.replace('.py', '.yaml'))
  File "/Users/tommyli/Desktop/kfp-new-feature/.venv/lib/python3.8/site-packages/kfp/compiler/compiler.py", line 1061, in compile
    self._create_and_write_workflow(
  File "/Users/tommyli/Desktop/kfp-new-feature/.venv/lib/python3.8/site-packages/kfp/compiler/compiler.py", line 1121, in _create_and_write_workflow
    _validate_workflow(workflow)
  File "/Users/tommyli/Desktop/kfp-new-feature/.venv/lib/python3.8/site-packages/kfp/compiler/compiler.py", line 1133, in _validate_workflow
    raise RuntimeError(
RuntimeError: Internal compiler error: Found unresolved PipelineParam.
Please create a new issue at https://github.com/kubeflow/pipelines/issues attaching the pipeline code and the pipeline package.
```

### Expected result

The PipelineParam should also be replaced in component annotations

### Materials and Reference

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by Ark-kun** [comment]
Changing image name is not supported by component.yaml. The rationale is that `component.yaml` describes a command-line program inside a particular image.

There are several workarounds:

* Use image tags in component.yaml and update the tag in the container registry as needed
* For CI/CD, you might want to patch the component.yaml with freshly-built image
* In general, to support reproducibility, when new image version is released, a new `component.yaml` version should be released alongside, pointing to the new image.
* It might be possible to replace the container image after the component has been instantiated:

```python
op1 = components.load_component_from_url(...)

def my_pipeline():
    task1 = op1(...)
    task1.container.image = ...
```

**Comment by Tomcli** [comment]
Thanks @Ark-kun for the workaround. Replace the container image with `task1.container.image = ...` works for us because we want to keep the backward compatibility for changing image tags using pipeline params. I can close this issue now.
