### ISSUE TITLE
[sdk] How to convert dsl.InputArgumentPath into component.yaml

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/pipelines#6385]
### Environment

*  KFP version: 1.7.0-rc3

*  KFP SDK version: 1.7.0

*  All dependencies version:

### Steps to reproduce
From the testdata [input_artifact_raw_value.py](https://github.com/kubeflow/pipelines/blob/master/sdk/python/tests/compiler/testdata/input_artifact_raw_value.py#L30). We want to know how to convert the `dsl.InputArgumentPath` feature in this example to load from component.yaml. 

### Materials and Reference

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by Ark-kun** [comment]
There are 3 main data passing placeholders supported by `component.yaml`:

* `{inputValue: Input 1}`
* `{inputPath: Input 1}`
* `{outputPath: Output 1}`

`InputArgumentPath` in ContainerOp corresponds to `{inputPath: Input 1}`

**Comment by Tomcli** [comment]
Thanks @Ark-kun for the clarification. One more question, will the `component.yaml` still able to use raw value as input artifacts? e.g.
https://github.com/kubeflow/pipelines/blob/fa1cf410f6c0a504d03bb3fc3b0159fcf5fceffc/sdk/python/tests/compiler/testdata/input_artifact_raw_value.py#L53
https://github.com/kubeflow/pipelines/blob/fa1cf410f6c0a504d03bb3fc3b0159fcf5fceffc/sdk/python/tests/compiler/testdata/input_artifact_raw_value.yaml#L56-L59

**Comment by Ark-kun** [comment]
>will the component.yaml still able to use raw value as input artifacts?

There is not change here compared with `ContainerOp`

Passing constant values to any component inputs is supported by the `component.yaml` design which does not separate inputs by the way the implementation consumes them.

This is supported in KFP v1: See the data passing test suite https://github.com/kubeflow/pipelines/blob/9ad37cc2a838fd50a1c2099815402f735ba602cb/samples/test/data_passing.py#L106

However the current version of the Vertex Pipelines compiler (v2 compiler) does not seem to support this yet. Although I've seen PR from Chen that fixes that issue.

**Comment by Tomcli** [comment]
Thanks @Ark-kun, I converted the example based on the usage in the test suite and it works as expected in V1. We look forward to seeing this feature be supported in V2 as well.
