### ISSUE TITLE
[backend] GoogleCloud Marketplace inverse proxy cannot forward hosted KFP UI

### ISSUE THREAD

**Issue by zijianjoy** [kubeflow/pipelines#6389]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
GCP Marketplace hosted KFP
*  KFP version: 
1.7.0-rc.3

### Steps to reproduce

Deploy 1.7.0-rc.3 using GCP marketplace:

Create a K8s 1.18 cluster using Marketplace, I have deleted and redeploy KFP instance multiple times. When I create KFP again, I select enable emissary executor and managed storage options.

I cannot access the KFP using `OPEN PIPELINES DASHBOARD` button.

I tried to use `kubectl port-foward` and I am able to see the KFP UI with this approach.

I tried to delete inverse-proxy-config configmap, and create an empty configmap placeholder, and restarted proxy-agent. But the issue still exists:

1. `kubectl delete cm   inverse-proxy-config -n default`
2. 
```
cat <<EOF | kubectl create -f -
> apiVersion: v1
> kind: ConfigMap
> metadata:
>   name: inverse-proxy-config
>   labels:
>     app.kubernetes.io/name: kubeflow-pipelines-emissary-mgd
>
>
> EOF
```
3. `kubectl rollout restart deployment/proxy-agent -n default`

### Expected result

Open Hosted KFP UI using inverse proxy successfully.

cc @Bobgy 

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by Bobgy** [comment]
@zijianjoy after you finish `kubectl rollout restart deployment/proxy-agent -n default` step, did you check what's the hostname in the configmap? Note, it will be a different hostname from before.

Besides, can you also log the exact error code/message you hit when visiting the inverse proxy URL.

**Comment by zijianjoy** [comment]
@Bobgy That is a good point, I noticed that the hostname is still the same even if I reset the inverse-proxy-config and restart proxy-agent. I checked the log from proxy-agent:

```
 "A proxy request failed: \"Get \\\"https://us-central1.pipelines.cloud.google.com/tun/m/4592f092208ecc84946b8f8f8016274df1b36a14/agent/pending\\\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)\""
``

**Comment by Bobgy** [comment]
>  "A proxy request failed: \"Get \\\"https://us-central1.pipelines.cloud.google.com/tun/m/4592f092208ecc84946b8f8f8016274df1b36a14/agent/pending\\\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)\""

This error is expected.
