### ISSUE TITLE
[bug] the pipeline can not mount pvc

### ISSUE THREAD

**Issue by zm274310577** [kubeflow/pipelines#6416]
### What steps did you take
when i create a run, the pipeline require a pvc(the pvc is created in the 'user' namespace and i am using the 'user' namespace )

### What happened:
when i describe the pod, the pvc mount failed.
Events:
  Type     Reason       Age        From               Message
  Normal   Scheduled    <unknown>  default-scheduler  Successfully assigned user/laji-fenlei-pipeline-lrmlx-3083496721 to slave2
  Warning  FailedMount  24m        kubelet, slave2    MountVolume.SetUp failed for volume "pvc-c9007abeba5a325a2cce65c6649692d6-pv" : CephFS: mount failed: mount failed: exit status 1
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/6d000df9-e380-495e-9738-a10b9082a23f/volumes/kubernetes.io\~cephfs/pvc-c9007abeba5a325a2cce65c6649692d6-pv --scope -- mount -t ceph -o \<masked\>,\<masked\> 192.168.9.51:6789,192.168.9.52:6789,192.168.9.53:6789:/kubeflow-fs/anli/laji/data /var/lib/kubelet/pods/6d000df9-e380-495e-9738-a10b9082a23f/volumes/kubernetes.io\~cephfs/pvc-c9007abeba5a325a2cce65c6649692d6-pv
Output: Running scope as unit run-737583.scope.
mount error 1 = Operation not permitted
  Warning  FailedMount  24m  kubelet, slave2  MountVolume.SetUp failed for volume "pvc-c9007abeba5a325a2cce65c6649692d6-pv" : CephFS: mount failed: mount failed: exit status 1
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/6d000df9-e380-495e-9738-a10b9082a23f/volumes/kubernetes.io\~cephfs/pvc-c9007abeba5a325a2cce65c6649692d6-pv --scope -- mount -t ceph -o \<masked\>,\<masked\> 192.168.9.51:6789,192.168.9.52:6789,192.168.9.53:6789:/kubeflow-fs/anli/laji/data /var/lib/kubelet/pods/6d000df9-e380-495e-9738-a10b9082a23f/volumes/kubernetes.io\~cephfs/pvc-c9007abeba5a325a2cce65c6649692d6-pv
Output: Running scope as unit run-737593.scope.
mount error 1 = Operation not permitted
  Warning  FailedMount  24m  kubelet, slave2  MountVolume.SetUp failed for volume "pvc-c9007abeba5a325a2cce65c6649692d6-pv" : CephFS: mount failed: mount failed: exit status 1
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/6d000df9-e380-495e-9738-a10b9082a23f/volumes/kubernetes.io\~cephfs/pvc-c9007abeba5a325a2cce65c6649692d6-pv --scope -- mount -t ceph -o \<masked\>,\<masked\> 192.168.9.51:6789,192.168.9.52:6789,192.168.9.53:6789:/kubeflow-fs/anli/laji/data /var/lib/kubelet/pods/6d000df9-e380-495e-9738-a10b9082a23f/volumes/kubernetes.io\~cephfs/pvc-c9007abeba5a325a2cce65c6649692d6-pv
Output: Running scope as unit run-737672.scope.
mount error 1 = Operation not permitted
  Warning  FailedMount  24m  kubelet, slave2  MountVolume.SetUp failed for volume "pvc-c9007abeba5a325a2cce65c6649692d6-pv" : CephFS: mount failed: mount failed: exit status 1
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/6d000df9-e380-495e-9738-a10b9082a23f/volumes/kubernetes.io\~cephfs/pvc-c9007abeba5a325a2cce65c6649692d6-pv --scope -- mount -t ceph -o \<masked\>,\<masked\> 192.168.9.51:6789,192.168.9.52:6789,192.168.9.53:6789:/kubeflow-fs/anli/laji/data /var/lib/kubelet/pods/6d000df9-e380-495e-9738-a10b9082a23f/volumes/kubernetes.io\~cephfs/pvc-c9007abeba5a325a2cce65c6649692d6-pv
Output: Running scope as unit run-737718.scope.
mount error 1 = Operation not permitted
  Warning  FailedMount  23m  kubelet, slave2  MountVolume.SetUp failed for volume "pvc-c9007abeba5a325a2cce65c6649692d6-pv" : CephFS: mount failed: mount failed: exit status 1
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/6d000df9-e380-495e-9738-a10b9082a23f/volumes/kubernetes.io\~cephfs/pvc-c9007abeba5a325a2cce65c6649692d6-pv --scope -- mount -t ceph -o \<masked\>,\<masked\> 192.168.9.51:6789,192.168.9.52:6789,192.168.9.53:6789:/kubeflow-fs/anli/laji/data /var/lib/kubelet/pods/6d000df9-e380-495e-9738-a10b9082a23f/volumes/kubernetes.io\~cephfs/pvc-c9007abeba5a325a2cce65c6649692d6-pv
Output: Running scope as unit run-737877.scope.
mount error 1 = Operation not permitted
  Warning  FailedMount  23m  kubelet, slave2  MountVolume.SetUp failed for volume "pvc-c9007abeba5a325a2cce65c6649692d6-pv" : CephFS: mount failed: mount failed: exit status 1
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/6d000df9-e380-495e-9738-a10b9082a23f/volumes/kubernetes.io\~cephfs/pvc-c9007abeba5a325a2cce65c6649692d6-pv --scope -- mount -t ceph -o \<masked\>,\<masked\> 192.168.9.51:6789,192.168.9.52:6789,192.168.9.53:6789:/kubeflow-fs/anli/laji/data /var/lib/kubelet/pods/6d000df9-e380-495e-9738-a10b9082a23f/volumes/kubernetes.io\~cephfs/pvc-c9007abeba5a325a2cce65c6649692d6-pv
Output: Running scope as unit run-738076.scope.
mount error 1 = Operation not permitted
  Warning  FailedMount  23m  kubelet, slave2  MountVolume.SetUp failed for volume "pvc-c9007abeba5a325a2cce65c6649692d6-pv" : CephFS: mount failed: mount failed: exit status 1
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/6d000df9-e380-495e-9738-a10b9082a23f/volumes/kubernetes.io\~cephfs/pvc-c9007abeba5a325a2cce65c6649692d6-pv --scope -- mount -t ceph -o \<masked\>,\<masked\> 192.168.9.51:6789,192.168.9.52:6789,192.168.9.53:6789:/kubeflow-fs/anli/laji/data /var/lib/kubelet/pods/6d000df9-e380-495e-9738-a10b9082a23f/volumes/kubernetes.io\~cephfs/pvc-c9007abeba5a325a2cce65c6649692d6-pv

### What did you expect to happen:
i think the '\<masked\>,\<masked\>' not assigned。when i mount manual. the run can work. for example：systemd-run --scope -- mount -t ceph -o name=admin,secret=\`ceph-authtool -p /etc/ceph/ceph.client.admin.keyring\` 192.168.9.51:6789,192.168.9.52:6789,192.168.9.53:6789:/kubeflow-fs/anli/laji/data /var/lib/kubelet/pods/5d54492e-7d2b-4478-8534-06bbe97eedcd/volumes/kubernetes.io~cephfs/pvc-c9007abeba5a325a2cce65c6649692d6-pv

i think whe 'name=admin,secret=\`ceph-authtool -p /etc/ceph/ceph.client.admin.keyring\`' is missing

### Environment:
the kubernetes version is: v1.18.5
the kubeflow version is: 1.3.0
the pipeline api-version and ui version is: 1.5.0

*  How do you deploy Kubeflow Pipelines (KFP)? 

deploy the kubeflow through manifests-1.3.0

*  KFP version: 

1.3.0

*  KFP SDK version: 

thanks a lot

**Comment by Bobgy** [comment]
@yanniszark @elikatsis do you want to take a look?

**Comment by zm274310577** [comment]
@Bobgy thinks a lot. The problem has been solved, the pvc is created in another microservice. when the user is cephfs(I created it before),  mount failed. change to admin, mount success. here is the code. 

```
cephfs=client.V1CephFSPersistentVolumeSource(monitors=CEPH_MON_URLS.split(","),
        path=cephfs_path,
        user='admin',
        secret_ref=client.V1SecretReference(
        namespace=K8S_NAMESPACE,
        name=CEPH_FS_SECRET_NAME),
        read_only=False)
```

As for why cephfs failed, I don't know yet, but it's enough for me
