### ISSUE TITLE
[components] Upgrade minio to the latest version

### ISSUE THREAD

**Issue by haoxins** [kubeflow/pipelines#6431]
### Feature Area

/area components

Is there any reason not to upgrade the [**`minio`**](https://hub.docker.com/r/minio/minio/tags) to the latest version?
Is it open for others to submit PR for this?

**Comment by Bobgy** [comment]
Thanks, we don't allow AGPL, so if upgrade, we can only choose a version before it was changed to AGPL.

**Comment by Bobgy** [comment]
We might need to consider a MinIO alternative, so that people can keep getting security fixes.

**Comment by NikeNano** [comment]
> We might need to consider a MinIO alternative, so that people can keep getting security fixes.

What alternative are there out there I am only aware of [rook](https://github.com/rook/rook)/[ceph](https://github.com/ceph/ceph). What are we looking for when it comes to replacing Minio except the license?

**Comment by haoxins** [comment]
I think [SeaweedFS](https://github.com/chrislusf/seaweedfs) could be another alternative.

**Comment by MatthiasCarnein** [comment]
It seems that [NooBaa](https://www.noobaa.io/) could be another alternative using an Apache License. The Datashim project uses it in their [tutorials](https://github.com/datashim-io/datashim/wiki/Deployment-and-Usage-of-S3-Object-Stores) with BackingStore [PV-Pool](https://github.com/noobaa/noobaa-operator/blob/master/doc/backing-store-crd.md#pv-pool-type) to setup an S3 Object Store. The other BackingStores could potentially replace Minio's Gateway functionality.

**Comment by haoxins** [comment]
@MatthiasCarnein just a bit curious about the License details.

Because this project uses argo-workflows, and argo-workflows uses MinIO v7 APIs, https://github.com/argoproj/argo-workflows/blob/master/go.mod#L35
Is this also influence Kubeflow pipelines?

**Comment by MatthiasCarnein** [comment]
@haoxins I'm not a lawyer but from my understanding the Minio Client SDK for Go is a separate piece of software that uses the Apache 2.0 license: https://github.com/minio/minio-go/blob/master/LICENSE
