### ISSUE TITLE
[feature] Allow time to live to be set on pipelines individually while supporting the persistance agent to do the GC. 

### ISSUE THREAD

**Issue by NikeNano** [kubeflow/pipelines#6432]
### Feature Area

There have been multiple issues related to time to live(ttl) for pipelines, https://github.com/kubeflow/pipelines/issues/5545, https://github.com/kubeflow/pipelines/issues/5234. A common solution is to use `set_ttl_seconds_after_finish` which don't respect the persistence agent and can resolve in that data is lost for the users. 

In order to allow users to
configure the ttl for pipelines the suggested solution is to set `TTL_SECONDS_AFTER_WORKFLOW_FINISH` [https://github.com/kubeflow/pipelines/issues/5234#issuecomment-805599988]
but this will set for all pipelines.

### What feature would you like to see?

To support the persistence agent while allowing users to set time to live on pipeline level, I suggest that we add the option to the pipeline spec and
update the persistence agent to support this.

### What is the use case or pain point?

Today either the users have to set the same TTL for all pipelines(through `TTL_SECONDS_AFTER_WORKFLOW_FINISH`  in the persistiance agent) or 
use `set_ttl_seconds_after_finish` which might result in data lose. 

### Is there a workaround currently?

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by NikeNano** [comment]
ping @Bobgy WDYT?

**Comment by SebBlin** [comment]
As far as I understand it, latest releases of KFP come with an updated release of Argo, that as update the way to specify a TTL in workflow (see https://argoproj.github.io/argo-workflows/fields/#ttlstrategy).
I made a PR to correct it : https://github.com/kubeflow/pipelines/pull/7141

**Comment by NikeNano** [comment]
As I understand this is now resolved so will close this.
