### ISSUE TITLE
Allow custom mounting for kfp local runner

### ISSUE THREAD

**Issue by etsyamitra** [kubeflow/pipelines#6435]
### Feature Area
Have been using the kfp local runner feature using the docker execution environment. 
......

run_pipeline_func_locally(
        pipeline_func,
        arguments={
            "train_output_dir": TRAINER_OUTPUT_PATH,
        },
        execution_mode=LocalClient.ExecutionMode("docker"),
    )
```
However this always traslated to docker running with mount on '/tmp'.  
```
['docker', 'run', '-v', '**/tmp:/tmp**', '<image>, '--training_epochs', '1', '--model_export_dir', '/tmp/model/1629731723/']
```
This pollutes the '/tmp' location in local and adds additional steps to components to interact (i.e. move over artifacts and keep them ready in corresponding '/tmp' location.
Alternatively if the component needs to access remote storage it needs to be authenticated and mounting the custom path/configs would be the only relatively safe way to do so.

### What feature would you like to see?
Ability for users to pass parameters to the docker itself like '-v' mount options or '--entrypoint' shell options etc.

### What is the use case or pain point?
There is friction in using kfp local runner as it is through docker vs plain docker due to the feature gap.

### Is there a workaround currently?
Move everything over to '/tmp' to use it for staging.


---

<!-- Don't delete message below to encourage users to support your feature request! -->
Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by chensun** [comment]
Just realize `run_pipeline_func_locally` is a wrapper function which does not expose the `pipeline_root` parameter. 

https://github.com/kubeflow/pipelines/pull/6462 should fix the issue.

**Comment by etsyamitra** [comment]
@chensun Thank you so much for working on it, would there be any way to expose the docker --entrypoint as well? It could be either at pipeline level or at component level to keep it custom.
