### ISSUE TITLE
KFP SDK v2 compatibility mode feedback

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#6451]
Documentation: www.kubeflow.org/docs/components/pipelines/sdk/v2/v2-compatibility/
Design: [bit.ly/kfp-v2-compatible](https://bit.ly/kfp-v2-compatible)
[New Features](https://docs.google.com/document/d/139pweX3PtCv96DLeyVYzZpcf3mB1Z0MFvjSEmu4D3tg/edit?pli=1#heading=h.jmnajnr9e0zj)
Breaking Changes and Known Caveats: https://github.com/kubeflow/pipelines/issues/6133

For **feedbacks**, comment on this issue.
For **bug reports**, create a separate issue logging the details and comment about it here.

**Comment by ConverJens** [comment]
KFP SDK v2 issue: https://github.com/kubeflow/pipelines/issues/6574

**Comment by AlexandreBrown** [comment]
Hello, we love the v2 so far but we would highly appreciate to be able to compare runs like we used to on v1.  
This is our main use of pipelines, to compare their metrics.  
Thanks and keep up the good work.

**Comment by zijianjoy** [comment]
Tracking issue mentioned by @AlexandreBrown in https://github.com/kubeflow/pipelines/issues/6912

**Comment by ConverJens** [comment]
@Bobgy https://github.com/kubeflow/pipelines/issues/7561

**Comment by Bobgy** [comment]
cc @chensun @zijianjoy

**Comment by rimolive** [comment]
Closing this issue as it looks like very outdated.

/close
