### ISSUE TITLE
[bug] Problem starting a pipeline run with REST api

### ISSUE THREAD

**Issue by mlu4679** [kubeflow/pipelines#6457]
### What steps did you take

I am trying to use the KFP REST API in order to create a new run of a pipeline that already exists.
Using the python requests package, I am authenticating myself in order to use POST and GET requests with the API. Currently, the GET requests work as intended, however, when I try to use a POST request to start a new pipeline run, I run into an error. A snippet of the code I am using is below:
```

runURL = f"{HOST}/pipeline/apis/v1beta1/runs"
inputobject2={"description":"","name":"gcd_test3","pipeline_spec":
{"parameters":[{"name":"a","value":"70"},{"name":"b","value":"35"},{"name":"c","value":"42"},{"name":"d","value":"14"}]},
"resource_references":[{"key":{"id":experimentID,"type":"EXPERIMENT"},"relationship":"OWNER"},
{"key":{"id":pipelineid,"type":"PIPELINE_VERSION"},"relationship":"CREATOR"}],"service_account":""}
headers2 = {
        "Content-Type": "application/json"
    }
output = session.post(runURL, data=inputobject2, headers = headers2)
pp.pprint(output)
pp.pprint(output.json())
```

### What happened:
I get a response 400 error, with the following text:
```
<Response [400]>
{'code': 3,
 'details': [{'@type': 'type.googleapis.com/api.Error',
              'error_details': 'Invalid input error: ListRuns must filter by '
                               'resource reference in multi-user mode.',
              'error_message': 'ListRuns must filter by resource reference in '
                               'multi-user mode.'}],
 'error': 'Invalid input error: ListRuns must filter by resource reference in '
          'multi-user mode.',
 'message': 'Invalid input error: ListRuns must filter by resource reference '
            'in multi-user mode.'}
```
### What did you expect to happen:
I expect that a new pipeline run should start, and that I should be able to view the details of the run in the KFP UI.
### Environment:

*  KFP version: 

1.0.0
*  KFP SDK version: 

kfp                           1.2.0
kfp-server-api                1.2.0

### Anything else you would like to add:

As said earlier, using get requests to retrieve information such as all the pipelines that already exist works fine, it is just the HTTPS POST commands that do not work. 

### Labels

/area sdk 

---

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by zijianjoy** [comment]
Hello @mlu4679 , you can refer to https://www.kubeflow.org/docs/components/pipelines/multi-user/#how-are-resources-separated to specify resource, you can use either the resource `NAMESPACE ` or `EXPERIMENT` in resource filter. Because these two fields allow multi-user mode to learn which namespace to run your pipeline.

Reference:
https://www.kubeflow.org/docs/components/pipelines/reference/api/kubeflow-pipeline-api-spec/#/definitions/apiResourceReference

**Comment by mlu4679** [comment]
Hi @zijianjoy
In the documentation, they use the object ApiResourceReference to specify the resource, is it possible to convert it to a dictionary to pass it along in my POST request? The sample seems to still use the kfp client in order to create a run/experiment.

**Comment by zijianjoy** [comment]
Hello @mlu4679 

Does this look like something you are looking for? https://github.com/kubeflow/website/issues/2916
