### ISSUE TITLE
[bug] Unhandled SageMaker training job status 'stopped' causing infinite loop

### ISSUE THREAD

**Issue by benhyy** [kubeflow/pipelines#6465]
### What steps did you take

Code gets stuck in infinite loop is SageMaker training job gets stopped (unhandled use case)

### What happened:

https://github.com/kubeflow/pipelines/blob/master/components/aws/sagemaker/train/src/sagemaker_training_component.py#L57-L66

Above code only caters for training job status `Completed` or `Failed`, so if the training job status is marked as `Stopped`, it causes an infinite loop in below code

https://github.com/kubeflow/pipelines/blob/d9c019641ef9ebd78db60cdb78ea29b0d9933008/components/aws/sagemaker/common/sagemaker_component.py#L197-L201

### What did you expect to happen:

Training job status `stopped` to be catered for

### Labels

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by NikeNano** [comment]
Thanks for adding this issue. You are more than welcome to contribute a fix @benhyy.

**Comment by surajkota** [comment]
This has been resolved in https://github.com/kubeflow/pipelines/pull/8336. Please use the latest version of components and let us know if you face any problems. Thanks
