### ISSUE TITLE
v2 - downloading/uploading artifacts should be backoff retried

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#6469]
v2 sample test flaky when downloading/uploading artifacts with error message:
```
net/http: TLS handshake timeout
```

_Originally posted by @Bobgy in https://github.com/kubeflow/pipelines/issues/6468#issuecomment-908093370_

**Comment by Bobgy** [comment]
the error is expected, because network is not always stable.
In these cases, we should have a backoff retry to handle the flakiness of network.

**Comment by capri-xiyue** [comment]
Reassigned it to James Wu to further discuss the priority and the assignee
