### ISSUE TITLE
Update doc to remove hard coded version

### ISSUE THREAD

**Issue by hongye-sun** [kubeflow/pipelines#647]
In the doc (https://www.kubeflow.org/docs/guides/pipelines/build-pipeline/), it includes a hard coded version, which will soon be obsolete after newer releases. 

Let's fix it by having a placeholder and have a link pointing to the release pages to let user pick up the latest version.

**Comment by IronPan** [comment]
We shouldn't have any hardcoded version in the doc since SDK should in theory be preinstalled in the JH image and user shouldn't do anything.

**Comment by vicaire** [comment]
Can this be closed?

**Comment by hongye-sun** [comment]
We still have the sdk version hard coded in the doc: https://www.kubeflow.org/docs/pipelines/sdk/install-sdk/.

**Comment by IronPan** [comment]
Yeah I would suggest use a placeholder and a link to release page too.

**Comment by IronPan** [comment]
Jupyter hub image don't release weekly so the SDK version there will be outdated too.

**Comment by gaoning777** [comment]
Should we close it? I think https://www.kubeflow.org/docs/pipelines/sdk/install-sdk/ has a placeholder for the SDK version now.

**Comment by gaoning777** [comment]
Feel free to reopen this issue.
