### ISSUE TITLE
Which all artifact types can be created using the pipeline sdk which are supported by argo workflows?

### ISSUE THREAD

**Issue by sujaykulkarn** [kubeflow/pipelines#6479]
Hi, I was trying to understand how to create HTTP, git and other artifacts using SDK which are supported by Argo Workflows. (https://argoproj.github.io/argo-workflows/configure-artifact-repository/) please help with your inputs on how to create pipelines using these artifacts. Thanks

**Comment by zijianjoy** [comment]
Hello @sujaykulkarn , currently this is not supported by KFP. cc @chensun

**Comment by chensun** [comment]
I think the ask is to support additional artifact repositories, which needs to be supported by KFP runtime first. 

@Bobgy to comment.

**Comment by Bobgy** [comment]
I am interested in more user feedback before adding these features, because you can also download the artifact you want in a component.
More detailed use-case that explains why these are useful are helpful.

And please thumbs up on the issue, if you are interested too.

**Comment by sujaykulkarn** [comment]
Hi @chensun, by KFP runtime you mean argo controller right? if that's the case it supports these extra artifacts, I tried manually editing the workflow YAML and deployed it in the Kubeflow pipelines UI and it works. But manual editing of workflow is difficult so if we have support for the same using KFP SDK it will be useful. 
@Bobgy Yes I agree with you, for general if KFP SDK supports these features then the user who has stored their input artifacts in a say git-repo, or an HTTP artifactory repo can easily intake those artifacts and also there are N number of opportunities which comes with this feature.
