### ISSUE TITLE
[backend] API performance regression in 1.5

### ISSUE THREAD

**Issue by jmcarp** [kubeflow/pipelines#6492]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
Standalone
*  KFP version: 
1.5.1
*  KFP SDK version: 
n/a

### Steps to reproduce

- Upgrade from 1.4.1 to 1.5.1.
- Refresh the runs page several times.
- API latency is mostly fast (~500ms) but sometimes jumps to >30s.

<img width="875" alt="Screen Shot 2021-09-01 at 11 28 10 PM" src="https://user-images.githubusercontent.com/1633460/131781384-e752bb4f-dd96-4aa8-95d2-46491b1218fd.png">

Note: after downgrading to 1.4.1, API performance was consistently fast (~500ms).

<img width="876" alt="Screen Shot 2021-09-02 at 12 21 53 AM" src="https://user-images.githubusercontent.com/1633460/131781405-2e3cd16d-9cd0-4130-b6a9-68c44924d952.png">

### Expected result

API performance should be unchanged.

### Materials and Reference

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by Bobgy** [comment]
Hi @jmcarp, thank you for filing this report!
Is it possible also trying to reproduce in the latest 1.7.0 release?

I don't have any ideas at the moment, so welcome any contributions
