### ISSUE TITLE
[sdk] compilation failed when reusing operator definition on inner For loop

### ISSUE THREAD

**Issue by vmolina** [kubeflow/pipelines#6495]
### Environment

*  KFP version: Not important
*  KFP SDK version: 1.7.* and 1.8.*

*  All dependencies version:
kfp                                     1.7.1
kfp-pipeline-spec                       0.1.10
kfp-server-api                          1.7.0
### Steps to reproduce

The following script fails to build to compile the pipeline when using kfp==1.7.* but succeeds when using kfp=1.6*

```python
import kfp
from kfp.components import create_component_from_func
from kfp.compiler import Compiler

from typing import List

def get_iterator() -> List[str]:
    return ["a", "b"]

def print_output(a: str, b: str) -> None:
    print(a, b)

@kfp.dsl.pipeline(name="test_pipeline")
def pipeline_func():
    op = create_component_from_func(get_iterator)()
    print(op.name)
    with kfp.dsl.ParallelFor(op.output) as loop_var:
        op2 = create_component_from_func(get_iterator)()
        print(op2.name)
        with kfp.dsl.ParallelFor(op2.output) as loop_var2:
            create_component_from_func(print_output)(a=loop_var, b=loop_var2)

Compiler().compile(pipeline_func, "test.yaml")

```

with the following error

> Traceback (most recent call last):
>   File "test/test_kfp_version_compat.py", line 24, in <module>
>     Compiler().compile(pipeline_func, "test.yaml")
>   File "/Users/victor.bellon/.virtualenvs/continuous-elas-meta/lib/python3.8/site-packages/kfp/compiler/compiler.py", line 1061, in compile
>     self._create_and_write_workflow(
>   File "/Users/victor.bellon/.virtualenvs/continuous-elas-meta/lib/python3.8/site-packages/kfp/compiler/compiler.py", line 1114, in _create_and_write_workflow
>     workflow = self._create_workflow(
>   File "/Users/victor.bellon/.virtualenvs/continuous-elas-meta/lib/python3.8/site-packages/kfp/compiler/compiler.py", line 950, in _create_workflow
>     workflow = self._create_pipeline_workflow(
>   File "/Users/victor.bellon/.virtualenvs/continuous-elas-meta/lib/python3.8/site-packages/kfp/compiler/compiler.py", line 717, in _create_pipeline_workflow
>     templates = self._create_dag_templates(pipeline, op_transformers)
>   File "/Users/victor.bellon/.virtualenvs/continuous-elas-meta/lib/python3.8/site-packages/kfp/compiler/compiler.py", line 653, in _create_dag_templates
>     inputs, outputs = self._get_inputs_outputs(
>   File "/Users/victor.bellon/.virtualenvs/continuous-elas-meta/lib/python3.8/site-packages/kfp/compiler/compiler.py", line 272, in _get_inputs_outputs
>     upstream_op = pipeline.ops[param.op_name]
> KeyError: 'get-iterator 2'

### Expected result

The pipeline should compile properly

### Materials and Reference

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by chensun** [comment]
This is fixed by https://github.com/kubeflow/pipelines/pull/6600
Pending KFP SDK 1.8.3 release (by today).
