### ISSUE TITLE
I believe this issue was fixed by #6473 . Closing as fixed, this is not the case please reopen this bug.

### ISSUE THREAD

**Issue by cah-parita-desai** [kubeflow/pipelines#6502]
I believe this issue was fixed by #6473 . Closing as fixed, this is not the case please reopen this bug.

_Originally posted by @SinaChavoshi in https://github.com/kubeflow/pipelines/issues/6426#issuecomment-911878051_

**Comment by cah-parita-desai** [comment]
@SinaChavoshi :- Wer you able to look into this further?

**Comment by Bobgy** [comment]
thank you for the report! reopened https://github.com/kubeflow/pipelines/issues/6426 for you
