### ISSUE TITLE
Where is the changelog for the `kfp` PyPi package?

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/pipelines#6511]
I often see releases for the [`kfp` PyPi releases](https://pypi.org/project/kfp/#history) which are not aligned with [`kubeflow/pipelines` releases](https://github.com/kubeflow/pipelines/releases), for example the latest versions are currently:
- [`kfp` == `1.8.0`](https://pypi.org/project/kfp/1.8.0/)
- [`kubeflow/pipelines` == `1.7.0`](https://github.com/kubeflow/pipelines/releases/tag/1.7.0).

__So I have two questions:__
1. Is there a public changelog for the `kfp` PyPi package (similar to the main [CHANGELOG.md](https://github.com/kubeflow/pipelines/blob/master/CHANGELOG.md))?
2. How are `kfp` PyPi releases related to pipelines releases?

**Comment by zijianjoy** [comment]
cc @chensun 

Currently we don't have CHANGELOG, defer to Chen to determine the direction of documentation

**Comment by chensun** [comment]
@thesuperzapper We have the changelog for SDK: https://github.com/kubeflow/pipelines/blob/master/sdk/RELEASE.md

> How are kfp PyPi releases related to pipelines releases?

KFP SDK is released independently. It's meant to be backward compatible with KFP backend except otherwise noticed.

**Comment by thesuperzapper** [comment]
@chauhang  perhaps we should link this changelog on [the `kfp` PyPi](https://pypi.org/project/kfp/)?

**Comment by chensun** [comment]
> @chauhang perhaps we should link this changelog on [the `kfp` PyPi](https://pypi.org/project/kfp/)?

That's a good. Will do so.
