### ISSUE TITLE
[backend] Caching leads to unexpected prefix error

### ISSUE THREAD

**Issue by jonasdebeukelaer** [kubeflow/pipelines#6526]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)? standalone on azure with minio object storage
*  KFP version: `1.7.0`
To find the version number, See version number shows on bottom of KFP UI left sidenav. -->
*  KFP SDK version: 
```
kfp                                   1.7.1
kfp-pipeline-spec                     0.1.9
kfp-server-api                        1.7.0
```

### Steps to reproduce

Run a pipeline twice with the second step getting an artifact from the first step.

Second run will fail on something like

```
Failed to execute component: failed to download input artifact "model" from remote storage URI "minio://mlpipeline/v2/artifacts/pipeline/my pipeline/3341543c-cb07-464b-b6a8-4d58d86fb209/train-3/model": URI "minio://mlpipeline/v2/artifacts/pipeline/my pipeline/3341543c-cb07-464b-b6a8-4d58d86fb209/train-3/model" does not have expected bucket prefix "minio://mlpipeline/v2/artifacts/pipeline/my pipeline/78bfc8c3-6707-474e-9b20-b6132830c060"

(I think this part is unrelated but leaving in in case it's useful)
time="2021-09-07T16:12:03.327Z" level=error msg="cannot save artifact /tmp/outputs/predictions/data" argo=true error="stat /tmp/outputs/predictions/data: no such file or directory"
Error: exit status 1
```

where `78bfc8c3-6707-474e-9b20-b6132830c060` is he current pipeline id and `3341543c-cb07-464b-b6a8-4d58d86fb209` is the previous pipeline run id.

### Expected result

caching works as expected and the new pipeline is able to access its cached results.

### Materials and Reference

error happens in line 100 in `object_store.go`.

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by Bobgy** [comment]
Hi @jonasdebeukelaer, that's a bug I introduced, I believe it should be fixed by https://github.com/kubeflow/pipelines/pull/6415 as a side effect. Can you verify KFP SDK 1.8.0?

**Comment by jonasdebeukelaer** [comment]
@Bobgy yes seems that fixed it thanks, sorry didn't see a new version had been released!

**Comment by Bobgy** [comment]
No worries, thank you for verifying the new version!
