### ISSUE TITLE
[bug] Sanitize Names kfp.dsl doesn't allow the usage of argo template variables

### ISSUE THREAD

**Issue by munagekar** [kubeflow/pipelines#6559]
### What steps did you take

Named a k8s resource as`xxx-{{workflow.uid}}`. It got converted to xxx-workflow-uid. This breaks argo workflow templating.

https://github.com/kubeflow/pipelines/blob/5d82fa7dc8dfe381a8759358b92cc94ef0a0f137/sdk/python/kfp/compiler/_k8s_helper.py#L20-L37. 

### What did you expect to happen:

k8s resource names should allow argo workflow templating.

### Anything else you would like to add:

`{{.+}}` should be considered a special case and should not be affected by name sanitization.

### Labels

/area sdk

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by chensun** [comment]
@munagekar, For my education, what's your use case to include Argo placeholders in some "name"?

**Comment by munagekar** [comment]
@chensun 

- prefix multiple resources created(svc,pvc,depolyment associated with a workflow ) with {{workflow.name}} to link all relevant resources together.
- avoid a resource-name-conflict if the same pipeline is executed twice simultaneously by making the name dependent on unique-id.
- previously this also prevented caching with VolumeOp by making the name unique. [REF](https://github.com/kubeflow/pipelines/issues/5257#issuecomment-813350932)
