### ISSUE TITLE
Issues for running pipelines without using GCP

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#658]
https://kubeflow.slack.com/conversation/CE10KS9M4/p1547076813104800
Igor Mameshin [1 hour ago]
@Alexey Volkov Sure there are multiple examples

Igor Mameshin [1 hour ago]
code-snippets/ml/kubeflow-pipelines/components/kubeflow/tf-serving/deploy-tf-serve.py:
```logging.info('Getting credentials for GKE cluster %s.' % cluster)
  subprocess.call(['gcloud', 'container', 'clusters', 'get-credentials', cluster,  '--zone', zone])```
```

Igor Mameshin [44 minutes ago]
code-snippets/ml/kubeflow-pipelines/components/kubeflow/containers/tf-serving/build.sh:
```
if [ -z "$1" ]
  then
    PROJECT_ID=$(gcloud config config-helper --format "value(configuration.properties.core.project)")
else
  PROJECT_ID=$1
fi
```

Igor Mameshin [37 minutes ago]
That’s for users who are interested in modifying and rebuilding example containers such as “gcr.io/google-samples/ml-pipeline-t2tproc”

Igor Mameshin [36 minutes ago]
But not everyone would need to modify the sample Docker images provides with examples

Igor Mameshin [35 minutes ago]
So at the minimum, Kubeflow should provide external configuration for storage

Igor Mameshin [24 minutes ago]
The TaxiCab example pipeline distributed with Kubeflow depends on Apache Beam for TFDV step:
kubeflow/pipelines/components/dataflow/tfdv/src/validate.py:
```
stats = tfdv.generate_statistics_from_csv(
        data_location=csv_data_file,
        column_names=column_names,
        delimiter=',',
        output_path=os.path.join(output_dir, 'data_stats.tfrecord'),
        pipeline_options=pipeline_options)
```

Igor Mameshin [21 minutes ago]
There is dependency on Apache Beam which does not currently support S3 from Python SDK, but it supports it from Java SDK.

Igor Mameshin [19 minutes ago]
TFDV is a valuable example.  I don’t know what is the best approach - rewrite TFDV step in Java, or not use Apache Beam, or add support for S3 to Apache Beam.  Neither of those options are a quick fix, so adding support for S3 in Beam may be the best options.

**Comment by govindKAG** [comment]
The articles say that the logs are collected from stack driver. Do logs work with pipelines if you are not on GCP?

**Comment by Ark-kun** [comment]
> The articles say that the logs are collected from stack driver. Do logs work with pipelines if you are not on GCP?

/assign @IronPan

**Comment by Ark-kun** [comment]
Related https://github.com/kubeflow/pipelines/issues/1654
