### ISSUE TITLE
[bug] How to use Sidecar in Vertex pipeline?

### ISSUE THREAD

**Issue by simanwangSC** [kubeflow/pipelines#6581]
### What steps did you take

In kfp pipeline I can use the following code to create a containerOp and add a Sidecar to it:
```
sidecar_task = dsl.Sidecar(name='x', image='x')
main_task = dsl.ContainerOp(name='x', image='x', sidecars=[sidecar_task])
```
When I switch to Vertex pipeline, since `dsl.ContainerOp` is deprecated I need to create a component like this:
```
main_op = kfp.components.load_component_from_text('''
    name: main_op
    implementation:
      container:
        image: x
    ''')
main_task = main_op()
```
I wonder how can I add a sidecar to it. Thank you.

### Environment:

*  How do you deploy Kubeflow Pipelines (KFP)? 

*  KFP version: 

*  KFP SDK version: 

### Labels

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by judahrand** [comment]
I think the way you'd want to do this for Vertex (although I'm not sure if sidecars are supported 🤔 ):

```python
main_op = kfp.components.load_component_from_text('''
    name: main_op
    implementation:
      container:
        image: x
    ''')
main_task = main_op()

sidecar_task = dsl.Sidecar(name='x', image='x')
main_task.add_sidecar(sidecar_task)
```

**Comment by chensun** [comment]
Sidecar is not support on Vertex Pipelines.

**Comment by capri-xiyue** [comment]
We don't have the plan to support sidecar in vertex pipeline in the near future.
