### ISSUE TITLE
method to check if SDK is talking to a real KFP API

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/pipelines#6585]
Currently, there does not seem to be a method on [`kfp.Client()`](https://kubeflow-pipelines.readthedocs.io/en/stable/source/kfp.client.html) which can reliably confirm that the `url` provided is actually a Kubeflow Pipelines API.

_NOTE: methods like `Client().list_pipelines()`  return `{'next_page_token': None, 'pipelines': None, 'total_size': None}` when run against non-kubeflow apis (which is indistinguishable from there being no pipelines in the cluster)._

__What is the best way to determine that a `kfp.Client()` instance is valid?__

**Comment by thesuperzapper** [comment]
@Bobgy am I missing something?

**Comment by NikeNano** [comment]
Could we use the health endpoint to validate this `/apis/v1beta1/healthz` , https://github.com/DavidSpek/pipelines/blob/4c3d6dd4ff7460c51611976090a26b9216ea2056/sdk/python/kfp/_client.py#L298-L303

**Comment by NikeNano** [comment]
/assign 
I will make a method and add PR to validate if connect to a `kubeflow pipelines` or not.

**Comment by NikeNano** [comment]
Or do we actually need to have a separate functionality in the sdk for this @thesuperzapper ?

**Comment by capri-xiyue** [comment]
We will call `get_kfp_healthz` api every time when we initialize client. Maybe we can check the response of `get_kfp_healthz` api to check whether it connects to a real KFP API. Refer to [code](https://github.com/kubeflow/pipelines/blob/7875b68654a69ca761cb0ba4a920a30925a0e94b/sdk/python/kfp/_client.py#L196)

**Comment by rimolive** [comment]
Closing this issue as it's stale for more than a year. Feel free to reopen it if the issue is still relevant.

/close
