### ISSUE TITLE
Potentially duplicated function list_pipeline_versions()?

### ISSUE THREAD

**Issue by KausthubK** [kubeflow/pipelines#6586]
Seems like there are two versions of this function within the same module:

https://github.com/kubeflow/pipelines/blob/7875b68654a69ca761cb0ba4a920a30925a0e94b/sdk/python/kfp/_client.py#L661

https://github.com/kubeflow/pipelines/blob/7875b68654a69ca761cb0ba4a920a30925a0e94b/sdk/python/kfp/_client.py#L1324

Should one of these be deprecated/removed/renamed?

**Comment by NikeNano** [comment]
Since they have the same name, the last one will be the one that is exposed when using the `Client`. Thus I think it should be fine to remove the one on L661.

**Comment by KausthubK** [comment]
@NikeNano - agreed - not sure on how proceed to a PR for this 🤷🏾‍♂️ 

I'm unable to create a remote branch with the change. I'm following the contribution readme [CONTRIBUTION.md](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md) but it doesn't say much re: creating upstream branches.

Or am I supposed to fork, fix, and send a patch? 

Or is there a core dev team that's taking care of it?

**Comment by NikeNano** [comment]
Workflow would be along the lines: 
1) Fork the repository: https://github.com/kubeflow/pipelines
2) Create a branch and update the code
3) Make a pull request to https://github.com/kubeflow/pipelines from your forked repo. 

You are more than welcome to make a PR to Kubeflow pipelines :) someone in the core team have to approve the PR, you can see who are part of the core team after you make a PR in the comments from the bot.

**Comment by KausthubK** [comment]
@NikeNano - thanks - I think I've done it right? hahaha (I'm a little new to forks and upstream contribution workflows like this one - typically worked within an org).

**Comment by NikeNano** [comment]
> @NikeNano - thanks - I think I've done it right? hahaha (I'm a little new to forks and upstream contribution workflows like this one - typically worked within an org).

Looks great! Had the same experience when I started to contribute to open source :)
