### ISSUE TITLE
Docs about how to write mlpipeline-ui-metadata and mlpipeline-metrics artifacts

### ISSUE THREAD

**Issue by xiaozhouX** [kubeflow/pipelines#660]
We can find that pipeline support argo artifact named `/mlpipeline-ui-metadata.json` and `/mlpipeline-metrics.json`, and some samples use it like [confusion_matrix.py](https://github.com/kubeflow/pipelines/blob/d79a835b3e433fc2439bf4ce6f4c703866f8fdcf/components/local/confusion_matrix/src/confusion_matrix.py). The artifact is finally rendered by frontend.
Are there any docs about the scheme and format of the artifacts ?

**Comment by yebrahim** [comment]
There are docs sections [here](https://www.kubeflow.org/docs/guides/pipelines/output-viewer/) and [here](https://www.kubeflow.org/docs/guides/pipelines/pipelines-metrics/), do these have what you need?

**Comment by xiaozhouX** [comment]
> There are docs sections [here](https://www.kubeflow.org/docs/guides/pipelines/output-viewer/) and [here](https://www.kubeflow.org/docs/guides/pipelines/pipelines-metrics/), do these have what you need?

yes, exactly. Thanks very much.

**Comment by yebrahim** [comment]
Great, closing this issue then.
