### ISSUE TITLE
Do I need to be running kubeflow on GCP to use pipelines?

### ISSUE THREAD

**Issue by govindKAG** [kubeflow/pipelines#661]
The articles on pipelines seem to suggest that pipelines are in some way dependent on GCP. I could not find anything definitive on this front. Is it possible to fully utilize kubeflow pipelines without GCP? if not, is it by design?

**Comment by paveldournov** [comment]
KubeFlow pipeline at its core is a multi-cloud platform and can be deployed on-prem as well, however some of the specific pipeline examples (e.g. TFX Taxi sample and Spark sample pipelines) require GCP services such as the GCS storage, DataFlow, and DataProc. We will be publishing more cloud neutral samples going forward and welcome contributions to the sample pipelines that are GCP independent.

**Comment by gaoning777** [comment]
Another aspect is that we will provide more kubernetes interfaces in the DSL language. For example, [image_pull_secret](https://github.com/kubeflow/pipelines/issues/695) will be exposed in the DSL such that images can be fetched from other registries. The goal is to make Kubeflow pipeline a kubernetes native(cross-platform) product.

**Comment by govindKAG** [comment]
that's good to know!

**Comment by pankajxyz** [comment]
@paveldournov I am also searching cloud neutral pipeline. The idea is to develop locally and scale it later on cloud. Please let me know if you have any jupyter notebook of some cloud neutral pipeline.  Right now, It seems like we must provide google cloud storage directory:
![image](https://user-images.githubusercontent.com/3924040/71808056-b904e980-30a7-11ea-9548-9e6e24063168.png)
