### ISSUE TITLE
[feature] V2 DSL Load_component_from_url Dataflow

### ISSUE THREAD

**Issue by pmcvay** [kubeflow/pipelines#6614]
### Feature Area

 /area components 

### What feature would you like to see?

Currently, it looks like loading the dataflow yaml components does not support v2. Also, the other google pipeline component seem to no longer use loading from url and instead use the google_cloud_pipeline_components library. It would be nice if the dataflow jobs were in that library as well

### What is the use case or pain point?
I have looked and I don't see a load_component_from_url under `import kfp.v2.component` so I have been using the old `import kfp.component`. I also was not able to find a yaml file for the `launch_flex_template` for v2.

```
dataflow_template_op = load_component_from_url(
    'https://raw.githubusercontent.com/kubeflow/pipelines/master/components/google-cloud/google_cloud_pipeline_components/experimental/dataflow/launch_flex_template/component.yaml'
)
```
```
/Users/.../lib/python3.8/site-packages/kfp/components/_components.py:174: FutureWarning: Container component must specify command to be compatible with KFP v2 compatible mode and emissary executor, which will be the default executor for KFP v2.https://www.kubeflow.org/docs/components/pipelines/installation/choose-executor/
  warnings.warn(
```

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by zijianjoy** [comment]
cc @IronPan would you like to add `command` to the component?
