### ISSUE TITLE
[frontend] Log tab issue with archived_logs and cache

### ISSUE THREAD

**Issue by boarder7395** [kubeflow/pipelines#6615]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
Kubeflow
*  KFP version: 
1.0.4

### Steps to reproduce
Run a pipeline that uses the cache for some component with archive logs configured.

### Expected result
When the pod is garbage collected after pulling from the cache the logs tab should either display "Pulled from cache." or
the logs of the original components run. How the logic is in the version of kfp I am using (1.0.4) the archive logs are pulled from prefix/{workflow.name}/{pod.name} and when the component was pulled from cache this file does not exist so the UI
displays "Failed to retrieve pod logs.".

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by zijianjoy** [comment]
Hello @boarder7395 , the pod log will not be cached, so it is expected not seeing the log. If you want to see this feature, maybe adding a feature request?
