### ISSUE TITLE
Is it possible to use a local path to stage a file for a kubeflow pipeline?

### ISSUE THREAD

**Issue by drubinstein** [kubeflow/pipelines#6620]
Hi,

I have a local csv file that I want to use to kick start my pipeline. Is there a way to "stage" that file using kubeflow? I can't quite make sure if it's possible to use InputPath as a pipeline parameter or not. Am I supposed to upload my file to GCS and then pass the GCS URI along instead?

Thanks

**Comment by su0625** [comment]
Hi,

Can this help you https://github.com/kubeflow/pipelines/issues/2977 ?

**Comment by drubinstein** [comment]
Yup. This seems relevant.

**Comment by drubinstein** [comment]
Looks like it's only accessible via the kfp CLI though?

**Comment by mike0355** [comment]
I think you can use add your csv file into dockerimage(In the dockerfile you can use "add" to add your csv file).
On the pipeline , you can try this code:

     import sys
     sys.path.append("your csv file path")
I use this method to my local npz file on the pipeline , and it's work for me.


![image](https://user-images.githubusercontent.com/51089749/135808805-2058cf2b-2295-4af7-a2b3-0bea6cbd3505.png)

**Comment by zijianjoy** [comment]
Looks like @mike0355 has already provided a solution. Please feel free to continue discussion if not worked.

**Comment by zhuyaguang** [comment]
if the data is too big ?
