### ISSUE TITLE
[feature] Is there any feature to control lifecycle of resource used in kf pipeline ?

### ISSUE THREAD

**Issue by anencore94** [kubeflow/pipelines#6644]
### What feature would you like to see?

There are `ResourceOp` to use some k8s resources(pvc, configmap, secret, ...) in kubeflow pipeline.
However, Is it possible to create and tear down such resources from the start of pipeline and the end of the pipeline ?
Also, Is it possible to tear down such resources no matter what pipeline succeeded or not (like `try ~ finally`)?

I couldn't find existing methods for this feature yet.

### What is the use case or pain point?

I'd like to use for control pvc's lifecycle to sync with kfp run and control some other custom resources.

### Is there a workaround currently?

Not yet

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by midhun1998** [comment]
Hi,
AFAIK we can leverage `ExitHandler `to tear down resources.
https://kubeflow-pipelines.readthedocs.io/en/latest/_modules/kfp/dsl/_ops_group.html#ExitHandler
