### ISSUE TITLE
[bug] Kubeflow VolumeOp (PVC) not delete after Pipeline execution.

### ISSUE THREAD

**Issue by peterhaddad3121** [kubeflow/pipelines#6649]
### What steps did you take

The first step of a Pipeline is creating a VolumeOp to be attached to a couple of KF components in a Pipeline.
After the pipeline finishes and all Component pods are Completed then deleted, the PVC created does not delete.
### What happened:

I edited the deployment of ml-pipeline-persistenceagent to include:
```
   - name: TTL_SECONDS_AFTER_WORKFLOW_FINISH
      value: "60"
```

### What did you expect to happen:

The PVC of the VolumeOp created to be deleted. All pods are deleted after pipeline completion, the PVC still exists and no deletion timestamp exists.

### Environment:

*  How do you deploy Kubeflow Pipelines (KFP)? 

*  KFP version: 

*  KFP SDK version: 

### Anything else you would like to add:

I saw all the corresponding issues, but this is related to using ArgoCD. This is using the Python SDK to run and create PIpelines.

### Labels

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by zijianjoy** [comment]
Possible related: https://github.com/kubeflow/pipelines/issues/3938

**Comment by juliusvonkohout** [comment]
Please close, since with #6622 merged you can set the owner references properly.
