### ISSUE TITLE
Document DSL functionality to specify execution order and execution dependencies

### ISSUE THREAD

**Issue by swiftdiaries** [kubeflow/pipelines#665]
Is there a way to order steps other than passing file_outputs to enforce dependencies? 
I'd like to be able to do: 
dsl.ContainerOp(step_name='first')
dsl.ContainerOp(step_name='second')
dsl.ContainerOp(step_name='third', dependencies=['first', 'second'])

Something similar to https://github.com/argoproj/argo/blob/master/examples/dag-coinflip.yaml.

**Comment by swiftdiaries** [comment]
TIL
You can add dependencies by doing:
op_name_second.after(op_name_first)

https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/dsl/_container_op.py#L104

**Comment by vicaire** [comment]
Does it solve your problem? Can we close this issue?

**Comment by swiftdiaries** [comment]
Yes it does solve the problem, I left it open for visibility in case other people were looking for something similar. We should probably add instructions to the website

**Comment by vicaire** [comment]
Good point. Re-opening and changing the title to keep track of adding the documentation.

**Comment by vicaire** [comment]
Note: instead of documentation on the website, it seems that having good samples would be a good option (assuming small samples, each documenting a particular feature).

**Comment by gaoning777** [comment]
Keeping track of the DSL samples in https://github.com/kubeflow/pipelines/issues/1034

**Comment by Ark-kun** [comment]
An easier way to add dependencies is to have data dependencies.
When you pass some output of task A to task B, the dependency is added, so you do not need  to write anything.

**Comment by gaoning777** [comment]
We do have samples illustrating the feature: https://github.com/kubeflow/pipelines/blob/a39ae8eb779e69e4e85e424abba8ecac3f60435f/samples/basic/recursion.py#L65. However it is not specifically for this feature. Agree that it is better to have a sample for each feature in the basic folder.

**Comment by SinaChavoshi** [comment]
submitted PR  #1668 for this issue pending addition of automated test for the sample.

**Comment by gaoning777** [comment]
Sample tests are tracked here: https://github.com/kubeflow/pipelines/issues/1813
