### ISSUE TITLE
python components don't work for images with python 2

### ISSUE THREAD

**Issue by alan-krumholz** [kubeflow/pipelines#666]
Same simple python code runs fine in an python 3 image but it won't run on a python 2 image:

```
import kfp
from kfp import compiler
import kfp.dsl as dsl
import kfp.notebook
import kfp.gcp as gcp
import datetime
OUTPUT_DIR = 'gs://pipelinestest/out'
PROJECT_NAME = 'energy-forecasting'
@dsl.python_component(
    name='Python test')
def python_Func() -> str:
    import tensorflow
    return("done")
P2Op = compiler.build_python_component(
    base_image = 'tensorflow/tensorflow:1.10.0',
    component_func = python_Func,
    staging_gcs_path = OUTPUT_DIR,
    target_image = 'gcr.io/' + PROJECT_NAME + '/component-p2:latest')
P3Op = compiler.build_python_component(
    base_image = 'tensorflow/tensorflow:1.10.0-py3',
    component_func = python_Func,
    staging_gcs_path = OUTPUT_DIR,
    target_image = 'gcr.io/' + PROJECT_NAME + '/component-p3:latest')
```

In the python 2 image, I get the following error:

> ImportError: No module named 'tensorflow'

In the python3 image, the component runs fine.

**Comment by gaoning777** [comment]
By default, the build_python_component configures the entrypoint as python3. That is why in python2 images, the tensorflow package is not found when you run python3 program. 
To support this, we need to change the component builder to make the entrypoint configurable.

**Comment by gaoning777** [comment]
fixing it in https://github.com/kubeflow/pipelines/pull/730

**Comment by gaoning777** [comment]
Now the component build supports python2. Fixed

**Comment by Ark-kun** [comment]
> def python_Func() -> str:

We only support Python 3.5+ officially.
Note that your function definition is only valid in Python 3.5+. It's a limitation of python, not Pipelines.
