### ISSUE TITLE
Support runtime drawing of sub-DAG.

### ISSUE THREAD

**Issue by zijianjoy** [kubeflow/pipelines#6674]
Prerequisite: https://github.com/kubeflow/pipelines/issues/6779

**Comment by amrobbins** [comment]
Hi @zijianjoy,

I am trying to create a pipeline that will read from a table during pipeline execution, and launch a few pod operations for each row that is in the table at that time. Will the feature that is mentioned here allow that capability? Or, do you know if that capability already exists? Thanks.

**Comment by zijianjoy** [comment]
@amrobbins Can you try using `parallelFor`? https://kubeflow-pipelines.readthedocs.io/en/stable/source/kfp.dsl.html?#kfp.dsl.ParallelFor

This issue is for tracking KFPv2 UI implementation, sorry that it is not obvious from title

**Comment by amrobbins** [comment]
ok, I see the parallel for does look like it will work for my use case. Thanks for the suggestion.

**Comment by zijianjoy** [comment]
Recently Reactflow has supported sub flow: https://reactflow.dev/docs/guides/sub-flows/

**Comment by zijianjoy** [comment]
It is completed: https://github.com/kubeflow/pipelines/pull/8326
