### ISSUE TITLE
Pushing csv/json/parquet files to Big Query using Kubeflow component 

### ISSUE THREAD

**Issue by engineeryashsaxena** [kubeflow/pipelines#6697]
I am trying to store the output of my final process to a big query table using kubeflow component, pls can you suggest best practise for the same. Accessing "google.cloud" in python from lightweight component is throwing errors, hence I need alternative suggestions for the same

**Comment by zijianjoy** [comment]
Potential cause of this issue: Kubeflow pipelines service account should have permission to communicate with BigQuery. Documentation: http://cloud/bigquery/docs/access-control. Feel free to comment here if this doesn't solve your problem.
