### ISSUE TITLE
client.list_experiments() not working as well as creating runs, authentication failing

### ISSUE THREAD

**Issue by rexad** [kubeflow/pipelines#6726]
### What steps did you take
We deployed kubeflow on premise using kustomize file https://github.com/kubeflow/manifests/tree/v1.3.1, v 1.3.1
Created a notebook, tried to create a run from it using kfp 

I can't connect from the notebook to pipelines  (to create runs and see experiments ) 
`import kfp`
`kfp_endpoint=None`
`client.list_experiments()`  

but i can enumerate pipelines  
`import kfp`
`kfp_endpoint=None`
`client = kfp.Client(host=kfp_endpoint) `
`print(client.list_pipelines())`

### What happened:
i'am getting 
`Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'content-type': 'application/json', 'trailer': 'Grpc-Trailer-Content-Type', 'date': 'Wed, 13 Oct 2021 11:48:57 GMT', 'x-envoy-upstream-service-time': '2', 'server': 'envoy', 'transfer-encoding': 'chunked'})
HTTP response body: {"error":"Internal error: Unauthenticated: Request header error: there is no user identity header.: Request header error: there is no user identity header.\nFailed to authorize with API resource references\ngithub.com/kubeflow/pipelines/backend/src/common/util.Wrap\n\t/go/src/github.com/kubeflow/pipelines .....`

I tried multiple things, some poeple faced the same issue, adding the namespace, creting a manifest as described in 
https://www.kubeflow.org/docs/components/pipelines/sdk/connect-api/#connect-to-kubeflow-pipelines-from-the-same-cluster
Nothing worked for me .
I would really appreciate any help 

### What did you expect to happen:
See the expierments, create runs from my pipelines 

### Environment:

*  How do you deploy Kubeflow Pipelines (KFP)? 

Deployed using Kustomize https://github.com/kubeflow/manifests/tree/v1.3.1
*  KFP version: 

*  KFP SDK version: 

### Anything else you would like to add:
if i pass the YRL of the pipeline UI in kfp client, there is no error but nothing is returned 
`{'experiments': None, 'next_page_token': None, 'total_size': None}`

### Labels

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by zijianjoy** [comment]
Hello @rexad , what is the platform you use to deploy Kubeflow? The Kubeflow Pipelines endpoint require an identity to be provided in request header when being called.

**Comment by rexad** [comment]
@zijianjoy thanks for the reply, 
makes sense but im calling from the notebook the same cluster, how can i pass this identity?

**Comment by rexad** [comment]
should i do something like this ?
https://github.com/kubeflow/kfctl/issues/140#issuecomment-719894529

**Comment by zijianjoy** [comment]
If you are using Google Cloud, you can set your email account in header `X-Goog-Authenticated-User-Email` field.

You can do this by using modHeader extension: https://modheader.com/guide/

**Comment by nschenone** [comment]
Yup tried it

**Comment by MarkusThill** [comment]
I would also like to highlight this point: After trying many things for hours I also just did a (I imagined somehow that I already did this; apparently I did not): `!pip install --upgrade kfp` before running (dont forget to restart your kernel...)

```
import kfp
client = kfp.Client()
print(client.list_experiments())
```

So @zijianjoy 's suggestion actually works with the newest kfp version...


> Would you like to try the multi-user mode approach here? https://www.kubeflow.org/docs/components/pipelines/sdk/connect-api/#multi-user-mode

**Comment by kim-sardine** [comment]
@MarkusThill OMG This is insane. Thanks a lot.

**Comment by SanderRednas** [comment]
Just as you created an allow for the pipelines you also have to do this for experiments if you want to run list_experiments() when you have multi-user deployment:

apiVersion: kubeflow.org/v1alpha1
kind: PodDefault
metadata:
  name: access-ml-experiments
  namespace: <NAMESPACE>
spec:
  desc: Allow access to Kubeflow Experiments
  selector:
    matchLabels:
      access-ml-experiments: "true"
  volumes:
    - name: volume-kf-experiments-token
      projected:
        sources:
          - serviceAccountToken:
              path: token
              expirationSeconds: 7200
              audience: experiments.kubeflow.org      
  volumeMounts:
    - mountPath: /var/run/secrets/kubeflow/experiments
      name: volume-kf-experiments-token
      readOnly: true
  env:
    - name: KF_PIPELINES_SA_TOKEN_PATH
      value: /var/run/secrets/kubeflow/pipelines/token

**Comment by abhijithremesh** [comment]
I am also facing the same issue. Not able to list both experiments and pipelines.


I have installed via manisfests on a on-prem local K8s cluster (RKE2).
I would like to know, to which version, kfp has been updated. 

In my case, 
kfp                       2.0.1
kfp-pipeline-spec 0.2.2
kfp-server-api      2.0.0
