### ISSUE TITLE
[backend] Error occured while trying to proxy to: ... central1.pipelines.googleusercontent.com

### ISSUE THREAD

**Issue by gordonsilvera** [kubeflow/pipelines#6734]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
- Created a custom Kubernetes cluster
- Created the pipeline through [AI Platform Pipelines](https://console.cloud.google.com/ai-platform/pipelines/clusters)

*  KFP version: 1.7.0

### Steps to reproduce
- This error is received when opening the UI and/or loading a pipeline from the CLI
```
Error occured while trying to proxy to: #####-dot-us-central1.pipelines.googleusercontent.com/apis/v1beta1/pipelines?page_token=&page_size=10&sort_by=created_at%20desc&filter=
```

### Expected result
The result should be a list of the available pipelines.
<img width="1217" alt="kubeflow-issue-gui" src="https://user-images.githubusercontent.com/13377661/137217476-a2d17cbd-ea45-46c5-842a-15ab75a40272.png">
<img width="1023" alt="kubeflow-issue-cli" src="https://user-images.githubusercontent.com/13377661/137217671-71d4e4e6-4ecf-480e-b187-5829549f32da.png">

### Materials and Reference

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by gordonsilvera** [comment]
`proxy-agent` is okay. However, there are a few status errors in the Deployments. In particular:
```
Deployment | metadata-grpc-deployment | Does not have minimum availability
Deployment | ml-pipeline | Does not have minimum availability 
```

**Comment by zijianjoy** [comment]
You can check more about the log in `metadata-grpc-deployment`, there might explain the reason why you don't have a working backend.

**Comment by hfarooqui** [comment]
Any updates on this issue?
I am facing similar problem with "Kubeflow on AWS" eks1.24 + kf1.7
"http://ml-pipeline-ui-artifact.kubeflow:80" in ml-pipeline-ui.log doesn't seem right:

```
ET /apis/v1beta1/healthz
GET /pipeline/artifacts/s3/XXXXXXXXXXXX/main.log?namespace=kubeflow
[HPM] Router new target: /artifacts -> "http://ml-pipeline-ui-artifact.kubeflow:80"
Proxied artifact request:  /pipeline/artifacts/s3/XXXXXXXXXXXX/main.log
[HPM] Error occurred while trying to proxy request /pipeline/artifacts/s3/XXXXXXXXXXXX/main.log from istioingress.example.net to /artifacts (ENOTFOUND) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```
![Screen Shot 2023-04-06 at 5 49 17 PM](https://user-images.githubusercontent.com/7764971/230657143-a5c2fd4e-ca74-4081-8917-cee24ae37668.png)

**Comment by MustaphaU** [comment]
I encountered a similar issue. I had scaled down my nodes from 2 to 1, and the PV for the MySQL backend (which stores pipeline metadata) was bound to the node that was terminated (in us-east-1f). My remaining node was in a different AZ (us-east-1a), so the PV couldn’t attach. I resolved this by scaling up the node group by 1; this provisioned a new node in `us-east-1f`.
