### ISSUE TITLE
[bug] Address CVE on click lower than 8.x

### ISSUE THREAD

**Issue by quan-dang** [kubeflow/pipelines#6766]
### What happened:

A CVE issue has been reported on click version 7.x on GitHub
https://github.com/pallets/click/issues/1833

### What did you expect to happen:

Please update click to resolve it!

**Comment by kevin-bates** [comment]
Is there an ETA for updating the `click` dependency to >= 8?  This is impacting the adoption of applications that use the KFP SDK.  Thanks.

**Comment by rimolive** [comment]
Closing this issue, click was updated in latest releases.

/close
