### ISSUE TITLE
KFP should support containerd runtime on Kube

### ISSUE THREAD

**Issue by animeshsingh** [kubeflow/pipelines#678]
KubeFlow pipeline currently only works on Docker runtime since the pipeline output artifacts are copied with "docker cp" command.  We need support for  containerd runtime

**Comment by hongye-sun** [comment]
Could you give more context on why it's needed? 

We rely on argo to copy the artifact files. However, only docker executor currently supports file operations in argo (https://github.com/argoproj/argo/tree/master/workflow/executor). There is an [argo FR](https://github.com/argoproj/argo/issues/970) to get rid of docker cp and it seems that argo team had a plan but still WIP.

**Comment by animeshsingh** [comment]
@hongye-sun we are moving towards containerd in IBM Cloud IKS, and hence this becomes key

**Comment by animeshsingh** [comment]
Hi folks - coming back to this. Given we have phased out support for docker in IBM Kubernetes service, this is becoming a blocker. Anyway to take this forward jointly with Argo?

**Comment by vicaire** [comment]
Thanks for filing the issue with Argo. Would you be able to drive support for containerd with both Argo and then KFP? Let me know if some help is needed.

**Comment by animeshsingh** [comment]
Thanks @vicaire. Definitely chasing it - there is a PR with Argo which are trying to make it work within our context, and then will be going back with what still remains opens.

**Comment by Duske** [comment]
Hey @animeshsingh, with new process namespace sharing (PNS) I got argo to run with containerd on k3s, no docker involved. You can use it by setting a property in the config map as described in #901 [here](https://github.com/argoproj/argo/issues/901#issuecomment-499159019)

Does this solve your problem?

**Comment by MingzhouZhou** [comment]
For those who have the same issue, add or change ```containerRuntimeExecutor: k8sapi,```  to configmap `workflow-controller-configmap` and restart deployment `ml-pipeline` work for me, this has been fixed in argo: https://github.com/argoproj/argo/pull/1419

**Comment by susan-shu-c** [comment]
Does this work without needing to modify Argo?
