### ISSUE TITLE
Kubeflow Pipeline conditionals should be able to handle multiple output parameters 

### ISSUE THREAD

**Issue by animeshsingh** [kubeflow/pipelines#679]
Argo supports conditionals that can handle multiple output parameters (e.g. (foo == true) && (bar == true))(https://github.com/argoproj/argo/issues/
860#issuecomment-410987112). 

However, the Kubeflow Pipeline compiler can’t parse multiple output parameters in python and translate that to Argo yaml format

**Comment by Ark-kun** [comment]
Duplicate of https://github.com/kubeflow/pipelines/issues/482
