### ISSUE TITLE
How to retrieve component status and logs from pipeline SDK ?

### ISSUE THREAD

**Issue by ysozer** [kubeflow/pipelines#6792]
### Feature Area

Hello
In our project, we are using kubeflow pipelines from SDK and not using UI at all. It is quite difficult to understand pipeline failure. Is there any way to retrieve component status and logs of individual pipeline run? 
Maybe it is possible but I could not find it. 

### What feature would you like to see?

I would like to retrieve component results and logs from pipeline SDK.

### What is the use case or pain point?
When a pipeline fails, we can't determine the reason for failure without going to kubeflow GUI.

### Is there a workaround currently?
No workaround

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by capri-xiyue** [comment]
The workaround is to call GET /apis/v1beta1/runs/{run_id} https://www.kubeflow.org/docs/components/pipelines/reference/api/kubeflow-pipeline-api-spec/#operation--apis-v1beta1-runs--run_id--get and check the apiPipelineRuntime field.
KFP V2 will support this feature.

**Comment by ozora-ogino** [comment]
This Client API seems like what you want. You can check completion by run_id.

https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.client.html#kfp.Client.wait_for_run_completion

Or you can use get_run and write your own script.
https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.client.html#kfp.Client.get_run

**Comment by droctothorpe** [comment]
@capri-xiyue is there active development on this feature currently? We were thinking of trying to contribute it upstream.

**Comment by msvensson222** [comment]
Any idea of how this would be done running the pipeline on Vertex AI? Can you access the state of the component/pipeline run somehow?

**Comment by rayan-roy** [comment]
Has this been resolved yet in KFP 2.0 version?

**Comment by droctothorpe** [comment]
I have a functional implementation on my subclass of `Client`. I can submit a PR if it seems useful to the maintainers. No pressure!

Given:
```python
client = Client()
logs = client.get_logs(<run_id>)
```

The result is a dictionary with a key for each logging backend and logs for each component listed in sequence. 

It also optionally pretty prints all components logs to stdout:
```
Kubernetes
==========
> logs-model
time="2022-07-19T19:35:53.435Z" level=info msg="capturing logs" argo=true
hello world

MinIO
=====
> logs-model
hello world
```

**Comment by rayan-roy** [comment]
> I have a functional implementation on my subclass of `Client`. I can submit a PR if it seems useful to the maintainers. No pressure!
> 
> Given:
> 
> ```python
> client = Client()
> logs = client.get_logs(<run_id>)
> ```
> 
> The result is a dictionary with a key for each logging backend and logs for each component listed in sequence.
> 
> It also optionally pretty prints all component logs to stdout:
> 
> ```
> Kubernetes
> ==========
> > logs-model
> time="2022-07-19T19:35:53.435Z" level=info msg="capturing logs" argo=true
> hello world
> 
> MinIO
> =====
> > logs-model
> hello world
> ```
> 
> This pipeline only has one component, `logs-model`.

However, does it return the component status though?

**Comment by droctothorpe** [comment]
No, but that would be really trivial to add. Thanks for the feature suggestion!

**Comment by whappybara** [comment]
Was wondering on the status of this, if a PR has been submitted or if some workaround exists for Kfp v1.7

The components in the pipeline I'm working with will output it's training status in the logs section. Intent here is to script something to grab the logs, parse them, and save them to eventually export as metrics. I don't have much control over the way the components input and output since I'm building with a set of images that I don't have modify access to. That's why I'd rather just script something on top to grab the logs.

I've tried the apiPipelineRuntime field as suggested but the stuff I'm getting from that doesn't seem to be the same as the logs that I'm looking for. Screenshot of the specific kind/place I'm looking for:

![image](https://user-images.githubusercontent.com/110224695/181717858-00faf908-4f5e-4eb6-a4eb-941618698d1f.png)

**Comment by droctothorpe** [comment]
Would ya'll prefer a table that looks like this?
```python
+---------------+-----------+
| Component     | Status    |
+---------------+-----------+
| hello-world   | Succeeded |
| kf-greeting   | Succeeded |
| kf-greeting-2 | Succeeded |
+---------------+-----------+
Progress: 3/3
```

Or a DAG in ASCII that looks like this?
```python
+---------------------------+     +-------------------------+
| kf-greeting-2 | succeeded | <-- | hello-world | succeeded |
+---------------------------+     +-------------------------+
                                    |
                                    |
                                    v
                                  +-------------------------+
                                  | kf-greeting | succeeded |
                                  +-------------------------+
```
