### ISSUE TITLE
[sdk] superfluous isinstance check in local run

### ISSUE THREAD

**Issue by feizerl** [kubeflow/pipelines#6799]
Hello,

I am trying to run a kubeflow pipeline locally, and am currently running into issue due to this check:

https://github.com/kubeflow/pipelines/blob/4abc4fd1874f7937a193d31dbbe650618c88ca95/sdk/python/kfp/_local_client.py#L475

My code (roughly) looks like this:

```py
@container_op
def upload(..) -> list:
   ...

@container_op
def download(path: String()):
   ...

with ParallelFor(upload.output) as path:
    download(path)
```

The code works on a remote k8 run, but fails locally when run with LocalClient due to the extra layer of serialization because of the above check.

It changes path from `gs://...` to `"gs://..."`. (Note the extra pair of quotations). 

What's the purpose of that check? Isn't that always going to succeed since everything is an instance of `object` in python anyway.

**Comment by lynnmatrix** [comment]
@feizerl Thanks for this issue, and you are right, the check will always be true. 
What i really want to check is whether the item is an instance of primitive type, if not, convert the item to string so that it can be used in command line.
