### ISSUE TITLE
Allow exit handlers at pipeline steps level

### ISSUE THREAD

**Issue by animeshsingh** [kubeflow/pipelines#680]
Need local component/step wise exit handlers. Currently KubeFlow Pipeline only allows one global exit handler

**Comment by animeshsingh** [comment]
Essentially KFP allows one exit handler per pipeline. In scenarios where something goes wrong with a particular step/component in a pipeline, or to insert a generic action with each component, there is need for exit handlers which can be inserted at a step level

**Comment by gaoning777** [comment]
@Ark-kun, is this part of the component plan?

**Comment by hongye-sun** [comment]
This is a FR to Argo that we submitted a while ago.
https://github.com/argoproj/argo/issues/906

**Comment by vicaire** [comment]
Still pending on the Argo side.

**Comment by fenghejingchi** [comment]
Is it in progress or not in the roadmap yet?

**Comment by hongye-sun** [comment]
@fenghejingchi 

The FR requires change on Argo side. It's currently not in our roadmap yet. Any help from community is very welcome.
