### ISSUE TITLE
[feature] Provide custom index_url to pip when installing packages in Pipeline components

### ISSUE THREAD

**Issue by valko073** [kubeflow/pipelines#6810]
### Feature Area

/area sdk
/area components

### What feature would you like to see?

As a user I would like to be able to provide a custom url to a self-hosted Pypi server for the components to install their 
_packages_to_install_ from. I could not find a way of doing so in the documentation / code.

### What is the use case or pain point?

Due to Firewall restrictions, it is not possible for me to reach the official Pypi server from my Kubeflow. When manually installing packages, I can point pip via the index_url to the self-hosted Pypi inside the network. I would love to have that same functionality when starting Pipeline components.

### Is there a workaround currently?

As a workaround, we have some custom Docker images with most commonly used packages preinstalled. However, this makes the images unnecessarily large and cannot cope with specific packages not preinstalled in the images.

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by chensun** [comment]
Hi @valko073 , IIRC `packages_to_install` also accepts a full GitHub path, for instance `'git+https://github.com/kubeflow/pipelines#egg=kfp&subdirectory=sdk/python'`. Would that work for you?

Alternatively, you may also consider containerizing your component--install the dependencies while building the container image.

**Comment by valko073** [comment]
Hi @chensun, 
the packages are hosted on a private Pypi server. I tried using the link to the server which didn't work for me. What did work was writing a custom image for the components that simply takes the bare Python:3.x image and adds a pip.conf that points to our server.

**Comment by chensun** [comment]
> Hi @chensun, the packages are hosted on a private Pypi server. I tried using the link to the server which didn't work for me. What did work was writing a custom image for the components that simply takes the bare Python:3.x image and adds a pip.conf that points to our server.

Got it. Thanks for the info.
If you don't mind hosting a custom image, I would suggest you pre-install the packages into the image--that way it's a one time installation cost, you would save some recurring runtime cost.

**Comment by chensun** [comment]
Hi @valko073, just want to let you know that this was fixed via https://github.com/kubeflow/pipelines/pull/7453, which was cherrypicked and released in KFP SDK 1.8.12.

/cc @connor-mccarthy
