### ISSUE TITLE
issue with `google_cloud_pipeline_components` and artifact URIs

### ISSUE THREAD

**Issue by amygdala** [kubeflow/pipelines#6819]
This is with the 1.7 Marketplace install of KFP on a GKE cluster, and running a pipeline that uses the 1P components via v2 compat mode. I'm using v0.1.8 of the `google_cloud_pipeline_components`.

There's an apparent issue with the 1P component handling of artifact URIs in v2 compat mode. (This pipeline runs fine on Vertex Pipelines).
I believe this is new-ish behaviour. While I haven't tested with v 0.17, it would be interesting to see if that version has the same issues.

For these components, I'm seeing errors like this one for `model-upload`:

```
  message: "Output Artifact "model" does not have a recognized storage URI "https://us-central1-aiplatform.googleapis.com/v1/projects/xxxxxxxx/locations/us-central1/models/5506217892460363776". Skipping uploading to remote storage." 
```
The model is uploaded successfully-- it's just the Artifact handling that's not working.

Then, looking at the `Input/Output' panel, I see this, possibly related:

```
{
  "error": {
    "code": 401,
    "message": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-
...
```
I see the same for e.g. the `endpoint-create` op. 

Then, a downstream op like `model-deploy` which takes as inputs the outputs from those ops, fails outright (unsurprisingly) as it can't get its inputs properly:

```
  message: "Failed to execute component: failed to fetch non default buckets: failed to parse bucketConfig for output artifact "endpoint" with uri "https://us-central1-aiplatform.googleapis.com/v1/projects/xxxxxxxx/locations/us-central1/endpoints/1899964888889950208": parse bucket config failed: unsupported Cloud bucket: "https://us-central1-aiplatform.googleapis.com/v1/projects/xxxxxxxx/locations/us-central1/endpoints/1899964888889950208"" 
```

![image](https://user-images.githubusercontent.com/115093/139131178-ceebd036-176b-4ce5-9cfa-fe5095578b27.png)

Note: I tried passing the default SA as an arg to the ops in case the 401 credentials issue is relevant, but that didn't seem to make a difference.  
Nor did passing the default SA as an arg to `create_run_from_pipeline_func` help (though the node pool is using the same SA already).
(in fact doing that that threw a different error: `task 'keras-debug-pipeline-jwcmv.custompythonpackagetrainingjob-run' errored: pods "keras-debug-pipeline-jwcmv-2236201252" is forbidden: error looking up service account default/xxxxxxxx-compute@developer.gserviceaccount.com: serviceaccount "xxxxxxxx-compute@developer.gserviceaccount.com" not found` )

/cc @SinaChavoshi @Bobgy @IronPan

**Comment by amygdala** [comment]
Update: for now, the team has dropped v2 compatible mode support.  Instead, a v2 engine mode is in the works, ETA early next year for an alpha version.

**Comment by capri-xiyue** [comment]
Reassigned it to James Wu to further discuss the priorty

**Comment by Ark-kun** [comment]
I have a similar issue with GCPC components.
I'm calling the official ModelDeployOp GCPC component and the log is
```
I0722 02:27:58.939668       1 env.go:30] cannot find launcher configmap: name="kfp-launcher" namespace="default"
I0722 02:27:58.939793       1 launcher.go:144] PipelineRoot defaults to "minio://mlpipeline/v2/artifacts".
I0722 02:27:58.940124       1 cache.go:120] Connecting to cache endpoint 10.16.15.15:8887
I0722 02:27:58.973459       1 launcher.go:193] enable caching
F0722 02:27:59.035967       1 main.go:50] Failed to execute component: failed to fetch non default buckets: failed to parse bucketConfig for output artifact "endpoint" with uri "
https://us-central1-aiplatform.googleapis.com/v1/projects/620505276504/locations/us-central1/endpoints/5039484002562473984
": parse bucket config failed: unsupported Cloud bucket: "https://us-central1-aiplatform.googleapis.com/v1/projects/620505276504/locations/us-central1/endpoints/5039484002562473984"
https://us-central1-aiplatform.googleapis.com/v1/projects/620505276504/locations/us-central1/endpoints/5039484002562473984
"
```

**Does this essentially mean that GCPC cannot be used with the current KFP backend?**

With the `V2_COMPATIBLE` mode I'm getting the aforementioned errors.

With the `V2_ENGINE` mode I'm getting the `ValueError: V2_ENGINE execution mode is not supported yet.` error.
