### ISSUE TITLE
End of support for v2 compatible mode in KFP SDK 1.9 

### ISSUE THREAD

**Issue by chensun** [kubeflow/pipelines#6829]
KFP v2 compatible mode (http://bit.ly/kfp-v2-compatible) was introduced to let KFP users experiment with KFP DSL v2 features on KFP before KFP v2 engine is ready. The features is first available in KFP SDK 1.6.2. Since then, we have collected valuable user feedback which helped us evaluate our design.

Given the ongoing effort for KFP v2 engine development and the rapid development in KFP SDK v2 code base, we decide to drop v2 compatible support in KFP SDK 1.9.0 release. Users can still try out v2 compatible mode via older version of KFP SDK (the latest one with v2 compatible support is KFP SDK 1.8.7).

/cc @Bobgy 
/cc @james-jwu 
/cc @neuromage

**Comment by haoxins** [comment]
Can we also setup a plan to refactor the documents/websites?

For me, I need introduce Kubeflow pipelines to my colleagues (most are data scientists) in my company.
The Kubeflow website still be the most important source of truth for end users.
Will be very impassioned if we can update the documents to the latest KFP.

**Comment by chensun** [comment]
> Can we also setup a plan to refactor the documents/websites?
> 
> For me, I need introduce Kubeflow pipelines to my colleagues (most are data scientists) in my company. The Kubeflow website still be the most important source of truth for end users. Will be very impassioned if we can update the documents to the latest KFP.

Yes, we have a push for documentation refresh in H1 2021.
