### ISSUE TITLE
[feature] Add hooks to transform compiled template/workflow manifests

### ISSUE THREAD

**Issue by jmcarp** [kubeflow/pipelines#6831]
### Feature Area

/area sdk

### What feature would you like to see?

Argo workflows has features that aren't exposed in KFP, such as synchronization, template defaults, and retry expressions. If I want to use an argo feature that isn't exposed in KFP, I can file a PR against this repo and wait for a new release, or fork or patch the sdk, or subclass the compiler and override private methods. None of these seem like good options!

Instead, it would be useful if KFP included template- and workflow-level hooks allowing users to arbitrarily transform the compiled manifests. I don't have a strong opinion about where these hooks should go, but I think @jli and/or @maxhully suggested adding options to `Compiler.compile` or to `PipelineContext`.

### What is the use case or pain point?

Use argo workflows options that aren't yet supported in KFP.

### Is there a workaround currently?

Let me know if there's a better workaround, but all I've thought of so far is patching the sdk or overriding private methods.

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by zijianjoy** [comment]
Is it possible for you to add post-processing step after Pipeline SDK compiles to workflow template?

cc @chensun for advice.

**Comment by chensun** [comment]
Hi @jmcarp, that's an interesting idea. I wonder if a hook is added to `Compiler.compile` or `to PipelineContext`, then how different would this be from a post-compilation patching approach? (you can compile a pipeline using KFP SDK, and then modify the compilation result in using your custom code).

Note that we're moving towards a direction that KFP SDK will produce a platform-agnostic format, which we call the Pipeline Intermediate Representation (IR). And we are still evaluating how to support platform specific features in this new world.

**Comment by jli** [comment]
> how different would this be from a post-compilation patching approach? (you can compile a pipeline using KFP SDK, and then modify the compilation result in using your custom code).

It would be similar I think. I'm already wrapping the kfp.compiler in order to implement this hack to reduce the generated workflow size: https://github.com/kubeflow/pipelines/issues/4170#issuecomment-655764762

It would just make it easier to do it. My wrapper function calls the kfp.compiler to write to a temp filename, reads the yaml back in, modifies the data, then writes back out to the final yaml file location. If KFP's compiler just took an argument that was a Callable, which gets called to mutate the generated workflow object before writing to disk, that would just save all users from having to do the wrapper function.

**Comment by chensun** [comment]
Reducing the generated workflow size seems to be orthogonal to the hook. 
That being said, we're moving towards v2, where compiler no longer produce Argo yaml but some intermediate representation defined by this proto: https://github.com/kubeflow/pipelines/blob/master/api/v2alpha1/pipeline_spec.proto
So I'm not sure if you would still need to a hook to modify the compilation result. By the time KFP v2 is ready, the conversion from this IR to Argo workflow yaml would happen in the backend.
