### ISSUE TITLE
Unable to create experiments other namespaces in Kubeflow

### ISSUE THREAD

**Issue by Sushmita92feb** [kubeflow/pipelines#6836]
I have a Kubeflow platform installed on Azure Kubernetes that supports multi-user isolation. But still, I am not able to create experiments and submit pipelines in some other namespace. All the Pipelines are getting run in the Single kubeflow namespace. Can someone please guide me on how can I segregate the pipeline into different namespaces?

Thanks in Advance
Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by zijianjoy** [comment]
cc @aronchick

**Comment by rc-coderepo** [comment]
How are you submitting your pipeline? can you share the pipeline used?
