### ISSUE TITLE
Test coverage for runs without experiments

### ISSUE THREAD

**Issue by IronPan** [kubeflow/pipelines#685]
Since we enabled runs without experiments at API level, we need proper test coverages for runs without experiments, e.g. unit tests, e2e tests.

**Comment by IronPan** [comment]
@rileyjbauer Since yasser left, could you help verify we can still create runs without experiment? I suggest we don't enable this functionality if it's not being used, or easy to disable in frontend. instead I think we should create a default experiment and use that in case people want to skip creating one.

**Comment by rileyjbauer** [comment]
Yes, it is still very easy to create runs without experiments via the UI. A user can simply hit `+ Create run` from a Pipeline's page, and then not choose an experiment, and the run will not be associated with any experiment.

**Comment by rileyjbauer** [comment]
This issue should be obsolete with #1089 which places all runs created without an explicit experiment into a "Default" experiment
