### ISSUE TITLE
[Python SDK] Can we upgrade the Google API Python Client packages to v2?

### ISSUE THREAD

**Issue by haoxins** [kubeflow/pipelines#6867]
### Feature Area

/area sdk

### What feature would you like to see?

* We should upgrade Google API packages to `v2`

### What is the use case or pain point?

* For our use cases (which the users on GCP), we will get warning messages if we use both kfp and google-api-client

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
kfp 1.8.9 requires google-api-python-client<2,>=1.7.8, but you have google-api-python-client 2.29.0 which is incompatible.
```

I think it's better to upgrade the dependency~

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by zijianjoy** [comment]
cc @chensun

**Comment by ji-yaqi** [comment]
Hi @haoxins, thanks for opening this issue. 
We're removing google-api-python-client for v2. 
Please use https://github.com/googleapis/python-aiplatform for submitting pipeline jobs.
