### ISSUE TITLE
[frontend] Run details page prefetches all artifacts; initial page load transfers a lot of data

### ISSUE THREAD

**Issue by jli** [kubeflow/pipelines#6870]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)? our own deployment to GKE (not sure if standalone or full)
*  KFP version: 1.5.1

### Steps to reproduce

background: My team has a large experiment which trains ~15 models in parallel. Each model training process includes a QC/reporting step, which generates an HTML report with various metrics and visualizations. Depending on the model and the data, the reports can be between 1MB and 30MB (they can include many images). These reports are stored on GCS and rendered as `web-app` type visualizations.

When opening the KFP runs detail page for these experiments, the frontend makes a bunch of requests to `/artifacts/get?source=minio&...mlpipeline-ui-metadata.tgz`, and then another bunch of requests to `/artifacts/get?source=gcs&...our_report_file.html`. Because these report files can be large, and there are many of them in this case, this is resulting in almost 500MB of data transfers every time someone opens the KFP UI page for this run:

<img width="1105" alt="Screen Shot 2021-11-04 at 14 52 33" src="https://user-images.githubusercontent.com/133466/140413075-387a0d20-3b16-44ae-af8e-f139b62d471f.png">

This adds load on the minio and ml-pipeline-ui services and eats bandwidth.

### Expected result

Instead of prefetching all the reports, only fetch them when the user clicks on the "Visualizations" tab.

### Materials and Reference

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by zijianjoy** [comment]
Hello @jli , we should probably change the fetching of all visualization artifacts when user switch to `Run output` tab on top of Run Details page. https://github.com/kubeflow/pipelines/blob/master/frontend/src/pages/RunDetails.tsx#L581-L615

**Comment by jmcarp** [comment]
@zijianjoy, I also noticed that the run details page refreshes artifacts periodically until the run is finished, meaning that we load mostly the same artifacts many times. Can artifacts change for a given step after they're written? I was wondering if we needed to keep refetching artifacts for completed nodes.

**Comment by zijianjoy** [comment]
@jmcarp After Artifact is written, its state can still be changed (For example: MARK_FOR_DELETE). But we don't need to fetch Artifact if user is not on `Run Output` tab, so by default you are not fetching all artifacts on `Graph` tab. We can separate the fetching mechanism among tabs in `RunDetails.tsx` file.
