### ISSUE TITLE
[frontend] "Pipelines" and "Experiments" icons disappear when left sidebar is collapsed

### ISSUE THREAD

**Issue by jli** [kubeflow/pipelines#6873]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)? standalone
*  KFP version: 1.7.1

### Steps to reproduce

Collapse the left sidebar. Observe that the first 2 icons, "Pipelines" and "Experiments", aren't visible:

<img width="66" alt="Screen Shot 2021-11-05 at 13 30 20" src="https://user-images.githubusercontent.com/133466/140553518-b3eae248-ebc8-4c5f-8f6a-4ebe6279d86b.png">

### Expected result

Pipelines and Experiments icons are visible when the sidebar is collapsed.

### Materials and Reference

- When the sidebar is expanded, the icons and text appear normally.
- When the sidebar is collapsed, I can still click on the empty spaces where the icons should be, and navigate to the respective pages.
- I took a quick look at the HTML changes when the sidebar is collapsed, and didn't notice anything obviously wrong. The first 2 sidebar buttons seem to have all the same classes as the rest of the buttons when expanded and collapsed.

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by zijianjoy** [comment]
Thanks for the report, this is fixed in https://github.com/kubeflow/pipelines/pull/6440, I expect the next release to fix it.
