### ISSUE TITLE
Trigger Airflow DAG from kubeflow V2 pipeline SDK

### ISSUE THREAD

**Issue by ajaykamal3** [kubeflow/pipelines#6885]
### Problem
Currently I'm having a vertex AI pipeline built using kubeflow v2 pipeline sdk (python function based). The last step of the pipeline will save the data to Big query table. I would like to trigger an existing Airflow DAG which consumes the data that is stored in Big query table saved by vertex AI pipeline. How can I trigger the Airflow DAG right after the vertex AI pipeline run was completed? How can I achieve this in kubeflow? If it is not possible in kubeflow or vertex ai, any other way of solving this problem using other of google cloud platform would be really appericiated. Suggest some solution please.

**Comment by capri-xiyue** [comment]
In kubeflow you can use exit handler https://github.com/kubeflow/pipelines/blob/927d2a9f2dfdb90ae156979b9e0d72afa14adcd6/samples/core/exit_handler/exit_handler.py#L47
