### ISSUE TITLE
[feature] Abstract KFP Argo workflow client functions

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/pipelines#6888]
### Feature Area
Currently, the KFP backend still relies heavily on the Argo golang client to run, get workflows, updates, and retry pipelines. This still remains true after implementing the v2 backend compiler because the compiled workflow needed the Argo golang client to manage the Argo workflows on Kubernetes. Since the Argo golang client needs to be part of the KFP backend code, we are proposing to abstract some common Argo client functions into a common golang interface, so other backend runtimes such as Tekton can also be plugin this way

Here is a rough docs we put up
https://docs.google.com/document/d/1Kz0WEYUesxOU8YN9QeXlsJBsalllOyr9ygpTvcGkuvA/edit#

We can take up this work if we agree on this approach.

### Is there a workaround currently?

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by goswamig** [comment]
My 2 cents, we should also try to keep the interface clean enough so that not just argo or tekton but airflow or any work flow engine should be able to integrate well.

**Comment by Tomcli** [comment]
> My 2 cents, we should also try to keep the interface clean enough so that not just argo or tekton but airflow or any work flow engine should be able to integrate well.

Yes, we will try to keep Argo and Tekton names out of the pictures for this new interface.
