### ISSUE TITLE
[bug] The pipeline is terminated immediately after startup

### ISSUE THREAD

**Issue by SeibertronSS** [kubeflow/pipelines#6896]
### What happened:

I created a pipeline with four components, but it was terminated immediately after it was started, and the status of the pipeline was displayed as `Unknown`.

### What did you expect to happen:

Pipeline can run normally.

### Environment:

*  How do you deploy Kubeflow Pipelines (KFP)? 
I deployed it by kubeflow manifests

*  KFP version: 
1.7.0

*  KFP SDK version: 
I used the pythonSDK, the version is 1.8.9

### Anything else you would like to add:
The version of **kubernetes is v1.19.9**.

The error message is displayed as:
```
Events:
  Type     Reason     Age   From               Message
  ----     ------     ----  ----               -------
  Normal   Scheduled  4s    default-scheduler  Successfully assigned kubeflow/pipeline-func-2qv86-3719103562 to 11.xx.x.xxx
  Normal   Pulled     2s    kubelet            Container image "gcr.io/ml-pipeline/argoexec:v3.1.6-patch-license-compliance" already present on machine
  Normal   Created    1s    kubelet            Created container wait
  Warning  Failed     0s    kubelet            Error: failed to start container "wait": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:319: getting the final child's pid from pipe caused \"EOF\"": unknown
  Normal   Pulled     0s    kubelet            Container image "is.default.svc.explore.academy.jd.local/kubekit:0.2.3" already present on machine
  Warning  Failed     0s    kubelet            Error: cannot find volume "pipeline-runner-token-7lcgk" to mount into container "main"

```

### Labels

 /area components 

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by capri-xiyue** [comment]
Can you try to use emissary executor https://www.kubeflow.org/docs/components/pipelines/installation/choose-executor/#emissary-executor

**Comment by SeibertronSS** [comment]
> Can you try to use emissary executor https://www.kubeflow.org/docs/components/pipelines/installation/choose-executor/#emissary-executor
Thanks for your suggestions, I will try. After I use emissary executor, can I still use docker image? My pipeline has problems only after it has all four components, and it can work normally when it has only four or less components. Why is this?

**Comment by zijianjoy** [comment]
@SeibertronSS 

How does the pipeline run work after applying emissary executor?
Which platform are you deploying your Kubernetes cluster? By creating Kubernetes cluster, you can potentially choose between docker runtime vs containerd runtime. In containerd runtime, you can only use emissary executor.

For the error message of your issue, would you like to look at this SO post to see if this applies to your deployment resource yaml? https://stackoverflow.com/questions/64990279/docker-error-process-linux-go319-getting-the-final-childs-pid-from-pipe-cause

**Comment by SeibertronSS** [comment]
> @SeibertronSS
> 
> How does the pipeline run work after applying emissary executor?
> 
> For the error message of your issue, would you like to look at this SO post to see if this applies to your deployment resource yaml? https://stackoverflow.com/questions/64990279/docker-error-process-linux-go319-getting-the-final-childs-pid-from-pipe-cause
> 
> If your pipeline run still fails, would you like to share your pipeline template which has 4 components?

After our investigation, we found that there was a problem with the routing table of our cluster, which caused duplicate ClusterIP to appear. I will close this issue. Thank you very much for your time.
