### ISSUE TITLE
python Code sample for configmap , volume creation 

### ISSUE THREAD

**Issue by kabilan6** [kubeflow/pipelines#6899]
Any code samples for configmaps, persistent volume creation ? I tried resourceop but its not working.

**Comment by midhun1998** [comment]
Hi @kabilan6 . There aren't any specific code samples for config maps but It should work the same way as other Kubernetes objects. For creating a PVC you can leverage [VolumeOp](https://github.com/kubeflow/pipelines/tree/master/samples/core/volume_ops) which utilises ResourceOps behind the scene. You can also leverage pre-built components by the community (https://github.com/kubeflow/pipelines/tree/master/components/contrib/kubernetes).
