### ISSUE TITLE
[Python version upgrade] Should we consider to upgrade the base/default images from Python:3.7 to 3.8

### ISSUE THREAD

**Issue by haoxins** [kubeflow/pipelines#6900]
### Feature Area

/area components

### What feature would you like to see?

As `Python 3.10` has released, and the `Python 3.8` has became most OS's default `Python(3)` version

So, I just advise that we should consider to upgrade the default Python version
(Such as: base images in the `Dockerfile`, default images in the output pipeline yaml)
to `3.8`

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by zijianjoy** [comment]
cc @chensun

**Comment by ji-yaqi** [comment]
Hi @haoxins, in order not to break our existing users, we will not update the image to 3.8 until we reach a point of deprecating 3.7. Thanks for the advice!
