### ISSUE TITLE
[bug] Everything is added to one item in the artifacts menu

### ISSUE THREAD

**Issue by jazzsir** [kubeflow/pipelines#6901]
### What steps did you take
I deployed various types of pipelines,
for example
https://github.com/Building-ML-Pipelines/building-machine-learning-pipelines/tree/master/pipelines/kubeflow_pipelines
https://github.com/jazzsir/kubeflow-pipelines/blob/master/simple-pipeline/mnist.ipynb
https://github.com/jazzsir/kubeflow-pipelines/blob/master/simple-pipeline/kfp-v2.ipynb
https://github.com/jazzsir/kubeflow-pipelines/blob/master/simple-pipeline/kfp-v2-artifact.ipynb
https://github.com/CODAIT/flight-delay-notebooks

### What happened:

In the Artifacts menu
1. All artifacts are added to one item whose "Pipeline/Workspace" field has no value .
2. I can't select artifacts generated by [pipelines(v2)](https://github.com/jazzsir/kubeflow-pipelines/blob/master/simple-pipeline/kfp-v2-artifact.ipynb) with python typing the type of inputs/outputs (Model, Dataset..) to view "Overview" and "Lineage Explorer" because they don't have a name(marked with red rectangle in the picture).
3. Unlike Kubeflow 1.3(KFP 1.6.0), [pipelines](https://github.com/jazzsir/kubeflow-pipelines/blob/master/simple-pipeline/mnist.ipynb) without python typing the type of inputs/outputs (Model, Dataset..) leave no artifacts.
4. Only pipelines generated by [kubeflow_dag_runner of TFX](https://github.com/Building-ML-Pipelines/building-machine-learning-pipelines/blob/master/pipelines/kubeflow_pipelines/pipeline_kubeflow.py) have a name

In the Excutions menu
1. "Run ID/Workspace/Pipeline" fields of Excutions generated by [pipelines(v2)](https://github.com/jazzsir/kubeflow-pipelines/blob/master/simple-pipeline/kfp-v2-artifact.ipynb) with python typing the type of inputs/outputs (Model, Dataset..) have no value.

![www](https://user-images.githubusercontent.com/4714923/141599188-4938601f-583e-478c-b3e6-1bdfa3c4a6d3.png)

### What did you expect to happen:

In the Artifact menu
1. All artifacts are added in separate entries and their "Pipeline/Workspace" field have a value.
2. All pipelines leave artifacts
3. All items has a name so that we can select it and view "Overview" and "Lineage Explorer"

In the Excutions menu
1. All "Run ID/Workspace/Pipeline" fields of Excutions have a value.

### Environment:

*  How do you deploy Kubeflow Pipelines (KFP)? Full Kubeflow deployment (Kubeflow 1.4)
*  KFP version: 1.7.0
*  KFP SDK version: 1.7.2 and 1.8.9

### Labels

/area frontend
/area backend

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by coalindiax** [comment]
Please guide on how to provide value pipeline/workspace and name  in artifact via KFP library
facing same issue

**Comment by zijianjoy** [comment]
This is fixed by https://github.com/kubeflow/pipelines/pull/6989. We are planning to make new release for it.
