### ISSUE TITLE
[bug] concurrent.futures.process.BrokenProcessPool using ProcessPoolExecutor

### ISSUE THREAD

**Issue by andrijaperovic** [kubeflow/pipelines#6903]
### What steps did you take

Running the following example code to gather output results from model training.
Results are failing to be retrieved from executor at runtime, which leads to downstream exception.

```
with ProcessPoolExecutor() as p_executor:
    for i in range(nprocs):
        futures.append(p_executor.submit(pool_single_model_train, Models._member_names_[i],
                                         self.train_data, self.test_data, user_ids_test))
resultdict = {}
for f in as_completed(futures):
    try:
        resultdict.update(f.result())
    except Exception as exc:
        LOGGER.exception('Future process generated an exception: %s' % (exc))

self.score, self.count = resultdict[Models.model.name][1][0], \
                                                     resultdict[Models.model.name][1][1]
```

### What happened:

Following exception is raised in the pipeline run:
```
{"stack": "Traceback (most recent call last):    File \"/trainer.py\", line 61, in __init__      resultdict.update(f.result())    File \"/opt/conda/lib/python3.7/concurrent/futures/_base.py\", line 428, in result      return self.__get_result()    File \"/opt/conda/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result      raise self._exception  concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.  "}
```

### What did you expect to happen:
Result should have been completed successfully by ProcessPoolExecutor.

### Environment:

Azure AKS v1.21.2 running KFP 1.7.0-alpha.1

*  How do you deploy Kubeflow Pipelines (KFP)? 
https://github.com/kubeflow/pipelines/blob/master/manifests/kustomize/env/azure/readme.md

*  KFP version: 
1.7.0-alpha.1

*  KFP SDK version: 
1.6.2

### Anything else you would like to add:
N/A

### Labels

/area components 

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by zijianjoy** [comment]
Hello @andrijaperovic , are you able to run a sample code using ProcessPoolExecutor in an independent Kubernetes pod successfully? It doesn't seem like an issue related to Kubeflow.

**Comment by andrijaperovic** [comment]
Hi @zijianjoy , looks like the issue was caused primarily by the node pool where the pipeline task was being scheduled which has a limited number of cores (vCPU's). Once we allocated a node pool in our k8s cluster with a suitable number of vCPU's, the pipeline ran successfully. Will go ahead and close this issue. Thanks for your help.
