### ISSUE TITLE
[frontend] pipeline metrics not showing

### ISSUE THREAD

**Issue by tomalbrecht** [kubeflow/pipelines#6912]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)? kubeflow manifests (branch 1.4)
*  KFP version: SDK 1.8.9 / build version dev_local

### Steps to reproduce

- Copy/Paste Code from here: https://www.kubeflow.org/docs/components/pipelines/sdk/pipelines-metrics/
- Create pipeline and create_run from component

### Expected result
- As documented here: https://www.kubeflow.org/docs/components/pipelines/sdk/pipelines-metrics/#view-the-metrics

### Materials and Reference
- I run the pipeline in 'mode=v1dsl.PipelineExecutionMode.V2_COMPATIBLE)' 
- I've tested both way (json and file)

![image](https://user-images.githubusercontent.com/17781570/141967606-e29d58eb-7931-49a5-97f1-5e0e5ef2295a.png)
![image](https://user-images.githubusercontent.com/17781570/141967677-6a67d06f-7cce-4349-a890-347b1276fd7e.png)
![image](https://user-images.githubusercontent.com/17781570/141967733-163fcc93-6bd1-44d3-ba24-408dddc9df2e.png)

[yamls.zip](https://github.com/kubeflow/pipelines/files/7545502/yamls.zip)

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by zijianjoy** [comment]
@tomalbrecht This feature is only supported in v1, but not v2 compatible.

**Comment by AlexandreBrown** [comment]
@zijianjoy Could we get an update on this issue? 

It looks like it received quite a few thumbs up but was not addressed in v2 compatible mode issue tacker https://github.com/kubeflow/pipelines/issues/6132

Perhaps we should consider the thumbs up count to be whatever this page shows + 6 from the old issue.

**Comment by zijianjoy** [comment]
@AlexandreBrown Thank you for bringing this up!

We have put the V2 compatible work on hold and currently work fully to V2. We are currently tracking it in our KFP V2 project. That said, we are aware of this requirement and working towards it. The thumbs-up information helps us prioritize the work in the V2 timeline.

**Comment by jayaswalayush** [comment]
@zijianjoy : Please can you provide an update on this issue https://github.com/kubeflow/kubeflow/issues/6346

**Comment by zijianjoy** [comment]
I think we need to make some design decision in order to support this feature on KFPv2. It will be very helpful if you can provide information like this:

1. What kind of metrics do you want to show on RunList? (For example: accuracy, roc score)
2. How do you want to export these metrics in your pipeline? (For example: create a component with a fixed name that generates parameters from #1.)
3. How do you want to use this feature on UI? (Show on RunList? Show on a different page? Do you need Filtering/Sorting?) Do you need any customization?

**Comment by chensun** [comment]
We no longer support v2 compatible mode, and the general metrics visualization is support in v2. 
One of the fixing PRs: https://github.com/kubeflow/pipelines/pull/7905
