### ISSUE TITLE
Can't enable GPU inside a pod

### ISSUE THREAD

**Issue by daniel-beyond** [kubeflow/pipelines#6913]
### Environment

Host 
- AWS ec2 instance with tesla k80 gpu
- Kind cluster with 1 node
- Nvidia driver is installed and nvidia-smi cmd works on host
- Kfp version 1.8.9

![image](https://user-images.githubusercontent.com/85550395/141992715-65103723-f00d-478e-9257-553f12bd2fbb.png)

### Steps to reproduce

I have a docker container that runs a train model that needs GPU.
When running on the host with the docker engine everything works fine with the cmd:
"docker run -d --gpus all <image id>"
and "nvidia-smi" works from within the container.

The model will only run if I add the "--gpus all" flag, when I run the container without this flag "nvidia-smi" doesn't work and the container won't recognize the GPU.

![image](https://user-images.githubusercontent.com/85550395/141994266-3aa21983-cf4c-47a1-a50d-f92bda7ae256.png)

When running the model with kfp as an argo workflow the pod raises the same exception:

![image](https://user-images.githubusercontent.com/85550395/141994266-3aa21983-cf4c-47a1-a50d-f92bda7ae256.png)

I already tries to add "set_gpu_limit(1)" to the containerOp but to no success, the pod is stuck on pending and the UI shows:

![image](https://user-images.githubusercontent.com/85550395/141995168-b0ce5354-ad12-48ad-b25e-134675ab9359.png)

**### Question**

- **How do I enable "nvidia-smi" inside the pod through kfp** ???
- **Does this even work on KIND cluster or AWS?**

Thanks a lot!

**Comment by kciy** [comment]
Hey how did you solve this?

**Comment by daniel-beyond** [comment]
@kciy 

Hey, the problem was the Kind cluster.
For some reason no pod was able to detect the GPU on the host, once I shifted to an AWS EKS the same exact configuration worked...
I didn't find a way to use the "--gpus all" flag in Kind.
