### ISSUE TITLE
[feature] [multi-user] Pipelines Profile Controller Supports Adding Labels to Created Resources

### ISSUE THREAD

**Issue by vinayan3** [kubeflow/pipelines#6923]
### Feature Area
/area manifests 

### What feature would you like to see?
The kubeflow pipielines deployment is placed into a cluster which has labeling requirements. The pipelines profile controller sync.py creates Kube resources in the profile's namespace. There needs to be a feature to allow adding labels to all the created resources.

### What is the use case or pain point?
The labeling requirements on the Kubernetes  cluster will cause the pods to be rejected when hard enforcement in Gatekeeper is turned on.

### Is there a workaround currently?
Not currently. The only workaround is to fork the pipelines repo, build the pipelines-profile-controller image, and  use that docker image.

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by zijianjoy** [comment]
You can change https://github.com/kubeflow/pipelines/blob/master/manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/sync.py#L161 in the way that you want to append labels, then apply the manifests to achieve your goal. This file will be packaged into configmap, and be executed as is during runtime.
