### ISSUE TITLE
Pipeline run does not write artifacts and stop

### ISSUE THREAD

**Issue by lenaherrmann-dfki** [kubeflow/pipelines#6930]
Hey folks, 

recently, I installed Kubeflow 1.4 with Multi User support. After a while, I managed to create a pipeline through a notebook-server. 

The pipeline should consists out of different steps each with input and output artifacts. 

Yet when I start the pipeline in a run, the first step does not stop nor seems to write any of the files as output-artifacts. If I look into the local minio, nothing has been written there. 

Do I need to grant the user explicit access to the kubeflow minio in order to write output artifacts? And if so, how do I grand this access? 

Any help is appreciated

**Comment by capri-xiyue** [comment]
Do you see any errors when the pipeline run? Can you share your pipeline yaml?
