### ISSUE TITLE
How to use docker images from a private registry

### ISSUE THREAD

**Issue by konsloiz** [kubeflow/pipelines#6931]
Hello! We are trying to deploy KFP in an enterprise environment with docker images from a private registry (For security reasons we are not allowed to use public registries such as gcr.io - so we pull the images and push them to our environment). The problem is that we are missing where some of the images can be configured. More specifically we would like to know where can we change the

1. gcr.io/ml-pipeline/kfp-launcher
2. Python 3.7
3. gcr.io/ml-pipeline/kfp-driver

Thank you for your help in advance.

**Comment by szpnygo** [comment]
How do you solve this problem?

**Comment by konsloiz** [comment]
Hello, we solved it using a tool called Kale.

**Comment by padrian2s** [comment]
For version 1.4 from what I see driver image is hardcoded in driver.go

**Comment by oldthreefeng** [comment]
> For version 1.4 from what I see driver image is hardcoded in driver.go

why this happened ??   

any solutions for this? @padrian2s
