### ISSUE TITLE
avoid declaring two times same function (and params) in vertex-pipeline with py-functions

### ISSUE THREAD

**Issue by iuiu34** [kubeflow/pipelines#6936]
context:
With vertex-pipeline + py-functions We can use a base_image (docker) with our py library pre-installed. Therefore the lib  functions are available to import inside the pipeline.
 
problem:
Assuming we want to use one of this functions (without any change) in the pipeline, is a little verbose to declare with @component the same function again, which is corresponding paramater types.
Would be cleaner if you could just declare it once. 
And the way the code works, wouldn't be so much of a change.

solution proposal:
assuming our function is in our library:
`from kfp_test.test import test`
then we have the option
1) clean but verbose
```
@component(base_image=base_image)
    def test(x: int) -> int:
        kwargs = locals()
        from kfp_test.test import test
        return test(**kwargs)`
```
2) not clean but not verbose
```
from inspect import getsource as getsource2

# deal with line 93 in component_factory.py: func_code = inspect.getsource(func)
def getsource(func):
    if 'func_code' in func.__dict__.keys():
        return func.func_code
    else:

        return getsource2(func)
from kfp.v2 import compiler
(...)
from kfp_test.test import test
 func_code = f'    def {inspect.signature(test)}:\n        kwargs = locals()\n        from kfp_test.test import test\n        return test(**kwargs)\n'
    test.func_code = func_code
    test = create_component_from_func(func=test, base_image=base_image)
```
if we had a function in kfp like `create_component_from_func_code` that handled option 2 natively (create a wrapper string automatically from the func and ingestit in the create_component() without declaring it) , then we would have a non-verbose, clean-way to use functions from the library inside the pipeline

**Comment by Iuiu1234** [comment]
PR #7049

**Comment by chensun** [comment]
IIUC, what you want to achieve after the PR is something like this:

```python
from kfp_test.test import test
 
test_op = create_component_from_func(func=test, base_image=base_image)
```

There're a couple of issues with this approach:
1. It requires installing the `kfp_test` package locally in order to compile, but that's really not necessary.
2. It makes an assumption that the locally installed package is the same version as that in the base image. But that's not something we can verify here.
3. If we want to try different versions of the base image--assuming there's interface changes to the test function--it would be a big pain as we have to remember to update the local package to match the image or switch among different virtual environments.

**Comment by Iuiu1234** [comment]
yep, you're right.

Then another approach would be to call the `base_image` inside py with an entrypoint like

```sh
FUNC_SOURCE=${python3 -m kfp.v2.component_factory.get_func_source(func)}
```

with `kfp.v2.component_factory.get_func_source` as in the PR:

```py
def get_func_source(func):
    name = func.__name__
    signature = inspect.signature(func)
    func_source = f'    def {name}{signature}:\n' \
                  f'        kwargs = locals()\n        ' \
                  f'from {func.__module__} import {name}\n        ' \
                  f'return {name}(**kwargs)\n'
    return func_source
```

With this we solve your problems cause now the usage would be
```py
test_op = create_component_from_func(func='main_module.test', base_image=base_image)
````

But main problem that I see now is that you need the image up and running before compiling the json.
Something like

* start container (in whatever your server is)
* run entrypoint
* compile json
* run pipeline (in whatever your server is)

If you have a server that's able to run pipelines, you should be able to start containers too. But I admit, that this back and forth is not very clean.

What are your thoughts?

**Comment by chensun** [comment]
I'm not sure I understand. 
Starting a container involves running its entrypoint. The compiled json tells the backend system how to run a container.

**Comment by iuiu34** [comment]
entrypoint would be
```sh
python3 -m kfp.v2.component_factory.get_func_source(func)
```

the idea would be to start the container alone before the pipeline to get the func definition. And then with the info, define the components and run the pipeline.

You can also think it as running first a one-step pipeline, with the `get_func_source` . 
And then setting up the components args for the desired pipeline

As said, is a little bit back and forth...

**Comment by chensun** [comment]
> entrypoint would be
> 
> ```shell
> python3 -m kfp.v2.component_factory.get_func_source(func)
> ```
> 
> the idea would be to start the container alone before the pipeline to get the func definition. And then with the info, define the components and run the pipeline.
> 
> You can also think it as running first a one-step pipeline, with the `get_func_source` . And then setting up the components args for the desired pipeline
> 
> As said, is a little bit back and forth...

I see. Probably not a good idea- that's even heavier than the current state...
