### ISSUE TITLE
[bug] Conditions used to select component

### ISSUE THREAD

**Issue by DanielNobbe** [kubeflow/pipelines#6949]
### What steps did you take

I am trying to use a pipeline to train two types of models (which are in different frameworks). I select which model type to train through a boolean pipeline argument. When selecting `Model_A`, I want to run a data preparation step for `Model_A`, and when selecting `Model_B` I want to run its respective data preparation step. I am using `dsl.Condition` to perform these steps. 

After either data preparation step, I want to run a data export step, which is the same for both models. I place this step after the conditional steps for the data preparation. 
See below an example script:
```
import kfp
import kfp.dsl as dsl
from kfp import compiler
from kfp.components import create_component_from_func

@create_component_from_func
def add1(a: float, b: float) -> float:
  '''Calculates sum of two arguments'''
  print(a + b)
  return a + b

@create_component_from_func
def add2(a: float, b: float) -> float:
  '''Calculates sum of two arguments'''
  print(a + b)
  return a + b

@create_component_from_func
def add3(a: float, b: float) -> float:
  '''Calculates sum of two arguments'''
  print(a + b)
  return a + b

@dsl.pipeline(
  name='addition-pipeline',
  description='An example pipeline that performs addition calculations.',
)
def add_pipeline(a: float, b: float,
    c: float, d: float,
    is_true: bool = True
):

    add_task = add1(a, b)

    with dsl.Condition(is_true == True, name='is-True'):
        add_task_2 = add2(c, d)
    with dsl.Condition(is_true == False, name='is-False'):
        add_task_2 = add2(a, c)
    
    add_task_3 = add3(a, add_task_2.output)

client = kfp.Client()
client.create_run_from_pipeline_func(
    add_pipeline,
    arguments={'a': 1, 'b': 2, 'c': 5, 'd': 12, 'is_true': False},
)
```
This script has a similar structure to the problem I am trying to solve: First, I perform an addition of two numbers (which are selected through the boolean flag), then I use the output of the addition in a following step. 

### What happened:

An error is triggered in the UI:
`invalid spec: templates.addition-pipeline.tasks.condition-is-False-2 templates.condition-is-False-2.outputs failed to resolve {{tasks.add2-2.outputs.parameters.add2-2-Output}}`

And the graph corresponding to the pipeline shows that `Add3` would not be started if the condition is True. 
![image](https://user-images.githubusercontent.com/42846160/143053104-e3736d1e-23f0-48f0-b8f9-d9ecde895824.png)

### What did you expect to happen:

The pipeline should not trigger an error, and `Add3` should always be dependent on the output of `Add2`.

### Environment:

*  How do you deploy Kubeflow Pipelines (KFP)? 

As part of a KubeFlow installation.
*  KFP version: 

1.5.0
*  KFP SDK version: 

1.8.9

### Anything else you would like to add:

It seems that `kfp` does not reference the first `Add2` as an input to `Add3`, as if it is being overwritten by the second `Add2`. Is the `Condition` class not made for use cases such as this? In the examples, it is only used for leaf nodes of the DAG, but our use case does not seem very far-fetched. 

It would be great if someone can shed some light on this.

### Labels

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by daisuke834** [comment]
I encountered a similar issue (but not the same).
When I ran:
```
@func_to_container_op
def op_0(flag: bool) -> bool:
    return flag

@func_to_container_op
def op_1(flag: bool) -> bool:
    return flag

@func_to_container_op
def op_2(flag: bool) -> bool:
    return flag

@func_to_container_op
def op_3(flag: bool):
    print(f"flag={flag}")

@dsl.pipeline(name="sample", description=__doc__)
def sample_pipeline(
    flag: bool = True,
) -> None:
    a = op_0(flag)
    with dsl.Condition(flag == False):
        b = op_1(a.output)
    with dsl.Condition(flag == True):
        b = op_2(a.output)
    op_3(b.output)
```
, it caused the following error messages 🤔 :
```
kfp_server_api.exceptions.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'X-Powered-By': 'Express', 'content-type': 'application/json', 'date': 'Wed, 08 Dec 2021 01:19:05 GMT', 'content-length': '790', 'connection': 'close'})
HTTP response body: {"error":"Failed to create a new run.: InternalServerError: Failed to validate workflow for (): templates.sample.tasks.condition-2 templates.condition-2.outputs failed to resolve {{tasks.op-2.outputs.parameters.op-2-Output}}","code":13,"message":"Failed to create a new run.: InternalServerError: Failed to validate workflow for (): templates.sample.tasks.condition-2 templates.condition-2.outputs failed to resolve {{tasks.op-2.outputs.parameters.op-2-Output}}","details":[{"@type":"type.googleapis.com/api.Error","error_message":"Internal Server Error","error_details":"Failed to create a new run.: InternalServerError: Failed to validate workflow for (): templates.sample.tasks.condition-2 templates.condition-2.outputs failed to resolve {{tasks.op-2.outputs.parameters.op-2-Output}}"}]}
```

When I commented out the last line `op_3(b.output)`, it worked correctly.

**Comment by raphaelTrench** [comment]
I have been facing this issue too, basically anytime a variable could have two possible values due to being the result  of a condition, on one of the conditions the pipeline will fail with:
`This step is in Error state with this message: Unable to resolve: {{tasks.condition-Full-Experiment-1.outputs.artifacts.split-dataset-output_train}}`

Im not sure if this is supposed to be the expected behaviour, but the only workarounds I was able to find is to put the rest of the pipeline that would depend upon the output ,separated in the conditional branch or to encapsulate the "steps" and returning multiple values. It doesn't seem intuitive to me but I was not able to find any other workarounds..
An example:

### Separating steps in the conditionals
```
@dsl.pipeline(
  name='addition-pipeline',
  description='An example pipeline that performs addition calculations.',
)
def add_pipeline(a: float, b: float,
    c: float, d: float,
    is_true: bool = True
):

    add_task = add1(a, b)

    with dsl.Condition(is_true == True, name='is-True'):
        add_task_2_cd = add2(c, d)
        add_task_3 = add3(a, add_task_2_cd.output)
    with dsl.Condition(is_true == False, name='is-False'):
        add_task_2_ac = add2(a, c)
        add_task_3 = add3(a, add_task_2_ac.output)    
```

**Comment by jacobmalmberg** [comment]
I have encountered the same stuff. Much like raphael, I'm not sure if it's a bug or not.

**Comment by gpotti** [comment]
+1, I'm facing the same issue. This is what I'm trying to do
1. Parse choices
2. Execute a container based on a condition and produce an output
3. Execute another container based on another condition and consume the output from step 2 above. 

Triggering a run ends up with 
kfp_server_api.exceptions.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'X-Powered-By': 'Express', 'content-type': 'application/json', 'date': 'Wed, 08 Dec 2021 01:19:05 GMT', 'content-length': '790', 'connection': 'close'})
HTTP response body: {"error":"Failed to create a new run.: InternalServerError: Failed to validate workflow for (): templates.sample.tasks.condition-2 templates.condition-2.outputs failed to resolve {{tasks.op-2.outputs.parameters.op-2-
