### ISSUE TITLE
doc: rename compatibility matrix page to tfx?

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#6953]
@zijianjoy @kramachandran @Bobgy in the interest of getting this merged, I have removed that rename from this PR.

However, I still think we should discuss renaming that page in the future.

_Originally posted by @thesuperzapper in https://github.com/kubeflow/website/pull/3063#discussion_r755575916_

**Comment by zijianjoy** [comment]
Thank you for creating this issue!


For the discussion of this doc title, I have a couple questions:

1. Is there any plan for compatibility matrix beyond tfx in the future? (Say PytorchX, MLMD, argo, etc.)
2. How does user find the right combination of ML frameworks+KFP nowadays? (Or how do we expect users to do to find out such combination) For example: A Kubeflow Pipelines user wants to use TFX, therefore they search `What TFX version to use in Kubeflow Pipelines` at Google to find out.
