### ISSUE TITLE
run vertex pipeline with py-func locally

### ISSUE THREAD

**Issue by iuiu34** [kubeflow/pipelines#6956]
For debugging, in kfp.V2, would be good to run the vertex_pipeline based on py-funcs you define locally (without docker build)
Also would avoid creating an almost identical, pipeline_local_func function.

For example with an
```py
from kfp.v2 import compiler
pipeline_filename = 'tmp/kfp_pipeline.json'
    compiler.Compiler().compile(pipeline_func=pipeline_func,
                                package_path=pipeline_filename)
    job = aiplatform.PipelineJob(
        pipeline_filename ,
        local = True)
    job.run()
```

**Comment by Iuiu1234** [comment]
An start step would be next code playing with the source of the code to execute it dynamically. But would only work with single output's and you still need to import properly the components as functions (which is verbose)

start_step could be confusing but since this is for debugging, seems a potential useful feature
```py
def run_pipeline_local(start_step=None, experiment_id=None):
    func_steps_output = dict(
        step_1="step_1_output",
        step_1="step_1_output",
        ...)
        
    func_steps = list(func_steps_output.keys())

    if start_step is not None:
        if start_step not in func_steps:
            raise ValueError
        print(f"start_step: {start_step}")
        start_index = func_steps.index(start_step)
    else:
        start_index = -1

    func_imports = {k: f"    def {k}(*args, **kwargs): return {v}" for k, v in func_steps_output.items()}
    func_imports = [v for k, v in func_imports.items() if func_steps.index(k) < start_index]
    func_imports = '\n'.join(func_imports)
    from test_module.pipeline import pipeline as func
    func_source = inspect.getsource(func)
    # delete kfp stuff
    func_source = func_source.replace('.output', '')
    func_source = func_source.replace('.component_spec', '')
    func_source_index_def = func_source.index("def churn_pipeline")
    func_source = func_source[func_source_index_def:]
    func_source_index_end_def = func_source.index("):")
    func_source_def = func_source[:func_source_index_end_def + 3]
    func_source_body = func_source[func_source_index_end_def + 3:]
    kwargs = {}
    # kwargs['start_step'] = start_step
    # kwargs['experiment_id'] = experiment_id
    exec_source = f"{func_source_def}\n{func_imports}\n{func_source_body}\n{func.__name__}(**kwargs)"
    print(exec_source)
```

**Comment by capri-xiyue** [comment]
Do you want to test and debug your python component in local environment?

**Comment by Iuiu1234** [comment]
Yep, this is for components based on py, not prebuild ones like google_cloud_pipeline_components (but run them also in local would be cool)
This is in order to
a) avoid having 2 files: kfp-pipeline & local-pipeline
b) enter debug mode
c) avoid building the docker image and release for debugging

**Comment by zijianjoy** [comment]
cc @chensun

**Comment by chensun** [comment]
Components and pipelines are quite different--one is a containerized app with optional Python function implementation, the other is a set of components organized in a DAG. I'd suggest we clearly define the scope of this request first.

It's on our roadmap to support local debugging/testing of a primitive component, but we are not planning for local debugging of pipelines--pipeline requires an orchestration engine, to fully support running a pipeline locally is almost like reimplement KFP backend.

**Comment by Iuiu1234** [comment]
yep, the function `run_pipeline_local` defined in #issuecomment-978066655 only covers the debugging of pipelines with only py-func components (i'm not sure if this is what you call primitive component)

agree that to locally debug all types of components will be out of this scope, 'cause is far more complex.

**Comment by hienqnguyen** [comment]
@chensun Do you have any details/updates on `It's on our roadmap to support local debugging/testing of a primitive component`? Thanks much!
