### ISSUE TITLE
[bug] Link on KubeFlow website is 404

### ISSUE THREAD

**Issue by haifeng-jin** [kubeflow/pipelines#6970]
### What steps did you take

Visit:

https://www.kubeflow.org/

Click on the KubeFlow Pipelines link, which direct me to 

https://www.kubeflow.org/docs/components/pipelines/overview/pipelines-overview/

### What happened:

I see a 404 page.

### What did you expect to happen:

display a page with contents.

### Environment:

*  How do you deploy Kubeflow Pipelines (KFP)? 

*  KFP version: 

*  KFP SDK version: 

### Labels

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by zijianjoy** [comment]
Thank you for the report! I created the fix https://github.com/kubeflow/website/pull/3081
