### ISSUE TITLE
[bug] TFX sample fails after upgrading to 1.4

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#6974]
### What steps did you take

* MLMD & TFX upgrade: https://github.com/kubeflow/pipelines/pull/6910

### What happened:

* Check test: https://oss-prow.knative.dev/view/gs/oss-prow/logs/kubeflow-pipeline-postsubmit-integration-test/1464225919869652992

### What did you expect to happen:

We need to upgrade the TFX sample to 1.4.0

### Labels

/area samples

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by Bobgy** [comment]
Failure error message coming from upgrading TFX from 1.2 to 1.4:

```
sample-test-7c4kw-3475281298: =========Argo Workflow Log=========
sample-test-7c4kw-3475281298: parameterized-tfx-oss-c6n2c-1861378462: time="2021-11-26T14:58:03.147Z" level=info msg="capturing logs" argo=true
sample-test-7c4kw-3475281298: parameterized-tfx-oss-c6n2c-1861378462: 2021-11-26 14:58:05.872653: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
sample-test-7c4kw-3475281298: parameterized-tfx-oss-c6n2c-1861378462: usage: container_entrypoint.py [-h] --pipeline_root PIPELINE_ROOT
sample-test-7c4kw-3475281298: parameterized-tfx-oss-c6n2c-1861378462:                                --kubeflow_metadata_config
sample-test-7c4kw-3475281298: parameterized-tfx-oss-c6n2c-1861378462:                                KUBEFLOW_METADATA_CONFIG --serialized_component
sample-test-7c4kw-3475281298: parameterized-tfx-oss-c6n2c-1861378462:                                SERIALIZED_COMPONENT --tfx_ir TFX_IR --node_id
sample-test-7c4kw-3475281298: parameterized-tfx-oss-c6n2c-1861378462:                                NODE_ID [--runtime_parameter RUNTIME_PARAMETER]
sample-test-7c4kw-3475281298: parameterized-tfx-oss-c6n2c-1861378462: container_entrypoint.py: error: the following arguments are required: --serialized_component
sample-test-7c4kw-3475281298: parameterized-tfx-oss-c6n2c-1861378462: time="2021-11-26T14:58:15.441Z" level=error msg="cannot save artifact /mlpipeline-ui-metadata.json" argo=true error="stat /mlpipeline-ui-metadata.json: no such file or directory"
sample-test-7c4kw-3475281298: parameterized-tfx-oss-c6n2c-1861378462: Error: exit status 2
```

**Comment by zijianjoy** [comment]
Thank you Yuan for finding this issue!

Will it be related to the tfx version in the https://github.com/kubeflow/pipelines/blob/master/samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py#L167?

Maybe at least we should upgrade tfx version to 1.4.0 in the parameterized_tfx_oss sample first, then investigate further for the issue?

TFX release changelog: https://github.com/tensorflow/tfx/blob/master/RELEASE.md

**Comment by jiyongjung0** [comment]
Thanks! I agree that we need to upgrade the code @zijianjoy pointed.
By the way, how about using the [default value](https://github.com/tensorflow/tfx/blob/d00b80c92792ec202564e2e90d081b361835e314/tfx/orchestration/kubeflow/kubeflow_dag_runner.py#L54) to avoid this kind of failure? It uses the image in the docker hub, then we don't need to update the version every time. (Or we can use tfx.version.__version__ in the parameterized_tfx_oss.py.)

**Comment by Bobgy** [comment]
> Thanks! I agree that we need to upgrade the code @zijianjoy pointed.
> By the way, how about using the [default value](https://github.com/tensorflow/tfx/blob/d00b80c92792ec202564e2e90d081b361835e314/tfx/orchestration/kubeflow/kubeflow_dag_runner.py#L54) to avoid this kind of failure? It uses the image in the docker hub, then we don't need to update the version every time. (Or we can use tfx.version.__version__ in the parameterized_tfx_oss.py.)

Using version.__version__ sounds like a good idea, because we don't want new image releases to break the sample.

**Comment by jiyongjung0** [comment]
Hi, @nroberts1, I think that you have to upgrade the TFX version installed in the container image, too. [The fix](https://github.com/kubeflow/pipelines/commit/3cfff3db1da0906a46980ce4f2b7ceda7458272a) updated the image to the TFX version of the client environment.

**Comment by nroberts1** [comment]
Yes that works I understand the fix now, thanks @jiyongjung0
