### ISSUE TITLE
[feature] Provide a way to define a set of default annotations for tasks

### ISSUE THREAD

**Issue by johnbuluba** [kubeflow/pipelines#6977]
### Feature Area

/area backend

### What feature would you like to see?

We would like to be able to define a set of annotations on the server-side, that will be automatically added to all pipeline tasks.

### What is the use case or pain point?

We need this feature to enable Istio sidecar injection by default to all the submitted pipelines. We want by default to annotate all tasks with:
```yaml
sidecar.istio.io/inject: true
proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
```
Currently, all tasks are automatically annotated with `sidecar.istio.io/inject: false` and we need a way to change this default behavior. 

### Is there a workaround currently?

The current workaround is to explicitly set the annotations in each pipeline task.

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by capri-xiyue** [comment]
Do you need to customize the annotation for pipeline tasks? For example, KFP provides a interface for user to define the annotations for specific pipeline tasks?
