### ISSUE TITLE
 Argument type "google.VertexDataset" is incompatible with the input type "Dataset"

### ISSUE THREAD

**Issue by v-loves-avocados** [kubeflow/pipelines#6981]
### What steps did you take

I created a KF pipeline in which:
1. First created a Vertex AI dataset
2. Defined a custom component, and pass the dataset as an input.

I was expecting that the dataset_create_task.outputs["dataset"] would pass a dataset to run_hptune as input. However, I got this error:

'Argument type "google.VertexDataset" is incompatible with the input type "Dataset"'

`def run_hptune(
    dataset:                Input[Dataset],
    hypertune_display_name: str,
    image_uri:              str, 
    staging_bucket:         str)->int:`

`@dsl.pipeline(name=pipeline_name, pipeline_root='gs://xxx')
def pipeline():

    dataset_create_task = gcc_aip.TabularDatasetCreateOp(
        project=project_id, 
        display_name=model_display_name,
        gcs_source=gcs_resource_uri
    )

    hypertune_job_run_task = run_hptune(
        dataset=dataset_create_task.outputs["dataset"],
        hypertune_display_name=hypertune_display_name, 
        image_uri=container_uri, 
        staging_bucket=staging_bucket)`

**Comment by lc-billyfung** [comment]
any update on this? I am encountering something similar with using the output of Vertex AI model upload, so I have a `google.VertexModel` that does not match `Input[Model]` in a python component.

**Comment by clausagerskov** [comment]
same problem

**Comment by clausagerskov** [comment]
try this:
```
hypertune_job_run_task = run_hptune(
    dataset=dataset_create_task.outputs["dataset"]**.ignore_type()**,
    hypertune_display_name=hypertune_display_name, 
    image_uri=container_uri, 
    staging_bucket=staging_bucket)`
```

**Comment by clausagerskov** [comment]
is it fixed though?

**Comment by clausagerskov** [comment]
okay then

**Comment by Cage89** [comment]
.
