### ISSUE TITLE
[bug] upgrade from MLMD 1.0.0 to 1.4.0 stuck in crashloopbackoff

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#6987]
Upstream issue: https://github.com/google/ml-metadata/issues/135

**Comment by Bobgy** [comment]
I tried reproducing this issue with a brand new MLMD grpc server, but I wasn't able to reproduce.

**Comment by Bobgy** [comment]
I'm going to delete the MLMD db manually to unblock the upgrade.

**Comment by Bobgy** [comment]
I connected to in-cluster mysql and deleted MLMD db in kfp-ci cluster.
```
kubectl run -it -n kubeflow --rm --image=mysql:8.0.12 --restart=Never mysql-client -- mysql -h mysql
$ show databases;
$ drop database metadb;
```

**Comment by zijianjoy** [comment]
Thank you Yuan for finding this issue! Does it mean KFP 1.8 will have breaking change for KFP upgrade scenario?

**Comment by Bobgy** [comment]
@zijianjoy we need to verify, if we cannot reproduce again, it might not be a breaking change.

**Comment by zijianjoy** [comment]
I have deployed a KFP 1.7.1, then upgrade to KFP 1.8.0 alpha 0. I am able to upgrade with no breaking change. 

### KFP 1.7.1 Artifacts (Look at version at bottom left)
![mlmd171](https://user-images.githubusercontent.com/37026441/144732092-88c9bef0-710a-4b5f-a6a2-3e0b50e935c8.png)


### KFP 1.8.0-alpha.0 Artifacts (Look at version at bottom left)
![mlmd180](https://user-images.githubusercontent.com/37026441/144732094-07af10cf-5dab-42f3-b910-319e810e3935.png)


### MLMD image version 
![mlmdimage140](https://user-images.githubusercontent.com/37026441/144732095-83c63d0a-b9ab-400d-b924-8e2d5c55de75.png)


Seems that the issue you encountered is not common case? Note that the way I upgraded is to follow instruction: https://www.kubeflow.org/docs/components/pipelines/installation/standalone-deployment/#upgrading-kubeflow-pipelines. Then I chose emissary executor again https://www.kubeflow.org/docs/components/pipelines/installation/choose-executor/.
