### ISSUE TITLE
ScheduledWorkflow CRD: CLI

### ISSUE THREAD

**Issue by ynqa** [kubeflow/pipelines#7]
Will it prepare the scheduledworkflows' CLIs in this repository to manage controller like `argo`? Or adding subcommands to argo.

**Comment by vicaire** [comment]
It will be done in this repo. Thanks!

**Comment by ynqa** [comment]
@vicaire Already done to make CLI? If it has not started yet, I'll make it!

**Comment by vicaire** [comment]
Sure, could you make a proposal of how it will look like? 

It would be nice if it could take as a parameter a file with an Argo workflow, and automatically generate the yaml for the ScheduledWorkflow.

**Comment by ynqa** [comment]
First, I'll make a command for installation of controller and CRD like `argo install...`. Then, ScheduledWorkflow controller is deployed as `Deployment` to kubernetes.

**Comment by ynqa** [comment]
@vicaire First, I'll make a command for installation of controller and CRD like `argo install`. Then, scheduledworkflow controller is deployed as `Deployment` to kubernetes.

**Comment by vicaire** [comment]
That looks great!

**Comment by ynqa** [comment]
@jlewi First, I think CLI to manage scheduledworkflows should be prepared.
For example, for dealing with the case to continue execution of the Argo workflow where it left off (or by indicating arbitrary position). I think also it's bothersome to handle this by `kubectl` and the manifests only.

And also I think it's not strange to install the components (CRD/controller) into k8s using this CLI also. that means satisfing consistency of operations.

But I agreed your opinions too. So I'll push once the manifest of controller only (I think there is no rush to prepare CLI itself) in #12 PR. Thanks.

**Comment by vicaire** [comment]
For installation of the CRD, we indeed need to conform to the Kubeflow standard of using a ksonnet package. 

Thanks for the reminder @jlewi.

**Comment by ynqa** [comment]
Sure. Thanks.

**Comment by ynqa** [comment]
I got it. Thanks.
