### ISSUE TITLE
Pipeline upload via URL doesn't work when port-forwarding from cloud shell

### ISSUE THREAD

**Issue by amygdala** [kubeflow/pipelines#700]
Uploading a pipeline from a URL doesn't work when port-forwarding from the cloud shell.  I see the following error, which of course is problematic b/c the URL is something like `https://8080-dot-3034840-dot-devshell.appspot.com/...` instead. 

![image](https://user-images.githubusercontent.com/115093/51358586-b7967780-1a78-11e9-8e1a-dbbea375fc9b.png)

**Comment by hongye-sun** [comment]
@yebrahim Is it a known issue? I remember that it's working before.

As a workaround, you can port forward from local shell.

**Comment by amygdala** [comment]
This is for a workshop where they're using cloud shell, so that workaround is not viable in that context. (but you're right, it does work via localhost)

**Comment by amygdala** [comment]
It looks like this was fixed in 4.1 (I'd been running 3.5) -- closing, will re-open if any other issues w/ it turn up.

**Comment by amygdala** [comment]
Hmmm.. I seem to be seeing this again w/ 0.4.1, so re-opening.  Not sure what's up.

**Comment by vicaire** [comment]
@yebrahim, do you know if this is a regression?

**Comment by amygdala** [comment]
It does seem to mostly work -- though I haven't been beating on it much. I just wanted to note on the issue that I had seen it again since.  I'm fine to close this if no one else is having probs.  (I'm wondering if there's any chance it was a browser caching issue).

**Comment by vicaire** [comment]
OK thanks. I will close it for now as that could prevent folks from filing an issue if they observe the problem.
