### ISSUE TITLE
[feature] Add GetPipelineByName endpoint

### ISSUE THREAD

**Issue by difince** [kubeflow/pipelines#7003]
### Feature Area

/area backend

### What feature would you like to see?

Add new endpoint - getPipelineByName 
Because the pipeline name is  unique within a namespace - the namespace should be taken into consideration

### What is the use case or pain point?
Simplify user experience and keep consistent with other tools like Kubernetes, DAGs in Argo, Airflow that use names as a reference instead of UUID 
This issue is inspired from #https://github.com/kubeflow/pipelines/issues/3360.

### Is there a workaround currently?
 Yes, use UUIDs  instead

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by capri-xiyue** [comment]
pipeline name is not unique in KFP. I think we can make the combination of name and namespace unique in KFP. FYI: https://github.com/kubeflow/pipelines/issues/3360#issuecomment-834450654

**Comment by difince** [comment]
Thank you for clarifying this @capri-xiyue. 
This issue is actually inspired by #3360 and I see it as the first issue from a list to cover entirely #3360. 
To your point of uniqueness - in the issue, I have written

> Because the pipeline name is unique within a namespace - the namespace should be taken into consideration

So, now in the [PR,](https://github.com/kubeflow/pipelines/pull/7004#pullrequestreview-827574954) there is a discussion on what is the best way to pass the namespace - using the `resource_reference` to filter on it or to make the namespace part of the URL itself.

**Comment by zijianjoy** [comment]
Note: After the backend change is merged, let's also follow up on the SDK side by using this new endpoint getPipelineByName.

**Comment by Bobgy** [comment]
> Note: After the backend change is merged, let's also follow up on the SDK side by using this new endpoint getPipelineByName.

We might want to delay the change, because we know a lot people upgrading KFP SDK to latest all the time, if we switch the API, their usage will break, because their deployment is not upgraded yet. Ideally, when we change existing SDK client implementation, we need to wait until the backend API is released for a while.

**Comment by difince** [comment]
@zijianjoy 
> let's also follow up on the SDK side by using this new endpoint getPipelineByName

Could you clarify what exactly do you mean? 
I see this new endpoint could incorporate within the CLI. The command could look like this:  
`kfp pipeline get --name NAME` 
WDYT? 

Is there something else I should consider? 

Once I know what is expected to be implemented I will open a dedicated issue about it. 
> we need to wait until the backend API is released for a while

Is this time gone or not yet?

**Comment by zijianjoy** [comment]
> I see that this new endpoint could be incorporated within the CLI. The command could look like this:
> kfp pipeline get --name NAME

This makes sense to me, but a bit correction about the order of subcommand: `kfp pipeline get --name NAME`.

>> we need to wait until the backend API is released for a while
> Is this time gone or not yet?

I tend to think it is about time SDK can start adding this API with SDK version 2.0.0+. cc @connor-mccarthy who is recently working on KFP SDK CLI.
