### ISSUE TITLE
[sdk] Compile fails when the pipeline name is not specified

### ISSUE THREAD

**Issue by ysk24ok** [kubeflow/pipelines#7013]
### Environment

*  KFP version: 

*  KFP SDK version: master

*  All dependencies version:

```
kfp                      1.8.9
kfp-pipeline-spec        0.1.13
kfp-server-api           1.7.1
```

### Steps to reproduce

```console
$ cat pipelines.py
from kfp.v2.dsl import pipeline, component
from kfp.v2.compiler import Compiler


@component
def do_nothing_op():
    pass


@pipeline()
def sample():
    do_nothing_op()


Compiler().compile(
    pipeline_func=sample,
    package_path="/tmp/pipeline.json",
)
$ python3 pipelines.py
Traceback (most recent call last):
  File "pipelines.py", line 17, in <module>
    Compiler().compile(
  File "/home/ysk24ok/repos/pipelines/sdk/python/kfp/v2/compiler/compiler.py", line 94, in compile
    pipeline_spec = self._create_pipeline_v2(
  File "/home/ysk24ok/repos/pipelines/sdk/python/kfp/v2/compiler/compiler.py", line 184, in _create_pipeline_v2
    pipeline_spec = self._create_pipeline_spec(
  File "/home/ysk24ok/repos/pipelines/sdk/python/kfp/v2/compiler/compiler.py", line 275, in _create_pipeline_spec
    self._validate_pipeline_name(pipeline.name)
  File "/home/ysk24ok/repos/pipelines/sdk/python/kfp/v2/compiler/compiler.py", line 393, in _validate_pipeline_name
    raise ValueError(
ValueError: Invalid pipeline name: Sample.
Please specify a pipeline name that matches the regular expression "^[a-z0-9][a-z0-9-]{0,127}$" using `dsl.pipeline(name=...)` decorator.
```

### Expected result

The pipeline can be compiled without specifying the name of the pipeline.

### Materials and Reference

https://github.com/kubeflow/pipelines/blob/c1b67154a2abb75bd7dea4d2c8c52a52e2e8f7b2/sdk/python/kfp/v2/compiler/compiler.py#L129
It seems this bug is caused here.
If the pipeline name is not specified, `pipeline_name` is None and `pipeline_meta.name` is used as its name, which is the return value of `_python_function_name_to_component_name`.

https://github.com/kubeflow/pipelines/blob/c1b67154a2abb75bd7dea4d2c8c52a52e2e8f7b2/sdk/python/kfp/v2/components/component_factory.py#L289-L291

This function capitalzies the first character and it does not match the rule in the compiler.
So I think we should add a new function like `_python_function_name_to_pipeline_name`  and use the result instead of `pipeline_meta.name`. Since the rule of components name and that of the pipeline name is different, we should use different functions.

```
pipeline_name = pipeline_name or _python_function_name_to_pipeline_name(pipeline_func)
```

If this approach is appropriate, I'll work on this.

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by zijianjoy** [comment]
cc @chensun

**Comment by ji-yaqi** [comment]
Hi @ysk24ok, in V2, we ask that pipeline name should be specified for better usage. 

Your code should look like:
```
@pipeline(name="your_pipeline_name")
def sample():
    do_nothing_op()
```

Hope this explains!

**Comment by ysk24ok** [comment]
@ji-yaqi Thank you for your response.
Then, how about make `name` arg of `pipeline` function required in v2 SDK?
It's a bit confusing that the type of`name` arg is `Optional[str]`.

**Comment by ysk24ok** [comment]
In kfp v2 (the stable release hasn't been made yet, though), the problem seems to be fixed.

```console
% cat pipeline.py
from kfp.dsl import pipeline, component
from kfp.compiler import Compiler


@component
def do_nothing_op():
    pass


@pipeline()
def sample_pipeline():
    do_nothing_op()


Compiler().compile(
    pipeline_func=sample_pipeline,
    package_path="/tmp/pipeline.yaml",
)
% python pipeline.py
% yq '.pipelineInfo' < /tmp/pipeline.yaml
name: sample-pipeline
```

The pipeline name is inferred from the pipeline function name. Closing this issue.
