### ISSUE TITLE
pod status is NotReady

### ISSUE THREAD

**Issue by ashissharma97** [kubeflow/pipelines#7021]
Hi,
I have installed Kubeflow from Kubeflow manifest and when I am running a pipeline I am getting pod status as “NotReady”. Can somebody help with this?

Thanks

**Comment by ashissharma97** [comment]
Hi @zijianjoy,
Thanks for replying
Here is the yaml file of the pod 
`
apiVersion: v1
kind: Pod
metadata:
  labels:
    pipeline/runid: d5d18505-8c11-4caa-8e5a-168e14e35981
    pipelines.kubeflow.org/cache_enabled: "true"
    pipelines.kubeflow.org/cache_id: ""
    pipelines.kubeflow.org/metadata_context_id: "3"
    pipelines.kubeflow.org/metadata_execution_id: "3"
    workflows.argoproj.io/completed: "false"
    workflows.argoproj.io/workflow: "[some_name]"
  name: "[name]"
  namespace: "[namespace]"
  ownerReferences:
  - apiVersion: argoproj.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Workflow
    name: "[some_name]"
    uid: b6ff07e0-c798-406c-afc5-275ba61226f2
  resourceVersion: "643080"
  uid: e755c715-c613-401f-b699-a741fc07d35f
spec:
  containers:
  - command:
    - argoexec
    - wait
    - --loglevel
    - info
    env:
    - name: ARGO_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: ARGO_CONTAINER_RUNTIME_EXECUTOR
      value: docker
    - name: GODEBUG
      value: x509ignoreCN=0
    - name: ARGO_CONTAINER_NAME
      value: wait
    - name: ARGO_INCLUDE_SCRIPT_OUTPUT
      value: "false"
    image: gcr.io/ml-pipeline/argoexec:v3.1.6-patch-license-compliance
    imagePullPolicy: IfNotPresent
    name: wait
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 32Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /argo/podmetadata
      name: podmetadata
    - mountPath: /var/run/docker.sock
      name: docker-sock
      readOnly: true
    - mountPath: /argo/secret/mlpipeline-minio-artifact
      name: mlpipeline-minio-artifact
      readOnly: true
    - mountPath: /mainctrfs/obj
      name: "[pvc]"
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-zgpz8
      readOnly: true
  - command:
    - python
    - print.py
    env:
    - name: ARGO_CONTAINER_NAME
      value: main
    - name: ARGO_INCLUDE_SCRIPT_OUTPUT
      value: "false"
    image: "[imagelink]"
    imagePullPolicy: Always
    name: main
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /obj
      name: "[volume_path]"
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-zgpz8
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-node
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default-editor
  serviceAccountName: default-editor
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - downwardAPI:
      defaultMode: 420
      items:
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.annotations
        path: annotations
    name: podmetadata
  - hostPath:
      path: /var/run/docker.sock
      type: Socket
    name: docker-sock
  - name: pvc_name
    persistentVolumeClaim:
      claimName: pvc_name
  - name: mlpipeline-minio-artifact
    secret:
      defaultMode: 420
      items:
      - key: accesskey
        path: accesskey
      - key: secretkey
        path: secretkey
      secretName: mlpipeline-minio-artifact
  - name: kube-api-access-zgpz8
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-12-10T19:19:28Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-12-10T19:19:28Z"
    message: 'containers with unready status: [main]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-12-10T19:19:28Z"
    message: 'containers with unready status: [main]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-12-10T19:19:28Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://867d5a7e486aa4809f7090221d75c982b698b98cde66a57dd4c6b4cf1ba5eb52
    image: "[container_link]"
    imageID: "[container_link_id]"
    lastState: {}
    name: main
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://867d5a7e486aa4809f7090221d75c982b698b98cde66a57dd4c6b4cf1ba5eb52
        exitCode: 0
        finishedAt: "2021-12-10T19:20:36Z"
        reason: Completed
        startedAt: "2021-12-10T19:20:36Z"
  - containerID: containerd://c78df00a2e6316fdf5ea69c8eddfa3c65adc358c2da852892ae2b7af7461f67f
    image: gcr.io/ml-pipeline/argoexec:v3.1.6-patch-license-compliance
    imageID: gcr.io/ml-pipeline/argoexec@sha256:44cf8455a51aa5b961d1a86f65e39adf5ffca9bdcd33a745c3b79f430b7439e0
    lastState: {}
    name: wait
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-12-10T19:19:51Z"
  hostIP: 10.1.0.31
  phase: Running
  podIP: 10.244.1.69
  podIPs:
  - ip: 10.244.1.69
  qosClass: Burstable
  startTime: "2021-12-10T19:19:28Z"
  `

**Comment by zijianjoy** [comment]
Can you share with me:

1. Kubernetes version
2. Kubeflow version
3. What executor your are using? https://www.kubeflow.org/docs/components/pipelines/installation/choose-executor/

**Comment by ashissharma97** [comment]
Sure...
Kubernetes Version: 1.21.6-gke.1500
Kubeflow Version: v1.4.0
The executor I am using is the default one which is containerd.

Thanks

**Comment by zijianjoy** [comment]
Are you using emissary executor?

`kubectl describe configmap workflow-controller-configmap | grep -A 2 containerRuntimeExecutor`

**Comment by ashissharma97** [comment]
No, I am using docker

**Comment by zijianjoy** [comment]
@ashissharma97 , KFP won't work if you are using Kubernetes version > 1.19, because docker runtime has been deprecated by Kubernetes. You will have to switch to use emissary executor in order to make your pipeline working.

In order to use emissary executor: https://www.kubeflow.org/docs/components/pipelines/installation/choose-executor/#migrate-to-emissary-executor

Detailed issue description: https://github.com/kubeflow/pipelines/issues/5714

**Comment by ashissharma97** [comment]
Thank You @zijianjoy, This resolved my issue.
