### ISSUE TITLE
[sdk] Wrong IPython url links

### ISSUE THREAD

**Issue by juliadeclared** [kubeflow/pipelines#7023]
### Environment

Running on a full KF 1.4 installation on top of GKE.

*  KFP version: 1.7.1

*  KFP SDK version: 1.6.0

*  All dependencies version:

kfp                             1.6.0
kfp-pipeline-spec               0.1.7
kfp-server-api                  1.6.0

### Steps to reproduce

Create an experiment `kfp.Client.create_experiment() `in a notebook
Click the generated link in Ipython

### Expected result

Currently generated link (incorrect): https://cluster_uri/#/experiments/details/88140703-5a6e-49ee-ba14-ed3b2a625877
Actual link (correct): https://cluster_uri/_/pipeline/?ns=namespace#/experiments/details/88140703-5a6e-49ee-ba14-ed3b2a625877

### Materials and Reference

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by zijianjoy** [comment]
cc @chensun

**Comment by chensun** [comment]
Hi @juliadeclared I saw you closed the PR. Is the issue still valid?

**Comment by casassg** [comment]
@chensun yes, the issue is still valid. For KF installations, the generated URI should include domain/_/pipeline since this is how its mapped for KF full installation.

Maybe this can be a small doc update or something similar. But it was quite tricky for us to debug.

**Comment by chensun** [comment]
> id. For KF installations, the generated URI should include domain/_/pipeline since this is how its mapped for KF full installation.

I see. yes, I recall the URL for standalone KFP deployment and full fledge KF deployment are different. And currently we don't have a way to tell from the SDK client side, so we can only return one form of the URL. 
You're probably right that this might need a doc update. Any suggestion where the change could be? Please feel free to create doc update PRs as well. Thanks!

**Comment by juliadeclared** [comment]
@chensun here is the doc update PR: https://github.com/kubeflow/website/pull/3105
