### ISSUE TITLE
[feature] Make func_to_container_op functions ready for autogenerated docs

### ISSUE THREAD

**Issue by hahamark1** [kubeflow/pipelines#7028]
### Feature Area

/area backend

### What feature would you like to see?

Currently the function wrapper (`func_to_container_op`) Does not copy the docstring of the function to the new wrapper object. Due to this, autogenerated docs cannot deal with kubeflow components.

### What is the use case or pain point?

It would help us drastically in spending less time on writing docs.

### Is there a workaround currently?
Currently, we write are docs by hand.

### How to solve it?

By adding the following to the function `func_to_container_op` in `components._python_op.py`

```
task_factory = _create_task_factory_from_component_spec(component_spec)

task_factory.__name__ = func.__name__
task_factory.__doc__ = func.__doc__

return task_factory
---

<!-- Don't delete message below to encourage users to support your feature request! -->
Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by zijianjoy** [comment]
cc @chensun

**Comment by ji-yaqi** [comment]
Hi @hahamark1, 

`func_to_container_op` function is actually deprecated. To generate the docstrings, we need some amount of work to generate kfp-specific docstrings. We will work on this in the future. Thanks!

**Comment by micahjsmith** [comment]
Hi @ji-yaqi , came across this and was wondering whether there is a way users could find out what are the deprecated aspects of v1 SDK from documentation/library itself. Would you be amenable to a PR that adds docstring updates/deprecation warnings to this function/other deprecated functions?
