### ISSUE TITLE
how to set restartPolicy "Never" to init containers 

### ISSUE THREAD

**Issue by changhoekim** [kubeflow/pipelines#7072]
```
kfp.dsl.ContainerOp(
      name = 'spark-test',
      image = 'blahblah',
      init_containers=[ kfp.dsl.UserContainer(name='sdfs', image='sdfs', command=['sh', '-c'], args=['sdfsf'])],
      command = ["sh", "-c"])
```
this is my operation.

I tested wrong init containers and then pipeline retry my pipeline so many times.
I want to test just one try.

how to set restartPolicy to my pipeline container ?

**Comment by chensun** [comment]
As far as I'm aware, we don't support setting restartPolicy for either main container nor init container via SDK. 
BTW, ContainerOp is deprecated, you should received a warning for the code above.
