### ISSUE TITLE
[feature] Flexible tensorboard images

### ISSUE THREAD

**Issue by casassg** [kubeflow/pipelines#7078]
### Feature Area

/area frontend

### What feature would you like to see?

Allow installations to modify the images available on tensorboard. This would allow us to have images with tftext or tensorboard expansions as needed. 

Currently tensorboard image list is a HTML embedded in the frontend.

### What is the use case or pain point?

Use tensorboard from KFP with different variations/versions and custom images.

### Is there a workaround currently?

Not possible, really manual deploy of an instance from kubectl.

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by dbg-raghulkrishna** [comment]
any update on this? i have to include our antifactory images in our organization
