### ISSUE TITLE
Can not use NFS volume for Tensorboard logs

### ISSUE THREAD

**Issue by SinaChavoshi** [kubeflow/pipelines#708]
I don't seem to be able to use an NFS mount as a source for the tensorboard data. Currently the only option seems to be to copy the data to a GCS bucket however this is a blocker for on prem deployment. 

Also related to #489  and #699

**Comment by IronPan** [comment]
Agreed. We plan to use PersistentVolume to decouple actual storage from the artifact store. I will send out a proposal publicly soon.

**Comment by vicaire** [comment]
Resolving in favor of related issues. Please re-open if needed.
