### ISSUE TITLE
 k8sapi executor does not support outputs from base image layer

### ISSUE THREAD

**Issue by wybaron** [kubeflow/pipelines#7106]
Run Experiments
![image](https://user-images.githubusercontent.com/19605510/147098266-16f704cf-9266-4b77-84dc-ebfd985db48c.png)

**Comment by zijianjoy** [comment]
Hello @wybaron , we don't support k8sapi executor, please switch to emissary executor: https://github.com/kubeflow/pipelines/issues/5714
