### ISSUE TITLE
[bug]  `custom_job.job_spec.tensorboard` incompatible with execution on Vertex Pipelines

### ISSUE THREAD

**Issue by aaaaahaaaaa** [kubeflow/pipelines#7123]
According to the documentation [here](https://cloud.google.com/vertex-ai/docs/experiments/tensorboard-training#create_a_custom_training_job), `Vertex Tensorboard` can be configured for a custom job on Vertex by settings `custom_job.job_spec.tensorboard`. However, it seems incompatible with an execution of the task on `Vertex Pipelines`:

When setting the `tensorboard` field, e.g.:
```
trainer_task = MyTrainerOp(...)
trainer_task.custom_job_spec = {
    "displayName": "My Trainer",
    "jobSpec": {
        "tensorboard": "projects/XXXX/locations/XXX/tensorboards/XXX",
        "workerPoolSpecs": [
            ...
        ],
    },
}
```

The following error is raised by `google.cloud.aiplatform.internal.JobService.CreateCustomJob`:
> custom_job.job_spec.service_account must be specified when uploading to TensorBoard

And if `serviceAccount` is set:
```
trainer_task = MyTrainerOp(...)
trainer_task.custom_job_spec = {
    "displayName": "My Trainer",
    "jobSpec": {
        "serviceAccount": SERVICE_ACCOUNT,
        "tensorboard": "projects/XXXX/locations/XXX/tensorboards/XXX",
        "workerPoolSpecs": [
            ...
        ],
    },
}
```

The following error is raised at the `google.cloud.aiplatform.v1.PipelineService.CreatePipelineJob` level:
> Specifying custom service account is not supported at the task level

So the two errors are basically blocking each other.

### Environment:

*  KFP version:  Vertex Pipelines
*  KFP SDK version: 1.8.10

**Comment by chensun** [comment]
```python
trainer_task.custom_job_spec = {
 ...
}
```
This was an experimental implementation, and it has been dropped post KFP SDK 1.8 release (deleted from master branch). 
Can you please try the replacement version, which is a component from [a separate Python package](https://pypi.org/project/google-cloud-pipeline-components/): 

https://cloud.google.com/vertex-ai/docs/pipelines/customjob-component

**Comment by aaaaahaaaaa** [comment]
Thanks for the clarification. I confirm the `create_custom_training_job_op_from_component` works for that purpose.
