### ISSUE TITLE
[backend] Envoy metadata pod is exposing admin interface

### ISSUE THREAD

**Issue by sebastien-prudhomme** [kubeflow/pipelines#7124]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?

Install Kubeflow Pipelines 1.7.0 (standalone mode) with kustomize. 

### Steps to reproduce

Get metadata-envoy-deployment pod IP address:

```
kubectl -n kubeflow get pod metadata-envoy-deployment-5b4856dd5-bd88x -o wide
NAME                                        READY   STATUS    RESTARTS   AGE   IP           NODE     NOMINATED NODE   READINESS GATES
metadata-envoy-deployment-5b4856dd5-bd88x   1/1     Running   0          84s   10.42.0.54   lenovo   <none>           <none>

```

Get some data from admin interface (port 9901):

```
curl 10.42.0.54:9901/clusters
metadata-cluster::default_priority::max_connections::1024
metadata-cluster::default_priority::max_pending_requests::1024
metadata-cluster::default_priority::max_requests::1024
metadata-cluster::default_priority::max_retries::3
metadata-cluster::high_priority::max_connections::1024
metadata-cluster::high_priority::max_pending_requests::1024
metadata-cluster::high_priority::max_requests::1024
metadata-cluster::high_priority::max_retries::3
metadata-cluster::added_via_api::false
metadata-cluster::10.43.201.59:8080::cx_active::0
metadata-cluster::10.43.201.59:8080::cx_connect_fail::0
metadata-cluster::10.43.201.59:8080::cx_total::0
metadata-cluster::10.43.201.59:8080::rq_active::0
metadata-cluster::10.43.201.59:8080::rq_error::0
metadata-cluster::10.43.201.59:8080::rq_success::0
metadata-cluster::10.43.201.59:8080::rq_timeout::0
metadata-cluster::10.43.201.59:8080::rq_total::0
metadata-cluster::10.43.201.59:8080::hostname::metadata-grpc-service
metadata-cluster::10.43.201.59:8080::health_flags::healthy
metadata-cluster::10.43.201.59:8080::weight::1
metadata-cluster::10.43.201.59:8080::region::
metadata-cluster::10.43.201.59:8080::zone::
metadata-cluster::10.43.201.59:8080::sub_zone::
metadata-cluster::10.43.201.59:8080::canary::false
metadata-cluster::10.43.201.59:8080::priority::0
metadata-cluster::10.43.201.59:8080::success_rate::-1
metadata-cluster::10.43.201.59:8080::local_origin_success_rate::-1
```

### Expected result

Pod metadata-envoy-deployment should not expose envoy admin interface as you can shutdown the server with it.

### Materials and Reference

See there: https://www.envoyproxy.io/docs/envoy/latest/operations/admin

In the Envoy doc, admin socket is listening on 127.0.0.1, not on 0.0.0.0 as in https://github.com/kubeflow/pipelines/blob/f4a37b27ec5950310a76943e1ff68289b9c40d7d/third_party/metadata_envoy/envoy.yaml#L4

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by zijianjoy** [comment]
cc @chensun .

**Comment by YosiElias** [comment]
I am interested in solving this (with liavweiss)
/assign

**Comment by YosiElias** [comment]
I checked with stand alone installation on Docker Desktop and it seems that this works as expected. 
This request is not accessible outside the cluster, because metadata-envoy-service is ClusterIP service:
![image](https://github.com/kubeflow/pipelines/assets/73485442/f10e9535-8f3b-4ada-bf4a-ccb08ab2a0d9)

So I have some question for you @sebastien-prudhomme:
1. Where did you run that curl from?
2. Did you use a local Kubernetes setup? Because maybe that's why you can access the ClusterIP service.

**Comment by sebastien-prudhomme** [comment]
curl was done from a Kubernetes node which has access to ClusterIP. For me if another pod inside the cluster can access this admin port, it's a security risk, but as I'm no more using kubeflow I close the issue.
