### ISSUE TITLE
[feature] Improve frontend CSS for task display name overflow

### ISSUE THREAD

**Issue by jli** [kubeflow/pipelines#7157]
### Feature Area

/area frontend

### What feature would you like to see?

Change the task display name CSS overflow properties so that long task names don't get truncated.

### What is the use case or pain point?

We have somewhat longer task display names, which map to functions in our codebase (so that it's easy to find the relevant code in our codebase). This causes the names to be truncated in the KFP graph view, and this makes it hard to read and use:

![Screen Shot 2022-01-10 at 16 59 27](https://user-images.githubusercontent.com/133466/148846062-79a28a31-9b99-4cfd-b0f5-a2c00066a0ae.png)

---

I experimented a bit, and just adding [`overflow-wrap: break-word`](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Text/Wrapping_Text#breaking_long_words) to the div with the display name helps a lot! (specifically, adding the CSS to the `div.label_<hash>` element which already has the `overflow: hidden` and `text-overflow: ellipsis` properties)

(Very long names still disappear because the task boxes have fixed height. I think ideally the height could expand to show the entire name, though I can imagine that this is hard to change because the graph layout code assumes fixed box size.)

![Screen Shot 2022-01-10 at 16 59 57](https://user-images.githubusercontent.com/133466/148846116-eafc9d26-18ea-42fc-91af-b18853b1210b.png)

### Is there a workaround currently?

No.

We can shorten our task names to a point, but this isn't feasible for all our pipelines. For example, some pipelines involve training multiple models, and we use prefixes to disambiguate each sub-dag, and being forced to use short abbreviations hurts clarity/understandability.

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by zijianjoy** [comment]
Hello @jli , thank you so much for the feature request! I agree that this can improve user experience, feel free to contribute since you have already tried the CSS style. Also, if you hover over to the node, you can see the full name from your mouse.
