### ISSUE TITLE
minio Express webserver doesn't specify character encoding

### ISSUE THREAD

**Issue by jli** [kubeflow/pipelines#7158]
### What steps did you take

- Click on a task on the KFP run page.
- On the Input/Output tab, click the minio:// link for `main-logs` to view raw logs.

### What happened:

The logs file is served from the minio Express webserver without any character encoding header. This causes any non-ascii UTF-8 characters to be rendered as garbled text.

### What did you expect to happen:

I think changing the Express server to always return UTF-8 is a reasonable default (i.e., `content-type: text/plain; charset=UTF-8`).

### Environment:

*  How do you deploy Kubeflow Pipelines (KFP)? standalone
*  KFP version: 1.7.1
*  KFP SDK version: 1.6.2

### Anything else you would like to add:

There is no workaround for this with Google Chrome, as the option to change the character encoding was removed a while ago.

### Labels

/area frontend
/area backend

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by zijianjoy** [comment]
I don't seem to reproduce the issue. Maybe it is because I don't understand it fully yet. Do you have an example pipeline I can run and inspect the logs for difference?

**Comment by jli** [comment]
@zijianjoy The issue is specifically with non-ascii characters. In our case, we have some logs that emit the emoji: ⏳

Here's some example logs from the "Logs" tab in the KFP web UI:
<img width="450" alt="Screen Shot 2022-01-18 at 20 16 41" src="https://user-images.githubusercontent.com/133466/150045291-c03f4cdd-6f86-475c-a313-527bf727210d.png">

And here's the same logs when served via the minio server:
<img width="408" alt="Screen Shot 2022-01-18 at 20 18 02" src="https://user-images.githubusercontent.com/133466/150045347-c4aec2a7-3d78-4534-8e7f-31cf177c4441.png">

So, the text "⏳ Entering timer Training Keras model" is show as "â³ Entering timer Training Keras model" when served via minio.

A pipeline that is just 1 task with code like `print("unicode stuff: 👍 🤞 😎")` should trigger the issue?

**Comment by zijianjoy** [comment]
Thank you @jli for the information. I have tested KFP backend and found that the header has already been `
content-type: text/plain; charset=utf-8` for the logs. I am wondering if your suggestion is to convert response to unicode instead of ascii. 

Reference: https://github.com/kubeflow/pipelines/blob/6fac61751b690b09846d0e7f2b657c95be884501/frontend/server/k8s-helper.ts#L243

Feel free to contribute if this helps your use case.

**Comment by zijianjoy** [comment]
Also see Nodejs redirection: https://github.com/kubeflow/pipelines/blob/6fac61751b690b09846d0e7f2b657c95be884501/frontend/server/app.ts#L145

**Comment by Wansh619** [comment]
Is this issue still open
