### ISSUE TITLE
[backend] discussion - resource reference in API interface considered harmful

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#7169]
There were some previous discussions around this topic, but let me summarize my arguments against using resource references in the public API.

## Proposal

Replace resource reference in API interface with explicit fields. For example, instead of passing resource reference for a pipeline version, we can just have a version ID / version Name field in the pipeline spec to specify which version we want to run.

After explicit fields are added in the API, generated API client will be good enough to use directly, so we may no longer need the manually maintained helpers.

## Rationale for introducing resource references

Each resource (pipeline, pipeline version, experiment, recurring run, etc) may have external relationship with other resources. Therefore, we introduced resource reference as a flexible and generic way to express and store this relationship, especially in the DB layer.

API proto:
https://github.com/kubeflow/pipelines/blob/0d64c3490a2da50c667e0dfd7a09b6e6ab7f5e55/backend/api/resource_reference.proto#L20-L52
DB Storage model: https://github.com/kubeflow/pipelines/blob/0d64c3490a2da50c667e0dfd7a09b6e6ab7f5e55/backend/src/apiserver/model/resource_reference.go#L23-L45

## Arguments against resource references

However, there are some cognitive overhead for understanding resource references.

For a given type of resource, what are the possible resource references? There are combinations for resource type, relationship type. A request is only valid when you get both right. For example, what are valid combinations of resource references for a create run request? The api definition says almost nothing: https://github.com/kubeflow/pipelines/blob/0d64c3490a2da50c667e0dfd7a09b6e6ab7f5e55/backend/api/run.proto#L233-L236. You can only learn that by reading other docs or reading code: https://github.com/kubeflow/pipelines/blob/0d64c3490a2da50c667e0dfd7a09b6e6ab7f5e55/backend/src/apiserver/server/util.go#L337 that the only possible combination is a pipeline version resource type + creator relationship.

For REST API users, they also need to worry about what's the exact spelling for the enums, they cannot get a helpful error when their spellings are incorrect.
For API generated client users, they need to learn where to import the resource reference model object and how to construct them: https://github.com/kubeflow/pipelines/blob/0d64c3490a2da50c667e0dfd7a09b6e6ab7f5e55/sdk/python/kfp/_client.py#L913-L919
It's hard to figure out without an example, and it's easy to forget that I'll need to look up this code snippet every once a while.

Therefore, a seemingly simple and flexible resource reference field expands to so many complexities in the downstream.

At the end, we manually maintain a SDK client method to expose the version ID arg as a simple field to hide resource reference from API: https://github.com/kubeflow/pipelines/blob/0d64c3490a2da50c667e0dfd7a09b6e6ab7f5e55/sdk/python/kfp/_client.py#L697.

Therefore, I propose that we consider adding resource references alternatives in public API interface and gradually let people use those explicit fields directly. It's still reasonable to use resource reference as the underlying implementation, because it's a flexible model.

## Common arguments for resource references and why I think they are not valid

1. Resource reference makes public interface flexible, e.g. when we add new relationships between resources or change sth, we don't need to change the public interface.

  [counter-argument]: I think the flexibility is only an illusion, an interface includes both the type definition and constraints user need to understand, as I mentioned above, users have to understand the exact valid combinations for a resource reference, so that's in fact part of the interface contract itself. Having a flexible type definition does not help make the actual interface flexible.

2. We can keep the API implementation simple.

  [counter-argument]: the cost of making API implementation simple is that additional complexities are introduced in the downstream -- SDK manually maintained methods, more documentation to explain these fields (that we cannot easily keep up-to-date) and still there are user cognitive load when understanding this. If we look at KFP ecosystem as a whole, I think more complexities are introduced overall than the simpler API implementation.

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by Bobgy** [comment]
/cc @zijianjoy @chensun @difince 

Sharing some thoughts about current API design, what do you think?

**Comment by difince** [comment]
@Bobgy I totally agree with all of your arguments and I could confirm that using the resource_reference was not that easy and intuitive for me as well. 
I have a question for case of [ getPipelineByName ](https://github.com/kubeflow/pipelines/pull/7004)(and namespace)
How the URL path `/apis/v1beta1/namespaces/{namespace}/pipelines/{name}`  is going to look like taking into consideration that the namespace is not a mandatory field? (in cases of Kubeflow standalone deployment and in multi-user mode - "shared" pipelines?)

**Comment by difince** [comment]
The question above is more about PR #7004 I will move it there. I agree with this proposal

**Comment by zijianjoy** [comment]
Agreeing to this proposal 👍. By looking at the KFP API list: https://www.kubeflow.org/docs/components/pipelines/reference/api/kubeflow-pipeline-api-spec/, I feel that the amount of work will require a major refactoring of existing APIs. And more importantly, it takes a longer time to migrate to new APIs and deprecate old APIs.

Code structure: For a better migration process, I am thinking about creating another [package](https://developers.google.com/protocol-buffers/docs/proto3#packages) for new APIs: https://github.com/kubeflow/pipelines/tree/master/backend/api. So when we deprecate, we just need to deprecate the old package. 

KFP standalone use case: When namespace is not required, we can use `-` for `unique resource lookup` in https://google.aip.dev/159.

**Comment by Bobgy** [comment]
> Code structure: For a better migration process, I am thinking about creating another [package](https://developers.google.com/protocol-buffers/docs/proto3#packages) for new APIs: https://github.com/kubeflow/pipelines/tree/master/backend/api. So when we deprecate, we just need to deprecate the old package.

Just my opinion, I am not sure whether it's worth the effort creating a new API package, because [it's non-trivial supporting two APIs using the same code](https://github.com/kubeflow/pipelines/blob/577902ca46eee101cf1d7d197908797f4ab16fce/backend/src/apiserver/main.go#L96-L109). Also, it's natural for an API to evolve: add new fields, deprecate old fields, support both fields in the same time to allow gradual migration to the new field etc.

example: https://github.com/kubeflow/pipelines/blob/a03b41e129712b1416ee68cdea1e5ad4da1341dc/api/v2alpha1/pipeline_spec.proto#L29-L31

**Comment by Ark-kun** [comment]
I fully agree with Yuan's argument.

The way the Experiments <-> Pipeline relationship and Pipeline <-> Version relationship were introduced and implemented was less than ideal. Actually, initially it was significantly worse: The user could not submit a pipeline run without creating an experiment first and specifying the relationship. Fortunately, this was changed after some time. The way the pipeline versions were introduced also went against the typical API design guidelines, which lead to many issues reported by the users.
To this day, we do not see any significant usage of Experiments or Versions.

The API could have been much simpler to use:

```
Run/create
Experiment/create
Experiment/<ID>/runs/add(runId=...)
Experiment/<ID>/runs/remove(runId=...)
Experiment/<ID>/runs/list

PipelineGroup/create
PipelineGroup/<ID>/pipelines/list
PipelineGroup/<ID>/pipelines/latest
Pipeline/create(spec=..., pipelineGroupId=...)
```

**Comment by difince** [comment]
Based on @Bobgy proposal in this issue, Anna @annajung and I created a proposal [document](https://docs.google.com/document/d/19OfU-hIsY4xBKA6b_F3dYIbSgrLMrVshucUSsyqotQ4/edit). It contains specific APIs changes we are proposing in order to remove `resource_references` from the APIs. Please comment or ask questions in the document or here in the issue. Hope we will bring the proposal up for discussion during the next Pipeline meeting (04/27/2022). 

cc: @chensun, @zijianjoy, @james-jwu,  @Ark-kun
