### ISSUE TITLE
[frontend] Unable to upload pipeline by URL in KF 1.4

### ISSUE THREAD

**Issue by akangst** [kubeflow/pipelines#7196]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
We're deployed in a full kubeflow installation in the platform-agnostic-multi-user configuration. 
*  KFP version: 
1.7

### Steps to reproduce

1. Open KF Pipelines UI
2. Click "Upload Pipeline" in the upper right. 
3. Fill out Name and Description fields
4. Select "Import by url" Radio Button and paste github link into Package Url box. 
5. Click "Create"

### Expected result

It should accept the pipeline and work like it does when the same template is uploaded as a local file. I get good results using that method. 

### Materials and Reference

Error Message that is output:

{"error":"Failed to authorize with API resource references: PermissionDenied: User 'dhoover@emailaddress.com' is not authorized with reason:  (request: \u0026ResourceAttributes{Namespace:,Verb:create,Group:,Version:,Resource:pipelines,Subresource:,Name:,}): Unauthorized access","code":7,"message":"Failed to authorize with API resource references: PermissionDenied: User 'dhoover@emailaddress.com' is not authorized with reason:  (request: \u0026ResourceAttributes{Namespace:,Verb:create,Group:,Version:,Resource:pipelines,Subresource:,Name:,}): Unauthorized access","details":[{"@type":"type.googleapis.com/api.Error","error_message":"User 'dhoover@emailaddress.com' is not authorized with reason:  (request: \u0026ResourceAttributes{Namespace:,Verb:create,Group:,Version:,Resource:pipelines,Subresource:,Name:,})","error_details":"Failed to authorize with API resource references: PermissionDenied: User 'dhoover@emailaddress.com' is not authorized with reason:  (request: \u0026ResourceAttributes{Namespace:,Verb:create,Group:,Version:,Resource:pipelines,Subresource:,Name:,}): Unauthorized access"}]}

To me this looks a lot like https://github.com/kubeflow/pipelines/issues/6102 where it also was not getting the proper attributes to make a clean Auth call back to the cluster. 

It looks like this was also referenced in https://github.com/kubeflow/pipelines/pull/6291. but perhaps it was not fixed all the way in multi-user configuration. 

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by zijianjoy** [comment]
cc @annajung , looks like this is related to https://github.com/kubeflow/pipelines/pull/6291. Do you have any insight for this issue? Thank you!

**Comment by annajung** [comment]
It's been a while since I worked on the issue, so I'm getting caught up. Taking a look at this issue this week and hope to have an update PR. 

/assign @annajung

**Comment by DnPlas** [comment]
Hi @annajung @zijianjoy, this error seems to still be present in 1.7.0-rc.1.

**Comment by NohaIhab** [comment]
Hello,
tested with 1.7.0-rc.1, Issue persists with the same error.
**Findings:**
Import by url only works when choosing to `Create a new pipeline version under an existing pipeline`, but fails on `Create a new pipeline`.

**Comment by rimolive** [comment]
Is this issue still relevant? Since 2.0.5 is out, I'll close this issue but feel free to reopen it if the issue persists

/close
