### ISSUE TITLE
[feature] Allow user to specify which input parameters to use in cache key

### ISSUE THREAD

**Issue by amitchnick** [kubeflow/pipelines#7201]
### Feature Area

/area sdk

### What feature would you like to see?

Right now, the only caching customization that exists on an operator level in v1 KFP (please correct me if I am wrong), is:
```
task = some_op()
task.execution_options.caching_strategy.max_cache_staleness
```
Something that would be greatly helpful for my use case is if there was a way to specify which input parameters should be used to generate the cache key, such as follows:

```
# assuming my input params are as follows: data_input_dir: str, model_output_dir: str, s3_path: str,
task = some_op()
task.execution_options.caching_strategy.include_input_parameters([data_input_dir, model_output_dir])
```
The expected behavior here would be that if there was a previous run of the given task with identical `data_input_dir` and `model_output_dir` inputs, but a different `s3_path`, the previously-cached task would be valid and be used.

### What is the use case or pain point?

We are trying to build full model training pipelines using KFP. The training jobs take a long time, and we would like them to use the cache whenever possible. However, each run has a _unique_ `s3_path` which we sync training checkpoints to during the job, which is the only way the jobs can finish successfully. Thus, we must provide `s3_path` as an input parameter, but it should not be used to determine whether the model has been trained with the same inputs before (ie. whether to use the cache). Rather, in our case, this should only depend on the data used (artifacts from the upstream task), and the config parameters (other input parameters to the task). Therefore, we would like to be able to have the caching mechanism ignore this unique `s3_path` parameter.

### Is there a workaround currently?

I have tried experimenting with injecting the S3 path as an env var, but it is still considered an input parameter when I do this. Unfortunately, there does not seem to be a real workaround at this time; we are just unable to take advantage of the cache on these jobs.

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by chensun** [comment]
> However, each run has a unique s3_path which we sync training checkpoints to during the job, which is the only way the jobs can finish successfully. 

I'm not quite following this part, how is `s3_path` used in the actual training step? Maybe some minimum pseudo code would help. Can you restructure your pipeline in a way that this is not an input to the training step?
