### ISSUE TITLE
[sdk] KFP Compiler doesn't propagate ParallelFor inputs

### ISSUE THREAD

**Issue by sabiroid** [kubeflow/pipelines#7204]
### Environment

*  KFP version:
1.8.2
*  KFP SDK version: 
1.8.2
*  All dependencies version:
```
kfp                      1.8.2
kfp-pipeline-spec        0.1.13
kfp-server-api           1.3.0
```

### Steps to reproduce

Try to compile this code:
```
import kfp
from kfp.components import func_to_container_op


@func_to_container_op
def produce_items() -> str:
    return '["first item", "second item"]'


@func_to_container_op
def do_nothing():
    pass


@kfp.dsl.pipeline()
def parallelfor_nested_pipeline_param_resolving(fname1: str, fname2: str):
    items_op = produce_items()
    items = items_op.output

    with kfp.dsl.ParallelFor(items) as outer_loop_item:
        with kfp.dsl.ParallelFor(items) as inner_loop_item:
            do_nothing()



if __name__ == '__main__':
    import kfp.compiler as compiler
    compiler.Compiler().compile(parallelfor_nested_pipeline_param_resolving,
                                __file__ + '.yaml')

```
It fails with a `KeyError: 'produce-items'` exception from within `fix_big_data_passing` function (not the actual bug location).

### Expected result

It should compile.

### Materials and Reference

The minimal code to reproduce is provided above. Based on my preliminary research, it seems that `compiler/compiler.py` simply doesn't have logic to recursively propagate inputs/outputs of `OpsGroup`s as it does for regular `Op`s except for several very specific cases, and `ParallelFor` is not among them. The exception it is failing the compilation with is not the actual bug location. It just surfaces the fact that certain parameter was not propagated through nested `OpsGroups`.

The code above can also be used as a unit test once the issue is fixed.

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by chensun** [comment]
This is KFP v1 code, which is currently moved to deprecated folder in master branch HEAD. We're currenlty focusing on the new v2 code. And based on a similar code in [this test file](https://github.com/kubeflow/pipelines/blob/5dcc6d9910372eee0b37cf31723910ed5f6fe98e/sdk/python/kfp/compiler_cli_tests/test_data/pipeline_with_loops_and_conditions.py#L92-L96), I'd assume this may not reproduce in v2. Please let me know if i'm wrong.

**Comment by sabiroid** [comment]
Yes, it looks like that
