### ISSUE TITLE
[bug] Bucket param missing when getting pipeline artifacts causing 403 in UI

### ISSUE THREAD

**Issue by mttcnnff** [kubeflow/pipelines#7214]
### What steps did you take

1. Navigated to view a pipeline in the UI
2. Clicked a component to view details
3. Clicked the "Visualizations" tab
4. Saw 403 responses in the network tab in browser:
![image](https://user-images.githubusercontent.com/17532157/151059268-868b1edc-68d7-4b26-88b1-8d4f38cff8da.png)
5. Port forwarded the `ml-pipeline-ui-artifact` service to `localhost:3000`:
```
kubectl port-forward svc/ml-pipeline-ui-artifact 3000:80
```
6. Copied request url which 403'd from screenshot:
```
https://test.kubeflow-platform.spotify.net/pipeline/artifacts/get?source=minio&namespace=hyperkube&bucket=&key=artifacts%2Ftaxi-example-pipeline-52s9w%2Ftaxi-example-pipeline-52s9w-1020558034%2Fmlpipeline-ui-metadata.tgz
```
7. Curl url with domain replaced by `localhost:3000` to target port-forwarded service, which resulted in error message:
```
curl localhost:3000/pipeline/artifacts/get\?source\=minio\&namespace\=hyperkube\&bucket\=\&key\=artifacts%2Ftaxi-example-pipeline-52s9w%2Ftaxi-example-pipeline-52s9w-1020558034%2Fmlpipeline-ui-metadata.tgz
Storage bucket is missing from artifact request%
```
8. Re-did Step 7 again, but filled in bucket with expected bucket name `kf-test-artifact-store`, which resulted in a successful response:
```
curl localhost:3000/pipeline/artifacts/get\?source\=minio\&namespace\=hyperkube\&bucket\=kf-test-artifact-store\&key\=artifacts%2Ftaxi-example-pipeline-52s9w%2Ftaxi-example-pipeline-52s9w-1020558034%2Fmlpipeline-ui-metadata.tgz -i
HTTP/1.1 200 OK
```

### What happened:
It doesn't seem that the `bucket=` query param is not being populated and I'm not sure why. We use Minio GCS Gateway for artifact storage and a Multi User install of KFP. Visualizations don't load as they seem to make the request described above on mount to the React DOM. In addition, component output strings are not loaded (unsure if that's related).

Visualizations not loading:
![image](https://user-images.githubusercontent.com/17532157/151062194-7c04632c-45b3-42b1-8c23-390ba8486b3c.png)

Component output strings not loading:
![image](https://user-images.githubusercontent.com/17532157/151062244-469ec00a-44d4-4aad-954a-6d8a94ded5ec.png)

### What did you expect to happen:
Visualizations to load:
![image](https://user-images.githubusercontent.com/17532157/151062410-ada5ebb4-c28c-4116-ac35-ec7a280eca44.png)

### Environment:

*  How do you deploy Kubeflow Pipelines (KFP)? 

Via argo app of apps based off of GCP Blueprints

*  KFP version: 1.3.0

*  KFP SDK version: 1.4.0

### Labels

/area backend 

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by zijianjoy** [comment]
Can you try using Kubeflow 1.4?

Note that the bucket information is specified in https://github.com/kubeflow/gcp-blueprints/blob/master/kubeflow/env.sh#L44, I am able to use this feature without problem. So there might be some bugs that have been fixed in Kubeflow 1.4.
