### ISSUE TITLE
[feature] Use Artifact metadata in a pipeline condition

### ISSUE THREAD

**Issue by burtenshaw** [kubeflow/pipelines#7250]
### Feature Area 

/area sdk

/area components

### What feature would you like to see?

Use the value of a metadata field from an Artifact in a  `dsl.Condition`. For example:

```python
with dsl.Condition(
    component_op.metadata["n_rows"] < 20,
    name="check-missing-vectors",
):
```
Or, allow for a component to return both a basic output and an Artifact output. Which would facilitate:

```python
with dsl.Condition(
    component_op.output < 20,
    name="check-missing-vectors",
):
```

### What is the use case or pain point?

I have been using the `dsl.Condition` to skip components based on the number of entries in a dataset. To do this, I used the Dataset's metadata attribute (`dataset.metadata["n_rows"]`). I then had to use another component to get the value and pass it to `dsl.Condition` and compare integers. This extra component seems unnecessary, and acting on metadata could make the condition logic really powerful.

### Is there a workaround currently?

As mentioned, I currently use a separate lightweight component that retrieves the metadata value.

```python
@component
def check_df_length_op(null_vectors: Input[Dataset]) -> int:
    return null_vectors.metadata["n_rows"]
```

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by chensun** [comment]
The feature request sounds reasonable.

**Comment by statmike** [comment]
I found another workaround that could be helpful to others.  The proposed feature is still preferred.

Have the component also output to a NamedTuple like:

```
define my_component(
    my_artifact: kfp.dsl.Output[kfp.dsl.Artifact]
) -> NamedTuple('outputs', [('state', str)]):

     from collections import namedtuple
     result = namedtuple('outputs', ['state'])

     my_artifact.metadata = dict(state = 'success')

     return result('success')
```

Then the `dsl.Condition` will work with:

```
component_op = my_component()

with kfp.dsl.Condition(component_op.outputs['state']  ==  'success'):

```
