### ISSUE TITLE
[bug] Artifacts and Lineage explorer don't work with KFP SDK V2

### ISSUE THREAD

**Issue by AlexandreBrown** [kubeflow/pipelines#7257]
### What steps did you take

1. Install Kubeflow 1.4
2. Create a pipeline with multiple artifacts type to illustrate the issue better (use Input[T] and Output[T])
3. Run pipeline
4. Navigate to the Artifacts page

### What happened:
- No  pipeline workspace and pipeline name is visible.
- All pipeline runs are grouped under this unnamed group
- Lineage explorer is not accessible/visible

![image-1.png](https://user-images.githubusercontent.com/26939775/152535918-a1fbb61f-94da-427c-a5b2-5b518e995dfc.png)

### What did you expect to happen:
I expect to get the same result as when using KFP SDK V1. Meaning we see all pipelines as groups and all artifacts under their respective pipeline group and we can access the lineage explorer.

### Environment:

*  How do you deploy Kubeflow Pipelines (KFP)? 
As part of Kubeflow manifest
*  KFP version: 
The one from Kubeflow 1.4 (backend is 1.7.1 I think)
*  KFP SDK version: 
1.8.6

### Labels

/area frontend
/area backend
/area sdk

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by zijianjoy** [comment]
Hello @AlexandreBrown , this is fixed in https://github.com/kubeflow/pipelines/pull/6989, you can try any 1.8.0 release candidate, for example: v1.8.0-rc.2 for the KFP backend.

**Comment by AlexandreBrown** [comment]
@zijianjoy Thanks, is this backend compatible with Kubeflow 1.4 ?

How would I upgrade my kfp backend ?

**Comment by AlexandreBrown** [comment]
Thanks @zijianjoy , could you explain how I can test the 1.8.0-rc.2 KFP backend with Kubeflow 1.4.1 manifest? Thanks
