### ISSUE TITLE
Pipeline deploy component does not support local model 

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/pipelines#726]
While I executed kubeflow Pipeline E2E TFX sample on local cluster, I found the TF-Serving cannot be started normally, checked details, that's caused by Pipeline deploy component does not support local model, so that the trained mode cannot be found after deployment pod started.

In the kubeflow section [Serve a local model using Tensorflow Serving](https://github.com/kubeflow/kubeflow/blob/master/components/k8s-model-server/Serve%20a%20local%20model%20using%20Tensorflow%20Serving.md), kubeflow support nfs pvc mode for trained mode storage, pipeline should also support that.

**Comment by jinchihe** [comment]
Created a PR for this, the enhancement will be useful for #721 . Thanks.

**Comment by paveldournov** [comment]
@jinchihe thanks!

@gaoning777 please take a look at the PR

**Comment by gaoning777** [comment]
Merged

**Comment by jinchihe** [comment]
Thanks @gaoning777
