### ISSUE TITLE
[bug] No _back_quoted_if_needed(model_name) in bigquery_predict_model_job

### ISSUE THREAD

**Issue by andrewmorrison-sky** [kubeflow/pipelines#7270]
### What steps did you take

Run google_cloud_pipeline_components.experimental.bigquery.BigqueryPredictModelJobOp job on pipeline. Pass in parameter model_name = "\`project.dataset.model\`" WITH BACKTICKS as I did on google_cloud_pipeline_components.experimental.bigquery.BigqueryEvaluateModelJobOp. Pipeline run fails due to error Syntax error: Invalid empty identifier at [1:32].

I can see that this is due to 

https://github.com/kubeflow/pipelines/blob/master/components/google-cloud/google_cloud_pipeline_components/container/experimental/gcp_launcher/bigquery_job_remote_runner.py#L393

where it is written as 'SELECT * FROM ML.PREDICT(MODEL \`%s\`, %s%s)'. Note that there is '\`%s\`', which means that if I pass in model_name with backticks already included there will be two backticks now

Where as in 

https://github.com/kubeflow/pipelines/blob/master/components/google-cloud/google_cloud_pipeline_components/container/experimental/gcp_launcher/bigquery_job_remote_runner.py#L599

It has 'SELECT * FROM ML.EVALUATE(MODEL %s%s%s)' % (
          _back_quoted_if_needed(model_name), input_data_sql, threshold_sql)

### What happened:
Pipeline job failed as I included backticks in model_name parameter

### What did you expect to happen:
That the pipeline would run successfully

### Environment:
kfp 1.8.11
google_cloud_pipeline_components 0.2.2

There just needs to be consistency between components, either backticks should not be included in both, or the _back_quoted_if_needed(model_name) should be done in both.

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by zijianjoy** [comment]
cc @IronPan
