### ISSUE TITLE
[frontend] args sort in ui doesn't follow py-func pipeline 

### ISSUE THREAD

**Issue by iuiu34** [kubeflow/pipelines#7294]
### Environment
Google vertex

### Deployment
If we define
```py
@component
def test(a: str, b: str, c: str, d:str) -> str:
    kwargs = locals()
    return str(kwargs)

@pipeline(
    name=name
)
def pipeline(
        a: str = 'a', b: str = 'b', c: str = 'c', d: str = 'd'):
    test_task = test(a, b, c,d)
```
Then the UI, doesn't display the args in order (a,b,c,d). In fact, the order seems pretty random (d,a,c,b). 
There's any reason behind this?

**Comment by zijianjoy** [comment]
Hello @iuiu34 , since it is Vertex Pipelines, you can file Google Support ticket to get more help. Closing it for now as it is not related to kubeflow pipelines.
