### ISSUE TITLE
[feature].need support for file list

### ISSUE THREAD

**Issue by robscc** [kubeflow/pipelines#7296]
### What feature would you like to see?

i want to merge multi files in one pipeline task,so i need support list[InputPath] such like this

### What is the use case or pain point?

if i have 50 tasks and output 50 files i need write a function with 50 params , it is painfull

### Is there a workaround currently?

i actually write 50 params function

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by chensun** [comment]
> i want to merge multi files in one pipeline task,so i need support list[InputPath] such like this

Can't you use `list[str]`?

**Comment by robscc** [comment]
> > i want to merge multi files in one pipeline task,so i need support list[InputPath] such like this
> 
> Can't you use `list[str]`?

so i put the content to str? that would make pod yaml too large to apply into k8s cluster
