### ISSUE TITLE
Reuse artifact in different pipeline/run

### ISSUE THREAD

**Issue by irabanillo91** [kubeflow/pipelines#7301]
My pipeline consists of three components: `dataset_preparation`, `training` and `evaluation`. The first one reads all files in my data lake and generates a dataset artifact (stored to S3) that is used in the following components. 

We keep adding new files to the datalake on a daily basis, so by default I want to train on all the data available. Therefore, I don't want to cache that component.

However, in some cases I might want to re-run that pipeline (with different hyperparameters for instance). To be able to compare runs, I'd like to run it on an existing dataset artifact. Thus I'd like to provide the artifact as an input parameter to the pipeline and skip the execution of `dataset_preparation`.

**Summary**: I'd like to be able to provide a dataset artifact as an optional input to the pipeline. If not provided, it will be created by the `dataset_preparation` component. If provided, `dataset_preparation` will be skipped. Is there any way to accomplish this? 

Thanks a lot in advance!

**Comment by chensun** [comment]
To reuse an existing artifact, you could use an `importer` that imports an artifact with a given path. For example,
https://github.com/kubeflow/pipelines/blob/a9f18fe985016ba9c1cbb24665d2b173797c91ec/sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_importer.py#L50-L55
This currently only works on Vertex Pipelines, but we will support it in Kubeflow Pipelines backend in the near future.

**Comment by irabanillo91** [comment]
Nice! So in order to skip the execution of the first component based on the given uri, I think something like this might work? 

```
@dsl.pipeline(name='pipeline-with-importer', pipeline_root='dummy_root')
def my_pipeline(dataset_uri: Optional[str]):
    with dsl.Condition(dataset_uri == ''):
        dataset_preparation_op = importer(artifact_uri=dataset_uri, artifact_class=Dataset)

    with dsl.Condition(dataset_uri != ''):
        dataset_preparation_op = dataset_preparation()

    train = train(dataset=dataset_preparation.outputs['artifact'])
    eval = eval(dataset=dataset_preparation.outputs['artifact'])
```

One thing that is slightly annoying is that the name of the artifact is hard-coded (see [here](https://github.com/kubeflow/pipelines/blob/a9f18fe985016ba9c1cbb24665d2b173797c91ec/sdk/python/kfp/v2/components/importer_node.py#L62)), so it's always set to ['artifact'](https://github.com/kubeflow/pipelines/blob/a9f18fe985016ba9c1cbb24665d2b173797c91ec/sdk/python/kfp/v2/components/importer_node.py#L26). **Couldn't we just pass the name as an argument to importer? And maybe have 'artifact' as default value.**

For my use case, that in turn forces me to set the output name for `dataset_preparation` to 'artifact as well. That component might generate multiple artifacts, so I'd rather use a descriptive name for each of them.

**Comment by AlexandreBrown** [comment]
@chensun Until it is supported in Kubeflow should we use simple `str` type for the dataset url and load it ourselves?

**Comment by irabanillo91** [comment]
> @chensun Until it is supported in Kubeflow should we use simple `str` type for the dataset url and load it ourselves?

I think it's not straight-forward, or at least I haven't been able to come up with an efficient way. I believe you can't convert the `str` to `Dataset` in the pipeline definition (that'd be executed at compilation time, not runtime). So the only way I can think of is inside the component. If the URI is passed, the component assigns it to the `Output[Dataset]` and skips the rest of the component logic. Something like:

```python
@component
def dataset_preparation_op(dataset_uri: str, dataset: Output[Dataset])
	if len(dataset_uri):
		dataset.uri = dataset_uri
        else:
		'Run dataset preparation logic'
```

However, I've set up Kubeflow to push the output artifacts to Minio after execution. So when this component ends, it will try to push `dataset.path` -> `dataset.uri`. Which will fail cause there's nothing at`dataset.path` within the container.

Therefore, I'd have to do the following:

```python
@component
def dataset_preparation_op(dataset_uri: str, dataset: Output[Dataset])
	if len(dataset_uri):
		dataset.uri = dataset_uri
		download_object(key=dataset.uri, path=dataset.path)
        else:
		'Run dataset preparation logic'
```

This would work, but it is extremely inefficient. Not only I'm launching a pod for just a simple cast, but now I have to download an artifact (which could be big), just to upload it immediately after and overwrite the original one with an exact copy of itself.

**Comment by AlexandreBrown** [comment]
@irabanillo91 I meant to simplify ditch the `Dataset` object all together and only use its path to download it in a Download Component then you share the PVC with other components and you're good to go. Other components can receive the local path as input.

**Comment by irabanillo91** [comment]
> @irabanillo91 I meant until we can specify that we don't want to upload a `Dataset` object I see 2 options :
> 
> 1. Use KFP SDK v1 and use `InputPath('Dataset')`
> 2. Ditch the `Dataset` object all together and only use a `my_dataset_path: str` to download it in a Download Component then you share the PVC with other components and you're good to go. Other components can receive the local path as input.

So it'd be something like this?

```python
DATASET_PATH = '/data/dataset.csv'

@component
def prepare_dataset_component(dataset_uri: str):
    if len(dataset_uri):
        download_object(key=dataset_uri, path=DATASET_PATH)
    else:
        import time
        dataset = dataset_preparation_logic() 
        with open(DATASET_PATH, "w") as f:
            f.write(dataset)
        upload_uri = f"s3://data-bucket/datasets/{time.strftime('%Y%m%d-%H%M%S')}.csv"
        upload_object(key=upload_uri, path=DATASET_PATH)

@component
def training_component():
    with open(DATASET_PATH, "w") as f:
        dataset = f.read()
    model = training_logic(dataset)

@pipeline(name="", description="", pipeline_root="")
def training_pipeline(dataset_uri: Optional[str]):
    prepare_dataset_op = prepare_dataset_component(dataset_uri=dataset_uri)
    training_op = training_component()
```

If `dataset_uri` is empty, it will run the component and store the dataset locally. If `dataset_uri` is provided instead, it downloads it and skips component execution. It just requires ensuring `DATASET_PATH` is visible across components.

Not ideal since it doesn't leverage Kubeflow abstractions for artifacts handling. It requires manually uploading/downloading dataset and setting up the the shared volume across components. But I guess it would get us going for now.

**Comment by grapefruitL** [comment]
You can split dataset_preparation into two components, the first one is used to create a pvc, and the second one accepts the url parameter to update the data in the pvc, so that the first component will only run once, which is equivalent to mounting the same One dataset, the second one is used to update the data, and then the same Pipeline can use different urls to achieve the purpose of expanding the dataset
