### ISSUE TITLE
[feature] Multi-user support for local standalone deployment

### ISSUE THREAD

**Issue by terrykong** [kubeflow/pipelines#7302]
### Feature Area

/area backend

### What feature would you like to see?

I would like to be able to run pipelines in specific namespaces that I have set up as a cluster administrator without having to deploy the full Kubeflow deployment.

### What is the use case or pain point?

Right now, I have followed [these instructions](https://www.kubeflow.org/docs/components/pipelines/installation/localcluster-deployment/) and everything works, but when I try to create a run from a pipeline func and specify a namespace, I see
```text
HTTP response body: {"error":"Validate experiment request failed.: Invalid input error: In single-user mode, CreateExperimentRequest shouldn't contain resource references.","code":3,"message":"Validate experiment request failed.: Invalid input error: In single-user mode, CreateExperimentRequest shouldn't contain resource references.","details":[{"@type":"type.googleapis.com/api.Error","error_message":"In single-user mode, CreateExperimentRequest shouldn't contain resource references.","error_details":"Validate experiment request failed.: Invalid input error: In single-user mode, CreateExperimentRequest shouldn't contain resource references."}]}
```

My use case is that I have an existing kubernetes cluster, and there are existing namespaces that everyone uses, so it would be convenient if I could just set the namespace and have that be accepted by the KFP backend.

### Is there a workaround currently?

Not that I am aware of.

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by zijianjoy** [comment]
Duplicate with https://github.com/kubeflow/pipelines/issues/6314.

Currently we don't have plan to support Multi-user feature in KFP standalone. Please use full Kubeflow if you want to benefit from Multi-user feature.
