### ISSUE TITLE
[sdk] PipelineParams are not serialized

### ISSUE THREAD

**Issue by MaxGrtz** [kubeflow/pipelines#7310]
### Environment

*  KFP SDK version: 1.8.11 (v2)

This is related to: #2206 
I also commented there, but I am not sure if adding a new issue is the better way to go.

I try to pass a dict containing pipeline parameters to a component (as shown by numerology in #2206 ), but the serialization of the pipeline params does not work.

```python
import fire
from utils.pipeline_cli import PipelineCLI

from kfp.v2 import dsl


@dsl.component(base_image="python:3.8-slim")
def print_op(params: dict):
    print(params)


@dsl.pipeline(
    name="test",
    description="test-pipeline.",
)
def pipeline(test: str = "test"):

    print_op(params=dict(foo=test))


if __name__ == "__main__":
    cli = PipelineCLI(pipeline=pipeline)
    fire.Fire(cli)
```
where PipelineCLI implements the compile and run subcommands.

even the following minimal example does not work.
```bash
python3 -c 'import kfp, json;print(json.dumps(kfp.dsl.PipelineParam("aaa")))'
```

both yield:

```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/opt/conda/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/conda/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/conda/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PipelineParam is not JSON serializable
```

**Comment by chensun** [comment]
This is expected. The basic building blocks for a pipeline are components and dsl features like `dsl.Condition`, `dsl.ParallelFor`, etc. You should avoid having arbitrary Python code like `dict(foo=test)`, they are non-containerized code that won't be executed at pipeline runtime. 
Consider using a component instead. For example:

```python
@component
def build_dict(key: str, value: str) -> dict:
    return dict(key=value)
```

**Comment by MaxGrtz** [comment]
@chensun thanks for the feedback.
This seems to me to be quite a limitation though.  
One would need to create such a component for every dict one wants to pass. 
a similar case is using string valued parameters in fstrings or concatenation. 
Moreover this clutters the graph with uninteresting operations. 

I agree that functional stuff has to happen inside of components, but combining parameters should be possible in the pipeline definition itself.
From how I understand things, kfp could serialize the parameters and replace them at runtime. At least from the issue I mentioned, this seems to be what was happening at some point.
