### ISSUE TITLE
[backend] Only 1 component gets logged into MLMD for some pipeline runs

### ISSUE THREAD

**Issue by calvinleungyk** [kubeflow/pipelines#7328]
### Environment
*  How did you deploy Kubeflow Pipelines (KFP)?
Full Kubeflow deployment
*  KFP version: 
1.5
*  KFP SDK version: 
1.6.0

### Steps to reproduce
After running several pipelines multiple times, only 1 component gets logged into MLMD for some pipeline runs. This is problematic as we can't query for pipeline artifacts reliably from MLMD.

### Expected result
For every run we expect all components log information into Kubeflow MLMD

### Materials and Reference

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by chensun** [comment]
In v1, the metadata logging is done in an async way. There could be a number of reasons if you have missing MLMD.

KFP 1.5 is relatively old, there's an chance there were bugs being fixed in the later version. Could you please try using the latest KFP release?

**Comment by casassg** [comment]
@chensun we are actually on 1.7.0 (aka default version for KF 1.4 distribution). 

Is there any pointers as to what and how KFP does log information into MLMD?
