### ISSUE TITLE
[backend] Some executions on Kubeflow MLMD have no values

### ISSUE THREAD

**Issue by calvinleungyk** [kubeflow/pipelines#7329]
### Environment
*  How did you deploy Kubeflow Pipelines (KFP)?
Full Kubeflow deployment
*  KFP version: 
1.5
*  KFP SDK version: 
1.6.0

### Steps to reproduce
Some output values of Kubeflow MLMD `mlmd.get_executions_by_context(context.id)` ([reference](https://www.tensorflow.org/tfx/ml_metadata/api_docs/python/mlmd/MetadataStore#get_executions_by_context)) just include the field names and no values, e.g.
```
custom_properties {
  key: "input:output_artifacts"
  value {
    string_value: "[\"saved_model_uri\", \"model_name\", \"user_data\"]"
  }
}
```

### Expected result
Output values of components should include the field names as well as the values

### Materials and Reference

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by chensun** [comment]
Can't tell if anything was wrong without seeing the pipeline/component code, it appears to me that the value here is a json serialized list of string.
