### ISSUE TITLE
[feature] When restoring an Experiment, add an option to restore all of its Runs

### ISSUE THREAD

**Issue by difince** [kubeflow/pipelines#7335]
### Feature Area

/area frontend 

### What feature would you like to see?
When restoring an experiment, a popup should show 3 options for the user to choose: `Cancel`, `Restore Experiment` and `Restore Experiment and All Runs`.
`Restore Experiment` needs to be highlighted because that is the default behavior.

### What is the use case or pain point?
see this [comment](https://github.com/kubeflow/pipelines/issues/5114#issuecomment-777735817)

### Is there a workaround currently?
Yes, currently the user could Restore the Experiment and then restore its Runs.

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by zijianjoy** [comment]
Hello @difince , thank you for filing this request. I am wondering what is the use case for restoring all the runs inside an experiment?

I am assuming the archived runs are something people don't usually visit. I might lack some knowledge on why people would want to massively restore all the runs.

**Comment by difince** [comment]
Hi @zijianjoy 
Could you take a look on these comments ( the first one is written by you) - [comment_1](https://github.com/kubeflow/pipelines/issues/5114#issuecomment-777735817) and [comment_2](https://github.com/kubeflow/pipelines/issues/5114#issuecomment-777932647)

I have already created a [PR](https://github.com/kubeflow/pipelines/pull/7147) about number 3: 

> 3) backend: Check whether a run is under archived experiment when [Unarchive API](https://www.kubeflow.org/docs/pipelines/reference/api/kubeflow-pipeline-api-spec/#operation--apis-v1beta1-runs--id-:unarchive-post) is called. If so, fail with error 400 (FAILED_PRECONDITION).

So as a follow-up, I was thinking to implement a number 2: 

> frontend: When restoring an experiment, popup should shows 3 options for user to choose: Cancel, Restore Experiment and Restore Experiment and All Runs, and highlight Restore Experiment because that is the default behavior.

If I understand the use case correctly - when the user wants to restore an Experiment - it would be nice if with a single click the user could restore the experiment & unarchive all of its runs.  
As a whole, this use case is marked as "good to have" - so if you think that it is not needed - I will close the issue

**Comment by difince** [comment]
I just checked the backed and I saw that there is no "bulk" archive/unarchive Runs endpoint.  
So if we decide to implement the feature - do do you think of adding such a "bulk" endpoints. 
```
/apis/v1beta1/runs/all:archive
/apis/v1beta1/runs/all:unarchive
```
WDYT ?

**Comment by zijianjoy** [comment]
Hello @difince , thank you for the reference. I tend to agree that this feature is good-to-have after [comment 2](https://github.com/kubeflow/pipelines/issues/5114#issuecomment-777932647). But if you are interested in implementing this API, then I am happy to support it. The API proposal sounds good to me:

```
/apis/v1beta1/experiments/{id}/runs:unarchive
```

**Comment by zijianjoy** [comment]
Hello @difince , I have got an update from the team yesterday. We start to suggest everyone making design proposal for review, for any API related changes. If you are going to work on this item, would you like to put together a doc to describe the new API? Then we can discuss it in the Kubeflow Pipelines Community meeting.
