### ISSUE TITLE
[release] Backend 1.8.1 tracker

### ISSUE THREAD

**Issue by chensun** [kubeflow/pipelines#7338]
Need to cherry-pick the following PRs to release-1.8 branch before making the official release:

- [x] https://github.com/kubeflow/pipelines/pull/7337

**Comment by zijianjoy** [comment]
Thank you Chen for handling this patch release! By learning from this experience, it is better to do a Kubeflow validation next time before cutting an official release. After this PR is merged, would you like to make a RC release for v1.8.1 first, which allows me to do a full validation on Kubeflow, then make an official release? Thank you!

**Comment by chensun** [comment]
> Thank you Chen for handling this patch release! By learning from this experience, it is better to do a Kubeflow validation next time before cutting an official release. After this PR is merged, would you like to make a RC release for v1.8.1 first, which allows me to do a full validation on Kubeflow, then make an official release? Thank you!

@zijianjoy 1.8.1-rc.0 is out: https://github.com/kubeflow/pipelines/releases/tag/1.8.1-rc.0
You can test it in full fledge Kubeflow now. Thanks!

**Comment by zijianjoy** [comment]
Confirming that this release candidate is working on Full Kubeflow, we can cut official version now. Thank you Chen!

**Comment by chensun** [comment]
Released: https://github.com/kubeflow/pipelines/releases/tag/1.8.1

**Comment by zijianjoy** [comment]
Appreciate the release! @chensun
