### ISSUE TITLE
Component Visualizations are not shown in Run Output

### ISSUE THREAD

**Issue by jayaswalayush** [kubeflow/pipelines#7339]
I have uploaded the metrics_visualization pipeline in the Kubeflow Console and when I invoke a run I am able to see the visualizations yet they are not seen in the run output

![image](https://user-images.githubusercontent.com/59866888/153585818-78748c5d-bfe7-4228-95d5-c79afdd5c13e.png)

![image](https://user-images.githubusercontent.com/59866888/153585857-cda2921e-48b9-4528-b568-e8866fffb993.png)

Do we need to make any configuration changes to show the visualizations in the Run Output ?

Used the below code to compile the pipeline :

    compiler.Compiler(mode=kfp.dsl.PipelineExecutionMode.V2_COMPATIBLE).compile(
        pipeline_func=pipeline, package_path=__file__.replace('.py', '.yaml')) 

As per the documentation : https://www.kubeflow.org/docs/components/pipelines/sdk/output-viewer/

The Run output tab shows the visualizations for all pipeline steps in the selected run. To open the tab in the Kubeflow Pipelines UI:

    Click Experiments to see your current pipeline experiments.
    Click the experiment name of the experiment that you want to view.
    Click the run name of the run that you want to view.
    Click the Run output tab.

**Comment by zijianjoy** [comment]
Hello @jayaswalayush , I have moved this issue to kubeflow pipelines repository. 

Indeed the `Run Output` for showing all visualizations is not implemented yet for V2. This is on our radar and we are planning to start working on it once we have built KFP v2.0.0-alpha.

**Comment by jayaswalayush** [comment]
Hello @zijianjoy , Any idea by when this issue will be resolved ? If we migrate to KFP v2.0.0-alpha then is this feature supported ?

**Comment by zijianjoy** [comment]
@jayaswalayush We are aiming to implement this feature in KFP v2.0.0-beta but we don't know exactly when yet. Please stay tuned!

**Comment by nkosteski** [comment]
Hey folks, I stumbled across this issue after having the same problems. However mine is with the 1.8.1 version of kubeflow (standalone) and with the v1 compiler. Were you experiencing the same issues with both the v1 and v2 compilers @jayaswalayush??

**Comment by zijianjoy** [comment]
For anyone who wants to use the Run Output feature: currently you can use KFPv1 because the feature is still available as is. 
![9TZqJtNyEPPxYPp](https://user-images.githubusercontent.com/37026441/171988236-8d8f2327-5b11-4e5a-930b-c604bdcaf4e0.png)

For KFPv2, we are working on providing the critical features so it gets GA first. Because the visualization is already available in side panel right now with KFP 2.0.0-alpha.2, the `Run Output` feature is nice to have but not necessarily blocking you from viewing the metrics. So we might have to attend to critical features first before attending to Run Output.

**Comment by jayaswalayush** [comment]
@zijianjoy : Sure thanks for the update but we would like to wait for this feature in KFP 2.0. Hope this feature is added soon

**Comment by Glorf** [comment]
Hi, I have the same issue as @nkosteski - after upgrading from Kubeflow Pipelines 1.4 to 1.8.5 I cannot see the Visualizations from the separate steps in "Run Output" view - even though they are properly rendered in step outputs. Pipeline is V1. Interesting phenomenon is, that "Visualization" generated by the last pipeline step is rendered properly - any previous visualizations are ommited. In 1.4 this feature was working properly so I suspect this is some kind of regression.

**Comment by zijianjoy** [comment]
Please start using Kubeflow Pipelines 2.0.0-alpha.X: The new metrics instruction is listed in https://www.kubeflow.org/docs/components/pipelines/v1/sdk/output-viewer/#v2-sdk-use-sdk-visualization-apis
