### ISSUE TITLE
[feature] System utilization for the pipeline and its steps

### ISSUE THREAD

**Issue by mikwieczorek** [kubeflow/pipelines#7341]
### Feature Area
Not sure

### What feature would you like to see?

Logging of system utilization to KFP metrics. Pipeline statistics of CPU/RAM/GPU usage over the course of pipeline run could be helpful in experiment comparison from performance point of view.
Example how the final results could look like when plotted nicely [wandb-example](https://wandb.ai/borisd13/char-RNN/runs/cw9gnx9z/system )

### What is the use case or pain point?

Monitoring resource utilization by the pipeline and by each step. Would allow to compare the runs in terms of performance/resource requirements. 

### Is there a workaround currently?

Manual logging or Prometheus? I encountered some Prometheus traces in the repo, but looks like deprecated or abandoned. 

If there is an existing solution to that problem, please let me know.

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by zijianjoy** [comment]
This is similar to https://github.com/kubeflow/pipelines/issues/6336. You can try deploying Prometheus and expose run metrics to there.
