### ISSUE TITLE
Best data versioning tool/framework with kfp for seamless integration.

### ISSUE THREAD

**Issue by vamshi-rvk** [kubeflow/pipelines#7356]
Hi, our team has started implementing kfp for mlops, and we are researching on best methods to data version. We primarily work on **images** but not limited to it. Which would be the best data versioning framework which works along with kfp with seamless integration and featureset.

**Comment by connor-mccarthy** [comment]
@vamshi-rvk, thanks for your question.

`kfp` does not natively support or integrate with any data versioning tools/frameworks, but [`dvc`](https://dvc.org/) is a popular open-source data version control system used in many MLOps workflows, including those that work with image data. I recommend you see if this service meets your needs.

**Comment by vamshi-rvk** [comment]
> @vamshi-rvk, thanks for your question.
> 
> `kfp` does not natively integrate with any data versioning tools/frameworks, but [`dvc`](https://dvc.org/) is a popular open-source data version control system used in many MLOps workflows, including those that work with image data. I recommend you see if this service meets your needs.

thanks for the respons.
