### ISSUE TITLE
XGBoost sample failure

### ISSUE THREAD

**Issue by gaoning777** [kubeflow/pipelines#736]
XGBoost sample fails recently because the default dataproc cluster version is bumped.

**Comment by gaoning777** [comment]
fixing it at https://github.com/kubeflow/pipelines/pull/735

**Comment by paveldournov** [comment]
@gaoning777 - the PR is merged, is the issue fixed? If so - please resolve the bug.

**Comment by gaoning777** [comment]
Yes, this is resolved. I'll close the issue.
