### ISSUE TITLE
[feature] Create parent directories of `output_component_file`

### ISSUE THREAD

**Issue by gabrielmbmb** [kubeflow/pipelines#7369]
### Feature Area

/area sdk

### What feature would you like to see?

I would like `output_component_file` file hierarchy to be created i.e. create parent directories if they do not exist. The example below raises `FileNotFoundError` because the parent directories do not exist.

**Code example:**
```python
from kfp.v2.dsl import pipeline, component


@component(
    output_component_file="build/components/test_component.yaml",
)
def test_component() -> None:
    ...


@pipeline(name="test-pipe")
def test_pipeline() -> None:
    task = test_component()


if __name__ == "__main__":
    from kfp.v2 import compiler

    compiler.Compiler().compile(
        pipeline_func=test_pipeline, package_path="build/pipeline.json"
    )

```

**Traceback:**
```plain
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    def test_component() -> None:
  File "/home/gmdev/.cache/pypoetry/virtualenvs/whatever-Ez6qCvWa-py3.8/lib/python3.8/site-packages/kfp/v2/components/component_decorator.py", line 104, in component
    return component_factory.create_component_from_func(
  File "/home/gmdev/.cache/pypoetry/virtualenvs/whatever-Ez6qCvWa-py3.8/lib/python3.8/site-packages/kfp/v2/components/component_factory.py", line 440, in create_component_from_func
    component_spec.save(output_component_file)
  File "/home/gmdev/.cache/pypoetry/virtualenvs/whatever-Ez6qCvWa-py3.8/lib/python3.8/site-packages/kfp/components/_structures.py", line 494, in save
    with open(file_path, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'build/components/test_component.yaml'
```

### What is the use case or pain point?

Kubeflow SDK will try to generate the component file definition automatically, so if the value of `output_component_file` contains directories that do not exist it will raise `FileNotFoundError`.

### Is there a workaround currently?

Yes, you can create the directory hierarchy just before `kfp` is imported to avoid the issue, but this solution does not seem very clean to me.

```python
from pathlib import Path

Path("build/components").mkdir(exist_ok=True, parents=True)

from kfp.v2.dsl import pipeline, component

...
```

Maybe it would be a good idea to add in the method below to check if the parent directories of `file_path` exist and if they don't, then create them.

https://github.com/kubeflow/pipelines/blob/6965dbac2faee0411fc0ca9565fd9a9d7ef8e2bf/sdk/python/kfp/components/_structures.py#L486-L495

I would love to start contributing to this repo, and if this feature proposal is finally accepted I would love to create a PR.

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by ji-yaqi** [comment]
Hi @gabrielmbmb, thank you and you can contribute this branch https://github.com/kubeflow/pipelines/tree/sdk/release-1.8 for SDK v1 changes. We might have some changes in v2 for this output file.
