### ISSUE TITLE
Tooltip in runtime graph can get stuck

### ISSUE THREAD

**Issue by rileyjbauer** [kubeflow/pipelines#738]
![image](https://user-images.githubusercontent.com/34456002/51779139-601c8b00-20ba-11e9-93ec-b7a64de1593a.png)

I've only seen this issue when a user is hovering over the `...` of a running pipeline, and the graph updates in a way that moves the parent node of the `...` (the TFX sample does this reliably in later steps, though it can sometimes be reproduced in the conditional example).

The issue seems to be the built-in handlers of the Tooltip not being fired.

A potential solution, as sort of mentioned [here](https://github.com/mui-org/material-ui/issues/11186), would be to create a wrapper `Icon` component that includes a Tooltip and the necessary mouse event handlers.

**Comment by Bobgy** [comment]
/close
I haven't seen this issue.
I think it's already fixed
