### ISSUE TITLE
Upgrade tensorflow and related components

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/pipelines#742]
Used the tensorflow and related components In the Pipeline, but seems the version is old, there are some new features and fixed some defects, it's better to upgrade tensorflow and component. 

```
tensorboard==1.6.0
tensorflow==1.6.0
tensorflow-transform==0.6.0
tensorflow-model-analysis==0.6.0 
```

Any plan or mechanismfor this? @jlewi  @IronPan  Thanks.

**Comment by gaoning777** [comment]
The current TFX components are updated when new versions offer features that are worth adding. Would you mind listing the new features in the new TFX releases that will enrich the functionalities of these TFX components? Thanks.

**Comment by jinchihe** [comment]
Thanks for your attention. @gaoning777 logged the ticket since I met some problems such as TFServing does not support my model unless upgreade TFServing (it has been upgraded). sorry It's hard to show the feature list but I noticed the TFX 0.13.0 has been released, we used old ones, personally we should have strategy to upgrade that.

**Comment by gaoning777** [comment]
The tfx components are currently using the latest TF version.
https://github.com/kubeflow/pipelines/tree/master/components/tfx
Feel free to reopen the issue.
