### ISSUE TITLE
[SDK] Pipeline runs web UI shows the wrong namespace

### ISSUE THREAD

**Issue by emenendez** [kubeflow/pipelines#7420]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)? As part of a full Kubeflow 1.4 install on GKE.
*  KFP version: 1.7.0, packaged with Kubeflow 1.4

### Steps to reproduce

1. Use the KFP Python SDK (for example, `create_run_from_pipeline_func()` to create a pipeline from a Jupyter Notebook. Use the `namespace` argument to create this pipeline run in a namespace that's not your own, but in which you are a collaborator.
2. The notebook will display a link to the "run details" page in the web UI of the following form: https://<cluster-domain>/pipeline/#/runs/details/<uuid>
3. Open the link.
4. The pipeline run details page is shown, but the namespace selector in the top-left corner shows your own default namespace, not the namespace in which the pipeline was actually run.

### Expected result

The pipeline run details should be shown, and the namespace selector in the top-left corner should show the namespace in which the pipeline was run (not your own namespace).

Thank you for your help debugging this issue!

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by zijianjoy** [comment]
Hello @emenendez , this is a known limitation we have right now, because SDK doesn't have the information about whether it is an KFP standalone or a full-fledged Kubeflow deployment. We don't have a clear idea yet about how to overcome this.

**Comment by emenendez** [comment]
Thanks so much for following up @zijianjoy!
