### ISSUE TITLE
[bug] connect to kfp method KF_PIPELINES_SA_TOKEN_PATH not working

### ISSUE THREAD

**Issue by hellobiek** [kubeflow/pipelines#7466]
### What steps did you take

I deployed a kubeflow in multi-user mode.
and now I try to connect to KFP with https://www.kubeflow.org/docs/components/pipelines/sdk/connect-api/
I use the PodDefault method, and use the variable of KF_PIPELINES_SA_TOKEN_PATH.

### What happened:

But try failed. 
and I clone the source code, but I can not see KF_PIPELINES_SA_TOKEN_PATH in the source code.

### What did you expect to happen:

KF_PIPELINES_SA_TOKEN_PATH  Is this PodDefault mothod still available?

### Environment:
KFP version: 1.2
KFP SDK version: kfp-1.8.11

**Comment by alexisgaziello** [comment]
[Temporary workaround](https://github.com/kubeflow/kubeflow/issues/6411#issuecomment-1080029132)

**Comment by grapefruitL** [comment]
just use following code, you will get pipeline info, no more additional params
```
import kfp
client = kfp.Client()
print(client.list_experiments())
```
