### ISSUE TITLE
[feature] allow upload_pipeline_version to create a pipeline with initial version

### ISSUE THREAD

**Issue by alexisgaziello** [kubeflow/pipelines#7494]
### Feature Area

/area backend
/area sdk

### What feature would you like to see?

My understanding is that at the moment, pipelines must be created using the method `upload_pipeline`.

If you create a new pipeline with `upload_pipeline_version` and tag it, for example, as v1.0.0:

```
client.upload_pipeline_version(
    pipeline_package_path="my-pipeline.yaml",
    pipeline_version_name="v1.0.0",
    pipeline_name="my-pipeline",
    description="my-pipeline description",
)
```

An ApiException (400) is raised:

```
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'x-powered-by': 'Express', 'date': 'Thu, 31 Mar 2022 15:00:15 GMT', 'content-length': '736', 'content-type': 'text/plain; charset=utf-8', 'x-envoy-upstream-service-time': '21', 'server': 'envoy'})
HTTP response body: {"error_message":"Please specify a pipeline id when creating versions.","error_details":"Please specify a pipeline id when creating versions.\ngithub.com/kubeflow/pipelines/backend/src/apiserver/server.(*PipelineUploadServer).UploadPipelineVersion\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/pipeline_upload_server.go:171\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2007\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2802\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1890\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357"}
```

### What is the use case or pain point?

We should be able to tag all pipeline versions, including the first one.

Right now `upload_pipeline` tags the initial version with the name of the pipeline.

**Pain points:**

1. Two different functions must be used to create and maintain a pipeline.
2. It would be nice to have the pipeline versions tagged from the start:

_Having:_ 

my-pipeline
 - v3.0.0
  - v2.1.0
  - v2.0.1
  - v2.0.0
  - v.1.0.0

_rather than:_

my-pipeline
  - v3.0.0
  - v2.1.0
  - v2.0.1
  - v2.0.0
  - my-pipeline

### Is there a workaround currently?

No, but pain points can be ignored.

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by bretttully** [comment]
Found a hack to get around this until it is fixed properly

```python
        kfp.compiler.Compiler().compile(pipeline_func, pipeline_path)

        pipeline = client.upload_pipeline(pipeline_path, pipeline_name=pipeline_name)
        pipeline_id = pipeline.id
        # delete the initial un-versioned "version"
        client.pipelines.delete_pipeline_version(pipeline_id)

        # create the versioned "version"
        pipeline_version = client.upload_pipeline_version(
            pipeline_path, pipeline_version_name=f"{pipeline_name}:{version}", pipeline_id=pipeline_id
        )
        pipeline_version_id = pipeline_version.id
```

**Comment by Doel10** [comment]
> Found a hack to get around this until it is fixed properly
> 
>         kfp.compiler.Compiler().compile(pipeline_func, pipeline_path)
> 
>         pipeline = client.upload_pipeline(pipeline_path, pipeline_name=pipeline_name)
>         pipeline_id = pipeline.id
>         # delete the initial un-versioned "version"
>         client.pipelines.delete_pipeline_version(pipeline_id)
> 
>         # create the versioned "version"
>         pipeline_version = client.upload_pipeline_version(
>             pipeline_path, pipeline_version_name=f"{pipeline_name}:{version}", pipeline_id=pipeline_id
>         )
>         pipeline_version_id = pipeline_version.id

> /reopen
> 
> This issue has not been fixed. The workaround does not work for v2 API due to the following error: AttributeError: 'V2beta1Pipeline' object has no attribute 'id'

Hello, I found a new workaround for v2 API:
```python
# Upload pipeline with undesired first version name
pipeline = kfp_client.upload_pipeline_from_pipeline_func(
    pipeline_func=pipeline_func,
    pipeline_name=pipeline_name,
    namespace=namespace,
)

# Get uploaded pipeline id by pipeline name
pipeline_id = kfp_client.get_pipeline_id(pipeline_name)

# List pipeline version names by pipeline id -> list with only one element
response = kfp_client.list_pipeline_versions(pipeline_id)

# Delete the undesired pipeline version
kfp_client.delete_pipeline_version(
    pipeline_id,
    response.pipeline_versions[0].pipeline_version_id,
)

# Re-upload the same pipeline specifying the desired version name
kfp_client.upload_pipeline_version_from_pipeline_func(
    pipeline_func=pipeline_func,
    pipeline_version_name="1.0.0",
    pipeline_name=pipeline_name,
)
```
