### ISSUE TITLE
[feature] Integrate withSequence loop with Kubeflow SDK

### ISSUE THREAD

**Issue by Sharathmk99** [kubeflow/pipelines#7504]
### Feature Area

/area sdk

### What feature would you like to see?

Loop feature with sequence will help to have better integration when user needs to create n number of identical steps using count number. 
For example, we run hyperparameter search and need to run n number of agents. With the current implementation of ParallelFor it can't be accomplished

### What is the use case or pain point?

Hyperparameter search and need to run n number of identical agents

### Is there a workaround currently?

Manually create yaml similar to https://github.com/argoproj/argo-workflows/blob/master/examples/loops-sequence.yaml

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by zijianjoy** [comment]
Hello @Sharathmk99 , currently this feature is not on our roadmap. Keeping this feature request open to collect more upvotes. We need a proper design if we want to support this feature.

**Comment by connor-mccarthy** [comment]
@Sharathmk99, this may work as a workaround if the iterable is known at compile-time:

```python
from kfp import compiler, dsl


@dsl.component
def print_text(msg: str):
    print(msg)


@dsl.pipeline(name='pipeline-with-loops')
def my_pipeline():
    items = ["a", "b", "c"]
    tasks = [print_text(msg=item) for item in items]

    for i, task in enumerate(tasks):
        if i == len(tasks) - 1:
            continue
        task.after(tasks[i + 1])
```

**Comment by Sharathmk99** [comment]
@connor-mccarthy Integration data is know runtime only from previous step.
Thanks for the suggestion. For now, I have added one extra step to take sequence number as input and output the list of sequence number length
