### ISSUE TITLE
Kubeflow 0.4 still include argo UI

### ISSUE THREAD

**Issue by gyliu513** [kubeflow/pipelines#753]
Kubeflow 0.4 still include argo UI but the UI cannot be opened. I think we are going to use Pipeline to replace argo, so why argo still exist? Can we remove argo ui from kubeflow?

```
root@gyliu-c11:~# kubectl get deploy -n kubeflow | grep argo
argo-ui                                                              1         1         1            1           9d
root@gyliu-c11:~# kubectl get svc -n kubeflow | grep argo
argo-ui                                                           NodePort    10.0.0.108   <none>        80:31376/TCP                    9d
```

**Comment by paveldournov** [comment]
@gyliu513 Argo is used as the orchestrator withink Kubeflow Pipelines. It could be good to keep the Argo UI available for lower level debugging of workflows.

**Comment by jlewi** [comment]
@gyliu513 What is the problem with the Argo UI that you are encountering?

**Comment by gyliu513** [comment]
Thanks @paveldournov , clear now. But the problem is that the argo UI cannot be opened and there is no logs from argo UI, how can I debug and check what is wrong with argo UI pod?

```
root@gyliu-dev1:~# kubectl logs -f argo-ui-7c9c69d464-2fkl2 -n kubeflow
>>> Empty here
```

**Comment by jlewi** [comment]
@gyliu513 Seems like an issue with Argo. it seems really odd that the Argo UI container isn't generating any logs. Is the container running? Is it crash looping?

**Comment by gyliu513** [comment]
@jlewi Argo ui is `Running` in my cluster but has no log and also the service cannot be accessed via NodePort.

```
root@gyliu-c11:~/cluster# kubectl get pods -n kubeflow | grep argo
argo-ui-7c9c69d464-2fkl2                                          1/1       Running             0          30d
```

```
root@gyliu-c11:~/cluster# kubectl get svc -n kubeflow | grep argo
argo-ui                                                           NodePort    10.0.0.108   <none>        80:31376/TCP                    30d
```

**Comment by vicaire** [comment]
@gyliu513, could you re-file this issue in the Kubeflow / Core repo as this seems independent from Kubeflow/pipelines. 

Closing this one. Please reopen if anything else is needed.
