### ISSUE TITLE
[feature] Exposing experiment name as a macro.

### ISSUE THREAD

**Issue by zygm0nt** [kubeflow/pipelines#7540]
### Feature Area

/area frontend
/area backend

### What feature would you like to see?

When in pipeline code I can use macros like {{workflow.annotations.pipelines.kubeflow.org/run_name}} or {{workflow.name}} to get those values, and potentially use them in some context, eg. passing to some component.

What I'd like to do is get current experiment name, that the run is assigned to. I'd like to pass it on to components for logging purposes.

Is this property exposed?

### What is the use case or pain point?

I would like to use that for consistent logging of run results. Now I need to copy and paste this value to a property in my pipeline.

### Is there a workaround currently?

Stated above - copy-pasting. 

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by chensun** [comment]
`{{workflow.annotations.*}}` and `{{workflow.name}}` aren't really part of KFP but Argo placeholders (https://argoproj.github.io/argo-workflows/variables/#global). And KFP experiments is not an Argo concept, so I don't think this is that easy to support.
