### ISSUE TITLE
Take a yaml format for pipelineSpec to submit them from UI to backend

### ISSUE THREAD

**Issue by zijianjoy** [kubeflow/pipelines#7571]
# Problem 

Support functionality to submit a pipeline template to backend, either from URL or a local file. 

# Materials
 
A list of sample pipelines are stored in https://github.com/kubeflow/pipelines/tree/master/sdk/python/kfp/compiler_cli_tests/test_data.

# User journey

1. Create a new Pipeline, select to upload from local folder. Successfully create a pipeline entity which is shown on Pipeline List page.
1. Create a new Pipeline, select to import from URL. Successfully create a pipeline entity which is shown on Pipeline List page.
2. Create a new Pipeline Version, successfully create a pipeline entity.
3. Select a V2 pipeline entity, you are able to see the ReactFlow UI (New DAG visualization). It should be able to show Execution, Artifact, Sub-DAG, and side panel.
4. Select a V2 pipeline entity, you are able to navigate to `Pipeline Spec` for a view of the yaml file.

**Comment by jlyaoyuli** [comment]
Except for `xgboost_sample_pipeline.yaml` pipeline, all of the testing pipelines were able to be uploaded via URL and local file. DAG visualization, side panel, and `Pipeline Spec` etc. are displayed as we expect.
