### ISSUE TITLE
[frontend] "clone recurring run" then changing the pipeline version resets run parameters to defaults

### ISSUE THREAD

**Issue by ckchow** [kubeflow/pipelines#7587]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?  terraform
*  KFP version: 1.4.0

### Steps to reproduce

Make sure you have a pipeline with more than 1 version.

Create a recurring run. Change some of the variables to non-default values. Start the run.

Then, clone the just-created recurring run. Change the pipeline version.

### Expected result

I think the values should remain what they were from the cloned recurring run and not be replaced by the defaults of the new pipeline version - creating a completely new recurring run with the new pipeline already provides that behavior.

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by Linchin** [comment]
I don't think "clone recurring run" passes the parameters. If you think this is a useful feature, feel free to open a feature request and describe your use case.
