### ISSUE TITLE
Allow users to configure pipeline root when creating new run.

### ISSUE THREAD

**Issue by zijianjoy** [kubeflow/pipelines#7598]
When creating new Run, user can specify a pipeline root location for artifact payload. PipelineRood definition is in https://www.kubeflow.org/docs/components/pipelines/overview/pipeline-root/.

Feature:
1. Show a `Checkbox` which asks user whether to set custom pipeline root.
2. If `Checkbox` is not checked, show nothing.
3. If `Checkbox` is checked, show an input box for accepting string value.
4. When creating new run, use the input box value to set `pipelineRoot` field inside `runtimeConfig`. If `Checkbox` is not checked, do not set `pipelineRoot` value.

**Comment by chensun** [comment]
I believe this is fixed. Let me know otherwise @jlyaoyuli
