### ISSUE TITLE
[feature] Support for "OR" condition on multiple filter predicates.

### ISSUE THREAD

**Issue by S-Mann** [kubeflow/pipelines#7602]
### Feature Area

/area backend

### What feature would you like to see?

Currently filter objects can have one or more query objects but they work with `AND` it would be great to somehow switch to `OR`  as well.
For example if you want to query [runs list API](https://www.kubeflow.org/docs/components/pipelines/reference/api/kubeflow-pipeline-api-spec/#operation--apis-v1beta1-runs-get) and get the multiple runs with different names you can't do it.
```json
{
  "predicates": [
    {
      "key": "id",
      "op": "IS_SUBSTRING",
      "string_value": "run1"
    },
    {
      "key": "id",
      "op": "IS_SUBSTRING",
      "string_value": "run21"
    }
  ]
}
```
And lets say you have 4 runs `["run1", "run11", "run21", "run51"]`
This filter on the API should return 3 runs `["run1", "run11", "run21"]`
As of now it returns no runs `[]`

### What is the use case or pain point?

Calling [runs list API](https://www.kubeflow.org/docs/components/pipelines/reference/api/kubeflow-pipeline-api-spec/#operation--apis-v1beta1-runs-get) multiple times (as many times as the number of predicates) is a bad design if we already have filtering why not refine it a little more and support multiple predicates with "OR" as well.

### Is there a workaround currently?

Call [runs list API](https://www.kubeflow.org/docs/components/pipelines/reference/api/kubeflow-pipeline-api-spec/#operation--apis-v1beta1-runs-get) multiple times (as many times as the number of predicates)

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by jlyaoyuli** [comment]
@S-Mann Thanks for your suggestion, it's a valid feature request. Feel free to contribute if you are interested!
