### ISSUE TITLE
Placeholder values (eg. {{workflow.status}} ) not working for v2 compiler & Vertex AI.

### ISSUE THREAD

**Issue by msvensson222** [kubeflow/pipelines#7614]
### Environment

*  KFP version:
`1.8.12`
*  All dependencies version:
`google-cloud-aiplatform==1.7.1`

### Steps to reproduce
I define a very simple pipeline with a single, image based, component, and compile it using the v2 compiler. After compiling it, I submit the pipeline job to Google Vertex AI. The input argument for the component is a placeholder, {{workflow.status}}. During execution on Vertex AI, the component log `{{workflow.status}}` as a string, but I was expecting `Succeeded`, or some other status value. Seems like the placeholder does not get replaced during execution.

Pipeline:
```python
from google.cloud import aiplatform
from google.cloud.aiplatform import pipeline_jobs
from kfp.v2.dsl import pipeline
from kfp.components import load_component_from_file

@pipeline(name="basic-pipeline",
          description="A pipeline with image based components",
          pipeline_root='gs://.../basic-pipeline')
def pipeline():
    step_0_spec = load_component_from_file('./comp_0.yaml')
    step_0_spec(status="{{workflow.status}}")


if __name__ == '__main__':
    from kfp.v2 import compiler
    compiler.Compiler().compile(
        pipeline_func=pipeline,
        package_path="pipeline.json"
    )

    from google.oauth2 import service_account
    credentials = service_account.Credentials.from_service_account_file("./gcp-sa-key.json")

    aiplatform.init(project='...',
                    location='europe-west4',
                    credentials=credentials)

    job = pipeline_jobs.PipelineJob(
        display_name="basic-pipeline",
        template_path="pipeline.json",
        enable_caching=False
    )

    job.run(service_account='...', sync=False)
```
Component (`comp_0.yaml` in the code above) specification:
```yaml
name: Step 0
description: Print inputs.

inputs:
  - {name: status, type: String}

implementation:
  container:
    image: eu.gcr.io/.../test_component:latest
    command: [
      python3,
      main.py,
      --status, { inputValue: status }
    ]
```
Component code:
```python
import logging
import argparse

def get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--status', type=str)
    return parser.parse_known_args()

def main(FLAGS):
    logging.basicConfig(level=logging.INFO)
    logging.info(f"Status: {FLAGS.status}")

if __name__ == '__main__':
    FLAGS, unparsed = get_args()
    main(FLAGS)
```

When executed on Vertex AI, the component logs "Status: {{workflow.status}}"
### Expected result
I was expecting the `status` within the component to log `Succeeded`,  or some other status value. This way of using placeholder works fine with the old compiler and not using Vertex AI. I am not sure if the problem is the new compiler or Vertex AI since I don't think I can use the old compiler for Vertex AI (only accepts json pipelines).

Complete compiled JSON pipeline (`pipeline.json`):
```json
{
  "pipelineSpec": {
    "components": {
      "comp-step-0": {
        "executorLabel": "exec-step-0",
        "inputDefinitions": {
          "parameters": {
            "status": {
              "type": "STRING"
            }
          }
        }
      }
    },
    "deploymentSpec": {
      "executors": {
        "exec-step-0": {
          "container": {
            "command": [
              "python3",
              "main.py",
              "--status",
              "{{$.inputs.parameters['status']}}"
            ],
            "image": "eu.gcr.io/.../test_component:latest"
          }
        }
      }
    },
    "pipelineInfo": {
      "name": "basic-pipeline"
    },
    "root": {
      "dag": {
        "tasks": {
          "step-0": {
            "cachingOptions": {
              "enableCache": true
            },
            "componentRef": {
              "name": "comp-step-0"
            },
            "inputs": {
              "parameters": {
                "status": {
                  "runtimeValue": {
                    "constantValue": {
                      "stringValue": "{{workflow.status}}"
                    }
                  }
                }
              }
            },
            "taskInfo": {
              "name": "step-0"
            }
          }
        }
      }
    },
    "schemaVersion": "2.0.0",
    "sdkVersion": "kfp-1.8.12"
  },
  "runtimeConfig": {
    "gcsOutputDirectory": "gs://.../basic-pipeline"
  }
}
```

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by chensun** [comment]
`{{workflow.status}}` and such are Argo variables (https://argoproj.github.io/argo-workflows/variables/#global), and Vertex Pipelines is not based on Argo, so it's by design that they won't work. 
On Vertex Pipelines, we provide a set of platform-agnostic placeholders. Here're some examples: https://github.com/kubeflow/pipelines/blob/6296c18c7c9ec37489f36efc2cd121a800155da6/sdk/python/kfp/compiler_cli_tests/test_data/pipeline_with_placeholders.py#L27-L46

**Comment by msvensson222** [comment]
Okay, I understand @chensun . Do you have any idea of how one would get the status of the run within a component, as asked in [this StackOverflow question?](https://stackoverflow.com/questions/72094768/how-to-get-the-status-of-a-pipeline-run-within-a-component-running-on-vertex-ai?noredirect=1#comment127610264_72094768) Would really appreciate your insight, since this is a key aspect of allowing us to move our infrastructure serverless on VertexAI. Thanks in advance!

**Comment by ysk24ok** [comment]
Hello @chensun, I've also encountered this problem.
What's the platform-agnostic alternative of `{{workflow.status}}`? It seems [kfp/dsl/\_\_init\_\_.py](https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/dsl/__init__.py) doesn't have that.
WIthout this, we can't migrate our in-house component which uses `{{workflow.status}}` to Vertex AI.
Thank you for your help in advance.

I'd say you should reopen this issue as it's not solved yet.

**Comment by RyuSA** [comment]
@ysk24ok @msvensson222 
FYI, there is a special input variable `PipelineTaskFinalStatus` for `ExitHandler`. This variable contains the workflow status, resource name, error code and so on.
ref: https://www.kubeflow.org/docs/components/pipelines/v2/author-a-pipeline/pipelines/#dslexithandler

You may want the workflow status at the end of the pipeline. Instead of  `{{workflow.status}}`, you can use `PipelineTaskFinalStatus.state` on the ExitHandler executed at the end of the pipeline to get the pipeline status.
But I think `PipelineTaskFinalStatus` is only available for Python-based component, not for YAML component.
