### ISSUE TITLE
Using API to manage pipeline in Multi-User mode

### ISSUE THREAD

**Issue by grapefruitL** [kubeflow/pipelines#7616]
### What feature would you like to see?

use [api ](https://www.kubeflow.org/docs/components/pipelines/reference/api/kubeflow-pipeline-api-spec/)to manage pipeline in Multi-User mode

### What is the use case or pain point?

in our dev group, kubeflow is managed by engineers who are not familiar with python, they need to manage pipelines with pipeline api and yaml file generated from our data scientists

### Is there a workaround currently?

now our data scientists are working without any mlops tools

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by jlyaoyuli** [comment]
@grapefruitL What do you mean by "manage"? What is your use case?

**Comment by grapefruitL** [comment]
@jlyaoyuli thank you for your reply.
Deploying, using and maintaining kubeflow requires some k8s knowledge that our data scientists don't have
Now I only have the way
Our data scientists are only responsible for writing the yaml of the pipeline and observing the running results, not for the startup of the pipeline
