### ISSUE TITLE
[frontend] "Failed to retrieve logs" in finished pipelines.

### ISSUE THREAD

**Issue by drozzy** [kubeflow/pipelines#7617]
Sometimes I click on old pipelines to check their logs and get the error "Failed to retrieve logs":

![Screenshot from 2022-04-26 14-02-00](https://user-images.githubusercontent.com/140710/165363496-8b8516c4-23e6-4e3a-915c-232833ef9c07.png)

**Comment by ji-yaqi** [comment]
We automatically recycle the pods 24 hours after creation. You can try to re-run the pipeline to get logs. Please re-open this issue if you have any more questions.

**Comment by drozzy** [comment]
This was failing on microk8s install of kubeflow pipelines.
Once I switched to https://k3ai.github.io/docs/tutorials/kubeflow/ everything is great.

**Comment by danielschulz** [comment]
We also experience the very same issue, once our cluster Auto-Scales. 

All logs are gone and NOT read from our mirror in MINIO (interface of KFP to access S3) / AWS S3 (physical location).

**Comment by AxoyTO** [comment]
Facing the same. Is there a way to increase or remove the 24h retention period? Logs disappear from the UI but they stay on the S3 bucket.
