### ISSUE TITLE
[backend] Unable to upload a specific testing pipeline via URL

### ISSUE THREAD

**Issue by jlyaoyuli** [kubeflow/pipelines#7652]
For the user journey test of upload pipeline. The testing pipeline https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/compiler_cli_tests/test_data/xgboost_sample_pipeline.yaml was not able to be uploaded via URL.

**Comment by zijianjoy** [comment]
Potential cause: This pipeline contains OptionalInput.

**Comment by chensun** [comment]
> Potential cause: This pipeline contains OptionalInput.

Then this should have been resolved via https://github.com/kubeflow/pipelines/issues/8716. @Linchin to verify

**Comment by Linchin** [comment]
Just tried using beta.0, it's still not working.
