### ISSUE TITLE
[frontend] Failed to display a pipeline execution graph: "No graph to show"

### ISSUE THREAD

**Issue by pahask8** [kubeflow/pipelines#7655]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
Manifests [files](https://github.com/kubeflow/pipelines/tree/master/manifests/kustomize) from

*  KFP version: 2.0.0-alpha.1 (worked well in 1.7.0, first observed in 1.8.1).

### Steps to reproduce
1. Pipeline was uploaded to Kubeflow using Kubeflow Python SDK (version 1.8.1)
2. Run a pipeline which is displaying as 2168 lines yaml file in Kubeflow UI.
3. Once completed, Kubeflow UI shows a message: "No graph to show" instead of pipeline execution graph. Please see a screenshot attached.

<img width="1507" alt="no_graph" src="https://user-images.githubusercontent.com/16062064/166611772-7de4eef3-6e05-4192-afdc-de0d3682507d.png">

### Expected result

Kubeflow UI shows a pipeline execution graph.

### Materials and Reference

There was a similar error described in https://github.com/kubeflow/pipelines/issues/4289.

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by jlyaoyuli** [comment]
Hello @pahask8 , would you mind providing the example you used for this run, so that we can reproduce the result for this issue. In addition, we would like to ask if you were using v1 mode or v2 mode for compiling the pipeline definition.

**Comment by pahask8** [comment]
Hello @jlyaoyuli, thank you for quick update. I used v1 mode for compiling the pipeline. I can try to provide an example of this , can you please suggest, will the complete yaml work for you? Thanks

**Comment by jlyaoyuli** [comment]
Hello @pahask8 , yes the complete yaml works. Can provide a simplified version of pipeline (yaml file)? Thank you :) Noted: We think that the potential reason for this error is because we upgrade node from 12 to 14, which doesn't allow using Buffer API on the Browser side. https://github.com/kubeflow/pipelines/blob/a8a3b93aded13c9c8f5c9207dd1c233488aaf29f/frontend/src/lib/Utils.tsx#L391

**Comment by pahask8** [comment]
Hello @jlyaoyuli, please find the attached pipeline file. Please note I masked all sensitive data there. Hope that helps. Thank you!
[pipeline.yaml.zip](https://github.com/kubeflow/pipelines/files/8756506/pipeline.yaml.zip)

**Comment by dsiegel** [comment]
It's definitely something to do with compressedNodes. The problem starts happening as soon as the pipeline gets big enough to trigger Argo to start using the compressedNodes method of storing the run state.

Any update on when this will be addressed?

**Comment by thenovices** [comment]
Also upping this as something that is impacting our team. We're downgrading KFP because this issue makes the latest versions of KFP unusable for us.
