### ISSUE TITLE
[backend] Output on GKE giving unclear error related to "container not found"

### ISSUE THREAD

**Issue by aronchick** [kubeflow/pipelines#7676]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
Just deployed directly from kubeflow manifests

*  KFP version: 
1.4.1, 1.5, 2.0.0 alpha

*  KFP SDK version: 
1.8.12

### Steps to reproduce
Upload the following yaml as a pipeline - run it: https://gist.github.com/aronchick/25d6fca71df0ef86846c40bec5cbc2c3

### Expected result

Runs correctly.

### Actual

```
This step is in Error state with this message: failed to save outputs: Error response from daemon: No such container: 77f84d932adba6d4b35769fbba02bfab4b48cf2128985f3c105d3744978abf9f
```
(The container name changes every time, the container name does not appear in the yaml)

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by aronchick** [comment]
Just to be clear, this may be a GKE thing. I have an EKS deployment and it seems to run fine. But the error is very confusing regardless.

**Comment by aronchick** [comment]
For what it's worth, I solved it by changing how I deployed kubeflow from manifests. You can read more about it here - https://github.com/SAME-Project/same-project/issues/126

HOWEVER, I think this is still a bug in KFP. The error message should be clearer what's going wrong - not being able to find a container can't be correct.

**Comment by aronchick** [comment]
It appears this error has been touched on here - https://github.com/kubeflow/pipelines/issues/1471 - but, i'd propose the core issue is that the error message is not helpful. We should work on that.

**Comment by zijianjoy** [comment]
This is probably due to Emissary executor not being used in the latest version of Kubernetes cluster.

As an overall point of view, I am looking for advice about what kind of error message it should show instead of the current message. Open to contributor or discussion about how to provide a proper error message.

**Comment by aronchick** [comment]
Genuinely unclear what the error is. If emissary has not been setup correctly, can we detect it? Could we output that error?

**Comment by zijianjoy** [comment]
Follow instruction in https://www.kubeflow.org/docs/components/pipelines/installation/choose-executor/ to detect workflow executor setup.
