### ISSUE TITLE
[bug] Pipeline component CI failure - ERROR: No matching distribution found for google-cloud-storage==2.2.1

### ISSUE THREAD

**Issue by shrinath-suresh** [kubeflow/pipelines#7686]
### What steps did you take

We have updated the pytorch samples present in kubeflow pipelines to work with latest version of kserve (kserve v2 protocol). The PR(https://github.com/kubeflow/pipelines/pull/7615) has been blocked due to the CI failure

```
ERROR: Could not find a version that satisfies the requirement google-cloud-storage==2.2.1 (from versions: 0.20.0, 0.21.0, 0.22.0, 0.23.0, 0.23.1, 1.0.0, 1.1.0, 1.1.1, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.4.0, 1.5.0, 1.6.0, 1.7.0, 1.8.0, 1.9.0, 1.10.0, 1.11.0, 1.11.1, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 1.13.2, 1.13.3, 1.14.0, 1.14.1, 1.15.0, 1.15.1, 1.15.2, 1.16.0, 1.16.1, 1.16.2, 1.17.0, 1.17.1, 1.18.0, 1.18.1, 1.19.0, 1.19.1, 1.20.0, 1.21.0, 1.22.0, 1.23.0, 1.24.0, 1.24.1, 1.25.0, 1.26.0, 1.27.0, 1.28.0, 1.28.1, 1.29.0, 1.30.0, 1.31.0, 1.31.1, 1.31.2, 1.32.0, 1.33.0, 1.34.0, 1.35.0, 1.35.1, 1.36.0, 1.36.1, 1.36.2, 1.37.0, 1.37.1, 1.38.0, 1.39.0, 1.40.0, 1.41.0, 1.41.1, 1.42.0, 1.42.1, 1.42.2, 1.42.3, 1.43.0, 1.44.0, 2.0.0)
ERROR: No matching distribution found for google-cloud-storage==2.2.1

```

### What happened:

Looks like the change in google-cloud-storage package version is causing an error and its blocking the current PR.

### What did you expect to happen:

All the CI runs should pass

### Environment:

*  How do you deploy Kubeflow Pipelines (KFP)? 

*  KFP version: 

*  KFP SDK version: 

### Labels

/area components

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by shrinath-suresh** [comment]
@chensun 
pulled the latest changes from master. build failing with following error

```
ERROR: Could not find a version that satisfies the requirement cachetools==5.0.0 (from versions: 0.0.0, 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 0.5.0, 0.5.1, 0.6.0, 0.7.0, 0.7.1, 0.8.0, 0.8.1, 0.8.2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 2.0.0, 2.0.1, 2.1.0, 3.0.0, 3.1.0, 3.1.1, 4.0.0, 4.1.0, 4.1.1, 4.2.0, 4.2.1, 4.2.2, 4.2.3, 4.2.4)
ERROR: No matching distribution found for cachetools==5.0.0
```

**Comment by shrinath-suresh** [comment]
cc: @zijianjoy @james-jwu @theadactyl

**Comment by chensun** [comment]
@shrinath-suresh, the issue with google-cloud-storage no long exists, but I found a few other issues and sent a couple of PRs that should fix the test failure, should be resolved by this week.
