### ISSUE TITLE
[Inquiry]Is there a way to display a figure when running pipeline?

### ISSUE THREAD

**Issue by yangyang919** [kubeflow/pipelines#7697]
We have deployed one kubeflow pipeline which has several components, fetch data, preprocess, train model, etc. We are wondering whether in one of these components, we can draw a figure using plt.plot() on dataframe object, output this figure and then in Experiments UI, we can view this figure in Run Output section?

I am thinking about embed figure into HTML, and output html, but failed. Anyone has similar experiences or suggestions? Thanks a lot!

**Comment by yangyang919** [comment]
Tried this:
In component code, output one html file:

    metadata = {
        'outputs': [{
            'storage': 'inline',
            'source': '<h1>Hello, World!</h1>',
            'type': 'web-app',
        }]
    }
    print(" html path ", args.html)
    with open(args.html, 'w') as f:
        json.dump(metadata, f)

Then in component.yaml file, define output type:

```outputs:
- {name: MLPipeline HTML, type: HTML, description: 'Figure'}
```


But no idea why in Run Output Tab UI, hello world does not show up

**Comment by zijianjoy** [comment]
Hello @yangyang919 , The `Run Output Tab` UI is currently broken. You can click the node which generates HTML visualization, it will open side panel. Click `Visualization` tab in the side panel, you should be able to see HTML visualization. https://www.kubeflow.org/docs/components/pipelines/sdk/output-viewer/#single-html-file

**Comment by yangyang919** [comment]
Hi @zijianjoy , thanks for answering!

I am able to display a simple HTML, but still could't display a figure output by component. I think it's the way how I do it, could you take a look and give some suggestions?

    myPlot = myDataframe.plot().get_figure()
    myPlot.savefig('my_plot')
    metadata = {
        'outputs': [
        {
            'type': 'web-app',
            'storage': 'inline',
            'source': "<img src='/tmp/outputs/MLPipeline_UI_metadata/data/my_plot.png'/>",
        }]
    }
    visualization_output = namedtuple('VisualizationOutput', [
        'mlpipeline_ui_metadata'])
    with open(args.html, 'w') as out_file:
        json.dump(metadata, out_file)

**Comment by yangyang919** [comment]
thanks @zijianjoy , I figured out a way to display dataframe plot into html. So I close this ticket accordingly.

**Comment by TranThanh96** [comment]
@yangyang919 can you share your solution ? I am struggling with visualizations, a lot of bugs

**Comment by gpotti** [comment]
@yangyang919 Could you please explain on how you solved this particular issue? I'm also trying to do visualization of image results of a classification problem

**Comment by pbasov** [comment]
Since this is top result in Google:
@TranThanh96 @gpotti Wanna see something bonkers?

Define `Output[HTML]`
```
@dsl.component(packages_to_install=['numpy', 'minio', 'matplotlib'])
def get_data(dataset_images: Output[Dataset], 
             dataset_labels: Output[Dataset],
             dataset_test_images: Output[Dataset],
             dataset_test_labels: Output[Dataset],
             dataset_example: Output[HTML]):```

Write base64 of an image to html:
```    
    plt.imshow(training_images[0], cmap='gray')
    plt.xlabel(f"Training sample, number: {training_labels[0]}")
    tmpfile = BytesIO()
    plt.savefig(tmpfile, format="png")
    tmpfile.seek(0)
    encoded = base64.b64encode(tmpfile.read()).decode("utf-8")

    html = f"<img src='data:image/png;base64,{encoded}'>"
    with open(dataset_example.path, 'w') as f:
        f.write(html)
```

@zijianjoy It's crazy that you're asking an ML engineer to do this to simply display a PNG in KFP UI.
