### ISSUE TITLE
[feature] Allow Graph Based XY Data as Artifact Type in UI + SDK (v2)

### ISSUE THREAD

**Issue by yribeiro** [kubeflow/pipelines#7701]
### Feature Area

/area frontend

### What feature would you like to see?

The feature would essentially allow us log XY and metrics for a graph along with titles in the metadata. This would be similar functionality for the ROC curve where we log a `List[float]` for TPR and FPR. 

In the Pipelines UI I think this would be adding support for an additional Viewer like `XYMetricsViewer` or similar. In the SDK, it would be a matter of implementing `Metric` subtype like `RegressionMetric` or something, with the ability to log XY data in metadata.

### What is the use case or pain point?

These graphs a super useful in comparing metrics evolution over time. Currently we are only able to log single scalar metrics / tabular data, which is a big pain point when comparing experiment runs. 

### Is there a workaround currently?

We currently log data to tensorboard, which requires a separate pod instance and we have to manually keep track of the pipeline run linked to the graph that is produced. As a result, developers do not really log many visualisations, which hinders progress. 

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by zijianjoy** [comment]
We are planning to implement Run Comparison feature, which can achieve the same goal without introducing new Artifact type.

**Comment by AlexandreBrown** [comment]
Should be covered by https://github.com/kubeflow/pipelines/issues/8794
