### ISSUE TITLE
[question] All possible status codes of Kubeflow Runs

### ISSUE THREAD

**Issue by yarnabrina** [kubeflow/pipelines#7705]
We have a [`streamlit`](https://streamlit.io/) app, which triggers a pipeline run based on user inputs. We regularly check the status of the submitted run and inform the run state in the UI using the following function.

```python
import kfp

def get_run_status(run_id: str) -> str:
    client = kfp.Client()

    run_details = client.get_run(run_id)
    run_status = getattr(getattr(run_details, "run"), "status")

    return run_status
```

We have decided to add some colour formatting based on the current run status. For that, we need to know all possible status codes, but we are not able to find anything comprehensive at [`kfp.dsl` documentation](https://kubeflow-pipelines.readthedocs.io/en/stable/source/kfp.dsl.html).

So far in our pipelines, we came across `Succeeded` and `Failed`, and rarely `Error`. We don't know if there are more or not, so some guidelines for this will be super helpful.

/area backend
/area sdk
/kind question

**Comment by connor-mccarthy** [comment]
Hi, @yarnabrina. You can find the set of possible status values in the `run.proto` definition here: https://github.com/kubeflow/pipelines/blob/0932905ff58a5effae510a9eeb30bbe86fc3adf1/backend/api/run.proto#L254-L255.

Please re-open if you have any other questions on this topic.
