### ISSUE TITLE
[bug] CrashLoopBackOff deploying standalone KFP to custom namespace

### ISSUE THREAD

**Issue by markgeejw** [kubeflow/pipelines#7714]
### What steps did you take

Deploy kfp standalone to on-premise k8s cluster, with custom namespace described in [docs](https://www.kubeflow.org/docs/components/pipelines/installation/standalone-deployment/#change-deployment-namespace). 

### What happened:

ml-pipeline-viewer-crd pod goes into CrashLoopBackOff with logs:
```
I0513 06:52:22.650451       1 main.go:96] Starting controller for the Viewer CRD
E0513 06:52:22.651800       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.5/tools/cache/reflector.go:167: Failed to watch *v1.Service: failed to list *v1.Service: services is forbidden: User "system:serviceaccount:<custom-ns>:ml-pipeline-viewer-crd-service-account" cannot list resource "services" in API group "" in the namespace "kubeflow"
E0513 06:52:22.652079       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.5/tools/cache/reflector.go:167: Failed to watch *v1.Deployment: failed to list *v1.Deployment: deployments.apps is forbidden: User "system:serviceaccount:<custom-ns>:ml-pipeline-viewer-crd-service-account" cannot list resource "deployments" in API group "apps" in the namespace "kubeflow"
E0513 06:52:22.652104       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.5/tools/cache/reflector.go:167: Failed to watch *v1beta1.Viewer: failed to list *v1beta1.Viewer: viewers.kubeflow.org is forbidden: User "system:serviceaccount:<custom-ns>:ml-pipeline-viewer-crd-service-account" cannot list resource "viewers" in API group "kubeflow.org" in the namespace "kubeflow"   
```

### What did you expect to happen:

Successful deployment with custom namespace

### Environment:

On-premise k8s cluster

*  How do you deploy Kubeflow Pipelines (KFP)? 
Standalone deployment using kustomize
*  KFP version: 
1.8.1
*  KFP SDK version: 
NA

### Anything else you would like to add:
The problem comes from the deployment still looking at the namespace `kubeflow` even though we specified a difference namespace in the relevant `kustomization.yaml` files.

After some digging, I found that the bug is because in [`backend/Dockerfile.viewercontroller`](https://github.com/kubeflow/pipelines/blob/c8a18bde299f2fdf5f72144f15887915b8d11520/backend/Dockerfile.viewercontroller#L43), the env var is actually `NAMESPACE` not `MINIO_NAMESPACE` as in [`manifests/kfp/base/pipeline/ml-pipeline-viewer-crd-deployment.yaml`](https://github.com/kubeflow/pipelines/blob/c8a18bde299f2fdf5f72144f15887915b8d11520/manifests/kustomize/base/pipeline/ml-pipeline-viewer-crd-deployment.yaml#L25). I am writing a PR to fix this.

### Labels

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by markgeejw** [comment]
Created PR #7715

**Comment by chensun** [comment]
Hi @markgeejw what is the k8s engine you're using with your on-prem cluster, and secondly in which namespace did you deploy minio?
After you changed the manifest, does it work for you?

**Comment by markgeejw** [comment]
I’m using kubeadm with containerd and calico. I deployed to a namespace with my own name, and yes after changing the manifest it worked.
