### ISSUE TITLE
[bug] ERROR1040: too many connections

### ISSUE THREAD

**Issue by jlouea** [kubeflow/pipelines#7716]
### What steps did you take

I have a use case that calling kubeflow backend service to get run id in a very high rps: about 200. However, I got HTTP 400 on my proxy. After looking into the root cause, I found error messages in ml-pipeline pod.

### What happened:
InternalServerError: Failed to get run: Error 1040: Too many connections. The detailed error:
```
github.com/kubeflow/pipelines/backend/api/go_client._RunService_GetRun_Handler
	bazel-out/k8-opt/bin/backend/api/linux_amd64_stripped/go_client_go_proto%/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:1289
google.golang.org/grpc.(*Server).processUnaryRPC
	external/org_golang_google_grpc/server.go:966
google.golang.org/grpc.(*Server).handleStream
	external/org_golang_google_grpc/server.go:1245
google.golang.org/grpc.(*Server).serveStreams.func1.1
	external/org_golang_google_grpc/server.go:685
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1333
I0513 08:47:18.882841       1 interceptor.go:29] /api.RunService/GetRun handler starting
I0513 08:47:18.883430       1 interceptor.go:29] /api.RunService/GetRun handler starting
I0513 08:47:18.884657       1 error.go:218] Error 1040: Too many connections
InternalServerError: Failed to get run: Error 1040: Too many connections
github.com/kubeflow/pipelines/backend/src/common/util.NewInternalServerError
	backend/src/common/util/error.go:142
github.com/kubeflow/pipelines/backend/src/apiserver/storage.(*RunStore).GetRun
	backend/src/apiserver/storage/run_store.go:182
github.com/kubeflow/pipelines/backend/src/apiserver/resource.(*ResourceManager).GetRun
	backend/src/apiserver/resource/resource_manager.go:277
github.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).GetRun
	backend/src/apiserver/server/run_server.go:43
github.com/kubeflow/pipelines/backend/api/go_client._RunService_GetRun_Handler.func1
```

### What did you expect to happen:
with 100 rps, the pipeline works fine. I hope it still works with high rps.

### Environment:

*  How do you deploy Kubeflow Pipelines (KFP)? 

*  KFP version: 0.7 

*  KFP SDK version: 0.7

### Anything else you would like to add:

I did some research, and some suggested set `db.SetMaxOpenConns(NUM)` ([reference](https://stackoverflow.com/questions/28135580/golang-mysql-error-1040-too-many-connections))

### Labels

/area backend 

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by connor-mccarthy** [comment]
Thanks for raising this and sorry to hear you're having issues. Unfortunately, KFP 0.7 is not currently supported.

Please consider trying KFP 1.8.1 and let us know if the issue exists in the 1.8 distribution.

**Comment by jlouea** [comment]
@connor-mccarthy thank you for the suggestions. We'll try.
