### ISSUE TITLE
[backend] cannot enter chroot for container named "main" error with Kubeflow Pipelines version 1.8.1

### ISSUE THREAD

**Issue by Priyanka4pc** [kubeflow/pipelines#7717]
### Describe the issue
* We are getting a random error PID error when using version 1.8.1 of the Standalone deployment of Kubeflow pipelines with both emissary and pns executors.   
* All the runs where this errors comes, the clone of the run or retry works completely fine. So a guess is that this error only comes when a new image is being pulled. 
* This error comes in the wait container of the pod and is not always reproducible but we got it by running the demo pipeline of Kubeflow and it comes randomly in one of the steps. 

### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
Step 1:  
minikube start --auto-update-drivers=true --cpus='4' --delete-on-failure=true --disk-size='20g' --driver='hyperkit' --kubernetes-version='stable' --memory='10g'
Step 2:  
export PIPELINE_VERSION=1.8.1
kubectl apply -k "github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=$PIPELINE_VERSION"
kubectl wait --for condition=established --timeout=60s crd/applications.app.k8s.io
kubectl apply -k "github.com/kubeflow/pipelines/manifests/kustomize/env/platform-agnostic-emissary?ref=$PIPELINE_VERSION"

### Steps to reproduce
* kubectl port-forward $(kubectl get pods -n kubeflow | grep ml-pipeline-ui | cut -d' ' -f1) 31380:3000 -n kubeflow &    
* Run [Demo] XGBoost - Iterative model training 

Error Message:
> This step is in Error state with this message: Error (exit code 1): cannot enter chroot for container named "main": no PID known - maybe short running container 
  
Logs of the containers of pod with this error
[container_wait.log](https://github.com/kubeflow/pipelines/files/8686671/container_wait.log)
[container_main.log](https://github.com/kubeflow/pipelines/files/8686672/container_main.log)
[container_init.log](https://github.com/kubeflow/pipelines/files/8686673/container_init.log)

### Expected result
Pipeline runs successfully

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by chensun** [comment]
Hi @Priyanka4pc, we don't officially support minikube deployment, maybe you can try one of the these local deployment choices: https://www.kubeflow.org/docs/components/pipelines/installation/localcluster-deployment/

**Comment by AdityaSoni19031997** [comment]
The same also happens when we use kind nonetheless

**Comment by jeesmon** [comment]
@AdityaSoni19031997 any luck with this error? I'm getting same error on kind.

**Comment by jeesmon** [comment]
It worked for me when I switched to `Emissary Executor` as mentioned here: https://www.kubeflow.org/docs/components/pipelines/v1/installation/choose-executor/#emissary-executor
