### ISSUE TITLE
Can pipeline components provide http services within the cluster?

### ISSUE THREAD

**Issue by grapefruitL** [kubeflow/pipelines#7727]
Can pipeline components provide http services within the cluster? For example, I have a data processing and analysis pipeline, which is designed to run for 1 hour. Other pods in the cluster access this pipeline through http requests to process the data and obtain results. After 1 hour, the pipeline runs and analyzes the request data it receives to obtain the analysis results.

**Comment by grapefruitL** [comment]
Now I can create the pipeline with the following code:
```
import kfp
import kfp.dsl as dsl
import kfp.components as comp

@dsl.pipeline(
   name='test demo pipeline',
   description='test demo pipeline'
)
def prepare_data_pipeline():
    
    start_service_op = kfp.dsl.ContainerOp(
        'start_service', 
        'kserve:v1',
        'python', 
        ['/root/test.py', '1']).add_pod_label('app','hello-pod')
 
pipeline_func = prepare_data_pipeline
kfp.Client().create_run_from_pipeline_func(pipeline_func, arguments={})
  
```  
Also create a service to access the component:
```
apiVersion: v1
kind: Service
metadata:
  name: hello-pod
  namespace: test
spec:
  ports:
  - port: 8889
    targetPort: 8889
    protocol: TCP
    nodePort: 30010
  type: NodePort
  selector:
    app: hello-pod
```
But you will get a warning:

> /opt/conda/lib/python3.8/site-packages/kfp/dsl/_container_op.py:1257: FutureWarning: Please create reusable components instead of constructing ContainerOp instances directly. Reusable components are shareable, portable and have compatibility and support guarantees. Please see the documentation: https://www.kubeflow.org/docs/pipelines/sdk/component-development/#writing-your-component-definition-file The components can be created manually (or, in case of python, using kfp.components.create_component_from_func or func_to_container_op) and then loaded using kfp.components.load_component_from_file, load_component_from_uri or load_component_from_text: https://kubeflow-pipelines.readthedocs.io/en/stable/source/kfp.components.html#kfp.components.load_component_from_file
>   warnings.warn(

I wonder if there is a way other than ContainerOp? It seems that other ways to create components cannot be used in conjunction with services

**Comment by connor-mccarthy** [comment]
Thanks, @grapefruitL. As indicated in the error message, `ContainerOp` is deprecated. Have you tried creating the same component using YAML and reading in using `kfp.components.load_component_from_file`?

FYI, the KFP v2 SDK will eventually have a `ContainerOp` alternative with similar functionality, though this is not yet available.

**Comment by grapefruitL** [comment]
Solved, after using `load_component_from_file` to generate `op `variables, you need to call the `add_pod_label `method
