### ISSUE TITLE
[bug] The pipeline UI shows that the pipeline has been running, but I have turned it off

### ISSUE THREAD

**Issue by ErraticO** [kubeflow/pipelines#7731]
### What steps did you take

When the scheduled task is executed, I delete it and turn off the automatically generated run.

### What happened: 
The pipeline UI shows that the pipeline has been running, but I have turned it off

### What did you expect to happen:
The UI interface should show the status of closing rather than running all the time

### Environment:

*  How do you deploy Kubeflow Pipelines (KFP)? 
1. Set pipeline scheduled task in Experiments
2. After the scheduled task takes effect, the pipeline execution is terminated
3. Delete scheduled task, A new pipeline run will be regenerated
4. Immediately terminate the pipeline running, and a bug occurs at this time
*  KFP version: 
kfp==1.6.6
python:3.8.6
*  KFP SDK version: 

### Labels

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by ErraticO** [comment]
![image](https://user-images.githubusercontent.com/41106127/168552621-9ca15333-8a04-46a6-9da9-2446be5eaed1.png)

**Comment by connor-mccarthy** [comment]
cc/ @zijianjoy

**Comment by zijianjoy** [comment]
The already started step will continue running, only the subsequent step will be terminated. Does it answer your question?

**Comment by ErraticO** [comment]
It is still going on without stopping, as if it were to be executed forever.

**Comment by zijianjoy** [comment]
@ErraticO What is your kubernetes version and what is your KFP backend version? You might need to upgrade to a newer version of KFP (like KFP Backend 1.8) to give it another try.
