### ISSUE TITLE
Use the ROC output viewer to visualize a precision recall curve.

### ISSUE THREAD

**Issue by alan-krumholz** [kubeflow/pipelines#774]
I was able to do it fine but the product expects the axis in the chart (that you define in the schema) to be called fpr and tpr which makes the visualization confusing even if it gets to display the right data.
It'll be good to be able to set the names of the axis with other values for use cases like this.

**Comment by yebrahim** [comment]
It seems like generalizing the ROC graph into a generic XY plot will help in that case then? How about supporting a metadata schema allows specifying the different axes labels and the name of the value? This would cover ROC curve, would it also be enough for PR curve? Are there any similar curves we can use such a schema for?

**Comment by alan-krumholz** [comment]
yes the dataset for PR curve would be very similar to the one of ROC curve:
Precision, Recall, Thresholds

As long as we could customize the names for the first two columns (and display those on the chart) this should work.

Thanks!

**Comment by rileyjbauer** [comment]
@ajchili is this covered by the work you've been doing?

**Comment by ajchili** [comment]
@rileyjbauer this is not directly covered by my current work. However, we could make an extensible graph visualization which does not specify the names of parameters to allow visualizations such as a PR Curve and ROC Curve to be generated by a single, generic, graph visualizer.

**Comment by Bobgy** [comment]
@jingzhang36 Can you take a look at this?

**Comment by ajchili** [comment]
@jingzhang36 we should be able to edit https://github.com/kubeflow/pipelines/blob/719f4074be4bffd9ef6b9e200fdf4f2cff837822/backend/src/apiserver/visualization/types/roc_curve.py#L37-L63
to something such as
```Python
if not variables.get("is_generated", False):
    # Assumes that csv files have headers included (but my knowledge of pandas is rusty).
    dfs = []
    files = file_io.get_matching_files(source)
    for f in files:
        dfs.append(pd.read_csv(f))

    df = pd.concat(dfs)
    df = pd.DataFrame({"x": df[variables.get("x", "x")], "y": df[variables.get("y", "y")], "labels": df[variables.get("labels", "labels")]})
else:
    # Load data from generated csv file.
    df = pd.read_csv(
        source,
        header=None,
        names=[variables.get("x", "x"), variables.get("y", "y"), variables.get("labels", "labels")]
    )
```

This would allow custom 2D line graphs to be created. We can also add support for lambdas should they be necessary.
