### ISSUE TITLE
[backend]  cache-server's behavior on pod annotations cause pipeline to fail

### ISSUE THREAD

**Issue by we10710aa** [kubeflow/pipelines#7757]
When cache-server find correspond result in cache, it remove the init container of pipeline pod and keep all annotations. This will cause pod with following annotations  fail to be created.

``container.apparmor.security.beta.kubernetes.io/init=runtime/default``

The kube-apiserver will reject the create api call because it can't find corresond container in pod manifest.

The error message will be like this
```
[metadata.annotations[container.apparmor.security.beta.kubernetes.io/init]: Invalid value: "init": container not found
```

Behavior like this will cause any cluster that enable ``PodSecurityPolicy`` ( or any cluster that use this annotation for security reason )  to fail to run the same pipeline more than once, because this annotation is added automatically.

### Environment

*  How did you deploy Kubeflow Pipelines (KFP)? Using Kubeflow manifest

*  KFP version:  v1.5
* Kubernetes v1.23

### Steps to reproduce
1. Install KF Pipeline on cluster that enable PodSecurityPolicy
2. Run any example pipeline twice, and the error will appear like below

<img width="1688" alt="image" src="https://user-images.githubusercontent.com/16017026/169294925-f34d4931-6a9e-4ef0-817e-0df3bd0cc393.png">

### Expected result
The pipeline can run any number of times

### Materials and Reference

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by chensun** [comment]
Hi @we10710aa, you can try disable caching following this instruction to block yourself. https://www.kubeflow.org/docs/components/pipelines/overview/caching/#disablingenabling-caching

And in the WIP KFP v2, we have a different implementation, maybe it will be compatible with your use case.
