### ISSUE TITLE
create_component_from_func vs func_to_container_op

### ISSUE THREAD

**Issue by thethiny** [kubeflow/pipelines#7794]
I don't seem to understand the behavior behind these two functions.
I have been using `create_component_from_func` for all of my pipelines, however all tutorials and guides I'm seeing online use `func_to_container_op` and the docstrings don't explain them enough (They both say `Converts a Python function to a component and returns a task`).
Can anyone elaborate on this as the documentation doesn't include much info about this?

**Comment by wenboown** [comment]
What is the difference between create_component_from_func and func_to_container_op?
They are equivalent, but func_to_container_op is deprecated in v2 of the SDK. For more information on what has been deprecated see here:
https://github.com/kubeflow/pipelines/issues/6133

Credit: Alexandre Brown in Community Slack

ref: https://journal.arrikto.com/kubeflow-tips-tricks-january-2022-238fde12f7d0

**Comment by zijianjoy** [comment]
We are moving away from `func_to_container_op` in KFPv1, we suggest to use `create_component_from_func` in KFPv1.

For KFPv2, we are moving away from both approaches above. We recommend using `@component` decorator in KFPv2. 

Feel free to reopen this issue if you need more help.

**Comment by zijianjoy** [comment]
cc @connor-mccarthy Do we support `extra_code` in `create_component_from_func`?

**Comment by connor-mccarthy** [comment]
`create_component_from_func` does not support `extra_code`, though for some use-cases you can work around this by using `subprocess.call` or `os.system` to execute a subprocess within the Python code itself

**Comment by casassg** [comment]
This won't work as we need to add extra code _before_ the function in order to avoid issues on default values from the parsed function.

**Comment by connor-mccarthy** [comment]
@casassg, I see. Yes, unfortunately that's one of the use-cases where this workaround will not work. The other approach is creating a containerized component that implements this.

I suspect this is a fairly common use-case. If you feel strongly about having `extra_code` functionality, please feel free to open a feature request issue requesting that this be included in v2, then the community can upvote it.
