### ISSUE TITLE
Give generated exit-handler a more special name

### ISSUE THREAD

**Issue by rileyjbauer** [kubeflow/pipelines#78]
If an exit handler is specified in the DSL, the compiler currently uses a bit of a hack to ensure that it is always called before the pipeline terminates: an extra DAG is added to the compiled yaml that is named something like `exit-handler-1` which is the only task of the entrypoint DAG, and wraps all other steps within the pipeline (they are tasks within the exit handler's DAG).

This works alright as a workaround, but it clutters the UI in a rather unhelpful way, so we currently hide this node by checking if the name starts with "exit-handler".

This is potentially problematic as it's not the most unlikely name for a user to pick, so maybe something like "__exit-handler" would be better until a better solution is found to the exit handler problem.

**Comment by vicaire** [comment]
The Argo yaml should have the information describing what the exit handlers are. Could the UI extract this information from the Argo yaml instead of relying on some special convention with the DSL? Since users will be able to specify the yaml without the DSL, this seems needed.

**Comment by rileyjbauer** [comment]
IIRC, the problem is that the DSL and Argo don't have exactly the same conception of exit handlers. Argo supports exit handlers via the `onExit` key which just points to a template to run after the workflow has otherwise ended, but as I mentioned above, the DSL explicitly wraps the entire pipeline in an exit handler in the form of a DAG template. I do not know exactly why this is done

**Comment by vicaire** [comment]
Thank you for the clarification @rileyjbauer.

**Comment by rileyjbauer** [comment]
@gaoning777 can you comment on why the DSL implements exit-handling like this?
