### ISSUE TITLE
Add an option to run Pipeline from local notebooks.

### ISSUE THREAD

**Issue by swiftdiaries** [kubeflow/pipelines#780]
By authenticating using load_kube_config instead of running from in-cluster notebooks, we could make the local iteration loop faster.

**Comment by gaoning777** [comment]
@Ark-kun you and Bradley were discussing running the notebook on the local machine, correct? any progress?Thanks

**Comment by vicaire** [comment]
The CLI supports this but reuses some K8 go libraries to match all the authentication method of kubectl. It would indeed be great to do the same from the Python SDK.

**Comment by Ark-kun** [comment]
> By authenticating using load_kube_config instead of running from in-cluster notebooks, we could make the local iteration loop faster.

AFAIK, Bradley has fixed that (made it possible to submit runs from a local notebook). Is this broken now?

**Comment by swiftdiaries** [comment]
Right now, I think you can do something like `client = kfp.Client(host='localhost:8080/pipeline')` to authenticate to the cluster. But that requires a port-forward on the localhost.

**Comment by gaoning777** [comment]
@hongye-sun has merged PRs to support various authorization mode. 
Feel free to reopen it.
