### ISSUE TITLE
[bug] Failed to clone a Run started by recurring Run

### ISSUE THREAD

**Issue by jkchang** [kubeflow/pipelines#7810]
### What steps did you take

1. Create a "hello-world" pipeline using: https://raw.githubusercontent.com/kubeflow/pipelines/master/backend/test/resources/hello-world.yaml
2. Create a recurring run using pipeline "hello-world"
3. Wait after a Run is started and completed.
4. Clone the Run, and click Start button, it fails with error:

### What happened:
 Run creation failed
{"error":"Failed to create a new run.: InvalidInputError: unknown template format: pipeline spec is invalid","code":3,"message":"Failed to create a new run.: InvalidInputError: unknown template format: pipeline spec is invalid","details":[{"@type":"type.googleapis.com/api.Error","error_message":"unknown template format","error_details":"Failed to create a new run.: InvalidInputError: unknown template format: pipeline spec is invalid"}]}
### What did you expect to happen:

It should start a new run from the clone.

### Environment:

*  How do you deploy Kubeflow Pipelines (KFP)? 

*  KFP version: 

*  KFP SDK version: 

### Labels

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by Linchin** [comment]
Would you mind sharing which version that you are using?

**Comment by jkchang** [comment]
version 1.8.1

**Comment by Bud-ds** [comment]
In the process of upgrading Kubeflow 1.2 to 1.5 on GCP
Environment:
How do you deploy Kubeflow Pipelines (KFP)? Our platform team deploys with a customized GCP procedure.
Version:
kfp==1.8.12
kfp-pipeline-spec==0.1.14
kfp-server-api==1.8.1

**Comment by vvnpan** [comment]
any updates on this @Linchin? We have the same issue running on pipelines version: 1.8.3, kubeflow: 1.6.0. 
Also clicking on the recurring run pipeline, it shows error for graph

**Comment by shivaga9esh** [comment]
Hello  @tleewongjaro-agoda - The missing objects(apiVersion, kind) were present in the initial pipeline yaml but when creating an experiment run from the given pipeline, those objects are going away when navigating through pipeline version link. Ultimately these clone run and unable to view the graph issues are still present. Any guidance please ? we are using kubelfow verion: 1.6. Do you think we need to install patch ? kindly suggest

**Comment by zijianjoy** [comment]
Looks like we are missing `apiVersion` and `kind` from the `GetRun` API. @Linchin Can you take a look at why is this happening for recurring run?

**Comment by zijianjoy** [comment]
Looks like the issue was fixed in KFP 2.0.0-beta.0. You can upgrade to the latest version to try.

**Comment by shivaga9esh** [comment]
Thanks much @zijianjoy i will give a try and let you know asap.

**Comment by tleewongjaro-agoda** [comment]
@zijianjoy Tried upgrading to 2.0.0-beta.0 and this issue is resolved. Thanks.

**Comment by shivaga9esh** [comment]
@zijianjoy @tleewongjaro-agoda @jkchang - As suggested, I have upgraded the KFP and corresponding KFP-Server-API but now i see a different error which is more problematic to all pipelines :(  Can you please suggest ? Our team generates YAML files to be able to upload to kubeflow as a pipeline. Error and sample code snippet below...

Error: 'kfp.dsl' has no attribute 'ContainerOp'
------
Sample code:
-------------
from kfp import dsl 
op =  dsl.ContainerOp(
      name=name,
      image='{0}.azurecr.io/{1}:{2}'.format(self._REGISTRY_NAME, self._IMAGE_NAME, version_tag),
      command=[ "python", self._WRAPPER_SCRPT],
      arguments=[
        '--env', self._ENV,
        '--sql file', sqlfile,
        '--whse', wh,
        '--loglevel',"INFO"
        ]
      )

**Comment by zijianjoy** [comment]
You might want to still use KFP SDK 1.8 for now. Because ContainerOp is replaced in KFP SDK v2. Another approach is to migrate your pipeline code to KFP v2. Reference: https://kubeflow-pipelines.readthedocs.io/en/2.0.0b9/source/dsl.html?h=containerop#module-kfp.dsl
