### ISSUE TITLE
[feature] Add authorization to both ReadArtifacts and ReportMetrics endpoints

### ISSUE THREAD

**Issue by difince** [kubeflow/pipelines#7818]
### Feature Area

</area backend >

### What feature would you like to see?
Ensure that the user has permission to call  [ReadArtifacts](https://github.com/kubeflow/pipelines/blob/665d826b38b10f559c4ac105f37fb24c17ef5561/backend/src/apiserver/server/run_server.go#L303) and [ReportMetrics](https://github.com/kubeflow/pipelines/blob/665d826b38b10f559c4ac105f37fb24c17ef5561/backend/src/apiserver/server/run_server.go#L278) 

`ReadArtifacts` and `ReportMetrics` could lavarage an existsing function - [`canAccessRun`  ](https://github.com/kubeflow/pipelines/blob/665d826b38b10f559c4ac105f37fb24c17ef5561/backend/src/apiserver/server/run_server.go#L359) to enable authorization.

### What is the use case or pain point?
 Currently, both [ReadArtifacts](https://github.com/kubeflow/pipelines/blob/665d826b38b10f559c4ac105f37fb24c17ef5561/backend/src/apiserver/server/run_server.go#L303) and [ReportMetrics](https://github.com/kubeflow/pipelines/blob/665d826b38b10f559c4ac105f37fb24c17ef5561/backend/src/apiserver/server/run_server.go#L278) does not check if the user has permissions to call these endpoints.

### Is there a workaround currently?
No. 
A security issue is exposed

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by zijianjoy** [comment]
Related: https://github.com/kubeflow/pipelines/issues/4649
