### ISSUE TITLE
Design Run Comparison page for V2

### ISSUE THREAD

**Issue by zijianjoy** [kubeflow/pipelines#7840]
# Description

Design the Run Comparison page for KFPv2. The main discussion points are:

1. What are critical user journeys?
2. How to handle compatibility with KFPv1?
3. What metrics does Run Comparison page compare? (for example: parameters, metrics, etc.)
4. How to compare metrics? (Side-by-side, combined chart, pick-and-choose comparison, etc.)
5. How to design the layout so that Run Comparison page is both easy-to-use and optimized for performance?

**Comment by zpChris** [comment]
This page has now been implemented; these questions are answered in detail in the internal design doc, and next steps are provided via GitHub Issues ([[1]](https://github.com/kubeflow/pipelines/issues/8129), [[2]](https://github.com/kubeflow/pipelines/issues/8130), [[3]](https://github.com/kubeflow/pipelines/issues/8131), [[4]](https://github.com/kubeflow/pipelines/issues/8132), [[5]](https://github.com/kubeflow/pipelines/issues/8133)) and on an internal "next steps" doc.
