### ISSUE TITLE
Compare various metrics for V2 Run Comparison page

### ISSUE THREAD

**Issue by zijianjoy** [kubeflow/pipelines#7841]
# Description

1. List the types of metrics we want to compare
2. Implement an efficient strategy to fetch these metrics
3. Provide functionality for users to adjust UI (For example: dropdown/checkbox for better comparison)

**Comment by zpChris** [comment]
This page has now been implemented, and these points are elaborated on in detail in the internal design doc as well as PR descriptions. We do not provide much functionality for users to adjust UI, though this will be an option if the parallel-coordinate plot is implemented for Scalar Metrics or Parameters.
