### ISSUE TITLE
Show parameters comparison for V2 Run Comparison page

### ISSUE THREAD

**Issue by zijianjoy** [kubeflow/pipelines#7842]
# Description

1. Retrieve parameters from backend
2. Determine the strategy about how to show parameter comparison
3. Scalability: How to handle comparison when number of parameters is very high?

**Comment by zpChris** [comment]
The parameter comparison was implemented in https://github.com/kubeflow/pipelines/pull/8105, and a separate issue for scalability was raised at https://github.com/kubeflow/pipelines/issues/8131. For reference, the Parameters section uses an analogous organization algorithm to the KFPv1 Run Comparison page, and the Parameters are already fetched alongside the run list.
