### ISSUE TITLE
Can you pass TypedDicts to components or pipelines?

### ISSUE THREAD

**Issue by cgebbe** [kubeflow/pipelines#7845]
### Feature Area

/area components

### What feature would you like to see?

Given the following code example: https://github.com/kubeflow/pipelines/issues/3412#issuecomment-1147075404 , it would be nice to pass `aws_config` not as a simple dictionary, but instead as a `TypedDict`. More exactly, we can split this up into:
- passing TypeDicts in between components
- passing TypeDicts as a parameter to pipeline to validate the parameter very early

### What is the use case or pain point?

Small typos can delay development.

### Is there a workaround currently?

Yes, simply use simpler dicts.

**Comment by zijianjoy** [comment]
Hello @cgebbe , can you describe how the `TypedDict` support will help you check typo?

/assign @connor-mccarthy
