### ISSUE TITLE
Deploy a new version of a model

### ISSUE THREAD

**Issue by clausagerskov** [kubeflow/pipelines#7859]
### Feature Area
As per this issue in the vertex-ai-samples repo, 
https://github.com/GoogleCloudPlatform/vertex-ai-samples/issues/585
Vertex AI has model versions numbers that increase when manually importing models with the GUI.
Is updating models to higher versions supported when doing CI/CD using kubeflow pipelines for GCP Vertex AI?

/area backend
/area sdk
/area samples
/area components

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by jlyaoyuli** [comment]
Hello @clausagerskov 
KFP SDK doesn't have client to talk to Vertex AI service. Would you mind creating another issue under this repo: https://github.com/googleapis/python-aiplatform ? Thank you.
