### ISSUE TITLE
[feature] google-cloud component for generic container jobs

### ISSUE THREAD

**Issue by defoishugo** [kubeflow/pipelines#7887]
### Feature Area

/area sdk 
/area samples
/area components

### What feature would you like to see?

The ability to create custom container jobs, not only for training.
In my mind, we should be able to output user-defined artifacts (e.g.: metrics, datasets, two models, ...).

### What is the use case or pain point?

**USE CASE:** As a user, I have an existing on-premise application with which is a docker container with different pipelines:
- split: split the dataset into train/test/val with customized strategy (not random)
- train: train a model
- evaluate: displays and save some metrics

When it comes to calling the training pipeline, I can use the `CustomContainerTrainingJob` which produces a `VertexModel`. It works pretty well and thank you for that!

But for the split and evaluate commands, I could not use the `CustomContainerTrainingJob` since it produces only `VertexModel` and not arbitrary `Artifact`. 

### Is there a workaround currently?

Currently, I do not have a working workaround. However, I am right now playing with `convert_method_to_component` and with the `CustomContainerTrainingJob` and I will find a solution for that. 

The first idea that comes to my min would be to generate the train, test and val datasets in the _AIP_MODEL_DIR_ folder. Then, instead of creating a model, I will generate an artifact for each file with an URI to the files. 

Do I like this workaround? NO. It needs a lot of edits in different parts of the code. The solution seems dirty and too much homemade. If you have any other idea, please tell me.

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by connor-mccarthy** [comment]
@defoishugo, thanks for reaching out. This is on our development roadmap as a "Bring your own container" feature. I believe this will meet your needs once implemented.

**Comment by defoishugo** [comment]
@connor-mccarthy perfect!

Current workaround: using YML file with a container implementation. The issue with that is mainly about linking a training job to a dataset, which means that in the Datasets UI of VertexAI you would not see the training job attached. Probably something to add in the Google API backend?

Still, this workaround is easy to implement for anyone who is looking for a quick solution and waiting for the "Bring your own container" epic/feature.

**Comment by defoishugo** [comment]
@connor-mccarthy Do we have any news about this topic?

When using the workaround described in my previous message, we could not see the trained model in the "Datasets" related trainings. It means that it breaks the lineage.

**Comment by connor-mccarthy** [comment]
Hi, @defoishugo. This is implemented. You can find the docs, which we are continuing to improve, are [here](https://www.kubeflow.org/docs/components/pipelines/v2/author-a-pipeline/components/#3-custom-container-components).
