### ISSUE TITLE
Add e2e test for recurring runs

### ISSUE THREAD

**Issue by yebrahim** [kubeflow/pipelines#789]
This is one of the least tested paths, and we've broken it in the past without noticing. I suggest adding an e2e test to make sure the following works:
- UI controls around recurring runs configuration.
- Submitting the new run request succeeds.

Optionally also testing the following, since these require the test to wait for at least a minute, prolonging the total e2e test duration:
- A new run appears in the experiment's run list.
- This new run has the right details (its name and experiment id reference get propagated correctly).
- The recurring run can be disabled.

**Comment by Bobgy** [comment]
The feature hasn't been changed for a while, so it's not urgent
