### ISSUE TITLE
[sdk] 1.8.1 git tag is misplaced

### ISSUE THREAD

**Issue by davidxia** [kubeflow/pipelines#7894]
The 1.8.1 git tag is [here](https://github.com/kubeflow/pipelines/commits/1.8.1/sdk/python/requirements.in) on Nov 23, 2021. The `kfp` package on Pypi [here](https://pypi.org/project/kfp/#history) was published on Sep 10, 2021. I suspect the git tag is misplaced and should be moved back to the correct commit that created the 1.8.1 PyPI package. Having misplaced git tags will create debugging confusion for users.

I haven't checked the correctness of other git tags.

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by zijianjoy** [comment]
Hello @davidxia , the SDK versions in Pypi are not the same as GitHub release tags. KFP package in Pypi (SDK) has its own release cycle. The GitHub release tags are for KFP backend (docker images).
