### ISSUE TITLE
[backend] GCR images not accessible: `Consumer 'project:ml-pipeline' has been suspended.`

### ISSUE THREAD

**Issue by VishDev12** [kubeflow/pipelines#7904]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?

Standalone installation with Kustomize on EKS.

*  KFP version: 1.7.0

My KFP runs are failing and when I tried to pull this image: `gcr.io/ml-pipeline/argoexec:v3.1.14-license-compliance` manually from another unrelated machine, that failed with the following error:

```
Error response from daemon: Head https://gcr.io/v2/ml-pipeline/argoexec/manifests/v3.1.14-license-compliance: denied: Permission denied: Consumer 'project:ml-pipeline' has been suspended.
```

I apologize if this is something from my side, but it seems serious if it is not.

Edit:
## Suggestions

1. Your jobs might not actually be failing. For us, the `main` container runs without issue. Only the `wait` container with the `gcr.io/ml-pipeline/argoexec:v3.1.14-license-compliance` image is stuck. [This comment](https://github.com/kubeflow/pipelines/issues/7904#issuecomment-1158019599) details how to deal with that temporarily.
2. If you have your core Kubeflow Pipelines components on machines that have the potential to roll. On spot instance, for example, then:
    a. Try freezing them if you can. For example, certain K8s scaling systems allow you to restrict scale down on certain node groups.
    b. Copy over the core images to one of your private container registries as soon as possible. After that, you should be able to update your Kubeflow Pipelines manifests with these private images.

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by VishDev12** [comment]
Okay, this feels real, I can't access any of the images from this repo.

And confirmed that other gcr.io pulls work fine, for example: `gcr.io/google-containers/busybox@sha256:d8d3bc2c183ed2f9f10e7258f84971202325ee6011ba137112e01e30f206de67`

**Comment by boarder7395** [comment]
This is definitely and issue our cluster is having the same issue.

**Comment by akdigitalself** [comment]
Related slack thread: https://kubeflow.slack.com/archives/CE10KS9M4/p1655400994211759

**Comment by akdigitalself** [comment]
@chensun @IronPan @james-jwu @zijianjoy As you are the [owners](https://github.com/kubeflow/pipelines/blob/master/OWNERS) of this project, can you please help restore ml-pippelines in gcr.io? Thanks!

**Comment by rtkshahwar** [comment]
I am having the same issue and it just broke my demo I was about to give to my team in an hour.

**Comment by VishDev12** [comment]
Some steps I'm taking to temporarily unblock our jobs:

1. SSH to the K8s machines where you know for a fact that the jobs previously succeeded, and run:
`docker image ls`
2. Find the images that are causing your job to fail now, for us, it's `v3.1.14-license-compliance`.
3. Run `docker tag gcr.io/ml-pipeline/argoexec:v3.1.14-license-compliance <private_repo>/xblox:v3.1.14-license-compliance`
4. Run `docker push <private_repo>/xblox:v3.1.14-license-compliance`

After that, I haven't figured out how to let new jobs know to use this image. But for the jobs that are presently stuck in limbo:

1. After uploading the image to the repo above, SSH to the machine where the jobs are stuck,
2. Login to the same private repo.
3. `docker pull <private_repo>/xblox:v3.1.14-license-compliance
`
4, `docker tag <private_repo>/xblox:v3.1.14-license-compliance gcr.io/ml-pipeline/argoexec:v3.1.14-license-compliance`

After this, I can confirm that the stuck job succeeded, but this is only a stop-gap measure, of course.

**Comment by akdigitalself** [comment]
Seems like it's back up in gcr.io: https://kubeflow.slack.com/archives/CE10KS9M4/p1655407543079189?thread_ts=1655400994.211759&cid=CE10KS9M4

**Comment by karan-kumar-by** [comment]
Pods are able to pull the image now.

**Comment by VishDev12** [comment]
Could we please get a short RCA from the developers before we close this issue? I want to evaluate the risks of something like this repeating.

**Comment by akdigitalself** [comment]
Should they be using artifact registry? https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr?_ga=2.199229930.-556289867.1649704015

+1 about the ask for an RCA.

**Comment by chensun** [comment]
> Could we please get a short RCA from the developers before we close this issue? I want to evaluate the risks of something like this repeating.

Apologize for the trouble, our project was mistakenly suspended for a short period due to some process error, and we'll be working on a postmortem to prevent this from happening again.
