### ISSUE TITLE
Report metrics error to client

### ISSUE THREAD

**Issue by hongye-sun** [kubeflow/pipelines#793]
Currently if metrics file or format is invalid, the persistent agent just ignores the error. There is no way for user to know what's the error. We need to report those errors back to user.

One option is to provide an error list on run proto and let PA to append errors to it.

**Comment by Bobgy** [comment]
We should keep this open

**Comment by Bobgy** [comment]
I think we can close this, when we switch to MLMD based metrics, errors will be the same as other MLMD upload errors and visible in logs.
