### ISSUE TITLE
Difference between add_volume and add_pvolume

### ISSUE THREAD

**Issue by rjtshrm** [kubeflow/pipelines#7945]
I couldn't find any good documentation b/w add_volume and add_pvolume and when to use which.

**Comment by Linchin** [comment]
Here is the documentation: 
https://kubeflow-pipelines.readthedocs.io/en/stable/source/kfp.dsl.html#kfp.dsl.BaseOp.add_volume
https://kubeflow-pipelines.readthedocs.io/en/stable/source/kfp.dsl.html#kfp.dsl.BaseOp.add_pvolumes

Are these what you are looking for?

**Comment by rimolive** [comment]
/close

In kfp these functions were replaced to `add_ephemeral_volume` and `mount_pvc`
