### ISSUE TITLE
Support inline html in html viewer

### ISSUE THREAD

**Issue by hongye-sun** [kubeflow/pipelines#795]
It is required for GCP component to output GCP console dashboard and stacker driver links.

**Comment by rileyjbauer** [comment]
One way to achieve this would be adding an extra field to the output metadata giving users the option to supply encoded HTML rather than just the current option where a path to the location of the HTML file is provided.

**Comment by hongye-sun** [comment]
This has been resolved by inline markdown view that Yasser added a few weeks back.
