### ISSUE TITLE
[backend] Terminate Behavior Regression between Workflow Controllers 2.x vs 3.x (HEAD)

### ISSUE THREAD

**Issue by aabbccddeeffgghhii1438** [kubeflow/pipelines#7963]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?

*  KFP version: 
1.8.2
*  KFP SDK version: 
1.8.2

### Steps to reproduce
Currently, Kubeflow's terminate function works by setting activeDeadlineSeconds to 0. However, argo's controller loop only checks this for Pending pods, so a long running pod must run to completion before terminating. This has since been fixed on Argo's workflow controller with [commit](https://github.com/argoproj/argo-workflows/pull/8065). However, Argo 3.3 is fundamentally incompatible with Kubeflow as updates to workflows are now done by WorkflowTaskResult instead of patching pods.

### Expected result
Ideally, clicking terminate instantly terminates the workflow and any running pod. This behavior is honored by the above commit. However, due to other changes there is no feasible route to upgrade ATM. If Kubeflow wishes to stay on 3.2.3, perhaps it should be considered to cherrypick out the patch?

### Materials and Reference

https://github.com/argoproj/argo-workflows/pull/8065

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by allenc97** [comment]
Do note that this behavior was true for Argo < 3, I.e https://github.com/argoproj/argo-workflows/blob/08c9964d5049c85621ee1cd2ceaa133944a650aa/workflow/controller/exec_control.go#L89.

**Comment by Linchin** [comment]
This will be resolved after we upgrade argo to version 3.3.

**Comment by allenc97** [comment]
Is there a timeline for this? For this upgrade, is it for 2.0, or 1.8.x?

**Comment by ryansteakley** [comment]
Additionally some of the pre-existing terminate commands do not work due to a change in the way they killed containers and the signals that were sent. Looks like they fixed this in https://github.com/argoproj/argo-workflows/issues/8687 what is the communities path-forward to regain this functionality?

**Comment by Sharathmk99** [comment]
@Linchin When can we expect version upgrade to 3.3?
