### ISSUE TITLE
Metrics using SDK 

### ISSUE THREAD

**Issue by bertinma** [kubeflow/pipelines#7971]
Hi, 

I'm. using kip to build my kubeflow pipeline following this method/tutorial : https://www.kubeflow.org/docs/components/pipelines/sdk/component-development/ 

So I have a python code, component.yaml, Dockerfile and build_image.sh files for each pipeline step. 

I want to track metrics produced during evaluation step. 

My codes are like that : 
* eval.py 

            metrics': [
                {
                    'name': 'loss',
                    'numberValue':  self.metrics_dict['loss'],
                    'format': 'RAW',
                },
                {
                    'name': 'iou_score',
                    'numberValue':  self.metrics_dict['iou_score'],
                    'format': 'PERCENTAGE',
                },
                {
                    'name': 'f1-score',
                    'numberValue':  self.metrics_dict['f1-score'],
                    'format': 'PERCENTAGE'
                },
            ]
        }
        print(args.metrics)
        with open(Path(args.metrics) / "mlpipeline-metrics.json", 'w') as f:
            json.dump(metrics, f)

* component.yaml 

      name : eval_seg
      description: Evaluate segmentation model
      outputs: 
      - {name: MLPipeline Metrics, type: Metrics, description: "metrics path"}
      
      implementation:
        container:
          image: gcr.io/.../eval_seg@sha256:...
          command: [
            python3.8, eval.py,
            --metrics,
            {outputPath: MLPipeline Metrics}
          ]

The step finished correctly but no metrics and artifacts were found for this step in "Visualizations" and  for the whole pipeline in "Run output" tab. 
 
Where I am wrong ? Is there a method to get metrics using this kubeflow method or I have to change how to build my pipeline ? 
Thanks for your help ! 

###################################

kfp version : 1.8.12 (installed with pip) 
kubeflow : 1.7.1
Kubernetes : 1.21.11-gke.900
Cloud deployment : GCP AI Pipelines

**Comment by harshvladha** [comment]
@bertinma how did you resolve the issue?

**Comment by bertinma** [comment]
I create a dictionary with my metrics and save to a minIO output path like this 

`metrics = {
            'metrics': [
                {
                    'name': 'loss',
                    'numberValue':  self.metrics_dict['loss'],
                    'format': 'RAW',
                },
                {
                    'name': 'iou_score',
                    'numberValue':  self.metrics_dict['iou_score'],
                    'format': 'RAW',
                },
                {
                    'name': 'f1-score',
                    'numberValue':  self.metrics_dict['f1-score'],
                    'format': 'RAW'
                },
            ]
        }`

       with open(Path(args.metrics) / "mlpipeline-metrics.json", 'w') as f:
            json.dump(metrics, f)`


Then I create a step to display them 


`from kfp.components import InputPath, OutputPath
def produce_metrics(metrics: InputPath('LocalPath'), roc_curve_values: InputPath('LocalPath'), mlpipeline_metrics_path: OutputPath('Metrics')):
    import json
    from pathlib import Path
    import pickle
    import pandas as pd 
    import os
    with open(Path(metrics) / 'mlpipeline-metrics.json', 'r') as f:
        metrics = json.load(f)
    with open(mlpipeline_metrics_path, 'w') as f:
        json.dump(metrics, f)`
