### ISSUE TITLE
Auto Refresh on for pipeline UI

### ISSUE THREAD

**Issue by SinaChavoshi** [kubeflow/pipelines#798]
Currently the user has to  manually hit the refresh  link  on all pages manually. If we could set an auto refresh for every x seconds would be a huge improvement to user experience. This was also raised by one of the customers using the platform.

**Comment by yebrahim** [comment]
This has already been done in the Run details page in @rileyjbauer's #722, which I think is where this is most relevant/needed.
@SinaChavoshi how useful do you think this is on other pages too?

**Comment by SinaChavoshi** [comment]
Run details would be the most impactful one. however this would be a nice to have feature for other pages as well ( ex all runs, experiments etc)

**Comment by Bobgy** [comment]
I agree this is a feature we need to rethink over.
I find myself usually confused in a page whether it refreshes or not. Sometimes I have to refresh the whole page to make sure.

**Comment by Bobgy** [comment]
I realized this is probably not a good idea for various list pages, because you can select some items and do certain actions. It will be very hard to design the UX considering refresh and selection together.

**Comment by Bobgy** [comment]
/close
I don't think this is doable. Please comment if you have an idea
