### ISSUE TITLE
[backend] DeleteExperiment does not clean up all relevant children objects from the DB 

### ISSUE THREAD

**Issue by difince** [kubeflow/pipelines#7982]
### Steps to reproduce
When [deleteExperiment](https://github.com/kubeflow/pipelines/blob/127dab4d4671849d596c455f4619ea807d22f6ea/backend/src/apiserver/server/experiment_server.go#L173) is called,  not all children objects ( like Runs/ resource_references) are deleted from MySQL. 
DeleteExperiment cannot be called from the front-end/GUI, but the user still could execute a cURL request. 
After an experiment is deleted the DB could get in an inconsistent state - having Runs that belong to an un-existing experiment - this leads to following up 404 exceptions in the frond-end.

### Proposed fix / behaviour
- IMO, delete experiments should be enabled only if the experiments are in an **Archived** state.  
So, validation needs to be added prior experiment to be deleted

- In order to clean up all Experiment's resource_references :
[s.resourceReferenceStore.DeleteResourceReferences(tx, id, common.Run)](https://github.com/kubeflow/pipelines/blob/e3678e1aadcb3be7bbd4f27059ae64db5631222e/backend/src/apiserver/storage/experiment_store.go#L238) > should be changed to `s.resourceReferenceStore.DeleteResourceReferences(tx, id, common.Experiment) `

- All related Runs to be cleaned up.

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by difince** [comment]
I just saw this [comment](https://github.com/kubeflow/pipelines/blob/127dab4d4671849d596c455f4619ea807d22f6ea/backend/api/experiment.proto#L84-L87) in the code. It looks that the current behavior is intended to behave this way - it is not a bug. But IMO, the server should self-validate that all runs/jobs are deleted, and not let the DB goes in an inconsistent state. 

The proposed above "fix/behavior" still makes sense to me.

**Comment by chensun** [comment]
As you found out this is currently by design, I can see arguments from both side. We can probably keep this issue for seeking opinions.
