### ISSUE TITLE
[sdk] Cut a new release that supports `typing_extensions 4.0`?

### ISSUE THREAD

**Issue by alanhdu** [kubeflow/pipelines#7983]
Currently, the latest `kfp=1.8.12` pins `typing_extensions to ` 'typing-extensions>=3.7.4,<4;python_version<"3.9"',`. This is a bit of a problem for us, since we have another dependency (PyTorch Lightning) that requires `typing-extensions >= 4`.  Would it be possible to cut a new release that supports the latest typing extensions?

**Comment by akchinSTC** [comment]
Can prob close this, kfp 1.8.13 was cut yesterday. 
Thanks!
