### ISSUE TITLE
[bug] TFJob launcher pipeline task fails when `delete_finished_tfjob` flag is `True`

### ISSUE THREAD

**Issue by eundonglee** [kubeflow/pipelines#7984]
https://github.com/kubeflow/pipelines/blob/127dab4d4671849d596c455f4619ea807d22f6ea/components/kubeflow/launcher/component.yaml#L19

When `delete_finished_tfjob` flag is `True`, TFJob launcher task fails with error below.

```
Traceback (most recent call last):
  File "/ml/launch_tfjob.py", line 136, in <module>
    main()
  File "/ml/launch_tfjob.py", line 133, in main
    tfjob.delete(args.name, args.namespace)
  File "/ml/launch_crd.py", line 115, in delete
    body)
TypeError: delete_namespaced_custom_object() takes exactly 6 arguments (7 given)
```

I think it's some kind of kubernetes client SDK version issue in `nikenano/launchernew:latest` container image.

**Comment by eundonglee** [comment]
I found this PR in `kubeflow/training-operator` repo about similar problem.
https://github.com/kubeflow/training-operator/pull/1281

I think those changes above should be applied here and also to `nikenano/launchernew` container image.
https://github.com/kubeflow/pipelines/blob/127dab4d4671849d596c455f4619ea807d22f6ea/components/kubeflow/common/launch_crd.py#L117-L123

**Comment by streamnsight** [comment]
The code might have been fixed, but the image in the component.yaml has not been updated so the changes are not propagated.

**Comment by sourabh-raja-murali** [comment]
We have a usecase where we want to delete the TF job as the TF job holds on to the PVC which also needs to be deleted upon TFJob completion. I could not find the updated image with the fix. Can the image with the fix be shared please?
