### ISSUE TITLE
Does Kubeflow (1.2) has dependency with any specific kfp python library version?

### ISSUE THREAD

**Issue by JebasinghLuccas** [kubeflow/pipelines#8001]
i am wondering if there any dependencies in kfp python library version when i want to use it in kubeflow

**Comment by connor-mccarthy** [comment]
@JebasinghLuccas, I do not believe there is any strict dependency on a KFP SDK version, so long as you're using a kfp SDK 1.x version, as we've adhered closely to the semantic versioning standards. The most recent is `1.8.13`.

Context: Kubeflow 1.2 uses Kubeflow Pipelines 1.0.4
