### ISSUE TITLE
Unable to set memory for a Kubeflow component using yaml

### ISSUE THREAD

**Issue by patrickmead** [kubeflow/pipelines#8038]
I'm using yaml for my Kubeflow components which run on Vertex AI.  I know that I have alternatives for creating components such as the python SDK, but I would like to use yaml directly if possible (rather than generating it).  I see methods like set_memory_limit and set_memory_request for the ContainerOp but when I use methods such as load_component_from_file I have a TaskSpec. 

Is there a way to set memory and other resources via the Kubeflow component yaml?

Thank you.

**Comment by patrickmead** [comment]
In the interim, it appears that I can set the memory in the pipeline json.

**Comment by chensun** [comment]
Hi @patrickmead, are you using KFP SDK v1.8.*? 
You can still set memory limit for components load from file. Example:
https://github.com/kubeflow/pipelines/blob/d5bc8ddd6250d90b38cff5759e856f73e71e7d03/sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_resource_spec.py#L25-L44

`set_memory_request` is not available/applicable for Vertex AI though.
