### ISSUE TITLE
[feature] Ability to add Runtime Class name to Kubeflow Pipeline

### ISSUE THREAD

**Issue by jayanthp-intellect** [kubeflow/pipelines#8052]
### Feature Area

/area backend
/area sdk

### What feature would you like to see?
Would like to have a separate method in kfp py package to add Runtime class (https://kubernetes.io/docs/concepts/containers/runtime-class/) to KF Pipeline Config and/or KFP Components. This is already supported in kubernetes py package (https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1RuntimeClass.md)

### What is the use case or pain point?
The latest upgrade to kops 1.23.x is altering the default runtime in containerd to **runc** instead of **nvidia**. This is forcing us to use the Runtime Class name to choose **nvidia** runtime for GPU workloads.

### Is there a workaround currently?
We manually override the default runtime set in the Containerd to nvidia and recycle the Containerd service (using some script customisation in the Kops Instance Group config)

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by jlyaoyuli** [comment]
Hi @jayanthp-intellect, can you provide the reference for changing the default Runtime?

**Comment by jayanthp-intellect** [comment]
@jlyaoyuli Refer to the following containerd config file auto-generated and managed by KOPS 1.23.x ([KOPS GPU support](https://github.com/kubernetes/kops/blob/master/docs/gpu.md)). This is on a GPU node with NVIDIA Drivers + CUDA 11.1. By default, KOPS sets and maintains the `default_runtime_name` to be **runc** which forces us to specify the Kubernetes Runtime Class as **"nvidia"** to override this and ensure that the Pod runs using the **nvidia** runtime name instead of **runc** runtime name.
```
version = 2

[plugins]

  [plugins."io.containerd.grpc.v1.cri"]
    sandbox_image = "k8s.gcr.io/pause:3.6"

    [plugins."io.containerd.grpc.v1.cri".containerd]
      default_runtime_name = "runc"

      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]

        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia]
          privileged_without_host_devices = false
          runtime_engine = ""
          runtime_root = ""
          runtime_type = "io.containerd.runc.v1"

          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia.options]
            BinaryName = "/usr/bin/nvidia-container-runtime"
            SystemdCgroup = true

        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
          runtime_type = "io.containerd.runc.v2"

          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
            SystemdCgroup = true
```
Inorder to be able to set this dynamically in the KubeFlow Pipeline, we need a method similar to `add_toleration` method [here](https://kubeflow-pipelines.readthedocs.io/en/stable/source/kfp.dsl.html)

**Comment by jayanthp-intellect** [comment]
@chensun @jlyaoyuli Is the information I provided relevant/sufficient for you guys to proceed or do you need more clarification? Let me know. Thanks.

**Comment by ketangangal** [comment]
@chensun , @jlyaoyuli , @jayanthp-intellect  
Please Find the solution needed : 

[Here](https://kubeflow-pipelines.readthedocs.io/en/1.8.13/_modules/kfp/dsl/_container_op.html#ContainerOp) with kfp sdk we are adding toleration in pod specification similarly we want to add runtime class request in the pod using kfp. 
```
class BaseOp(object):

    def add_toleration(self, tolerations: V1Toleration):
        Add K8s tolerations.

        Args:
          tolerations: Kubernetes toleration For detailed spec, check toleration
            definition
            https://github.com/kubernetes-client/python/blob/master/kubernetes/client/models/v1_toleration.py

        self.tolerations.append(tolerations)
        return self
``` 

We want this method to be implemented so , we can provide runtime class request directly. 
This mtd is not present yet , I have created to make it clear what we want. 
```
class BaseOp(object):

    def add_runtime_class(self, runtime_class: V1beta1RuntimeClass):
        self.runtime_class.append(runtime_class)
        return self

```

So once you generate the podspec it should have runtimeclass present in it !

```
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  runtimeClassName: myclass
```

**Comment by ketangangal** [comment]
I have talking about this feature: 
https://github.com/argoproj/argo-workflows/issues/7519

**Comment by ketangangal** [comment]
kOps will also install a RuntimeClass nvidia. As the nvidia runtime is not the default runtime, you will need to add runtimeClassName: nvidia to any Pod spec you want to use for GPU workloads. The RuntimeClass also configures the appropriate node selectors and tolerations to run on GPU Nodes. 

In kubeflow we cant specify runtime class for pod specification:

**Comment by namirinz** [comment]
https://github.com/kubeflow/pipelines/issues/11084
