### ISSUE TITLE
[feature] Add authorization to all functions in ReportServer

### ISSUE THREAD

**Issue by difince** [kubeflow/pipelines#8074]
### Feature Area
There are two API-server endpoints that still miss authorization - [ReportWorkflow](https://github.com/kubeflow/pipelines/blob/d48776fb2d9752ca48af14ea6256791d2b167a71/backend/src/apiserver/server/report_server.go#L32) and [ReportScheduledWorkflow](https://github.com/kubeflow/pipelines/blob/d48776fb2d9752ca48af14ea6256791d2b167a71/backend/src/apiserver/server/report_server.go#L45). This is a security issue. Each endpoint should validate that the user has permission to call them. 

**persistent-agent** service calls these endpoints. Once authorization is enabled, the persistent-agent need to authorize itself by providing user information in the request headers.

This issue is a related/ follow-up issue to PR https://github.com/kubeflow/pipelines/pull/7819

 /area backend 

### Is there a workaround currently?
no. A security issue exists in the current implementation.

---

Love this idea? Give it a 👍.

**Comment by difince** [comment]
cc: @juliusvonkohout

**Comment by juliusvonkohout** [comment]
For the next KFP meeting ;-)

**Comment by zijianjoy** [comment]
Hello @difince , the `ReportWorkflow` and `ReportScheduledWorkflow` are used by single persistent-agent instance for monitoring the status of workflow. persistent-agent itself cannot and shouldn't authenticate as a user. 
/assign @chensun

**Comment by difince** [comment]
Thank you @zijianjoy for your feedback. How services are supposed to authenticate themself?

**Comment by juliusvonkohout** [comment]
> Hello @difince , the `ReportWorkflow` and `ReportScheduledWorkflow` are used by single persistent-agent instance for monitoring the status of workflow. persistent-agent itself cannot and shouldn't authenticate as a user. /assign @chensun

By default every kubeflow user can hijack them, since these endpoints are unauthenticated. So first they need ANY kind of authentication.

**Comment by juliusvonkohout** [comment]
> Thank you @zijianjoy for your feedback. How services are supposed to authenticate themself then? Any suggestion? I guess this reflects on the implementation of #7819 as well ?

@chensun (@zijianjoy college at google) already approved #7819 so i do not think that it is affected. Readartifact etc. is really called by users for a proper reason. Reportworkflow might only be abused for no reason.

**Comment by difince** [comment]
Fixed by #9699 
The persistence agent authenticates itself via a service account token, meanwhile, the pipeline API server has enabled authentication and authorization logic.
