### ISSUE TITLE
[bug] Kubeflow Pipelines Standalone Kustomize incompatible with K8s 1.22+

### ISSUE THREAD

**Issue by dsiegel** [kubeflow/pipelines#8076]
KFP Kustomize setup does not work with Kubernetes 1.22+. The [kustomization.yaml](https://github.com/kubeflow/pipelines/blob/master/manifests/kustomize/cluster-scoped-resources/kustomization.yaml) references an API that was removed (apiextensions.k8s.io/v1beta1). 

### Environment

*  How do you deploy Kubeflow Pipelines (KFP)?

Kubeflow Pipelines Standalone

*  KFP version:

Version: [1.7.1](https://www.github.com/kubeflow/pipelines/commit/1d53de98c731d3cf6ef9017ad19bbfcf19787de3)

### Steps to reproduce

```
> kubectl diff --kustomize  "github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=1.7.1"

error: resource mapping not found for name: "applications.app.k8s.io" namespace: "" from "github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=1.7.1": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
ensure CRDs are installed first
```

### Expected result

It should diff with my current kfp state.

### Materials and reference

The beta CustomResourceDefinition API (apiextensions.k8s.io/v1beta1) has been removed. See [Kubernetes 1.22 API changes](https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/).

### Labels

backend

---

Impacted by this bug? Give it a 👍.

**Comment by dsiegel** [comment]
I suspect that upgrading from KFP 1.7.1 fixes this. Never mind.

**Comment by tanken** [comment]
Hi, Im facing the same issue with Kubernetes 1.22, doesnt seem like KFP 1.7.1+ fixes this
