### ISSUE TITLE
[bug] TypeError: Object of type PipelineParam is not JSON serializable

### ISSUE THREAD

**Issue by lightingghost** [kubeflow/pipelines#8095]
### Environment

*  KFP SDK version:
1.8.13

### Steps to reproduce

```
import kfp
import kfp.v2.dsl as dsl

@dsl.component
def compute(x: int) -> int:
    return x

@dsl.component
def print_op(results: dict):
    print(results)

@dsl.pipeline(name='pipeline')
def pipeline():
    outputs = {i: compute(i).output for i in range(10)}
    print_op(outputs)

kfp.v2.compiler.Compiler().compile(
    pipeline_func=pipeline,
    package_path="/tmp/test_pipeline.json"
)
```
it give error of `TypeError: Object of type PipelineParam is not JSON serializable`

### Expected result

it compiles without an error

### Labels

/area backend

---

Impacted by this bug? Give it a 👍.

**Comment by connor-mccarthy** [comment]
Hi @lightingghost. Using a component within a list comprehension is not a permitted component usage pattern in the KFP SDK and will result in unpredictable behavior. This is the source of the error.

`outputs = {i: compute(i).output for i in range(10)}`
