### ISSUE TITLE
[frontend] Artifact API Does not support S3 Regions

### ISSUE THREAD

**Issue by kdubovikov** [kubeflow/pipelines#8111]
<img width="1727" alt="Screenshot 2022-08-08 at 18 16 17" src="https://user-images.githubusercontent.com/832185/183455928-0c6c6c10-da25-4c2b-b19f-13573e43bafe.png">

<img width="1719" alt="Screenshot 2022-08-08 at 18 16 02" src="https://user-images.githubusercontent.com/832185/183455906-ba856df3-d657-4bbb-922f-572c7faf2aae.png">

Artifact fetching API does not seem to support region for s3 resources. If we look here, https://github.com/kubeflow/pipelines/blob/e8abec24fed4c4f8be6f527207b1cec9811ce3e7/frontend/server/minio-helper.ts#L50, the region parameter is not being passed and it is not a part of the artefact API as well. However, MINIO Client API allows you to specify region when creating a client: https://docs.min.io/docs/javascript-client-api-reference.html. I think API should fetch default region using `MINIO_REGION` environment variable which should be passed as a part of `ml-pipeline-ui-artifact` k8s deployment `env` map.

### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
[kubeflow-manifests](https://github.com/awslabs/kubeflow-manifests)

*  KFP version: 
1.5.1

### Steps to reproduce

1. Launch any pipeline
2. Go to Run UI
3. Try to download any output
4. Observe the error: Failed to get object in bucket [bucket] at path [path]: S3Error: The authorization header is malformed; the region 'us-east-1' is wrong; expecting '[actual bucket region]'

**Comment by kdubovikov** [comment]
My bad, I've found that it actually uses `AWS_REGION` variable here: https://github.com/kubeflow/pipelines/blob/e8abec24fed4c4f8be6f527207b1cec9811ce3e7/frontend/server/configs.ts#L129. Will add that to deployment to test if it works

**Comment by kdubovikov** [comment]
It works as expected if I specify `AWS_REGION`, `AWS_SECRET_ACCESS_KEY`, and `AWS_ACCESS_KEY_ID `

**Comment by kdubovikov** [comment]
Actually, I think that there is still an issue when we use multi-profile setup. The problem lies in the `ml-pipeline-ui-artifact` deployment which is automatically created for each profile. 

Here, https://github.com/kubeflow/pipelines/blob/a0a8f1da8cb7ca53cde7717aa78e666b634fec75/manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/sync.py#L304 we sync only `` and `` variables. However, when using s3, this code suggest that we should provide `AWS_REGION`, `AWS_SECRET_ACCESS_KEY`, and `AWS_ACCESS_KEY_ID`.

https://github.com/kubeflow/pipelines/blob/e8abec24fed4c4f8be6f527207b1cec9811ce3e7/frontend/server/configs.ts#L129

That means that we should add those variables to `pipelines-profile-controller`. When I add them manually to the `ml-pipeline-ui-artifact` UI fetches all s3 artifacts in the Pipeline UI as expected.

**Comment by rawc0der** [comment]
Hi @kdubovikov @chensun,

Also running into this problem after switching Artifact Store persistence to S3.

Wondering if you've seen the latest **MinioJS v7.0.27** with _Assume Web Identity Role_ support https://github.com/minio/minio-js/pull/960 ?

This could be part of the fix, without needing any workaround if I'm not mistaken.
