### ISSUE TITLE
[feature] Implement comprehensive unit tests for the KFP SDK Client class

### ISSUE THREAD

**Issue by droctothorpe** [kubeflow/pipelines#8126]
### Feature Area

/area sdk

### What feature would you like to see?
We would like to see comprehensive unit tests for the KFP SDK [Client](https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/client/client.py#L82) class to improve confidence in code changes.

The existing coverage looks [quite sparse](https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/client/client_test.py). 

My team and I would be interested in contributing this to the upstream but want to make sure that we're not stepping on anyone's toes / it makes sense to core maintainers.

### What is the use case or pain point?
Reduced confidence in code changes / releases.

### Is there a workaround currently?
No.

---

Love this idea? Give it a 👍.

**Comment by chensun** [comment]
Hi @droctothorpe feel free to contribute ? JFYI, here're some example code on how we tested the v2 Vertex client (which was moved out of KFP package in the master branch): https://github.com/kubeflow/pipelines/tree/sdk/release-1.8/sdk/python/kfp/v2/google/client
