### ISSUE TITLE
[backend] Use the taskInfo name to find artifact 

### ISSUE THREAD

**Issue by zichuan-scott-xu** [kubeflow/pipelines#8171]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
Kubeflow Pipelines Standalone
*  KFP version: 
2.0.0-alpha.3

*  KFP SDK version: 
2.0.0b2

### Steps to reproduce
1. Open https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/compiler/test_data/pipelines/two_step_pipeline_containerized.py
2. Call `.set_display_name('name1')` on `component1` and `.set_display_name('name2')` on `component2` when defining `my_pipeline`
3. Run the file to compile a yaml IR
4. Submit the IR to KFP standalone

### Expected result

The pipeline is not able to run as the second component couldn't find the component `component1`, which is renamed.

### Materials and Reference

https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/compiler/test_data/pipelines/two_step_pipeline_containerized.py
https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/compiler/test_data/pipelines/two_step_pipeline_containerized.yaml

---

Impacted by this bug? Give it a 👍.

**Comment by Lejboelle** [comment]
Still experiencing this issue on Kubeflow 1.8, KFP version 2.0.1, KFP SDK version 2.4.0.

**Comment by pbasov** [comment]
Hitting the same issue.

```@dsl.pipeline(
    name='KServe LLM Deployment Pipeline',
    description='A pipeline that creates a KServe HuggingFace LLM InferenceService'
)
def kserve_deployment_pipeline(model_id: str = "TheBloke/Llama-2-7B-Chat-AWQ", use_gpu: bool = True):
    kserve_task = create_kserve(model_id=model_id, use_gpu=use_gpu)
    kserve_task.set_caching_options(False)

    gradio_task = serve_gradio(model_endpoint=kserve_task.output, model_id=model_id)
    gradio_task.set_caching_options(False)

    kserve_task.set_display_name("Run LLM with KServe")
    gradio_task.set_display_name("Start Gradio frontend")
```
    
`kserve_task` returns model endpoint URL as a string, gradio_task is not able to run with the error:
 ```
failed: failed to resolve inputs: resolving input parameter model_endpoint with spec task_output_parameter:{producer_task:"create-kserve" output_parameter_key:"Output"}: cannot find producer task "create-kserve"
```
