### ISSUE TITLE
[backend] <Bug Name>TypeError: compile() got an unexpected keyword argument 'pipeline_parameters'

### ISSUE THREAD

**Issue by r-matsuzaka** [kubeflow/pipelines#8175]
#### How did you deploy Kubeflow Pipelines (KFP)?

- minikube  latest (kubernets 1.21.14)
- kustomize 3.2.0
- kubectl 1.21.14
- kubeflow/manifests v1.6-branch

```shell
git clone https://github.com/kubeflow/manifests.git -b v1.6-branch
cd manifests
bash hack/setup-kubeflow.sh
```

*  KFP version: 
```
$ print(kfp.__version__)
1.8.13
```
I tried both:
```
pip install kfp==1.8.13
pip install --pre kfp
```

### Steps to reproduce

https://www.kubeflow.org/docs/components/pipelines/sdk/build-pipeline/#getting-started-building-a-pipeline

### Expected result
I cannot get kubeflow pipeline yaml file by following method. And I got `TypeError: compile() got an unexpected keyword argument 'pipeline_parameters'`

```
kfp.compiler.Compiler().compile(
    pipeline_func=my_pipeline,
    package_path='pipeline.yaml',
    pipeline_parameters={'url': 'https://storage.googleapis.com/ml-pipeline-playground/iris-csv-files.tar.gz'})
```

From this implementation, I should use `pipeline_parameters` argument for `kfp.compiler.Compiler().compile`
https://github.com/kubeflow/pipelines/blob/3b1bd08ce0188605cff90e3f14563d55436aac96/sdk/python/kfp/compiler/compiler.py#L62

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

**Comment by chensun** [comment]
Hi @r-matsuzaka, 

Sorry about the confusion here. The doc you referred to is about KFP v1, and the master branch code is about KFP v2. The code for v1 can be found in the `sdk/release-1.8` branch: https://github.com/kubeflow/pipelines/blob/0ad4cdfaabebbb566dad2b9523267d886942f2ad/sdk/python/kfp/compiler/compiler.py#L1129-L1144

and `pipeline_parameters` was not there.

We're working on adding the v2 doc, and you may find some recent changes in: https://github.com/kubeflow/website/commits/pipelines-v2-docs
