### ISSUE TITLE
500 Error Jupyter notebook

### ISSUE THREAD

**Issue by kstory8** [kubeflow/pipelines#818]
I tried to launch a jupyter notebook from a custom docker image. This failed (presumably because of permissions issues accessing the particular GCR). Now, jupyterhub keeps failing with the following error:

500 : Internal Server Error
Failed to reach your server. Please try again later. Contact admin if the issue persists.

You can try restarting your server from the home page.

**Comment by kstory8** [comment]
<img width="288" alt="screen shot 2019-02-12 at 4 35 34 pm" src="https://user-images.githubusercontent.com/10334951/52677845-567d8a80-2ee4-11e9-9184-d260662579ac.png">

**Comment by gaoning777** [comment]
I don't think the kubeflow offersw customized notebook image if you follow the kubeflow pipeline deployment.
instructions on customizing jupyterhub and notebook images:
https://github.com/kubeflow/kubeflow/tree/master/components/jupyterhub

@jlewi Can you offer more instructions or the user practice to customize notebook images?

**Comment by jlewi** [comment]
Can you provide the full JupyterHub logs? 
I would also suggest deleting the JupyterHub pod to force it to restart.
You can also check for any jupyter pods and delete those.

**Comment by vicaire** [comment]
Resolving since this issue has been inactive for a while. Please re-open if needed.
