### ISSUE TITLE
[feature] add delete button for runs to KFP UI

### ISSUE THREAD

**Issue by tingshua-yts** [kubeflow/pipelines#8185]
### Feature Area

 /area frontend 

### What feature would you like to see?
![image](https://user-images.githubusercontent.com/57979478/186108318-99aa686b-6b9d-4247-ab98-c68b7d00d796.png)

can add delete button for runs ? Currently, there is no delete button. Is there any design concern？

### What is the use case or pain point?
I submitted a batch of tasks and found that they did not meet expectations. I hope to delete them

### Is there a workaround currently?

I use kubectl delete workflow xxxx

---

Love this idea? Give it a 👍.

**Comment by jlyaoyuli** [comment]
Hi @tingshua-yts , you can archive the runs first and then delete them in the archived list.
