### ISSUE TITLE
kfctl.sh apply platform 

### ISSUE THREAD

**Issue by timbuktuu** [kubeflow/pipelines#820]
Created a cluster following the command line instructions on a Mac OS and saw the following error, but the cluster seems to have been created correctly.

++ kubectl get secret --namespace=kubeflow kubeflow-oauth
+ O='Error from server (NotFound): secrets "kubeflow-oauth" not found'
+ RESULT=1
+ set -e
+ '[' 1 -eq 0 ']'

**Comment by IronPan** [comment]
I guess you saw this in the last step 
```
${KUBEFLOW_SRC}/scripts/kfctl.sh apply k8s
```

Could you double check the cluster and see if secret is there
```
 kubectl get secret kubeflow-oauth -n kubeflow
```

**Comment by timbuktuu** [comment]
Yes, we run the kfctl.sh apply k8s script and the secret was not in the cluster.

**Comment by IronPan** [comment]
could you retry the apply command? the error message says it's not found in the cluster but the command should create it.

**Comment by aaron-nall** [comment]
I'm not sure if it helps, but when deploying to GKE, the kubeflow-oauth secret is created when applying platform rather than k8s.  It will also only be created if CLIENT_SECRET and CLIENT_ID are exported in the shell environment.

**Comment by vicaire** [comment]
Resolving since this issue as been inactive for a while. Please reopen as needed.
