### ISSUE TITLE
[feature] import python function in component

### ISSUE THREAD

**Issue by TranThanh96** [kubeflow/pipelines#8205]
for example:
I have a file utils.py which defined some functions.
How can I import those functions in my components?
Any ideas?

**Comment by JonasTischer** [comment]
I'm struggling with the same issue. Do I understand correctly that it is generally possible?
@connor-mccarthy do you have an example implementation you could reference too?

**Comment by connor-mccarthy** [comment]
Here is the most up to date documentation on this feature: https://www.kubeflow.org/docs/components/pipelines/v2/author-a-pipeline/components/#2-containerized-python-components

Pair this with `kfp component build --help` for more information.

If that doesn't help, please let me know and I will update the documentation to fill in any gaps.

**Comment by ViktorLitviakov8050** [comment]
@connor-mccarthy could you provide please up to date documentation regarding import a custom function into a kfp component ? if you have such...
This link unfortunately lead to 404: https://www.kubeflow.org/docs/components/pipelines/v2/author-a-pipeline/components/#2-containerized-python-components

**Comment by connor-mccarthy** [comment]
Just updated the link in https://github.com/kubeflow/pipelines/issues/8205#issuecomment-1366048845, @ViktorLitviakov8050.
