### ISSUE TITLE
[frontend] Can't see log field in UI (SDK v2)

### ISSUE THREAD

**Issue by sergeykuprikov** [kubeflow/pipelines#8255]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
from kubeflow/manifests v1.4
*  KFP version: 1.7.0
### Steps to reproduce
QQ
When I try to run a simple pipeline on SDK 2, I don't see the main.log fields in the output artifact.
Although I can see the log saved in minio.
![image](https://user-images.githubusercontent.com/85128586/189547248-264e5617-6669-4a25-8ac7-fc58ef6223ae.png)
UI:
![image](https://user-images.githubusercontent.com/85128586/189547303-fed1e165-c70e-4cec-9093-d4d0651f6fd6.png)
Minio:
![image](https://user-images.githubusercontent.com/85128586/189547416-d75dd922-6bf4-486a-bbd1-d66f58991152.png)
Log:
![image](https://user-images.githubusercontent.com/85128586/189547475-be9b13f9-f422-49a0-b496-af8f1c1857de.png)

### Expected result
Like this:
![image](https://user-images.githubusercontent.com/85128586/189547501-83a3e5d5-a92c-4acf-a2ca-bf037099668b.png)
### Materials and Reference

---

Impacted by this bug? Give it a 👍.

**Comment by connor-mccarthy** [comment]
We do not support main.logs in KFP v2 compatible mode. We are no longer supporting KFP v2 compatible mode.

We support main.logs in KFP v1 and are working toward support in KFP v2.
