### ISSUE TITLE
[feature] Allow GCP ModelUploadOp to upload a model version

### ISSUE THREAD

**Issue by parthmishra** [kubeflow/pipelines#8257]
### Feature Area

/area components

### What feature would you like to see?

The ability to upload a Vertex Model version to the model registry

### What is the use case or pain point?

In the REST API for[ model upload](https://cloud.google.com/vertex-ai/docs/reference/rest/v1/projects.locations.models/upload#request-body), the request body has several fields including `parentModel` which can be supplied if uploading a new model version. 

The current version of [`ModelUploadOp`](https://github.com/kubeflow/pipelines/blob/1739434f4ad2000105e0a8feff41b587e3c9de8c/components/google-cloud/google_cloud_pipeline_components/container/v1/gcp_launcher/upload_model_remote_runner.py#L55) only supplies the `model` field in the request: 

```python
  upload_model_request = {
      # TODO(IronPan) temporarily remove the empty fields from the spec
      'model':
          json_util.recursive_remove_empty(
              append_unmanaged_model_artifact_into_payload(
                  executor_input, model_spec))
  }
```

### Is there a workaround currently?

I believe this can be done by creating a custom component that uses the `gcloud` sdk and then `gcloud ai model upload ... --parent-model ... --version-aliases ` but I haven't tried it yet. 

---

Love this idea? Give it a 👍.

**Comment by meken** [comment]
Similarly other Ops that can generate a model (Custom*TrainingJobRunOp, AutoML*TrainingJobRunOp etc) should support adding new versions of a model as well.

**Comment by edday1** [comment]
> 

+1

**Comment by IronPan** [comment]
This should now be supported by the latest release, via the parent_model parameter. Please reopen if you see it's not working.
https://google-cloud-pipeline-components.readthedocs.io/en/google-cloud-pipeline-components-1.0.34/google_cloud_pipeline_components.v1.model.html

**Comment by xRagnorokx** [comment]
Was this functionality also added to components that use the uploaded models? For example how would one reference a specific model version (with a version alias) in BatchPredictOp? Maybe I missed it but can't seem to find documentation on this.
