### ISSUE TITLE
Cannot get key for artifact location

### ISSUE THREAD

**Issue by SeibertronSS** [kubeflow/pipelines#8269]
### Environment

*  How do you deploy Kubeflow Pipelines (KFP)?

    I deploy the Kubeflow Pipelines (standalone) by Kubeflow Manifests (https://github.com/kubeflow/manifests)

*  KFP version:

    1.7.0

*  KFP SDK version:
    
    1.8.2

When  I submit a pipeline, I will get the error `This step is in Error state with this message: Error (exit code 1): key unsupported: cannot get key for artifact location, because it is invalid`
![image](https://user-images.githubusercontent.com/69496864/190337738-fdab8af7-f0af-4ba1-9fa2-a7529bc90c7a.png)

The code is as follows
```
import kfp
from kfp.components import create_component_from_func

client = kfp.Client()

def add(a: float, b: float) -> float:
  '''Calculates sum of two arguments'''
  return a + b


add_op = create_component_from_func(
    add, output_component_file='add_component.yaml')



import kfp.dsl as dsl

@dsl.pipeline(
  name='Addition pipeline',
  description='An example pipeline that performs addition calculations.'
)
def add_pipeline(
  a='1',
  b='7',
):
  # Passes a pipeline parameter and a constant value to the `add_op` factory
  # function.
  first_add_task = add_op(a, 4)
  # Passes an output reference from `first_add_task` and a pipeline parameter
  # to the `add_op` factory function. For operations with a single return
  # value, the output reference can be accessed as `task.output` or
  # `task.outputs['output_name']`.
  second_add_task = add_op(first_add_task.output, b)

# Specify argument values for your pipeline run.
arguments = {'a': '7', 'b': '8'}

# Create a pipeline run, using the client you initialized in a prior step.
client.create_run_from_pipeline_func(add_pipeline, arguments=arguments, run_name="add-8")

print("submit pipeline")
```
This problem seems to be related to Minio.

---

Impacted by this bug? Give it a 👍.

**Comment by connor-mccarthy** [comment]
@SeibertronSS, do other pipelines have this error? Have you successfully run a pipeline on this deployment?

It seems like there may be an issue with the deployment related to the [minio artifact secret](https://github.com/kubeflow/pipelines/blob/74c7773ca40decfd0d4ed40dc93a6af591bbc190/manifests/kustomize/third-party/minio/base/mlpipeline-minio-artifact-secret.yaml).
