### ISSUE TITLE
invalid spec: templates.xxx.tasks.condition-1 failed to resolve {{tasks.None.outputs.parameters.yyy}}

### ISSUE THREAD

**Issue by mengxi-ascent** [kubeflow/pipelines#827]
Thanks for the great work.

When I try to use dsl.Condition with user-specified PipelineParam, the condition is translated as tasks.None.outputs.parameters.yyy in the yaml file.
When I try to launch a run of the pipeline in the pipeline-ui, I get the error "invalid spec: templates.xxx.tasks.condition-1 failed to resolve {{tasks.None.outputs.parameters.yyy}}" .
Any idea about that?

Here is a small example:
```
        @dsl.pipeline()
        def define_pipeline(
                is_var_true=dsl.PipelineParam("is_var_true", value="T")
        ):
           with dsl.Condition(is_var_true == 'T'):
               op = dslContainerOp(...)

**Comment by Ark-kun** [comment]
It's a bug that happens when you use `PipelineParam` in the conditional predicate.

**Comment by gaoning777** [comment]
Is it still an issue. I tried the new compiler and it works. 
Feel free to reopen the issue.

**Comment by deepio-oc** [comment]
I still see this issue in the latest code. I tried to run the following pipeline and got this error "invalid spec: templates.skelton-pipeline.tasks.condition-1 failed to resolve {{tasks.xxx.outputs.parameters.xxx-status}}

Here is my code:

`
def skelton_pipeline(counter = 0):

    a_op = comp.func_to_container_op(func_A, base_image=base_image)
    a_task = a_op (counter)

    b_op = comp.func_to_container_op(func_B, base_image=base_image)
    b_task = b_op (a_task.outputs['counter'])

    with dsl.Condition(a_task.outputs['status'] == 0):
        c_op = comp.func_to_container_op(func_C, base_image=base_image)
        c_task = c_op (a_task.outputs['counter'])

`
