### ISSUE TITLE
[feature] Add a progress bar in the DAG UI for long-running tasks

### ISSUE THREAD

**Issue by MainRo** [kubeflow/pipelines#8292]
### Feature Area

/area frontend
/area backend
/area sdk

### What feature would you like to see?

In the UI displaying the DAG of the pipeline, it would be great to see a progress bar on each task. This would allow to visually see how far the task is to completion. In the code of the component, we could provide information on the progress with a dedicated API in the SDK.

### What is the use case or pain point?

It is difficult to estimate how long a task will run. The only option I know, as of today, is to log the progress information.

### Is there a workaround currently?

I add some traces/logs in my task, but this implies looking regularly to the logs of each running task.

---

Love this idea? Give it a 👍.

**Comment by chensun** [comment]
This is infeasible, as each task is a containerized app. KFP system doesn't have visibility into the progress of a task. 
Our suggestion would be use the log workaround as you described.

**Comment by MainRo** [comment]
ok, thanks for answering.
