### ISSUE TITLE
[feature] Stop recurring run when failed

### ISSUE THREAD

**Issue by casassg** [kubeflow/pipelines#8294]
### Feature Area

/area backend 

### What feature would you like to see?

Support for stopping recurring runs (or retry N times) if a run fails.

### What is the use case or pain point?

At the moment, when a recurring run has a failed run, it will continue scheduling new runs independently of previous state. Ideally, we would like to define a custom behaviour were a scheduled run gets retried N times or it stops scheduling new runs after trying to schedule N runs. 

This is mostly for cases where running for date X+1 is counterproducing when X is missing. For example for data processing where you want to make sure that no gaps are missing between segments.

### Is there a workaround currently?

Currently there is some sort of way which is to use an ExitHandler to stop the run by instrospecting into itself  and finding the recurring_run id associated with current run. However that makes it complicated to support. Ideally we make the handling more transparent by doing this on the controller and configuring it from UI.

---

Love this idea? Give it a 👍.

**Comment by chensun** [comment]
This feels like a custom logic that probably shouldn't be part of a scheduling system. Alternatives could be implementing the custom logic yourself either from client side or in component level like using exit handler.

**Comment by casassg** [comment]
@chensun I wonder wdym to implement this from client side? Scheduled runs after they are created as a resource are only checked by the controller itself so not sure how could client perform retries. Unless you mean reimplementing recurring runs from client manually
