### ISSUE TITLE
[sdk] Unable to import ServiceAccountTokenVolumeCredentials in KFPv2 SDK

### ISSUE THREAD

**Issue by zijianjoy** [kubeflow/pipelines#8300]
### Environment

*  KFP version:
KFP 2.0.0-alpha4
*  KFP SDK version: 
2.0.0-beta.4

### Steps to reproduce

Follow https://www.kubeflow.org/docs/components/pipelines/v1/sdk/connect-api/#full-kubeflow-subfrom-inside-clustersub to set the default SA token path as empty. But `ServiceAccountTokenVolumeCredentials` cannot be imported.

From the `__init__.py` file, ServiceAccountTokenVolumeCredentials is not exported: 
https://github.com/kubeflow/pipelines/blob/e14a784327c83e2d7f3e66dc09f4b3af3323cbc7/sdk/python/kfp/client/__init__.py#L17

If we don't import `ServiceAccountTokenVolumeCredentials`, that means by default it should use default SA token path when creating KFP client: `kfp.Client()`. However, this command has failed due to:

```
File /opt/conda/lib/python3.8/site-packages/kfp/client/client.py:372, in Client._get_config_with_default_credentials(self, config)
    360 """Apply default credentials to the configuration object.
    361 
    362 This method accepts a Configuration object and extends it with
    363 some default credentials interface.
    364 """
    365 # XXX: The default credentials are audience-based service account tokens
    366 # projected by the kubelet (ServiceAccountTokenVolumeCredentials). As we
    367 # implement more and more credentials, we can have some heuristic and
   (...)
    370 
    371 # TODO: auth.ServiceAccountCredentials does not exist... dead code path?
--> 372 credentials = auth.ServiceAccountTokenVolumeCredentials()
    373 config_copy = copy.deepcopy(config)
    375 try:

AttributeError: module 'kfp.client.auth' has no attribute 'ServiceAccountTokenVolumeCredentials'
```

### Expected result

User can create KFP client using the default SA token path. User can also configure SA token path to be custom value so KFP SDK can read from a different location. User can configure SA token path to be None, in this case, KFP SDK should be able to use environment variable KF_PIPELINES_SA_TOKEN_PATH.

cc @chensun @connor-mccarthy 

---

Impacted by this bug? Give it a 👍.

**Comment by connor-mccarthy** [comment]
Thank you, @zijianjoy!
