### ISSUE TITLE
[feature] Container start and end times associated with a Pod 

### ISSUE THREAD

**Issue by ameya-parab** [kubeflow/pipelines#8308]
### Feature Area

/area backend 

### What feature would you like to see?

We want to track the start and end times of containers within a pod (Kubeflow Pipeline/Run task). In other words, for better observability, we would like to log the start and end times of the `init`, `wait` and `main` container which are triggered as part of a KFP pod. The `mlpipeline` metabase currently tracks total run and task duration but does not have information on container runtimes.

### What is the use case or pain point?

To improve the observability experience, we would like to track the initialization, wait, and execution time for a Kubeflow pipeline task (preferably in the metabase).

### Is there a workaround currently?

We are currently polling the Kubernetes API server periodically to retrieve container runtimes for a specific Pod (KFP task), but there is a major issue with short lived tasks (<10 seconds), where the Pod's container details are lost if the node on which the Pod was running is scaled down.

---

Love this idea? Give it a 👍.

**Comment by Linchin** [comment]
Hi @ameya-parab, thank you for bringing up this feature request. We recommend using the API from k8s to collect pod info now, and we don't have plans to implement this functionality. Feel free to open this thread if you have more thoughts!
