### ISSUE TITLE
Flaky presubmit step in build-scheduledworkflow-image

### ISSUE THREAD

**Issue by hongye-sun** [kubeflow/pipelines#831]
I frequently get failures like:
build-scheduledworkflow-image:	go: golang.org/x/lint@v0.0.0-20180702182130-06c8688daad7: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /go/pkg/mod/cache/vcs/79f2695321bc515689ad880a6109a13399c003ff78670317e7d502240c43b765: exit status 128:
build-scheduledworkflow-image:		fatal: unable to access 'https://go.googlesource.com/lint/': The requested URL returned error: 502
build-persistenceagent-image:	go: golang.org/x/sync@v0.0.0-20180314180146-1d60e4601c6f: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /go/pkg/mod/cache/vcs/55179c5d8c4db2eaed9fae4682d4c84a1fd3612df666b372bef3bbb997c9601f: exit status 128:
build-persistenceagent-image:		error: RPC failed; HTTP 502 curl 22 The requested URL returned error: 502 Bad Gateway
build-persistenceagent-image:		fatal: The remote end hung up unexpectedly
build-persistenceagent-image:	go: golang.org/x/sync@v0.0.0-20181108010431-42b317875d0f: unknown revision 42b317875d0f
build-persistenceagent-image:	go: error loading module requirements
build-persistenceagent-image:	The command '/bin/sh -c GO111MODULE=on go build -o /bin/persistence_agent backend/src/agent/persistence/*.go' returned a non-zero code: 1
build-persistenceagent-image:	
build-scheduledworkflow-image:	go: error loading module requirements
build-scheduledworkflow-image:	The command '/bin/sh -c GO111MODULE=on go build -o /bin/controller backend/src/crd/controller/scheduledworkflow/*.go' returned a non-zero code: 1
build-scheduledworkflow-image:	

It seems that the https://go.googlesource.com/lint/ is not quite stable. is any way that we can make it more stable, like adding retries?

**Comment by IronPan** [comment]
this seems not happening recently. close for now
