### ISSUE TITLE
[backend] Duplicate volumes are found when running on ACI

### ISSUE THREAD

**Issue by abishek-murali** [kubeflow/pipelines#8318]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?  [Standalone deployment](https://www.kubeflow.org/docs/components/pipelines/v1/installation/standalone-deployment/)

*  KFP version: 1.8.5 (Kubeflow 1.6.0)

*  KFP SDK version: 1.2.0 (and 1.8.14)

### Steps to reproduce
- Running kubeflow job on AKS with virtual node enabled. Trying to run the containers using Azure container instances (ACI)

Logs
```
 api call to https://management.azure.com/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.ContainerInstance/containerGroups/xxxx?api-version=2021-07-01: got HTTP response status code 400 error code "DuplicateVolumes": Duplicate volumes 'kube-api-access-vn5q4' are found.
```

### Expected result

- Run container using ACI  

### Materials and Reference

Known [limitations](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Faks%2Fvirtual-nodes%23known-limitations&data=05%7C01%7Cabishek.murali%40canvass.io%7C8966891c9a864c4459bf08daa1838d8e%7C97332a9ca51844d9892b98b1e9b24b29%7C0%7C0%7C637999883635197847%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Tgf43N7KROmJ2bfCvZxPzJbCrk5Umfup4beRpd86VWo%3D&reserved=0) about ACI

---

Impacted by this bug? Give it a 👍.

**Comment by Linchin** [comment]
Hi @abishek-murali, thank you for reporting the bug. Maybe you can try upgrading the SDK to the version 1.8.14 and see if the error still exist.

**Comment by abishek-murali** [comment]
@Linchin I upgraded to 1.8.14, and the error still exists
