### ISSUE TITLE
Missing PullPolicy for ContainerOp

### ISSUE THREAD

**Issue by akranga** [kubeflow/pipelines#832]
ContainerOp is missing a `pullPolicy`. Happy to make a PR. Souns like a simple change? Or I miss something?

**Comment by gaoning777** [comment]
Sure. Go ahead and send a PR to add the imagepullpolicy in the containerop. Also, do not forget to update the DSL compiler to add the corresponding field in the argo yaml.
Thanks

**Comment by vicaire** [comment]
@hongye-sun Adding Hongye as an FYI.

**Comment by mattiasarro** [comment]
This can now be achieved via

`ContainerOp(container_kwargs={"image_pull_policy": "Always"})`

**Comment by vicaire** [comment]
@akranga, I am assuming that what @mattiasarro indicated resolves your use case. Please reopen if this is not the case.
