### ISSUE TITLE
[sdk] Unable to retrieve runs / experiments / recurring jobs in pipeline component (500 error)

### ISSUE THREAD

**Issue by Lejboelle** [kubeflow/pipelines#8358]
### Environment

*  KFP version:
2.0.0-alpha.5 (Kubeflow 1.6.1)
*  KFP SDK version: 
1.8.14

### Steps to reproduce
My main goal is to retrieve a job name or job id in a recurring run. I tried the PIPELINE_JOB_ID_PLACEHOLDER from the v2 dsl, but that didn't work. Then I tried creating a component that uses the KFP SDK to retrieve the job id, however, it is not possible to even retrieve a list of runs, even though, the token is mounted.
`from kfp import dsl, compiler
from kfp.components import func_to_container_op
import kubernetes.client as k8s
`
`def _print(namespace: str):
    from kfp import Client
    client = Client()

    try:
        print("runs:")
        print(client.list_runs(namespace=namespace))
        print()
    except Exception as e:
        print("failed to get runs")
        print(e)

    try:
        print("pipelines")
        print(client.list_pipelines())
    except Exception:
        print("failed to get pipelines")

    try:
        print("experiments")
        print(client.list_experiments(namespace=namespace))
        print()
    except Exception as e:
        print("failed to get experiments")
        print(e)

print_op = func_to_container_op(_print, packages_to_install=["kfp==1.8.14"])

@dsl.pipeline(
    name="test-pipeline",
)
def test_pipeline():
    vol_sat = k8s.V1ServiceAccountTokenProjection(audience="pipeline.kubeflow.org", expiration_seconds=7200, path="token")
    vol_proj = k8s.V1ProjectedVolumeSource(sources=[k8s.V1VolumeProjection(service_account_token=vol_sat)])
    vol = k8s.V1Volume(name="volume-kf-pipeline-token", projected=vol_proj)
    task = print_op(namespace="{{workflow.namespace}}")
    task.add_pvolumes({"/var/run/secrets/kubeflow/pipelines": vol})
`

### Expected result
The 'list_pipelines' works as expected:
`{'next_page_token': None, 'pipelines': [...], 'total_size': 3}`

But the other return:
`(500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'content-type': 'application/json', 'date': 'Thu, 13 Oct 2022 09:52:55 GMT', 'x-envoy-upstream-service-time': '4', 'server': 'istio-envoy', 'x-envoy-decorator-operation': 'ml-pipeline.kubeflow.svc.cluster.local:8888/*', 'transfer-encoding': 'chunked'})
HTTP response body: {"error":"Internal error: [Unauthenticated: Request header error: there is no user identity header.: Request header error: there is no user identity header., Authentication failure: Unauthenticated: Review.Status.Authenticated is false: Failed to authenticate token review]\nFailed to authorize with API resource references\ngithub.com/kubeflow/pipelines/backend/src/common/util.Wrap\n\t/go/src/github.com/kubeflow/pipelines/backend/src/common/util/error.go:287\ngithub.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).canAccessRun\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/run_server.go:400\ngithub.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).ListRuns\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/run_server.go:192\ngithub.com/kubeflow/pipelines/backend/api/go_client._RunService_ListRuns_Handler.func1\n\t/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2198\nmain.apiServerInterceptor\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/interceptor.go:30\ngithub.com/kubeflow/pipelines/backend/api/go_client._RunService_ListRuns_Handler\n\t/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2200\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1282\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1616\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:921\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581\nFailed to authorize with namespace resource reference.\ngithub.com/kubeflow/pipelines/backend/src/common/util.Wrap\n\t/go/src/github.com/kubeflow/pipelines/backend/src/common/util/error.go:287\ngithub.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).ListRuns\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/run_server.go:194\ngithub.com/kubeflow/pipelines/backend/api/go_client._RunService_ListRuns_Handler.func1\n\t/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2198\nmain.apiServerInterceptor\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/interceptor.go:30\ngithub.com/kubeflow/pipelines/backend/api/go_client._RunService_ListRuns_Handler\n\t/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2200\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1282\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1616\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:921\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581","code":13,"message":"Internal error: [Unauthenticated: Request header error: there is no user identity header.: Request header error: there is no user identity header., Authentication failure: Unauthenticated: Review.Status.Authenticated is false: Failed to authenticate token review]\nFailed to authorize with API resource references\ngithub.com/kubeflow/pipelines/backend/src/common/util.Wrap\n\t/go/src/github.com/kubeflow/pipelines/backend/src/common/util/error.go:287\ngithub.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).canAccessRun\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/run_server.go:400\ngithub.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).ListRuns\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/run_server.go:192\ngithub.com/kubeflow/pipelines/backend/api/go_client._RunService_ListRuns_Handler.func1\n\t/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2198\nmain.apiServerInterceptor\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/interceptor.go:30\ngithub.com/kubeflow/pipelines/backend/api/go_client._RunService_ListRuns_Handler\n\t/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2200\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1282\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1616\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:921\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581\nFailed to authorize with namespace resource reference.\ngithub.com/kubeflow/pipelines/backend/src/common/util.Wrap\n\t/go/src/github.com/kubeflow/pipelines/backend/src/common/util/error.go:287\ngithub.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).ListRuns\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/run_server.go:194\ngithub.com/kubeflow/pipelines/backend/api/go_client._RunService_ListRuns_Handler.func1\n\t/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2198\nmain.apiServerInterceptor\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/interceptor.go:30\ngithub.com/kubeflow/pipelines/backend/api/go_client._RunService_ListRuns_Handler\n\t/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2200\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1282\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1616\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:921\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581","details":[{"@type":"type.googleapis.com/api.Error","error_message":"Internal error: [Unauthenticated: Request header error: there is no user identity header.: Request header error: there is no user identity header., Authentication failure: Unauthenticated: Review.Status.Authenticated is false: Failed to authenticate token review]\nFailed to authorize with API resource references\ngithub.com/kubeflow/pipelines/backend/src/common/util.Wrap\n\t/go/src/github.com/kubeflow/pipelines/backend/src/common/util/error.go:287\ngithub.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).canAccessRun\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/run_server.go:400\ngithub.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).ListRuns\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/run_server.go:192\ngithub.com/kubeflow/pipelines/backend/api/go_client._RunService_ListRuns_Handler.func1\n\t/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2198\nmain.apiServerInterceptor\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/interceptor.go:30\ngithub.com/kubeflow/pipelines/backend/api/go_client._RunService_ListRuns_Handler\n\t/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2200\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1282\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1616\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:921\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581\nFailed to authorize with namespace resource reference.\ngithub.com/kubeflow/pipelines/backend/src/common/util.Wrap\n\t/go/src/github.com/kubeflow/pipelines/backend/src/common/util/error.go:287\ngithub.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).ListRuns\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/run_server.go:194\ngithub.com/kubeflow/pipelines/backend/api/go_client._RunService_ListRuns_Handler.func1\n\t/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2198\nmain.apiServerInterceptor\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/interceptor.go:30\ngithub.com/kubeflow/pipelines/backend/api/go_client._RunService_ListRuns_Handler\n\t/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2200\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1282\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1616\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:921\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581","error_details":"Internal error: [Unauthenticated: Request header error: there is no user identity header.: Request header error: there is no user identity header., Authentication failure: Unauthenticated: Review.Status.Authenticated is false: Failed to authenticate token review]\nFailed to authorize with API resource references\ngithub.com/kubeflow/pipelines/backend/src/common/util.Wrap\n\t/go/src/github.com/kubeflow/pipelines/backend/src/common/util/error.go:287\ngithub.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).canAccessRun\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/run_server.go:400\ngithub.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).ListRuns\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/run_server.go:192\ngithub.com/kubeflow/pipelines/backend/api/go_client._RunService_ListRuns_Handler.func1\n\t/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2198\nmain.apiServerInterceptor\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/interceptor.go:30\ngithub.com/kubeflow/pipelines/backend/api/go_client._RunService_ListRuns_Handler\n\t/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2200\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1282\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1616\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:921\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581\nFailed to authorize with namespace resource reference.\ngithub.com/kubeflow/pipelines/backend/src/common/util.Wrap\n\t/go/src/github.com/kubeflow/pipelines/backend/src/common/util/error.go:287\ngithub.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).ListRuns\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/run_server.go:194\ngithub.com/kubeflow/pipelines/backend/api/go_client._RunService_ListRuns_Handler.func1\n\t/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2198\nmain.apiServerInterceptor\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/interceptor.go:30\ngithub.com/kubeflow/pipelines/backend/api/go_client._RunService_ListRuns_Handler\n\t/go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2200\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1282\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1616\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:921\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"}]}`

Also tried manually loading the credentials using kfp.auth.ServiceAccountTokenVolumeCredentials(path=None) and input those to the client constructor.
When running a notebook using an access-ml-pipeline poddefault, there are no issues, and I'm able to list runs, experiments, etc.

Not sure if this is a bug or a design choice.

Is there no way to retrieve the job id / job name in a recurring run?

Impacted by this bug? Give it a 👍.

**Comment by gkcalat** [comment]
HI @Lejboelle!
It seems that you might have wrong client initialization. Please, follow [these instructions](https://www.kubeflow.org/docs/components/pipelines/v1/sdk/connect-api/).

**Comment by Lejboelle** [comment]
I fixed the issue - it wasn't the client initialization since the defaults point to the correct host and credentials.
I did, however, enter a wrong audience value in the V1ServiceAccountTokenProjection (**pipeline**.kubeflow.org instead of **pipelines**.kubeflow.org).

Closing.
