### ISSUE TITLE
[feature] Support graph sharding to limit the size of each shard

### ISSUE THREAD

**Issue by amrobbins** [kubeflow/pipelines#8374]
### Feature Area

/area frontend

### What feature would you like to see?
Responded to all of these below.
### What is the use case or pain point?
Responded to all of these below.
### Is there a workaround currently?

For my use-case I need to create demand forecasts each night for each of the sku's that belong to a few hundred online stores. If I were to try to run this as a single pipeline, it would fail because it would surpass the size limits for the graph, but also it would be unwieldy due to its size.

To work around this problem, my pipeline has 2 parameters named num_shards and selected_shard. I then use use modulus with the hash of the store's name to shard the jobs. This has gotten me by for a while but with a recent acquisition I now have so many stores that I would need to maintain maybe 50 shards.

So my feature request is to build shard support into kubeflow. The way I am thinking about it, I would specify how many shards that a pipeline should be broken into and then kubeflow would create that many pipeline jobs, each one getting passed its shard number. At the top level, a sharded job would look like a normal pipeline run, but when I click on it, there is another level of page that would show maybe just a simple box representing each shard, with status of passed, failed or running. Then I could click on the box to drill down into the shard's graph to inspect the job.

I am considering trying to get 50 shards manually set up, but it will by kinda messy for this job. I expect that I will need to use a set up like this for a number of features so it's hard to imagine that I'll be able to keep scaling this way for other future jobs that I will need to run for the online stores that we support.

---

Love this idea? Give it a 👍.

**Comment by zijianjoy** [comment]
Hello @amrobbins , I think your request is very similar to `ParallelFor` functionality, and you can define pipeline run inside a pipeline run in KFPv2. Closing this issue now and feel free to reopen it if it doesn't fulfill your requirement.

References:
1. Docs on ParallelFor: https://www.kubeflow.org/docs/components/pipelines/v2/author-a-pipeline/pipelines/#dslparallelfor
1. Example pipeline: https://github.com/kubeflow/pipelines/blob/98c4a22691c31a7988aba41debb8b8f56466fc1b/sdk/python/test_data/pipelines/pipeline_with_parallelfor_parallelism.py
1. Reference docs on ParallelFor: https://kubeflow-pipelines.readthedocs.io/en/2.0.0b6/source/dsl.html#kfp.dsl.ParallelFor

**Comment by amrobbins** [comment]
Hi James,

This feature is actually intended to allow parallel for to scale to process larger jobs. In my case I need to run jobs for a changing set of hundreds of stores. If I were to do this in a single parallel for loop, I would hit the size limit in the screenshot below:

![sizeLimit](https://user-images.githubusercontent.com/17150932/197290471-ffd1604a-0227-4f11-b16b-47f0637d02b3.png)

This issue is also tracked here: [https://github.com/kubeflow/pipelines/issues/3134](https://github.com/kubeflow/pipelines/issues/3134)

It would really help me if 3134 had a resolution, but even if that was fixed it would not solve my issue because I would not be able to really inspect a single execution graph of that size. To get around both issues I break the job into shards, but doing this manually has big drawbacks and if there was another level of page, containing each shard that I could click on to get to the graph, that would really solve the scaling issue that I am up against.

**Comment by amrobbins** [comment]
Hi James,

I responded in a comment with further detail. Would you consider re-opening this issue?

Thanks,
Andrew
________________________________

**Comment by chensun** [comment]
Hi Andrew,

Thank you for the explanation. 

> To get around both issues I break the job into shards, but doing this manually has big drawbacks and if there was another level of page, containing each shard that I could click on to get to the graph, that would really solve the scaling issue that I am up against.

I think the KFP v2 may help mitigate the issue, if not solving it. 
In KFP v2, we added a new feature that enables users to use pipelines within another pipeline ([a simple example demonstrating the use case](https://github.com/kubeflow/pipelines/blob/master/sdk/python/test_data/pipelines/pipeline_in_pipeline_complex.py)). You could possibly do a first pass of sharding of your data, send each shard to run in a sub-pipeline (using ParallelFor), where sub-pipelines could do further sharding. On the UI, the sub-pipelines (aka sub-DAGs) are rendered as single units similar to a component, and you can zoom into/expand the sub-pipelines to see details inside (per current implementation, it will navigate to a separate "tab" UI. Would this be close to what you may wanted?

To try out KFP v2, you need to install KFP 2.0.0a6 (available via [Kubeflow 1.6.1 on GCP](https://github.com/GoogleCloudPlatform/kubeflow-distribution/releases/tag/v1.6.1)), and use KFP SDK 2.0.0beta (latest being [2.0.0b6](https://pypi.org/project/kfp/2.0.0b6/)) to compile your pipeline.

**Comment by amrobbins** [comment]
Thank you for the suggestion. I will try this out and let follow up on this thread.

**Comment by amrobbins** [comment]
Hi I know it has been a while since I requested this feature. I do now have a kubeflow v2 compatible instance (I am using kfp==2.0.0b11, kfp-pipeline-spec==0.2.0, kfp-server-api==2.0.0a6). The pipeline in pipelines feature does seem like it will help in my use case, but when running kubeflow v2, I noticed there were no output logs for ops anymore, here is a screenshot showing what is there:

![kfpv2logs](https://user-images.githubusercontent.com/17150932/214160548-5271518f-6d49-41c9-ad62-29972a0c8717.png)

whereas previously there were more tabs including the "Logs" tab.

![kflogs](https://user-images.githubusercontent.com/17150932/214160947-00b75475-d843-4e94-93f4-b9b430197e5a.png)

Can you confirm that kubeflow 2 will still have the ability to view run logs? Maybe this is just because the version I am using a beta? thanks.

**Comment by zijianjoy** [comment]
Support logs view in KFPv2 is on our radar and currently an work item. cc @jlyaoyuli
