### ISSUE TITLE
Please provide information on how to generate or get API_Keys to us the pipeline endpoints in the documentation

### ISSUE THREAD

**Issue by JV-DHL** [kubeflow/pipelines#8379]
I request you to please provide information on how to generate the API_KEY to use the kubeflow pipelines endpoints in the documentation

**Comment by zijianjoy** [comment]
Hello @JV-DHL , what do you mean by API_KEY and why do you need it? Closing this issue for now since I don't think it is related to KFP at the moment based on current information.

**Comment by JV-DHL** [comment]
I need the API_KEY to use the endpoints like run a pipeline , archive an experiment , get run details etc. Which can be done using kfp_spi_server in python. Though the method isn’t clear for me as in how the API’s can be used .
