### ISSUE TITLE
[feature] Add i18n Support

### ISSUE THREAD

**Issue by Souheil-Yazji** [kubeflow/pipelines#8380]
### Feature Area

/area frontend

### What feature would you like to see?

Include i18n support for Kubeflow Pipelines to allow multilingual support. 

### What is the use case or pain point?

Offering kubeflow pipelines in languages other than English will help non-english native users with the kubeflow pipelines UI.

### Is there a workaround currently?

We host Kubeflow Pipelines at Statistics Canada, we're required to offer a french translation of the frontend, which we use our own [fork](https://github.com/StatCan/kubeflow-pipelines) to implement using i18next.

One major issue is keeping the fork synced with the upstream code base, as we try to keep our hosting of Kubeflow up to date. 

A solution which would benefit the upstream project, our team, and other users would be to merge the i18n work to the upstream repo. I've already seen [a PR for i18n ](https://github.com/kubeflow/pipelines/pull/8137) which shows that other users of kubeflow are interested in internationalization of Pipelines. 

Our fork's current state is 2.0.0-alpha.3 which should integrate with KF1.6 successfully. We are currently implementing the i18n for that release. 

---

Love this idea? Give it a 👍.

**Comment by zijianjoy** [comment]
Please bring i18n support to Kubeflow community (For example: https://github.com/kubeflow/kubeflow/issues/6665).

My feedback is that it will bring difficulty to maintain the i18n up-to-date in long term. Therefore I suggest making i18n an extension than contributing to the main repos.
