### ISSUE TITLE
[bug] GKE preemption inconsistently treated as WorkflowNodeError and WorkflowNodeFailed

### ISSUE THREAD

**Issue by pjo256** [kubeflow/pipelines#8381]
Hello! Unsure if this should be filed with Argo, but we're seeing some inconsistency with error-handling for preemptions. For some context, we run a large number of jobs with preemptible node pools in GKE. We typically don't want to retry application failures, but we always want to retry preemptions. We added a retry policy for `OnError`, and successfully triggered this policy when manually pre-empting nodes (e.g. deleting a node in the node pool). 

When looking at Argo workflows in the cluster, this was recorded as a `WorkflowNodeError` with a `pod deleted` error message and triggered our retry policy. During actual pre-emption, we see `WorkflowNodeFailed` - `Pod was terminated due to imminent node shutdown` - this does not trigger our `OnError` retry policy. 

Typical application failures show as `WorkflowNodeFailed` and do not trigger our retry policy as expected. 

On a related note, it would be useful if we could inspect the workflow status before retrying, or conditionally retry for a subset of failure reasons - not sure if this is already possible. 

### Environment

*  How do you deploy Kubeflow Pipelines (KFP)? GCP AI Platform Managed Pipelines on GKE

*  KFP version: 1.8.5

### Expected result

Node pre-emption should trigger the `OnError` retry policy.

### Materials and reference

---

Impacted by this bug? Give it a 👍.

**Comment by zijianjoy** [comment]
Hello @pjo256 , looks like it is an Argo question, can you create the issue in their repository and link it here? Thank you so much!

**Comment by pjo256** [comment]
Created https://github.com/argoproj/argo-workflows/issues/9880
