### ISSUE TITLE
[frontend] When execution graph gets too big, it is not displayed instead there is a spinning progress indicator that is displayed forever

### ISSUE THREAD

**Issue by amrobbins** [kubeflow/pipelines#8391]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?

I followed the instructs here: https://www.kubeflow.org/docs/distributions/gke/deploy/overview/
*  KFP version: 

v1.5.0

### Steps to reproduce
1. Create a pipeline that includes a parallel for loop
2. Increase the number of pods that the parallel for launches until the issue is observed.

The issue appear as in this screenshot
![spinning2](https://user-images.githubusercontent.com/17150932/198089321-522f3e78-6140-46d2-8636-816f58032d84.png)

### Expected result

The graph would eventually display. This was the case for me prior to upgrading to v1.5.0.

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

**Comment by connor-mccarthy** [comment]
@amrobbins, I suggest using KFP v2. Parallel for loops are represented as subDAGs in v2, which enables the UI to handle them layer-by-layer.
