### ISSUE TITLE
[feature] Automatically pass pod outputs via file system to avoid size limitation

### ISSUE THREAD

**Issue by amrobbins** [kubeflow/pipelines#8394]
### Feature Area

 /area backend

### What feature would you like to see?

I would like kubeflow to pass op output via a file transparently to the user.

### What is the use case or pain point?

I have a need to pass a list of batches of skus as output from an op, but some stores have enough sku's that this exceeds the maximum number of bytes that can be returned by an op, as shown below:

![metadata](https://user-images.githubusercontent.com/17150932/198372610-990b5f25-457f-47b4-a96d-b0525129d6ee.png)

The reference to the list is then passed to a parallel for so that a pod is launched for each batch of skus.

### Is there a workaround currently?

I am not aware of a workaround. I tried to write the sku's into a file instead of returning a list, however it doesn't seem like I can iterate over the contents of the file using a parallel for, so I don't have a way of dynamically determining the batches of skus and launching ops for each.

---

Love this idea? Give it a 👍.

**Comment by connor-mccarthy** [comment]
@amrobbins, can you check to see if you have the same issue in KFP v2? If so, can you please send a reproducible example?

**Comment by amrobbins** [comment]
Yes, I'll be migrating over to kubeflow 2 and I'll provide an updates. Thanks.
