### ISSUE TITLE
[bug] <Component container doesn't start>

### ISSUE THREAD

**Issue by crbl1122** [kubeflow/pipelines#8418]
### Environment

*  How do you deploy Kubeflow Pipelines (KFP)?

*  KFP version:

*  KFP SDK version:

kfp                                   1.8.14
kfp-pipeline-spec                     0.1.16
kfp-server-api                        1.8.5
### Steps to reproduce

I am testing a yaml specified component in a GCP Kubeflow pipeline. The problem is that the component container doesn't start because is searching the "program.py" test module on a different path than the one specifies in Dockerfile as working directory and where the module actually is placed. Please observe that the path reported in the error: " "/src/components/program.py" is different than the one from Dockerfile "/pipelines/component/src". 

`the replica workerpool0-0 exited with a non-zero status of 127. Termination reason: ContainerCannotRun.
Termination log message: failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: exec: "/src/components/program.py": stat /src/components/program.py: no such file or directory: unknown

FROM python:3.9

RUN mkdir -p /pipelines/component/src
WORKDIR /pipelines/component/src
COPY program.py /pipelines/component/src/program.py
COPY input.txt /pipelines/component/src/input.txt

ENTRYPOINT ["python", "program.py"]`

### Labels

---

Impacted by this bug? Give it a 👍.

**Comment by chensun** [comment]
Hi @crbl1122, can you please share how you define the component YAML? Is `/src/components/program.py` coming from the YAML definition?

**Comment by crbl1122** [comment]
Hi @chensun the reference to 'program.py' is made in Dockerfile declaration of workdir and entry point (above). Also please view below the yaml specifications of the two components and pipeline function. The components are load from the yaml files.

%%writefile component_1.yaml
name: component_1
description: Read few lines from local file and forward them 

inputs:
- {name: input1_path, type: String} #
- {name: param1, type: Integer, default: 3, description: 'number of lines to read'}

outputs:
- {name: output1_path, type: String, description: 'output text file'}

implementation:
    container:
        image: ....test_comp_1:latest
        command: [
          /src/components/program.py,
          --input1_path, {inputValue: input1_path},
          --param1,    {inputValue: param1},
          --output1_path, {outputPath: output1_path},
        ]

%%writefile component_2.yaml
name: component_2
description: Read few lines received from component 1 and forward them

inputs:
- {name: input1_path, type: String}
- {name: param1, type: Integer, default: 3, description: 'number of lines to read'}

outputs:
- {name: output1_path, type: String, description: 'output text file'}

implementation:
    container:
        image: ....test_comp_2:latest
        command: [
          /src/components/program.py,
          --input1_path, {inputValue: input1_path},
          --param1,    {inputValue: param1},
          --output1_path, {outputPath: output1_path},
        ]

# build pipeline
@dsl.pipeline(
    name="test-pipeline",
    pipeline_root= "PIPELINE_ROOT",
    description = "test pipeline for container based components",
)

# Define pipeline
def my_pipeline_fn(in_path: str, param1_: int):
   
    task_1 = component_1_op(input1_path = in_path , param1 = param1_)
    task_2 = component_2_op(input1_path = task_1.outputs['output1_path'], param1 = param1_)

**Comment by crbl1122** [comment]
It is not a bug. It was due to  discrepance in path definition between the YAML and Dockerfile files
