### ISSUE TITLE
[Question]  How to save GPU costs in kubeflow pipelines?

### ISSUE THREAD

**Issue by r-matsuzaka** [kubeflow/pipelines#8427]
Excuse me, is it possible to run each step on different node?  
For example, in this case `cifar-preproc` runs on CPU node but `cifar-train` runs on GPU node.  
To save costs, I want to use GPUs only when they are needed to save costs.

![image](https://user-images.githubusercontent.com/76238346/200150043-1d812f97-11e7-4182-96cf-4f244c2f6484.png)

https://cloud.google.com/blog/topics/developers-practitioners/scalable-ml-workflows-using-pytorch-kubeflow-pipelines-and-vertex-pipelines?hl=en

**Comment by Linchin** [comment]
Hi @r-matsuzaka, thank you for your question! We offer component level support for node selection. See reference here: https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.dsl.html#kfp.dsl.BaseOp.add_node_selector_constraint
Please let us know if you have any more questions.
