### ISSUE TITLE
Need to replace Minlo with s3 as an alternative for artifact storage in kubeflow

### ISSUE THREAD

**Issue by SoujanyaSan** [kubeflow/pipelines#8429]
### Feature Area

 /area backend

### What feature would you like to see?

Need to have pipeline manifests,metrics and logs of each pipeline node should be exported to s3 from ml pipelines and also need to retireve from the same for the visualization in the kubeflow

### What is the use case or pain point?

Facing difficulty in disintegrating minio from kubeflow(as by default kubeflow ships with Minlo) 

### Is there a workaround currently?

---

Love this idea? Give it a 👍.

**Comment by Linchin** [comment]
Hi @SoujanyaSan, thank you for bringing up the request. We have a similar feature request here #7878. Please see updates in this request.
