### ISSUE TITLE
[frontend] v2 ui doesn't show error cause

### ISSUE THREAD

**Issue by stobias123** [kubeflow/pipelines#8449]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
* AWS Manifests.
https://www.kubeflow.org/docs/pipelines/installation/overview/. -->
*  KFP version: 
gcr.io/ml-pipeline/frontend:2.0.0-alpha.5
To find the version number, See version number shows on bottom of KFP UI left sidenav. -->

### Steps to reproduce

Run this pipeline.
https://github.com/kubeflow/pipelines/blob/master/samples/v2/lightweight_python_functions_v2_pipeline/lightweight_python_functions_v2_pipeline.py

After fixing a few parameter naming issues, it runs, and fails without showing why. (In my case it was b/c of bucket issues, but i have to go to logs)

### Expected result

See logs and understand why it fails.

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

**Comment by jlyaoyuli** [comment]
Hi @stobias123 , thank you for reaching out. Currently KFP v2 is in the alpha phase, and the fix is what we are currently working on.

**Comment by jlyaoyuli** [comment]
Hello @stobias123, we are happy to share that the logs feature is already included in our latest release (https://github.com/kubeflow/pipelines/releases/tag/2.0.0-rc.1). Please give a try and let us know where we can improve on our system! Also, Feel free to re-open this issue if you have any question!
