### ISSUE TITLE
kfp component can not access gpu (on premise)

### ISSUE THREAD

**Issue by TranThanh96** [kubeflow/pipelines#8451]
### Environment

ubuntu 20-04
cluster k3s: 1 node gpu: https://www.kubeflow.org/docs/components/pipelines/v1/installation/localcluster-deployment/#1-setting-up-a-cluster-on-k3s
deployed gpu-operator

### Steps to reproduce

this is code check:
```
import kfp
from kfp import dsl

def gpu_smoking_check_op():
    return dsl.ContainerOp(
        name='check',
        image='tensorflow/tensorflow:latest-gpu',
        command=['sh', '-c'],
        arguments=['nvidia-smi']
    ).set_gpu_limit(1)

@dsl.pipeline(
    name='GPU smoke check',
    description='smoke check as to whether GPU env is ready.'
)
def gpu_pipeline():
    gpu_smoking_check = gpu_smoking_check_op()

if __name__ == '__main__':
    arguments = {}

    client.create_run_from_pipeline_func(
        gpu_pipeline, 
        arguments=arguments)
```

and this is result: sh: 1: nvidia-smi: not found
![image](https://user-images.githubusercontent.com/26323599/201849120-27970509-3898-4e41-a1b8-6ca4d1920eb2.png)

all pods are running:
![image](https://user-images.githubusercontent.com/26323599/201849255-ee024079-4089-4dd8-bdbf-ba34fdcf91ed.png)

nvidia-docker check ok:
![image](https://user-images.githubusercontent.com/26323599/201849317-803140fb-0f80-4116-ae18-1c1f99dc654d.png)

How can I access gpu on kfp?

**Comment by jlyaoyuli** [comment]
Hello @TranThanh96 , 
Here is the instruction of enabling GPU: https://www.kubeflow.org/docs/distributions/gke/pipelines/enable-gpu-and-tpu/
Maybe you were missing `gpu_op.add_node_selector_constraint()`
