### ISSUE TITLE
[pipelines]why user can see all pipelines from other member 

### ISSUE THREAD

**Issue by hellobiek** [kubeflow/pipelines#8460]
kubeflow 1.5
kfp 1.8.12

why user can see all pipelines from other member?

**Comment by jlyaoyuli** [comment]
Hi @hellobiek , namespace for pipeline is working in progress. 
https://github.com/kubeflow/pipelines/issues/4197

**Comment by hellobiek** [comment]
@jlyaoyuli  thank you.
