### ISSUE TITLE
[frontend] Archived experiments do not show up in archived list

### ISSUE THREAD

**Issue by Linchin** [kubeflow/pipelines#8483]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
KFP standalone

*  KFP version: 
Self built based on #8480 

### Steps to reproduce
Since this bug only appeared after PR #8480, maybe it's more reasonable to investigate after it is merged. 
Here are the steps:
1. Create an experiment using v2 api
2. Archive this experiment
3. On the frontend, the archived experiment still appears in the active experiments list. It's not present in the archived experiments list
4. However, if you click into this archived experiment, the button says "Restore", which means FE acknowledges that the experiment is archived.
5. This might be because the v2 api uses a different `StorageState` that is generated from the v2 proto

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

**Comment by jlyaoyuli** [comment]
#8864
