### ISSUE TITLE
[frontend] Image reference specifying tag with digest should work

### ISSUE THREAD

**Issue by doctapp** [kubeflow/pipelines#8490]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)? Google Vertex AI
*  KFP version: 1.8.6 (Python 3.10.6)

### Steps to reproduce

Use image reference containing both tag and digest, e.g., `gcr.io/some-project-id/some-product:0.0.1@sha256:0123456789abcedf0123456789abcedf0123456789abcedf0123456789abcedf`

### Expected result

Pipeline should run but receiving `google.api_core.exceptions.InvalidArgument: 400 Invalid image URI gcr.io/some-project-id/some-product@sha256:0123456789abcedf0123456789abcedf0123456789abcedf0123456789abcedf` instead.

### Materials and Reference

Using either tag (e.g., `gcr.io/some-project-id/some-product:0.0.1`) or digest (e.g., `gcr.io/some-project-id/some-product@sha256:0123456789abcedf0123456789abcedf0123456789abcedf0123456789abcedf`) works.

Expected image reference including both tag and digest is very useful for identifying correct images which is complex with just using digest.

Example stack trace:

```
Traceback (most recent call last):
  File "/home/user/product/venv/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 72, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/user/product/venv/lib/python3.10/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/user/product/venv/lib/python3.10/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Invalid image URI gcr.io/some-project-id/some-product@sha256:0123456789abcedf0123456789abcedf0123456789abcedf0123456789abcedf."
	debug_error_string = "UNKNOWN:Error received from peer ipv4:172.217.13.106:443 {grpc_message:"Invalid image URI gcr.io/some-project-id/some-product@sha256:0123456789abcedf0123456789abcedf0123456789abcedf0123456789abcedf.", grpc_status:3, created_time:"2022-11-22T00:00:00.000000000+00:00"}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/product/venv/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 74, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.InvalidArgument: 400 Invalid image URI gcr.io/some-project-id/some-product@sha256:0123456789abcedf0123456789abcedf0123456789abcedf0123456789abcedf.
```

Thanks!

---

Impacted by this bug? Give it a 👍.

**Comment by gkcalat** [comment]
Hi @doctapp,
Can you share what client are you using and how you submitted the job?

**Comment by doctapp** [comment]
Hi @gkcalat,
using Python 3.10.6, google_cloud_aiplatform 1.18.3 and kfp 1.8.16.

As for how the image is set:
```
@dsl.component
def some_func(...): ...
...
some_fun.component_spec.implementation.container.image = 'gcr.io/some-project-id/some-product:0.0.1@sha256:0123456789abcedf0123456789abcedf0123456789abcedf0123456789abcedf'
...
@dsl.pipeline(...):
def pipeline(...):
  some_func(...)
...
from kfp.v2 import compiler
compiler.Compiler().compile(pipeline_func=pipeline, package_path='pipeline.json')
job = PipelineJob(
        display_name='test',
        template_path='pipeline.json',
        parameter_values=...,
        enable_caching=enable_caching,
    )
job.submit(service_account=...)
```

That's the high-level :) Please let me know if you need more info.

Thanks

**Comment by zijianjoy** [comment]
Hello @doctapp , I am wondering what should the expected behavior to be when the image tag and digest are pointing to different images. It might cause confusion to which image is actually used in the pipeline run. I am leaning towards keeping only digest or tag when you are referring an image. Please let me know if you don't agree.

/cc @chensun

**Comment by doctapp** [comment]
@zijianjoy Please use digest when both are specified and no need to check (could log a warning if there's a mismatch if that's something you want to implement but don't need this check). It's way more useful to specify both tag and digest since it provides context particularly when debugging and is safe when the digest is added to the tag by automation. Leave it to users to decide how to interpret both and let kubeflow use digest when both are specified.
Thanks

**Comment by connor-mccarthy** [comment]
@doctapp, it looks like your error is surfacing from job submission via the Vertex SDK (`google.cloud.aiplatform`). Please consider opening an issue in that repository: https://github.com/googleapis/python-aiplatform.

**Comment by doctapp** [comment]
Raised https://github.com/googleapis/python-aiplatform/issues/1861
