### ISSUE TITLE
[feature] kfp.component to accept tuples/lists of component outputs as args

### ISSUE THREAD

**Issue by sradc** [kubeflow/pipelines#8491]
### Feature Area

/area sdk

### What feature would you like to see?

The ability to pass in a list/tuple of `component.output` as an arg to a component. E.g. so that examples like the following work:

```python
from kfp.v2 import compiler, dsl

@dsl.component
def my_transformer_op(item: str) -> str:
    return item + "_transformed"
 
@dsl.component
def my_aggregator_op(args: list) -> str:
    return " ".join(args)

@dsl.pipeline("aggtest", "agg test")
def dynamic_pipeline():
    transformed_vals = []
    for x in ["a", "b", "c"]:
        transformed_vals.append(my_transformer_op(x))
    my_aggregator_op([x.output for x in transformed_vals])

compiler.Compiler().compile(pipeline_func=dynamic_pipeline, package_path="my_pipeline.yaml")
```

```
TypeError: Object of type PipelineParam is not JSON serializable
```

(Looking at [this](https://stackoverflow.com/a/63219053) stackoverflow post, seems this kind of thing was possible in v1; but seems it's not possible in v2?)

### What is the use case or pain point?

For aggregating results, e.g. see [this](https://sidsite.com/posts/kubeflow-hyperparam-opt/) example of hyperparameter optimization, and the screenshots attached below.

### Is there a workaround currently?

*Yes*. There are workarounds. For example, I created a hacky workaround, that modifies the source code of a function, to expand args annotated with PseudoList into actual args of the function, and then add lines to the function def to collect these into tuples with the original name of the arg. (Using ast/inspect.)

Source code here: https://github.com/sradc/kubeflow_hyperparam_opt_example/blob/b3ef4d7e01055e27011a4d1311cf9adccf37869e/pseudo_tuple_component.py

Example of using it here (there's also an example in blog post linked above): https://github.com/sradc/kubeflow_hyperparam_opt_example/blob/41bc48e31407f79fbbcd07b39ea82586a5a71562/pseudo_tuple_example.ipynb 

Will also reproduce the example here:

```python
from kfp.v2 import compiler, dsl

from pseudo_tuple_component import PseudoTuple, pseudo_tuple_component


MY_LIST = ["a", "b", "c"]
PIPELINE_NAME = "pseudo-tuple-example"

@dsl.component
def my_transformer_op(item: str) -> str:
    return item + "_transformed"
 
@pseudo_tuple_component(globals_=globals(), locals_=locals())
def my_aggregator_op(args: PseudoTuple(len(MY_LIST), str)) -> str:
    return " ".join(args)

@dsl.pipeline("aggtest", "agg test")
def dynamic_pipeline():
    transformed_vals = []
    for x in MY_LIST:
        transformed_vals.append(my_transformer_op(x).output)
    my_aggregator_op(*transformed_vals)

compiler.Compiler().compile(pipeline_func=dynamic_pipeline, package_path=f"{PIPELINE_NAME}.json")
```

To show more explicitely how the function is modified:

```python
from pseudo_tuple_component import expand_PseudoTuple_annotated_args_to_str


def my_aggregator_op(args: PseudoTuple(len(MY_LIST), str)) -> str:
    return " ".join(args)


new_source_code_for_func = expand_PseudoTuple_annotated_args_to_str(
    my_aggregator_op, globals_=globals(), locals_=locals()
)
print(new_source_code_for_func)
```

```
def my_aggregator_op(args_0: str, args_1: str, args_2: str) -> str:
    args = (args_0, args_1, args_2)
    return ' '.join(args)
```

---

This is related to issues:
- https://github.com/kubeflow/pipelines/issues/1933
- https://github.com/kubeflow/pipelines/issues/3412

---

This is the kind of thing you could do (taken from [here](https://sidsite.com/posts/kubeflow-hyperparam-opt/), using my workaround):

![Screenshot 2022-11-22 at 22 27 04](https://user-images.githubusercontent.com/17290057/203434169-909d39dd-dbfb-45eb-b0fd-b78a42751f03.png)

![pseudo_tuple_example](https://user-images.githubusercontent.com/17290057/203435052-47bd3f09-7d76-4afc-b79a-c95b4ae0f05b.png)

---
 
Love this idea? Give it a 👍.

**Comment by connor-mccarthy** [comment]
Hi @sradc. Thanks for suggesting this. We definitely want to enable expression of more complex topologies like the ones you show.

Right now we're working on three separate designs/implementations related to this feature request:
- Support for lists of artifacts
- Support for fan-in from `dsl.ParallelFor`
- Support for fanning-in outputs from multiple `dsl.Condition` branches (possibly support for elif/else conditions too), such as similar to the following:

Do these WIP features collectively enable you to express the types of pipeline topologies you wish to express?

**Comment by sradc** [comment]
Looks like this has been added (I haven't tried it yet); https://github.com/kubeflow/pipelines/pull/8631

**Comment by connor-mccarthy** [comment]
Hey, @sradc. Fan in of parameters from `dsl.ParallelFor` has been added. The other features (fan-in of artifacts) and collection from `dsl.Condition` are coming soon.
