### ISSUE TITLE
[bug] Issue with ImageDatasetCreateOp

### ISSUE THREAD

**Issue by wardVD** [kubeflow/pipelines#8500]
### Environment

*  KFP SDK version:
2.0.0b4

### Steps to reproduce

Run https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/pipelines/google_cloud_pipeline_components_automl_images.ipynb

No issues on `kfp==1.8.13`

Issue: 
![image](https://user-images.githubusercontent.com/2136274/204304592-f6078988-9c68-43d7-8ff0-826e09f803f3.png)

---

Impacted by this bug? Give it a 👍.

**Comment by zijianjoy** [comment]
Currently Google Cloud Pipeline Component hasn't been migrated to KFP SDK V2, so it is a work-in-progress.

/cc @connor-mccarthy

**Comment by dmytro212** [comment]
@wardVD can you share your email
