### ISSUE TITLE
[feature] S3 Integration for Artifact Storage (IRSA)

### ISSUE THREAD

**Issue by ryansteakley** [kubeflow/pipelines#8502]
## S3 Integration for Artifact Storage (IRSA)
As of Kubeflow pipelines 2.0-alpha6 release, using IRSA for artifact storage in S3 is not fully supported(details later in the doc). There has been a long-running thread with high-interest for this functionality in the[ kubeflow pipelines github](https://github.com/kubeflow/pipelines/issues/3405). These proposal aims to address it.
 
To support using IRSA with S3, we want to add the[ AWS JS SDK credentials](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_credential_providers.html) module to the frontend container image and update the[ aws-helper](https://github.com/kubeflow/pipelines/blob/4bb57e6723b7a5c2eb685536e5a293aea87bd3a1/frontend/server/aws-helper.ts) to use credentialProviderChain function from the AWS JS SDK.

**Please read the following [design document](https://docs.google.com/document/d/1kWbenzENgj2SE8oKshiu_MMzZuBqfZ8Iv1LQSmwJD7E/edit?usp=sharing&resourcekey=0-DxxoE1CFqJkUeSYpEBKfmg) to better understand the reasoning and use-case behind this feature**.

---
/area frontend 
Love this idea? Give it a 👍.

**Comment by surajkota** [comment]
Hi @james-jwu, @zijianjoy Can you please tag Jo Li/people from frontend side to review this proposal

cc @chensun

**Comment by surajkota** [comment]
@jlyaoyuli

**Comment by surajkota** [comment]
Hi @gkcalat, I believe @ryansteakley is interested to contribute this functionality. Shall we go ahead with the PR?
@jlyaoyuli let us know if you have any comments

**Comment by ryansteakley** [comment]
resolved by #8651 merged, thanks everyone!
