### ISSUE TITLE
[feature] Support different ServiceAccounts for each component (least privilege)

### ISSUE THREAD

**Issue by agilgur5** [kubeflow/pipelines#8524]
### Feature Area

/area sdk

### What feature would you like to see?

I would like to be able to configure different k8s `ServiceAccount`s for each component in my pipeline.

### What is the use case or pain point?

Main examples are for integrations:
1. Let's say I want to run the Spark Operator in one of my components, then I need to give that component RBAC access to the `SparkApplication` CR. _But_, I don't want to allow my other components access to `SparkApplication` CRs.
2. Let's say I want one of my components to access secrets from Vault's CSI Driver, then I need to give that component RBAC access to PSPs for CSI (in older k8s versions). _But_, I don't want to allow my other components access to CSI.

Basically, limiting to **least privilege** RBAC per component.
In secured environments with a component catalog, an example of usage here would be that anything that requires RBAC has to go through the component catalog -- i.e. any integrations that require RBAC are through secured components.

### Is there a workaround currently?

All components must be given the same `ServiceAccount` with RBAC allowed for all. So if I only have _one_ component that needs to integrate with Spark, _all_ components are given access to Spark.
This does not fit least privilege security paradigms, causing many components to have extra unnecessary permissions, widening the attack surface area unnecessarily.

## Additional Details

Argo Workflows does currently allow different `ServiceAccount`s per Workflow, and there exists a workaround to allow different `ServiceAccount`s per step: https://github.com/argoproj/argo-workflows/issues/2053. So this is already possible in Argo Workflows, it just needs support in Kubeflow Pipelines.

I would be more than happy to contribute this work as it's critical to a few teams that I work with. I may also contribute to an official feature in Argo for this as well (so that the workaround is not necessary)

---

Love this idea? Give it a 👍.

**Comment by zijianjoy** [comment]
Hello @agilgur5 , thank you so much for bringing this up and offering to contribution. If you can write a design doc about how you plan to implement the per-component service account feature, and get it reviewed by Pipelines Working Group (Join the Pipelines Community Meeting), we can review and approve it for enabling the implementation. Thank you!

**Comment by agilgur5** [comment]
Hi @zijianjoy, thanks for the quick response!

> If you can write a design doc about how you plan to implement the per-component service account feature

So _originally_ I was hoping to get some guidance on where in the codebase to look/start from for this feature (which I would need to understand a good bit before proposing a Design Doc, depending on the level of implementation details expected).

But I managed to find a decent bit myself, and I think this might actually be a simpler contribution than I first thought.

## `podSpecPatch` is already used

In particular, I found that [`podSpecPatch`](https://github.com/kubeflow/pipelines/blob/217cbd9e6e0c79316bb98c005e3154cea08afb71/backend/src/v2/compiler/argocompiler/container.go#L210) is _already_ used by the compiler. The workaround for per-step `ServiceAccount`s in Argo Workflow [also uses `podSpecPatch`](https://github.com/argoproj/argo-workflows/issues/2053#issuecomment-827120183).

I see #4877 requested it and I looked through the implementation to support GPU requests in #5972. 

Based on the code there and the existing support in the compiler, it seems like this feature might actually only require changes to the SDK to expose a `ServiceAccount` configuration (and not the compiler or backend as I originally anticipated). Does that sound about right to you?

I need to read through a bit more, but if so, this might only require a small PR similar to #5972 to implement. If that is the case, would a Design Doc + Pipelines WG review be necessary for this? Or could I just go straight to PR if the source changes are limited in scope to say < 50 LoC source in the SDK only?

I can probably work in a Design Doc + Community Meeting if needed, but that needs a bit more scheduling/synchronous coordination 😅

**Comment by zijianjoy** [comment]
We need to make sure that your contribution still works in KFP v2, would you like to take a closer look and see if the proposed change is valid in the KFPv2 syntax? https://www.kubeflow.org/docs/components/pipelines/v2/

**Comment by agilgur5** [comment]
Yea as far as I could tell, a `set_service_account` function would be compatible with both versions

**Comment by zijianjoy** [comment]
I think there are two main points to be considered:
1. In KFP v2, we are using PipelineSpec to define a pipeline template: https://github.com/kubeflow/pipelines/blob/217cbd9e6e0c79316bb98c005e3154cea08afb71/api/v2alpha1/pipeline_spec.proto#L50. In your design, you mention that we only need to change KFP SDK, how do we represent service_account for individual steps in PipelineSpec proto?
2. Users currently can set service account for the whole pipeline run when you are creating a new run, that means you can execute the same pipeline template using different service account. Why do you think we should follow the pattern of `set_gpu_limit()` to set service account during pipeline compile time?

**Comment by agilgur5** [comment]
Gonna answer these out of order as I think they're dependent on each other:

> 2\. Why do you think we should follow the pattern of `set_gpu_limit()` to set service account during pipeline compile time?

2. For the same reason why something like `set_gpu_limit()` exists: one may set each _component_ to have a different limit, and the same for Service Accounts (per opening comment). Since each component can have a different Service Account for least privilege, a component needs to be able to be configured with a Service Account. Depending on the Pipeline itself it runs in and _where_ that Pipeline runs (etc), the component may need a different Service Account.
Also, the current way to set Service Accounts in Argo Workflows relies on using `podSpecPatch`.
I don't think there's as much need for that to change based on other component's outputs/results like `set_gpu_limit`, but that use-case is possible too.

> 1. In KFP v2, we are using PipelineSpec to define a pipeline template:

1. Thanks for the `proto` reference, I wasn't aware of that!
Based on 2., it would be the same as how `set_gpu_limit` is configured right now, which does not have an explicit named configuration
As far as I understand -- please correct me if I'm wrong, I'm much more familiar with the underlying Argo Workflows spec than KFP's own spec and so may very well have gaps here -- this is just an `input` to the component (which can have a default value). Since a component effectively wraps a singular AW `template`, the `template` must accept as `input` anything that can be parametrized, as it can be used in many different Pipelines (workflows in AW terms).

**Comment by agilgur5** [comment]
Correction on the above 1., I do seem to have misunderstood the `proto` a bit. My eyes seemed to have glossed over the `PipelineContainerSpec` last night because I woke up and immediately thought I missed something then found it 😅 Apologies for my misunderstanding as a first-time contributor to this project.

1. Based on my re-read of the `proto`, it looks like a `ServiceAccount` would likely be defined under `PipelineContainerSpec`:
https://github.com/kubeflow/pipelines/blob/217cbd9e6e0c79316bb98c005e3154cea08afb71/api/v2alpha1/pipeline_spec.proto#L652
Same as where `cpu_limit` and `AcceleratorConfig` (i.e. GPU config) are currently.
The naming is a bit off though because `ServiceAccount` / `serviceAccountName` is actually a field on the Pod, not a container... hmm... 💬

Based on that, that does make it sound like it _may_ need a spec change for v2, unless I'm misunderstanding something again.
When I looked at the compiler code before though, I did see that [`podSpecPatch`](https://github.com/kubeflow/pipelines/blob/217cbd9e6e0c79316bb98c005e3154cea08afb71/backend/src/v2/compiler/argocompiler/container.go#L210) was already used and defined as an `input` so I feel like I'm still missing something here.

If that _does_ require a spec change, then yea a Design Doc would absolutely be understood in that scenario. _Especially_ so if, for proper naming/nesting, a `PipelinePodSpec` would have to wrap the `PipelineContainerSpec`, as that's definitely a larger change 😅

Would appreciate any further guidance or links/references here! And again, please correct me if I'm wrong in my understanding anywhere above!

**Comment by zijianjoy** [comment]
Thank you @agilgur5 for the detailed answers and your thinking process!

To share more information, I would like to suggest this reading for KFPv2 system design: https://docs.google.com/document/d/1fHU29oScMEKPttDA1Th1ibImAKsFVVt2Ynr4ZME05i0/edit.

------

To give a high level summary of difference between KFPv1 and v2:

KFP V1:

SDK compiles Pipeline Template (`ArgoWorkflow CR`) -> Backend deploys `ArgoWorkflow CR` with runtime parameters -> Finish.


KFP V2:

SDK compiles Pipeline Template (`PipelineSpec`) -> Backend translates `PipelineSpec` with `RuntimeConfig` to `ArgoWorkflow CR` -> Backend deploys `ArgoWorkflow CR` -> Finish. 


-------

As you have noticed, we are looking for information as followed in a design doc:
1. Do we set service account at the compile time, or at runtime?
2. What should be the level of granularity for service account setting? (component level, pod level, container level, pipeline level, or others?) Note that a pipeline can run within a pipeline (We sometimes call this concept as sub-DAG).
3. When there is a conflict of service account configuration, which one takes higher priority? (You can set service account for the whole run at runtime currently. If a component inside has a different service account at compile time, which service account should it choose?)
4. Based on the decision above, what is the proposed proto change in `PipelineSpec`?

-------

Hope that this information is helpful! It will be easier to discuss these topics in a design doc.

**Comment by agilgur5** [comment]
Just wanted to quickly note that I'm still engaged here and this is now on my main team's JIRA board.

My family caught COVID etc so it's been a bit of a hectic new year 😅

I'll have a response soon with some questions and am working on a design doc in the next week or so

**Comment by starpit** [comment]
heya, any status updates here?

**Comment by agilgur5** [comment]
I got COVID shortly after my previous comment and got the rough end of it. Then got re-org'd at work (again) and headed up a new team, on top of other corporate things, so this dropped pretty far down on the priority list as a result unfortunately 😕 

I have been doing more OSS work recently and did some work on the upstream issue recently, discovering that it seems to already be implemented(??): https://github.com/argoproj/argo-workflows/issues/2053#issuecomment-1597524593

I'm hoping I can get back to Kubeflow work ~next week, but tbd

**Comment by agilgur5** [comment]
Thought I'd update here that I'm no longer working on a team that actively uses Kubeflow, so I've been contributing less here. Anyone feel free to take this on.

Simultaneously, I have become an active contributor in upstream Argo Workflows, so can certainly help with any integration. This does indeed already work upstream (you'll notice I myself closed the issue as I now have some permissions upstream)
