### ISSUE TITLE
[feature] Documentation around specifying pod configuration for components (e.g. volume mounts/pod affinity etc) in v2

### ISSUE THREAD

**Issue by elibixby** [kubeflow/pipelines#8527]
### Feature Area

/area samples

### What feature would you like to see?

It's unclear from documentation to what extent you should be able to configure the pod that run a given task in v2. In v1 the [BaseOp](https://github.com/kubeflow/pipelines/blob/1.8.16/sdk/python/kfp/dsl/_container_op.py#L810) class seems to suggest that most aspects of a pod are configurable within the pipeline but this functionality seems to completely disappear in v2 with the move to `ComponentSpec` which seems to have no such configuration fields. Is this still possible? Some documentation on customizing pod fields would help here.

### What is the use case or pain point?

Many steps for my use case require specific pod affinity, tolerances, and premounted volumes etc. It is unclear how to do that in the context of v2 pipelines.

---

Love this idea? Give it a 👍.

**Comment by connor-mccarthy** [comment]
Hi, @elibixby. Please see a description of plans to support this in KFP SDK v2 here: https://github.com/kubeflow/pipelines/issues/8570#issuecomment-1349057570

**Comment by elibixby** [comment]
Do I read this correctly that the plan is to be platform agnostic even outside of Kubernetes? I'm really skeptical that a workflow library can be built that actually supports real use cases without providing access to at least the level of abstraction that Kubernetes already provides, and am disappointed to hear that kubeflow is moving in that direction.

**Comment by connor-mccarthy** [comment]
@elibixby, thanks for expressing your concern. Hopefully the following resolves some of your questions:

The _pipeline topology_ itself will be platform agnostic (this is represented in PipelineSpec IR). Each node/task in the pipeline can have features bound to it. Features that aren't specific to a particular executing backend (environment variables, display name, retry behavior, etc.) will be represented directly in IR.

Features that are are tied to a particular backend (either by concept or by API/specification) will be will _still be exposed and configurable_, but not represented directly in IR YAML (they will be represented alongside IR YAML). This enables feature parity with v1 Kubeflow concepts in the KFP SDK, while still maintaining cross-platform portability of the core pipeline definition.

In the case of Kubernetes, Kubernetes concepts will be exposed via the `kfp.kubernetes` subpackage _within_ the KFP SDK library (see [example](https://docs.google.com/document/d/10Cx-B18V6gR35VOmTe8_8gB67srOFF_un7NN8qXP1T4/edit#heading=h.etyis0olf88a)).

From a pipeline authoring standpoint, you will still be able to author the same pipeline using Kubernetes-specific abstractions once this work is complete, but your code will merely look a little different (slightly less object oriented) and the YAML file containing your pipeline (which is largely implementation detail) will represent these features differently.

**Comment by elibixby** [comment]
Does this mean KubeFlow will be moving away from using Argo as the workflow system? Because the comparative complexity of the Python SDK my team is strongly considering using KubeFlow operators for caching etc but authoring pipelines with another Argo frontend (e.g. Hera). This currently seems to work quite well.

It sounds like this will stop working if you move to a custom IR? If so I hope there are plans to pull out the components that add useful functionality to Argo as separate projects for those of us who don't care about platform agnosticism.

**Comment by connor-mccarthy** [comment]
> Does this mean KubeFlow will be moving away from using Argo as the workflow system?

KFP SDK v2.x.x is moving to writing custom IR, which is submitted to the KFP BE and compiled to Argo by the KFP BE. This is already how the v2 namespace behaves in KFP SDK v1.x.x. KFP SDK v2.x.x promotes this to the primary authoring style.

> I hope there are plans to pull out the components that add useful functionality to Argo as separate projects

The `sdk/release-1.8` will continue to hold the latest KFP SDK v1.8.x changes and, despite focusing development efforts on KFP SDK v2.x.x, we have continued to release KFP SDK v1 patch versions. You can continue to `pip install kfp==1.8`.

Furthermore, the KFP v2 BE will still accepts Argo workflow.
