### ISSUE TITLE
Switch default package format to .zip

### ISSUE THREAD

**Issue by IronPan** [kubeflow/pipelines#854]
.zip is better compatible with mac OSX in case of file selecting window. 
We should switch default pipeline package format to .zip instead of .tar.gz
- DSL compile into a .zip
- API accept .zip in addition to what is supported now.

**Comment by gaoning777** [comment]
DSL generating the zip file: https://github.com/kubeflow/pipelines/pull/855

**Comment by vicaire** [comment]
Can we close this issue?
