### ISSUE TITLE
[Bazel support] <Will support bazel build for Kubeflow>

### ISSUE THREAD

**Issue by xushaoxiao** [kubeflow/pipelines#8555]
### Bazel build is good

Whether to consider supporting bazel build ?

**Comment by connor-mccarthy** [comment]
Thanks, @xushaoxiao. We've supported bazel in the past, but it slowed down development velocity and required extra effort to maintain. This is not something we are looking to support at this time.

Here is a bit of context: https://github.com/kubeflow/pipelines/issues/3250

cc @chensun
