### ISSUE TITLE
[New feature] Can not use the output_loop_item as a display name for a task.

### ISSUE THREAD

**Issue by MinhManPham** [kubeflow/pipelines#8564]
### Environment
*  KFP version:
kfp==1.8.16
*  KFP SDK version:
kfp                           1.8.16
kfp-pipeline-spec             0.1.16
kfp-server-api                1.8.5

### Steps to reproduce

```
def pipeline(countries, start, end, model_types):
    get_countriest_task = get_countriest_op(countries=countries)
    with dsl.ParallelFor(get_countriest_task.output) as country_code:
        download_data_task = download_data_op(
            country_code=country_code, start_date=start, end_date=end
        ).set_display_name(str(country_code))
```

### Expected result

I expect in the UI, each component's name is corresponding to the `country_code`.

### Materials and reference

Code for download_data_op:

```
def get_countriest(countries:str) -> str:
    import json
    countries= countries.split(",")
    return json.dumps(countries)
```

### Actual result

![image](https://user-images.githubusercontent.com/65837910/206959170-00c14224-205f-4c01-843c-f2286160a434.png)

---

Impacted by this bug? Give it a 👍.

**Comment by chensun** [comment]
This is currently be design, `set_display_name` doesn't support runtime value an this moment.
