### ISSUE TITLE
[bug] component VertexNotificationEmailOp fails when there are 2-level chained conditions

### ISSUE THREAD

**Issue by rikardocorp** [kubeflow/pipelines#8580]
Message Error:

<_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "Internal error encountered."
	debug_error_string = "{"created":"@1671108949.152751032","description":"Error received from peer ipv4:142.250.125.95:443","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"Internal error encountered.","grpc_status":13}"
>

The above exception was the direct cause of the following exception:

**Comment by tarrade** [comment]
Got the same issue. We should have a fix for Vertex AI on GCP. The fix will need 3 weeks to be deployed.
https://issuetracker.google.com/issues/274611724

**Comment by tarrade** [comment]
On my side, it is now working in europe-west4. Look like GCP team fully deployed the fix
