### ISSUE TITLE
[components] ModelBatchPredictOp params PipelineParams not iterable

### ISSUE THREAD

**Issue by telpirion** [kubeflow/pipelines#8591]
## Environment

*  KFP version:

Vertex Pipelines

*  KFP SDK version: 

v1.8.12

### Steps to reproduce

+ Pass the output of another operation to the ModelBatchPredictOp, subscript into the `output` property
+ Compile the pipeline

### Expected result

Pipeline compiles

### Actual result

Receive error "PipelineParams object is not iterable"

### Materials and Reference

Related: #2206

---

Impacted by this bug? Give it a 👍.

**Comment by connor-mccarthy** [comment]
@telpirion, can you verify whether you get the same result using the latest versions of KFP SDK v1 and GCPC v1? If so, can you provide a minimal reproducible example?
