### ISSUE TITLE
[frontend] No graph to show with increasing number of pods

### ISSUE THREAD

**Issue by hkair** [kubeflow/pipelines#8599]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
Cloud: AWS, EKS.

*  KFP version: 
Kubeflow - 1.6.1
KFP - 1.8.13

### Steps to reproduce
No graph to show error (even though the pipeline successfully ran)
![Screenshot 2022-12-19 at 2 11 38 PM](https://user-images.githubusercontent.com/58126733/208501754-ad9486f4-431e-47b1-800c-fe2f07db1ee7.png)
![Screenshot 2022-12-19 at 2 09 52 PM](https://user-images.githubusercontent.com/58126733/208501546-803b2fe8-cb9a-404b-b67e-10e2133d3049.png)
![Screenshot 2022-12-19 at 2 09 59 PM](https://user-images.githubusercontent.com/58126733/208501559-e7d458f1-4519-4e29-9283-fe9a8d944dca.png)

- Currently, our pipeline is for our offline training architecture and kubeflow is running on top of AWS Elastic Kubernetes Service.
- It seems the problem of "No graph to show" occurs when we have too many number of pods running for our pipeline.
- The num_games parameter is used to determine how many games we should use to train our models. At num_games=500, we are able to successfully view the graphs as shown in the expected results section.
- But, beyond that at num_games=750 and 1000, we are unable to see the pipeline graph and get a "No graph to show" in the Kubeflow UI.

![image](https://user-images.githubusercontent.com/58126733/208497306-260a44c1-3723-4f82-bf76-3586cc338f9f.png)
- This is our current kubeflow pipeline for our offline training at num_games=100. We are currently utilizing the ParallelFor method to parallelize and batch our preprocessing process. For each batch, **10 games are processed**,  thus for num_games=100 there are 10 batches for preprocessing and within each ParallelFor there are a total of 3 components being run.
- The number of pods is therefore linear to the num_games we are training on. With num_games = 100, there are 10 batches and in each batch there are 3 components/pod, so we can assume there are at least 30 pods that have been initialized.

num_games = 500, 50x3 = 150 + 10 (constant pods) = 160 pods initialized 
num_games = 750, 75x3 = 235 + 10 (constant pods) = 245 pods initialized
num_games = 1000, 100x3 = 300 + 10 (constant pods) = 310 pods initialized

### Expected result
- The expected result should be to show the graph of the kubeflow pipeline
- At a training session with num_games = 500, the graph is displayed correctly in the Kubeflow UI and pass that at 750 games or 1000 games, no graph is shown.
![Screenshot 2022-12-19 at 1 31 33 PM](https://user-images.githubusercontent.com/58126733/208495666-221897f8-ee6e-42a1-ae1e-6ad8215fadc4.png)
![Screenshot 2022-12-19 at 2 10 09 PM](https://user-images.githubusercontent.com/58126733/208501623-7d6559d9-34f7-43dc-b31c-17c4e8e97f9e.png)

### Materials and Reference
https://kubeflow-pipelines.readthedocs.io/en/stable/source/kfp.dsl.html#kfp.dsl.ParallelFor

Impacted by this bug? Give it a 👍.

**Comment by ananth102** [comment]
This was a regression in the Pipeline frontend, it has been fixed in #8343, but has not been part of a release yet. If this feature is a must have, a custom image of the Pipeline frontend can be [built](https://github.com/kubeflow/pipelines/blob/master/developer_guide.md).

Similar issue for more context: https://github.com/kubeflow/pipelines/issues/7655

**Comment by connor-mccarthy** [comment]
Blocked. This will be resolved when the next KFP BE/FE releases.

**Comment by gkcalat** [comment]
2.0.0-beta.0 has been [released](https://github.com/kubeflow/pipelines/releases/tag/2.0.0-beta.0). Please, upgrade the manifests and, if the issues will still be present, reopen this issue.
