### ISSUE TITLE
[bug] Max retries exceeded with connection refused

### ISSUE THREAD

**Issue by MatthewRalston** [kubeflow/pipelines#8605]
### Environment

*  How do you deploy Kubeflow Pipelines (KFP)?
Minikube v1.28.0
kubernetes 1.22.2
Kustomize v3.2.0
kubectl v1.25.5
Manifests v1.6.1

### Manifests were installed on a running minikube instance:

```bash
# After clone..
while ! kustomize build example | minikube kubectl -- apply -f -; do echo "Retrying to apply resources"; sleep 10; done
```

### Minikube started with compatible version of kubernetes and kustomize according to v1.6.1 Manifests `README.md`

```
minikube start --driver=docker --kubernetes-version=v1.22.2 --cpus=10 --memory=40gb --disk-size=50gb --container-runtime=containerd --wait-timeout=6m
# Then verify that pods are running with 
minikube kubectl -- get pods -n kubeflow --all
```

*  KFP version:
dev_local ????
*  KFP SDK version:

```bash
kfp                           1.8.17
kfp-pipeline-spec             0.1.16
kfp-server-api                1.8.5
```
### Expected result

The expected behavior is that the `kfp` Python client (v1.8.17) is able to connect with the following basic invocation in a Kubeflow Pipelines Python script, with `@dsl` declarations adorning the pipeline function called next.

```python
kubeflow_host='192.168.111.222'
kubeflow_port=443
client = kfp.Client(host="{0}:{1}/pipeline".format(kubeflow_host, kubeflow_port), namespace="kubeflow")
client.create_run_from_pipeline_func(my_func, arguments={ ... some params })
```

#### Screenshot of KFP Version running the pipelines dashboard I am able to access with `minikube tunnel`

![Screenshot from 2022-12-19 21-24-32](https://user-images.githubusercontent.com/4308024/208567426-714cf92b-7192-41b2-a70b-332cc18ea45b.png)

Screenshot showing dev_local kfp version, running on localhost through `minikube tunnel`

```python
py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/matt/.pyenv/versions/miniconda3-4.7.12/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='127.0.0.1', port=443): Max retries exceeded with url: /pipeline/apis/v1beta1/experiments?filter=%7B%22predicates%22%3A+%5B%7B%22op%22%3A+1%2C+%22key%22%3A+%22name%22%2C+%22stringValue%22%3A+%22Default%22%7D%5D%7D&resource_reference_key.type=NAMESPACE&resource_reference_key.id=default (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa5a794f050>: Failed to establish a new connection: [Errno 111] Connection refused'))


```

### Labels

---

Impacted by this bug? Give it a 👍.

**Comment by MatthewRalston** [comment]
Update in status. I can verify the `istio-ingressgateway`  internal address (1.2.3.4 here) but the external IP is still wonky.
```bash
istio-ingressgateway   NodePort   1.2.3.4   <none>        1234:2345/TCP,80:987/TCP,443:789/TCP,5678:6789/TCP,91234:92234/TCP   15h

```

**Comment by MatthewRalston** [comment]
If I use the port described by `minikube service list -n istio-system` for `http2` and in the same host as `minikube ip`, I get a `400` error bad request with an HTML response and a div with class `dex-container`. I'm hoping I'm hitting the dex authentication suite I've created via Manifests.

**Comment by chensun** [comment]
This looks to me it might be some minikube configuration issue, or it's possible there's not enough resource, were you able to list all the pods and see if any are not in a healthy state?

PS: we don't officially support minikube.

**Comment by MatthewRalston** [comment]
Yes, minikube is properly configured and I can run pipelines directly from the dashboard.

**Comment by ammaryasirnaich** [comment]
@MatthewRalston Hi, did you managed to solve this issue, i am also have similar issue?
