### ISSUE TITLE
[bug] kfp does not allow introspection of PipelineParam values for debugging.

### ISSUE THREAD

**Issue by MatthewRalston** [kubeflow/pipelines#8626]
### Environment

```bash
Minikube v1.28.0
kubernetes 1.22.2
Kustomize v3.2.0
kubectl v1.25.5
Manifests v1.6.1
kfp                           1.8.17
kfp-pipeline-spec             0.1.16
kfp-server-api                1.8.5
```

*  How do you deploy Kubeflow Pipelines (KFP)?

I deploy it locally on a minikube cluster. 
*  KFP version:
kfp                           1.8.17

*  KFP SDK version:

kfp                           1.8.17
kfp-pipeline-spec             0.1.16
kfp-server-api                1.8.5
### Steps to reproduce

I expect to be able to use Python logic or properly use the `kfp.dsl.Condition` constructor to provide conditional logic (i.e. whether or not to decompress an input file) within a `@kfp.dsl.pipeline` pipeline. Instead, I cannot introspect `PipelineParam` objects in the pipeline! How do I do conditional validations? Seems like an essential function for a production grade pipeline. I'm sure it's user error and documentation.

```python
#!/bin/env python

import os
import sys
import argparse

import kfp.dsl as dsl
import kfp.components as comp
import kfp

components_dir = os.path.join(os.path.dirname(__file__), "components")

#gunzip = comp.load_component_from_file(os.path.join(components_dir, "gunzip.yaml"))


@dsl.pipeline(
    name='kubeflow-barebone-demo',
    description='kubeflow demo with minimal setup'
)
def rnaseq_pipeline(fastq1: str) -> bool:
    # Step 1: training component

    gunzip = dsl.ContainerOp(
        name='gunzip',
        images='bitnami/minideb:latest',
        command=[
            'gunzip',
            fastq1
        ],
        file_outputs={'fastq1': fastq1.rstrip(".gz")}
    )

    
    with dsl.Condition(os.path.splitext(fastq)[1] is ".gz", name='gunzip_is_needed'):
        gunzip1 = gunzip(fastq)
        # I'd really like to view and print the components of gunzip1.outputs, or even understand when gunzip1.output
        # can be used as a convenient shortcut, or even debug what the expected key value should be. I'm getting KeyErrors before the step is complete.
        print("GUNZIPPED")

    with dsl.Condition(os.path.splitext(infile)[1] is not ".gz", name='is_gunzip_not_needed'):

        print("NOT GUNZIPPED")


if __name__ == "__main__":
    logger = get_root_logger(2)
    
    kfp.compiler.Compiler().compile(rnaseq_pipeline, 'pipeline.yaml')

```

### Expected result

The desired behavior is either the proper way to create a function that can launch individual pipeline steps, checking outputs for certain desired behaviors in the path only.  I'm trying to debug some very basic code, and I don't understand the desired `kfp` implementation semantics/syntax. Thanks for your help.

### Labels

---

Impacted by this bug? Give it a 👍.

**Comment by connor-mccarthy** [comment]
This is expected behavior. See [comment](https://github.com/kubeflow/pipelines/issues/8203#issuecomment-1366043593) for a relevant information.

You can achieve this by swapping out the arbitrary Python code in `dsl.Condition` for a task that does the check:

```
is_gz_task = is_gz(path=infile)
with dsl.Condition(is_gz_task.output == False, name='is_gunzip_not_needed'):
```

In general, the pipeline body must contain only orchestration logic and cannot use runtime values or arbitrary user code. Component bodies can contain arbitrary user code.

**Comment by MatthewRalston** [comment]
Will take a look. Thanks for the speedy response.
