### ISSUE TITLE
Pipeline：<lambda>() missing 1 required positional argument: 'y'

### ISSUE THREAD

**Issue by leoliang1988** [kubeflow/pipelines#8641]
Hello,here is my model:

model = Pipeline([
('scaler',FunctionTransformer(StandardScaler().fit_transform, validate=True)),
('dummy', FunctionTransformer(lambda X, y: dummy_fit_transform(X, y), validate=False)),
('reshape', FunctionTransformer(reshape_to_3d, validate=True)),
('bidirectional', KerasClassifier(build_fn=create_model, epochs=10, batch_size=64))
])

def dummy_fit_transform(X, y):
model = DummyClassifier(strategy='most_frequent')
model.fit(X, y)
return model.predict(X)

def create_model():
model = Sequential([
Bidirectional(LSTM(128)),
Dense(1, activation='sigmoid')
])
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
return model

def reshape_to_3d(X):
return np.reshape(X, (X.shape[0], 1, X.shape[1]))

The question is that when I run : model.fit(x_train, y_train)

the system notice me :

TypeError: () missing 1 required positional argument: 'y'

please tell me how to fix it,thank you very much!

**Comment by Linchin** [comment]
Hi @leoliang1988, it looks like this error message comes from the function `model.fit()`, where it requires more input arguments than you provided. Maybe the `DummyClassifier`'s documentation can provide more info?
