### ISSUE TITLE
Contributing to pipeline CICD for ppc64le arch

### ISSUE THREAD

**Issue by pranavpandit1** [kubeflow/pipelines#8660]
Hello,

My team is working on a request of "Porting Kubeflow to IBM Power (ppc64le)" 
For the same purpose, we want to contribute to CICD for the pipeline repository for ppc64le architecture.
Kindly provide the details of how to access existing CI builds, files, logs, etc.  

for more details, reference the link [Kubeflow Umbrella issue](https://github.com/kubeflow/kubeflow/issues/6684)

**Comment by jlyaoyuli** [comment]
@pranavpandit1 We suggest you to pull the changes from our website and make your own CICD pipeline, because our current testing infra in Google Cloud (GKE), and we don't have the access to IBM Power. Feel free to reopen this if you have any idea or suggestion.

**Comment by pranavpandit1** [comment]
@jlyaoyuli: I second Adil's thought about using GitHub actions as it will be easier to contribute.
Any specific reasons for not using GitHub Actions?

**Comment by lehrig** [comment]
@zijianjoy - any news on this?

**Comment by lehrig** [comment]
Still waiting on progress within https://github.com/GoogleCloudPlatform/oss-test-infra/issues/1972
