### ISSUE TITLE
[sdk] `wait_for_run_completion` occasionally hangs forever in `RunServiceApi.get_run` call

### ISSUE THREAD

**Issue by jli** [kubeflow/pipelines#8661]
### Environment

*  KFP version: 1.7.1
*  KFP SDK version: 1.8.12
*  All dependencies version:
```
kfp                             1.8.12
kfp-pipeline-spec               0.1.16
kfp-server-api                  1.8.3
```

(I know we're on an older version of the kfp sdk, but it doesn't look like the relevant code has changed much since then.)

### Steps to reproduce

- Launch a long-running run on KFP
- Create a few processes that call `kfp.Client.wait_for_run_completion` with INFO logging enabled[1]
- After ~10-15 minutes, I observe that ~2 out of 3 wait calls are hanging after the RunServiceApi.get_run call. The hanging continues even after the run completes.

[1] enable INFO logging to see when `wait_for_run_completion` makes a new call
```python
logging.basicConfig(format="%(asctime)s %(message)s", datefmt="%Y-%m-%d %H:%M:%S", force=True)
logging.getLogger().setLevel(logging.INFO)
```
I also added more logging calls before and after the `get_run` API call here: https://github.com/kubeflow/pipelines/blob/f4588f31128d268974bdffb16e487ea170706011/sdk/python/kfp/client/client.py#L1330

### Expected result

`wait_for_run_completion` should continue polling until the run completes.

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

**Comment by jlyaoyuli** [comment]
@jli Thanks for reaching out. Can you provide how you observe the run status (GetRun API call)?
