### ISSUE TITLE
What is Difference of pipelines between V1 and V2???

### ISSUE THREAD

**Issue by kimkihoon0515** [kubeflow/pipelines#8680]
Does V2 still supports argo workflow or not??
And for now V1 compiler compiles pipeline into yaml file but in V2 the compiler only supports json file format.
Are you guys planning to support a function that supports to be compiled as a yaml file??
Plus what is pipeline Spec?

**Comment by chensun** [comment]
Hi @kimkihoon0515 

> Does V2 still supports argo workflow or not??

KFP v2 still supports argo workflow.

> And for now V1 compiler compiles pipeline into yaml file but in V2 the compiler only supports json file format.
> Are you guys planning to support a function that supports to be compiled as a yaml file??

In master branch, KFP SDK (currently at 2.0-beta) support compiling to YAML as well. However, it's worth noting that the file format itself isn't what matter, but the content format. In KFP v1, the YAML is of Argo Workflow CRD, while in KFP v2, the JSON/YAML is of PipelineSpec--and this leads to your third question.

> Plus what is pipeline Spec?

Pipeline spec is the spec definition described via [this proto message](https://github.com/kubeflow/pipelines/blob/d1f1ee9f2bbd09df7ea6ab51b21f07ba5f86c871/api/v2alpha1/pipeline_spec.proto#L50). It's meant to be an Intermediate Representation (IR) of pipeline. KFP v2 creates this abstraction layer on top of Argo, the new IR spec is platform-agnostic. The goal is to support running the same pipeline across multiple platforms/engines: KFP, KFP on tekton, Vertex Pipelines, etc.

This ["Understanding KFP v2"](https://docs.google.com/presentation/d/1HzMwtI2QN67xQp2lSxmuXhitEsukLB7mvZx4KAPub3A/edit#slide=id.gb4a3fac3a8_7_1911) deck we presented at Kubeflow Pipelines community meeting may help you have a better view of KFP v2. You need to join [kubeflow-discuss](https://groups.google.com/g/kubeflow-discuss) Google group to gain access to the docs we've shared with the community.

**Comment by kimkihoon0515** [comment]
@chensun I saw the roadmap on YT. So you guys gonna stop releasing major version of v1?

**Comment by chensun** [comment]
> @chensun I saw the roadmap on YT. So you guys gonna stop releasing major version of v1?

That is correct. We will continue patching v1 (1.8) for security and vulnerability fixes, but there's no planned feature work/release for v1.
