### ISSUE TITLE
[bug] 1.6 manifests leads to deployment issue with kubeflow pipelines

### ISSUE THREAD

**Issue by MatthewRalston** [kubeflow/pipelines#8683]
### Environment

Minikube v1.28.0
kubernetes 1.22.2
Kustomize v3.2.0
kubectl v1.25.5
Manifests v1.6.1

*  How do you deploy Kubeflow Pipelines (KFP)?
Locally, on minikube, via manifests v1.6.1.

I've also experimented with Argoflow on my OS, but it's not relevant here.

*  KFP version:

*  KFP SDK version:

kfp                           1.8.17
kfp-pipeline-spec             0.1.16
kfp-server-api                1.8.5

### Steps to reproduce
Create pipeline.py from the following.

```python
#!/bin/env python

import os
import sys
import argparse

import kfp.dsl as dsl
import kfp.components as comp
import kfp



import logging
global logger
logger = None

def get_root_logger(level):
    levels=[logging.WARNING, logging.INFO, logging.DEBUG]
    if level < 0 or level > 2:
        raise TypeError("{0}.get_root_logger expects a verbosity between 0-2".format(__file__))
    logging.basicConfig(level=levels[level], format="%(levelname)s: %(asctime)s %(funcName)s L%(lineno)s| %(message)s", datefmt="%Y/%m/%d %I:%M:%S")
    root_logger = logging.getLogger()
    return root_logger



components_dir = os.path.join(os.path.dirname(__file__), "components")

#gunzip = comp.load_component_from_file(os.path.join(components_dir, "gunzip.yaml"))


#is_unzip_needed = comp.load_component_from_file(os.path.join(components_dir, "is_unzip_needed.yaml"))

def gunzip(infile:str, outfile:str):
    """ Infile like 'path/to/example.txt.gz', outfile like 'path/to/example.txt' """

    return dsl.ContainerOp(
        name='gunzip',
        image='bitnami/minideb:latest',
        command=[
            '/bin/zcat $0 > input.txt ',
            '|| ',
            'mv $0 input.txt'
        ],
        file_outputs={
            'output': 'input.txt'
        }
    )


@dsl.pipeline(
    name='kubeflow-barebone-demo',
    description='kubeflow demo with minimal setup'
)
def pipeline(fastq1:str):
    # Step 1: training component

    gunzip1 = gunzip(infile=fastq1, outfile = str(fastq1).rstrip(".gz")).set_cpu_request('1').set_cpu_limit('1').set_memory_request('512Mi').set_memory_limit('512Mi')



if __name__ == "__main__":
    logger = get_root_logger(2)
    
    kfp.compiler.Compiler().compile(rnaseq_pipeline, 'pipeline.yaml')

```

### Expected result

I expect that my 'gunzip' container should run, given that the executable listed can be verified to be installed in that container (alpine:latest or bitnami/minideb:latest)

However, I am observing the following in the dashboard logs.

```bash

failed to find name in PATH: exec: "echo $0": executable file not found in $PATH
```

The correct behavior should be to locate or understand the shell builtin 'exec'. 
### Materials and reference

![Screenshot from 2023-01-12 14-28-26](https://user-images.githubusercontent.com/4308024/212910879-c8bc76d2-2e03-4360-8cc0-778e4e2390eb.png)

### Labels

---

Impacted by this bug? Give it a 👍.

**Comment by chensun** [comment]
Hi @MatthewRalston , 

First of all `dsl.ContainerOp` has been deprecated as a user interface, you should have seen a deprecation warning on it.
However, I think the real culprit for the error is `str(fastq1).rstrip(".gz")`, this is code not containerized. You can either wrap the code in a lightweight component, or handle the logic within `gunzip` component.

**Comment by MatthewRalston** [comment]
Hi thanks for the quick response.

I needed to use this interface to set the container requirements (CPU, memory request/limit) via kfp. Is there an alternative way to specify container limits via the v1.8 kfp on a 1.6 manifests Kubeflow instance?

**Comment by MatthewRalston** [comment]
Also I can confirm that removal of the str(fastq) etc component is not the culprit of the bash builtin "exec" not being found in the Alpine Linux container. 

New syntax is

```python
gunzip1 = gunzip (infile=fastq1).set_cpu_request('1') etc.
```

**Comment by MatthewRalston** [comment]
Hey @chensun, when you get a chance, would you mind revisiting this issue please? Again, I'm using a vanilla kubernetes instance (minikube; compliant) and deploying kubeflow pipelines via the v1.6 branch manifests from kubeflow/manifests.

![Screenshot from 2023-01-12 14-28-26](https://user-images.githubusercontent.com/4308024/214159750-e462bba3-cb30-4170-87d7-2a7513c38b75.png)

**Comment by chensun** [comment]
> Also I can confirm that removal of the str(fastq) etc component is not the culprit of the bash builtin "exec" not being found in the Alpine Linux container.
> 
> New syntax is
> 
> ```python
> gunzip1 = gunzip (infile=fastq1).set_cpu_request('1') etc.
> ```

Sorry, I spoke too earlier without looking carefully at the error message--though the `str(fastq)` usage was also an error that would not give you the expected value.

You're right that the culprit is the about the exec path, to solve that you should add `sh -c` in front of your command. But then another issue is you're not really passing the value as you thought--`$0` doesn't magically map to `infile`. 

I would still suggest dropping `dsl.ContainerOp` so that you know what a proper component interface and data-passing story should look like.

Try the following 
```python
from kfp import components
from kfp import dsl

foo = components.load_component_from_text("""
    name: foo
    inputs:
    - {name: msg, type: String}
    implementation:
      container:
        image: debian:latest
        command: 
        - sh
        - -c
        - /bin/echo $0
        args:
        - {inputValue: msg}
""")

@dsl.pipeline
def bar():
    foo('hello')
```

**Comment by MatthewRalston** [comment]
Done. New version uploaded. Fails to write outputs, which is distinctly a different error. Should I follow up on gitter, Slack, or just start a new issue?

![image](https://user-images.githubusercontent.com/4308024/214195224-97f16a56-0f6d-4034-bc56-b656da247507.png)

**Comment by MatthewRalston** [comment]
As a follow up, is this something that could be handle with a more graceful error checking process, to see if MinIO is reachable? or that the /tmp directory is available in the container before data is written? I'm pretty sure MinIO is part of my problem, because there's a 90% chance that it's a issue with deployment, and not bash syntax.

**Comment by MatthewRalston** [comment]
Thanks for checking this issue out last week @chensun . I'm fairly confident the issue isn't my bash syntax related to the $0? I've since reworked the script as follows:

* pipeline.py

```python
...
gunzip = comp.load_component_from_file("gunzip.yaml")

@dsl.pipeline(name="kubeflow-barebone-demo", description="")
def pipeline(fastq1: str):
    gunzip1 = gunzip(infile=fastq1).set_cpu_request(...) # as above
```

* gunzip.yaml
```yaml
name: gunzip
description: Gunzips an Input file to an Ouput filepath
inputs:
- {name: infile, type: String, description: 'Data for gzip decompression'}
outputs:
- {name: Output, type: String, description: 'Output decompressed plaintext'}
implementation:
  container:
    image: alpine:latest
    # command is a list of strings (command-line arguments). 
    # The YAML language has two syntaxes for lists and you can use either of them. 
    # Here we use the "flow syntax" - comma-separated strings inside square brackets.
    command: [
    sh,
    -c,
    zcat,
    {inputPath: infile},
    '>',
    {outputPath: Output}
    ]

```

**Comment by MatthewRalston** [comment]
Thank you to Chen Sun and Benjamin Tan for encouraging the `sh -c` prelude and the v1.8 syntax, respectively. Closing the original issue thanks to chensun , opened a new issue linked above.
