### ISSUE TITLE
ModuleNotFoundError: No module named 'kfp'

### ISSUE THREAD

**Issue by shankarpm** [kubeflow/pipelines#872]
I am getting this error on this line in python3 Env. I am using Mac .

>>> from kfp.components import load_component_from_file
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'kfp' 

I have installed all the requirements below for kubeflow pipeline
pip3 install https://storage.googleapis.com/ml-pipeline/release/0.1.10/kfp.tar.gz --upgrade
gcloud components install kubectl

Please let me know .thanks
Shankar

**Comment by gaoning777** [comment]
I had this problem before because the pip3 installs the package in a place that the python3 does not include. Please check your python path and see if the packages are there.

**Comment by Ark-kun** [comment]
Try `python3 -m pip install https://storage.googleapis.com/ml-pipeline/release/0.1.10/kfp.tar.gz --upgrade`.
This should work in rare cases when your python3 and pip3 are de-synced.

**Comment by vicaire** [comment]
Resolving since it has been open for a while. Please reopen if more help is needed.
