### ISSUE TITLE
[sdk] registry client delete_version KeyError: 'done'

### ISSUE THREAD

**Issue by askaupup** [kubeflow/pipelines#8731]
### Environment
Python version 3.8.6 Local Jupyter Notebook
MacBook Pro 2019

*  KFP version: kfp 2.0.0b10  
*  KFP SDK version:  kfp 2.0.0b10  
*  All dependencies version:
kfp                              2.0.0b10
kfp-pipeline-spec                0.1.17
kfp-server-api                   2.0.0a6

### Steps to reproduce
1. Create a repository in Artifact Registry in Google Cloud with kubeflow pipelines format. Replace the host with the repository created and upload a test component yaml file(i.e. pipeline with one component) to this repository. Example code as below: 
```
from kfp.registry import RegistryClient 
client = RegistryClient(host="https://us-east1-kfp.pkg.dev/<project_id>/component-test") 
component_name, version = client.upload_pipeline("compoent.yaml", tags=["0.0.1"])
```
2. Use a **registryClient** and **component_name, version** variables from the previous step and run the code below
```
client.delete_version(component_name,version)
client.delete_package(component_name)
```
The given version is successfully deleted in Artifact Registry in GCP but raises the following error: 
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/105866640/213487957-fae2d435-63b6-40bf-aee0-31083bfaa3ee.png">
When no such version exists in the artifact registry repository, **delete_version** function will return True instead shown as below:
<img width="613" alt="image" src="https://user-images.githubusercontent.com/105866640/213488636-1401ff53-0c16-46f5-888e-5761fb4ada2a.png">
delete_package function raises the error regardless of the existence of the package. 
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/105866640/213486899-981040e9-dd49-4777-a3e0-7f9f0f354bef.png">

### Expected result
The given version is successfully deleted without raising any errors.  The given package is deleted from Artifact Registry repository without any errors. 

### Materials and Reference

Impacted by this bug? Give it a 👍.

**Comment by anifort** [comment]
issue also present in kfp 2.0.0b11

**Comment by eliska-kremenova** [comment]
/reopen issue present in 
```
kfp==2.3.0
kfp-pipeline-spec==0.2.2
kfp-server-api==2.0.5
```

The workaround is as follows
```
class FixedRegistryClient(RegistryClient):
    def __init__(self, **kwargs) -> None:
        super().__init__(**kwargs)

    def delete_package(self, package_name: str) -> None
        url = self._config["delete_package_url"].format(package_name=package_name)
        self._request(request_url=url, http_request="delete")
```
