### ISSUE TITLE
Not able to retrieve the logs in Kuebflow's UI Log console.

### ISSUE THREAD

**Issue by sneharth37** [kubeflow/pipelines#8761]
I have set up logging.info () at various places in my code and the UI Log console is retrieving only a few of them. I have also noticed that it stops logging in the middle and the last log I see is Tearing down program. Although my pipeline doesn't seem to fail anywhere, I can see this happening across most of them.
I have used this as to set up my logs.
# Set up logging
    root = logging.getLogger()
    root.setLevel(logging.INFO)
    handler = logging.StreamHandler(sys.stdout)
    handler.setLevel(logging.INFO)
This has worked well previously and hasn't been working fine since last 4-5 days.

**Comment by danielschulz** [comment]
We also experience the very same issue, once our cluster Auto-Scales. All logs are gone and NOT read from our mirror in MINIO (interface of KFP to access S3) / AWS S3 (physical location).
