### ISSUE TITLE
is there any doc about kfp-launcher, I just upgrade to pipeline v2, found kfp use this binary to start the pod command

### ISSUE THREAD

**Issue by elim19** [kubeflow/pipelines#8768]
is there any doc about kfp-launcher, I just upgrade to pipeline v2, found kfp use this binary to start the pod command

**Comment by chensun** [comment]
Hi @elim19, you may find more info about launcher in the design doc we shared with the community: [bit.ly/kfp-v2](https://bit.ly/kfp-v2)
To gain access to the doc, please join https://groups.google.com/g/kubeflow-discuss google group.

**Comment by elim19** [comment]
> Hi @elim19, you may find more info about launcher in the design doc we shared with the community: [bit.ly/kfp-v2](https://bit.ly/kfp-v2) To gain access to the doc, please join https://groups.google.com/g/kubeflow-discuss google group.

@chensun , I see in the pipeline code(tag 1.8.5), when pipeline is transformed to argo workflow, it  will create a driver task to make podSpecPatch to the pod, but when I deployed 1.8.5 gcr.io/ml-pipeline/api-server, I don't see this feature, which version have this driver task?
