### ISSUE TITLE
[feature] Add dataclass for filter

### ISSUE THREAD

**Issue by JakeSummers** [kubeflow/pipelines#8778]
### Feature Area

/area sdk
/area samples

### What feature would you like to see?

#6748 added support for filters.  

The suggested workflow, is to build the predicates like this ([doc](https://www.kubeflow.org/docs/components/pipelines/v1/tutorials/sdk-examples/#example-2-listing-pipelines-with-a-filter)).: 

```
filter = json.dumps(
	{
		'predicates': [
			{
				'key': 'name', 
				'op': 1,     # <-- NOTE: 1 means "EQUALS" - very hard to read.
				'string_value': '{}'.format(pipeline_name)
			}
		]
	})
```

It would be much nicer, if the sdk provided a dataclass that would help to build these predicates.  Something like this: 

```
from dataclasses import dataclass
from enum import Enum
from typing import List


# https://www.kubeflow.org/docs/components/pipelines/v1/tutorials/sdk-examples/#example-2-listing-pipelines-with-a-filter
# https://github.com/kubeflow/pipelines/blob/64bf95333ccc3a0411793c4a11325b71595ab150/backend/api/filter.proto#L25-L63

class Operation(Enum):
    # Operators on scalar values. Only applies to one of |int_value|,
    # |long_value|, |string_value| or |timestamp_value|.
    EQUALS = 1
    NOT_EQUALS = 2
    GREATER_THAN = 3
    GREATER_THAN_EQUALS = 5
    LESS_THAN = 6
    LESS_THAN_EQUALS = 7

    # Checks if the value is a member of a given array, which should be one of
    # |int_values|, |long_values| or |string_values|.
    IN = 8

    # Checks if the value contains |string_value| as a substring match. Only
    # applies to |string_value|.
    IS_SUBSTRING = 9


@dataclass()
class Predicate:
    key: str
    op: Operation
    string_value: str

@dataclass
class Filter:
    predicates: List[Predicate]

```

This could then be used like this: 

```
my_filter = Filter([
    Predicate(
        key="name",
        op=Operation.EQUALS,
        string_value="my-experiment"
    )
])
```

As an aside, the inline doc is currently, broken:

![image](https://user-images.githubusercontent.com/5657503/216106309-2b0f3e02-32f1-4fa8-a88a-b9f2eceb8a05.png)

### What is the use case or pain point?

Needing to build json, particularly json that uses `'op': 1` where `1` means `Equals` is not very user friendly.  

### Is there a workaround currently?

Yes.

---

Love this idea? Give it a 👍.

**Comment by connor-mccarthy** [comment]
@JakeSummers, I think this is a good idea. If you're interested in contributing this (including the [docs](https://github.com/kubeflow/website) fix) I would happy to review your PR.
