### ISSUE TITLE
Use multiple components in the ExitHandler

### ISSUE THREAD

**Issue by AlbertCintas** [kubeflow/pipelines#8783]
Hello!

Is it possible to run two steps with two components in the Exit Handler? Maybe some workaround to perform a similar task?
I've been trying to do it in many different ways but all attempts have been unsuccessful.

Thank you!

**Comment by connor-mccarthy** [comment]
Hi, @AlbertCintas. If you're using KFP v2 (BE nearly in beta), the following example should demonstrate the usage you're looking for:

```python
from kfp import compiler
from kfp import dsl
from kfp.dsl import component


@component
def print_op(message: str):
    """Prints a message."""
    print(message)


@component
def fail_op(message: str):
    """Fails."""
    import sys
    print(message)
    sys.exit(1)


@component
def get_run_state(status: dict) -> str:
    print('Pipeline status: ', status)
    return status['state']


@dsl.pipeline
def exit_op():
    print_op(message='notify task failure.')


@dsl.pipeline
def my_pipeline():
    exit_task = exit_op()

    with dsl.ExitHandler(exit_task):
        print_op(message='message')
        fail_op(message='Task failed.')
```

**Comment by AlbertCintas** [comment]
Thank you for your answer!

Tried this method, but couldn't compile it with two components (loaded from a file) called from inside the exit_op.

**Comment by AlbertCintas** [comment]
Hello, sorry for the late answer, I've been on vacation. I think I might have not been clear with my request, sorry for that.

What I need are two components as part of the exit handler component (one performs cleanup, the other sends a notification). Unfortunately, we're still running KFP v1, even though I've been compiling some pipelines to be V2_compatible. I've tried so many ways of doing it, but none compiles (if using v1) or works in KFP v1 (if compiled using v2).

Following your example, what I would need is something like this:
```
@component
def cleanup_op():
    print("This component performs cleanup")

@component
def notification_op():
    print("This component sends a notification")

@component
def print_op(message: str):
    """Prints a message."""
    print(message)

@dsl.pipeline
def exit_op():
    cleanup_op()
    notification_op()

@dsl.pipeline
def my_pipeline():
    exit_task = exit_op()

    with dsl.ExitHandler(exit_task):
        print_op(message='message')
```

Is it possible to do this in KFP v1? I was reading Argo documentation and it is possible to have multiple exit handlers running and even choose which one to run depending on a condition, but I've found nothing related for Kubeflow.

**Comment by connor-mccarthy** [comment]
I see, @AlbertCintas. This is not possible in v1.

In v2, you can use a pipeline as your exit task to accomplish this: https://github.com/kubeflow/pipelines/blob/9926f31a3a0f5c250a8b31ce474f16bb72520ab5/sdk/python/test_data/pipelines/pipeline_as_exit_task.py#L51
