### ISSUE TITLE
Changing pipeline version doesn't work during local deployment

### ISSUE THREAD

**Issue by Rstar1998** [kubeflow/pipelines#8784]
Changing pipeline version doesn't work during local deployment
The following commands  does not work for PIPELINE_VERSION=1.8.9

```
export PIPELINE_VERSION=1.8.5
kubectl apply -k "github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=$PIPELINE_VERSION"
kubectl wait --for condition=established --timeout=60s crd/applications.app.k8s.io
kubectl apply -k "github.com/kubeflow/pipelines/manifests/kustomize/env/platform-agnostic-pns?ref=$PIPELINE_VERSION"

```

**Comment by chensun** [comment]
Does it work for 1.8.5 but not for 1.8.9? Not sure which local deployment methods are you using, and did you get any specific error? 
Maybe you've already seen this, but here's our local deployment instruction: https://www.kubeflow.org/docs/components/pipelines/v1/installation/localcluster-deployment/

**Comment by Rstar1998** [comment]
Yes It works for 1.8.5 but not for 1.8.9. I am using the same docuemntation for installation => 
https://www.kubeflow.org/docs/components/pipelines/v1/installation/localcluster-deployment/

**Comment by chensun** [comment]
Sorry, I followed the reported message without checking the facts. We don't have a release tag for 1.8.9. 
The latest is 1.8.5 for deployment.
You might have been confused by the KFP SDK version?
