### ISSUE TITLE
which version of gcr.io/ml-pipeline/api-server has driver task in argo workflow?

### ISSUE THREAD

**Issue by elim19** [kubeflow/pipelines#8788]
I see in the pipeline code(tag 1.8.5), when pipeline is transformed to argo workflow, it will create a driver task to make podSpecPatch to the pod, but when I deployed 1.8.5 gcr.io/ml-pipeline/api-server, I don't see this feature, which version have this driver task?

**Comment by elim19** [comment]
anyone knows this issue?

**Comment by jlyaoyuli** [comment]
@elim19 Thanks for reaching out! The driver task is supported in KFP v2 SDK. https://www.kubeflow.org/docs/components/pipelines/v2/run-a-pipeline/
