### ISSUE TITLE
[bug] How to restart Kubeflow pipeline starting from a failed step/component?

### ISSUE THREAD

**Issue by jayaprasadt** [kubeflow/pipelines#8790]
### Environment

*  How can I restart the Kubeflow pipeline after fixing error in a failed step, retaining the data/model in previous steps?

* I'm running a pipeline that has 4 steps/components

1. Download Data
2. Load data as frame
3. Train and save model
4. Predict

If the 'Predict' step/component fails because of a syntax error, is there a way to restart the run only for the 'Predict' step after fixing the error? 

This should retain the data and model info till the 'Train and save model' step, and rerun only the modified 'Predict' component.

*  KFP version: 1.6.3

> kfp                      1.6.3
> kfp-pipeline-spec        0.1.16
> kfp-server-api           1.6.0

### Steps to reproduce

Create a pipeline with more than one component / step. 
Run the pipeline with a syntax error in any step other than the first step.
Fix the error in the failed step/component and retry the pipeline. 
Pipeline starts from the first step onward losing all the data and models from previous run.

### Expected result

The pipeline should retain the data and model info from previous run and start rerunning from the failed step.

### Labels

---

Impacted by this bug? Give it a 👍.

**Comment by jlyaoyuli** [comment]
@jayaprasadt Thanks for reaching out. Would you mind sharing what type of issue you're trying to fix? If the change is related to pipeline template, it won't start from the failed step by design.

At the meantime, we suggest you to try the KFP v2 to see whether the problem exists.

**Comment by jayaprasadt** [comment]
@jlyaoyuli Thanks for confirming the pipeline won't start from the failed step if the change is related to pipeline template. I'll try KFP v2 and let you know.
