### ISSUE TITLE
[sdk] Cannot execute containerized python component - AttributeError: 'PythonComponent' object has no attribute '__annotations__'

### ISSUE THREAD

**Issue by b4sus** [kubeflow/pipelines#8791]
### Environment

*  KFP version:
2.0.0-alpha.5
*  KFP SDK version: 
2.0.0b9
*  All dependencies version:
kfp                      2.0.0b9
kfp-pipeline-spec        0.1.16
kfp-server-api           2.0.0a6

### Steps to reproduce

I am following these [instructions](https://www.kubeflow.org/docs/components/pipelines/v2/author-a-pipeline/components/#2-containerized-python-components) to create containerized python component. I am able to build the component and push the image using kfp cli.
I am not quite sure how to use the component in pipeline, this is what I am doing:
Component file (components/mycomp.py):
```python
@component(
    base_image='python:3.11-slim',
    target_image='...',
    packages_to_install=['pandas >=1.5.3']
)
def do_stuff(some_id: str, output_df: Output[Artifact]):
    print(f'Hello {some_id} from containerized component')
    df = pd.DataFrame(np.random.default_rng().random((4, 3)))
    with open(output_df.path, 'w') as fp:
        df.to_csv(fp, index=False)
```
Pipeline definition file
```python
import components.mycomp

@dsl.pipeline(name='cont-pipeline')
def cont_pipelinesome_id: str):
    task1 = components.mycomp.do_stuff(some_id=some_id)
```
Then I can either run the pipeline or compile, upload and run. During run the image is downloaded and executed, but fails with following error:
```
[KFP Executor 2023-02-03 13:41:08,810 INFO]: --component_module_path is not specified. Looking for component `do_stuff` in config file `kfp_config.ini` instead
[KFP Executor 2023-02-03 13:41:08,810 INFO]: Loading KFP component "do_stuff" from mycomp.py (directory "." and module name "mycomp")
[KFP Executor 2023-02-03 13:41:09,067 INFO]: Got executor_input:
{
  "inputs": {
    "parameterValues": {
      "some_id": "asd"
    }
  },
  "outputs": {
    "artifacts": {
      "output_df": {
        "artifacts": [
          {
            "type": {
              "schemaTitle": "system.Artifact",
              "schemaVersion": "0.0.1"
            },
            "uri": "minio://mlpipeline/v2/artifacts/pipeline/cont-pipeline/88d0c5ea-b5c0-4fc2-b461-6aa2d4233c5c/do_stuff/output_df"
          }
        ]
      }
    },
    "outputFile": "/tmp/kfp_outputs/output_metadata.json"
  }
}
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/usr/local/lib/python3.11/site-packages/kfp/components/executor_main.py", line 105, in <module>
executor_main()
File "/usr/local/lib/python3.11/site-packages/kfp/components/executor_main.py", line 98, in executor_main
executor = component_executor.Executor(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/kfp/components/executor.py", line 63, in __init__
output_artifact = self.make_artifact(
^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/kfp/components/executor.py", line 81, in make_artifact
annotation = func.__annotations__.get(name)
^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PythonComponent' object has no attribute '__annotations__'
F0203 13:41:09.239538 36 main.go:49] failed to execute component: exit status 1
Error: exit status 1
```
Why I think it is an sdk problem - looking at executor_main.py, this is how the function is loaded:
```
function_to_execute = getattr(module, func_name)
```
and later in [Executor.__init__](https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/components/executor.py#L81) the __annotations__ are accessed and the error is raised.
The `func` (or `function_to_execute` above) is not the actual function `do_stuff` (as the code seems to expect), but it is the PythonComponent because `do_stuff `is decorated with @component, that's why the annotations are not there.

Am I creating the pipeline incorrectly (and what would be the correct way?) perhaps or is it a bug?

### Expected result

Pipeline runs successfully.

---

Impacted by this bug? Give it a 👍.

**Comment by micmarty-deepsense** [comment]
I'm experiencing the same issue. Is this something that would be easy to fix for the next release?

**Comment by micmarty-deepsense** [comment]
The workaround described by @b4sus worked for me though (https://github.com/kubeflow/pipelines/issues/8791#issuecomment-1419168779)

**Comment by connor-mccarthy** [comment]
Thanks for raising this, @b4sus and @micmarty-deepsense. I am working on a fix.

**Comment by micmarty-deepsense** [comment]
Huge thanks @connor-mccarthy! 👏 
I'm gonna try it.

**Comment by connor-mccarthy** [comment]
@micmarty-deepsense, [2.0.0-beta.13](https://pypi.org/project/kfp/2.0.0b13/) contains this fix, so you should be able to try from this version.
