### ISSUE TITLE
How to accessing the source code from Images

### ISSUE THREAD

**Issue by ultrons** [kubeflow/pipelines#881]
In my experiments with kubeflow pipelines so far, time and again I have come across some excellent example of components for training and model deployment etc. 

To make a meaningful use of those components I need to edit the source code corresponding to that step and all I have is the container image.

Is there a recommended way or an upcoming feature that facilitates this instead of the users developing their own uniq ways with kubectl or docker export etc?

**Comment by Ark-kun** [comment]
Currently all the components that we publish have source code and `Dockerfile`s available. Do you see some exceptions?

BTW, You can always use `docker run -it --entrypoint sh <image>` to check what's inside the container image.

**Comment by vicaire** [comment]
Resolving. Please reopen if anything else is needed.
