### ISSUE TITLE
[sdk] cannot wait for dsl.ParallelFor completion

### ISSUE THREAD

**Issue by max-gartz** [kubeflow/pipelines#8817]
### Environment

*  KFP SDK version: 2.0.0b11

*  All dependencies version:
kfp                                      2.0.0b11
kfp-pipeline-spec             0.2.0
kfp-server-api                   2.0.0a6

### Steps to reproduce
The following example fails to even create the graph component from the pipeline function with: 

"RuntimeError: Tasks cannot depend on an upstream task inside a ParallelFor that is not a common ancestor of both tasks. Task outer-op depends on upstream task inner-op."

```python
@dsl.component
def inner_op(x: str):
    print(x)


@dsl.component
def outer_op():
    print("outer task")


@dsl.pipeline(name="test-pipeline")
def pipeline():
    with dsl.ParallelFor(items=[{"a": "1"}, {"a": "2"}]) as x:
        inner_task = inner_op(x=x.a)
    outer_task = outer_op().after(inner_task)
```
### Expected result
should work, including compilation.

I want to be able to wait for the loop to complete before executing a following task.
I would expect this example to work or have another way of referencing the loop task group in the "after" call.

---

Impacted by this bug? Give it a 👍.

**Comment by kakaxilyp** [comment]
I came across the same issue when tried to convert an existing v1 pipeline implementation to v2, which had a downstream task depending on upstream tasks in a `ParallelFor` group. Then I came across this new [commit](https://github.com/kubeflow/pipelines/pull/8631) in kfp pre-release `2.0.0b12`. At least using `dsl.Collected` the compiler was able to build the DAG as expected. But would like to confirm if that was the intended way to achieve this dependency pattern in v2, if so, what was the logics behind it?

**Comment by MaxGrtz** [comment]
@kakaxilyp 
thanks for sharing this. In the previous release `dsl.Collected` was not yet available.
how do I get around the problem that my parallel for might not have an output but a side effect that I want to wait for?

**Comment by kakaxilyp** [comment]
Yeah I had the same question actually, probably better to ask @connor-mccarthy to enlighten us about the thoughts behind this new pattern.

Just a general workaround I can think of, would be letting the downstream task explicitly retry-check-loop to verify the side effect I guess, though this really should be achieved by DAG dependencies.

**Comment by connor-mccarthy** [comment]
@kakaxilyp @MaxGrtz, the original reason for blocking use of `task_a.after(task_b)` where `task_b` is defined in a loop is that it introduces some runtime behavior ambiguity: should `task_b` run after all `task_a` instances finish? Just one `task_a` finishes? Something else?

That being said, this issue has been discussed a few times and I think it's worth revisiting this choice. It seems reasonable to me to just agree on what the `.after` means and support it.

I will look into this and follow up on this thread. Thank you for bringing this up.

**Comment by MaxGrtz** [comment]
@connor-mccarthy Thanks for the clarification.
What do you think about support of after for task groups? Is is something that might be feasible long term?

**Comment by MaxGrtz** [comment]
BTW:
I solved this for now basically as @kakaxilyp suggested. I added a dummy output for the inner task (e.g. 0) and created a task for printing a List of int and used `dsl.Collected` to collect the inner task results. 
Then the next task can be made dependent on to the print task with `.after` again.

**Comment by connor-mccarthy** [comment]
> What do you think about support of after for task groups? Is is something that might be feasible long term?

This definitely is something worth considering, though there are some syntactical challenges with referring to the `TasksGroup` object, particularly with the `dsl.ParallelFor` case. For example, this reads a bit strange:

```python
with dsl.ParallelFor([1, 2, 3]) as x:
    comp_1(num=x)

comp_2(text='hi').after(x)
```

When using the context manager, the `dsl.ParallelFor` instance "becomes" the int variable `x`. Referring to it as the `TasksGroup` afterward is slightly abusing it's meaning as an int variable. These little changes in meaning are where some of the complexity in the authoring experience starts to creep in.

@MaxGrtz and @kakaxilyp, I think maybe the best option here is to wrap the `ParallelFor` sub-DAG in a pipeline, nest the pipeline, and call `.after()` on the inner pipeline. This is fully supported in the current 2.x.x release.

```python
@dsl.pipeline
def inner():
    with dsl.ParallelFor([1, 2, 3]) as x:
        comp(num=x)

@dsl.pipeline
def outer():
    inner_task = inner()
    comp().after(inner_task)
```

(untested, but this should be approximately correct)

**Comment by MaxGrtz** [comment]
@connor-mccarthy I see. Thats really ambiguous. 
I like the nested pipeline approach you proposed. I tried it and it works like a charm. Thanks!

**Comment by TheMichaelHu** [comment]
BTW we can avoid defining a separate pipeline by assigning the `ParallelFor` to a variable before using it as a context manager.

```
inner_task = dsl.ParallelFor([1, 2, 3])
with inner_task as x:
    comp_1(num=x)
comp_2(text='hi').after(inner_task)
```

**Comment by MartinHjelm** [comment]
> BTW we can avoid defining a separate pipeline by assigning the `ParallelFor` to a variable before using it as a context manager.
> 
> ```python
> inner_task = dsl.ParallelFor([1, 2, 3])
> with inner_task as x:
>     comp_1(num=x)
> comp_2(text='hi').after(inner_task)
> ```

Seems to throw an error in kfp 2.7.0

  File "/Users/bhh963/Library/Python/3.9/lib/python/site-packages/kfp/compiler/compiler_utils.py", line 730, in <setcomp>
    {pipeline.tasks[after_task] for after_task in task.dependent_tasks})
KeyError: 'for-loop-2'
