### ISSUE TITLE
feature(backend): Update healthz service in KFP v2

### ISSUE THREAD

**Issue by gkcalat** [kubeflow/pipelines#8833]
Current state:

KFP v2 inherited HealthzSerivce from KFP v1:

```
service HealthzService {
  // Get healthz data.
  rpc GetHealthz(google.protobuf.Empty) returns (GetHealthzResponse) {
    option (google.api.http) = {
      get: "/apis/v2beta1/healthz"
    };
  }
}

message GetHealthzResponse {
  // TODO(gkcalat): redesign this service to return status
  // and move server configuration into a separate service
  // TODO(gkcalat): rename or deprecate v1beta1 HealthzService
  // 
  // Returns if KFP in multi-user mode
  bool multi_user = 3;
}
```

We need to:
1. Make the service consistent with its purpose and compliant with AIP
2. Move `multi_user` and other server configuration-related information to a separate service

---

Love this idea? Give it a 👍.

**Comment by DharmitD** [comment]
@gkcalat @chensun could you elaborate on what the "AIP compliance" means? And where could I find relevant guidelines?
