### ISSUE TITLE
[frontend] Cannot GET /apis/v2beta1/healthz

### ISSUE THREAD

**Issue by chensun** [kubeflow/pipelines#8837]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)? KFP standalone deployment

*  KFP version:  2.0.0-beta.0

*  KFP SDK version: N/A

### Steps to reproduce

Hit healthz endpoint, e.g.: https://\<kfp endpoint\>/apis/v2beta1/healthz

### Expected result

Expect to get the same result for `v1beta1/healthz`, whic is something like
```
{"buildDate":"Tue Feb 7 23:42:37 UTC 2023","frontendCommitHash":"438b16597d4fcad18b7562cea5760c2b8374d6ef","frontendTagName":"2.0.0-beta.0","apiServerReady":true,"apiServerCommitHash":"438b16597d4fcad18b7562cea5760c2b8374d6ef","apiServerTagName":"2.0.0-beta.0","apiServerMultiUser":false,"multi_user":false}
```

Instead, for `v2beta1/healthz`, I got 

```
404: Cannot GET /apis/v2beta1/healthz
```

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

**Comment by chensun** [comment]
I was confused, the healthz response I saw was served by the frontend. So missing v2beta1/healthz is expected, as we haven't migrate frontend to connect to v2 APIs yet.

https://github.com/kubeflow/pipelines/blob/508b6a133ab7a0d8abefe7ac95a4de824461e30b/frontend/server/app.ts#L109-L116

**Comment by gkcalat** [comment]
This is resolved as per @chensun's comment and our discussion.
