### ISSUE TITLE
[backend] error: unknown field "isOptional" in ml_pipelines.ComponentInputsSpec.ParameterSpec

### ISSUE THREAD

**Issue by chensun** [kubeflow/pipelines#8846]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
standalone
*  KFP version: 
2.0.0-beta.0

*  KFP SDK version: 
N/A

### Steps to reproduce
Run https://github.com/kubeflow/pipelines/blob/master/sdk/python/test_data/pipelines/pipeline_with_condition.py

or find its run result in sdk execution test, e.g.: https://oss.gprow.dev/view/gs/oss-prow/pr-logs/pull/kubeflow_pipelines/8841/kubeflow-pipelines-sdk-execution-tests/1625208635669876736

Pipeline failed with error:
```
F0213 19:04:16.807068      19 main.go:74] KFP driver: failed to unmarshal component spec, error: unknown field "isOptional" in ml_pipelines.ComponentInputsSpec.ParameterSpec
componentSpec: 0xc00067b7e0
```

### Expected result

no error, pipeline succeed.

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

**Comment by Linchin** [comment]
fixed by #8860
