### ISSUE TITLE
chore(backend): Upgrade gorm to v2

### ISSUE THREAD

**Issue by gkcalat** [kubeflow/pipelines#8852]
Problem:

1. Backend's `storage` relies on `gorm` v1 package
2. `gorm` v1 is not actively developed and it will be difficult if we need to make more complex SQL queries
3. Lack of support of multiple database drivers
4. Bags and issues that will not be resolved in `gorm` v1

Solution:

1. Migrate to `gorm` v2 because it has:
   - better support of multiple database drivers and dialects (including MySQL and PostgreSQL)
   - simpler `gorm`-based SQL syntax
   - built-in serializers
   - smarter auto-migration
   - support of `ROW_NUMBER` and other advances SQL
   - support of `Upsert`
   - performance improvements
   - [other improvements](https://gorm.io/docs/v2_release_note.html)

---

Love this idea? Give it a 👍.

**Comment by Linchin** [comment]
Closed and see more info at #9859
