### ISSUE TITLE
[backend] Permission issues with api-server:2.0.0-beta.0

### ISSUE THREAD

**Issue by b4sus** [kubeflow/pipelines#8854]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
Installed following kubeflow manifests installation - master version (currently identical to tag v1.7.0-rc.0) of manifests with beta.0 instead of alpha.6 version of kubeflow pipeline components.
*  KFP version: 
2.0.0-beta.0
*  KFP SDK version: 
2.0.0b12

### Steps to reproduce

Run pipeline like described in [pipelines documentation](https://www.kubeflow.org/docs/components/pipelines/v2/author-a-pipeline/components/).
The call to `create_run_from_pipeline_func` fails with following error:
```
HTTP response body: {"error":"Failed to create a new v1beta1 run: Failed to create a run due to authorization error. Check if you have write permissions to namespace kubeflow-user-example-com: PermissionDenied: User 'user@example.com' is not authorized with reason:  (request: \u0026ResourceAttributes{Namespace:kubeflow-user-example-com,Verb:create,Group:,Version:,Resource:pipelines,Subresource:,Name:,}): Unauthorized access","code":7,"message":"Failed to create a new v1beta1 run: Failed to create a run due to authorization error. Check if you have write permissions to namespace kubeflow-user-example-com: PermissionDenied: User 'user@example.com' is not authorized with reason:  (request: \u0026ResourceAttributes{Namespace:kubeflow-user-example-com,Verb:create,Group:,Version:,Resource:pipelines,Subresource:,Name:,}): Unauthorized access","details":[{"@type":"type.googleapis.com/google.rpc.Status","code":7,"message":"User 'user@example.com' is not authorized with reason:  (request: \u0026ResourceAttributes{Namespace:kubeflow-user-example-com,Verb:create,Group:,Version:,Resource:pipelines,Subresource:,Name:,})"}]}
```
The roles and binding created from manifest look correct. After some digging I found that problem comes from [here](https://github.com/kubeflow/pipelines/blob/2.0.0-beta.0/backend/src/apiserver/server/run_server.go#L132) :
```go
	resourceAttributes := &authorizationv1.ResourceAttributes{
		Namespace: run.Namespace,
		Verb:      common.RbacResourceVerbCreate,
		Resource:  common.RbacResourceTypePipelines,
	}
	if err := s.resourceManager.IsAuthorized(ctx, resourceAttributes); err != nil {
		return nil, util.Wrapf(err, "Failed to create a run due to authorization error. Check if you have write permissions to namespace %s", run.Namespace)
	}
```
The `resourceAttributes` doesn't specify `Group`.
After adding `Group:     common.RbacPipelinesGroup,` (`common.RbacPipelinesGroup` being `pipelines.kubeflow.org`) to attributes, building the docker image and using it instead of `gcr.io/ml-pipeline/api-server:2.0.0-beta.0` I run to exactly same problem [in other place](https://github.com/kubeflow/pipelines/blob/2.0.0-beta.0/backend/src/apiserver/server/pipeline_server.go#L122). Again, the group added, image built, pushed, used, the pipeline is running.
Problem could in other places as well.

### Expected result

Pipeline runs

---

Impacted by this bug? Give it a 👍.

**Comment by sergeyshevch** [comment]
Same Issue on listing kubeflow pipelines thought UI. I was forced to update to 2.0.0-beta.0 because of AWS S3 IRSA support introduced in this update but now I'm totally blocked by this issue

**Comment by b4sus** [comment]
I had the listing issue as well, I guess that for this the fix will come eventually from manifests, but I could fix it with creating a cluster role binding like this:
```shell
kubectl create clusterrolebinding my-kubeflow-pipelines-edit --clusterrole=kubeflow-pipelines-edit --user=user@example.com
```
Cluster-role `kubeflow-pipelines-edit` is already there from manifests (I guess `kubeflow-pipelines-view`) would suffice.

**Comment by sergeyshevch** [comment]
I solved it for now by downgrading back to alpha.6. But thanks for the great idea!

**Comment by sergeyshevch** [comment]
@gkcalat Looks like this bug was introduced by https://github.com/kubeflow/pipelines/pull/8633 PR. Can you look on it?

**Comment by amybachir** [comment]
> I had the listing issue as well, I guess that for this the fix will come eventually from manifests, but I could fix it with creating a cluster role binding like this:
> 
> ```shell
> kubectl create clusterrolebinding my-kubeflow-pipelines-edit --clusterrole=kubeflow-pipelines-edit --user=user@example.com
> ```
> 
> Cluster-role `kubeflow-pipelines-edit` is already there from manifests (I guess `kubeflow-pipelines-view`) would suffice.

That didn't work for me

**Comment by gkcalat** [comment]
> @gkcalat Looks like this bug was introduced by #8633 PR. Can you look on it?

@sergeyshevch, thanks for pointing this out. This change has been reverted and the fix will be included in the next 2.0.0-beta.2 release, which is going to happen by the end of this week. This particular issue, however, seems to be unrelated.

@b4sus, @amybachir , the original error suggests that `user@example.com` doesn't have access to `kubeflow-user-example-com`. Perhaps, you were running a default sample (the provided link is broken) as these names are used as default placeholders? 

In full Kubeflow (multi-user) mode, KFP assumes that a user has access to a k8s namespace. It is created when you open the dashboard UI for the first time. For example, creating a run sends a POST request to the backend with authentication header that carries information required to authorize.

Please, test out the next release and reopen this issue if it persists. Thank you!

**Comment by b4sus** [comment]
Tested on beta.2 - issue still happens - PR submitted #9365

**Comment by chronoclast** [comment]
> I had the listing issue as well, I guess that for this the fix will come eventually from manifests, but I could fix it with creating a cluster role binding like this:
> 
> ```shell
> kubectl create clusterrolebinding my-kubeflow-pipelines-edit --clusterrole=kubeflow-pipelines-edit --user=user@example.com
> ```
> 
> Cluster-role `kubeflow-pipelines-edit` is already there from manifests (I guess `kubeflow-pipelines-view`) would suffice.

This worked great for me, **thank you so much!**

Just in case this is useful for someone else, in our setup (on-prem installation) the user parameter has a different format, with the following pattern:
`system:serviceaccount:<KUBEFLOW_USERNAME>:default`

So the resulting command is:

```bash
kubectl create clusterrolebinding <BINDING_NAME> --clusterrole=kubeflow-pipelines-edit --user=system:serviceaccount:<KUBEFLOW_USERNAME>:default
```

Note that the "user" in this case is just the `default` service account on the dedicated namespace of that user, which has the same name as the user itself. All tutorials mention the `default-editor` service account when using for example the Python Kubeflow Pipelines client (`kfp`), but this solution didn't work, it had to be `default` instead.
