### ISSUE TITLE
[Feature Request]Add metrics in experiments section of kubeflow for version 2

### ISSUE THREAD

**Issue by Rstar1998** [kubeflow/pipelines#8869]
How to get something like this (below image) in Kubeflow pipeline version 1.8.5 ( python kfp version 2  )? 

![image](https://user-images.githubusercontent.com/42741300/220033777-dc809a71-2b3e-4554-b209-bd702bc89328.png)

Currently in the experiment dashboard  , I don't see any metrics in the experiment section of the page like in the image above. Is this feature (metrics in column format) removed ?  
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/42741300/220033385-9294c251-4b59-4f3f-9dde-9bc9ce23f145.png">

Code snippet : 
```
def produce_metrics(
  # Note when the `create_component_from_func` method converts the function to a component, the function parameter "mlpipeline_metrics_path" becomes an output with name "mlpipeline_metrics" which is the correct name for metrics output.
  mlpipeline_metrics_path: Output[Metrics],
):
  import json

  accuracy = 0.9
  metrics = {
    'metrics': [{
      'name': 'accuracy-score', # The name of the metric. Visualized as the column name in the runs table.
      'numberValue':  accuracy, # The value of the metric. Must be a numeric value.
      'format': "PERCENTAGE",   # The optional format of the metric. Supported values are "RAW" (displayed in raw format) and "PERCENTAGE" (displayed in percentage format).
    }]
  }
  with open(mlpipeline_metrics_path.path, 'w') as f:
    json.dump(metrics, f)
```

I would love if we can filter and sort on metrics for a pipeline in an experiment.

**Comment by Rstar1998** [comment]
Any updates on this ?

**Comment by zijianjoy** [comment]
This is not planned for KFPv2. Instead of the above approach, you can use Scalar metrics https://www.kubeflow.org/docs/components/pipelines/v1/sdk/output-viewer/#scalar-metrics to achieve the same goal. You can define any amount of metrics with any value.

**Comment by khituras** [comment]
I would very much support the integration of scalar metrics in the experimental overview table just as it was done in v1. If you optimize a perticular metrics it helps a lot to see it directly in the table. Especially because the metric comparison view is arranged horizontally which reduces the number of visible run greatly for a large number of runs.

**Comment by kabartay** [comment]
Any update on this?
