### ISSUE TITLE
[bug] Not able to change base_image for hyperparameter_tuning_job experimental components (GetTrialsOp, GetBestTrialOp, etc)

### ISSUE THREAD

**Issue by RansSelected** [kubeflow/pipelines#8872]
*  KFP version:
1.8.19 and earlier ones

### Steps to reproduce

- I'm constructing a Vertex AI pipeline;
- I'm using Hyperparameter tuning components in my pipeline;
- I have the very strict vpc-sc settings; if I want to use components such as GetBestTrialOp, etc from 
https://github.com/kubeflow/pipelines/blob/37b3397aee374f5ea29665de7839e09e1462e794/components/google-cloud/google_cloud_pipeline_components/experimental/hyperparameter_tuning_job/utils.py 
I only have the option to use predefined base_image and  it also will try to install some packages; but because of vpc-sc I don;t have access to the public pypi;
- pipeline is failing because there is no way to modify the base image in experimental components from hyperparameter_tuning_job utils; also, there seems to be no way to specify to install packages that experimental component will try to install from the private pypi;

### Expected result

- I can specify image for the components in hyperparameter_tuning_job utils (GetBestTrialOp, GetBestHyperparametersOp, etc)
- I can specify private artifact registry for hyperparameter_tuning_job utils (GetBestTrialOp, GetBestHyperparametersOp, etc) component to load python packages from it;

---

Impacted by this bug? Give it a 👍.

**Comment by connor-mccarthy** [comment]
@RansSelected, as a short term fix, I suggest you either (1) fork the component and change the code yourself or (2) modify the object in-memory to override the image tag.
