### ISSUE TITLE
[sdk] parent_model parameter of ModelUploadOp is ignored

### ISSUE THREAD

**Issue by MainRo** [kubeflow/pipelines#8881]
### Environment

*  KFP version:
Vertex AI
*  KFP SDK version: 
kfp==1.8.19
google-cloud-pipeline-components==1.0.39
*  All dependencies version:
kfp                                   1.8.19
kfp-pipeline-spec                     0.1.16
kfp-server-api                        1.8.1

### Steps to reproduce

Create a task that uploads a model with a parent:

```python
...
model = GetVertexModelOp(model_resource_name=existing_model.output)
gcc_model.ModelUploadOp(
    project=config['project_id'],
    location=config['region'],
    display_name=model_name,
    parent_model=model.output,
    unmanaged_container_model=importer_spec.output,
    labels=model_labels.output,
)
```

The generated built json for this task is the following:

```
        "exec-model-upload": {
          "container": {
            "args": [
              "--type",
              "UploadModel",
              "--payload",
              "{\"display_name\": \"{{$.inputs.parameters['display_name']}}\", \"description\": \"{{$.inputs.parameters['description']}}\", \"explanation_spec\": {\"parameters\": {{$.inputs.parameters['explanation_parameters']}}, \"metadata\": {{$.inputs.parameters['explanation_metadata']}}}, \"encryption_spec\": {\"kms_key_name\":\"{{$.inputs.parameters['encryption_spec_key_name']}}\"}, \"labels\": {{$.inputs.parameters['labels']}}}",
              "--project",
              "{{$.inputs.parameters['project']}}",
              "--location",
              "{{$.inputs.parameters['location']}}",
              "--gcp_resources",
              "{{$.outputs.parameters['gcp_resources'].output_file}}",
              "--executor_input",
              "{{$}}",
              "--parent_model_name {{$.inputs.artifacts['parent_model'].metadata['resourceName']}}"
            ],
            "command": [
              "python3",
              "-u",
              "-m",
              "google_cloud_pipeline_components.container.v1.model.upload_model.launcher"
            ],
            "image": "gcr.io/ml-pipeline/google-cloud-pipeline-components:1.0.39"
          }
        },
```

The parent_model_name entry seems invalid:

> "--parent_model_name {{$.inputs.artifacts['parent_model'].metadata['resourceName']}}"

And the model is uploaded as a new model instead of a new version

### Expected result

The model should be uploaded as a new version.

By changing the json with this:

```
"--parent_model_name",
"{{$.inputs.artifacts['parent_model'].metadata['resourceName']}}"
```

Then it works.

### Materials and Reference

The issue probably comes from the component's yaml definition here:
https://github.com/kubeflow/pipelines/blob/google-cloud-pipeline-components-1.0.39/components/google-cloud/google_cloud_pipeline_components/v1/model/upload_model/component.yaml#L112

>  then: [concat: ["--parent_model_name ", "{{$.inputs.artifacts['parent_model'].metadata['resourceName']}}",]]

where the values should not be concatenated, maybe something like this:

>  then: ["--parent_model_name ", "{{$.inputs.artifacts['parent_model'].metadata['resourceName']}}",]

---

Impacted by this bug? Give it a 👍.

**Comment by MainRo** [comment]
This is related to #8257

**Comment by tautrimas** [comment]
Similarly, `CustomContainerTrainingJobRunOp` does not allow passing in `parent_model` at all, even though its `run` method accepts it.

**Comment by connor-mccarthy** [comment]
I believe this is fixed in the latest version of GCPC: `google-cloud-pipeline-components==1.0.43`. Please feel free to reopen if there is still an issue.

**Comment by RansSelected** [comment]
Hello,

Unfortunately I'm still experiencing same issue, parent_model is ignored;
![image](https://github.com/kubeflow/pipelines/assets/43318715/e6e6fff0-a443-4665-a216-641bd8b6d992)

I'm getting the parent like this:

`_ID = 0
## ATTENTION - when using model parent it does not create separate id, but attaches @n to exisiting id
try:
    models = aip.Model.list(project = PROJECT_ID, location = REGION ,  order_by = "create_time desc",   filter=("display_name={}").format(CURRENT_USE_CASE_UP))
    models = [model for model in models if "default" in model.version_aliases]
    PARENT_MODEL_URI = models[_ID].uri
    PARENT_MODEL_RES_NAME = models[_ID].resource_name
except Exception as e:
    print(f"No parent model exists, {e}")
    PARENT_MODEL_URI = None
    PARENT_MODEL_RES_NAME = None`

then passing to pipeline as parameter:

`pipeline_params = {
    "parent_model_uri": PARENT_MODEL_URI,
    "parent_model_res_name": PARENT_MODEL_RES_NAME,
}`
    
`pipeline_job = aip.PipelineJob(
    parameter_values=pipeline_params,...`
    

Then in pipeline, i'm getting the parent_model:

`# Get the Vertex AI model resource
 get_model_task = GetVertexModelOp(model_resource_name=parent_model_res_name).set_display_name("Get parent model")`

and finally passing as argument parent_model:

` model_upload_op = ModelUploadOp(
                    parent_model = get_model_task.outputs["model"], ...`

**Comment by connor-mccarthy** [comment]
Can you please try pip installing GCPC via `pip install git+https://github.com/kubeflow/pipelines.git@refs/pull/9608/merge#subdirectory=components/google-cloud` and seeing if the issue is resolved on this version? If so, we can release this change with the next GCPC v1 release.

**Comment by RansSelected** [comment]
Hi @connor-mccarthy !
I've installed the version and it is still not working... No error either, just not attaching the parent

The only code that works to attach the parent that works for me, is the one with the aip.Model.upload (I've created a custom component):
```python 

        model = Model.upload(
            display_name=display_name,
            serving_container_image_uri=serving_container_image_uri,
            artifact_uri=artifact_uri,
            description=description,
            project=project_id,
            location=project_location,
            labels=labels["query_labels"][CURRENT_ENV],
            sync=sync,
            parent_model = PARENT_MODEL_RES_NAME,
            version_aliases = version_aliases,
            serving_container_predict_route="/predict", # Needs to match the POST method that returns the predict
            serving_container_health_route="/health_check", # Needs to match the GET method for health checks
            serving_container_ports=[80],
        )
```

**Comment by RansSelected** [comment]
@connor-mccarthy No, no errors also previously, just not attaching the parent.
I'm not sure where to get this json, as by default the only generated templates for me are the templates for custom component sin .yaml files.

But the .yaml that I found after the installation in python-packages looks like this:

```yaml

 "exec-model-upload": {
          "container": {
            "args": [
              "--type",
              "UploadModel",
              "--payload",
              "{\"display_name\": \"{{$.inputs.parameters['display_name']}}\", \"description\": \"{{$.inputs.parameters['description']}}\", \"explanation_spec\": {\"parameters\": {{$.inputs.parameters['explanation_parameters']}}, \"metadata\": {{$.inputs.parameters['explanation_metadata']}}}, \"encryption_spec\": {\"kms_key_name\":\"{{$.inputs.parameters['encryption_spec_key_name']}}\"}, \"labels\": {{$.inputs.parameters['labels']}}}",
              "--project",
              "{{$.inputs.parameters['project']}}",
              "--location",
              "{{$.inputs.parameters['location']}}",
              "--gcp_resources",
              "{{$.outputs.parameters['gcp_resources'].output_file}}",
              "--executor_input",
              "{{$}}",
              "--parent_model_name {{$.inputs.artifacts['parent_model'].metadata['resourceName']}}"
            ],
            "command": [
              "python3",
              "-u",
              "-m",
              "google_cloud_pipeline_components.container.v1.model.upload_model.launcher"
            ],
            "image": "gcr.io/ml-pipeline/google-cloud-pipeline-components:1.0.39"
          }
        },

```

**Comment by parthmishra** [comment]
I was still getting this issue and manually patching the removal of Concat worked (providing an empty `then` statement to `IfPresentPlaceholder` also worked). Thats still kind of annoying to do and there is the other separate issue of not being able to add default version or version aliases so I've just been using a custom component to do this for now.

**Comment by connor-mccarthy** [comment]
This is fixed in the latest version of GCPC v2.

**Comment by RansSelected** [comment]
@connor-mccarthy The issue still persist in version 1.0.45
