### ISSUE TITLE
[feature] Add a version_aliases argument to ModelUploadOp

### ISSUE THREAD

**Issue by MainRo** [kubeflow/pipelines#8882]
### What feature would you like to see?

It is possible to upload new versions of a model by using the parent_model parameter of ModelUploadOp. However these versions are not aliased as "default", and there is no way to set custom aliases.
It would be nice to add this feature that is already supported in the aiplatform.Model.upload API.

### What is the use case or pain point?

There is no way to set the aliases of a new model.

### Is there a workaround currently?

After the model is uploaded, one has to change the aliases in the console.

---

Love this idea? Give it a 👍.

**Comment by Xemnas0** [comment]
I add that this is strictly necessary.
Currently, a model uploaded as new version of an existing model through ModelUploadOp **cannot** be deployed with ModelDeployOp, as there's no way to specify the version.
