### ISSUE TITLE
[sdk] ImportError: cannot import name 'container_component' from 'kfp.dsl' 

### ISSUE THREAD

**Issue by Mayuraggarwal1992** [kubeflow/pipelines#8893]
### Environment

*  KFP version: 1.8.19

*  KFP SDK version: 1.8.19

*  All dependencies version:
kfp==1.8.19
kfp-pipeline-spec==0.1.16
kfp-server-api==1.8.5
python== 3.8.1

### Steps to reproduce
* Run the below code.
`import kfp
from kfp.dsl import (
  container_component,
  ContainerSpec,
  pipeline,
) 

@container_component
def comp_typosquatting():
    return ContainerSpec(
        image='us-docker.pkg.dev/xxxx/image:v1',
        command=[
            'python',
            'main.py'
        ])

@pipeline(name="typosquatting-v1", description="xxxx generator")
def xxxx():
    # Loads the yaml manifest for each component
    full_pipeline = comp_xxxxx

    first_task = full_pipeline()

if __name__ == "__main__":
    kfp.v2.compiler.Compiler().compile(
        xxxx, "xxxxxx-step_pipeline.json"
    )
`

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

**Comment by connor-mccarthy** [comment]
@Mayuraggarwal1992, this was introduced in [`kfp==2.0.0-beta.2`](https://github.com/kubeflow/pipelines/blob/master/sdk/RELEASE.md#200-beta2), so it will not be present `kfp==1.8.19`

**Comment by pythonking6** [comment]
I cannot help but think v2 is full of bugs!!
