### ISSUE TITLE
[backend] pipelines not accessible after upgrade to 2.0.0-beta.0

### ISSUE THREAD

**Issue by bmopuri** [kubeflow/pipelines#8897]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
Full Kubeflow deployment managed by K8S team.
*  KFP version: kubeflow 1.6 and kubeflow pipelines 2.0.0-beta.0
*  KFP SDK version: 

### Steps to reproduce
This issue started occurring after pipelines upgrade to 2.0.0-beta.0 version from 2.0.0b6.  
This is on a multi user setup.   After this upgrade, I cannot list pipelines.   But I can access runs, experiments etc with no issues.

`I0225 00:06:06.131318       7 interceptor.go:29] /api.PipelineService/ListPipelinesV1 handler starting
I0225 00:06:06.131592       7 resource_manager.go:1781] Getting user identity
I0225 00:06:06.131618       7 resource_manager.go:1802] User: <****masked***>, ResourceAttributes: &ResourceAttributes{Namespace:,Verb:get,Group:pipelines.kubeflow.org,Version:v1beta1,Resource:pipelines,Subresource:,Name:,}
I0225 00:06:06.131645       7 resource_manager.go:1803] Authorizing request
I0225 00:06:06.136920       7 resource_manager.go:1832] PermissionDenied: User '***Masked*****' is not authorized with reason:  (request: &ResourceAttributes{Namespace:,Verb:get,Group:pipelines.kubeflow.org,Version:v1beta1,Resource:pipelines,Subresource:,Name:,}): Unauthorized access
E0225 00:06:06.136950       7 error.go:272] Unauthorized access
github.com/kubeflow/pipelines/backend/src/apiserver/resource.(*ResourceManager).IsAuthorized
	/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/resource/resource_manager.go:1826
github.com/kubeflow/pipelines/backend/src/apiserver/server.(*PipelineServer).checkAccess
	/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/pipeline_server.go:1018
github.com/kubeflow/pipelines/backend/src/apiserver/server.(*PipelineServer).listPipelines
	/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/pipeline_server.go:370
github.com/kubeflow/pipelines/backend/src/apiserver/server.(*PipelineServer).ListPipelinesV1
	/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/pipeline_server.go:430
github.com/kubeflow/pipelines/backend/api/v1beta1/go_client._PipelineService_ListPipelinesV1_Handler.func1
	/go/src/github.com/kubeflow/pipelines/backend/api/v1beta1/go_client/pipeline.pb.go:2108
main.apiServerInterceptor
	/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/interceptor.go:30
github.com/kubeflow/pipelines/backend/api/v1beta1/go_client._PipelineService_ListPipelinesV1_Handler
	/go/src/github.com/kubeflow/pipelines/backend/api/v1beta1/go_client/pipeline.pb.go:2110
`

URL looks like this https://***masked***/_/pipeline/?ns=mynamespace#/pipelines
For list pipelines looks like Namespace shows empty in the resource attributes although it's available in the url.
I0224 23:46:50.574897       7 resource_manager.go:1802] User: ***masked***, ResourceAttributes: &ResourceAttributes{Namespace:,Verb:get,Group:pipelines.kubeflow.org,Version:v1beta1,Resource:pipelines,Subresource:,Name:,}

Where as If I access runs https://***masked***/_/pipeline/?ns=mynamespace#/runs , this works fine. 
I0225 00:01:27.712083       7 resource_manager.go:1802] User: ***masked***, ResourceAttributes: &ResourceAttributes{Namespace:mynamespace,Verb:list,Group:pipelines.kubeflow.org,Version:v1beta1,Resource:runs,Subresource:,Name:,}

I see that https://github.com/kubeflow/pipelines/blame/master/backend/src/apiserver/server/pipeline_server.go#L362 has undergone changes with beta release.  

### Expected result

User should be able to access pipelines page with no issues. 

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

**Comment by zijianjoy** [comment]
Please note that KFP 2.0.0-beta.0 is not tested yet. Thank you for raising this problem. We should investigate how to distinguish shared namespace vs private namespace, and we need to validate authorization based on multi-user vs standalone mode.


Reference: https://github.com/kubeflow/pipelines/pull/8831

**Comment by bmopuri** [comment]
> 

Thanks @zijianjoy  for looking into this issue.  Good to know that this is still being tested.  Excited to see private/shared pipelines framework as well.

**Comment by gkcalat** [comment]
@bmopuri, thank you for reporting. This should be resolved. Please, test out the next release (`2.0.0-beta.2`) and reopen this issue if it persists. Thank you!
