### ISSUE TITLE
[feature] Kubeflow - Pass Tensorflow MapDataset from one component to another

### ISSUE THREAD

**Issue by RubensZimbres** [kubeflow/pipelines#8899]
I am implementing a Kubeflow pipeline in Google Cloud Vertex AI. Basically I have two components: prepare_data and train_model:

```
@component(
    packages_to_install = [
        "pandas==1.3.4",
        "numpy==1.20.3",
        "unidecode",
        "nltk==3.6.5",
        "gcsfs==2023.1.0"
        
    ],
)

def prepare_data(dataset:str,
        data_artifact: Output[Dataset]) -> NamedTuple("Outputs", [("ratings", Dataset),("movies", Dataset),("train", Dataset),("test", Dataset)]):
```

and...

```@component(
    packages_to_install = [
        "tensorflow-recommenders==0.7.0",
        "tensorflow==2.9.1",
    ],
)
def train_model(epochs: int, 
                ratings: Input[Dataset],
                movies: Input[Dataset],
                train: Input[Dataset],
                test: Input[Dataset],
    model_artifact: Output[Model]) -> NamedTuple("Outputs", [("model_artifact", Model)]):
```

prepare_data is generating four Tensorflow datasets (movies, ratings,train and test) that will be used inside train_model component.

How do I save (or reference) these datasets from prepare_data to be used inside train_model? Does Kubeflow already have this feature or does it need to be implemented ?For instance, I get the following error:

```AttributeError: 'Dataset' object has no attribute 'map'```

For this line of code:

```user_ids = ratings.map(lambda x: x["requisito"])```

My pipeline looks like this:

```
@dsl.pipeline(
    pipeline_root=PIPELINE_ROOT + "data-pipeline",
    name="pipeline-with-deployment",
)

def pipeline():
    prepare_data_op = prepare_data('gs://bucket-777/data.csv').set_cpu_limit('16').set_memory_limit('32G').set_caching_options(False)
    
training_op=train_model(3,prepare_data_op.outputs["ratings"],prepare_data_op.outputs["movies"],prepare_data_op.outputs["train"],prepare_data_op.outputs["test"]).set_cpu_limit('16').set_memory_limit('32G').set_caching_options(False)

    
    deploy_op = deploy_model(training_op.outputs["model_artifact"] ,"projectid","us-central1")
```

training_op.outputs["model_artifact"] is an index for similarity search of word embeddings. The whole thing works perfectly in a single piece data-train, but when I split, the datasets do not keep their properties.

Any ideas on how to overcome this issue are welcome.

![image](https://user-images.githubusercontent.com/20270054/221688507-64b52249-0744-4075-81df-a4439176954f.png)

Love this idea? Give it a 👍.

**Comment by connor-mccarthy** [comment]
Hi, @RubensZimbres. Working with input/output artifacts as you are trying to is not supported, but it's a planned feature for the SDK.

In the meantime, please follow the docs on [input artifacts](https://www.kubeflow.org/docs/components/pipelines/v2/author-a-pipeline/component-io/#input-artifacts) and [output artifacts](https://www.kubeflow.org/docs/components/pipelines/v2/author-a-pipeline/component-io/#output-artifacts).
