### ISSUE TITLE
[sdk] json.decoder.JSONDecodeError using CustomContainerTrainingJobRunOp

### ISSUE THREAD

**Issue by tautrimas** [kubeflow/pipelines#8906]
### Environment

*  KFP version: 
VertexAI pipelines V2
*  KFP SDK version:
1.8.19

*  All dependencies version:
kfp                              1.8.19
kfp-pipeline-spec                0.1.16
kfp-server-api                   1.8.5

### Steps to reproduce

Use `google-cloud-pipeline-components` version 1.0.29 or above

```python
# Op:
train_model_op = aiplatform.CustomContainerTrainingJobRunOp(
        args=["--foo", "bar"],
        ...
)
# Compile
compiler.Compiler().compile(pipeline, package_path=package_path)
```

Problem, compiled pipelines v2 JSON output contains:

```json
              "--method.args",
              "['--foo', 'bar']",
```

During runtime, training execution fails early:

```
...
File "/opt/python3.7/lib/python3.7/site-packages/google_cloud_pipeline_components/container/aiplatform/remote_runner.py", line 254, in runner
prepare_parameters(serialized_args[INIT_KEY], cls.__init__, is_init=True)
File "/opt/python3.7/lib/python3.7/site-packages/google_cloud_pipeline_components/container/aiplatform/remote_runner.py", line 210, in prepare_parameters
value = deserializer(value)
...
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
```

* It seems that incorrect serializer or deserializer is selected which causes to generate invalid JSON.
* The training works fine in 
 `google-cloud-pipeline-components` 1.0.28 which outputs
```json
              "--method.args",
              "{{$.inputs.parameters['args']}}",
```

### Expected result

Training runs successfully.

### Materials and Reference

Changes since 1.0.28 to 1.0.29: https://github.com/kubeflow/pipelines/compare/google-cloud-pipeline-components-1.0.28...google-cloud-pipeline-components-1.0.29

---

Impacted by this bug? Give it a 👍.

**Comment by BohdanBilonoh** [comment]
I found a workaround

aiplatform 1.24.1
kfp 1.8.22
google-cloud-pipeline-components 1.0.44

```python
@dsl.pipeline
def pipeline(train_job_args: str):
    training_op = gcc_aip.CustomContainerTrainingJobRunOp(
        ...
        args=train_job_args,
    )

job = aiplatform.PipelineJob(
    ...
    parameter_values={
        ...
        "train_job_args": json.dumps([
            "key", "value",
        ])
    }
)
```
