### ISSUE TITLE
[feature] PipelineJob.from_pipeline_func does not allow you to set failure_policy

### ISSUE THREAD

**Issue by anifort** [kubeflow/pipelines#8912]
### Feature Area
 /area sdk 

### What feature would you like to see?
when running a pipelines using PipelineJob.from_pipeline_func , I want to be able to set the failure_policy to fast or slot. At the moment I cannot set the failure policy

### What is the use case or pain point?
to control the failure policy for my executed pipeline

### Is there a workaround currently?
Yes, I can. compile my pipeline and set the failure policy as PipelineJob(....., failure|_policy="slow")  and then submit the pipeline

---

Love this idea? Give it a 👍.

**Comment by connor-mccarthy** [comment]
Thanks for raising this, @anifort. This pertains to the Vertex SDK. Can you open this as an Issue in https://github.com/googleapis/python-aiplatform?
