### ISSUE TITLE
Pipeline get stuck with string with \u character

### ISSUE THREAD

**Issue by eavelardev** [kubeflow/pipelines#8933]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?

[Local Deployment](https://www.kubeflow.org/docs/components/pipelines/v1/installation/localcluster-deployment/#deploying-kubeflow-pipelines) - K3s on Windows Subsystem for Linux (WSL)

*  KFP version: 
1.8.5

*  KFP SDK version: 
```
kfp                      1.8.19
kfp-pipeline-spec        0.1.16
kfp-server-api           1.8.5
```

### Steps to reproduce

```python
from typing import NamedTuple
from collections import namedtuple
import kfp
import kfp.dsl as dsl
from kfp.v2.dsl import component

@component
def product_name(text: str) -> str:
    return text

@component(packages_to_install=["emoji"])
def emoji(text: str) -> NamedTuple('Outputs', [('emoji_text', str),('emoji', str)]):

    import emoji
    from collections import namedtuple
    
    emoji_text = text
    emoji_str = emoji.emojize(':' + emoji_text + ':', language="alias") # "\u2728"
    print("output one: {}; output_two: {}".format(emoji_text, emoji_str))

    emoji_output = namedtuple('Outputs', ['emoji_text', 'emoji'])
    return emoji_output(emoji_text, emoji_str)

@component
def build_sentence(product: str, emoji: str, emojitext: str) -> str:
    print("We completed the pipeline, hooray!")
    end_str = product + " is "
    if len(emoji) > 0:
        end_str += emoji
    else:
        end_str += emojitext
    return end_str

@dsl.pipeline(name="hello-world", description="An intro pipeline")
# You can change the `text` and `emoji_str` parameters here to update the pipeline output
def intro_pipeline(text: str = "Vertex Pipelines", emoji_str: str = "sparkles"):
    product_task = product_name(text)
    emoji_task = emoji(emoji_str)
    consumer_task = build_sentence(
        product_task.output,
        emoji_task.outputs['emoji'],
        emoji_task.outputs['emoji_text']
    )

kfp_endpoint = "http://localhost:8080/pipeline"

kfp.Client(host=kfp_endpoint).create_run_from_pipeline_func(
    intro_pipeline, arguments={}, mode=kfp.dsl.PipelineExecutionMode.V2_COMPATIBLE)
```

This also happens if the value is returned directly so the `emoji` library is not the issue
```python
 return emoji_output(emoji_text, "\u2728")
```
if the `\u` character is removed from the string the pipeline works well

### Expected result

Finish execution of the pipeline and output: Vertex pipelines is :sparkles:

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

**Comment by eavelardev** [comment]
same issue https://github.com/kubeflow/pipelines/issues/7283

**Comment by connor-mccarthy** [comment]
@eavelardev, can you ensure that whatever string is being outputted is serializable by `json.dumps`? If so, it should be serializable by the executing BE.

If you can use `json.dumps` and are still experiencing runtime failures, please follow up.

**Comment by eavelardev** [comment]
I tested this
```python
return emoji_output(emoji_text, json.dumps(emoji_str))
```
It runs fine but but I get the string value with quotation marks as output. 

just mention that '\uxxxx' is the representation of an [unicode character](https://en.wikipedia.org/wiki/List_of_Unicode_characters) maybe at some point in the pipeline this isn't processed well when is received by a component.

When I define this value as argument also I got an error
```python
    ...
    consumer_task = build_sentence(
        product_task.output,
        emoji_task.outputs['emoji'],
        '\u2728'
    )
    ...
    kfp.Client(host=kfp_endpoint).create_run_from_pipeline_func(
    ...
```

```
ApiException: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'X-Powered-By': 'Express', 'content-type': 'application/json', 'date': 'Fri, 10 Mar 2023 01:50:27 GMT', 'content-length': '763', 'connection': 'close'})
HTTP response body: {"error":"Failed to create a new run.: InternalServerError: Failed to store run hello-world-bbtjr to table: Error 1366: Incorrect string value: '\\xE2\\x9C\\xA8\",\"...' for column 'WorkflowRuntimeManifest' at row 1","code":13,"message":"Failed to create a new run.: InternalServerError: Failed to store run hello-world-bbtjr to table: Error 1366: Incorrect string value: '\\xE2\\x9C\\xA8\",\"...' for column 'WorkflowRuntimeManifest' at row 1","details":[{"@type":"type.googleapis.com/api.Error","error_message":"Internal Server Error","error_details":"Failed to create a new run.: InternalServerError: Failed to store run hello-world-bbtjr to table: Error 1366: Incorrect string value: '\\xE2\\x9C\\xA8\",\"...' for column 'WorkflowRuntimeManifest' at row 1"}]}
```

Also, it doesn't run if the compiled yaml file is uploaded to the UI. Mention that this pipeline run in Vertex AI using the compiler  v2
```python
from kfp.v2 import compiler

compiler.Compiler().compile(
    pipeline_func=intro_pipeline, package_path="intro_pipeline_job.json"
)

job = aip.PipelineJob(
    display_name="intro pipeline job",
    template_path="intro_pipeline_job.json"
).run()
```
But this can't be uploaded to the UI with KFP 1.8.5.

**Comment by connor-mccarthy** [comment]
> I get the string value with quotation marks as output.

Can you describe what you mean by this?

It looks like `json` can `dump` the following:
`python -c 'import json; print(json.dumps("\\uxxxx"))'`
`python -c 'import json; json.dumps(u"xxxx")'`

**Comment by eavelardev** [comment]
> Can you describe what you mean by this?

I meant in the output pipeline, I get -> Vertex Pipelines is "\u2728", instead of -> Vertex pipelines is :sparkles:

I got :sparkles: output by the `emoji` component but when that value is used as argument by `build_sentence` component the pipeline got stuck

**Comment by hilcj** [comment]
Tried the pipeline from top using kfp 2.0.12b seems working file 
![image](https://user-images.githubusercontent.com/17188784/224438908-ccdcb0f1-7afc-4e6b-89b5-ef197bbe4adc.png)

**Comment by connor-mccarthy** [comment]
/assign @gkcalat

Upon more investigation/understanding, this looks like it may be a MP BE issue after all.

**Comment by eavelardev** [comment]
> reading from the text that the trouble is with that pipeline on KFP backend instead of Vertex... Did I read that correctly or miss something?

As I mentioned at the beginning, I'm using a [Local Deployment](https://www.kubeflow.org/docs/components/pipelines/v1/installation/localcluster-deployment/#deploying-kubeflow-pipelines). The instructions are for KFP `1.8.5` it seems `1.8.19` isn't configured for local deployment. In this setup is where I have the issue.

**Comment by connor-mccarthy** [comment]
Thank you for clarifying, @eavelardev.

May not be the fix, but you can always set `PIPELINE_VERSION=1.8.19` to deploy that version locally.

**Comment by eavelardev** [comment]
> May not be the fix, but you can always set `PIPELINE_VERSION=1.8.19` to deploy that version locally.

I tried that, but I get an error for `1.8.19` 

`kubectl apply -k manifests/kustomize/cluster-scoped-resources`
```
error: resource mapping not found for name: "applications.app.k8s.io" namespace: "" from "manifests/kustomize/cluster-scoped-resources": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
ensure CRDs are installed first
```

**Comment by connor-mccarthy** [comment]
Also, FYI this [comment above](https://github.com/kubeflow/pipelines/issues/8933#issuecomment-1464710187) @gkcalat @chensun
