### ISSUE TITLE
[backend] defaultNamespace cmd argument for api-server since beta.0

### ISSUE THREAD

**Issue by b4sus** [kubeflow/pipelines#8945]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
From manifests, using version beta.0 images instead of alpha.6
*  KFP version: 
2.0.0-beta.0
*  KFP SDK version: 
2.0.0b12 (but it is irrelevant I think for this)

### Steps to reproduce

Apply `ml-pipeline` deployment on a cluster where there is no default experiment yet created in mysql. The pod will fail to start with the error:
```
main.go:76] Failed to create default experiment. Err: Failed to create the default experiment: Invalid input error: Namespace cannot be empty
```

### Expected result

Pod starting creating the default experiment.

### Materials and Reference

In pull request #8633 there was new command line argument for api-server added named `defaultNamespace` with an empty string as default value. This value is used for creation of new default experiment if it is not yet there - you will not have this issue if you are just updating because the default experiment will be already there (in mysql). There is an empty string check [here](https://github.com/kubeflow/pipelines/blob/2.0.0-beta.0/backend/src/apiserver/resource/resource_manager.go#L1027) throwing the error.

I guess as a workaround I can manually insert an experiment and default experiment id into the mysql with some reasonable values and pod will start (still to try).

I assume `Dockerfile`'s `CMD` has to be adjusted to provide this argument when executing api-server - not sure what the value should be though - what is the indented value?

---

Impacted by this bug? Give it a 👍.

**Comment by gkcalat** [comment]
@b4sus, thank you for reporting. This should be resolved. Please, test out the next release (`2.0.0-beta.2`) and reopen this issue if it persists. Thank you!
