### ISSUE TITLE
[BUG] ml-pipeline pod CrashLoopBackOff: Config DBConfig.ExtraParams not specified, skipping

### ISSUE THREAD

**Issue by Al4DIN** [kubeflow/pipelines#8985]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?

=> Using Kustomize method 

*  KFP version: 

=> Kubeflow 1.6.1
*  KFP SDK version: 

### Steps to reproduce

The only pods that have health issue are ml-pipeline & ml-pipeline-persistenceagent when I did deploy kubeflow on my kubernetes cluster 1.25

Here's the logs f **ml-pipeline**
![image](https://user-images.githubusercontent.com/49256330/224974401-5ba17524-22b7-4af1-bf46-ed9971083695.png)

For **ml-pipeline-persistenceagent** 
![image](https://user-images.githubusercontent.com/49256330/224974588-8da9bb3f-dd1f-42aa-ad40-5c87383d767d.png)

And by looking at different issues and solutions, I tried to investigate the MySQL pod since these pods are related to storage and I did find the communication error between the ml-pipeline pods and mysql pod

![image](https://user-images.githubusercontent.com/49256330/224974973-166e048b-12c2-46ef-ba88-cbf7afaff644.png)

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

**Comment by chensun** [comment]
Kubeflow 1.6.1 was tested against k8s 1.22. If possible, can you try lower the k8s version? And we'll need to look into the possible incompatibility issue later.

**Comment by woof** [comment]
Same issue
k8s v1.21.3, kf pipeline 1.8.5

**Comment by shalberd** [comment]
seems like I have this issue, too, Red Hat Openshift Pipelines v1.8.2 via OLM on Openshift OCP 4.10.47. What do you mean by enableServiceLinks: false? Where in your code does that have an impact? I am downstream in Red Hat Opendatahub, for context.

**Comment by tppalani** [comment]
Hi @Al4DIN 

will able to resolve the above issue if yes can you please share the notes how did you fixed
