### ISSUE TITLE
[backend] Minio failed to put file

### ISSUE THREAD

**Issue by ketangangal** [kubeflow/pipelines#8989]
I am getting this error :

```

This step is in Error state with this message: Error (exit code 1): failed to put file:
 Get "http://minio-service.kubeflow:9000/mlpipeline/?location=": dial tcp 100.68.6.113:9000: i/o timeout
```

Restarting the Kfp pods under kubeflow namespace -> did not work [ same error ]
i also check volume mounts | Everything is okay from that side.

Hence i am confused now with next steps. Need your help regarding the same.

**Comment by chensun** [comment]
Hi @ketangangal, which KFP version/deployment means are you using? And how did you hit this error? Is there a specific pipeline you're running?

**Comment by ketangangal** [comment]
@chensun 
Kfp Pipeline Version : 1.8.0 
Installation Method: Kustomise 

We have a setup of multiple gpu and cpu nodes. When i hit run training sometimes i get this error: 

```
This step is in Error state with this message: Error (exit code 1): failed to put file:
 Get "http://minio-service.kubeflow:9000/mlpipeline/?location=": dial tcp 100.68.6.113:9000: i/o timeout
```

**Comment by ketangangal** [comment]
@chensun

**Comment by tiru1930** [comment]
@chensun @ketangangal am also seeing same issues,how to resolve or

**Comment by ketangangal** [comment]
@chensun any idea on this issue ? , @tiru1930

**Comment by tbaggu** [comment]
@ketangangal  looks like it is some DNS issue in my case at least, i,e pod that are running on worker node are not able to communicate to master nodes ips , nslookup kubernetes.default is failing from worker node pod, not sure how to solve this issue got stuck at there

**Comment by ketangangal** [comment]
@tbaggu Please let me know if you have solved it !

**Comment by tbaggu** [comment]
@ketangangal nope, not yet, so far I just moved my worker node to under the same subnet and it is working.

**Comment by ketangangal** [comment]
@tbaggu can you explain me more about you solution to move the worker under same subnet !

**Comment by koalalorenzo** [comment]
We have also encountered the same issue. Any suggestion is welcome! :O It looks like this container does not uses the same nameserver as the others or the cluster.

**Comment by vvnpan** [comment]
The minio-gateway was [scheduled to be removed](https://github.com/minio/minio/issues/14331) in June 2022, I see that kubeflow is still using the 2019 version of the image. Are there plans to make updates to using the latest Minio?

**Comment by ketangangal** [comment]
Hello, 

This issue occurs due to minio backend change from efs to ebs for me. Since ebs it not multi AZ we end up having no access to minio from different AZ from where Minio ebs is present. 

**So Please check your minio backend and verify if its available through out AZ.**
