### ISSUE TITLE
CustomTrainingJobOp: Failed to parse the container spec json payload to requested prototype.

### ISSUE THREAD

**Issue by bertChristiaens1** [kubeflow/pipelines#8991]
### Environment

*  How do you deploy Kubeflow Pipelines (KFP)?
I am using Vertex AI with the v2 python SDK (kfp==2.0.0b12), together with the `google-cloud-pipeline-components==1.0.33` library, compile the pipeline and run it with aiplatform.run().
*  KFP version:
v2
*  KFP SDK version:
2.0.0b12

### Steps to reproduce
I am running a simple pipeline with only one component from the `google-cloud-pipeline-components`: google_cloud_pipeline_components.experimental.custom_job.CustomTrainingJobOp to start a vertex ai custom training job. I am using the `containerSpec` option for the Job, which links to a container in gcr (google container registry). This worked without any problems until last week and no changes have been made to the code (it was just running in production).

At the moment, the pipeline component fails immediately with the error `Failed to parse the container spec json payload to requested prototype.  Payload: {...}`.
I already double checked the formatting of the specs that are passed with the CustomTrainingJobOp and they match the google documentation https://cloud.google.com/vertex-ai/docs/reference/rest/v1/CustomJobSpec#ContainerSpec.

### Expected result

The pipeline component should start a training job on vertex training.

### Labels

Impacted by this bug? Give it a 👍.

**Comment by connor-mccarthy** [comment]
@bertChristiaens1, it looks like you're using KFP SDK 2.x.x with GCPC 1.x.x, while GCPC 1.x.x requires KFP SDK 2.x.x.

Can you try with GCPC 2.x.x? Please re-open if you continue to face this error.
