### ISSUE TITLE
[feature] Add support for ad hoc triggering of recurring runs to the KFP SDK

### ISSUE THREAD

**Issue by droctothorpe** [kubeflow/pipelines#8997]
### Feature Area

/area sdk

### What feature would you like to see?

Ad hoc trigger support for recurring runs in the KFP SDK (and eventually the UI).

### What is the use case or pain point?

Currently, there is no way to ad hoc trigger a recurring run in KFP. A common user experience is creating a recurring run then validating it works as expected by creating a run. If the cron expression is set to once a day, it's not reasonable to wait until the cron expression is satisfied.

Argo Workflows makes this turn key in its UI and CLI. At the moment, this is not possible in KFP.

### Is there a workaround currently?

The only workaround currently is to take some of the parameters passed to `create_recurring_run` and manually pass them to `create_run_from_pipeline_package`. Part of the problem with this approach, in addition to the fact that it's not obvious or intuitive, is that there parameters of these functions vary in subtle ways. For example, `create_recurring_run` accepts an `experiment_id`, whereas `create_run_from_pipeline_func` accepts an `experiment_name`. 

---

Love this idea? Give it a 👍.

**Comment by chensun** [comment]
Replied in https://github.com/kubeflow/pipelines/pull/8998#issuecomment-1473287386, and we should probably continue the discussion here, as it likely can't be solved by SDK alone.

> A common user experience is creating a recurring run then validating it works as expected by creating a run.

I wonder if the common scenario should be the other way around. Are we usually create a run first then turn it into a recurring once verified the run works?

**Comment by droctothorpe** [comment]
I think validation is just one use case for ad hoc executions of recurring runs, but there are many others.

As a frame of reference, the Argo Workflows UI supports push-button ad hoc executions:

![](https://i.imgur.com/sWREakU.png)

The Argo Workflows CLI also supports ad hoc execution of CronWorkflows:

```bash
argo submit --from cronwf/my-cron-wf
```

**Comment by chensun** [comment]
> I think validation is just one use case for ad hoc executions of recurring runs, but there are many others.

For my education, care to elaborate on some "others"?
"A has some feature thus we should have the same" isn't a convincing argument IMO. I'm not denying the value of the feature, but it just feels unclear to me, and I would like to learn more from a user's perspective.

Anyway, if you would like to proceed, please follow the [contribution guidelines](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#contribution-guidelines) for the next steps.

**Comment by droctothorpe** [comment]
> I would like to learn more from a user's perspective.

Sorry if I was too vague / hand-wavy about this! 

Common use cases for recurring runs on our platform are ETL and report creation.

Sometimes these operations need to happen outside of the window specified by the recurring run's cron expression. This can be when new data arrives (for ETL), or updated reports are required ad hoc, i.e. unanticipated input or output.

In addition, complex, long-running pipelines can be brittle and fail for various reasons. When this happens, users often want to re-run the pipeline to rule out one-off errors, like short-lived hiccups in dependencies. It can also sometimes be helpful to live debug an active pipeline.

I can interview some of our end users for more specifics if it helps! I am but a humble MLOps peon.

> please follow the [contribution guidelines](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#contribution-guidelines) for the next steps

TIL about the additional steps introduced by https://github.com/kubeflow/pipelines/pull/8482! Will definitely adhere to it for future feature contributions.
