### ISSUE TITLE
[backend] Getting read_artifact from kfp.Client().runs results in internal server error

### ISSUE THREAD

**Issue by tama-biro** [kubeflow/pipelines#9003]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?

Kubeflow deployed using Kubeflow manifests repo to Azure Kubernetes cluster

*  KFP version: 

2.0.0-alpha3

*  KFP SDK version: 

1.8.19

### Steps to reproduce

Calling `read_artifact` on `client.runs`, similar to [this issue](https://github.com/kubeflow/pipelines/issues/4327) results in a 500 Internal Server error.

Top of error message says `InternalServerError: failed to unmarshal workflow` and at bottom `Invalid input error: Unknown execution spec`.

<img width="706" alt="image" src="https://user-images.githubusercontent.com/74452047/225863091-48ac11ca-111d-430a-9153-b6c413ff47de.png">

### Expected result

Previously, this has returned artifact as dictionary where `data` can be picked out to retrieve run output.

### Materials and Reference

Following steps in [this issue](https://github.com/kubeflow/pipelines/issues/4327) for a run created with `create_run_from_pipeline_func` should reproduce error.

---

Impacted by this bug? Give it a 👍.

**Comment by Linchin** [comment]
I think the same error was brought up in #8256, and fixed in #8287. Maybe you can upgrade the backend and see if the error persist? The fix is included from 2.0.0-alpha.5 onwards. I will close the issue for now, but feel free to reopen if upgrade doesn't work.
