### ISSUE TITLE
[backend] The ApiParameter in v1 run should store in v2 runtime config.

### ISSUE THREAD

**Issue by jlyaoyuli** [kubeflow/pipelines#9008]
In v1 run, we use `APIParameter` in `pipeline_spec` to store the parameters. After introducing runtime_config concept in v2 run, we have to store the parameters into `RuntimeParameter` in `runtime_config`.

Note: The change is also needed in recurring run.

<img width="1497" alt="Screenshot 2023-03-17 at 2 00 55 PM" src="https://user-images.githubusercontent.com/56132941/226057903-7d674db1-5790-4359-a4cc-368486f1d269.png">

<img width="1497" alt="Screenshot 2023-03-17 at 2 02 30 PM" src="https://user-images.githubusercontent.com/56132941/226057936-f7a0ce0f-17e3-429d-92d7-9efc93c3d75c.png">

**Comment by zijianjoy** [comment]
In V1 API, the `apiParameter` field is `{string: string}` value pair: https://www.kubeflow.org/docs/components/pipelines/v1/reference/api/kubeflow-pipeline-api-spec/#/definitions/apiParameter.

In V2 API, the runtime config is `{string: protobufValue}` pair: https://github.com/kubeflow/pipelines/blob/master/backend/api/v2beta1/runtime_config.proto#L26.

I am afraid they are not compatible. Why don't we continue using V1 API for V1 runs?

**Comment by jlyaoyuli** [comment]
Thanks @zijianjoy for pointing this out! I agree with this point.

Therefore, the main problem is not storing v1's `APIParameter` into v2's runtime config. We should keep v1 and v2 separately. However, `APIParameter` in v1 recurring run is still missing.

**Comment by jlyaoyuli** [comment]
Re-define in https://github.com/kubeflow/pipelines/issues/9012
