### ISSUE TITLE
[feature] How to save kubeflow logs in GCP Stackdriver Monitoring for specific interval of time (like 3 months, 6 months) etc ?

### ISSUE THREAD

**Issue by Rstar1998** [kubeflow/pipelines#9031]
Hi folks , I need  to save Kubeflow pipeline  logs in GCP Stackdriver Monitoring for specific interval of time (like 3 months, 6 months) etc. How can I can I achieve something like that ? Any configurations that I need to change ?
As of now I get the below error prompt:

<img width="788" alt="image" src="https://user-images.githubusercontent.com/42741300/227166189-1b5bc4c4-a96e-433e-a8c0-584c3f85d1cc.png">

Also can we store Kubeflow pipeline logs to GCS buckets ?

**Comment by zijianjoy** [comment]
The documentation at https://cloud.google.com/stackdriver/docs/solutions/gke/using-logs should include instructions on how to access and view logs for GKE.

**Comment by zijianjoy** [comment]
It seems that logging is not enabled for your GKE clusters. Can you confirm if you are receiving any other logs from the same cluster?

**Comment by Rstar1998** [comment]
@zijianjoy Yes I do received other logs from the gke but I not able to get logs from a specific pods or related to a container running in kubeflow.
