### ISSUE TITLE
[feature] Setting name for worker in dsl.ParallelFor

### ISSUE THREAD

**Issue by zanelliriccardo** [kubeflow/pipelines#9055]
### Feature Area

area components 

### What feature would you like to see?

Possibility to set a suffix for workers in dsl.ParallelFor component

### What is the use case or pain point?

I need to parallelize two different model and merge their prediction. Now I cannot see which worker works on which model unless opening a component and looking its argument.

### Is there a workaround currently?

No workaround because LoopArgument are initialized inside ParallelFor

---

Love this idea? Give it a 👍.

**Comment by jlyaoyuli** [comment]
@zanelliriccardo Can you share which pipeline you were running (KFP or vertex pipeline)? Because it might be related to backend changes.

**Comment by zanelliriccardo** [comment]
> @zanelliriccardo Can you share which pipeline you were running (KFP or vertex pipeline)? Because it might be related to backend changes.

vertex pipeline

**Comment by connor-mccarthy** [comment]
We have not begun work on this item, though we welcome contribution! I haven't fully thought through side-effects and API design, but one path toward achieving this could be via the [existing task keys](https://github.com/kubeflow/pipelines/blob/4a57ab69ddc0abf08daa73473646492bad7ab38d/api/v2alpha1/pipeline_spec.proto#L101) in the `PipelineSpec` message:

<img width="673" alt="image" src="https://github.com/kubeflow/pipelines/assets/55268212/082b0603-efcc-495f-a0a7-ea8dff34e37d">
