### ISSUE TITLE
[sdk] Can't filter pipelines by namespace/profile

### ISSUE THREAD

**Issue by mChowdhury-91** [kubeflow/pipelines#9074]
### Environment

*  KFP version:
$pip list | grep kfp -->
kfp                       1.8.19
kfp-pipeline-spec         0.1.16
kfp-server-api            1.6.0

### Steps to reproduce

 1. Log in Kubeflow and select your namespace/profile and go to Pipelines component
2. I can see the pipelines uploaded by other teams(irrespective of profile) and others can view my pipelines as well

### Expected result

 Behaviour should be same as Runs tab. Others pipelines should be hidden as the yaml might hold confidential information

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

**Comment by zijianjoy** [comment]
This item is being discussed in https://github.com/kubeflow/pipelines/issues/4649, closing this bug to deduplicate issues.
