### ISSUE TITLE
[bug] Missing backticks in BigQuery table reference

### ISSUE THREAD

**Issue by statmike** [kubeflow/pipelines#9092]
### Environment

Error is related to how a query is formatted for passing to BigQuery.

### Steps to reproduce

Use the prebuilt pipeline at: https://github.com/kubeflow/pipelines/blob/master/components/google-cloud/google_cloud_pipeline_components/experimental/automl/forecasting/prophet_predict_pipeline.yaml

Where the input table name requires a [quoted identifier](https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical).

An error is returned by the component `bigquery-query-job` with `taskInfo: name: remove-feature-columns` 

### Expected result

Accept any allowable BigQuery table name as input.

Impacted by this bug? Give it a 👍.

**Comment by statmike** [comment]
I traced the location of the the missing backticks and created a [pull request](https://github.com/kubeflow/pipelines/pull/9093)

**Comment by TheMichaelHu** [comment]
Good catch, we should be escaping all BQ tables with backticks in these queries. I will fix in the pipeline definition that generates this pipeline. Otherwise your fix will be overwritten the next time the pipeline gets compiled.
