### ISSUE TITLE
[feature] Add environment variables support for ContainerSpec when definining Container Component in v2

### ISSUE THREAD

**Issue by juansebashr** [kubeflow/pipelines#9102]
### Feature Area

area sdk

### What feature would you like to see?

Add environment variables support to the ContainerSpec class when defining a container_component in v2 code improving reusability on the container components. Is odd that is not implemented because is a fairly easy change of [code](https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/components/structures.py#LL324C16-L324C16),I open a PR that should did the trick.

### What is the use case or pain point?

Can input the env variables that you want especially when using a container image that is used on other projects and is a problem to modify.

### Is there a workaround currently?

I need to define an environment variable direct on the Dockerfile or put them on args and add an export command to the container image, but this is a lot less elegant

---

Love this idea? Give it a 👍.

**Comment by connor-mccarthy** [comment]
@juansebashr, is this issue resolved via the [`.set_env_variable`](https://kubeflow-pipelines.readthedocs.io/en/2.0.0b13/source/dsl.html#kfp.dsl.PipelineTask.set_env_variable) task [configuration method](https://www.kubeflow.org/docs/components/pipelines/v2/pipelines/pipeline-basics/#task-configurations)?

It was a deliberate choice to not permitting setting environment variables on [Container Components](https://www.kubeflow.org/docs/components/pipelines/v2/components/container-components/) in KFP SDK v2, as it would introduce an asymmetry with [Python Components](https://www.kubeflow.org/docs/components/pipelines/v2/components/lightweight-python-components/) which do not permit binding an environment variable to the component. Instead, the single way to do this is by setting the environment variable on the task.

**Comment by juansebashr** [comment]
@connor-mccarthy Ohhh I understand, my bad! Thank you so much! :D

As a humble opinion, maybe should put a little paragraph on the component docs explaining that the env variables should be defined on the task configurations, the instinct is to define on the component, especially when migrating from V1 hehe.

**Comment by connor-mccarthy** [comment]
Makes sense. Will consider adding a note on this in the [migration instructions](https://www.kubeflow.org/docs/components/pipelines/v2/migration/).

**Comment by connor-mccarthy** [comment]
@juansebashr, PR updating the docs: https://github.com/kubeflow/website/pull/3489

**Comment by zijianjoy** [comment]
Closing this issue for now, feel free to reopen if you have more questions.

**Comment by sephib** [comment]
Hi,
Assuming we want to use the `container_component` within a [local runner](https://www.kubeflow.org/docs/components/pipelines/v2/local-execution/), how can we add the environment variables?
> Instead, the single way to do this is by setting the environment variable on the task.  

The rational is that since we share the  [Container Components](https://www.kubeflow.org/docs/components/pipelines/v2/components/container-components/), then it would be good to verify that the component is running correctly when reutilizing it in a different project .
for example - 
```python
#src/components.py
@container_component
def extract_data_component(queries_path:str,
                           output_uri: Output[Dataset]
                           ):

    return ContainerSpec(
        image="eu.gcr.io/common/data-extraction:v1.4.2",
        command=["python", "run.py"], 
        args=['--queries_path', "queyr/query_example.sql",
              '--output_uri', f"{output_uri.uri}"
              ], 
        )
```
I would like to run the component using
```python
# tests/test_extract_data.py
from src.components import extract_data_component
from kfp import local

local.init(runner=local.DockerRunner(), 
           pipeline_root="tmp/outputs"
           )

extract_data_task = extract_data_component(
    queries_list="queries/example2.sql",
)
```

**Comment by connor-mccarthy** [comment]
This is a good feature request, @sephib. Since the feature you are requesting is somewhat different than the original GitHub issue, would you mind re-opening another feature request issue with this content?

**Comment by sephib** [comment]
sure - here is the [feature request](https://github.com/kubeflow/pipelines/issues/10504)
