### ISSUE TITLE
[backend] Argo Workflows is Using Legacy Pod Patches

### ISSUE THREAD

**Issue by TobiasGoerke** [kubeflow/pipelines#9110]
When executing any pipeline, the following lines are logged in the `wait` container:

```
# ...
time="2023-04-06T07:58:47.339Z" level=info msg="Create workflowtaskresults 403"
time="2023-04-06T07:58:47.339Z" level=warning msg="failed to patch task set, falling back to legacy/insecure pod patch, see https://argoproj.github.io/argo-workflows/workflow-rbac/" error="workflowtaskresults.argoproj.io is forbidden: User \"system:serviceaccount:kubeflow-user-example-com:default-editor\" cannot create resource \"workflowtaskresults\" in API group \"argoproj.io\" in the namespace \"kubeflow-user-example-com\""
time="2023-04-06T07:58:47.356Z" level=info msg="Patch pods 200"
time="2023-04-06T07:58:47.362Z" level=info msg="Killing sidecars []"
time="2023-04-06T07:58:47.362Z" level=info msg="Alloc=7530 TotalAlloc=12844 Sys=24530 NumGC=4 Goroutines=12"
```

In addition to Argo considering this method to be legacy / insecure, we've had issue with pipeline steps being stuck / not being displayed as succeeded in the UI, depending on the files that were written to the OutputPath, as the resulting pod's annotation was malformed. 

Fixing this RBAC issue is easily done by adding the resource `workflowtaskresults` to the [aggregate-to-kubeflow-pipelines-edit ClusterRole](https://github.com/kubeflow/pipelines/blob/1caa8e0d6889e50cde217a18abddb2c17df6ef6e/manifests/kustomize/base/installs/multi-user/view-edit-cluster-roles.yaml#L100).

However, this will cause Argo Workflow to no longer write the annotation `workflows.argoproj.io/outputs` to the pipeline's pods, which several Kubeflow components rely on, e.g.:
- [metadata_writer](https://github.com/kubeflow/pipelines/blob/3f4d686f6a04d0e2c2bda551af82981e329ed95c/backend/metadata_writer/src/metadata_writer.py#L72)
- [cache mutation](https://github.com/kubeflow/pipelines/blob/3f4d686f6a04d0e2c2bda551af82981e329ed95c/backend/src/cache/server/mutation.go#L44)

**Comment by zijianjoy** [comment]
Assign @Linchin to fix this issue by adding RBAC permission to aggregate-to-kubeflow-pipelines-edit. 

cc @gkcalat

**Comment by Sharathmk99** [comment]
I did face the same problem in Kubeflow 1.7.0. Thank you @zijianjoy  for looking into it.

**Comment by Linchin** [comment]
Hi @TobiasGoerke, thank you so much for reporting the issue! I found the place to add the permission, which seems to be associated with permissions given to service account in a namespace. Could you please help me and share a minimum pipeline that has the original issue, i.e., "pipeline steps being stuck / not being displayed as succeeded in the UI"? Thank you!

**Comment by TobiasGoerke** [comment]
> Hi @TobiasGoerke, thank you so much for reporting the issue! I found the place to add the permission, which seems to be associated with permissions given to service account in a namespace. Could you please help me and share a minimum pipeline that has the original issue, i.e., "pipeline steps being stuck / not being displayed as succeeded in the UI"? Thank you!

Glad to hear so! 
Unfortunately, I'm not able to reproduce the stuck pipeline issue anymore. I recall the output file's content being stored to the pod annotation `workflows.argoproj.io/outputs`, though.. 
The pipeline must have looked similar to this

```python
# Attention: this example doesn't reproduce the issue
import kfp.dsl as dsl
from kfp.components import OutputPath, create_component_from_func


def example_step(test_path: OutputPath()):
    import pickle
    import numpy as np

    arr = [np.array([1, 2, 3]), np.array([1, 2, 3]), np.array([1, 2, 3])]

    with open(test_path, "wb") as f:
        pickle.dump(arr, f)

    print("Finished")


example_op = create_component_from_func(
    example_step, base_image=BASE_IMAGE, packages_to_install=["numpy"]
)


@dsl.pipeline(name="Test Pipeline")
def pipeline():
    example_op()


plain_pipeline_result = client.create_run_from_pipeline_func(
    pipeline, arguments={}, experiment_name=EXPERIMENT_NAME, namespace=NAMESPACE
)

```

**Comment by proluoo** [comment]
> Hi @TobiasGoerke, thank you so much for reporting the issue! I found the place to add the permission, which seems to be associated with permissions given to service account in a namespace. Could you please help me and share a minimum pipeline that has the original issue, i.e., "pipeline steps being stuck / not being displayed as succeeded in the UI"? Thank you!

I met the same question, and how to deal with it?

**Comment by TobiasGoerke** [comment]
> > Hi @TobiasGoerke, thank you so much for reporting the issue! I found the place to add the permission, which seems to be associated with permissions given to service account in a namespace. Could you please help me and share a minimum pipeline that has the original issue, i.e., "pipeline steps being stuck / not being displayed as succeeded in the UI"? Thank you!
> 
> I met the same question, and how to deal with it?

Our users redesigned their pipelines and I lost track of the issue as stuck pipelines haven't resurfaced for us.
If you're currently having this problem, I'm sure providing a reproducible example would lead to this issue getting fixed.
Cheers!
