### ISSUE TITLE
[backend] failure to run pipeline OCI runtime create failed: runc create failed: unable to start container process: exec: "/var/run/argo/argoexec": stat /var/run/argo/argoexec: no such file or 

### ISSUE THREAD

**Issue by amybachir** [kubeflow/pipelines#9119]
All pipeline runs fail with the following error message: 
```
Error: failed to start container "main": Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/var/run/argo/argoexec": stat /var/run/argo/argoexec: no such file or directory: unknown
```
### Environment

*  KFP Standalone
*  KFP version: 2.0.0b13
*  KFP SDK version: 
kfp                      2.0.0b13
kfp-pipeline-spec        0.2.0
kfp-server-api           2.0.0a6

### Steps to reproduce

1. compile pipeline from hello_world sample https://github.com/kubeflow/pipelines/blob/2.0.0b13/samples/v2/hello_world.py
2. use the UI to create a pipeline run after uploading the pipeline yaml from the UI

### Expected result
pipeline should run successfully 

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

**Comment by gkcalat** [comment]
Hi @amybachir,

Could you please clarify witch backend version are you using for the standalone deployment?

**Comment by kdrivas** [comment]
@amybachir I had a similar issue and I migrated the emissary executor following these instructions and it worked 
https://www.kubeflow.org/docs/components/pipelines/v1/installation/choose-executor/#emissary-executor

**Comment by REXCHE** [comment]
for those using minikube and kubeflow, this error occcurs when you install  kubefflow by using the env  "platform-agnostic-pns".

`kubectl apply -k "github.com/kubeflow/pipelines/manifests/kustomize/env/platform-agnostic-pns?ref=$PIPELINE_VERSION" `

The error is displayed on the dashboards when you run a pipeline as 

> kubeflow pipeline Failed to retrieve pod logs  

when you click on details you get :
> Error response: podname argument is required

when you run minikube logs you will get the this error message

> failure to run pipeline OCI runtime create failed: runc create failed: unable to start container process: exec: "/var/run/argo/argoexec": stat /var/run/argo/argoexec: no such file

  you need to either install a different kubeflow pipeline which supports the emissary executor 

`export PIPELINE_VERSION=2.0.1`

`kubectl apply -k "github.com/kubeflow/pipelines/manifests/kustomize/env/platform-agnostic-emissary?ref=$PIPELINE_VERSION"  `

or you change the emissary executor of your minikube by runniing this four lines of code

`kubectl config set-context --current --namespace kubeflow`

`
kubectl patch configmap workflow-controller-configmap --patch '{"data":{"containerRuntimeExecutor":"emissary"}}' 
`

`systemctl daemon-reload`

`systemctl restart kubelet`

**Comment by muhammadyaseen** [comment]
Thank you @REXCHE for posting the detailed instructions. I can confirm that this solution worked for me (although with slight changes because of my environment). I will detail it here with the hope that others may find it helpful.

I was getting the following error while running any pipeline:
```
minikube kubectl -- describe pod -n kubeflow-user-example-com hello-pipeline-2vkhx-4019745573 

.
.
(irrelevant output omitted)

 Warning  Failed     3m36s  kubelet            Error: failed to start container "main": Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/var/run/argo/argoexec": stat /var/run/argo/argoexec: no such file or directory: unknown
```

I applied the suggested fix:

```
$ minikube kubectl -- config set-context --current --namespace kubeflow
>>> Context "minikube" modified.

$minikube kubectl -- patch configmap workflow-controller-configmap --patch '{"data":{"containerRuntimeExecutor":"emissary"}}' 
>>> configmap/workflow-controller-configmap patched

$systemctl daemon-reload
```

After this, I couldn't run `systemctl restart kubelet` because (if I understand correctly) `kubectl` isn't running as a service in my environment (Manjaro).

Instead, I had to restart it as follows:

```
minikube stop

minikube start
```

After these changes, my pipeline run succeeded.

One interesting detail is that I tried the same setup on Windows and it worked without requiring any fixes or patches. Any idea why is that the case?
