### ISSUE TITLE
Report a potential vulnerability via GitHub feature  

### ISSUE THREAD

**Issue by Sim4n6** [kubeflow/pipelines#9127]
I may have identified a vulnerability in the latest codebase of kubeflow/pipelines.

I would like to submit the security report privately using the [GitHub Private Vulnerability Reporting](https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository) feature.  Which permits the possibility to accept/refuse the security report privately and request a CVE accordingly.

Could you please consider enabling the feature for the kubeflow/pipelines repository?

**Comment by gkcalat** [comment]
Hi @Sim4n6,

Thank you for a suggestion. We need to create a separate issue in [kubeflow/kubeflow](https://github.com/kubeflow/kubeflow) repository to enable this feature on the org-level.

As a temporary solution, you can report the CVE in the slack channel to the owners of KFP repo. You can check the owners in the root OWNERS file. For example, @chensun.

**Comment by Sim4n6** [comment]
Hi @gkcalat, I wrote a message on Slack and an issue on kubflow repo. No reply from last week. It looks to me like I have reached a dead-end.

**Comment by gkcalat** [comment]
Added you to the private thread. Let's follow up there.

**Comment by juliusvonkohout** [comment]
@gkcalat  i also have something for the KFP UI. What is your slack username?

**Comment by Sim4n6** [comment]
Report submitted via huntr.dev platform at https://huntr.dev/bounties/bde55c6c-b0bc-4ba7-afe1-2a2fca24c742 (private report)
