### ISSUE TITLE
Tensorboard pods unable to launch 

### ISSUE THREAD

**Issue by komalkotha** [kubeflow/pipelines#9155]
Tensorboard is unable to launch in user profile it throwing below error .do we need to give any permission to default service Account or any configmap changes we need to make . Presently we PSP in cluster default-editor has the permissions

  ownerReferences:
  - apiVersion: tensorboard.kubeflow.org/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Tensorboard
    name: t1
    uid: 8f415f73-30f6-4674-9dc9-3356be6f75fa
  resourceVersion: "216338025"
  uid: 03da80a3-8903-4368-a440-e6d87e749fce
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: t1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: t1
    spec:
      affinity: {}
      containers:
      - args:
        - --logdir=/tensorboard_logs/
        - --bind_all
        command:
        - /usr/local/bin/tensorboard
        image: tensorflow/tensorflow:2.1.0
        imagePullPolicy: IfNotPresent
        name: tensorboard
        ports:
        - containerPort: 6006
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tensorboard_logs/
          name: tbpd
          readOnly: true
        workingDir: /
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: tbpd
        persistentVolumeClaim:
          claimName: test-volume
status:
  conditions:
  - lastTransitionTime: "2023-01-31T14:48:53Z"
    lastUpdateTime: "2023-01-31T14:48:53Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2023-01-31T14:48:54Z"
    lastUpdateTime: "2023-01-31T14:48:54Z"
  ###   **m**essage: 'pods "t1-79d5c94587-" is forbidden: PodSecurityPolicy: unable to admit
      pod: [spec.initContainers[0].securityContext.runAsNonRoot: Invalid value: false:
      must be true spec.initContainers[0].securityContext: Invalid value: []int64{0}:
      group 0 must be in the ranges: [{1 65535}] spec.initContainers[0].securityContext.capabilities.add:
      Invalid value: "NET_ADMIN": capability may not be added spec.initContainers[0].securityContext.capabilities.add:
      Invalid value: "NET_RAW": capability may not be added]'****
    reason: FailedCreate
    status: "True"
    type: ReplicaFailure
  - lastTransitionTime: "2023-01-31T14:58:54Z"
    lastUpdateTime: "2023-01-31T14:58:54Z"
    message: ReplicaSet "t1-79d5c94587" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 1
  unavailableReplicas: 1
](url)

**Comment by zijianjoy** [comment]
Do you have any PodSecurityPolicy enforced in your cluster? KFP doesn't have restriction on pod deployment permission.

Reference: https://medium.com/@suruti94/debugging-k8s-podsecuritypolicy-related-issues-9730c90d9eff

**Comment by komalkotha** [comment]
@zijianjoy  yeah psp is enabled and we have given permission to default-editor **serviceAccount** in all kubeflow profiles but tensorboard pods are running with default service account when we launch from the dashboard.
 Is there anyway we can change serviceAccount to use default-editor in **tensorboard controller** or any config map
. because we have given  psp permission to default-editor serviceAccount.
