### ISSUE TITLE
[sdk] Volumes with kfp-kubernetes - no such file or directory

### ISSUE THREAD

**Issue by b4sus** [kubeflow/pipelines#9160]
### Environment

*  KFP version:
2.0.0.beta.1
*  KFP SDK version: 
2.0.0b14
*  All dependencies version:
kfp                      2.0.0b14
kfp-kubernetes           0.0.1
kfp-pipeline-spec        0.2.2
kfp-server-api           2.0.0b1

### Steps to reproduce

Following the [readme](https://github.com/kubeflow/pipelines/blob/master/kubernetes_platform/python/README.md) of the new functionality, I can create and mount the volume in 2 tasks (one depends on the other), however the second one cannot read (no such file or directory) what the first one wrote.
I noticed in yaml file of the task pod the following:
```yaml
  volumes:
  - emptyDir: {}
    name: 59943aa7-e26a-4714-9d8e-51f3aafc20d8-my-pvc
```
Reading [this](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir), the `emptyDir` just seems wrong and it doesn't look like I can control that (in sdk).

Is this a bug or am I doing something wrong?
### Expected result

One task can see what previous task wrote to pv.

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

**Comment by Linchin** [comment]
Hi @b4sus, thank you so much for bringing this up! This is an known issue and is fix by #9150. Just as you said, using `emptyDir` clears the pvc every time a task finishes. Now we are using [persistentVolumeClaim](https://kubernetes.io/docs/concepts/storage/volumes/#persistentvolumeclaim) instead.
