### ISSUE TITLE
[sdk] Unable to use custom params when using kfp.Client().run_pipeline()

### ISSUE THREAD

**Issue by arun-vc** [kubeflow/pipelines#9171]
### Environment

*  KFP version:

[2.0.0-alpha.5](https://github.com/kubeflow/pipelines/tree/2.0.0-alpha.5/manifests/kustomize)
*  KFP SDK version: 

kfp==2.0.0b13
*  All dependencies version:

```
kfp                      2.0.0b13
kfp-pipeline-spec        0.2.0
kfp-server-api           2.0.0a6
```

### Steps to reproduce

```
client = kfp.Client()
run = client.run_pipeline(
    experiment_id=experiment_id,
    job_name=run_name,
    params=params,
    pipeline_id=pipeline_id,
    version_id=version_id,
)
```

pipeline runs with default params and not custom ones specified below:

tried 2 formats for params:
* {"x": "206", "seed": "3007"}
* {"parameters": {"x": "206", "seed": "3007"}}

### Expected result

Pipeline should run with custom params

### Materials and Reference

Followed docs: https://kubeflow-pipelines.readthedocs.io/en/2.0.0b13/source/client.html#kfp.client.Client.run_pipeline
---

Impacted by this bug? Give it a 👍.

**Comment by arun-vc** [comment]
Hi @connor-mccarthy has there been any update on this ?

**Comment by connor-mccarthy** [comment]
@arun-vc, can you try upgrading to the latest version of the KFP SDK (2.0.0-rc.2) and KFP BE (2.0.0-rc.1) and see if this error persists?

**Comment by pythonking6** [comment]
I am also seeing this, not being able to use custom parameters is a pretty big deal!!

**Comment by pilot7747** [comment]
Same issue on latest kfp version

**Comment by wagnerpeer** [comment]
Is it still a thing in kfp 2.5.0 / kfp-sdk 2.13.0 ?
