### ISSUE TITLE
[sdk] Can't submit recurring run with pipeline version reference

### ISSUE THREAD

**Issue by tleewongjaro-agoda** [kubeflow/pipelines#9196]
### Environment

*  KFP version:
1.6 (running 2.0.0-beta.1 pipeline API & UI)

*  KFP SDK version:
`kfp==2.0.0b14`

### Steps to reproduce

Submit recurring run using latest SDK

```
    client.create_recurring_run(
            experiment_id = experiment.experiment_id, 
            job_name=job_name,
            cron_expression=cron_expression,
            pipeline_id=pipeline_id,
            version_id=pipeline_version_id,
            params=json.loads(params)
        )
```

Got error

```
  File "/opt/lib/python3.9/site-packages/kfp/client/client.py", line 979, in _create_job_config
    pipeline_spec=pipeline_doc.to_dict(),
AttributeError: 'NoneType' object has no attribute 'to_dict'
```

https://github.com/kubeflow/pipelines/blob/2.0.0b14/sdk/python/kfp/client/client.py#L979

mitigated by replacing that line with `pipeline_spec=pipeline_doc.to_dict() if pipeline_doc else {},`

### Expected result

Submit recurring run to Kubeflow

### Materials and reference

https://github.com/kubeflow/pipelines/blob/2.0.0b14/sdk/python/kfp/client/client.py#L979

### Labels
 /area sdk

---

Impacted by this bug? Give it a 👍.

**Comment by chensun** [comment]
Hi @tleewongjaro-agoda,

The issue you reported has been resolved by https://github.com/kubeflow/pipelines/pull/9191. This fix will be included in the upcoming SDK release.
