### ISSUE TITLE
Pipeline: allow user edit existing pipelines from UI and update underlying nodes upon saving. 

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/pipelines#920]
It would be nice to allow user edit existing pipeline CR from UI and pipeline controller take actions to update child resources when necessary.

**Comment by vicaire** [comment]
Could you please provide a concrete use case for your feature request?

**Comment by ryan-williams** [comment]
I assume [editing pipelines from within JupyterHub running on the KF cluster] is the preferred way to get the kind of flow @kunmingg is probably seeking?

I've been in iteration loops where, each time I want to test, I compile a pipeline `.py` locally, upload the resulting `.tar.gz`, and start a new run with it.

Having my local `.py` just submit a run using `kfp.Client` is probably one way to improve on that. I'm guessing it's possible or intended to be able to do that from JH.

Apologies if I misunderstood the ask.

**Comment by kunmingg** [comment]
Yes, thanks ryan
@vicaire sorry for late reply, can we update existing pipelines through UI or do we have API to make a PUT call to update pipeline?

**Comment by vicaire** [comment]
@ryan-williams, looks like you are looking for a single command to compile a pipeline and create a run from it, correct? Are you looking for this in the Python SDK or in a CLI tool? 

@kunmingg, yes we have an API. It can be called using the CLI or SDK. Would you like to be able to call the API directly?

**Comment by xiaogaozi** [comment]
@vicaire If my understanding is correct, currently either [HTTP](https://github.com/kubeflow/pipelines/blob/master/backend/api/swagger/pipeline.swagger.json) or [RPC](https://github.com/kubeflow/pipelines/blob/master/backend/api/pipeline.proto) haven't update pipeline API. There're just create and delete pipeline APIs.
