### ISSUE TITLE
[Help Wanted] Use large files from notebook server in KubeFlow Pipeline

### ISSUE THREAD

**Issue by nutmilk10** [kubeflow/pipelines#9201]
I have a kubeflow notebook server that houses a large file (100 GB+) and was trying to read it into my pipeline but I am getting a file not found error. Not sure what's the best step since most tutorials I see download their data which isn't feasible in my case. 

![image](https://user-images.githubusercontent.com/131425383/233691873-6ba87d32-2c77-4b3a-8d1d-dde6fc74afe1.png)

**Comment by chensun** [comment]
Hi @nutmilk10, the component code is meant to be executed at runtime in the kfp cluster, so it's expected that it won't read files from your local notebook. I think you'll have to resign your pipeline to either upload your data file to some cloud storage like s3, gcs, etc. or preload your data into an existing volume that is precreated in the cluster.

**Comment by nutmilk10** [comment]
> Hi @nutmilk10, the component code is meant to be executed at runtime in the kfp cluster, so it's expected that it won't read files from your local notebook. I think you'll have to resign your pipeline to either upload your data file to some cloud storage like s3, gcs, etc. or preload your data into an existing volume that is precreated in the cluster.

So if I have an existing notebook server where the data exists in a volume called 'data-rw', how would I load it in my pipeline?
