### ISSUE TITLE
[bug] Possible Dependency over specification/typo in GCPC-2.0.0b1

### ISSUE THREAD

**Issue by xRagnorokx** [kubeflow/pipelines#9239]
Apologies if this is the wrong place to post this, my issue seems to be in the GCPC==2.0.0b1 python package hosted on Pypi (https://pypi.org/project/google-cloud-pipeline-components/#history) and its dependencies. Since GCPC seems to live in this repo I am posting here, but I am unsure if it is a Backend, Frontend or SDK bug.

### Short Summary:

It seems the version of aiplatform used in GCPC==2.0.0b1 was pinned to less than 2 but also EXACTLY 1.14.0. The dependencies file for GCPC before this version and throughout this repo generally specify "aiplatform <2, => some_version" but what i think is the GCPC 2.0.0b1 release branch (https://github.com/kubeflow/pipelines/blob/google-cloud-pipeline-components-2.0.0b1/components/google-cloud/dependencies.py) has it specified as changing from:

"google-cloud-aiplatform>=1.14.0,<2" to "google-cloud-aiplatform==1.14.0,<2",

In the following commit: https://github.com/kubeflow/pipelines/commit/04d7fa3c5ec333e31052b1c31fabf85bc7af8dbc

Was this intentional or is it a typo? If a typo how quickly can this be fixed as it is blocking me using GCPC components in Pipeline Templates on GCP Vertex AI (since Cloud Scheduled Pipeline Jobs template_path argument expects the https uri of the Pipeline Template in a KFP Artifact Repo and https pulling of KFP artifacts was only added in aiplatform after 1.14)

### Full Context:

I am trying to write a KFP Pipeline containing Google Cloud Pipeline Components, store said pipeline in a KFP Artifact repository in Google Cloud Platform and then schedule this pipeline template using Cloud Scheduler to call a Cloud Function which will pull the template from a HTTPs URI and run the template as a pipeline job. I am essentially following the steps outlined here: https://cloud.google.com/vertex-ai/docs/pipelines/create-pipeline-template?hl=en#vertex-ai-sdk-for-python

However trying to install both GCPC==2.0.0b1 and aiplatform==1.24.1 in a clean environment causes PIP to complain that aiplatform 1.24.1 doesn't match the dependencies specified for the GCPC package. 

```
The conflict is caused by:
    The user requested google-cloud-aiplatform==1.24.1
    google-cloud-pipeline-components 2.0.0b1 depends on google-cloud-aiplatform<2 and ==1.14.0
```

Note that PIP is somehow requesting <2 and _exactly_ 1.14.0 which to me seems odd. If I force the install locally and try running my Cloud Function to pull the artifact using https uri as a template path it builds the job and submits it to GCP fine, so I suspect this is a accidental over pinning of the dependency. 

The non-zero exit status of this PIP build means that I cannot deploy the Cloud Function needed to schedule a KFP which makes use of GCPC components, as GCP refuses to deploy a requirements file that causes PIP to technically fail (even though the build seems fine when testing it).

This problem can be reproduced by installing a conda env (attached below), or by installing GCPC==2.0.0b1 and aiplatform==1.24.1 into a clean environment using pip directly. 

### Expected result

I would expect pip to allow me to install aiplatform==1.24.1 alongside GCPC 2.0.0b1 as both are required to use GCPC in Pipeline templates and I suspect the pinning of aiplatform to less than 2 but _exactly_ 1.14.0 is a typo.

### Materials and reference:

Conda File to reproduce issue:
```
channels:
  - conda-forge
dependencies:
  - python==3.10
  - pip
  - pip:
    - google-cloud-aiplatform==1.24.1
    - google-cloud-pipeline-components==2.0.0b1
```
    
 
### Labels

/area components

---

Impacted by this bug? Give it a 👍.

**Comment by xRagnorokx** [comment]
@chongyouquan tagging you since you may remember if this was deliberate!

**Comment by xRagnorokx** [comment]
Ill note that for now I've rolled back to 2.0.0b0 which seems to work fine as it has >= not == in aiplatform dependency spec

**Comment by connor-mccarthy** [comment]
This is resolved in all the latest releases of GCPC.
