### ISSUE TITLE
docker magic command should print kaniko pod logs

### ISSUE THREAD

**Issue by hongye-sun** [kubeflow/pipelines#924]
Otherwise, there is no way for notebook user to understand what's wrong in their dockerfile.

The current workaround to debug docker command issue is to find the kaniko pod in cluster and print it logs:

kubectl get pods -n kubeflow | grep kaniko
kubectl logs <kaniko pod name> -n kubeflow.

**Comment by gaoning777** [comment]
Fixed at https://github.com/kubeflow/pipelines/pull/1247
