### ISSUE TITLE
[sdk] Pyright classifies use of types "not allowed"

### ISSUE THREAD

**Issue by WalterSmuts** [kubeflow/pipelines#9240]
### Environment
```
[walter@cuddles Development]$ pip list | grep kfp
kfp                      1.8.20
kfp-pipeline-spec        0.1.16
kfp-server-api           1.8.5
```

### Descriptoin

Pyright seems to think kubeflow pipeline's use of type constructors in the function signature is incorrect:

```
[walter@cuddles Development]$ cat kubeflow.py
from kfp.components import InputPath

def my_op(input_file_path: InputPath(str)):
    print(input_file_path)
```
```
[walter@cuddles Development]$ pyright kubeflow.py
No configuration file found.
No pyproject.toml file found.
stubPath /home/walter/Development/typings is not a valid directory.
Assuming Python platform Linux
Searching for source files
Found 1 source file
pyright 1.1.291
/home/walter/Development/kubeflow.py
  /home/walter/Development/kubeflow.py:3:28 - error: Illegal type annotation: call expression not allowed (reportGeneralTypeIssues)
1 error, 0 warnings, 0 informations
Completed in 0.534sec
```

Is there a way around this? Is this the intended way to use the pipelines `InputPath` API? 
Impacted by this bug? Give it a 👍.

**Comment by chensun** [comment]
Hi @WalterSmuts, admittedly I think this type annotation usage isn't correct. But I don't have a better solution. Maybe you'll have to add some comments on the line to disable pyright check.

**Comment by WalterSmuts** [comment]
Can't you do something similar to `list` and `optional` and such? I believe they use the square brackets to signify a type constructor argument:
```
a = list[int] = [0, 1, 2]
```
