### ISSUE TITLE
load_component_from_file() input to be parameterised

### ISSUE THREAD

**Issue by masoudjalayer90** [kubeflow/pipelines#9251]
Issue:
looking to parse a pipeline argument through to the input for load_component_from_file()

```
@dsl.pipeline(name="my-pipeline")
def pipeline(
    model_version: str 
) -> None:

run_model_for_partition_task = comp.load_component_from_file(
        filename=f"models/run_model_{model_version}_component_spec.yaml"
```

However getting this error - 
`FileNotFoundError: [Errno 2] No such file or directory: 'models/run_model_{{pipelineparam:op=;name=model_version}}_component_spec.yaml'`

Is there a way to do the above, as to avoid having to hardcode the location of the component spec file?

**Comment by chensun** [comment]
Hi @masoudjalayer90, this is currently not supported. Can you explain why you want this dynamic feature?

**Comment by masoudjalayer90** [comment]
hi @chensun this would enable me to use the parse an argument into the pipeline function that can be used to specify model_version (in the example given above). This would allow the use of multiple component_spec yaml files within the same pipeline, without having to hardcode the location of the said yaml file, and hence have a more dynamic/reusable pipeline. 

thanks in advance

**Comment by chensun** [comment]
A pipeline function needs to be compiled into some spec (same yaml format as the component you would load from), so at the compilation time, all the component definition must be realized (static value). 
You can still achieve the dynamic/reusable pipeline by choosing which loaded component to run using a parameter. For example:

```python
model1 = load_component_from_file('model1.yaml')
model2 = load_component_from_file('model2.yaml')

@dsl.pipeline(name="my-pipeline")
def pipeline(
    model_version: str 
) -> None:
    with dsl.Condition(model_version == 'v1'):
        model1(...)
    with dsl.Condition(model_version == 'v2'):
        model2(...)
```

Would that work for you?

**Comment by masoudjalayer90** [comment]
@chensun Thank you for your response. 
Yes, this will work for my case. Thanks again
