### ISSUE TITLE
[frontend] tfx components like StatisticsGen and ExampleValidator does not display other splits than 'train' and 'eval' in the KFP vizualization window

### ISSUE THREAD

**Issue by ykacer** [kubeflow/pipelines#9266]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
Kubeflow Pipelines as part of a full Kubeflow deployment in Google Cloud Platform
  
*  KFP version: 
v1.5

### Steps to reproduce

When creating a third split named "val" (for example),  visualization components windows (at least StatisticsGen and ExampleValidator) only display the 'train' and 'eval' split even if the 3 splits sub-folders are present in google storage buckets (`Split-train`, `Split-eval` and `Split-val`) . BTW, with `tfx.InteractiveContext()` in jupyter  notebook, i can see the 3 visualizations splits

### Expected result

Seeing other splits than `train` and `eval` in windows components vizualisations

I

Impacted by this bug? Give it a 👍.

**Comment by jlyaoyuli** [comment]
Hi @ykacer, would you mind providing the tfx pipeline definition? Then, we can reproduce the issue. Also, the KFP version you were using is quite old. Suggest to use newer version here: https://www.kubeflow.org/docs/components/pipelines/v1/installation/standalone-deployment/
