### ISSUE TITLE
Kubeflow deployer component fails when deployment already exists

### ISSUE THREAD

**Issue by DanSanche** [kubeflow/pipelines#927]
Context: The deploy script runs 'kubectl apply' to create a deployment, and then waits for a pod name to become active before continuing in the script

https://github.com/kubeflow/pipelines/blob/ba64bd3866023c36c93cf2b46a066a1b008bb6c4/components/kubeflow/deployer/src/deploy.sh#L159

Issue: If the deployment already exists in the cluster, running 'kubectl apply' will delete the old pod and create a new one. In this case, two pods may briefly be running at the same time. This will cause the pod_name variable to be set to a string with two pod names, which will cause later steps to fail

Solution: Could be as simple as running wc -l on pod_name in the [while loop](https://github.com/kubeflow/pipelines/blob/ba64bd3866023c36c93cf2b46a066a1b008bb6c4/components/kubeflow/deployer/src/deploy.sh#L158) to make sure it only contains one pod, or we could add more robust checks. Let me know what you think

**Comment by vicaire** [comment]
@IronPan, is this addressed by the work to update the cluster with the latest version of Kubeflow?

**Comment by IronPan** [comment]
this is not the kubeflow deployment. it's the component code to start tf-serving pod. 

I am not entirely sure why we need to list pod name, and get pod status. 
Getting deployment level health status should be good enough. 
And to pull logs for all pods, we can do 
```
kubectl logs -l app=${SERVER_NAME}
```

**Comment by IronPan** [comment]
Forward this to @hongye-sun in case I miss anything.

**Comment by hongye-sun** [comment]
I agree with Yang. It seems pull deployment status should be enough. I don't think we have assigned anyone to fix the issue, though.

**Comment by jlewi** [comment]
This code is very outdated. Filed: kubeflow/pipelines#2542 about updating or deleting it.
