### ISSUE TITLE
Cannot find module for path ml_metadata/metadata_store/mlmetadata

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#928]
https://travis-ci.com/kubeflow/pipelines/jobs/182659416

```
go: downloading github.com/valyala/bytebufferpool v1.0.0
build github.com/kubeflow/pipelines/backend/src/apiserver: cannot find module for path ml_metadata/metadata_store/mlmetadata
The command "go vet -all -shadow ./..." exited with 1.
0.48s$ go test ./...
build github.com/kubeflow/pipelines/backend/src/apiserver: cannot find module for path ml_metadata/metadata_store/mlmetadata
The command "go test ./..." exited with 1.
```

**Comment by neuromage** [comment]
@Ark-kun can you rebase on master? The backend now requires bazel to build. `go build/vet/test` etc will no longer work.

**Comment by Ark-kun** [comment]
Actually, just doing `git commit --amend && git push --force` (without any changes) was enough to fix the issue. The root cause is described here: https://github.com/kubeflow/pipelines/issues/929
