### ISSUE TITLE
[bug] Unexpected Argo behavior with background processes and emissary executor

### ISSUE THREAD

**Issue by ajaypbrt** [kubeflow/pipelines#9292]
### Environment

We have a Kubeflow deployment with KFP and are running `gcr.io/ml-pipeline/argoexec:v3.3.8-license-compliance` with the emissary executor.

### Steps to reproduce
Create and run a pipeline with this op:
```
def test_op():
    return dsl.ContainerOp(
        name="test_container",
        image='public.ecr.aws/amazonlinux/amazonlinux:latest',
        command=["/bin/sh", "-c"],
        arguments=["sleep 600 & ls -a"]
    )
```

### Expected result

I expect the container to behave as if I ran
`docker run public.ecr.aws/amazonlinux/amazonlinux:latest /bin/sh -c 'sleep 600 & ls -a'`
in which case the container command backgrounds the sleep process, runs `ls -a`, and the `/bin/sh` process and container exit immediately after. Note: I observed no difference when adding `--init`.

With Argo, the container will run:
```
argoexec emissary -- /bin/sh -c "sleep 600 & ls -a"
```
However, while the `/bin/sh` process exits, the `argoexec` process waits on the sleep process.

If I run this same image, command, and argument set in AWS Batch, I get the expected behavior.

In my view, the `argoexec emissary` interception is breaking the abstraction I had for running my image with a specified command and arguments.

Impacted by this bug? Give it a 👍.

**Comment by jlyaoyuli** [comment]
Hi @ajaypbrt, can you share what the expected result looks like? Also, it seems like the issue is related to Argo, so we suggest to report this one in Argo community.

**Comment by ajaypbrt** [comment]
I will post it there. I expect the container to exit immediately when the main process `/bin/sh` exits and not wait for any background processes.

**Comment by ajaypbrt** [comment]
Just tried with Argo `3.4.7` and it appears to be fixed. What version does KFP use under the hood?
