### ISSUE TITLE
[bug] Kubeflow Pipelines issue K8s 1.22+

### ISSUE THREAD

**Issue by tanken** [kubeflow/pipelines#9298]
### Environment

Hi, a previously reported issue https://github.com/kubeflow/pipelines/issues/8076 doesnt seem to be fixed with any of the latest KFP versions.

*  How do you deploy Kubeflow Pipelines (KFP)?
Standalone deployment on EKS https://www.kubeflow.org/docs/components/pipelines/v1/installation/standalone-deployment/

*  KFP version:
1.8.13

### Steps to reproduce

```
> kubectl diff --kustomize  "github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=1.8.13"
error: unable to recognize "github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=1.8.13": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
```

### Materials and reference

The beta CustomResourceDefinition API (apiextensions.k8s.io/v1beta1) has been removed. See [Kubernetes 1.22 API changes](https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/).

### Labels

---

Impacted by this bug? Give it a 👍.

**Comment by jlyaoyuli** [comment]
Hi @tanken, we suggest to try KFP v2 beta.1: https://github.com/kubeflow/pipelines/releases/tag/2.0.0-beta.1
