### ISSUE TITLE
Persist pod logs after they finish

### ISSUE THREAD

**Issue by yebrahim** [kubeflow/pipelines#93]
This is needed so that pods can be garbage collected after they've finished, and to remove the dependency on the cluster state.

Currently, we're already seeing issues when a cluster is resized where the frontend can't find pods started by some of the runs.

**Comment by IronPan** [comment]
close https://github.com/kubeflow/pipelines/issues/439?

**Comment by vicaire** [comment]
Resolving in favor of https://github.com/kubeflow/pipelines/issues/844
