### ISSUE TITLE
GitHub checks have been enabled in this repo, but are not supported by Tide.

### ISSUE THREAD

**Issue by cjwagner** [kubeflow/pipelines#930]
It appears that GitHub checks from Travis CI have been enabled in this repo. This is causing issues with merge automation because Tide does not respect GitHub checks, only GitHub status contexts and will continue to try to merge PRs that are actually unmergeable due to failing checks from Travis CI.
Please disable the GitHub checks from Travis CI ASAP to prevent merge automation from getting stuck on PRs in this repo.

https://github.com/kubeflow/pipelines/pull/922#issuecomment-470338742
https://github.com/kubeflow/pipelines/pull/814#issuecomment-465836997

**Comment by neuromage** [comment]
@cjwagner would you know how one can disable github checks?

/cc @vicaire 
/cc @IronPan 
/cc @hongye-sun 
/cc @yebrahim 
Did we change anything in our travis CI set up recently?

**Comment by cjwagner** [comment]
> @cjwagner would you know how one can disable github checks?

No I don't, sorry. The checks are coming from Travis CI though so presumably there is some configuration to disable them there.
As a side note, consider moving your Travis CI tests to a ProwJob.

**Comment by cjwagner** [comment]
Ping. This is still a problem.
Tide got stuck on this PR for a short while yesterday morning: https://github.com/kubeflow/pipelines/pull/938

**Comment by vicaire** [comment]
Let me sync up with @IronPan tomorrow. I will follow up by Monday EOD (if not earlier)

**Comment by IronPan** [comment]
The travis tests are mostly unit tests. I always encourage people to add tests to prow but there is no current plan to migrate existing travis test to prow. there is no drawback and no much benefit either. we can prioritize this if people feel strong about it.

**Comment by IronPan** [comment]
also travis was running twice because our project was set up with both travis.org and travis.com. i disabled .org.

**Comment by vicaire** [comment]
Can we close the issue?

**Comment by cjwagner** [comment]
> Can we close the issue?

Yes, I haven't seen any errors related to this recently. The problems may have been caused by the duplicate Travis CI services.
/close

Keep in mind that Tide was designed before GH checks existed so the behavior is kind of undefined.
If Tide is working for you that is great though!

**Comment by cjwagner** [comment]
/reopen 
This is happening again: https://github.com/kubeflow/pipelines/pull/1287
https://prow.k8s.io/tide-history?repo=kubeflow%2Fpipelines&branch=master

**Comment by cjwagner** [comment]
Ping. This is still an issue.

**Comment by cjwagner** [comment]
Still an issue. Please address.

**Comment by BenTheElder** [comment]
ping @jlewi

**Comment by Bobgy** [comment]
/close
in favor of https://github.com/kubeflow/pipelines/issues/1653
