### ISSUE TITLE
[backend] Untracked changes on master after `git clone`

### ISSUE THREAD

**Issue by caren-guo** [kubeflow/pipelines#9316]
### Environment

On MacOS.

```
➜  git clone https://github.com/kubeflow/pipelines.git
Cloning into 'pipelines'...
remote: Enumerating objects: 100317, done.
remote: Counting objects: 100% (2590/2590), done.
remote: Compressing objects: 100% (1191/1191), done.
remote: Total 100317 (delta 1461), reused 2211 (delta 1307), pack-reused 97727
Receiving objects: 100% (100317/100317), 66.21 MiB | 7.33 MiB/s, done.
Resolving deltas: 100% (65899/65899), done.
Checking connectivity... done.
➜  cd pipelines
➜  git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   components/aws/sagemaker/Model/README.md
	modified:   components/aws/sagemaker/Model/component.yaml

no changes added to commit (use "git add" and/or "git commit -a")
```
This is preventing us fro, using the git ref as a base in a `kustomization.yaml` because kustomize will run a `git checkout` in the background and that fails due to untracked files.

### Steps to reproduce

Simply do a `git clone` on a clean location.

### Expected result

There should not be untracked files.

**Comment by chensun** [comment]
I was able to reproduce but not the same error message:

> git clone git@github.com:kubeflow/pipelines.git
> Cloning into 'pipelines'...
> remote: Enumerating objects: 100585, done.
> remote: Counting objects: 100% (2910/2910), done.
> remote: Compressing objects: 100% (1434/1434), done.
> remote: Total 100585 (delta 1589), reused 2302 (delta 1312), pack-reused 97675
> Receiving objects: 100% (100585/100585), 66.16 MiB | 16.38 MiB/s, done.
> Resolving deltas: 100% (66032/66032), done.
> warning: the following paths have collided (e.g. case-sensitive paths
> on a case-insensitive filesystem) and only one from the same
> colliding group is in the working tree:
> 
>   'components/aws/sagemaker/Model/component.yaml'
>   'components/aws/sagemaker/model/component.yaml'
>   'components/aws/sagemaker/Model/README.md'
>   'components/aws/sagemaker/model/README.md'

@surajkota

**Comment by surajkota** [comment]
Hi @chensun, checking in, we are investigating and working on a fix

**Comment by ananth102** [comment]
Hi, apologies for the inconvenience this has caused. I developed the change on an linux system and did not catch the error. Have created a PR to fix the error.

**Comment by surajkota** [comment]
Fix has been merged, can you try with latest branch now?

**Comment by caren-guo** [comment]
Thanks for fixing! It works for me now.
