### ISSUE TITLE
[sdk] <Bug Name>

### ISSUE THREAD

**Issue by maganaluis** [kubeflow/pipelines#9330]
### Environment

*  KFP version: `2.0.0-alpha.5`

*  KFP SDK version: `2.0.0b15`

*  All dependencies version: N/A

### Steps to reproduce

The following import fails, and this is currently how many examples are setup in the master branch.

```
import kfp.deprecated.components as components
```

```
...
site-packages/kfp/deprecated/_client.py", line 396, in Client
def get_kfp_healthz(self) -> kfp_server_api.ApiGetHealthzResponse:
AttributeError: module 'kfp_server_api' has no attribute 'ApiGetHealthzResponse'. Did you mean: 'V2beta1GetHealthzResponse'?
```

### Expected result

Expect the import `import kfp.deprecated.components as components` to work without errors.

### Materials and Reference

The import as been failing since b13, I would expect this import to work since users will be refericing the master branhc as away to stay up to date with Kubeflow Pipelines.

---

Impacted by this bug? Give it a 👍.

**Comment by papagala** [comment]
I have the same issue even with `sdk` version `2.0.1`. Another way of running into this error:

```
In [9]: import kfp.deprecated

AttributeError: module 'kfp_server_api' has no attribute 'ApiGetHealthzResponse'
```
