### ISSUE TITLE
[sdk] GetVertexModelOp in google-cloud-pipeline-components==2.0.0b3 references image with kfp v1 (latest)

### ISSUE THREAD

**Issue by tuukkasarvi** [kubeflow/pipelines#9349]
GetVertexModelOp in google-cloud-pipeline-components==2.0.0b3 references image with older version of google-cloud-pipeline-components and kfp v1 (latest):
https://github.com/kubeflow/pipelines/blob/google-cloud-pipeline-components-2.0.0b3/components/google-cloud/google_cloud_pipeline_components/experimental/model/get_model/component.py#L49

### Environment

*  KFP version:
kfp==2.0.0b16

*  All dependencies version:
kfp==2.0.0b16
kfp-pipeline-spec==0.2.2
kfp-server-api==2.0.0b1
google-cloud-pipeline-components==2.0.0b3

### Steps to reproduce

```python
from kfp import dsl
from google_cloud_pipeline_components.experimental.model import GetVertexModelOp

@dsl.pipeline(name="pipeline")
def a_pipeline():
    get_model_op = GetVertexModelOp(model_name="my-resource-name")
```

### Expected result

Pipeline runs and GetVertexModelOp returns a reference to model.

### Actual result

From Vertex pipelines logs:

"/opt/conda/bin/python3: Error while finding module specification for 'google_cloud_pipeline_components.container.experimental.model.get_model.get_model' (ModuleNotFoundError: No module named 'google_cloud_pipeline_components.container.experimental.model"

The problem seems to be that gcr.io/ml-pipeline/google-cloud-pipeline-components:latest has kfp v1 where the directory structure is different than in v2 which google-cloud-pipeline-components==2.0.0b3 uses.

**Comment by connor-mccarthy** [comment]
This is fixed.
