### ISSUE TITLE
[sdk] Which versions work with which one

### ISSUE THREAD

**Issue by axel7083** [kubeflow/pipelines#9389]
We have some issues figuring out which version of the `sdk` goes with which `kfp-server-api`, and the extra `[kubernetes]` in kubeflow.

In Kubeflow/manifest, in the 1.7 release they are using `Kubeflow Pipelines 2.0.0-alpha.7` however they do not specify the sdk or kfp-server-api. 

Based on some conversation in the kubeflow slack, a working setup is `kfp==2.0.0b12` and `kfp-server-api==2.0.0a6`. But this make impossible to use the kubernetes extra since 
> kfp-kubernetes 0.0.1 requires kfp>=2.0.0-beta.13, but you have kfp 2.0.0b12 which is incompatible.

Moreover we can try to force using  kfp-kubernetes, but got errors when trying to use secrets for instance.
> AttributeError: 'PipelineTask' object has no attribute 'platform_config'

I know @connor-mccarthy @chensun have helped people on the slack for related issues, and we would be grateful to have some clarification.

**Comment by chensun** [comment]
Sorry about the confusion. We have a tracking bug to document the compatibility matrix: [Kubeflow Pipelines 2.0.0-alpha.7](https://github.com/kubeflow/pipelines/issues/8728)

Short answer:
- `Kubeflow Pipelines 2.0.0-alpha.7` backend doesn't support the feature added via `kfp-kubernetes` or `platform_config` yet. But you can get k8s specific feature (volume, secrets, etc) working using the v1 SDK syntax. `kfp==1.8.*` should also work with this backend.
- `Kubeflow Pipelines 2.0.0-Beta.2` supports `kfp-kubernetes` or `platform_config` features. For this backend, you need SDK `kfp>=2.0.0b17`.

**Comment by axel7083** [comment]
Thanks you closing as I got the anwser expected
