### ISSUE TITLE
Moving and retrieving logs from persistent volume

### ISSUE THREAD

**Issue by animeshsingh** [kubeflow/pipelines#940]
We are running into issues where pipeline logs are getting wiped out from IKS based on rotation policy .Currently, the latest Argo executor could save logs to S3 persistent volume when the archiving flag is enabled. 

However, Kubeflow Pipeline frontend is getting the logs using K8S API.
https://github.com/kubeflow/pipelines/blob/master/frontend/server/k8s-helper.ts#L120-L129

Therefore, we need to modify the above function to something similar to what Argo did to their frontend, so our logs could be persistent.

https://github.com/argoproj/argo-ui/pull/15/files#diff-84cac750d2884ddb71e3f362ae241797R131
https://github.com/argoproj/argo-ui/blob/master/src/api/app.ts#L134-L160

**Comment by vicaire** [comment]
Added your suggestion to https://github.com/kubeflow/pipelines/issues/844

Resolving in favor of https://github.com/kubeflow/pipelines/issues/844
