### ISSUE TITLE
[feature] Cache Server to cache tasks as they complete instead of waiting on the entire pipeline.

### ISSUE THREAD

**Issue by CosyOranges** [kubeflow/pipelines#9454]
### Feature Area

We make **heavy** use of Kubeflow's caching feature.
However, it doesn't play very well with some of the config you can set in Argo's `workflow-controller-configmap`. We run a large amount of pipelines at scale and as the number of pipelines increased the load on our EKS-Control plane also increased to the point where ~24k containers existed in one of our clusters and pretty much brought the entire cluster to a stand-still.
- After some debugging the root cause was found to be the interplay between the above configmap and the `cache-server`.
- To improve things we altered the `workflow-controller-configmap` to the following:
- ```
    spec:
        parallelism: 50  # Parallelism limits the max total parallel pods that can execute at the same time in a workflow
        # PodGC describes how to delete completed pods as they complete: https://argoproj.github.io/argo-workflows/fields/#podgc
        podGC:
            strategy: OnPodSuccess # Strategy is the strategy to use. One of "OnPodCompletion", "OnPodSuccess", "OnWorkflowCompletion", "OnWorkflowSuccess"
        # TTLStrategy limits the lifetime of a Workflow that has finished execution depending on if it Succeeded or Failed                                    
        ttlStrategy:
            secondsAfterSuccess: 60  # Time to live after workflow is successful
            secondsAfterFailure: 10800  # Time to live after workflow fails
            # secondsAfterCompletion: 604800 # Time to live after workflow is completed, replaces ttlSecondsAfterFinished

- This caused an issue with caching: Pods were being cleaned up before the `workflow` itself was marked as completed and so the pod was **not** added to the cache-db

The root cause of this problem is the following in `backend/src/cache/server/watcher.go`

```
    func isPodCompletedAndSucceeded(pod *corev1.Pod) bool {
	    return pod.ObjectMeta.Labels[ArgoCompleteLabelKey] == "true" && pod.Status.Phase == corev1.PodSucceeded
    }
```
- This means the watcher won't deem a pod ready to be cached until the entire pipeline has completed.

### What feature would you like to see?

Ideally the above `isPodCompletedAndSucceeded` would simply check the whether or no the pod itself is successful, if yes we don't care about the rest of the pipeline and that pod/tasks metadata can be added to the cache-db

### What is the use case or pain point?

This would greatly increase the scalability of caching and also help to reduce the load on the Control Plane for people running pipelines at large scales as they will be able to clean pods up at a greater rate and still benefit from caching.

### Is there a workaround currently?

Not really, we've currently made the above change to our Fork of Kubeflow and are running this in our clusters

---

Love this idea? Give it a 👍.

**Comment by CosyOranges** [comment]
@gkcalat I can look to submit the changes if the above suggestion makes sense

**Comment by gkcalat** [comment]
Hi @CosyOranges,

Sounds good to me. Please, assign your PR to @chensun and @Linchin.
