### ISSUE TITLE
[backend] Artifact passing fails with kfp launcher using s3 and query parameters

### ISSUE THREAD

**Issue by cchanley2003** [kubeflow/pipelines#9456]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
  Self hosted

*  KFP version: 
  kubeflow 1.7
*  KFP SDK version: 
 kfp sdk 1.8.19

### Steps to reproduce

1. Added the following the kfp-launcher configmap:
```
data:
  defaultPipelineRoot: s3://<bucket>?region=<region>&endpoint=<endpoint>443
  ```

2. Tested with sample data passing (everything worked and everything went into s3) using parameters passing only.  Wrote the following test for artifact passing:
```

from kfp import ( dsl, compiler)
from kfp.v2.dsl import component
from kfp.v2.dsl import (
    Input,
    Output,
    Dataset,
)

@component
def write_data(output: Output[Dataset]):
    with open(output.path, "w") as writer:
        writer.write("Hello World")

@component
def read_data(input: Input[Dataset]):
    with open(input.path, "r") as reader:
        print(reader.read())

@dsl.pipeline(
    name="data-passing-pipeline",
    description="A pipeline that passes data between components",
)
def test_data_passing():
    data = write_data()
    read_data(data.outputs["output"])


if __name__ == "__main__":
    # execute only if run as a script
    compiler.Compiler(mode=dsl.PipelineExecutionMode.V2_COMPATIBLE).compile(
        test_data_passing, "datapassing_V2.yaml")
 ```
 
3. Compile and run the pipeline.
* Write data successfully writes to bucket/pipeline/run name/run id/write_data/output
* Fails to pass the artifact to the next level.

Logs:
write_data:
```
time="2023-05-18T17:46:27.683Z" level=info msg="capturing logs" argo=true
I0518 17:46:27.707799      17 launcher.go:144] PipelineRoot defaults to "s3://<bucket>?region=us-gov-west-1&endpoint=s3.us-gov-west-1.amazonaws.com:443".
I0518 17:46:27.707962      17 cache.go:143] Cannot detect ml-pipeline in the same namespace, default to ml-pipeline.kubeflow:8887 as KFP endpoint.
I0518 17:46:27.707970      17 cache.go:120] Connecting to cache endpoint ml-pipeline.kubeflow:8887
I0518 17:46:28.311175      17 launcher.go:193] enable caching
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[KFP Executor 2023-05-18 17:46:39,713 INFO]: Looking for component `write_data` in --component_module_path `/tmp/tmp.FWpikJlbBK/ephemeral_component.py`
[KFP Executor 2023-05-18 17:46:39,713 INFO]: Loading KFP component "write_data" from /tmp/tmp.FWpikJlbBK/ephemeral_component.py (directory "/tmp/tmp.FWpikJlbBK" and module name "ephemeral_component")
I0518 17:46:39.791419      17 launcher.go:860] ExecutorOutput: {
  "artifacts": {
    "output": {
      "artifacts": [
        {
          "name": "output",
          "uri": "s3://<bucket>/write-data/output",
          "metadata": {
            "s3_region": ""
          }
        }
      ]
    }
  }
}
I0518 17:46:42.977145      17 object_store.go:249] uploadFile(localFilePath="/s3/<bucket>s/write-data/output", blobFilePath="write-data/output")
time="2023-05-18T17:46:43.270Z" level=info msg="/tmp/outputs/output/data -> /var/run/argo/outputs/artifacts/tmp/outputs/output/data.tgz" argo=true
time="2023-05-18T17:46:43.270Z" level=info msg="Taring /tmp/outputs/output/data"
```
read_data
```
time="2023-05-18T17:47:04.086Z" level=info msg="capturing logs" argo=true
I0518 17:47:04.111076      18 launcher.go:144] PipelineRoot defaults to "s3://<bucket>?region=us-gov-west-1&endpoint=s3.us-gov-west-1.amazonaws.com:443".
I0518 17:47:04.111241      18 cache.go:143] Cannot detect ml-pipeline in the same namespace, default to ml-pipeline.kubeflow:8887 as KFP endpoint.
I0518 17:47:04.111249      18 cache.go:120] Connecting to cache endpoint ml-pipeline.kubeflow:8887
I0518 17:47:04.299847      18 launcher.go:193] enable caching
F0518 17:47:07.879874      18 main.go:50] Failed to execute component: failed to download input artifact "input" from remote storage URI "s3://<bucket>/write-data/output": failed to list objects in remote storage "write-data/output": blob (code=NotFound): NoSuchKey: The specified key does not exist.
	status code: 404, request id: 8TSYRFXKQAVT04R9, host id: cIgr/PDL5WrVcBp1yvm+icUoYnWnInLMaueFYHZ0OWSQod0OYrdg+p2hRUzPaw8puaUbzkEcvF0=

```
### Expected result

The pipelines successfully runs. 

---

Impacted by this bug? Give it a 👍.

**Comment by cchanley2003** [comment]
Not sure if this handles all cases but to get around the issue we change the regex in objectstore.go to:
```
	bucketPattern := regexp.MustCompile(`(^[a-z][a-z0-9]+:///?)([^/?]+)([\?][^/]+)?/([^?]*)?$`)
```
And then change what groups are pulled for prefix. Seems to work for the couple of cases we tried.  Basically grab the query string first and then grab prefix.

**Comment by cchanley2003** [comment]
Oh and one other thing we had to changes in the launcher was that it does a prefix check between the artifact uri and the default bucket. If it is using a cached artifact from a pervious run it always thinks it is a non default bucket because it is including the run id in the prefix. Which works most of the time, but in this case also drops the query parameters when it recreates the bucketconfig. It should realize that is still the default bucket. So the logic is wrong basically for non-default bucket checking. Haven't looked whether these issues exist in the v2 version of the launcher....

**Comment by Linchin** [comment]
Hi @cchanley2003, thank you for reporting the issue! Looks like you are using KFP 1.7.x. I recommend upgrading to `2.0.0-rc.1` and see if the issue persists. Also, could you please help me understand why changing the regex pattern can help solve the issue? Is the current regex
```
bucketPattern = regexp.MustCompile(`(^[a-z][a-z0-9]+:///?)([^/?]+)(/[^?]*)?(\?.+)?$`)
```
not recognizing something in your uri?

**Comment by cchanley2003** [comment]
So a few notes. First why are we doing this:

1. Need custom endpoints for s3 buckets in certain regions such as gov cloud. The query string is supported by golangs blob syntax.

Why does this work? This assumes the query string is in the middle of the url and the prefix is after. I think the original regex assumes query string is at the end. But this can never happen since ml-metadata (or something related to that) always postfixes the bucket with pipeline/run_name/run_id. So there is no way to insert the query string at then of the pipelineRoot. 

As far as I can tell once you query string is added to the original regex it ends up dropping the prefix (in this case the pipeline/run_name/run_id that is added to every root bucket.

Hopefully this makes sense. 

As for upgrading we are running kubeflow 1.7 (see https://www.kubeflow.org/docs/releases/kubeflow-1.7/) which references an alpha version of kfp 2.0.0.

**Comment by cchanley2003** [comment]
One other note of something we ran into is that if cache hit occurs the query string beaks as well. This is because when a cache hit occurs the source artifact is considered to be a non-default bucket. It considers it a non-default bucket because the run_id is different due to the postfix that was added.  But when creating the non-default bucket it doesn't carry over the query string. 

So either the run_id shouldn't be considered when deciding if this is a non-default bucket or the query string needs to be used when recreating the bucket.

**Comment by Linchin** [comment]
Thank you for explaining, I see why the regex isn't working. Although you are using kfp 2.0.0-alpha.7, the error log seems to use a much older version of launcher:
```
I0518 17:46:27.707799      17 launcher.go:144] PipelineRoot defaults to 
```
The file `launcher.go` and the message have been removed long ago.

**Comment by cchanley2003** [comment]
Yeah that was pipeline compiled with a 1.8 sdk. I'll retry with  2.0.0 sdk

**Comment by cchanley2003** [comment]
So I attempted to use the kfp2.0.0rc1 sdk. Was unable to compile the pipeline. I then attempted to compile this [pipeline](https://github.com/kubeflow/pipelines/blob/master/samples/v2/lightweight_python_functions_v2_pipeline/lightweight_python_functions_v2_pipeline.py)  and got similar error. 
```
AttributeError: '_FieldProperty' object attribute '__doc__' is read-only
```
Also the rc1 launcher doesn't seem to be compatible with a pipeline compiled with 1.8. So not sure how to test rc1 launcher?
