### ISSUE TITLE
[feature] Permit exit tasks to consume outputs from tasks enclosed by the exithandler

### ISSUE THREAD

**Issue by connor-mccarthy** [kubeflow/pipelines#9459]
### Feature Area
Specifically, support functionality exposed by `task.ignore_upstream_outputs` in the KFP SDK (SDK implementation https://github.com/kubeflow/pipelines/pull/8838).

/area backend

### What feature would you like to see?

Enable exit tasks to consume outputs of tasks enclosed by the exit handler.

Specifically, the following should be runnable:

```python
@dsl.pipeline()
def my_pipeline(text: str = 'message'):
    task = fail_op(message=text)
    print_op(message=task.output).ignore_upstream_failure()
```

---

Love this idea? Give it a 👍.

**Comment by ketangangal** [comment]
Yes its required since we should be having some way to make a proper status update at the end of the pipeline.

**Comment by connor-mccarthy** [comment]
This is [supported](https://github.com/kubeflow/pipelines/blob/master/sdk/RELEASE.md#200) in `kfp==2.0.0`.
