### ISSUE TITLE
display call for loaded component should show better view of component info

### ISSUE THREAD

**Issue by hongye-sun** [kubeflow/pipelines#947]
This is a use case in notebook, when user use ipython display API to display a loaded component. Currently, it only displays a normal python function signature. It's better to show more metadata including:
name, description, type information.

**Comment by Ark-kun** [comment]
I'm thinking of this. I'm not sure IPython would allow showing more information for a function object. It should be showing the component.yaml source (and it sometimes does that), but that's flaky.

I was thinking about returning a callable ComponentSpec object instead of a function. But I'm afraid it would be confusing to people (they might not know that it's callable). I'd still like to try and do that.
What do you think?

**Comment by Ark-kun** [comment]
>It's better to show more metadata including: name, description, type information.
It has always shown this information. Can you show a screenshot where it does not?

**Comment by hongye-sun** [comment]
Here is the sample output:

`<function dataproc_submit_pig_job(project_id, region, cluster_name, queries='', query_file_uri='', script_variables='', pig_job='', job='', wait_interval='30')>`

It doesn't show component description, parameter description, parameter type, output information.

**Comment by Ark-kun** [comment]
Try this in Jupyter:

```
my_component = kfp.components.load_component_from_text(
'''
name: My component
description: This component does whatever I want
inputs:
- name: param1
  type: My custom type
implementation:
  container:
    image: docker/whalesay:latest
'''
)
```

then type `my_component(` and press Shift+Tab or just execute `my_component??` or `help(my_component)`. You'll get:

```
Signature: my_component(param1:'My custom type')
Docstring: This component does whatever I want
Source:  
```

**Comment by Ark-kun** [comment]
What does `dataproc_submit_pig_job??` show?

**Comment by Ark-kun** [comment]
> It doesn't show component ... parameter type

Well, that component does not specify types: https://github.com/kubeflow/pipelines/blob/master/components/gcp/dataproc/submit_pig_job/component.yaml

**Comment by hongye-sun** [comment]
It shows component description in the doc string. Maybe we should also include inputs and outputs description in the docstring.

**Comment by Ark-kun** [comment]
>It doesn't show component description

Component description is used to for the docstring. But function's `__str__`  does not show the docstring. You need to invoke `help(fun)` or `fun?` or `fun(` + Shift+Tab.

Docstrings are not shown that way


>parameter description, output information.

Yes, it might be a good idea to include those in the docstring.
