### ISSUE TITLE
Standardize release tags

### ISSUE THREAD

**Issue by chensun** [kubeflow/pipelines#9476]
## Issue:

While investigating a recent [upgrade test failure](https://oss.gprow.dev/view/gs/oss-prow/pr-logs/pull/kubeflow_pipelines/9473/kubeflow-pipeline-upgrade-test/1660746693114597376), I discovered that it's upgrade upgrading from the last release (which is supposed to be 2.0.0-rc.1 at this moment)

![image](https://github.com/kubeflow/pipelines/assets/2043310/5c1fef2f-a614-439f-9b2e-173ab834e74e)

Further more, the tag [v2.0.0b2](https://github.com/kubeflow/pipelines/releases/tag/v2.0.0b2) belongs to an almost one-year old SDK release, instead of the recent backend release [2.0.0-beta.2](https://github.com/kubeflow/pipelines/releases/tag/2.0.0-beta.2) -- the runtime releases and the SDK releases have been competing with each other on git tag names:

A few examples:
The following tags are for SDK releases:
- [1.8.22](https://github.com/kubeflow/pipelines/tree/1.8.22)
- [2.0.0b17](https://github.com/kubeflow/pipelines/tree/2.0.0b17)
- [sdk-2.0.0-rc.1](https://github.com/kubeflow/pipelines/tree/sdk-2.0.0-rc.1)

while the followings are for runtime releases:
- [1.8.5](https://github.com/kubeflow/pipelines/tree/1.8.5)
- [2.0.0-beta.2](https://github.com/kubeflow/pipelines/tree/2.0.0-beta.2)
- [2.0.0-rc.1](https://github.com/kubeflow/pipelines/tree/2.0.0-rc.1)

and there are two outliers whose tag names starts with a `v`:
```bash
$ git tag --sort=v:refname | tail -30
2.0.0-alpha.2
2.0.0-alpha.3
2.0.0-alpha.4
2.0.0-alpha.5
2.0.0-alpha.6
2.0.0-alpha.7
2.0.0-beta.0
2.0.0-beta.1
2.0.0-beta.2
2.0.0-rc.1
2.0.0b1
2.0.0b2
2.0.0b3
2.0.0b4
2.0.0b5
2.0.0b6
2.0.0b7
2.0.0b8
2.0.0b9
2.0.0b10
2.0.0b11
2.0.0b12
2.0.0b13
2.0.0b14
2.0.0b15
2.0.0b16
2.0.0b17
sdk-2.0.0-rc.1
v1.7.0-alpha.3
v2.0.0b2
```

This is causing issue that the upgrade test was preparing from the wrong starting version because of the sorting: https://github.com/kubeflow/pipelines/blob/3bd2a8d0e5e1aaa51ffbd5ae116615730437ed3b/test/upgrade-tests.sh#L76

## Proposal:

I propose the following AIs to solve the issue:
1. [DONE] Delete the `v1.7.0-alpha.3` and  `v2.0.0b2` tag, so they don't mess up with tag sorting.
1. [#9478] Going forward, for SDK releases, we always prefix tag name with `sdk-`.
1. [DONE] Retag recent SDK releases (from 2.0.0b1 to 2.0.0b17) to include the `sdk-` prefix, so that `2.0.0-rc.1` becomes the latest tag without `sdk-` prefix.
1. [#9477] Change the upgrade test script to exclude tags starting with `sdk-` prefix.

@connor-mccarthy @Linchin @jlyaoyuli @gkcalat  What do you think?

**Comment by kuldeepjain** [comment]
@chensun @connor-mccarthy  Looks like in retagging the SDK releases, the tag `2.0.0b6` was missed and deleted. We no longer see `2.0.0b6` or `sdk-2.0.0b6` tag. Can you please check?

**Comment by chensun** [comment]
> @chensun @connor-mccarthy Looks like in retagging the SDK releases, the tag `2.0.0b6` was missed and deleted. We no longer see `2.0.0b6` or `sdk-2.0.0b6` tag. Can you please check?

@kuldeepjain Yes, I did experience some errors on a few old tags, and ignored them because I didn't think anyone would actually need those old tags. Any reason you're interested in this specific tag?

**Comment by kuldeepjain** [comment]
@chensun We were using that tag, is it possible to restore that to `sdk-2.0.0b6`?
cc: @rachitchauhan43 @deepk2u

**Comment by chensun** [comment]
@kuldeepjain is there anything blocking you from moving to a newer version. In fact, all 2.0 alpha and beta versions prior to 2.0.0b16 are subjects to a dependency breakage which affects all Python lightweight components at runtime. So you should probably upgrade to 2.0.0b16 or later.
Context: https://github.com/kubeflow/pipelines/issues/9300
