### ISSUE TITLE
Kubeflow version vs Jupyter Hub Image Versions Confusion

### ISSUE THREAD

**Issue by ultrons** [kubeflow/pipelines#948]
We specify a kubeflow version during our One Click Deployment. I chose 0.4.1.
Once we go the pipeline UI and try to start a jupyter hub I am presented with a list of images I can select from based on tensorflow version, cpu/gpu and kubeflow version, and there is no image listed with 0.4.1

It's good to give the user flexibility to select an image with different kubflow version but it's a little confusing as well and at the same time there is no image with the same version chosen at the time of deployment,  very confusing.

By the way, the issue aside, Kubeflow pipelines is awesome :)

**Comment by Ark-kun** [comment]
> a list of images I can select from based on tensorflow version, cpu/gpu and kubeflow version, and there is no image listed with 0.4.1

Interesting. I did not notice the images mentioning KF version in addition to the tensorflow version and flavor.

Nevertheless, there is probably not much KF or KFP-specific in those images, so the version does not really matter. You should probably try using the latest version of the KFP package by running

```
!pip3 install https://storage.googleapis.com/ml-pipeline/release/0.1.12/kfp.tar.gz --upgrade
```
in the notebook. See the [releases](https://github.com/kubeflow/pipelines/releases) page.

>By the way, the issue aside, Kubeflow pipelines is awesome :)

Thank you a lot for the feedback!

**Comment by vicaire** [comment]
Looks like this can be close. Please reopen if there is any oustanding items.
