### ISSUE TITLE
Add SDK support for sidecars

### ISSUE THREAD

**Issue by texasmichelle** [kubeflow/pipelines#949]
In order to connect to a CloudSQL instance, the cloudsql-proxy sidecar is necessary (according to the [docs](https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine)). Here is an [example definition file](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/master/cloudsql/postgres_deployment.yaml).

In order to use KF pipelines with applications that rely on CloudSQL as a backend, we need SDK support for specifying a sidecar. This is already supported by Argo (example [here](https://github.com/argoproj/argo/blob/master/test/e2e/functional/sidecar-volumes.yaml#L31-L38)).

Related to Issue #759 and potentially resolved by PR #879.

**Comment by vicaire** [comment]
PR: https://github.com/kubeflow/pipelines/pull/879

**Comment by vicaire** [comment]
Increase the priority as Michelle needs this urgently.

**Comment by Ark-kun** [comment]
The support was added in #879.
