### ISSUE TITLE
[sdk] Remove trailing whitespace in the generated YAML

### ISSUE THREAD

**Issue by zzmao** [kubeflow/pipelines#9520]
Trailing whitespace are observed in the generated YAML files:
![image](https://github.com/kubeflow/pipelines/assets/34247652/d918e5c3-bbca-440e-9f89-c778eeb95e35)

We could remove them by simply apply `rstripe()`.

@connor-mccarthy  If this looks good to you, I can create a PR.

**Comment by connor-mccarthy** [comment]
SGTM, @zzmao. Thanks for catching this.
