### ISSUE TITLE
[backend] Cache Debugging QA

### ISSUE THREAD

**Issue by WalterSmuts** [kubeflow/pipelines#9524]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)? unsure
*  KFP version: 1.8.5
*  KFP SDK version: 1.8.20

### Not a bug.
This is not a bug. Only a question. I tried joining the kubeflow slack but the link on the readme does not allow you to sign-in if you've not already got an account with https://kubeflow.slack.com/.

### Question

How do I debug tasks that are not cached? I expect it to be cached because all inputs come from cached tasks and no changes has been made. Simply re-running the pipeline without changing *anything* results in another execution of my task. I am sure I haven't set `max_cache_staleness` for this task. I'm using code-pickling (could be the culprit).

I'm hoping there is some way I can introspect the decisions on why using a cache wasn't considered. If that's not possible perhaps some tips on what kubeflow considers when deciding to use a cached output of a previous run.

---

Impacted by this bug? Give it a 👍.

**Comment by Linchin** [comment]
Hi @WalterSmuts, thank you for bringing up this question! We do allow cache for tasks, and you can check out the design doc here: https://docs.google.com/document/d/1_Hy1_KvuKh-heydg8qIyXYTiMfNPxePx4BHGpZT4xMk/edit?resourcekey=0-PTtkRPF5xpS3lD8dssqX1Q
Hope this info helps you understand the issue! Please let me know if you have any more questions.

**Comment by WalterSmuts** [comment]
This document is not publicly accessible. I've requested permission but am still waiting. 

I'm more interested in ways of *debugging* and *introspecting* the process. How do I understand why a *specific* task was cached or not cached. Can I see this information in the logs?

**Comment by gniewus** [comment]
> I'm more interested in ways of debugging and introspecting the process. How do I understand why a specific task was cached or not cached? Can I see this information in the logs?

Would be amazing to at least see the generated hash value for the task. 
I'm currently using KPF 2.0.0 on Vertex AI and the cache works correctly only  50% of the time ...
