### ISSUE TITLE
[feature] Kubeflow-Node-Red

### ISSUE THREAD

**Issue by NightLightTw** [kubeflow/pipelines#9532]
### Feature Area

It takes many laborious procedures to build a practical ML pipelines including pipeline docker file compilation and edit. Laborious manual operations on kubeflow package are required to observe trainning results.

### What feature would you like to see?

Kube-node-red is aiming to integrate Kubeflow/Kubebeters with node-red, leveraging node-red's low-code modules, and using Kubeflow resources (e.g. Kubeflow pipeline, Kserve) to enhance its AI/ML ability.

### What is the use case or pain point?

Although kubeflow pipeline is a convenient tool for major ML operations such training and testting, it takes many laborious procedures to build a practical ML pipelines, not to mention switching between various ML algorithms and data sets. A graphical UI can provide a rapid deployment medium for ML developer, professional/non professional alike, to exercise an ML operation without starting from scratch. The following site provide some completed integration suites and examples for illustration of this op.
https://github.com/NightLightTw/kubeflow-Node-RED

### Is there a workaround currently?

No workaround as far as I know.

---

Love this idea? Give it a 👍.

**Comment by Linchin** [comment]
Hi @NightLightTw, thank you for requesting this feature! Kubeflow intends to work with different platforms. It would be great if you could bring this up in the Kubeflow community meeting. 
Here are the Kubeflow manifest: https://github.com/kubeflow/manifests

**Comment by NightLightTw** [comment]
Dear @Linchin 👍 Thank you for replying our feature request.  I will be glad to attend your group meeting to introduce the new integration feature of Node-red with Kubeflow.  Please give us the web site and time of the meeting.  We will attend on time.

**Comment by thesuperzapper** [comment]
I just wanted to link my response to the other issue with what I think your next steps should be:
- https://github.com/kubeflow/manifests/issues/2499#issuecomment-1699863245
