### ISSUE TITLE
docs(backend): v2 concepts 

### ISSUE THREAD

**Issue by Linchin** [kubeflow/pipelines#9538]
### Environment
run, job, pipeline, pipeline version,  etc.
Similar to https://www.kubeflow.org/docs/components/pipelines/v1/concepts/

*  How do you deploy Kubeflow Pipelines (KFP)?

*  KFP version:

*  KFP SDK version:

### Labels

---

Impacted by this bug? Give it a 👍.

**Comment by chensun** [comment]
Obsolete
