### ISSUE TITLE
Proxy agent and Controller Manager in CrashLoopBackOff state

### ISSUE THREAD

**Issue by keithpij** [kubeflow/pipelines#9546]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
I deployed KFP to the K8S cluster that comes with Docker Desktop. I used the following commands:

  export PIPELINE_VERSION=2.0.0-rc.1
  kubectl apply -k "github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=$PIPELINE_VERSION"
  kubectl wait --for condition=established --timeout=60s crd/applications.app.k8s.io
  kubectl apply -k "github.com/kubeflow/pipelines/manifests/kustomize/env/dev?ref=$PIPELINE_VERSION"

*  KFP version: Version: 2.0.0-rc.1

*  KFP SDK version: I ran: pip install kfp --pre
    kfp                      2.0.0rc1
    kfp-pipeline-spec        0.2.2
    kfp-server-api           2.0.0rc1

### Steps to reproduce
I am seeing the proxy-agent pod and the controller-manager pod stuck in the CrashLoopBackOff state. When I look at the logs of the proxy-agent I see the output below. I am unable to look at the logs of the controller-manager. When I try I get a message saying "logs are hidden because volume is too excessive".  The KFP UI seems to be working fine and I can submit a pipeline and get it to run. I just need to understand these errors in case I see them in another environment.

+++ dirname /opt/proxy/attempt-register-vm-on-proxy.sh
++ cd /opt/proxy
++ pwd
+ DIR=/opt/proxy
++ kubectl get configmap inverse-proxy-config -o json
++ jq -r '.data.Hostname // empty'
+ HOSTNAME=
+ [[ -n '' ]]
+ [[ ! -z '' ]]
++ curl http://metadata.google.internal/computeMetadata/v1/instance/zone -H 'Metadata-Flavor: Google'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: metadata.google.internal

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

**Comment by zijianjoy** [comment]
Can you try this installation approach instead?
https://www.kubeflow.org/docs/components/pipelines/v1/installation/localcluster-deployment/#deploying-kubeflow-pipelines

**Comment by Hongbo-Miao** [comment]
I got [same error](https://github.com/kubeflow/pipelines/issues/9719) on latest version 2.0.0 too when install by

```shell
export PIPELINE_VERSION=2.0.0
kubectl apply --kustomize="github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=${PIPELINE_VERSION}"
kubectl wait crd/applications.app.k8s.io --for=condition=established --timeout=60s
kubectl apply --kustomize="github.com/kubeflow/pipelines/manifests/kustomize/env/dev?ref=${PIPELINE_VERSION}"
```

Based on @keithpij method:

```shell
export PIPELINE_VERSION=2.0.0
kubectl apply --kustomize="github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=${PIPELINE_VERSION}"
kubectl wait crd/applications.app.k8s.io --for=condition=established --timeout=60s
kubectl apply --kustomize="github.com/kubeflow/pipelines/manifests/kustomize/env/platform-agnostic?ref=${PIPELINE_VERSION}"
```

This will install without `proxy-agent` and `controller-manager` 😃

---

Regarding `platform-agnostic-pns` - Process Namespace Sharing (PNS) which also mentioned [here](https://www.kubeflow.org/docs/components/pipelines/v1/installation/localcluster-deployment/#deploying-kubeflow-pipelines)

> Note: Process Namespace Sharing (PNS) is not mature in Argo yet - for more information go to [Argo Executors](https://argoproj.github.io/argo-workflows/workflow-executors/) and reference “pns executors” in any issue you may come across when using PNS.

I found in [ArgoCD document](https://argoproj.github.io/argo-workflows/workflow-executors/#process-namespace-sharing-pns), it shows:

![image](https://github.com/kubeflow/pipelines/assets/3375461/f10a458d-161f-462c-9b41-ec25acc5ca3c)

So I think we should not use `platform-agnostic-pns` any more.

**Comment by imranrazakhan** [comment]
I tested with 2.3.0 and Proxy agent in CrashLoopBackOff state.

**Comment by etheleon** [comment]
HI @imranrazakhan, 

I deleted the deployement `proxy-agent` and `controller-manager` deployments following @hongbo-miao's advise and it works. Hope this helps :)

**Comment by etheleon** [comment]
@HumairAK, Can we reopen this issue. I would love to work on this 🙇

**Comment by george-kuanli-peng** [comment]
I got same error on latest version 2.3.0 too and the workaround by @hongbo-miao works for me.

```bash
export PIPELINE_VERSION=2.3.0
kubectl apply --kustomize="github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=${PIPELINE_VERSION}"
kubectl wait crd/applications.app.k8s.io --for=condition=established --timeout=60s
kubectl apply --kustomize="github.com/kubeflow/pipelines/manifests/kustomize/env/platform-agnostic?ref=${PIPELINE_VERSION}"
```

**Comment by kaikaila** [comment]
I experienced the same bug on version 2.4.0. I agree with @etheleon that we should reopen this issue, since he' committed to fix it.

**Comment by techiechap** [comment]
Is there any way i can use 1.8X rc?
