### ISSUE TITLE
[feature] Kubeflow kserve pipeline with Node-red control for IOT application

### ISSUE THREAD

**Issue by ifuwang** [kubeflow/pipelines#9583]
### Feature Area

We implemented a kserve pipeline specifically for the IOT Rasberry PI chipset.  The pipeline takes in a regular input data, be a text or image, and feeds into a trained model. e.g. H5 file, from other AI training processes.   The pipeline will take an input from Rasberry PI sensor, and deliver an output back to the PI chipset for proper response such as playing an audio or beeping a buzzer.  A node-red GUI frontend is constructed with a custom node which can trigger the execution of such a kserve pipeline.  The message node in the node-red pallet can be dragged to the canvas and connected to the kserve pipeline node will show the inference result. 

### What feature would you like to see?
A node-red GUI frontend is constructed with a custom node which can trigger the execution of such a kserve pipeline.  The message node in the node-red pallet can be dragged to the canvas and connected to the kserve pipeline node.  Eventually, it shows the inference result which can be a text or an action on the PI sensor. 

### What is the use case or pain point?
A medical care use case can be tested here.  The completed kserve pipeline can detect whether the patients entering a hospital is wearing a mask or not.  The node-red custom node trigger a Rasberry PI chip camera sensor and feed it to the kserve model and get feedback from the inference result.  The result then transfer back to the Rasberry PI for proper response.  

The medical use case is helpful for saving hospital human labors.  Additionally, this pipeline can be useful for easy configuration of any IOT development where a desired input can be led to the model for inference.  The inference result can be fed back to the PI for response.  The benefit of such pipeline is easy and fast deployment of a trained model for relevant IOT devices. 
### Is there a workaround currently?
None to my knowledge.

---

Love this idea? Give it a 👍.

**Comment by Linchin** [comment]
Hi @ifuwang, could you please explain what exactly needs to be done on KFP to achieve this feature? Thank you.

**Comment by ifuwang** [comment]
@Linchin thanks for your enquiry.  What this feature needs is a Node-red front end interacting with a Kubeflow pipeline modules.  The Node-red front end originally comes with GUIs specifically geared toward IOT applications.  For Node-red nodes to communicate with the Kubeflow pipeline, a KFP server API is needed to interact with the Node-red custom Nodes.  We have initially implemented a few custom nodes that communicate with the kubeflow pipeline containers.  They are a random forest pipeline node, a decision tree pipeline node, and a logistic regression pipeline node as can be seen in the following site:
https://github.com/NightLightTw/kubeflow-Node-RED，What is missing currently is an integration canvas showing fusion of this AI pipeline node with the IOT operation nodes.  This will then complete  the targeted feature to complete the  AIOT application scenario.   We hope to present this feature within the kubeflow suite.  Please let us know what and where is the best way to present?
