### ISSUE TITLE
[backend] OOM on large OutputPath file

### ISSUE THREAD

**Issue by WalterSmuts** [kubeflow/pipelines#9584]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
Not sure
*  KFP version: 
Version: 1.8.5
*  KFP SDK version: 
```
$ pip list | grep kfp
kfp                          1.8.20
kfp-pipeline-spec            0.1.16
kfp-server-api               1.8.5
```

### Steps to reproduce

Run the code in the listing below. I observer OOM. I observer the following logs:
```
time="2023-06-07T10:47:13.665Z" level=info msg="capturing logs" argo=true
Waiting before...
Waiting after...
time="2023-06-07T10:49:15.563Z" level=info msg="/tmp/outputs/output/data -> /var/run/argo/outputs/artifacts/tmp/outputs/output/data.tgz" argo=true
time="2023-06-07T10:49:15.563Z" level=info msg="Taring /tmp/outputs/output/data"
time="2023-06-07T10:49:26.391Z" level=info msg="archived 2 files/dirs in /tmp/outputs/output/data"
```

Then I observe state `This step is in Error state with this message: OOMKilled (exit code 137)`.

### Expected result

No OOM. I specify that the pod should have atleast 8GB free memory. I expect that the processes involved in zipping and transferring a 500MB file should not exceed the 8GB limit.

### Materials and Reference

```python
from kfp import dsl
from kfp.components import func_to_container_op
from kfp.components import OutputPath, InputPath


@func_to_container_op
def create_large_output_dir(
    output_path: OutputPath(str),  # type: ignore
):
    import os
    import time

    print("Waiting before...")
    time.sleep(60) 
    os.system(f"mkdir -p {output_path}")
    os.system(f"tail --bytes 500M /dev/urandom > {output_path}/out.txt")
    print("Waiting after...")
    time.sleep(60) 


@func_to_container_op
def ingest_large_input_dir(
    input_path: InputPath(str),  # type: ignore
):
    import os

    os.system(f"ll {input_path}")


@dsl.pipeline(name="metrics-visualization-pipeline")
def pipeline():
    task = create_large_output_dir()
    task.set_memory_request("8G")
    ingest_large_input_dir(input=task.outputs["output"])


from kfp import Client

client = # the client

client.create_run_from_pipeline_func(
    pipeline,
    arguments={},
    experiment_name="walter-experiment",
    run_name="walter-run",
)
```

---

Impacted by this bug? Give it a 👍.

**Comment by WalterSmuts** [comment]
I found out there is an argoexecutor which runs alongside the Python container. The cluster logs indicated that it was being OOMKilled. I found a config in the cluster that specified memory settings for argoexecutor so I increased the max from 512MB to 1024MB. This solved the issue.

I still think it would be helpful to provide a bit more information via the UI to help debug these kind of issues

**Comment by chensun** [comment]
Curious if this also affects v2. @Linchin to help follow up.

**Comment by mysterious-progression** [comment]
We have the same problem (with InputPath). It appears there is a fundamental flaw in that the entire file is read into memory in the argo containers responsible for moving files. The correct and desired behavior is that the file should transferred by chunking. 

It's not clear whether this is a bug the kubeflow team needs to fix or the argo team.
