### ISSUE TITLE
tfx/taxi-cab-classification-pipeline.py  fails at preprocess step with 

### ISSUE THREAD

**Issue by ucdmkt** [kubeflow/pipelines#960]
Steps to reproduce

$ pip list
 : 
kfp                      0.1.11  

$ python taxi-cab-classification-pipeline.py

(upload taxi-cab-classification-pipeline.py.tar.gz from Pipelines UI)

Run fails at preprocessing, with the following log.

Traceback (most recent call last):
  File "/ml/transform.py", line 303, in <module>
    main()
  File "/ml/transform.py", line 276, in main
    schema = json.loads(file_io.read_file_to_string(args.schema))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 295, in read_file_to_string
    return f.read()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 120, in read
    self._preread_check()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 80, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /tfx-taxi-cab-classification-pipeline-example-9pw4w/validation/schema.json; No such file or directory

**Comment by ucdmkt** [comment]
From 'validation' step's log, I see the following log lines

INFO:root:Writing schema to /tfx-taxi-cab-classification-pipeline-example-9pw4w/validation/schema.pb2
INFO:root:Writing JSON schema to /tfx-taxi-cab-classification-pipeline-example-9pw4w/validation/schema.json


I do also see some anomalies raised from the 'validation' step, but 'validation' component itself succeeds.

**Comment by Ark-kun** [comment]
Does this reproduce?

**Comment by gaoning777** [comment]
Is it still an issue? @ucdmkt 
Feel free to reopen if so.

**Comment by benjamintanweihao** [comment]
@ucdmkt did you manage to solve this because I'm seeing the same problem

**Comment by ucdmkt** [comment]
@benjamintanweihao My above error report is a long time ago (previous release of TFX, based on far old release of KFP), so I suspect it is not relevant any more. 

What versions of TFX and KFP are installed, and do you see the same stack trace?

**Comment by ucdmkt** [comment]
For my particular case, updating to more recent TFX and KFP eliminated the above-reported error.
