### ISSUE TITLE
[feature] <Quantum AI kubeflow pipeline with Node-red control>

### ISSUE THREAD

**Issue by justin0322** [kubeflow/pipelines#9600]
### What feature would you like to see?
A GUI front-end that allows users to trigger a quantum AI flow without having to do the manual configuration of traditional data to/from quantum data, and adapt a specific quantum circuit.  The flow can take any traditional data for quantum AI training.  A slection of quantum circuit is ready for rapid testing of a real world AI big data test case. 

### What is the use case or pain point?
The use case can be a simple mnist CNN classification problem or a complicated virus detection problem using PSO swarm algorithm, e.tc.

Quantum AI features a mass parallel calculation capability which can expedite the AI training process for many industrial applications. However, its setup process is inherent complicated. Generally, It not only requires conversion to/from traditional data to quantum data, but also the design of complex quantum circuit. We wrap the whole procesures into a kubeflow pipeline, and show the control flow can be run on a Node-red GUI front end.  The test case runs a mnist data set CNN classification application and the accuracy can reach a %96 high with short one half training time compared to traditional AI.  We are seting up the PR and will have a local repository for all the code and readme file illustrating the complete processes.
### Is there a workaround currently?
None to my knowledge

One have to go through a laborious set up and conversion procedures of traditional data to/from quantum data.  It generally requires some professional understanding of the quantum simulator such as IBM Qiskit.

---

Love this idea? Give it a 👍.

**Comment by Davidnet** [comment]
This is maybe going over my head, but maybe what you could do at the moment is using Kubeflow to interact with the IBM SDKs and use their APIs to control a quantum computer. Maybe a cool first pr will be a cool Kubeflow pipeline example interacting with that kind of service. Let me know if that workaround works for you.

**Comment by justin0322** [comment]
Dear David,

Great to hear you are interested in our project.  At this moment we have built the whole integration flow from Node-red to kubeflow pipeline.  The whole kubeflow pipeline on quantum AI is fully tested and proven feasible.  However, our quantum AI features joining qiskit neural network simulation, rather real quantum computer.  We will do an initial PR on kubeflow pipeline ASAP.  Please help review the PR and give us your opinions.
