### ISSUE TITLE
Make single step pipeline easier in DSL

### ISSUE THREAD

**Issue by hongye-sun** [kubeflow/pipelines#961]
There is many boilerplate code to build a single component pipeline today. See example: https://github.com/kubeflow/pipelines/blob/b4ad648fb0acd2f73f8cd3d819e5de17ab70bc7f/components/gcp/bigquery/query/README.md

Better to provide support in DSL to make it less tedious. Example:
```
component_op = load_component(...)
pipeline = **dsl.build_pipeline_from_component**(component_op)
compiler.Compiler().compile(pipeline)
```

**Comment by Ark-kun** [comment]
That's pretty easy to do, but I wonder about the use case. The only thing you can do with a pipeline is to upload it to KFP server and submit for execution.

Submitting single component for execution might be more useful:

```
component_op = load_component(...)
client.run_component(arguments={'param1': 'value1'})
```
or 

```
component_op = load_component(...)
task = component_op(param1='value1')
client.run_task(task)
```

Do you think this will cover your use case?

**Comment by vicaire** [comment]
+1

For instance: 
- Creating a pipeline with a single step using a TF-job should be as easy as running a TF-job directly using fairing. 
- Same for a Katib job.

**Comment by randxie** [comment]
@Ark-kun @hongye-sun I have created a prototype to address this issue (for internal need) that converts a ContainerOp into a pipeline func by filling args/kwargs into the following template:

```Python
def pipeline({pipeline_kwargs}):
  task = component_op({component_args}){use_gcp_secret}
```

After the filled template is converted into a Python function, the dsl.pipeline decorator is applied to the generated function. Then the compiler is able to compile the pipeline func into pipeline.tar.gz. Do you think such implementation is general enough to be incorporated?

**Comment by Ark-kun** [comment]
> I have created a prototype to address this issue

That sounds great. What's the user-facing APi of that prototype?

**Comment by Ark-kun** [comment]
Solved by https://github.com/kubeflow/pipelines/pull/1555
You can now do the following:

```python
train_op = load_component(....)
compiler.Compiler().compile(train_op)
```
or
```python
train_op = load_component(....)
kfp.Client().create_run_from_pipeline_func(train_op, arguments={...})
```
