### ISSUE TITLE
[backend] using large number of file watchers / instances

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/pipelines#9610]
Kubeflow Pipelines seems to be using a very large number of file watchers & instances, this has caused issues like: 

- https://github.com/kubeflow/manifests/issues/2087

Currently, the only solution is to increase the max, with these values in `/etc/sysctl.conf`:

- `fs.inotify.max_user_instances = 1280`
- `fs.inotify.max_user_watches = 655360`

I am not certain which Pod is opening all these file watchers, but I think it might be `Deployment/ml-pipeline` (that is, `gcr.io/ml-pipeline/api-server`) because it fails to start with the `"too many open files"` error. However, it also might be that `ml-pipeline` will fail if there are too many open files, but it's not causing the large number of open files.

I am not sure if we can do something about how many of these file watchers we use, to get it down to a more typical number.
I would appreciate someone taking a look.

---

Impacted by this bug? Give it a 👍.

**Comment by thesuperzapper** [comment]
@kubeflow/wg-pipeline-leads

**Comment by jlyaoyuli** [comment]
Hello @thesuperzapper, can you provide more information to prove that the issue (open too many files) is attributed by pipeline?
