### ISSUE TITLE
[feature] Plotting Scalar Metrics

### ISSUE THREAD

**Issue by axel7083** [kubeflow/pipelines#9613]
### Feature Area

/area backend

### What feature would you like to see?

I would like to be able to plot for example getting an Histograms when comparing runs based on chosen scalar metrics.

### What is the use case or pain point?

It would make easier to visualize the results.

---

Love this idea? Give it a 👍.

**Comment by zpChris** [comment]
I think it would make reading those scalar metrics easy in many circumstances, depending on the range and quantity of the data. It might be tricky to display different variables in this format - whether they would be on the same histogram with a color legend (while paying attention to accessibility concerns), or if each variable would have its own separate histogram.

I was working on this CompareV2 page last summer, though I am not currently working on this area.
