### ISSUE TITLE
[sdk]: credentials type as str instead of ServiceAccountTokenVolumeCredentials

### ISSUE THREAD

**Issue by axel7083** [kubeflow/pipelines#9614]
## Description

When creating a kfp Client and providing the argument `credentials`, the typing indicates `str` but is suppose to be `kfp.client.ServiceAccountTokenVolumeCredentials`.

https://github.com/kubeflow/pipelines/blob/a9ac0b95bcc69c6214ca4e5e3208c816096f0377/sdk/python/kfp/client/client.py#L153

**Comment by gkcalat** [comment]
Hi @axel7083!
Thank you. If you would like, you are very welcome for send a short PR and cc @connor-mccarthy.
