### ISSUE TITLE
[feature] <Bagging pipeline with Node-red control>

### ISSUE THREAD

**Issue by Lance410247** [kubeflow/pipelines#9621]
### What feature would you like to see?

Bagging is an Ensemble learning technique that allows partition of a whole data set into different sub-set of dataset for seperate training processes and aggregation of a final prediction result given different balloting strategy.  Bagging is a useful technique normally seen in federated learning for many industrial applications such as IT security and medical services where privacy is an issue.  Our bagging pipeline has data separation, decision tree training and balloting steps.  Each is wrapped into pipeline components.  A complete pipeline docker file is constructed and a yaml file is conbined within a Node-red custom node for easy deployment. 

### What is the use case or pain point?
Bagging pipeline requires a lot of man power to construct including data separation and different AI training procedures.  An automation feature can save developer or deployer alike a lot of labor.   A GUI is handy to have for easy deployment and testing of different data partition schemes and different training algorithm.

We use breast cancer data set for our illustration.
### Is there a workaround currently?
none to my knowledge.  Currently, we have an initial draft if all the codes and readme file in the following repository: 
https://github.com/Lance410247/kubeflow-node-red

---

Love this idea? Give it a 👍.

**Comment by 482170765** [comment]
reopen
