### ISSUE TITLE
[Pipeline backend] <In few scenarios, on pipeline terminate, the pipeline doesn't show the right status>

### ISSUE THREAD

**Issue by mChowdhury-91** [kubeflow/pipelines#9627]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
  Standalone deployment

*  KFP SDK version: 1.8.14

### Steps to reproduce
There are 2 scenarios:
1. For long running Kubeflow pipelines, the terminate pipeline action doesn't update the right status. The job was complete, but the status show running and even on terminate nothing happens..
2. Sometimes, the terminate button doesn't change the status. Although the pod is terminated and "Completed", the kubeflow UI still shows the pipeline as running..

### Expected result

On terminate, once the pipeline pod is killed and in "Completed" status, the UI should also reflect back the failure staus

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

**Comment by gkcalat** [comment]
Thank you @mChowdhury-91. This is covered by #8966. Let's keep that for tracking the issue.
