### ISSUE TITLE
[samples] Component specification for kfpv2

### ISSUE THREAD

**Issue by surajkota** [kubeflow/pipelines#9638]
### Feature Area

/area samples
/area components

### What feature would you like to see?
Samples and documentation on component specification, build and package instructions for KFPv2 components similar to https://www.kubeflow.org/docs/components/pipelines/v1/sdk/component-development/#creating-a-component-specification so that users can simply use `load_component_from_file/url` to use a component.

### What is the use case or pain point?
We are investigating KFPv2 support for [SageMaker components](https://github.com/kubeflow/pipelines/tree/master/components/aws/sagemaker#amazon-sagemaker-components-for-kubeflow-pipelines) so that users can simply use `load_component_from_file/url` and run their workload. This is general ask since all the components might need to make changes to support KFPv2

I have looked at following documentation:
- https://www.kubeflow.org/docs/components/pipelines/v2/load-and-share-components/
- https://www.kubeflow.org/docs/components/pipelines/v2/components/container-components/
- https://www.kubeflow.org/docs/components/pipelines/v2/components/containerized-python-components/

Will components built for KFPv1 be compatible with KFPv2?

---

Love this idea? Give it a 👍.

**Comment by chensun** [comment]
> Will components built for KFPv1 be compatible with KFPv2?

Generally speaking, yes. KFP v2 aims to be backward compatible with v1 components for the critical paths. 

To add one more documentation to your existing list, components and pipelines are now compiled/persisted in the same manner:
https://www.kubeflow.org/docs/components/pipelines/v2/compile-a-pipeline/
