### ISSUE TITLE
dsl.ContainerOp.after() only works with Ops that have already sanitized names

### ISSUE THREAD

**Issue by mschuwalow** [kubeflow/pipelines#965]
With version 0.1.11

This works:
dataset_op = S3DownloadOp("download-dataset", ...)

train_op = TrainOp("train",... )
train_op.after(dataset_op)

This doesn't:
dataset_op = S3DownloadOp("Download-dataset", ...)

train_op = TrainOp("train",... )
train_op.after(dataset_op)

**Comment by hongye-sun** [comment]
I believe this has been fixed by https://github.com/kubeflow/pipelines/commit/7ce03f07d41a04fbfac96812ee99b716032178fb.

Could you try 0.1.12?

**Comment by mschuwalow** [comment]
Yeah its fixed in 0.1.12. Thanks for the quick reply and I'm closing the issue.
