### ISSUE TITLE
[bug] Out of date documentation linked in google-cloud-components on README file 

### ISSUE THREAD

**Issue by patelmm79** [kubeflow/pipelines#9670]
[This page](https://github.com/kubeflow/pipelines/tree/master/components/google-cloud) appears to be updated for v2.0.0,

however, the text "Please see the [Google Cloud Pipeline Components API reference documentation] " links to v1.0.41 documentation.

Impacted by this bug? Give it a 👍.

**Comment by gkcalat** [comment]
This has been fixed. Thanks!
