### ISSUE TITLE
[feature] Option to provide pipeline parameters as a JSON file or some other key-value mapping.

### ISSUE THREAD

**Issue by seanswyi** [kubeflow/pipelines#9672]
### Feature Area

/area sdk

### What feature would you like to see?

As far as I'm concerned when creating a pipeline using a Python function, you can specify the pipeline parameters so that you can adjust them in the Kubeflow UI. However, I thought that it would be convenient if we could provide the parameters as a dictionary or something rather than type out every single parameter in the Python code.

### What is the use case or pain point?

Being able to manage many pipeline parameters and keep track of runs and their argument values.

### Is there a workaround currently?

Not exactly a workaround. The pipeline that I want to run has a total of 30ish parameters and I'm currently finding myself manually typing them out in the function definition.

---

Love this idea? Give it a 👍.

**Comment by chensun** [comment]
Hi @seanswyi, we do support dictionary-typed input parameters in v2: https://www.kubeflow.org/docs/components/pipelines/v2/data-types/parameters/#input-parameters

**Comment by seanswyi** [comment]
@chensun Thanks, just noticed. I'll try to use that and re-open the issue if needed.
