### ISSUE TITLE
[feature] Migration from @material-ui to @mui

### ISSUE THREAD

**Issue by Sharathmk99** [kubeflow/pipelines#9675]
### Feature Area

/area frontend

### What feature would you like to see?

We are planning to introduce hierarchy Run List view to accommodate use-cases like Resume Training KF Run should be under Main Train KF Run also Analysis KF Run should be under respective Train KF Run.

- Train 1
- -- Resume Train
- -- Analysis Run 1
- -- Retry Resume Train
- Train 2
- -- Resume Train
- ....

As Frontend uses very old `@materila-ui` package it's difficult to implement this view. Planning to use this package https://material-table.com/#/docs/features/tree-data, but it doesn't work as it depends on @mui package.
Any plans to upgrade @material-ui to @mui?

### Is there a workaround currently?

No

---

Love this idea? Give it a 👍.

**Comment by zijianjoy** [comment]
I think we already have this functionality for grouping list:

![4G5aCkHM7Yw9y94](https://github.com/kubeflow/pipelines/assets/37026441/7238f6a7-bf6a-4cc0-8be0-ff012af5e01f)
