### ISSUE TITLE
Where is `UserContainer` for v2? Is it deprecated completely?

### ISSUE THREAD

**Issue by seanswyi** [kubeflow/pipelines#9679]
I was previously using `UserContainer` to create my init containers as follows:

```
    @property
    def INIT_CONTAINER(self) -> dsl.UserContainer:
        return dsl.UserContainer(
            name="git-sync",
            image="k8s.gcr.io/git-sync:v3.1.1",
            mirror_volume_mounts=True,
        )
```

However, I notice that in v2 it's been deprecated. What can I use in v2 to implement the same functionality? I've tried using things like `ContainerSpec` but I'm not sure if it's the same thing.

https://github.com/kubeflow/pipelines/blob/536d93a1bffe035bf5222e7a48faf59d3b053800/sdk/python/kfp/deprecated/dsl/_container_op.py#L685

**Comment by chensun** [comment]
`UserContainer` is deprecated from v2. Can you check if `container_component` fits your use case?
https://www.kubeflow.org/docs/components/pipelines/v2/components/container-components/

**Comment by seanswyi** [comment]
@chensun @rimolive Sorry for the late reply. Yes, I recall using `container_component` and `ContainerSpec` instead of `UserContainer` worked.
