### ISSUE TITLE
Unable to run sidecar with kubeflow

### ISSUE THREAD

**Issue by robbiedow** [kubeflow/pipelines#9700]
Hi,

I am trying to run a sidecar in a kubeflow component, and I can't figure out how to do it. I found some [documentation](https://kf-pipelines.readthedocs.io/en/latest/source/kfp.dsl.html#kfp.dsl.Sidecar) that indicates there is a class called kfp.dsl.Sidecar, but this example indicates this is not the case.

**I Ran:**

```
import kfp
echo = kfp.dsl.Sidecar(
        name="echo",
        image="nginx:1.13",
        command=["nginx", "-g", "daemon off;"],
    )
```

**I got the error:**

`AttributeError: module 'kfp.dsl' has no attribute 'Sidecar'`

I also tried implementing [this example](https://github.com/kubeflow/pipelines/blob/master/samples/core/sidecar/sidecar.py) from the kubeflow pipelines repo, but the line `from kfp.deprecated import dsl, compiler` does not import. I kept getting the error `AttributeError: module 'kfp.dsl' has no attribute <SomePackage>` for various packages. After pip installing the ones that were missing, I finally got `AttributeError: module 'kfp_server_api' has no attribute 'ApiGetHealthzResponse'` which I don't know how to resolve.

It seems that the GitHub example and documentation are both for Kubeflow v1 anyways, and I am looking for a solution that works in v2. Is there a way to implement a sidecar on v2?

**Comment by Linchin** [comment]
Hi @robbiedow, the documentation you linked is not the official documentation. Please use [this](https://kubeflow-pipelines.readthedocs.io/en/sdk-2.0.1/) for documentation. At this point, KFP v2 does not support sidecar. We will use #9768 to track the feature request.
