### ISSUE TITLE
[feature] Continued support for resourceOp / custom resource definitions

### ISSUE THREAD

**Issue by vsoch** [kubeflow/pipelines#9703]
### Feature Area

/area backend
/area sdk

### What feature would you like to see?

To continue discussion from https://github.com/kubeflow/pipelines/issues/8570, the resourceOp was deprecated in v2, and although `kfp[kubernetes]` [supports](https://www.kubeflow.org/docs/components/pipelines/v2/platform-specific-features/) the removed volume types, there is no longer obvious support or design plan for resourceOp being used in the context of creating a custom resource definition. Any custom operator that would have worked in v1 via resourceOp no longer has support. For our use case, we were testing version 1 (and required this ability) and version 2 has become not possible for us to use. I suspect there is equivalent need if you ask across the community.

### What is the use case or pain point?

Running custom resources / controllers that can handle scoped work to work with KubeFlow pipelines.

### Is there a workaround currently?

I have not found a workaround - I am looking to use Kueue or back to basic Argo (the first might be a good direction, the second adds some complexity in that logs / statuses aren't easy to pass forward to the running Argo pod without a bit of hacks.

---

Love this idea? Give it a 👍.

**Comment by zijianjoy** [comment]
Feel free to contribute to `kfp[kubernetes]` to extend the capability of VolumeOps.

**Comment by vsoch** [comment]
We can close - I am going to follow https://github.com/kubeflow/pipelines/issues/9768
