### ISSUE TITLE
[bug] back button after opening run link not working

### ISSUE THREAD

**Issue by axel7083** [kubeflow/pipelines#9715]
### Environment

*  How do you deploy Kubeflow Pipelines (KFP)? manifests

*  KFP version: 2.0.0

*  KFP SDK version: 2.0.0

## Description

When opening an url with a run-id like `https://{hostname}/_/pipeline/#/runs/details/{run-id}` we are redirected to `https://{hostname}/_/pipeline/?ns={namespace}#/runs/details/{run-id}` 

When clicking on the `back` button.
![image](https://github.com/kubeflow/pipelines/assets/42176370/0ad707b3-465f-4660-a7ce-1c0de026706a)

The url changed from `https://{hostname}/_/pipeline/?ns={namespace}#/runs/details/{run-id}` to the original link we clicked on without the namespace without the page changing. (Probably using back or previous url)

### Expected result

Going back to the list of run ? or experiment ? 

### Labels

/area frontend

---

Impacted by this bug? Give it a 👍.

**Comment by chensun** [comment]
@jlyaoyuli can you please help verify if there's a bug? Thanks!
