### ISSUE TITLE
[sdk] Setting the Display name of the component doesn't show updates to the pipeline

### ISSUE THREAD

**Issue by hugzee3** [kubeflow/pipelines#9721]
### Environment

*  KFP: 2
*  KFP SDK version: 2.0.1
*  All dependencies version:
kfp                                2.0.1
kfp-pipeline-spec       0.2.2
kfp-server-api             2.0.0

### Description

Renaming a component only reflects the name change, but doesn't update the KFP UI with the logs/ IO params, etc. 

### Steps to reproduce

```
import os

import kfp
from kfp.dsl import component, Output, Artifact, pipeline


@component(base_image="python:3.10-slim")
def comp(a: int, b: int, c: Output[Artifact]):
    import json

    with open(c.path, "w") as fp:
        json.dump({"result": a + b}, fp)
        pass

    pass


@pipeline(name="test-component-renaming-pipeline")
def test_pipeline(a: int, b: int):
    task = comp(a=a, b=b)
    task.set_display_name("Add Component").  # uncommenting this would render the screenshot 2 below
    pass


def compile_pipeline(pipeline, yaml_filename, dirname="."):
    path = os.path.join(dirname, yaml_filename)
    cmplr = kfp.compiler.Compiler()
    cmplr.compile(pipeline_func=pipeline, package_path=path)
    pass


if __name__ == "__main__":
    compile_pipeline(
        test_pipeline,
        yaml_filename=os.path.join(os.path.dirname(__file__), "test-component-renaming-pipeline.yaml"),
    )
    pass
```

### Current result

![Screenshot 2023-07-10 at 17 39 35](https://github.com/kubeflow/pipelines/assets/56828368/41d29fc4-fc94-4c55-a9db-c5dd33ad428a)

### Expected result

![Screenshot 2023-07-10 at 17 40 31](https://github.com/kubeflow/pipelines/assets/56828368/21e0e4d2-fe7c-48fc-bcb3-a0879e7fc0d6)

Impacted by this bug? Give it a 👍.

**Comment by zijianjoy** [comment]
Hello @hugzee3 , looks like you are hitting a cache in `Expected result`, so it is using the same artifact path as the first run. So maybe you can try creating a new pipeline without hitting the cache?

**Comment by hugzee3** [comment]
Hi @zijianjoy , 
How exactly can i do this?

**Comment by hugzee3** [comment]
Hey @zijianjoy , I did try running a new pipeline with `run_pipeline(enable_caching=False)` it doesn't seem to take any effect. Still the same.

**Comment by zijianjoy** [comment]
@hugzee3 Is the problem regarding `Output Artifact` still using `Add Component` in its path name? What is the new artifact path name when you disable caching?
