### ISSUE TITLE
Add static type checking sample test

### ISSUE THREAD

**Issue by gaoning777** [kubeflow/pipelines#974]
A full coverage at the e2e tests help to identify the problems sooner.
And, adding basic sample tests as e2e tests also help to illustrate the features.

**Comment by vicaire** [comment]
@gaoning777, could you please provide more details on the scope of this issue? Is it about improving e2e test coverage for everything? Or just some particular features or samples?

**Comment by gaoning777** [comment]
I added the issue such that the problems in the referenced PRs can be surfaced earlier. 
Now changing the title to add a static type checking sample test.

**Comment by Ark-kun** [comment]
AFAIK all current type checking code can be tested by unit-tests that do not require cluster.
If you want to test a sample notebook, it's easy to programmatically convert it to python and execute.
