### ISSUE TITLE
`AttributeError: cython_sources` when installing KFP SDK + running Python components

### ISSUE THREAD

**Issue by connor-mccarthy** [kubeflow/pipelines#9745]
> TLDR: Cython 3.0.0 just GA'd and introduced a regression which affects building `pyyaml` on _some_ operating systems with _some_ versions of Python. Upgrade to the latest version of the KFP SDK (v1 or v2) and recompile your components to get the fix.

**Short term fix options**
* Upgrade to the latest version of the KFP SDK within the major version you are using (`1.8.22` and `2.0.1` at the time of writing this)
* Switch to a Python image/version that does not exhibit this error (`python:3.7` appears to work in some cases)

With either option, recompile your components to get the fix.

**Useful information**
* This is an issue originating from outside the KFP.
* https://github.com/yaml/pyyaml/issues/601 is good public documentation of this issue.
* This is thematically similar to https://github.com/kubeflow/pipelines/issues/9326#issuecomment-1535491761, but appears to have smaller impact due to fewer affected combinations of KFP SDK versions and environments.

**Reproducing**
* `docker run python:3.7 pip install 'kfp==1.8.20'` PASS
* `docker run python:3.10 pip install 'kfp==1.8.20'` FAIL

* `docker run python:3.10 pip install 'kfp==1.8.22'` PASS

* `docker run python:3.10 pip install 'kfp>=2.0.0,<3.0.0'` PASS

**Long term fix**

We are nearing completion a change that extracts a KFP runtime package, preventing similar failures for existing components that use prior versions of the KFP SDK (versions we cannot patch once released).

**Comment by atemate** [comment]
Seeing this issue on GCP Vertex that uses Kubeflow internally. Forcing `pyyaml==5.3.1` fixes the issue (see [this comment](https://github.com/yaml/pyyaml/issues/724#issuecomment-1638587228))
