### ISSUE TITLE
[Request header error: there is no user identity header] Using the kubeflow pipeline APIs, I was unable to create a run.

### ISSUE THREAD

**Issue by srikarjavvaji** [kubeflow/pipelines#9747]
I am following tutorial of Kubeflow Pipelines API: [Kubeflow](https://www.kubeflow.org/docs/components/pipelines/v1/tutorials/api-pipelines/) & [Kubeflow Pipelines API](https://www.kubeflow.org/docs/components/pipelines/v1/reference/api/kubeflow-pipeline-api-spec/)

I've installed Kubeflow on a MicroK8s and started experimenting with the Kubeflow Pipelines API, I was able to upload a pipeline to the central dashboard by using[ kubeflow upload API](https://www.kubeflow.org/docs/components/pipelines/v1/reference/api/kubeflow-pipeline-api-spec/), but when I tried utilizing the [Kubeflow RUN API](https://www.kubeflow.org/docs/components/pipelines/v1/reference/api/kubeflow-pipeline-api-spec/#operation--apis-v1beta1-runs-post), I was unable to establish a RUN. It initially asks me to enter my experiment ID, which I did after creating the experiment in the central dashboard, and then I entered my experiment ID. After passing Experiment ID facing with the below issue, can anyone offer assistance?

RUN_ID=$((
curl -H "Content-Type: application/json" -X POST ${SVC}/apis/v1beta1/runs \
-d @- << EOF
{
   "name":"${PIPELINE_NAME}_run",
   "pipeline_spec":{
      "pipeline_id":"${PIPELINE_ID}"
   }
}
EOF
) | jq -r .run.id)
{"error":"**Invalid input error: Job has no experiment.","code":3,"message**":"Invalid input error: Job has no experiment.","details":[{"@type":"type.googleapis.com/api.Error","error_message":"Job has no experiment.","error_details":"Invalid input error: Job has no experiment."}]}

**After passing the Experiment Id Getting with this below error**

curl -v -H "Content-Type: application/json" -X POST ${SVC}/apis/v1beta1/runs -d @- << EOF
{
  "name":"${PIPELINE_NAME}_run",
  "pipeline_spec":{
    "pipeline_id":"${PIPELINE_ID}"
  },
  "resource_references": [
    {
      "key": {
        "type": "EXPERIMENT",
        "id": "376a6097-67e3-48b4-bda1-26538abae21d"
      },
      "relationship": "OWNER"
    }
  ]
}
EOF
Note: Unnecessary use of -X or --request, POST is already inferred.
 Trying 127.0.0.1:8888...
 TCP_NODELAY set
 Connected to localhost (127.0.0.1) port 8888 (#0)
> POST /apis/v1beta1/runs HTTP/1.1
> Host: localhost:8888
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 278
> 
 upload completely sent off: 278 out of 278 bytes
 Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Content-Type: application/json
< Date: Mon, 17 Jul 2023 10:08:03 GMT
< Transfer-Encoding: chunked
< 
{"error":"Internal error: Unauthenticated: **Request header error: there is no user identity header**.: Request header error: there is no user identity header.\nFailed to authorize with API resource references\ngithub.com/kubeflow/pipelines/backend/src/common/util.Wrap\n\t/go/src/github.com/kubeflow/pipelines/backend/src/common/util/error.go:287\ngithub.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).canAccessRun\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/run_server.go:400\ngithub.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).

**Comment by srikarjavvaji** [comment]
My work has literally struck at this point, could someone kindly assist me?

**Comment by vikas-saxena02** [comment]
@srikarjavvaji as commented on [stackoverflow post](https://stackoverflow.com/questions/77042963/kubeflow-errorinvalid-input-error-job-has-no-experiment-code3-message/77199795#77199795), please use the GUI and try running the pipeline from it. Most likely, there seems to be an issue with your setup as its working for me.  Attached is the snaphot for the same
<img width="1387" alt="Screenshot 2023-10-28 at 5 54 24 am" src="https://github.com/kubeflow/pipelines/assets/90456542/55c07901-36e8-46e2-8ab5-c533ca13282e">

**Comment by vikas-saxena02** [comment]
@srikarjavvaji can you share if the proposed solution work for you? As mentioned, happy to jump on a quick call.
