### ISSUE TITLE
[feature] labeled pods with pipeline-id, pipeline-version, component-name/id for retrieving logs in loki properly

### ISSUE THREAD

**Issue by axel7083** [kubeflow/pipelines#9776]
### Feature Area

/area backend

### What feature would you like to see?

When running a pipeline, after some time the logs are removed, since the terminated pods are cleanup. When using [Loki](https://github.com/grafana/loki), we can fetch the logs using the label `pipeline/runid`. 

However we cannot filter by pipeline name/version/step in Grafana.

Adding the following elements would allow to easily explore the logs later:
- `pipeline/id`
- `pipeline/versionid`
- `pipeline/name`
- `pipeline/stepid`
- `pipeline/stepname`

## Going further

The log tab should not fetch the logs from the kubernetes api but rather a Loki instance. Maybe both, during the run, using the kubernetes api for watching them, then after completion using Loki.

---

Love this idea? Give it a 👍.

**Comment by zijianjoy** [comment]
Thank you @axel7083 , we are welcoming contributions for making pod labels configurable in KFP.
