### ISSUE TITLE
[sdk] ParallelFor loop argument types not recognized

### ISSUE THREAD

**Issue by stijntratsaertit** [kubeflow/pipelines#9777]
### Environment

*  KFP version: **2**
*  KFP SDK version: **2.0.1**

*  All dependencies version:
```bash
➜ pip list | grep kfp
kfp                      2.0.1
kfp-pipeline-spec        0.2.2
kfp-server-api           2.0.0
```

### Steps to reproduce
Previously, in KFP SDK v1.8.*, the following worked when the `my_component` component accepted 2 arguments, the first being `int` and the second being a `str`.

```python
@dsl.component
def my_component(first_param: int, second_param: str):
    # do some things
    return

with dsl.ParallelFor(
    [
        {"first_param": 1, "second_param": "hello"},
        {"first_param": 0, "second_param": "world"},
        {"first_param": 1, "second_param": "hello"},
    ],
    parallelism=3,
) as params:
    my_component(first_param=params.first_param, second_param=params.second_param)
```

When upgrading to KFP SDK v2.0.1, this is now thrown as an error when compiling the pipeline:
```
ERROR:__main__:Incompatible argument passed to the input 'first_param' of component 'my_component': Argument type 'STRING' is incompatible with the input type 'NUMBER_INTEGER'
```

### Expected result

No error and a correct passage of `first_param` as an integer parameter to `my_component`.

### Materials and Reference

It could be that I'm misusing the arguments to `dsl.ParallelFor` as I couldn't find very much more similar examples other than [the main docs](https://kubeflow-pipelines.readthedocs.io/en/master/source/dsl.html?h=parallel#kfp.dsl.ParallelFor).

A possible angle to the issue could be regarding this: https://github.com/kubeflow/pipelines/blob/6dfcd533f495bf19019bb09baf5ec0d3775e0f1c/sdk/python/kfp/components/for_loop.py#L46

The type that comes in here is `dict`, no regex match is found and None is returned. Because of that, an automatic fallback to `String` is done here: https://github.com/kubeflow/pipelines/blob/6dfcd533f495bf19019bb09baf5ec0d3775e0f1c/sdk/python/kfp/components/for_loop.py#L243-L244

---

Impacted by this bug? Give it a 👍.

**Comment by alvarodemig** [comment]
Same error that was commented here:
https://github.com/kubeflow/pipelines/issues/9366

**Comment by stijntratsaertit** [comment]
I would actually argue it is not identical; this is specifically about multiple datatypes within the dictionary. `first_param` is an integer, ``second_param` a string. The referenced PR used the same integer types

**Comment by alvarodemig** [comment]
This is still a bug
