### ISSUE TITLE
[feature] Configuring securityContext at pod level

### ISSUE THREAD

**Issue by axel7083** [kubeflow/pipelines#9783]
### Feature Area

/area backend
/area sdk

/area components

### What feature would you like to see?

Being able to configure securityContext in v2.

### What is the use case or pain point?

When using an image from dockerhub for example, which has not a default user 0 in the `@dsl.component(base_image="<non-root-image>")`, when trying to write to OutputPath, got the following error:

>  failed to execute component: unable to create directory "/minio/mlpipeline/v2/artifacts/pipeline-name/uuid/custom-function" for output artifact "model": mkdir /minio: permission denied

## Details

Worflow support the security at spec level [Workflow Pod Security Context](https://argoproj.github.io/argo-workflows/workflow-pod-security-context/).

---

Love this idea? Give it a 👍.

**Comment by chensun** [comment]
What are the versions of KFP and SDK you're using? Also what container image being used for the component?

**Comment by dashanji** [comment]
Agree +1.

I'm using KFP v2, and it look like we can't add the `securityContext` to the IR YAML.

**Comment by rimolive** [comment]
PR #10538 will handle this

**Comment by juliusvonkohout** [comment]
i think it is possible now, if not please reopen

**Comment by zswf-mle** [comment]
@chensun @juliusvonkohout  How is that completed? I still can't find a way to set the security context.

**Comment by juliusvonkohout** [comment]
see https://github.com/kubeflow/pipelines/issues/12205 and upvote it
