### ISSUE TITLE
[frontend] Frontend Dockerfile don't build

### ISSUE THREAD

**Issue by SamirPS** [kubeflow/pipelines#9804]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
I didn't deploy KFP, I only tried to build the frontend container image

### Steps to reproduce

git clone this repo with this tag ``2.0.0-alpha.7``
```
cd pipelines/frontend
docker build
```

and you will get this error:

```
Error workbox-webpack-plugin@6.6.1: The engine "node" is incompatible with this module. Expected version ">=16.0.0
```

### Expected result

The dockerfile should build

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

**Comment by zijianjoy** [comment]
Hello @SamirPS , would you like to try the following using the latest KFP repo?

```
cd pipelines/
docker build -f frontend/Dockerfile .
```

**Comment by SamirPS** [comment]
With the ```2.0.0``` it's work but not the ```2.0.0-alpha.7```

**Comment by zijianjoy** [comment]
We recommend using a newer version, since we have announce GA for KFP 2.0.
