### ISSUE TITLE
[sdk] Is dsl.Collected a feature of kfp version==1.8.19 ?

### ISSUE THREAD

**Issue by Aditya-171** [kubeflow/pipelines#9823]
*  KFP SDK version: 1.8.19

*  All dependencies version:
kfp       1.8.19
kfp-pipeline-spec    0.1.16
kfp-server-api     1.6.0

Hi i was trying to use dsl.Collected , but was facing the error as 
AttributeError: module 'kfp.dsl' has no attribute as 'Collected'

Also the following sdk docs for the 1.8.19 kfp version dos not exist

https://kubeflow-pipelines.readthedocs.io/en/1.8.19/source/dsl.html

---

Impacted by this bug? Give it a 👍.

**Comment by zijianjoy** [comment]
Closing this issue since we have provided an answer, feel free to reopen if this is not the case.
