### ISSUE TITLE
Include TFX Chicago Taxi Pipeline example as part of API Server pre-loaded samples

### ISSUE THREAD

**Issue by neuromage** [kubeflow/pipelines#983]
This relies on #982 being fixed first.

/assign @neuromage

**Comment by gaoning777** [comment]
This refers to the tfx oss sample, doesn't it?

**Comment by neuromage** [comment]
Yes, that's right Ning.

**Comment by gaoning777** [comment]
https://github.com/kubeflow/pipelines/blob/master/samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py is added to the backend. 
Feel free to reopen the issue.
