### ISSUE TITLE
[feature] Default Credentials for Custom Training Jobs in Vertex AI Pipelines.

### ISSUE THREAD

**Issue by jirapast** [kubeflow/pipelines#9836]
My colleague (**https://github.com/WanchanaMoonmuang**) and I implemented a Vertex AI Pipeline that included a custom training job. However, during our implementation, we encountered a bug related to credentials. After conducting a thorough investigation, we discovered that the credentials being used to run the Vertex AI Pipeline were not being passed to the custom training job unless explicitly specified. Upon examining the file _"components/google-cloud/google_cloud_pipeline_components/v1/custom_job/utils.py,"_ we noticed that the argument for inputting the service account was set to an empty string by default.

To address this issue, we proposed the idea of raising an exception if the service account argument is left empty. Alternatively, we considered the possibility of utilizing the default credentials used in the Vertex AI Pipeline to ensure consistency and proper functioning.

**Comment by zijianjoy** [comment]
@jirapast You need to provide your custom credential/SA when trying to bring up the custom training job within the pipeline. Reference: https://google-cloud-pipeline-components.readthedocs.io/en/google-cloud-pipeline-components-2.3.0/api/v1/custom_job.html#v1.custom_job.create_custom_training_job_from_component.service_account.
