### ISSUE TITLE
Pipeline component that trigger another pipeline

### ISSUE THREAD

**Issue by fclesio** [kubeflow/pipelines#9863]
First at all thanks for the collaboration and put so much effort in this tool. 

I would like to know if there's some component that emulates the behavior of the [TriggerDagRunOperator](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/operators/trigger_dagrun/index.html#airflow.operators.trigger_dagrun.TriggerDagRunOperator) in Apache Airflow?

The reason of my question is that in some situations in Airflow it's quite common to break large DAGs in small ones and call them via triggers and/or sensors. Without that, folks that are migrating from Airflow to Kubeflow will need to migrate all those large DAGs in a single pipeline file.  

I've checked the [docs](https://kubeflow-pipelines.readthedocs.io/en/latest/source/dsl.html) and the issues but I did not managed to find something similar.

Thanks for the work once again.

**Comment by connor-mccarthy** [comment]
@fclesio, the closest thing KFP has to this is the ability to use pipelines within other pipelines (i.e., pipeline as a component). Here is some [documentation on this](https://www.kubeflow.org/docs/components/pipelines/v2/pipelines/pipeline-basics/#pipelines-as-components).

**Comment by nathan-chan-brt** [comment]
Is this only available in V2, or does this also work in V1?
