### ISSUE TITLE
[feature / question] Use the KFP SDK inside a pipeline

### ISSUE THREAD

**Issue by GfxKai** [kubeflow/pipelines#9871]
### Feature Area

/area sdk
/area components

### What feature would you like to see?

In KFP v2, there doesn't seem to be any way of using the KFP API from inside a pipeline component.

It would be great if the `PodDefault` for a Kubeflow Profile could be applied to pipeline task pods, enabling the KF service account token to be mounted into pipeline task pods as well as Notebook pods.

### What is the use case or pain point?

I'm trying to create a model evaluation pipeline which:
1. Imports the latest available test data
2. Imports the latest successfully trained model **from a different pipeline**
3. Calculates performance metrics for the existing model

With this workflow, I can create recurring runs to measure model degradation over time.

### Is there a workaround currently?

Currently, the best I can do is to just compute the model performance at train time within the model pipeline. However, this doesn't allow for re-evaluating the performance when new data is added.

---

Love this idea? Give it a 👍.

**Comment by gkcalat** [comment]
Hi @GfxKai!

Have you considered keeping track of the Model artfiact uris and passing it to the model eval pipeline?
