### ISSUE TITLE
[feature] Update default base image for lightweight components

### ISSUE THREAD

**Issue by ianonavy** [kubeflow/pipelines#9872]
### Feature Area

/area sdk

### What feature would you like to see?

I'd like to see the default base image for Python function-based components be updated to Python 3.11. Example [here](https://github.com/kubeflow/pipelines/commit/7e9ea23612da0be10e784aea1f1a6812964b58fa).

### What is the use case or pain point?

When authoring new lightweight Python components, it is tedious to have to set `base_image="python3.11"` for each component. I can't find a setting to up the default `base_image`, and for compliance reasons we need to use a version of Python that still receives security patches.

I can see that the SDK overall supports as far back as Python 3.7, and I am guessing that is why the base image is so old. Perhaps for compatibility, the default base image could be derived from `sys.version`? So for example if I'm running the KFP SDK in a Python 3.10 virtual environment, maybe it would default to `python:3.10`

### Is there a workaround currently?

Currently we are wrapping the `component` decorator with `functools.wraps` to set the default base image.

---

Love this idea? Give it a 👍.

**Comment by connor-mccarthy** [comment]
@ianonavy, this would unfortunately be a breaking change and cannot be done within KFP SDK major version 2. While the Python language features in 3.11 should be backward compatible with those in 3.7, there almost certainly exists some user code which has [dependencies](https://kubeflow-pipelines.readthedocs.io/en/master/source/dsl.html#kfp.dsl.component.packages_to_install) that require a Python version <3.11.
