### ISSUE TITLE
[bug] Can't increase/attach shared memory to pipeline task in kfp sdk v2, e.g. PyTorch training fails.

### ISSUE THREAD

**Issue by hsteude** [kubeflow/pipelines#9893]
### Environment

*  How do you deploy Kubeflow Pipelines (KFP)?
Manifests
*  KFP version:
2.0.0
*  KFP SDK version:
2.0.1

### Steps to reproduce

Create and run a simple PyTorch (lightning) training pipeline:
```python
from kfp import dsl
from kfp.client import Client


# define pytorch (lightning) training component
@dsl.component(
    packages_to_install=["torch==2.0.0", "pytorch_lightning"],
    base_image="python:3.9",
)
def pytorch_training(num_workers: int, input_size: int, batch_size: int):
    import torch
    from torch import nn
    import torch.nn.functional as F
    from torch.utils.data import DataLoader, Dataset
    import pytorch_lightning as pl

    class ExampleDataset(Dataset):
        def __init__(self, size: int = 1000, number_samples: int = 100):
            self.x = torch.randn(number_samples, size, size)
            self.size = 1000

        def __len__(self):
            return self.x.shape[0]

        def __getitem__(self, idx):
            return self.x[idx, :, :]

    class ExampleModel(pl.LightningModule):
        def __init__(self, inputsize: int):
            super(ExampleModel, self).__init__()
            self.linear = nn.Linear(inputsize, inputsize)

        def forward(self, x):
            return self.linear(x)

        def training_step(self, batch, batch_idx):
            x = batch
            loss = F.mse_loss(self(x), x)
            return loss

        def configure_optimizers(self):
            return torch.optim.SGD(self.parameters(), lr=0.1)

    dataset = ExampleDataset(size=input_size, number_samples=100)
    train_loader = DataLoader(dataset, num_workers=num_workers, batch_size=batch_size)
    model = ExampleModel(inputsize=input_size)
    trainer = pl.Trainer(max_epochs=1)
    trainer.fit(model, train_loader)


# define pipeline
@dsl.pipeline
def shared_memory_pipeline(
    num_workers: int = 0, input_size: int = 1000, batch_size: int = 100
):
    pytorch_training_task = pytorch_training(
        num_workers=num_workers, input_size=input_size, batch_size=batch_size
    )


# compile and run pipeline
client = Client()
client.create_run_from_pipeline_func(
    shared_memory_pipeline,
    arguments=dict(num_workers=5, input_size=1_000, batch_size=100),
    experiment_name="shared-memory",
    enable_caching=True,
)
```

### Expected result
Pipelne gets compiled and executed without errors.

### Materials and reference
* This is the error I get:
```
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1133, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/usr/local/lib/python3.9/multiprocessing/queues.py", line 113, in get
    if not self._poll(timeout):
  File "/usr/local/lib/python3.9/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/usr/local/lib/python3.9/multiprocessing/connection.py", line 424, in _poll
    r = wait([self], timeout)
  File "/usr/local/lib/python3.9/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/usr/local/lib/python3.9/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 503) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit.
```

* There is a workaround in skd v1: https://github.com/kubeflow/pipelines/issues/6880
* Default values for shared memory for containerd and Docker is 64MD. Thus, the pipeline above works fine, if a batch is small enough (e.g. for batch_size=1). It will also run just fine if the number of workers for the Data Loader is set to 0 and no shared memory is required.

### Labels

Impacted by this bug? Give it a 👍.

**Comment by gkcalat** [comment]
Hi @hsteude!

You can specify memory requests using SDK: `.set_memory_request()` and `.set_memory_limit()`: https://kubeflow-pipelines.readthedocs.io/en/sdk-2.0.1/source/dsl.html?h=set_memory#kfp.dsl.PipelineTask.set_memory_request

**Comment by hsteude** [comment]
Hi @gkcalat and thanks for your answer!

Unfortunately, using `.set_memory_request()` and `.set_memory_limit()` doesn't address the actual issue I am facing. These methods set the general memory allocation for the container, not the *shared memory*, which is the limiting factor here. PyTorch's DataLoader uses shared memory when `num_workers > 0`, and it's this shared memory that gets exhausted.

The example above still fails when using the methods to increase memory requests and limits.

Could this issue be reopened since the problem still persists even when applying the suggested memory settings?

Thanks a lot in advance!

Cheers,
Henrik

**Comment by clemgaut** [comment]
I have the same issue with kfp 2.50, and I confirm that increasing the memory limit does not fix the issue.
The only solution currently seems to be to revert to kfp v1, so I also think this issue should be repoened.

**Comment by HumairAK** [comment]
You can specify empty dir share volume mounts via: 


```python
@dsl.pipeline
def my_pipeline():
    task = comp()

    # Is the same as:
    kubernetes.empty_dir_mount(
        task,
        volume_name="random-name",
        mount_path = "/dev/shm",
        medium = "Memory",
        size_limit = "2Gi"
    )
```

Which is what https://github.com/kubeflow/pipelines/pull/10704 attempts to also implement, though this already exists in KFP latest. Let us know if any more work beyond this is needed to address this.
