### ISSUE TITLE
Is there a way to specify "privileged" for a containerOp?

### ISSUE THREAD

**Issue by aronchick** [kubeflow/pipelines#990]
cc @sethjuarez 

--------------

Afaict the relevant permissions are svc-account roles and instance scopes. the latter can't be change on running nodes.

I tried updating and re-applying the cluster `.yaml` to grant the new permissions.

The svc-accts _may_ have picked up the new roles on the next pipeline run attempt.

I believe the nodes did not get the new scopes, and I had to start a fresh cluster with the changes made manually between the `generate` and `apply` `platform` kfctl steps

making this more transparent and tweakable definitely seems important for usability

**Comment by aronchick** [comment]
/assign @gaoning777 

cc @hongye-sun

**Comment by aronchick** [comment]
cc @ryan-williams

**Comment by ryan-williams** [comment]
I tried changing `gcp_config/cluster.jinja` (instance scopes) and `gcp_config/iam_bindings.yaml` (svc-acct roles), and re-running `kfctl.sh apply platform`.

I get this error:

```
No method found to update field 'cluster' on resource '$KFAPP' of type 'container-v1beta1'.
    The resource may need to be recreated with the new field.
```

In principle, it should be possible to implement such changes through k8s, but seems like that's not implemented today. Making that happen could be a good direction to take this issue, or it may warrant a separate issue.

I don't see any lighter-weight way of changing instance permissions, let alone per-`ContainerOp`-permissions.

Verifying that svc-acct roles can or can't be changed on the fly would be good to do as part of this, as well.

**Comment by hongye-sun** [comment]
Starting from kubernetes 1.10, The legacy access scope is no longer needed
if the cluster is created with custom service account. One action item is
to migrate kubeflow to use custom sa.
https://cloud.google.com/kubernetes-engine/docs/how-to/access-scopes

Changing access scope without downtime currently requires to create a new
node pool and migrate pods from old pool to new one , then delete the old
pool.

BTW, this is a general kubeflow setup issue. Pipeline is a component
installed as part of kubeflow.

**Comment by ryan-williams** [comment]
Good to know!

Not sure if this is for, against, or orthogonal to what you're proposing, but maybe we should just boot instances with the full `cloud-platform` scope by default. Using svc-acct roles seems to be the preferred way to control permissions.

That should avoid the annoying problem of having to reboot instances to tweak their scopes.

Assuming svc-accts' permissions can be modified on the fly, this would allow changing permissions at "whole pipeline" granularity.

lmk if I'm missing something.

**Comment by hongye-sun** [comment]
If you just want to change the access level of a single container, have you tried ContainerOp(...).apply(gcp.use_gcp_secret()) to use preconfigured [GCP user sa](https://www.kubeflow.org/docs/started/getting-started-gke/#gcp-service-accounts) to talk to other GCP services? I don't think it is restricted by the oauth scope configured on the node.

Actually, kubeflow already uses custom sa in the setup and grant [minimum oauth scopes](https://github.com/kubeflow/kubeflow/blob/master/deployment/gke/deployment_manager_configs/cluster.jinja#L19) for default sa.

**Comment by ryan-williams** [comment]
Interesting @hongye-sun, seems like you're saying that individual containers can be given escalated/specific permissions today? 

This would be great to have a full example of somewhere. If you want to leave any more breadcrumbs here that would also be appreciated 😄

**Comment by hongye-sun** [comment]
Yes. The details is in the code: https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/gcp.py#L15

We extensively use the GCP secret in samples. Here is [one](https://github.com/kubeflow/pipelines/blob/master/samples/resnet-cmle/resnet-train-pipeline.py#L98) of them.

Filed https://github.com/kubeflow/pipelines/issues/993 to add it into pipeline document.

**Comment by Ark-kun** [comment]
> Interesting @hongye-sun, seems like you're saying that individual containers can be given escalated/specific permissions today?
> 
> This would be great to have a full example of somewhere. If you want to leave any more breadcrumbs here that would also be appreciated

It's not that the container/pod can be more privileged. But you can pass credentials to the program running inside the container and it can use those those credentials to access some service and have more access permissions.

**Comment by kkasravi** [comment]
This can be done today under Profiles - where a given user is provided a namespace and a RoleBinding. The Role used for the RoleBinding currently does not allow the user to access the PodSecurityPolicy but if the [Role](https://github.com/kubeflow/kubeflow/blob/master/components/profile-controller/pkg/controller/profile/profile_controller.go#L403) were changed to 

```
				APIGroups: []string{
					"extensions",
				},
				Resources: []string{
					"daemonsets",
					"deployments",
					"deployments/rollback",
					"deployments/scale",
					"ingresses",
					"networkpolicies",
=> 					"podsecuritypolicies",
					"replicasets",
					"replicasets/scale",
					"replicationcontrollers/scale",
				},
				Verbs: []string{
					"create",
					"delete",
					"get",
					"list",
					"patch",
					"update",
					"watch",
=>					"use",
				},
```

I believe that would allow privileged to be used. @lluunn will the profile-controller be active in 0.5? My feeling is we would need something like a ProfileGroup that would allow certain individuals creating profiles to have this privilege.... effectively a Role of 'admin' vs 'edit'....

**Comment by gaoning777** [comment]
@aronchick @ryan-williams 
Does ContainerOp(...).apply(gcp.use_gcp_secret())  solve the problem?

**Comment by gaoning777** [comment]
We are transitioning to Workload identity. 
Check out https://www.kubeflow.org/docs/gke/pipelines/authentication-pipelines/
