### ISSUE TITLE
[frontend] No Logs tab in UI

### ISSUE THREAD

**Issue by Saurav-D** [kubeflow/pipelines#9906]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
AWS, Terraform, Vanilla
*  KFP version: 
KFP 1.7
pipeline: 2.0.0-alpha.7

### Steps to reproduce

Run any pipeline

### Expected result
Logs tab with logs. Right now, I just see Input/Output and Task Details. Also, I don't see pod ID.

### Materials and Reference

![Screenshot 2023-08-18 at 12 29 09 PM](https://github.com/kubeflow/pipelines/assets/26328148/d48cc35f-72c3-4d1b-a6b3-749af0b67638)

---

Impacted by this bug? Give it a 👍.

**Comment by gkcalat** [comment]
Hi @Saurav-D,

Logs are available in KFP 2.0.0. It is expected to be included in Kubeflow 1.8 (releasing in 2023 Q4)
