### ISSUE TITLE
Add documentation/sample about how to mount secret on ContainerOp

### ISSUE THREAD

**Issue by hongye-sun** [kubeflow/pipelines#993]
We don't have any documentation explain how to use secrets in pipeline. It's worth to have a section or page and a basic sample pipeline to demonstrate it.

**Comment by vicaire** [comment]
@gaoning777, I am assigning the DSL sample issues to illustrate features to you. Please reassign to the most appropriate person as needed.

**Comment by SinaChavoshi** [comment]
Added sample code PR #1676 . 
TODO: Add test case for sample

**Comment by gaoning777** [comment]
sample tests are tracked here: https://github.com/kubeflow/pipelines/issues/1813
