### ISSUE TITLE
module 'kfp.components' has no attribute 'create_component_from_func'

### ISSUE THREAD

**Issue by Aman123lug** [kubeflow/pipelines#9933]
### Environment

I am trying to build the Kubeflow pipeline. i am using version 2.0.1.
I am getting this error:

module 'kfp.components' has no attribute 'create_component_from_func'

And along i i followed the document of KFPv2 there are some code already written in docs for the testing it has already created some function and pipelines I copy paste all things from docs for test then I compiled then it's created yaml file I simply upload in kubeflow ui which install in a cluster
But I am getting this error : 
Cannot get MLMD object from meta store

again and again I getting same error also it has shown a pop-up and says:
Unkown content type recived

Is there any other way to import this or this is a version error?
![263000793-0a4ecc0f-d9d1-409d-988a-fbd5d75ad4cd](https://github.com/kubeflow/pipelines/assets/94223645/a4a871c2-1ae5-4600-8086-5f870a6b0d93)

**Comment by connor-mccarthy** [comment]
For KFP SDK v2, please use the `@dsl.component` decorator. See [documentation on Lightweight Python Components](https://www.kubeflow.org/docs/components/pipelines/v2/components/lightweight-python-components/) for more information.
