### ISSUE TITLE
Kubeflow error:Invalid input error: Job has no experiment. code:3 message

### ISSUE THREAD

**Issue by srikarjavvaji** [kubeflow/pipelines#9941]
I am following tutorial of Kubeflow Pipelines API: [[Kubeflow](https://www.kubeflow.org/docs/components/pipelines/v1/tutorials/api-pipelines/)] & [Kubeflow Pipelines API](https://www.kubeflow.org/docs/components/pipelines/v1/reference/api/kubeflow-pipeline-api-spec/)
    
I've installed Kubeflow on a MicroK8s and started experimenting with the Kubeflow Pipelines API, I was able to upload a pipeline to the central dashboard by using [kubeflow upload API](https://www.kubeflow.org/docs/components/pipelines/v1/reference/api/kubeflow-pipeline-api-spec/), but when      I tried utilizing the [Kubeflow RUN API](https://www.kubeflow.org/docs/components/pipelines/v1/reference/api/kubeflow-pipeline-api-spec/#operation--apis-v1beta1-runs-post), I was unable to establish a RUN. As RUN_ID is showing as null but in the [document](https://www.kubeflow.org/docs/components/pipelines/v1/tutorials/api-pipelines/),  by running this command curl ${SVC}/apis/v1beta1/runs/${RUN_ID} | jq it is showing the value of RUN_ID.Can anyone offer assistance.
    
I tried several various approaches, but they were unsuccessful, I was literally struck at my work regarding this issue can anyone please help on this issue..

RUN_ID=$((
curl -H "Content-Type: application/json" -X POST ${SVC}/apis/v1beta1/runs
\-d @- \<\< EOF
{
"name":"${PIPELINE_NAME}\_run",
"pipeline_spec":{
"pipeline_id":"${PIPELINE_ID}"
}
}
EOF
) | jq -r .run.id)

% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   388  100   277  100   111  23083   9250 --:--:-- --:--:-- --:--:-- 32333

$ echo $RUN_ID
null

$ curl -H "Content-Type: application/json" -X POST ${SVC}/apis/v1beta1/runs  
\-d @- \<\< EOF  
{  
"name":"${PIPELINE_NAME}\_run",
"pipeline_spec":{
"pipeline_id":"${PIPELINE_ID}"
}  
}  
EOF
{"error":"Invalid input error: Job has no experiment.","code":3,"message":"Invalid input error: Job has no experiment.","details":\[{"@type":"type.googleapis.com/api.Error","error_message":"Job has no experiment.","error_details":"Invalid input error: Job has no experiment."}\]}

**Comment by d0m3n1cc** [comment]
You need first to create an experiment and than use it's id in run, passing it as a parameter.

**Comment by srikarjavvaji** [comment]
> 

Please provide advice on how to create an [experiment](https://www.kubeflow.org/docs/components/pipelines/v2/reference/api/kubeflow-pipeline-api-spec/#operation--apis-v2beta1-experiments-post)  as the error is **Job has no experiment** .I'm literally stuck and need assistance to move on. Also how to create Job.

**Comment by d0m3n1cc** [comment]
Just check the API specification for the case:
https://www.kubeflow.org/docs/components/pipelines/v1/reference/api/kubeflow-pipeline-api-spec/#operation--apis-v1beta1-experiments-post

**Comment by srikarjavvaji** [comment]
> Just check the API specification for the case: https://www.kubeflow.org/docs/components/pipelines/v1/reference/api/kubeflow-pipeline-api-spec/#operation--apis-v1beta1-experiments-post

can you please give me one example on creation of [Experiment ](https://www.kubeflow.org/docs/components/pipelines/v1/reference/api/kubeflow-pipeline-api-spec/#operation--apis-v1beta1-experiments-post)using kubeflow API

**Comment by srikarjavvaji** [comment]
Kindly please let me know if more information requried...
