### ISSUE TITLE
What's the current behaviour with the run_pipeline?

### ISSUE THREAD

**Issue by fclesio** [kubeflow/pipelines#9960]
Thanks once again for the great library. 

I  have a ML pipeline that consists in 3 tasks: ETL > Pre-Processing > Modelling and Deploy. 

Since those tasks are sequential, I created 3 pipelines and I used the [kfp.client.run_pipeline ](https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/client/client.py#L688C9-L688C21) to run each one sequentially.  

One thing that I noticed is that the client only _fires_ the pipeline and if the API returns 200 marks it as a success, regardless of the pipeline runtime length. 

In my case the run_pipeline did actually fired up all pipelines, but all of them ran at the same time (not desirable behaviour).

There some way to have some kind of "wait status" that only return success if the pipeline called runs until the end?

Thanks once again.

**Comment by connor-mccarthy** [comment]
@fclesio, I think the best solution for what you are trying to achieve is to compose the tasks together into a sequential DAG using a pipeline. Please take a look at the docs on [data passing and task dependencies](https://www.kubeflow.org/docs/components/pipelines/v2/pipelines/pipeline-basics/#data-passing-and-task-dependencies) and feel free to re-open if there are outstanding issues.

**Comment by fclesio** [comment]
Thanks for the answer @connor-mccarthy, but I am afraid that I express myself with a lack of detail. 

For a single pipeline it's clear that we can set those dependencies; however, if we have multiple and _independent_ pipelines that needs to have some sequencing, that solution does not work. 

On top of that, let's say that we have a Pipeline (DAG) with almost 1000 lines, if we have 5 similar ones with the same size we're talking about to have a single pipeline with 5000 lines. 

Being more specific: there is some component that can triggers another pipeline/DAG like [Airflow has the triggerDAGrun](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/operators/trigger_dagrun/index.html)?

**Comment by connor-mccarthy** [comment]
I see, @fclesio. Thanks for the detail. KFP doesn't provide this sort of functionality directly, unfortunately.
