### ISSUE TITLE
[backend] Persistence Agent failing kubeflow-pipeline-mkp-test (2)

### ISSUE THREAD

**Issue by difince** [kubeflow/pipelines#9962]
### Steps to reproduce
Having in mind issue: [Persistence agent failing kubeflow-pipeline-mkp-test](https://github.com/kubeflow/pipelines/issues/9904) that appeared after changes in the Persistence agent manifests files - I guess that the mkp-test may fail again after the merge of [this](https://github.com/kubeflow/pipelines/pull/9957) PR as it also has changed the manifests files. 

At the moment there is no automatic way to move/sync changes done in main manifest files to the manifests in the marketplace helm chart that is why I suggest someone validate the state of the `mkp-test`  and apply the changes done in the above PR in the helm chart if needed.

Please close this issue if that is not the case.
cc: @zijianjoy, @chensun

### Labels

---

Impacted by this bug? Give it a 👍.

**Comment by chensun** [comment]
AI: run MKP presubmit test for backend changes
