### ISSUE TITLE
[feature] Enable Setting Image Pull Policy in V2 SDK

### ISSUE THREAD

**Issue by PhilippeMoussalli** [kubeflow/pipelines#9980]
### Feature Area

/area sdk

### What feature would you like to see?
KFP V1 supported setting the image pull policy [link](https://github.com/kubeflow/pipelines/blob/4bee3d8dc2ee9c33d87e1058bac2a94d899dd4a5/sdk/python/kfp/deprecated/dsl/_container_op.py#L518)

This feature is currently not available in KFP V2

### What is the use case or pain point?  

We used to set image pull policy to always in V1 to avoid cases when outdated images are pulled. 

### Is there a workaround currently?  

No current workaround.  

---

Love this idea? Give it a 👍.

**Comment by rimolive** [comment]
cc @Tomcli @chensun I believe this issue can be closed as #10416 is merged. Can you confirm?

**Comment by Tomcli** [comment]
Yes, #10417 should close this issue.
/close
