### ISSUE TITLE
Duplicated exit handler execution 

### ISSUE THREAD

**Issue by hongye-sun** [kubeflow/pipelines#999]
Currently exit handler generated two steps in the generated argo yaml. One is at the start of the DAG and the other as the exit step.

https://screenshot.googleplex.com/n5qsgCJn3WU

**Comment by vicaire** [comment]
Could you please clarify the issue? I am not sure what this is about. Thanks!

**Comment by hongye-sun** [comment]
Yes, the exit handler step will be executed twice in a pipeline. The first one is executed at the start of the pipeline and the second one is executed at the end of the pipeline. The second one is expected but the first one is not. The fix should remove the first step from the generated argo spec.

**Comment by vicaire** [comment]
Thanks. Updated the area/priority

**Comment by logicbomb421** [comment]
I'm also experiencing this issue.

A little more context:

I have a component that I load from `component.py`:
```python
import kfp.components as components

def component_func(...):
    ...

op = components.func_to_container_op(
    component_func,
    ...
)
```

And in `pipeline.py`, I use the component like so:

```python
import component
import kfp

@kfp.dsl.pipeline(...)
def pipeline_func(...):
    exit_handler = component.op(...)
    with kfp.dsl.ExitHandler(exit_handler):
        ...
```

When running a pipeline built this way, the exit handler is invoked immediately upon start, as well as upon exit.
