### ISSUE TITLE
[feature] Set timeouts for v2 PipelineTask

### ISSUE THREAD

**Issue by vanHavel** [kubeflow/pipelines#9996]
### Feature Area

/area sdk
/area components

### What feature would you like to see?

Ability to set individual timeouts on each `PipelineTask` in kfp v2.

### What is the use case or pain point?

We are currently using kubeflow pipelines v1 and considering a migration to v2. kfp v1 supports the `set_timeout()` method on `ContainerOp`. I don't see an equivalent functionality in v2 `PipelineTask`.

Setting timeouts is important, as in various situations scripts can get stuck for a multitude of reasons. Timeouts are necessary to prevent cost and resource waste.

### Is there a workaround currently?

I am not aware of any convenient workaround. If you have one, please share.

---

Love this idea? Give it a 👍.

**Comment by issagorgias** [comment]
I'm very interested in this feature

**Comment by vanHavel** [comment]
It's available in latest kfp[kubernetes] as `set_timeout`
